### ISSUE TITLE
WKT Geometries reverting lng lat

### ISSUE THREAD

**Issue by pfazzino** [dbeaver/dbeaver#5832]
Just trying the GIS features in 6.0.3.201904211926 and looks like rendering of a WKT POINT is reversing the input coords. Take a look at this example which should be rendering in Brookline, Boston

![image](https://user-images.githubusercontent.com/1869459/57010298-dff34d80-6bf3-11e9-9d88-5e742368a2b3.png)

**Comment by serge-rider** [comment]
What is your database?

**Comment by serge-rider** [comment]
Please post sample SQL query in plaintext.

**Comment by pfazzino** [comment]
mysqld  Ver 5.7.22 for Linux on x86_64 (MySQL Community Server (GPL))

select st_geomfromtext("POINT(42.33118 -71.11777)")

**Comment by serge-rider** [comment]
This is already fixed in 6.0.4 EA (https://dbeaver.io/files/ea)

Thanks for the report anyway.

**Comment by pfazzino** [comment]
just downloaded EA 6.0.4.201905011413, issue still present

**Comment by uslss** [comment]
verified

**Comment by pfazzino** [comment]
![image](https://user-images.githubusercontent.com/1869459/57022696-ccfa7080-6c27-11e9-970e-a19950262c2e.png)

**Comment by serge-rider** [comment]
@pfazzino Super weird. This is how it works on my machine:
(note that in text format coordinates are also flipped)

![image](https://user-images.githubusercontent.com/6398845/57022732-aa248800-6c38-11e9-815c-4b8adbb49b2c.png)

**Comment by serge-rider** [comment]
Have no clue so far..

**Comment by serge-rider** [comment]
What MySQL driver do you use?

**Comment by pfazzino** [comment]
@serge-rider not sure if you're saying it's fixed. your screenshot is showing the same issue I'm reporting. The text coords should not be flipped and the map is rendering the flipped coords not the ones provided in the query. The problem is in the render, run

`select st_astext(st_geomfromtext("POINT(-71.11777 42.33118)"));`

and you'll see the correct output as input.

Driver...
![image](https://user-images.githubusercontent.com/1869459/57023007-d33d1c80-6c28-11e9-92fd-bcb96f86103d.png)

**Comment by serge-rider** [comment]
You just flipped coordinates in your source query (originally it was 42.33118 -71.11777: https://github.com/dbeaver/dbeaver/issues/5832#issuecomment-488264333)
As you can see on my screenshot that map is rendered correctly for query
```sql
select st_geomfromtext("POINT(42.33118 -71.11777)")
```


MySQL stores GIS coordinates in a flipped form. We use OpenStreetMap engine which uses different coordinates notation. As well as Postgis (PostgreSQL).
So DBeaver flips coordinates in MySQL geometry data type to render it correctly.

**Comment by serge-rider** [comment]
The question is: what MySQL format is correct:
- The native MySQL format you posted originally in https://github.com/dbeaver/dbeaver/issues/5832#issuecomment-488264333
- Or OSM/Postgis format you posted in https://github.com/dbeaver/dbeaver/issues/5832#issuecomment-488301616

**Comment by serge-rider** [comment]
As some particular databases may keep coordinates in flipped/inverted form I've added special coordinates toggle in the map viewer. Check it in the new EA version build.

**Comment by pfazzino** [comment]
The correct format is as defined by the WKT standard which defines POINT(x y). Your example correctly rendering the map is passing (POINT y x). It doesn't matter how MYSQL stores this internally as that is opaque to the user experience as long as the spatial functions operate correctly.

`select st_geomfromtext("POINT(-71.11777 42.33118)")`

should return the POINT as entered in the query into the results grid and be rendered on the map in the correct position, not at latitude -71.11777 longitude 42.33118 but at latitude 42.33118 longitude -71.11777. Wrapping this query in st_astext and rendering a string into the resultsgrid gives the correct output thus I believe showing that this issue is in how dbeaver is rendering the spatial type and how mysql is storing the coordinates is not a factor.

**Comment by pfazzino** [comment]
> As some particular databases may keep coordinates in flipped/inverted form I've added special coordinates toggle in the map viewer. Check it in the new EA version build.

thanks. Will give it a try. Not sure I understand the justification but if it fixes the issue then great...

**Comment by serge-rider** [comment]
@pfazzino Unfortunately it matters how MySQL stores data.

https://forums.mysql.com/read.php?23,209566,209566
https://stackoverflow.com/questions/29935651/postgis-latitude-longitude-read-out-reversed
https://postgis.net/2013/08/18/tip_lon_lat/

So, if some database engine stored coordinates in inverted form then its DBeaver's job to flip them. 
WKT itself (being a simple text format representing coordinates as a sequence of numbers) doesn't define lat/lon or lon/lat order.

**Comment by pfazzino** [comment]
It matters to the developer of dbeaver but it shouldn't matter to the user of the product. If I store and query a WKT POINT geometry I expect the output to match my input. It looks as though whatever dbeaver is doing in terms of inverting or not inverting the x,y, it is incorrect for the mysql/driver combination that I'm using.

WKT specification does in fact specify lat/long order. See http://portal.opengeospatial.org/files/?artifact_id=25355 section 7 which clearly defines a POINT as x,y (lng, lat).

In the end, if I store a point based geometry, I expect the rendered output to match what I input. I don't care how it's stored. If I query based on the specification a coordinate represented as POINT(-71.11777 42.33118) then the output should match the x, y inputs.

**Comment by serge-rider** [comment]
DBeaver flips coordinates only to render them on a map viewer. This weird side-effect when they are also flipped in text form is actually a bug. This transformation must be invisible for users. This issue will be fixed before 6.0.4 release.

General thoughts:

It doesn't matter what X and Y mean inside a application. At least if this application has a  consistent data model. But any application must integrate with outer world (get source data in some format from source systems and pass data in other format to target systems). So it is still important what X and Y mean in a real world app.

> WKT specification does in fact specify lat/long order. See http://portal.opengeospatial.org/files/?artifact_id=25355 section 7 which clearly defines a POINT as x,y (lng, lat).

In your example (`POINT(42.33118 -71.11777)`) 42 is latitude and -71 is longitude so it is POINT(lat,lon).

WKT specification doesn't strictly define what is X and what is Y. This topic is described in details in the first article I posted above. By historical reasons MySQL format (lat/lon) differs from the most of other geospatial storage systems (lon/lat).

**Comment by pfazzino** [comment]
I appreciate we've now agreed this is a bug in the text form rendering and look forward to the fix. 

However in all WKT examples, x = lat, y = lng. If it's required to flip this internally for map rendering that's fine but the default expectation is that POINT(-71.11777, 42.33118 ) renders in the Boston area. My latter examples where this is flipped were to demonstrate the issue and this is what I was doing to get this to render before you added the new toggle option. With that new feature I guess this is no longer a factor once the text form is fixed.

thx for your help.

**Comment by pfazzino** [comment]
btw, just noticed that the toggle option is resetting on every execution. Can we either flip the default so it works without flipping or save the selected option.

**Comment by pfazzino** [comment]
Can we fix the above (the toggle setting not saving and having to keep selecting it) or fix the default? The co-ord ref system dialog shows the order as lon lat so really this should be the default imho.

![image](https://user-images.githubusercontent.com/1869459/58646609-ad756700-82fd-11e9-917e-5aa37af15536.png)

**Comment by serge-rider** [comment]
@pfazzino Agreed, this makes sense. Could you create a separate ticket for that?
