### ISSUE TITLE
SQL Completion 'Convert keyword case' unchecked is not honoured.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [dbeaver/dbeaver#5833]
#### System information: 
- Operating system (distribution) and version: Win7
- DBeaver version: 6.03.201904211926
- Java version: Dbeaver Help->About isn't telling me which version of Java it's using.
- Additional extensions: None

#### Connection specification:
- Database name and version: Not relevant
- Driver name: Not relevant
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Not relevant

#### Describe the problem you're observing:

With auto complete enabled it is not possible to type 'where' and press ENTER without the SQL editor changing the case of 'where' to uppercase.

It seems to me that the root of this issue is that the ENTER key appears to be hardcoded to be the key to insert the currently selected word completion candidate and there is no way to configure it to be anything else.

#### Steps to reproduce, if exist:

In the Preferences dialog on the Editors -> SQL Editor -> SQL Completion page
Enable auto activation - checked
Activate on typing - checked
Convert keyword case - unchecked

In an SQL editor type 'where' and press ENTER.
Result - WHERE
Expected - where

**Comment by uslss** [comment]
Unfortunately, cannot reproduce the issue on 6.0.4 and 6.0.5 EA version.
The issue is reproducible for me only in case when default case is set as"Upper" in SQL Formatting page. Could you check it?
![image](https://user-images.githubusercontent.com/31996417/57586746-eb534c80-7502-11e9-9994-37861c712c77.png)
