### ISSUE TITLE
can't delete rows from UI?

### ISSUE THREAD

**Issue by Jerry-Fix** [dbeaver/dbeaver#5834]
#### System information: 
- Operating system (distribution) and version
macOS 10.14.3
- DBeaver version
6.0.3
- Java version 
java version "1.8.0_144"
- Additional extensions

#### Describe the problem you're observing:
When I use script to query some sql, and shows the result below the UI, but when I try to delete some of the rows, I can't since the delete button is in gray mode, don't know where goes wrong?
![DBeaver_6_0_3_-__ls-sg_lookvps___Script-1](https://user-images.githubusercontent.com/670336/57023649-2c2aa600-6c65-11e9-9dd8-4dbda13798c4.jpg)

**Comment by 01viniciusmelo** [comment]
Too can't update rows. I tried update rows, but not commit.

**Comment by serge-rider** [comment]
If you want to delete/update rows in custom query results then:
- Result columns must contain some unique key (otherwise DBeaver can't identify rows)
- Driver must provide columns metadata information (source table and column names). You can see it in Metadata panel.

**Comment by jaseywang** [comment]
![image](https://user-images.githubusercontent.com/670336/57067184-dc012180-6d00-11e9-84fa-1411b4a88bbb.png)

@serge-rider meet your two requirements, seems still can't delete the row.

**Comment by Zabbah** [comment]
Cannot delete rows with 6.0.5: buttons to add, delete, etc. rows are grayed out, same as @jaseywang 
I had to go back to version 6.0.4.

**Comment by earonesty** [comment]
From what I can tell DBeaver may have a bug where sqlite BLOB unique columns are ignored ... even though they are listed as "unique columns"

**Comment by kseniiaguzeeva** [comment]
Is it still actual for you? Which  database and DBeaver version do you use now?

**Comment by uslss** [comment]
issue isn't updated for a long time. Ticket closed

**Comment by hylkevds** [comment]
I'm on 7.1.1 and the edit buttons are completely missing in the "Data" tabs of all my tables, except for the "Edit cell value in separate dialog/editor" button. Database: Oracle

**Comment by uslss** [comment]
@hylkevds , there was in issue with oracle editor in 7.1.1 that was fixed in scope of #9060 . Hotfix was released this week. Could you try to re-install 7.1.1?

**Comment by hylkevds** [comment]
Yep, that did the trick! Thanks for the quick reply!
