### ISSUE TITLE
How to prevent query retries

### ISSUE THREAD

**Issue by rsliva** [dbeaver/dbeaver#5837]
#### System information: 
- Windows 10
- DBeaver version 6
- Java version 8

#### Connection specification:
- Hive 3 Database
- Hive JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

When a query failure occurs there are several retries (4 attempts counting the first failure). I want to have 0 retries. I cannot find where to configure this.

**Comment by uslss** [comment]
hi @rsliva ,
it could be changed in connection properties.
![image](https://user-images.githubusercontent.com/31996417/82324210-f0828b80-99e1-11ea-92e0-0ab560e27b38.png)
sorry for so delayed response
