### ISSUE TITLE
[macOS Mojave] Tabs dragged to another screen will "pop" back onto the original screen whenever a context menu or model is displayed on the original screen

### ISSUE THREAD

**Issue by LeeKevin** [dbeaver/dbeaver#5838]
#### System information: 
Operating system (distribution) and version: Mac - Mojave
DBeaver version - 6.0.1
Java version - 8 Update 92

#### Connection specification:
Database name and version - PostgreSQL
Driver name - PostgreSQL JDBC Driver 42.2.3.jre7
Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When using multiple monitors:

1. Open multiple script tabs in the main dbeaver window
2. Grab a tab and drag it to another monitor/screen
3. Back in a script tab in the main window, execute a query that results in an error modal or prompt the editor for an autocomplete context menu.

Result: The windows dragged to the other monitors/screens will be displayed back in the same monitor/screen as the main dbeaver window.

This issue only cropped up when I upgraded to macOS Mojave.

#### Steps to reproduce, if exist:
See above
****

[Screen Recording 2019-05-01 at 5.08.40 PM.mov.zip](https://github.com/dbeaver/dbeaver/files/3136390/Screen.Recording.2019-05-01.at.5.08.40.PM.mov.zip)

**Comment by LeeKevin** [comment]
This also occurs on DBeaver 6.04

**Comment by uslss** [comment]
seems that issue is fixed in 7.1 version.
If it is still actual for you - feel free to reopen the ticket
