### ISSUE TITLE
import CSV doesn't create collumns when filename contains "_"

### ISSUE THREAD

**Issue by jindrichmatous** [dbeaver/dbeaver#5839]
Hallo,
I found one thing when importing the CSV files.
jdbc:relique:csv:C:\MA01Projects\WGWR\Import

When the filename contains underscore "_", I can browse data, but no column names are created. So I cannot make export, import these data. See attachment.

thanks,

J.Matous

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Hello @jindrichmatous ,
Could you clarify what database, OS, DBeaver version are used?

**Comment by jindrichmatous** [comment]
Hallo,

Thanks for response.

Of cause, It is easy to change file name, but for other customers. It is about CSV import there is no database. I am sending versions of system and driver.

 

Regards,


J.Matous

**Comment by serge-rider** [comment]
I can't reproduce this. Underscore in file name doesn't affect anything.
Maybe you have some specific driver properties?
Could you send sample CSV file which is not recognized properly?

**Comment by jindrichmatous** [comment]
Hallo Serge Rider,

Thanks for the time. I run it on different machine and it works right.

So close it, it is not so important.

 

JM
