### ISSUE TITLE
Visual table editor updates wrong database (MySQL)

### ISSUE THREAD

**Issue by antoniustefan** [dbeaver/dbeaver#5841]
#### Describe the problem you're observing:
When editing data using the visual table editor (right click on a table -> Edit table -> Data tab) on a database which is not the current active one it sends the update to the active database instead.

In the screenshot below you can see:
1. the active database is: **active_database**
2. the editor shows the edit is taking place on: **another_database.some_table**
3. the script generated by the editor actually wants to update: **active_database.some_table**

![image](https://user-images.githubusercontent.com/7008135/57069016-055b8680-6cdc-11e9-876e-f758403b5046.png)

#### Steps to reproduce, if exist:
0. assume we have 2 databases on a MySQL server: DB_A and DB_B
1. set the default database on the MySQL connection to DB_A
2. open the connection
3. browse to a table on DB_B
4. right click on that table, select **Edit Table** and go to the **Data** tab
5. change some existing data row, or add a new row
6. click on the **Script** button to see the script that would be executed and notice it is against the wrong DB_A database

Notes:
The most common way I managed to reproduce this to set the active database in the connection properties. Changing the database using the context menu sometimes does not reproduce the issue.

If the DB_B database has a different structure than DB_A, the issue will be slightly different. DBeaver will prevent you from editing (probably because it is trying to get table metadata from the wrong place).

#### System information:
Windows 7 SP1
DBeaver 6.0.3
OpenJDK 1.8.0_192
MySQL driver 5.1.47

**Comment by serge-rider** [comment]
This is a bug in MySQL extension (it appeared in 6.0.1 version I believe).
Catalog name is ignored during resultset metadata reading.

Thanks for the report.

**Comment by serge-rider** [comment]
The fix is available in Early Access version (https://dbeaver.io/files/ea), please test.

**Comment by antoniustefan** [comment]
Tested the Early Access version and it's fixed now.
Thank you very much !
