### ISSUE TITLE
SQL Completion: Auto-complete does not work after EXEC keyword

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#5843]
DBeaver - Version 6.0.3 CE
Operating System: Windows 10
JDBC Driver: jTDS 1.3.1 / SQL Server
Database: Microsoft SQL Server Database

After updating to this version of Dbeaver, i am not longer able to get auto-complete to work for stored procedures after EXEC keyword. @serge-rider 

![image](https://user-images.githubusercontent.com/38669892/57088730-8577f100-6cc8-11e9-90d0-2c2324227c86.png)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
