### ISSUE TITLE
fix to closed issue#4064 tab separator with csvDriver does not persist

### ISSUE THREAD

**Issue by lollym** [dbeaver/dbeaver#5847]
#### System information: 
- Operating system (distribution) and version: Win10 Enterprise 1083
- DBeaver version: CE, earlier today 4.2.2, now 6.0.3
- Java version : Java 8 Update 201
- Additional extensions

#### Connection specification:
- Database name and version: csv
- Driver name: earlier today cvsjdbc 1.0.31, now cvsjdbc 1.0.35
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
cutting and pasting tab from a text editor as making it connection settings driver properties separator works, but only for that session. next time launch DBeaver, the separator has been replaced with a space. so all data smushed in one column. I then edited .dbeaver-data-sources.xml in a text editor and replaced it there. When DBeaver launched it, once more, had been replaced by a space. I also edited beaver-data-sources.xml in a text editor and replaced it &#09;. Saved, closed, then reopened in text editor saw that the code had been replaced by the tab. Kept the text editor open when DBeaver launched, file parsed correctly. Closed DBeaver and text editor reported it changed. Reloaded in text editor, separator now a space.

#### Steps to reproduce, if exist:
as above

**Comment by uslss** [comment]
cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket
