### ISSUE TITLE
[freature_request]ERD Diagram generate DDL for non existing DB

### ISSUE THREAD

**Issue by bitsnaps** [dbeaver/dbeaver#5852]
Hi,
DBeaver already has the ability to generate DDL script for existing database, how about non existing databases? this feature is available in MySQL Workbench Community Edition (aka. [Forward Engineering](https://dev.mysql.com/doc/workbench/en/wb-forward-engineering-live-server.html)). I couldn't find anyway to generate DDL from newly created ERD Diagram, if this feature doesn't exists in the current version wouldn't be easy to create it since the ERD Diagram already support create DDL from existing DBs? This helps creating a new schema right from ERD.

**Comment by leandroramos** [comment]
It would be awesome!

**Comment by uslss** [comment]
will be implemented soon in EE version

**Comment by uslss** [comment]
https://github.com/dbeaver/pro/issues/500
