### ISSUE TITLE
Use ssh to connect clickhouse fail

### ISSUE THREAD

**Issue by 631068264** [dbeaver/dbeaver#5853]
I use dbeaver 6.0.4

Test ssh success
![image](https://user-images.githubusercontent.com/8144089/57205126-db150c00-6fee-11e9-9b73-36b7e88eb2a3.png)

but connect clickhouse fail
![image](https://user-images.githubusercontent.com/8144089/57205154-20d1d480-6fef-11e9-948a-434befe8c64c.png)

**Comment by serge-rider** [comment]
Generally Clickhouse works fine with SSH.
Check you connection settings. Maybe server listens different IP address and localhost/127.0.0.1 isn't a valid address.
