### ISSUE TITLE
Is it possible to export sql queries in JSON format in Dbeaver?

### ISSUE THREAD

**Issue by Manav1995** [dbeaver/dbeaver#5855]
I am trying to figure out a way to get Dbeaver and matillion redshift in sync using github. Matillion doesn't accept sql files as input, so I want to convert my dbeaver queries into JSON format which is accepted by matillion.

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer, Query cannot be exported in JSON format, but query result can (select in query context menu Execute>Export from query).
Please reopen the ticket or create a new one if you have any other questions.
