### ISSUE TITLE
Suggestion: Semantic Versioning

### ISSUE THREAD

**Issue by boan-jfm** [dbeaver/dbeaver#5856]
Hi, I looked at you milestones, and can't figure out how you determine your versions. Eg. 6.1.0 or 6.0.4.

It seems like you have features and patches in both. I suggest to be more strict about the versioning, and use semantic versioning: https://semver.org/

>Given a version number MAJOR.MINOR.PATCH, increment the:
>1. MAJOR version when you make incompatible API changes,
>2. MINOR version when you add functionality in a backwards-compatible manner, and
>3. PATCH version when you make backwards-compatible bug fixes.

But nice you are using the milestones, and it seems like there is a process :-)

**Comment by p91paul** [comment]
While semver is useful for libraries, how would you define an "incompatible API change" to a desktop tool?
