### ISSUE TITLE
"Extension Office" broken with DBeaver 6.0.4 on linux

### ISSUE THREAD

**Issue by javajack** [dbeaver/dbeaver#5857]
Here is the plugin that is broken.

https://github.com/dbeaver/dbeaver/wiki/Extension-Office

Here is the error that appears as message.

An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.apache.commons.cli,1.3.1
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ce.feature,6.0.4.201905052017
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.application,6.0.4.201905052017
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sample.database,1.0.45.201905052017
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.ui.tipoftheday,1.0.14.201905052017
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.rcp.feature,2.1.83.201905052017
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.standalone.feature,6.0.4.201905052017

**Comment by alesc2000** [comment]
I get the same error on Ubuntu 19.04

**Comment by serge-rider** [comment]
Yes, seems to be a bug in CE version packaging (some P2 bundles are missing).
Could you test fixed version (https://dbeaver.io/files/ea) ?

**Comment by javajack** [comment]
Works on the ea build.  Thanks to fix it promptly.

**Comment by sishgupta** [comment]
Fixed on Windows 7x64 Thank you

**Comment by samiconductor** [comment]
Affects Vrapper 0.74.0 too. Thanks for fixing!

```
An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.ibm.icu.base,58.2.0.v20170418-1837
No repository found containing: osgi.bundle,org.apache.commons.cli,1.3.1
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ce.feature,6.0.4.201905052017
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.application,6.0.4.201905052017
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sample.database,1.0.45.201905052017
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.ui.tipoftheday,1.0.14.201905052017
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.rcp.feature,2.1.83.201905052017
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.standalone.feature,6.0.4.201905052017
```

**Comment by uslss** [comment]
verified
