### ISSUE TITLE
Exporting data only extracts one row

### ISSUE THREAD

**Issue by wazowsk1** [dbeaver/dbeaver#5858]
#### System information: 
- Operating system (distribution) and version
windows 10
- DBeaver version
6.0.4
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
Oracle SQL
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When trying to export data with the selected options "Selected columns only" and/or "Selected rows only" it only exports the first row

#### Steps to reproduce, if exist:
1. query table
2. select a few rows/columns
3. export data with "Selected columns only" and "Selected rows only" to markdown

#### Include any warning/errors/backtraces from the logs
none

**Comment by uslss** [comment]
Unfortunately, cannot reproduce the issue.
@wazowsk1 could you tell what target format was used in that case?

**Comment by wazowsk1** [comment]
Bit late, but after restarting dbeaver it works again as expected
