### ISSUE TITLE
Using scripts for different databases

### ISSUE THREAD

**Issue by pieceofquality** [dbeaver/dbeaver#5860]
I have sql script, which i want use for different databases.
Can i create variable, which definition would be depended of selected database?

**Comment by pieceofquality** [comment]
i use own variable and it's very annoying enter database name after script executing

`FROM ${db_name}.api_users
INNER JOIN ${db_name}.api_user_cards ON ${db_name}.api_user_cards.user_id = ${db_name}.api_users.id`

**Comment by uslss** [comment]
it is already implemented. Script could be executed for different databases using tasks

**Comment by p91paul** [comment]
I don't think tasks address the request at all. This is, in my understanding, about automatically setting a variable (in this example db_name) based on the chosen connection.
