### ISSUE TITLE
Can´t open https://dbeaver.io/files/jdbc/

### ISSUE THREAD

**Issue by renatosartori** [dbeaver/dbeaver#5863]
Hello!
I can´t connect to https://dbeaver.io/files/jdbc/ to download the jdbc drive.

Message:
403 Forbidden
nginx/1.4.6 (Ubuntu)

Best regards,

#### System information: 
- Operating system (distribution) and version Windows 10 Pro
- DBeaver version 6.0.2
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
We don't provide JDBC drivers download repository for a long time. All drivers are downloaded from vendors web sites, Maven or some other official links.
