### ISSUE TITLE
Problem with completion of Oracle dictionary views.

### ISSUE THREAD

**Issue by bobf32** [dbeaver/dbeaver#5866]
#### System information: 
Windows 10 Enterprise 1803
DBeaver versions > 5.1.6.

Oracle 12c

When executing a query referencing an Oracle view such as user_objects, the completion feature does not suggest any column name proposals unless the view name is prefixed by the owner.  

E.g.

`SELECT t.* from SYS.USER_TABLES t WHERE t.<Ctrl-Space> // This will produce a valid list of columns from which to choose.`

`SELECT t.* from USER_TABLES t WHERE t.<Ctrl-Space> // This will not produce a valid list of columns from which to choose.`

However, the latter query will produce a list of valid columns in version 5.1.6. In most releases since then the query without the view owner has failed to produce a proposal list.

**Comment by bobf32** [comment]
Hi, 

Has this one received any attention? It's really irritating to remember to prefix each dictionary view with the owner, after years of built up muscle memory :(

**Comment by uslss** [comment]
Sorry for so late response.
Unfortunately, cannot reproduce it against 7.0.5.
![image](https://user-images.githubusercontent.com/31996417/82804715-717ece80-9e8b-11ea-9405-715169f0c2f2.png)

if issue is still actual for you - feel free to reopen it.
once again sorry for so late response.
