### ISSUE TITLE
Nothing is rendered when create a directory on a empty view

### ISSUE THREAD

**Issue by Bai-Xiaoguang** [dbeaver/dbeaver#5867]
#### System information: 
- Win7
- DBeaver 6.0.4
- JDK 8

#### Describe the problem you're observing:
There is nothing rendered while I create a directory on the first time I started the dbeaver.
Then I tried sometimes, but it still render nothing on it.
The 'lost' directories will be appear when I finished a connection creation.

**Comment by serge-rider** [comment]
What is a "directory"? Do you mean connection folder?

**Comment by serge-rider** [comment]
Done

**Comment by uslss** [comment]
verified
