### ISSUE TITLE
Disable inline editor

### ISSUE THREAD

**Issue by GriGrim** [dbeaver/dbeaver#5868]
#### System information: 
- Windows 7 Professional
- 6.0.2

#### Connection specification:
- Exasol

#### Describe the problem you're observing:
Is it possible to disable inline editor?
I need to have possiblity to run DML queries but not to change data in result set grid.

**Comment by umphy** [comment]
I was looking for the same feature as well. As a work around, how about changing the results section from Grid to Text?

**Comment by GriGrim** [comment]
Thanks for helping me to find right preference.
Setting that I need can be found in **Preferences** - **Database** - **Editors** - **Data Editor** - **Presentation**
In **Grid** block there is a setting called **Double-click behaviour**.
Choose **None**.
![grid_inline_editor](https://user-images.githubusercontent.com/2479756/57601147-626cfd00-7564-11e9-8f8e-78d01c068629.png)
