### ISSUE TITLE
Different schema for each sql editor

### ISSUE THREAD

**Issue by Redirts** [dbeaver/dbeaver#5871]
#### System information: 
- Operating system (distribution) and version: Windows 10 64 bit
- DBeaver version: 6.0.4
- Java version 1.8.0_211
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgreSQL 9.6.10 on x86_64
- Driver name: org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I want to have two SQL Editor windows open with queries for the same PostgreSQL DB but targeting different schemas.

When I change the active schema on one SQL Editor window the other windows associated to the same DB also change the active schema.

#### Steps to reproduce, if exist:
See above

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by uslss** [comment]
already implemented
