### ISSUE TITLE
How can i create a DBeaver Connection through CLI or any programmatic way

### ISSUE THREAD

**Issue by niraj8241** [dbeaver/dbeaver#5874]
#### System information: 
- Operating system (distribution) and version -- Windows 10 Version 1703
- DBeaver version -- Version 6.0.0
- Java version -- 1.8
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name -- Redshift
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Hi,

I am trying to find an option where I can create/update my DBeaver Connection through a command line option. Is it possible to do?

--
Niraj

**Comment by serge-rider** [comment]
Check this: https://github.com/dbeaver/dbeaver/wiki/Command-Line

**Comment by niraj8241** [comment]
I did had a look at the CLI. But it seems like it just runs through CLI, open up Dbeaver. But I can't seem to create a new Connection or update an existing one with new username and password. I already have couple of connection created which I would like to update via CLI took. Can you give me an example on creating and updating username and passwords.

**Comment by serge-rider** [comment]
Well, there is `password` parameter for connection opening thru cli.
Something like this:
```
-con driver=driver|database=xxx|openConsole=true|folder=SQLite|user=usr|password=mypwd
```

**Comment by sackp** [comment]
i noticed that when using cli to open dbeaver, the password is stored in logs. Is there a way to stop logging or mask out the password?

**Comment by serge-rider** [comment]
Could you post an example of such logs?
It definitely shouldn't be there.

**Comment by sackp** [comment]
it is the same issue listed here: https://github.com/dbeaver/dbeaver/issues/3788

located in $HOME\.dbeaver4\.metadata\.log

here is a simple log:!ENTRY org.jkiss.dbeaver.model 2 0 2019-05-16 14:23:16.062
!MESSAGE Project [P/General] already added
!SESSION 2019-05-17 10:43:29.098 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -con driver=oracle|user={username}|password={Password}|url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST={host})(PORT=51000))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME={TNS})))
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -con driver=oracle|user={username}|password={password}|url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST={host})(PORT=51000))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME={DSN})))

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
There are not any updates on issue for a long time. 
It is closed.
If it is still actual for you - feel free to reopen it
