### ISSUE TITLE
Autocomplete problems (ctrl+space)

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#5875]
System information: 
- OS Windows 7 Pro x64
- DBeaver 6.0.4
- Java version 1.8.0_201
- No additional extensions

Connection specification:
- Postgresql 9.5
- PostgreSQL standard driver 9.4.1212.jre7

Query for example:
"SELECT t. FROM some_table t"
If i stay after "t." and press ctrl+space - no results in field searching
If i add space symbol after table alias like that "SELECT t. FROM some_table t " (or move to next line and add "join....") - field searching returns result

**Comment by ems2811** [comment]
#### System information:
- Windows 7 Pro x64
- DBeaver 6.1.4
- Java version 1.8.0_211
- No additional extensions

#### Connection specification:
- PostgreSQL 9.5.16 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit
- Driver org.postgresql:postgresql:RELEASE[9.4.1212.jre7]

Problem with cte still reproduces in DBeaver 6.1.4

**Comment by uslss** [comment]
issue isn't reproducible in 6.2.3. Ticket closed
