### ISSUE TITLE
Null Connection returned

### ISSUE THREAD

**Issue by fedefel** [dbeaver/dbeaver#5877]
#### System information: 
- Windows 10 Professional
- 6.0.4 and 6.0.3
- Java version 1.8.0 build 1.8.0_211-b12)
#### Connection specification:
- Apache Drill
- we use client proxy

#### Steps to reproduce, if exist:

re Configuring Apache Drill connection that worked in past times, I'm not able to connect to the db and it returns "Null Connection Returned".
On driver settings I've 
_org.apache.hadoop:hadoop:common-RELEASE
org.apache.drill.exec:drill-jdbc-all-RELEASE

Clicked Download and Update, it generates the list, ask to download and I let it download.

in Preferences -> Driver -> Maven, I've also put repository.mapr.com and Maven Central to the top.

I don't understand why it gives this error, it is happening since 6.0.2

**Comment by serge-rider** [comment]
Thanks for the resolution note
