### ISSUE TITLE
Query in oracle too slow

### ISSUE THREAD

**Issue by luizplago** [dbeaver/dbeaver#5878]
When performing a select on some tables I realized that the first time is really slow. Using the "Query Manager" I checked that there is a query that is executed before the select I made, and this is extremely slow. (In my case it's taking about 30 seconds to bring 33 records)

SELECT C.TABLE_NAME,
       C.CONSTRAINT_NAME,
       C.CONSTRAINT_TYPE,
       C.STATUS,
       C.R_OWNER,
       C.R_CONSTRAINT_NAME,
       C.TABLE_NAME AS R_TABLE_NAME,
       C.DELETE_RULE,
       COL.COLUMN_NAME,
       COL.POSITION
FROM ALL_CONSTRAINTS C,
     ALL_CONS_COLUMNS COL,
     ALL_CONSTRAINTS RC
WHERE C.CONSTRAINT_TYPE = 'R'
AND   C.OWNER = 'OWNER'
AND   C.OWNER = COL.OWNER
AND   C.CONSTRAINT_NAME = COL.CONSTRAINT_NAME
AND   RC.OWNER = C.R_OWNER
AND   RC.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME
AND   C.TABLE_NAME = 'TABLE'
ORDER BY C.CONSTRAINT_NAME,
         COL.POSITION

The following is the result of the "execution plan":
![image](https://user-images.githubusercontent.com/1467093/57380349-3bd34e80-717f-11e9-8522-14e186d08234.png)

But by changing the query and taking out the table ALL_CONSTRAINTS that is being used twice.

SELECT C.TABLE_NAME,
       C.CONSTRAINT_NAME,
       C.CONSTRAINT_TYPE,
       C.STATUS,
       C.R_OWNER,
       C.R_CONSTRAINT_NAME,
       C.TABLE_NAME AS R_TABLE_NAME,
       C.DELETE_RULE,
       COL.COLUMN_NAME,
       COL.POSITION
FROM ALL_CONSTRAINTS C,
     ALL_CONS_COLUMNS COL
WHERE C.CONSTRAINT_TYPE = 'R'
AND   C.OWNER = 'OWNER'
AND   C.OWNER = COL.OWNER
AND   C.CONSTRAINT_NAME = COL.CONSTRAINT_NAME
AND   C.TABLE_NAME = 'TABLE'
ORDER BY C.CONSTRAINT_NAME,
         COL.POSITION

That way the result came in only 1 second and the result of the "execution plan" was this:
![image](https://user-images.githubusercontent.com/1467093/57380492-72a96480-717f-11e9-841f-b9c86ae8b510.png)

I believe that with this change the performance would improve a lot, I hope to be helping.

**Comment by serge-rider** [comment]
Well, this second ALL_CONSTRAINTS join is there for a reason (it is in the foreign keys reading procedure).
Oracle metadata reading performance issue are very database-dependent (e.g. on our test db this query works less than 1 second).

In any case, on some Oracle server enabling following options increases performance significantly, could you try it:
![image](https://user-images.githubusercontent.com/6398845/57639652-1304ec00-75b9-11e9-9ebd-53aa3cbce66f.png)

**Comment by luizplago** [comment]
I've seen that it looks for the foreign keys, that's why the query is so slow in my database because there are many tables referencing it, so I made that suggestion.

In my case even marking these optimization options, it still runs this select in all_constraints twice so it does not help, the first run takes at least 30 seconds, after that it gets great.

Here in the company we use Oracle 10g.

Would it not be possible to review the reasons for this use?

**Comment by AndrewKhitrin** [comment]
Hello @luizplago  !

Can you execute this query on your environment and give us execution plan and approx execution time  

_SELECT 
	c.TABLE_NAME,
	c.CONSTRAINT_NAME,
	c.CONSTRAINT_TYPE,
	c.STATUS,
	c.R_OWNER,
	c.R_CONSTRAINT_NAME,
	(SELECT rc.TABLE_NAME FROM DBA_CONSTRAINTS rc WHERE rc.OWNER = c.r_OWNER AND rc.CONSTRAINT_NAME = c.R_CONSTRAINT_NAME) AS R_TABLE_NAME,
	c.DELETE_RULE,
	(SELECT col.COLUMN_NAME FROM DBA_CONS_COLUMNS col WHERE col.OWNER ='OWNER' AND col.CONSTRAINT_NAME = c.CONSTRAINT_NAME) COLUMN_NAME,
	(SELECT col.POSITION FROM DBA_CONS_COLUMNS col WHERE col.OWNER ='OWNER' AND col.CONSTRAINT_NAME = c.CONSTRAINT_NAME) POSITION
FROM
	DBA_CONSTRAINTS c
WHERE
	c.CONSTRAINT_TYPE = 'R'
	AND c.OWNER = 'OWNER'
	AND c.TABLE_NAME = 'TABLE'_
	
If it possible can you use real TABLE and OWNER name

**Comment by luizplago** [comment]
Hello @AndrewKhitrin I saw your query here, it did not work because the result was multiple lines, but I understood your idea. I'll talk to some friends who understand query optimization well here too. Below is the result of the original consultation so you have an idea of what I said about the multiple lines.

The last column (POSITION) of the lines that I selected will have values 1 and 2.

![image](https://user-images.githubusercontent.com/1467093/57810069-52f4dc00-773d-11e9-9de0-580b33fc7c0e.png)

**Comment by AndrewKhitrin** [comment]
Hello @luizplago !

This query just for check some ideas on your specific environments. Can you test this one (with mult. columns) ?

> SELECT 
> 	c.TABLE_NAME,
> 	c.CONSTRAINT_NAME,
> 	c.CONSTRAINT_TYPE,
> 	c.STATUS,
> 	c.R_OWNER,
> 	c.R_CONSTRAINT_NAME,
> 	(SELECT rc.TABLE_NAME FROM DBA_CONSTRAINTS rc WHERE rc.OWNER = c.r_OWNER AND rc.CONSTRAINT_NAME = c.R_CONSTRAINT_NAME) AS R_TABLE_NAME,
> 	c.DELETE_RULE,
> 	(
> 	    SELECT LTRIM(MAX(SYS_CONNECT_BY_PATH(cname || ':' || p,','))    KEEP (DENSE_RANK LAST ORDER BY curr),',') 
> 		FROM   (SELECT 
> 		               col.CONSTRAINT_NAME cn,col.POSITION p,col.COLUMN_NAME cname,
> 		               ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) AS curr,
> 		               ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) -1 AS prev
> 		        FROM   DBA_CONS_COLUMNS col 
> 		        WHERE  col.OWNER ='OWNER' AND col.TABLE_NAME = 'TABLE' AND col.CONSTRAINT_NAME = c.CONSTRAINT_NAME 
> 		        )	GROUP BY cn	CONNECT BY prev = PRIOR curr AND cn = PRIOR cn START WITH curr = 1	    
> 	    ) COLUMN_NAMES_NUMS
> FROM
> 	DBA_CONSTRAINTS c
> WHERE
> 	c.CONSTRAINT_TYPE = 'R'
> 	AND c.OWNER = 'OWNER'
> 	AND c.TABLE_NAME = 'TABLE'

Can you check this one with  real TABLE and OWNER name ?

**Comment by luizplago** [comment]
Hello @AndrewKhitrin this new query went very well!
In my environment I can not run the "DBA_CONSTRAINTS, DBA_CONS_COLUMNS" view, so it replaces "ALL_CONS_COLUMNS, ALL_CONS_COLUMNS"
 
> SELECT C.TABLE_NAME,
       C.CONSTRAINT_NAME,
       C.CONSTRAINT_TYPE,
       C.STATUS,
       C.R_OWNER,
       C.R_CONSTRAINT_NAME,
       (SELECT RC.TABLE_NAME
        FROM **ALL_CONSTRAINTS** RC
        WHERE RC.OWNER = C.R_OWNER
        AND   RC.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME) AS R_TABLE_NAME,
       C.DELETE_RULE,
       (SELECT LTRIM(MAX(SYS_CONNECT_BY_PATH (CNAME || ':' || P,',')) KEEP (DENSE_RANK LAST ORDER BY CURR),',')
        FROM (SELECT COL.CONSTRAINT_NAME CN,
                     COL.POSITION P,
                     COL.COLUMN_NAME CNAME,
                     ROW_NUMBER() OVER (PARTITION BY COL.CONSTRAINT_NAME ORDER BY COL.POSITION) AS CURR,
                     ROW_NUMBER() OVER (PARTITION BY COL.CONSTRAINT_NAME ORDER BY COL.POSITION) -1 AS PREV
              FROM **ALL_CONS_COLUMNS** COL
              WHERE COL.OWNER = 'OWNER'
              AND   COL.TABLE_NAME = 'TABLE_NAME'
              AND   COL.CONSTRAINT_NAME = C.CONSTRAINT_NAME)
        GROUP BY CN CONNECT BY PREV = PRIOR CURR AND CN = PRIOR CN START WITH CURR = 1) COLUMN_NAMES_NUMS
FROM **ALL_CONSTRAINTS** C
WHERE C.CONSTRAINT_TYPE = 'R'
AND   C.OWNER = 'OWNER'
AND   C.TABLE_NAME = 'TABLE_NAME'

The execution plan of the new query was (running in: 1 second!):
![image](https://user-images.githubusercontent.com/1467093/57852454-a0169380-77b9-11e9-8343-9319deba23b5.png)


The execution plan of the old query is (running in: 35 seconds):
![image](https://user-images.githubusercontent.com/1467093/57852673-259a4380-77ba-11e9-8220-0e9a4b1ad490.png)

**Comment by luizplago** [comment]
Hello @AndrewKhitrin the query was great, but I did not realize that the results were different. The original query returns 33 records while the new one returns 30.

**Comment by AndrewKhitrin** [comment]
@luizplago All "multicolumn" constraints in new query will presents in one row in column COLUMN_NAMES_NUMS. Propably this is the reason why you see 30 rows instead 33

**Comment by luizplago** [comment]
Dude, you saved my life! It worked perfectly!

**Comment by AndrewKhitrin** [comment]
Thanks !

**Comment by AndrewKhitrin** [comment]
@luizplago Hi !

Can you downlad EA version here - https://dbeaver.io/files/ea/ and check it on your environment.


Thanks.

**Comment by luizplago** [comment]
I downloaded the version, but I could not use the improvement. What do I need to do to activate it?

**Comment by AndrewKhitrin** [comment]
Its already bundled, just look  on query speed in "Query Manager",  anything changed ?

**Comment by luizplago** [comment]
I've tried checking and unchecking the performance options "Use RULE hint for system catalog queries." and "use metadata queries optimizer", but the original query continues.

**Comment by serge-rider** [comment]
@luizplago I've re-published EA version, could you test it one more time?

**Comment by luizplago** [comment]
I'm not getting. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/1467093/57948656-9b84d480-78b8-11e9-8859-4b0f8a141e08.png)

![image](https://user-images.githubusercontent.com/1467093/57948753-e69ee780-78b8-11e9-8bec-3d5006446faf.png)

**Comment by serge-rider** [comment]
The query you posted is constraints reading query. Foreign keys reading query was changed.

**Comment by luizplago** [comment]
dude, I did not find your change.

**Comment by serge-rider** [comment]
@luizplago Could you test how FK reading query looks like? Just expand Foreign Keys folder and see query in Query Manager view (enable metadata queries view).
I've tested latest EA and on my machine it looks like this:
```sql
SELECT 
    c.TABLE_NAME,
    c.CONSTRAINT_NAME,
    c.CONSTRAINT_TYPE,
    c.STATUS,
    c.R_OWNER,
    c.R_CONSTRAINT_NAME,
    (SELECT rc.TABLE_NAME FROM ALL_CONSTRAINTS rc WHERE rc.OWNER = c.r_OWNER AND rc.CONSTRAINT_NAME = c.R_CONSTRAINT_NAME) AS R_TABLE_NAME,
    c.DELETE_RULE,
    (
        SELECT LTRIM(MAX(SYS_CONNECT_BY_PATH(cname || ':' || p,','))    KEEP (DENSE_RANK LAST ORDER BY curr),',') 
        FROM   (SELECT 
                       col.CONSTRAINT_NAME cn,col.POSITION p,col.COLUMN_NAME cname,
                       ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) AS curr,
                       ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) -1 AS prev
                FROM   ALL_CONS_COLUMNS col 
                WHERE  col.OWNER ='HR' AND col.TABLE_NAME = 'ACCOUNTS' AND col.CONSTRAINT_NAME = c.CONSTRAINT_NAME 
                )   GROUP BY cn CONNECT BY prev = PRIOR curr AND cn = PRIOR cn START WITH curr = 1      
        ) COLUMN_NAMES_NUMS
FROM
    ALL_CONSTRAINTS c
WHERE
    c.CONSTRAINT_TYPE = 'R'
    AND c.OWNER = 'HR'
    AND c.TABLE_NAME = 'ACCOUNTS'
```

**Comment by luizplago** [comment]
In the version available I could not see the changes ... I see the queries in the query manager, but it remains the original. if I'm doing something wrong please let me know how I can do it.

**Comment by AndrewKhitrin** [comment]
Hello @luizplago can you please elaborate step by step what and how you execute query in EA DBeaver client, what metrics and results you get and evaluate.

**Comment by luizplago** [comment]
The test I have done is pretty simple, I clean the query manager and run a simple query with a table that has many relationships.

So even with this version available the query that it stops and keeps running a good time (20-30 seconds) remains the original.

![image](https://user-images.githubusercontent.com/1467093/57975398-897d6180-799e-11e9-88a5-01cdd45b508b.png)


> SELECT c.TABLE_NAME, c.CONSTRAINT_NAME, c.CONSTRAINT_TYPE, c.STATUS, c.R_OWNER, c.R_CONSTRAINT_NAME, rc.TABLE_NAME AS R_TABLE_NAME, c.DELETE_RULE, col.COLUMN_NAME, col.POSITION
FROM ALL_CONSTRAINTS c, ALL_CONS_COLUMNS col, ALL_CONSTRAINTS rc
WHERE c.CONSTRAINT_TYPE = 'R'
AND c.OWNER = 'CM'
AND c.OWNER = col.OWNER
AND c.CONSTRAINT_NAME = col.CONSTRAINT_NAME
AND rc.OWNER = c.r_OWNER
AND rc.CONSTRAINT_NAME = c.R_CONSTRAINT_NAME
AND c.TABLE_NAME = 'FUNCIONARIO'
ORDER BY c.CONSTRAINT_NAME, col.POSITION

In this execution I have an error with the query below, because here the sys user is not the owner of these views

> SELECT 1 FROM SYS.ALL_TAB_COLS WHERE 1<>1

**Comment by serge-rider** [comment]
Please check it in 6.0.5 release.
Regular constraints reading queries were also updated

**Comment by luizplago** [comment]
Guys, I found the incredible improvement I know she certainly improved the performance a lot, but I do not understand why it does not work in my environment. Here in my environment dbeaver 6.0.5 continues to use the original query.
