### ISSUE TITLE
Firebird DDL: wrong SQL on new column

### ISSUE THREAD

**Issue by borgogelli** [dbeaver/dbeaver#5879]
DbEaver 6.0.4 with Firebird 2.5 database connection

When I try to add a new colum

![image](https://user-images.githubusercontent.com/7045594/57441993-583cbd00-724b-11e9-9bec-aa2113df0c58.png)

the DDL generated is
```
ALTER TABLE PROVA ADD COLUMN1 INTEGER SET DEFAULT  DEFAULT 1;
 ...
```
and of course is not a valid sql syntax (the DEFAULT clause is added twice)
But even if I don't insert any default value, see the picture below

![image](https://user-images.githubusercontent.com/7045594/57442310-fc266880-724b-11e9-9957-9677f69a6655.png)

the DDL generated is wrong
```
ALTER TABLE PROVA ADD COLUMN1 INTEGER DROP DEFAULT;
...
```
That sql statement is not compatible with the Firebird syntax (token unknown error on DROP)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
