### ISSUE TITLE
[feature request] Save ER Diagram layout

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#5880]
After re-arranging the ER diagram with tens of tables, i found out that closing the diagram or refreshing it changes the arrangment of tables, instead of just adding/removing/updating.
Which means, every time i make a small change to a table, i have to re-arrange the full ER diagram again, from scratch.
That is really time comsuming, and makes the "ER Diagram" tool pretty "unuseful" to me.

**Comment by uslss** [comment]
Already implemented in 7.0.5

**Comment by logan-life** [comment]
Refreshing does indeed cause the ERD to reset in layout. So this is either not actually implemented, or a bug.

Version 24.1.2.202407071610
