### ISSUE TITLE
Error when inserting Geometry column with PostGIS

### ISSUE THREAD

**Issue by nikolovjd** [dbeaver/dbeaver#5881]
#### System information: 
- Operating system (distribution) and version: Ubuntu 19.04
- DBeaver version: 6.0.4

#### Connection specification:
- Database name and version: Postgresql 9.6 with PostGIS
- Driver name: JDBC

#### Describe the problem you're observing:
Trying to insert a new Geography value results in the following error:
```SQL Error [22023]: ERROR: Geometry SRID (0) does not match column SRID (4326)```

If I add the SRID to the WKT representation, like: SRID=4326;POINT (-19 11.1):
``` 
Error synchronizing data with database
Reason:
org.postgis.PGgeometry.<init>(org.locationtech.jts.geom.Geometry)
```

I can insert values without using DBeaver just fine. Also I can update existing entries. The error only occurs when trying to insert a new row, even if I duplicate an existing row with a Geography value.

In previous versions of DBeaver I could insert data using WKT like SRID=4326;POINT (0 1), but after updating to 6.0.4 I can't.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
