### ISSUE TITLE
backup: cannot disable opening of file manager

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#5883]
DBeaver 6.0.4, CE on Linux with Postgres 11

Database -> Tools -> Backup

With one of the latest updates, the checkbox to disable the file manager after backup is gone.
There seems to be no setting for that either:

Preferences -> General -> Workspace -> Command for launching system explorer

seems to match, but it does not matter if I leave it empty or set something, it always opens Gwenview (which isn't even a file manager).
Looks as if either the setting is for something entirely different (if so, for what?) or it has no effect.

**Comment by uslss** [comment]
cannot reproduce it for now. File manager isn't opened.
if it is still actual for you - feel free to reopen the ticket
