### ISSUE TITLE
backup: settings not remembered

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#5884]
DBeaver 6.0.4, CE on Linux/Debian SID  with Postgres 11, OpenJDK 11

Database -> Tools -> Backup

Each time I open the Backup dialog I need to select at least
- Format
- Compression
- Encoding
again.

Instead the previously selected values should show (as happens with "Output folder" and "File name pattern").
Additionally, Encoding should by default show the DB encoding.

**Comment by uslss** [comment]
previously selected values are shown now.
if it is still actual for you - feel free to reopen the ticket
