### ISSUE TITLE
Oracle resulst

### ISSUE THREAD

**Issue by levent1132** [dbeaver/dbeaver#5885]
Hi,
![resim](https://user-images.githubusercontent.com/20375605/57541094-ece01180-7356-11e9-90ec-dc6cef6a6589.png)

How ı can delete this (00000000) after start from dot_??

I could't fınd ın settıngs whıch ı found ın ınternet.
![resim](https://user-images.githubusercontent.com/20375605/57541450-bc4ca780-7357-11e9-983d-43995d1924ab.png)

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/57607528-ef6b8280-7573-11e9-905b-b3495113f5e0.png)

**Comment by levent1132** [comment]
Hi Sergey, 
I was checked this "checkbox" before and it was already "checed". Still results are coming with many "zero(0)". I tied with another DB program. Results are coming normal. Just on Dbeaver showing like that.
Still I couldn't fix. Look like its so easy problem but nobody could fix it yet.
Thanks.
![resim](https://user-images.githubusercontent.com/20375605/57708601-49eb0880-7672-11e9-82c8-2754a7353caf.png)

**Comment by levent1132** [comment]
@serge-rider  Could you check again? Is it not possible to fix or nor ?

**Comment by serge-rider** [comment]
This checkbox should be <b>un</b>checked in your case. 
Once you check it zeroes may appear if database data type has long scale.
