### ISSUE TITLE
MongoDB doesn't understand nor respect Date fields

### ISSUE THREAD

**Issue by fabiopedrosa** [dbeaver/dbeaver#5886]
While editing a mongoDB row if there's any ISODate like this:

![image](https://user-images.githubusercontent.com/88341/57543581-a38ac480-734c-11e9-9ad1-d7898d6b89a0.png)

once I try to update ANY value, it converts it to string:

![image](https://user-images.githubusercontent.com/88341/57543600-b1d8e080-734c-11e9-8f0e-29356939a6dc.png)

This is a major flaw for me.

**Comment by serge-rider** [comment]
Thanks for the bug report.
Although `ISODate()` value is not a valid JSON value it works in Mongo BSON. 
So we'll add support of it.
Thanks for the bug report.

**Comment by uslss** [comment]
verified
