### ISSUE TITLE
"Format SQL" incorrectly inserts spaces in scientific notation of numbers

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#5887]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.0.4
- Java version: 8
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11.2 / PostGIS 2.5.2
- Driver name: PostgreSQL driver for Windows
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

"Format SQL" incorrectly inserts spaces in scientific notation of numbers, see the spaces around the "+" as inserted after selecting "Format SQL", which should read as **"9E+6"**. As a consequence, running the query results in an error. Removing the spaces result in successful query evaluation.

![afbeelding](https://user-images.githubusercontent.com/7635726/57573243-00f24480-7425-11e9-80cf-74fae5307f42.png)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
