### ISSUE TITLE
Minor usability issue: F4 context menu options not opening "Properties" TAB properly

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#5889]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.0.4
- Java version: 8
- Additional extensions

#### Connection specification:
- Database name and version:  PostgreSQL 11.2
- Driver name: PostgreSQL driver for Windows
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Hi,

I noticed this minor usability issue: 

If you click on the F4 right-click context menu's for e.g. a table or view in an attempt to show the columns or indexes of a relation ("View Columns" / "View Indexes"), then, depending on whether the "Properties" / "Data" / "ER Diagram" was the TAB that was open the last time you accessed the table, instead of showing the columns or indexes, the "Data" or "ER Diagram" may be opened and the columns or indexes not shown, despite explicitly choosing that context menu option. Only when the "Properties" TAB was the active TAB when the relation was last accessed, will the columns or indexes be correctly shown.

From a usability perspective, when the user chooses to view the columns or indexes ("View Columns" / "View Indexes"), I would expect the "Properties" TAB to be automatically selected, instead of the last viewed TAB to be remembered and opened.

#### Steps to reproduce, if exist:
**- Choose e.g. "View Indexes" _after having closed a table with the "Data" TAB active_:**

![afbeelding](https://user-images.githubusercontent.com/7635726/57580153-2ffcca80-74a6-11e9-8384-e80498c64118.png)

**- "Data" TAB is incorrectly opened instead of the "Properties" TAB:**

![afbeelding](https://user-images.githubusercontent.com/7635726/57580309-296f5280-74a8-11e9-8dd7-c8f0fdd0eb09.png)

**- I would expect DBeaver to jump straight to the "Properties" TAB:**

![afbeelding](https://user-images.githubusercontent.com/7635726/57580341-9551bb00-74a8-11e9-8e65-106997c4676f.png)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified

**Comment by mboeringa** [comment]
Great, thanks for picking these minor issues up as well, this is what makes DBeaver such a useful application.
