### ISSUE TITLE
In 6.0.4 Active connection is no longer colored

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#5891]
#### System information: 
- Operating system (distribution) and version: Mac
- DBeaver version: 6.0.4
- Java version: 1.8.0_192
- Additional extensions

#### Connection specification:
- Database name and version: various
- Driver name: default
- Do you use tunnels or proxies (SSH, SOCKS, etc): ssh tunnel

#### Describe the problem you're observing:
In previous versions (6.0.2 and below) the active connection and selected schemas were colored according to the environment color settings
In 6.0.4 the color is just plain grey (while the results pane itself IS colored properly):
![image](https://user-images.githubusercontent.com/18515297/57581170-837a1300-74bc-11e9-8be6-725015380b44.png)

**Comment by serge-rider** [comment]
We can't  return it back as is because now we use native OS controls and they do not support changing of background color. However we'll try to use another way to visualize it.

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by pyrocks** [comment]
awesome, thanks!
