### ISSUE TITLE
Saving scripts in v6.0.4

### ISSUE THREAD

**Issue by linxpatrick** [dbeaver/dbeaver#5892]
OS = OpenSuSE Leap 15
DBeaver = 6.0.4
Java version = unknown
No additional extensions

Database is PostgreSQL using the JDBC driver.
In don't understand why saving scripts in DBeaver works the way it does. Here's what I mean.
If I create a script and save it, particularly using CTRL+S, it saves without allowing me to give it a name. The name is Script or Script-1, etc. Names like this are pretty much useless when it comes time to load it up again.
I set the connection to save to a shared folder. If I click File>>Save SQL Script the correct directory opens but the file file name is set to Script-1, Script-2, etc, even if I previously saved the file or loaded the file using File>>Load SQL Script. I have to select the script that I saved before from the list in order to get the same name as previously used. This will eventually lead to overwriting the wrong script.
Can saving scripts be made to work like most every other program works when saving a document? Use Libre Office Writer as an example.

**Comment by kseniiaguzeeva** [comment]
Is this still actual for you? You can rename Script using shortcut Ctrl+F2 or via context menu. 
The script will be saved with that name.

**Comment by uslss** [comment]
there is no update on ticket for a long time. if issue is still actual for you - feel free to reopen the ticket
