### ISSUE TITLE
Data Refresh

### ISSUE THREAD

**Issue by AmbroiseVuaridel** [dbeaver/dbeaver#5895]
I would like to schedule auto-refresh to happen on a regular basis as described here:
https://github.com/dbeaver/dbeaver/wiki/Data-Refresh
I cannot find the button anywhere, was that functionality removed ?

#### System information: 
- Operating system (distribution) and version MACOSX 10.14.4 (18E226)
- DBeaver version   6.0.4.201905052017

**Comment by uslss** [comment]
As far as I see, this functionality still exists on Windows build (button is mentioned at attached picture). Unfortunately, I've got no possibility to check it on MacOS at the moment. Could you please check that there is no button there on macos?
![image](https://user-images.githubusercontent.com/31996417/57652232-c67cd900-75d7-11e9-9b8c-57581dd7a9f0.png)

**Comment by AmbroiseVuaridel** [comment]
> As far as I see, this functionality still exists on Windows build (button is mentioned at attached picture). Unfortunately, I've got no possibility to check it on MacOS at the moment. Could you please check that there is no button there on macos?
> ![image](https://user-images.githubusercontent.com/31996417/57652232-c67cd900-75d7-11e9-9b8c-57581dd7a9f0.png)

Ok, thank you, the problem was that you need to select a table to see the button, I was always selecting a DB instead. Does that mean the auto-refresh is only applied on that table ? if no, why put the button there ?

**Comment by uslss** [comment]
yes. auto-refresh is applied on the table only
