### ISSUE TITLE
DBeaver might not dump startup exceptions if log is fresh

### ISSUE THREAD

**Issue by codebling** [dbeaver/dbeaver#5901]
The **[log](https://github.com/dbeaver/dbeaver/files/3175821/dbeaver.log)** for #5899 contains 3 run attempts, and 4 exceptions. What's more interesting is what isn't in the file. The first run after deleting the log file never dumps exceptions, even though DBeaver was crashing in the same manner every time. 

As with #5899, this issue may not be worth fixing but might be worth noting in case an issue is filed with a first run log that contains no exceptions.

**Comment by uslss** [comment]
cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket

**Comment by codebling** [comment]
Have not really used Dbeaver in a while, and the two issues seemed to specifically be related to upgrade. Closing the issue seems fine to me

**Comment by codebling** [comment]
(The crash was on startup and possibly before Eclipse framework had fully initialised itself)
