### ISSUE TITLE
Unable to rename sequence in Postgresql

### ISSUE THREAD

**Issue by tchibatron** [dbeaver/dbeaver#5902]
#### System information: 
- Windows 10
- DBeaver version 6.0.3
- Java version 8
- Additional extensions no

#### Connection specification:
- Database name and version Postgres 11.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
DBeaver generates wrong DDL to update sequence name. And, probably, because of this, it's impossible to rename sequence.

#### Steps to reproduce, if exist:
Create sequence with name sequence_generator. Save it:
![1](https://user-images.githubusercontent.com/6930846/57688655-b223f500-7646-11e9-9b92-34e06974697e.png)

Try to rename:
![2](https://user-images.githubusercontent.com/6930846/57688691-c831b580-7646-11e9-925b-bdd83c8ce374.png)
Error message appears, but shouldn't have to.
![image](https://user-images.githubusercontent.com/6930846/57688726-ded80c80-7646-11e9-9878-ef94b754e5e4.png)

**Comment by CristianUrbainski** [comment]
Hello, I solved this problem, but how do I apply the solution, commit and merge request for the team to evaluate my solution ?
I plan to start helping here, because it's a project that I use a lot in the day-to-day and I chose to start with something easier.

**Comment by tchibatron** [comment]
@CristianUrbainski You should create a fork of this repo. Than create a pull request from your fork to devel branch of current repository.

**Comment by CristianUrbainski** [comment]
i created pull request

https://github.com/dbeaver/dbeaver/pull/5923

I noticed something strange, changing the name of the sequence even without saving the change the name is already changed in the name of the tab, and in the menu on the side where the connections are shown, should this be?

**Comment by uslss** [comment]
verified
