### ISSUE TITLE
Sequence does not appear in project tree when creating column with serial type.

### ISSUE THREAD

**Issue by tchibatron** [dbeaver/dbeaver#5904]
#### System information: 
- DBeaver version: 6.0.4
- Java version: 8
- Additional extensions: no

#### Connection specification:
- Database name and version: Postgresql 11.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Steps to reproduce, if exist:
Create a column in a table with type serial.
Do not forget to check Not Null checkbox.
Click save button.

Observe that sequences node in project tree does not contain new sequence for new created column in previous steps.
If you click on refresh button, it will appear.

[Video](https://www.dropbox.com/s/2xjfuwl638vl4ws/Kazam_screencast_00002.mp4?dl=0)

**Comment by serge-rider** [comment]
We do not refresh other metadata objects on any schema changes. We probably should but it is a more generic task.

**Comment by kseniiaguzeeva** [comment]
Will be implemented in https://github.com/dbeaver/dbeaver/issues/6398
