### ISSUE TITLE
Manual selection of column type suggestion combobox does not work

### ISSUE THREAD

**Issue by tchibatron** [dbeaver/dbeaver#5906]
#### System information: 
- Does not depend on OS, verified on Linux and Windows
- DBeaver version 6.0.4
- Java version: 8
- Additional extensions: no

#### Connection specification:
- Database name and version: Postgresql 11.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Steps to reproduce, if exist:
Add column with default type(varchar for postgresql)
Click on type hyperlink.
Start typing "se" to find "serial" type.
Click on serial in suggestion combobox.

Error appears.

Please take a look to the [video](https://www.dropbox.com/s/0rn5kajjomhypy4/Kazam_screencast_00005.mp4?dl=0)

**Comment by uslss** [comment]
Fized. Verified on Win
