### ISSUE TITLE
Minor usability issue: "Move to next / last row" do nothing if no record is selected

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#5909]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.0.4
- Java version: 8
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11.3 / PostGIS 2.5.2
- Driver name: PostgreSQL driver for Windows
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Hi,

I noticed this minor usability issue: 

After having opened a table and going to the Data TAB, initially there will be no record selected. In that case, if you click on the enabled "Move to next row" or "Move to last row" buttons to browse through the current record set, nothing happens. Only after a I select a record, will the buttons actually do something. Of course and logically, something like "Move to next row" is not possible until an active record is available in the data grid.

However, this is somewhat counter-intuitive: either the buttons should be disabled until you select a record, or better, the table should open with a selected record, or the buttons must also function without a selected record by automatically selecting the first record once clicked if no selected active record is available.

E.g. Microsoft Access seems to always open up with a row active.

#### Steps to reproduce, if exist:

![afbeelding](https://user-images.githubusercontent.com/7635726/57763221-405cb180-7701-11e9-90a9-3fc5680f82fb.png)

![afbeelding](https://user-images.githubusercontent.com/7635726/57763494-c11bad80-7701-11e9-803e-cb8f43233980.png)

**Comment by serge-rider** [comment]
Good point

**Comment by uslss** [comment]
verified
