### ISSUE TITLE
[Fearture request] Ability to save Backup/Import tools configuration

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#5910]
When Backing-up using (in this case, on postgres database) "RightClick on schemaname -> Tools -> Backup", after the view "Choose objects to export", in the "Backup Settings" section, only "Output" section (Output folder, File name pattern) is saved.
The Settings part (Format, Compression, Encoding, ...) is always resetter to default values.
If, for instance, i chose Format=Plain and Compression=9, next time i export those settings are defaulted, so one has to change those every time.

**Comment by uslss** [comment]
feature is already implemented
