### ISSUE TITLE
Problems for exporting data using the Office integration

### ISSUE THREAD

**Issue by andersusilva** [dbeaver/dbeaver#5911]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.0.3.20190411926
- Java version: 8 build 1.8.0_181-b13
- Additional extensions: [Office integration](https://dbeaver.io/update/office/latest/)

#### Connection specification:
- Database name and version: aserel
- Driver name: Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
- I am having trouble exporting data such as date or time using the Office integration extension, because when I extract this data that is in the date or time format, it appears to be of type text in the .xlsx file.
- This impairs the display, filter, or PivotTable using text-type fields. In DBeaver this data is as DATA, I believe the problem is only in extension.

#### Steps to reproduce, if exist:
Execute the query, display the data, select the export data option, select the XLSX option, click on next, choose the table settings, click on next, configure options and parameters of output, click on next, check results and click on to finish. When I open the generated file, all fields that would be of type date or time in excel are in text format and do not allow field customization, only if I edit one by one.

**Comment by uslss** [comment]
verified

**Comment by andersusilva** [comment]
Verified and corrected? How should I proceed?

**Comment by andersusilva** [comment]
> 
> 
> verified

Verified and corrected? How should I proceed?

**Comment by uslss** [comment]
Hi @andersusilva ,
issue was already fixed and for CE version will be available only after 6.1.0 release,
But this fix is already available in EE version EA  (https://dbeaver.com/files/ea/)
Feel free to reopen the ticket if your issue isn't solved.
Sorry for any inconvenience caused.
