### ISSUE TITLE
Sample database (SQLite) has erroneous tables

### ISSUE THREAD

**Issue by allentiak** [dbeaver/dbeaver#5915]
-The table "Employee3" should be named "Employee".
(The view "EmpView" points to the missing "Employee" table.)

-The table "foo" should be deleted

Found in DBeaver CE 6.0.4.201905052017.

**Comment by serge-rider** [comment]
Actually there are different SQLite Chinook database dumps over the internet, not sure that there is some canonical one.
Anyhow Employee3 is definitely some weird bug. `foo` is still there.
Thanks for the bug report.

**Comment by allentiak** [comment]
You're welcome!

BTW: The "canonical" Chinook moved from CodePlex (
https://archive.codeplex.com/?p=chinookdatabase) to GitHub (
https://github.com/lerocha/chinook-database).

**Comment by uslss** [comment]
verified
