### ISSUE TITLE
Geometries with EPSG:25832 are not displayed correctly in the map panel

### ISSUE THREAD

**Issue by torsten3y** [dbeaver/dbeaver#5918]
#### System information: 
- Operating system (distribution) and version
* Win10 64-bit
- DBeaver version
* 6.0.4
- Java version 
* java version "1.8.0_77"
- Additional extensions

#### Connection specification:
- Database name and version
* 
- Driver name
* postgresql-42.2.5.jar
* postgis-jdbc-2.2.1.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
* SSH-Tunnel

#### Describe the problem you're observing:
I'm working with wbk_geometry having a UTM-Projection. EPSG-Code is: 25832.
When I select a geometry of a table or query the point or polygon is displayed but iin a wrong location. The geometry is actually always displayed at the northern border of the worldmap.
The map-setting is done to EPSG:25832, i.e. it should fit.

#### Steps to reproduce, if exist:
Use a geometry with EPSG:25832 and display it in the map panel. Maybe the error is also true for all geometrys which differ from 4326 but I cannot check this currently.

#### Include any warning/errors/backtraces from the logs
* No entries in the logfile
![map_point_location_dbeaver1](https://user-images.githubusercontent.com/3072738/57856235-de797600-77ec-11e9-86cb-5ac2cd6acb06.png)
![map_point_location_dbeaver12](https://user-images.githubusercontent.com/3072738/57856236-de797600-77ec-11e9-9133-8fe5a522f1a4.png)

![map_point_location_dbeaver1](https://user-images.githubusercontent.com/3072738/57856096-93f7f980-77ec-11e9-9f53-6e29cc8573df.png)
![map_point_location_dbeaver12](https://user-images.githubusercontent.com/3072738/57856097-93f7f980-77ec-11e9-84f5-017d6ecdb6f3.png)

**Comment by torsten3y** [comment]
Sorry for double-posting the images!

**Comment by serge-rider** [comment]
Please post some geometry examples in 25832.
Something like 
```sql
SELECT 1,'SRID=25832;POINT(-73.985744 40.748549)'::geometry
```

**Comment by torsten3y** [comment]
First of all, THX for taking it up!
Here is a result of, i.e. the qurey returning the geometry in EPSG:25832:
`select 1, wkb_geometry from _schema.table_ limit 1;`

?column?|wkb_geometry              |
--------|--------------------------|
       1|POINT (360521 5628168.729)|

And the same query but this time returning the geometry in 4326:
`select 1, st_transform(wkb_geometry, 4326) from _schema.table_ limit 1;`

?column?|st_transform                               |
--------|-------------------------------------------|
       1|POINT (7.021164038493922 50.78846803756188)|

Here the selected point is displayed correctly on the map.

**Comment by serge-rider** [comment]
Well, it transforms/renders fine on the latest versions: 
![image](https://user-images.githubusercontent.com/6398845/57928638-0aaef880-78ba-11e9-90bd-211a4a91dc4c.png)

You can download Early Access from https://dbeaver.io/files/ea

**Comment by torsten3y** [comment]
Great, works like a charm! That's really the killer feature for me with Dbeaver.

**Comment by torsten3y** [comment]
All done in the latest version 6.0.5, works perfectly!
