### ISSUE TITLE
PostgreSQL. Backup does not work

### ISSUE THREAD

**Issue by tchibatron** [dbeaver/dbeaver#5919]
#### System information: 
- Windows 10
- DBeaver version: 6.0.3
- Java version: 8
- Additional extensions: no

#### Connection specification:
- Postgresql 11.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
The dump file, DBeaver has created, is empty.

#### Steps to reproduce, if exist:
Right click on DB name. -->Tools -> Backup -> Select schema and table -> Next
Format: plain
Compression: 4
Encoding: UTF-8
Check Use sql insert instead of COPY for rows
Click start.

Output:
C:\Users\alexey_chibisov\.dbeaver-drivers\clients\postgresql\win\pg_dump.exe --format=p --compress=4 --encoding=UTF-8 --inserts -t public.address --verbose --host=localhost --port=5432 --username=postgres test
Backup started at Thu May 16 16:21:21 MSK 2019
Backup finished at Thu May 16 16:21:21 MSK 2019
Process exit code: -1073741515

Log file is clear.

If I run DBeaver generated command in console I see next errors:
![image](https://user-images.githubusercontent.com/6930846/57856970-d0305780-77f6-11e9-9fb8-ee00c32e09c0.png)
![image](https://user-images.githubusercontent.com/6930846/57856983-d6becf00-77f6-11e9-9295-338b215a0996.png)

**Comment by serge-rider** [comment]
zlib1 and lebeay32 are pretty common shared libs. Never had a chance to test on a machine without them. Anyway, it seems that we have to ship them too.
Thanks for the bug report.

**Comment by uslss** [comment]
verified
