### ISSUE TITLE
Allow reverting changes to single cells

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#5920]
Hi,
https://github.com/dbeaver/dbeaver/issues/1447 and https://github.com/dbeaver/dbeaver/issues/1446 were opened for full undo support.

It would be probably good enough, and more easily doable, a simple "revert this cell". Currently we have the cancel button at the bottom, which reverts all changes done to the cells and not yet persisted. But if you edited 10 cells, and realize one of those edits is wrong, you can either revert all 10 or persist all 10. A "cancel edit on this cell" item in the cell context menu would be most appreciated, and the old cell value is probably readily available to dbeaver because it's needed for the "Cancel" button feature.

**Comment by serge-rider** [comment]
We already have it: context menu Edit->Reset cell changes (or just <kbd>ESC</kbd>)

**Comment by p91paul** [comment]
thanks! sorry didn't notice :smile:
