### ISSUE TITLE
Translation error: privileges grantor/grantee translations are interchanged.

### ISSUE THREAD

**Issue by snoop247** [dbeaver/dbeaver#5925]
#### System information: 
- Microsoft Windows version 1703 (Build 15063.1387)
- DBeaver version 6.0.4.201905052017
- Java version 8 Update 201 (Build 1.8.0_201-bd09)

#### Describe the problem you're observing:
The German translations of the columns 
`grantee` - `Begünstigter`
`grantor` - `Begünstiger`
are switched, when showing user privileges on a table. 

Since they are almost identical, maybe an alternative translation would be clearer as well:
`grantee` - `Empfänger`
`grantor` - `Geber`.

I just wanted to inform, because I noticed it today. Normally I use the EN version.
best regards
Daniel

**Comment by serge-rider** [comment]
Good point, thanks for the report and better translation propose.
