### ISSUE TITLE
parameters input window

### ISSUE THREAD

**Issue by icegood** [dbeaver/dbeaver#5926]
#### System information: 
- Operating system: Linux ice-ubuntu16 4.15.0-50-generic #54~16.04.1-Ubuntu SMP Wed May 8 15:55:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- DBeaver : 6.0.4
- Java : 
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

- Additional extensions : none

#### Connection specification:
- SQLite: SQLite version 3.28.0 2019-04-16 19:49:53
- Driver name: jdbc:sqlite:
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
For a given query  'select * from my+_table where :my_col = :q'
In parameter input screen for 'q' i cannot properly input value. I don't see updates for it

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update almost a month. ticket closed
