### ISSUE TITLE
Row insertion in data view fails with older PostgreSQL version

### ISSUE THREAD

**Issue by EricBrunel** [dbeaver/dbeaver#5928]
#### System information: 
- Operating system (distribution) and version: Linux openSuse Leap 15.0
- DBeaver version: 6.0.4.201905052017
- Java version: OpenJDK 10.0.2
- Additional extensions: -

#### Connection specification:
- Database name and version: PostgreSQL v7.4.8
- Driver name: postgres-jdbc (standard driver)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Acces to databse via an IPSec VPN

#### Describe the problem you're observing:
Whenever I try to insert a new row in the data view, I get an error:
`ERROR: syntax error at or near "RETURNING"`
If I copy the INSERT and paste it directly in a SQL Editor view and execute it, it works. It seems the data view is adding a RETURNING clause that is not supported by the server (which is very old for sure: v7.4.8 dates from quite a few years ago and doesn't support this clause in INSERTs).

Is there any way to prevent the RETURNING clause from being added to the INSERT? I looked in the preferences but didn't spot anything that seemed relevant, but maybe I missed something...

**Comment by uslss** [comment]
cannot reproduce an issue for now. if it is still actual for you - feel free to reopen the ticket
