### ISSUE TITLE
Add Google Spanner support

### ISSUE THREAD

**Issue by flascaray** [dbeaver/dbeaver#5930]
I am using the official JDBC driver for Google Spanner in Dbeaver. The queries work very well but the autocomplete doesn't work.

it would be nice if Dbeaver support Spanner.

**Comment by serge-rider** [comment]
Done. We'll use https://github.com/olavloite/spanner-jdbc driver by default (because official one requires auth)

**Comment by flascaray** [comment]
@serge-rider that driver does not work correctly in certain queries. Also the queries are very slow. The good thing about that driver is that the autocomplete works

**Comment by serge-rider** [comment]
Maybe this depends on the driver version? I had an impression that both these drivers use the same google api/libraries.

**Comment by serge-rider** [comment]
From dbeaver perspective they are very similar. The only problem with simba driver is impossibility of automatic download.

**Comment by serge-rider** [comment]
We will include OS driver in the next version. If there are any issues with it - please create separate ticket. We'll change the driver if there will be no workarounds
