### ISSUE TITLE
[PostgreSQL] Cannot create database when owner has hyphen

### ISSUE THREAD

**Issue by EpicEric** [dbeaver/dbeaver#5932]
#### System information: 
- Linux Mint 18.3
- DBeaver 6.0.4

#### Connection specification:
- PostgreSQL 10

#### Describe the problem you're observing:
I cannot create a database if the assigned owner has an hyphen in the name.

#### Steps to reproduce
1. Create a user with an hyphen in the name (eg. "hello-world")
2. Right click on an active connection
3. Create -> Database
4. Create any database (eg. "example") with "hello-world" as the owner

```
SQL Error [42601]: ERROR: syntax error at or near "-"
  Position: 35
ERROR: syntax error at or near "-"
  Position: 35
ERROR: syntax error at or near "-"
  Position: 35
```

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
