### ISSUE TITLE
Grid display of linked records (FR)

### ISSUE THREAD

**Issue by kgeographer** [dbeaver/dbeaver#5934]
Feature Request: 
Ability to view "child" records from a second table linked by FK relation, when selecting a row in a grid. This has been done in Valentina Studio (which has other issues) and would make switching to dBeaver (superior in several other ways) an easy choice. Brilliant software, thanks.
![image](https://user-images.githubusercontent.com/1753945/57972998-2b7d5980-795f-11e9-877b-c5cab89ddf41.png)

**Comment by serge-rider** [comment]
We already have reference value viewer (in a panel "Value View") but it shows just a couple of columns (so-called dictionary ones). Having complete second result set of linked table may be really useful.
