### ISSUE TITLE
<no schema> showing in toolbar instead of the set schema in connection setting

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#5944]
#### System information: 
- Operating system (distribution) and version: Windows 10 1809 (OS Build 17763.437)
- DBeaver version: 6.0.5

#### Connection specification:
MSSQL 2016

#### Describe the problem you're observing:
Previously the Ctrl+9 then select db to connect to would update toolbar to show the database that it connects to.

Recently though to show which schema that you are connected to you need to go Ctrl+0 and then the Schema is shown in dropdown toolbar.

I have checked various dbs and same thing happens all the time.

The connection is there but in the drop down it says <no schema>

Go in with Ctrl+0 then I can see the database is selected in the dropdown and I can see in the background that it updates active connection to show the right DB

**Comment by uslss** [comment]
can't reproduce.
if issue is still actual for you - feel free to reopen the ticket
