### ISSUE TITLE
Export includes virtual generated columns in insert statement

### ISSUE THREAD

**Issue by ErikvLinstee** [dbeaver/dbeaver#5946]
#### System information: 
- Ubuntu 19.04
- 6.0.4.201905052017
- OpenJDK 11.0.3

#### Connection specification:
- MySQL

I have a number of tables with generated columns. These are columns that do not actually contain data, but are generated from another column using an expression.

When I export such a table, the insert statements include the generated column. Upon execution, such an insert statement will fail, because the data cannot actually inserted.

**Comment by uslss** [comment]
still reproducible (7.1.1) for e.g. export from db to db

**Comment by serge-rider** [comment]
Generally generated columns can be excluded by turning off option "Include generated columns".  However this will also remove all non-virtual auto-increment columns.

We shouldn't export virtual columns in SQL format ever.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Virtual column is still exported if you run export from Data Editor. Steps:
1. Open a table with virtual column in Data Editor (e.g. postgres.Xeniia.newtable_1)
2. Open Export wizard via Data Editor for the table
3. Select Database and press Next
4. Set creating a new table in a Target
5. Press Schema btn

Actual result: virtual column appears in DDL:
CREATE TABLE "Xeniia".newtable_1_to(
	column1 bigserial NOT NULL,
	column2 varchar,
	vcolumn varchar);

**Comment by serge-rider** [comment]
@kseniiaguzeeva This is ok. Because user may want to export virtual columns.
This ticket is about data export in SQL INSERT format.

**Comment by kseniiaguzeeva** [comment]
verified
