### ISSUE TITLE
[Feature Request] Make the option "Truncate target table before load" false by default

### ISSUE THREAD

**Issue by gabrieltulli** [dbeaver/dbeaver#5948]
In the data transfer tool, on the last step, the option "Truncate target table before load" come enabled by default.
This may cause a huge headache when you just want to add some data to a existent table.
If the option came disabled the worst case cenario is the user having to make the import again.

![image](https://user-images.githubusercontent.com/1847957/58023371-00714200-7ae6-11e9-9660-9f2f44fdffce.png)

**Comment by jccostasouza** [comment]
For the love of god, please accept this suggestion.

**Comment by serge-rider** [comment]
I am quite sure it is already disabled by default. At least this is what I see in new versions.

However, as this is still a very dangerous option we need additional user confirmation for it.

**Comment by uslss** [comment]
verified.
By default feature is disabled. Pop-up appears in case feature is checked
![image](https://user-images.githubusercontent.com/31996417/58051777-c0e53d00-7b5b-11e9-8e18-a914c15371fc.png)

**Comment by gabrieltulli** [comment]
thanks! 👍

**Comment by gabrieltulli** [comment]
I downloaded the new version 6.1.0 currently on EA and the fix works greatly well. The only point is that the option still come enabled by default, but with the pop-up I think that is ok.
