### ISSUE TITLE
Loses focus after editing cell value on datagrid/table data

### ISSUE THREAD

**Issue by calegarifabio** [dbeaver/dbeaver#5949]
#### System information: 
- Operating system (distribution) and version: MacOS Mojave / Linux Ubuntu / Windows
- DBeaver version 6.0.5 / 6.0.4 / 6.0.3......

#### Describe the problem you're observing:
inside a grid data editor, when you press the ENTER, edit the value, and try to navigate with the arrows to another column or record, the focus is lost, you need to click the mouse to focus back.

**Comment by calegarifabio** [comment]
In version 5.3.0 works fine

**Comment by tati-kru** [comment]
Thank you for the bug report

**Comment by serge-rider** [comment]
Can't reproduce this on Windows.
 
But on MacOS it is broken indeed.

**Comment by serge-rider** [comment]
It is a side effect of #5399 fix

**Comment by daltondiaz** [comment]
It's work fine on linux version 6.0.4, but on Macs ins't work!!

**Comment by tati-kru** [comment]
Verified
