### ISSUE TITLE
Aurora PostgresQL Schema Backup Failing Due to Case Sensitive Naming 

### ISSUE THREAD

**Issue by Ninjapg** [dbeaver/dbeaver#5950]
#### System information: 
- Operating system (distribution) and version  - Windows 10, 64 bit
- DBeaver version   - 6.0.5
- Java version  : 8
- Additional extensions: None

#### Connection specification:
- Database name and version : Aurora PostgreSQL 9.6
- Driver name : Driver 42.2.0.jre7
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  Yes

#### Describe the problem you're observing:

While taking a backup for NossilBI schema, as the schema name has Caps. Can you please update the backup script to consider such exceptions.

pg_dump.exe --format=c -n "NossilBI" --verbose --host=127.0.0.1 --port=51149 --username=postgresusr postgres
Backup started at Mon May 20 12:22:12 EDT 2019
pg_dump: last built-in OID is 16383
pg_dump: no matching schemas were found
Backup finished at Mon May 20 12:22:13 EDT 2019
Process exit code: 1

#### Steps to reproduce, if exist:

Create Schema with Case Sensitive, Ex NossilBI
Create few tables and views, 
Take Backup

#### Include any warning/errors/backtraces from the logs

pg_dump.exe --format=c -n "NossilBI" --verbose --host=127.0.0.1 --port=51149 --username=postgresusr postgres
Backup started at Mon May 20 12:22:12 EDT 2019
pg_dump: last built-in OID is 16383
pg_dump: no matching schemas were found
Backup finished at Mon May 20 12:22:13 EDT 2019
Process exit code: 1

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified

**Comment by Ninjapg** [comment]
Thanks, can you please let me know, when can i use the code to update.
