### ISSUE TITLE
Feature request: code indexing similar to Intellij

### ISSUE THREAD

**Issue by morl-la** [dbeaver/dbeaver#5953]
#### System information: 
- Operating system (distribution) and version: macos
- DBeaver version: 6.0.5

#### What
It would be nice for DBeaver to (optionally) index code objects (triggers, procedures, functions) similar to intellij with Java methods/classes.
This means that ctrl+clicking on a name of a function/procedure/trigger goes to the code that defines it within the project, if found.
Not sure how feasible this is, but it would be a cool feature.

**Comment by serge-rider** [comment]
Generally it already implemented. Just press ctrl and move mouse above identifier.

However there may be some issues in target objects resolution and it very depends on your database.
What is your database btw?

**Comment by morl-la** [comment]
You mean something similar to F4 - that's not what I mean. I mean this will go to where the code that creates the function is in the source file (same file or another file in the same project).
so for example on a postgres project if I <whatever>+click on `myfunc` in `select myfunc()` it will theoretically go to `myfunc.sql` in which `create function myfunc` exists.

The F4 functionality is nice - but it is less useful for actual DB development.

**Comment by morl-la** [comment]
@uslss why was this closed? this is a valid feature request, unless you have no intention of implementing it - and then state so.
