### ISSUE TITLE
Execute log - row count empty

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#5954]
System information:

    OS Windows 7 Pro x64
    DBeaver 6.0.5
    Java version 1.8.0_201
    No additional extensions

Connection specification:

    Postgresql 9.5
    PostgreSQL standard driver 9.4.1212.jre7

After executing query below in "Execute Log" insert row count doesn't display. In "Statistics" count=2
```
CREATE TEMP TABLE tt(id int);

INSERT INTO tt
VALUES(1),(2)
```

![изображение](https://user-images.githubusercontent.com/22142845/58075414-5d392f00-7bb0-11e9-9d98-69b04f46f7fe.png)
![изображение](https://user-images.githubusercontent.com/22142845/58075435-6a561e00-7bb0-11e9-9205-bf27252ec5db.png)

**Comment by ems2811** [comment]
The same problem with DBeaver 6.1 (empty row count in "Execution Log" after insert/update/delete)

**Comment by ems2811** [comment]
The same problem with DBeaver 6.1.2 (empty row count in "Execution Log" after insert/update/delete). System information and connection specification the same

**Comment by ems2811** [comment]
The same problem with DBeaver 6.1.3 (empty row count in "Execution Log" after insert/update/delete)
Differences in system information: Java version 1.8.0_211

**Comment by uslss** [comment]
verified
