### ISSUE TITLE
Sybase connections always require to redownload license.txt

### ISSUE THREAD

**Issue by ALDamico** [dbeaver/dbeaver#5956]
#### System information: 
- Windows 10 v 10.0.17763.503
- DBeaver 6.0.4 (although this issue also occurred with 6.0.0 and later versions)
- Java version 1.8.0_201
- No extensions

#### Connection specification:
- Database name and version Sybase Adaptive Server Enterprise 12.5.4
- Driver name: Sybase jConnect
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
Whenever I connect to a Sybase ASE database, DBeaver prompts me to download the file LICENSE.txt for the jConnect driver and refuses to connect to the server otherwise.
![image](https://user-images.githubusercontent.com/33159753/58085221-9e374080-7bbc-11e9-969d-4352a44fcebf.png)
This behavior only disappears after I manually remove the LICENSE.txt file from the dialog, forcing the application to redownload the driver itself.

#### Steps to reproduce, if exist:
Attempt to connect to a Sybase ASE 12.5.4 database.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
