### ISSUE TITLE
Can't edit the cell using DBeaver 6.0.5 (with Dbeaver 6.0.2 works)

### ISSUE THREAD

**Issue by dsu-inf** [dbeaver/dbeaver#5957]
I upgraded DBeaver from 6.0.2 to 6.0.5 (latest version).
After this upgrade I cannot edit the cell anymore:

![image](https://user-images.githubusercontent.com/45175580/58092305-6cca6f00-7bd4-11e9-959e-f876ca4e6ea5.png)

![image](https://user-images.githubusercontent.com/45175580/58092314-7227b980-7bd4-11e9-9558-2f5f3239278e.png)

If you need more information please add a comment.

**Comment by PabloAPereira** [comment]
I got the same problem, before update I could do a select and edit the result and now I need to write the whole sentence to UPDATE

**Comment by troegel01** [comment]
100% reproducible here. Issue as described above with version 6.0.5 under Windows 10 64 bit.

**I did a rollback to version 6.0.4 and everything is working as before.**

**Comment by AndrewKhitrin** [comment]
Data can not edited in any table or only in some?

**Comment by dsu-inf** [comment]
@AndrewKhitrin 
In any table. I tried in both variants: to edit a result set (the result of `select * form T where ...`) and to edit the table's data.

**Comment by AndrewKhitrin** [comment]
@dsu-inf 

Which version of Oracle do you use ?

**Comment by marcgise** [comment]
Same here. Only happens with Oracle. I'm using the driver 18.3, but also happens with previous drivers like 12.2.0.1.
I tried with dbeaver 6.0.4 and it works perfectly, so it's an error introduced in the latest version 6.0.5.
It happens with all the tables

**Comment by AndrewKhitrin** [comment]
@dsu-inf 

Can you execute two queries on your environment (from user ) and give results (its just constraints definitions for table OR_INSTANCE in schema DSU_ORGA)

```
SELECT 
	c.TABLE_NAME,
	c.CONSTRAINT_NAME,
	c.CONSTRAINT_TYPE,
	c.STATUS,
	c.R_OWNER,
	c.R_CONSTRAINT_NAME,
	(SELECT rc.TABLE_NAME FROM ALL_CONSTRAINTS rc WHERE rc.OWNER = c.r_OWNER AND rc.CONSTRAINT_NAME = c.R_CONSTRAINT_NAME) AS R_TABLE_NAME,
	c.DELETE_RULE,
	(
	    SELECT LTRIM(MAX(SYS_CONNECT_BY_PATH(cname || ':' || p,','))    KEEP (DENSE_RANK LAST ORDER BY curr),',') 
		FROM   (SELECT 
		               col.CONSTRAINT_NAME cn,col.POSITION p,col.COLUMN_NAME cname,
		               ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) AS curr,
		               ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) -1 AS prev
		        FROM   ALL_CONS_COLUMNS col 
		        WHERE  col.OWNER ='DSU_ORGA' AND col.TABLE_NAME = 'OR_INSTANCE' AND col.CONSTRAINT_NAME = c.CONSTRAINT_NAME 
		        )	GROUP BY cn	CONNECT BY prev = PRIOR curr AND cn = PRIOR cn START WITH curr = 1	    
	    ) COLUMN_NAMES_NUMS
FROM
	ALL_CONSTRAINTS c
WHERE
	c.CONSTRAINT_TYPE = 'R'
	AND c.OWNER = 'DSU_ORGA'
	AND c.TABLE_NAME = 'OR_INSTANCE'
```

and this

```
SELECT
	c.TABLE_NAME,
	c.CONSTRAINT_NAME,
	c.CONSTRAINT_TYPE,
	c.STATUS,
	c.SEARCH_CONDITION
	,
	(
	    SELECT LTRIM(MAX(SYS_CONNECT_BY_PATH(cname || ':' || p,','))    KEEP (DENSE_RANK LAST ORDER BY curr),',') 
		FROM   (SELECT 
		               col.CONSTRAINT_NAME cn,col.POSITION p,col.COLUMN_NAME cname,
		               ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) AS curr,
		               ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) -1 AS prev
		        FROM   ALL_CONS_COLUMNS col 
		        WHERE  col.OWNER ='DSU_ORGA' AND col.TABLE_NAME = 'OR_INSTANCE' AND col.CONSTRAINT_NAME = c.CONSTRAINT_NAME 
		        )	GROUP BY cn	CONNECT BY prev = PRIOR curr AND cn = PRIOR cn START WITH curr = 1	    
	    ) COLUMN_NAMES_NUMS
FROM
	ALL_CONSTRAINTS c
WHERE
	c.CONSTRAINT_TYPE <> 'R'
	AND c.OWNER = 'DSU_ORGA'
	AND c.TABLE_NAME = 'OR_INSTANCE'
```

**Comment by dsu-inf** [comment]
@AndrewKhitrin 

> Which version of Oracle do you use ?

![image](https://user-images.githubusercontent.com/45175580/58108421-7cf24680-7bf4-11e9-9906-7cb7edaf37ef.png)

> Can you execute two queries on your environment (from user ) and give results (its just constraints definitions for table OR_INSTANCE in schema DSU_ORGA)

For both queries the result is an error (`SQL Error [904] [42000]: ORA-00904: "C"."CONSTRAINT_NAME": invalid identifier`) 

![image](https://user-images.githubusercontent.com/45175580/58108767-19b4e400-7bf5-11e9-8bca-958287286f76.png)

**Comment by serio72** [comment]
Same for me: I cannot edit fields or view constraints in oracle

**Comment by AndrewKhitrin** [comment]
@dsu-inf 
Can you try ti execute this query 

```
SELECT 
	c.TABLE_NAME,
	c.CONSTRAINT_NAME,
	c.CONSTRAINT_TYPE,
	c.STATUS,
	c.R_OWNER,
	c.R_CONSTRAINT_NAME,
	(SELECT rc.TABLE_NAME FROM ALL_CONSTRAINTS rc WHERE rc.OWNER = c.r_OWNER AND rc.CONSTRAINT_NAME = c.R_CONSTRAINT_NAME) AS R_TABLE_NAME,
	c.DELETE_RULE,
	(
	    SELECT LTRIM(MAX(SYS_CONNECT_BY_PATH(cname || ':' || p,','))    KEEP (DENSE_RANK LAST ORDER BY curr),',') 
		FROM   (SELECT 
		               col.CONSTRAINT_NAME cn,col.POSITION p,col.COLUMN_NAME cname,
		               ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) AS curr,
		               ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) -1 AS prev
		        FROM   ALL_CONS_COLUMNS col 
		        WHERE  col.OWNER ='DSU_ORGA' AND col.TABLE_NAME = 'OR_INSTANCE'
		        ) d  WHERE cn = c.CONSTRAINT_NAME 	GROUP BY cn	CONNECT BY prev = PRIOR curr AND cn = PRIOR cn START WITH curr = 1	    
	    ) COLUMN_NAMES_NUMS
FROM
	ALL_CONSTRAINTS c
WHERE
	c.CONSTRAINT_TYPE = 'R'
	AND c.OWNER = 'DSU_ORGA'
	AND c.TABLE_NAME = 'OR_INSTANCE'
```

**Comment by dsu-inf** [comment]
@AndrewKhitrin 

For your last query the result is:
```
TABLE_NAME |CONSTRAINT_NAME   |CONSTRAINT_TYPE|STATUS |R_OWNER |R_CONSTRAINT_NAME|R_TABLE_NAME  |DELETE_RULE|COLUMN_NAMES_NUMS|
-----------|------------------|---------------|-------|--------|-----------------|--------------|-----------|-----------------|
OR_INSTANCE|FK5C6F8F916756A16 |R              |ENABLED|DSU_ORGA|SYS_C0018297386  |OR_RDBMS      |NO ACTION  |RDBMS:1          |
OR_INSTANCE|FK5C6F8F9154740346|R              |ENABLED|DSU_ORGA|SYS_C0018297402  |OR_MACHINE    |NO ACTION  |NOMACHINE:1      |
OR_INSTANCE|FK5C6F8F9155E70947|R              |ENABLED|DSU_ORGA|SYS_C0018293576  |OR_INSTANCE   |NO ACTION  |NOINSTANCEBASE:1 |
OR_INSTANCE|FK5C6F8F9192612CCF|R              |ENABLED|DSU_ORGA|SYS_C0018297395  |OR_APPLICATION|NO ACTION  |NOAPPLICATION:1  |
```

**Comment by ritielledomingos** [comment]
Good afternoon!
I am also having the same problem in version 6.0.5, the previous version (6.0.4) was working normally. Windows 10 OS.

**Comment by AndrewKhitrin** [comment]
Thank you all very much for your participation.

We are trying to fix the issue in the release.

Could you test the version from early access (https://dbeaver.io/files/ea/) and reportthe results here in comments (whether the problem is fixed or not)

Thanks again to all of you!
Andrew.

**Comment by diego-vasarelli** [comment]
Hi,

the early access version seems to work good. I'm on Windows 10.

Thanks for the support!!

**Comment by marcgise** [comment]
Hi, I can confirm too that it works on Ubuntu 18.04 ;)

Thanks!

**Comment by PabloAPereira** [comment]
Hi, 
This new version works fine. I am using Win10 64bits

Thanks.

**Comment by dsu-inf** [comment]
It's OK. Thanks

**Comment by mmislablum** [comment]
> Thank you all very much for your participation.
> 
> We are trying to fix the issue in the release.
> 
> Could you test the version from early access (https://dbeaver.io/files/ea/) and report the results here in comments (whether the problem is fixed or not)
> 
> Thanks again to all of you!
> Andrew.

I download that version and it works ok in *Oracle 11g Release 11.2.0.2.0 64 bits Production Driver: Oracle JDBC 11.2.0.4.0*

Thanks a lot!!
