### ISSUE TITLE
I found a typo in the client when ading a new local client

### ISSUE THREAD

**Issue by edward2990** [dbeaver/dbeaver#5962]
Whan opening the window to add a new local client i found a typo it says 'Acadir' instead of 'Añadir'

![image](https://user-images.githubusercontent.com/18198323/58111259-2585b380-7bbf-11e9-96a6-ba1d6a70c6b4.png)

_This is a great tool, nice work_

**Comment by serge-rider** [comment]
Thanks for the bug report
