### ISSUE TITLE
Copy as HTML is broken

### ISSUE THREAD

**Issue by JMarkMurphy** [dbeaver/dbeaver#5963]
#### System information: 
- Windows 10
- DBeaver version - 6.0.5
- Java version - included

#### Describe the problem you're observing:
Copy as HTML pastes as text not HTML

#### Steps to reproduce, if exist:
1. Select results in result set
2. Select Advanced Copy
3. Select Copy as HTML

![image](https://user-images.githubusercontent.com/2379218/58117155-f1fd5600-7bcb-11e9-9cd8-997a73ca3746.png)

4. Past into Outlook message

![image](https://user-images.githubusercontent.com/2379218/58117261-28d36c00-7bcc-11e9-8264-5690ade7c8d3.png)

Using SQuirreL Client with similar operation I get:

![image](https://user-images.githubusercontent.com/2379218/58117343-56b8b080-7bcc-11e9-98a3-c4948abb0477.png)

The HTML as text is largely useless to me. It appears that the way SQuirreL puts the data onto the clipboard is different than what dBeaver does.

**Comment by serge-rider** [comment]
We need to set proper clipboard format for CopyAs commands.

**Comment by uslss** [comment]
verified
