### ISSUE TITLE
Connecting to DB2 on AS400

### ISSUE THREAD

**Issue by aditseng** [dbeaver/dbeaver#5965]
#### System information: 
- Window Server 2013
- DBeaver version 6.0.4
- Java version 
- Additional extensions

#### Connection specification:
- DB2 on AS400
- db2jcc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

I'm getting the following error:
[jcc][t4][10509][13454][3.71.22] Connection to the data server failed. The IBM Data Server for JDBC and SQLJ license was invalid 
or was not activated for the DB2 for z/OS subsystem. If you are connecting directly to 
the data server and using DB2 Connect Unlimited Edition for System z, perform the 
activation step by running the activation program in the license activation kit.  
If you are using any other edition of DB2 Connect, obtain the license file, 
db2jcc_license_cisuz.jar, from the license activation kit, and follow the installation 
directions to include the license file in the class path. ERRORCODE=-4230, SQLSTATE=42968

The DB administrator is asking if I can use the JTOpenToolkit, but when I try to download that driver it doesn't work with DBeaver.

Any help would be appreciated.

**Comment by patrickmdnet** [comment]
This is a server side issue.  There is an APAR here for error code -4230 which may help you:
https://www-01.ibm.com/support/docview.wss?uid=swg1IC82094
