### ISSUE TITLE
Consider changing default font for SQL Editor to "Hack"

### ISSUE THREAD

**Issue by Walkeer** [dbeaver/dbeaver#5967]
"Hack" font is specifically designed for coding and is in my opinion easier to read then the default used by DBeaver for SQL editor. Please consider using it as default.

https://github.com/source-foundry/Hack
https://sourcefoundry.org/hack/

**Comment by uslss** [comment]
SQL Editor font could be changed in preferences to the font you need
![image](https://user-images.githubusercontent.com/31996417/83782693-97308280-a698-11ea-8242-ac9e66ce2f4f.png)
