### ISSUE TITLE
[bug] Query "execution in progress" popup has no background and is unreadable

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#5970]
As from image here
https://www.dropbox.com/s/fug3zhk2m5zp5l1/DBeaver605.jpg?dl=0

The "Query in progress" popup is not a real popup, is unreadable and almost impossible to see in big resolution screens
(Ubuntu Mate 18.04, defaulth OS theme, default DBeaver theme)

**Comment by wiwwo** [comment]
Also, it changes position every time, makeing it even harder to find.
If a query returned values, it is placed in the middle of the datagrid.
If a query ended in error, it is placed in the loewr-right area.

**Comment by wiwwo** [comment]
Please fix this, it is pretty annoying... :-)

![2](https://user-images.githubusercontent.com/3930671/59604922-cb203a00-910d-11e9-92e8-54ce6b5f83dd.png)


![1](https://user-images.githubusercontent.com/3930671/59604924-cb203a00-910d-11e9-8fcf-e581336d89d9.png)

**Comment by wiwwo** [comment]
Create MV; OK.
Refresh mv ... Popup invisible
![image](https://user-images.githubusercontent.com/3930671/59610242-46d3b400-9119-11e9-8646-312616009e99.png)

**Comment by wiwwo** [comment]
![4](https://user-images.githubusercontent.com/3930671/59610708-2eb06480-911a-11e9-85ff-9f52ead87d87.png)

**Comment by serge-rider** [comment]
Status message font was fixed

**Comment by uslss** [comment]
verified
