### ISSUE TITLE
Test connection doesn't work

### ISSUE THREAD

**Issue by bokanebo** [dbeaver/dbeaver#5971]
#### System information: 
- Win 10 pro 64
- DBeaver version 6.0.5
- Java version 1.8
- Additional extensions

#### Connection specification:
- Oracle 11 and 12
- ojdbc8, Oracle client: odac 12.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
After installing new version I can't finish creating new connection or do a test connection unless going back to initial window.

#### Steps to reproduce, if exist:
New database connection, Oracle, define connection parameters and when you click Test Connection or Finish nothing's happen. Go back and you will be able to test or create connection.

**Comment by serge-rider** [comment]
Is "Test Connection" button enabled?
Could you check for error log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by uslss** [comment]
issue cannot be reproduced. Ticket closed

**Comment by BenPhillipsBMLL** [comment]
I have this same issue now on Ubuntu 18.04, for PostgreSQL

**Comment by TimothyAlexisVass** [comment]
I have this same issue on Ubuntu18.04 for MariaDB and MySQL.
When clicking Test Connection... or Finish nothing happens at all, no error message, nothing...

**Comment by TimothyAlexisVass** [comment]
This was working on a different computer in our department and I noticed we were using different versions. I had DBeaver 7.0.3 and the other one was 7.0.1.

After installing 7.0.1, the connection was successful. So it seems to be specifically for 7.0.3

**Comment by TimothyAlexisVass** [comment]
This was working on a different computer in our department and I noticed we were using different versions. I had DBeaver 7.0.3 and the other one was 7.0.1.

After installing 7.0.1, the connection was successful. So it seems to be specifically for 7.0.3
