### ISSUE TITLE
fetch all rows is not working v6.0.0 in MAC

### ISSUE THREAD

**Issue by krsbalu** [dbeaver/dbeaver#5974]
#### System information: 
- Operating system (distribution) and version -  MAC
- DBeaver version - 6.0.0
- Java version 1.8.0.151
- Additional extensions

#### Connection specification:
- Database name and version - any database
- Driver name - i use postgres, oracle , db2
- Do you use tunnels or proxies (SSH, SOCKS, etc)? none

#### Describe the problem you're observing: I cant use fetch all rows, but i ca use only next rows . its giving trouble for me. I tried changing shortcut key as well but no use.
What can fix this issue

**Comment by serge-rider** [comment]
Check confirmations settings:
![image](https://user-images.githubusercontent.com/6398845/58385074-5e74bc80-7ff3-11e9-9f7f-55e85e779c69.png)

**Comment by krsbalu** [comment]
Hey thank u.. This might help
