### ISSUE TITLE
oracle: unable to connect with user alias/proxy username[schemaname]

### ISSUE THREAD

**Issue by pdorio** [dbeaver/dbeaver#5976]
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise
- DBeaver version: 6.0.5

#### Connection specification:
- Database name and version: Oracle 11g

#### Describe the problem you're observing:

I'm trying to connect to one of my Oracle Databases.

With TOAD or FME I'm simply giving as login **my_username[my_schema]** but does not work with DBeaver.

In practice the content in parentheses is an alias or a user proxy

another syntax is used for aliases? e.g.: username@myschema or myschema/username ?

#### Include any warning/errors/backtraces from the logs

ORA-01017: invalid username/password; logon denied

**Comment by uslss** [comment]
cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket

**Comment by sae13** [comment]
hey hi

**Comment by brasio** [comment]
I have the same problem too. It seems that Dbeaver does not accept oracle proxy users, like my_proxyusername[my_schema]
