### ISSUE TITLE
SQL Formatter (workbench/j format) does not work anymore

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#5977]
#### System information: 
- Operating system: Linux Mint 19
- DBeaver version: 6.0.5
- Java version: 1.0.8 (Oracle)

Hi,
In preceding versions of DBeaver, I could format SQL in SQL Editor using the Workbench/j formatter, which was integrated for times.
But since DBeaver 6.0.5, Ctrl+Maj+F does not work anymore, and I can't find Workbench/j formatter in the SQL Format settings.

Did I miss something?

Thanks in advance for your help.

Cedric

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
