### ISSUE TITLE
 The nvarchar columns on the SQL Server appear to be 2 times larger. for Example nvarchar(20) --> nvarchar(40)

### ISSUE THREAD

**Issue by tarkandogan** [dbeaver/dbeaver#5981]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by AaronBastian** [comment]
same problem

**Comment by ahudelson** [comment]
**### System information:**

- Operating system (distribution) and version = macOS Majave 10.14.6
- DBeaver version = 6.1.4
- Java version = OpenJDK 1.8.0_222-b10
- Additional extensions

**### Connection specification:**

- Database name and version = MSSQL 2014
- Driver name = Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? = No

**### Describe the problem you're observing:**
nvarchar column metadata in DBeaver (character limit) appears to be double the actual character limit in the database columns.  This can be verified by connecting to the target database with both MSSQL Management Studio (shows correct character limits) and DBeaver (shows incorrect character limits)

**### Steps to reproduce, if exist:**
**### Include any warning/errors/backtraces from the logs**

**Comment by serge-rider** [comment]
I can't reproduce this. We actually calculate NVarchars length separately (with COLUMNPROPERTY function). There is a separate column "Bytes" which shows column length in bytes.
From my test env:
![image](https://user-images.githubusercontent.com/6398845/63533777-27407980-c516-11e9-9235-e73dfb369839.png)


Maybe this somehow depends on the particular server version.
We are using following query to read columns:
```sql
SELECT c.*,t.name as table_name,t.schema_id, COLUMNPROPERTY(c.object_id, c.name, 'charmaxlen') as char_max_length, dc.definition as default_definition,ep.value as description
FROM AdventureWorks2012_Data.sys.all_columns c
JOIN AdventureWorks2012_Data.sys.all_objects t ON t.object_id=c.object_id
LEFT OUTER JOIN AdventureWorks2012_Data.sys.default_constraints dc ON dc.parent_object_id=t.object_id AND dc.parent_column_id=c.column_id
LEFT OUTER JOIN AdventureWorks2012_Data.sys.extended_properties ep ON ep.class=1 AND ep.major_id=t.object_id AND ep.minor_id=c.column_id AND ep.name='MS_Description'WHERE t.object_id=TABLE_ID
ORDER BY c.object_id,c.column_id
```

You can execute this query by replacing TABLE_ID with real table ID (you can find it in table editor, field ID).
There are two different columns in this query: max_length and char_max_length. Please check their values.

**Comment by ahudelson** [comment]
Ok - I ran the query, and got the same result you did - "max_length" matches the metadata listed in the navigator view of columns.  However, when I view the same column in MSSQL Management Studio, the metadata and Length listed (when viewing column properties) is exactly half.  Interestingly, the "Size" listed in column properties matches what is shown in DBeaver.

![MSSQL-BLNDSETS](https://user-images.githubusercontent.com/29107790/63535829-fb060800-c4d7-11e9-8682-2fb53df25572.png)

**Comment by ahudelson** [comment]
My assumption is that the metadata is actually displaying the max length in bytes vs actual string length?

**Comment by serge-rider** [comment]
@ahudelson it shows both. See my screenshot above. "Length" is in chars, "Bytes" is in bytes.

**Comment by AaronBastian** [comment]
@serge-rider I can see that it shows both in the properties pane, but where it gets utterly confusing is showing the bytes in the database navigator pane:
![Screen Shot 2019-08-22 at 1 28 03 PM](https://user-images.githubusercontent.com/3698650/63540032-eed27880-c4e0-11e9-8b49-09cbc672e11d.png)
It is much more helpful to see the length here rather than the bytes.

**Comment by ahudelson** [comment]
Also, I don't even think that ^^ is correct.  Column properties in DBeaver show "Length" and "Bytes" the same = 30 

![Properties](https://user-images.githubusercontent.com/29107790/63540662-1d048800-c4e2-11e9-888f-32e2bd7ed827.png)

**Comment by serge-rider** [comment]
@ahudelson I see. So it must be something in SQL Server config or in incorrect max length reading.
I believe you are using DBeaver preconfigured driver `Microsoft JDBC Driver for SQL Server (MSSQL)`

- What is your SQL Server exact version?
- Could you execute the query I posted above to see what values are returned in max_length and char_max_length columns? To get table ID double-click on table and copy value of ID property.

**Comment by ahudelson** [comment]
SQL Server 13.0.1708

I ran the query and the values for the "DESCRIPT" column in the "BLNDSETS" table (the one that most of the screenshots show) and the max_length = 30 and the "char_max_length" = NULL

![descript1](https://user-images.githubusercontent.com/29107790/63550742-edad4580-c4f8-11e9-89ac-343f2b74f7b5.png)
![descript2](https://user-images.githubusercontent.com/29107790/63550743-edad4580-c4f8-11e9-85f5-84e76de5cb6d.png)

**Comment by serge-rider** [comment]
Thanks for details. By some reason your SQL Server doesn't return proper length in chars by using COLUMNPROPERTY function (although it is the only documented way to get it - as far as I know).
Anyway, I've added a workaround for this.

Please, check the fix in the Early Access version (https://dbeaver.io/files/ea).

**Comment by ahudelson** [comment]
I got 6.2.0 early build on my Mac and it looks like your workaround was a success!  Thanks for all your assistance.

![6 2 0](https://user-images.githubusercontent.com/29107790/63594994-9309fd00-c57d-11e9-89db-8c13a90881eb.png)

**Comment by AaronBastian** [comment]
I can also verify that this resolves the issue. Thanks so much!

**Comment by MariaMozgunova** [comment]
This issue is present for me. I downloaded the DBeaver community edition a few days ago. The nvarchar columns show twice the size compared to what I see when viewing column size from the Microsoft SQL Server Management Studio.

Is there any way to get the correct nvarchar columns size to show up?
