### ISSUE TITLE
[PostgreSQL] Show dependents triggers in functions properties

### ISSUE THREAD

**Issue by rbovard** [dbeaver/dbeaver#5982]
Following #5304, it would also be great to see dependents triggers in functions properties.

Thanks again for your work.

**Comment by serge-rider** [comment]
That's easy

**Comment by uslss** [comment]
verified

**Comment by rbovard** [comment]
Thanks a lot @serge-rider for the quick implementation!

Just a question: is it normal that the fields `table` and `schema` are empty?

![image](https://user-images.githubusercontent.com/4549666/59684312-0425e080-91da-11e9-8e11-b9952b47a4cf.png)

**Comment by rbovard** [comment]
Thanks a lot!
