### ISSUE TITLE
Don't use right alt key in editor shortcuts

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#5984]
#### System information: 
- Operating system (distribution) and version: Windows 10
- System language: polish
- DBeaver version: 6.0.4.201905052017
- Java version: 1.8.0_77
- Additional extensions: None

#### Describe the problem you're observing:

Right alt key is used to type various non-english characters. Some shortcuts however are binded by default to some actions and aren't even listed in General/Keys preferences, so I can't unbind them.

One example is Right Alt + e shortcut - it toggles horizontal scrollbar in editor, but it should insert polish _ę_ instead (in my case) - just like I would expect from text editor.

**Comment by serge-rider** [comment]
I'm quite sure that <kbd>CTRL+ALT+E</kbd> is the only shortcut which is bound to CTRL+ALT+Letter (or Right Alt) combination in DBeaver. It toggles word wrap mode in text editors.

I'll just change it to <kbd>CTRL+ALT+SHIFT+W</kbd>. Thanks for the bug report.

**Comment by uslss** [comment]
verified
