### ISSUE TITLE
High CPU usage when opening long clob

### ISSUE THREAD

**Issue by wazxse5** [dbeaver/dbeaver#5985]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04.2 LTS
- DBeaver version: 6.0.5
- Java version :
        openjdk version "1.8.0_212"
        OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
        OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
- Additional extensions

#### Connection specification:
- Database name and version: Oracle 12
- Driver name: ojdbc7-12.1.0.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I have a table which keeps history commands sent to the system. Commands are long jsons. Jsons are held in column of type clob. 
When in query result i click on any cell in column command, value of cell displays in right panel 'Value'. If **word wrapping** is on there is high (100%) singlethread cpu usage and whole dbeaver begins to lag and run slowly. When i click on another cell in different column (e.g datetime) everything starts to work normally.

**Comment by serge-rider** [comment]
Generally value panel is not supposed to be used with very long texts.
You could use separate editor (<kbd>shift+enter</kbd>) for long values.

However generally value view panel works fine with medium-size texts. Could you post an example of a text value which causes performance issues?
