### ISSUE TITLE
SQL server output crashes on huge output log (FR: use console view)

### ISSUE THREAD

**Issue by stefanon** [dbeaver/dbeaver#5986]
#### System information: 
- Linux Mint 19 Tara
- DBeaver 6.0.5 CE
- openjdk version "11.0.3" 

#### Connection specification:
- PostgreSQL 11.3
- Driver name PostgreSQL JDBC Driver 42.2.0.jre7

#### Describe the problem you're observing:

DBeaver freezes and then crashes closing without any error notification.

#### Steps to reproduce, if exist:
I've a function called when updating values in a 200K+ row table, that in several points uses 'RAISE NOTICE' statements to write infos to the server output panel, and when I do a full table uptdate this repeatedly make Dbeaver crash and die silently.

**Comment by serge-rider** [comment]
Thanks for the bug report.

We need to redesign current server output view.
We should use Eclipse console view for that. It is more handy and suitable for this.
Will do after 6.1 release. So labeling this as FR and as a bug.

For now just avoid opening console view whenever you expecting huge output.

**Comment by uslss** [comment]
verified
