### ISSUE TITLE
Feature question: selecting rows in the result panel

### ISSUE THREAD

**Issue by ZeusDeus** [dbeaver/dbeaver#5988]
Is it possible to replicate oracle sql developer behaviour In result panel in Dbeaver:
when you select a couple of cells in one row
![row](https://user-images.githubusercontent.com/49918855/58256442-aedfe600-7d77-11e9-95f3-d7f000335e9e.png)
and ctrl+click on the other row i want dbeaver to select the same columns in the other row
like this:
![want](https://user-images.githubusercontent.com/49918855/58256543-de8eee00-7d77-11e9-81c7-9f30f1f46894.png)
Now it behaves like this:
![now](https://user-images.githubusercontent.com/49918855/58256568-e8b0ec80-7d77-11e9-82dc-713d56987082.png)
thanks in advance!

**Comment by serge-rider** [comment]
This makes sense, thanks for proposal. And it is easy to implement.

I can't change <kbd>ctrl+click</kbd> behavior as a lot of people get used to the old behavior (extra single cell selection). 
So I'll make it <kbd>ctrl+alt+click</kbd>.

**Comment by ZeusDeus** [comment]
Great to hear! Thank you

**Comment by uslss** [comment]
verified

**Comment by ZeusDeus** [comment]
I've tested this feature and it works as intended BUT when diselecting already with ctrl + alt + click only one field diselects, not the whole row. Please fix!
