### ISSUE TITLE
Export: 1st line starts with ï»¿ (EF BB BF)

### ISSUE THREAD

**Issue by bobromeo** [dbeaver/dbeaver#5989]
*MS-windows server 2012 R2, dBeaver 6.0.5, Java 8u161
*MariaDB 15.1, Driver MariaDB (or.mariadb.jdbc:mariadb-java-client:RELEASE [1.5.5])
*No Warnings/Errors

After query in data grid> Export data ...> CSV> 
Open file with editor> Windows 1252
![afbeelding](https://user-images.githubusercontent.com/49475326/58259513-fd3fb580-7d74-11e9-9d45-b893678eba53.png)
In Hex:
![afbeelding](https://user-images.githubusercontent.com/49475326/58259713-5f98b600-7d75-11e9-8f76-3958b0b211bf.png)

**Comment by serge-rider** [comment]
Just turn off "Insert BOM" option:
![image](https://user-images.githubusercontent.com/6398845/58385159-b2cc6c00-7ff4-11e9-9bd7-5019f53e69b3.png)

**Comment by bobromeo** [comment]
Thx! Missed that one.
