### ISSUE TITLE
Postgres multiline comments are highlighted in a wrong way

### ISSUE THREAD

**Issue by snuyanzin** [dbeaver/dbeaver#5990]
#### System information: 
- Operating system (distribution) and version: Ubuntu 19.04
- DBeaver version: 6.0.5
- Java version: openjdk version "11.0.3" 
- Additional extensions

#### Connection specification:
- Database name and version: postgres 9.0.6
- Driver name:
- Do you use tunnels or proxies (SSH, SOCKS, etc) no

#### Describe the problem you're observing:
Syntax highlighting is wrong for query with multiline comments.

#### Steps to reproduce, if exist:
use query 
```
select 1 /* multiline comment
 * with nesting: /* nested block comment */
 select 2 */;
```
This type of comments is supported by postgres based on https://www.postgresql.org/docs/8.0/sql-syntax.html#SQL-SYNTAX-COMMENTS
It is executed ok but it is highlighted in a wrong way

**Comment by uslss** [comment]
reproducible
![image](https://user-images.githubusercontent.com/31996417/58373740-cd8eda00-7f3b-11e9-957a-553c6741b91b.png)

**Comment by serge-rider** [comment]
Umm, this is very non-standard. Nested multiline comments support will be more tricky than it looks like..

**Comment by ShadelessFox** [comment]
Support for nested comments was added for PostgreSQL and SQL Server.

**Comment by kseniiaguzeeva** [comment]
verified
