### ISSUE TITLE
Cannot successfully update existing or install new DBeaver Eclipse plugin 

### ISSUE THREAD

**Issue by sgarbarini** [dbeaver/dbeaver#5991]
#### System information: 
- Operating system: Xubuntu 18.04 / Linux 4.15.0-50-generic
- DBeaver version: (DBeaver IDE 6.0.5.201905192156)
- Java version: jdk1.8.0_171
- Eclipse version: Version: 2018-09 (4.9.0) Build id: 20180917-1800

#### Connection specification:
- Database name and version: N/A
- Driver name: N/A
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : N/A

#### Describe the problem you're observing:
Tried to update to latest version and got some incompatibility errors.  Unfortunately didn't write it down.  Decided to un-install and re-install.  Only option available now is "DBeaver IDE"... I think the update site used to offer various options:  Core, Generic, MS-SQL, etc.  Anyway, the reinstall gives the following error:

Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver IDE 6.0.5.201905192156 (org.jkiss.dbeaver.ide.feature.feature.group 6.0.5.201905192156)
  Missing requirement: DBeaver GIS Support 1.0.33.201905192156 (org.jkiss.dbeaver.data.gis 1.0.33.201905192156) requires 'osgi.bundle; org.jkiss.bundle.gis 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver Databases 1.0.0.201905192156 (org.jkiss.dbeaver.db.feature.feature.group 1.0.0.201905192156)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ext.mysql [2.1.94.201905192156,2.1.94.201905192156]
  Cannot satisfy dependency:
    From: DBeaver MySQL Support 2.1.94.201905192156 (org.jkiss.dbeaver.ext.mysql 2.1.94.201905192156)
    To: osgi.bundle; org.jkiss.dbeaver.data.gis 0.0.0
  Cannot satisfy dependency:
    From: DBeaver IDE 6.0.5.201905192156 (org.jkiss.dbeaver.ide.feature.feature.group 6.0.5.201905192156)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.db.feature.feature.group [1.0.0.201905192156,1.0.0.201905192156]

#### Include any warning/errors/backtraces from the logs
!ENTRY org.eclipse.equinox.p2.operations 4 10053 2019-05-23 15:05:58.486
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 10053 2019-05-23 15:05:58.486
!MESSAGE Cannot complete the install because one or more required items could not be found.
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.486
!MESSAGE Software being installed: DBeaver IDE 6.0.5.201905192156 (org.jkiss.dbeaver.ide.feature.feature.group 6.0.5.201905192156)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.486
!MESSAGE Missing requirement: DBeaver GIS Support 1.0.33.201905192156 (org.jkiss.dbeaver.data.gis 1.0.33.201905192156) requires 'osgi.bundle; org.jkiss.bundle.gis 0.0.0' but it could not be found
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2019-05-23 15:05:58.486
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.486
!MESSAGE From: DBeaver Databases 1.0.0.201905192156 (org.jkiss.dbeaver.db.feature.feature.group 1.0.0.201905192156)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.486
!MESSAGE To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ext.mysql [2.1.94.201905192156,2.1.94.201905192156]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2019-05-23 15:05:58.486
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.486
!MESSAGE From: DBeaver MySQL Support 2.1.94.201905192156 (org.jkiss.dbeaver.ext.mysql 2.1.94.201905192156)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.486
!MESSAGE To: osgi.bundle; org.jkiss.dbeaver.data.gis 0.0.0
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2019-05-23 15:05:58.486
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.486
!MESSAGE From: DBeaver IDE 6.0.5.201905192156 (org.jkiss.dbeaver.ide.feature.feature.group 6.0.5.201905192156)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.486
!MESSAGE To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.db.feature.feature.group [1.0.0.201905192156,1.0.0.201905192156]

!ENTRY org.eclipse.equinox.p2.operations 4 10053 2019-05-23 15:05:58.488
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 10053 2019-05-23 15:05:58.488
!MESSAGE Cannot complete the install because one or more required items could not be found.
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.488
!MESSAGE Software being installed: DBeaver IDE 6.0.5.201905192156 (org.jkiss.dbeaver.ide.feature.feature.group 6.0.5.201905192156)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.488
!MESSAGE Missing requirement: DBeaver GIS Support 1.0.33.201905192156 (org.jkiss.dbeaver.data.gis 1.0.33.201905192156) requires 'osgi.bundle; org.jkiss.bundle.gis 0.0.0' but it could not be found
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2019-05-23 15:05:58.488
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.488
!MESSAGE From: DBeaver Databases 1.0.0.201905192156 (org.jkiss.dbeaver.db.feature.feature.group 1.0.0.201905192156)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.488
!MESSAGE To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ext.mysql [2.1.94.201905192156,2.1.94.201905192156]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2019-05-23 15:05:58.488
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.488
!MESSAGE From: DBeaver MySQL Support 2.1.94.201905192156 (org.jkiss.dbeaver.ext.mysql 2.1.94.201905192156)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.488
!MESSAGE To: osgi.bundle; org.jkiss.dbeaver.data.gis 0.0.0
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2019-05-23 15:05:58.488
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.488
!MESSAGE From: DBeaver IDE 6.0.5.201905192156 (org.jkiss.dbeaver.ide.feature.feature.group 6.0.5.201905192156)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2019-05-23 15:05:58.488
!MESSAGE To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.db.feature.feature.group [1.0.0.201905192156,1.0.0.201905192156]

**Comment by steftux** [comment]
Hi. same error appearing on windows and with eclipse 4.11 (2019-03) - any hints on the following requirements?

_Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver IDE 6.0.5.201905192156 (org.jkiss.dbeaver.ide.feature.feature.group 6.0.5.201905192156)
  Missing requirement: DBeaver GIS Support 1.0.33.201905192156 (org.jkiss.dbeaver.data.gis 1.0.33.201905192156) requires 'osgi.bundle; org.jkiss.bundle.gis 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver Databases 1.0.0.201905192156 (org.jkiss.dbeaver.db.feature.feature.group 1.0.0.201905192156)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ext.mysql [2.1.94.201905192156,2.1.94.201905192156]
  Cannot satisfy dependency:
    From: DBeaver MySQL Support 2.1.94.201905192156 (org.jkiss.dbeaver.ext.mysql 2.1.94.201905192156)
    To: osgi.bundle; org.jkiss.dbeaver.data.gis 0.0.0
  Cannot satisfy dependency:
    From: DBeaver IDE 6.0.5.201905192156 (org.jkiss.dbeaver.ide.feature.feature.group 6.0.5.201905192156)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.db.feature.feature.group [1.0.0.201905192156,1.0.0.201905192156]_

**Comment by serge-rider** [comment]
Thanks for the bug report. It is a bug in Eclipse plugin bundle packaging.
We reworked Eclipse plugin publishing so now it will have only one feature (DBeaver IDE). Optional extension may be added to it later.

Fixed update site is now at https://dbeaver.io/files/ea/update/dbeaver/ (please check).

I'll re-publish real update site today or tomorrows once it will be tested.

**Comment by uslss** [comment]
verified
