### ISSUE TITLE
PostgreSQL - Generated DDL doesnt contain columns' comments

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#5992]
Option to generate table DDL doesnt include comments, just table structure and indices 

![image](https://user-images.githubusercontent.com/5410448/58307811-16da0f00-7e00-11e9-8600-572fa6cb0fba.png)

double clicking on table via Navigator and selecting DDL shows comments.

Can right click option have comments as well ?

**Comment by serge-rider** [comment]
You can get full table DDL in the table editor (tab "DDL").
"Generate SQL" command generates DDL for object itself only.
