### ISSUE TITLE
Menu List Showing Multiple times

### ISSUE THREAD

**Issue by ramrasi** [dbeaver/dbeaver#5993]
I m uinf Fedora 30 with Mate Desktop
Useing Dbeaver with Postgres Session Menu List showing double times....

![image](https://user-images.githubusercontent.com/6615196/58315071-6d5e4200-7e2e-11e9-903d-4ca22b425d2c.png)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
