### ISSUE TITLE
Show more informative error message for unknown hostname

### ISSUE THREAD

**Issue by ondrejzacha** [dbeaver/dbeaver#5996]
When connecting to a database with an unknown hostname, DBeaver shows only a generic connection error – example:

![image](https://user-images.githubusercontent.com/28254773/58323271-cd032000-7e23-11e9-9b24-956047aa4931.png)

I would like to get a more informative error message, e.g. `R`'s DBI library gives the following error for the same issue:
> could not connect [user]@[host]:[port] on dbname "[dbname]": could not translate host name "[host]" to address: nodename nor servname provided, or not known

**System information:**
DBeaver 6.0.5
MacOS 10.14.5

**Comment by serge-rider** [comment]
What database/driver is it?

**Comment by ondrejzacha** [comment]
This was PostgreSQL.

**Comment by uslss** [comment]
cannot reproduce it now.
if issue is still actual for you - feel free to reopen the ticket
