### ISSUE TITLE
Feature Request: Open Output Window Automatically

### ISSUE THREAD

**Issue by jsmith0103** [dbeaver/dbeaver#5998]
Would like to request that the output window open automatically if a message populates. Currently using DBeaver 6.0.5 with PostgreSQL 11.3.

Example:
RAISE NOTICE '%','Test message';

A message is output, but I don't know that unless I open the Output window manually using Ctrl Shift O (Windows 10).

**Comment by serge-rider** [comment]
Will be implemented in #10683
