### ISSUE TITLE
[Bug] 6.0.5 ERD editor dark theme issues

### ISSUE THREAD

**Issue by Lightfire228** [dbeaver/dbeaver#6000]
When using the default DBeaver/Eclipse Dark theme, the ERD editor shows column names in black on dark grey, which is very hard to read.  

This was introduced in 6.0.5.  Performing a clean install of 6.0.4, the bug does not occur, but performing a clean install of 6.0.5, it does.  By a clean install, I mean running the DBeaver uninstaller, then deleting the `~/.dbeaver` folder.

#### Steps to reproduce
0. Install DBeaver 6.0.5
0. Navigate to Window > Preferences > General > Appearance, and set Theme to Dark (I'm using the Windows variant, but it happens on all variants on my machine)
0. Restart DBeaver
0. Create a new Connection to an existing database
0. In the Database Navigator, navigate to [Connection Name] > [Database name] > Schemas > [Schema name], right click, and click View Diagram
0. The generated ERD will have unreadable column names

#### Example images
6.0.5:
![image](https://user-images.githubusercontent.com/15241322/58357533-321d3c80-7e49-11e9-8fd2-cd0e90a28adc.png)
6.0.4:
![image](https://user-images.githubusercontent.com/15241322/58357554-43fedf80-7e49-11e9-8ca2-84808d214ba2.png)

#### System information: 
- Operating system (distribution) and version
  - Windows 10 Pro, build 17763
- DBeaver version
  - 6.0.5, standalone + jre
- Java version
  - Prepackaged JRE
- Additional extensions
  - None

#### Connection specification:
- Database name and version
  - PostgreSQL 9.5.0
- Driver name
  - PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
  - No

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
