### ISSUE TITLE
SQL Server Auto Increment

### ISSUE THREAD

**Issue by DCM314** [dbeaver/dbeaver#6001]
New version 6.0.5 no longer seems to support creation of an IDENTITY column for new tables that auto increment.

**Comment by adbakke** [comment]
I'm just wondering why this is considered a "feature request" and not a bug? Curious how you folks label things.

**Comment by serge-rider** [comment]
@adbakke as far as I remember this feature (IDENTITY columns creation) was never supported. That's why it is FR but not a bug report.

**Comment by uslss** [comment]
verified. IDENTITY columns creation is supported now.
![image](https://user-images.githubusercontent.com/31996417/61932190-674e2400-af8b-11e9-8cdd-27f5c76b4ad8.png)
