### ISSUE TITLE
Oracle auto complete not work properly after update to 6.0.5

### ISSUE THREAD

**Issue by shilkazx** [dbeaver/dbeaver#6005]
#### System information: 
- Operating system (distribution) and version Archlinux x64
- DBeaver version 6.0.5
- Java version jdk 12
- Additional extensions

#### Connection specification:
- Database name and version Oracle 12c
- Driver name jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
After update from 6.0.4 to 6.0.5, the auto complete of table column name when writing SQL is gone. But the auto complete of table name still work.

e.g. when typing the sql below, old version would pop up assist window at the beginning of each word typing(select, b.column_a, from, dual), but new version do not give suggestion when typing b.column_a, but still offer suggestion when typeing key word and table names.

select b.column_a
from dual b

**Comment by ZeusDeus** [comment]
same problem, but I can't even get it to work on earlier versions, it just doesn't work with aliases, only works when full table name is specified

**Comment by uslss** [comment]
Ticket closed.
Issue isn't reproducible on 6.1.2
