### ISSUE TITLE
generateSQL does not appear in version 6.0.5

### ISSUE THREAD

**Issue by miguelsc82** [dbeaver/dbeaver#6007]
MAC OS 6.0.5

The option Generate SQL as a contextual menu is no longer present.

**Comment by serge-rider** [comment]
Can't  reproduce. What exactly context menu do you mean?

**Comment by miguelsc82** [comment]
Hi. In the contextual menu on "Results".  Please see photo attached
![Screenshot 2019-05-28 at 14 27 46](https://user-images.githubusercontent.com/51085944/58477862-e6bea300-8154-11e9-8012-ad2533cdf497.png)

**Comment by serge-rider** [comment]
This was already fixed. You can check this in Early Access version (https://dbeaver.io/files/ea).

**Comment by miguelsc82** [comment]
Thanks. I can see it fixed in EA version
