### ISSUE TITLE
no schemes no tables from server connection

### ISSUE THREAD

**Issue by 287852793** [dbeaver/dbeaver#6010]
#### System information: 
- windows10 64bit
- DBeaver version 6.0.5
- Java version jdk1.8_11

#### Connection specification:
- mysql8 / hive2 ... on server docker images
- almost try all version drivers
- no proxies 

#### Describe the problem you're observing:
when I create a connection from server docker image database
no schemes and table shown on the connection trees

but I can query datas from server connection by sql session
like this ---->
![image](https://user-images.githubusercontent.com/42363487/58449490-54130980-813e-11e9-85d3-ab397343a686.png)

local connections has no problems
(my local mysql version is  mysql56 )

#### Include any warning/errors/backtraces from the logs
no warnings no errors

HELP .......

**Comment by serge-rider** [comment]
Wow, this looks weird.
What MySQL server version it is?
Are there other schemas in main toolbar drop-down besides `mysql`?

DBeaver uses query `show databases` to load schema list. What happens if you execute this query in SQL editor?

**Comment by 13871591944** [comment]
> Wow, this looks weird.
> What MySQL server version it is?
> Are there other schemas in main toolbar drop-down besides `mysql`?
> 
> DBeaver uses query `show databases` to load schema list. What happens if you execute this query in SQL editor?

server mysql version : mysql  Ver 15.1 Distrib 10.3.14-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

![image](https://user-images.githubusercontent.com/42363487/58464475-568a5900-8168-11e9-878b-d9c2dcabf7be.png)

I tried to use DBeaver 6.0.5  &  5.3.5 ，the same problem occured
maybe this related to mysql version， but my server has no mysql56 to be tested....

HELP...

**Comment by serge-rider** [comment]
I see. There are no non-system schemas in your remote database (both mysql and information_schema are system catalogs which cannot be directly used by users).
Just create a new schema.

In order to see system schemas turn this on:
![image](https://user-images.githubusercontent.com/6398845/58465082-a0127e00-813f-11e9-8865-1be54a9ca7fe.png)

**Comment by 13871591944** [comment]
> I see. There are no non-system schemas in your remote database (both mysql and information_schema are system catalogs which cannot be directly used by users).
> Just create a new schema.
> 
> In order to see system schemas turn this on:
> ![image](https://user-images.githubusercontent.com/6398845/58465082-a0127e00-813f-11e9-8865-1be54a9ca7fe.png)

SOLVED!!! Thank you very, very much~~~~

my connection for  server hive2 has the same problem 
I want to show the tables on left tree panel   
I tried to turn on "Show system objects" & "Show utility objects" for  hive connection
but still no tables to shown

This is the first time I tried to use hive , I don't know much about the hive connection 
Can hive tables be displayed ??

![image](https://user-images.githubusercontent.com/42363487/58466605-8b98aa80-816c-11e9-9fa5-3c8e2fc629f1.png)


Ask for advice.

**Comment by 0iras0r** [comment]
> > I see. There are no non-system schemas in your remote database (both mysql and information_schema are system catalogs which cannot be directly used by users).
> > Just create a new schema.
> > In order to see system schemas turn this on:
> > ![image](https://user-images.githubusercontent.com/6398845/58465082-a0127e00-813f-11e9-8865-1be54a9ca7fe.png)
> 
> SOLVED!!! Thank you very, very much~~~~
> 
> my connection for server hive2 has the same problem
> I want to show the tables on left tree panel
> I tried to turn on "Show system objects" & "Show utility objects" for hive connection
> but still no tables to shown
> 
> This is the first time I tried to use hive , I don't know much about the hive connection
> Can hive tables be displayed ??
> 
> ![image](https://user-images.githubusercontent.com/42363487/58466605-8b98aa80-816c-11e9-9fa5-3c8e2fc629f1.png)
> 
> Ask for advice.

Hello everyone!
I experiencing the same issue... it seems a problem of permission about the user..
maybe the user needs to read something like information schema... or permission about metastore... any experienced hive user here?

I am able to interact with tables... but they are not shown on the left panel.

Regards

**Comment by Henry-Jones** [comment]
Hello,

i have the same problem (tables not showing), but in my case the underlying database engine (4.x) might be the problem, as there is no Information_schema db in this version.

Is there a way to connect to such an antique db or need I upgrade the database engine (which must be checked with the supplier of the end application of course) ?

**Comment by 13871591944** [comment]
Hello
Hive data connections have not been used recently, and the issues remain unresolved
However, the SQL query can still be used
I don't think it's about the database engine, it's about the version of the database, but I didn't test it
Maybe I should ask the administrator again

**Comment by serge-rider** [comment]
@Henry-Jones what database do you use? MySQL?

@13871591944 What hive server version do you use? This is how it look in my test env (AWS EMR Hive):
![image](https://user-images.githubusercontent.com/6398845/62940265-7a5a5400-bdd3-11e9-8fa7-f7b6135d58ca.png)

**Comment by Henry-Jones** [comment]
@serge-rider : Yes, MySQL in version 4.x (exact value of x not available right now). Supplier states that it's not possible to update to newer version :(

**Comment by serge-rider** [comment]
Could you try it in Early Access version (https://dbeaver.io/files/ea) and driver `MySQL (Old)`

**Comment by Henry-Jones** [comment]
First thing in the morning, when I'm back at work.

**Comment by Henry-Jones** [comment]
Hello,

now I get the following message and are unable to open the connection at all. The same message appears when I use the former "MySQL" connector without the "(old)" addition:

![message](https://user-images.githubusercontent.com/9108755/63007473-feb6e080-be80-11e9-9965-219cd845364d.png)

Here is the logfile: [log.zip](https://github.com/dbeaver/dbeaver/files/3500504/log.zip)

**Comment by 0iras0r** [comment]
> @Henry-Jones what database do you use? MySQL?
> 
> @13871591944 What hive server version do you use? This is how it look in my test env (AWS EMR Hive):
> ![image](https://user-images.githubusercontent.com/6398845/62940265-7a5a5400-bdd3-11e9-8fa7-f7b6135d58ca.png)

My version of Apache Hive is 3.1.0 (included in the HDP Hortonworks Platform)

**Comment by serge-rider** [comment]
@13871591944  Is it still reproducible in 6.2?

**Comment by 13871591944** [comment]
@serge-rider Yes, as in version 6.0

**Comment by serge-rider** [comment]
Agreed. Now it is very hard to understand what this ticket about.
@Henry-Jones please create new ticket (you can refer on this one). 

@13871591944 Please attach error/debug log files (if possible) - https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by uslss** [comment]
there is no updates more than a month. ticket closed
