### ISSUE TITLE
Oracle export timestamp column to TXT file

### ISSUE THREAD

**Issue by NullpointerForever** [dbeaver/dbeaver#6011]
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise
- DBeaver version: 6.0.5
- Java version: 1.8.0_77-b03
- Additional extensions

#### Connection specification:
- Database name and version: Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
- Driver name: oracle.jdbc.OracleDriver (12.1.0.2.0) from ojdbc7.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
After exporting to TXT file the timestamp columns are cropped. Example:
```
|TIMESTAMP_TEST|
|--------------|
|2012-05-23 00:|
```
On result grid format of timestamp is correct. Export to other file formats is also correct.

#### Steps to reproduce, if exist:
Export to TXT file with TIMESTAMP(6) type column.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
