### ISSUE TITLE
I can not edit a record in the table v6.0.5

### ISSUE THREAD

**Issue by osanmartinp** [dbeaver/dbeaver#6017]
#### System information: 
- Operating system (distribution) and version MAC
- DBeaver version 6.0.5
- Java version 1.8

#### Connection specification:
- Driver name Oracle 7

#### Describe the problem you're observing:
I can not edit a record in the table:
![image](https://user-images.githubusercontent.com/1796018/58498891-018d1980-814d-11e9-82e2-2a81826cc280.png)

**Comment by uslss** [comment]
Hi @osanmartinp ,
thanks for the bug report.
It seems that your issue duplicates #5957  that was already fixed and could be tested in EA version (https://dbeaver.io/files/ea/). Please, let us know if it doesn't resolve your problem.

**Comment by quiescer** [comment]
I had the same issue and the updated version (6.1.0) works for me.

**Comment by Zardoz89** [comment]
This is happening on DBeaver 6.0.5.201905192012 (linux , with Oracle JDK 1.8.0_191 and OpenJDK 11.0.3) connecting to Oracle databases.

Tested with :
* Oracle 12 driver (ojdbc7-12.1.0.2.0)
    * Oracle 12 database -> OK
    * Oracle 11 databases -> Can't edit cells or add new rows. However, doing a simple UPDATE table SET X... works fine
* Oracle 11 driver (ojdbc6-11.2.0.4)
    * Oracle 11 databases -> Can't edit cells or add new rows. However, doing a simple UPDATE table SET X... works fine
    * Oracle 10 databases -> Same issue
    * Oracle 9 databases -> Ok
