### ISSUE TITLE
File not behaving as SQL when being renamed to .sql

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#6018]
#### System information: 
- Operating system (distribution) and version: mac
- DBeaver version: 6.0.5

#### Describe the problem you're observing:
Having a file named file.sql.old - you cannot choose a connection nor the syntax is recognized as an SQL file - which is perfectly fine.
However, after renaming the file to file.sql while the file is still open in editor, the file is still treated as ".old" meaning you still cannot choose a connection nor the syntax is highlighted.

#### Steps to reproduce, if exist:
See above

#### Workaround
Close and re-open the file

#### Expected Behavior
Upon rename of a file to .sql it should be treated as an SQL file as if I just opened it

**Comment by uslss** [comment]
cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket

**Comment by pyrocks** [comment]
@uslss I just reproduced it with latest version, very easily. For some reason I don't have the option to reopen the issue... please reopen it.

open a file names whatever.old
right click -> rename
change extension to .sql
file is not recognized as standard sql
![image](https://user-images.githubusercontent.com/18515297/88187196-e62d7980-cc3e-11ea-8986-2718c30ce2e9.png)

thanks.

**Comment by pyrocks** [comment]
@serge-rider I don't know why uslss don't see my messages. I don't have the option to reopen. This is still relevant.

**Comment by pyrocks** [comment]
thanks.

**Comment by uslss** [comment]
@pyrocks 
as for me, there is no rename option at context menu for non-sql file
![image](https://user-images.githubusercontent.com/31996417/92727255-7ce10180-f377-11ea-982b-2200c1eb21f2.png)
am i doing something wrong?

**Comment by pyrocks** [comment]
When the file is under an active project - I do have this option:
![image](https://user-images.githubusercontent.com/18515297/92739138-3e524380-f385-11ea-87cd-89ca56e118d3.png)

When opening an arbitrary file not under the project - you're right, the option is not there:
![image](https://user-images.githubusercontent.com/18515297/92739476-9b4df980-f385-11ea-9d81-2706f4c165a0.png)

**Comment by serge-rider** [comment]
Fixed.
Editor will be reopened.

**Comment by uslss** [comment]
verified
