### ISSUE TITLE
PostgreSQL boolean value displayed wrong (false instead of true) in set-returning function (ST_IsValidDetail)

### ISSUE THREAD

**Issue by andywicht** [dbeaver/dbeaver#6020]
#### System information: 
- Operating system: Win 10
- DBeaver version: 5.0.5
- Java version: jdk-11.0.2

#### Connection specification:
- Database name and version: PostgreSQL 11.3.1 with PostGIS 2.5.2
- Driver name: PostgreSQL

#### Describe the problem you're observing:
The result value 'true' is displayed as 'false' in grid view. ST_IsValidDetail is a set-returning PostGIS function.
![grid](https://user-images.githubusercontent.com/21099522/58543649-268e9480-8200-11e9-8e69-40a1fda8b3d6.png)

The text output shows the correct result (same as result directly obtained by running the query in psql shell).
![text](https://user-images.githubusercontent.com/21099522/58543652-28f0ee80-8200-11e9-9444-343253a9173f.png)

#### Steps to reproduce, if exist:

```sql
SELECT ST_IsValid(geom),
       ST_IsValidDetail(geom),
       ST_IsValidReason(geom)
FROM (SELECT ST_GeomFromText('POLYGON((464970 6700000, 464980 6700000, 464980 6700000, 464980 6700010, 464970 6700010, 464970 6700000))', 3857) AS geom) AS foo;
```

**Comment by serge-rider** [comment]
Thanks for the bug report.
It was caused by incorrect boolean value parser in PostgreSQL struct data type handler.

**Comment by uslss** [comment]
verified
