### ISSUE TITLE
Corrupted display

### ISSUE THREAD

**Issue by nmadham** [dbeaver/dbeaver#6021]
![image](https://user-images.githubusercontent.com/16705400/58553725-a78b6300-81e3-11e9-9aea-7495dc14e76e.png)

Please see the attached image. "Connections toolbar" has been repeated thrice, I tried to fix it by updating the Dbeaver to the latest 6.0.5 version and also resetting the perspective but NO LUCK.

Can someone please review it.

**Comment by tati-kru** [comment]
Unfortunately, it is known Eclipse issue. Please, reset UI settings to fix this (Menu >> File >> Reset UI settings).
<img width="295" alt="Screenshot 2019-05-29 at 15 37 57" src="https://user-images.githubusercontent.com/30336552/58557837-04107180-8228-11e9-9550-55b94b684b73.png">

**Comment by nmadham** [comment]
Thanks,
