### ISSUE TITLE
The data does not appear in the grid option only in the text option

### ISSUE THREAD

**Issue by AnitaChiele** [dbeaver/dbeaver#6022]
#### System information: 
- Operating system (distribution) and version:
OS: Fedora 29 TwentyNine
Kernel: x86_64 Linux 5.0.16-200.fc29.x86_64
DE: Cinnamon 4.0.10
WM: Muffin

- DBeaver version:
6.0.5

- Java version:
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

- Additional extensions: -

#### Connection specification:
This not apply because its happen allways.

#### Describe the problem you're observing:
I can not view the data in grid mode. By clicking on the Grid icon it appears quickly and then it goes away.
You can see the data in the column with f7, you can also use the arrow keys to navigate between these results and see the others.

Log and images are in google drive, in the images will also have the mysql workbench only to demonstrate that there are data in the table.

#### Steps to reproduce, if exist:
Just click the Grid icon in a table.

#### Include any warning/errors/backtraces from the logs:
https://drive.google.com/drive/folders/1M3qT7g3IZCkia0G_jfrqreC55VDbQoKu?usp=sharing

**Comment by joseph8th** [comment]
Same issue. Linux Mint 19 with Mate DE and Oracle JDK 11.0.2.

Grid data appears until I try to click inside the panel (anywhere). Then it goes blank. Only text view works.

**Comment by hptsys** [comment]
Same. Ubuntu 18.04 Mate, Java SE 1.8.0_201,DBeaver v6.1.0
Grid view:
![image](https://user-images.githubusercontent.com/52942149/61259544-04f06900-a7be-11e9-8762-ae300f9cdc69.png)
Same table text view (content smudged)
![dbeaver_text_view](https://user-images.githubusercontent.com/52942149/61259678-9069fa00-a7be-11e9-8198-db086d86f2cf.png)

**Comment by slamtrooper** [comment]
I ran into this as well. Check if the solution referenced in #5854 fixes this for you.

**Comment by AnitaChiele** [comment]
@slamtrooper that's it, work for me!

I executed this command and started dbeaver in the terminal:
`$ export GTK_IM_MODULE=ibus`

Just for check if set:
`$ echo $export GTK_IM_MODULE`

And execute in terminal:
`$ dbeaver`

Thank you!
