### ISSUE TITLE
BEGIN alias is not working for MySQL transactions

### ISSUE THREAD

**Issue by lazb** [dbeaver/dbeaver#6023]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro 1809 Build 17763.503
- DBeaver version 6.0.5

#### Connection specification:
- Database name and version MySQL 5.5.62
- Driver name MySQL (mysql:mysql-connector-java:RELEASE [5.1.44]
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes, just SSH to the Docker instance.

#### Describe the problem you're observing:

Trying to execute the transaction with BEGIN alias would cause a syntax error.

#### Steps to reproduce, if exist:

This query will work:

```
START TRANSACTION;
SELECT id FROM pm_acl_entries WHERE id = 1;
COMMIT;
```

This query will not work and it will throw syntax error:

```
BEGIN;
SELECT id FROM pm_acl_entries WHERE id = 1;
COMMIT;
```

> SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT id FROM pm_acl_entries WHERE id = 1;
> COMMIT' at line 2

**Comment by serge-rider** [comment]
Thanks for the bug report. 
It was a bug in MySQL dialect definition (BEGIN was treated as anonymous SQL block begin)

**Comment by lazb** [comment]
Thanks, that was fast :)

**Comment by uslss** [comment]
verified
