### ISSUE TITLE
SYS and SYSTEM objects are not visible in Oracle Database while connected as SYS

### ISSUE THREAD

**Issue by dasamitkumar** [dbeaver/dbeaver#6024]
#### System information: 
- Operating system (distribution) and version - MacOS 10.14
- DBeaver version - 6.0.5

#### Connection specification:
- Database name and version - Oracle 11.2

#### Describe your question:
While I am connected as SYS to the Oracle Database, the Left pane which provides drop-down of the objects does not show the SYS, SYSTEM and other system related users.

**Comment by serge-rider** [comment]
You need to enable "Show system objects" option:
![image](https://user-images.githubusercontent.com/6398845/58694150-034c1c80-839b-11e9-8282-aed3820095cc.png)

**Comment by dasamitkumar** [comment]
Thanks for the solution.

**Comment by MichaelMih** [comment]
Now it has moved to: Connection right-click -> Connection view... -> Show system objects
