### ISSUE TITLE
Advanced paste does not copy NULLs in columns of type DATE

### ISSUE THREAD

**Issue by negora** [dbeaver/dbeaver#6026]
#### System information: 
- Operating system (distribution) and version: Debian 9.9.
- DBeaver version: 6.0.5.201905192012.
- Java version: 1.8.0-212.
- Additional extensions: none.

#### Connection specification:
- Database name and version: PostgresSQL 9.6.
- Driver name: org.postgresql.Driver.
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

#### Describe the problem you're observing:

The problem occurs under the following circumstances: In the `Data` tab of any table, you copy at least one row that contains a column of type `DATE`, and that is set to `NULL`. Then, when you open the context menu and choose `Advanced paste`, the value for that column is pasted as an empty string instead of as a `NULL`.

When you click `Save`, the server returns an error because you are passing an empty string for a column for which the server expects a value of type `DATE` or `NULL`.

This same error also occurs in columns of type `TIMESTAMP WITHOUT TIME ZONE`. And I guess that also in other temporal types.

Thank you.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified for Date, Timestamp types
