### ISSUE TITLE
Writing a new preview plugin for BLOBs?

### ISSUE THREAD

**Issue by Darker** [dbeaver/dbeaver#6027]
I was trying to find a tutorial on writing DBeaver plugin, but couldn't find any. I would like to write a plugin that adds new preview format for BLOB fields. I know that DBeaver supports some image types in blob field, so I'd like to add a plugin that allows preview of a different image format.

Is that possible in some reasonable time (weekend project)? The format in question is binary ppm, so parsing is easy, I just need a way to do the plugin to render it in the value field.

**Comment by serge-rider** [comment]
Yes, this can be done as a weekend project. But you have to know Java + some knowledge of Eclipse platform would be a good benefit.

Generally DBeaver plugins are regular Eclipse (or OSGI) plugins. You could try to copy-paste existing plugin to see how it works.
See https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse or https://github.com/dbeaver/dbeaver/wiki/Develop-in-IDEA for dev environment setup instructions.

You can use plugin <a href="https://github.com/dbeaver/dbeaver/tree/devel/plugins/org.jkiss.dbeaver.ui.editors.image">v</a> as an example for a new plugin.
