### ISSUE TITLE
ability to send json query to a Mongo replica node

### ISSUE THREAD

**Issue by antonmos** [dbeaver/dbeaver#603]
Currently, I am able to connect and execute SQL queries.
However, when trying to execute a native json query like db.collection.findOne()
I get the following error:

> com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector. Client view of cluster state is {type=REPLICA_SET, servers=[{address=foo-a1.mongolab.com:44444, type=REPLICA_SET_SECONDARY, roundTripTime=32.7 ms, state=CONNECTED}]

**Comment by uslss** [comment]
seems to be fixed.
if the issue still actual for you, feel free to reopen the ticket
