### ISSUE TITLE
Map viewer CRS 4326 default for longitude latitude is inverted

### ISSUE THREAD

**Issue by pfazzino** [dbeaver/dbeaver#6030]
When using CRS 4326 the rendering is inverting longtitude and latitude and treating geometry fields as latitude longitude. This default should be reverted to match the CRS selction dialog

![image](https://user-images.githubusercontent.com/1869459/58685828-df75e000-8374-11e9-975b-a08859a235c2.png)

Also related, the flip latitude/longitude coordinates option is not preserved requiring this option to be selected everytime a query or even new geometry column is selected in the result set.

**Comment by uslss** [comment]
verified
