### ISSUE TITLE
Export results to excel very slowly

### ISSUE THREAD

**Issue by shengjhen** [dbeaver/dbeaver#6031]
#### System information: 
- Operating system (distribution) and version Window 10
- DBeaver version 6.0.5
- Java version openjdk-1.8.0
- Additional extensions Extension Office

#### Connection specification:
- Database name and version: Oracle 11g
- Driver name: ojdbc6.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
Use Extension Office to export result to excel is very slowly,the export process didn't consider defaultRowPrefetch parameter.

**Comment by serge-rider** [comment]
Does it work slowly only for XLSX format or for any data export format?

**Comment by shengjhen** [comment]
> Does it work slowly only for XLSX format or for any data export format?

only for XLSX format

**Comment by uslss** [comment]
verified
