### ISSUE TITLE
Query Result editor Version 6.0.5.201905192012

### ISSUE THREAD

**Issue by mmislablum** [dbeaver/dbeaver#6033]
In the current Community Version aren't available the buttom SAVE, CANCEL, SCRIPT, ADD ROW, DUPLICATE ROW, DELETE ROW and I can't edit a field in a Oracle table where I have edit rights.

Please fix this bug, I use a lot your software! I wonderful!!

**Comment by uslss** [comment]
Hi @mmislablum ,
thanks for the bug report.
It seems that your issue duplicates #5957 that was already fixed and could be tested in EA version (https://dbeaver.io/files/ea/). Please, let us know if it doesn't resolve your problem.
Ticket will be closed as duplicate. If issue isn't fixed feel free to reopen the ticket.
