### ISSUE TITLE
How to escape special characters in database password

### ISSUE THREAD

**Issue by alec-ngo** [dbeaver/dbeaver#6034]
#### System information: 
- redhat 7.5
- DBeaver Community Edition 6.0.3

#### Connection specification:
- MS SQL Server 2017

#### Describe your question:

I'm getting a "login failed for user..." error when connecting to MS SQL Server db. I suspect it is due to the fact that the password contains '/' or '$' characters. While I don't believe MS SQL regards these as special characters, I suspect dbeaver may regard / or $ as special characters and is escaping them. 

The reason why I suspect this is because I have no issue connecting to the same db via a python script.

Example password with / and $ chars:      Abbc/$a9aa$

**Comment by Ventals** [comment]
The same issues with PostgreSQL

*Password contains `(` and `)` symbols

**Comment by supahcraig** [comment]
Same in Oracle with & when doing ALTER USER IDENTIFIED BY to change password.   The trick for Oracle is to SET DEFINE OFF because it thinks the & is a prompt for a substitution variable.    Also wrapping the password in quotes can help in some cases.

**Comment by akilovich** [comment]
Hello, @alec-ngo @Ventals @supahcraig. Sorry for the late response. I can not reproduce it against 7.2.0. Is it still actual for you?

**Comment by uslss** [comment]
There are not any updates on issue for a long time. 
It is closed.
If it is still actual for you - feel free to reopen it

**Comment by qrizly2** [comment]
**Environment:**

operating system: ubuntu 24.04
application version: 24.3.3.202501191633
driver: MySQL
driver connector: com.mysql:mysql-connector-j-8.2.0.jar

**Problems**
Unable to connect with a password containing a "$" and "#" character through a SSH tunnel.
When i connect manually on the server the password works
