### ISSUE TITLE
Incorrect string is used in Main menu - SQL Editor

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6035]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.1.0

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/31996417/58736315-0e886200-8406-11e9-8b9c-6d5e02806562.png)

**Comment by uslss** [comment]
verified

**Comment by nmat** [comment]
is this related to: https://github.com/dbeaver/dbeaver/issues/5944 ?
