### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by mdadlani** [dbeaver/dbeaver#6038]
#### System information: 
- Ubuntu 14
- DBeaver version: 6.0.5

#### Connection specification:
- Database name: Vertica

#### Describe your question:
If I delete a script from the Dbeaver, Is there a way to recover those scripts?
I have accidentally deleted a very large script that I was creating for a very long time. And now I am looking for recovering that script anyhow. Can anyone help here?

**Comment by kseniiaguzeeva** [comment]
Unfortunately there is no way to undo delete when you press **yes** in Confirmation window.
