### ISSUE TITLE
(feature request) Execute/Export Script should execute @set commands in sequence

### ISSUE THREAD

**Issue by knwpsk** [dbeaver/dbeaver#6041]
I ask that the [Execute > Export To File] process should execute the @set (etc) commands and queries in a script in linear sequence (same as it does when the results are directed to tabs in the app).

Using dbeaver v6.0.5 on Windows

When I have the following commands in a script:

@set o = Table1
select * from "${o}" limit 10;
@set o = Table2
select * from "${o}" limit 10;
@set o = Table3
select * from "${o}" limit 10;

I select all and execute as script.  dBeaver (correctly) sends the three result sets to three tabs.  No problem.
But if I select all and Execute > Export To File, then there's a problem.  dBeaver apparently runs all three @set commands first, then runs the three queries.  So the three resulting files are all identical, and contain only the content of Table3.

Thanks

(My own use case:  I have very large data sets, so they're broken out into tables by day.  So if I need to run a query over multiple days, the set of commands above is one way to do it efficiently, rather than needing to run one, wait, change table, run again, wait... etc.)

**Comment by serge-rider** [comment]
Good point. We'll redesign "Export data from query" behavior.

**Comment by uslss** [comment]
verified

**Comment by knwpsk** [comment]
I would def buy you guys a coffee or a beer for this one.  Thanks!!

**Comment by knwpsk** [comment]
Works like magic!  Thanks again, guys.
