### ISSUE TITLE
Order of columns in both data grid and left tree

### ISSUE THREAD

**Issue by daevidvincent** [dbeaver/dbeaver#6046]
It's curious (and often confusing) that the left tree columns are alphabetical while the data grid view is in DDL order. Both have their uses, but the right-click menu for each should have an option to switch to the other view order so they can be aligned. 

![image](https://user-images.githubusercontent.com/20825058/58826800-58d03580-85f6-11e9-9964-0c5c4091643a.png)

**Comment by serge-rider** [comment]
Database navigator (one the left side) sorts elements alphabetically by default (you can disable this in preferences). While data viewer reads columns in the order provided by server.
Disabling alphabetical sorting will make order the same (but less convenient in some cases).

**Comment by daevidvincent** [comment]
Sure, but I don't want to go through preferences to toggle these things as they are useful for finding a column, especially if there are lots of them to sift through. This should be surfaced up to the right-click menu on EACH thing (left side) and (top header). Hence `feature request` (which you have now removed the label) 😞

**Comment by vlkrrrr** [comment]
As a workaround you can order the columns in data viewer alphabetically with the custom filters:

![dbeaver](https://user-images.githubusercontent.com/22052934/92130207-c1631f00-ee04-11ea-834c-ffd6a320840e.PNG)

**Comment by uslss** [comment]
seems issue is outdated for now (21.2.4)
