### ISSUE TITLE
[Feature request] Connection marked as "production" shall not automatically re-connect at DBeaver startup

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6047]
It is nice and cool to have last open connections re-opened when starting dBeaver.
But, for connection marked as "Production", it would be nice to have a check in configuration so that i can choose this behavior or not

**Comment by wiwwo** [comment]
I just opened a "old" sql script file, and it automatically connected to last connection i userd it... Which was PROD... And i was about to drop a table in PROD...
Please, this would be useful :-)

**Comment by nicolasmafra** [comment]
Not just for production! Why reconnect on startup? Is this really useful for most? Please, make a survey about it.

**Comment by uslss** [comment]
It could be disabled in Preferences
![image](https://user-images.githubusercontent.com/31996417/162145480-6455ac99-3b20-4732-ba8c-8a61519096d5.png)

**Comment by nicolasmafra** [comment]
This option can be disabled by default. Think in production connections for example.
