### ISSUE TITLE
SQL Server version 8 is not supported by this driver

### ISSUE THREAD

**Issue by noraj** [dbeaver/dbeaver#6048]
#### System information: 

- Operating system (distribution) and version: ArchLinux
- DBeaver version: 6.0.4.201905162234
- Java version : openjdk version "1.8.0_212"

#### Connection specification:

- Database name and version: `Microsoft SQL Server 2000 8.00.766.00; SP3a`
- Driver name: mssql-jdbc RELEASE 7.2.1.jre8
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

`SQL Server version 8 is not supported by this driver. ClientConnectionId:d4ef36de-cff9-4525-b38d-d3881da6b020`

**Comment by serge-rider** [comment]
You could try to use old driver (jTDS or MS) in order to work with old SQL Server versions.

**Comment by noraj** [comment]
@serge-rider I finally used sqsh to interact with MS SQL 8. I do not personally need it anymore. So if anyone else really need that I think we can close the issue.

**Comment by tioback** [comment]
Too bad that this doesn't solve the issue.
Instead of closing it, why not fix it?

**Comment by bigoper** [comment]
> You could try to use old driver (jTDS or MS) in order to work with old SQL Server versions.

How did you get/use the old driver?
Thanks

**Comment by julian-innerchild** [comment]
Scrolling down on drivers selection screen will offer you those older drivers. Just add a new server connection and select the correct one.

You could check the following screenshots:
1. Driver selection screen
![1](https://user-images.githubusercontent.com/94164672/171431525-366109b5-f8fc-48ed-ad0f-10c2a3570a96.png)

2. Scrolling down to pick the correct one [https://postimg.cc/F77YycdS](https://postimg.cc/F77YycdS)
![2](https://user-images.githubusercontent.com/94164672/171431518-0415fd6e-185e-48e2-ad2f-70eb21efe5cb.png)
