### ISSUE TITLE
JSON format value in addition to Binary, Text, XML

### ISSUE THREAD

**Issue by daevidvincent** [dbeaver/dbeaver#6049]
Sadly there is no JSON format (and beautifier) option in the value window mode. Only `Binary`, `Text` and `XML`

![image](https://user-images.githubusercontent.com/20825058/58842439-0f4a0f80-8623-11e9-9742-181bf8775d1e.png)

**Comment by serge-rider** [comment]
We have JSON format support in DBeaver EE. We are planning to move this feature to community version in 6.2.

**Comment by galileo-pkm** [comment]
This wiki page (https://github.com/dbeaver/dbeaver/wiki/Working-with-XML-and-JSON)  lists JSON as supported with no mention that this is a Enterprise version only. 
The wiki page should be amended.

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by p91paul** [comment]
judging from milestones, 6.2 is up next in 2 weeks!

**Comment by daevidvincent** [comment]
I downloaded `6.2` from "ea" and confirmed JSON works....

![image](https://user-images.githubusercontent.com/20825058/63970407-e3d79500-ca58-11e9-85d2-79da6cecd624.png)

Love the color coding too!

Not to get greedy, but my next feature request would be for collapsing the blocks. ;-)

Also, it doesn't work on JSON that is in an array...

![image](https://user-images.githubusercontent.com/20825058/63970760-cc4cdc00-ca59-11e9-847e-a4af454701cb.png)

**Comment by daevidvincent** [comment]
Am I blind or did you somehow re/move one of the features I use every day in the new v7.0.0? How do I view the value as JSON now ?!! I've hunted and hovered over every button, widget, icon, menu that I can see around this screen. It used to be prominent and easy to find. What happened?

![image](https://user-images.githubusercontent.com/20825058/75954988-d1a43c80-5e69-11ea-861a-d422b34e685d.png)

**Comment by kseniiaguzeeva** [comment]
Hi @daevidvincent. Cannot reproduce. Please tell the column type where JSON is not displayed.
Do you use PostgreSQL?

**Comment by daevidvincent** [comment]
@kseniiaguzeeva I updated the image with a few more arrows. I'm not understanding your ask though. Its the column called `rubric` defined as `jsonb` array. [Literally the same column (and screenshots from earlier in this thread)](https://user-images.githubusercontent.com/20825058/63970760-cc4cdc00-ca59-11e9-847e-a4af454701cb.png). I use this column (and others like it) all the time.

There used to be a [button/menu on the Value pane](https://user-images.githubusercontent.com/20825058/58842439-0f4a0f80-8623-11e9-9742-181bf8775d1e.png) that showed various formats like XML, Binary, Text, and of course JSON (as of this ticket). Now, as per my callout bubble above, there is no button/menu that I can find that has those options anymore in v7.0.0 on Windows 10 (like there was in v6.x)

**Comment by serge-rider** [comment]
@daevidvincent your column has type Array (of json). It consists of one element. 
We don't support inline json editor of array elements yet.

**Comment by daevidvincent** [comment]
Huh. Interesting. I stand corrected! This is JSON not in an array and you're right, it formats just fine. I must be working too late... :-) Ignore me. :)
![image](https://user-images.githubusercontent.com/20825058/76026401-89c1fb80-5ee3-11ea-8aa2-47402e8f7731.png)
