### ISSUE TITLE
extension information in PostgreSQL

### ISSUE THREAD

**Issue by asotolongo** [dbeaver/dbeaver#6051]
Can you add extension information in PostgreSQL to info system on dbeaver? like Language, Tablespace information, etc 

You can use the following query to get this : 
"select name from pg_available_extensions where installed_version is not null"

Thanks

**Comment by serge-rider** [comment]
We already have Extensions under the schema->System Info elements.
We need to move it under the database->Extensions.
We need a way to determine whether extension is installed or not + install/uninstall actions.

**Comment by asotolongo** [comment]
to get if extension is installed the query:
select name from pg_available_extensions where installed_version is not null;
to get if extension is installed the query: 
select name from pg_available_extensions where installed_version is  null;


to install extension: 
CREATE EXTENSION [ IF NOT EXISTS ] name_of_extension CASCADE;
to uninstall extension: 
DROP EXTENSION [ IF EXISTS ] name_of_extension  CASCADE ;

**Comment by uslss** [comment]
verified
