### ISSUE TITLE
[Feature request] "Trim trailing spaces" editor features

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6052]
(sql) editor lacks feature "trim trailing spaces"

**Comment by fsv-vhsab** [comment]
Is this feature available? could really need this. Thanks!

**Comment by LonwoLonwo** [comment]
Feature implemented in DBeaver 21.0.2

More information about how it works here: https://github.com/dbeaver/dbeaver/wiki/SQL-Formatting

**Comment by kseniiaguzeeva** [comment]
verified
