### ISSUE TITLE
Dbeaver: MySQL Date function error: Error code 1064, SQL state 42000: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

### ISSUE THREAD

**Issue by DY-OAK** [dbeaver/dbeaver#6053]
Error while querying DATE, sample query -

SELECT DATE('2003-12-31 01:02:03');

Error code 1064, SQL state 42000: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

Target DB version: MySQL 5.5
Dbeaver versions used: 5.0.1+ and 6.0+
![Dbeaver_Date_Error](https://user-images.githubusercontent.com/51381386/58904764-0443bd80-86bd-11e9-90b0-bca32cb5c9a6.jpg)

**Comment by serge-rider** [comment]
Can't reproduce, please check this in DBeaver 6.1
