### ISSUE TITLE
`WITH` keyword wrongly identified as "data modification" command in mySql read-only connections

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6060]
dBeaver 6.0.5, mySql driver 8.0.11, read-only connection.

Query
```with test as (select 1 from dual) select * from test;```
not executed, 
error returned is
```SQL Error [S1009]: Connection is read-only. Queries leading to data modification are not allowed.```

Obviously, this is not a query that changes anything in data... :-)

**Comment by wiwwo** [comment]
mySql version `5.7.26-0ubuntu0.18.04.1`

**Comment by dst1980** [comment]
Starting a new script and typing
select 1 from dual

Will trigger this before even trying to run the script.  Some of the background lookup processes seem to be flagged as queries leading to data modification.  This is a change which was implemented after 6.3.0.

**Comment by uslss** [comment]
Cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket
