### ISSUE TITLE
Generate changelog for Liquibase from DBeaver

### ISSUE THREAD

**Issue by tchibatron** [dbeaver/dbeaver#6061]
I was wandering if you could add an opportunity to generate changelog file for selected DB.
Sometimes I start up new projects from the beginning, when there is no DB at all. I create a first version of DB schema using DBeaver. I do it from UI. Than I need to create a changelog.xml file using Liquibase to put it to VCS as a kind of "init scripts" for DB.
I do this scenario several times until we don't have an agreement with a customer or my team.
It will be really convenient to have a special button somewhere in context menu to generate this file.

Script example of using Liquibase to generate changelog:
`liquibase --driver=oracle.jdbc.OracleDriver \
      --classpath=\path\to\classes:jdbcdriver.jar \
      --changeLogFile=com/example/db.changelog.xml \
      --url="jdbc:oracle:thin:@localhost:1521:XE" \
      --username=scott \
      --password=tiger \
      generateChangeLog` 

Documentation is [here](https://www.liquibase.org/documentation/generating_changelogs.html)

**Comment by AndrewKhitrin** [comment]
@tchibatron 

You gan get Liquibase changelog in XML format from preview compare results window by selection format in Report type dropdown

![image](https://user-images.githubusercontent.com/25009233/59192357-d104a100-8b8a-11e9-9a94-cd4ed8f5d88e.png)

**Comment by tchibatron** [comment]
Unfortunately this is not convenient way. I your case I must compare my DB with another one. In my case I have only one DB.

**Comment by serge-rider** [comment]
We'll this feature in 6.1.1 EA. Generally it will work very similarly to schema compare but with empty target snapshot.

**Comment by uslss** [comment]
verified
