### ISSUE TITLE
Add support for Multiple selections (multi-cursor)

### ISSUE THREAD

**Issue by adbakke** [dbeaver/dbeaver#6064]
**Is your feature request related to a problem? Please describe.**
Oftentimes I'm copying and pasting from another coding language to try create my queries, being able to select multiple lines in dBeaver would prevent me from needing to write my queries in another code editor and then paste in.

**Describe the solution you'd like**
Add the ability to have multiple cursor editing. It's standard in many code editors (Atom, Sublime, VSCode, etc).

**Describe alternatives you've considered**
Copying and Pasting into another editor to create queries.

**Additional context**
Looks like this:
![multi-cursor](https://user-images.githubusercontent.com/5157757/59050994-d5af1980-8859-11e9-876d-0271cd9b011b.gif)

**Comment by adbakke** [comment]
Searched for this one already and didn't find anything.

**Comment by RickClemons** [comment]
Any update on this?

**Comment by lsalmins** [comment]
would also love this

**Comment by nkev** [comment]
would love this too

**Comment by adornodev** [comment]
would love this too

**Comment by surmol** [comment]
Would also like this.

**Comment by alanmiller41** [comment]
This would be super nice

**Comment by DJPretorius** [comment]
Please add support for this. Soooo needed in DBeaver

**Comment by TBG-FR** [comment]
Need it too, very convenient when you work with people that doesn't write scripts like you do ahah

**Comment by dustinfast** [comment]
Agreed! One of the reasons I love DBeaver is it incorporates many advanced text editing features -- it's missing this one though!! :)

**Comment by tomstock1337** [comment]
I would also like this

**Comment by ConnorWilloughby2** [comment]
Aswell as this it would also be interesting to add a Ctrl + Shift + Down type function like in vs code.

**Comment by kelwest** [comment]
Please add this! Right now I edit queries with multiselect in a different application then copy the query back to Dbeaver. This would save so much time!

**Comment by TripC4** [comment]
Please add this! It is killing feature for sql.

**Comment by superbeer** [comment]
Please add this feature to Dbeaver

**Comment by ak-rocksdev** [comment]
Any update on this? Would be so useful..

**Comment by BernhardNinaus** [comment]
Please add this functionality 👍

**Comment by satnatantas** [comment]
Isn't this rather a request for Eclipse editor which DBeaver uses?

**Comment by pallavJha** [comment]
This will be a very helpful feature, especially when IntelliJ, Eclipse, Sublime and VSCode support it OOTB

**Comment by lvilasboas** [comment]
This would be an excellent feature! Please do add it

**Comment by seidmanm** [comment]
Please add this. Switching to Dbeaver from a different sql editor. Multiple cursors is a staple in my workflow.

**Comment by atranel** [comment]
Please add it, I have often same variables etc. to change in my SQL code. It would be nice to have also something like Visual Studio Code has. CTRL+D will add to selection same text further in code.

**Comment by adbakke** [comment]
Would be nice to see some acknowledgement on this. There have been steady comments of agreement every single month since adding this feature request.

**Comment by alosipov** [comment]
Voting for this one as well!

**Comment by lestevam** [comment]
I would like these feature too.

**Comment by rjake** [comment]
Same here

**Comment by lbarron-md** [comment]
Please add this

**Comment by jeffschaper** [comment]
How do we up-vote this feature request. This would be awesome to have!

**Comment by vnikiten01** [comment]
Up Vote

**Comment by serge-rider** [comment]
Multi-selection feature is planned in the standard Eclipse platform/swt: https://bugs.eclipse.org/bugs/show_bug.cgi?id=466532

At the moment we support only block selection (<kbd>alt+shift+a</kbd>).

There are a couple of known Eclipse plugins which adds a sort of multi-selection support: 
- https://github.com/caspark/eclipse-multicursor
- https://github.com/EliMirren/Eclipse-Multiple-Cursor 

However they don't provide all needed features and are not supported anymore . But still worth investigation.

**Comment by danchen4** [comment]
Would be a game changer

**Comment by AkshayRShiraguppi** [comment]
> This will be a very helpful feature, especially when IntelliJ, Sublime and VSCode support it OOTB

Well, even notepad++ uses this. Its due time Dbeaver develops and adds it.

**Comment by GaryLiuTelus** [comment]
Upvote for this.

**Comment by pweiss82** [comment]
Yes, please add this. I would use that everyday!

**Comment by AshfordN** [comment]
Also interested in this feature

**Comment by jandude** [comment]
Up Vote

**Comment by ewertones** [comment]
+1

**Comment by HolgerGH** [comment]
+1 :)

**Comment by RyanMerlin** [comment]
Upvote!  Agree on the gamechanger comment! +1

**Comment by MarkrJames** [comment]
+ 1  Please add! 🙏

**Comment by jhofstede** [comment]
Is there a way we can crowdfund and sponsor the development of this feature? I would be happy to sponsor such a feature.

**Comment by p91paul** [comment]
@jhofstede according to https://dbeaver.com/support/ buying a EE license should get you priority tickets, though I'm unsure how that works.

**Comment by alexarze** [comment]
> At the moment we support only block selection (alt+shift+a).

While this great to know (it is __so__ slow though), I definitely would use a multiselect cursor on a regular basis. Disappointing we're waiting for Eclipse to implement this.

**Comment by jpdesarrolloapp** [comment]
+1

**Comment by ohigs-airup** [comment]
+1

**Comment by jean-estime** [comment]
+1 🙏

**Comment by 90awlui** [comment]
+1

**Comment by elbertcastaneda** [comment]
+1

**Comment by chelicery** [comment]
+1

**Comment by Aileron79** [comment]
This would be a nice feature, I'd be happy about a multiline editing feature. In the example above just let me select the word "quick" in all lines and replace it in all lines by typing "slow". Have not found anything like that, doubt it makes sense to create another feature request for that.

**Comment by serge-rider** [comment]
Multi-selection feature was implemented in Eclipse platform, planned to be released in 2021-12 version. It will be added in DBeaver a bit later (after we will migrate to 2021-12).
(see details here - https://bugs.eclipse.org/bugs/show_bug.cgi?id=466532)

**Comment by Mrfork91** [comment]
+1

**Comment by CaioOliveiraw** [comment]
+1

**Comment by silvaevandro** [comment]
+1

**Comment by lastseenjustnow** [comment]
+1

**Comment by serge-rider** [comment]
Multiple selections was added in Eclipse 2021-12 and in DBeaver 21.3.3.
First version doesn't contain proper keyboard shortcuts, they will be added in the next update (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=576377).

How to use multi-selection:
- Switch to bclock selection mode (<kbd>ALT+Shift+A</kbd>)
- Select block of code you want to edit
- Switch to multi-selection mode. You can find this command by pressin search icon in the main toolbar: "To multi-selection".

You can assign a shortcut manually. Find command "To multi-selection" in Preferences->Appearance->Keys and assign a key binding.

**Comment by jobe451** [comment]
Uhhhhh, that is so far away from anything like what VSCode offers.

For instance, shift-arrow-down selects multiple lines, shift-arrow-right selects by character, arrow-right does not move the cursor character by character. Instead, the multiselection is reduced to the last cursor: FAIL, BIG FAIL!

**Comment by dnlw07** [comment]
please improve multiline feature if possible. When I hold Ctrl button and press Left/Right arrow then multiline cursor disappears. 
The multiline feature would greatly improve productivity in DBeaver. Currently i need to copy paste the code to VSCode to make modifications using Multi-Cursor Editing. Ctrl+D shortcut to select next occurrence would also be very helpful

**Comment by dhouck** [comment]
Iʼm glad we now have a partial implementation, but this is not close to a full implementation of the requested feature and this issue should not be closed.
