### ISSUE TITLE
SQL pasting / formatting bug in "SQL Editor" with specific characters / scripts (Sri Lanka)

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#6066]
#### System information: 
- Operating system (distribution) and version: Windows 10 + latest service packs
- DBeaver version: 6.0.5
- Java version: Version 8, update 211
- Additional extensions n/a

#### Connection specification:
- Database name and version: n/a
- Driver name n/a
- Do you use tunnels or proxies (SSH, SOCKS, etc)? n/a

#### Describe the problem you're observing:
When pasting (Ctrl+V on Windows) SQL with specific characters, DBeaver omits trailing brackets directly after the sequence of trailing characters. In this case the sequence of characters is the official name of Sri Lanka, see this OpenStreetMap link and the "name" field there:
https://www.openstreetmap.org/relation/536807

#### Steps to reproduce, if exist:
- Paste this SQL code line in a SQL Editor window:
`(osm_name IS NULL OR osm_name NOT IN ('Cuba','Great Britain','Jamaica','Madagasikara','Srí Lanka','ශ්‍රී ලංකාව இலங்கை')) AND foo=bar`
- Now notice the brackets before **AND** are missing. Also notice the ending single quote of the series of characters, although still there, is displayed differently and very small compared to the other single quotes:
![afbeelding](https://user-images.githubusercontent.com/7635726/59057877-b2a55980-889b-11e9-804d-e53a3bdec505.png)

**Comment by uslss** [comment]
seems that issue is fixed.
cannot reproduce it for now. If it is still actual for you - feel free to reopen the ticket

**Comment by mboeringa** [comment]
@uslss 

I can confirm that this old issue seems fixed in the latest releases. I just installed v7.0.5, and cannot reproduce it either, so you were right to close the issue.
