### ISSUE TITLE
MS SQL Server. Text view issue in special cases

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6067]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version EA 6.1.0

#### Connection specification:
- Database name and version SQL Server 2017

#### Describe the problem you're observing:
In some cases text view is shown incorrectly for MS SQL tables (Text view)
![image](https://user-images.githubusercontent.com/31996417/59072660-19db0200-88cc-11e9-9b84-2c9f8a7e2e24.png)
Column types:
![image](https://user-images.githubusercontent.com/31996417/59072679-2a8b7800-88cc-11e9-99ae-387967ae34df.png)

According to Recording view, issue could be caused by column with hierarchyid type
![image](https://user-images.githubusercontent.com/31996417/59072815-f795b400-88cc-11e9-846b-87929328a2fb.png)

**Comment by uslss** [comment]
similar issue appiars for mongo db (List type)
![image](https://user-images.githubusercontent.com/31996417/59075724-e0f65980-88da-11e9-8425-0cdbb11aeec4.png)

**Comment by uslss** [comment]
reproducible for datatypes like json, jsonb, varbinary

**Comment by serge-rider** [comment]
It happens with binary data types when String binary presentation is enabled.
It is a bad idea to use this mode in plaintext. Switch to Hex or Base64 binaries presentation.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
