### ISSUE TITLE
Error synchronizing data with database

### ISSUE THREAD

**Issue by Speirs47** [dbeaver/dbeaver#6068]
#### System information: 
- Operating system (distribution) and version
**openSUSE Leap 15.1, but happened also on 15.0**
- DBeaver version
**currently 6.0.5, but happened before. I think since 6.0.0 or even earlier**
- Java version 
**openjdk 10.0.2 2018-07-17**
- Additional extensions
**none**

#### Connection specification:
- Database name and version
**10.2.22-MariaDB**
- Driver name
**mariadb-java-client-1.5.5.jar**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
**SSH tunnel**

#### Describe the problem you're observing:
When I try to edit and save data in one table it would throw an error **Error synchronizing data with database** (more info below). It doesn't matter which column I'm trying to edit but it only happens in one table.
Removing DBeaver's config directory so it would create a new one is helping but as I just found out - only temporary

#### Include any warning/errors/backtraces from the logs
> SQL Error [1615] [HY000]: (conn:142203) Prepared statement needs to be re-prepared
> Query is: UPDATE dane_nowe.pozycje_rezerwacji
> SET usunięty=?
> WHERE ID_pozycji=?, parameters [0,82391]
>   (conn:142203) Prepared statement needs to be re-prepared
> Query is: UPDATE dane_nowe.pozycje_rezerwacji
> SET usunięty=?
> WHERE ID_pozycji=?, parameters [0,82391]
>   (conn:142203) Prepared statement needs to be re-prepared
> Query is: UPDATE dane_nowe.pozycje_rezerwacji
> SET usunięty=?
> WHERE ID_pozycji=?, parameters [0,82391]
>     Prepared statement needs to be re-prepared
> Query is: UPDATE dane_nowe.pozycje_rezerwacji
> SET usunięty=?
> WHERE ID_pozycji=?, parameters [0,82391]
>     Prepared statement needs to be re-prepared
> Query is: UPDATE dane_nowe.pozycje_rezerwacji
> SET usunięty=?
> WHERE ID_pozycji=?, parameters [0,82391]

And here's table structure

> CREATE TABLE `pozycje_rezerwacji` (
>   `ID_pozycji` int(11) NOT NULL AUTO_INCREMENT COMMENT '',
>   `ID_rezerwacji` int(11) DEFAULT 0 COMMENT '',
>   `ID_kartoteki` int(11) DEFAULT 0 COMMENT '',
>   `szer` smallint(5) unsigned DEFAULT 0 COMMENT '',
>   `wys` smallint(5) unsigned DEFAULT 0 COMMENT '',
>   `ilość` decimal(10,3) unsigned DEFAULT 0.000 COMMENT '',
>   `data_rezerwacji` date DEFAULT NULL,
>   `waga` decimal(10,3) DEFAULT 0.000 COMMENT '',
>   `usunięty` tinyint(1) NOT NULL DEFAULT 0,
>   `data_dodania` datetime DEFAULT current_timestamp() COMMENT '',
>   `wydane` tinyint(1) NOT NULL DEFAULT 0,
>   `rodzaj` smallint(1) NOT NULL DEFAULT 0 COMMENT '',
>   `niestandardowa` tinyint(1) NOT NULL DEFAULT 0,
>   `etykieta` tinyint(1) NOT NULL DEFAULT 0 COMMENT '',
>   `uszk_prod` tinyint(1) NOT NULL DEFAULT 0 COMMENT '',
>   `uszk_dost` tinyint(1) NOT NULL DEFAULT 0 COMMENT '',
>   `ID_optymalizacji` int(11) NOT NULL DEFAULT 0 COMMENT '',
>   PRIMARY KEY (`ID_pozycji`)
> ) ENGINE=InnoDB AUTO_INCREMENT=86117 DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci AVG_ROW_LENGTH=84

**Comment by Speirs47** [comment]
Anything?

I should also mention that I got two exactly the same databases (production and testing) and that issue applies to both databases (just that one table)

**Comment by serge-rider** [comment]
This seems to be this bug: https://bugs.mysql.com/bug.php?id=42041
Standard recommendation is to upgrade server.
Also you could try another client driver version (e.g. MySQL 8.x).

**Comment by Speirs47** [comment]
I downloaded latest driver from MariaDB website (2.4.2) and it seems like the problem was fixed.
I was using version 1.5.5 which seems to be downloaded from DBeaver driver repository so I think it would be a good idea to update it considering that version 1.5.5 of mariadb client doesn't seem to be supported.

**Comment by serge-rider** [comment]
Thank for the information, I'll update default driver version (btw you can choose any driver version right from DBeaver driver download interface)

**Comment by uslss** [comment]
verified
