### ISSUE TITLE
When there's an error while dumping a database, popup shows "completed" message

### ISSUE THREAD

**Issue by schmunk42** [dbeaver/dbeaver#6070]
#### System information: 
- Operating system (distribution) and version: Arch Linux
- DBeaver version: 6.0.4.201905162234
- Java version: java version "1.8.0_211" 
- Additional extensions ?

#### Connection specification:
- Database name and version: MySQL 5.x
- Driver name ?
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:

I am trying to use a custom `mysqldump` command, but got the path wrong.
But the general problem is, that DBeaver says "Export complete" despite and Exit-Code of 1.
It should show a error notice in the popup.

![Bildschirmfoto von 2019-06-07 16-19-05](https://user-images.githubusercontent.com/649031/59111490-6ca2d100-8941-11e9-9b9d-be72b01df8f9.png)

**Comment by uslss** [comment]
seems that issue is fixed. Error window appears
