### ISSUE TITLE
sql autocompletion doesn't work

### ISSUE THREAD

**Issue by raghunath-g** [dbeaver/dbeaver#6073]
#### System information: 
- Operating system (distribution) and version :  Windows 10 Enterprise
- DBeaver version : 6.0.5 May 19th, 2019

#### Connection specification:
- Database name and version : Oracle 12

#### Describe your question:
SQL autocompletion is not working when pressed ctrl + space, it doesn't list out the column name. 
We have multiple schema in the DB 
I tried setting ALTER SESSION SET CURRENT_SCHEMA = <SCHEMA_NAME> 
but that doesn't work either.

**Comment by Speirs47** [comment]
I got the same problem on openSUSE, I posted about it sometime ago #5955

**Comment by jim256** [comment]
Still an issue for me

**Comment by jim256** [comment]
@serge-rider 
Just wanted to check in and see if there was any update here :) This and no smooth scrolling (#6713, #6536 ) are the only two things causing me to look elsewhere (and then miss all the awesome things DBeaver has that they don't :) )

**Comment by jim256** [comment]
@serge-rider just following up here. I keep trying every new release of DBeaver. Still an issue for me that auto-complete often offers no suggestions when it should (without pressing ctrl + space and with trying ctrl + space)

macOS 10.15.3 (19D76)
DBeaver 6.3.5.202002151353
Snowflake 4.3.1 using Snowflake JDBC Driver 3.12.0

**Comment by uslss** [comment]
seems to be obsolete. Cannot reproduce it for now.
![image](https://user-images.githubusercontent.com/31996417/132694369-3a1bca31-21ee-4635-be8e-ec3d3688a5a7.png)
