### ISSUE TITLE
PostgreSQL.Role.Permissions.Sequence not work

### ISSUE THREAD

**Issue by sparkji** [dbeaver/dbeaver#6076]
#### System information: 
- Operating system (distribution) and version Ubuntu 19.04
- DBeaver version  5.0.4.201905052017
- Java version  openjdk 1.8.0_212
- Additional extensions

#### Connection specification:
- Database name and version Postgresql 11
- Driver name PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Role>Permissions>Sequences
Select one permission('SELECT'), then unselect it, then select another permission('USAGE'), then click Save button, the SQL Preview not refresh, 'SELECT' permission still be there.
After click 'Persist' button, no promotion if operation successes, and Permission box not be checked.

**Comment by uslss** [comment]
fixed
