### ISSUE TITLE
Create jobs by GUI

### ISSUE THREAD

**Issue by ivanelson** [dbeaver/dbeaver#6077]
Hi,
In DBEaver there is some way to create a job through the GUI interface. Same thing exists in PGAdmin?

![image](https://user-images.githubusercontent.com/779883/59203367-cf2fe300-8b74-11e9-9cc0-3c31c75b4112.png)

**Comment by ivanelson** [comment]
One more requires this feature. #6262

**Comment by dcbeckman** [comment]
I also need this feature.  BigSQL seems to have just ended support for pgAdmin 3 LTS, and I can no longer install LTS on my new machine.  I hate using pgAdmin 4.  Please make a DBeaver front end for the pgAgent scheduler.

**Comment by eraviolo** [comment]
Yes please! It would be a very useful feature for all pgAgent users who migrated from PgAdmin4 (:S) to DBeaver...

**Comment by rupirilo** [comment]
Agreed! This is a feature I could really do with. pgAdmin4 is horrible to use and pgAdmin3 is almost unusable with more recent server releases.

**Comment by jinverso** [comment]
I concur, this is a must-have feature for dbbeaver and would be very appreciated by all Postgres admins

**Comment by curala70** [comment]
Definitely a **must-have feature** as already mentioned by @jinverso

**Comment by ivanlonel** [comment]
Is there any chance this could be used to manage [pg_cron](https://github.com/citusdata/pg_cron) jobs as well?

**Comment by ShadelessFox** [comment]
Hello @ivanlonel,

It is possible since both pgAgent and pg_cron use cron to create schedules, so we can use the same logic for these two.

But please create a separate feature request.

**Comment by ivanlonel** [comment]
> Hello @ivanlonel,
> 
> It is possible since both pgAgent and pg_cron use cron to create schedules, so we can use the same logic for these two.
> 
> But please create a separate feature request.

Thanks for your reply, @ShadelessFox. I've created #14943, following your advice.

**Comment by uslss** [comment]
verified
