### ISSUE TITLE
Minimum and Maximum Values in Calc Panel Sometimes Incorrect

### ISSUE THREAD

**Issue by aloeber** [dbeaver/dbeaver#6078]
#### System information: 
- Windows 10 Enterprise
- DBeaver v6.1.0.201906091949
- JRE v1.8.0_171

#### Connection specification:
- AWS Redshift v1.0.7562 running PostgreSQL 8.0.2
- Redshift JDBC Driver v1.2.27.1051

#### Describe the problem you're observing:
Appears to be a bug causing minimum and maximum values within the Calc panel to sometimes be incorrect:
![Capture](https://user-images.githubusercontent.com/22184158/59235995-0c15cd00-8ba9-11e9-9210-e5314492d4c7.PNG)
In every case I observed where the values were incorrect in the Calc panel, the values for the minimum and the maximum were exactly the same number. 

#### Steps to reproduce, if exist:
I queried a table that contained several different variable types, and simply highlighted various stretches of different fields in the Results planel, then checked them against the minimum and maximum values displayed in the Calc panel. Varchar, bool, int4, and numeric fields have so far yielded the correct min and max, but in my limited testing float8 type fields always gave incorrect ones.

_As an aside, I am very impressed by the quality of DBeaver's performance, UI, and feature set - especially since it's freely-distributed software. Keep up the great work, dev(s)!_

**Comment by serge-rider** [comment]
Thanks for the bug report.
It was an error in numeric values compare (happened whenever values are less than 1)

**Comment by uslss** [comment]
verified
