### ISSUE TITLE
[DBeaver EE] Foreign keys are not added to the changelog during migrate

### ISSUE THREAD

**Issue by tchibatron** [dbeaver/dbeaver#6081]
#### System information: 
- Windows 10
- DBeaver version 6.1.0 EE
- Additional extensions: no

#### Connection specification:
- PostgreSQL 11.2 (Debian 11.2-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
- Driver name: n\a
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
When I create changelog for my DB DBeaver does not add foreign keys to the changelog file.

#### Steps to reproduce, if exist:
Create DB called asdf. 
Create DB called empty.
Create table called my_table in asdf DB.
Create column id type serial, and column clmn1 type varchar  in my_table:
![image](https://user-images.githubusercontent.com/6930846/59274891-eac5e700-8c63-11e9-9a3e-8f8b9b69ed88.png)
Add primary key to id column in my_table table.
Create table called connected_table.
Add column id type int4;
Add column clmn2 type varchar;
Add column my_table_id type int4;
Add primary key to id column;
Add foreign key to my_table_id column (reference to my_table):
![image](https://user-images.githubusercontent.com/6930846/59275181-7ccdef80-8c64-11e9-80e2-e878af333bb6.png)
Right click on asdf DB -> select compare/migrate -> Compare/Update structure
Select table and sequences of asdf table on the left pane and empty db on the right panel:
![image](https://user-images.githubusercontent.com/6930846/59275347-d46c5b00-8c64-11e9-9665-93507ce26568.png)
Click compare -> select changeLog in report type comobobox:
![image](https://user-images.githubusercontent.com/6930846/59275467-0aa9da80-8c65-11e9-9969-659584e85cb0.png)

Note that changelog does not have foreign key for connected table.

**Comment by uslss** [comment]
Fixed. Verified
