### ISSUE TITLE
Exporting table from MySQL: Can't create target table

### ISSUE THREAD

**Issue by bobromeo** [dbeaver/dbeaver#6082]
*MS-windows server 2012 R2, dBeaver 6.1.0, Java 8u161
*MariaDB 10.1.37 + MySQL 5.5.62
*Driver MariaDB (org.mariadb.jdbc:mariadb-java-client:RELEASE [1.5.5])
*Errors: Can't start data transfer --> Reason: Can't create target table

Exporting table from MySQL gives errors.

Database navigator> Tables> Right-click> Export Data

Generated create statement is faulty when there are Enum fields:
Example: nb enum(1),

Work-a-round: First use Generate SQL> DDL
Example: `nb` enum('J','N') DEFAULT 'N',
^^^nb is between back-quotes

**Comment by uslss** [comment]
Cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket
