### ISSUE TITLE
IntelliJ IDEA development

### ISSUE THREAD

**Issue by rbellamy** [dbeaver/dbeaver#6084]
#### System information: 
Windows 10 18362.145
DBeaver 6.1.0

#### Connection specification:
N/A

#### Describe your question:
I've successfully set up my development environment in both Eclipse and IntelliJ IDEA to the point where I can run and debug DBeaver in IntelliJ.

However, the IDEA integration is struggling with the OSGi bundle configuration, and thus there are numerous inline semantic errors, as well as outright dependency resolution failures because IntelliJ can't find the `Import-Package` header in the manifest or it doesn't recognize the dependency.

![image](https://user-images.githubusercontent.com/94763/59290663-ee3e7b80-8c2d-11e9-9409-25179252040e.png)
![image](https://user-images.githubusercontent.com/94763/59292888-c9003c00-8c32-11e9-8710-534c0797c200.png)

Do you have a suggestion on how to get this working as smoothly as possible?

**Comment by serge-rider** [comment]
You shouldn't add OSGI support in IDEA project. IDEA works poorly with Eclipse-based RCPs.

Try to follow WIKI instructions strictly. Project configuration (https://github.com/dbeaver/dbeaver-idea-project) usually works without additional configuration (except Eclipse classpath which has to be done manually).

**Comment by rbellamy** [comment]
Yep, ignoring the OSGI stuff made all the difference.

**Comment by rbellamy** [comment]
Actually, now it's not working again. Even though I much prefer IDEA, Eclipse is so much easier to work with here. I may just stick with that.

**Comment by rbellamy** [comment]
Got it working again. Thanks for the thorough set of instructions.
