### ISSUE TITLE
How to remove --routines option from mysqldump?

### ISSUE THREAD

**Issue by schmunk42** [dbeaver/dbeaver#6086]
#### System information: 
- Operating system (distribution) and version: Arch Linux Kernel 5.1.8-arch1-1-ARCH
- DBeaver version 6.0.4

#### Connection specification:
- Database name and version: Server MySQL 5.7 - Client MariaDB 10.3

#### Describe your question:
When dumping a database the client always adds the `--routines` flag to `mysqldump`.
This is problematic with the above client server combination, see https://jira.mariadb.org/browse/MDEV-17429

I found the corresponding code here: https://github.com/dbeaver/dbeaver/blob/6ebe0bcc6d531508bdc5dffaf16a50a7a3bade75/plugins/org.jkiss.dbeaver.ext.mysql.ui/src/org/jkiss/dbeaver/ext/mysql/tools/MySQLExportWizard.java#L161-L163

How can I remove the option from the command?

**Comment by noahbetzen-wk** [comment]
I agree. At the very least, there could be another `Settings` checkbox for `No routines`.

**Comment by pajonas** [comment]
@schmunk42 I opened an PR to add a settings option. See https://github.com/dbeaver/dbeaver/pull/36416
