### ISSUE TITLE
Ctrl + E panel overflow main screen

### ISSUE THREAD

**Issue by dwhitz** [dbeaver/dbeaver#6087]
#### System information: 
- Operating system Win10 10.0.16299.1029
- DBeaver version 6.1.0.201906091949
- Java version JDK 1.8.0_171
- Additional extensions No

#### Describe the problem you're observing:
I have 2 external monitor, when i press CTRL + E the panel overflow the main screen.

![Scripts panel](https://i.snag.gy/vLoxYi.jpg)

The monitors have different resolutions. 
The laptop has a Full-HD monitor, while the left monitor is Full-HD widescreen and the right monitor is SXGA (1280×1024).

Dragging dbeaver from one monitor to another cause this issue because seems to save the previous monitor resolution. If I try to close and **re-open** dbeaver on the main monitor, the bug is still present.

#### Steps to reproduce, if exist:
- Add two external monitor (it happens also with one monitor)
- Open dbeaver
- Open multiple scripts
- Move dbeaver to another monitor
- Press CTRL + E and ESC
- Move dbeaver to the previous monitor
- Press CTRL + E -> Bug

#### Include any warning/errors/backtraces from the logs
No errors or warnings from the logs

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified

**Comment by dwhitz** [comment]
Hi guys, 
Sorry to come back on this issue but I've just downloaded and tested with 6.1.2 (6.1.2.201907061627) and the bug is still present, video in attachment.

[dbeaver_panel_bug.zip](https://github.com/dbeaver/dbeaver/files/3367174/dbeaver_panel_bug.zip)

**Comment by dwhitz** [comment]
@uslss Could you please re-open this issue?

**Comment by dwhitz** [comment]
@uslss Could you please re-open this issue?
