### ISSUE TITLE
How to connect to Athena with ACCESS_KEY, SECRET_KEY, SESSION_TOKEN, DBEAVER 6.1.0

### ISSUE THREAD

**Issue by thirups** [dbeaver/dbeaver#6088]
Not able to connect to Athena using Temporary credentials
#### System information: 
- Operating system (distribution) and version - MAC
- DBeaver version - 6.1.0
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version - Athena
- Driver name - https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.6/docs/Simba+Athena+JDBC+Driver+Install+and+Configuration+Guide.pdf
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by shawnweeks** [comment]
I'm going to attempt to tackle this along with some other Athena cleanup I've run across.

**Comment by uslss** [comment]
could you add some additional info? does any error appear in log?

**Comment by uslss** [comment]
there is no update on issue more than a month.
Ticket closed.
If issue still reproducible for you - feel free to reopen the ticket
