### ISSUE TITLE
DB2 Schemas not showing in version 6.0.2 or later

### ISSUE THREAD

**Issue by riroly** [dbeaver/dbeaver#6092]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by riroly** [comment]
I was using version 6.0.1 successfully.
I have tried versions 6.0.2 and later, but the DB2 Z/os schemas do not show anymore.
Anyone have any suggestions on what the resolution to this is?

**Comment by serge-rider** [comment]
Please try to disable schema filters for z/OS driver:
![image](https://user-images.githubusercontent.com/6398845/59527569-a137ff00-8ee4-11e9-8bb1-1ac686cdd919.png)
If this will help then we'll disable this option by default.

**Comment by riroly** [comment]
Serge,
This did work.I connected to my database and now see the schema listing.
Thanks!
Richard
    On Friday, June 14, 2019, 1:41:13 PM EDT, Serge Rider <notifications@github.com> wrote:  
 
 
Please try to disable schema filters for z/OS driver:

If this will help then we'll disable this option by default.

**Comment by uslss** [comment]
closed without testing
