### ISSUE TITLE
Date field values do not match with the ones shown by both, my system and mysql console

### ISSUE THREAD

**Issue by lherreranetlink** [dbeaver/dbeaver#6093]
#### System information: 
- OS: macOs High Sierra 10.13.6
- DBeaver version: 6.1.10

#### Connection specification:
- MySQL 8.0.16
- JDBC
- Not using tunnels or proxies 

#### Describe the problem you're observing:

The problem is kind of simple to describe. The past Monday I just downloaded the new release of your system, I installed it, and apparently, there wasn't any problem.
But right now I'm working with date fields, and I think that there could've been some trouble in your latest version.
Basically, when try to store this information into the database:

![Captura de pantalla 2019-06-12 a la(s) 12 06 53](https://user-images.githubusercontent.com/30661966/59373405-3aadb800-8d0f-11e9-97d2-b7ae9982192c.png)

Then, I dump this information in the browser to see what is being sent to the server:

![Captura de pantalla 2019-06-12 a la(s) 12 09 45](https://user-images.githubusercontent.com/30661966/59373457-55802c80-8d0f-11e9-8132-e30c4b74337e.png)

And then, I store the record and the database shows incorrect values for the fields `begining_date` and `expiration_date` : 

![Captura de pantalla 2019-06-12 a la(s) 12 11 24](https://user-images.githubusercontent.com/30661966/59373524-76488200-8d0f-11e9-9b86-357505340615.png)

As you can see, the days in those fields seems to be decreasing by one, and  a curious thing is that, today earlier, they were increasing.

But, the weirdest thing is that when I try to see the data in my system. It show this:
![Captura de pantalla 2019-06-12 a la(s) 12 13 09](https://user-images.githubusercontent.com/30661966/59373649-bc054a80-8d0f-11e9-8bef-6a6e48fcf8cf.png)

And also when I do a query in Mysql CLI, it shows the same dates as the previous image.

**Comment by acgomes68** [comment]
Hi!

I have same problem...

Look at this...DBeaver x MySql terminal:

![select_com_data_dbeaver](https://user-images.githubusercontent.com/38814530/61890062-0ff17a80-aedd-11e9-80cc-4cc55085795d.png)

![select_com_data_terminal](https://user-images.githubusercontent.com/38814530/61890095-2566a480-aedd-11e9-8988-2098a1b56001.png)

System Info:

- OS: debian 10 buster

- DB: mysql  Ver 15.1 Distrib 10.3.15-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

- version: dbeaver 6.1.3.201907211943

**Comment by lherreranetlink** [comment]
@acgomes68 What a pity that no one from the dbeaver team has happened to answer. Not even a comment about this from them. Today I faced the same issue, I'm afraid I'm gonna change my database manager until this is fixed.

**Comment by lherreranetlink** [comment]
I just updated to the latest version and the error is still there.

**Comment by acgomes68** [comment]
I just updated to the version 6.1.4 today (Aug 5th, 2019), but the error remains there for me too.
What can we do? An error as basic like this and no one fixes it...
I believe, no I'm sure, that many users are likely to be affected by this error and have not yet realized.

**Comment by lherreranetlink** [comment]
@acgomes68 I'm gonna use `MySQL Workbench` while this is fixed... It's a pity since `dbeaver` is very good, but I already got confused while working a lot of times due to this.

**Comment by serge-rider** [comment]
Sorry, just missed this ticket.

**Comment by serge-rider** [comment]
@acgomes68 @lherreranetlink Could you say your local time zone? It is written in the status bar of DBeaver main window.

**Comment by lherreranetlink** [comment]
@serge-rider  It says CST
![Captura de Pantalla 2019-08-05 a la(s) 12 26 22](https://user-images.githubusercontent.com/30661966/62483002-4603e980-b77c-11e9-8739-1a649d2664b4.png)

**Comment by serge-rider** [comment]
Please run following queries:

```sql
select now();

SELECT @@global.time_zone, @@session.time_zone;

SELECT @@system_time_zone;

SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP);
```

By default MySQL driver returns date/time values in server time zone. It is possible that in server's time zone actual date is different. 
It may be in the past or in the future depending on the difference between client and server time zones.

**Comment by acgomes68** [comment]
Abs.

*Antonio Carlos Gomes*

*Certificações*

   -
*ITIL®Foundation Certificate in IT Service Management (syllabus 2011) *
   -
*IT Service Management Foundation based on ISO/IEC 20000 (syllabus 2011) *
   -
*Green IT Citizen *
   - *Professional Scrum Master I*

+55 11 9 5475-0644 (*Tim*)




Em seg, 5 de ago de 2019 às 14:18, Serge Rider <notifications@github.com>
escreveu:

**Comment by acgomes68** [comment]
Abs.

*Antonio Carlos Gomes*

*Certificações*

   -
*ITIL®Foundation Certificate in IT Service Management (syllabus 2011) *
   -
*IT Service Management Foundation based on ISO/IEC 20000 (syllabus 2011) *
   -
*Green IT Citizen *
   - *Professional Scrum Master I*

+55 11 9 5475-0644 (*Tim*)




Em seg, 5 de ago de 2019 às 14:59, Serge Rider <notifications@github.com>
escreveu:

**Comment by serge-rider** [comment]
Workarounds:
1. Enable "Use native date/time format" option:
![image](https://user-images.githubusercontent.com/6398845/62531480-d442a300-b842-11e9-92f1-069d88ea478e.png)
1. Modify date/timestamp format to show time zone:
![image](https://user-images.githubusercontent.com/6398845/62531523-ecb2bd80-b842-11e9-9964-1b276c7eb26e.png)

In the next version we'll set these options by default (for MySQL only).

**Comment by serge-rider** [comment]
You can test this in Early Access version (https://dbeaver.io/files/ea)

**Comment by acgomes68** [comment]
That's right! It works...

Congrats Serge!

Tks

![dbeaver_data_formatting](https://user-images.githubusercontent.com/38814530/62544345-fbdf3e80-b835-11e9-8f9d-c6b9eddeb09a.png)

![dbeaver_query_window](https://user-images.githubusercontent.com/38814530/62544361-00a3f280-b836-11e9-89a5-42e8da2fd001.png)

**Comment by lherreranetlink** [comment]
@serge-rider Seems to work! Thanks

**Comment by kseniiaguzeeva** [comment]
Verified
