### ISSUE TITLE
DB2 AS/400 Diagrams, and other metadata not showing in version 6.0.5 or later 

### ISSUE THREAD

**Issue by TRGFRATER** [dbeaver/dbeaver#6096]
DB2 AS/400 ER Diagrams, Foreign Keys, References and other metadata not showing in version 6.0.5 or later.
driver: jt400.jar
I came back to 6.04. This version is fine.

**Comment by serge-rider** [comment]
Can't reproduce.
Please check debug/error logs for any errors/warnings (https://github.com/dbeaver/dbeaver/wiki/Log-files)

Also you could try workaround in #6092

**Comment by uslss** [comment]
there is no update for a long time.
ticket closed
