### ISSUE TITLE
Grant on function/procedures has some problem... 

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6102]
In a schema, open a function/ procedure by double clicking on its name.
Go to permissions.
Without clicking on save, click on execute checkbox grant for a user to grant it, than revoke it.
Than, for another user, click on execute checkbox some times, leaving it as "not granted".

When clicking on SAVE, even if you checked *and unchecked* the grant, in the Sql Preview show those grants will be given.
Plus, when checking and unchecking multiple times on the same user, the grant will be granted multiple times.
Please see screenshot here.
First line is about a grant has being checked and unchecked.
Remaining rows are for grant that has being checked and unchecked many times, eventually leaving the grant to unchecked.
![image](https://user-images.githubusercontent.com/3930671/59501083-0ff06a80-8e9b-11e9-9a6b-0a8b9a518d13.png)

**Comment by wiwwo** [comment]
Sorry forgot: `6.1.0.201906091949`

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
