### ISSUE TITLE
pg_restore custom format fails with "couldn't find block-id"

### ISSUE THREAD

**Issue by apolyton** [dbeaver/dbeaver#6103]
#### System information: 
- Windows 10 1809
- DBeaver standalone version 6.1.0
- openjdk version "1.8.0_212-1-ojdkbuild"
- Additional extensions none

#### Connection specification:
- Postgresql 9.6.12
- Driver name postgresql jdbc 42.2.5 
- no tunnel

#### Describe the problem you're observing:
[foo.zip](https://github.com/dbeaver/dbeaver/files/3290176/foo.zip)
This backup only contains one table "_dbupdater" with 1 row and 4 columns, though it has no primary key.
Backup was made with pgadmin3 1.23.0b by BigSQL. Trying to restore with dBeaver yields
"pg_restore: [Custom-Archiver] couldn'tf find Block-ID 2117 in archive -- possible damaged archive" (rough translation)
Restoring this backup with pgAdmin or pg_restore on cmd.exe yields no errors. Also when backup was made within DBeaver restoring it yields no errors.

**Comment by serge-rider** [comment]
Potentially this may happen because of different versions of pg_restore shipped along with DBeaver and PG server which created the archive.
Workaround: install and configure PostgreSQL cli tools with the same version as your server version (you could download 9.6 zip archive from https://www.postgresql.org/download/windows/).

**Comment by apolyton** [comment]
I've manually set the Postgresql local client to the binary path of 9.6. Same results occur.

**Comment by schmied** [comment]
I get the same error, a database restore fails with various environments: dbeaver builtin, pg9.6, and pg11

**Comment by SteveOswald** [comment]
I also have this issue in various enviroments.

**Comment by uslss** [comment]
cannot reproduce it for now. if it is still actual - feel free to reopen the issue
