### ISSUE TITLE
Inconsistent colors in grid view for Colorize Data Types

### ISSUE THREAD

**Issue by mdahlman** [dbeaver/dbeaver#6104]
#### System information: 
- Operating system: MacOS Mojave
- DBeaver version: CE 6.1.0.201906091949
- Java version: openjdk-12.0.1.jdk

#### Connection specification:
- Database name and version: PostgreSQL 11
- Driver name: postgresql-42.2.5.jar (standard driver)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
There seem to be inconsistent colors applied to result sets viewed in a grid. I'm using entirely default settings, as far as I know. I turned on Colorize Data Types.
Expected: all numbers are blue
Actual: some numbers are in blue, some are in black.
I don't really understand the pattern for which numbers are in which color.

#### Steps to reproduce, if exist:
self-contained query which works on PostgreSQL:
```
select 20 as "a", 1 as "b", 'row1' as row_label
union all select 15, 3, 'row2'
union all select 15, 2, 'row3'
union all select 9, 1, 'row4'
union all select 8, 2, 'row5'
union all select 6, 2, 'row6'
union all select 5, 6, 'row7'
union all select 4, 5, 'row8'
union all select 4, 1, 'row9'
union all select 3, 1, 'row10'
```

I suspect that it's not related to PostgreSQL... but I have not tested with other technologies.

![Screen Shot 2019-06-14 at 9 40 23 AM](https://user-images.githubusercontent.com/2158311/59524843-b9c6fb80-8e89-11e9-817d-da40e2378294.png)

**Comment by z6epo** [comment]
Tested with Sample database (SQLite), works as expected
OS : W10
DBeaver Version : CE 6.1.0.201906091949
![2019-06-20_13h03_23](https://user-images.githubusercontent.com/44536005/59844693-cfda2d80-935b-11e9-8dd0-60c21f3c71e8.png)

**Comment by mdahlman** [comment]
Huh. Thank you for testing. I tried another database technology. I get the same inconsistent coloring on Oracle:
![Screen Shot 2019-06-21 at 8 25 00 AM](https://user-images.githubusercontent.com/2158311/59933346-28620700-93fe-11e9-83aa-3114cbe9198b.png)

I suppose it could be linked to MacOS as @uslss has tagged it.

**Comment by marchrius** [comment]
Same here, same version with Dark theme and default theme with Theme system disabled

![Schermata 2019-06-25 alle 14 29 09](https://user-images.githubusercontent.com/534837/60098398-c71b9a00-9755-11e9-85bf-a0820abbce0b.png)
![Schermata 2019-06-25 alle 14 26 48](https://user-images.githubusercontent.com/534837/60098399-c71b9a00-9755-11e9-9e49-e88f0c3cf63a.png)

**Comment by serge-rider** [comment]
This is definitely a Mac-specific issue. Trying to find some logic in this glitch..

**Comment by serge-rider** [comment]
That's some kind of magic. I still have no clue how does it happen. I can't even understand the pattern. It is somehow related to row numbering.

At the moment my only assumption is that it is some MacOS rendering cache.
Any ideas would be very appreciated.

**Comment by sutolaci** [comment]
On version 7.0.4, MacOS X, sqlite database it is working as expected. Shall I make any modification on the configuration?
![Screenshot 2020-04-28 at 14 01 56](https://user-images.githubusercontent.com/3977964/80485016-f512d180-8958-11ea-977b-88a5f2ab2056.png)

**Comment by Andrew0002** [comment]
I just ran across this issue yesterday while doing queries on one of our SQL Server db's at work. I'm a new DBeaver user. I'm on MacOS 11.0.1 (Big Sur) and I'm on DBeaver 7.3.0.202011291229. 

Out of curiosity I loaded the current community version on Windows and was _not_ able to reproduce the issue. I did, however, find something interesting while tinkering with the Mac version. May or may not be helpful for someone doing debugging. 

- Go to Preferences > User Interface > Appearance > Colors and Fonts
- Expand "Database Query Results"
  - Set "Selection foreground" to a color that will stand out. I used blue #0432FF.
  - Set "Grid header foreground" to a color that will stand out. I used magenta #FF40FF.

With this config, you would expect all the row headers to be magenta, the selected cell contents to be blue, and other cells to be their default.

When you run the query from the original post, you'll see that sometimes the Grid Header color is applied to cells. Sometimes, when cells are selected that contain the same number as a row number, the Selection Foreground color gets applied to the row header. 

I do see a pattern to what's happening (see below). 

<img width="317" alt="Screen Shot 2020-12-08 at 1 13 23 PM" src="https://user-images.githubusercontent.com/1099466/101530213-3b9cc580-3957-11eb-8af9-c5dce20edb69.png">

For first row through last row...
{
- For each cell, column 1 through n 
  - Has a cell with same value been drawn before (Including header cells)? 
_Note: I'm assuming the current row's header is not drawn yet_
    - Yes: use same color as last time.
    - No: is the current cell selected?
      - Yes: use "selected" fore color
      - No: use default fore color
- Render header cell for current row.
  - Has a cell with same value been drawn before (including cells on this row)?
    - Yes: use same color as last time.
    - No: use default header fore color

}

I agree with the earlier assessment that this seems to be a caching issue. Whether it's in the application itself or the framework being used is beyond my knowledge.

**Comment by flambchap** [comment]
It really turned out to be a caching problem. Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
