### ISSUE TITLE
Couldn't connect to Oracle

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6107]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version EA 6.1.1

#### Connection specification:
- Database name and version Oracle 12
#### Describe the problem you're observing:
Error appears when trying to connect to Oracle.
![image](https://user-images.githubusercontent.com/31996417/59568304-95357400-9081-11e9-8ff4-3c5c6cfd1951.png)

There is no any info in log.

**Comment by serge-rider** [comment]
Fixed. It was a bad JDK11 bundle (java.security.* modules were missing)

**Comment by uslss** [comment]
verified
