### ISSUE TITLE
Error when trying to delete column

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6108]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version ea 6.1.1

#### Connection specification:
- Database name and version - doesn't matter

#### Describe the problem you're observing:
Shown on gif.
![npe](https://user-images.githubusercontent.com/31996417/59568674-9a48f200-9086-11e9-83e7-4460aa58eddd.gif)

#### Steps to reproduce, if exist:
1. Open any table
2. Try to delete column
#### Include any warning/errors/backtraces from the logs
[test.txt](https://github.com/dbeaver/dbeaver/files/3294494/test.txt)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
