### ISSUE TITLE
Error appears when trying to disconnect from db if any object from db is opened

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6109]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version EA 6.1.1

#### Connection specification:
- Database name and version - doesn't matter

#### Describe the problem you're observing:
Error appears when trying to disconnect from db if any object from db is opened
![image](https://user-images.githubusercontent.com/31996417/59568741-8ce03780-9087-11e9-8f93-c2d926142ea1.png)

#### Steps to reproduce, if exist:
1. Connect to db
2. Open any object for editing (F4)
3. Disconnect from DB

![image](https://user-images.githubusercontent.com/31996417/59568759-b9944f00-9087-11e9-97cd-2cc55f271075.png)

#### Include any warning/errors/backtraces from the logs
[error_on_disconnect.log](https://github.com/dbeaver/dbeaver/files/3294498/error_on_disconnect.log)

**Comment by serge-rider** [comment]
This seems to be a side effect of #6108 (navigator tree became corrupted after incorrect object delete handling).

**Comment by uslss** [comment]
fixed. verified
