### ISSUE TITLE
geometry column type for postgres 

### ISSUE THREAD

**Issue by TimNZ** [dbeaver/dbeaver#6110]
#### System information: 
- Operating system (distribution) and version
OS X 10.14.5
- DBeaver version
6.1.0 Community
#### Connection specification:
- Database name and version
Postgres 11.3
Drivers: 
org.postgresql - 42.2.5
net.postgis: 2.3.0

#### Describe your question:
When I do 'Create new column' via the UI in [table] -> Properties -> Columns, neither 'geometry' or 'geography'  are listed as column types.

Is this intentional?

**Comment by uslss** [comment]
as a workaround column type can be filled in manually

**Comment by uslss** [comment]
verified

**Comment by krlicmuhamed** [comment]
@uslss I have a similiar issue, however If I enter column data type as geography, I get `Bad data type name specified`...
[Image](https://i.imgur.com/4DDF4Kp.png)

**Comment by LonwoLonwo** [comment]
Hello @krlicmuhamed 
That version of DBeaver are you using?
Do you have PostGIS extension on Postgres?
Is geography type in the list of data types when create a column?
