### ISSUE TITLE
Float type is incorrectly shown for PostgreSQL databases

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6111]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version EA 6.1.1

#### Connection specification:
- Database name and version PostgreSQL and Postgre-like dbs (e.g. Redshift)
#### Describe the problem you're observing:
Float numbers are shown incorrectly for postgre-like databases. 
For example, 0.3 is shown as 0.30000001192092896
![image](https://user-images.githubusercontent.com/31996417/59596743-f7818980-9100-11e9-80b5-d85034b742f3.png)

**Comment by uslss** [comment]
Reopen. Issue is still reproducible for two-digits and more numbers

**Comment by serge-rider** [comment]
Please write more details

**Comment by uslss** [comment]
For example, 2.3 stays 2.3, but if i enter 13.3 it becomes 13.3000002
![float_is](https://user-images.githubusercontent.com/31996417/60402065-ce4a0a00-9b92-11e9-8fb6-038486c8e0d4.gif)

**Comment by serge-rider** [comment]
Thanks. Fixed.
I had to fix very base numeric formatter behavior. 

Please check how float4/float8 values are formatted. It also makes sense to test this this on Oracle and MySQL.

**Comment by uslss** [comment]
verified.
Tested in PostgreSQL (float4, float8), MySQL (float), Oracle (float)
