### ISSUE TITLE
[bug] Renaming a materialized view from the database navigator fails because of `materialized` keyword missing

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6112]
dbeaver `6.1.0.201906091949`

Trying to rename a materialized view in the DB Navigator (left part) by pressing F2 and choosing a different name, generates this sql preview
`ALTER VIEW old_name RENAME TO new_name;`
fails with
`ERROR: "old_name" is not a view`
Problem is: it is a *materialized* view.

Correct statement should be 
`ALTER MATERIALIZED VIEW old_name RENAME TO new_name;`

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
