### ISSUE TITLE
Is there a way to change the preferences where closing the window doesn't exit the app?

### ISSUE THREAD

**Issue by daniel9x** [dbeaver/dbeaver#6114]
#### System information: 
- Mac OSX
- DBeaver 6.1.0

#### Connection specification:
- PostgreSQL 10.6

#### Describe your question:

I'm a relatively new DBeaver user and have enjoyed the app so far. However I find it a little jarring that "closing" the app doesn't just push it to the background. Most of my MAC apps do this by default. I'm wondering if there's a way to change a preference to only being able to close the app by right+click->QUIT like with most of my other ones.

**Comment by uslss** [comment]
sorry for the late response.
@daniel9x is it still actual?

**Comment by uslss** [comment]
there is not any update on the issue for a long time.
If the issue is still actual for you - feel free to reopen the ticket
