### ISSUE TITLE
Cannot resolve project dependencies

### ISSUE THREAD

**Issue by kaelte** [dbeaver/dbeaver#6115]
#### System information: 
- Operating system: macOS 10.14.5 Mojave
- DBeaver version: 06c447644a - (HEAD, tag: 6.1.0) Color settings dialogs fix (NPEs)
- Java version "1.8.0_112"

#### Describe the problem you're observing:
The built has been failing for all versions newer as 6.0.1.

#### Steps to reproduce, if exist:
```
git pull
git checkout 6.1.0
mvn package
```

#### Include any warning/errors/backtraces from the logs
```
mvn package
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: org.jkiss.dbeaver:org.jkiss.utils:2.1.93-SNAPSHOT @ /Users/klaus/GIT/dbeaver/bundles/org.jkiss.utils/pom.xml
[INFO] Resolving dependencies of MavenProject: org.jkiss.dbeaver:org.jkiss.utils:2.1.93-SNAPSHOT @ /Users/klaus/GIT/dbeaver/bundles/org.jkiss.utils/pom.xml
[INFO] Resolving class path of MavenProject: org.jkiss.dbeaver:org.jkiss.utils:2.1.93-SNAPSHOT @ /Users/klaus/GIT/dbeaver/bundles/org.jkiss.utils/pom.xml
[INFO] Computing target platform for MavenProject: org.jkiss.dbeaver:org.jkiss.wmi:2.0.103-SNAPSHOT @ /Users/klaus/GIT/dbeaver/bundles/org.jkiss.wmi/pom.xml
[INFO] Resolving dependencies of MavenProject: org.jkiss.dbeaver:org.jkiss.wmi:2.0.103-SNAPSHOT @ /Users/klaus/GIT/dbeaver/bundles/org.jkiss.wmi/pom.xml
[INFO] Resolving class path of MavenProject: org.jkiss.dbeaver:org.jkiss.wmi:2.0.103-SNAPSHOT @ /Users/klaus/GIT/dbeaver/bundles/org.jkiss.wmi/pom.xml
[INFO] Computing target platform for MavenProject: org.jkiss.dbeaver:org.jkiss.dbeaver.slf4j:1.0.0-SNAPSHOT @ /Users/klaus/GIT/dbeaver/plugins/org.jkiss.dbeaver.slf4j/pom.xml
[INFO] Resolving dependencies of MavenProject: org.jkiss.dbeaver:org.jkiss.dbeaver.slf4j:1.0.0-SNAPSHOT @ /Users/klaus/GIT/dbeaver/plugins/org.jkiss.dbeaver.slf4j/pom.xml
[INFO] {osgi.os=win32, osgi.ws=win32, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.jkiss.dbeaver.slf4j 1.0.0.qualifier
[ERROR]   Missing requirement: org.jkiss.dbeaver.slf4j 1.0.0.qualifier requires 'bundle org.slf4j.api 0.0.0' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.jkiss.dbeaver:org.jkiss.dbeaver.slf4j:1.0.0-SNAPSHOT @ /Users/klaus/GIT/dbeaver/plugins/org.jkiss.dbeaver.slf4j/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

**Comment by mlt** [comment]
Note ideal, but workaround https://stackoverflow.com/a/56676957/673826

**Comment by mlt** [comment]
There is also https://www.eclipse.org/lists/tycho-user/msg08177.html . So try downgrading Maven to 3.6.0

**Comment by loro2** [comment]
I had the same error on Windows, downgrading maven to 3.6.0 indeed did help.

**Comment by serge-rider** [comment]
I'll fix slf4j bundle config (it is actually not used yet so you can exclude it from Eclipse build for now).

**Comment by serge-rider** [comment]
But Maven 3.6.1 still isn't compatible with Tycho. 3.6.0 should be fine.

**Comment by kaelte** [comment]
The problem still persists:
```
$ mvn -V
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /opt/local/share/java/maven3
Java version: 1.8.0_112, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre
Default locale: de_CH, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"


$ mvn package

Missing requirement: org.jkiss.dbeaver.slf4j 1.0.0.qualifier requires 'bundle org.slf4j.api 0.0.0' but it could not be found
```
I do not want to dowgrad Maven as I do not know whether this will have further side effects.
What is `Tycho`? Will it become compatible with Maven 3.6.1?

For the time being I keep on using DBeaver 6.0.1.

**Comment by elonlo** [comment]
thanks, to me fine, downgrading maven to 3.6.0

**Comment by brossaip** [comment]
I had the same problem and compiling with maven 3.6.0 solved the problem.
Thanks for the information!

**Comment by kaelte** [comment]
The issue seems to have been solved:
```
git pull
git checkout 6.2.0
mvn package
```
```
...
[INFO] tests 1.0.0-SNAPSHOT ............................... SUCCESS [  0.002 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:04 min
[INFO] Finished at: 2019-09-11T18:51:38+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by eiDear** [comment]
we can also upgrade maven to [maven-3.6.2](http://maven.apache.org/download.cgi) to package **_dbeaver_**:
`
$ cd dbeaver
$ mvn -v
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T23:06:16+08:00)
Maven home: **_{maven-dir}_**\apache-maven
Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: **_{jdk-dir}_**\jdk1.8.0_212\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

$ mvn package
...
[INFO] org.jkiss.dbeaver.ext.test 1.0.123-SNAPSHOT ........ SUCCESS [  0.239 s]
[INFO] tests 1.0.0-SNAPSHOT ............................... SUCCESS [  0.000 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:37 min
[INFO] Finished at: 2019-10-17T08:42:24+08:00
[INFO] ------------------------------------------------------------------------
`
