### ISSUE TITLE
Can't define a primary-key

### ISSUE THREAD

**Issue by wwhai** [dbeaver/dbeaver#6117]
When I  define a primary key,Dbever show such exceprion:
![image](https://user-images.githubusercontent.com/20577297/59663726-389d9a80-91e2-11e9-99ec-0f409dbb7fde.png)
![image](https://user-images.githubusercontent.com/20577297/59663747-43582f80-91e2-11e9-8a88-d4c7f7e19bf4.png)
Please help me.

**Comment by uslss** [comment]
you could read about your issue more here:
https://stackoverflow.com/questions/8645889/there-can-be-only-one-auto-column
