### ISSUE TITLE
Please support EnterpriseDB (EDB) derivative of PostgreSQL

### ISSUE THREAD

**Issue by rbellamy** [dbeaver/dbeaver#6118]
**Is your feature request related to a problem? Please describe.**
Please support EnterpriseDB (EDB) derivative of PostgreSQL

**Describe the solution you'd like**
EnterpriseDB has a derivative of PostgreSQL which includes the following challenges when working with ANY database tool OTHER THAN pgAdmin4, and specifically for DBeaver:

1. Custom JDBC connection URL - in DBeaver you MUST create customer driver based on the "Generic" type. In order to leverage the already excellent PostgreSQL support, a new model with a custom JDBC connection URL is needed.
2. EnterpriseDB has packages, PostgreSQL does not.
3. EnterpriseDB has complex types that PostgreSQL does not, including collection types (`TABLE` and `ARRAY`) and composites (`OBJECT` types with fields of type `TABLE`).
4. EnterpriseDB has a custom implementation of the Oracle
PL/SQL language implemented as an overlay to pgSQL called SPL.

**Describe alternatives you've considered**
I tried creating a custom driver definition of type "PostgreSQL" with a URL Template of `jdbc:edb://{host}:{port}/{database}` and using the `com.edb.Driver` JDBC driver class. DBeaver throws an exception, which turns out to be because it ends up using `jdbc:postgresql://{host}:{port}/{database}` instead.

**Additional context**
I understand that items 2 through 4 above are a significantly heavy ask. However, using the PostgreSQL JDBC driver with EDB is not a viable option, as it has additional functionality which can cause unexpected behavior for "normal" PostgreSQL operations. DBeaver's PostgreSQL support is already robust and useful, and if I want to be able to use the EDB JDBC driver with DBeaver, I see no other alternative than to provide a custom `PostgreEdbModel` implementation.

**Comment by garyshell** [comment]
This would be VERY useful to me.  Our current testing doesn't expose editing of functions and procedures.  Beyond that support of packages would be appreciated as well.

**Comment by uslss** [comment]
Done in the scope of #6135
