### ISSUE TITLE
[bug] DBeaver flooding .xsession-errors - Ubuntu mate 18.04

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6123]
Attaching `.xsession-errors` for today.
DBeaver version 6.1.0.201906091949

[DBeaver-.xsession-errors-.log](https://github.com/dbeaver/dbeaver/files/3306210/DBeaver-.xsession-errors-.log)

**Comment by uslss** [comment]
Cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket
