### ISSUE TITLE
Eclipse Color Theme does not keep theme after restart

### ISSUE THREAD

**Issue by angelotodaro** [dbeaver/dbeaver#6125]
#### System information: 
- Windows 10 Enterprise 10.0.17134
- 6.1.0.201906091949
- Eclipse Color Theme

#### Describe the problem you're observing:
When I choose a different color theme it stays for the entire time that I am currently using the application, however whenever I close and restart the application the editor colors default back to what they were. I'm using the Dark Theme under Preferences -> General -> Appearance with the Default for Color and font theme.

#### Steps to reproduce, if exist:
Change color theme using Preferences -> General -> Appearance -> Color Theme and then restart the application.

**Comment by mc51** [comment]
I can confirm this using the same setup @angelotodaro

**Comment by uslss** [comment]
Cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket
