### ISSUE TITLE
Filtering Data of numerical field in Data-View doesn't work properly because of thousend seperator

### ISSUE THREAD

**Issue by yennor** [dbeaver/dbeaver#6126]
#### System information: 
- Debian Linux Buster (10)
- Dbeaver: 6.1.0
- Java version: 1.11-71

#### Connection specification:
- Database name and version
Postgresql 11+200+deb10u1
- Driver name
PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
When opening the data-view of a Table and then Clicking on the Filtering Symbol of a numerical Column, I can enter the number I want to filter for by keyboard, it will jump in the list of all the available numbers to the correct number. But if the number has more than 3 Figures, it doesn't work. Because of the thousend seperator with which the numer is display. When I enter the number WITH the thousand seperator i.e. '1.234' instead of '1234', then it does find the proper number

#### Steps to reproduce, if exist:
See above

**Comment by serge-rider** [comment]
Numeric columns mist be filtered as numbers. No groupings are needed for that.
Thanks for the bug report, see fix in the next version.

**Comment by uslss** [comment]
verified
