### ISSUE TITLE
I can't edit cell on a resultset

### ISSUE THREAD

**Issue by Tiger136500** [dbeaver/dbeaver#6127]
I having this problem with DBeaver6.1 for linux.it's not a readonly oracle connection,if I try to  execute `select * from SYS.DICTIONARY;` and i can edit this result ,but when i select myself database  just like `select  *  from cs.test;`,i can't edit the result and the button of SAVE、CANCEL、Script was disabled,but if i press F4 when cursor is on table name,after that ,whatever i executed,that result can be modified

**Comment by Tiger136500** [comment]
and it's happens only in version 6.1

**Comment by p91paul** [comment]
There was a bug in 6.1, you should upgrade to the latest version

**Comment by Tiger136500** [comment]
> There was a bug in 6.1, you should upgrade to the latest version
i had download 6.0version DBeaver  and it's work
Thanks for your answer

**Comment by uslss** [comment]
Seems to be duplicate of #5957 
Closed.
