### ISSUE TITLE
Error foreign key mariadb

### ISSUE THREAD

**Issue by srRodolfo** [dbeaver/dbeaver#6130]
Error creating foreign key mariadb, in the update select no action and dbeaver changes to restricted every time.

I'm Brazilian, I'm using goole translator to write to you, thank you for the excellent program!

**Comment by serge-rider** [comment]
In MariaDB/MySQL ref action `RESTRICT` = `NO ACTION`, they are 100% equivalents.

https://dev.mysql.com/doc/refman/5.6/en/create-table-foreign-keys.html

So it is not a bug.

**Comment by srRodolfo** [comment]
Really friend you're right, thank you! =)
the mariadb link is https://mariadb.com/kb/en/constraint/
