### ISSUE TITLE
Import from flat text with bind variables

### ISSUE THREAD

**Issue by DriesSch** [dbeaver/dbeaver#6132]
Hello guys

I've been using DBeaver for quite a while now and enjoying it very much.
An older collegue of me still uses SQLTalk though. I'm trying to convince him to migrate to DBeaver, but he's not doing it, because he's in charge of migrating a lot of data for our customers.

To migrate the data he uses the following method
He gets a CSV file from our customers with a number of columns and rows which looks a bit like this:
"col1","col2","col3","col4"
"100000","B","0000001","ABC"
"200000","A","0000055","MLK"

He needs to import this into a table which has a lot more colums, the missing data he fills with data from older rows.
in SQLTalk he uses this syntax:

INSERT INTO TableName 
	SELECT TableCol0,
		TableCol1,
		TableCol2,
		TableCol3,
		'2019-07-01',
		TableCol5,
		TableCol6,
		TableCol7,
		TableCol8,
		TableCol9,
		TableCol10,
		:4,
		TableCol12,
		TableCol13,
		sysdate,
		USER 
	FROM TableName 
WHERE TableCol1= :1 AND TableCol2= :2 AND TableCol3= :3
\
"100000","B","0000001","ABC"
"200000","A","0000055","MLK"
/

As you can see, he copy/pastes the data from the CSV into the query, he executes it and binding the variables is done automatically by sqltalk.

Is there a way DBeaver can do it like this?

**Comment by DriesSch** [comment]
No one? :(

**Comment by serge-rider** [comment]
You can use Import Data->CSV on your table. Mark all columns which are no in CSV as `skip` on a mapping page:
![image](https://user-images.githubusercontent.com/6398845/65536922-f684a300-df0c-11e9-9223-14a0e02f97a7.png)

**Comment by DriesSch** [comment]
> You can use Import Data->CSV on your table. Mark all columns which are no in CSV as `skip` on a mapping page:
> ![image](https://user-images.githubusercontent.com/6398845/65536922-f684a300-df0c-11e9-9223-14a0e02f97a7.png)

Hey Serge,

Thanks for the response. This counts for INSERT though, can it do UPDATE too?

**Comment by kseniiaguzeeva** [comment]
It is not equal to UPDATE, but maybe will be useful too:
You can use "Truncate target table(s) before load" function (Import Data->CSV). Tthis will remove ALL data for the target table.
![CvBY5E6Uqj](https://user-images.githubusercontent.com/51405061/70889825-8447ca00-1ff4-11ea-8265-f39fcf77d349.png)

**Comment by uslss** [comment]
there is no update on an issue more than a month.
Ticket closed.
If the issue still actual - feel free to reopen the ticket
