### ISSUE TITLE
EDB extension

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6135]
Enterprise DB driver.

We need to:
- Get right driver download URL/maven repo
- Support packages

**Comment by rbellamy** [comment]
Unfortunately, EnterpriseDB does NOT make it easy to download its JDBC drivers. In almost every case, you must download some type of package. There is no "bare" JDBC jar file download, nor do they have a Maven repository. All JDBC downloads require a username/password and are under a proprietary license.

I'm not sure how you want to handle this - I've looked at the `plugins/org.jkiss.dbeaver.ext.oracle/plugin.xml` file, and I can see how you have things arranged there, and I think that's likely to be our best bet here.

https://www.enterprisedb.com/advanced-downloads
 
1. Windows - MSI or StackBuilder executable that installs the JDBC jar files onto the local file system.
  a. JDBC 11 'connectors' - https://sbp.enterprisedb.com/getfile.jsp?fileid=11437
  b. JDBC 11 postgis - http://get.enterprisedb.com/advstacks/edb-as11-postgis-2.5.0-1-windows-x64.exe
2. Linux - StackBuilder installer or RPM or SuSE native packages to install the JDBC jar files onto the local file system.
  a. YUM repo - https://yum.enterprisedb.com
  b. http://yum.enterprisedb.com/11/redhat/edb_11_redhat_rhel-7-x86_64.tar.gz => edb_11_redhat_rhel-7-x86_64.tar.gz/edb-as11-postgis-jdbc-2.2.1-6.x86_64.rpm/edb-as11-postgis-jdbc-2.2.1-6.x86_64.cpio/./usr/edb/as11/java/jdbc/postgis-jdbc-2.2.1.jar

**Comment by serge-rider** [comment]
We are in touch with EDB team. I hope we'll find some appropriate solution.

If no good solution will be found then we'll just do the same what we do for Oracle (manual driver download instructions).

**Comment by rbellamy** [comment]
We have some contacts at EDB that might be helpful, as well.

**Comment by dstegman** [comment]
In an effort to see if I could use an EDB driver with DBeaver, I am able to get it to connect to the server and run queries.  It's definitely snappier than Toad Edge (congrats on that).  The issues I am running into, and I know this isn't the driver you would supply so it would potentially be wonky, are:
- I can't view a list of functions.  There is a function drop-down under my schema (below tables), but when I click on the drop-down I see “Unsupported vector type: com.edb.util.PGobject”.
- Also I do not see packages or procedures, which EDB supports.

This is a pretty preliminary list, I don't do a lot of function/procedure/package creation or updating, so those are a lower priority for me, but others in our company do require the ability to create and edit those.

I am using edb-jdbc18-9.4.1212.1.jar for my driver file.

**Comment by emesar** [comment]
My experience so far has been pretty similar to @dstegman - got the JDBC .jar from EDB's website, and was able to setup the server connection. However, having the following issues:

- Viewing the function list for a schema gives the following error: `Can't read procedures: Unsupported vector type: com.edb.util.PGobject`. Pretty sure this is because it's attempting to lump the procedures in with the functions.
- I don't see any packages listed.

We use both procedures and packages somewhat frequently at my company, so support for them is needed. Also using the edb-jdbc18.jar for my driver file.

**Comment by LonwoLonwo** [comment]
Problem with “Unsupported vector type: com.edb.util.PGobject” fixed for EDB driver in DBeaver 21.3.0

But.
We changed the standard driver for EnterpriseDB connection on the PostgreSQL driver.
If you want to use EnterpriseDB driver:

1. Go to connection settings -> "Edit Drivers Settings" Dialog ->"Libraries" tab and delete PostgreSQL driver.
2. Add your driver with the "Add File" tab.
3. Change driver class with the "Find class" tab and drop-down list
4. Return to the "Settings" tab and change URL Template (replace "postgresql" on "edb")
5. Click the "OK" button.


![2021-11-18 17_31_03-DBeaver 21 2 5 - postgres](https://user-images.githubusercontent.com/45152336/142436372-5656c121-cf4e-421f-9059-83937ca652d6.png)

![2021-11-18 17_32_47-Connection _postgres 1_ configuration](https://user-images.githubusercontent.com/45152336/142436376-32be2f0b-bab7-4311-9e59-8c1b155a8351.png)

![2021-11-18 17_34_22-Connection _postgres 1_ configuration](https://user-images.githubusercontent.com/45152336/142436379-8a439e64-b179-4d83-b633-eac3997c3616.png)

Packages will be added to the [DBeaver Enterprise](https://dbeaver.com/) version.

**Comment by Matvey16** [comment]
Verified

**Comment by LonwoLonwo** [comment]
And still, the EDB driver is better. Returned it for an EDB connection.

**Comment by Matvey16** [comment]
Verified

**Comment by felipecrs** [comment]
Looks like they've improved it:

https://mvnrepository.com/artifact/com.enterprisedb/edb-jdbc

https://www.enterprisedb.com/docs/jdbc_connector/latest/installing/using_maven/

<img width="1868" height="711" alt="Image" src="https://github.com/user-attachments/assets/168dcf10-87df-4c3f-b588-8ced4e3f7874" />

**Comment by yeroc** [comment]
@felipecrs Yes, and the postgis extension is also published as well: https://mvnrepository.com/artifact/com.enterprisedb/edb-postgis-jdbc.
