### ISSUE TITLE
[bug] Saving a Script file "with name" does not rename title bar

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6136]
Ubuntu Mate 18.04
DBEaver 6.1.0.201906091949

Please refere to images.
Open a file, type something, save it with `File -> Save As`
Window title should change. It changes if i switch to another window, but not instantaneously.

Starting situation:
![Pre](https://user-images.githubusercontent.com/3930671/59911238-b8f71200-9413-11e9-99af-8d6b6f03f420.png)

After "save as":
![POST](https://user-images.githubusercontent.com/3930671/59911248-bdbbc600-9413-11e9-872c-027387fc330f.png)

**Comment by uslss** [comment]
Is issue still actual for you in the recent(6,2,3) version?

**Comment by wiwwo** [comment]
Yes

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
still reproducible

**Comment by serge-rider** [comment]
Also fixed for "Save As" action.

**Comment by uslss** [comment]
verified
