### ISSUE TITLE
export database from informix to postgresql 

### ISSUE THREAD

**Issue by yerrysherry** [dbeaver/dbeaver#6137]
Hello,

I use Version 6.1.0 on a Macbook. I export an Informix database to a PostgreSql database.

I select a table, right click "Export data" and choose "Database" and click on "Next". Then I choose the "Columns" button.

When the source type is of "Text", the dbeaver propose "json" for the source type of PostgreSql. I think it should also "Text". 

Regards,
Gerrit

**Comment by yerrysherry** [comment]
Sorry, bytea

Error occurred during public.actie_aanpak data load

Reason:
SQL Error [42804]: Batch entry 0 INSERT INTO public.actie_aanpak (actiea_id,actie_id,jaar,tekst,wijz_l_d,wijz_l_user)
VALUES (3,3,2000,?,'2001-05-04 +02','CLAEYSSV  ') was aborted: ERROR: column "tekst" is of type json but expression is of type bytea
  Hint: You will need to rewrite or cast the expression.
  Position: 103  Call getNextException to see other errors in the batch.

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there are not any updates on issue. Ticket will be closed.
If issue is still actual for you - feel free to reopen the ticket
