### ISSUE TITLE
I cant create procedures on editor

### ISSUE THREAD

**Issue by jesusferm** [dbeaver/dbeaver#6138]
#### System information: 
- Fedora 30 x86_64, with gnome
- DBeaver version 6.1.0

#### Connection specification:
- MariaDB from xampp 10.3.15-MariaDB

#### Describe your question:

I cant create procedure directly in editor, in versión 6.0, its works this query:

CREATE PROCEDURE obtTotalImgBo(id_bol INT)
BEGIN
	select count(id) as total from hj_img_bol where bol_id = id_bol;
END;

when i execute the query, show this error:

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1064] [42000]: (conn:1770) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 3

in versión 6.0, not necesary use delimiter, but in 6.1.0, i added delimiter, but not work, i use the assistan procedure create.

**Comment by serge-rider** [comment]
I can't reproduce this. Procedure can be create without an issue.
Maybe this is related to the driver version. I use MariaDB driver 2.6.0

**Comment by uslss** [comment]
there are not any updates on ticket for a long time.
If issue is still actual for you - feel free to reopen the ticket
