### ISSUE TITLE
Snowflake: time datatype values not shown correctly

### ISSUE THREAD

**Issue by egoryainova** [dbeaver/dbeaver#6139]
#### System information: 
- Operating system (distribution) and version: **Windows 10 Enterprise 17763.503, version 1809**
- DBeaver version: **6.0.2.201904071344**
- Java version: 
- Additional extensions

#### Connection specification:
- Database name and version: **SNOWFLAKE**
- Driver name: **Snowflake-JDBC-3.7.0.jar**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **No**

#### Describe the problem you're observing:
I created table with column of TIME data type. Then I generated values for this column, also of time data type. When I run SELECT * FROM TABLE1, I see correct values for TIME column in Snowflake but in DBeaver, the column shows an offset of 18 hrs, for example, when I see 00:00:00 in Snowflake, I see 18:00:00 in DBeaver.

#### Steps to reproduce, if exist:
1) Create table TABLE1 with column of TIME data type. 
2) Insert rows into the table 
3) Run SELECT * FROM TABLE1
4) Check results in Snowflake and DBeaver. 
    Expected behavior: values should match 
    Actual behavior: Snowflake shows correct values whereas DBeaver shows incorrect values

**Comment by uslss** [comment]
Cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket
