### ISSUE TITLE
JasperSoft SQL parameters format support

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6140]
jaspeSWe need to support SQL variables in JasperSoft SQL format ($P{...} or $P!{...} )
That's quite easy to support. Extra config option also makes sense.

https://community.jaspersoft.com/documentation/tibco-jaspersoft-studio-user-guide/v60/using-parameters-queries

**Comment by smatherx** [comment]
Hello, is this feature still working? I get the following message when calling a sql statement with jasper parameter.

select
raw.*
from
(select 'Test' testdata) raw
where
$P{testcall} like testdata

![jasper_parameter_error](https://user-images.githubusercontent.com/95544640/208693548-7604056b-b2ae-4fad-8df8-ac7788bd1167.png)

Thank you
