### ISSUE TITLE
Output tab no longer displays Postgresql messages in 6.1.0

### ISSUE THREAD

**Issue by drewed** [dbeaver/dbeaver#6141]
#### System information: 
Metric | Value
-------|-------
OS|Mac OS 10.14.5
DBeaver Version|6.1.0.201906091949 Community Edition
Java Version|OpenJDK 64-Bit Server VM Corretto-8.212.04.2 (build 25.212-b04, mixed mode)
Extensions|None

#### Connection specification:
Metric | Value
-------|-------
Database Name and Version|PostgreSQL 10.4
Driver Name|PostgreSQL standard driver (org.postgresql:postgresql:RELEASE [9.4.1212.jre7] and net.postgis:postgis-jdbc:RELEASE [2.2.1]
Tunnels or Proxies|None

#### Describe the problem you're observing:
When I run a function on the server which uses the raise statement to log messages to the client, I don't see those messages in the output window in DBeaver.  I confirmed that the client_min_messages is set appropriately and that the command line psql tool shows the expected messages so it appears to be a DBeaver bug.

#### Steps to reproduce, if exist:
Run the following:
```sql
set client_min_messages = log;
do $$
begin
    raise log 'Testing...testing...1, 2, 3...';
end;
$$;
```

#### Include any warning/errors/backtraces from the logs
No relevant information in the logs.

**Comment by serge-rider** [comment]
I can't reproduce this:
![image](https://user-images.githubusercontent.com/6398845/59993803-ddd8c880-9651-11e9-9e99-131298b0cf2d.png)

**Comment by drewed** [comment]
I did a clean boot and upgraded to 6.1.1.  Output is now visible.  Probably and inconsistent state on my machine.  Thank you for looking into it.
