### ISSUE TITLE
Visual bug on GTK3 / ArchLinux

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6142]
All navigator tree elements for colored connections types are overflow the tree (ignoring horizontal scroll).
Seems to be a GTK3 but we still need more testing on our side.

**Comment by jsivak** [comment]
This issue has seemed to resolved itself. Some of the system packages that have been updated on my system include:

    Java 12     	
    linux 5.1.16     	
    gtk3 (3.24.10-1)  	
    gtk-update-icon-cache (3.24.10-1)

I’m guessing the gtk3 3.24.10 update might be the “solution”?

**Comment by serge-rider** [comment]
@jsivak Thanks for the information. Yes, this might be a solution.
