### ISSUE TITLE
change DBeaver timezone(influxdb)

### ISSUE THREAD

**Issue by seven1oe** [dbeaver/dbeaver#6144]
#### System information: 
- Operating system (distribution) and version
Windows 10 LTSB 2016
- DBeaver version
6.1
- Java version
1.8 

#### Connection specification:
- Database name and version
influxdb-1.7.6
- Driver name
bundle?

#### Describe the problem you're observing:
I think it is influxdb's problem.
But I  can not change the query statement.
Even worse，Dbeaver will auto add `LIMIT` in the end of the statement.
I can not add `tz('')` in the statement because it will cause error!
I just edit `com.dbeaver.ee.influxdb.exec.executeStatement()` and it works.

#### Emmm
`queryString = queryString + " LIMIT " + this.getLimit() + " tz('" + System.getProperty("user.timezone") + "')";`

**Comment by flykarry** [comment]
can you share your compiled jar for me?
