### ISSUE TITLE
NumberFormatException displayed when part of a type is empty

### ISSUE THREAD

**Issue by cedricpineau** [dbeaver/dbeaver#6145]
#### System information: 
- Operating system (distribution) and version : Up to date Linux Mint
- DBeaver version - DBeaver 6.0 to DBeaver 6.1.1 standalone CE tar.gz
- Java version : Embbeded in dbeaver standalone CE
- Additional extensions : None

#### Connection specification:
- Database name and version : Postgresql 10
- Driver name : PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no 

#### Describe the problem you're observing:
NumberFormatException displayed when part of a type is empty.
(Same error as reported on the last comment of this closed issue : https://github.com/dbeaver/dbeaver/issues/5370)

#### Steps to reproduce, if exist:
CREATE TYPE MyType AS (
  id TEXT,
  value INT
);

CREATE TABLE MyTable (
  id TEXT PRIMARY KEY,
  mytype MyType
);

INSERT INTO MyTable VALUES ('row1', null);
INSERT INTO MyTable VALUES ('row2', '("type2",42)');
INSERT INTO MyTable VALUES ('row3', '("type3",)');
INSERT INTO MyTable VALUES ('row4', '("type4",0)');

SELECT * FROM MyTable;

#### Include any warning/errors/backtraces from the logs

![NumberFormatException_on_empty_type_part](https://user-images.githubusercontent.com/540325/60020398-3c249c00-9690-11e9-9f38-6a84e8937c0d.png)

**Comment by cedricpineau** [comment]
I fixed the problem with this patch :

[NumberFormatException_on_empty_type_part_patch.txt](https://github.com/dbeaver/dbeaver/files/3320928/NumberFormatException_on_empty_type_part_patch.txt)

With this result :

![Fix-NumberFormatException_on_empty_type_part](https://user-images.githubusercontent.com/540325/60021157-bd306300-9691-11e9-8c53-04c527239c31.png)

**Comment by serge-rider** [comment]
@cedricpineau Thanks for the detailed bug report!
The actual fix is a bit more complicated but generally idea is the same.

**Comment by uslss** [comment]
verified
