### ISSUE TITLE
Cant connect to some mysql servers in 6.1.1 version

### ISSUE THREAD

**Issue by alexsmff** [dbeaver/dbeaver#6146]
#### System information: 
- Operating system (distribution) and version - Windows 10 
- DBeaver version - 6.1.1
- Java version - 11
- Additional extensions

#### Connection specification:
- Database name and version  - avesha_piardroid
- Driver name - mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  - no

#### Describe the problem you're observing:

Hi!
thanks for you great product. I've noticed, that I can't connect to mysql server, while previous version connect without problems.

**Comment by flerxu** [comment]
You are not walking alone.

**Comment by serge-rider** [comment]
Most likely it is a result of JDK11 migration.
Could you provide a bit more information?
Debug log file would be very useful - https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by alexsmff** [comment]
You can reproduce this
server name - avesha.mysql.tools
db - avesha_piardroid
user - avesha_piardroid

**Comment by serge-rider** [comment]
It is no reproducible in the latest build.
Please check this in the Early Access version (https://dbeaver.io/files/ea)

**Comment by serge-rider** [comment]
If anybody had issues with MySQL/SSH/SSL connectivity in 6.1.1 - please try EA version (see above) and write some note about the results.

**Comment by alexsmff** [comment]
Same error in 6.1.2

Connection to 'avesha_piardroid' was lost and cannot be re-established.
What do you want to do?

Причина:
 Could not create connection to database server. Attempted reconnect 3 times. Giving up.

Could not create connection to database server. Attempted reconnect 3 times. Giving up.
  Communications link failure

The last packet successfully received from the server was 28 milliseconds ago.  The last packet sent successfully to the server was 28 milliseconds ago.
  Communications link failure

The last packet successfully received from the server was 28 milliseconds ago.  The last packet sent successfully to the server was 28 milliseconds ago.
    Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
    Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.

server - avesha.mysql.tools
db - avesha_piardroid

**Comment by serge-rider** [comment]
@alexsmff I can connect to it without any issues using 6.1.2, 6.1.1 or earlier versions. 
And there are no any SSH/SSL settings so even if it doesn't work - it is unrelated to Java version upgrade.
Could you post debug log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by alexsmff** [comment]
Where are no errors in log file. It's a connection error. Can I somehow export connection config from dbeaver?

**Comment by serge-rider** [comment]
These still have to be in dbeaver-debug.log file. 
Any error messages/screenshots would be helpful.
BTW does it work if you downgrade to 6.1.0?

**Comment by alexsmff** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3348983/dbeaver-debug.log)
Here is my debug log

Yes, in 6.1.0 everything is fine, problems only with 6.1.1 and 6.1.2 versions

**Comment by serge-rider** [comment]
Thank you.

This error looks like a general network error (e.g. firewall timeout). Maybe you need to use different server IP address/host name. 
At the moment I can't figure out how this can be related to DBeaver version. Maybe Java11 has different network addresses resolution configuration. But I'm not aware of that.

Could you try to install Java8 on your machine and delete folder `jre` in DBeaver 6.1.2 install directory (C:/Program Files/DBeaver/jre). If this will help then problem is definitely in Java version and we'll try to find some solution.

**Comment by alexsmff** [comment]
In last release everything is working now, thanks!
