### ISSUE TITLE
Columns, order in touple is not as requested

### ISSUE THREAD

**Issue by cerebel** [dbeaver/dbeaver#6147]
Windows 7
 DBeaver_CE 6.1.1 ( in 6.1.0 is ok)  / [ AdoptOpenJDK (64bit) 11.0.3   or  jdk1.8.0_212_x64 ]
 Oracle JDBC driver [12.1.0.2.0] , Oracle 12
  (no error log , trace sql is ok )

sql> with t as (select 1 a, 2 b, 3 c from dual) select c,b,a, c,b,a from t

After second execution, the result is (the columns)   "cc bb aa", instead "cba cba"

**Comment by GiannisDimitriou** [comment]
@uslss  This bug is not only specific for oracle. 
I am experiencing the same behaviour with PostgreSQL as well, though it seems not database specific like issue.

**Comment by serge-rider** [comment]
Thanks for the bug report. Th problem was caused by multiple columns with the same name.

**Comment by uslss** [comment]
verified

**Comment by JMarkMurphy** [comment]
Still see this:
![image](https://user-images.githubusercontent.com/2379218/60723594-0f7b4a80-9f02-11e9-9ebb-b3dbb9258798.png)

 Notice that CONTACTID and ADDRESSID have same sequence number, but the metadata for the resultset looks like this:
![image](https://user-images.githubusercontent.com/2379218/60723725-6ed95a80-9f02-11e9-9361-09a66e6fa851.png)

**Comment by serge-rider** [comment]
@JMarkMurphy I don't know how to reproduce this. What kind of query produces this result? What driver?
What do you see in data viewer (i.e. does this error happen only in filter settings dialog)?

**Comment by JMarkMurphy** [comment]
Driver is jt400 (DB2 for i).
This only happens in the filter settings dialog. Here is a query and result set that you can query on any IBM i machine (like pub400.com).

![image](https://user-images.githubusercontent.com/2379218/60736837-77dc2300-9f26-11e9-924e-78b077402d37.png)

Everything looks good here, but when I go into filter settings, I see:

![image](https://user-images.githubusercontent.com/2379218/60736883-9cd09600-9f26-11e9-96e8-446819296548.png)

Table name has the same sequence number twice, and sequence #4 is missing.
