### ISSUE TITLE
Can't connect to PostgreSQL via SSL

### ISSUE THREAD

**Issue by marcospgp** [dbeaver/dbeaver#6148]
Using version 6.1.1 (latest at time of writing)

I'm trying to connect to a PostgreSQL on Digital Ocean but always get the same error: `SSL error: handshake_failure`.

I have tried many different variations of the settings but to no avail. For example, I set SSL to true and the mode to require, ignoring the other fields, and I get the error.

I tried using PGAdmin and the connection is successful with the exact same configuration (turning SSL on with mode "require" and not specifying anything else when it comes to certificates and whatnot).

I wanted to use DBeaver but I can't seem to get past this error.

Thanks!

Edit: I have tried setting the SSL factory as mentioned here https://github.com/dbeaver/dbeaver/issues/2133#issuecomment-328644614

I have also tried editing the SSL settings on the driver settings directly, instead of just turning SSL on in the SSL tab.

**Comment by flerxu** [comment]
Same error on windows platform. My postgresql server is 11.4 on linux .

**Comment by NekoKoneko** [comment]
Same error even with the direct connection w/o SSL.
DBeaver Community 6.1.1
Postgres 11.4 on Ubuntu 18.04.2.

PS. Downgrading to 6.1.0 fixed the problem.

**Comment by appsnporras** [comment]
got the same error for 6.1.1
downgraded to 6.1.0 made it work again?

**Comment by serge-rider** [comment]
Seems to be a result of Java 11 migration..

**Comment by serge-rider** [comment]
Actually I can't reproduce the issue on Windows 10.
Could you post error/debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files) with this error?

**Comment by NekoKoneko** [comment]
[6.1.1.zip](https://github.com/dbeaver/dbeaver/files/3329506/6.1.1.zip)

DBeaver 6.1.1  (clean install, no .dbeaver* or .eclipse folders in home)
Direct PostgreSQL connection - SSH and SSL are disabled
Windows 10 x64 1903
PostgreSQL 11.4
Ubuntu 18.04.2

**Comment by AndrewKhitrin** [comment]
Hello all.

We checked the SSL connection in version 6.1.1 on our dev environment with self-signed certificate and sslmode verify-ca and it works.

Can you give us more detail about connection mode and cert types (encription strength etc).

Thanks,
Andrew.

**Comment by appsnporras** [comment]
I get the error even if I don't have ssl enabled using DBeave4 6.1.1
Client: Windows 10 1903 x64
Server: Ubuntu 18 04 PostgreSQL 11

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by serge-rider** [comment]
@appsnporras this is because of SSH tunnel issues I think.
Anyway, this looks like this issue: https://support.cloudbees.com/hc/en-us/articles/115003785531-SSL-handshake-failures-due-to-incompatible-Cipher-Suite

Perhaps this happens because we didn't enable Unlimited Stgength Policy in the bundled JDK 11.
Trying to figure out how to fix this..

**Comment by serge-rider** [comment]
@NekoKoneko according to the log you have SSL enabled. This is odd as I don't see ssl settings in your datasoures.xml file.
Maybe SSL is required by the server-side.
Anyhow this seems to be the same problem as in other cases - lack of encryption configuration in JDK11.

**Comment by serge-rider** [comment]
Please check how it works in Early Access version (https://dbeaver.io/files/ea/).
JDK build was enhanced with extra encryption modules.
Note: only Windows installer was patched.

**Comment by flerxu** [comment]
Here is the log file.

**Comment by flerxu** [comment]
Here is the log file
[dbeaver4.zip](https://github.com/dbeaver/dbeaver/files/3330174/dbeaver4.zip)

**Comment by flerxu** [comment]
> Please check how it works in Early Access version (https://dbeaver.io/files/ea/).
> JDK build was enhanced with extra encryption modules.
> Note: only Windows installer was patched.
Here is the log file.
[dbeaver4.zip](https://github.com/dbeaver/dbeaver/files/3330177/dbeaver4.zip)

**Comment by flerxu** [comment]
> Please check how it works in Early Access version (https://dbeaver.io/files/ea/).
> JDK build was enhanced with extra encryption modules.
> Note: only Windows installer was patched.

Here is the log file.
[dbeaver4.zip](https://github.com/dbeaver/dbeaver/files/3330180/dbeaver4.zip)

**Comment by flerxu** [comment]
> Please check how it works in Early Access version (https://dbeaver.io/files/ea/).
> JDK build was enhanced with extra encryption modules.
> Note: only Windows installer was patched.

6.1.2 EA works well, thanks!

**Comment by NekoKoneko** [comment]
> Please check how it works in Early Access version (https://dbeaver.io/files/ea/).

Connecting successfully in EA 6.1.2, thanks!

**Comment by serge-rider** [comment]
@flerxu @NekoKoneko thanks for testing!
