### ISSUE TITLE
Toggle Database Navigator

### ISSUE THREAD

**Issue by jdmcfadden-usx** [dbeaver/dbeaver#6150]
We can assign a keystroke to the Show View (Database Navigator) command to quickly get to the Database Navigator. Any chance we could get a toggle so we could hide it again quickly? Right now, it's a mouse operation or several keystrokes.

**Comment by uslss** [comment]
shortcut could be assigned in preferences
![image](https://user-images.githubusercontent.com/31996417/140028120-c0ae6a06-fffe-46dc-b1fe-a426faf2ec0f.png)
