### ISSUE TITLE
It create two sessions for one Hive client

### ISSUE THREAD

**Issue by wangyum** [dbeaver/dbeaver#6152]
#### System information: 
- DBeaver version: 5.2.4

#### Connection specification:
- Hive version: 3.1.1

#### Describe the problem you're observing:

It create 2 sessions for one client.

#### Steps to reproduce, if exist:
1. Start Hive thriftserver:
```
bin/hiveserver2
```
2. Connect Hive thriftserver:
![image](https://user-images.githubusercontent.com/5399861/60078237-1bc31300-975e-11e9-816f-2901b05b63a5.png)
3. Check the Hive thriftserver web UI:
![image](https://user-images.githubusercontent.com/5399861/60078317-4d3bde80-975e-11e9-92a6-6a62af793d11.png)

**Comment by uslss** [comment]
if issue is still actual for you - feel free to reopen the ticket
