### ISSUE TITLE
Right click -> SET to empty string

### ISSUE THREAD

**Issue by murat-mehmet** [dbeaver/dbeaver#6153]
**Is your feature request related to a problem? Please describe.**
I can't set multiple NULL fields to empty string. On normal cells there's Edit > SET to NULL on the context menu.

**Describe the solution you'd like**
 It would be really great to have SET to Empty String.

**Describe alternatives you've considered**
There's no alternative that works, at least I could not find. I tried copy paste but an empty string cannot be copied. advanced copy/paste also failed, it always pasted column header to the field, or nothing at all.

**Comment by ChStark** [comment]
It would also be nice to add a "Generate UUID" option on this context menu as well [Right Click -> Edit -> Generate UUID] as an alternative to [Menu->Edit->Generate UUID]

**Comment by serge-rider** [comment]
Sounds like a good feature.
And it is easy to implements.

**Comment by serge-rider** [comment]
@ChStark UUID is more tricky. Because most databases do not have special data type for it (and bind value generation to a data type).

**Comment by uslss** [comment]
verified
