### ISSUE TITLE
User grant view bug at MySQL

### ISSUE THREAD

**Issue by dmitrygribenchuk** [dbeaver/dbeaver#6154]
Hello! I have some strange behavior when with user privileges.
System information:
    Operating system (distribution) and version: Debian GNU/Linux 9.9 (stretch)
    DBeaver version: 6.1.1.201906240635

Connection specification:
    Database name and version: MySQL (Percona) 8.0.15
    Driver name: MySQL 8+
    Do you use tunnels or proxies (SSH, SOCKS, etc)? yes

When I create user by copy/paste from another server I can't see user grant at GUI and view all grants via command  SHOW GRANTS FOR 'user'@'host';

**Comment by john9x** [comment]
I can confirm this issue.
Dbeaver 6.1.0 showing user grants fine but 6.1.1 and later not.
All checkboxes is clear.

Windows 10

**Comment by dmitrygribenchuk** [comment]
It's not reproduced on 6.1.3
