### ISSUE TITLE
Can't connect to SQL server using DBEaver 6.1.1

### ISSUE THREAD

**Issue by equeinne** [dbeaver/dbeaver#6155]
#### System information: 
- Ubuntu 18.04
- DBeaver version 6.1.1
- Java version 1.8

#### Connection specification:
- SQL Server
- Driver name: SQL Server old driver: net.sourceforge.jtds.jdbc.Driver
- Do not use tunnels or proxies 

#### Describe the problem you're observing:
After upgrade to 6.1.1 my connection to SQL Server do not work
Tried different versions 1.2.6 -> 1.3.1
drivers properties show me in a red color 
repo:/drivers/jtds/SSO/x86/ntlmauth.dll
repo:/drivers/jtds/SSO/x64/ntlmauth.dll

**Comment by serge-rider** [comment]
Please post debug error log - https://github.com/dbeaver/dbeaver/wiki/Log-files
Perhaps this is a result of JDK11 migration.

**Comment by equeinne** [comment]
I succeed to connect still using java 8 so I close the issue.
I switched jdk 8 or 11 to debug. Maybe was bad jdk installation. Do not reproduce the problem.

**Comment by serge-rider** [comment]
Please check latest Early Access version (https://dbeaver.io/files/ea/). It contains fixed Java bundle.

**Comment by serge-rider** [comment]
Hoever it is fixed for Windows only.
We do not ship JDK for Linux versions. Anyhow, any additional information (e.g. log file) would be very helpful.

**Comment by uslss** [comment]
ticket closed
there is no update more than a month.
If issue stiil actual for you feel free to reopen the ticket or create a new one
