### ISSUE TITLE
 How to turn off backquote when column auto-complete

### ISSUE THREAD

**Issue by zChimera** [dbeaver/dbeaver#6157]
How to turn off backquote when column is auto-complete when using mariaDB

SELECT A.\`column_1\` FROM table

**Comment by augusto-marcelo** [comment]
Same problem here using MySQL. Did you found out any solution to disable that?

**Comment by uslss** [comment]
For now, suggested columns aren't backquoted by default.
Seems the issue is obsolete

**Comment by flzpenteado** [comment]
I am using the  21.3.1.202112130652 version, and backquotes are enabled by default, and I cannot disable it!
PS: I'm on MacOs
