### ISSUE TITLE
See the row information when hovering the mouse over a foreign key reference

### ISSUE THREAD

**Issue by ChStark** [dbeaver/dbeaver#6158]
**Is your feature request related to a problem? Please describe.**
This feature request is not a problem, is a nice to have kind of request. Sometimes when I am navigating data, I don't want to click on a foreign key reference to load the data in a different window.

**Describe the solution you'd like**
It would be nice to see the information hovering the mouse over the reference (the little blue square with the arrow) so no navigation is needed and I can keep reading the information of the current row.

**Describe alternatives you've considered**
Working with navigation, but is ugly and is easy to lose the track of the information you are analyzing.

**Comment by uslss** [comment]
seems to be related with #10765
