### ISSUE TITLE
Is it possible/feasible to support a Non-JDBC database that only communicates through gRPC ?

### ISSUE THREAD

**Issue by ChStark** [dbeaver/dbeaver#6159]
#### System information: 
- Operating system (distribution) and version : Any
- DBeaver version: 6.1.1

#### Connection specification:
- Database name and version
Dgraph 1.0.15

#### Describe your question:
I see the main focus of dbeaver is to provide a general framework to work with database and their respective JDBC driver, not all emergent database work with JDBC. Is it possible to support a database that uses gRPC for the interaction?

Thanks in advance

**Comment by serge-rider** [comment]
Of course.
DBeaver already supports databases like Cassandra, Mongo, Redis, DynamoDB, WMI and others by using their native Java API (most of them are in EE versin though).

However you can check how WMI connector (it is in community version) works to see general approach for non-JDBC drivers.
