### ISSUE TITLE
[PostgreSQL] Autocompletion doesn't works in select queries

### ISSUE THREAD

**Issue by dudul08** [dbeaver/dbeaver#6160]
Hi,
I updated DBeaver from 5.3.3 to 6.1.1 version.
Since  this update, there is this issue : the autocompletion for the field selection doesn't works in 6.1.1.

![autocompletion_ok_5 3 3](https://user-images.githubusercontent.com/16609450/60158596-b7ea2a00-97f1-11e9-88d0-eb2d4691ee81.PNG)
![autocompletion_no_ok_6 1 1](https://user-images.githubusercontent.com/16609450/60158595-b7ea2a00-97f1-11e9-8fc2-59477e4c782d.PNG)

I tested with other version : with 6.0.0.201903101945 version it's ok but for next version it's not ok. 

Windows 10
java 1.8

Thank you for your help.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
