### ISSUE TITLE
[PostgreSQL] Missing `;` in schema comment

### ISSUE THREAD

**Issue by rbovard** [dbeaver/dbeaver#6162]
Hi there,

In the source DDL for a schema, a `;` is missing:
* `COMMENT ON SCHEMA <schema> IS '<comment>'` > `COMMENT ON SCHEMA <schema> IS '<comment>';`

Best!

**Comment by dorbae** [comment]
This problem does not happen to me. Could you explain your environment? ex) DBeaver version, JDK version and so on.

<img width="527" alt="스크린샷 2019-06-26 20 56 53" src="https://user-images.githubusercontent.com/25657896/60177999-4e036c00-9855-11e9-8d0e-5f4591330705.png">

**Comment by rbovard** [comment]
Oh sorry.

DBeaver 6.1.0
Java 1.8
Windows 7

![image](https://user-images.githubusercontent.com/4549666/60178501-fa286100-981b-11e9-965b-a5cdff67063a.png)

**Comment by serge-rider** [comment]
Thanks for the bug report.
It will be fixed in the next version.

**Comment by uslss** [comment]
verified

**Comment by rbovard** [comment]
Thanks a lot!
