### ISSUE TITLE
Ordering by Available\Used  Size in Tablespace view for Oracle doesn't take account of orders of magnitude

### ISSUE THREAD

**Issue by BillAdama** [dbeaver/dbeaver#6163]
Hi,
speaking of Oracle (not teseted with other RDBMs), when you order the tablespaces by Available or Used size, it doesn't take account of orders of magnitude, so 100MB is greater of 10GB.
Can you please fix this?

Thanks you!

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified

**Comment by BillAdama** [comment]
Thank you for fixing but how do I change this option?
