### ISSUE TITLE
sql editor does not allow to scroll down

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#6164]
Editors are allow to scroll until last line:

![_](https://user-images.githubusercontent.com/799021/60197749-b39d2b80-9848-11e9-9965-961695127d6b.jpg)

but dbeaver restrict to scroll down until I add empty lines to the end of text

![_2](https://user-images.githubusercontent.com/799021/60197782-c9aaec00-9848-11e9-8657-73d19f0f06b4.jpg)

I highlight manually added lines. You can see that scroll bar at the bottom already

**Comment by uslss** [comment]
will be resolved in #10950
