### ISSUE TITLE
[help] whats Invalid status 72 stand for？

### ISSUE THREAD

**Issue by icedrowning** [dbeaver/dbeaver#6165]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 6.1.0.201906091949

#### Connection specification:
- Database name and version hive

#### Describe your question:
When i test connection to databases, it shows invaild status 72.
I dont know whats code 72 stands for ? And how to solve it?

**Comment by uslss** [comment]
is it still actual?

**Comment by willbenica** [comment]
@uslss, I'm running into this same issue. Should I open a new issue, or should I reopen this one. Happy to provide more information, as I am running into this currently.

**Comment by maurerle** [comment]
I have the same issue connecting to a HDFS on Port 50070 with Apache Spark
using: `jdbc:hive2://server:50070`

A suggestion found here:
https://community.cloudera.com/t5/Support-Questions/Hive-http-transport-mode-problem/m-p/136747/highlight/true#M99396
suggests to add custom transportmode params, but I don't know how to do it in dbeaver
