### ISSUE TITLE
Extract DCL along with DDL

### ISSUE THREAD

**Issue by lacanoid** [dbeaver/dbeaver#617]
Using Postgres, but it might well apply elsewhere too.

Extract DCL (GRANT and ALTER SET OWNER) together with DDL definitions for an object.
This would make it much more copy-paste friendly, as well as allowing for admin to 
see a more complete definition of an object.

Now it's quite easy for DCL to get lost, should one have to DROP table, for example,
or copy it to another database by just by running generated SQL.

For Postgres in particular, this would have to involve setting the object owner with
ALTER SET OWNER, as the object owner can be notably different from the object schema.

**Comment by lacanoid** [comment]
It would be kind of nice, if comments were included as well.

**Comment by serge-rider** [comment]
This was already done for Oracle.

**Comment by HeadLessX** [comment]
+1 on the comments in DDL tab (also mentioned in https://github.com/dbeaver/dbeaver/issues/720 )

**Comment by serge-rider** [comment]
For PostgreSQL we already support both DCL and comments (for columns and for table itself).
If you mean some other database - please create a separate ticket (each database has its own syntax for that).

Closing this legacy ticket.
