### ISSUE TITLE
remove element from er diagram (or the whole diagram)

### ISSUE THREAD

**Issue by martijintro** [dbeaver/dbeaver#6170]
because of no forum i ask here: how to remove an element from the er digram or the whole one? can't see any options...

-> 

https://i.ibb.co/NKBb1MM/Unbenannt.jpg

regards, j

**Comment by martijintro** [comment]
I've found the "problem" - the er diagrams will be created from the database directly, so the elements will be gone if i delete them on DB..

**Comment by tati-kru** [comment]
You can create a custom ER-diagram (https://github.com/dbeaver/dbeaver/wiki/Custom-Diagrams) and edit it as you need. You can delete or add tables including tables from other databases.
