### ISSUE TITLE
Shortcut CTRL+S (save) stops working after a long time

### ISSUE THREAD

**Issue by AdrianoBortoloto** [dbeaver/dbeaver#6172]
#### System information: 
- Microsoft Windows 10 Pro 10.0.18362 Compilação 18362
- DBeaver 6.1.1.201906240635
- Java version 1.8.0_211
- No extensions

#### Connection specification:
- PostgreSQL 10.6
- org.postgresql.Driver 9.4.1212.jre7
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
The shortcut CTRL+S (save) stops working after a long time (~2h). If dbeaver is restarted, works again during a few hours. I don't know if have any other action related to this problem besides the time that dbeaver keep opened.

**Comment by Depariel** [comment]
This has been happening to me too. It's very frustrating.

**Comment by uslss** [comment]
is this still actual for you?

**Comment by Depariel** [comment]
It is for me, yes. I've already encountered it today.

**Comment by bluelurker** [comment]
This is very annoying. It happened to me as well. Save works through the File menu but not with Ctrl + S shortcut. I'm using version 6.3.0.201912042122

**Comment by rakstar** [comment]
Came to report this. Good to know I'm not alone. I noticed this for a while, upgraded to 6.3.2.202001051908 today and still have the issue. I'm on KDE neon User Edition 5.17, Ubuntu 18.04.  It works again after restarting the application.

**Comment by codism15** [comment]
This also happens for me, using 6.0.4 on Win 8. When it happens, the other CTRL- hotkeys work fine. Also, the issue seems isolated to individual tabs - I just closed the one that CTRL-S was not working and realized CTRL-S in the remaining tabs works fine.

**Comment by Bschitter** [comment]
Happens to me also on Windows 10 with version 6.3.2. Seems to happen as AdrianoBortoloto said after DBeaver is opened for a long time. Noticed it with Ctrl+S and Ctrl+Insert.

**Comment by jmaster92** [comment]
I had the same problem, but I found that's happend with a large file. This file, includes larger lines with chars that appear due encoding errors. For each Ctrl + S in the file, more incorrect chars was saved, until the file made so long that linter line reading not working and Ctrl+S doesn't nothing. What if the DBeaver team put the UTF8 encodding by default from installation?

**Comment by bluelurker** [comment]
The issue still persists in Version 6.3.4.202002011957

**Comment by com-squidbit** [comment]
I'm facing the very same issue.
Using version 6.2.2.201910061950.

**Comment by saravegga** [comment]
I also have this issue on the latest version.

**Comment by serge-rider** [comment]
Does this happen in SQL editor only or in the table data editor too?

I think it is definitely not related to the dbeaver uptime. It seems to be a result of some performed actions (opened dialogs, executed commands, etc).

**Comment by bluelurker** [comment]
I found the problem only in the SQL Editor. Can I run dbeaver in debug mode to generate logs?

**Comment by bluelurker** [comment]
If it helps anyone, as a workaround, you can enable "Save editor on query execute" under Preferences-> Editors-> SQL Editor. Works fine so far.

**Comment by renezito** [comment]
The same problem.
Windows 10 Pro
Language: Español (Latinoamérica)
Keyborard: Latinoamericano
DBeaver 7.0.0

Inclusive, if I go to File / Save then sql file is still with the asterisk (*).

I uploaded an mp4 file compressed.

Thanks.

[DBeaver no graba.zip](https://github.com/dbeaver/dbeaver/files/4397166/DBeaver.no.graba.zip)

**Comment by renezito** [comment]
> The same problem.
> Windows 10 Pro
> Language: Español (Latinoamérica)
> Keyborard: Latinoamericano
> DBeaver 7.0.0
> 
> Inclusive, if I go to File / Save then sql file is still with the asterisk (*).
> 
> I uploaded an mp4 file compressed.
> 
> Thanks.
> 
> [DBeaver no graba.zip](https://github.com/dbeaver/dbeaver/files/4397166/DBeaver.no.graba.zip)

I noticed that after close Dbeaver it doesn't ask me to save the file... then I check the file and Dbeaver saved it, but doesn't remove the asterisk... Check by your own.

**Comment by robobobeng** [comment]
Same issue here (Windows 7, DBeaver Community edition 7.0.2)

**Comment by uslss** [comment]
duplicates #4483
