### ISSUE TITLE
Data grid editing disabled in DBeaver 6.1.1, Oracle 12.1.0.2.0

### ISSUE THREAD

**Issue by JasonConeHM** [dbeaver/dbeaver#6173]
#### System information: 
- macOS 10.14.5
- DBeaver 6.1.1
- Java 1.8

#### Connection specification:
- Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production
- Drivers:
  - ojdbc7.jar
  - xdb6.jar
  - orai18n.jar
- No tunnels or proxies

#### Describe the problem you're observing:
Symptomatically identical to https://github.com/dbeaver/dbeaver/issues/5957, but I didn't want to expand the conversation in that issue due to its version-specific nature.

Essentially, data grid values are effectively read-only. I have to downgrade to DBeaver 5.3.5 to regain the functionality to edit data grid values.

The data grid editor functionality works fine with both Postgres 10.9 and Redshift 1.0.8187 (Postgres 8.0.2).

#### Include any warning/errors/backtraces from the logs
When attempting to execute the queries that @AndrewKhitrin provided in #5957, I get the following error for all attempts:
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1467] [72000]: ORA-01467: sort key too long

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2778)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Attempting to execute the same queries with DBeaver 5.3.5 results in the same error.

**Comment by JasonConeHM** [comment]
As a follow-up, I failed to mention that there are no other log entries that would speak to this issue.

**Comment by AndrewKhitrin** [comment]
Hello @JasonConeHM !

You have try this query (with your OWNER and TABLE of course)  :

> SELECT 
> 	c.TABLE_NAME,
> 	c.CONSTRAINT_NAME,
> 	c.CONSTRAINT_TYPE,
> 	c.STATUS,
> 	c.R_OWNER,
> 	c.R_CONSTRAINT_NAME,
> 	(SELECT rc.TABLE_NAME FROM ALL_CONSTRAINTS rc WHERE rc.OWNER = c.r_OWNER AND rc.CONSTRAINT_NAME = c.R_CONSTRAINT_NAME) AS R_TABLE_NAME,
> 	c.DELETE_RULE,
> 	(
> 	    SELECT LTRIM(MAX(SYS_CONNECT_BY_PATH(cname || ':' || p,','))    KEEP (DENSE_RANK LAST ORDER BY curr),',') 
> 		FROM   (SELECT 
> 		               col.CONSTRAINT_NAME cn,col.POSITION p,col.COLUMN_NAME cname,
> 		               ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) AS curr,
> 		               ROW_NUMBER() OVER (PARTITION BY col.CONSTRAINT_NAME ORDER BY col.POSITION) -1 AS prev
> 		        FROM   ALL_CONS_COLUMNS col 
> 		        WHERE  col.OWNER ='DSU_ORGA' AND col.TABLE_NAME = 'OR_INSTANCE'
> 		        ) d  WHERE cn = c.CONSTRAINT_NAME 	GROUP BY cn	CONNECT BY prev = PRIOR curr AND cn = PRIOR cn START WITH curr = 1	    
> 	    ) COLUMN_NAMES_NUMS
> FROM
> 	ALL_CONSTRAINTS c
> WHERE
> 	c.CONSTRAINT_TYPE = 'R'
> 	AND c.OWNER = 'DSU_ORGA'
> 	AND c.TABLE_NAME = 'OR_INSTANCE'

?
`

**Comment by JasonConeHM** [comment]
> Hello @JasonConeHM !
> 
> You have try this query (with your OWNER and TABLE of course) :

@AndrewKhitrin: yes, I've tried that query and various versions of it (ensuring to use the correct owner/table names), but all result in the following error:
```
SQL Error [1467] [72000]: ORA-01467: sort key too long
```
This appears to be encountered by numerous 12c users, so if you can give me an idea of what you're looking for, perhaps I can come up with something that works in this case?

**Comment by AndrewKhitrin** [comment]
@JasonConeHM 

Thanks for clarifications can you execute this subquery :

> select col.CONSTRAINT_NAME cn,
> 			col.POSITION p,
> 			col.COLUMN_NAME cname,
> 			row_number() over (partition by col.CONSTRAINT_NAME 	order by	col.POSITION) as curr,
> 			row_number() over (partition by col.CONSTRAINT_NAME		order by	col.POSITION) -1 as prev
> 		from
> 			ALL_CONS_COLUMNS col
> 		where
> 			col.OWNER = 'DSU_ORGA'
> 			and col.TABLE_NAME = 'OR_INSTANCE'

with correct owner and tables and paste result here (if it possible) ?

**Comment by JasonConeHM** [comment]
@AndrewKhitrin: that works fine. Here's the output from the most simple table in our schema that I could find (even though the issue manifest for any/all tables/queries). I did, however, substitute the names for `PK_A` and `COL_B` so as to not leak any IP.

|CN|P|CNAME|CURR|PREV|
|--|-|-----|----|----|
|PK_A|1|ID|1|0|
|SYS_C002343002||ID|1|0|
|SYS_C002343003||COL_B|1|0|

**Comment by AndrewKhitrin** [comment]
@JasonConeHM 

Thank you very much for answers, can you help us to understand problem, please answer for question :

1. Does problem query works for this simple table (with PK_A and COL_B subs) ?

2. Can you execute this query :

```
SELECT 
    c.TABLE_NAME,
    c.CONSTRAINT_NAME,
    c.CONSTRAINT_TYPE,
    c.STATUS,
    c.R_OWNER,
    c.R_CONSTRAINT_NAME,
    (SELECT rc.TABLE_NAME FROM ALL_CONSTRAINTS rc WHERE rc.OWNER = c.r_OWNER AND rc.CONSTRAINT_NAME = c.R_CONSTRAINT_NAME) AS R_TABLE_NAME,
    c.DELETE_RULE,
    (
      SELECT LISTAGG(COLUMN_NAME || ':' || POSITION,',') WITHIN GROUP (ORDER BY "POSITION") 
      FROM ALL_CONS_COLUMNS col
      WHERE col.OWNER = 'FKS' AND col.TABLE_NAME = 'TBL_MAIN' AND col.CONSTRAINT_NAME = c.CONSTRAINT_NAME GROUP BY CONSTRAINT_NAME 
    ) COLUMN_NAMES_NUMS
FROM
    ALL_CONSTRAINTS c
WHERE
    c.CONSTRAINT_TYPE = 'R'
    AND c.OWNER = 'FKS'
    AND c.TABLE_NAME = 'TBL_MAIN'
```

but for "problem" owner\table wich give ORA-01467 and give us results.

Thanks,
Andrew.

**Comment by JasonConeHM** [comment]
@AndrewKhitrin:

> 1. Does problem query works for this simple table (with PK_A and COL_B subs) ?

No, the query @ https://github.com/dbeaver/dbeaver/issues/6173#issuecomment-506501746 fails with the "sort key too long" error when executed with the same owner/table that's used in the query @ https://github.com/dbeaver/dbeaver/issues/6173#issuecomment-506682476 (which succeeds).

> 2. Can you execute this query :

Yes, the query executes successfully using the same owner/table as above, but does not select any rows. If I remove the `c.CONSTRAINT_TYPE = 'R'` predicate, 3 rows are selected that are related to the same constraints that are documented @ https://github.com/dbeaver/dbeaver/issues/6173#issuecomment-506703745.

**Comment by JasonConeHM** [comment]
@AndrewKhitrin: just so that we're clear, the above behavior is identical between v5.3.5 and v6.1.1; I'm don't immediately see how this is related to the read-only behavior of the data grid in v6.1.1 vs. the read/write ability in v5.3.5.

**Comment by AndrewKhitrin** [comment]
@JasonConeHM 

Could you test the 6.1.2 version from early access (https://dbeaver.io/files/ea/) and report the results here in comments (whether the problem with ORA-01467  is fixed or not)

**Comment by JasonConeHM** [comment]
@AndrewKhitrin: the behavior is identical to 6.1.1 and 5.3.5; the query @ https://github.com/dbeaver/dbeaver/issues/6173#issuecomment-506501746 still fails with `SQL Error [1467] [72000]: ORA-01467: sort key too long`.

**Comment by AndrewKhitrin** [comment]
Now we have options "Simple constraints reading query" (available in EA only) in connection properties (Oracle Properties), can you download EA, enable it and check how it works.

![shot_ea](https://user-images.githubusercontent.com/25009233/60519852-0d8c6e00-9ced-11e9-94eb-d1e4bacb1527.PNG)

**Comment by JasonConeHM** [comment]
@AndrewKhitrin: the 6.1.2 EA build solved the originally-observed problem(s) - thanks!

I'll continue to use it and put it through its paces and will report any other observed issues in the form of new Issues.

Thanks for your diligence in looking into this! I have several other coworkers who will be most pleased with this fix.
