### ISSUE TITLE
PostgreSQL integer array column unavailable

### ISSUE THREAD

**Issue by marcospgp** [dbeaver/dbeaver#6176]
Using DBeaver 6.1.0

I'm trying to create an integer array column for a table in a PostgreSQL database, and can't seem to find the option. I have tried entering it manually and get an error, while interestingly an array of text (`text[]`) gets converted to `_text` when I press enter, and seems to be identified as a text array correctly.

Thanks!

**Comment by serge-rider** [comment]
In PostgreSQL data type _text stands for array of text. text[] is just another form of record.
You can set data type to int4[] manually (which is basically the same as _int4).

**Comment by tomislavhofman** [comment]
This is the error I get when I try to set it manually.

An error has occurred. See error log for more details.
Bad data type name specified: int4[]

**Comment by tomislavhofman** [comment]
_int8 works but _int4 throws the following error:

Error setting property 'dataType' value

Reason:
Bad data type name specified: _int4

**Comment by uslss** [comment]
cannot reproduce it for now.
column with _int4 type is successfully created using ui.

**Comment by smitt14ua** [comment]
@uslss try to update a value in already existed column, I have error when try this
