### ISSUE TITLE
Generated SQL is empty for data types

### ISSUE THREAD

**Issue by smithtim** [dbeaver/dbeaver#6178]
#### System information: 
- Operating system (distribution) and version: **MacOS Mojave 10.14.5**
- DBeaver version: **6.1.1**

#### Connection specification:
- Database name and version: **SQL Server**
- Driver name: **MS SQL Server / SQL Server**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **no**

#### Describe the problem you're observing:

When I right-click on any item under "Data Types" and choose "Generate SQL" --> "DDL", the generated SQL is empty except for a single semicolon.

Original ticket which was supposed to provide this functionality: #4414

**Comment by tony1223** [comment]
Same here and we need this feature,too. QQ

**Comment by kseniiaguzeeva** [comment]
implemented

**Comment by LonwoLonwo** [comment]
CREATE TYPE InventoryItem AS TABLE
(
    [Name] NVARCHAR(50) NOT NULL,
    SupplierId BIGINT NOT NULL,
    Price DECIMAL (18, 4) NULL,
    PRIMARY KEY (
        Name
    )
)

**Comment by kseniiaguzeeva** [comment]
Closed
