### ISSUE TITLE
MySql: Connection not auto-refreshed after long (2h and more) standby mode

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6181]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.1.1

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
Connection is not auto-refreshed after long (2h and more) standby mode. It works only after manual refreshing.
#### Steps to reproduce, if exist:
1. Connect to MySQL DB
2. Do not do anything in database 2 hours or more.
3. Try to open some object (db or tables catalog)
#### Include any warning/errors/backtraces from the logs
[mysql.txt](https://github.com/dbeaver/dbeaver/files/3338687/mysql.txt)

**Comment by serge-rider** [comment]
Connection recovery added to object property reader.

**Comment by uslss** [comment]
verified
