### ISSUE TITLE
Add "Output" to Show View

### ISSUE THREAD

**Issue by jakehell** [dbeaver/dbeaver#6185]
**Is your feature request related to a problem? Please describe.**
The only way to show the Output tab is to enter the shortcut ctrl + shift + o. It took a bit of time to figure this out.

**Describe the solution you'd like**
Would be much easier if the Output tab was available using Window -> Show View

**Additional context**
![image](https://user-images.githubusercontent.com/5951826/60364011-b6179680-99aa-11e9-9178-6c8dbe5b1632.png)
Nothing in the Show View window

**Comment by uslss** [comment]
![image](https://user-images.githubusercontent.com/31996417/101851755-344f0500-3b6d-11eb-89fe-be6bcc0f5c28.png)
Show output button is already available in SQL editor
