### ISSUE TITLE
Cannot click Auto Generated checkbox

### ISSUE THREAD

**Issue by jupelester** [dbeaver/dbeaver#6186]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 6.1.0.201906122139
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version: SQL Server 2016
- Driver name I don't know
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I'm trying to create an identity column in a new table. I right-clicked and selected "Create New Column" under the "Columns" tab. I started to fill out the attributes of the column: 
name: id
Type: int
Length: 4
Precision: 10
Not Null: Checked
Auto Generated: <Can't click it>

![image](https://user-images.githubusercontent.com/7945392/60368410-c5084400-99be-11e9-80bf-9debb5ace945.png)

**Comment by serge-rider** [comment]
Do you use SQL Server?
IF so then this issue is tracked in #6001

Thanks for the bug report anyway.

**Comment by jupelester** [comment]
Yes MSSQL. How should I read the link you provided? I couldn’t tell if you considered it a bug or a feature request there. Since it’s a pretty important capability and the UI seems to support adding identity, not being able to create an IDENTITY column is more of a bug than feature request. 

Is there an ETA for this to work? Thank you!
