### ISSUE TITLE
Geometry viewer always transforms to Earth-specific projection

### ISSUE THREAD

**Issue by rustprooflabs** [dbeaver/dbeaver#6190]
#### System information: 
- Operating system (distribution) and version:  Windows 10 Pro 64-bit
- DBeaver version:  6.1.1
- Java version:  11.0.3
- Additional extensions: 

#### Connection specification:
- Database name and version:  PostgreSQL 11.4, PostGIS 2.5
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

The amazing geometry viewer ([original issue](https://github.com/dbeaver/dbeaver/issues/4222)) appears to auto-transform all PostGIS data to 4326 without a way to disable the functionality.  It was suggested ([Twitter](https://twitter.com/dbeaver_news/status/1145222583564021760)) to change the SRID to hide the map but that truly does only hide the map.  It does not disable the transformation of the data before being visually represented.  It seems that adding a check on the SRID to see if it is valid before making the change might solve this issue.  Having an option to disable the overlay manually would also provide a real solution.

This issue makes the geometry viewer feature unusuable for use cases not bound to Earth.  A few examples of non-Earth use cases of PostGIS:

* Medical ([Howard Hughes Medical Institute case study](https://www.postgis.net/2018/11/03/howard_hughes/))
* Fictional worlds
* Space
* Example (teaching) data sets

#### Steps to reproduce:

In an empty database, create the PostGIS extension and a `points` table with 100 points from `(1, 1)` to `(100, 100)`.  While this intentionally exceeds the max North value on Earth (90 degrees), it
is valid data in non-Earth scenarios.

	CREATE EXTENSION IF NOT EXISTS postgis;

	DROP TABLE IF EXISTS points;
	CREATE TABLE points AS 
	SELECT ST_MakePoint(x, x) AS geom FROM generate_series(1, 100) x;

Verify the geometry data does not have an SRID set:

	SELECT DISTINCT ST_SRID(geom) FROM points;

	Name   |Value|
	-------|-----|
	st_srid|0    |

My expectation for a visualization of this data is a straight line as seen in this screenshot from QGIS:

![image](https://user-images.githubusercontent.com/3085224/60398550-df553580-9b16-11e9-8b9e-3ea5d9aef92f.png)

Following the suggestion to change the SRID, I found that does hide the map under the data but the visualization is obviously still bound by Earth's projection.  The curve of the northern ranges into the flat line is the indicator there.

![image](https://user-images.githubusercontent.com/3085224/60398557-f5fb8c80-9b16-11e9-8bf7-4cf157505894.png)

I would expect data without a valid SRID to not be transformed to any projection.   I like the auto-transfrom when you **know** the source but in an unknown that seems to be a risky guess.

**Comment by rustprooflabs** [comment]
I see it is being set to the default value [here](https://github.com/dbeaver/dbeaver/blob/339938cfd964d874356c4dde3061cd692edfdb72/plugins/org.jkiss.dbeaver.data.gis/src/org/jkiss/dbeaver/data/gis/handlers/GeometryAttributeTransformer.java).

        if (srid == 0) {
            srid = GisConstants.DEFAULT_SRID;
        }

Maybe a switch to disable that action?

**Comment by serge-rider** [comment]
Agreed. This looks more like a bug in one of latest versions.
We definitely have to have support for non-Earth based projections,

We could use:
1. Leaflet L.CRS.Simple layer (flat surface projection)
2. https://github.com/kartena/Proj4Leaflet (support of different CRSes on JS-side)

**Comment by serge-rider** [comment]
Fixed. For now we'll use Simple projection. 
Any unrecognized or projection or 0 will be treated as Simple projection. It can be changed in GIS viewer manually.

**Comment by uslss** [comment]
#6362

**Comment by uslss** [comment]
verified.
Created issue #6362
