### ISSUE TITLE
ERD palette icons issue

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6191]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.1.2
- Java version 11

#### Describe the problem you're observing:
ERD palette icons issues:
- check Use large icons -> shows no icons;
- switch to icons layout -> no items are shown
![pallete_iconsissue](https://user-images.githubusercontent.com/31996417/60401448-524bc400-9b8a-11e9-9712-24a33dd1d018.gif)

**Comment by serge-rider** [comment]
I've added "Large" icons - in fact they are just regular icons as we don't have large ones.
At least it fixes icons layout and other palette glitches

**Comment by uslss** [comment]
verified
