### ISSUE TITLE
Switching lines with JSON auto-format enabled throws OutOfBounds

### ISSUE THREAD

**Issue by gvburg** [dbeaver/dbeaver#6193]
#### System information: 
- Windows 10 x64 with DBeaver EE 6.1.0.201906122139
- Java SE Dev Kit 10.0.2
- No extensions

#### Describe the problem you're observing:
I downloaded the EE edition today, licenced last week, especially for the JSON viewer tool. With enabled JSON in the viewer and enabled auto-wrap, I was not able to switch between two JSON-containing fields. Upon switching from the 1st to a 2nd field, the preview got empty and stayed empty, until switching to another format or to a field containing non-JSON.

This is especially annoying when you are only working with the JSON-containing fields. One always has to click on a non-JSON field, and back to the next to switch field-previews.

Also the thrown errors create a really bad runtime.

#### Steps to reproduce, if exist:
Click on a JSON-containing field in a column with JSON format. Enable "JSON", "Word Wrap" and "Auto Format" in the preview settings. Click on another JSON-containing field without switching to non-JSON fields. Now the error's are thrown and the 2nd preview goes empty. As long as you don't go to another non-JSON field, the error's are thrown periodically and each time when changing fields, the preview stays empty.

#### Include any warning/errors/backtraces from the logs
[JSON-viewer-bug.log](https://github.com/dbeaver/dbeaver/files/3344309/JSON-viewer-bug.log)

**Comment by serge-rider** [comment]
Unfortunately I can't reproduce this problem. Columns switching works just fine with simple json values.

Most likely (and according to the log file) it is caused by some specific json content rendering. Coud you post an example of json field values which cause this issue?

**Comment by gvburg** [comment]
Of course, but to be exact: it's not column switching, it is row switching. I also attached a print screen. E.g. the first field contains:
`{
  "bday": "2017-10-04T00:00:00+02:00",
  "lang": "aa",
  "suffix": "Ms",
  "lastName": "Test",
  "firstName": "Monika"
}`

The second field right below contains:
`{
  "bday": "2018-10-24T00:00:00+02:00",
  "suffix": "MR",
  "lastName": "Test",
  "firstName": "Tobias"
}`

In the attached picture you see two actions, the first was clicking in row 12 column 2, 
![JSON-viewer-bug_action1](https://user-images.githubusercontent.com/49973492/60428566-67ac0700-9bf9-11e9-800b-cb38cfb89c33.png)
the second action was clicking in row 13 column 2 WITHOUT any other action in between, like switching columns or something. 
![JSON-viewer-bug_action2](https://user-images.githubusercontent.com/49973492/60428567-67ac0700-9bf9-11e9-8c80-cefe8a0e11d3.png)
NOTE: again, it is row switching related, not column switching.

**Comment by serge-rider** [comment]
I've reproduced this.
This bug appears only in Dark theme (some weird issue with text editor redraw). I'll try to find and resolve it.

Workaround: use Light or Classic theme.

Thanks for testing.

**Comment by serge-rider** [comment]
Another workaround: disable "word wrap" in dark theme. Looks like some internal bug in Eclipse dark theme renderer.

**Comment by gvburg** [comment]
I have not though of changing theme, thanks for the workaround. 

Word wrap unfortunately is really useful, especially when you deal with space-saving unformatted JSON, therefore I won't disable it. But maybe useful for others. Looking forward to the bugfix!

**Comment by serge-rider** [comment]
This issue seems to be fixed after we switched to the latest Eclipse platform version.
Please verify.

**Comment by gvburg** [comment]
I gladly confirm that in release 6.1.5 this issue has been fixed! In the dark theme of the released version 6.1.0 it's present but with disabling the theme I found a good workaround. Looking forward to the release!
