### ISSUE TITLE
Wrong BootLoader constants in the error log file

### ISSUE THREAD

**Issue by gvburg** [dbeaver/dbeaver#6194]
#### System information: 
- Windows 10 x64 with DBeaver EE 6.1.0.201906122139 (licensed, not trial)
- Java SE Dev Kit 10.0.2
- No extensions

#### Describe the problem you're observing:
I installed my DBeaver EE today with the installation file "dbeaver-ee-6.1.0-x86_64-setup.exe" downloaded from the x64 installer button on the website (especially because of the JSON viewer). When reporting a JSON viewer bug issue (see here: https://github.com/dbeaver/dbeaver/issues/6193), I checked the error logs and noticed, that the wrong BootLoader constants "OS=win32" are loaded. I double checked my 64x Windows by the way, and I am 100% sure about that. 

#### Steps to reproduce, if exist:
Open the error-log in DBeaver (see documentation here: https://github.com/dbeaver/dbeaver/wiki/Log-files). Export the log to your files. Open the file and check the first "SESSION" section.

#### Include any warning/errors/backtraces from the logs
[JSON-viewer-bug.log](https://github.com/dbeaver/dbeaver/files/3344299/JSON-viewer-bug.log) (the error's in the log are from the reported JSON viewer bug)

**Comment by serge-rider** [comment]
Well, it says OS=win32, ARCH=x86_64 so it seems to be correct. 
`win32` is generic name for all Windows-based architectures.

**Comment by gvburg** [comment]
I'm terribly sorry, that was uneducated from me.
