### ISSUE TITLE
Encoding ignored when exporting BLOBs

### ISSUE THREAD

**Issue by Evil2000** [dbeaver/dbeaver#6196]
#### System information: 
Windows 10 x64
DBeaver 6.1.1
Java 1.8.0.211
Office Ingetration Extension

#### Connection specification:
Firebird 2.5 
org.firebirdsql.jdbc:jaybird-jdk18:RELEASE (Version: 3.0.3)
Direct TCP connection

#### Describe the problem you're observing:
When exporting binary data stored in BLOBs and selecting "Base64" in the format settings, the data is still exported in hex.

#### Steps to reproduce, if exist:
Create a selection which selects BLOBs columns.
Right click the result and choose "Export result...".
Choose CSV or HTML and click Next.
In the "Format settings..." select "Inline" in the Binary data dropdown. Select Base64 as "Encoding". Click next and next.
Open the resulting file and checkt the exported values.
The BLOBs where exported as hex values, not as Base64 encoded strings.

#### Include any warning/errors/backtraces from the logs
No errors or warnings appear.

![grafik](https://user-images.githubusercontent.com/697191/60428452-1e5bb780-9bf9-11e9-9cc6-14455d48b31b.png)
![grafik](https://user-images.githubusercontent.com/697191/60428501-3c291c80-9bf9-11e9-967f-316155377559.png)
![grafik](https://user-images.githubusercontent.com/697191/60428545-57942780-9bf9-11e9-948a-dd47b0371c0b.png)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
