### ISSUE TITLE
Using Variable in where clause for export returns empty csv

### ISSUE THREAD

**Issue by BigMcLargeHuge** [dbeaver/dbeaver#6198]
Hi All,

I've noticed that using a variable to filter data in an export returns an empty csv like so:

`set @dsid := "abc-123"`
`select * from dealers where dataset_id = @dsid`

This of course returns data just fine within the DBeaver interface but it exports an empty set.  This seems related to [this issue.](https://github.com/dbeaver/dbeaver/issues/5635) But I can that issue #5635 is resolved while this is still outstanding.

Local OS: OSX 10.14.5
DBeaver Version: 6.1.1.201906240635
MySQL:
innodb_version	5.6.37-82.2
protocol_version	10
version	5.6.37-82.2-log
version_comment	MySQL Community Server (GPL)
version_compile_machine	x86_64
version_compile_os	Linux

**Comment by serge-rider** [comment]
You need to use different syntax:

```sql
@set varName = value
select * from dealers where dataset_id = ${varName};
```

or

```sql
@set varName = 'string-value'
select * from dealers where dataset_id = :varName;
```

**Comment by SCSVEL** [comment]
@serge-rider I did try exactly like you mentioned here but no luck. I am using V4.0.3. Is there any settings that should be changed?

**Comment by p91paul** [comment]
@SCSVEL you might need to upgrade if 4.0.3 is your DBeaver version, current version is 6.1.5
