### ISSUE TITLE
Not showing schema with Netezza

### ISSUE THREAD

**Issue by Buster452** [dbeaver/dbeaver#6199]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.1.0.201906091949
- Java version: 1.8.0_131
- Additional extensions

#### Connection specification:
- Database name and version: Netezza
- Driver name: nzjdbc.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
I don't see schemas anywhere.  Not in the database navigator, not anywhere.  We have schemas enabled and in use on our Netezza system.  Using other tools I can see these schema, but can't in DBeaver.

**Comment by Buster452** [comment]
Newly observed behavior since issue was initially reported.
I can create new schema in the database, I can then see all the schemas in that database.  If I close DBeaver and reopen an connect then I don't see the schemas.

Steps to reproduce
1. Connect to Netezza Server
2. Expand the tree in Database Navigator for your working database (whichever database you're messing around in).
3. Database Navigator might show just Tables, Views, Indexes, Procedures and Data Types under the database.
  3a. It should be showing a list of schemas below the database in Navigator before it lists the object types (Tables, views, indexes etc...).
  3b. If no schemas are showing, continue to 4.
4. Create a new schema in your database.
5. Right click on the database in navigator and "refresh".  
6. After refreshing, it will show all schemas in that database now.  Something it didn't do before.
7. Close and reopen DBeaver. 
8. Reconnect to your database on Netezza and look for the schemas.  They are no longer showing, but they are there when you query the Metadata.

**Comment by serge-rider** [comment]
Thanks for the bug report.
I think this is a result of enabled schema filters. We will disable them by default in the next version.

Workaround: disable this option in the driver settings dialog:
![image](https://user-images.githubusercontent.com/6398845/60686793-25115580-9eab-11e9-90f4-23476b04a195.png)

**Comment by uslss** [comment]
Verified.
Mentioned option in the driver settings dialog is disabled by default.
