### ISSUE TITLE
Values are duplicated in filter (Ctrl+F11) 

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6200]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.1.2 EA
- Java version 11

#### Connection specification:
- Database name and version PostgreSQL 11

#### Describe the problem you're observing:
Values are duplicated in filter (Ctrl+F11)  in case FK is used. More info in attached picture. Unused value ("6") isn't duplicated
![image](https://user-images.githubusercontent.com/31996417/60460367-3577c500-9c4c-11e9-93df-599746a58b09.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
