### ISSUE TITLE
PostgreSQL: tablespaces management

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6204]
We need to support tablespaces create/drop/edit.

Also we need to move Tablespaces folder to the database->Storage->Tablespaces (from database->System Info->Tablespaces).

**Comment by uslss** [comment]
Reopened.
1. Tablespaces folder isn't moved to the database->Storage->Tablespaces (from database->System Info->Tablespaces)
2. Taablespace couldn't be edited

**Comment by uslss** [comment]
verified
