### ISSUE TITLE
TimescaleDB connection in left panel and overall support

### ISSUE THREAD

**Issue by sergtop** [dbeaver/dbeaver#6205]
#### System information: 
- Operating system (distribution) and version: MacOS 10.15
- DBeaver version 6.1.1
- Java version 11
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name TimescaleDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Localhost

#### Describe the problem you're observing:
If I try to add a new connection to TimescaleDB it doesn`t appear in a connection list panel. Opening connection list to the main panel (F4 on Connection row) this TimescaleDB connection exists, but double click on it is not working. It is possible to open a script tab for this connection and write queries but not able to open Data/Properties tabs view for schemas and tables for this type of connection.

#### Steps to reproduce, if exist:
Add a new connection for TimescaleDB and try to use it

**Comment by serge-rider** [comment]
I can't reproduce this. Sounds like some kind of DBeaver internal error.
- Does this happen only with Timescale connections?
- Could you send error/debug logs? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by sergtop** [comment]
This TimescaleDB connection has appeared in the left panel after a couple of program restarts. After it appeared all newly added connections of TimescaleDB are working fine and all the features needed are also available. Seems like some internal problem that is fixable with restarts.

**Comment by serge-rider** [comment]
This still looks like a bug in DBeaver. Any log files would be very helpful, otherwise I can't realize what is wrong.

**Comment by sergtop** [comment]
This issue was not reproduced. Also tried on 6.1.2 - works fine. Sorry, but no logs from that moment are available.

**Comment by serge-rider** [comment]
Ok.
Thanks for testing
