### ISSUE TITLE
[mysql] SQL Error [S1009] on explain

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6206]
When running explain plan in read-only connection, error
`SQL Error [S1009]: Connection is read-only. Queries leading to data modification are not allowed.` is raised.

Obviously, `explain` is not a "data changing" query.

Example: use read only connection to mysql, run query
`explain select 1 from dual`

**Comment by serge-rider** [comment]
1. This is a server-side error, we can't affect this
2. In fact explain may change data. Usually database server has to save explain results somewhere (in temporary or permanent table) to let users read explain plan later. At least Oracle works like this.
