### ISSUE TITLE
[dbeaver v6.1.0] Error while backing up a Postgres database having schema with a specific name

### ISSUE THREAD

**Issue by anvuong** [dbeaver/dbeaver#6207]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04.2
- DBeaver version: 6.1.0
- Java version: 1.8.0_201
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 10.9
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: none

#### Describe the problem you're observing:
It's impossible to backup a schema with a specific name like "user", the error is as follow:
/usr/bin/pg_dump --format=c -n "\"user\"" --verbose --host=127.0.0.1 --port=31267 --username=smartlog stx
Backup started at Tue Jul 02 17:32:59 ICT 2019
pg_dump: last built-in OID is 16383
pg_dump: [archiver (db)] query failed: ERROR:  invalid regular expression: parentheses () not balanced
pg_dump: [archiver (db)] query was: SELECT oid FROM pg_catalog.pg_namespace n
WHERE n.nspname OPERATOR(pg_catalog.~) E'^(\\\\user\\)$'

#### Steps to reproduce, if exist:
- Right-click on a Postgres database → Tools → Backup
- On Backup wizard, select a schema with a specific name like "user", then press button "Start"
  [https://flic.kr/p/2gpnDbL](https://flic.kr/p/2gpnDbL)
- Backup will fail with error as shown in the following photo:
  [https://flic.kr/p/2gpo1vv](https://flic.kr/p/2gpo1vv)

#### Include any warning/errors/backtraces from the logs
I've digged into dbeaver's source code and think that commit "81ca0f014c254eb672f0cbe2e677c373980ec811" might cause the error.

In file "/src/org/jkiss/dbeaver/ext/postgresql/tools/PostgreBackupWizard.java", line 146 if I remove the call to function "escapeCLIIdentifier", then the backup can complete without any error.

**Comment by anvuong** [comment]
I'm sorry for providing incorrect url to the screenshot photos in "Steps to reproduce", the modified ones are:
On Backup wizard, select a schema with a specific name like "user", then press button "Start"
[https://flic.kr/p/2gpnDbL](https://flic.kr/p/2gpnDbL)

Backup will fail with error as shown in the following photo:
[https://flic.kr/p/2gpo1vv](https://flic.kr/p/2gpo1vv)

**Comment by nicoschl** [comment]
I also have the same problem and I was regularly using this feature until it broke. I see the OP has the version as 6.1.0, I can't verify that unfortunately. My error message differ slightly in the `WHERE` clause of the error message.

```/usr/bin/pg_dump --clean --create --format=c -n "\"data\"" --verbose --host=localhost --port=5432 ****** example
Backup started at Mon Aug 12 11:32:03 SAST 2019
pg_dump: last built-in OID is 16383
pg_dump: [archiver (db)] query failed: ERROR:  invalid regular expression: parentheses () not balanced
pg_dump: [archiver (db)] query was: SELECT oid FROM pg_catalog.pg_namespace n
WHERE n.nspname OPERATOR(pg_catalog.~) E'^(\\\\data\\)$'
```
I have double the amount of back slashes being escaped.

**Comment by nikleonard** [comment]
I have the same error in dbeaver v6.1.5 when trying to backup a schema named "ref". Downgraded to 6.0.5 and it works fine.

**Comment by danghung-dev** [comment]
I also have the same error in dbeaver v6.1.5. 
I use macos High Sierra 
![image](https://user-images.githubusercontent.com/5670932/64005194-12796c80-cb3a-11e9-93c0-31be77084d62.png)

**Comment by nikleonard** [comment]
Still present in 6.2.1.
Trying to make a backup of a database with a schema called "ref"
(Works with 6.0.5 and previous versions)

/usr/bin/pg_dump --format=c -n ...
Backup started at Thu Oct 03 16:51:11 CLST 2019
pg_dump: last built-in OID is ...
pg_dump: [archiver (db)] query failed: ERROR:  invalid regular expression: parentheses () not balanced
pg_dump: [archiver (db)] query was: SELECT oid FROM pg_catalog.pg_namespace n
WHERE n.nspname OPERATOR(pg_catalog.~) E'^(\\\\ref\\)$'

Backup finished at Thu Oct 03 16:51:11 CLST 2019
Process exit code: 1

**Comment by nikleonard** [comment]
Is possible to add the "bug" tag to this issue?. Is not being seen by anybody.

**Comment by danghung-dev** [comment]
@nikleonard  How can I downgrade to 6.0.5? 
I use macos and install by brew cask install dbeaver-community

**Comment by serge-rider** [comment]
This issue was caused by #5950 fix.
Thanks for the bug report (sorry for so long resolution, we have too many tickets)

**Comment by serge-rider** [comment]
Still reproducible on MacOS.
Another problem with quotes escaping on Linuxes and MacOS was fixed.

**Comment by uslss** [comment]
verified
