### ISSUE TITLE
Export to .txt without header row delimiter

### ISSUE THREAD

**Issue by Dbrown020** [dbeaver/dbeaver#6209]
Using DBeaver 5.3.3, Windows 7. 

Right click resultset -> export data -> TXT -> formatting is "connection's default", binaries set to NULL, Show NULLs is unchecked, show leading and trailing delimiter both unchecked. 

File results in a row of "--------" below the header row, which I need to eliminate. How can I export to .TXT without this header row delimiter?

**Comment by serge-rider** [comment]
It is not possible in current version. But it is very easy to implement. I'll add such option in the next version:
![image](https://user-images.githubusercontent.com/6398845/60686559-cc8d8880-9ea9-11e9-9dec-8d2bd78c195b.png)

**Comment by uslss** [comment]
verified
