### ISSUE TITLE
Export multiple tables in one database doesn't work in 6.1.1

### ISSUE THREAD

**Issue by goxr3plus** [dbeaver/dbeaver#6211]
I tested it in 6.1.1 and it doesn't work correctly it is producing multiple files ->

Selecting 3 tables -> Export Data -> SQL/SQL -> Write to Single File -> Next -> Finish -> I see `2` files instead of one . I need all the data in one file . 

It used to work as far as i remember 

@serge-rider

**Comment by serge-rider** [comment]
Thank you for the bug report

**Comment by uslss** [comment]
verified
