### ISSUE TITLE
Database connectivity issues with 6.1.1 but not in 6.1.0

### ISSUE THREAD

**Issue by goxr3plus** [dbeaver/dbeaver#6212]
We were trying to connect to production database yesterday using an SSH tunnel . 

I had the latest version 6.1.1 of DBeaver and i was having the below error all the time :

![dbeaver_2019-07-02_12-08-30](https://user-images.githubusercontent.com/20374208/60573570-96a0b500-9d80-11e9-8f9c-33d0e417fd20.png)

Double checked the ssh tunnel it was working perfectly , just couldn't connect tot the database , all the credentials were correct.

---

And here comes the strange part . I unistalled DBeaver **6.1.1** and installed **6.1.0** and it worked without changing nothing .

I am worried if that something to do with the migration to Java 11 or some kind of bug , it's important to be solved , all the company was affected by that bug , we all unistalled the latest version and some using MySQLWorkBench .

I installed again today DBeaver 6.1.1 just in case and again the same error : 

![dbeaver_2019-07-03_10-58-22](https://user-images.githubusercontent.com/20374208/60574059-7d4c3880-9d81-11e9-8f6d-d01fe1b13558.png)

**Comment by goxr3plus** [comment]
@serge-rider

**Comment by guyco33** [comment]
Same for me when connecting to Presto-sql with https and jks file

**Comment by goxr3plus** [comment]
@guyco33 I have Oracle JDK 11.0.3 installed in my computer , so is DBeaver using it's own version `OpenJDK` or the Oracle JDK ?

**Comment by serge-rider** [comment]
It is a known issue (see #6148).
It was already fixed (the bundled JDK11 was patched) - you can test it in Early Access version (https://dbeaver.io/files/ea)

@guyco33 It depends. If you have installed DBeaver using Windows or MacOS installer then DBeaver will use OpeJDK 11 which is included in the installer distrib.

**Comment by goxr3plus** [comment]
@serge-rider  Is Early Access DBeaver version safe to use for production :) ? I mean not any critical bugs etc?

**Comment by tati-kru** [comment]
@goxr3plus usually, it's quite stable because we test all features that appear in EA. But we do not recommend it for the big production systems. This fix will be included to the version 6.1.2. You can wait for couple days till July 8 for the official release.

**Comment by guyco33** [comment]
I am using DBeaver's own JDK version

**Comment by serge-rider** [comment]
If anyone coul test this issue in the Early Access version (just the possibility to connect to a database) - please do. Otherwise I can't validate whether this issue is fixed or not :(
Thanks

**Comment by goxr3plus** [comment]
@serge-rider  I will test now

**Comment by goxr3plus** [comment]
@serge-rider  It's working perfectly thank you , i am closing this issue :)

**Comment by goxr3plus** [comment]
@serge-rider  Can you please check this issue i opened too => https://github.com/dbeaver/dbeaver/issues/6211

**Comment by guyco33** [comment]
Thanks @serge-rider  
Approved that 6.1.2 i's working for Mac (installer+ JRE)

**Comment by goxr3plus** [comment]
6.1.4 having the same issue again guyz :)

**Comment by goxr3plus** [comment]
@serge-rider

**Comment by serge-rider** [comment]
@goxr3plus Please create new ticket, this one is too heavy. And we didn't change JRE version in 6.1.4.

**Comment by goxr3plus** [comment]
Okay it seems it was a problem from my side :) Now it works.
