### ISSUE TITLE
Popup window when long running query ends

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6214]
There is already a feature to play a sound when long running query end (true, no?), but in offices speakers are always on mute, and anyway, you might miss the sound for any reason.

A new popup window opened, which will flush in taks bar, will be more effective.

**Comment by serge-rider** [comment]
This feature is already implemented:
![image](https://user-images.githubusercontent.com/6398845/60662671-4a777280-9e5d-11e9-8e54-931ce7d4107c.png)

**Comment by wiwwo** [comment]
Cool! Sorry :-)
