### ISSUE TITLE
Option to freeze (pin) columns in result set

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#6216]
Option to freeze left columns in results preview would be very handy
Would it be possible to add that ?

** UPDATE 31/10/19 **
Attaching pic showing what I meant by columns freeze / pin option 
(random img found in Internet but showing concept)

![image](https://user-images.githubusercontent.com/5410448/67928076-7233d880-fbba-11e9-8c63-85c7570aa328.png)

**Comment by serge-rider** [comment]
This feature is already there: 
![image](https://user-images.githubusercontent.com/6398845/60642510-75979d00-9e30-11e9-9e93-3c9100966c4e.png)

**Comment by maciey** [comment]
I m looking to freeze column not tab 
(So if I have 100 columns, scrolling right I can still see left most column)

**Comment by serge-rider** [comment]
Well, you also can change columns order (by drag-n-drop or in Custom Filters dialog). And then save columns settings for current table/query.

**Comment by matthewsommer** [comment]
We would love this feature as well. We're growing DBeaver heavily at my company and the number 1 user compliant is interacting with the columns and filters. They want to be able to re-order the columns then freeze them like in Excel.

**Comment by serge-rider** [comment]
I've improved saving of columns visibility/position. "Freezeing" columns looks like very handy feature especially for tables with huge number of columns. However it requires quite a lot of effort. Start working on it after 6.2 release,

**Comment by sc5606** [comment]
@serge-rider eagerly waiting for this feature... Thank you in advance.

**Comment by SilvioGrosso** [comment]
Yep. Thanks a lot for considering its development.

This feature would be *extremely* useful.
We freeze columns with Excel - LibreOffice Calc quite often.
At work we have plenty of tables with more than 60 columns and this feature is indeed handy -)

**Comment by serge-rider** [comment]
Done

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/81702289-beb67580-9473-11ea-8dfc-98a8b50ffa2a.png)

**Comment by maciey** [comment]
Brilliant ! Many thanks

**Comment by uslss** [comment]
verified

**Comment by ognivo777** [comment]
Would be very useful add some kind of SQL hint to specify pinned columns right from SQL expression, so after make changes on it and re-run, columns still be pinned.

**Comment by JonLVacasa** [comment]
> ![image](https://user-images.githubusercontent.com/6398845/81702289-beb67580-9473-11ea-8dfc-98a8b50ffa2a.png)

Is there directions on how to achieve this? Would like to be able to freeze columns in result set

**Comment by maciey** [comment]
> > ![image](https://user-images.githubusercontent.com/6398845/81702289-beb67580-9473-11ea-8dfc-98a8b50ffa2a.png)
> 
> Is there directions on how to achieve this? Would like to be able to freeze columns in result set

Right clicking on columns header:

![obraz](https://user-images.githubusercontent.com/5410448/182152600-b2e557b4-67ed-4ab4-aa9d-148a375b4fec.png)
