### ISSUE TITLE
MSSQL DDL generation weird result with FKs

### ISSUE THREAD

**Issue by e-ruiz** [dbeaver/dbeaver#6218]
**Is your feature request related to a problem? Please describe.**
Yes, the problem occours on generate SQL/DDL from MSSQL tables with foreingkeys. The SQL generated include FK definitions directly on `CREATE TABLE` statement, ignoring the logical creation of tables, but following the alphabetical order of tables. It causes FK definitions errors when a referer constraint points to an unexistent table. Probably it happens with differents SGBDs, not tested yet.

**Describe the solution you'd like**
Would be fine if SQL/DDL generator creates a SQL with constraints definitions at the end of result SQL, after tables creations.

**Describe alternatives you've considered**
To avoid this problem, I am using [mssql-scripter ](https://github.com/microsoft/mssql-scripter/blob/dev/doc/usage_guide.md), but would be nice to make everything I need on one tool: DBeaver.

**Additional context**
To create the above scenario:
1 - Create some tables to test.
```sql
CREATE TABLE teste.dbo.other_table (
	id int PRIMARY KEY,
	name varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);

CREATE TABLE teste.dbo.an_example (
	id int PRIMARY KEY,
	id_to_other_table int NOT NULL,
	CONSTRAINT fk_an_example_id_to_another_table FOREIGN KEY (id_to_other_table) REFERENCES teste.dbo.other_table(id)
);
```

2 - On Database navigator, select the new tables.
3 - Right click and select `Generate SQL` / `DDL`.
4 - Result DDL:
```sql
-- Drop table

-- DROP TABLE teste.dbo.an_example GO

CREATE TABLE teste.dbo.an_example (
	id int NOT NULL,
	id_to_other_table int NOT NULL,
	CONSTRAINT PK__an_examp__3213E83FB1F61969 PRIMARY KEY (id),
	CONSTRAINT fk_an_example_id_to_another_table FOREIGN KEY (id_to_other_table) REFERENCES teste.dbo.other_table(id)
) GO;

-- Drop table

-- DROP TABLE teste.dbo.other_table GO

CREATE TABLE teste.dbo.other_table (
	id int NOT NULL,
	name varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__other_ta__3213E83F889F5E42 PRIMARY KEY (id)
) GO;
```

Note that, the `an_example` definitions is on top of `other_table`, but defines an FK to that table, causing `SQL Error [1767] [S0000]: Foreign key 'fk_an_example_id_to_another_table' references invalid table 'teste.dbo.other_table'.` when executed.

Actually it is not a big problem when we have a few tables, but with a bunch of tables and foreign keys is a pain.

**DBeaver version: 6.1.1**

**Comment by serge-rider** [comment]
This is not SQL Server-specific, we have the same issue in other databases.

**Comment by serge-rider** [comment]
Fixed, now we take foreign keys into consideration. 
Also new tab "DDL" was added to SQL Server schema editor (contains all tables and views DDL in right order)

**Comment by uslss** [comment]
verified.
Created issues #6387 #6388
