### ISSUE TITLE
Unable to find valid certification path to requested target when I try to connect in a remote server.

### ISSUE THREAD

**Issue by fjavier** [dbeaver/dbeaver#6219]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.1.1
- Java version: 8
- Additional extensions: none

#### Connection specification:
- Database name and version: Postgres 9.4
- Driver name: PostgreSQL standard driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
I'm getting this error: 
**unable to find valid certification path to requested target** when I am trying to connect to remote database, in previous versions I didn't get this error.

![image](https://user-images.githubusercontent.com/3578372/60628349-548e6800-9dae-11e9-8c1e-e5349e981d39.png)

**Comment by serge-rider** [comment]
Did this work in earlier version of DBeaver?

Generally this error says that your certificate is invalid (e.g. it doesn't match database server address).

**Comment by dorbae** [comment]
I'm not sure that this way will be a proper solution. But, could you try this?

* Your PostgreSQL connection -> Edit Connection

![2019-07-04 15 35 34](https://user-images.githubusercontent.com/25657896/60644731-f0cd7300-9e71-11e9-8a32-c11946875733.png)

* Connection settings > Driver properties >  set **sslmode=require**

![2019-07-04 15 36 16](https://user-images.githubusercontent.com/25657896/60644821-25d9c580-9e72-11e9-9ee5-25f3a1369ed7.png)

* And then, reconnect your database

**Comment by serge-rider** [comment]
Could you try this in 6.1.2 Early Access (https://dbeaver.io/files/ea)?

**Comment by fjavier** [comment]
> in earlier version of DBeaver?
> 
> Generally this error says that your certificate is invalid (e

Yep, I did it, but i had the same result.

@dorbae  Also, I tried change the driver ssl mode as you said, but it doesn't show me the options.

![image](https://user-images.githubusercontent.com/3578372/60675323-594c2e00-9e39-11e9-91e1-543890da3be3.png)

![image](https://user-images.githubusercontent.com/3578372/60675375-7c76dd80-9e39-11e9-8462-d032cc1ae616.png)

**Comment by hlascelles** [comment]
I can't help with Windows I'm afraid, but if anyone comes to this after upgrading their RDS certificates on AWS recently, the following may help:

```
# Download the 2019 root cert
curl https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem --output rds-ca-2019-root.pem

# Convert `.pem` to `.der`
openssl x509 -outform der -in rds-ca-2019-root.pem -out certificate.der

# Import into Java's cacerts.
# It will prompt "Warning: use -cacerts option to access cacerts keystore" but you can ignore it.
# If prompted for `keystore password:` use the Java default `changeit` (no, really)
# When prompted `Trust this certificate?` type "yes" <enter>
sudo $JAVA_HOME/bin/keytool -import -alias rds-ca-2019-root -keystore $JAVA_HOME/lib/security/cacerts -file certificate.der
```

**Comment by JuniorC07** [comment]
i had this problem with SQL server and changing the following setting from false to true solved the problem.

![image](https://user-images.githubusercontent.com/45216535/205785027-cb8cd547-7f66-4889-9e39-6f08ca9521cc.png)

**Comment by fcortesjp** [comment]
I can confirm that what @JuniorC07 suggested works also to connect to a mysql instance. 
I did have to add the property 'trustServerCertificate' though as it was not there by default.

**Comment by surdu** [comment]
What @JuniorC07 suggested is correct, but I don't see how would you know to change this... Can't this be the default?

**Comment by CainaMorais** [comment]
> Eu tive esse problema com o SQL Server e alterar a seguinte configuração de false para true resolveu o problema.
> 
> ![imagem](https://user-images.githubusercontent.com/45216535/205785027-cb8cd547-7f66-4889-9e39-6f08ca9521cc.png)

Cara fiz exatamente isso e resolveu meu problema que era parecido com o do Francisco.

**Comment by chenyaooo** [comment]
> i had this problem with SQL server and changing the following setting from false to true solved the problem.
> 
> ![image](https://user-images.githubusercontent.com/45216535/205785027-cb8cd547-7f66-4889-9e39-6f08ca9521cc.png)

It worked, thank you!

**Comment by sung35** [comment]
Set "Connection settings > SSL > Advanced >SSL Factory" to com.amazon.redshift.ssl.NonValidatingFactory. Assuming you are using redshift-jdbc42.2.x.jar.  My version was redshift-jdbc42-2.1.0.11.jar  Basically you configure the driver to use NonValidatingFactory to not validate the server when connecting.
