### ISSUE TITLE
SP source display is not correct

### ISSUE THREAD

**Issue by z20067765** [dbeaver/dbeaver#622]
DB: Sybase 
Version: Adaptive Server Enterprise/15.7/EBF 25871 SMP SP137 /P/Sun_svr4/OS 5.10/ase157sp137x/3984/64-bit/FBO/Fri May 27 00:14:45 2016

The start lines:
![image](https://cloud.githubusercontent.com/assets/11585705/17091939/5da96bfa-5271-11e6-91c5-6fd5da265de5.png)
But it should be:
![image](https://cloud.githubusercontent.com/assets/11585705/17091977/a52635ee-5271-11e6-8be2-43c41b01662f.png)

The first line at line 350
![image](https://cloud.githubusercontent.com/assets/11585705/17091993/ccbb0ea4-5271-11e6-8c90-e0857ac074d8.png)

In DBeaver, the create table DDL(should be at the beginning) and drop table DDL(should be at the end
) at line 390-470
![20160725142830](https://cloud.githubusercontent.com/assets/11585705/17092529/eab7b6a6-5275-11e6-891a-0daf731269bb.png)

**Comment by serge-rider** [comment]
Did I understand correctly that main problem is missing procedure header (CREATE PROCEDURE AS)?

**Comment by z20067765** [comment]
Not miss,  procedure header was at line 407(please see the last picture), but it should be at the first line.
I'm sure SP is right. But In DBeaver, the source is confusing.

**Comment by jeisoncp** [comment]
Same error here.

**Comment by uslss** [comment]
cannot reproduce on 6.0.2
