### ISSUE TITLE
[Oracle] ORA-00911 in update view with the semicolon at end

### ISSUE THREAD

**Issue by norlancd** [dbeaver/dbeaver#6222]
#### System information: 
- Operating system (distribution) and version - **Windows 10**
- DBeaver version - **6.1.1.201906240635**
- Java version - java.vm.version=**11.0.3+7**

#### Connection specification:
- Database name and version - **Oracle 11g**

#### Describe the problem you're observing:
when I try to **update a view with the semicolon** at the end you get an **error ORA-00911**

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
