### ISSUE TITLE
customer drivers configuration file path

### ISSUE THREAD

**Issue by zhangxingr** [dbeaver/dbeaver#6224]
When i'm connecting the oracle, i add local drivers into driver-manager.
Now, I want to know where the configuration file path is, please tell me.

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer. Please try to see it using following way Connection settings>Main> Edit Driver Settings>Information
![dbeaver_fMp2Zkycfk](https://user-images.githubusercontent.com/51405061/80078008-f7d78600-8556-11ea-865e-71193ba4cbcc.png)

Please reopen the ticket or create a new one if you have additional questions.
