### ISSUE TITLE
Can't select schema

### ISSUE THREAD

**Issue by benneteapen** [dbeaver/dbeaver#6225]
I'm not sure if this is a bug or if it is because of something I'm not doing right.

This feature used to work in an earlier version where I could select the schema from the dropdown and hence didn't have to include the schema name whenever I write a query.

![image](https://user-images.githubusercontent.com/8217039/60703363-3bf18f80-9f1f-11e9-8d6a-6fd746be54e2.png)

Now after updating to version 5.0.1 when I click the dropdown I'm given an option to select a schema of my choice. But after selecting it, it reverts back to 'None'

I even tried editing the connection to select the default schema of my choice but it doesn't help. I always have to include the schema name in the query

![image](https://user-images.githubusercontent.com/8217039/60703616-d4880f80-9f1f-11e9-9489-6fb06ef65306.png)

**Comment by serge-rider** [comment]
Can't reproduce this. Does it still happen in 6.1.3+?

**Comment by benneteapen** [comment]
I haven't tried it on version 6+. I tried it on 5.0.1
I'll try uninstalling v5 and install v6 and see if I get the same error.
