### ISSUE TITLE
Connections get always created in "General" project

### ISSUE THREAD

**Issue by tcrass** [dbeaver/dbeaver#6226]
#### System information: 
- Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
- 6.1.1
- openjdk version "1.8.0_212"

#### Connection specification:
- MariaDB 10.1.38-0+deb9u1
- org.mariadb.jdbc:mariadb-java-client:RELEASE[1.5.5]
- no tunnels or proxies

#### Describe the problem you're observing:
New connections get always displayed in the "General" project's "Connections" node, not in the "Connections" node belonging to the project they were created in.

#### Steps to reproduce, if exist:
- Create a new project "Foo".
- Right-click on Foo's "Connections" node and select "Create"->"Connection" from the context menu.
- Enter valid connection information 
- Click on "Connection details" and enter "Bar" as connection name
- Click "Finish"
- The newly created connection "Bar" shows up under "General"->"Connections" instead of "Foo"->"Connections"

#### Include any warning/errors/backtraces from the logs
No log entries were written during the described connection creation process.

**Comment by serge-rider** [comment]
You can choose target project in the new connection wizard:
![image](https://user-images.githubusercontent.com/6398845/60713458-748e6a80-9f19-11e9-8a76-39010d08ed07.png)

Agreed, this is not very obvious. Any UI suggestions are welcome )

**Comment by tcrass** [comment]
D'oh -- how could I have missed that?!

Thanks for clarifying!

Cheers --

    Torsten
