### ISSUE TITLE
duplicate schema names in database navigator panel

### ISSUE THREAD

**Issue by plvnv** [dbeaver/dbeaver#6229]
This behavior on all 6.1.1 versions (linux, windows,eclipse with dbeaver plugin)
Database PostgresSQL (11.2.1 postgrespro build)

![image](https://user-images.githubusercontent.com/52536610/60726184-a3b9d180-9f43-11e9-912d-f620777d1a06.png)

**Comment by serge-rider** [comment]
This seems to be a bug in schem list reading.
DBeaver uses following query to read schemas:

```sql
SELECT n.oid,n.*,d.description FROM pg_catalog.pg_namespace n
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=n.oid
```

How many rows it returns? I assume that your database has dup rows in pg_description table (generally this shouldn't happen ever).
What if you will add distinct in the beginning:

```sql
SELECT distinct n.oid,n.*,d.description FROM pg_catalog.pg_namespace n
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=n.oid
```

**Comment by plvnv** [comment]
It looks like a problem in the "description" column, randomized comments are loaded, and then we get duplication

In other utilities (pgadmin, omnidb and etc) the list of schemes is displayed correctly.

**Comment by serge-rider** [comment]
I think I found the bug.
Could you test the fix in the latest Early Access version (https://dbeaver.io/files/ea)?

**Comment by plvnv** [comment]
Sorry,bug is still there

![image](https://user-images.githubusercontent.com/52536610/60733088-978a4000-9f54-11e9-9ce6-c330bcf0f601.png)

![image](https://user-images.githubusercontent.com/52536610/60733177-cacccf00-9f54-11e9-8b84-e667c45c1177.png)

**Comment by serge-rider** [comment]
Sorry, I've published wrong version. Please test the latest one.

Now schema read query is:

```sql
SELECT n.oid,n.*,d.description FROM pg_catalog.pg_namespace n
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=n.oid AND d.objsubid=0
```

**Comment by plvnv** [comment]
Duplication Fixed

![image](https://user-images.githubusercontent.com/52536610/60734218-dec60000-9f57-11e9-9145-431b86029b77.png)

But where the schemas comments came from (description column) is not yet clear :) They should not be at all (comments are only to the tables)

**Comment by serge-rider** [comment]
Indeed. In addition to objsubid we need condition on column classoid. Now fixed (EA is ready).
Thanks for testing it

**Comment by plvnv** [comment]
Great, thanks!
