### ISSUE TITLE
NPE appears when trying to add element to array

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6233]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.1.2

#### Connection specification:
- Database name and version Clickhouse

#### Describe the problem you're observing:
NPE appears when trying to add an element to the array.

#### Steps to reproduce, if exist:
1. Create table with any array
2. Try to add any element to array using Panels

![npe_clickhouse](https://user-images.githubusercontent.com/31996417/60754073-b0dacd00-9fe4-11e9-98c7-c4adeab3ff5a.gif)

[npe_clickhouse.log](https://github.com/dbeaver/dbeaver/files/3364555/npe_clickhouse.log)

**Comment by serge-rider** [comment]
It is Clickhouse-specific. 
And generally you can't edit Clickhouse tables that easily. Moreover JDBC driver doesn't support arrays save at all.
Now we have error `Can not bind statement parameter -> Can't bind object of class ru.yandex.clickhouse.ClickHouseArray` at the save time and this is maximum what we can get.

**Comment by uslss** [comment]
verified
