### ISSUE TITLE
DBeaver does not highlight error in compare to psql

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#6234]
Example query:
```
SELECT * FROM ( VALUES (1) ) t
infinity
```

![_](https://user-images.githubusercontent.com/799021/60756097-0b365680-a002-11e9-81f2-cdff8996f64a.jpg)

![_2](https://user-images.githubusercontent.com/799021/60756098-0f627400-a002-11e9-99a8-e0d865fb4f47.jpg)

**Comment by serge-rider** [comment]
Actually DBeaver sets cursor exactly in the position of error:
![image](https://user-images.githubusercontent.com/6398845/60756586-56029f00-9fff-11e9-9305-80ad24008f6e.png)

At least it should.

**Comment by KES777** [comment]
thanks. did not pay attention for that happened

Would be nice if line will be highlighted also (see red arrow) instead of first row (see green arrow)
![_](https://user-images.githubusercontent.com/799021/60757218-417ad280-a010-11e9-8cf1-c3a128b0d4c5.jpg)

**Comment by uslss** [comment]
There are no updates for more than a month.
The ticket is closed. 
If you want to propose a feature request or enhancement, please create a new ticket.

**Comment by KES777** [comment]
The feature request was: `highlight second line instead of first`
Was it fixed?
