### ISSUE TITLE
Ctrl+Alt+Shift+F does not work on windows 10

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#6236]
#### System information: 
- Operating system (distribution) and version: windows 10 pro 1903 (18362.207)
- DBeaver version: 6.1.2
- Additional extensions: None

#### Describe the problem you're observing:
Ctrl+Shift+Alt+F does not change to the Filter field but clicking the option in the keybinding list does go to the field.

#### Steps to reproduce, if exist:
Ran a select in the sqlite database that comes with dbeaver for testing.

Select * from Album

Ctrl+Alt+Shift+F and nothing happens.

**Comment by serge-rider** [comment]
I can't reproduce this (it perfectly switches between filter input and data grid).
- Check Preferenes->General->Keys for any shortcut conflicts
- Try to reset UI settings (https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings)

**Comment by JorisMolnar** [comment]
> I can't reproduce this (it perfectly switches between filter input and data grid).

Did you try this on Windows **1903**? Ever since I upgraded Windows 10 to this version this key combination stopped working in every program.

**Comment by nmat** [comment]
I tested again now with both the 1903 and 1809 and on 1809 it works but not on latest 1903 as mentioned by @JorisMolnar 

Thank you for pointing this out.

**Comment by nmat** [comment]
Also tested now a second machine where it worked on 1809

Upgraded it to version 1903 and now Ctrl+Alt+Shift+F does not work.

So this is related to version diff of windows 10.

**Comment by serge-rider** [comment]
Maybe there is some other software installed shich handles ctrl+alt+shift+f globally?
Anyway, looks like we can't fix this from DBeaver side..

**Comment by jsh-de** [comment]
For the archives: I tripped on this bug with a software of mine today, I was still running Windows 10 1909 (not sure why Windows auto-update hadn't happened yet). I updated my Windows to 20H2 using the Update Assistant, and joyfully note: the bug seems to have been fixed by Microsoft: KeyDown-events for CTRL-ALT-SHIFT-F do occur again.
