### ISSUE TITLE
can not scroll horizontally

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#6239]
can not scroll horizontally:

![_](https://user-images.githubusercontent.com/799021/60811956-0ce65280-a199-11e9-85ec-3b932558d1e0.jpg)

**Comment by KES777** [comment]
value is not displayed:
![_](https://user-images.githubusercontent.com/799021/60812019-3bfcc400-a199-11e9-8b5c-9e61fbdf775c.jpg)

**Comment by KES777** [comment]
can not do column wider:
![_](https://user-images.githubusercontent.com/799021/60812097-6189cd80-a199-11e9-87fd-909574b43bf6.jpg)

**Comment by serge-rider** [comment]
You cannot scroll single column.
But you can:
- Use plaintext mode
- Run "Columns pack: fit values"
- Open value view panel to see full value.

**Comment by serge-rider** [comment]
And I can't eproduce problem with empty value view panel.
BTW what PG database/driver do you use?

**Comment by KES777** [comment]
>BTW what PG database/driver do you use?

probably default. I just install DBeaver and use it.

> Use plaintext mode

can not, because of https://github.com/dbeaver/dbeaver/issues/6238

>    Run "Columns pack: fit values"

where this options is available?

>  Open value view panel to see full value.

https://github.com/dbeaver/dbeaver/issues/6239#issuecomment-509214753

value is not available for `explain analyse` queries

**Comment by KES777** [comment]
>You cannot scroll single column.

Why not if it does not fit window?

**Comment by serge-rider** [comment]
In order to support scrolling of individual columns will require to make some brand new UI. Generally it is not applicable to spreadsheet.

Long values should be edited in value panel or in editor dialog (shift+enter). I can't reproduce the problem with empty value editor. 
Do you have some SQL query which will help me to reproduce it?

**Comment by KES777** [comment]
I have, but, as you can see, this query over 10+ tables. I am not sure I can provide DDL fro all of them
