### ISSUE TITLE
Dbeaver is unable to retain the original datatype

### ISSUE THREAD

**Issue by nmadham** [dbeaver/dbeaver#6240]
#### System information: 
- Operating system (distribution) and version WIN - 10 
- DBeaver version 6.1.2

#### Connection specification:
- Database name and version - SQL Server 16
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Datatypes of columns in the select list are smalldatetime but the results are reformatted to date in Dbeaver.

I have attached a snapshot of this issue to this ticket,
The one in the left is from Dbeaver(dark theme) and the one in the right is from SSMS.
![image](https://user-images.githubusercontent.com/16705400/60815390-8a906b00-a165-11e9-92cc-34d6eaf9fea0.png)

**Comment by uslss** [comment]
cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket
