### ISSUE TITLE
Issues retrieving data from influx db

### ISSUE THREAD

**Issue by resquej** [dbeaver/dbeaver#6243]
#### System information: 
- Windows
- DBeaver EE 6.1

#### Connection specification:
- Influx DB 1.7.6 in Linux Ubuntu 64

#### Describe the problem you're observing:
Issues found navigating over Influx db data. Mainly when setting the Graph view.

#### Include any warning/errors/backtraces from the logs
Enclosed the log: [influx_issue.log](https://github.com/dbeaver/dbeaver/files/3371409/influx_issue.log)

**Comment by uslss** [comment]
cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket
