### ISSUE TITLE
Extra quote is added

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#6244]
Extra quote is added for reserved words
![_](https://user-images.githubusercontent.com/799021/60866306-a876d200-a230-11e9-85d0-b90b2f223438.jpg)

Here two quotes at the end. I expect only one:
![_2](https://user-images.githubusercontent.com/799021/60866313-aa409580-a230-11e9-8df4-47aab1a9197a.jpg)

#### System information: 
- Linux Mint 19.1
- DBeaver version 6.1.2

**Comment by uslss** [comment]
issue is still reproducible, but quite differently.
![2020-03-22_19h23_04](https://user-images.githubusercontent.com/31996417/77254536-a8115080-6c72-11ea-9da6-147bef852e43.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
reopened.
Quotes are disappeared completely now
![2020-03-26_12h56_03](https://user-images.githubusercontent.com/31996417/77634170-95906300-6f61-11ea-80d5-325720d8f7a3.gif)

**Comment by serge-rider** [comment]
it is not a bug. This table name doesn't need quotes. Quotes are inserted automatically only for identifiers with special characters in their names.

**Comment by uslss** [comment]
verified

**Comment by KES777** [comment]
>it is not a bug. This table name doesn't need quotes. Quotes are inserted automatically only for identifiers with special characters in their names.

Yes, they are not required. But if user put them explicitly, why you remove them?

**Comment by serge-rider** [comment]
Because you use "smart" auto-completion. It adds/removes quotes when it decides then they are (not) needed. It always worked this way.
We could make a special option (like "keep quotes") but I'm not sure that it makes sense. 
Why do you need these quotes?

**Comment by KES777** [comment]
Ok. No, thanks.
