### ISSUE TITLE
PostgreSQL: newly created function not listed until reconnect

### ISSUE THREAD

**Issue by nevarsin** [dbeaver/dbeaver#6247]
#### System information: 
- Ubuntu 18.04
- DBeaver version 6.1.2
- Java 1.8

#### Connection specification:
- PostgreSQL 10.9
- PostgreSQL JDBC Driver
- No tunnels or proxies

#### Describe the problem you're observing:
Whenever a new function is created (CREATE FUNCTION) it won't appear on the left panel object list (and neither is searchable) until a manual disconnection and subsequent reconnection is performed.

Using the Invalidate/Reconnect button does not solve the issue.

#### Steps to reproduce, if exist:

1) Create a function
2) Look for the function on the object list (left panel by default) -> not found
3) Disconnect from the DB 
4) Reconnect to the DB 
5) Look for the function again -> found

**Comment by uslss** [comment]
cannot reproduce it against recent (7.0) version.
If issue is still actual for you - feel free to reopen the ticket.
