### ISSUE TITLE
For IBM DB2 iSeries/AS400 connection, we were able to set libraries=*LIBL but after recent 6.1.2 patch this no longer works.

### ISSUE THREAD

**Issue by kyungone** [dbeaver/dbeaver#6248]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by patrickmdnet** [comment]
Cannot reproduce in devel. When I set "Database/Schema" to `*LIBL`, the libraries property is set properly in the JDBC driver string.  Unfortunately I do not have access to an AS/400 DB2 so not able to test further.

![image](https://user-images.githubusercontent.com/858798/75615883-a216cc80-5b17-11ea-95f6-582f52cec0b2.png)

**Comment by JMarkMurphy** [comment]
If you want to test on a current IBM i box for free, there is always [pub400.com](https://pub400.com/)

**Comment by dkornacki-cutco** [comment]
Under driver properties, set _naming_ to "system" along with setting library list as above. This works on the current version (21.0.4).

This can probably be closed.
