### ISSUE TITLE
Sql script in view declaration cannot show the full script and became single line

### ISSUE THREAD

**Issue by rmanisthebest** [dbeaver/dbeaver#6252]
#### Describe the problem you're observing:
One of the view has a declaration script over 1000 lines SQL. When i open it with Dbeaver, it shows only part of the declaration script (first 6xx lines) at first time. Second time i tried to reconnect and it formatted the script into 3 lines. It seems working fine in the db side (if i don't save it) but it is hard for me to re-formatting it back and update . code behind some single line comments (--col_name) is also recognized as comment which is not originally.

So, basically:
What i expected:
> 
1                CREATE OR REPLACE VIEW temp.order_view (a,b,c,d)
2                select a, b, c, d  from table1 
3                 --group by 1
...................
1000           where flag <>1;
> 

It becomes:
case 1 - only part of the script is shown
> 
1               CREATE OR REPLACE VIEW temp.order_view (a,b,c,d)
2              select a, b, c, d  from table1 
3                 --group by 1
...................
672           (select A,
> 

case 2 - able to see whole script but in one line
> 
1                CREATE OR REPLACE VIEW temp.order_view (a,b,c,d)
2                select a, b, c, d  from table1 --group by 1.....................................where flag <>1
> 

- Operating system (distribution) and version:
Window10pro, v1803

- DBeaver version: 
before update(6.0.0) after update(6.1.2)

- Java version: 
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

#### Connection specification:
- Database name and version
Oracle 9
- Driver name
Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

Thank you so much!

**Comment by uslss** [comment]
cannot reproduce it for now.
If issue is still actual for you - feel free to reopen the ticket
