### ISSUE TITLE
Dashboard pie and bar chart not visible - only EE feature

### ISSUE THREAD

**Issue by Sargul** [dbeaver/dbeaver#6253]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
DBeaver 6.1.2

#### Connection specification:
- Any Database

#### Describe your question:
In the dashboard creation dialog pie and bar chart are not selectable. Is this an DBeaver EE feature?

I've looked at the wiki and there the pie and bar chart type can be selected in the Default view drop down. However I can only select timeseries:
![image](https://user-images.githubusercontent.com/5595511/60942958-d289cc00-a2e4-11e9-9e7c-6520681fb46d.png)

**Comment by uslss** [comment]
hi @Sargul ,
sorry for the late response,
Yes, you're right, Pie and bar charts are EE feature. So for CE version only Time series view is available.
