### ISSUE TITLE
Function not available  in SQL server

### ISSUE THREAD

**Issue by ranajitsircar** [dbeaver/dbeaver#6255]
Some of the function like DATEADD, DATEDIFF, DATEFROMPARTS, DATENAME not available.

**Comment by LonwoLonwo** [comment]
"CURRENT_TIMEZONE", "DATEPART", "DATEADD", "DATEDIFF", "DATEDIFF_BIG", "DATEFROMPARTS", "DATENAME", "DATETIMEFROMPARTS", "EOMONTH", "GETDATE", "GETUTCDATE", "ISDATE", "SYSDATETIMEOFFSET", "SYSUTCDATETIME",  "SMALLDATETIMEFROMPARTS", "SWITCHOFFSET", "TIMEFROMPARTS", "TODATETIMEOFFSET" added according [documentations ](https://docs.microsoft.com/en-us/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql?view=sql-server-ver15)

**Comment by uslss** [comment]
verified
