### ISSUE TITLE
Can't update DBeaver using Help -> Install new software...

### ISSUE THREAD

**Issue by gustavofcalmeida** [dbeaver/dbeaver#6257]
#### System information: 
- Operating system (distribution) and version Win 7 64
- DBeaver version  6.1.0.201906091949
- Java version 8

#### Describe the problem you're observing:
When I try to update DBeaver I get:

Cannot complete the install because of a conflicting dependency.
  Software **being installed: DBeaver IDE 6.1.2.201907061627** (org.jkiss.dbeaver.ide.feature.feature.group 6.1.2.201907061627)
  Software **currently installed: DBeaver 6.1.0.201906091949** (org.jkiss.dbeaver.core.product 6.1.0.201906091949)
  Only one of the following can be installed at once: 
    **DBeaver SSH tunnels 1.0.31.201906091949** (org.jkiss.dbeaver.net.ssh 1.0.31.201906091949)
    **DBeaver SSH tunnels 1.0.33.201907061627** (org.jkiss.dbeaver.net.ssh 1.0.33.201907061627)
  Cannot satisfy dependency:
    From: DBeaver Community Edition 6.1.0.201906091949 (org.jkiss.dbeaver.ce.feature.feature.group 6.1.0.201906091949)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [6.1.0.201906091949,6.1.0.201906091949]

(...)

#### Steps to reproduce, if exist:
Help -> Install new Software -> mark DBeaver (https://dbeaver.io/update/ce/latest/) -> Next
![Sem título](https://user-images.githubusercontent.com/11458901/60965539-77f46e00-a2ec-11e9-8f9e-2a5182196f30.png)

**Comment by serge-rider** [comment]
Please try to uninstall previous version of DBeaver plugin first.
Plugin/features structure was completely changed in version 6.1. Thus some plugin conflicts may occur (but not neccessary, it depends on the previous version number).

**Comment by gustavofcalmeida** [comment]
Thanks. How do I uninstall the plugin?

**Comment by serge-rider** [comment]
Main menu -> Help -> About Eclipse IDE -> Installation Details -> find DBeaver in the list of installed software and click "Uninstall ..." button.

**Comment by gustavofcalmeida** [comment]
After I uninstalled as above, DBeaver couldn't initiate anymore.
I had to download the entire new version.
Maybe this procedure works when you have Eclipse and install DBeaver as a plugin. Which is not my case.

**Comment by serge-rider** [comment]
Yes, this works for Eclipse plugin version only.
In standalone version it shouldn't happen ever. Because every version upgrade removes previously version completely.
