### ISSUE TITLE
Why do newer version of dbeaver autoincrement csv files upon data export?

### ISSUE THREAD

**Issue by golanv** [dbeaver/dbeaver#6258]
#### System information: 
- Fedora 30
- dbeaver-ce-6.1.2

#### Connection specification:
- PostgreSQL 9.6

#### Describe your question:
Newer versions of dbeaver seem to take the liberty of adding a sequential number (_#.csv) to the end of a table's file name when exporting data to CSV.  I'm not sure what problem this is supposed to fix exactly, but it makes the feature unusable for me (I'd have to script a way of removing the number from those files).  There is also no obvious way of turning this off.  Is there a way to turn this off?  Wouldn't using a file name format like "${table}_${seq}" be more flexible?

**Comment by dalonsosice** [comment]
The same happend with SQL Connection
DBeaber 6.1.5

**Comment by golanv** [comment]
Since there has been no response to this in some time, I suspect this may be unintended funcationality.  Bug #6911 has been opened to replace this question.
