### ISSUE TITLE
Error in opening a VIEW

### ISSUE THREAD

**Issue by npda59** [dbeaver/dbeaver#6260]
In DBeaver 6.1.2.201907061627 Community Edition,
FIREBIRD 3.0
java.runtime.version=11.0.3+12-LTS
java.specification.version=11
Window 10 Home,
when opening a VIEW I get the following error:
class org.jkiss.dbeaver.ext.firebird.model.FireBirdView cannot be cast to class org.jkiss.dbeaver.ext.firebird.model.FireBirdTable (org.jkiss.dbeaver.ext.firebird.model.FireBirdView and org.jkiss.dbeaver.ext.firebird.model.FireBirdTable are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @335e3708)

**Comment by SylwesterZarebski** [comment]
Have the same problem, when opening Firebird SQL view to edit it, i got:
```
org.jkiss.dbeaver.ext.firebird.model.FireBirdView cannot be cast to org.jkiss.dbeaver.ext.firebird.model.FireBirdTable
```

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified

**Comment by SylwesterZarebski** [comment]
Thanks for quick fix, You're great! :-)
