### ISSUE TITLE
Redshift DDL generation invalid with `diststyle AUTO`

### ISSUE THREAD

**Issue by aleskiewicz** [dbeaver/dbeaver#6261]
#### System information: 
- Widows 10, 1809
- DBeaver version: 6.1.2.201907061627
- Java version bundled
- Additional extensions none

#### Connection specification:
- Database name and version: Redshift, Cluster version 1.0.8205
- Driver name postgres-redshift-jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
when generating DDL on a table, I get following entry: 
`<<Error - UNKNOWN DISTSTYLE>>;`

diststyle in use: 

`diststyle AUTO;`

It was added this year: https://aws.amazon.com/about-aws/whats-new/2019/03/amazon-redshift-now-automatically-picks-the-best-distribution-st/

#### Steps to reproduce, if exist:

Create a table with `diststyle auto` and generate DDL 

#### Include any warning/errors/backtraces from the logs
Nothing in logs

**Comment by serge-rider** [comment]
Thanks for the bug report.
You can test the fix in Early Access version (https://dbeaver.io/files/ea)

**Comment by uslss** [comment]
verified
