### ISSUE TITLE
PostgreSQL Index Descending column shown as Ascending

### ISSUE THREAD

**Issue by fandaa** [dbeaver/dbeaver#6263]
#### System information: 
- Windows 10 Pro, 1903
- DBeaver 6.1.2
- No additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 10.5
- Driver name: PostgreSQL

#### Describe the problem you're observing:
The index containing a DESC column is being shown as ASC in the UI. DDL (Source) is ok. 

`recalculated_pageviews` and `topic_id` should NOT be ticked as the Ascending in this case.

![image](https://user-images.githubusercontent.com/3234524/61050160-99d21b80-a3e6-11e9-85e0-cd919586399f.png)

#### Steps to reproduce, if exist:
```
CREATE TABLE public.test_table (
	id bigint NOT NULL,
	category_id int8 NOT NULL,
	active bool NOT NULL DEFAULT false,
	recalculated_pageviews int8 NULL,
	dep_version int8 NOT NULL DEFAULT '-1'::integer,
	topic_id int8 NULL,
	CONSTRAINT test_table_pk PRIMARY KEY (id, category_id, dep_version)
);
CREATE INDEX test_idx ON public.test_table USING btree (active, dep_version, category_id, recalculated_pageviews DESC, topic_id DESC);
```
Open index details.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by kseniiaguzeeva** [comment]
Verified. Reproduced according ticket example and with creating another table.

**Comment by fandaa** [comment]
> Thanks for the bug report

No problem, thanks both for fixing & great product. :)
