### ISSUE TITLE
[BUG] Postrges Table DDL ignoring `UNLOGGED` status

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6264]
Creating a table (or altering a table to) `UNLOGGED` is not specified in table DDL.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
![image](https://user-images.githubusercontent.com/31996417/61882251-c450c800-af00-11e9-9a1a-86d2cc967b5c.png)
verified
