### ISSUE TITLE
Do not warn me if I run a SELECT statement in PRODUCTION but indeed for DELETE, UPDATE etc.

### ISSUE THREAD

**Issue by GertJMyburgh** [dbeaver/dbeaver#6266]
My suggestion for a future DBeaver release: (Community Edition and others)
DBeaver Community Edition does have a setting that will warn me if I try to run a query in PRODUCTION. The problem is it also warns me for every SELECT query I want to run/execute. Please refine that current setting that you can tick a box next to either UPDATE, DELETE, CREATE, DROP and SELECT (for those that want that) etc. So it will then give me a warning for any other SQL statements that I try to run in PRODUCTION but not for the SELECT statements.
 
Regards,
 
Gert Myburgh
Metropolitan
South Africa

**Comment by Sargul** [comment]
DBeaver only warns if it can't detect, that the statement is a select statement. This works work me in most situations. Except some special syntax Exasol or DB2 databases support and DBeaver can't parse correctly as SQL statement.

Can you post the database system, DBeaver Version and sample SQL including DDL  you are using?

Regards

**Comment by uslss** [comment]
there is no updates more than a month
ticket closed
