### ISSUE TITLE
Exporting Data to csv ends in error "Invalid Fetch Size"

### ISSUE THREAD

**Issue by OSmeilus** [dbeaver/dbeaver#6268]
Hi

When I'm exporting the result to csv I recive this message:
Invalid Fetch Size

I tried different settings for Fetch size: Default 10000, 5000, 200. All ends up in this error

#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise; Version 1709
- DBeaver version: 6.1.2.201907061627
- Java version: Version 8 Update 171
- Additional extensions

#### Connection specification:
- Database name and version: DB2/400
- Driver name: ODBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by erika-e** [comment]
Changing the fetch size to 0 allowed me to export a csv file.

**Comment by serge-rider** [comment]
Most likely your ODBC driver for DB2/400 doesn't support fetch size.
Setting it to 0 will resolve the problem. However export performance will be relatively slow.
