### ISSUE TITLE
Copy/Paste Roles (PostgreSQL) don't works

### ISSUE THREAD

**Issue by zarpelon** [dbeaver/dbeaver#6271]
When I try to copy roles from postgres between differents connections, it does not work.

#### System information: 
- Ubuntu 19.04
- DBeaver 6.0.4

#### Connection specification:
- Database name and version
- PostgreSQL

**Comment by uslss** [comment]
related to #8133

**Comment by uslss** [comment]
closed as duplicate of #8133
