### ISSUE TITLE
SQL Editor - Add bottom padding

### ISSUE THREAD

**Issue by charlesg99** [dbeaver/dbeaver#6272]
This is on Linux, DBeaver version 6.0.4.

When the editor displays scrollbars, the bottom line is partially hidden and becomes completely unusable when the mouse hovers over it:

![Peek 2019-07-12 14-46](https://user-images.githubusercontent.com/33044886/61151981-3e229380-a4b5-11e9-85b4-e6eae20bc451.gif)

Would it be possible to add a bit of padding at the bottom of the editor to alleviate this? 

Thanks!

**Comment by DetourToNirvana** [comment]
The same issue is present on Mac OS as well. I am on Catalina 10.14.6 (18G103)

**Comment by uslss** [comment]
will be fixed in the scope of #10950
