### ISSUE TITLE
DBeaver 6.1.1 and 6.1.2 do not load user privileges

### ISSUE THREAD

**Issue by silvershadowcc** [dbeaver/dbeaver#6275]
Where all the applicable/granted privilege boxes are supposed to be ticked, now they are all blank after 6.1.0

#### Connection specification:
- Database name and version
  mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1
- Driver name
  Both MariaDB and MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
  SSH tunnel

**Comment by glw** [comment]
I am seeing the same thing for:
DBeaver 6.1.2
DB: Postgresql
OS: Ubuntu

**Comment by serge-rider** [comment]
@glw I can't reproduce this for PostgreSQL, please file separate ticket for it.

**Comment by uslss** [comment]
Verified,
