### ISSUE TITLE
Appearance in Regolith Lunix (Ubnutu i3WM distro)

### ISSUE THREAD

**Issue by chaseydog** [dbeaver/dbeaver#6276]
#### System information: 
- Regolith Linux (Ubuntu 19.04)
- DBeaver version 

#### Describe your question:
Appearance in Regolith Lunix - SQL Query editor dark and hard to read. 

![Rigolith](https://user-images.githubusercontent.com/30329469/61177279-30493d00-a59f-11e9-9ec3-fd0bb538c459.png)

**Comment by uslss** [comment]
if issue is still actual - feel free to reopen it
