### ISSUE TITLE
DDL generation's "drop" statement contains schema name when "Use fully qualified names" is unchecked

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#6277]
could be related to https://github.com/dbeaver/dbeaver/issues/3164

#### System information: 
- Operating system (distribution) and version: mac os
- DBeaver version : 6.1.0 community
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version: postgres 11.2
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/18515297/61180170-00d81600-a61b-11e9-9e17-0832ea6ab8bf.png)

#### Steps to reproduce, if exist:
In DB Navigator right click a table --> generate SQL --> DDL --> check/uncheck _use fully qualified names_ - makes no difference on the commented _drop_ statement - it's always with the schema name.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified

**Comment by Moridin11** [comment]
I am experiencing this but only with the create portion. The drop portion appears to be working correctly.
