### ISSUE TITLE
Eastern Summer Time

### ISSUE THREAD

**Issue by sirber** [dbeaver/dbeaver#6278]
#### System information: 
- Windows 10 x64
- DBeaver 6.1.2
- Java (bundeled)

#### Connection specification:
- MySQL 8.0.16 freshly installed
- mysql-connector-java 8.0.11
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:

The server time zone value 'Eastern Summer Time' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

Driver does't have a serverTimezone property.
Workbench connects whitout issues

#### Steps to reproduce, if exist:
add connextion, test it

**Comment by sirber** [comment]
mysql driver 5.1.44 (server version 4.x+) works though.

**Comment by uslss** [comment]
if issue is still reproducible for you, feel free to reopen the ticket
