### ISSUE TITLE
[BUG] save/restore configuratoin disapeared in 6.1.2?

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6280]
Is it me, or is it now not possible anymore to save and restore configuratoins in DBeaver?

**Comment by serge-rider** [comment]
What exactly configuration do you mean?

**Comment by wiwwo** [comment]
All of them, epf file.
I just noticed it has been moved from bottom left corner of preferences, to File -> Export -> Genera- -> Preferences
Is this change premeditated?
Closing this ticket...
