### ISSUE TITLE
Connection proxy config: support PAC

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6281]
More and more people use DBeaver from behind corporate firewalls.
We needto support PAC. 
Prxy vole seems to be the right thing (https://github.com/MarkusBernhardt/proxy-vole/)
Note: Java11 support may require additional efforts (https://github.com/MarkusBernhardt/proxy-vole/issues/68)

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/61720798-c03d7280-ad67-11e9-96ce-2388712f7cbc.png)

**Comment by serge-rider** [comment]
PAC implementation required quite a lot of 3rd party dependencies. And needed mostly in corporate environments.
So moving to EE.

**Comment by uslss** [comment]
Work as expected in 6.1.4 EA build.
Tested on win. 
Need to be tested on ubuntu

**Comment by uslss** [comment]
work as expected for "use browser proxy settings" on ubuntu 19.04
