### ISSUE TITLE
SELECT Statement Locked Table Problem

### ISSUE THREAD

**Issue by hasanunlukilinc** [dbeaver/dbeaver#6283]
SELECT Statement Locked Table Problem,

 I saw the issues which are likes this but they are closed. **But This bug is still continuing.** When I execute simple select query, if I don't commit or rollback, other queries is waiting it. There is absolutely table locked problems.

http://prntscr.com/ofg7z6

I had this problem in both windows and mac os system.

My Dbeaver Version 6.0.5.201905192012
Connection  Driver PostgreSQL JDBC
Java Version 1.8

**Comment by uslss** [comment]
cannot reproduce it for now.
If it is still actual - feel free to reopen the ticket
