### ISSUE TITLE
MySQL: unnecessary fractional .0 part for DATETIME values 

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#6284]
In the data grid I get values like `2019-07-15 21:56:50.0` for datetime columns that don't have any fractional digits. I have the native date/time format set in the preferences. Could we get rid of the trailing `.0` part? It looks a bit messy and also propagates to data exports.

**Comment by austin-beer** [comment]
This is probably related to #4603.

**Comment by uslss** [comment]
similar to #7268
