### ISSUE TITLE
Structure/object types are shown incorrectly and cannot be changed if db is inactive

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6290]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.1.3 EA

#### Connection specification:
- Database name and version Postgresql 10

#### Describe the problem you're observing:
Structure/object types are shown incorrectly and values cannot be changed if db is inactive. Affects both on Grid and Text views
#### Steps to reproduce, if exist:
![еее](https://user-images.githubusercontent.com/31996417/61324044-2aab5b80-a81a-11e9-91de-2920d6dc4d4e.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
