### ISSUE TITLE
Exporting data to SQL rounds floats

### ISSUE THREAD

**Issue by vesterij** [dbeaver/dbeaver#6292]
Selecting table with right-click -> Export Data -> SQL
- Extract type = single query
- Date/numbers format = native
- Omit schema name = true
- Data rows per statement = 1

This is an example row I exported with dbeaver (6.1) in 2019-06-18

`INSERT INTO dr_address (link_id,area_code,street_name,lat,lon) VALUES (5430987,778,'Valakankuja',62.647,27.08);`

This is the same row in database exported today 2019-07-17 with dbeaver (6.1.2)

`INSERT INTO dr_address (link_id,area_code,street_name,lat,lon) VALUES (5430987,778,'Valakankuja',62.64656568339424,27.08033812807776);`

My database is postgresql-x64-10 - PostgreSQL Server 10 in Windows10 machine

columns are just basic postgres floats
```
	lat float8 NULL,
	lon float8 NULL,
```

I could not find a way to get coordinates exported intact with SQL. With CSV it works when format numbers is selected.

I could force Minimum fraction digits, but it is not the same.

I am fairly certain that I did exactly same thing month ago but different results.

Cheers,
Jarno

**Comment by uslss** [comment]
thanks for the bug report
btw, sorry for long response

**Comment by uslss** [comment]
fixed in scope of #8099
