### ISSUE TITLE
csv import to postgresql miss lines while importing

### ISSUE THREAD

**Issue by israelio** [dbeaver/dbeaver#6293]
#### System information: 
- MacOS Mojave 10.14.4
- DBeaver version 6.1.2.201907061627
- java version "10.0.1" 2018-04-17
- No additional extensions

#### Connection specification:
- PostgreSQL 11.2 (Debian 11.2-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
- Driver PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no - running the postgress within docker.

#### Describe the problem you're observing:
I was trying import large amount of data (1gb - 1685587 lines / 96 columns) using dbeaver to a postgresql, the import process ends without any issues/errors but only 500000-830000 lines are being imported and its not constant. 
When using other tools such as TablePlus to do the import all the lines are being imported correctly.

I've create a smaller csv with 11 lines / 96 columns (first line is a header line) and only 9 lines imported with dbeaver

#### Steps to reproduce, if exist:

Create 96 columns (maybe less) csv file with 10+ lines
Create a table structure to hold the data (i've used pgfutter) 
Right click the table and choose import data, choose csv and follow the wizard
By the end do select count(*) on the table and notice that the number of rows is differ from the number of rows by using wc -l on the csv file.

If needed i can supply the csv files that i was using as they contain public data.

**Comment by uslss** [comment]
Cannot reproduce an issue for now.
If it is still actual for you - feel free to reopen the ticket.
Best regards,
