### ISSUE TITLE
MySQL inline datetime edit not working

### ISSUE THREAD

**Issue by reddyshyam** [dbeaver/dbeaver#6294]
#### System information: 
- OS - Windows 10 Pro 64bit 1903 (latest)
- DBeaver version - 6.1.2
- Java version - Bundled with 6.1.2
- Additional extensions - None

#### Connection specification:
- Database name and version - MySQL 5.7
- Driver name - mysql-connector-java (5.1.44)
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  SSH

#### Describe the problem you're observing:

MySQL inline datetime edit not working

#### Steps to reproduce, if exist:
Upon click of 'Save' on the editor after changing the datetime value, following error is thrown (shown under errors section).

Script generated is 
--  Auto-generated SQL script #201907171750
UPDATE wsqa.course_batches_dtl SET end_date='02-06-2019 10:00:00' WHERE id=7;

#### Include any warning/errors/backtraces from the logs
Error synchronizing data with database

Reason:
SQL Error [1292] [22001]: Data truncation: Incorrect datetime value: '02-06-2019 10:00:00' for column 'end_date' at row 1

**Comment by serge-rider** [comment]
Thanks for the bug report. It will be fixed in the next version.

Workaround: enable "Use native date/time format" option on Data Formats preference page

**Comment by reddyshyam** [comment]
Thanks @serge-rider for the bug fix and your time. Will wait for the next version now. :)

Regarding work around, I prefer the way it is i.e. without enabling the suggested option. I do a sql update to correct my datetime at the moment which does the job. 

Thanks again for your time and this great tool.

**Comment by kseniiaguzeeva** [comment]
Verified
