### ISSUE TITLE
Arrange tables when importing CVS files

### ISSUE THREAD

**Issue by amatosg** [dbeaver/dbeaver#6295]
**Is your feature request related to a problem? Please describe.**
When importing multiple files, foreign key restrictions (might) prevent importing them as they are arranged by name and we're not able to freely arrange the files.

**Describe the solution you'd like**
When importing multiple files, I would love to be able to arrange the files/tables so importing would follow any restrictions there might be in the db.

**Describe alternatives you've considered**
Currently I have to import single files following FK restrictions.

**Additional context**
No additional context is necessary, I think it's very straightforward :)

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion and sorry for the late response.

**Comment by ShadelessFox** [comment]
Hello @amatosg,

I believe this feature was implemented in #11118. Can you upgrade and check it out? Thanks!

**Comment by amatosg** [comment]
While I don't have files to make tests, for the description I see in the issue matches my request.

**Comment by ShadelessFox** [comment]
Alrighty then, I will close this issue for now. Thanks for response!
