### ISSUE TITLE
Network Profiles: two profiles with the same name could be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6300]
#### System information: 
- Operating system (distribution) and version win 10x64
- DBeaver version 6.1.3

#### Describe the problem you're observing:
Two profiles with the same name could be created. After Saving lastly created profile replace previously created profile.

![profiles](https://user-images.githubusercontent.com/31996417/61486125-69245000-a9ab-11e9-9a0e-5bf677a5dd41.gif)

**Comment by uslss** [comment]
verified

**Comment by kseniiaguzeeva** [comment]
Checked: Error message "wrong profile name" appears after attempt to create a new profile using existed profile name.
