### ISSUE TITLE
Development - org.jkiss.dbeaver.ext.ui.locks.model does not exist

### ISSUE THREAD

**Issue by alex-fernandez** [dbeaver/dbeaver#6308]
I am trying to setup my development workspace to contribute to dbeaver. However, I stumbled upon a issue on one of the plugin on 'org.jkiss.dbeaver.ext.ui.locks'. The error says that the org.jkiss.dbeaver.ext.ui.locks.model doesn't exist in the plugin. Upon checking I can confirm that the package do not exist on the plugin. Was the package left out for some reason? Can we just remove it since it is blocking the startup of the UI from the export package manifest file?
![Screenshot_20190721_214623](https://user-images.githubusercontent.com/7582277/61590767-2491f200-ac01-11e9-9d53-b91a5cab8ce7.png)

Branch: devel

**Comment by serge-rider** [comment]
It is a non-critical warning in Eclipse IDE. Already fixed, thanks for bug report.
