### ISSUE TITLE
Query result from Athena is taking longer time

### ISSUE THREAD

**Issue by mnt1979** [dbeaver/dbeaver#6310]
When I run a query to Athena on version 6.1.2 on mac, it is taking longer time to return result.  it looks like search proposals query is taking forever to return result and affecting all other queries.  Background tasks list shows search proposals (seeking for SQL completion proposals: Find object by name) that is taking long long time to complete.

Dbeaver version 6.1.2
DB Type: Athena
AWS zone: US-EAST-1

**Comment by uslss** [comment]
hi @mnt1979 ,
is it still reproducible for you against 7.0?

**Comment by vermgit** [comment]
@uslss It didn't fix it for me. Still long delay up to ten minutes.

This version actually stops responding if I try to disconnect/reconnect before I reach that menu entry (note that doing that didn't change anything in 6.3.5).

You really need to fix this as for some reason the behaviour only happens on our production database.

**Comment by mnt1979** [comment]
> hi @mnt1979 ,
> is it still reproducible for you against 7.0?

It looks like fixed for me.

**Comment by uslss** [comment]
@vermgit is it reproducible for you in 7.0.2? if it is, please create new issue with version, database you use and steps that could help to reproduce an issue.
@mnt1979 thanks for response.
seems that issue mentioned in this ticket is solved. ticket closed
