### ISSUE TITLE
Logical foreign keys: integrate with ERD

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6314]
Once we create a logical connection in ERD it must create logical foreign key. Also need a way to create rexternal references right from entity ERD (not just from custom diagrams).

**Comment by serge-rider** [comment]
Now we create logical foreign keys each time we create association in ERD.
Information about logical FKs is stored in project configuration.

Maybe we should leave diagram-specific connections. But I'm not sure..

**Comment by uslss** [comment]
Verified.
Ability to delete FK using ERD need to be added. Created issue #6411
