### ISSUE TITLE
Oracle. Spatial data is shown incorrectly in CE

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6315]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.1.3 CE

#### Connection specification:
- Database name and version Oracle 12

#### Describe the problem you're observing:
Spatial data is shown as "oracle.sql.STRUCT@6aa060f6". No information appears in log.
![image](https://user-images.githubusercontent.com/31996417/61623245-efc48000-ac7e-11e9-9740-0cbf78e7cb69.png)

**Comment by serge-rider** [comment]
Oracle spatial data viewer works only in EE version.
However in CE geometry type must be resolved as structure.

Fixed

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/61872490-1fc48b00-aeec-11e9-968d-79a1e24931ca.png)
