### ISSUE TITLE
KB shortcuts, Colors & other settings reset after update to 6.1.3

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#6318]
I had my DBeaver color theme configured to be the default dark theme that was here in older versions, such as orange text for SQL keywords. After updating to 6.1.3, it overwrote my custom keyboard shortcuts, color and display settings (I had it zoomed in), and now shows the SQL keywords in a light blue that is hard to read on a dark theme.
![dbeaver_bad_color_scheme](https://user-images.githubusercontent.com/11860098/61632317-38873380-ac95-11e9-9816-98335ea4b21a.png)

**Comment by jazz290** [comment]
I have lost all my existing editors after upgrading to 6.1.3 on Mac and Windows. Is there any way to restore the existing editors that were saved on exit and restored when updating versions.

**Comment by serge-rider** [comment]
UI settings were rest during workspace migration in 6.1.3.
You can use UI settings from you previous version. You will need to copy file workbench.xmi from old workspace location to the new workspace location. See exact paths for different versions here: https://github.com/dbeaver/dbeaver/wiki/Workspace-Location

**Comment by david-cortes** [comment]
> UI settings were rest during workspace migration in 6.1.3.
> You can use UI settings from you previous version. You will need to copy file workbench.xmi from old workspace location to the new workspace location. See exact paths for different versions here: https://github.com/dbeaver/dbeaver/wiki/Workspace-Location

That's an empty file in the old location.
