### ISSUE TITLE
DB2 Iseries, Database Navigator doesn't display list of procedures.

### ISSUE THREAD

**Issue by cmdrwayne** [dbeaver/dbeaver#632]
Selecting procedures displays list of function names not procedure names as expected.

DB2 Iseries should have Tables, Views, Indexes, Procedures, and Functions.

**Comment by cmdrwayne** [comment]
To list procedure names for example, given a schema and catalog, one would use:
SELECT specific_name FROM qsys2/routines WHERE SPECIFIC_schema='CCCPGM031' AND specific_catalog='PHOENIX' AND routine_type='PROCEDURE';

To list function names  for example, given a schema and catalog, one would use:
SELECT specific_name FROM qsys2/routines WHERE SPECIFIC_schema='CCCPGM031' AND specific_catalog='PHOENIX' AND routine_type='FUNCTION';

**Comment by serge-rider** [comment]
I'll need to find/setup DB2 iSeries to test it.

**Comment by cmdrwayne** [comment]
I can test it if you like ?

I'm currently at version 4.08

Dbeaver currently lists function when it should be listing procedures.
routine_type='PROCEDURE'

Does something like this work for getting the list?

To list procedure names for example, given a schema and catalog, one would
use:
SELECT specific_name FROM qsys2/routines WHERE SPECIFIC_schema='user
library' AND specific_catalog='machine name' AND routine_type='PROCEDURE';

To list function names for example, given a schema and catalog, one would
use:
SELECT specific_name FROM qsys2/routines WHERE SPECIFIC_schema='user
library' AND specific_catalog='machine name' AND routine_type='FUNCTION';

**Comment by uslss** [comment]
cannot reproduce against 22.0.2
