### ISSUE TITLE
array_agg display incorrect (confusing) output for empty result {null}

### ISSUE THREAD

**Issue by AlexandrOnuf** [dbeaver/dbeaver#6320]
#### System information: 
- Operating system (distribution) and version:
   - OS: Ubuntu 18.04 bionic
   - Kernel: x86_64 Linux 4.15.0-54-generic
- DBeaver version 6.1.2 community edition
- Java version 
```bash
➤ java --version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing
```
- Additional extensions - Excel

#### Connection specification:
- Database name and version: `postgres (PostgreSQL) 9.6.1`
- Driver name `PostgreSQL`
- Do you use tunnels or proxies (SSH, SOCKS, etc)? tested with SSH and without

#### Describe the problem you're observing:
`array_agg` display incorrect (confusing) output for empty result `{null}`

#### Steps to reproduce, if exist:
Execute next `SELECT`
```postgresql
select array_agg(a) FROM (VALUES (null, 1)) AS _ (a, id) GROUP BY id;
```

##### Current output
![dbeaver-output](https://user-images.githubusercontent.com/32614537/61641575-0e8b3c80-aca8-11e9-9ec8-269c19a346e5.png)

##### Expected output (from `psql`):
```bash
postgres=# SELECT array_agg(a) FROM (VALUES (null, 1)) AS _ (a, id) GROUP BY id;
 array_agg 
-----------
 {NULL}
(1 row)
```

p.s.
Output with type cast
![dbeaver-output-with-type-cast](https://user-images.githubusercontent.com/32614537/61641748-5a3de600-aca8-11e9-93e5-26c300db4fbe.png)

**Comment by uslss** [comment]
it seems that issue is already fixed in 7.0.0
![image](https://user-images.githubusercontent.com/31996417/76634469-5a506600-6557-11ea-803c-8c7dcb6e601b.png)
