### ISSUE TITLE
duplicate function names in database navigator panel

### ISSUE THREAD

**Issue by plvnv** [dbeaver/dbeaver#6322]
This behavior is observed on all versions 6.1.3 versions (linux, windows,eclipse with dbeaver plugin)
Database PostgresSQL (11.4.1 postgrespro build)

![image](https://user-images.githubusercontent.com/52536610/61642633-f74d4e80-aca9-11e9-8e27-7e6f168d8e2b.png)

**Comment by plvnv** [comment]
any ideas?

**Comment by uslss** [comment]
cannot reproduce issue.
is it still reproducible on 6.3.3?

**Comment by plvnv** [comment]
> cannot reproduce issue.
> is it still reproducible on 6.3.3?

Yes, still reproducible on dbeaver 6.3.3. Even after update postgres pro up to 11.6.1

The same database functions are displayed correctly without duplicates in pgAdmin4 v 4.17

**Comment by plvnv** [comment]
Maybe this help
![Снимок экрана 2020-01-29 в 14 03 23](https://user-images.githubusercontent.com/52536610/73364411-9b4c2e00-42bb-11ea-9313-b089672fcf28.png)

comments in the red square belong to other objects in the data schema

**Comment by plvnv** [comment]
![image](https://user-images.githubusercontent.com/52536610/78364380-03720580-75c6-11ea-98a9-b1c20b8d9706.png)

please post here sql query  used to show functions in dbeaver navigation panel, i think it is wrong

**Comment by uslss** [comment]
@plvnv , all the queries that are executed are shown in query manager. (Window - Show View - Query Manager)
Still not reproducible for me

**Comment by uslss** [comment]
there are not any updates on issue. Ticket will be closed.
If issue is still actual for you - feel free to reopen the ticket with additional info
