### ISSUE TITLE
Automatically set project for connection

### ISSUE THREAD

**Issue by BigMcLargeHuge** [dbeaver/dbeaver#6323]
A small feature that I think would greatly increase user friendliness of the Projects View.  Currently, one is able to create a connection by right clicking on a project and selecting **Create > Connection** However, unless the user re-specifies the project for the connection again, the connection is relegated to the "General" project with no obvious way of changing it.  

I don't know the codebase well enough to make the change myself but one would think that the project reflect whichever project was right-clicked to create the connection.

**Comment by serge-rider** [comment]
This makes great sense, thanks for noticing this.

**Comment by kseniiaguzeeva** [comment]
Verified.
