### ISSUE TITLE
Import data from CSV to DDL

### ISSUE THREAD

**Issue by fabianMendez** [dbeaver/dbeaver#6324]
Sometimes we don't want to import the data right away but just make sure the data is importable and send the queries to another environment.

It would be cool to be able to select an output file to save the generated DDL.

Q: Why don't I import the data from the file and then generate the DDL?
A: There may already be data in the table so I don't know which came from the file

Thanks

**Comment by uslss** [comment]
Target DDL could be already copied in Data Transfer Wizard
![image](https://user-images.githubusercontent.com/31996417/162146400-3fe6366a-759e-4cdf-ba5d-6ce6e3b1d366.png)
