### ISSUE TITLE
cascade the results tabs

### ISSUE THREAD

**Issue by bracharedis** [dbeaver/dbeaver#6328]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
I would like to have the ability, on the same connection tab, to move results tab one  in a side or under another in order to compare 2 results easily or to detach results tab as it can be done with the query tab

**Describe alternatives you've considered**

**Additional context**

**Comment by uslss** [comment]
probably relates to #11082

**Comment by E1izabeth** [comment]
Detaching of result tab was implemented.
Also showing two or more results from one execution in the one tab will be implemented in scope of #6861.
