### ISSUE TITLE
MS SQL - Connection config - General - Filters - Disabled

### ISSUE THREAD

**Issue by Spoelle** [dbeaver/dbeaver#6330]
Windows 7 SP1 64-bit
DBeaver 5.3.3
MS SQL-Server 2012 (10.50.1600.1)

The filters are disabled on reopening DBeaver. 
Before if the filters where enabled when closing DBeaver then they where still enabled when reopening DBeaver.

thanks for your good work!

**Comment by Spoelle** [comment]
Sorry!! 
DBeaver version is 6.1.3.201907211943

**Comment by Spoelle** [comment]
![image](https://user-images.githubusercontent.com/19902865/61720101-7e5ffc80-ad66-11e9-914e-84e757d61378.png)

**Comment by Spoelle** [comment]
I've checked all my other projects (>10) and the problem is only in one project; in the other projects all the connection filters are enabled when reopening DBeaver, so no problem. Next week I'll create the buggy project again from scratch.
So maybe you can close this issue ?

**Comment by Spoelle** [comment]
I've tried to create a new project but with the same result... Filters disabled on restarting DBeaver. More bad news... I have a project where filters are working fine but when I change the filter settings in the latest version of DBeaver I get the same result for this project ->filters disabled when restarting DBeaver... annoying problem.

**Comment by Spoelle** [comment]
Just tested the new version (6.1.4.201908041900) and the filters are still enabled after restarting DBeaver, TOP! 
Issue closed.

**Comment by serge-rider** [comment]
Thanks for the information
