### ISSUE TITLE
When viewing data in PostgreSQL, and filtering on bit values, the where clause needs quotes.

### ISSUE THREAD

**Issue by shirotakakah** [dbeaver/dbeaver#6332]
When viewing a table in a PostgreSQL database, and you filter on a bit value, the default "where code" produced at the top of the form produces an error because the driver treats bit values a strings instead of numbers.  
Walk Through:  In Figure 1 you can see that I have a table called itemdefinitions that has a column named used that is of type bit.
![bug1a](https://user-images.githubusercontent.com/6653861/61721898-8bf59200-ad26-11e9-8331-bc40c5dce511.jpg)

In Figure 2 you can see I am filtering on used = 1
![bug1b](https://user-images.githubusercontent.com/6653861/61721926-9879ea80-ad26-11e9-95f5-c938a1b9c6dd.jpg)

In Figure 3 you can see that the default WHERE code produced by the filter has "used=1" as part of it.  This produces the error:
SQL Error [42883]: ERROR: operator does not exist: bit = integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 55
![bug1c](https://user-images.githubusercontent.com/6653861/61721954-a29be900-ad26-11e9-8931-0b728297d333.jpg)

In Figure 4 you can see if i put single quotes around the 1, treating it like a string, the issue is solved.
![bug1d](https://user-images.githubusercontent.com/6653861/61721965-a7609d00-ad26-11e9-8cf9-9f3e9e746f36.jpg)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
