### ISSUE TITLE
Lost all connections in database navigator after copy/paste

### ISSUE THREAD

**Issue by mkortink** [dbeaver/dbeaver#6334]
#6028 ## System information: 
- Windows 10
- DBeaver version 6.1.1
![dbnav](https://user-images.githubusercontent.com/27032470/61757329-6b4f3a00-ae03-11e9-8c34-89a3d1810042.PNG)
![projects](https://user-images.githubusercontent.com/27032470/61757331-6b4f3a00-ae03-11e9-8b8e-5fae56182c05.PNG)

#### Connection specification:
- Multiple, see attachments

#### Describe your question:
I am new to DBeaver so this may be a user error rather than software issue. I have set up 12 connections which listed under 'Database Navigator' and also I note the 'General' project. Everything was going great and I am very impressed with DBeaver.

Then, I decided to create a project and copy/paste the connections from the navigator to the 'Connections' folder under my new project which I had made the active project. Here is what happens -
1) The connections disappeared from the navigator (see attachment).
2) The connections are duplicated under the connections of the 'General' project with a number appended (see attachment).
3) The connections do not appear in the connections of the new project, even though it is active and i right-clicked over that folder and selected paste.
4) If I now try to copy/paste the connections back to the navigator OR to my new project, they just replicate again under the general project with a incremented number.
5) I cannot figure out how to get the connections to return to the navigator!

I want all the connections back in the database navigator and will give up on projects which don't seem to work. How can i do this?

**Comment by mkortink** [comment]
Hi, after copy/paste of connections from 'Database Navigator' to my new projects 'Connections' folder all that happens is the connections disappear from the navigator and get duplicated under the 'General' project. This is despite me using right-click and paste while hovering over the new projects connection folder. I also can't paste back to the navigator, it just duplicates again under the 'General' project.

How do I recover the database navigator connections and get back to normal?

Windows 10
DBeaver 6.1.1

**Comment by serge-rider** [comment]
Duplicate of #6321 
Workaround: right click on the project "General" element -> Set active.

**Comment by serge-rider** [comment]
I missed that DBeaver verion is 6.1.1. It is a dufferent probem than in #6321.
Could you send error/debug logs? I can't realize what was happened without them (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by mkortink** [comment]
Hi Serge, looked at the log and its not an error, there are no error messages. It seems to be a feature, and I may be misunderstanding projects. Here are two fresh screen shots. 

![1 Capture](https://user-images.githubusercontent.com/27032470/61999973-2a5f6a00-b110-11e9-844c-0c5b6bd54171.PNG)
![2 Capture](https://user-images.githubusercontent.com/27032470/61999974-30554b00-b110-11e9-8d48-c7c5a31fa248.PNG)
Note Metapplica is active. If I copy/paster the MariaDB connection from General to Metapplica by right-clicking and copying from General then right-clicking and pasting to Metapplica, intead of the connection appearing in Metapplica, it replicates in General. 

Intuitively I expect the connection to show up in Metapplica, I want to use this connection in several projects.

**Comment by ChetanVashisht** [comment]
I faced this exact issue, turns out the `active project` under the `database navigator` changed from General to Desktop. Change it back and everything works fine!
