### ISSUE TITLE
It's take too many time to execute 200 rows

### ISSUE THREAD

**Issue by dron4ik86** [dbeaver/dbeaver#6336]
I try to execute the query and I put limit 200
But it's taking too many time to execute the query.
It can take some times 42 sec to get the result.
After 42 sec for my next queries, I will get the result immediately.
I have dbeaver 6.1.3
Macos Mojave 10.14.5
![DBeaver 6 1 3 -  QA2  plot_reports sql 2019-07-24 09-43-54](https://user-images.githubusercontent.com/46297535/61771214-e14da400-adf7-11e9-8812-8c540c9b621b.jpg)

**Comment by serge-rider** [comment]
What is your database?

**Comment by dron4ik86** [comment]
> What is your database?

MySQL 8

**Comment by serge-rider** [comment]
Does this problem happens every time you connect to a database or after some period of inactivity?

Perhaps it is a result of connection timeout or socket/ssh/vpn tunnel timeout. This can be solved by setting Keep-Alive option.

**Comment by dron4ik86** [comment]
> Does this problem happens every time you connect to a database or after some period of inactivity?
> 
> Perhaps it is a result of connection timeout or socket/ssh/vpn tunnel timeout. This can be solved by setting Keep-Alive option.

The problem is that I can't the "Keep-Alive" in the settings.
![4444](https://user-images.githubusercontent.com/46297535/61848888-32bd6800-aeb8-11e9-90e3-a3cce7b1a0de.jpg)
