### ISSUE TITLE
Dbeaver does not detect unique key on a table despite primary key being present

### ISSUE THREAD

**Issue by pavlexander** [dbeaver/dbeaver#6337]
#### System information: 
- win10 x64
- dbeaver 6.1.1

#### Connection specification:
- org.sqlite.JDBC 3.28.0

#### Describe the problem you're observing:
I am trying to remove a record from sqlite database. I use dbeaver program for all operations. So when the action is performed, following error is shown:

> No unique key is defined

#### Steps to reproduce, if exist:

Query for table creation was this:

```sql
CREATE TABLE betGroups ( 
id INTEGER PRIMARY KEY AUTOINCREMENT, 
betgroupstatus INTEGER NOT NULL,
dateInserted DATETIME DEFAULT CURRENT_TIMESTAMP)
```
Insert some dummy data. Then I select a record in "data" view. Press "delete" on a keyboard. and then click "save" button below. First the warning is shown that no physical unique key is found, so he program suggests to use ALL ROW as a key. If I press cancel, then the above mentioned error is shown.

![image](https://user-images.githubusercontent.com/20644772/61771533-c3347380-adf8-11e9-88cb-48c6ed2e59c2.png)

![image](https://user-images.githubusercontent.com/20644772/61771545-c92a5480-adf8-11e9-8089-d92211a5cd1a.png)

However, If we check the unique keys tab - we will see that a unique key is present as well as the primary key.

![image](https://user-images.githubusercontent.com/20644772/61771558-cdef0880-adf8-11e9-9db7-ce94a9da988d.png)

![image](https://user-images.githubusercontent.com/20644772/61771566-d2b3bc80-adf8-11e9-8e08-c7c0e2456f37.png)

So as far as Sqlite database is concerned - unique key exists, bu the program fails to detect it for some reason during manual delete operation. Please investigate.

**Comment by pavlexander** [comment]
I see that the label says "can't reproduce".. So, can I further assist you? Have you used SQL delete operation or a physical keyboard button?

Here is insert statement just in case

`insert into betGroups (betgroupstatus) values (1);`

**Comment by serge-rider** [comment]
Now I've reproduced this. Thanks for detailed bug report

**Comment by pavlexander** [comment]
you are welcome :)

And thank you for the awesome product!

**Comment by serge-rider** [comment]
This is side effect of the #424 fix. Currently DBeaver doesn't use unique keys with nullable columns.
I believe we should use them in SQLite at least.

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by maltem-za** [comment]
@serge-rider @kseniiaguzeeva This problem appears to be back with 24.2.5.202411171748
I was able to insert a new row into a SQLite table that has a PK defined, but can't delete or modify it using the GUI. Works via script. Let me know if you need further details.

**Comment by znemeth23** [comment]
I can confirm this is happening in the GUI of 24.3.2 - I want to modify a field in a table which has a PRIMARY KEY and I get the "No unique key" error message.
(in this example, `deadline_id` is the PK and I tried to modify a `date` field in one of the rows)

![Image](https://github.com/user-attachments/assets/8ec6ddbf-3dde-444a-9e37-9b024583bac2)

(it's a MariaDB database; from SQL script it works correctly)

UPDATE: strange, ever since I did the desired modification from the SQL script, I can modify from the GUI as well without the error message.

**Comment by maltem-za** [comment]
The regression appears to have been fixed - thank you! Can't find mention of it in the release notes, but I'm on 25.0.1.202503231807 now and I was able to modify a row through the GUI without problems.

**Comment by pferreirafabricio** [comment]
For anyone with this problem, maybe this comment can help: https://github.com/dbeaver/dbeaver/issues/37459#issuecomment-2935864740

**Comment by dentsu-sh** [comment]
As addition to @pferreirafabricio comment:

I used only the global settings (disabled the data source settings). 
Fiddling with this setting seems to change the way the information is read or cached. Now the PK information is known to DBeaver also when disabling the data source setting.
