### ISSUE TITLE
Dragging connection in Database Navigator

### ISSUE THREAD

**Issue by indricilia** [dbeaver/dbeaver#6338]
After importing all my dbvisualizer connects (thanks for that... great feature), I cannot organise the connections into the folders I require because a drag does not go beyond the length of the panel.

I'm running Dbeaver 6.1.3 Community Edition on a Fedora  30 64 bit installation.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by E1izabeth** [comment]
It seems this issue is not active anymore. I can scroll the navigator tree if I more dragged object to the top or bottom of the navigator window
