### ISSUE TITLE
Soft wrap value in value viewer

### ISSUE THREAD

**Issue by bytesnz** [dbeaver/dbeaver#6340]
**Is your feature request related to a problem? Please describe.**
Long single line values, such as JSON strings, can require a lot of horizontal scrolling to view the entire value

**Describe the solution you'd like**
Add an option to soft wrap values in the value viewer

**Describe alternatives you've considered**
Horizontal scrolling is the only option at the moment. The strings can't be formatted to include new lines

**Additional context**
![image](https://user-images.githubusercontent.com/1755886/61792530-e0773b00-ae14-11e9-9dc6-ee53032e1c89.png)

**Comment by p91paul** [comment]
This feature is available, it's in the dropdown next to the book icon in your screenshot

**Comment by bytesnz** [comment]
Doh. How did I miss that. Cheers.
