### ISSUE TITLE
Oracle Scheduled Jobs Error

### ISSUE THREAD

**Issue by benjminer** [dbeaver/dbeaver#6342]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro (1809)
- DBeaver version: 6.1.3

#### Describe the problem you're observing:
When browsing in the Database Navigator to Scheduler > Jobs, a error pops up due to it unable to find the image file.

![image](https://user-images.githubusercontent.com/8846747/61806131-659e2800-adf4-11e9-8497-55f5ab43aa1e.png)

A similar error occurs when double clicking on the job to view the job details.

![image](https://user-images.githubusercontent.com/8846747/61806334-bdd52a00-adf4-11e9-9056-59b83240ebf0.png)

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/61883371-ff53fb00-af02-11e9-955f-e86f78e578f3.png)
