### ISSUE TITLE
 "Default database/schema" is not saved

### ISSUE THREAD

**Issue by cerebel** [dbeaver/dbeaver#6343]
#### System information: 
w7_x64
DBeaver 6.1.3 ce .zip
jdk1.8.0_212_x64
 
#### Connection specification:
 db: Oracle 12
driver: Oracle JDBC driver [12.1.0.2.0] 

#### Describe the problem you're observing:
 Default database/schema is not saved.
#### Steps to reproduce, if exist:

1. start dbeaver in clean new profile 
 >  dbeaver.exe -data   someNewPath
2. add driver of: Oracle JDBC driver 
3. create a new connection to db oracle 
4. on Projects:general->connection  'edit connection (F4)'
   under connectionSettings->initialization  set  "default database/schema" with another value which is not associated with current user
5. make disconnect session and  connect session  - the schema is OK [ point (4.) "default database/schema"]
6. File->exit
7.  start dbeaver
 >    dbeaver.exe -data   someNewPath
8.  repeat point (4.) - as result ->  "Default database/schema" is empty
 
9. Later, I tested this with open workspace created by 6.1.2 - the schema was saved ok, and on make connection (disconnect, connect) - the schema is ok.

**Comment by cerebel** [comment]
@serge-rider  mark as fixed in #6356

**Comment by serge-rider** [comment]
Thanks for info
