### ISSUE TITLE
Double click on node open data

### ISSUE THREAD

**Issue by daevidvincent** [dbeaver/dbeaver#6344]
I would like a preference option such that **double-click on a node** (ie. a Table) opens up the **Data tab** (the tab next to _Properties_  which is the only option available now).

![image](https://user-images.githubusercontent.com/20825058/61820710-6d68c700-ae0a-11e9-9e19-21b229d7c321.png)

**Comment by serge-rider** [comment]
I'll make it a bit more general:

![image](https://user-images.githubusercontent.com/6398845/62821940-0e7eae00-bb7d-11e9-9bd3-cca25efe6a74.png)

**Comment by kseniiaguzeeva** [comment]
Verified
