### ISSUE TITLE
SQL using GROUP BY clause don't perform with DBeaver, but perform with HeidiSQL and pgAdmin 4 [bug or question]

### ISSUE THREAD

**Issue by 01viniciusmelo** [dbeaver/dbeaver#6346]
#### System information: 
- Operating system and version: Windows 10
- DBeaver version: 6.1.3 (and all versions)
- Java version: 11.0.3.0
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgreSQL 11.0.4.19175
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

I am having problem running SQL with GROUP BY clause using DBeaver. Making a comparison using HeidiSQL and pgAdmin I don't have the same problem. I believe it is a bug.

My SQL with GROUP BY clause:
(Part 1)
![20190724_201152](https://user-images.githubusercontent.com/7417002/61836627-6d42e880-ae57-11e9-95c9-5fda164cdf94.jpg)
(Part 2)
![20190724_201211](https://user-images.githubusercontent.com/7417002/61836659-9499b580-ae57-11e9-9858-4e679ff51504.jpg)

Error GROUP BY clause with DBeaver:
![20190724_200821](https://user-images.githubusercontent.com/7417002/61836673-a7ac8580-ae57-11e9-8749-1f24318c0885.jpg)

This same SQL using GROUP BY clause with pgAdmin 4.10 and HeidiSQL 10.2.0.5599 performed and showed data:
(pgAdmin 4.10)
![20190724_201123](https://user-images.githubusercontent.com/7417002/61836684-b004c080-ae57-11e9-9642-dc0c07d439e2.jpg)
(HeidiSQL 10.2.0.5599)
![IMG_20190724_210901_617](https://user-images.githubusercontent.com/7417002/61837184-f9eea600-ae59-11e9-8675-6663df372dcc.jpg)

**Comment by serge-rider** [comment]
This caused by empty line in the middle of your query.
By default DBeaver treats empty line as query delimiter.
You can:
- Select your query before executing it (in this case dbeaver executes selected text ignoring any delimiters)
- Disable this feature in preferences (min menu Window->Preferences):
![image](https://user-images.githubusercontent.com/6398845/61852746-7dd87a80-aeba-11e9-91ef-d71e8a614daa.png)

**Comment by 01viniciusmelo** [comment]
Okay. I get it, but from my point of view I see that I could improve the message when that happened. The error message demonstrates that it would actually be an error in my SQL, but it is not. I suggest you enter this option in preferences at the end of the Run command.

**Comment by 01viniciusmelo** [comment]
Thanks, @serge-rider .
