### ISSUE TITLE
more intuitive new SQL tab

### ISSUE THREAD

**Issue by rdp** [dbeaver/dbeaver#6348]
When I first tried out dbeaver, I could traverse database table tree hierarchy, and modify data there, but it wasn't clear how to pull open a new "SQL query" tab.  If you right click near the tabs the only option is "close" or "detach" no "open new tab" or anything.
<img width="521" alt="Screen Shot 2019-07-25 at 9 41 01 AM" src="https://user-images.githubusercontent.com/12496/61888484-cbf07c80-aec0-11e9-8cd5-832e54410354.png">

Appears I'm not the only one who gets confused by this: https://stackoverflow.com/q/34526817/32453

Wonder if there's a way to make it more intuitive here.  Thanks!

**Comment by cerebel** [comment]
You have in main menu 'special' item "SQL Editor"  (and two additional icons in Toolbar for sql editor).

**Comment by rdp** [comment]
Hmm OK those buttons on the toolbar work.  But it's not immediately evident to a beginner what they do, and it takes actually awhile for the tooltip to appear to explain it.  A couple more options that might help for the newbie: having the "tooltip" appear for the toolbar more quickly.  Or change the icon so it includes "SQL" somehow.  And/or having a right click menu on the "connection" have an option "new SQL" that type of thing... :)

**Comment by rdp** [comment]
I think the general gist of this can be boiled down to "the SQL Editor toolbar mini icon" is...confusing...it looks like little snakes or something eating one another?  At least for me I didn't know what it meant initially...
