### ISSUE TITLE
Apache Drill driver not working since 6.1.0

### ISSUE THREAD

**Issue by mlrabbitt** [dbeaver/dbeaver#6352]
Windows 10 x64 v1903
DBeaver 6.1.3
Included JRE version

Apache Drill JDBC 1.16
org.apache.drill.jdbc.Driver

Since 6.1.0 release, connections using JDBC Drill driver fail with one of two errors:

> Unexpected driver error occurred while connecting to database
>   com/sun/management/OperatingSystemMXBean
>   com/sun/management/OperatingSystemMXBean
>     com.sun.management.OperatingSystemMXBean
>     com.sun.management.OperatingSystemMXBean

or

> Unexpected driver error occurred while connecting to database
>   Could not initialize class oadd.org.apache.drill.exec.memory.RootAllocator
>   Could not initialize class oadd.org.apache.drill.exec.memory.RootAllocator

To reproduce, just open new connection for Apache Drill and click "Test Connection".  Nothing needs to be populated to test.

**Comment by serge-rider** [comment]
We missed jdk.management module in redist JDK.
Thanks for the bug report.

**Comment by serge-rider** [comment]
You can test the fix in Early Access version (https://dbeaver.com/files/ea)

**Comment by uslss** [comment]
verified
