### ISSUE TITLE
Failed to create java virtual machine .

### ISSUE THREAD

**Issue by RooyeKhat** [dbeaver/dbeaver#6353]
#### System information: 
- Operating system (distribution) and version
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.18362 Build 18362

- DBeaver version
6.1.3
- Java version
 Recommended Version 8 Update 221 (filesize: 1.97 MB)

- Additional extensions
None

Upgrade dbeaver 6.1.0. to 6.1.3 and happens this problem

**in cli mode show this error :**

> <JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.

**Comment by sonotley** [comment]
Same for me Java 1.8.0_91

**Comment by RooyeKhat** [comment]
> Same for me Java 1.8.0_91
> 
> Rolled back to 6.1.1 and working ok.

Although this bug is there, it's the only fast fixing solution
Once you completely remove the software and install it again, the problem will be resolved

**Comment by sonotley** [comment]
Doesn't the installer perform an uninstall first? What component needs uninstalling to workaround the error?

**Comment by RooyeKhat** [comment]
> Doesn't the installer perform an uninstall first? What component needs uninstalling to workaround the error?

1- First Remove DBeaver
2- install again and with reset setting
![image](https://user-images.githubusercontent.com/13883221/62006018-88ac3d00-b150-11e9-9f46-426ab330dff7.png)

Do not forget about this part
Environment variables  > system variables > Path
C:\Program Files (x86)\Java\jre1.8.0_221\bin

![image](https://user-images.githubusercontent.com/13883221/62006035-babd9f00-b150-11e9-95bd-49dfaaa92c2a.png)

**Comment by serge-rider** [comment]
Why don't you want to use JDK shipped along with DBeaver (OpenJDK11 in 6.1.+)?
There is no need to install any JRE/JDK anually and bundled JDK is the most tested and well-suitable JDK version for DBeaver.

**Comment by rom1k669** [comment]
In my case, to rollback, you don't need to manually uninstall current version and reset settings while installing older. Just install older version (I also changed install path), and it will save all your connections and settings. 
(Saved scripts you can find there: C:\Users\*user*\.dbeaver4\General\Scripts)

**Comment by jaharnum** [comment]
I'm using Windows 10, haven't messed with the settings as far as using the bundled JDK, *and* I have Java 1.8.0 installed and in path anyways, but I also had this issue with the latest update and went back to 6.1.0

**Comment by sonotley** [comment]
There seems to be a lot of confusion here. I uninstalled 6.1.1 using the uninstaller and then installed 6.1.3 with 'reset settings' and it worked fine. I didn't do anything to my Java path and I didn't lose any connections or scripts, they all carried over fine.

**Comment by RooyeKhat** [comment]
> There seems to be a lot of confusion here. I uninstalled 6.1.1 using the uninstaller and then installed 6.1.3 with 'reset settings' and it worked fine. I didn't do anything to my Java path and I didn't lose any connections or scripts, they all carried over fine.

i say in older post for me solve with this way.

**Comment by RooyeKhat** [comment]
@serge-rider please change this labels to bug because many user when upgrade to 6.1.3 have this problem 
this is not question this subject is problem with upgrade to new version

**Comment by serge-rider** [comment]
@RooyeKhat I still can't figure out what is actually wrong.

1. What the point to install Java manually? It is already included in the DBeaver installer. 
1. We use Java 11 since 6.1.1.
1. Please post some error message/screenshot/stacktrace. At the moment it is not clear what is this ticket about.

**Comment by sonotley** [comment]
> @RooyeKhat I still can't figure out what is actually wrong.
> 
> 3. Please post some error message/screenshot/stacktrace. At the moment it is not clear what is this ticket about.

I believe these steps should reproduce the issue (sorry, haven't tested as I only have one environment available and I'm using that to work in). OS is Windows 10.

1. Install DBeaver 6.1.0
2. (there may be a step here to create some clutter in the settings etc)
3. Run DBeaver 6.1.3 installer without 'reset settings' checked
4. Start DBeaver
5. Observe that application fails to start with error "Failed to create Java Virtual Machine"

**Comment by kaianuar** [comment]
6.1.4 also has the same issue. Installed with reset settings unchecked and error message appears when starting the app. Reinstalled with reset settings checked and app started without errors.

**Comment by RooyeKhat** [comment]
@serge-rider any update ?

**Comment by kolykhalov** [comment]
Same here with 6.1.5, you have to reset settings at reinstall, what a bugger [sigh].

**Comment by chr1xm** [comment]
@RooyeKhat it worked your solution for me, thank you!

**Comment by CBlack42** [comment]
HI! For the EE 6.2.0 install, I had the same issue. I found if I installed the Community 6.2.3 with JRE package, the 6.2.0 launched without failure. <<shrug emoji>> This is the second time I have run into this error. The first time with the EE 6.1 version, adding the Java Heap Size and Memory Size to the Java Options in the System Environment Variables fixed the issue. When I installed 6.2.0, it all broke. So, I dunno if the next version is going to break all this, but for now, it's all up and running and working great. Good luck with anyone still having this issue.

**Comment by razonrus** [comment]
Same problem with 6.2.5. I just downloaded & installed 6.2.3 version and all works again
https://github.com/dbeaver/dbeaver/releases/tag/6.2.3

**Comment by sebnukem** [comment]
Same problem with 6.3.3 and openjdk 11.0.6 on macOS

**Comment by dgcofer** [comment]
Was able to get Dbeaver to start with an installation of Oracle JDK 8 update 202 on my Mac in `/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home` I just had to edit the `/Applications/DBeaver.app/Contents/Info.plist` file.

I added the following under the `<key>Eclispe</key>`

```xml
<key>Eclipse</key>
  <array>
    <string>-vm</string<string>/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java</string>
    <!-- Other properties left out-->
  </array>
```
Dbeaver would fail to start with AdoptOpenjdk version 11.0.6

### Works for Oracle JDK 8 Update 202
```
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```

### Fails for AdoptopenJDK version 11.0.6
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```

**Comment by MikailSrmt** [comment]
> Original
 ```<key>Eclipse</key>
  <array>
    <string>-vm</string<string>/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java</string>
    <!-- Other properties left out-->
  </array>
```
> Quote

Thanks @dgcofer 
There is small syntax error on your config.

```
<key>Eclipse</key>
  <array>
    <string>-vm</string>
    <string>/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java</string>
    <!-- Other properties left out-->
  </array>

**Comment by neverfox** [comment]
Unfortunately, @dgcofer's solution doesn't work with [adoptopenjdk](https://github.com/AdoptOpenJDK/homebrew-openjdk) JVMs.

**Comment by neverfox** [comment]
@dgcofer Any thoughts on why it would fail with AdoptOpenJDK?

**Comment by fasfsfgs** [comment]
I'm having this issue with version 7.0.1.
macOS High Sierra 10.13.6

**Comment by steveoh** [comment]
@neverfox 

```sh
$ brew cask install java11
Error: Cask 'java11' is unavailable: No Cask with this name exists.
```

**Comment by neverfox** [comment]
@steveoh You need to tap versions first: `brew tap homebrew/cask-versions`

**Comment by banfware** [comment]
I'm having this issue with version:
Dbeaver 7.0.1.
macOS Mojave 10.14.5 (18F132)
java -version
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment (build 14+36-1461)
OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

**Comment by miun173** [comment]
> I'm having this issue with version:
> Dbeaver 7.0.1.
> macOS Mojave 10.14.5 (18F132)
> java -version
> openjdk version "14" 2020-03-17
> OpenJDK Runtime Environment (build 14+36-1461)
> OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

Yeah, i got this message when launch dbeaver `Failed to create the Java Virtual Machine.`

**Comment by banfware** [comment]
> > I'm having this issue with version:
> > Dbeaver 7.0.1.
> > macOS Mojave 10.14.5 (18F132)
> > java -version
> > openjdk version "14" 2020-03-17
> > OpenJDK Runtime Environment (build 14+36-1461)
> > OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
> 
> Yeah, i got this message when launch dbeaver `Failed to create the Java Virtual Machine.`
> Well, i solved this by using this java version
> 
> ```
> java -version
> 
> java version "12.0.1" 2019-04-16
> Java(TM) SE Runtime Environment (build 12.0.1+12)
> Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
> ```

Thank miun173, this means that I have to downgrade the java version from 14 to 12.
I will update asap.

**Comment by banfware** [comment]
Miun173, BINGO!
Thank you very much.

**Comment by serge-rider** [comment]
Issue with OpenJDK for MacOS is tracked in #8229

**Comment by DanielNetoP** [comment]
I add this problem but after latest adoptopenjdk 11.0.7 it started to work again on my mac.

**Comment by jamessa** [comment]
1.3 works for me. Thank you all.

```
$ brew cask install adoptopenjdk13
$ java -version
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)

```

**Comment by rdp** [comment]
reinstall worked for me on OS X after I got this message after the OS upgraded to big sur, for followers... :)
