### ISSUE TITLE
Did not detect columns when creating table in PostgreSQL

### ISSUE THREAD

**Issue by marcospgp** [dbeaver/dbeaver#6354]
I was creating a PostgreSQL table and when trying to save the query appeared without columns, even though I had created them.

After confirming and creating the table, no columns were created (should have guessed from the query) but my locally created columns were all erased.

Things that might have caused this:

* I had a table with the same name previously. I might have renamed the old one only after opening a "create table" tab, causing dbeaver to think the table already existed.
* I had two tabs open with the same table I was creating. I tried saving my changes from both - one could not do it because it was trying to run "ALTER TABLE" and the table did not yet exist. The other did it but pushed no columns and erased my work.

Lost a bit of work there! 😄

**Comment by uslss** [comment]
cannot reproduce an issue against recent version (7.0).
Ticket will be closed.
If issue is still actual for you, feel free to reopen the ticket with additional info that could be helpful for issue reproducing
