### ISSUE TITLE
Transaction/Execution log for (GUI) actions outside of the script environment

### ISSUE THREAD

**Issue by 97-109-107** [dbeaver/dbeaver#6355]
I'd like to see the exact commands dbeaver has executed (or is scheduled to) when doing

- Database → Tools → Execute Script
- Table → Export data → [export to another database with mapping]

Motivation - I have some maintenance operations that I'd like to automate and schedule from outside dbeaver.

Neither [Log files](https://github.com/dbeaver/dbeaver/wiki/Log-files) nor [Transaction log](https://github.com/dbeaver/dbeaver/wiki/Transaction-Log) provide a log of the above.

**Comment by uslss** [comment]
If I understand you right, you could do this using [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager).
Sorry for so late response
