### ISSUE TITLE
Improve SQL Autocomplete and implement shortcut syntax feature

### ISSUE THREAD

**Issue by NightlyFox** [dbeaver/dbeaver#6357]
This is what would be nice to see
SELECT { * FROM ? } -> highlighted:light-blue,opacity:75
LEFT { JOIN ? alias ON alias.? = ? } -> highlighted:light-blue,opacity:75

Have a slightly highlighted and transparent suggestion for the statement, basically what is within the {} above, but without the {} when suggesting in the UI. Suggestions would be made for all common sql syntax. Suggestions will also make suggestions based on the type of database you are connected too.

Pressing tab will auto type the statement and then take you through each of the ?, when you press enter it will take you too the next ? and so on until statement is finished. 

It will really help with writing/remembering sql syntax and speed up the amount of time usually taken with writing the whole statement. 

As a more advanced features, users should be able to create their own suggestions so that if they often write something that is not in the built in suggestion engine then they can add it themselves.

A shortcut feature where i can type something like :shortcut and when you press tab it will automatically write out predefined sql code you made for that shortcut name.

**Comment by uslss** [comment]
a similar feature is already implemented
https://github.com/dbeaver/dbeaver/wiki/SQL-Templates
