### ISSUE TITLE
Creating MariaDB strored procedure with DBeaver generates unclear error.

### ISSUE THREAD

**Issue by schwabenheinz** [dbeaver/dbeaver#6359]
#### System information: 
- Linux Mint 19.3
- DBeaver version 6.1.3
- Java version 
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

#### Connection specification:
- Database name and version: MariaDB 10
- Driver name: ?
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
See also: [](https://stackoverflow.com/questions/57222928/mariadb-strored-procedure-gerates-unclear-error-whats-wrong)

#### Steps to reproduce, if exist:
I created an SQL Query, which works fine in DBeaver. 
Now I would like to change it to a stored procedure but still without success.

Following is my code:
```

DELIMITER //
CREATE PROCEDURE hibiscus.findAllForPivot
 (
     IN jahr varchar(4),
     IN kontos VARCHAR(500)
 )
   BEGIN
select 
 VCT.l1_Id,
 VCT.l1_GroupName,
 VCT.l2_Id,
 VCT.l2_GroupName,
 sum( case when (VCT.monat = 1) then dbetrag end ) AS `jan`,
 sum( case when VCT.monat = 2 then dbetrag end ) AS `feb`,
 sum( case when VCT.monat = 3 then dbetrag end ) AS `mrz`,
 sum( case when VCT.monat = 4 then dbetrag end ) AS `apr`,
 sum( case when VCT.monat = 5 then dbetrag end ) AS `mai`,
 sum( case when VCT.monat = 6 then dbetrag end ) AS `jun`,
 sum( case when VCT.monat = 7 then dbetrag end ) AS `jul`,
 sum( case when VCT.monat = 8 then dbetrag end ) AS `aug`,
 sum( case when VCT.monat = 9 then dbetrag end ) AS `sep`,
 sum( case when VCT.monat = 10 then dbetrag end ) AS `okt`,
 sum( case when VCT.monat = 11 then dbetrag end ) AS `nov`,
 sum( case when VCT.monat = 12 then dbetrag end ) AS `dez`
 from hibiscus.V_HibCrosUmsGiroOpaOmaReport VCT
 where  VCT.jahr = jahr and VCT.konto_id in (kontos)
 group by VCT.L1_id, VCT.L1_GroupName, VCT.L2_id, VCT.L2_GroupName;
 END 
 //
 DELIMITER ;
```

I got always the following error:

```
SQL-Fehler [1064] [42000]: (conn:26) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 26
Query is : CREATE PROCEDURE hibiscus.findAllForPivot
```

If I remove the group by line, the same error is at line 25 If I use the complete select statement with where and group by alone, everything works fine! I check double the fields in the table.
I thought will get mad because I can't find the reason.
The fields in the table are (entered by copy&paste):

dBetrag
id
Jahr
JahrMonat
konto_id
L1_GroupName
L1_id
L2_GroupName
L2_id
Monat

I did the same with PhpMyAdmin and did not get this error. Everything was fine, the procedure was created.
I assume that the reason is something around DBeaver.

Thank you in advance
Schwabenheinz

**Comment by uslss** [comment]
is it still actual against the recent version (7.0)?

**Comment by schwabenheinz** [comment]
Thank you for asking!
Yes, i tried it with Version 7.0.0.202003021717.
I got:
SQL-Fehler [1064] [42000]: (conn:33) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 26
Query is : CREATE PROCEDURE hibiscus.findAllForPivot.........

**Comment by LonwoLonwo** [comment]
It is still actual in [new versions](https://dbeaver.io/)? 
Some changes have been added to the query parsing in the SQL Editor

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it
