### ISSUE TITLE
DBeaver should warn before opening dozens of tables / views etc.

### ISSUE THREAD

**Issue by mboeringa** [dbeaver/dbeaver#6360]
**DBeaver Version: 6.1.3**

**Is your feature request related to a problem? Please describe.**
Currently, if I select a few dozens tables in an attempt to e.g. delete them, and if I subsequently accidentally double click the selection, DBeaver opens up all tables / views selected without issuing any warning. If the list of tables was long, I end up with dozens of opened TABs in the DBeaver window. Maybe I have missed it, but there doesn't seem to be any menu option to close all open TABs in one action, so I need to manually close each object (Closing DBeaver and re-opening it will also re-open all open TABs again...)

**Describe the solution you'd like**
DBeaver should either warn before opening multiple tables / views etc., or DBeaver should offer a menu option to close all tabbed windows in one go.

**Describe alternatives you've considered**

**Additional context**
![afbeelding](https://user-images.githubusercontent.com/7635726/61994092-60501000-b076-11e9-96ed-2b398b528d3a.png)

**Comment by serge-rider** [comment]
Good point

**Comment by serge-rider** [comment]
DBeaver will show confirmation dialog if you are opening more than 3 editors at once.

**Comment by p91paul** [comment]
on a side note, DBeaver does allow to close all tabs by right-clicking on one of them.

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by mboeringa** [comment]
@p91paul 

Thanks for the tip, stupid, I missed that one! 

I already tried right-clicking, but not with the mouse hovering exactly over the TAB itself, hence I didn't encounter the context menu.
