### ISSUE TITLE
Improve "sql to java code" feature

### ISSUE THREAD

**Issue by stalent** [dbeaver/dbeaver#6363]
Hi there,
When we use copy sql as java code feature in "Choose Format" panel, Java code results something like this:

```
"select\n" + 
"*\n" + 
"from\n" + 
"table;\n";
```

May we improve this feature with StringBuilder instead of using "+"? 

```
query.append("select");
query.append("*");
query.append("from");
query.append("table;")
```

Or may we add  customization options in this panel?

plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/convert/impl/JavaSQLConverter.java

```
for (int i = 0; i < sourceLines.length; i++) {
            String line = sourceLines[i];
            result.append('"').append(CommonUtils.escapeJavaString(line)).append(lineDelimiter).append('"');
            if (i < sourceLines.length - 1) {
                result.append(" + \n");
            } else {
                result.append(";");
            }
        }
 
```

**Comment by serge-rider** [comment]
This can be improved by adding extra config options (in additions to existing two options). E.g. "Use StringBuilder".

**Comment by loro2** [comment]
Hi there,
I'm looking forward to contribute some code to this project, and this issue one seems like an ideal starting point. I'd be happy to take it.

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/62368701-0c41a180-b536-11e9-9322-88e280ea559f.png)

**Comment by stalent** [comment]
Hi there,
Firstly, Thanks for the job.
May we remove the new line character "\n" from each line? You know as a developer, when we use stringbuilder for create query, it is not necessary using new line character. Besides it has '\n' character, it will fail to execute directly and we will have to remove it again.
Don't you agree with?

**Comment by loro2** [comment]
You can set the "line delimiter" value to blank and it will remove the '\n' characters.
