### ISSUE TITLE
List of scripts panel overflow main screen

### ISSUE THREAD

**Issue by dwhitz** [dbeaver/dbeaver#6364]
It's the same bug open here #6087, I've already asked **to re-open that issue because was not fixed** in release 6.1.2. (I've also tested with v.6.1.3)

The panel continues overflow the borders, is really annoying and almost useless, you can see it with the attached video. [dbeaver_panel_bug](https://github.com/dbeaver/dbeaver/files/3439585/dbeaver_panel_bug.zip)

I hope that you can now check it and/or give me a feedback.

**Comment by serge-rider** [comment]
Fixed (for all popup panels, not just for script selector)

**Comment by uslss** [comment]
verified
