### ISSUE TITLE
DBeaver deletes all rows when I accidentally delete a row w/o primary key

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#6365]
#### System information: 
- Operating system (distribution) and version
Windows 10 Enterprise 10.0.16299

- DBeaver version
5.1.6.201808262133

- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

When I select some table and forget to select the primary key, and manually delete one record, and hit save, it deletes every row in the table

I would like to understand how to remove this default behavior, as it has led me to deleting every row in a table several times. 

It should either error or at the very least not do anything

#### Steps to reproduce, if exist:

- create some table with primary key, add 10 rows
- instead of select *, so select col_not_primary_id
- delete the row in the table editor
- hit save, and bottom right status will show it has deleted all the rows

**Comment by serge-rider** [comment]
I can't reproduce this.
Whenever DBeaver sees that table doesn't have unique key or unique index it asks user to specify "virtual" unique key (on client side). 
![image](https://user-images.githubusercontent.com/6398845/62070196-51b25600-b23a-11e9-9118-13a802f24f4e.png)
If user doesn't set such key then delete fails.
So, I can't reproduce situation when there is no unique key and DBeaver still deletes a row(s) from a table:
![image](https://user-images.githubusercontent.com/6398845/62070260-6e4e8e00-b23a-11e9-95e2-c0bc8b981b4b.png)

Could you list steps to reproduce this issue?
Also it is possible that you set some non-unique column as virtual unique key.

**Comment by rdp** [comment]
screencast recording possible please?

**Comment by uslss** [comment]
there is no updates on ticket more than a month. 
ticket closed
