### ISSUE TITLE
There are not a search line in some column filters of Reference table

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#6367]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 6.1.4
- Java version 11
- Additional extensions

#### Connection specification:
- Database name and version MySQL 8+, PostgreSQL
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
There are not a search line in some column filters of Reference table. The same situation with filters of a source table.
#### Steps to reproduce, if exist:
1. open MySQL 8+ db> sakila>country> Data tab (or any other table with foreign key)
2. select any column  and open References panel
3. Check column filters of the reference table
![filter search reference panel](https://user-images.githubusercontent.com/51405061/62026074-9a3e2500-b1e2-11e9-9782-aaf902fb421f.gif)

**Comment by serge-rider** [comment]
We don't show search panel if column type is not string (char/varchar) and it is not a dictionary (not a foreign key).
I've added a few fixes in dictionary values search function.

**Comment by kseniiaguzeeva** [comment]
Verified
