### ISSUE TITLE
GIS Spatial Map View broken

### ISSUE THREAD

**Issue by FaySmash** [dbeaver/dbeaver#6369]
#### System information: 
- Operating system **Windows 10 x64**
- DBeaver version **6.1.3 portable**
- Java version **Java 8 Update 201**
- Additional extensions **-**

#### Connection specification:
- Database name and version **MySQL 5.7**
- Driver name **mysql-connector-java-8.0.17.jar**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **-**

#### Describe the problem you're observing:
Spatial Map View stays blank.

#### Steps to reproduce, if exist:
Connect to a DB holding spatial files, select a cell containing a coordinate, activate the Map Panel.

#### Include any warning/errors/backtraces from the logs

No logs were written, but I opened the created HTML file in an external Webbrowser and used the Development-Tools to narrow down the issue to the line:

```
var sourceTips = [ {"fid":"14","gml_id":"DEBYvAAAAABZbnVL","gml_parent_id":"DEBYvAAAAABZbnC3","gml_modellart":"DLKM","punktart":"30","dfk_type":"13001","viewmode":"1400","viewmode2":"0","sym_name":"3020","breite":"1.0","z_relativ":"0.0","sym_bezeichnung":"Meißelzeichen","info":"
S<=  3 cm","featurename":"AX_Aufnahmepunkt","x":"585946.8","y":"5546017.6","t_gml_dt":"2018-01-03 15:02:37","fid_fme":"32230"} ];
```

The issue is, that there is a linebreak after the 268th character on line 26. It was displayed, after I removed the linebreak:

```
var sourceTips = [ {"fid":"14","gml_id":"DEBYvAAAAABZbnVL","gml_parent_id":"DEBYvAAAAABZbnC3","gml_modellart":"DLKM","punktart":"30","dfk_type":"13001","viewmode":"1400","viewmode2":"0","sym_name":"3020","breite":"1.0","z_relativ":"0.0","sym_bezeichnung":"Meißelzeichen","info":"S<=  3 cm","featurename":"AX_Aufnahmepunkt","x":"585946.8","y":"5546017.6","t_gml_dt":"2018-01-03 15:02:37","fid_fme":"32230"} ];
```

**Comment by FaySmash** [comment]
Issue:

![Unbenannt](https://user-images.githubusercontent.com/30392780/62041846-ed24d600-b1fc-11e9-9c7f-f977afd80361.PNG)

Error:
![grafik](https://user-images.githubusercontent.com/30392780/62041907-0fb6ef00-b1fd-11e9-8a19-f1fc46815167.png)

![grafik](https://user-images.githubusercontent.com/30392780/62041933-1e050b00-b1fd-11e9-987d-6af5ba6f021d.png)

Fixed:

![grafik](https://user-images.githubusercontent.com/30392780/62041971-3aa14300-b1fd-11e9-9085-52edc714f05c.png)

![grafik](https://user-images.githubusercontent.com/30392780/62041992-455bd800-b1fd-11e9-8a65-02c81199c049.png)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified

**Comment by porfirioribeiro** [comment]
I'm having this problem on latest dbeaver on Manjaro Linux installed via Flatpak

![imagem](https://user-images.githubusercontent.com/499246/66493341-c82aca00-eaad-11e9-8285-98774e2872e1.png)

**Comment by serge-rider** [comment]
On Linux DBeaver embed FireFox browser in order to show spatial data. I see two possible causes of this problem:
- Something went wrong in Flatpak installation (e.g. some deps are missing). You could try to install from deb package to test this
- Something is wrong with FireFox embedding on your system. It may or may not be related to Flatpak.

**Comment by porfirioribeiro** [comment]
Installing dbeaver from pacman the issue does not exist.
Sadly because flatpak is official and always updated before the pacman one.

**Comment by djagar** [comment]
I have the same issue as original https://github.com/dbeaver/dbeaver/issues/6369#issue-473975307 .
System information:
- Operating system Windows 10 x64
- DBeaver version 6.2.5
- java.version=11.0.5

Connection specification:
- PostgreSQL 10.11 (Debian 10.11-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
- PostgreSQL JDBC Driver 42.2.5

Additionally, an error pop-up appears when trying to switch to spatial view:

![Exception](https://user-images.githubusercontent.com/28300962/70733245-3daf5280-1d0a-11ea-8907-8b8ca982894f.PNG)

**Comment by serge-rider** [comment]
@djagar this looks like a very different issue (original one was fixed a time ago).
Please upgrade to 6.3 and post error log (you can get it in error log view - https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by djagar** [comment]
@serge-rider please find attached [dbeaver-debug_anonymised.log](https://github.com/dbeaver/dbeaver/files/3960108/dbeaver-debug_anonymised.log).

**Comment by djagar** [comment]
@serge-rider please find attached [dbeaver-debug_anonymised.log](https://github.com/dbeaver/dbeaver/files/3960145/dbeaver-debug_anonymised.log).
