### ISSUE TITLE
Data Transfer IO issue

### ISSUE THREAD

**Issue by UserIssue213** [dbeaver/dbeaver#6370]
Unable to export anything.  Receiving a "Data transfer completed with errors" message each time.  I have re downloaded the application, but still showing issues.  Did not have issues last week.  I'm running this from Windows and using the latest version.
[Dbeaver Error.log](https://github.com/dbeaver/dbeaver/files/3442227/Dbeaver.Error.log)

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
You can't use backslash characters ( \ ) in output file names.
Use some other dates divider.
