### ISSUE TITLE
Can't edit SQLite column of existing database with DBeaver

### ISSUE THREAD

**Issue by baermathias** [dbeaver/dbeaver#6373]
#### System information: 
Ubuntu 19.04
DBeaver version 6.1.3.201907211943

#### Connection specification:
SQLite
SQLite JDBC driver by Taro L. Saito (extension of Zentus driver)

#### Describe the problem you're observing:
The SQLite database was created with Python Django. I can open it and add columns, but can't edit the existing columns with DBeaver. If Columns are added with DBeaver, they can be edited.

#### Steps to reproduce, if exist:
Connect to DB
Then open DB -> Tables -> Columns
Choose a column and right-click it, then choose `EDIT Column`
Chhose ANY input field and try to write something else into it, doesn't work!

**Comment by serge-rider** [comment]
Was fixed in 7.0 (new SQLite driver supports columns add/drop/rename)
