### ISSUE TITLE
dbeaver at window7 connect phoenix kerberos error

### ISSUE THREAD

**Issue by kaiqiangmeng** [dbeaver/dbeaver#6376]
#### System information: 
- Operating system (distribution) and version
  windows 7
- DBeaver version

#### Connection specification:
- Database name and version
  dbeaver-ce-6.1.3
#### Describe your question:
connect phoenix error：
Unexpected driver error occurred while connecting to database
  org.apache.hadoop.security.authentication.util.KerberosUtil.hasKerberosKeyTab(Ljavax/security/auth/Subject;)Z
  org.apache.hadoop.security.authentication.util.KerberosUtil.hasKerberosKeyTab(Ljavax/security/auth/Subject;)Z

 in dbeaver.ini add
-Djavax.security.auth.useSubjectCredsOnly=false
-Djava.security.krb5.conf="D:\mkq\soft\dbeaver\krb5.ini"
-Dsun.security.krb5.debug=true

Error not resolved

**Comment by serge-rider** [comment]
This problem caused by extra hadoop jars in dependencies. We'll fix Phoenix driver config so it will use just client jar.

**Comment by serge-rider** [comment]
Note: Phoenix driver doesn't work with OpenJDK 11.

**Comment by kseniiaguzeeva** [comment]
Verified
