### ISSUE TITLE
New table can't be created in PostgreSQL using DB Navigator tree

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#6377]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 6.1.4
- Java version 11
- Additional extensions

#### Connection specification:
- Database name and version PostgreSQL
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
New table can't be created in PostgreSQL using DB Navigator tree (mysql and Postgres in 6.1.2 haven't such problem)
#### Steps to reproduce, if exist:
1. Open DB Navigator tree> PostgreSQL> posgres>Public>Tables and create a new table by right click
2. Create a new column in Properties tab and press "Save".

Expected result: a new table is created
Actual result: "script generate error" window is shown ("java.lang.NullPointerException") without creating a table.
#### Include any warning/errors/backtraces from the logs
[.log](https://github.com/dbeaver/dbeaver/files/3445510/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3445512/dbeaver-debug.log)
![300719](https://user-images.githubusercontent.com/51405061/62107156-ae9c2380-b2af-11e9-9918-c94dc1438bfb.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
