### ISSUE TITLE
Data viewer: UIX improvements

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6379]
- We need to reduce number of items in context menus.
- Reduce number of context menus themselves
- Change the way we control column's view/behavior
- Add in-place virtual structure editor
- Fix toolbar icons

**Comment by cerebel** [comment]
Please 'disable' or  set as 'option' -  "Bold Text"  on  headers of row:column of selected cell.
![result_6 1 2_vs_6 1 4d](https://user-images.githubusercontent.com/7722567/62151765-c0121980-b309-11e9-8eb7-1ee862625a0b.png)

**Comment by serge-rider** [comment]
@cerebel what is wrong with bold font? We need a way to distinguish focus column/row from selected columns/rows.

**Comment by cerebel** [comment]
1. it's wider
![bold](https://user-images.githubusercontent.com/7722567/62204539-0a40dc80-b396-11e9-856e-9f0291ab6840.png)
 and less visible text 
![bold2](https://user-images.githubusercontent.com/7722567/62204568-1dec4300-b396-11e9-97a5-4589f01fec7d.png)

2. it's harder to read  (this aspect i also could provide )
  (by [example](https://www.lifewire.com/how-to-use-bold-type-effectively-1074100)  > Whole paragraphs of _text set in bold type are hard to read_. The reason bold type creates emphasis is that it slows down the reader and forces the eye to take in the words more carefully. If you slow them down too much, they may just skip over what you have to say.
)

It could be added as option:  general->appearance->basic 
  "Grid selected header  background" (this option exist)
+"Grid selected header  Font"  (as new)

**Comment by serge-rider** [comment]
@cerebel Agreed. We'll try another way (thin border around header column)

**Comment by uslss** [comment]
Changing of column format issue #6399

**Comment by uslss** [comment]
verified

**Comment by timkrins** [comment]
What is the reason for reducing number of items in context menu?
My most used context menu item was the Edit menu.
I can train myself to not use it but just wondering about the drive behind the change.

**Comment by serge-rider** [comment]
Most of Edit menu actions present in the bottom toolbar and they have shortcuts. Why to use context menu when it is 3 clicks instead of 1?

Rarely used commands were moved to the main menu Edit.

**Comment by pyrocks** [comment]
Not sure if it's related to the changes (I'm running the 6.1.4 early access) , but for some odd reason the data grid decided to bold the number "1" when I run a plain "select * from table" query:
![image](https://user-images.githubusercontent.com/18515297/62597825-eaf30380-b8ef-11e9-85f0-0399d30647b0.png)
If I add an order by to the query it does not reproduce. very strange.

**Comment by serge-rider** [comment]
@pyrocks are you on Mac? I've seen such glitch a couple of times on MacOS, have no idea how it happens.

**Comment by pyrocks** [comment]
Yes, on mac. So its a mac bug?

**Comment by maclof** [comment]
I do not think the right click edit menu should have been removed. Mistake imo.
