### ISSUE TITLE
Did the convert keyword setting dissapear?

### ISSUE THREAD

**Issue by Blanen** [dbeaver/dbeaver#6380]
I'm looking to disable dbeaver automatically converting keywords to lowercase. I think uppercase keywords makes SQL much more readable.

https://stackoverflow.com/questions/42004796/how-to-switch-the-capitals-characters-transform-in-dbeaver

https://github.com/dbeaver/dbeaver/issues/295

These settings seem to have dissapeared.

**Comment by Blanen** [comment]
Nevermind, this is now not under "General" but under "Database". Because that makes sense.

Also searching for any "Convert", "convert", "Keyword", "keyword" yields no results.

**Comment by tati-kru** [comment]
Actually this feature was divided to two different settings.
One of them is Database > SQL Editor > SQL formatting > Formatter dropdown. This is for to change case of keywords during formatting.
Another one is Database > SQL Editor > SQL Completion  > Auto format > Convert keyword case checkbox. This is for to auto-convert keywords to upper/lower case on Enter. 

I'm not sure what exactly you are looking for, you can check both.
