### ISSUE TITLE
PrimaryKey icon on header not appears on postgres

### ISSUE THREAD

**Issue by mcunha98** [dbeaver/dbeaver#6383]
I notice that, I manage mysql/mariadb and postgresql databases and for postgresql the icon of primary key not appear.

Here a comparative image to show what I talk about...

https://i.postimg.cc/1XJNR8DT/screenshot-496.png

**Comment by serge-rider** [comment]
It is a bit more tricky in PG than in MySQL (because we need to read pk info from different system table).
We will read this info in lazy mode (icon will appear only if table constraints were already read - this is always true for table data viewer).

**Comment by uslss** [comment]
verified
