### ISSUE TITLE
Edit foreign key

### ISSUE THREAD

**Issue by stormriderstudios** [dbeaver/dbeaver#6384]
#### System information: 
- OS: Manjaro xfce
- DBeaver version: 6.0.4.201905162234

#### Connection specification:
- Database name and version: MySQL 5.5.55

#### Describe your question:
Having created a foreign key I wanted to change the onupdate from the default of NoAction to Cascade. I found that there was no way to edit the foreign key at all and had to delete and recreate it. Is this standard behaviour? Apologies - I'm just digging into the deeper areas of MySQL so if the question is daft let me know!

**Comment by serge-rider** [comment]
As far as I know foreign key edit is not supported by MySQL. So yes, you need to drop and re-create FK.

**Comment by stormriderstudios** [comment]
Thanks!
