### ISSUE TITLE
MySQL 8 '00:00:00' TIME is shown as NULL 

### ISSUE THREAD

**Issue by slawo-ch** [dbeaver/dbeaver#6385]
#### System information: 
- Operating system (distribution) and version 
official mysql8 docker image: https://github.com/docker-library/mysql/blob/4af273a07854d7e4b68c5148b8e23b86aa8706e2/8.0/Dockerfile
- DBeaver version: 6.1.3
- Java version 
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
- Additional extensions
none

#### Connection specification:
- Database name and version
```
SHOW GLOBAL VARIABLES LIKE '%version%';

Variable_name          |Value                       |
-----------------------|----------------------------|
innodb_version         |8.0.17                      |
protocol_version       |10                          |
slave_type_conversions |                            |
tls_version            |TLSv1,TLSv1.1,TLSv1.2       |
version                |8.0.17                      |
version_comment        |MySQL Community Server - GPL|
version_compile_machine|x86_64                      |
version_compile_os     |Linux                       |
version_compile_zlib   |1.2.11                      |
```
- Driver name
Connector/J 8.0: mysql-connector-java-8.0.11.jar

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
```
SELECT CAST('00:00:00' as TIME) as t;

-> Shows t as NULL in the result grid. Should show '00:00:00' as it does for MySQL 5.x.
```
#### Steps to reproduce, if exist:
see above

**Comment by uslss** [comment]
issue isn't reproducible in 6.2.3
![image](https://user-images.githubusercontent.com/31996417/67412846-58920000-f5c0-11e9-8d09-a1a2d91a2eac.png)
