### ISSUE TITLE
DBeaver: Please add history/news for version 6.1.3

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#6386]
Seems the release of DBeaver Community version 6.1.3 never got any history/news information on the changes it include.

Please add one.
.

**Comment by serge-rider** [comment]
Sorry, we didn't publish release notes for 6.1.3 due to some unclear reasons. Now fixed.

BTW you always can get release notes from https://github.com/dbeaver/dbeaver/releases
