### ISSUE TITLE
Generate DDL: settings aren't working

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6387]
#### System information: 
- Operating system (distribution) and version win 10x64
- DBeaver version 6.1.4

#### Describe the problem you're observing:
"Use fully qualified names" and "Compact SQL" options has no effect on Generated DDL 
#### Steps to reproduce, if exist:
- Choose some table
- Generate SQL - DDL for the table
- Check-uncheck "Use fully qualified names" and "Compact SQL" options

Issue isn't reproducible for other generated SQL like SELECT, UPDATE, INSERT, etc
![ddl_options](https://user-images.githubusercontent.com/31996417/62203720-61de4880-b394-11e9-8fde-23642637f924.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
Verified.
"Use fully qualified names" works as expected
