### ISSUE TITLE
Generate Table DDL works incorrect in special cases

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6388]
#### System information: 
- Operating system (distribution) and version win 10x64
- DBeaver version 6.1.4

#### Connection specification:
- Database name and version MSSQL

#### Describe the problem you're observing:
Generated DDL for tables is duplicated for some tables. Possibly, the issue is reproducible only for tables that have got both FK and UK.
#### Steps to reproduce, if exist:
Issue is reproducible for an_example table from ticket #6218 
![image](https://user-images.githubusercontent.com/31996417/62205189-93a4de80-b397-11e9-89a3-8eca95eec6f8.png)

**Comment by serge-rider** [comment]
Fixed (some cache issue)

**Comment by uslss** [comment]
verified
