### ISSUE TITLE
Backticks in MariaDB/MySql

### ISSUE THREAD

**Issue by MeboGit** [dbeaver/dbeaver#6389]
Is there a way to disable backticks (MySql/MariaDB) in statements that look as follows:

```
create
 or REPLACE view `cwifi_stat`.`v_test` as
select `z`.`calledstationid` as `calledstationid`
from (
 select `cwifi_stat`.`station_datum`.`calledstationid` as `calledstationid`
 from `cwifi_stat`.`station_datum` limit 1
 ) `z`
```

Thanks in advance....

**Comment by serge-rider** [comment]
No, unfortunately. This query (view definition) is generated by MySQL/Maria server and there are no options which disables this behavior.

**Comment by MeboGit** [comment]
Ok, thanks for the quick response.
