### ISSUE TITLE
Support metadata specification in a SQL comment on the first few lines of the sql script

### ISSUE THREAD

**Issue by majkinetor** [dbeaver/dbeaver#639]
### Description

Dbeaver should parse first few lines of opened SQL scripts to get the metadata about connection properties and possibly other metadata. 

Dbeaver should also had an option to create/update this metadata automatically based on the active connection for the current SQL editor.
### Benefit

SQL files work in specific environment and during development and debug phases its often required to send SQL scripts to other systems and other team members that may or may not use Dbeaver. Some of the benefits include:
- Migration to/from other tools that support this.
- Quick setup for new team members and database administrators, who often require minimum configuration in order to get involved as fast as possible. 
- Examples on the net and documentations often work with predefined schemes: MS SQL NorthWind, Oracle HR schema etc. As it is learning experience it is better not to think about boilerplate and just jump strait into action which this system would allow.
### Details
- Connection could be specified in full or perhaps a dbeaver connection by name could be referenced.
- There should be an option to enable disable metadata interpretation.
- There should be an option to specifically handle passwords (i.e. they could be left empty and dbeaver could pop up to ask for it first time this script gets executed/loaded).
- Connections created this way could be added to _ad hoc_ connections or among General connections.
- There could be an option for location (perhaps someone would like this info at the end of the file so focus on the problem is not lost)
#### More metadata

Connection spec is essential, but this would also be very practical:
- There could be an option for single line or multiline metadata spec. This could be useful if other metadata apart from connection are considered (see [vim modeline magic](http://vim.wikia.com/wiki/Modeline_magic) as an example). For example recently added Sql editor auto connect could be specified here: `-- dbeaver: ac: exec` (specifies AutoConnect on EXECution). Considering other metadata would greatly improve overall dbeaver experience because important settings would become dynamic and project dependent. Potential candidates could include: 
  - connection specification
  - connection reuse
  - save on execution
  - auto activation
  - auto format
  - sql timeout
  - commit type
#### Only connection

SQL Server:

```
-- dbeaver: con: "Data Source=localhost;Initial Catalog=Nortwind;Integrated Security=SSPI;"

SELECT FirstName, LastName
FROM Employees;
```

Oracle, asks for password

```
-- dbeaver: con: "test/***@ora.company.com:1521/xe as sysdba"
```

Metadata example, uses named connection previously created in dbeaver.

```
-- dbeaver: con: 'mysql - localhost' | ac: activation | cr: true | soe: false | af: false 
```

Same as previous, multiline

```
/* dbeaver:
connection:        mysql - localhost
auto connect:      activation
connection reuse:  true
save on execution: false
auto format:       false

*/
```

**Comment by majkinetor** [comment]
Even with only Dbeaver connection name this quickly becomes very practical (i.e. scope of usuablity is only within DBeaver). 

In the case with Oracle for example, I alway have 3 different connections:

- 1 to connect to the root database, so called CDB
- 1 to connect to the application database as admin
- 1 to connect to the application database as user

All those connections are related to the single project.
I have many scripts saved and all of them require specific connection.

Currently I keep the DBeaver connection name (F2 copy/paste) as a first line. It looks like this

**Application schema as admin sys**
```
-- Oracle - Test - pdbtest/sys

SELECT Name, Value
FROM V$DIAG_INFO
WHERE Name = 'Diag Trace'
```


**CDB schema as admin sys**
```
-- Oracle - Test - mof/sys

SELECT name, pdb
FROM   v$services
ORDER BY name;
```

**Application schema as user mof**
```
-- Oracle - Test - pdbtest/mof

update BANKS set DATE=null;
```

**Comment by majkinetor** [comment]
Ignore last comment, Dbeaver remembers this internally, I just didn't notice. It selects correct connection.

**Comment by uslss** [comment]
already implemented
![image](https://user-images.githubusercontent.com/31996417/133054796-9e5c2cb7-e317-4d72-b8ce-3e4e99f24e8a.png)
