### ISSUE TITLE
Cannot import Legacy XML connections file

### ISSUE THREAD

**Issue by ruimbribeiro** [dbeaver/dbeaver#6390]
Hi,

#### System information: 
- Ubuntu 19.04
- DBeaver 6.1.3

From a previous install I saved the connections configuration in a file stored at `{$HOME}/.dbeaver4/General` named `.dbeaver-data-sources.xml`

With this new version it's not possible to import this XML. Furthermore, it seems that the connections are now stored in a `.json` file instead at `{$HOME}/local/share/.DBeaverData/workspace6/General/.dbeaver` named `data-sources.json`

At class `plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/app/DBPDataSourceRegistry.java` there are two types of config files `MODERN` and `LEGACY`; i'm not sure how we can trigger/load legacy configuration files.

**Comment by serge-rider** [comment]
You can delete new configuration (delete folder `.dbeaver` in project directory).
In that case DBeaver will try to open old configuration (`.dbeaver-data-sources.xml`) and convert it into the new format.
