### ISSUE TITLE
Cannot run .sql file on mysql

### ISSUE THREAD

**Issue by mcunha98** [dbeaver/dbeaver#6391]
#### System information: 
- Operating system (distribution) and version : Win10
- DBeaver version 6.1.2
- Java version java version "1.8.0_221" Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

#### Connection specification:
- Database name and version mysql 8 - MariaDB JDBC driver
- Driver name org.mariadb.jdbc.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

I wrote a .sql file that create a store procedure on server and run it.
If I run this file under heidisql everything works fine, but under DBeaver I cannot run...

```
DELIMITER $$
use placetransfer;

DROP PROCEDURE migrar_db$$
CREATE PROCEDURE migrar_db() 
	BEGIN
		/* Configuracao das variaveis para uso em todo o script !!!! */
		declare v_id_loja int default 7;

		create table migrar_log (ID int NOT NULL AUTO_INCREMENT, hora DATETIME NULL, texto VARCHAR(10000) NULL, PRIMARY KEY (ID));
		insert into migrar_log(hora,texto) values (now(),concat('Script iniciado'));
		insert into migrar_log(hora,texto) values (now(),concat('ID da loja : ', v_id_loja));

		show tables like 'tbl_vitrine';
		select found_rows() into v_num_rows;
		if (v_num_rows > 0) then
			insert into migrar_log(hora,texto) values (now(),'Importando tabela de vitrine');
			delete from tbl_vitrine where id_loja <> v_id_loja; 
			insert into place.tbl_vitrine select * from tbl_vitrine;
		end if;

		insert into migrar_log(hora,texto) values (now(),'Script concluido');
	END $$
DELIMITER ;

call migrar_db();
select * from migrar_log;
```

This is a small piece of code, if I run, everything ok but on DBeaver:
**SQL Error [1064] [42000]: (conn:166279) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DROP PROCEDURE migrar_db' at line 3
Query is : use placetransfer;**

**Comment by serge-rider** [comment]
You have a wrong delimiter after `use placetransfer;` - you must use $$ as delimiter as you redefined it one line earlier..

**Comment by mcunha98** [comment]
@serge-rider I understood, but why I can run this on heidisql without errors ?
Considering that run on server, doesn't make sense because the error will be fired on both (heidi/dbeaver)
