### ISSUE TITLE
ER diagram shows tables but no relationships

### ISSUE THREAD

**Issue by ifuchs** [dbeaver/dbeaver#6394]
I open an SQLite file with the Community Edition and ER Diagram shows tables but no relationships. What am I missing?

**Comment by marcosdipaolo** [comment]
+1

**Comment by serge-rider** [comment]
Are there any foreign keys in your schema?
Here is ERD for SQLite sample database: 
![image](https://user-images.githubusercontent.com/6398845/62544355-e7b03700-b85f-11e9-90b2-dfaf3933cf16.png)

**Comment by ifuchs** [comment]
I have tried with several sqlite db and I have not seen the relationships on the ER diagram. Here is one example db. Perhaps there are no relationships to show?

**Comment by serge-rider** [comment]
Perhaps. Just open a table editor, switch to Foreign Keys tab to see relations.

**Comment by devmi** [comment]
If your tables don't have FK (Foreign Keys) between them, you can add [virtual FK](https://dbeaver.com/docs/dbeaver/ER-Diagrams/#structure-adjustment) (for exploration purposes):
> (Available for [Custom Diagrams](https://dbeaver.com/docs/dbeaver/ER-Diagrams/Custom-Diagrams) only) - connect tables with a connector: click the Show Palette button (▶️ ) in the upper-left corner of the diagram tab and then, in the Palette panel, click Connection:
> ![image](https://github.com/dbeaver/dbeaver/assets/19313261/55ac590a-5640-4207-be0e-259d07a03c8b)
>
> Now click the tables that you want to connect with each other in turn, one by one. To stop the connection line, double-click the last table
