### ISSUE TITLE
Pre-install jar of jdbc driver in DBeaver

### ISSUE THREAD

**Issue by lt101018** [dbeaver/dbeaver#6395]
Does anyone know how can I pre-install an existing jdbc jar files in DBeaver? I tried revising file path in plugin.xml to a local directory instread of maven address. It works fine in Eclipse debug mode but it cannot find driver after I export it as a product.

**Comment by uslss** [comment]
Hi @lt101018 ,
you could do this according to this guide https://github.com/dbeaver/dbeaver/wiki/Admin-Manage-Drivers
sorry for so late response
