### ISSUE TITLE
Disable Inline Editing on result set

### ISSUE THREAD

**Issue by LukasBreit** [dbeaver/dbeaver#6397]
#### System information: 
- IBM I series 7.2
- DBeaver version 5.2.4

#### Connection specification:
- DB2

#### Describe your question:
Is it possible to disable inline editing of a result set? Setting the preferences of Double-click behaviour to "None" disables not all the possibilities to edit the result set. If a cell is focused and you start entering some text, you can still change the value. The same is possible by right click on a cell --> Edit --> Inline Edit. 
All these options need to be disabled, so that the user can update a table only by using a sql statement, not the result set of a Select statement. 

Thanks for help!

**Comment by serge-rider** [comment]
There is no such feature (yet?).
You can make connection read-only but this will prevent any kind of data edit (including execution of UPDATE statements).

Could you say why do you need such non-standard feature? 
Maybe we need a feature request for it..

**Comment by LukasBreit** [comment]
We had some problems with the inline-edit. 
We have tables without a primary key, so all columns are used by DBeaver for an update on these tables. When someonde did an update via inline-edit, some records have been changed, which shouldn't be changed. 
Our assumption is, that the table structure has been changed outside from DBeaver, but DBeaver remembered the old table structure and used this for the update.

Because such errors can create a lot of work for us, we want to disable the feature.

**Comment by serge-rider** [comment]
This makes sense

**Comment by serge-rider** [comment]
We'll make it even better:

![image](https://user-images.githubusercontent.com/6398845/62790411-5d6c0b00-bacb-11e9-8b83-26ea66bdbb89.png)

**Comment by kseniiaguzeeva** [comment]
Verified.

**Comment by corbin-bohne** [comment]
Does the setting in @serge-rider screenshot prevent all edits to database structure or just those made inline in the results grid window?

**Comment by serge-rider** [comment]
Depending on settings. 
Data edit restricts any direct data edit (inline or in value editor panel). But allows to execute SQL queries like UPDATE/DELETE.
