### ISSUE TITLE
DBeaver: Database Navigator tree does only flag first trigger of many that is disabled/enabled

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#6400]
DBeaver - **Version 6.1.3 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

If I in the **Database Navigator** choose to disable/enable more than one table trigger, only the 1st table trigger is flagged as changed state.

I think a small loop is missing when it comes to update the table trigger state in the **Database Navigator**.

**Comment by serge-rider** [comment]
Thank for the bug report

**Comment by uslss** [comment]
verified
