### ISSUE TITLE
DBeaver: Database Navigator context menu choice Tools -> Disable trigger ought to be named Disable trigger(s)

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#6401]
DBeaver - **Version 6.1.3 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

The **Database Navigator** tree context menu choice **Tools -> Disable trigger** ought to be slightly renamed as **Disable trigger(s)**. This since I can Disable/Enable more than one trigger.

**PS**. The disable trigger dialog **Disable trigger** and he **Disable trigger progress** dialog ought to be changed too.

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/62544679-f0593b00-b868-11e9-980e-632b511c5f4a.png)
