### ISSUE TITLE
DBeaver: Redraw/Repaint of the Database Navigator tree is slighly damaged

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#6402]
DBeaver - **Version 6.1.3 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Redraw/Repaint of the Database Navigator tree is slighly damaged.

**o** Open a connction/sesion to a **SQL Server** database **with table triggers**.
**o** Expand the schema with Table Triggers displayed.
**o** Mark more than one table trigger.
**o** Right click on one of the table triggers and choose Tools -> Disable trigger.
**o** Press the **OK** button in the **Disable trigger** dialog.
**o** Press the **CLOSE** button in the **Disable trigger progress** dialog.
**o** Left click with the mouse on any of the disabled triggers.
**o** The **Database Navigator** tree disappear except the table triggers that was disabled.
**o** Press the **UP**/**DOWN** key on the keyboard to paint/draw the missing tree nodes.

**Note 1**: The above description does not 100% indicate the problem. You have to try a coule of times.

**Note 2**: I use the Dark theme in DBeaver and are unsure of this is what causing the trouble.

**Comment by serge-rider** [comment]
Please test it in 6.1.4 (there were a few fixes related to trigger management)

**Comment by pdanie** [comment]
I have tried it now in version **6.1.4 CE** and I can't make it break like in **6.1.3 CE**. Maybe it was solved with the other fixes related to trigger management.

**Comment by serge-rider** [comment]
Mark as not reproducible anymore.
