### ISSUE TITLE
Dbeaver: Menu choice SESSION MANAGER has been removed for SQL Server

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#6404]
DBeaver - **Version 6.1.3 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Somewhere after version **6.0.0 CE** of **DBeaver** the context menu choice of **Tools** -> **Session Manager** for a **SQL Server** database has been removed.

I can't understand why it has been removed in that:
**o** It worked great in version **6.0.0 CE**.
**o** It is still there for **MariaDB** and **PostgreSQL** databases (and probably more than those two).

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/62368782-4dd24c80-b536-11e9-9b2a-a77334a2c854.png)
