### ISSUE TITLE
Export db always try to lock tables

### ISSUE THREAD

**Issue by itsafety** [dbeaver/dbeaver#6405]
#### System information: 
- Windows 10
- DBeaver version 6.1.3.201907211943

#### Connection specification:
- Maria DB

#### Describe the problem you're observing:
Dumping database with Execution method setting to Normal (no locks) returns error code 2 with comments Access denied form user .... to database ... when using LOCK TABLES

![dbeaver-error](https://user-images.githubusercontent.com/53222913/62303732-f02df980-b47c-11e9-9c09-3b32af69decc.png)

#### Include any warning/errors/backtraces from the logs
C:\Users\marci\AppData\Roaming\DBeaverData\drivers\clients\mysql\win\mysqldump.exe --routines --add-drop-table --disable-keys --extended-insert -v --host=192.168.150.75 --port=3306 -u itm_client itm
Export started at Thu Aug 01 16:50:35 CEST 2019
-- Connecting to 192.168.150.75...
mysqldump: Got error: 1044: Access denied for user 'itm_client'@'%' to database 'itm' when using LOCK TABLES
Export finished at Thu Aug 01 16:50:35 CEST 2019
Process exit code: 2

**Comment by uslss** [comment]
Hi @itsafety ,
cannot reproduce an issue against 7.0
is it still actual for you?

**Comment by testica** [comment]
@itsafety for you dbeaver version try to put in "extra command args" input: `--single-transaction` to prevent table locking

**Comment by testica** [comment]
@uslss installing dbeaver 7.0 the issue persists.
For some reason whatever option selected in execution method is locking.

**Comment by serge-rider** [comment]
Probably we should add extra option to dump wizard.

**Comment by LonwoLonwo** [comment]
Fixed here: https://github.com/dbeaver/dbeaver/issues/16100

You can choose the execution method before dump:

![2023-09-21 12_49_14-Export](https://github.com/dbeaver/dbeaver/assets/45152336/fe76de14-0a50-40ad-bc47-f1d41294c358)

Available in the last DBeaver.
