### ISSUE TITLE
Color Preferences Not Found/Adjustable

### ISSUE THREAD

**Issue by YoshioHasegawa** [dbeaver/dbeaver#6406]
When adjusting my color preferences in Dbeaver, I am not able to figure out how to adjust the following fields...

1. Highlighted hover-labels within folders.
2. Content assist descriptions.
3. Executing query second counter.

The solution I am looking for is to implement the ability to change the colors for these fields or, to assist me with figuring out how to adjust them if they already exist.

Assisting images:
1. Highlighted hover-labels within folders.
![image](https://user-images.githubusercontent.com/36059599/62313645-2439f800-b446-11e9-8a90-307012414cb9.png)

2. Content assist descriptions.
![image](https://user-images.githubusercontent.com/36059599/62313625-17b59f80-b446-11e9-91b9-a512b0ea2d51.png)

3. Executing query second counter.
![image](https://user-images.githubusercontent.com/36059599/62313594-0371a280-b446-11e9-8e66-47db5074d479.png)

**Comment by uslss** [comment]
already fixed
