### ISSUE TITLE
Unable to associate with data source in 1.6.3

### ISSUE THREAD

**Issue by PeteBauer** [dbeaver/dbeaver#6409]
Hi,
Since the upgrade to 1.6.3 I'm unable to associate a scritp with a datasource.
I can select a datasource, but I isn't remembered.

I tried to remove the .metadata folder, but that didn't help.

**Comment by serge-rider** [comment]
Can't reproduce this.
- Do you have active project (you can see this in "Projects" view)?
- Is there anything in error/debug log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

You could also try Early Access version (https://dbeaver.io/files/ea). There were a few fixes related to new project metadata structure and script management.

**Comment by PeteBauer** [comment]
I figured out that I used the Data Source in the wrong project. I associated the right Data Source and now it's working again.

Thanks anyway!
