### ISSUE TITLE
Logical foreign keys (integrate with ERD): sync on Connection delete need to be added

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6411]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.1.4

#### Describe the problem you're observing:
Now we've got no check if Virtual FK was deleted on ERD/Grid.
So if we delete connection on ERD, it stays in Logical structure

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
