### ISSUE TITLE
Dbeaver : Catalog Filter enabled checkbox not getting saved

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#6414]
DBeaver - Version 6.1.3 CE
Operating System: Windows 10
JDBC Driver: mssql-jdbc 7.0.0.jre11
Database: Microsoft SQL Server Database

The catalog filter for database schema is not getting saved. Everytime i open dbeaver i have to check enabled checkbox. Screenshot below. @serge-rider 

![image](https://user-images.githubusercontent.com/38669892/62374805-5c9f0c00-b502-11e9-8c87-6b51ee28c768.png)

**Comment by serge-rider** [comment]
Thanks for the bug report (this is a bug in 6.1.3 version, side-effect of new connections configuration format).

**Comment by uslss** [comment]
verified
