### ISSUE TITLE
Data Format not working

### ISSUE THREAD

**Issue by marcos-romero-cerc** [dbeaver/dbeaver#6416]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04
- DBeaver version: 6.1.3.201907211943
- Java version : openjdk 11.0.4 2019-07-16
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 10.9 (Ubuntu 10.9-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit
- Driver name: postgresql 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Data format is not being respected when querying for numbers. Data source does not have custom data formatting and global configuration is default, with 10 decimal digits

#### Steps to reproduce, if exist:

Run 'select 0.0009;' Output on result set should be 0.0009, but is 0.001

**Comment by cerebel** [comment]
I made some simulation

Oracle, [Number ](https://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#CNCPT1832) > Numbers of virtually any magnitude can be stored and are guaranteed portable among different systems operating Oracle Database, **up to 38 digits** of precision.

so, with   '9' x50 after dot 
the sql :  select   0.1234567890123456789012345678911234567892123456789 as zz from dual;

1. run in  sqlplus 
 > column zz format  9.99999999999999999999999999999999999999999999999999
 > select   0.1234567890123456789012345678911234567892123456789 as zz from dual;
 > return:  .12345678901234567890123456789112345678920000000000
 
 return 50 digits after dot. 
 
2. run in dbeaver
w7x64 / DBeaver ce 6.1.2 /  jdk1.8.0_212_x64 /  Oracle JDBC driver [12.1.0.2.0] , Oracle 12

> select   0.1234567890123456789012345678911234567892123456789 as zz from dual;

 database.editor.dataEditor.dataFormats.format[number - roundingMode->Half_Even   (as default)]
> displayed value: 0.123

but on copy value from cell, and paste it 
> 0.1234567890123456789012345678911234567892

  database.editor.dataEditor.dataFormats.format[number - roundingMode->Unnecessary]
> displayed value: 0.1234567890123456789012345678911234567892

**Comment by marcos-romero-cerc** [comment]
@cerebel I tried and it had the same result with "select 0.00009;" on my same configuration.


Just some additional comment on this: it was working fine on 6.1.0. I tested it before updating to check if it was a version issue. I did not changed any configuration on Data Formats.

**Comment by cristoforo** [comment]
Same with me, was working before latest updates but now I get too aggressive rounding (only when displaying - "value" remains correct).

Setting Rounding Mode as UNNECESSARY solved for me

![image](https://user-images.githubusercontent.com/5610315/62485693-b3843a00-b7bd-11e9-92fa-4f68c56b203e.png)
