### ISSUE TITLE
MySQL connection over SSH caches data

### ISSUE THREAD

**Issue by mathus13** [dbeaver/dbeaver#6418]
#### System information: 
- Windows 10 build 18362.207
- DBeaver version 6.1.3.201907211943
- Java version 8.21

#### Connection specification:
- Database name and version 
- Driver name **com.mysql.jdbc.JDBC4CommentClientInfoProvider**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **SSH**

#### Describe the problem you're observing:
Update statements appear to be successful, but after invalidate/reconnect the original values appear. Confirmed the update did not take. If values are updated outside of dbeaver, refreshing the table does not show updates until the connection is invalidated.

**Comment by serge-rider** [comment]
If you are working in manual transaction mode then you probably need to commit/rollback your changes. Or switch to auto-commit mode.

**Comment by mathus13** [comment]
Correct assumptions. This fixed my issue
