### ISSUE TITLE
Hive: View issues

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6422]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.1.4
#### Connection specification:
- Database name and version Hive

#### Describe the problem you're observing:
View issues:
1. On view creation ";" is automatically added at the end of the script, so if user's statement got ";", script couldn't be saved.
![image](https://user-images.githubusercontent.com/31996417/62414602-5bff9600-b626-11e9-90c6-2faf44c883da.png)
![image](https://user-images.githubusercontent.com/31996417/62414606-6f126600-b626-11e9-9080-7ca2f58e1e47.png)
2. View couldn't be changed. Possibly it is connected with incorrect statement. Create instead of Create and Replace. 
![image](https://user-images.githubusercontent.com/31996417/62414622-ab45c680-b626-11e9-9554-b58848972c9d.png)
Also Replace isn't highlighted as a special word.
![image](https://user-images.githubusercontent.com/31996417/62414646-daf4ce80-b626-11e9-9333-930c39b53083.png)

**Comment by serge-rider** [comment]
Problem with semicolon fixed.
Problem with view alter is more general (it is the same for all generic drivers incuding Hive).
We need separate ticket for it.

**Comment by uslss** [comment]
closed.
Created issue #6430
