### ISSUE TITLE
References table: possibility to choose several column filter criterias at the same time

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#6427]
**Is your feature request related to a problem? Please describe.**
It would be great if several filter criterias could be selected in column filter of references table.

**Describe the solution you'd like**
1. open a references table with several rows
2. click a column filter of the references table > select several filter values > press Enter (also "ok"btn can be added in the window of column filter).

Expected result: All selected values are shown in the references table

<img width="960" alt="references filter criteria" src="https://user-images.githubusercontent.com/51405061/62418959-89782e00-b67e-11e9-8968-097181d9f5e4.png">

**Comment by serge-rider** [comment]
Done

**Comment by kseniiaguzeeva** [comment]
Thank you! Verified.
