### ISSUE TITLE
Hive. Complex type values couldn't be edited.

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6431]
#### System information: 
- Operating system (distribution) and version win 10x64
- DBeaver version 6.1.4

#### Connection specification:
- Database name and version Hive

#### Steps to reproduce, if exist:
1. Create table
```use default;
create table test (
	ok1 STRING,
	bar STRUCT<type:STRING>,
	baz ARRAY<STRING>,
	ok2 BIGINT
);
```

2. Try to add value from ui to bar column - error appears (log attached)
3. Try to add value to baz column - elements could be added, but couldn't be saved, because it isn't supported

[array.txt](https://github.com/dbeaver/dbeaver/files/3465142/array.txt)
[struct.txt](https://github.com/dbeaver/dbeaver/files/3465143/struct.txt)

**Comment by serge-rider** [comment]
Hive driver doesn't support this feature. So we can't support this feature, at least using Generic Hive driver.
