### ISSUE TITLE
Clone SQL editor shortcut

### ISSUE THREAD

**Issue by yjd** [dbeaver/dbeaver#6433]
Suggestion The cloning function can set a shortcut or add it to the label right-click menu.
Thanks!

![2019-08-05_111645](https://user-images.githubusercontent.com/6856740/62436994-00432300-b774-11e9-876f-441681b71f9f.png)
![2019-08-05_112116](https://user-images.githubusercontent.com/6856740/62437002-0507d700-b774-11e9-8d26-4b7b8e555a7b.png)

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/62460672-ebba5700-b782-11e9-9b02-3864cd04292a.png)

**Comment by yjd** [comment]
Thank you!

**Comment by serge-rider** [comment]
Chinese localization of this command is provided by Eclipse team (Babel project)
