### ISSUE TITLE
DBeaver: Use of Toggle Result Panels (key F7) is broken if focus is set on a data grid

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#6434]
DBeaver - **Version 6.1.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Use of **Toggle Result Panels** (key **F7**), and **Toggel Panels Layout** is broken. If focus is not set on a data grid cell nothing happens.

Before I could press the key **F7** without having to click on a data grid cell. Now I have to.

**o** Connect to a database of choice.
**o** Show data from a table (ie. choose to show the **Data** tab).
**o** Press key **F7** to show the Result Panels.
**o** The **Result Panels** are shown.
**o** Press key **F7** again to hide the Result Panels.
**o** **Noting happens!**
**o** Click on a column value of choice in the table data grid.
**o** Press key **F7** again to hide the Result Panels.
**o** The **Result Panels** are hidden.

**NOTE**: I get the same effect if I instead of using the **F7** key choose the **Configure** -> **Layout** -> **Toggle Result Panels** or **Toggle Panels Layout**.

**Comment by serge-rider** [comment]
Can't reproduce. Please check error/debug logs and attach them if there is anything related there.

**Comment by pdanie** [comment]
I have now tried it with a clean configuration (the one I noticed the fault had the configuration converted from the old **6.1.0 CE** format). It seems to work. I can press **F7** multiple times and it binds to the right function.

Maybe it will be ok now when I start with a clean configuration slate.

**Comment by serge-rider** [comment]
Ok, thanks for testing
