### ISSUE TITLE
DBeaver: Data grid contextmenu choice Navigate has been lost

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#6435]
DBeaver - **Version 6.1.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Somewhere after version **6.0.0. CE**, the context menu choice **Navigate** is missing.

**o** Connect to a database of choice.
**o** Show table (with foreign keys) data in a grid.
**o** Right click on a table row.
**o** **There is no context menu choice for Navigate**.

For version 6.0.0 CE there was a context menu with **Navigate**.

**PS**. The context menu **Layout** seems to be missing too.

**DBeaver version 6.0.0 CE**:

![2019-08-05 09-53-28](https://user-images.githubusercontent.com/31191374/62448227-97ee4480-b767-11e9-9ec0-e2ccf7e6d07d.png)

**DBeaver version 6.1.4 CE**:

![2019-08-05 09-53-40](https://user-images.githubusercontent.com/31191374/62448246-a0df1600-b767-11e9-849c-694fd465f479.png)

**Comment by serge-rider** [comment]
Since 6.1.4 we redesigned data viewer context menu. Navigate and Layout have been moved to Configure dropdown in the bottom toolbar. Most of items in Edit sub-menu have been moved to Edit main menu.
Also navigate sub-menu actions will be moved to the Navigate main menu in 6.1.5.

**Comment by pdanie** [comment]
Hmmmmmm.

I can't see what **Navigate** around the database has to do with something named **Configure**. I can not even see what **Layout** stuff have to do with something namd **Configured**.

Are you sure the move of those two context menu items was a good one ? I can for sure say hat no one of my collegues at work will find the **Configure** button and its contents. The old placement in the context menu most of them found after some prodding.

**Comment by serge-rider** [comment]
This is controversial. But these sub-menus definitely shouldn't be in the context menu, it is already too heavy. 

Navigate commands will be moved in the main menu and will be removed from Configure dropdown. Also most useful navigate actions are in the bottom toolbar of data viewer. And they have shortcuts.

Layout is actually a data viewer look-and-feel configuration. So I think we'll leave it in Configure. Layout commands are rarely used and all of them have corresponding tool buttons and shortcuts. Basically the menu is redundant and presented only as a reference of all possible layout configurations.

**Comment by serge-rider** [comment]
Also check #6379 (it is the main ticket about data viewer UIX changes)

**Comment by pdanie** [comment]
Good enough for me. Adding the menu choices to the main menu works and maybe are a good compromise.

Thanks.

**Comment by serge-rider** [comment]
We'll return Navigate menu in 6.2.1 (at least partially). There are some commands that we can't add in other places..

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by Taariqq** [comment]
I am missing the 'Right-Click' 'context menu' on the left panel when I expand the databases. After creating a new database I want to refresh the menu so the new database shows up but I don't have any way of doing it.
Is this related or should I open a new issue?
