### ISSUE TITLE
DBeaver: Filter set by using Navigate References are cleared when updating table data

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#6436]
DBeaver - **Version 6.1.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

If I choose to **Navigate Reference** from one table to another, a filter expression is created by _DBeaver_. But when I request that the new table data is refreshed by pressing the **F5** key, that filter is cleared. 

For _DBeaver_ version **6.0.0 CE** that was not the case.

**o** Connect to a database of choice (that have foreign keys).
**o** Show table data grid for a table of choice (a table that has foreign keys).
**o** Press key **CTRL+1** to **Navigate References** and chooce a table in the list.
**o** The choosen table are shown with a filter specified to sort out only those rows that are of interest.
**o** Press key **F5** to refresh the displayed data.
**o** **The previous set filter is lost**.

This might be what I noticed in in issue #6403.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by kseniiaguzeeva** [comment]
Verified.
