### ISSUE TITLE
Add SQL function(HIVE)

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6439]
Currently, for the HIVE SQL function or fewer commands, we hope to increase the HIVE SQL statement prompt and highlight,thank you

**Comment by serge-rider** [comment]
DBeaver highlights keywords and functions reported by Hive driver. We can customize this list.

What exactly functions do you mean?

**Comment by Pengchenghua** [comment]
> DBeaver强调Hive驱动程序报告的关键字和功能。我们可以自定义此列表。
> 
> 究竟是什么功能？
For example, adding SQL function to automatically supplement such functions as regexp_replace()\to_date\substr(), etc., all without correct prompt, statement optimization, formatting problems, such as line breaking is done by ",", rather than by function or SQL parameters

**Comment by LonwoLonwo** [comment]
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL

**Comment by LonwoLonwo** [comment]
regexp_replace()\to_date()\substr()  and more

**Comment by uslss** [comment]
verified
