### ISSUE TITLE
DBeaver: Change of font color with Dark Theme to improve readability

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#6441]
DBeaver - **Version 6.1.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

There are still a few places where an increase in readability would benifit the **Dark** theme. 

It's mostly fields with _light gray_ background and _white_ font color, or _dark gray_ background with _black_ font color.

One idea might be to use the **dark gray** background with **whiteish** font color, and use the **light gray** background with **blackish/dark greyish** font color instead.

**A few examples included below**

![2019-08-05 15-39-37](https://user-images.githubusercontent.com/31191374/62469618-ea942480-b798-11e9-8bbb-7ca6ffd29dfa.png)

![2019-08-05 15-42-46](https://user-images.githubusercontent.com/31191374/62469630-f41d8c80-b798-11e9-8e05-af31233b7112.png)

![2019-08-05 15-44-06](https://user-images.githubusercontent.com/31191374/62469640-fb449a80-b798-11e9-9d2f-4a6c4e80fae0.png)

![2019-08-05 16-07-14](https://user-images.githubusercontent.com/31191374/62470820-8b83df00-b79b-11e9-96ae-83d28da3a1b6.png)

![2019-08-05 17-47-17](https://user-images.githubusercontent.com/31191374/62477589-96de0700-b7a9-11e9-8963-b85358b6a769.png)

![2019-08-05 17-57-39](https://user-images.githubusercontent.com/31191374/62478299-04d6fe00-b7ab-11e9-8951-6a12c4445d94.png)

**Also changed line numbers in the SQL Editor is really hard to read**

![2019-08-05 16-24-03](https://user-images.githubusercontent.com/31191374/62471865-d999e200-b79d-11e9-8677-d758b9ee3f90.png)

**Comment by rpalloni** [comment]
Same here #6302

**Comment by blueglyph** [comment]
Also, all the selection widget don't keep a consistent color, they change once the user toggles an option or moves the mouse cursor over them. It's almost impossible to know whether an option is checked or not (for example in the user privileges).

**Comment by ssilva** [comment]
As a workaround, I'm using the plugin [Darkest Dark Theme](https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle).

**Comment by serge-rider** [comment]
Most mentioned issues were resolved in versions 7.2-7.3

Please reopen is some of them are still reproducible
