### ISSUE TITLE
DBeaver: SQL Editor SQL Assistant not working for DROP PROCEDURE/FUNCTION command

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#6442]
DBeaver - **Version 6.1.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

There is no intellisense (ie **SQL Assistans**) when writing **DROP PROCEDURE** or **DROP FUNCTION** in the **SQL Editor**. Not anything automatic while typing, nor when requesting manual lookup (using **CTRL+BLANK** key).

This works (only manual lookup) for **PostgreSQL** but not for the **new Microsoft SQL Server Driver**.

**Comment by serge-rider** [comment]
Done

**Comment by uslss** [comment]
verified
