### ISSUE TITLE
Keep multiple results tabs open if 'Execute' is clicked after 'Execute in separate results tab'..?

### ISSUE THREAD

**Issue by spinjector** [dbeaver/dbeaver#6447]
If I click the button 'Execute script statements in separate results tab', it does what it says and gives me a new results tab. But if I already have multiple results tabs open, and I inadvertently click the normal 'Execute' button......*it closes ALL currently open results tabs without any notification*.  This can be very frustrating.

Are there any settings to control this behavior..? I would like to be warned before multiple results tabs are closed. I searched the documentation and the DB Preferences window, but I could find no settings to change this behavior.

A possible enhancement to make this feature more intuitive would be to change the function of the *normal* 'Execute' button so any results of the *current execution* are placed in the *current results tab*. And then the user may decide which results tabs to close...but manually.

**Comment by serge-rider** [comment]
Actually this is a bit more complicated. If your script produces many resultsets (tabs) then multiple script execution will generate tons of them. That's why we close old tabs before execute.
You can pin any number of currently opened tabs to prevent their close.

I could add yet another config option which will control this behavior but I'm not sure that this is a good solution (as we already have too many options and it is really hard to find where they are).

**Comment by spinjector** [comment]
Oh, I wasn't aware a script could open multiple tabs on it's own; I thought it could only occur by the user pressing the button. I only use DB for SQL on  DB2/400. Perhaps I'm using the feature in an unusual way? If I'm developing a complex query, I'll tweak it slightly, and then open results in new tabs as I go. Then I can compare the results of different runs in different tabs to be certain I'm getting the results I'm looking for.

I think simply adding a warning/prompt to the user that multiple tabs are to be closed would be enough. Perhaps even adding another that warns the script is about to open multiple tabs - to prevent the tabs-explosions that you describe..?

As for DB being too complex with too many settings..? Perhaps. But then so is my lovely life-companion. She baffles me at times, but the rewards are fantastic. =-D

**Comment by serge-rider** [comment]
Agreed. I think we can add confirmation dialog with option "Do not ask again". This won't be too annoying and there is no need to search config option in preferences.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/62549989-c3595800-b869-11e9-96f4-d7350211bcef.png)

**Comment by spinjector** [comment]
That looks good to me. It would definitely reduce the "GRRR!" noises coming from my office. Even with this discussion fresh in my head today, I still accidentally closed some tabs, so I would definitely be grateful for the warning dialog. =-)

**Comment by p91paul** [comment]
> If your script produces many resultsets (tabs) then multiple script execution will generate tons of them
However, this only happens if you run as script. When running single statements (i.e. ctrl+enter), the original proposal (replace current tab, leave others opened) is perfectly sound. Having 2 different buttons gives you the opportunity to have 2 different behaviors.

**Comment by spinjector** [comment]
I understand. However, my concern is simply if one clicks the button 'Execute script into new tab', and then clicks the button 'Execute script', *all tabs are immediately closed without notification*. I began this thread to ask that a notification message be instantiated to protect tabs being accidentally closed. Then the user can choose which tabs to close manually.

**Comment by p91paul** [comment]
Yes my suggestion is that when you have many tabs opened, running a single statement replaces the current tab without asking, leaving other tabs opened.

Instead, if you execute a script, the confirmation popup makes perfect sense because (as serge pointed out) you risk opening too many tabs.

**Comment by kseniiaguzeeva** [comment]
Verified.

**Comment by cariware** [comment]
I definitely prefer to keep open my unpinned results tabs when executing on a single tab. By some accident, I think I once clicked "Don't ask again" and "yes", so now my unpinned tabs are getting closed when I CTRL+Enter to execute. I can't seem to find the relevant preference setting to change this behavior. Does one exist or should I reinstall DBeaver?

**Comment by kseniiaguzeeva** [comment]
Unfortunately you should reinstall DBeaver
