### ISSUE TITLE
Running Vacuum with context menu on older versions (PostgreSQL)

### ISSUE THREAD

**Issue by lrweck** [dbeaver/dbeaver#6448]
DBeaver uses a (relatively) new syntax of VACUUM on its context menu tool.

After version 9.x, you can use VACUUM options inside parentheses, and before that, all options must be sequentially written besides VACUUM. ANALYZE option must be the last one, mandatorily.

link to doc: [VACUUM](https://www.postgresql.org/docs/8.4/sql-vacuum.html)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by kseniiaguzeeva** [comment]
Verified.
