### ISSUE TITLE
auto generate `use my_currently_active_db` when create SQL Query 

### ISSUE THREAD

**Issue by erlangp** [dbeaver/dbeaver#6450]
auto generate `use my_currently_active_db` when create SQL Query

**Comment by serge-rider** [comment]
Please clarify. DBeaver execute `use XXX` whenever you switch active database (in main toolbar or in database navigator).
![image](https://user-images.githubusercontent.com/6398845/62538601-7ec2c200-b853-11e9-8a70-1a8288aa7404.png)

**Comment by erlangp** [comment]
thanks @serge-rider :+1:

**Comment by erlangp** [comment]
there are no option Set Active
https://imgur.com/a/zp8Nadq

**Comment by uslss** [comment]
issue isn't reproducible. If it is still actual for you - feel free to reopen the ticket
