### ISSUE TITLE
Update dialog information says to "Press More Info" but its changed to Update ...

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#6451]
Update dialog now says to press More Info in the dialog but the button is changed to Update ...

![image](https://user-images.githubusercontent.com/383031/62516503-8ec3ad00-b825-11e9-8bb3-a7a391b64886.png)

**Comment by serge-rider** [comment]
Oops, fixed.
It was a side effect of hotfix version release. Thank you for noticing this.

**Comment by nmat** [comment]
![image](https://user-images.githubusercontent.com/383031/66290779-6e28d980-e8e0-11e9-83a3-60752bcf882d.png)

Text seems to again indicate to click on "More Info" when upgrading. I think this is a dialog issue where the bolded text is hard coded.
