### ISSUE TITLE
PostgreSQL execution log row count empty after calling any function

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#6452]
#### System information: 
- Windows 7 Pro x64
- DBeaver 6.1.4
- Java version 1.8.0_211
- No additional extensions

#### Connection specification:
- PostgreSQL 9.5.16 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit
- Driver org.postgresql:postgresql:RELEASE[9.4.1212.jre7]

In "Execution log" row count doesn't displays after calling any function in SQL script

If i execute
```
SELECT md5('df');

DROP TABLE IF EXISTS tt1;
DROP TABLE IF EXISTS tt2;

CREATE TEMP TABLE tt1(id int, code text);
CREATE TEMP TABLE tt2(id int, code text);

INSERT INTO tt1(id,code)
VALUES(1,'1'),(2,'2'),(3,'3');

ANALYZE tt1;

INSERT INTO tt2(id,code)
SELECT *
FROM tt1;
```
Execution log looks like this (row count only at calling function md5, after it row count is empty):
![изображение](https://user-images.githubusercontent.com/22142845/62517426-0d254c80-b830-11e9-8acd-3b758b236279.png)

If i execute previous query like this
```
DROP TABLE IF EXISTS tt1;
DROP TABLE IF EXISTS tt2;

CREATE TEMP TABLE tt1(id int, code text);
CREATE TEMP TABLE tt2(id int, code text);

INSERT INTO tt1(id,code)
VALUES(1,'1'),(2,'2'),(3,'3');

ANALYZE tt1;

SELECT md5('df');

INSERT INTO tt2(id,code)
SELECT *
FROM tt1;
```
Execution log looks like this (empty row count at last query):
![изображение](https://user-images.githubusercontent.com/22142845/62517581-56759c00-b830-11e9-8f85-59a1203f6258.png)

**Comment by serge-rider** [comment]
Thanks for the bug report.
This issue happened in script mode only.

**Comment by kseniiaguzeeva** [comment]
Verified.
