### ISSUE TITLE
Link to download DBeaver 6.1.4 Windows 64 bit (installer + JRE) redirect to 404

### ISSUE THREAD

**Issue by Stoumfou** [dbeaver/dbeaver#6453]
This issue doesnt for DBeaver software but for https://dbeaver.io/download/

The link to download 6.1.4 Windows 64 bit (installer + JRE)  => "https://dbeaver.io/files/6.1.5/dbeaver-ce-6.1.5-x86_64-setup.exe" 
return a 404.

Have a good day

**Comment by serge-rider** [comment]
Thank you for the bug report. Fixed.
