### ISSUE TITLE
Empty Exasol schemes are not displayed

### ISSUE THREAD

**Issue by Neonchen** [dbeaver/dbeaver#6459]
We are using an Exasol database and got the case that two schemes are not displayed. Both have views but no normal tables. One example for this is the exa_statistics scheme, which contains diverse statistic data. We are able to view the contained data by using sql statements but the navigator is not showing anything so it is not an accessibility problem.
Is this a bug or just a configuration issue?

**Comment by Sargul** [comment]
Hi,

EXA_STATISTICS and SYS are not really schemes as they are internal and cannot be changed.

However they are shown per default in DBeaver
![image](https://user-images.githubusercontent.com/5595511/62675457-6c599d00-b9a7-11e9-8442-1b763fe7ca26.png)

![image](https://user-images.githubusercontent.com/5595511/62675470-74194180-b9a7-11e9-9f7e-3d14149309ce.png)

Screenshots are from 6.1.4.

Do you have filters active?
![image](https://user-images.githubusercontent.com/5595511/62675585-e1c56d80-b9a7-11e9-9e42-350145184011.png)

**Comment by Neonchen** [comment]
No. No filters are activated.

**Comment by Sargul** [comment]
I'm sorry that this issue got overlooked so long.

Do you still have the same issue in the newest version?

We have changed a lot of things how Exasol Plugin is handling things, so could you please check the newest version?

**Comment by Neonchen** [comment]
Hey Sargul,
thx for your reply. The issue is not fixed in 7.0.2.

**Comment by uslss** [comment]
@Neonchen ,
could you try to change Connection view to Advanced and check Show System objects option? it works for me
![image](https://user-images.githubusercontent.com/31996417/79849646-67b90580-83cb-11ea-8901-758360e6f6e9.png)

**Comment by Neonchen** [comment]
> @Neonchen ,
> could you try to change Connection view to Advanced and check Show System objects option? it works for me
> ![image](https://user-images.githubusercontent.com/31996417/79849646-67b90580-83cb-11ea-8901-758360e6f6e9.png)

This works! Thx uslss
