### ISSUE TITLE
[DBeaver][Teradata] how to pull Chinese character

### ISSUE THREAD

**Issue by aioie** [dbeaver/dbeaver#646]
I have struggled to pull the Chinese character. I using DBeaver v3.7.0 for windows 10 to connect Teradata.  the results of date set like below.

![image](https://cloud.githubusercontent.com/assets/6565192/17290676/a6b62b90-581a-11e6-9e13-c23ee7cc1971.png)

I attached configuration text file.
[configuration.txt](https://github.com/serge-rider/dbeaver/files/393442/configuration.txt)

and below is my properties setting.
![image](https://cloud.githubusercontent.com/assets/6565192/17290743/02e295a2-581b-11e6-8916-2acb6f19a1a8.png)

How can I fix this issue? Please give me a guide to figure out step by step because I'm not a background with DB.

Thanks,

**Comment by tati-kru** [comment]
Hello @aioie,
Does this problem continue to be actual?

**Comment by tati-kru** [comment]
It looks like this question was solved. It will be closed. If you think that it is actual just let us know.
