### ISSUE TITLE
PostgreSQL insert statement auto complitition error

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#6460]
#### System information: 
- Windows 7 Pro x64
- DBeaver 6.1.4
- Java version 1.8.0_211
- No additional extensions

#### Connection specification:
- PostgreSQL 9.5.16 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit
- Driver org.postgresql:postgresql:RELEASE[9.4.1212.jre7]

Creating table for test;
```
CREATE TABLE tmp_table_06082019(
	id int,
	code varchar(10),
	name text);
```
Refreshing connection.
Typing "INSERT INTO tmp_table_06082019(", press ctrl+space - results are tables of current (active) schema (not table columns).
Typing "INSERT INTO tmp_table_06082019(id,", press ctrl+space - result is table columns

**Comment by uslss** [comment]
still reproducible in 6.2.3

**Comment by kseniiaguzeeva** [comment]
still exists in 6.2.5

**Comment by ems2811** [comment]
Doesn't reproduce in 6.3.3
