### ISSUE TITLE
How to write valid query for DynamoDB

### ISSUE THREAD

**Issue by Sammons** [dbeaver/dbeaver#6462]
#### System information: 
- Operating system (distribution) and version: Mac OSX
- DBeaver version: DBeaver Enterprise	6.1.0.201906122139

#### Connection specification:
- Database name and version: Amazon DynamoDB

#### Describe your question:
I can right click on a table and do "edit data" to see the tabular view of the data, but I cannot figure out how to scan/query the tables. The Wiki also does not mention Dynamo on the right hand side of the landing under "Databases".

How can I query the tables besides just dumping samples of the data?

**Comment by serge-rider** [comment]
There are two options.
You can use simple SQL queries like
```sql
select * from TableName where KeyName='Value'
```
But there are a lot of limitations in DynamoDB queries. E.g. you must specify primary key or partition key.

Also you can use JSON-like API queries: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html

**Comment by Sammons** [comment]
🤦‍♂ I didn't try single ticks around my right-hand value. Also didn't realize I could do the JSON apis 👍  Thank you!
