### ISSUE TITLE
[Feature request] Make "Empty query string" error less intrusive

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6463]
When trying to execute a query from two lines below the query itself, the popup "Empty query string" appears.
Good, right.
But i think it would be good to have the option to reduce it to a small message below data grid, or even better, not open at all, and just show/do nothing...

**Comment by serge-rider** [comment]
Good point.
I'll show warning in active tab status bar.

**Comment by kseniiaguzeeva** [comment]
Verified
