### ISSUE TITLE
[Cloudera][ImpalaJDBCDriver](500100) Error getting table information from database.

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6465]
eclipse.buildId=unknown
java.version=1.8.0_73
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
警告
Wed Aug 07 14:17:06 CST 2019
SQL Warning (DataSource: Hadoop -impala; Code: 0; State: 01000): [Cloudera][ImpalaJDBCDriver](500100) Error getting table information from database.

**Comment by serge-rider** [comment]
Could you post more info. 
Some problem description is needed.
Stacktrace would be very helpful as well (https://github.com/dbeaver/dbeaver/wiki/Log-files)
Otherwise it is not clear what is this ticket about.

**Comment by Pengchenghua** [comment]
[dbeaver_sql_20190807.log](https://github.com/dbeaver/dbeaver/files/3476266/dbeaver_sql_20190807.log)

**Comment by Pengchenghua** [comment]
> Could you post more info.
> Some problem description is needed.
> Stacktrace would be very helpful as well (https://github.com/dbeaver/dbeaver/wiki/Log-files)
> Otherwise it is not clear what is this ticket about.

dbeaver_sql_20190807.log

**Comment by serge-rider** [comment]
I don't see the error (Error getting table information from database.) in the log.
I don't understand how and which circumstances it happens.
