### ISSUE TITLE
PostgreSQL queries return wrong/incorrect result from db

### ISSUE THREAD

**Issue by 452** [dbeaver/dbeaver#6466]
This issue for search engines(who will try to find solution to the same problem) about how to fix problem with incorrect data in resultset because PostgreSQL driver newer than DB and not support as well.

I spend e few hours and found solution to make new connection in dbever but use not recommended latest PostgreSQL from list, but use PostgreSQL Old driver from this list.

I have problem with PostgreSQL connection and incorrect response

dbeaver return wrong/incorrect results/response/data from PostgreSQL database

I have simple sql:

`SELECT name from users where id=1`
as result I have some strange data not filtered by id, strange behavior

**dbeaver version:** Community Edition 6.1.4 (eclipse plugin and standalone version .deb)
**PostgreSQL version:**
```
SELECT version();
PostgreSQL 10.6 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.2.0) 8.2.0, 64-bit
--only work if in dbeaver you select PostgreSQL Old driver
```

**Solution:** if your dbeaver return not correct data from PostgreSQL DB you need try to use new connection to your DB with PostgreSQL Old driver...

issue can be closed or need to think about driver version validation and db version

**Comment by serge-rider** [comment]
Could you write a bit more info. 
What exactly is not correct in the results, "strange data" sounds quite strange :)

**Comment by 452** [comment]
Problem with active "postgres" DB
the same sql query return different result when active postgres DB or target DB
it confused me, because I use dbeaver first time
**Image 1**
![image](https://user-images.githubusercontent.com/1583753/62648729-114e8880-b95c-11e9-8af1-54a9f38dccdf.png)
**Image 2**
![image](https://user-images.githubusercontent.com/1583753/62648598-cc2a5680-b95b-11e9-983f-24910ba134f3.png)
![image](https://user-images.githubusercontent.com/1583753/62649086-cda84e80-b95c-11e9-951f-22df30227009.png)

**Comment by 452** [comment]
also UI improvement light gray or some gray color for inactive/not connected DB in list

**Comment by kseniiaguzeeva** [comment]
Is it still actual for you? Which DBeaver and Postgres driver do you use now?

**Comment by uslss** [comment]
@452 
probably you've got auto-sync with navigator option enabled. So you queried data from different database, as it is shown on you pictures.
Ticket closed.
If issue is still actual for you - feel free to reopen the ticket
