### ISSUE TITLE
Active datasource and active schema on toolbar not updating when a different database connection is used or switched to

### ISSUE THREAD

**Issue by reddyshyam** [dbeaver/dbeaver#6469]
#### System information: 
- Operating system (distribution) and version ~ Windows 10 Pro 64 bit 1903 Latest
- DBeaver version ~ 6.1.4
- Additional extensions ~ None

#### Connection specification:
- Database name and version ~ MySQL 5.7
- Driver name ~ MySQL JDBC Standard
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  ~ SSH

#### Describe the problem you're observing:
Active datasource and active schema not updating when a different database connection is used or switched to. Assuming I closed the saved editor file with a different database source, re-opening it will show the last used database and no schema selected which makes sense. Now if I connect to a new database, then from datasource dropdown, select the active one, the datasource or schema do not get updated. When I click on Active database connection on Database Navigator, then the datasource and active schema get updated. I think this changed with 6.1.4 or 6.1.3

#### Steps to reproduce, if exist:
Please see attached. 

![DB issue](https://user-images.githubusercontent.com/12392746/62628687-5fa65c00-b949-11e9-9831-76b8b6955461.gif)

#### Include any warning/errors/backtraces from the logs
No errors thrown in log file. Have completed un-installed and re-installed just in case if it was an upgrade issue but the issue remains.

**Comment by reddyshyam** [comment]
Added to this since 6.2.0, in the above condition, if an sql update is performed, click on 'Save' button of ResultSet or 'Commit' button, will cause IDE to close.

**Comment by uslss** [comment]
obsoleted issue.
Ticket closed
