### ISSUE TITLE
Databases created for projects don't show up in database navigation tab

### ISSUE THREAD

**Issue by BigMcLargeHuge** [dbeaver/dbeaver#6472]
I've noticed that database connections that are created in the projects tab don't show up in the database navigation tab.  However you can add database connections in the database navigation tab and assign them to projects.  Maybe I'm misunderstanding something but reciprocity here would make sense to me.

OSX 10.14.6
DBeaver 6.1.4
mysqld  Ver 5.6.43 for osx10.14 on x86_64 (Homebrew)

**Comment by p91paul** [comment]
I believe database navigator only shows connections of currently active project. From projects view you can set the active project.
