### ISSUE TITLE
Object container selector- save history (data transfer, fk)

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6473]
This affects data transfer wizard and foreign key creation wizard.
There is a "Container name" control which holds information about target container (schema or database).
In dat transfer wizard we save only last used container ,in FK creation we do not save anything.

This is not user-friendly. We need to save history of last N containers and let user to choose one.

- We need to turn container name input into combobox with N elements.
- Settings must be persistent between different DBeaver sessions.
- Settings must be saved per-project (each project has separate list of last used containers)
- We need to perform actual object search only when user selects a container (perform connection and object search).

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/62644755-1bb45680-b94b-11e9-88e9-82c3e2b30281.png)

![image](https://user-images.githubusercontent.com/6398845/62644770-27a01880-b94b-11e9-9c78-75e1b7c092e6.png)

**Comment by uslss** [comment]
Reopened.
User could choose connection as target container.
So when user exports table, everything looks ok 
![image](https://user-images.githubusercontent.com/31996417/62711409-ad7e9b00-ba01-11e9-8fc3-5f037ae0bdff.png)
but as a result user gets an error
![image](https://user-images.githubusercontent.com/31996417/62711463-c424f200-ba01-11e9-964f-53ff398d353f.png)
For Virtual FK user got next result
![image](https://user-images.githubusercontent.com/31996417/62711536-e4ed4780-ba01-11e9-94df-dc9168e1f2ee.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
