### ISSUE TITLE
Virtual primary key enhancement

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6474]
We need an ability to define virtual unique key for a table even if it already has some real unique key.
This is needed to provide possibility to link tables with virtual foreign key using any custom table columns.

- Virtual PK definition must be available in logical entity edit dialog
- In virtual FK definition dialog it must be possible to define logical PK for tables which already have real one

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/62649345-07755700-b955-11e9-9b07-25375f1e3195.png)

**Comment by uslss** [comment]
Verified.
Virtual unique key could be created even for tables with real unique keys.
- Virtual PK definition must be available in logical entity edit dialog - ok
- In virtual FK definition dialog it must be possible to define logical PK for tables which already have real one - ok
