### ISSUE TITLE
Double-click on a table in search results opens 'Model root' tab

### ISSUE THREAD

**Issue by lhimo** [dbeaver/dbeaver#6475]
#### System information: 
- Windows 10 64 bit
- DBeaver 6.1.4.201908041900

#### Connection specification:
- DB2

By searching for a table in a database connection, double-clicking on it from the results list opens up a '#root' tab instead of opening the table for viewing/editing. 

#### Steps to reproduce:
- Search from the ctrl+H menu
- Double-click on a resulted table
- '#root' tab opens

![image](https://user-images.githubusercontent.com/36077138/62682746-31fafa80-b9bd-11e9-98a4-0bb06b4aed8b.png)

If I click double-click on the table again it opens up like it should.

**Comment by serge-rider** [comment]
Can't reproduce. Could you write a bit more details.
- Does context menu work on search results?
- Please post a screenshot of results table
- Are there anything related in debug/error log? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by lhimo** [comment]
I think it happens when you have results from multiple schemas.

**Comment by uslss** [comment]
is it still actual?

**Comment by lhimo** [comment]
It still happens sometimes

**Comment by lhimo** [comment]
A quick workaround is right click + Edit

**Comment by uslss** [comment]
there is no update on ticket for a long time, it will be closed.
if it is still actual for you - feel free to reopen the ticket
