### ISSUE TITLE
Add support for multiple databases in postgreSQL

### ISSUE THREAD

**Issue by ricardobr001** [dbeaver/dbeaver#6476]
I've searched in the web and found this [issue] (https://github.com/dbeaver/dbeaver/issues/232) from 2016 asking how to work with multiple databases with one connection.

You guys could add this feature for postgreSQL, It'll be a nice feature.

With mySQL servers we already have this feature, and works really well, the same functionallity with postgreSQL would be really interesting.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/62819156-c8602500-bb51-11e9-9e3d-52003f07c6ed.png)

**Comment by ricardobr001** [comment]
That functionality is cool, but would be better if we could specify the db we want to use in the SQL Editor.

In mySQL we can do a `SELECT` like the example below.
`SELECT * FROM my_database1.my_table`
`SELECT * FROM my_database2.my_table`
Or we can specify the database we are using with command `USE`.

That functionality would be interesting, avoiding us to open multiplies connections to query multiplies databases

**Comment by serge-rider** [comment]
You can specify databse+schema for SQL editor. It can be selected in the selectors in the main toolbar.
![image](https://user-images.githubusercontent.com/6398845/62823104-67564280-bb8d-11e9-9856-7c845dd7afd9.png)

**Comment by AlexWayfer** [comment]
> ![image](https://user-images.githubusercontent.com/6398845/62819156-c8602500-bb51-11e9-9e3d-52003f07c6ed.png)

Where is this checkbox now?

![image](https://user-images.githubusercontent.com/6510020/199201651-f4f8a305-9b59-445f-ac2e-8e3c9404c291.png)

**Comment by warnes** [comment]
On the `PostgreSQL` tab:
![Screenshot 2022-11-30 at 3 22 37 PM](https://user-images.githubusercontent.com/6144863/204900851-6b42b338-510b-4692-a833-e6c06439d912.png)

**Comment by kikonen** [comment]
Schema selection in toolbar seems to be rather unusably klunky to use, however. :(
