### ISSUE TITLE
PostgreSQL: auto-recover after "current transaction is aborted" error

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6479]
In PostgreSQL in transactional mode any error leads to consequent errors "current transaction is aborted, commands ignored until end of transaction block", User must manually perform commit or rollback operation.
While in some enterprise applications it makes sense to perform a commit after error (e.g. save changes before last good savepoint) in DBeaver it doesn't make any sense.

So we can freely rollback current transaction.
We can make it automatically without even warning user. It will work only if "Connection auto-recovery option is enabled".

**Comment by uslss** [comment]
verified
