### ISSUE TITLE
How to copy individual/single database 

### ISSUE THREAD

**Issue by ORESoftware** [dbeaver/dbeaver#6480]
I am looking for an easy way to copy a database (not a snapshot of the whole database server, just one single database), using DBeaver:

<kbd>
<img width="658" alt="Screen Shot 2019-08-08 at 11 15 23 AM" src="https://user-images.githubusercontent.com/11139560/62727427-514e5380-b9ce-11e9-9ff0-f29480f8b0e7.png">
</kbd>

for some reason, I don't see an option to copy and name the copy, of a database with the UI tool. I would think this would be something many users would want to do?

**Comment by uslss** [comment]
It is already implemented
https://github.com/dbeaver/dbeaver/wiki/Backup-Restore
