### ISSUE TITLE
Community extensions?

### ISSUE THREAD

**Issue by jim256** [dbeaver/dbeaver#6482]
This is probably a stupid question, but are there extensions or repositories for extensions outside of the few mentioned here?
https://github.com/dbeaver/dbeaver/wiki/Optional-extensions

I get the impression that there may be and think I've seen a repository URL and a few extensions somewhere before, but can't seem to find them again.

I'd love to find something that, for example, mimics some of the add-ins available for SSMS like auto-tab renaming, showing grid aggregates when highlighting data in the results pane, better autocomplete (only seems to work about 70% of the time by default, the other 30% of the time it offers no suggestions), etc.

**Comment by serge-rider** [comment]
Being Eclipse RCP DBeaver supports installation of any Eclipse plugins. 
Som you can install almost any extension from https://marketplace.eclipse.org/ (more than 1000).

**Comment by p91paul** [comment]
for the second request (grid aggregates) check out the "calc" panel on the right of the resultset. It can calculate many functions on selected cells

**Comment by jim256** [comment]
Thank you guys so much! I appreciate it.

**Comment by jim256** [comment]
Thank you guys so much! I appreciate it.
