### ISSUE TITLE
Search in Value panel for XML / Text 

### ISSUE THREAD

**Issue by LeoLozes** [dbeaver/dbeaver#6484]
**Is your feature request related to a problem? Please describe.**
In large fields like XMLTYPEs in Oracle or CLOBs (or just really long texts), you always have to export the value to another editor if you want to search in it. 

**Describe the solution you'd like**
It would be great to have a search field in the value panel:

![image](https://user-images.githubusercontent.com/11133817/62778019-7a92e080-baaf-11e9-9dfa-790f0a725661.png)

This would already be great, but if on top of it there's some kind of expand / collpase per tag, then it would be awesome 💃 

It's one of the only things I miss comparing with SQL Developer: 

![image](https://user-images.githubusercontent.com/11133817/62778213-17ee1480-bab0-11e9-82f5-a7538d1ec0ee.png)

**Comment by serge-rider** [comment]
Makes sense. I'll add find/replace action in the context menu. Along with some other useful actions.

Hint: you also can open your huge xml/json in a separate editor (shift+enter on a cell). Then just <kbd>ctrl+f</kbd>.

Adding code folding as a way too different/complicated feature. Please create another feature request for it.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/62821140-4f23fa80-bb70-11e9-9c82-cffc654759d4.png)

**Comment by uslss** [comment]
verified

**Comment by uslss** [comment]
verified

**Comment by LeoLozes** [comment]
> Adding code folding as a way too different/complicated feature. Please create another feature request for it.

Thanks for resolving it that quickly! Keep up the good job, it's the first database manager that made me ditch Toad for good, and improving every day :)

I'll create another feature request for the code folding.
