### ISSUE TITLE
Visualize read-only state of data / metadata editors

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6485]
We need a way to visualize read-only state of connection, data and metadata editors.
with some icon or text mark.
Correlates with #6397

**Comment by serge-rider** [comment]
- Showing lock icon in the top-left corner for locked tables/connection
- Showing lock icon before column type icon for read-only columns (expressions, etc)

**Comment by serge-rider** [comment]
+ tooltips with explanation why exactly table/column is readonly

**Comment by mkgrgis** [comment]
It will be nice if UI operations ALTER + CREATE + INSERT + UPDATE for readonly connection will be blocked. Now when you try to perform an operation there is an error message from db or jdbc. It is correct, but pointless.

**Comment by serge-rider** [comment]
Done:
![image](https://user-images.githubusercontent.com/6398845/74465327-3ccfa400-4ea6-11ea-815e-01a5c697aeff.png)
no we will show detailed explanation why column is read-only. + show lock icon.

@mkgrgis There is no standard way to determine that connection is in read-only state.
But you can set read-only option in connection settings - in this case dbeaver don't let you to edit data in will show it in UI correctly.

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by mkgrgis** [comment]
@serge-rider Yes, readonly connection = "true" in read-only option in connection settings.

**Comment by serge-rider** [comment]
@mkgrgis I see. DBeaver doesn't check actual SQL queries (yet). If driver doesn't support read-only connections (most of primary drivers support it) then you can execute any query.

Generally it is not possible to restrict data modification on client side (as it can be performed in stored procedure or by other non-direct way). That's why we rely on database-side read-only state.

**Comment by mkgrgis** [comment]
Previously, it was only meant to block "shadow" ALTER + CREATE + DROP + INSERT + UPDATE + DELETE requests from UI, and not any expressions from any UI/DB/jdbc etc. source. Now the program fully implements my wishes. Thanks.
