### ISSUE TITLE
dBeaver 6.1.4 Can't Show List of Tables/Views in Database Navigator

### ISSUE THREAD

**Issue by lalato** [dbeaver/dbeaver#6487]
#### System information: 
MacOS 10.14.5
dBeaver 6.1.4

#### Connection specification:
- Teradata 16.20

#### Describe the problem you're observing:
After upgrading to 6.1.4, when I attempt to view the database objects in the Navigator pane, it results in the spinning beachball from which the only way out is to Force Quit dBeaver.

#### Steps to reproduce, if exist:
Every time I attempt to expand the Connection to see Tables/Views

<img width="246" alt="image" src="https://user-images.githubusercontent.com/9371670/62803104-6eeaee00-ba9e-11e9-8d98-64086e191c42.png">

**Comment by serge-rider** [comment]
What version of Teradat driver do you use?
In 6.1.1+ we have upgraded bundled Java version to 11. This may cause problems in old JDBC drivers.
If you use default preconfigured driver (15.0) - please try to download fresh driver from https://downloads.teradata.com/download/connectivity/jdbc-driver

**Comment by lalato** [comment]
I'm using the 16.20 Teradata driver, but will check for a newer version.  I had no issues like this with 6.1.3.

**Comment by lalato** [comment]
I decided to try downloading the installer and re-installing from there.  The issue is now resolved for me.  Not sure why updating via Homebrew would have resulted in this issue.
