### ISSUE TITLE
DBeaver loses control over connection status

### ISSUE THREAD

**Issue by zazy** [dbeaver/dbeaver#6491]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04.3
- DBeaver version: 6.1.4
- Additional extensions: none

#### Connection specification:
- Database name and version: MySQL 5.7.27 on Ubuntu server 16.04.1
- Driver name: MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
As soon as I connect to my remote MySQL db all operations are executed quickly. Everyting works fine while I keep interacting with DBeaver. But if I leave the UI for a short time and (for example) read an email, when I return to DBeaver I'm no longer able to do anything. Every task takes forever, there is no way to cancel any pending task and the only way to let DBeaver to work again is to kill the process and restart it. Hitting the "Cancel" button under the "Fetch table data" for example, or hitting the "Stop" button in the "Background tasks" view, this simply does nothing but change the button status to "Disabled" so that it can no longer be clicked. This makes DBeaver unuseful.

I tried to change some connections driver parameters before posting this issue:
- Change the connectionTimeout parameter to 0
- changed the interactiveClient to true

#### Steps to reproduce, if exist:
As above

#### Include any warning/errors/backtraces from the logs
![Schermata da 2019-08-11 18-19-12](https://user-images.githubusercontent.com/10668286/62836570-ea969780-bc64-11e9-879a-17dbc88233e0.png)

**Comment by uslss** [comment]
hi @zazy is it still actual?

**Comment by zazy** [comment]
Hi @uslss I'm now on 7.0.3 and I no longer have this bug. Feel free to close this. Thank you.
