### ISSUE TITLE
Float values rounded up to 3 fractional digits when editing cell values

### ISSUE THREAD

**Issue by wcactus** [dbeaver/dbeaver#6493]
I have a PostgreSQL table with following definition:
```
CREATE TABLE public.partners (
	id serial NOT NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	"name" varchar(250) NOT NULL,
	website varchar(250) NULL,
	phone varchar(250) NULL,
	address text NULL,
	x float8 NULL,
	y float8 NULL,
	city varchar(100) NULL,
	CONSTRAINT partners_pkey PRIMARY KEY (id)
);
```

I opened this table in DBeaver and swithed to the "Data" tab. Then I tried to edit values in cells "x" or "y" and got "73.394" instead of original value "73.394236" after switching to edit by double click on table cell.

I checked Settings > Databases > Editors > Data editor > Data formats, and "Maximum fractional digits" was set to "10".

Operation system: Windows 10 Pro x64
DBeaver version: 6.1.4.201908041900
Database: PostgreSQL 11.4 (Debian 11.4-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
Driver: PostgreSQL JDBC Driver
Connection: local

**Comment by serge-rider** [comment]
I can;t reproduce this. 
Please verify that you don't have settings "Data editor > Data formats" redefined for your particule connection. Like this:
![image](https://user-images.githubusercontent.com/6398845/62839436-06606480-bc8a-11e9-9e0a-67eff97e83cb.png)

**Comment by wcactus** [comment]
I have no checked option "Datasourse xxx settings" on this tab for connection.
![Screenshot_1](https://user-images.githubusercontent.com/14895107/62839697-42012b80-bc96-11e9-9ded-978fe02b2337.png)

**Comment by msharp228** [comment]
I noticed this issue on 6.1.2 and 6.1.4 when just selecting the data (no edit required).  The columns with the issue are float4 with precision and scale 8.  My Numbers Data Format have Maximum Fraction Digits 10.  The problem doesn't occur in 6.1.0 or 6.1.1.

**Comment by serge-rider** [comment]
this can be reproduced by executing simple query "SELECT 73.394236"

This can be fixed by setting "rounding mode" parameter to "UNNECESSARY" (in Data Formats settings).
Probably we should set it to default (now we use default Java rounding - HALF_EVEN).

**Comment by kseniiaguzeeva** [comment]
Verified
