### ISSUE TITLE
Can't Highlight/Copy DBeaver Version

### ISSUE THREAD

**Issue by Lonniebiz** [dbeaver/dbeaver#6497]
In dBeaver 6.1.4.201908041900, on Windows 10, it will not allow you to highlight and copy the dBeaver version from the Help > About dialog.

Since the version numbers are 15 characters long, this ability would be helpful during bug reporting.

![DBeaverVersion](https://user-images.githubusercontent.com/151919/62845011-d1084680-bc8a-11e9-9960-c36a96813935.png)

**Comment by serge-rider** [comment]
Good point

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by Lonniebiz** [comment]
Yep. I noticed this today. You can copy the version now. Thanks.
