### ISSUE TITLE
close jdbc connection (main)

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6499]
![image](https://user-images.githubusercontent.com/26621087/62849983-348a8680-bd14-11e9-8ca1-4ebc71faff01.png)
Unable to close JDBC connection (main) in time,need to close the software to end

**Comment by serge-rider** [comment]
What kind of operation did you do? Sometime it may happen when network tunnel/vpn/proxy connection has died. In that case you need to wait till socket timeout will happen.
