### ISSUE TITLE
Postgres connection error 

### ISSUE THREAD

**Issue by lucam89i** [dbeaver/dbeaver#6500]
#### System information: 
- Windows 10
- DBeaver CE 6.1.4 

#### Connection specification:
- Postgres 9.3.5.14

#### Describe your question:
Hi,
Actually i'm working with DBEaver CE 6.1.0. 
I'm trying to migrate to DBeaver 6.1.4 but i found a problem with postgres connection. 

When i try to connect to my postgres database dbeaver shows the error "**Server does not support SSL**" but i'm not use SSL connection in my connection settings. 

![image](https://user-images.githubusercontent.com/39702112/62853901-0b56ff80-bcee-11e9-9543-5d5c1c82c448.png)

![image](https://user-images.githubusercontent.com/39702112/62853865-f37f7b80-bced-11e9-874c-19fffc5b8e82.png)

![image](https://user-images.githubusercontent.com/39702112/62854081-87e9de00-bcee-11e9-82f4-643ee92b4310.png)

Obviously with DBeaver 6.1.0 the same connection work fine.
 
Can you help me?

Best Regards.
LR

**Comment by kseniiaguzeeva** [comment]
Is this question still actual for you? Could you try 7.0.3 version?

**Comment by uslss** [comment]
there is no update on ticket for a long time. if issue is still actual for you - feel free to reopen the ticket
