### ISSUE TITLE
Add a 'Select All' button when importing connections

### ISSUE THREAD

**Issue by WouterVdS** [dbeaver/dbeaver#6501]
**Is your feature request related to a problem? Please describe.**
We regularly import a lot of database connections from a csv file (250+ connections). In the import wizard, there is a step to select all database connections which you want to import. This is a frustrating task for 250+ connections.

**Describe the solution you'd like**
A simple 'Select All' button to automatically select all database connections.

**Describe alternatives you've considered**
/

**Additional context**
![screenshot](https://user-images.githubusercontent.com/10326197/62856448-3d1f9480-bcf5-11e9-8d25-c5d10a344064.png)

**Comment by serge-rider** [comment]
This makes sense. And easy to do.

**Comment by WouterVdS** [comment]
Thanks a lot Serge!

**Comment by uslss** [comment]
verified
