### ISSUE TITLE
[BUG] Long-time operations notifications generates error when DBeaver has focus

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6502]
Whenever *for the first time* DBeaver has to open a popup notifying the end of long-time operation, it produces the error in screenshot (Ubuntu Mate 18.04, DBeaver 6.1.4). Still, query executed correctly, which is really confusing...

To reproduce, start a fresh DBeaver instance, set `Enable long-time operations notifications` to 10 seconds, run (in PG) the query `SELECT pg_sleep(10);`, be sure not to take focus away from running window.

Error will be:

![err1](https://user-images.githubusercontent.com/3930671/62863780-1a4bab00-bd0a-11e9-9d82-dd40f16341c4.png)

**Comment by p91paul** [comment]
Could be a less destructive version of this? https://github.com/dbeaver/dbeaver/issues/3931

That ticket made DBeaver unable to start, but its workaround involved commenting something about AtkWrapper in java properties, so maybe the same workaround helps you.

**Comment by serge-rider** [comment]
@p91paul thanks for the hint.

Anyway, we need to add error handler for try notifications to avoid user confusion.

**Comment by serge-rider** [comment]
@wiwwo could yout test the fix in Early Access version (https://dbeaver.io/files/ea)?

**Comment by wiwwo** [comment]
6.1.5 from https://dbeaver.io/files/ea seems to have solved the problem!
