### ISSUE TITLE
Date format in Results window

### ISSUE THREAD

**Issue by jkashwin** [dbeaver/dbeaver#6503]
#### System information: 
- Operating system (distribution) and version = Windows 10 Enterprise
- DBeaver version = 6.1.4.201908041900

#### Connection specification:
- Database name and version = Oracle 12

#### Describe your question:
I'm trying to get one of my date fields to display in DD-MON-YY format in the resultset window and no matter how much I try changing and restarting Dbeaver, it does not work. It still displays date field in "dd-MON-yy hh:mi:ss" format. I tried going to Edit Connection->Connection configuration for my oracle database->Result Sets->Data Formatting and setting
Type: Date - Pattern = dd-MMM-yy . Tried it for this specific connection as well as globally, but I can't get only the date portion to display. What am I doing wrong?

 This used to work in one of the previous versions correctly but has since stopped working in version 6.x if i remember correctly. 

![dBeaver_DateFormatIssue](https://user-images.githubusercontent.com/33062038/62879523-ec0da180-bcf0-11e9-8469-3515c7bde6ad.JPG)

**Comment by jkashwin** [comment]
Also wanted to report a bug related to this question - Changing "format" type under Preferences->Editors->Data Format does NOT save the format upon hitting [Apply] or [Apply and Close] buttons.

**Comment by serge-rider** [comment]
Date type in Oracle are sophisticated. In fact there is no DATE data type - it is basically the same as TIMESTAMP.
There are several techniques (e.g. using column display width or precision) but we stopped using them in 5.x version. Because sometimes it worked incorrectly (and we printed timestamps as dates - and this is much worse).

If anybody has any thoughts about this (how to correctly determine whether column has type DATE or TIMESTAMP) - please write a note.

Till then we show all dates as timestamps in Oracle. And this is why changing Date format doesn't affect anything (you need to change timestamp format).

**Comment by jkashwin** [comment]
Thank you for your quick reply! The display does NOT matter much. I was just trying to export data from the results window without the time portion of the Date/Timestamp field.  Tried changing the timestamp format globally to display the date/timestamp column as 'dd-MMM-yy', but the resultset window or the table data view still displays time along with the date. What am I missing?

**Comment by serge-rider** [comment]
It shoudl work if you will change timestamp format:

![image](https://user-images.githubusercontent.com/6398845/62955624-a8e72780-bdf1-11e9-833e-1f597517682e.png)

![image](https://user-images.githubusercontent.com/6398845/62955639-ae447200-bdf1-11e9-9341-3aa7e20a6cf7.png)

**Comment by p91paul** [comment]
> Date type in Oracle are sophisticated. In fact there is no DATE data type - it is basically the same as TIMESTAMP.

Yes, the only difference is TIMESTAMP has fractional seconds

> There are several techniques (e.g. using column display width or precision) but we stopped using them in 5.x version. Because sometimes it worked incorrectly (and we printed timestamps as dates - and this is much worse).
> 
> If anybody has any thoughts about this (how to correctly determine whether column has type DATE or TIMESTAMP) - please write a note.

The trivial way, if you are working on a single table, is to check ALL_TAB_COLUMNS. However I suppose you are trying to use jdbc metadata to be more general and handle custom queries. What does ResultSetMetaData.getColumnTypeName return you? Javadoc says "Retrieves the designated column's database-specific type name.", which looks promising.

**Comment by serge-rider** [comment]
We use direct select from ALL_TAB_COLUMNS so it is not  problem. 
Anyway DATE. iss actually timestamp (even without frational seconds).
So this doesn't solve the problem. There is no data type which holds only date without time.

But still Oracle itself (sql plus for instance) somehow shows only date part for some columns.

**Comment by p91paul** [comment]
Ok I see your point now.
I'd still say the default formatting for DATE should be with time up to second, while the default for TIMESTAMP should be with time up to microseconds; so they at least deserve to be 2 separate datatypes with separate formats.

I believe the only way it does that is by looking at the value. If the time part is 00:00:00 it's a date and time can be truncated. However this must be done on a cell-by-cell basis.
