### ISSUE TITLE
Can't see the table list in the Add Constrain window

### ISSUE THREAD

**Issue by sebolio** [dbeaver/dbeaver#6506]
#### System information: 
- Microsoft Windows 10 Home (1903)
- DBeaver version 6.1.14

#### Connection specification:
- Postgresql latest

#### Steps to reproduce, if exist:
Open "constraints" tab then right click and choose "Create new constraint"

#### Include any warning/errors/backtraces from the logs

I can't see any of my tables on the chooser, however if I click "Select All" they do get selected and I can click "OK" and they get all added

![image](https://user-images.githubusercontent.com/197329/62905241-98727680-bd37-11e9-9c2a-46b323969213.png)

![image](https://user-images.githubusercontent.com/197329/62905267-b63fdb80-bd37-11e9-84a3-aefa62b77bb2.png)

**Comment by serge-rider** [comment]
Do you mean column list? 
It is not visible because dialog has too small size. DBeaver remembers dialog size from previous usage and sometimes it is too small. We must set its size to fit all contents at least.
Thank you for the bug report.

Workaround: resize dialog manually (using mouse).

**Comment by sebolio** [comment]
Thank you @serge-rider. 
I didn't know the dialog was resizable because, it's not something common for dialogs in Windows, maybe you could put an icon in the corner like the lines in TEXTAREAS:

![image](https://user-images.githubusercontent.com/197329/62970768-36208100-bdde-11e9-8be8-5c6cfc211d54.png)

**Comment by kseniiaguzeeva** [comment]
Verified.
