### ISSUE TITLE
Can't view data in grid mode

### ISSUE THREAD

**Issue by azambiez** [dbeaver/dbeaver#6507]
#### System information: 
- Operating system: Linux Mint 19.2 Cinamon (Linux asyw-pc 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)
- DBeaver version: 6.1.4 (I also tried other 6.* version and it's the same result)
- Additional extensions: No
![Screenshot from 2019-08-13 08-35-26](https://user-images.githubusercontent.com/12593736/62909087-639d0880-bda5-11e9-96d6-5fde3460bec5.png)

#### Connection specification:
- Database name and version: (MySQL, Oracle)
- Driver name: (Default MySQL driver, Official Oracle driver)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I can't view the data on grid mode, while text mode is okay
#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/12593736/62909422-c216b680-bda6-11e9-95bd-126e3bc09896.png)
![image](https://user-images.githubusercontent.com/12593736/62909438-cf33a580-bda6-11e9-9c57-53c55f464972.png)

**Comment by bmcduartecsw** [comment]
Hey, I'm facing the same issue using Linux Mint too. How did you solve it @azambiez ?

**Comment by bmcduartecsw** [comment]
Found a fix. I'm leaving the link for anyone with the same issue: [#5854](https://github.com/dbeaver/dbeaver/issues/5854)

**Comment by azambiez** [comment]
> Found a fix. I'm leaving the link for anyone with the same issue: [#5854](https://github.com/dbeaver/dbeaver/issues/5854)

Yes. Sorry! I should have left it here so that other people can see.
