### ISSUE TITLE
ER Diagram background using Darkest Dark theme

### ISSUE THREAD

**Issue by armando-basile** [dbeaver/dbeaver#6508]
#### System information: 
- Operating system (distribution) and version: Mageia 7 x86_64
- DBeaver version: 6.1.4 CE
- Additional extensions: Darkest Dark theme

#### Describe the problem you're observing:
When i generate ER Diagram, background is black but, if i click on each other place in DBeaver, background change to white, also if i try to export an image for example.

![background_white](https://user-images.githubusercontent.com/4487385/62926914-c7c7c880-bdb5-11e9-87da-deafc36061f0.jpg)

to restore background color to black i need to use Refresh Diagram button

**Comment by uslss** [comment]
still reproducible in 7.1.2

**Comment by deanna-abrams** [comment]
Related request - it would be nice to have the option to export with a white background and white tables even when in dark mode, so that you can get a nice printable image without changing color themes for the whole application.

**Comment by cristian-home** [comment]
Still reproducible in 7.1.2

**Comment by uslss** [comment]
not reproducible against 21.0.3

**Comment by cristian-home** [comment]
Still reproducible in 21.0.3

![bug](https://user-images.githubusercontent.com/4079493/115426678-5a914b00-a1c6-11eb-9e7c-914096cb4d50.gif)

**Comment by LucasRibeiroRJBR** [comment]
Still reproducible in 21.2.4

**Comment by BoilingSoup** [comment]
22.1.0 still reproducible

**Comment by hnavia** [comment]
23.0.0.202303040621 - Still reproducible
