### ISSUE TITLE
Expand All button in Project explorer tab expand only selected tree not all

### ISSUE THREAD

**Issue by SylwesterZarebski** [dbeaver/dbeaver#6509]
### System information:

- Operating system (distribution) and version: Windows 10 x64 1809
- DBeaver version: 6.1.4
- Additional extensions: none

### Describe the problem you're observing:

When clicking `Expand All` button in `Project explorer` tab, only selected subtree is expanded, not all. On the contrary, `Collapse All` button collapses all subtrees.<br>

Using this button.<br>

![obraz](<https://user-images.githubusercontent.com/1755531/62934145-26943e80-bdc4-11e9-9803-0d8792075f3b.png>)

### Desired functionality

Expand all subtrees.

### Steps to reproduce, if exist:

Select (click) first item i.e. Bookmarks in Project explorer tab.<br>

Click `Expand All` button.<br>

ER Diagrams and Scripts are not expanded, only Bookmarks was.

### Include any warning/errors/backtraces from the logs

N/A.

**Comment by serge-rider** [comment]
Agreed, this works in an unexpected way.

However expanding all folders is dangerous. There can be thousands of nested folders and a single misclick may lead to the program hangup.
- Maybe we should expand everything but only on one tree level? 
- Or maybe some warning/confirmation should be used in case of deep folders tree?
- Or maybe we shouldn't expand linked folders?

Any thoughts?

**Comment by SylwesterZarebski** [comment]
I think there is little danger in this case - in Project explorer tab.
And even if someone could have millions of bookmarks or scripts, complexity is only 3 times larger (Bookmarks + ER Diagrams + Scripts) than one subtree.

If this button is used elsewhere, there may be dragons ;-).

**Comment by serge-rider** [comment]
The problem is in linked folders. You can link your disk C: or / to the scripts folder. This will lead to expansion of thousands folder and will take forever.

**Comment by SylwesterZarebski** [comment]
Yet it is the same problem when using button and `Scripts` is selected.

Quick workaround could be changing description to `Expand Selected` (which is current behaviour) instead of `Expand All` and icon to something more distinct.
I'm not really used to 'Expand All' in this context (Project explorer tab), thus workaround/rename is fine for me.

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D22](https://dbeaver.testquality.com/project/8805/result/1744132/defect/6048). Do not remove or edit.

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D50](https://dbeaver.testquality.com/project/8805/result/1761602/defect/6105). Do not remove or edit.

**Comment by serge-rider** [comment]
Command label fixed

**Comment by uslss** [comment]
verified
