### ISSUE TITLE
query duplications after invalidating

### ISSUE THREAD

**Issue by darek1028** [dbeaver/dbeaver#6514]
#### System information: 
- Windows 10 Pro
- DBeaver version 6.1.4
Connections to PostgreSQL

Hi,
I'm sorry i can't find this issue, maybe I cannot named it correctly as a noob.
When invalidating connection, no matter if manually or not, running query sent from an editor seems to be 'duplicated' once. 

E.g. I'm creating a table, and after each invalidation a new same 'job' appears.
![Przechwytywanie](https://user-images.githubusercontent.com/54082472/62975797-84a04080-be1b-11e9-81f7-b35dfef38d40.JPG)

When first one finish, other will return error to dbeaver...
I use BD for few years and I don't remember such thing.

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer. I cannot reproduce issue in DBeaver 7.0.3. Is it still actual for you?

**Comment by darek1028** [comment]
Hi,
Yes it's still happen. I had a long query today - after connection
invalidation I saw additional PID 'clone' with different number and fresh
start date in session manager.
regards,


czw., 23 kwi 2020 o 10:54 Kseniia <notifications@github.com> napisał(a):

**Comment by kseniiaguzeeva** [comment]
I reproduced. And as I see it is expected behavior. Your query is running, and you invalidate the database at this time (disconnect, then connect).
So, the query is interrupted and the query execution begins again, once the database was connected.
![dbeaver_WeJpGMlBGu](https://user-images.githubusercontent.com/51405061/81301691-0d35cf80-9082-11ea-8a56-889142891f72.png)

Can I help you with something else?

**Comment by darek1028** [comment]
Thank you,
I misunderstood session manager. After invalidating, old PID assigned to my
query is STILL ACTIVE.
But in query manager i see duration and result.... Ive never looked at
query manager.
I can terminate "old" pid in session manager, what doesn't imply any message

Is it possible in dbeaver to make query (create table) run still after
client's disconnection?:)
regards,


czw., 7 maj 2020 o 15:46 Kseniia <notifications@github.com> napisał(a):

**Comment by kseniiaguzeeva** [comment]
It depends on whether the backend has received the query. If yes, then the query is executed.

Please reopen the ticket or create a new one, if you have any other questions.
