### ISSUE TITLE
Postgres Query Speed / Performance

### ISSUE THREAD

**Issue by jim256** [dbeaver/dbeaver#6516]
#### System information: 
- Operating system (distribution) and version: OS X Mojave 10.14.6 (18G87)
- DBeaver version 6.1.4

#### Connection specification:
- PostgreSQL 10.1

#### Describe your question:
The query speed in PostgreSQL seems to be really slow. It will take significantly longer to fetch the first 150 rows than Postico will take to fetch all 8k rows. Are there any particular settings I need to be looking at? Or is it a known issue that it's slower?

**Comment by serge-rider** [comment]
No, there are no any special settings for that. Generally PostgreSQL queries can work very fast (e.g. I can export about 50k rows per second using Data export wizard). So this must be something in your network configuration or in the driver configuration or in the query itself (if it is something complicated).

You can try to view query execution plan in DBeaver and in Postico.
