### ISSUE TITLE
Error reported after cancel query, unable to query

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6518]
![image](https://user-images.githubusercontent.com/26621087/62988807-45eca380-be78-11e9-83ac-d9fe2064b628.png)
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Administrator/AppData/Roaming/DBeaverData/workspace6/

This is a continuation of log file C:\Users\Administrator\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2019-08-14 09:40:38.271

org.jkiss.dbeaver.model
错误
Wed Aug 14 09:45:11 CST 2019
Error executing query
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Administrator/AppData/Roaming/DBeaverData/workspace6/

This is a continuation of log file C:\Users\Administrator\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2019-08-14 09:40:38.271

org.jkiss.dbeaver.model
错误
Wed Aug 14 09:45:11 CST 2019
SQL 错误 [08S01]: org.apache.thrift.transport.TTransportException: SASL authentication not complete

**Comment by uslss** [comment]
unfortunately cannot reproduce the ticket.
there is to less information.
if it is still actual for you - feel free to reopen the ticl=ket or create a new one
