### ISSUE TITLE
 Read a negative frame size (-2147418110)!

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6520]
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

This is a continuation of log file C:\Users\Administrator\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2019-08-14 11:01:14.535

org.jkiss.dbeaver.model
警告
Wed Aug 14 11:38:22 CST 2019
org.jkiss.dbeaver.DBException: SQL 错误 [08S01]: Read a negative frame size (-2147418110)!

**Comment by uslss** [comment]
unfortunately cannot reproduce the ticket.
there is to less information.
if it is still actual for you - feel free to reopen the ticl=ket or create a new one
