### ISSUE TITLE
Update dbeaver without loosing plugins

### ISSUE THREAD

**Issue by anandkothapeta** [dbeaver/dbeaver#6522]
#### System information: 
- Windows 10
- 6.1.4

#### Connection specification:
- Mysql 5.x

#### Describe your question:
I looked around but didn't find the answer. 
We use the dbeaver zip version to update the version. We have git and other plugins installed. However whenever we upgrade we keep loosing plugins. Is there a way to upgrade plugins without loosing the plugins.
We upgrade by unzipping the zip version of dbeaver and replace the contents.

Thanks,
Anand K.

**Comment by ethanherbertson** [comment]
I think this behavior is currently "intentional". However, I'd love it if installed plugins could be auto-updated, or in some way persisted, when DBeaver CE was updated. It really is a pain to have to maintain a list of plugins I have installed and where I got them, so that I can grab them all again whenever I update.

It's actually the only reason I don't update DBeaver every two weeks.

If they can't be persisted across DBeaver updates, is there at least a way to export a list of currently-installed plugins, and where they came from? Even an export/import feature would remove a lot of the hassle of upgrading.

**Comment by anandkothapeta** [comment]
Dbeaver is built on Eclipse. So same behavior is fine with Eclipse. When I upgrade Eclipse I dont loose my plugins. May be the only difference is I am upgrading via unzipping the dbeaver but usually eclipse is updated via software update.

**Comment by ethanherbertson** [comment]
This also applies to people like myself that only have DBeaver and don't
use eclipse.

**Comment by anandkothapeta** [comment]
May be I was not clear. When I upgarde eclipse I dont loose my plugins. But in dbeaver we do.

**Comment by ethanherbertson** [comment]
FYI the latest version(s?) of DBeaver CE now start a wizard the first time you start the program after upgrading, that prompts you to update (reinstall?) your plugins. This might fix your issue, or at least help.

**Comment by 2019-05-10** [comment]
That wizard loads the plugin all over again from its update site, which in my case takes considerable time, and blocks in the meantime DBeaver completely -- just to download the exact same version that was already installed.

**Comment by GregStef** [comment]
> FYI the latest version(s?) of DBeaver CE now start a wizard the first time you start the program after upgrading, that prompts you to update (reinstall?) your plugins. This might fix your issue, or at least help.

Where is this wizard? I've never seen it during the past 5 updates (at least) - now on 23.3.5.202402181738

**Comment by GregStef** [comment]
> That wizard loads the plugin all over again from its update site, which in my case takes considerable time, and blocks in the meantime DBeaver completely -- just to download the exact same version that was already installed.

Where is this wizard? I've never seen it for, at least, the past 5 updates (now on 23.3.5.202402181738)

**Comment by xenago** [comment]
I've never seen that wizard pop up. I always have to go and reinstall the git/theme plugins every update and it takes a while...
