### ISSUE TITLE
[BUG] Unable to close editor with "Update conflict" file

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6524]
Open a sql editor
Write something
Save (as) file somewhere, call it XXX

Open a text editor
Open XXX
Change something
Save

Go back in DBeaver
This appears:
![notification1](https://user-images.githubusercontent.com/3930671/63089781-5759ac80-bf59-11e9-9055-6d59276824e5.png)
Click "Do not replace"
Try to close that tab
Notification appears:
![notification2](https://user-images.githubusercontent.com/3930671/63089840-8c65ff00-bf59-11e9-8625-a79ecd734f84.png)
Click NO

File won't close.
There is no way i can close that tab without overwriting the file.

**Comment by mtricht** [comment]
@wiwwo I'm unable to reproduce this on 6.1.5, are you still experiencing this issue?

**Comment by wiwwo** [comment]
Sems like problem solved

**Comment by wiwwo** [comment]
Problem back in (at least) 7.1.0

**Comment by serge-rider** [comment]
This behavior was changed in 7.3. Now it looks like this:
![image](https://user-images.githubusercontent.com/6398845/107230097-a938a100-6a2f-11eb-8acc-3fe68f488e4e.png)

**Comment by uslss** [comment]
verified
