### ISSUE TITLE
Use of workbench/j as formatter

### ISSUE THREAD

**Issue by deep750** [dbeaver/dbeaver#6525]
Hi,
I tried to use the workbench/j as formatter. Using it works, but I'm not able to configure the workbench formatter. How do I configure the formatter, as when I configure the formatter options in workbench, the changes aren't applied in dbeaver. A little help on how to apply the formatter from workbench/j in dbeaver is apprecieated

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer. Is it still actual for you? What exactly do you want to configure?

**Comment by deep750** [comment]
Yes please. I would appreciate a how to

**Comment by deep750** [comment]
Any updates?

**Comment by kseniiaguzeeva** [comment]
A little investigating was needed. DBeaver uses only default Workbench settings.
