### ISSUE TITLE
Not a valid month when trying to import csv

### ISSUE THREAD

**Issue by manfromouterspace** [dbeaver/dbeaver#6526]
## System information: 
- Windows 7 x64
- DBeaver 6.1.4

#### Connection specification:
- Oracle 11g Enterprise Edition

#### Describe your question
I'm trying to import csv file into db. One of the fields had a date datatype. In CSV it has dd.mm.yyyy format like 01.03.2019. And i selected same template in importing wizard. But i still get the error "not a valid month".
Maybe i'm doing something wrong?

**Comment by serge-rider** [comment]
Date format is wrong. It should be dd.MM.yyyy (note uppercase M for month, lower case m is for minutes)
