### ISSUE TITLE
dBeaver shows incorrect results from function calls 

### ISSUE THREAD

**Issue by liudvikasakelis** [dbeaver/dbeaver#6527]
#### System information: 
- Arch linux 5.2.8 kernel
- Dbeaver 6.1.4

#### Connection specification:
- SQL server 2016 SP2
- Microsoft JDBC Driver for SQL Server - version 7.2.1, also same behavior with jTDS

#### Describe the problem you're observing:

Executing a stored function returns different results when done from dBeaver. I cannot provide all the sources, but what I'm doing is essentially this:

    select * From [table].[schema].[procedure] (123456, null, 0, 0, 0, 0) WHERE FieldName = 'Field_1';

this returns slightly different results depending if I call it from dBeaver or from Python using `jaydebeapi`. The differences are not that obvious/big (the table that the function returns has a few values equal to NULL when the function was called from dBeaver).

#### Steps to reproduce, if exist:

Connect to the database, press Ctrl + ], paste in the command:

    select * From [table].[schema].[procedure] (123456, null, 0, 0, 0, 0) WHERE FieldName = 'Field_1';

press Ctrl + Enter. Some results will be returned.

Python script:

    import jaydebeapi  
    conn_url = 'jdbc:sqlserver://1.1.1.1;user=user;password=password'
    class_name = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    query = "select * From [table].[schema].[procedure] (123456, null, 0, 0, 0, 0) WHERE FieldName = 'Field_1';"
    conn = jaydebeapi.connect(class_name, conn_url)
    curs = conn.cursor()
    curs.execute(query)
    curs.fetchall()

Different results returned.

I know this contains little information, and I really can't disclose the sources to the procedure being called, but in essence, what could be possible reasons for dBeaver to return different results when given an identical function call? Literally every other way I know of connecting to a MS SQL server (python through odbc, R through odbc, SSMS) returns the correct result, same as the python script above, and only dbeaver returns certain cells filled with NULL values. Furthermore, if this is not a bug and just some configuration option that I missed, is that a sensible default if it returns different results?

I'll be happy to provide any additional information, however, all the sources are company property and very likely confidential.

**Comment by p91paul** [comment]
it might have something to do with date formats/decimal separators, which depend on locale settings?

**Comment by liudvikasakelis** [comment]
Any simple way to check that? 
I'm not sending any locale-depending parameters to the function (the first parameter is an ID for a table, and it's definitely delivered intact), and I would have thought that the internal variables inside the procedure don't depend on my client settings.

**Comment by p91paul** [comment]
they depend on it, since locale parameters usually are set per connection/session

**Comment by liudvikasakelis** [comment]
Will try, thanks for your notes. By the way, where would I find settings for setting these locale parameters? Is it just sending client system locale settings etc?

**Comment by uslss** [comment]
Data Formats could be changed in Preferences
![image](https://user-images.githubusercontent.com/31996417/88223759-a8494900-cc70-11ea-9760-1899fcd59741.png)
