### ISSUE TITLE
Support logical references and foreign keys on the References panel

### ISSUE THREAD

**Issue by tati-kru** [dbeaver/dbeaver#6530]
All logical foreign keys and references has to be shown in the list on the Reference panel together with regular and foreign keys and references.

As foreign keys and references can be from different databases now we need to show the database name on the Reference panel.

**Comment by Pengchenghua** [comment]
> 必须在“参考”面板的列表中显示所有逻辑外键和引用以及常规键和外键和引用。
> 
> 由于外键和引用现在可以来自不同的数据库，我们需要在“参考”面板上显示数据库名称。

Can SQL completion be prompted for name completion in the editor? Currently, the lookup function in name cannot be implemented

**Comment by kseniiaguzeeva** [comment]
Verified.
