### ISSUE TITLE
Error running job 'Search proposals...' execution: 

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6532]
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Administrator/AppData/Roaming/DBeaverData/workspace6/

This is a continuation of log file C:\Users\Administrator\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_2.log
Created Time: 2019-08-16 10:26:50.286

org.jkiss.dbeaver.model
错误
Fri Aug 16 10:42:58 CST 2019
Error running job 'Search proposals...' execution:

**Comment by serge-rider** [comment]
Not clear what exactly works incorrectly. There may be numerous exception in the log but it doesn' mean that it is a bug. It maybe network failure error or anything else.
