### ISSUE TITLE
Close window on click on copy button in generate SQL dialog

### ISSUE THREAD

**Issue by tchibatron** [dbeaver/dbeaver#6533]
It would be nice, if it was an option to configure the behavior of Generate SQL dialog when user clicks on the copy button.
The goal of the feature is to avoid of clicking on copy and after that on close button. To my mind it's better to have one button "Copy & close" and another one  - "Cancel".

**Comment by serge-rider** [comment]
This makes sense. And I don't think that need some config option for that. Extra button maybe..

**Comment by kseniiaguzeeva** [comment]
Verified
