### ISSUE TITLE
DBeaver: Schema filter at Database level

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#6535]
DBeaver - Version 6.1.4 CE
Operating System: Windows 10
JDBC Driver: mssql-jdbc 7.0.0.jre10
Database: Microsoft SQL Server Database

@serge-rider Can we have a feature where the Schema filter be applied at database level rather than connection level ?
As of now the Schema filter works fine but at the connection level only.

Please let me know if such a feature can be added ? This will be very helpful.

**Comment by uslss** [comment]
for now, schemas could be filtered in the scope of one database at Database tab. If it doesn't resolve the problem, please reopen an issue or create a new one
![image](https://user-images.githubusercontent.com/31996417/121178864-a88e0b00-c867-11eb-923b-53a31900498a.png)
