### ISSUE TITLE
Smooth Scrolling in Query Results Pane

### ISSUE THREAD

**Issue by jim256** [dbeaver/dbeaver#6536]
When browsing the results of a query (whether a query I wrote or the default that's run when I open a table and go to the "Data" tab), the fact that the scrolling is jumpy makes it difficult to keep track of where I'm looking.

The horizontal scrolling is definitely the most frustrating for me personally. When trying to scroll sideways using the Apple Magic Mouse or the trackpad, it will usually jump 2-4 columns over, which can be frustrating.

I'd like to see smooth scrolling (horizontal and vertical) implemented. For an example, see how Postico scrolling works.

**Comment by serge-rider** [comment]
Agreed in general. Column-based scrolling makes much sense in some cases but having it as default (and the only) scrolling mode isn't good at all.

I've added smooth scrolling mode, And the preference option for it: 

![image](https://user-images.githubusercontent.com/6398845/67958952-0b89db80-fc09-11e9-9d1c-eaa5e006b8da.png)

It is enabled by default so smooth scrolling will be the default mode since 6.2.4.

**Comment by jim256** [comment]
Awesome news! Really excited about that. Thank you!

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by Pengchenghua** [comment]
> 已验证

WIN10 Function is invalid

**Comment by kseniiaguzeeva** [comment]
Thank you for the buf report. Investigating.

**Comment by kseniiaguzeeva** [comment]
Found out that the function is disabled by default in PostgreSQL (but it can be activated). Please tell which database do you use?
![7KwZTWxDD6](https://user-images.githubusercontent.com/51405061/68181368-15fcfa00-ffa8-11e9-9168-927d1d5f2833.png)

**Comment by serge-rider** [comment]
@kseniiaguzeeva it is not disabled for PostgreSQL. Perhaps it was changed for a particular connection?

**Comment by kseniiaguzeeva** [comment]
My mistake. Now I see, it is not set to default if Restore defaults.

**Comment by kseniiaguzeeva** [comment]
@Pengchenghua please reopen if you still reproduce it. In that case I kindly ask you to right more details.

**Comment by RecycleBin-X** [comment]
This function is not working for Mac version somehow

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce. Please be sure that the function is enabled (Properties>Editors>Data Editor>Presentation):
![image](https://user-images.githubusercontent.com/51405061/79346418-057b8300-7f3b-11ea-8b70-e80823dbe7e4.png)

Which DBeaver version do you use?

**Comment by RecycleBin-X** [comment]
> I cannot reproduce. Please be sure that the function is enabled (Properties>Editors>Data Editor>Presentation):
> ![image](https://user-images.githubusercontent.com/51405061/79346418-057b8300-7f3b-11ea-8b70-e80823dbe7e4.png)
> 
> Which DBeaver version do you use?

It's enabled. It's **unbelievably** lagging  when I scroll down the table.
DBeaver 7.0.2, macOS 10.15.4, MacBook Pro 16"
<img width="841" alt="image" src="https://user-images.githubusercontent.com/63602123/79348415-90727280-7f67-11ea-90ef-7ec31e1149d1.png">

**Comment by kseniiaguzeeva** [comment]
Smooth scrolling works in horizontal direction only. Could you please send me a video with this bug?

**Comment by RecycleBin-X** [comment]
> Smooth scrolling works in horizontal direction only. Could you please send me a video with this bug?

Sure. However may I request a feature for smooth scrolling vertically as well, it feels uncomfortable if I'm using touchpad to view the table.

**Comment by RecycleBin-X** [comment]
[Screen Recording 2020-04-15 at 10.46.53 PM.mov.zip](https://github.com/dbeaver/dbeaver/files/4481908/Screen.Recording.2020-04-15.at.10.46.53.PM.mov.zip)

It looks okay but actually it lags and does not follow my scrolling. Even though I stopped scrolling, I still need to wait it for a while until it stops. I'm not sure if this is macOS issue since I've got similar experience with Jetbrains IDEs.

**Comment by Evilart86** [comment]
Mac OS Catalina 10.15.6
Horizontal scroll through columns doesn't work smoothly
The options is enabled
Tried to disable and reenable doesn't help me
![image](https://user-images.githubusercontent.com/20624473/92328197-9d534800-f067-11ea-8a5c-1586c530471e.png)

**Comment by kseniiaguzeeva** [comment]
Looks like Mac OS issue. Please create a new ticket.

**Comment by andrewchouman** [comment]
@kseniiaguzeeva @Evilart86 I'm having the same issue. Was a ticket ever opened?

**Comment by kseniiaguzeeva** [comment]
Could you please create a new ticket for the bug?

**Comment by ooobii** [comment]
I created this issue #10184 thinking that it was not already implemented...

**Comment by patrickkidd** [comment]
This does not work on Big Sur. The option is checked and horizontal scrolling is still per-column when using the trackpad wheel. It is smooth when dragging the horizontal scrollbar but the scrollbar is not always visible and is so cumbersome to grab by making it appear and then grabbing it before it disappears that it is quite frustrating.
