### ISSUE TITLE
Filters ">" and "<" don't work in data grid for decimal numbers in column of 'float' type

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#6540]
Filters ">" and "<" don't work in data grid for decimal numbers in column of 'float' type
#### System information: 
- Operating system (distribution) and version Widows 10
- DBeaver version 6.1.5
- Additional extensions

#### Connection specification:
- Database name and version MySQL
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
Filters ">" and "<" don't work in data grid for decimal numbers in column of 'float' type
#### Steps to reproduce, if exist:
Try to filter ">" and "<" column of "float type" in data grid of DB Navigator

**Comment by serge-rider** [comment]
It is MySQL-specific issue: https://stackoverflow.com/questions/6135395/mysql-float-data-not-selecting-in-where-clause

> Generally, you should never check equality with floats
Agreed. And I don't think that we should fix it on DBeaver side right now.
