### ISSUE TITLE
Global filter of DB Navigator doesn't filter full database

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#6541]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 6.1.5
- Additional extensions

#### Connection specification:
- Database name and version MySQL
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
global filter of DB Navigator doesn't filter full database but only a folder where it was opened (for example only "tables" folder of a database)

**Comment by serge-rider** [comment]
Can't reproduce. Need more details.

**Comment by serge-rider** [comment]
I've reproduced this in a way (at some moment I wasn't able to disable global filter using navigator menu).
But we will fix this in the next version because fix may break some other filter-related features.

**Comment by kseniiaguzeeva** [comment]
1. Global filter filters properly if trees of folders weren't opened yet in DB Navigator after running DBeaver, 
2. If to make global filtering, then remove it: a) the global filter is removed properly if a tree of a filtered folder wasn't opened before filter removing; b) the global filter isn't removed if a tree of a filtered folder was opened before filter removing (but it works properly for a folder even with opened folder's tree if to use its context menu to remove Global filter).
3. Global filter doesn't filter properly, if trees of folders were opened in DB Navigator after running DBeaver (but it works properly for a folder with opened folder's tree if to use its context menu to open Global filter).

**Comment by kseniiaguzeeva** [comment]
Works with some nuances (pls see comment above)
