### ISSUE TITLE
Can't download 6.1.5 dmg file for MacOS

### ISSUE THREAD

**Issue by dorbae** [dbeaver/dbeaver#6548]
#### System information: 
- MacOS Mojave 10.14.6
- 6.1.5

#### Describe the problem you're observing:
I can't download **.dmg** installer file. Mainly because that file is not exists in **/files/6.1.5/** path.

#### Steps to reproduce, if exist:

<img width="953" alt="스크린샷 2019-08-19 11 21 43" src="https://user-images.githubusercontent.com/25657896/63235222-96e30a00-c273-11e9-83e4-6dbb83424a26.png">

<br />
 
<img width="1676" alt="스크린샷 2019-08-19 11 15 26" src="https://user-images.githubusercontent.com/25657896/63235232-9ea2ae80-c273-11e9-8d52-b846f66f7c20.png">

<br />

<img width="1394" alt="스크린샷 2019-08-19 11 14 49" src="https://user-images.githubusercontent.com/25657896/63235239-a19d9f00-c273-11e9-979f-fbea08ccf64b.png">

**Comment by LebronKodan** [comment]
Same issue, and only found 6.1.4 file in Release 6.1.5 assets.
![image](https://user-images.githubusercontent.com/2226464/63237851-2c7f9900-c276-11e9-95ba-0501d254bb9d.png)

**Comment by serge-rider** [comment]
Yep, there were some problems in automatic Mac build publishing. Now fixed.
Thanks for the bug report.
