### ISSUE TITLE
"Query execution was restricted by connection configuration"

### ISSUE THREAD

**Issue by ChthonVII** [dbeaver/dbeaver#6549]
#### System information: 
- Operating system (distribution) and version: Debian Buster
- DBeaver version: 6.1.5
- Additional extensions: none

#### Connection specification:
- Database name and version: SQL Server, some ancient version
- Driver name: "Microsoft JDBC Driver for SQL Server"
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: OpenVPN (but that should be transparent to DBeaver)

#### Describe the problem you're observing:
Attempt to run any query whatsoever, and get error: "Query execution was restricted by connection configuration."

#### Steps to reproduce, if exist:
Attempt to run any query whatsoever, and get error: "Query execution was restricted by connection configuration."

Suspect that issue may be related to the fact that my permissions for this connection are read-only. Has read-only been mistakenly redefined in v6.1.5 to be unable to do anything at all?

Workaround: Downgrade to v6.1.4

**Comment by heliomcp** [comment]
Have the same issue in connections I only have read only access.

**Comment by wolfgangley** [comment]
Same issue here - unable to use DBeaver after update from 6.1.4 to 6.1.5 when working with read-only databases.
SQL queries are no longer possible on such read-only databases which is a serious bug.

**Comment by SourabhKr** [comment]
Same issue in Exasol, reverted to 6.1.4 and everything started working fine.

**Comment by wolfgangley** [comment]
...and rolling back to 6.1.4 is not really an option as now the (re)installation of the GIT plugin fails due to missing dependency. That is a different problem but makes this bug report even more urgent as we do not have a workaround for people using the GIT plugin.

**Comment by alexlaedi** [comment]
I have exactly the same, apparently this only affects "read-only" connections..

**Comment by serge-rider** [comment]
Yes, it is a bug in connection config permissions config. Read-only connection restricts everything.
Workaround: disable read-only flag and set proper restrictions in "Edit permissions"dialog.

However, I think we will need to release hotfix 6.1.5 version as so many people were affected by this bug.

**Comment by carlosefr** [comment]
I'm using 6.1.5 and I still get this error. I had to use the workaround proposed for 6.1.4.

**Comment by jrogers22** [comment]
> #### System information:
> * Operating system (distribution) and version: Debian Buster
> * DBeaver version: 6.1.5
> * Additional extensions: none
> 
> #### Connection specification:
> * Database name and version: SQL Server, some ancient version
> * Driver name: "Microsoft JDBC Driver for SQL Server"
> * Do you use tunnels or proxies (SSH, SOCKS, etc)?: OpenVPN (but that should be transparent to DBeaver)
> 
> #### Describe the problem you're observing:
> Attempt to run any query whatsoever, and get error: "Query execution was restricted by connection configuration."
> 
> #### Steps to reproduce, if exist:
> Attempt to run any query whatsoever, and get error: "Query execution was restricted by connection configuration."
> 
> Suspect that issue may be related to the fact that my permissions for this connection are read-only. Has read-only been mistakenly redefined in v6.1.5 to be unable to do anything at all?
> 
> Workaround: Downgrade to v6.1.4

I'm having this issue at the moment. I'm not able to determine why. I can right-click "View Data" successfully for any table, but cannot use the script or query editor for the same tables.

**Comment by irzan2010** [comment]
Hi, I know I bump an old thread, but I do this workaround and it work for me:
- Right click on your database connection, and click on **Edit Connections**
- In left panel choose **General**, and uncheck **Read-only connection**, then click OK.
![image](https://github.com/dbeaver/dbeaver/assets/2494970/0e56796f-5183-4f57-ac5f-6ef2f8fe3c6a)

DBeaver will reconnect your database connection, and you can continue your work again.
I hope this will help anyone out there.

**Comment by elemle** [comment]
Same issue in Version 24.0.3.202404211624   This does not resolve it.

**Comment by marden** [comment]
Same issue in 24.1.0

**Comment by hans-tno** [comment]
For what it's worth: I had the same issue in 24.3.0 while colleagues working on the same database had no problem. I then changed the Connection Type (Settings > General) from Development to Test (or Production, both did the job) and voilà, can run queries. I doubt if this makes sense but it works for me.

**Comment by stevage** [comment]
I experience the same as @hans-tno . Changing back to development caused the issue again and going to test fixed it again. Very weird.
