### ISSUE TITLE
6.1.5 Goto Database Object stop working for Informix DataBase

### ISSUE THREAD

**Issue by amivanovano** [dbeaver/dbeaver#6551]
#### System information: 
- Client OS - Windows10
- DBeaver 6.1.5

#### Connection specification:
- Informix Dynamic Server 12.10.FC7
- Informix JDBC Driver for Informix Dynamic Server 4.50.JC1

![image](https://user-images.githubusercontent.com/28041955/63245484-fb4c9c00-c268-11e9-8f54-5cf6cdd9edef.png)

I never seen Stored Procedures from this point, but I always opened tab for Tables!
In DBEaver 6.1.5 I can't open Tables too.

**Comment by serge-rider** [comment]
It is the same bug as in #6555
Thank you for the bug report anyway
