### ISSUE TITLE
Unable to connect to database after latest release

### ISSUE THREAD

**Issue by johamm** [dbeaver/dbeaver#6552]
I've just updated dBeaver and now there's some MySQL databases I can no longer connect to. 

When I try, the following error shows:

![image](https://user-images.githubusercontent.com/2692644/63250667-0e10a200-c264-11e9-94e1-8475ea202292.png)

Here's the setup for the MySQL driver:

![image](https://user-images.githubusercontent.com/2692644/63250500-b5410980-c263-11e9-824c-b928b42b12f9.png)

When I go into "Download/Update", I see it says the MySQL driver files are missing so I've tried doing the "Force download / overwrite" bit but it doesn't seem to solve the issue.

![image](https://user-images.githubusercontent.com/2692644/63250578-df92c700-c263-11e9-9a77-c3924933698c.png)

I'm not entirely sure what to do to get the connection up and running again.

Can someone please help me here, possibly in the most lamest terms possible?  This is not my forte!

**Comment by feralg** [comment]
I have this problem too with connections by SSH Tunnel to MySQL server version 5.1.61. With MySQL server 5.7.27 it works OK.

I suspect it has to do with the driver update. I tried to downgrade but got no success. Any help would be appreciated.

**Comment by johamm** [comment]
Same - I can't downgrade either.  I've tried uninstalling dBeaver and going back to the old version but it's still showing the same issue.  I don't have the ability to upgrade the database to a newer version :(  Oddly enough my old version of MySQL Workbench still allows me access so for now I have a work around but I'd really like to continue using dBeaver as I much prefer it.

**Comment by serge-rider** [comment]
Yes, this happened after removing driver MySQL 5. It is a legacy driver bu MySQL server < 5.7 are still very widely used.
Thank you for the bug report.

We will release 6.1.5 hotfix version tomorrow. 
It will fix the problem with MySQL driver (and a couple of other problems)

**Comment by feralg** [comment]
I've installed the EA version today and now I have Version 6.1.5.201908211501 in Linux Mint 19.2. I'm still having this problem.

**Comment by TiZ-EX1** [comment]
6.1.5 is the stable release, not the early access release. Early access is 6.2.0.

**Comment by feralg** [comment]
Where do I get the fix? I made a Virtual Machine with LinuxMint xfce 19.2 and DBeaver 6.1.2, that I know worked before, and I'm still getting this error...

**Comment by feralg** [comment]
I got it! I have to manually change back the driver used in the connection. Thanks.
