### ISSUE TITLE
Can't connect to MySQL in 6.1.5 - time zone error

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#6553]
After I installed the latest DBeaver 6.1.5 I can no longer connect to any of my MySQL servers. The error says:

`The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.`

or:

`The server time zone value 'Central European Summer Time' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone `support.

I don't know exactly how I need to configure JDBC driver and I don't know why I'd have to. What's wrong? I'll have to revert to 6.1.4 for now.

**Comment by serge-rider** [comment]
Does it affect only new connection or old ones (created in dbeaver before 6.1.5) too?

**Comment by lemon-juice** [comment]
I didn't create any new connections so it all affects the old ones. I now reverted to 6.1.4 and the same error persists. It must be something with the new driver that DBeaver 6.1.5 prompted me to update, which I did.

**Comment by serge-rider** [comment]
I see. Well, you can set driver property serverTimeZone to value `UTC`.
We'll release hotfix version soon, thanks for the bug report.

**Comment by lemon-juice** [comment]
OK, I've set the propterty to UTC and the connection works, however datetime values are 2 hours off now. There's some unnecessary time zone conversion and AFAIK datetime columns in MySQL do not have any time zone associated with them.

**Comment by serge-rider** [comment]
Hotfix will return server timezone selector in the connection page so you can set proper value.
I believe it will be released before tomorrow.

**Comment by lemon-juice** [comment]
Okay, thanks!

**Comment by lemon-juice** [comment]
I still have this problem after upgrading to 6.2.0. I can't connect if the serverTimezone driver property is empty. There is the Server Time Zone field in the General connection settings but if I choose the time zone there then DBeaver will not connect.
