### ISSUE TITLE
H2GIS driver

### ISSUE THREAD

**Issue by ebocher** [dbeaver/dbeaver#6557]
We'd like to add a H2GIS (www.h2gis.org) driver to the dbeaver connection wizard. As H2 database, the aim is to offer two types of connection : H2GIS embedded and H2GIS server

Would the community be interested?

If yes, here, how we plan to proceed : 

- Create a plugin bundle as org.jkiss.dbeaver.ext.h2 -> org.jkiss.dbeaver.ext.h2gis
- Declare the required dependencies in dbeaver/plugins/org.jkiss.dbeaver.ext.generic/plugin.xml
- Find a way to initialize the H2GIS spatial functions (see http://www.h2gis.org/docs/1.5.0/quickstart/)

Best regards

**Comment by ebocher** [comment]
Based on H2 plugin, I added the H2GIS driver. Code is here : https://github.com/ebocher/dbeaver/tree/devel_h2gis/plugins/org.jkiss.dbeaver.ext.h2gis

The next step is to initialize the spatial functions with the following sql query : 

```sql
CREATE ALIAS IF NOT EXISTS H2GIS_SPATIAL FOR "org.h2gis.functions.factory.H2GISFunctions.load";
CALL H2GIS_SPATIAL();
```

The initialization of the functions must also be done when the connection to the database is tested.

I have some doubts about the method. 
Is it necessary to add a specific H2GIS dialect to load the spatial functions ?
Can you advise me or give me some hints ?
Regards

**Comment by serge-rider** [comment]
Looks good 👍 

However, does it really make sense to create new extension? If GIS data is the only difference between h2gis and regular h2 then it probably can be done in org.jkiss.dbeaver.ext.h2 extension. 
And add extra functionality there.
And of course new driver definition has to be added.

Do I understand correctly that showing GIS data (similarly to how it was done for PostgreSQL or MySQL)  is the main purpose of this new driver?

**Comment by ebocher** [comment]
Dear @serge-rider 
Thanks for the comment.

I am in favour of a specific extension.
H2GIS is not an "official" spatial extension as PostGIS for PG. Even if H2GIS is currently the most complete  spatial functions, some other extensions with a different architecture can be proposed by the community. So if you add it in the H2 extension you will have to add extra functionality for each of them.
Moreover (but I'm not sure about that), it seems that it will be interesting in the future to inject from the H2GISQLDialect some metadata in order to improve the user experience with DBbeaver UI.

Best

**Comment by ebocher** [comment]
Another argument in favour, I will be interested to add an entry "import data" when the user right-click in the database browser. I think about a custom import to load spatial data in an H2GIS database.

**Comment by ebocher** [comment]
@serge-rider 
I'd like to display H2GIS geometry (stored natively as JTS object) with the GIS component. Could you point me the class who is doing the work to detect the geometry datatype ?
Best

**Comment by ebocher** [comment]
@serge-rider 
I found some information in the PG driver. An interface GisAttribute, constant to map Geometry type. Do I need to extend all classes as for example PostgreTableColumnManager ?

**Comment by serge-rider** [comment]
@ebocher Probably we need to discuss details more deeply. Please write me on serge@jkiss.org

**Comment by ebocher** [comment]
@serge-rider 
+1

**Comment by uslss** [comment]
verified
