### ISSUE TITLE
Semi-Automatic Updates

### ISSUE THREAD

**Issue by Lonniebiz** [dbeaver/dbeaver#6558]
In DBeaver Version 6.1.5.201908191054, I have a suggestion that isn't urgent, but may be worthy of future consideration.

I update DBeaver each time a new version is released, and the process of updating is already simple, but the steps of updating could be automated.

Upon selecting "Update" from the help menu, these steps could be done:

1) Check for updates, if none exist, Tell the user they're up-to-date. If updates exist then:
2) Prompt the user to save any unsaved work.
3) Determine how DBeaver is currently installed (version, location of files, etc).
4) Download the correct version based on #3's info.
5) Auto-launch the installer and then immediately close DBeaver.

Again, this isn't urgent to me, and if it doesn't get done at all, that's ok. This is just a suggestion.

**Comment by serge-rider** [comment]
In 6.1.5 we already have new version download. But we don't do 3 and 5.

**Comment by jspeis** [comment]
Would be great to see this! (Came to request the same). I do think 3 & 5 would be nice to have if possible.

**Comment by nicoschl** [comment]
It would be great if everything could be a seamless update of the core of DBeaver plus any of the installed DBeaver plugins without having to do all the manual steps. I know DBeaver is based on Eclipse, where this functionality already exist, I don't need to download a new Eclipse everytime there is a new release or update to a plugin, Eclipse take care of everything.

You would make many people happy if this feature request and #6522 could be implemented.

**Comment by ethanherbertson** [comment]
Just upgraded to 6.3.4 (CE) and upon running the new version for the first time, I was automatically prompted to update/reinstall the plugin I had installed. Seems like progress!

**Comment by nicoschl** [comment]
How did you upgrade @ethanherbertson ? Did you install/extracted the new version "over" the existing version or into a new/clean directory?

I'm asking because I just upgraded to 6.3.5 (CE) by extracting the linux tar.gz package into a new directory and when I run dbeaver I don't get the prompt you are referring to. I'm running Arch Linux with KDE, but I doubt the OS or KDE have an influence here.

**Comment by ethanherbertson** [comment]
I used the Windows installer. I did not do a clean uninstall/reinstall.

**Comment by ShadelessFox** [comment]
Now it is possible to install an update directly from DBeaver on Windows and macOS.

Unfortunately, there is no an easy way to test this until the next version will come out.

**Comment by nicoschl** [comment]
> Now it is possible to install an update directly from DBeaver on Windows and macOS.

Does this include Linux? 

I'm no expert on how Eclipse does this, but if it works on Windows and macOS, why wouldn't it work on Linux?

**Comment by ShadelessFox** [comment]
> Does this include Linux?
> 
> I'm no expert on how Eclipse does this, but if it works on Windows and macOS, why wouldn't it work on Linux?

Short answer: currently no.

As of now, we stick to the simple approach to download the installation file and launch it manually. On Linux there's DEB and RPM packages which can be installed both using GUI application and terminal, and there's a bunch of such applications (including terminals) per each distro and so on. I hope this makes sense.

**Comment by Lonniebiz** [comment]
On Kubuntu 20.04, I installed Dbeaver using snap:
`sudo snap install dbeaver-ce`

Whoever is maintaining that snap is doing a good job. My system pretty much stays on the latest stable release without effort. When I see update notifications, I just ignore them (knowing I'll have that new version automatically soon enough).

**Comment by nicoschl** [comment]
@ShadelessFox Thanks for the explanation. I thought/was hoping that it uses the Eclipse way of updating itself.

**Comment by p91paul** [comment]
@Lonniebiz That would be, unless I'm mistaken, because the snap maintainer is the upstream itself and building snap is part of their release process :smile:

**Comment by p91paul** [comment]
For linuxes, the only sound way is to provide a deb/rpm repository instead of (or in addition of) a deb/rpm file. Should be a matter of creating the correct directory structure and metadata files, which isn't trivial, but not that difficult as well. The system will then take care of updates instead of the application.

For people installing from deb/rpm, running an installer or even the eclipse way of updating (which is possibly worse) are very unusual and shouldn't be applied.

People installing from zip, they are a different story though.

**Comment by kseniiaguzeeva** [comment]
verified (Mac and Win10 were tested)
