### ISSUE TITLE
Database Navigator lost folder's definition

### ISSUE THREAD

**Issue by mcunha98** [dbeaver/dbeaver#6559]
I updated from 6.1.2  to 6.1.5 and Database Navigator lost my folder's definition.
If necessary I give more details, but basically when create folders on database navigator to organize the connection, after migrate/upgrade to new version you'll lose all folders defintion

**Comment by serge-rider** [comment]
Could you check error log for any related errors https://github.com/dbeaver/dbeaver/wiki/Log-files ?

**Comment by serge-rider** [comment]
BTW you could re-run migration process:
1. Shutdown DBeaver
2. Delete 6.1.3+ workspace (DbeaverData directory in https://github.com/dbeaver/dbeaver/wiki/Workspace-Location)
3. Start DBeaver again

**Comment by mcunha98** [comment]
Probably I lost the time to get the log...the first log item that I had :

eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Mon Jul 22 10:41:18 BRT 2019
Error initializing Windows registry
