### ISSUE TITLE
Double info in General User Guide

### ISSUE THREAD

**Issue by Spoelle** [dbeaver/dbeaver#6562]
FYI
![image](https://user-images.githubusercontent.com/19902865/63330378-06b8c980-c334-11e9-9f49-d5811e6f3f5d.png)

![image](https://user-images.githubusercontent.com/19902865/63330366-01f41580-c334-11e9-9ebb-8316d049f9c2.png)

**Comment by serge-rider** [comment]
Thank you for the bug report. 
Fixed.
