### ISSUE TITLE
Allow connection username to be defined in dbeaver-data-sources.json

### ISSUE THREAD

**Issue by MannerMan** [dbeaver/dbeaver#6564]
**Is your feature request related to a problem? Please describe.**

I have written an application that generates dbeaver configuration files for the almost 200 different database servers in our company. We have different environments with various employees having access to different environments. The generator creates `.dbeaver-data-sources-<environment_name>.xml` files to accommodate this and it has worked out very well. The generator sets the correct username and ssl certificate config for every connection (which is different for every employee) but does not set passwords for connections due to security reasons, so the user is prompted for that.

Since dbeaver 6.1.3 with the new configuration format, it's not possible to define a username in the regular `.dbeaver-data-sources.json` files. Instead the username configuration has moved to an encrypted global credential storage (`credentials-config.json`). This make it very difficult to separate username configuration for separate environments, and separate generated username configuration from user-defined configuration. In fact, it appears very difficult to generate a compatible encrypted credential file outside of dbeaver.

**Describe the solution you'd like**

Allow username to be defined/read as a property of the regular `.dbeaver-data-sources.json` files. I understand that passwords are well suited to be put into the credentials storage, but it would be *very* useful for this use-case to at least be able to manually define the username for a connection in `.dbeaver-data-sources.json` files. It's, in my opinion a very tiny security trade-off considering the usefulness. DBeaver can still default to saving and loading usernames from the encrypted credential storage, but if not found look for username property in the plain configuration. This would regain the previous behavior but still default to best security.

**Describe alternatives you've considered**

I could skip the definition of username for generated connections, requiring the user to enter his or her full ldap username for every connection manually. Although this would probably cause us to use pgadmin instead.

**Additional context**

Somewhat related issues:
#6390 & #6415

**Comment by serge-rider** [comment]
This makes sense. And not too hard to implement

**Comment by serge-rider** [comment]
New JSON fields support added in data-sources.json file: `user` and `password`. They can be places inside `configuration` element 

```json
	"connections": {
		"postgresql-1294077257514--1782558860": {
			"provider": "postgresql",
			"driver": "postgres-jdbc",
			"name": "Postgre - sample",
			"save-password": true,
			"show-system-objects": true,
			"configuration": {
				"host": "127.0.0.1",
				"port": "5432",
				"database": "postgres",
				"url": "jdbc:postgresql://127.0.0.1:5432/postgres",
				"user": "user",
				"password": "password",
```

or inside network handler config (e.g. 

```json
"handlers": { 
  "ssh_tunnel": {
     "user": "user",
     "password": "password"
  }
}
```

**Comment by MannerMan** [comment]
Excellent, this will work out great for our use-case! Thank you kindly! :+1:

**Comment by uslss** [comment]
Verified
