### ISSUE TITLE
Data Editor - Some Filter icons disappeared

### ISSUE THREAD

**Issue by Spoelle** [dbeaver/dbeaver#6566]
System information: 
- WIN7 SP1
- DBeaver version 6.1.5

Connection specification:
- MS SQL Server 2012
- Microsoft JDBC Driver for SQL Server

Describe the problem you're observing:
Only "Save filter settings" icon/button available
Printscreen from documentation
![image](https://user-images.githubusercontent.com/19902865/63350670-2533ba80-c35e-11e9-85d3-6780a0351d8e.png)

Printscreen from version 6.1.5
![image](https://user-images.githubusercontent.com/19902865/63350721-3da3d500-c35e-11e9-8384-6cef2d784f9c.png)

**Comment by serge-rider** [comment]
Apply filter button has been moved into the filter text field.
Refresh button was combined with auto-refresh config button.
All command actions are still there but UI became more compact.

**Comment by Spoelle** [comment]
ok, Thanks for the explanation !!
