### ISSUE TITLE
Database specific commands such as IMPORT and EXPORT

### ISSUE THREAD

**Issue by markusschaeffer** [dbeaver/dbeaver#6567]
#### System information: 
- Operating system (distribution) and version: Win7
- DBeaver version: 6.0.1

#### Connection specification:
- Database: DB2 v11.1.4041.603
- Driver: DB2 for Linux/Unix/Windows driver db2jcc4

#### Describe your question:

Hello,

I am trying to execute database specific commands via the SQL editor in dbeaver.
In particular, I want to use commands such as IMPORT and EXPORT (I am using a DB2 DB). 

E.g.
```SQL
IMPORT FROM D:\test.csv of DEL 
MODIFIED BY coldelX09 chardel|
COMMITCOUNT 10000

INSERT INTO ADBA.TESTTABLE
(
	Field1, 
	Field2
);
```

Commands such as SELECT, UPDATE etc. are working fine but database specific/native commands always fail.

Is there any way to execute such database specific/native commands via the sql editor? I know that there is a GUI for importing and exporting but my needs exceed the ones available via the GUI.

**Comment by kai-morich** [comment]
What kind of error do you get?

**Comment by markusschaeffer** [comment]
SQL-Fehler [42601]: The statement was not processed because a character that is not supported in SQL statements was included in the SQL statement.

> What kind of error do you get?

SQL-Error[42601]: An unexpected token "IMPORT FROM 'D:\test.csv' of DEL  
MODIFIED" was found following "BEGIN-OF-STATEMENT".

**Comment by uslss** [comment]
Already implemented as Tools for DB2
