### ISSUE TITLE
ResultSet fetch size missing in toolbar

### ISSUE THREAD

**Issue by jmhg92** [dbeaver/dbeaver#6568]
#### System information: 
- OS: Windows 7x64
- DBeaver: 6.1.5.201908191349

#### Describe the problem you're observing:
The ResultSet fetch size limit is missing in the main toolbar after updating.
![image](https://user-images.githubusercontent.com/20491257/63355160-51821380-c32b-11e9-8010-2db79f18506c.png)

I have reset the UI settings and even deleted the workbench.xmi file, but to no avail. I know that I can set the limit under "Connection configuration > Result Sets > ResultSet fetch size" but this is quite inconvenient.

I tried editing the perspective in the "Customize Perspective" menu but I cannot find the correct option. I did notice that under "Tool Bar Visibility > Transaction monitor" there are 2 options that are grayed out:
![image](https://user-images.githubusercontent.com/20491257/63356117-dcafd900-c32c-11e9-8587-b0a9e1ee229d.png)

**Comment by serge-rider** [comment]
Since 6.1.0 version fetch size input has been moved to the bottom toolbar
![Screenshot 2019-08-21 at 12 02 47](https://user-images.githubusercontent.com/6398845/63418481-d0e71400-c40b-11e9-9d87-5ed4ee1941ad.png)

**Comment by jmhg92** [comment]
> Since 6.1.0 version fetch size input has been moved to the bottom toolbar
> ![Screenshot 2019-08-21 at 12 02 47](https://user-images.githubusercontent.com/6398845/63418481-d0e71400-c40b-11e9-9d87-5ed4ee1941ad.png)

OK, I see where it is now. However, I had version 6.1.4 before updating and the input was at the top; only after I updated to 6.1.5 did the location change to the bottom toolbar.
