### ISSUE TITLE
New Installations of dbeaver shows blank project explorer

### ISSUE THREAD

**Issue by sishgupta** [dbeaver/dbeaver#6569]
Since around the 6.0 release, a new installation of dbeaver will show no column headers or any items in the Project Explorer. As such not even the default "folders" for 'Bookmarks', 'ER Diagrams', or 'Scripts' will show.

The workaround is to click the "Configure columns" button and to select any extra column for display or to uncheck "DataSource" as a column.

After this, the headers for this view will show, and the items will list.

I have tested this on multiple windows 7 SP1 machines, and multiple Windows 10 machines (builds 1903,1809 and 1803), 
I first noticed the issue around the dbeaver 6.0 release and can say it is still an active issue with 6.1.4 & 6.1.5.
There are no plugins installed.

**Comment by serge-rider** [comment]
This happens on fresh DBeaver installations.
Thank you for the bug report.

**Comment by sishgupta** [comment]
Sorry it's not supposed to be this kind of "blank". It's incorrectly
blank...

**Comment by uslss** [comment]
Verified
