### ISSUE TITLE
Mysqldump cannot be found yet it's in the bin folder and works on a replica device. 

### ISSUE THREAD

**Issue by kerranm** [dbeaver/dbeaver#6574]
Running Dbeaver on Ubuntu 19.10. Mysqldump is sitting pretty in the /usr/bin folder and works fine from the temrinal.

However, DBeaver cannot find mysqldump from this folder when adding the bin folder as the home client folder. In fact, the contents of the bin folder (through the Dbeaver lense) is not the identical. ie: there are files missing, the main one being mysqldump. 

I have replicated this environment on another machine and Dbeaver works fine. 

Strange? Has anyone else experienced this issue?

**Comment by mrafidianto** [comment]
Yes, it happens too in ubuntu 18.04.

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
cannot reproduce it for now. If issue is still actual for you - feel free to reopen the ticket

**Comment by daviestobialex** [comment]
Just experience the same issue with DBeaver 7.1.2 on Linux Mint 20

**Comment by fbc** [comment]
Yea I went as far as installing the client but since dbeaver is running in the user account it does not have access to the utilities.
```
~$ sudo find / -name mysqldump
[sudo] password for xxx: 
/usr/bin/mysqldump
/snap/dbeaver-ce/93/usr/bin/mysqldump
/snap/dbeaver-ce/94/usr/bin/mysqldump

```

**Comment by fbc** [comment]
I'm going to uninstall my SNAP version and install the deb file from the website and see if that solves my problem.

**Comment by NDMann** [comment]
> I'm going to uninstall my SNAP version and install the deb file from the website and see if that solves my problem.

@fbc Did you solve the issue installing .deb?
