### ISSUE TITLE
Advanced Copy and Excel Extension missing rows

### ISSUE THREAD

**Issue by Jnb2387** [dbeaver/dbeaver#6575]
#### System information: 
- Operating system (distribution) and version
**Windows 10**
- DBeaver version
**6.1.4**
- Additional extensions
**Excel**

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Using Advanced copy HTML and Excel Dump do not copy all rows of data

#### Steps to reproduce, if exist:
Using Advanced Copy
Run query, right click data table highlight advanced copy select Copy AS HTML
Paste into another editor like notepad. Only certain rows are copied.

Using Excel Export Extension
Run query, click excel button on bottom of data table, excel opens but with missing rows of data

**Comment by p91paul** [comment]
both options only export selected cells. However, if you select only one cell it will export everything (at least, it should)
