### ISSUE TITLE
Inline edit and wrong primary key used

### ISSUE THREAD

**Issue by LukasBreit** [dbeaver/dbeaver#6578]
#### System information: 
- IBM I series 7.2
- DBeaver version 5.2.4

#### Connection specification:
- DB2

#### Describe your question:
We got some problems with the inline-edit function. We have tables that don't have a primary key. If inline editing is used we use all columns as primary key. But there are problems if the table strucutre is changed outside of DBeaver, because the <virtual-meta-data>-Tag in the .dbeaver-data-sources.xml isn't updated. So there are cases that the inline edit updates wrong records, because the old table structure, that is saved in the xml-file, is used. Is there a possiblity to prevent DBeaver saving the virtual meta data in the file, so each time when inline editing is done, DBeaver has to get the current primary key (all columns)?

Thanks for your help!

**Comment by serge-rider** [comment]
Agreed, this make sense. I think we can persist option "Use all columns" instead of actual column names.

**Comment by LukasBreit** [comment]
Isn't there a way to update the table strucutre before doing an inline edit? For example delete the virtual meta data-tag for the table or update the tag?

**Comment by serge-rider** [comment]
Sure. Right click on data editor->Logical Structure->Clear virtual unique key.

**Comment by serge-rider** [comment]
Will be included in 6.3.1

**Comment by uslss** [comment]
verified

**Comment by LukasBreit** [comment]
I have tested it now with the current version 7.0.5 and have seen that the virtual-meta-data-Tag is no longer used. But when changing the table structure (added a new column) outside of DBeaver and afterwards copying a row of the table and changing the new column value via inline edit, the two rows seem to have still the same primary key. Because when changing one of the two rows always bot are changed. 
Could you check this please? Thank you!
