### ISSUE TITLE
Query timing always 0ms

### ISSUE THREAD

**Issue by wlasiukk** [dbeaver/dbeaver#6579]
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version : 6.1.5
- Additional extensions : DBeaver Office Support, DevStyle Icon Designer , Darkest Dark theme

#### Connection specification:
- Database name and version : Any (tested on db2 and Hive)
- Driver name : na
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : na

#### Describe the problem you're observing:
in version 6.1.5 query timing show always 0ms
ie: "90 row(s) fetched - 0ms (+31ms)" when query takes about 10s

#### Steps to reproduce, if exist:
run any query on any connection

#### Include any warning/errors/backtraces from the logs

No errors in log.

**Comment by serge-rider** [comment]
Thanks you for the bug report

**Comment by kseniiaguzeeva** [comment]
Verified.
