### ISSUE TITLE
CSV write error Syntax error: Encountered " <NAME> "UPDATE "" at line 1, column 1.

### ISSUE THREAD

**Issue by Fischmuetze** [dbeaver/dbeaver#6580]
#### System information: 
- macOS mojave 10.14.6
- DBeaver version  DBeaver	6.1.5.201908191349	org.jkiss.dbeaver.core.product
- Java version: java.version=12.0.2

#### Connection specification:
- csv file 
- Driver name jdbc:relique:csv:/Users/steffen/Downloads
- connection settings successful

#### Describe the problem you're observing:
CSV structure will be successful detected and displayed
After changes in the data tab and pressing the save button at the bottom it will appear an error message. Problem is independently of the structure of the csv files

Error synchronizing data with database

Ursache:
SQL-Fehler: Syntax error: Encountered " <NAME> "UPDATE "" at line 1, column 1.
Was expecting:
    "SELECT" ...

Error synchronizing data with database

Ursache:
SQL-Fehler: Syntax error: Encountered " <NAME> "UPDATE "" at line 1, column 1.
Was expecting:
    "SELECT" ...
    

#### Steps to reproduce, if exist:
Small csv file test.csv
"Name","Vorname"
"Lehmann","Yvonne"
"Meier","Steffen"

a simple csv connection

**Comment by serge-rider** [comment]
CSV driver doesn't support source CSV files modification.
As far as I know most of the CSV drivers doesn't support this.

Workaround: import CSV to some relation table (e.g. SQLite). Edit table data. Export table as CSV.
