### ISSUE TITLE
Scaling issue on Gnome/Wayland

### ISSUE THREAD

**Issue by MindWithCake** [dbeaver/dbeaver#6581]
#### System information: 
- Operating system: Ubuntu 19.04
- Window manager: GNOME Shell 3.32.2 (Wayland)
- DBeaver version: 6.1.5
- Java version: openjdk version "11.0.4" 2019-07-16

On my system I have 2 monitors:
 - Screen 1 (main) is the laptop HiDPI screen. It has a scale factor of 150%, or else I can kiss my eyes goodbye
 - Screen 2 is an external HDMI monitor: same resolution as Screen 1, but not HiDPI. Scale factor is 100%
I use Wayland because it has support for different, non integral, scale factors on different monitors.

#### Describe the problem you're observing:
The problem is the same as #3975, which is supposed to have been resolved 8 months ago.
When launched from .desktop file (or gnome-terminal, which is started from a desktop file) some elements of the application have a 2x zoom.
![icon-scale](https://user-images.githubusercontent.com/10020251/63424007-c88fd880-c40d-11e9-9c6d-0eab6c11f8d4.png)
When launched from guake terminal the zoom is correct, but on Screen 2 the menu items are displayed at the height they would have on Screen 1
![menu-offset](https://user-images.githubusercontent.com/10020251/63424019-d0e81380-c40d-11e9-9297-1e85c5358973.png)
If I try launching with `--launcher.GTK_version 2` it just says:
> The Dbeaver executable launcher no longer supports running with GTK + 2.x. Continuing using GTK+ 3.x.

#### Include any warning/errors/backtraces from the logs

When launching from gnome terminal I have some warning which are not there in guake
> (DBeaver:31883): Gtk-CRITICAL **: 15:31:27.522: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

Otherwise the output is the same.

If I go to Installation Information -> Configuration there are some differences.
From guake:
> org.eclipse.swt.internal.deviceZoom=100
> org.eclipse.swt.internal.gdk.backend=x11
> GDK_BACKEND=x11
> GIO_LAUNCHED_DESKTOP_FILE=~/.config/autostart/guake.desktop
> GIO_LAUNCHED_DESKTOP_FILE_PID=3299

From gnome terminal:
> org.eclipse.swt.internal.deviceZoom=200
> DESKTOP_AUTOSTART_ID=10dd22b96992b46f39156636987999607000000028310019
> GJS_DEBUG_OUTPUT=stderr
> GJS_DEBUG_TOPICS=JS ERROR;JS LOG
> GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/fdb56996_49f2_4f00_8709_7b3d1d338eec
> GNOME_TERMINAL_SERVICE=:1.225

There are more differences about "Compare Support", which is [Active] with guake, [Starting] with terminal/launcher, but I don't think they are related to the issue.

As you can see, launching from gnome terminal/launcher sets the deviceZoom=200 (plus it doesn't set the X11 GDK backend, but I'm not sure it should).

**Comment by slokhorst** [comment]
Is this still an issue with 6.2.5? It did solve some other HiDPI bugs.

**Comment by MindWithCake** [comment]
Something has changed indeed, but now the problems on the slave monitor are different:

- if I maximize the windows it's twice as big as expected. In the first image you can see the result, the red dot is (approximately) where I have to click to open the "file" menu
- If I minimize the window and then manually resize it to fit the screen everything is correctly placed, but the text is quite clunky, like when you enlarge a screenshot, as in the second image.

![Schermata del 2019-11-19 13-42-36](https://user-images.githubusercontent.com/10020251/69149095-0b794f00-0ad6-11ea-8f24-5cda7ae5c39b.png)

![Schermata del 2019-11-19 13-45-57](https://user-images.githubusercontent.com/10020251/69148961-c35a2c80-0ad5-11ea-958b-96874a3834a1.png)


If you need more information feel free to ask: I'm a programmer, I'm not afraid of using command line options or building from source ^^

**Comment by bschofield** [comment]
I am also having this issue, also on Ubuntu (19.10) with Wayland.

In my case, I have a laptop display which is set to 100% scale, and two external 4k monitors which are set to 125% scale.

On the laptop (100% scale), everything works normally:

![image](https://user-images.githubusercontent.com/1534502/72603316-b3fa3280-3910-11ea-989d-60c7c2cde6b7.png)

If I drag the same window over to the 125% scaled screen, it looks like this:

![image](https://user-images.githubusercontent.com/1534502/72603875-c759cd80-3911-11ea-95b2-eb73cafcc0d4.png)

Had to take a photo of the screen for that one, because any window event, including trying to take a screenshot, changes the image.

After a redraw, the same window looks like this:

![image](https://user-images.githubusercontent.com/1534502/72603375-ce341080-3910-11ea-91c2-ea513aab0b5f.png)

**Comment by serge-rider** [comment]
This is a bug in Eclipse platform.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=553486
https://bugs.eclipse.org/bugs/show_bug.cgi?id=549504

We can't fix it from dbeaver side but I'll try to work closer with Eclipse team.

**Comment by bschofield** [comment]
The Eclipse team might have fixed this:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=541370
https://bugs.eclipse.org/bugs/show_bug.cgi?id=564097

@serge-rider Is that any use any use?

**Comment by serge-rider** [comment]
Probably this issue will be fixed after migration to Eclipse 2020-09 platform.
However 2020-09 has its own issues (e.g. problems with dark theme and Java 11 requirement).

**Comment by uslss** [comment]
is it still actual?

**Comment by ihabunek** [comment]
This is version 21.2.0.202108291732 running od Debian with SwayWM on Wayland with scaling set to 1.5.

![image](https://user-images.githubusercontent.com/482138/131388509-677c052b-0289-483f-a13f-3c5168e07850.png)

**Comment by emmanueltouzery** [comment]
I see the same thing as https://github.com/dbeaver/dbeaver/issues/6581#issuecomment-908592007 on fedora 34, also with sway.

**Comment by rom1dep** [comment]
same as https://github.com/dbeaver/dbeaver/issues/6581#issuecomment-908592007 on fedora with KDE

**Comment by clayrisser** [comment]
I'm having the same issue on Debian using SwayWM.

**Comment by Kaspary** [comment]
Same issue on Ubuntu with KDE!
![2021-12-27_15-20](https://user-images.githubusercontent.com/30197537/147497667-20164c2c-386c-4eef-b10b-e9c9038634c5.png)
![2021-12-27_15-22](https://user-images.githubusercontent.com/30197537/147497720-3b0e2258-9172-4e3d-a8d5-b2fbea51fe11.png)

**Comment by lapsha38** [comment]
u also can use workaround like this:

export GDK_BACKEND=x11
dbeaver-ce

**profit!**

or u can change .desktop file like this:
sudo vim '/usr/share/applications/dbeaver-ce.desktop'
and change exec line:
Exec=env GDK_BACKEND=x11 /usr/share/dbeaver-ce/dbeaver

**Comment by ihabunek** [comment]
@lapsha38 This does help, but scaling doesn't work well with apps running on xwayland. At least not on my setup (swaywm).

Here's dbeaver running on x11 with 2x scaling:

![image](https://user-images.githubusercontent.com/482138/148693157-4237bdff-2c0b-4c61-97b4-2887e3fb544f.png)

And here it is without scaling, zoomed to get approximately the same text size:

![image](https://user-images.githubusercontent.com/482138/148693194-ce664fbb-defb-4633-ab00-15788103919b.png)

Notice that the text is nowhere as sharp when using scaling. This does not happen with apps running natively on wayland.

**Comment by bohrasd** [comment]
Currently my workaround on Fedora 35 KDE wayland is using xwayland
I'm using the following flatpak permission settings
```
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;fallback-x11;ssh-auth;
devices=dri;
filesystems=home;

[Session Bus Policy]
org.freedesktop.Notifications=talk
org.freedesktop.FileManager1=talk

[Environment]
PATH=/app/clients/bin:/app/jre/bin:/usr/bin
GDK_DPI_SCALE=0.5
GDK_BACKEND=x11

```

**Comment by major-mayer** [comment]
I am also having some huge problems using KDE Wayland (5.24.4) and 125% fractional scaling on my 4K display.
I switched to the regular Adwaita GTK theme, but the layout is still completely broken and whenever you hover over some element, there appear some weird black boxes that block the visibility:

![grafik](https://user-images.githubusercontent.com/17907799/166324180-fdd21a7a-da8e-48ae-950f-b556046990f7.png)

**Comment by mystiquewolf** [comment]
Also experience this on KDE 5.24.5 with Wayland and 125% display scale. XWayland works OK.

**Comment by MindWithCake** [comment]
I just upgraded to Ubuntu 22.04.1 and tried a wayland session again. Many of the issues are gone now, there is just a little glitch left: icons loaded while the application is on the main screen (125% zoom) are of the correct size, while icons loaded when dbeaver is on the secondary screen (100% zoom) are zoomed. In the attached image the icons underlined in blue have been loaded on the main screen, the ones in red on the secondary.
On the main screen blue icons look blurry (like in the image), while on the secondary screen they are sharp as intended.
![Schermata del 2022-08-17 10-59-30](https://user-images.githubusercontent.com/10020251/185082026-c72c5a3b-bdf4-4784-96f9-c85561285c1b.png)

**Comment by rdslw** [comment]
This is not a "only wayland/gnome" issue. 

Dbeaver is (still after 5 yrs) completely f*cked up on pure X11 (using minimal i3), if user is having 4k display in hidpi mode (dpi:192). For clarity: only one monitor, no fancy setups.

In essence: this is hidpi on linux general dbeaver bug.

It's easily visible during startup, while inital welcoming modal window with dbeaver gfx & logo: its shown multiplied x4.

Pay attention to size of interface gfx elements are disproportionate smaller comparing to text:
![Screenshot 2022-10-14 21 48 55+02 00](https://user-images.githubusercontent.com/2506763/195930369-e86ea81a-b67e-49e4-96fc-a89979cf8284.png)

It is possible to use GDK_DPI_SCALE=0.5 -> then everything is ultra small (people use 4k in 2022 ;) ) while keeping perspective of UI. It looks okeish then but of course completely unusable due to ultra small size, pic below is around 1/10 of the monitor:
![Screenshot 2022-10-14 21 55 10+02 00](https://user-images.githubusercontent.com/2506763/195931183-c9fd74d9-64a3-43f2-b323-82b6d618243f.png)

**Comment by jpcartailler** [comment]
FWIW, there is a similar issue in Win10/DBeaver 22.3.0 (and prior as well), on a secondary monitor from a 4K laptop. Icons are just too small in navigation/menu bar, as well as in bottom row navigation in various contexts, in sidepanels (esp right one).

![image](https://user-images.githubusercontent.com/5258731/207308928-f40a7e7e-714d-443b-ac17-eb4dad10d791.png)

**Comment by Bryan2333** [comment]
Any updates on this?

**Comment by 12c76dc** [comment]
Some UI elements seems to be scaling like font, but other elements has issue:
![image](https://github.com/dbeaver/dbeaver/assets/88608064/5375cd39-0159-4ede-a693-f7bc91a415ea)

I have 4K screen with 200% scaling and 192 font DPI. Any idea how this could be fixed?

I'm using KDE Plasma 5 with X11 session. Using `GDK_DPI_SCALE` makes UI distorted

**Comment by MindWithCake** [comment]
After a long time not working with fractional zoom I tried again today, and everything is working fine. The only problem is an annoying popup asking me to "Restart for the zoom changes to take full effect?", but even if I don't restart there are no issues. I'm closing the issue.

My current environment is

- Arch Linux
- GNOME Shell 45.3
- DBeaver 23.3.3
- openjdk 21.0.2 2024-01-16

**Comment by matthieu-foucault** [comment]
@MindWithCake I wouldn't say this is resolved. The constant "Restart for the zoom changes to take full effect?" popup is very disruptive and making me look at alternatives for dbeaver

**Comment by major-mayer** [comment]
Yeah, the scaling issues (even worse on KDE) were also the main reason why I switched to Datagrip.

**Comment by normic** [comment]
I just recognized that there is an easy fix, at least for me. Just opening (or even moving to) my internal screen sets the resolution correctly. When moved to any other screen after that, all is fine.
