### ISSUE TITLE
SQL Server: change default value for existing column

### ISSUE THREAD

**Issue by mbianchetto** [dbeaver/dbeaver#6583]
#### System information: 
- Operating system (distribution) and version Microsoft Windows [Versione 10.0.17134.950]
- DBeaver version  6.1.5.201908191349
- Java version Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
- Additional extensions

#### Connection specification:
- Database name and version Microsoft SQL Server Standard (64-bit)
- Driver name Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
Updating table design, setting  a newid() value for unique idetifier column, (or a Getdate() default value for DateTime2 fields ... ) I have the error "Errore SQL [156] [S0001]: Incorrect syntax near the keyword 'DEFAULT'"

the generated sql  script is

ALTER TABLE TABLENAME ALTER COLUMN guidcolumn uniqueidentifier DEFAULT newid() NOT NULL GO

but (maybe) the correct command is like 

ALTER TABLE  TABLENAME ADD CONSTRAINT  	CONSTRAINTNAME  DEFAULT newid() FOR guidcolumn

I'm surely  wrong somehow

**Comment by serge-rider** [comment]
Yes, it has to be ADD CONSTRAINT.
Additionally we need to drop old default constraint if it exists

**Comment by uslss** [comment]
verified
