### ISSUE TITLE
Explain Plan display issue with Mariadb

### ISSUE THREAD

**Issue by davidbullado** [dbeaver/dbeaver#6584]
#### System information: 
- Linux 5.0.0-25-generic #26~18.04.1-Ubuntu  x86_64 x86_64 x86_64 GNU/Linux
- DBeaver Version 6.1.5.201908191349
- No additional extensions

#### Connection specification:
- Mariadb 10.3.16
- MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Explain plan is not correctly displayed. Only 3 columns are displayed.
#### Steps to reproduce, if exist:
Do an explain plan

**Comment by serge-rider** [comment]
I can't reproduce this. Could you post a screenshot?

**Comment by davidbullado** [comment]
Yes of course :
Normal result with a previous version of MariaDB:
![image](https://user-images.githubusercontent.com/10708817/63752012-b819ab00-c8b0-11e9-942f-cb9ffbdf6f89.png)
With a recent version:
![image](https://user-images.githubusercontent.com/10708817/63751902-8accfd00-c8b0-11e9-91f2-87216b88823e.png)

**Comment by uslss** [comment]
is it still actual?
it isn't reproducible for me on 6.3.0
![image](https://user-images.githubusercontent.com/31996417/69729422-5aa72b80-1137-11ea-8667-543db6a43465.png)

**Comment by uslss** [comment]
there is no update on ticket more than a month.
Ticket closed.
If issue still actual for you - feel free to reopen the ticket
