### ISSUE TITLE
Error on Bind Parameters

### ISSUE THREAD

**Issue by zarpelon** [dbeaver/dbeaver#6585]
#### System information: 
- Ubuntu 19.04
- DBeaver 6.1.5

#### Connection specification:
- Postgres
- PostgreSQL

#### Describe the problem you're observing:
When I execute a query that have parameters, the count of time is starting before that I click on OK button to execute the query

![Captura de Tela_selecionar área_20190821142313](https://user-images.githubusercontent.com/264762/63453556-4c9e8c00-c41f-11e9-9f8c-1d807f96d452.png)

**Comment by serge-rider** [comment]
In fact timing is reset after you set parameters. But yes, it looks quite strange.

**Comment by serge-rider** [comment]
Fixed.

**Comment by uslss** [comment]
verified
