### ISSUE TITLE
Database Navigator empty on first start of DBeaver 6.1.5 after upgrade

### ISSUE THREAD

**Issue by rschr** [dbeaver/dbeaver#6586]
This is on DBeaver 6.15, no extensions, on Linux Mint 19.2 Cinnamon. There are no errors in the logs, only three warnings which seem to be unrelated:

```
Warning: NLS unused message: dialog_text_view_open_editor in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: dialog_text_view_open_editor_tip in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: IDEApplication_workspaceInUse_Cancel in: org.eclipse.ui.internal.ide.messages
```

As the title suggests, I started DBeaver and it came up as a clean slate; none of my connections/databases are there. "Re-running the migration process" as suggested in #6559 (which does not seem related as there is an error accessing the Windows registry mentioned) didn't help.

I've deactivated the PPA and manually reverted to 6.1.2 for now.

**Comment by serge-rider** [comment]
I'm kinda reproduced this. It is similar to #6599

**Comment by serge-rider** [comment]
Please follow workaround described in #6599 (after 6.2 release).

Although I'm not sure that it is 100% the same bug (if you use single config file then it is different). In any case I found a case when new config files aren't created after migration. Hopefully it will solve the problem.

**Comment by rschr** [comment]
Yes – after installing DBeaver 6.2.0 EA, starting it, closing it, removing the DBeaverData directory and starting it again, it asked about the migration, which I confirmed, and then the connections indeed were migrated. Thanks!

**Comment by kseniiaguzeeva** [comment]
Similar with 6599
