### ISSUE TITLE
Cannot View Multiple Results Sets Returned From Stored Proc With Teradata Driver

### ISSUE THREAD

**Issue by coomesy** [dbeaver/dbeaver#6589]
#### System information: 
Mac OSX
DBeaver 6.5

#### Connection specification:
- Teradata
- Teradata Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Cannot view multiple result sets coming back from a Teradata Java Proc
#### Steps to reproduce, if exist:
Create a Teradata Java Proc(might can rep with just a normal TD proc as well) that returns multiple result sets.
Call the proc from DBeaver
Notice that only one result set is able to be viewed

No logs or warnings

**Comment by serge-rider** [comment]
Please try to enable multiple resultsets support in Teradata driver configuration:
![image](https://user-images.githubusercontent.com/6398845/63640344-b335db00-c6a7-11e9-8d4d-fc4bedf88e59.png)

If it will work fine then we'll enable this parameter by default (so please write here about results).

**Comment by serge-rider** [comment]
@coomesy any update?
