### ISSUE TITLE
Convert keyword case NOT working

### ISSUE THREAD

**Issue by GiannisDimitriou** [dbeaver/dbeaver#6591]
#### System information: 
- Windows 10
- 6.1.5

#### Connection specification:
- Postgres

#### Describe the problem you're observing:
The "Convert keyword case" feature is not working unless you set the following option to 'UPPER'
Database->Editors->SQL Editor->SQL formatting->Keyword case 
#### Steps to reproduce, if exist:
Enable "Convert keyword case" and set the Database->Editors->SQL Editor->SQL formatting->Keyword case  to 'Default'

**Comment by serge-rider** [comment]
By default PostgreSQL uses lower case for identifiers and keywords.
Does it work?

**Comment by GiannisDimitriou** [comment]
Hi @serge-rider  it does work only if you set both settings I mentioned above. 
Which I found confusing since there is no message/note to tell you that these settings are binded together.
From my understanding "Convert keyword case" is a flag that controls whether the "Keyword case" option is enabled or not, which I found as an extra unneccessary step. Setting the "Keyword case" to your desired value should work without needing any extra setting to be enabled IMO.

**Comment by pyrocks** [comment]
@serge-rider I agree with @GiannisDimitriou  that it is indeed confusing. I couldn't understand why "Convert keyword case" doesn't work on postgres - had no idea I also had to change SQL formatting->Keyword case.
These setting should either be unified with 4 options (Upper, Lower, DB Default, Do not convert) or be placed next to each other.

**Comment by michal-bartak** [comment]
I was just notified by my co-worker that the automatic upper case stopped working after installing the most recent version (he had some 'ancient' version - probably year or two old - on the previous notebook, though).

Simply entering 'select' it doesn't turn into SELECT

The editor is connected to db, while writing. I have both settings set:
![image](https://user-images.githubusercontent.com/7868445/202146644-6f261dab-3044-4b4a-a7dc-c1e521cb6104.png)
![image](https://user-images.githubusercontent.com/7868445/202146697-4c57547e-b81d-4f0e-8b5b-f16a7aa5c242.png)


Thus I wouldn't call it an enhancement. It's a bug IMO

with regards

**Comment by jserafim** [comment]
I'm having the same problem described by @michalk-k , the automatic upper case is not working in version 22.2.4.202211061524

It was working before, in version 22.0.3.202204170718 , so it is definitely a bug.

It would also be great to have these settings unified with 4 options, as described by @pyrocks .

**Comment by pyrocks** [comment]
I confirm. It was working correctly in the previous version 22.2.3 - but stopped working on 2.2.4 without changing any setting.

**Comment by pyrocks** [comment]
@uslss don't know if you guys saw it because it's a revived old one. just in case...

**Comment by michal-bartak** [comment]
Seems v22.2.5 fixes automatic keywords conversion to uppercase

**Comment by E1izabeth** [comment]
Does this issue still actual for the latest DBeaver version?

**Comment by michal-bartak** [comment]
Unless you ask OP, I've confirmed that it has been fixed (See my post above your ones). It still works properly in 22.3.1 ;)

**Comment by E1izabeth** [comment]
Thank you for reply. I'll close this issue then.
