### ISSUE TITLE
Result Sets menu missing 6.1.4

### ISSUE THREAD

**Issue by geanmatheus** [dbeaver/dbeaver#6593]
#### System information: 
Windows 10 Pro

#### Connection specification:
All

#### Describe your question:
According to the title, the menu is gone. See attached image
![print](https://user-images.githubusercontent.com/18244115/63519771-e6bb0e80-c4c9-11e9-82e1-294fe05016e1.png)

**Comment by serge-rider** [comment]
It is not in Database->Editors->Data

**Comment by geanmatheus** [comment]
Ok, Thanks
