### ISSUE TITLE
Clarify the Display of Large Integers in Arrays

### ISSUE THREAD

**Issue by kdonavin** [dbeaver/dbeaver#6597]
# Problem

If query results contain arrays of large integer values, the display of commas to separate 1000s places makes for an ambiguous representation of integer elements in the array. Simple example:

```
select array [1100,2200] as a;
```

Produces a result set that looks like this in DBeaver:

![Screen Shot 2019-08-22 at 5 37 24 PM](https://user-images.githubusercontent.com/16674499/63556855-9496df00-c503-11e9-8eea-bde02b33951d.png)

Is that the integers "1,100" and "1,200", or the integers "1", "100", "2", and "200"? Not possible to tell without copying and pasting the cell.

# Proposed Solution

* Use semi-colons between integers: `[1,100;2,000]`. This is how I would handle ambiguous commas in an English sentence:

> My favorite cities are Chicago, IL; San Francisco, CA; and Salt Lake City, UT.

**Describe alternatives you've considered**

Some countries use periods to separate thousands places, but I feel this would be too confusing with actual floating decimal points. For example `[1.101, 1.202]`: Are these decimal point values or integers?

**Comment by serge-rider** [comment]
I can't reproduce the problem with formatting (in arrays numbers are not formatted with group dividers, at least in PostgreSQL). 
What is your database?

**Comment by uslss** [comment]
ticket closed. there is no update on ticket more than a month

**Comment by kdonavin** [comment]
@serge-rider Hi, Sorry I failed to respond. DB is Hadoop 3 and the driver is JDBC Presto 0.192. 

Interesting to know that this is not a universal problem with different SQL flavors.

**Comment by t4ko** [comment]
I landed on this page while looking for a solution to the same problem, for anyone in the same situation you can disable grouping or change the locale in Preferences > Editors > Data Editor > Data Formats
