### ISSUE TITLE
F3 - cuts naming if long script names are used

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#6598]
## System information: 
- Operating system (distribution) and version: windows 10 1903
- DBeaver version: 6.1.5
- Additional extensions: git

#### Describe the problem you're observing:
F3 new script window and having folders causes naming of scripts to be stripped off. The Names are not resized or resizable since they are static in the view. See screenshot below.

#### Steps to reproduce, if exist:
Create folder hierachy in the Scripts for the project you have.
Press F3

![image](https://user-images.githubusercontent.com/383031/63571407-660b1980-c580-11e9-9069-477d983f0251.png)

The script "this_is_a_long_named_script" is cut off in the naming and there is no way to get to see the name.

**Comment by serge-rider** [comment]
It is a bug in tree expand routine.
Thanks for the bug report

**Comment by kseniiaguzeeva** [comment]
Verified
