### ISSUE TITLE
Loosing connections stored in Database navigator

### ISSUE THREAD

**Issue by herbinator** [dbeaver/dbeaver#6599]
I have 2 dbeaver-data-sources.xml files. After upgrading to 6.1.4 and also 6.1.5 it looks ok. I create a new connection. Closing dbeaver and opening again makes me lose all connections which used to be in the second dbeaver-data-sources-Extra.xml file. Deleting the .dbeaver file works to get everything back but off course without the newly created connection.

**Comment by serge-rider** [comment]
Yep. We need to add support of multiple config files for the new configuration format.

**Comment by serge-rider** [comment]
In order to make a proper migration just delete DBeaverData folder and re-run DBeaver (6.2+). It will migrate all your old configuration files and save them in the new format (json).

**Comment by blocka** [comment]
This did not work. My old connections do not appear after migrating.

**Comment by E1izabeth** [comment]
@blocka it may be connected with #17305
Which DBeaver version did you use before last update?

**Comment by blocka** [comment]
Before this I used dbeaver 4...not exactly sure what version.
Unlike in that issue, I don't have any json file to speak of...just the xml file.

On top of this, when I restart dbeaver, I lose all my connections. I don't see any data-sources.json (but I do see a credentials-config.json)

**Comment by E1izabeth** [comment]
@blocka, thank you for quick answer. Do you have any error in the [log](https://github.com/dbeaver/dbeaver/wiki/Log-files) file?
Maybe it seems like described in #17300?

**Comment by blocka** [comment]
I see this:
```eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Aug 09 09:28:42 EDT 2022
Error loading datasource config from .local/share/DBeaverData/workspace6/General/.dbeaver-data-sources.xml
```

**Comment by E1izabeth** [comment]
@blocka could you send me your `.dbeaver-data-sources.xml`?

**Comment by blocka** [comment]
Renaming `.dbeaver-data-sources.xml` to `data-sources.json` fixed the problem of losing the connections on restart. Is there a tool that can manually convert data-sources.xml to the new format?
