### ISSUE TITLE
Copy script from preview changes does not work

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#6600]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 6.1.5 (6.1.4 also affected)
- Additional extensions: N/A

#### Connection specification:
- Database name and version: Oracle 11
- Driver name: ojdbc8
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Button copy from the "preview changes" window does nothing; instead, it should be copying changes to the clipboard

#### Steps to reproduce, if exist:

1. Open a table editor
2. Edit some cells
3. Click on "Script"
4. Changes are previewed in form of insert/update/delete statements
5. Click copy
6. Script is *not* copied to the clipboard

#### Include any warning/errors/backtraces from the logs
Nothing is written to the logs while doing steps 3/4/5 above.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by kseniiaguzeeva** [comment]
Verified
