### ISSUE TITLE
Keys keyboard binding for Ctrl+6 ≠ Ctrl+Num6..?

### ISSUE THREAD

**Issue by spinjector** [dbeaver/dbeaver#6602]
I found a couple small issues with the keys binding. This is a Windows 7 system on a Dell M6800 laptop, with DB v5.2.5.201811181655.

The default binding to maximize/restore the results panel is Ctrl+Shift+6. This works ok. But...if I use Ctrl+Shift+Num6 (on the number keypad), it doesn't work. It does something else, je ne sais quoi. 

This seems odd, because _Ctrl+6 and Ctrl+Num6 both work the same_. Perhaps the combination of Ctrl+Shift causes the Num keys to throw different keyboard codes..?

The other issue is perhaps just a typo..? In the keys editor window, if I search for 'SQL', it seems all the items for category 'SQL Editor' have a 'When' description as follows. It seems to differ greatly from all the others:

%context.org.jkiss.dbeaver.ui.editors.sql.script.name.

See below:

![2019-08-23_08-10-22](https://user-images.githubusercontent.com/21039987/63593260-a4550880-c581-11e9-92bc-77c639be87ad.png)

**Comment by serge-rider** [comment]
Well, numpad works as numbers only when NumLock is enabled. In this case it works just fine. Otherwise num keys work as cursor keys.

In regards to glitch with key bindings. I believe we've fixed this problem long time ago, just upgrade to some newer version.
