### ISSUE TITLE
DBeaver shows wrong execution time for stored procedure

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#6603]
DBeaver - Version 6.1.4 CE
Operating System: Windows 10
JDBC Driver: mssql-jdbc 7.0.0.jre10
Database: Microsoft SQL Server Database

@serge-rider While working on bugs, I was able to notice that Dbeaver is always giving back wrong execution time for any stored procedure. This seems to be a bug.

**Comment by serge-rider** [comment]
This bug was fixed in 6.1.5

**Comment by serge-rider** [comment]
Please reopen if it still present
