### ISSUE TITLE
Show field content in Value tab in hex format

### ISSUE THREAD

**Issue by MocniMax** [dbeaver/dbeaver#6604]
Hello.

It would be nice to have ability to show hex value of any field in Result Set Value tab, similar to one in field edit popup. In that way revising possible invalid data will be much faster than pressing Shift-Enter for each record/field. 

That will be especially useful for debugging when different character set data is presented and to show values of all non printable characters.

Regards

**Comment by serge-rider** [comment]
I'm not sure about "any field" (because it is quite unclear how to convert numbers/datetimes/etc into bytes) but it makes sense for strings.

**Comment by MocniMax** [comment]
Yes, I meant any string field. Idea is to be able to debug string content easily.
Regards

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/65536269-c557a300-df0b-11e9-947b-cb8a8f60dbeb.png)

**Comment by MocniMax** [comment]
Excellent!
Will try it as soon as it will be released.

**Comment by kseniiaguzeeva** [comment]
Verified
