### ISSUE TITLE
Escaped quote taken as closing quote in editor

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#6606]
In PostgreSQL, if I try to write a query that has text with escaped characters, and put there an escaped quote, it will take the statement as having the escaped quote being the closing quote, and then the actual closing quote has a new opening quote. As such, text after it will show as string with unmatched closing.
![incorrect_quote_closing](https://user-images.githubusercontent.com/11860098/63600329-0a667d80-c5cc-11e9-8cfb-1b135dce3984.png)

**Comment by serge-rider** [comment]
By default single quote can be escaped by double-single-quote combination. As far as I know PostgreSQL fails to parse constructs like `'\''` (at least in my test environment).

So you need to use something like `c1 ~ E''''` instead of backslash escaping.

**Comment by david-cortes** [comment]
> By default single quote can be escaped by double-single-quote combination. As far as I know PostgreSQL fails to parse constructs like `'\''` (at least in my test environment).
> 
> So you need to use something like `c1 ~ E''''` instead of backslash escaping.

That's not correct, `E'\''` (when prefixed with `E`) is valid and will escape the quote. In newer PostgreSQL versions I think `'\''` is also valid depending on configuration of defaults. If I run the query in the picture it executes correctly, despite the coloring.

**Comment by serge-rider** [comment]
Ok, I see. Well, it breaks SQL standard (in a way) but we still can try to support this c-style strings escape too.
It will require to define new Eclipse PatternRule with multiple escape characters support. Not a big deal but still requires some effort. Moving to 6.2.1.

**Comment by uslss** [comment]
verified
