### ISSUE TITLE
Cannot execute queries with double dollar quoting

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#6608]
**Steps to reproduce:**
* Connect to some PostgreSQL DB
* Open an editor tab
* Write a query with double-dollar quoting, e.g.
```sql
select $$Dianne's horse$$::varchar
```
* Run the query by pressing `Ctrl` + `Enter`, or selecting it and then running it

**Expected results:** should execute the query and return an unnamed column with text `Dianne's horse` in the same way as other SQL interfacers would.

**Actual results:** does not execute the query, throws a dialog for variable selection.

**Comment by serge-rider** [comment]
Yes, it is a bug in SQL parser. It evaluates PostgreSQLs-specific double-dollar params incorrectly.

Workaround: 
- Disable SQL parameters in preferences.
- Add space after first double-dollar quote

**Comment by serge-rider** [comment]
Main problem with dollar quotes is that we can't show them as strings. Because they are widely used for functions/procedures definition.

Showing whole function body as a solid string is very inconvenient. Even pgAdmin can't handle dollar quotes properly. We need to make some trick here..

**Comment by serge-rider** [comment]
We will use following workaround:
- Double dollar quotes will be treated as string quotes: $$Some ' string$$
- Dollar quotes with tag (e.g. $function$) will be treated as block toggles. All text inside will be evaluated as SQL.

This is not 100% compliant with PG syntax rules. But it lets to quote strings and to edit functions as SQL at the same time.
The only problem I see now: if you will use dollar quotes with tag and put strings (not SQL) inside (e.g. `$x$Dianne's horse$x$`) then dbeaver won't be able to parse it correctly.

**Comment by mlt** [comment]
We can have it all! My patch [can exclude](https://github.com/mlt/dbeaver/blob/f777085d1f8cbb3a74544cf73d8a111bd9151eb5/plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/syntax/DollarQuoteRule.java#L48) some combinations (function for now) while making it flexible to use `$whatever$`

![](https://user-images.githubusercontent.com/413384/54484909-62d76900-483d-11e9-810f-60ae01a11d1d.png)

**Comment by uslss** [comment]
verified
