### ISSUE TITLE
Cannot list anything with connection to PostgreSQL server v7.4.8 with new 'PostgreSQL (Old)' driver 

### ISSUE THREAD

**Issue by EricBrunel** [dbeaver/dbeaver#6609]
#### System information: 
- Linux openSuse 15.0
- DBeaver v6.1.5

#### Connection specification:
- Database server: PostgreSQL v7.4.6
- Driver: PostgreSQL (Old)
- Connection through an IPSec VPN

#### Problem description
I used a connection to this old PostgreSQL server with the 'PostgreSQL' driver and it could connect OK. I had issues due to features unsupported in this database server version, it was a bit annoying, but usable. So when I saw a new PostgreSQL driver for pre-v8.x was available, I recreated the connection using this driver.

The connection can be created without problem and a 'test connection' works and displays the correct server version. But when I try to expand any node under 'information_schema', 'pg_catalog' or 'public' in the connection tree, I get an error:
`SQL Error [42704]: ERROR: type "e" does not exist`
and nothing is listed. So I cannot even see the tables in the database, making the connection unusable.

**Comment by serge-rider** [comment]
Please post error stacktrace (you can get it in the error log (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by EricBrunel** [comment]
Here is the full log, since there seems to be several stacktraces that can be of interest:
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/3544821/dbeaver.log)
Note that my former connection using the 'PostgreSQL' driver still exists, so the first stacktraces are caused by this connection and are not relevant. I'm guessing the relevant ones start at line 364 in the log (message issued at 09:27:51.183).

**Comment by uslss** [comment]
hi @EricBrunel ,
does this issue still reproducible for you against recent version?

**Comment by EricBrunel** [comment]
Yes, it is. I'm actually no more using DBeaver on a regular basis, but I just downloaded version 7.0.1 of the Community Edition and I tried again: I'm getting the exact same error.

**Comment by serge-rider** [comment]
@EricBrunel thanks for testing. Could you send this error stacktrace?

**Comment by EricBrunel** [comment]
I got the debug log, but I'm not sure how to interpret it. Note that I still have the 2 connections defined: one with the newest PostgreSQL driver and one with the "legacy" one.
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4403352/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Looks like a bug in PostgreSQL driver.
Could you try some old driver version, e.g. 9.2?

![image](https://user-images.githubusercontent.com/6398845/77939624-2055c280-72c0-11ea-9d08-bf3d799b68a2.png)

**Comment by EricBrunel** [comment]
And you're right! I changed the driver version to 9.2-1004-jdbc41 and it seems to work without problem now. Thank you!

**Comment by serge-rider** [comment]
Great)
