### ISSUE TITLE
DBeaver 6.1.5: Filters in results Grids are not available

### ISSUE THREAD

**Issue by avo15** [dbeaver/dbeaver#6612]
Results Tab Grid does not show any values in Column filters in v 6.1.5 while it works in prior versions

**Comment by serge-rider** [comment]
Please clarify - what filters do you mean? Some screenshot would be very helpful

**Comment by serge-rider** [comment]
It is a bug in 6.1.5. Thanks for the bug report

**Comment by uslss** [comment]
verified

**Comment by guyfromwy** [comment]
This remains an issue in 6.2 and 6.2.1. I would have reported it in 6.2, but I thought I saw something say it was going to be in whatever was scheduled to be released on Sept 19th.
Thanks
