### ISSUE TITLE
diselecting rows in the result panel through ctrl+alt_click

### ISSUE THREAD

**Issue by ZeusDeus** [dbeaver/dbeaver#6613]
In the issue "Feature question: selecting rows in the result panel #5988" the option to select the same columns in different row through ctrl+alt+click was implemented. It works as intended, but when diselecting using the same keys, only one cell is diselected (the same as ctrl+click). Please make it consistent with the option to diselect several cells through ctrl+alt+click. Thank you

**Comment by serge-rider** [comment]
Good point. See fix in the next version.

**Comment by kseniiaguzeeva** [comment]
Verified.
