### ISSUE TITLE
Detached editor, on delete script - is applied on previous editor

### ISSUE THREAD

**Issue by cerebel** [dbeaver/dbeaver#6616]
#### System information: 
w7x64(as custom workspace)
dbeaver ce: 6.1.5(as clean workspace), 6.1.3 (with some custom workspace)
jdk1.8.0_212_x64

#### Describe the problem you're observing:
detached script, on delete, is not  deleted the selected script
#### Steps to reproduce, if exist:

1 start dbeaver  
  by example " dbeaver.exe -data "%USERPROFILE%\\.dbeaver4_ws_6.1.5_test"
2. create 2 new sql editors with "ctrl+]"
3. right click on "Script-1" (the second editor) - in popUp menu -> "detach"
4. on detached editor, right click on "Script-1" - in popUp menu -> "delete this script"
  as result -> dbeaver prompt deletion of "Script.sql" - this is wrong
 notes, if there are some additional clicks of focus/select windows - the bug can't be reproduced

#### Include any warning/errors/backtraces from the logs
no error in logs

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report. It still exists in 6.3.2

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
