### ISSUE TITLE
SQLite encrypted (cipher) driver

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6617]
We need to add SQLite Crypt (Cipher) driver in the default DBeaver configuration.
We'll use https://github.com/Willena/sqlite-jdbc-crypt

**Comment by uslss** [comment]
verified

**Comment by serge-rider** [comment]
It works but it still don't support auto-configuration. This makes this driver senseless in many cases.
We need a special UI.

**Comment by tz182736** [comment]
How can I configure this to open SQLite cipher database ?
where to put in passphrase ??
https://github.com/Willena/sqlite-jdbc-crypt

**Comment by thecodingcod** [comment]
Hi  @tz182736  , In case you're still interested
I've created a detailed gist with steps I've tried to make it work for me
https://gist.github.com/thecodingcod/a3987ddde8892d1a6bda8bd94febb7d0

**Comment by gshanbhag525** [comment]
> Hi @tz182736 , In case you're still interested I've created a detailed gist with steps I've tried to make it work for me https://gist.github.com/thecodingcod/a3987ddde8892d1a6bda8bd94febb7d0

I have compiled more simpler version which doesnot need us download the drivers locally to disk.
https://gist.github.com/gshanbhag525/01210cf12d76ee82dbb4692ac1e0cc44
