### ISSUE TITLE
New connection is created at inactive project

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6621]
#### System information: 
- Operating system (distribution) and version win 10x64
- DBeaver version 6.2.0 EA

#### Describe the problem you're observing:
New connection is created in inactive project after changing of active project.
#### Steps to reproduce, if exist:
1. Change active project
2. Create New connection - check created connection
![inactive project](https://user-images.githubusercontent.com/31996417/63654467-2e1ff400-c783-11e9-8d31-d5056c25c9ca.gif)

**Comment by serge-rider** [comment]
It is not a bug. It is a feature added in the recent version.

We use current database navigator selection to determine current project (active or inactive - doesn't matter). And you can see project name on the first page of connection wizard.

**Comment by uslss** [comment]
Closed
Created issue #6627
