### ISSUE TITLE
Field disappear from treeview when move other field 

### ISSUE THREAD

**Issue by mcunha98** [dbeaver/dbeaver#6625]
I created a new column on mysql database, the field is the last one.
After create I moved it to desired place, but I notice that other field disappear from treeview (in list view I see the field, but in treeview not).

Example :
https://i.postimg.cc/G3G64J1Y/screenshot-558.png

In this case, the field **nr_notafiscal**  stay on list but not in treeview when I start the move operation

**Comment by serge-rider** [comment]
I can't reproduce column disappear. 
But I see the bug in table editor - actual column move isn't visualized (but reflected in the navigator tree ).

**Comment by kseniiaguzeeva** [comment]
Verified
