### ISSUE TITLE
can't type backtick/backquote in sql editor

### ISSUE THREAD

**Issue by miellaby** [dbeaver/dbeaver#6626]
#### System information: 
- Windows 10 with AZERTY keyboard and French Locales
- dBeaver 6.1.5
- drivers Mysql and Postgres

#### Connection specification:
- Mysql 5.6
- mysql
-  No tunnel, no proxy

#### Describe the problem you're observing:
When in an SQL editor, I can't type backquote (`) in my query. Very problematic when typing mysql tables names.

Please note that it's possible to copy & paste a backquote and it works. So it's more a question of an ignored key sequence.

Also note that on a french keyboard, the backquote is obtained through a Dead_key (cf. https://en.wikipedia.org/wiki/Dead_key )

#### Steps to reproduce, if exist:
Dbeaver on Windows with Azerty keyboard > open SQL editor > type backquote (`) > no backquote

#### Include any warning/errors/backtraces from the logs
no log

**Comment by miellaby** [comment]
FYI the bug is actually on the whole application. Event input entries in settings dialogs refuse to accept backquotes.

**Comment by uslss** [comment]
cannot reproduce the issue, is it still actual?

**Comment by miellaby** [comment]
It is. I now recommend french developer to install and use another windows keyboard map like http://planetozh.com/projects/azertyck/

**Comment by miellaby** [comment]
I also heard that it's a running Eclipse bug which has never been fixed. Need a source for this one.

**Comment by miellaby** [comment]
FYI, this bug fixed itself some times ago (sorry I didn't notice when exactly).
