### ISSUE TITLE
Query result sets output quickly

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6629]
Query result set output result set speed is slow, not as fast as in HUE platform
- Operating system (distribution) and version
- DBeaver version 6.20 -ea
- Database name and version  HIVE
![image](https://user-images.githubusercontent.com/26621087/63754294-342ee580-c8e7-11e9-87ae-a3a8e3132de0.png)

**Comment by serge-rider** [comment]
We will need much more details to investigate any performance issues. there can be hundreds of different reasons.
Note that DBeaver used Hive JDBC driver which has its own issues/config parameters.
 I'm not sure what HUE platform is and how exactly it works with Hive.
