### ISSUE TITLE
Enquoting selected text deletes it instead

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#6630]
**Steps to reproduce:**
* Open an SQL editor.
* Write some select statement.
* Double-click some non-quoted word from the select statement.
* Press quote character.

**Expected behavior:** should enclose in quotes the text that was selected.

**Actual behavior:** replaces the text with empty quotes.
![dbeaver_enquote](https://user-images.githubusercontent.com/11860098/63765055-ec9d5f00-c8d0-11e9-9f08-161abb5b0a31.gif)

**Comment by serge-rider** [comment]
It is not a bug, most of text editors behave this way.
But this could be a good feature.

**Comment by JuanLH** [comment]
Hi, which branch I have to clone to get that case?

**Comment by david-cortes** [comment]
> Hi, which branch I have to clone to get that case?

Happens on the release version, so I guess all of them would have this behavior.

**Comment by p91paul** [comment]
@JuanLH AFAIK, most work is done on the devel branch

**Comment by JuanLH** [comment]
Hi, I'm trying to run the proyect for find the bug but i'm facing errors for missing dependencies, i  guess.
I did the following:

- Clone the repo  [devel] branch.
- Added existing maven proyect and i searched the git repo downloaded.
- Updated maven proyect.

And i have this
![Error for dependencies](https://user-images.githubusercontent.com/10179221/64491507-3d994580-d237-11e9-849d-971c6878c7a0.png)

**Comment by JuanLH** [comment]
Ok, I found [https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse](url) I fix that error, I was the plugins

**Comment by JuanLH** [comment]
I don't have the same behavior in the SQL editor, look:
![enquoting dbeaver 2](https://user-images.githubusercontent.com/10179221/64493411-ef437100-d24d-11e9-928b-30514e3a0771.gif)
I cloned the devel branch. 

And I don't have options for connections, maybe I have to include some data, right?
![connections](https://user-images.githubusercontent.com/10179221/64493457-71339a00-d24e-11e9-8569-1f6ecc1b40c1.gif)

**Comment by david-cortes** [comment]
> I don't have the same behavior in the SQL editor, look:
> ![enquoting dbeaver 2](https://user-images.githubusercontent.com/10179221/64493411-ef437100-d24d-11e9-928b-30514e3a0771.gif)
> I cloned the devel branch.
> 
> And I don't have options for connections, maybe I have to include some data, right?
> ![connections](https://user-images.githubusercontent.com/10179221/64493457-71339a00-d24e-11e9-8569-1f6ecc1b40c1.gif)

I don't think there's any need to have data. But how are you producing that video? are you pressing quote character key after selecting the text?

**Comment by JuanLH** [comment]
Ok, I was my bad, it's work fine, now I'm looking for the code of SQL Editor.
finding in this **project/module** | 2019-09-08 22:01:45.075 - > Start org.jkiss.dbeaver.ui.editors.sql [1.0.16.qualifier] 
and putting a breakpoint in SQLEditor class constructor when I press F3 or click on the option for open a SQL editor the program **stop**, ok I continue going forward but when the program invokes this method in Method class the followings elements don't find, look:
![Debug source not found](https://user-images.githubusercontent.com/10179221/64500319-b37acc80-d28a-11e9-9f40-c89a9cf9a876.gif)

Well, I want to **keep going forward debugging** until I get the code that opens the panel (i think)  with the editor to get the events of this editor.

**Comment by uslss** [comment]
verified

**Comment by OverDrone** [comment]
I'm sorry for resurrecting old thread but I couldn't find any other info on this feature. I'm sure some guys happy to have this feature, but I want it disabled and I can't find anywhere in settings how to do this. Can anybody help me?

**Comment by glockenbach** [comment]
Hello! How is this features configured? I have different behaviour depending on keyboard input layout. I would like both input layouts to work the same.
