### ISSUE TITLE
I see  different fonts I have installed in my OS

### ISSUE THREAD

**Issue by PetroGromovo** [dbeaver/dbeaver#6631]
I see that after installation DBeaver has different fonts I have installed in my OS : https://imgur.com/a/4jiBJYi
I have found “Preferences”->"Colors and Fonts ", but I failed to apply my system fonts to the app :
https://imgur.com/a/qsDNJjV
even clicking on “Use system Font” button I do not see my system fonts applied to this app.
How can I apply my system fonts? Maybe configuring some config files?

Thanks!

**Comment by serge-rider** [comment]
This is controlled by Eclipse platform, it detect current system font and use it as default font for application. Perhaps there is a bug in system font detect function.
But we can't fix this.

Did you try to set your font manually in DBeaver?

**Comment by uslss** [comment]
there is no update on issue for a long time.
ticket closed
