### ISSUE TITLE
Optional fully qualified names in object editor generated SQL

### ISSUE THREAD

**Issue by samiconductor** [dbeaver/dbeaver#6633]
**Is your feature request related to a problem? Please describe.**
When you save changes made in the object editor, altering a table for example, you can click save and copy the SQL instead of persisting it. We often use this SQL in our Flyway scripts and have to be sure to remove the schema names from the generated SQL to avoid errors in other environments.

**Describe the solution you'd like**
It would be nice if the object editor save dialog that lets you copy SQL before it is persisted had optional fully qualified names like the generate SQL dialog (SELECT, INSERT, UPDATE, etc.).

**Describe alternatives you've considered**
We simply remove the schema names after the fact. But we forget sometimes and have to fix it in test. Not a big deal.

**Additional context**
[Flyway](https://flywaydb.org/) is used for db migrations. I'm sure you're familiar.

DBeaver is awesome! Thanks!

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/67852495-8e356c80-fb1d-11e9-8c0b-e0110ce7dc52.png)

**Comment by uslss** [comment]
Verified for Oracle, PostgreSQL, MySQL
