### ISSUE TITLE
URL Template field from User defined drivers are disregarded

### ISSUE THREAD

**Issue by nledenyi** [dbeaver/dbeaver#6634]
#### System information: 
- Operating system (distribution) and version: Win 10 Pro
- DBeaver version: Version 6.1.5.201908191349
- Additional extensions: none

#### Connection specification:
- Database name and version: Greenplum 4.3.31 but it looks to me that the issue is wider
- Driver name: user defined
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSL

#### Describe the problem you're observing:
When a user either creates a new or modifies an existing driver, the Driver Manager's dialog allows one to modify the URL Template. However, that is going to be disregarded and not used at all. As a result of that, if the custom driver what the user loaded requires a different connection URL then the connection will fail

#### Steps to reproduce, if exist:
I believe the issue is widespread and could be reproduced with any drivers which require a different connection URL compared to the ones built into DBeaver. However, the specific use case I was facing with is the following:
- download the Pivotal Greenplum JDBC driver from here: http://gpdb.docs.pivotal.io/5140/datadirect/datadirect_jdbc.html
- create a new user defined driver whereas the previously downloaded jar file is loaded and the URL Template is defined as follows: jdbc:pivotal:greenplum://{host}:{port};DatabaseName={database} (see screenshot below)
- select driver type as Greenplum
- fill in the rest of the fields for the driver, then create a new connection using this driver
- create a new connection using this new driver, and upon connecting it will fail because it is using the default URL template (see screenshot below) for the parent Greenplum driver type and not the one defined in the user defined or modified driver 

#### Include any warning/errors/backtraces from the logs
Bad URL: jdbc:postgresql://dev-gp-xxx:5432/xxx

#### Workarounds tried:
- i tried editing the URL directly in data-sources.json (while DBeaver was closed). Unfortunately it still did not pick it up correctly
- tried leaving the URL Template field empty, to see if it prompts to provide one while creating the connection. Unfortunately it didn't and still failed
- created an another driver with Driver Type=Generic. That was able connect, however in that case I'm losing quite a lot of GUI features which are otherwise working fine 

#### Screenshots:

![dbeaver1](https://user-images.githubusercontent.com/12593338/63783047-9dfdbe00-c8ec-11e9-80d8-8cf7a98ef234.png)
![dbeaver2](https://user-images.githubusercontent.com/12593338/63783055-a1914500-c8ec-11e9-801a-89aab27ca052.png)

#### Similar issues: 

I believe this one might be related:
https://github.com/dbeaver/dbeaver/issues/5516

However, I decided to open this issue still because:
- I think the issue is wider and not specific to one given driver type as opposed to what the other issue was focusing on
- I wanted to include more details and tried workaround in my ticket
- I'm hoping that it is a relatively easy fix and feel the old issue likely would have slipped under the radar

**Comment by serge-rider** [comment]
This happens because you set driver type to Greenplum. In this case DBeaver generates connection URL internally (as for other PG and PG-derived databases).
I've fix driver config so now you can edit the URL.

**Comment by uslss** [comment]
verified

**Comment by nledenyi** [comment]
Hi @serge-rider,

Thanks for the fix. Tested it using the 6.2 Early Access. Works now, however it doesn't take effect if enable SSL under the SSL tab, I have to go into the Driver properties and set encryptionMethod to SSL and validateServerCertificate to false in order to connect using SSL. Not sure if this is expected or something that could be improved.

![dbeaver3](https://user-images.githubusercontent.com/12593338/64098310-d7a84c00-cd66-11e9-963a-32529a451fce.png)
![dbeaver4](https://user-images.githubusercontent.com/12593338/64098314-da0aa600-cd66-11e9-8114-35f1288779a3.png)
