### ISSUE TITLE
Unsupported operation code: 97

### ISSUE THREAD

**Issue by FIFernandes** [dbeaver/dbeaver#6635]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version- 6.1.5

#### Connection specification:
- Firebird 3.0 

#### Describe your question:
I have an application that connects to the Firebird database, I use an encryption plugin from the site below and I have not problems.
https://ib-aid.com/en/firebird-encryption-plugin-framework/

When I try to connect using DBBeaver I get  Unsupported operation code: 97

**Comment by mrotteveel** [comment]
Receiving this error would mean that you're using Jaybird 3.0.3 or earlier. Upgrade to Jaybird 3.0.4 or higher (at this time, 3.0.8 is the latest available version).

**Comment by FIFernandes** [comment]
So pressing the "Download/update" does not work or upgrade to jaybird 4.0.0 

https://www.firebirdsql.org/en/jdbc-driver/

**Comment by mrotteveel** [comment]
@FIFernandes That doesn't seem directly related to this issue. However, it could have to do with #8294.
