### ISSUE TITLE
After multiple temporary tables are created with HIVE, temporary tables cannot be found

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6637]
After creating multiple temporary tables, HIVE cannot find temporary tables, export EXCEL, and prompt error boxes；
Thank you for reporting an issue.
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
错误
Wed Aug 28 13:54:26 CST 2019
SQL 错误 [10001] [42S02]: Error while compiling statement: FAILED: SemanticException [Error 10001]: Line 112:2 Table not found 'temp_visit'

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/26621087/63829266-9fd28a80-c99b-11e9-8f08-c41cde2756e0.png)

**Comment by serge-rider** [comment]
This happened because data transfer handler didn't reuse source execution context.
See fix in the next version.

Workaround: disable "Open separate connection for each editor" option.

**Comment by uslss** [comment]
verified
