### ISSUE TITLE
Ctrl+Insert does not copy selection from script editor

### ISSUE THREAD

**Issue by AnrDaemon** [dbeaver/dbeaver#6638]
#### System information: 
- Windows 7 Pro/RUS SP1
- DBeaver 6.5.1

#### Describe the problem you're observing:
Hitting `Ctrl+Insert` does nothing, text in clipboard does not change.

#### Steps to reproduce, if exist:
Open script editor, enter text, select, hit `Ctrl+Ins`.

**Comment by serge-rider** [comment]
Can't reproduce.
Try to reset workspace UI settings (sometimes keyboard shortcuts become messy, especially after number of version upgrades). 
https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings

**Comment by AnrDaemon** [comment]
It's a fresh installation, and new workspace.
I have no idea, why, but it started to behave after another reboot.
Perhaps, and environmental problem.
