### ISSUE TITLE
How to save and then import a project with a diagram?

### ISSUE THREAD

**Issue by electrotype** [dbeaver/dbeaver#6639]
DBeaver 6.0.0
SQL Server

We'd like to share a DBeaver project in Git so developers can update it when they change the schema. The project contains a diagram of the tables.

When I save the project from my DBeaver instance and another develop try to import it using "`File Open Projects from File System...`", the diagram is *empty*. I found that this is because the `id` of the `data-source` element from the `data-schema.erd` file is not the one it should be on another DBeaver instance...

Is there a way to share a project so the diagram will work fine for everybody? How can we all have the same `id` for `data-source`?

**Comment by uslss** [comment]
is it still actual?

**Comment by electrotype** [comment]
@uslss if you are asking me, I haven't checked in a long time... But my guess is that the issue is still there.

**Comment by marcelo-lara** [comment]
I get this message when trying to open an .ERD exported file 
```
org.jkiss.dbeaver.DBException: Can not get file from editor input org.eclipse.ui.ide.FileStoreEditorInput@f1d3f64c
	at org.jkiss.dbeaver.erd.ui.editor.ERDEditorStandalone.loadContentFromFile(ERDEditorStandalone.java:192)
	at org.jkiss.dbeaver.erd.ui.editor.ERDEditorStandalone$1.evaluate(ERDEditorStandalone.java:151)
	at org.jkiss.dbeaver.erd.ui.editor.ERDEditorStandalone$1.evaluate(ERDEditorStandalone.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
The steps I'm doing:
1. on Windows: Open DBeaver, open a database and save the ERD as `file.erd`
2. on Ubuntu: Open the `file.erd`  with DBeaver.

any ideas?

**Comment by NickVeld** [comment]
Version 22.2.3.202210231354 Protable installation Windows 11. The bug is still actual.

**Comment by E1izabeth** [comment]
Does it still actual for the latest DBeaver version? We improved the process of resolving data source id for diagrams in #20800

**Comment by electrotype** [comment]
I can't confirm, sorry. I guess the issue can be closed and someone will ask to open it again if it is required.

Thank you for the support.
