### ISSUE TITLE
bigquery driver not updated

### ISSUE THREAD

**Issue by yiga2** [dbeaver/dbeaver#6641]
I am on 6.1.5 CE
BigQuery JDBC 1.21 is out at https://cloud.google.com/bigquery/providers/simba-drivers/ but cannot figure out how to download through the driver manager.
I can obviously download and add manually but like to use the manager to pick a version.

**Comment by serge-rider** [comment]
Unfortunately it is not possible to list all supported versions in case of direct file download.
Anyway, I'll update Bigquery driver version in the next release, thank for the report.

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/64020134-823b2780-cb39-11e9-80be-3edbb973e266.png)
