### ISSUE TITLE
Right click data cell -> Set to default (current time) is BROKEN

### ISSUE THREAD

**Issue by maclof** [dbeaver/dbeaver#6642]
#### System information: 
- Operating system (distribution) and version - Windows 10 Pro
- DBeaver version - 6.1.5
- Additional extensions - N/A

#### Connection specification:
- Database name and version - MySQL 5.8
- Driver name - MySQL for 4.1+ (com.mysql.jdbc.Driver)
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  - No

#### Describe the problem you're observing:
Whenever I right click a timestamp cell and click "Set to default (current time)" it uses the following date format: "yyyy-MM-dd-HH.mm.ss Z" which is *not* what it should be using.

The database connection does not use any "Data formatting" overrides, and the global timestamp format is set to use "yyyy-MM-dd HH:mm:ss".

If we change the global timestamp format to something slightly different, e.g. "yyyy-MM-dd HH:mm:ss Z" it then uses the new format correctly, but if we then edit the format back to "yyyy-MM-dd HH:mm:ss" it will ignore this and go back to using it's original format ""yyyy-MM-dd-HH.mm.ss Z"

Please fix this or advise how we're supposed to go back to using the normal MySQL timestamp format without having to have overrides for each connection?

#### Steps to reproduce, if exist:
As above.

**Comment by serge-rider** [comment]
You can disable native MySQL date formatting:

![image](https://user-images.githubusercontent.com/6398845/63939022-85b1ae80-ca66-11e9-8bfb-e939ce2247fc.png)

It was set by default for MySQL as an experiment. I think we'll disable it in the next version.

**Comment by maclof** [comment]
@serge-rider that would make sense, only if we had the "Use native date/time format" option selected on the global data formats, but we do not, nor do we use any per connection overrides.

I assume it is currently ignoring the global "Use native date/time format" option and just defaulting to MySQL native format?

![](https://i.imgur.com/zUoXAcD.png)

**Comment by serge-rider** [comment]
Yes exactly, default value was changed only for MySQL drivers. Just open settings for any MySQL connection and you will see it.

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by duSupport** [comment]
6.2版本出现了更严重的问题，使用默认的yyyy-MM-dd HH:mm:ss根本没有用，必须自己修改成别的格式，哪怕是在后面加个空格，否则使用的就是 yyyy-MM-dd-HH.mm.ss Z 格式
