### ISSUE TITLE
Prompted to download Postgres driver every time start DBeaver

### ISSUE THREAD

**Issue by daevidvincent** [dbeaver/dbeaver#6644]
Every time I start Windows 10 DBeaver 6.1.5 (I think it started around v6.1.2 or so) I am prompted to download postgres drivers. I check "force" and the divers appear to be in the directory, but it doesn't matter.

![image](https://user-images.githubusercontent.com/20825058/63898456-edf08980-c9ad-11e9-87c4-113d5168ab23.png)

![image](https://user-images.githubusercontent.com/20825058/63898475-fe086900-c9ad-11e9-920a-0e2412ed4b35.png)

![image](https://user-images.githubusercontent.com/20825058/63898500-137d9300-c9ae-11e9-977c-ab6275d2d8f0.png)

**Comment by serge-rider** [comment]
This is a bug in a recent dbeaver version (related to the new workspace format).
I believe I've fixed it a few days ago. 
Could you check it in Early Access version (https://dbeaver.io/files/ea) ?

**Comment by daevidvincent** [comment]
I'll try again, but it blows up trying to install....
![image](https://user-images.githubusercontent.com/20825058/63969450-be498c00-ca56-11e9-8992-f0ae693aa836.png)

**Comment by daevidvincent** [comment]
I can confirm, that when I started DBeaver, and connected to my local development database (as I always do), I did NOT get the driver prompt. I will continue to use this 6.2 version and report back if I notice anything different. Thank you!

**Comment by denis-pujdak-adm-it** [comment]
Had the same problem but after the upgrade 6.2.1 the problem dissapeared.
Thanks guys.
