### ISSUE TITLE
UI: column position not changed: Properties, click icon Move object up

### ISSUE THREAD

**Issue by erlangp** [dbeaver/dbeaver#6645]
#### System information: 
- Windows 8
- DBeaver version 6.1.5

#### Problem:
Column position not changed after click icon Move object up

#### Steps to reproduce:
Properties, click icon Move object up or click icon Move object down

**Comment by erlangp** [comment]
https://imgur.com/a/FoAX8VE

**Comment by serge-rider** [comment]
It is changed but this change is not visible in the table editor.
This bug was fixed in #6625

Thanks for the bug report anyway.

**Comment by erlangp** [comment]
Thanks!
