### ISSUE TITLE
Very slow SQL assist with Oracle

### ISSUE THREAD

**Issue by romgerman** [dbeaver/dbeaver#6646]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro N 1803 17134.950
- DBeaver version: 6.1.5.201908191349

#### Connection specification:
- Database name and version: Oracle 11g Enterprise Edition Release 11.2.0.4.0

#### Describe your question:
After Ctrl+Space i wait around 30 seconds and then get notification "Datasource was invalidated" and then only after 30 seconds i get results. What can be the problem?

**Comment by serge-rider** [comment]
Did you try to play with Oracle performance settings:
![image](https://user-images.githubusercontent.com/6398845/63934422-9577c580-ca5b-11e9-92fb-517b9df8ee0e.png)

**Comment by romgerman** [comment]
Yes. They do not help at all.

**Comment by serge-rider** [comment]
Could you send error or/and debug log to see whether there any errors occur during auto-completion?
Also please check query manager view (main menu Window->Show View->Query manager). You can enable viewing all internal queries DBeaver execute to read system info. If some of these queries are executing for too long time - please post them.

**Comment by uslss** [comment]
there is no update on ticket for a long time.
ticket closed
