### ISSUE TITLE
Comments disappear

### ISSUE THREAD

**Issue by zombiesbyte** [dbeaver/dbeaver#6647]
When creating new columns (in my case 23 new columns on a new table) I had added comments to most fields. When saving the comments did not appear. Come to think of it, the SQL didn't include any comments.

I'm connecting to a Postgres database. Window 10 DBeaver 6.1.5

**Comment by zombiesbyte** [comment]
Additional: I've just tried adding in a comment after the fact and there are no issues there

**Comment by serge-rider** [comment]
Thank you for the bug report.
This issue happens only with new table (if you add columns or comments for existing table then it works)

**Comment by kseniiaguzeeva** [comment]
Verified
