### ISSUE TITLE
Please make program window title more useful

### ISSUE THREAD

**Issue by AnrDaemon** [dbeaver/dbeaver#6648]
![20190829-161913-](https://user-images.githubusercontent.com/6532485/63943778-0083c500-ca79-11e9-9226-ed2af4b9ea90.png)

As you can imagine, it is not really clear, which database is opened in which instance of the program.
Please make program title a little bit more useful.

P.S.
No, opening two databases in the same window is even less useful.
Switching is slow, relation of a given connection to the specific tab is not really apparent, and overall, the experience is frustrating.

**Comment by serge-rider** [comment]
You can configure it here:
![image](https://user-images.githubusercontent.com/6398845/63944914-c4e5fc80-ca72-11e9-9578-612f867623be.png)

**Comment by AnrDaemon** [comment]
Would be more apparent, if there was some filler.
And it does not update active window title, that also confused me, when I was looking there initially.
