### ISSUE TITLE
Grouping panel : SQL Error when using space in column name

### ISSUE THREAD

**Issue by Doxxxxxx** [dbeaver/dbeaver#6650]
#### System information: 
- Operating system: Windows 10 64bits fr
- DBeaver version: 6.1.5.201908181949
- Additional extensions: DBeaver Office Support

#### Connection specification:
- Database: SQL Server 11.0.2100.60 & SQLite
- Driver name: Microsoft JDBC Driver for SQL Server & SQLite JDBC driver by Taro L. Saito (extension of Zentus driver)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
When I add a column containing a white space in the grouping panel, I get the following error in the panel:
`SQL Error [155] [S0001]: 'space' n'est pas une option GROUP BY reconnue.`
and it displays the sql request that was used by the grouping panel:
```
SELECT [col with space], COUNT(*) FROM (
select 
 a.AR_Ref as [sku],
 a.AR_Stat04 as [col_without_space],
 a.AR_Stat04 as [col with space]
from dbo.F_ARTICLE a) src
GROUP BY col with space
HAVING COUNT(*) > 1
```
You can see that the brackets in group by parameters are missing (_col with space_).
Same problem if I use quotes instead of brackets for column names. 
Same problem with SQLite connexion

#### Steps to reproduce, if exist:

1. Execute initial request:
```
select 
 a.AR_Ref as [sku],
 a.AR_Stat04 as [col_without_space],
 a.AR_Stat04 as [col with space]
from dbo.F_ARTICLE a
```

2. Drag the column [col with space] in grouping panel
-> Error

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by Doxxxxxx** [comment]
Thanks you for the fix and your great software !
I will wait the release for testing.

**Comment by uslss** [comment]
verified
