### ISSUE TITLE
Sorting in results grid not working when clicking column header

### ISSUE THREAD

**Issue by jim256** [dbeaver/dbeaver#6652]
#### System information: 
- 10.14.6 (18G87)
- DBeaver version 6.1.5
- Additional extensions: Excel / Office extension

#### Connection specification:
- Snowflake
- Snowflake JDBC 3.8.8
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
After running a query, clicking a column and sorting by it has no effect on the order of the records. The sort arrow in the header changes, but the order of the data does not.

#### Steps to reproduce, if exist:
Run a query. Click the column header of a column to sort by that column.

Not sure if it's related to https://github.com/dbeaver/dbeaver/issues/3407 or not

**Comment by serge-rider** [comment]
I can't reproduce this.
Do you mean that sorting doesn't work at all, in all tables, all databases?

**Comment by Pengchenghua** [comment]
> 我无法重现这一点。
> 你是说在所有表，所有数据库中排序都不起作用？

I have the same problem with mine

**Comment by jim256** [comment]
> I can't reproduce this.
> Do you mean that sorting doesn't work at all, in all tables, all databases?

I think it only happens if I have an explicit ORDER BY in my query. It will re-run the query as if it's sorting, but doesn't actually change the sort. if I remove the ORDER BY, then it works.

Maybe that's the intended behavior. I'd like to be able to change the sorting after the fact though, without having to comment out my ORDER BY

**Comment by serge-rider** [comment]
This may happen if nested ordering queries are used by dbeaver, In this case Snowflake returns different query metadata and dbeaver looses previous state.

Workaround: disable nested queries for ordering:
![image](https://user-images.githubusercontent.com/6398845/71719593-ea738000-2e2f-11ea-9884-ae4c5ac6e4ab.png)

**Comment by PedroD** [comment]
This bug still exists.

**Comment by daguej** [comment]
FWIW, I thought I was having this problem until I noticed that I had two columns with sort enabled.  Since the first column was `id`, it didn't matter what else I tried to sort by.

**Comment by stantonium** [comment]
> This bug still exists.

Yep, still exists for me too.

**Comment by minaguib** [comment]
I thought I had the same issue, but I just discovered it's a human error.

It looks like DBeaver supports sorting on multiple columns.

So, if you click ↑ or ↓ on columnA to sort by it (it works)
Then later click ↑ or ↓ on columnB, it'll appear broken, but I think that's because it's being added as a secondary sort column.

If you'd like to sort by columnB, you must first de-select the sorting arrow to default ↕ on columnA
