### ISSUE TITLE
HIVE Switch library error reporting

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6654]
![image](https://user-images.githubusercontent.com/26621087/63995813-6ed58f80-cb2c-11e9-8968-91a8a425b84a.png)
SQL 错误 [08S01]: org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset by peer: socket write error
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset by peer: socket write error
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset by peer: socket write error
java.net.SocketException: Connection reset by peer: socket write error
java.net.SocketException: Connection reset by peer: socket write error
Connection reset by peer: socket write error
Connection reset by peer: socket write error

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
Can't reproduce. What Hive driver do you use?

**Comment by Pengchenghua** [comment]
> 无法重现。你用什么蜂巢驱动程序？

hive 1.10

**Comment by uslss** [comment]
can't reproduce. is it still actual for you?

**Comment by uslss** [comment]
there is no update on ticket more than a month.
Ticket closed.
If issue still actual for you - feel free to reopen the ticket
