### ISSUE TITLE
DBeaver username and password request box pops up when running queries

### ISSUE THREAD

**Issue by imiddlebrook** [dbeaver/dbeaver#6655]
#### System information: 
- Windows 8
- DBeaver version 6.0.4.201905052017

#### Connection specification:
- Snowflake

#### Describe your question:
When running an SQL in DBeaver, not every time but often, the popup box requesting to enter username and password pops up. I have to either hold escape as the box pops up constantly or keep clicking cancel. If i leave the box there, the query pauses. After holding down escape or clicking cancel the box eventually disappears and the query pulls back the results. Do you know what this issue could be because I can't work out what it is causing it?

I am connecting via a proxy and added in the correct proxy address, checked the requires authentication box and entered in my username and password, so i'm unsure why the box keep popping up when running a query. If i un-check the authentication box  in the network connections setting the query errors straight away saying it can't connect.

I have attached a photo of the pop box
![Authentication](https://user-images.githubusercontent.com/54709125/64016616-5f037e80-cb1f-11e9-9e5f-36426e810100.PNG)

**Comment by serge-rider** [comment]
This dialog is not a part of DBeaver UI. Most likely it appears whenever proxy authentication is required.
It may happen during SQL queries execute because of timed out connection. You could try to configure keep-alive interval in connection settings.
