### ISSUE TITLE
dbeaver 6.1.5 connetct hive Error: Invalid status 82

### ISSUE THREAD

**Issue by yanzibugui** [dbeaver/dbeaver#6656]
HI:
    I used dbeaver 6.1.5 to connect hive (using SSH Jump Server, and the jump server connection was successful), but connection results showed that [Could not open client transport with JDBC Uri:jdbc:hive2://127.0.0.1:42652/default:Invalid status 82], I searched the reason online, but there was no information about [Invalid status 82]. can you help me??

**Comment by uslss** [comment]
if issue is still actual for you - feel free to reopen the ticket
