### ISSUE TITLE
Sorting error

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6657]
Click sort, unable to sort the sort field, click no response

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
Can't reproduce.
Please provide more details (what database, some screenshot would be very helpful)

**Comment by Pengchenghua** [comment]
> 无法重现。
> 请提供更多详细信息（什么数据库，一些截图将非常有帮助）
HIVE,If I press 1, then I press 2, I can't sort by 2, or sort at the same time
![image](https://user-images.githubusercontent.com/26621087/64098529-b0b73d80-cd99-11e9-894e-09073010bd1d.png)

**Comment by serge-rider** [comment]
You have 3 columns included in ordering. If you want to order only by province_code then you need to remove ordering from two other columns.
You can do this by clicking on sort icon again or by opening custom filters dialog.

**Comment by Pengchenghua** [comment]
> 订购时包含3列。如果您只想通过province_code订购，那么您需要从其他两列中删除订购。
> 您可以通过再次单击排序图标或打开自定义过滤器对话框来执行此操作。

Can I just click sort without unclicking and click sort?

**Comment by serge-rider** [comment]
Yes. Press <kbd>CTRL</kbd> key when clicking on sort icon.
