### ISSUE TITLE
SSL for Greenplum Driver

### ISSUE THREAD

**Issue by kevinsoll** [dbeaver/dbeaver#6658]
System information: 
- Windows 7
- DBeaver version, CE 1.5

 Connection specification:
- Pivotal 5.x

As part of company wide distribution,   installation was sent out as bare bones
copy,  drivers were not included as part of the install.

I am trying to configure Pivotal JDBC driver to connect to Pivotal
jar file downloaded and inported into driver manager.
I am able to connect using non-ssl connection.
I have put the ssl options in driver properties, but the SSL tab does not show up when I am trying to create the connection.

1) Is there something that needs to be done for the ssl table to show up in connections?
2) Do you know if anyone has done this before?  (Would I be better off using generic Postgres driver to connect to greenplum.

Thank you,

Kevin S.

**Comment by serge-rider** [comment]
You need to create driver based on PostgreSQL driver type.
SSL configuration is database-specific.
(Note: see #6634 , perhaps you will need to use 6.2 EA version for this)

BTW what is wrong with standard GP (PostgreSQL) driver?
