### ISSUE TITLE
Issue with delimiter in "Persist Changes" window when saving a trigger

### ISSUE THREAD

**Issue by coldenol** [dbeaver/dbeaver#6659]
#### System information: 
- OS: Windows 10 Pro, ver. 1903, build 18362.295
- DBeaver version: 6.1.4.201908041900

#### Connection specification:
- Database name and version: MySQL 5.7

#### Describe your question:
When I making changes to my trigger and review them in the window "Persist Changes" I see that in the beginning delimiter is set to $$ but at the end it is set to $$ again. Isn't it a bug?
Please refer to the screenshots.
![1](https://user-images.githubusercontent.com/49859188/64034172-cc7ed180-cb56-11e9-927a-716c05ed6852.jpg)

![2](https://user-images.githubusercontent.com/49859188/64034185-d1dc1c00-cb56-11e9-82a0-5e0312953593.jpg)

**P.S.**
When I do the same steps via MySQL Workbench it sets delimiter to ; sign at the end.

**Comment by serge-rider** [comment]
Yes, it is a bug. Thanks for noticing.

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/64457414-35d48680-d0fb-11e9-9845-d554b47c80eb.png)
