### ISSUE TITLE
uppercase db and table names

### ISSUE THREAD

**Issue by r3p0rtI55u3** [dbeaver/dbeaver#6661]
I have upgraded to the latest version on db community 

as always has to go into settings and change the key words to uppercase 

but now its changes the db and table name when the selection comes up and press enter, which is annoying, i always like when you get the drop down on key words and it changes them to uppercase,

please let me know if there is a setting i may of missed 

update 
actually found what i did wrong 

there are 2 places i need to go 

1 - SQL completion 
2 - SQL formatting 

number 2 is what i need,

but still words like truncate comes lowercase, while SELECT , FROM  i can set to upper?

**Comment by uslss** [comment]
cannot reproduce it anymore. if it is still actual for you - feel free to reopen the ticket
