### ISSUE TITLE
Error in generated SQL when deleting column

### ISSUE THREAD

**Issue by zazy** [dbeaver/dbeaver#6662]
#### System information: 
- Operating system (distribution) and version: Ubuntu Desktop 16.04.6 LTS
- DBeaver version: 6.1.5
- Additional extensions: none

#### Connection specification:
- Database name and version: MySQL 5.7.27
- Driver name: mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When saving a table structure after removing a column, the generated SQL shown before apply is possible is wrong. It uses the column name in place of the table name.
For example: if I delete column **column1** from table **table1**, when I click on the **Save** button the generated SQL is _ALTER TABLE column1 DROP COLUMN column1;_
Since I can't edit the SQL I can't click on **Persist** or an error is thrown.

#### Steps to reproduce, if exist:
1. Double click on a table in your database
2. Go to **Properties** panel and select **Columns** sub panel
3. Right click on a column in the column list and, from the popping up menu, select **Delete**
4. Click on the **Save** button in the bottom right corner

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
