### ISSUE TITLE
Lightweight version / configuration

### ISSUE THREAD

**Issue by sinnlos-jmb** [dbeaver/dbeaver#6664]
Hi, congratulations on DBeaver, is great. Is it possible to make a lightweight version of dbeaver for old / slower computers?  Or maybe disabling certain modules of the app.

System information:

    Operating system (distribution) and version: Linux MX 4.19
    DBeaver version: 6.1.5
    Additional extensions: none

Connection specification:

    Database name and version: MySql 5.7.27
    Driver name: mysql
    Do you use tunnels or proxies (SSH, SOCKS, etc)? No

Greetings and keep the great work!

MB

**Comment by serge-rider** [comment]
It is not that easy. Community edition already has minimum number of pre-installed extensions.

- You can set Classic theme to disable advanced css UI. 
- You can reduce max amount of memory (1Gb by default). 
- You can remove some base extensions like schema compare, ssh, spatial viewer, charts and dashboards.
- It is also possible to make version just for one database (this will remove most of drivers and database extensions).

These changes can make DBeaver a bit lighter but I'm afraid we can't provide too many different versions. It takes a lot of resources to build/host different product versions.
