### ISSUE TITLE
Export result set optimization

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6668]
When exporting tens of thousands of pieces of data, it takes more than 5 minutes. Whether it is exported from the result set or directly, can the time be optimized?

**Comment by serge-rider** [comment]
It is not clear - what exactly you propose?

You can change fetch size parameter (in some cases it increases performance dramatically).

**Comment by Pengchenghua** [comment]
> 目前尚不清楚 - 你究竟提出了什么建议？
> 
> 您可以更改提取大小参数（在某些情况下，它会显着提高性能）。

提高 导出效率
