### ISSUE TITLE
load error

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6669]
SQL 错误 [08S01]: org.apache.thrift.TApplicationException: ExecuteStatement failed: out of sequence response
org.apache.thrift.TApplicationException: ExecuteStatement failed: out of sequence response
org.apache.thrift.TApplicationException: ExecuteStatement failed: out of sequence response
ExecuteStatement failed: out of sequence response
ExecuteStatement failed: out of sequence response

![image](https://user-images.githubusercontent.com/26621087/64138837-42be5500-ce31-11e9-924d-c26ab8a76249.png)

*IMPORTANT* -  *before* creating a new issue please look around:
 - DBeaver documentation: https://github.com/dbeaver/dbeaver/wiki
 and
 - open issues in Github tracker: https://github.com/dbeaver/dbeaver/issues
  
If you cannot find a similar problem, then create a new issue. Short tips about new issues can be found here: https://github.com/dbeaver/dbeaver/wiki/Posting-issues

Please, do not create issue duplicates. If you find the same or similar issue, just add a comment or vote for this feature. It helps us to track the most popular requests and fix them faster.

Please fill in as much of the template as possible.
-->

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
Please post error log and some description. At least database type and steps to reproduce.
