### ISSUE TITLE
get list of tables and columns from dbeaver

### ISSUE THREAD

**Issue by jj304** [dbeaver/dbeaver#6670]
Hi,

I am using an ODBC connection to connect to HIVE tables and would like to get a list of all these tables (around 200) and their columns including datatype so that I can export this.  I do not need the data in the table.  Does anyone know how I could do this in DBeaver?  

thanks

**Comment by serge-rider** [comment]
Did you try to use preconfigured Hive driver (JDBC)?

**Comment by uslss** [comment]
there is no update on ticket for a long time.
ticket closed
