### ISSUE TITLE
Weird autocomplete behavior

### ISSUE THREAD

**Issue by gaea44** [dbeaver/dbeaver#6672]
Hi,

with current version of DBeaver CE (6.1.5), autocomplete is a total mess.
I didn't change anything in default settings.

And I had to go to 5.2.1 to find a better behavior.

![image](https://user-images.githubusercontent.com/8070041/64164145-25d65180-ce32-11e9-9a75-6834eed4d4da.png)

![image](https://user-images.githubusercontent.com/8070041/64164293-78177280-ce32-11e9-8ab3-cfed5dfb3988.png)

**Comment by uslss** [comment]
@gaea44 could you add your database version?

**Comment by gaea44** [comment]
Hi,

Database is Oracle 11g version 11.2.0.4.0 (64b)
And I'm using ojdb6 as driver.

Thanks

**Comment by uslss** [comment]
Hi, unfortunately, cannot reproduce the issue. Could you try on the latest version (6.2.5)?

**Comment by uslss** [comment]
there is no any updates. issue closed
