### ISSUE TITLE
When scrolling horizontally text gets scrambled

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#6673]
#### System information: 
- Operating system (distribution) and version - mac os
- DBeaver version - 6.1.5
- Additional extensions

#### Connection specification:
- Database name and version - postgres 11.2
- Driver name - default
- Do you use tunnels or proxies (SSH, SOCKS, etc)? not relevant

#### Describe the problem you're observing:
Sometimes when fast scrolling long text horizontally (left/right) with dragging the horizontal scrollbar the display gets scrambled:
![image](https://user-images.githubusercontent.com/18515297/64176419-196bec00-ce66-11e9-861a-005ecec42168.png)

It seems to have started happening in version 6.1.4 (or maybe a little earlier).
Workarounds: minimize dbeaver window and restore, scroll vertically etc.

#### Steps to reproduce, if exist:
Always when dragging the horizontal scrollbar left/right and the text is long. it also happens in the "value" pane i.e when looking at a value which is a json.
It does not happen when moving the cursor using left/right arrows or alt/ctrl+arrows.
It also does not happen when single clicking on the scrollbar outside of its current position (i.e to move it to a different part in the line).

**Comment by Luis3ma** [comment]
The problem is related to Eclipse.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=548491
https://bugs.eclipse.org/bugs/show_bug.cgi?id=548605

**Comment by hafarey** [comment]
Yes this appears to be the same issue that affected Spring Tool Suite 4 (https://github.com/spring-projects/sts4/issues/312).  Eclipse 4.13 fixes it.

**Comment by daniel9x** [comment]
Any word on when the standalone will be updated to use 4.13? This is super annoying at times.

**Comment by sr3d** [comment]
I'd love to have this issue fixed as well since it's a bit annoying, especially with the script editor.

**Comment by uslss** [comment]
seems that issue is fixed
