### ISSUE TITLE
double click to open ER diagram

### ISSUE THREAD

**Issue by Cisnocxie** [dbeaver/dbeaver#6674]
- Operating system windows 10
- DBeaver version 6.1.5

- Database name and version
oracle

How to config to double click a table in a ER diagram to open it in a new tab to show its ER. 
It is what I want in previous version, but I can't find a settings to do this in 6.1.5. I can only right click table and select "view diagram" to open it. It this operation cancelled?

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/64355901-ac458b80-d00a-11e9-95ca-e5dab6c82d39.png)

**Comment by Cisnocxie** [comment]
Hi serge-rider, this is not the setting I want.
![image](https://user-images.githubusercontent.com/24191122/64394317-34b64180-d088-11e9-8e20-fe9166b70003.png)
If I want to open a table ER diagram in a ER diagram page like above showing, I can't double click to open it. Can only right click and select the "view diagram".
![image](https://user-images.githubusercontent.com/24191122/64394396-91196100-d088-11e9-8994-a1c3f395d3b0.png)

**Comment by serge-rider** [comment]
I think this bug was fixed after 6.1.5, please try Early Access version (htttps://dbeaver.io/files/ea)
