### ISSUE TITLE
Hint at UNIT in preferences/settings, please

### ISSUE THREAD

**Issue by gudesh** [dbeaver/dbeaver#6675]
When the user edits the preferences,

some settings do concern "delays", for instance, 
but nothing (whether label nor tooltip) hints at the UNIT (millisecond, second,...?)

This need applies generally to all settings having a UNIT (time-related, space-related, etc...)

**Comment by serge-rider** [comment]
I found 3 pages where time units weren't obvious. Fixed.
Thanks for noticing this

**Comment by uslss** [comment]
Reopened
![image](https://user-images.githubusercontent.com/31996417/65978599-a6fa2600-e47c-11e9-9d30-33fb0b341158.png)
![image](https://user-images.githubusercontent.com/31996417/65978733-e6c10d80-e47c-11e9-965a-a5a0e5e445c4.png)

**Comment by serge-rider** [comment]
Fixed
