### ISSUE TITLE
Parsing error in Code Editor for double-quoted DB-Objects' names

### ISSUE THREAD

**Issue by gudesh** [dbeaver/dbeaver#6676]
Hi,

DBeaver 6.1.5, Oracle, here.

When I click on the procedure icon (within the left-hand tree) to open for edit the following, legit, procedure within following package:

`
CREATE OR REPLACE PACKAGE BODY ODS."MF=MX_DP=fact=mis=etl" IS

  PROCEDURE "*STD*=trnc=mv" IS
    BEGIN
      EXECUTE IMMEDIATE 'TRUNCATE TABLE "ODS"."MF=MX_DP=fact=mv" DROP STORAGE';
    END;
END;
`

I get following error :

`Dangling meta character '*' near index 12
PROCEDURE\s+*STD*=trnc=mv
            ^
Dangling meta character '*' near index 12
PROCEDURE\s+*STD*=trnc=mv`

**The parser seems to not process the double-quote naming notation properly**
(which is very useful for both profiting of code-generation and overcoming
ORACLE's silly 30-char limitation, btw)

**Comment by uslss** [comment]
if issue is still actual for you - feel free to reopen the ticket

**Comment by gudesh** [comment]
Re-tested on Version 7.2.0.202008302047

Problem still there.
To be precise, it happens when double-clicking in the left-hand tree on a Package's Procedure (ORACLE) which name
looks like ` "*STD*=trnc=mv"`.
(see the stars ?)

I then get a pop-up saying:
```
Dangling meta character '*' near index 12
`PROCEDURE\s+*STD*=trnc=mv`
```
