### ISSUE TITLE
Cannot see what I am typing when completing table properties and attributes

### ISSUE THREAD

**Issue by tom-hanson** [dbeaver/dbeaver#6677]
#### System information: 
- Operating system (distribution) and version: **Linux Mint 18.1 Cinnamon 64-bit (Cinnamon: 3.2.7)**
- DBeaver version: **6.1.4**
- Additional extensions: **none**

#### Connection specification:
- Database name and version: MySQL - Ver 15.1 Distrib 10.3.9-MariaDB
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
This has happened over all the versions of DBeaver I have used for almost the last year. When I have created a new table and filling out the column names/data types etc. I cannot physically see what I am typing as if Linux Mint theme is overlaid on top of the text editor. 

I have tried changing theme settings on Mint but same issues arise.

Changing data (on the Data tab) works fine but anything on the Properties tab has this issue as well as well selecting 'Create New Column' I cannot see what I am typing when changing Data Type etc.

#### Include any warning/errors/backtraces from the logs
Not applicable for this issue

**Comment by tom-hanson** [comment]
Downgrading to 5.2.1 works for me even though I shouldn't have to do this.

**Comment by p91paul** [comment]
you shouldn't close an unresolved issue, maybe someone will step on this and solve it...

**Comment by tom-hanson** [comment]
> you shouldn't close an unresolved issue, maybe someone will step on this and solve it...

I found another issue when searching that was exactly the same as mine (which yeah sure I should have done initially) with no one able to re-create the issue and AFAIK it's still open.

**Comment by ryanhinton** [comment]
I am experiencing an issue not being able to view the text that I am typing in the sql text editor.  Intellisense still works as if it sees everything I am typing, I just cannot see it.  I even reset the text editor to factory default.
