### ISSUE TITLE
Unable to see Trigger Body for Oracle Database, part 2

### ISSUE THREAD

**Issue by Boksh** [dbeaver/dbeaver#6679]
I have a similar problem with not displaying the body of triggers for Oracle tables (#3444).
I can view trigger body in SQL Query `SELECT TRIGGER_BODY FROM SYS.ALL_TRIGGERS WHERE TRIGGER_NAME = 'MY_TRIGGER_NAME'`
but I don’t see the body in the DBeaver trigger properties window, in the declaration segment.
The declaration segment displays the text:

`/* ERROR WHILE READING SOURCE:
SQL Error [17008] [99999]: Закрытое соединение
*/` 
or
`--- Emty source`

In error logs I see:
`Error loading object metedata from database`, plugin: org.jkiss.dbeaver.model

SQL Query `SELECT * FROM SYS.ALL_SOURCE` returns only triggers in my schema, but trigger 'MY_TRIGGER_NAME' is in a different schema,
In the object tree I can see the trigger 'OTHER_SCHEMA.MY_TRIGGER_NAME' and can see all trigger properties except body.

#### System information: 
- OS: Windows 7
- DBeaver version: 6.1.3.201907211943

#### Connection specification:
- Database name and version: Oracle Database 11g EE Release 11.2.0.3.0
- Driver name: JDBC, ojdbc14.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

**Comment by uslss** [comment]
it seems the issue is already fixed.
issue closed.
