### ISSUE TITLE
FIX DBeaver Preferences settings option pages shown double

### ISSUE THREAD

**Issue by allanlaal** [dbeaver/dbeaver#6680]
#### System information: 
- Operating system (distribution) and version: Ubuntu Mate Linux 16.04LTS
- DBeaver version: 6.1.5
- Additional extensions: 
 `
	allan@L4:~/.eclipse/org.jkiss.dbeaver.product_6.1.5_620785679_linux_gtk_x86_64/plugins$ dir -1

	org.eclipse.debug.core_3.13.300.v20190514-0832.jar
	org.eclipse.debug.ui_3.14.100.v20190518-2143.jar
	org.eclipse.ui.console_3.8.500.v20190514-0743.jar
	org.jkiss.dbeaver.core.eclipse_6.1.5.201908191349.jar
	org.jkiss.dbeaver.debug.core_1.0.44.201908191349.jar
	org.jkiss.dbeaver.debug.ui_1.0.44.201908191349.jar
	org.jkiss.dbeaver.ext.postgresql.debug.core_1.0.44.201908191349.jar
	org.jkiss.dbeaver.ext.postgresql.debug.ui_1.0.44.201908191349.jar
`
#### Connection specification:
irrelevant

#### Describe the problem you're observing:
Preferences pages appear double

#### Steps to reproduce, if exist:
• Open DBeaver
• Open Edit → Preferences
• see that all pages in the sidebar have duplicates

#### Include any warning/errors/backtraces from the logs
Error log only had MySQL transaction errors

**Comment by uslss** [comment]
is it still actual?
