### ISSUE TITLE
can't change language en to zh in DBeaver 6.20 CE

### ISSUE THREAD

**Issue by leezm** [dbeaver/dbeaver#6681]
#### System information: 
- Operating system (distribution) and versionqin 
win10 x64 1903
- DBeaver version 
6.20CE
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
can't change language en to zh
![无标题](https://user-images.githubusercontent.com/24444492/64314684-6ffe3500-cfe2-11e9-8625-502eb414da50.png)
![TIM截图20190905133908](https://user-images.githubusercontent.com/24444492/64314731-9a4ff280-cfe2-11e9-8362-21bef4c1a9ae.png)

**Comment by serge-rider** [comment]
DBeaver CE (from Windows Store) is a single language application, it supports only English language at the moment (because of Microsoft Store policy)

Workaround: install DBeaver by downloading installer from dbeaver.io/dbeaver.com web site.

**Comment by leezm** [comment]
> DBeaver CE (from Windows Store) is a single language application, it supports only English language at the moment (because of Microsoft Store policy)
> 
> Workaround: install DBeaver by downloading installer from dbeaver.io/dbeaver.com web site.

okay...but I like this version,because it's seems strat faster than previous version and update is more convenient.Unable to switch languages has little impact.😂
