### ISSUE TITLE
DBEAVER does not display all the schemas of an OpenEdge more than one connection

### ISSUE THREAD

**Issue by MoisesMF1984** [dbeaver/dbeaver#6684]
Hi,

When the connection has many databases, the schema is not displayed.

DBeaver Community Edition 6.1.5.201908191349
Windows 10
Progress OpenEdge 11.4
Driver OpenEdge 11.4

![Evidencia](https://user-images.githubusercontent.com/54941438/64340741-41219800-cfbd-11e9-8e4f-5eba9ea72fcc.png)

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
if it is still actual for you - feel free to reopen the ticket
