### ISSUE TITLE
End background task

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6686]
Excuse me, where can I end the background task? Because I can cancel the task I am inquiring, but I can't finish the query. When the window is closed, the background task is still "requested to cancel" and keeps turning;
![image](https://user-images.githubusercontent.com/26621087/64395343-7d6ff980-d08c-11e9-8d24-ff3a7846bdc4.png)

**Comment by Pengchenghua** [comment]
![image](https://user-images.githubusercontent.com/26621087/64395383-a2fd0300-d08c-11e9-9af5-fa2fc42acc87.png)

**Comment by kseniiaguzeeva** [comment]
Looks like a bug. To reproduce (7.0.4):

1. Open Background Tasks
2. Open SQL Editor  for Postgresql
3. execute select pg_sleep(10);
4. Close  SQL Editor.

Expected: the query is interrupted in Background Tasks
Actual: continuation of query execution is shown

Note: Pressing **Cancel operation** btn doesn't help  in Background Tasks if SQL Editor window with the query was closed before.

**Comment by serge-rider** [comment]
Can't reproduce.
Is see following dialog: 
![image](https://user-images.githubusercontent.com/6398845/95492799-4c0ae100-09a4-11eb-8c57-c99649736c94.png)

Parhaps you checked "Don't ask again" and clicked No. You can check this in Preferences->User Interface->Confirmations.

**Comment by kseniiaguzeeva** [comment]
I cannot see this popup. I set always in Confirmations of User interface. The issue still can be reproduced. Please see
![Uploading CIHI1kwt5h.gif…]()

**Comment by serge-rider** [comment]
In fact problem was caused by incorrect active job cancel after editor close.
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by lparimala** [comment]
> In fact problem was caused by incorrect active job cancel after editor close. Fixed.

Cant we cancel a job without closing the editor.?
