### ISSUE TITLE
Don't working hotkey "Add to favorites" (Ctrl+Alt+Shift D)

### ISSUE THREAD

**Issue by mihmig** [dbeaver/dbeaver#6687]
Don't working hotkey "Add to favorites" (Ctrl+Alt+Shift D) - nothing happened
when i select table/procedure in object tree press this hotkey

**Comment by serge-rider** [comment]
Try to reset UI settings (in main menu File). Shortcut settings sometimes break after numerous version upgrades.

**Comment by mihmig** [comment]
I tried, it didn't help

**Comment by serge-rider** [comment]
I still can't reproduce.
Please check your preferences:
![image](https://user-images.githubusercontent.com/6398845/69484404-eb35f100-0e43-11ea-8b14-dde1bba4c641.png)

**Comment by uslss** [comment]
there is no update on ticket more than a month.
Ticket closed.
If issue still actual for you - feel free to reopen the ticket
