### ISSUE TITLE
Incorrect display of float numbers

### ISSUE THREAD

**Issue by rafaelmartines** [dbeaver/dbeaver#6688]
#### System information: 
- Ubuntu 19.04
- DBeaver 6.1.5

#### Connection specification:
- PostgreSQL
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

On resultset Dbeaver shows the result as intended...

![image](https://user-images.githubusercontent.com/8183691/64427021-86f66300-d086-11e9-855b-ce5ad8ddd8ec.png)

...but when I copy and past the result, the value of the result turns into 1.2345678912E10, I didn't change any settings on DBeaver, just regulary update it, when I change the resultset as text...

![image](https://user-images.githubusercontent.com/8183691/64427152-db014780-d086-11e9-8171-f5e7909ff02b.png)

I tried to change the round in number format on preferences, but nothing happened

#### Steps to reproduce:

The query: `select 12345678912::float;`

**Comment by serge-rider** [comment]
It is a side effect of #6111 fix.
@uslss please verify  test cases in #6111 too.

**Comment by uslss** [comment]
verified
