### ISSUE TITLE
Upgrading from CE to EE

### ISSUE THREAD

**Issue by jadstartin** [dbeaver/dbeaver#6690]
#### System information: 
- Ubuntu 19.04 (disco)
- Version 6.1.5.201908191349 (CE)

#### Connection specification:
- PostgreSQL 11.5 (Ubuntu 11.5-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

#### Describe your question:

Hi,

I've been using Dbeaver CE for some time. Our company just purchased a license for EE and am attempting to install it. Is there an elegant way to upgrade my installation and retain stored connections / settings? I attempted to do a dpkg install of ee over the top of ce, but received the error below. 

Thanks

```
$ sudo dpkg -i ~/Downloads/dbeaver-ee_6.1.0_amd64.deb 
Selecting previously unselected package dbeaver-ee.
(Reading database ... 199600 files and directories currently installed.)
Preparing to unpack .../dbeaver-ee_6.1.0_amd64.deb ...
Unpacking dbeaver-ee (6.1.0) ...
dpkg: error processing archive /home/jad/Downloads/dbeaver-ee_6.1.0_amd64.deb (--install):
 trying to overwrite '/usr/share/dbeaver/dbeaver', which is also in package dbeaver-ce 6.1.5
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Processing triggers for gnome-menus (3.32.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-4ubuntu1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 /home/jad/Downloads/dbeaver-ee_6.1.0_amd64.deb
```

**Comment by rindeal** [comment]
the _dbeaver-ee_ `.deb`'s `control` file should state `Conflicts: dbeaver-ce` and vice versa

**Comment by p91paul** [comment]
anyway, you can solve your issue by uninstalling dbeaver ce first, user settings are kept in an user folder which is not removed by uninstall. Not sure if dbeaver ee uses the same config folder of ce, if so it will automatically get your workspace as you left it.

**Comment by serge-rider** [comment]
DBeaver CE and EE share the same workspace (connections, etc).
In case of deb package you need to uninstall CE before installing CE.

**Comment by jadstartin** [comment]
I was able to uninstall/reinstall while preserving settings. Such a nice tool... Thanks

```
$ dpkg -l | grep dbeaver
ii  dbeaver-ce                                                  6.1.5                                amd64        DBeaver Community
$ sudo dpkg -r dbeaver-ce
...
$ sudo dpkg -i ~/Downloads/dbeaver-ee_6.2.0_amd64.deb
```
