### ISSUE TITLE
Columns with data types timestamp, datetime, geometry are not filtered by cell value

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#6691]
#### System information: 
- Operating system (distribution) and version Windows 10 home
- DBeaver version 6.2.0 EE

#### Connection specification:
- Database name and version Mysql, SQL Server yes for MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? yes for MySQL

#### Describe the problem you're observing:
Columns with data types timestamp, datetime, geometry are not filtered by cell value MySQL, SQL Server Express
#### Steps to reproduce, if exist:
1.Open data view of a table in MySQL, SQL Server where some of following column types exist: timestamp, datetime, geometry.
2. Try to filter  a value of some of columns with type timestamp, datetime, geometry by using filtering icon in column header

Expected result: selected data is filtered
Actual result: no data is displayed

**Comment by serge-rider** [comment]
Fixed for MySQL date/time columns (we now use native format again).
Can't fix for SQL Server (it doesn't support implicit varchar->datetime conversion).
Won't fix for geometries (too much effort while it doesn't make sense in most cases).

**Comment by kseniiaguzeeva** [comment]
Verified
