### ISSUE TITLE
Truncate statement for DB2 when importing data is not correct

### ISSUE THREAD

**Issue by lavalex** [dbeaver/dbeaver#6692]
Hello,

Seems that the truncate statement that is generated for DB2, when I check option to truncate data before import is not correct.

**Comment by uslss** [comment]
is it still actual?

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D30](https://dbeaver.testquality.com/project/8805/result/1743987/defect/6057). Do not remove or edit.

**Comment by serge-rider** [comment]
Fixed (IMMEDIATE clause added)

**Comment by kseniiaguzeeva** [comment]
Verified
