### ISSUE TITLE
OPEN with EXCEL ERROR

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6695]
6.2.0
Export EXCEL, only partial export, not all export, for example: select all the 100 rows, export only 15

![image](https://user-images.githubusercontent.com/26621087/64507004-13658780-d30c-11e9-9c8b-3d4483d22418.png)
![image](https://user-images.githubusercontent.com/26621087/64507121-72c39780-d30c-11e9-8b97-6351d23d9eb9.png)

![image](https://user-images.githubusercontent.com/26621087/64507135-7c4cff80-d30c-11e9-848b-deff67434bc2.png)

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
Can't reproduce.
re you trying to export full resultset or just selected rows?

**Comment by uslss** [comment]
there is no updates on a ticket more than a month.
ticket closed
