### ISSUE TITLE
Windows without content when transforming column

### ISSUE THREAD

**Issue by zlisten** [dbeaver/dbeaver#6696]
#### System information: 
- Operating system (distribution) and version : WIN7
- DBeaver version : 6.1.5 and 6.2.0
- Additional extensions : none

#### Connection specification:
- Database name and version : mysql 5.7.24
- Driver name : default
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
This is a follow-up to a issue [6671]( https://github.com/dbeaver/dbeaver/issues/6671)
I rearranged it. And I think I know why you can't reproduce it.

No problem operation:
1.open a table directly
2.right click column bigint(20) and try to use "column view -> Set "xxx" format -> Epoch Time "
![图片](https://user-images.githubusercontent.com/12082706/64506243-6a1d9200-d309-11e9-8996-b11f23e355bd.png)

Problematic operation:
1. write a script and execute it.
2. right click column bigint(20) and try to use "column view -> Set "xxx" format -> Epoch Time "
**screenshot of 6.1.5**
![图片](https://user-images.githubusercontent.com/12082706/64506317-be287680-d309-11e9-90a7-01de76dcf526.png)

**screenshot of 6.2.0**
![图片](https://user-images.githubusercontent.com/12082706/64506631-d9e04c80-d30a-11e9-819a-3928b4fb0787.png)
(Click ok, it works)

I regret not having described the problem clearly all at once.

**Comment by kseniiaguzeeva** [comment]
verified
