### ISSUE TITLE
Connection authorization failure occurred when upgrade to 6.1.3

### ISSUE THREAD

**Issue by mikkk3l** [dbeaver/dbeaver#6697]
#### System information: 
- Operating system (distribution) and version Windows 10 Enterprise 1803
- DBeaver version 6.2.0 
- Java version: 1.8
- Additional extensions

#### Connection specification: (in principe nothing to do with the problem)
- Database name and version DB2 11
- Driver name IBM DB2 JDBC Universal Driver Architecture 3.72.24
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  SSH

#### Describe the problem you're observing:
Schema combo is empty and when connecting an error is returned:
"Error connecting to datasource

Reason:
[jcc][t4][2013][11249][3.72.24] Connection authorization failure occurred.  Reason: User ID or Password invalid. ERRORCODE=-4214, SQLSTATE=28000"

In 6.1.2 version I can correctly connect with same data.

**Comment by serge-rider** [comment]
Please verify your connection settings. Maybe something was changed on server-side.

Potentially it is possible that some configuration settings were lost during migration (although we can't reproduce this and there were no such reports in the past).

**Comment by uslss** [comment]
there is no updates on ticket more than a month.
ticket closed
