### ISSUE TITLE
Numbers not formatted correctly based on local settings

### ISSUE THREAD

**Issue by gandreani** [dbeaver/dbeaver#6698]
**System information:**
Operating system (distribution) and version Windows 10 Professional 1709
DBeaver version 6.2.0
Java version: 11.0.2
Additional extensions
**Connection specification: (in principe nothing to do with the problem)**
Database name and version DB2 z/os 11
Driver name IBM DB2 JDBC 4.16.53
Do you use tunnels or proxies (SSH, SOCKS, etc)? No
**Describe the problem you're observing:**
By setting the locale to Italian, the decimal numbers remain separated by a dot instead of a comma (ex 3.1415 instead of 3,1415) .
The problem started with version 6.1.5 and is also present in 6.2. 
The number formatting works fine in 6.1.4.

**Comment by serge-rider** [comment]
This is a side effect of #6493 fix.
This problem happens only with BigDecimal numbers (however some drivers use this data type by default for all numbers).

Thanks for the bug report.

**Comment by uslss** [comment]
verified
