### ISSUE TITLE
Changed format for Timestamp and Datetime column type

### ISSUE THREAD

**Issue by deathcomes84** [dbeaver/dbeaver#6699]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 6.2.0

#### Connection specification:
- Database name and version: MySQL 5.7.18

#### Describe your question:

I have a column with type "timestamp" and "datetime"
before upgrading to version 5.2.0 the values where show like this "yyyy-MM-dd HH:mm:ss"
but after upgrading the format changed to "yyyy-MM-dd-HH.mm.ss +zzzz".

How can i change is back?

**Comment by serge-rider** [comment]
Yes, you can:
![image](https://user-images.githubusercontent.com/6398845/64559503-1cc41380-d34f-11e9-9893-b6e82e97e3b0.png)

Now we should timezone by default (for MySQL only). To avoid user confusion when server reside in a different timezone.

**Comment by psygnoser** [comment]
![Screenshot from 2019-09-10 09-09-33](https://user-images.githubusercontent.com/550095/64591736-c97fae80-d3aa-11e9-80f0-9c9cb294eb3f.png)

I have the same issue and event though the Timestamp setting shows `yyyy-MM-dd HH:mm:ss` it still displays the timestamps as `yyyy-MM-dd-HH.mm.ss +zzzz`. It only works if I check the `User native date/format` and disconnect and reconnect.

**Comment by deathcomes84** [comment]
The format is currently "yyyy-MM-dd HH:mm:ss" (in database settings and in global settings) but when i open a table it is shown like "yyyy-MM-dd-HH.mm.ss +zzzz".

**Comment by deathcomes84** [comment]
I there a chance that is a bug when upgrading from the previous version? 
Meaning it needs an "options reset" or something like that?

**Comment by dezlov** [comment]
Another one here hit by this bug.

The formatting issue appeared after upgrading to 6.2.0. I never changed the default formats. The global format is set at `yyyy-MM-dd HH:mm:ss`, but the resultsets are now displayed in this awkward `yyyy-MM-dd-HH.mm.ss Z` format, despite the fact that the connection configuration is set to use the global settings!

Two workarounds so far:
1. Override the format for Timestamp type in connection settings, per connection.
2. Enable "_Use native date/time format_" option in the global settings.

**Comment by pnalysz** [comment]
I think I am facing similar problem. When I insert `'2009-03-29 02:00:00'` value to column of `timestamp` data type it gets converted to `'2009-03-29 03:00:00'` (`'2009-03-29 02:00:00'` does not exist in CET where I reside).

**Comment by dezlov** [comment]
@pnalysz - It is not a similar problem at all. It looks like a timezone conversion issue, especially so if you are using the TIMESTAMP type. You may also be hit by an ambiguous timezone mapping if it is around the DST time change period.

**Comment by pnalysz** [comment]
Thanks for your remark. Why on earth any conversion takes place if `timestamp `is timezone-naive?

**Comment by dezlov** [comment]
@pnalysz - See MySQL docs snippet below...

> MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval. (This does not occur for other types such as DATETIME.) By default, the current time zone for each connection is the server's time. The time zone can be set on a per-connection basis. As long as the time zone setting remains constant, you get back the same value you store.

**Comment by serge-rider** [comment]
@pnalysz This is how MySQL driver works. It converts all timestamps to the local (client) timezone. Unless we read timestamps as strings (then they are fetched in server timezone - the same for all clients).

This bug will be fixed in the next version (in #6691).

We'll use the same client-side format as MySQL native timestamp format. + will use native timestamp fetch by default. This should resolve most of problems with time conversion in MySQL.

**Comment by pnalysz** [comment]
Thanks, it seems it is really not a proper place for this one since I use postgres. I will have to look what postgres does under the hood. But I am pretty sure I did not have this problem before 6.2.0.

**Comment by pnalysz** [comment]
@serge-rider Could you confirm that I may be facing #6015? Thanks a lot.

**Comment by uphlewis** [comment]
Is there any setting where we can tell Dbeaver to display the data exactly as it is returned in the query results? The automatic formatting has bitten me in the butt a few times, for instance `0000-00-00 00:00:00` being incorrectly displayed as null in the GUI, or other weird subtle issues that i didnt pick up on until i actually opened up a mysql CLI shell.

**Comment by deathcomes84** [comment]
I want to add that now that i'm using v6.3.2 it seems to be somewhat fixed. Meaning that now the column with type "datetime" is being displayed as "yyyy-MM-dd HH:mm:ss.0". 
I don't know what this ".0" is (timezone maybe?) but it is by far better than " +zzzz".
