### ISSUE TITLE
Hangs on visualizing jsonb

### ISSUE THREAD

**Issue by WilliamRaynaut** [dbeaver/dbeaver#6701]
#### System information: 
- Ubuntu 18.04.3
- DBeaver 6.2.0
#### Connection specification:
- PostgreSQL 9.6
- PostgreSQL JDBC Driver

#### Describe the problem you're observing:
When querying for a fairly large jsonb field (around 80k chars, a fairly flat json tree of depth 3), the query execute fine and instantly, and displays the first few fields of the jsonb in the record grid. However, clicking on the jsonb field for any record (to view the full json in the Value tab for instance) instantly freezes dbeaver, with a single core going to 100% usage. Left to run about half an hour as so, got no response whatsoever. Accessing the exact same field on the exact same record from another machine (same setup except for dbeaver still on 6.0.3) works fine.

#### Include any warning/errors/backtraces from the logs
The logs seem pretty uninformative, and .log and dbeaver-debug.log appear out of sync...
The two files are only a few lines long so I included them.
The only vaguely suspicious line is at 76 in debug:

```
2019-09-09 14:21:49.501 - > Start org.jkiss.dbeaver.ui.editors.image [1.0.16.201909081341]
2019-09-09 14:21:49.504 - Can't detect image type: Unsupported or unrecognized format
2019-09-09 14:21:49.507 - > Start org.jkiss.dbeaver.ui.editors.json [1.0.0.201909081341]
```

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3590435/dbeaver-debug.log)
[log.log](https://github.com/dbeaver/dbeaver/files/3590443/log.log)

**Comment by serge-rider** [comment]
Unfortunately I can't reproduce this.

Could you sand some sample of json value which makes DBeaver to hang?
Does it hang if you disable value auto-format and/or word wrap?

**Comment by WilliamRaynaut** [comment]
Thanks for the fast response.
Turning off the word wrap indeed seems to mitigate the issue a lot (auto-format was already off), goes from hangs forever to hangs for ~10s. This still seems quite long to me, but I can live with that.
Does this behaviour seem normal to you ? I can't really concieve how accessing data already fetched could consume 10s of full cpu, or how computing a few thousands linebreaks would takes half an hour... Smells like something off in the Value tab formating ^^
I'm sorry I'm not allowed to disclose the actual content of the json. It is a list of ~600 json objects, each of depth 2, for a total just over 80k chars.
Let me now if I can provide more data on the issue, else I'll just make do with the short freezes...

**Comment by serge-rider** [comment]
No, 10s for rendering is definitely not good, 80k json is nothing.
in my test case I use 250k json and it renders in 0.1-0.5sec.

- Is it a single line json? Then auto-formatting may help.
- Do you use Dark or Darkest Dark theme?

**Comment by WilliamRaynaut** [comment]
It is indeed single line. I don't see any difference in response time with auto-format on or off, only the word wrap that absolutely destroys it.
I was using the Dark theme. There is a little variation when disabling theming or when trying a few different themes... Best I got is on Classic, down to 2-3s.
I noticed that there is some coloration of the values inside the json (different for ints and strings). I tried diabling that but couldn't find a way.

**Comment by serge-rider** [comment]
Eventually I've reproduced this.

**Comment by serge-rider** [comment]
It seems to be some kind in Eclipse platform (StyledText render). Workaround added.

**Comment by kseniiaguzeeva** [comment]
Verified
