### ISSUE TITLE
Missing quotes during function drop

### ISSUE THREAD

**Issue by mweirauch** [dbeaver/dbeaver#6702]
#### System information: 
- Operating system (distribution) and version: Fedora 30
- DBeaver version: 6.1.5
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 9.6.11
- Driver name: ?
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Missing quotes around extension name in DROP DDL.
The following DDL is generated: `DROP EXTENSION uuid-ossp CASCADE;`
Should be: `DROP EXTENSION "uuid-ossp" CASCADE;`

#### Steps to reproduce, if exist:
* PostgreSQL-Installation with "uuid-ossp" plugin/extension
* Context-Menu on the extension -> Delete
* Confirm dialog
* Error message dialog:
```
ERROR: syntax error at or near "-"
  Position: 20
```

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
