### ISSUE TITLE
PostgreSQL: Impossible to see partition in partition (after upgrade to 6.1.2+)

### ISSUE THREAD

**Issue by HugoShamrock** [dbeaver/dbeaver#6703]
#### System information: 
- Operating system (distribution) and version: Debian 10
- DBeaver version: 6.1.2+
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 11.5
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:

- version 6.1.2 add Partitions DDL and other things around partitions
- but made it impossible to see partition in partition in Database Navigator tree

**Comment by serge-rider** [comment]
I've added nested partitions navigation support. However I lack real world examples to test this.
Could you post some SQL snippet (nested partition create).

**Comment by HugoShamrock** [comment]
Sorry for the later answer ... since version 6.2.3 it's o.k. ... big thanks to all for the good work!
