### ISSUE TITLE
On Ubuntu snap installation is not working

### ISSUE THREAD

**Issue by compalmanel** [dbeaver/dbeaver#6704]
I'm running Ubuntu 19.04. After using Ubuntu Software (a snap frontend) to install DBeaver, it fails to start with the following error:

> (process:8713): Gtk-WARNING **: Locale not supported by C library.
> 	Using the fallback 'C' locale.
> Failed to connect to Mir: Failed to connect to server socket: No such file or directory
> Unable to init server: Could not connect: Connection refused
> Dbeaver: Cannot open display: 
> Failed to connect to Mir: Failed to connect to server socket: No such file or directory
> Unable to init server: Could not connect: Connection refused
> Invalid Configuration Location:
> The configuration area at '/home/pmfa/.eclipse/1738816236_linux_gtk_x86_64/configuration' > could not be created.  Please choose a writable location using the '-configuration' command > > line option.

**Comment by aurelijusrozenas** [comment]
Same on Ubuntu 18.10.
> (process:7538): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Dbeaver: Cannot open display: 
Invalid Configuration Location:
The configuration area at '/home/infro/.eclipse/1738816236_linux_gtk_x86_64/configuration' could not be created.  Please choose a writable location using the '-configuration' command line option.

**Comment by bkolasa** [comment]
Exactly the same on Ubuntu 18.04.3 LTS

**Comment by leandropaz** [comment]
Same issue on Ubuntu 19.10.

**Comment by cristiancmello** [comment]
Same issue on Ubuntu 19.10.

**Comment by gogosofta** [comment]
same here (ubuntu 19.10)

**Comment by tayfunyasar** [comment]
same here. dbeaver isnt in latest version in snap store. it is still in 5.2.5

**Comment by audacioustux** [comment]
same in manjaro kde
```
11:04:30:0140 Gtk Locale not supported by C library.

11:04:30:0141 Gtk Failed to load module "canberra-gtk-module"
No protocol specified
Unable to init server: Could not connect: Connection refused
11:04:30:0146 Gtk cannot open display: :0
```

**Comment by serge-rider** [comment]
Fixed by @galgalesh PR

**Comment by uslss** [comment]
verified

**Comment by alacevedo** [comment]
Se agrega delay a la descarga de documentos
