### ISSUE TITLE
Missing Mock Data Generation Option

### ISSUE THREAD

**Issue by bimbangboom** [dbeaver/dbeaver#6705]
#### System information: 
- Operating system - Windows 10
- DBeaver version - 6.2.0

#### Connection specification:
- Database name and version - Any - Oracle, etc.

#### Describe the problem you're observing:
Generate Mock Data option cannot be found

#### Steps to reproduce, if exist:
Start DBeaver
Connect to any database
Right click on a table or view
Notice the generate mock data option is not there, as advertised in the Wiki.

https://github.com/dbeaver/dbeaver/wiki/Mock-Data-Generation-in-DBeaver

**Comment by serge-rider** [comment]
See #6592
