### ISSUE TITLE
[PostgreSQL] Lock Manager query

### ISSUE THREAD

**Issue by lrweck** [dbeaver/dbeaver#6706]
Hi, 

For older PostgreSQL versions, the column pg_stat_activity.pid does not exists. Instead DBeaver should user pg_stat_activity.procpid.

![image](https://user-images.githubusercontent.com/26086198/64563144-f4bfba80-d324-11e9-966d-3dd149ec3f5e.png)

**Comment by serge-rider** [comment]
@lrweck do you know in what exactly PG version this was changed? I couldn't find any information on pg_stat_activity structure before 9.2.
Also we do joins with blocked_activity by pid column. Was it also changed?
Maybe you can post a lock reading valid query for older PG versions?

**Comment by lrweck** [comment]
@serge-rider 

According to [the release notes](https://www.postgresql.org/docs/9.3/release-9-2.html), the change happened on 9.2 [E.51.2.6. Monitoring](https://www.postgresql.org/docs/9.3/release-9-2.html#AEN123771). Also, CTEs weren't available until 8.4

pg_locks view didn't change, I believe. 

Where can I get the query used by DBeaver to edit it?

**Comment by serge-rider** [comment]
It is here: https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/lock/PostgreLockManager.java

**Comment by uslss** [comment]
if the issue is still actual - feel free to reopen the ticket or create a new one.
BR
