### ISSUE TITLE
Weird behavior on SELECT COUNT(1) FROM TABLE

### ISSUE THREAD

**Issue by matheus-rossi** [dbeaver/dbeaver#6708]
Hello!

When I run the following query on dbeaver 6.20 connecting do SQL SERVER and FIREBIRD

SELECT COUNT(1) FROM SB1010
It returns the number 7

When i run the same query on MSSQL

it returns the real number of rows, that is 443.398 rows

What could be wrong ? maybe something on my configs ?

Dbeaver version: 6.2.0.201909081341

**Comment by serge-rider** [comment]
I can't reproduce this issue.
Did this work correctly in previous DBeaver versions?
Potentially this may be somehow related to the recent "fetch size" configuration option usage change.

You could try to play with following options:
![image](https://user-images.githubusercontent.com/6398845/64647585-f3c08300-d421-11e9-83a8-01b084e6eddb.png)

Please write aobut results.

**Comment by uslss** [comment]
there is no update on ticket for a long time.
ticket closed
