### ISSUE TITLE
DB Metadata search pop-up closes as soon as it opens

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#6709]
**Steps to reproduce:**
* Launch Dbeaver.
* Connect to some database, maybe run some queries.
* Go to the top panel, click 'Search' -> 'DB Metadata'.

**Expected behavior:** should display the metadata search dialog, let the user search for things there.

**Actual behavior:** the metadata search dialog pop-up appears, but then closes instantly, without any error messages.

**Setup:** dbeaver 6.2.0, running on windows 10.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by serge-rider** [comment]
Workaround: press <kbd>ctrl+h</kbd> and then switch to metadata search.

**Comment by uslss** [comment]
verified
