### ISSUE TITLE
SQL completion prompt error

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6710]
When querying the table, there are no popup fields in this table, which is an error prompt;
![image](https://user-images.githubusercontent.com/26621087/64615061-5f97f100-d40c-11e9-8794-5ed88a911b02.png)

eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

#### System information: 
- Operating system (distribution) and version WIN10
- DBeaver version  6.20
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by kseniiaguzeeva** [comment]
Is the ticket still actual for you?

**Comment by uslss** [comment]
there is no update on ticket for a long time. 
If issue is still reproducible for you - feel free to reopen the ticket with additional info that could be helpful to make the issue clearer
