### ISSUE TITLE
The regular expression cannot be recognized

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6711]
No substitution can be identified using regular expressions
![image](https://user-images.githubusercontent.com/26621087/64616965-1c3f8180-d410-11e9-9c70-7251f0f4e807.png)
![image](https://user-images.githubusercontent.com/26621087/64616982-282b4380-d410-11e9-8ed4-0561e75a6dc6.png)

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
If you are on Windows you need to use `\r\n` as line delimiter in your regexp.
