### ISSUE TITLE
mark result of "group by"

### ISSUE THREAD

**Issue by ramunozp** [dbeaver/dbeaver#6712]
**Is your feature request related to a problem? Please describe.**
It is not always clear to see the groups, especially when the amount of information is large. To clearly see the data, especially when we group it, the idea is to be able to mark each group visually, either in colors (table mode) or lines (text mode).

**Describe the solution you'd like**
It would be great if we could somehow highlight the grouped records, for example (text mode):

 | 20190904 | 28 | 2 | 1 | 6558797 | 20190903 | 16: 50: 51 |
 ------------------------------------------------------------------------------
 | 20190904 | 28 | 2 | 1 | 6559285 | 20190904 | 09: 19: 16 |
 | 20190904 | 28 | 2 | 1 | 6559753 | 20190904 | 17: 20: 07 |
 ------------------------------------------------------------------------------
 | 20190905 | 28 | 2 | 1 | 6560841 | 20190905 | 17: 41: 37 |
 ------------------------------------------------------------------------------
 | 20190906 | 28 | 2 | 1 | 6562437 | 20190906 | 12: 54: 06 |
 | 20190906 | 28 | 2 | 1 | 6562440 | 20190906 | 13: 01: 17 |
 | 20190906 | 28 | 2 | 1 | 6562439 | 20190906 | 12: 59: 11 |
 | 20190906 | 28 | 2 | 1 | 6562438 | 20190906 | 12: 55: 02 |
 ------------------------------------------------------------------------------

**Additional context**
applied to:
select {columns} from {table} group by {columns}

**Comment by uslss** [comment]
Probably, [Rows coloring](https://github.com/dbeaver/dbeaver/wiki/Data-View-and-Format#rows-coloring) could be used in this case
