### ISSUE TITLE
Add Placeholder for Main/Metadata variations in ApplicationName

### ISSUE THREAD

**Issue by gavenkoa** [dbeaver/dbeaver#6715]
With `SELECT application_name FROM pg_stat_activity` I see:

```
DBeaver 5.3.0 - Metadata
DBeaver 5.3.0 - Main
```
Under **File -> Properties -> Connections -> Global settings -> Override application name** I see placehoslders for "DBeaver" as `${application.name}`  and for version: `${application.version}` (which produces something different: `5.3.0.201812092025`).

I want to set fixed string and placeholder for Metadata/Main variation - to understand who and **why** (from functional point of view) connection has been established.

**Comment by serge-rider** [comment]
This makes sense.
We could add variable ${context.name} for that, I think. However it will require some code refactoring for this feature.

**Comment by serge-rider** [comment]
I've added 2 new variables: ${context.name} and ${context.id} which you can use for custom application name.
${context.name} is name in form "Metadata", "Main", etc.
${context.id} is unique ID of context (auto-generated).
