### ISSUE TITLE
Sometimes can't connect to sqlserver in Dbeaver CE

### ISSUE THREAD

**Issue by leezm** [dbeaver/dbeaver#6718]
#### System information: 
- Operating system (distribution) and version
win10 1903
- DBeaver version
dbeaver ce
- Additional extensions

#### Connection specification:
- Database name and version
mssql2005
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
This seems to be jre's problem，because it's ok in decompressed version.
![QQ截图20190911141355](https://user-images.githubusercontent.com/24444492/64672656-a3d3d180-d49e-11e9-8727-e5415137cd29.png)
Reference : [https://blog.csdn.net/m0_37808229/article/details/85119013](url)
So,which jre is Dbeaver CE use?

**Comment by serge-rider** [comment]
By default (if you use Windows/MacOS installer) DBeaver 6.1+ uses JDK 11. Unlimited encryption already enabled by default.

What dbeaver version do you use?
DBeaver jre resides in dbeaver install directory, subfolder `jre`.

**Comment by leezm** [comment]
> By default (if you use Windows/MacOS installer) DBeaver 6.1+ uses JDK 11. Unlimited encryption already enabled by default.
> 
> What dbeaver version do you use?
> DBeaver jre resides in dbeaver install directory, subfolder `jre`.

I use Dbeaver CE Version，witch can download in ms store.

**Comment by leezm** [comment]
> Windows Store def isntall location is `C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_XXX`

but I can't find this file:Java.security in then path:XXX/jre/lib/security.That's why I commit this issue.Do you know where's the file in CE version?
