### ISSUE TITLE
phoenix can't input the port

### ISSUE THREAD

**Issue by qq459673705** [dbeaver/dbeaver#6719]
#### System information: 
- ubuntu18.04
- DBeaver 6.20
- Additional extensions

#### Connection specification:
- Phoenix-hbase   4.14.1-HBase-1.2
- Driver name  org.apache.phoenix.jdbc.PhoenixDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  ssh

#### Describe the problem you're observing:
Database port not specified and no default port number for driver 'Apache Phoenix'
I can't join the port with the jdbc-url address.
when i input the port, the jdbc-url address is not change.
![2019-09-11 15-32-03屏幕截图](https://user-images.githubusercontent.com/6657548/64677020-5dd03b00-d4a9-11e9-9bdd-b3da44369b5c.png)

**Comment by serge-rider** [comment]
Click on "Edit driver" then change URL pattern to `jdbc:phoenix:{host}[:{port}]` then change port number.
I'll fix default Phoenix driver configuration.
Thanks for the bug report

**Comment by uslss** [comment]
verified
