### ISSUE TITLE
Support PKCS11 SSH authentication method

### ISSUE THREAD

**Issue by rnijveld** [dbeaver/dbeaver#6720]
**Is your feature request related to a problem? Please describe.**
At my company we use yubikeys in combination with the OpenSC PKCS11 module for authentication. Currently I can't find a way to use this in dbeaver, and I currently manually create a SSH tunnel before opening the connection on dbeaver.

**Describe the solution you'd like**
Built-in support for PKCS11 so that any authentication module may be used for creating a SSH tunnel.

**Describe alternatives you've considered**
Manually creating a SSH tunnel on the command line works, but requires additional steps and I can't reasonably expect everyone else on my team to be doing the same. I tried using the "before connect" shell commands that dbeaver offers, but I couldn't get it to work when the PKCS11 module asks for user input (i.e. a pin number for the smart card or yubikey).

**Comment by serge-rider** [comment]
Perhaps BouncyCastle security provider will fix this.
For that you could try to install SSHJ optional package (Help->Install New Software, then choose it from drop-down menu). 
And then switch your connection's SSH config from JSch to SSHJ.

IF this won't help please provide more details (error messages/log files would be very helpful)
