### ISSUE TITLE
i  bring up a question for NLS LANG

### ISSUE THREAD

**Issue by jpk0914** [dbeaver/dbeaver#6721]
* Database Info
oracle 11g r2
NLS_LANGUAGE : AMERICAN
NLS_TERRITORY : AMERICA
NLS_CHARACTERSET : US7ASCII 

* laptop registry 
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\ORACLE\KEY_OraClient11g_home1NLS_LANG  :  AMERICAN_AMERICA.US7ASCII

korean string in query result is broken  (it likes '?')
how can i  fix this problem?

**Comment by kseniiaguzeeva** [comment]
Is it still actual for you? If yes, please tell which DBeaver version do you use now?

**Comment by uslss** [comment]
there is no update on issue for a long time. If it is still actual for you - feel free to reopen the ticket
BR
