### ISSUE TITLE
unable to close session in Vertica with new version

### ISSUE THREAD

**Issue by hannahshachar** [dbeaver/dbeaver#6722]
![image](https://user-images.githubusercontent.com/18379198/64681406-52204c80-d488-11e9-9a87-663ccdbc9671.png)

select close_session('v_soda_node0001-313816:0x9b51a');

![image](https://user-images.githubusercontent.com/18379198/64681456-6ebc8480-d488-11e9-80bc-eab34dda4654.png)

And also unable to copy and paste the error

**Comment by serge-rider** [comment]
Try to disable option "Use SQL to limit fetch size": 
![image](https://user-images.githubusercontent.com/6398845/64708230-ef957380-d4bc-11e9-93f4-122417dfad7a.png)

**Comment by uslss** [comment]
duplicates #6717

**Comment by hannahshachar** [comment]
It was already disabled.

**Comment by hannahshachar** [comment]
![image](https://user-images.githubusercontent.com/18379198/65154304-f0d21d80-da33-11e9-9ec2-cfcb30ba457e.png)
