### ISSUE TITLE
Cancelling a query sometime never ends

### ISSUE THREAD

**Issue by abolognino** [dbeaver/dbeaver#6723]
#### System information: 
- Operating system (distribution) and version
Ubuntu 18.04
- DBeaver version
6.2.0.201909081341
- Additional extensions
Vrapper

#### Connection specification:
- Database name and version
Oracle 11gr2
- Driver name
ojdbc6 (11.2)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no
#### Describe the problem you're observing:
sometime cancelling a query never ends, even after disconnecting from network. I'm forced to either use another tab or restart dbeaver.

#### Steps to reproduce, if exist:
can't always reproduce but happens often with big long-running queries

#### Include any warning/errors/backtraces from the logs
Will add later

**Comment by cerebel** [comment]
Usually, in w7, I close connection  with [ProcessHacker](https://processhacker.sourceforge.io/) (tab Network, filter by dbeaver)  (sometimes need to wait some seconds in dbeaver.. or call again Cancel operation)

**Comment by Pengchenghua** [comment]
我的也会出现这个问题，已经反馈，希望大大们可以解决这个问题

**Comment by serge-rider** [comment]
See #3616.
Oracle driver doesn't support query cancel on some systems (this depends on Oracle server version and server OS version).
Unfortunately we can't fix this from DBeaver side.
