### ISSUE TITLE
[Usability] Add checkboxes to metadata viewer to show/hide columns

### ISSUE THREAD

**Issue by lacanoid** [dbeaver/dbeaver#6727]
Please add checkboxes to metadata viewer to show or hide columns. Hiding columns is already possible, but one has to go through the hassle of scrolling and clicking the menus. Adding a checkbox to the metadata viewer seems a natural thing to do.

Also, reordering of the columns from the metadata viewer would be nice too.

Metadata viewer is good for handling columns, as it display more of them than the grid view.

**Comment by majkinetor** [comment]
Yeah, please add button [x] on each column. Its totally inefficient to kill bunch of columns via menu.

**Comment by uslss** [comment]
Columns could be reordered and hide/shown using [Customize filters](https://github.com/dbeaver/dbeaver/wiki/Data-Filters#advanced-filters-configuration)
![image](https://user-images.githubusercontent.com/31996417/128050281-ace204c3-cc3a-46fa-b278-8b0ddef19e1d.png)

**Comment by majkinetor** [comment]
We know that, that was not the issue. The issue is about UX and interactivity - something that is needed quite often is hidden behind inefficient menu options.

**Comment by lacanoid** [comment]
I had no idea there was "customize filters". It is similar like what I had in mind. Reordering by dragging would be nice, though.

This could be merged into the metadata panel so everyone could find it.
