### ISSUE TITLE
Latin (spanish) character encoding issues

### ISSUE THREAD

**Issue by CristianH033** [dbeaver/dbeaver#6729]
Hi.
Some texts in the menus show a wrong encoding in spanish.
Here are some screenshots:
![image](https://user-images.githubusercontent.com/4079493/64748521-08f7e900-d4d8-11e9-82d4-cbd9e27e2495.png)
![image](https://user-images.githubusercontent.com/4079493/64748598-43618600-d4d8-11e9-95ef-6294db1e9dae.png)
![image](https://user-images.githubusercontent.com/4079493/64748624-5c6a3700-d4d8-11e9-8057-5d73080e7742.png)

#### System information: 
- Ubuntu 19.04 64bits
- DBeaver 6.2.

**Comment by mkgrgis** [comment]
java properties problemas de traducción y codificación (8-bit) de texto

**Comment by uslss** [comment]
if it still actual - feel free to reopen the ticket
