### ISSUE TITLE
Bug with CASE WHEN ELSE END in Oracle script #3481 (Reopen)

### ISSUE THREAD

**Issue by AlperArikan** [dbeaver/dbeaver#6732]
Same issue with #3481

When I execute Create queries with a CASE WHEN statement which ends with a trailing semicolon gives the following error but when I remove semicolon then it runs.

“ORA-00933: SQL command not properly ended”

--This gives error
CREATE TABLE XYZ AS
SELECT CASE WHEN 1=1 THEN 1 ELSE 0 END AS CLMN
FROM DUAL;

--Working
CREATE TABLE XYZ AS
SELECT CASE WHEN 1=1 THEN 1 ELSE 0 END AS CLMN
FROM DUAL

--Working
CREATE TABLE XYZ AS
SELECT 1 AS CLMN
FROM DUAL;

Dbeaver 6.1.3
Server Oracle Database 12c Enterprise Edition Release 12.2.0.1.0
Client Oracle 12.1.0
Driver ojdbc8.jar

Dbeaver Preferences\SQL Processing\Delimeter settings
Statements Delimeter= ;
Ignore native delimeter unchecked
Blank line is statement delimeter checked
Remove trailing query delimeter checked

**Comment by serge-rider** [comment]
Fixed (we must leave trailing delimiter only if query ends with `END;`

**Comment by kseniiaguzeeva** [comment]
Verified
