### ISSUE TITLE
Update/upgrade dialog is hidden behing startup splash

### ISSUE THREAD

**Issue by Tux** [dbeaver/dbeaver#6733]
#### System information: 
- openSUSE (Leap 15.0, Leap 15.1, and TumbleWeed)
- DBeaver - 6.2.0
- n/a

#### Connection specification:
- n/a
- n/a
- n/a

#### Describe the problem you're observing:

When starting dbeaver after installing a newer version (from rpm), a dialog appears to ask if I should migrate my old settings to the new version. This dialog is *completely* hidden behind the startup splash, which I have to move out of the way dragging with Alt-<1> (plasma5).

I just reproduced the issue on a openSUSE Leap 15.1, where this [dialog](https://tux.nl/Files/DBeaver-604-620.png) is completely hidden behind this [startup splash](https://tux.nl/Files/DBeaver-620.png)

#### Steps to reproduce, if exist:

Update to a more recent version (if exists) and start dbeaver.
It is at least the second time I've seen this happening.

#### Include any warning/errors/backtraces from the logs

Import workspace
  DBeaver 6.2.0 uses a new configuration format.
  Do you want to migrate existing settings (version 6.0.4)?
[ Migrate (Recommended) ] [ Do not migrate ]

**Comment by serge-rider** [comment]
This happens only on some Linuxes.
Thanks for the bug report.

**Comment by uslss** [comment]
verified
