### ISSUE TITLE
Hadoop Hive query resubmission issues

### ISSUE THREAD

**Issue by mtdeguzis** [dbeaver/dbeaver#6734]
#### System information: 
- Operating system (distribution) and version: Windows 7 / Windows 10
- DBeaver version: 6.0.0.201903101945
- Additional extensions

#### Connection specification:
- Database name and version: 
- Driver name: `org.apache.hive.jdbc.HiveDriver`
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

![image](https://user-images.githubusercontent.com/27829577/64791517-d7b60200-d545-11e9-81f5-24e8434cc427.png)

#### Describe the problem you're observing:
We have discovered that when a failed query dies on Hadoop Hiveserver2, the end user merely see's the query continuing to "run." What is actually happening in the background on the hiveserver side, is we see DBeaver resubmitting the query up to 5 times. We will see the Tez WebUI show new retries show up, all while the end user is seeing the loading bar for the query running.

This error message is then shown to the user:
```
SQL Error [2] [08S01]: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.tez.TezTask.
 Session stats:submittedDAGs=0, successfulDAGs=163, failedDAGs=0, killedDAGs=2¶
```

When we run the bad query via `beeline` (default CLI for running hive queries with Hadoop Hive), the error is produced after the first run, with no retries submitted. To us, this then identifies a potential issue with the application, or more specifically, the driver, resubmitting the query. It appears the connection is invalidated and then it retries.

If the user presses the cancel button, it does seem to halt this retry process.

When the query fails and it retries, we notice the connection is invalidated:
![image](https://user-images.githubusercontent.com/27829577/64796322-83168500-d54d-11e9-86bf-16476b96a950.png)

SQL Errors are printer in the results window, but the "Execute query" continues to wait:
![image](https://user-images.githubusercontent.com/27829577/64797465-71ce7800-d54f-11e9-9367-8fa2529fe61f.png)

Eventually when retries are exhausted:
![image](https://user-images.githubusercontent.com/27829577/64798611-4f3d5e80-d551-11e9-8a5f-af490b84b853.png)

#### Steps to reproduce, if exist:
Run a query that consistently will fail using the Apache Hive JDBC driver.

#### Include any warning/errors/backtraces from the logs

Note: https://github.com/dbeaver/dbeaver/wiki/Log-files is now wrong for OS X DMG installations. Logs are at:
```
~/.dbeaver4/.metadata
```

The attached log will show this attempt(s) starting at `2019-09-12 10:58:35.342`. The host names have been anonymized for privacy.

```
2019-09-12 11:07:06.145 - Invalidate datasource 'my_hiveserver hive 2.1 10500' connections...
2019-09-12 11:07:06.347 - Operation failed. Retry count remains = 1
```

Log: [dbeaver.log](https://github.com/dbeaver/dbeaver/files/3606295/dbeaver.log)

**Comment by serge-rider** [comment]
This happens because Hive driver closes connection after the error. DBeaver thinks that connection was closed due to some network issues, tries to reopen it and to re-execute query again.

This behavior controlled by the following pref settings:
![image](https://user-images.githubusercontent.com/6398845/65062321-74343600-d984-11e9-8129-17fdf9f84d7b.png)

You can disable auto-recovery or reduce number of retries.

**Comment by mtdeguzis** [comment]
Thanks! I will test this ASAP. Thank you for the response.

**Comment by mtdeguzis** [comment]
Looks like turning this off did the trick. Curious why we would get 5 retries when ours was set to 1, but turning it off does indeed stop the resubmission of the job. Definitely a good piece of info for the Wiki if it's not already there.

**Comment by mtdeguzis** [comment]
I also have 1 here, but strange we get 5 retries when it is 1:
![image](https://user-images.githubusercontent.com/27829577/65146995-30284c00-d9eb-11e9-97c2-6bfb1fdf9106.png)

Though it fixes the issue overall.
I set this to 0 and retested.
