### ISSUE TITLE
XML editor not opening

### ISSUE THREAD

**Issue by yvfisch** [dbeaver/dbeaver#6738]
#### System information: 
- Operating system (distribution) and version
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.16299 Build 16299

- DBeaver version
Version 6.2.0.201909081341

- Additional extensions
SVG
Office

#### Connection specification:
- Database name and version
db2 9.x

- Driver name
don't know

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
I have a table within a db2 db that has a column of type XML.

When I try to edit/view the column content with shift+enter I get an exception:

class org.eclipse.ui.internal.ErrorEditorPart cannot be cast to class org.jkiss.dbeaver.ui.editors.content.ContentEditor (org.eclipse.ui.internal.ErrorEditorPart is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @37d146e6; org.jkiss.dbeaver.ui.editors.content.ContentEditor is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @27cb781)

#### Steps to reproduce, if exist:
Well, it happens all the time for xml columns 

#### Include any warning/errors/backtraces from the logs
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/3608679/dbeaver.log)
[dbeaver_details.log](https://github.com/dbeaver/dbeaver/files/3608680/dbeaver_details.log)

**Comment by serge-rider** [comment]
Thank you for the bug report. This seems to be a side effect of some other error (e.g. network communication failure) happened during XML content loading from the server side.
In any case we need to handle such error properly.

**Comment by uslss** [comment]
verified
