### ISSUE TITLE
Compare only structure cannot detect datatypes diferences

### ISSUE THREAD

**Issue by vicsanca** [dbeaver/dbeaver#6739]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04
- DBeaver version:  6.2.0.201909081341
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 10
- Driver name: postgresql jdbc 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
"Compare only structure" don't detect different datatypes. Unchecking "Compare only structure" detects it but shows too much irrelevant information. Datatypes are part of structure.

#### Steps to reproduce, if exist:
Compare two tables, one with int4 and another with int8

**Comment by uslss** [comment]
Thanks for the bug report!

**Comment by uslss** [comment]
expected behaviour
