### ISSUE TITLE
inconsistent File loading: file->open and SQL Editor->load script have different results

### ISSUE THREAD

**Issue by pgutsche** [dbeaver/dbeaver#6740]
#### System information: 
- Operating system (distribution) and version
Microsoft Windows 10 Enterprise
Version	10.0.16299 Build 16299

- DBeaver version
  DBeaver	6.2.0.201909081341	org.jkiss.dbeaver.core.product	null
  German language setting
  
#### Connection specification:
- Database name and version
Postgres  9.5.4

#### Describe your question:
I have a SQL File containing a German special character. 
File is UTF-8 encoded. 
(only content is the following line:
select 'Dokumenten Konto Abschluß und Bescheinigung' ;
-- note the last character from the third word.)

With DBeaver text encoding preferences  Cp1252 or ISO-8859-1 the following happens:

File loading behaviour is different when I use File-Open Menu or SQL-Editor Load Script 
If I use File-Open Method text is displayed in the SQL Editor correctly the special character ß is valid.
as a second step I have to connect the SQL Editor then to a database and can run the statement.

If I use a running SQL Editor (connected to the same DB) and use SQL-Editor-> Load script 
The file is loaded, but the special Character is NOT recognised/diplayed correctrly.

With DBeaver text encoding preferences UTF-8 both ways do NOT work.

Is this something with my preferences messed up, or is this a bug?

![resultsAndPreferences](https://user-images.githubusercontent.com/55281608/64862748-98fe7580-d633-11e9-87e0-33d788e6a187.jpg)

[example.zip](https://github.com/dbeaver/dbeaver/files/3610043/example.zip)

**Comment by uslss** [comment]
issue is already fixed.
ticket closed
