### ISSUE TITLE
Map not displaying in the Map Panel

### ISSUE THREAD

**Issue by Chunkford** [dbeaver/dbeaver#6742]
Hi,
I have MULTILINESTRINGS in a table.
I can view the lines in the map panel but with no map layer underneath, just a grey background.

![Selection_032](https://user-images.githubusercontent.com/11464425/64877824-11703100-d64a-11e9-8a04-f97fab126f95.png)

The SRID being used is 27700 (British National Grid), could this be the reason why no map is being show as when I change it to 4326 I do get a map but the lines are not positioned correctly, which is to expected?

**Comment by serge-rider** [comment]
The library we use for CRS transformations (CTS from Orbis) doesn't support 27700->4326 conversion. I hope it will some day.

If you are on PostgreSQL then you could use Postgis conversion function ST_Transform (it is smarter than cts).
For example
```sql
SELECT ST_Transform('SRID=27700;POINT(258647 665289)'::geometry, 4326)
```
