### ISSUE TITLE
Extra blank line on XML value with Auto Format

### ISSUE THREAD

**Issue by carragom** [dbeaver/dbeaver#6744]
#### System information: 
- Operating system (distribution) and version: Windows 10 v1903
- DBeaver version: 6.2.0
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgreSQL v11.5
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:

When using Auto-Format in the value panel, XML content gets an extra blank line. Auto-Format es great especially for the new JSON viewer so I would like to have it on all the time. But I have to switch back and forth because of this issue.

#### XML With Auto-Format

![image](https://user-images.githubusercontent.com/970403/64911457-3a8ed100-d6df-11e9-9b8b-1a62142c55bd.png)

#### XML Without Auto-Format

![image](https://user-images.githubusercontent.com/970403/64911482-98231d80-d6df-11e9-9da0-1fc79eba076e.png)

**Comment by serge-rider** [comment]
Thanks for the bug report. This happens when XML is already formatted.
I'll add extra processing to remove redundant whitespaces before indenting the xml. It may reduce formatting performance though.

**Comment by kseniiaguzeeva** [comment]
Verified
