### ISSUE TITLE
PG: foreign data wrappers configurator

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6745]
A wizard which will collect all virtual references to external databases and let user to configure FDW in PostgreSQL.
This wizard will generate SQL script which will:
- Generate CREATE EXTENSION
- Generate CREATE SERVER 
- Generate CREATE USER MAPPING 
- Generate CREATE FOREIGN TABLE(s)

It will allow to copy result script or to execute it.
It must take into consideration all available/installed extensions, available foreign wrappers.
It must support all (or as many as possible) known FDW plugins.

**Comment by serge-rider** [comment]
Alpha version is ready.
Additions:
- Check already mapped foreign tables
- Add mapping script execution
- Add "Copy script" button
- Add extra foreign wrappers configs
- Add table options (?)

**Comment by uslss** [comment]
verified for clickouse - PostgreSQL
