### ISSUE TITLE
Refreshing a connection throws an error

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#6747]
#### System information: 
- Operating system (distribution) and version - mac os
- DBeaver version 6.2.0
- Additional extensions

#### Connection specification:
- Database name and version - postgres 11.4
- Driver name - default
- Do you use tunnels or proxies (SSH, SOCKS, etc)? -no

#### Describe the problem you're observing:
Right click a connection itself (not a db/schema) and click "Refresh"
![image](https://user-images.githubusercontent.com/18515297/64921458-02b18780-d7cc-11e9-89d1-d768e4f95826.png)
The DB actually has 4 databases.
Also there's a typo - should be `found` instead of `fond`.

#### Steps to reproduce, if exist:
For some reason it happened to me a few times and now I can't reproduce (the image is legit though :) ) I will see if I can reproduce.

**Comment by uslss** [comment]
Thanks for the bug report.
Unfortunately, I can't reproduce the issue. It'll be rather good if you reproduce the issue and steps will become clearer :)
