### ISSUE TITLE
SQLite automatically convert datetime data into UnixEpoch values

### ISSUE THREAD

**Issue by Dookie78** [dbeaver/dbeaver#6749]
I have a table in MSACCESS which contain a DateTime column. when i export this table to a SQLite table, Dbeaver automatically convert the Datetime Data into Epoch values. Any way to control these conversion???

**Comment by serge-rider** [comment]
Technically SQLite doesn't support DateTime data type. SQLite driver converts all date/timestamp values into epoch time. It is the default behavior. As far as I know it is not possible to change it.

You can with with epoch time in SQLite as with dates, there are special conversion functions for that.

If you want to persist timestamps in form of strings then you need to convert datetime columns on MSAccess side (using some datetime conversion function). For example:
```sql
SELECT COL_DATETIME || '',COLUMN2,COLUMN3 FROM NEW_TABLE;

SELECT CStr(COL_DATETIME),COLUMN2,COLUMN3 FROM NEW_TABLE;
```
