### ISSUE TITLE
Field mapping does not work when exporting from redshift to mongo db

### ISSUE THREAD

**Issue by maimike** [dbeaver/dbeaver#6750]
**Step to reproduce**
Export redshift to mongodb
Put mapping: example clientname to client_name
Export
**Expected:**
Data export to mongodb with filed client_name
**Actual:**
Data export to mongodb with filed clientname

**Comment by uslss** [comment]
Thanks for the bug report.
Unfortunately, I cannot reproduce the issue.
@maimike , could you clarify steps or add some additional info that helps reproduce the issue?

**Comment by uslss** [comment]
there is no updates on ticket more than a month. Ticket closed.
If issue still actual for you feel free to reopen the ticket and add some additional info
