### ISSUE TITLE
Forced query cancel

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#6755]
I see many threads asking for query cancel to work in environments where that's impossible due to the lack of support on the driver/server side.

What DBeaver **could** do, however, it to turn the ”cancel query” button into a ”force disconnect" button after the first click, instead of disabling it. Clicking on that button should show a dialog reminding the user that clicking that button will disconnect DBeaver from the query, but the query might continue running on the database server.
Confirming that will unlock DBeaver interface allowing it to be used for other queries.

This looks like an easy enough fix (although i don't know how much control you have on that button), and will give people what they care about, which is often not query cancel but the ability to run a new query.

**Comment by serge-rider** [comment]
In fact it already works exactly as you described. If query cancel doesn't actually cancel it then DBeaver tries to cancel whole connection.

This is controlled by following pref option:
![image](https://user-images.githubusercontent.com/6398845/65030529-62cd3880-d948-11e9-851c-9c7f13349a65.png)

Meaning of this parameter: when query cancel operation takes longer than this value (ms) DBeaver will close whole connection.

By default it was set to 0 (= disabled). Perhaps we should change it to some reasonable value..

**Comment by p91paul** [comment]
my suggestion is for more manual version of that. Setting a timeout is difficult because sometimes you deal with a query which actually takes a long time to cancel (e.g. needs to rollback a large update) while sometimes you deal with a select you don't care about. If you reclick on the button you clearly state your intention instead.

**Comment by rdp** [comment]
Wow that works perfectly.  I was about to suggest something similar (Postgres "cancel" commands sometimes get lost if network is down or flakey, resulting in indefinitely running query with no ability to cancel it).  After "x" seconds of a cancelled query not working, change button from greyed out "canceled" to a new button "force disconnect" or add a new button or what not.

**Comment by brent-kelly-vt** [comment]
Bumping this issue. In our instance, this bug dynamic is related to: VPN connection to AWS Redshift 

I have not messed with the Error Handling or SQL Processing settings, but "Cancel execution" [after 10000 ms] seems like a workable solution, provided it doesn't leave the execution hanging server side.

Does closing the dBeaver application locally also prompt the server side execution to end?

**Comment by brent-kelly-vt** [comment]
Just updated to 6.3.5 and it seems it may be fixed?!? Hopefully not getting too excited too early, but this is a big help if resolved. Thanks to DBeaver dev team!

**Comment by Lonniebiz** [comment]
I submitted a new issue that focus more on @p91paul 's ultimate conclusion rather than what's said in his initial post:
https://github.com/dbeaver/dbeaver/issues/9272

**Comment by p91paul** [comment]
thanks for reopening, I didn't notice my issue got closed!
