### ISSUE TITLE
how to view SQL behind a View in DBEAVER

### ISSUE THREAD

**Issue by gut839** [dbeaver/dbeaver#6756]
#### System information: 

- DBeaver version 5.3.5

#### Describe your question:

Hi - i am new to coding.

I have an infolink for spotfire that is a View.

When i bring up this view in DBEAVER - how do i see what the sql code is that actually generates this view?

thanks in advance!!

**Comment by serge-rider** [comment]
What database do you use?

Usually view source is on DDL or source tab. But for some databases it is not supported.

**Comment by uslss** [comment]
there is no update on ticket for a long time.
ticket closed

**Comment by AdySouza** [comment]
na versão 24.1
clique com o botão direito na view 
selecione GERAR SQL > DDL
o conteúdo da view, o sql do resultado é apresentado

**Comment by dofire** [comment]
translation for @AdySouza comment in english:
```
in version 24.1
right click on the view
select GENERATE SQL > DDL
the content of the view, the result sql is presented
```
