### ISSUE TITLE
Annoying backtick after autocompleting columns

### ISSUE THREAD

**Issue by elessartd** [dbeaver/dbeaver#6758]
HI. After upgrading to dbeaver 6.1.5-2, columns autocomplete automatically adds backtick. Is there a way to disable this feature? 

See attachement.

![Screenshot_20190917_122028](https://user-images.githubusercontent.com/5447223/65033601-a1152880-d945-11e9-853c-0a878aec2adc.png)

**Comment by uslss** [comment]
Hi @elessartd 
could you add some additional info like type of database? do you have any special settings for SQL editor or all settings are "Default"?
Waiting for your response

**Comment by elessartd** [comment]
Thanks for the reply. currently i'm using two databases. The first one uses mariadb driver 1.1.5 and the latter myqsl driver 8.0.11. Regardings the editor settings i use default settings

**Comment by uslss** [comment]
Probably, issue is fixed in scope of #7895 .
Ticket will be closed.
If issue is still actual for you, feel free to reopen the ticket
