### ISSUE TITLE
[BUG but crazy] - Right mouse click not working sometimes

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6760]
Hellooooo!!!
i posted some bugs already in the past, many were true bugs, so i might say i have a small reputation, no?
Now, this bug is imbarassing... :-D
So, this is imbarassing and i will receive tons of "cannot reproduce"...
But on Ubuntu Mate 18.04 (latest), DBeaver 6.2.0 (i think previous was affected), when right-clicking on an element in the database navigator (eg, a table, view, whatever), i have _sometimes_ to fire the right clich 2 or 3 times... 
Sorry, sounds crazy, but maybe i am ont alone in this problem...
If so, again, sorry, ignore this :-D

**Comment by serge-rider** [comment]
It is not crazy. And we already have similar bug report (in fact it is a dup of #6489)
Indeed, it is not easy to reproduce it, this happens only on some Linuxes in certain circumstances.
Trying to find a way to reproduce this in dev environment.
