### ISSUE TITLE
(minor) "go" in table name breaks "Execute SQL Statement" keyboard shortcut

### ISSUE THREAD

**Issue by SliceThePi** [dbeaver/dbeaver#6761]
#### System information: 
- OS: Linux Mint 19.2 MATE
- DBeaver version: 6.2.0
- Additional extensions: None

#### Connection specification:
- Database name and version: Not sure off the top of my head, but doesn't matter as this is a GUI issue
- Driver name: Azure SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: I don't think so, but there could be some network stuff that our db team is doing that I'm not aware of.

#### Describe the problem you're observing:
When hitting the keyboard shortcut for "Execute SQL Statement," 

#### Steps to reproduce, if exist:
Create a table with "go" in the name (i.e. "categories" or something), then type a one-line query using that table name and hit CTRL+Enter with your cursor at the end of the line (or anywhere after "go").

The query sent to the server will start just after the "go" and will likely throw a syntax error.

Actually creating the table is optional, since this error happens before reaching the server.

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by serge-rider** [comment]
Reealy weird bug. I'm surprised that nobody reported it before - it is an old one.

Thanks for the bug report!

**Comment by uslss** [comment]
verified
