### ISSUE TITLE
No way to use jConnect setMaxRows using fetch size configuration (especially useful for UPDATE/INSERT)

### ISSUE THREAD

**Issue by attachedx** [dbeaver/dbeaver#6762]
**Is your feature request related to a problem? Please describe.**

Most other DB UI Tools allow to set a LIMIT that is achievable by jdbc setMaxRows function. Its not available in DBeaver (using it for jConnect Sybase, this is already available in Squirrel which is otherwise an inferior tool in nearly every way to dBeaver)

Its a great feature to keep setMaxRows (that is something user can control like from the slot for Fetch Size), especially when logging into production and inadvertently running any update by mistake. This limits the damage caused. and is ALSO highly useful while doing huge updates. currently the Fetch size only limits the rows read -NOT the rows updated.

**Comment by serge-rider** [comment]
Well, DBeaver always call setMaxRows on SELECT statements whenever you execute any query or view table data.

But it never calls it on UPDATE or DELETE statements. This was made on purpose because in some drivers (e.g. SQL Server or Sybase) it limits number of updated/deleted rows - and this is not what users usually expect. Sometimes you need to update many more rows than fetch size, sometimes you need to delete all rows in a table, etc.

So, this is very controversial feature request. How do you see this feature? In what cases we should set max rows and in what cases we shouldn't?

**Comment by attachedx** [comment]
I believe a user controllable fetch size slot is the best feature to have isnt it? No conditional check behind the scenes by DBeaver, but user controls the limit of rows (and is consistent across update/insert/delete)

When user wants to update/delete everything they simply remove the number or make it zero in the grid slot with fetch size provided. 

I'm surprised people are fine with just limiting data returned and do not care about the damage any update could cause by default.

This way a wrong SQL that runs on ALL rows will only be turned ON by user action. I really think this is most straight forward user controlled way of doing the maxrows functionality

**Comment by serge-rider** [comment]
Fetch size limits only number of read rows. Fetch == read.

There must be a different option to limit number of updated/deleted rows.
Note that most JDBC drivers don't use setMaxRows to limit number of updated rows. 
Most of databases don't even support such feature. 
JDBC API is quite clear about this - this parameter must affect only resulset size.

SQL Server/Sybase driver isn't JDBC API compliant here, so we added a workaround specifically for it.

In any case your SQL statement mustn't delete wrong rows. Sometimes even a single row delete can be catastrophic. So, general rules are:
- Don't delete wrong rows
- Use transactions (manual commit) on prod server
- Validate your changes before commit
- Backup your databases

Limiting amount of damage by this fetch size is a very-very bad and fragile way to protect your data.

So I'm still unsure about this FR. There is no general solution for it anyway. 
Making SQL Server driver behavior different than other databases doesn't look like a good idea after all.
