### ISSUE TITLE
Unable to automatically terminate connection

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6763]
When HIVE queries, it is found that there are too many join threads, which cannot automatically terminate threads, resulting in resource occupation!

#### System information: 
- Operating system (distribution) and version  win10 64bit
- DBeaver version   6.20
- Additional extensions

#### Connection specification:
- Database name and version    HIVE 1.1.1
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
You can cancel running queries in Hive (if you are using standard Apache hive driver).
Also DBeaver cancels all running queries on disconnect. 
Could you write any steps to reproduce this problem?

**Comment by Pengchenghua** [comment]
I can't find IT, IT maintenance staff told me not to use this software, which occupied the background resources seriously

**Comment by Pengchenghua** [comment]
> You can cancel running queries in Hive (if you are using standard Apache hive driver).
> Also DBeaver cancels all running queries on disconnect.
> Could you write any steps to reproduce this problem?

![image](https://user-images.githubusercontent.com/26621087/65165549-98ba0c00-da71-11e9-97a9-be644c16baf0.png)
When the software is shut down, the connection thread ends 5 minutes faster

**Comment by uslss** [comment]
is it still actual?
