### ISSUE TITLE
 45/5000 I can't connect dbeaver with firebird

### ISSUE THREAD

**Issue by felipeinpark** [dbeaver/dbeaver#6764]
#### System information: 
- Operating system Windows 10 - 64 bits 1809 Comilation 17763.720
- DBeaver version = 6.2.0.201909081341

#### Connection specification:
- Database name and version
WI-V2.5.9.27139 FIREBIRD 2.5

#### Describe your question:

I am trying to connect to a firebird database that is running on a local server using dbeaver.

But I can't, I tested all available driver versions in dbeaver.

I always have this error
"I / O error during" CreateFile (open) "operation for file" D: \ CTBLI9 \ FDB / controller01.fdb: 3050 / C: \ firebird.dba "; Error while trying to open file; The filename, directory name, or volume label syntax is incorrect [SQLState: 08001, ISC error code: 335544344]
   I / O error during "CreateFile (open)" operation for file "D: \ CTBLI9 \ FDB / controller01.fdb: 3050 / C: \ firebird.dba"
   I / O error during "CreateFile (open)" operation for file "D: \ CTBLI9 \ FDB / controller01.fdb: 3050 / C: \ firebird.dba"
     Error while trying to open file; The filename, directory name, or volume label syntax is incorrect. "

Follows print of the configuration.

Note, I have hidden the username and password in print

**Comment by felipeinpark** [comment]
follow print

![CONFIGURATION](https://user-images.githubusercontent.com/45456817/65066541-e7c14d80-d95a-11e9-9fb2-5db301c7ffc3.jpg)
![ERROR](https://user-images.githubusercontent.com/45456817/65066547-ec860180-d95a-11e9-9bf0-c5a5f23e41e0.jpg)

**Comment by uslss** [comment]
Hi @felipeinpark ,
could you try to replace backslashes in 'Path' and 'Host' with slashes? Probably it could help.
Waiting for your response.

**Comment by felipeinpark** [comment]
> Hi @felipeinpark ,
> could you try to replace backslashes in 'Path' and 'Host' with slashes? Probably it could help.
> Waiting for your response.

Thank you for your help.
Unfortunately, it did not work.
Do you think of any other solutions?

Thanks

**Comment by felipeinpark** [comment]
I solved the problem.
Just enter the ip on the host and the bank file address on the server.

Example.
Host: 192.168.1.1
path: C: /base/base.fdb

And the user must have permission on the bank directory.

**Comment by MauricioChavesDias** [comment]
For me it didn't work, I'm using a virtual machine Azure.
