### ISSUE TITLE
current_time does not equal network time

### ISSUE THREAD

**Issue by cyrnicolase** [dbeaver/dbeaver#6766]
#### System information: 
- os ubuntu18.04
- DBeaver version 6.2.0

#### Describe your question:

```
SELECT CURRENT_TIME;   
```
This query returns 15:51:18,  but the network time is 15:44:xx. Is my setting wrong ?

**Comment by uslss** [comment]
Hi @cyrnicolase ,
probably this issue could be caused by incorrect time settings on your DB server.

**Comment by cyrnicolase** [comment]
Hi @uslss ,
Thank you for your reply. I found the cause of the error. The machine's time is wrong
