### ISSUE TITLE
[Question/feature request] Where is configuratoin stored now?

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6768]
I lost this note in the 6.1.3 release note https://dbeaver.io/2019/07/31/dbeaver-6-1-3/
`New project configuration format was implemented. Main advantages: `

Which direcotories should i now backup to save my DBeaver configuration?
`$HOME/.local/share/.DBeaverData/workspace6/` is full of stuff i do not need to backup (logs, locks, plugins, ...)
old dir `$HOME/.dbeaver4/` seams ot be dead and gone, correct?

Could you please save logs, locks ands stuff in one dir, which again i do not need to backup, and *real* config files that help me bootstrap a new dbeaver install from scratch with no pain (logins, credentials, shortcuts, windows/tabs positions, ...) in one dir, which basically will be the only dir i will need to backup? Pretty please... :-)

**Comment by p91paul** [comment]
well, old .dbeaver4 did contain logs as well...

**Comment by p91paul** [comment]
well, old .dbeaver4 did contain logs as well...

**Comment by serge-rider** [comment]
https://github.com/dbeaver/dbeaver/wiki/Workspace-Location

**Comment by wiwwo** [comment]
> https://github.com/dbeaver/dbeaver/wiki/Workspace-Location
$XDG_DATA_HOME is not a standard defined env variable (Ubuntu Mate 18.04)

> well, old .dbeaver4 did contain logs as well...
Yes, correct. Which means, i backup useless stuff in order to have a working backup.
Putting logs in one path/subdir, and just configuration in another, will allow me not to backup log files, which i don't need i case i have to restore my machine/installation.
PLUS, those file tend to be very big in size; i would like ot have a "single" and "safe" plain i could tell `logrotate` or whatever script to cleanup/rotate/delete/whatsoever

:-)

**Comment by snakyjake1** [comment]
Wish this was configured in the UI.

**Comment by serge-rider** [comment]
@wiwwo It is `~/.local/share` if XDG_DATA_HOME not set (just fixed the wiki page, thanks for noticing)
@snakyjake1 You can change default location by passing `-data path` command line parameter (or add it in dbeaver.ini file)

**Comment by serge-rider** [comment]
Regarding original question:
Workspace contains all the stuff (including working files). You can skip `metadata` folder if you don't need it. Also all dbeaver configs may be placed in different projects. Eg. you may have one local project + several shared projects (cloned from Git). All projects reside in workspace folder. Default project name if `General`.
So if you don't use multiple projects you can backup just folder `workspace6/General`.

**Comment by Binly42** [comment]
> Workspace contains all the stuff (including working files). You can skip `.metadata` folder if you don't need it. 

Tested the shortcut config is stored in the file:
`DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi`
...
