### ISSUE TITLE
PostgreSQL : Autocompletion with schema

### ISSUE THREAD

**Issue by dudul08** [dbeaver/dbeaver#6769]
Hi,
With version 6.2.0, I have to add the schema name in front of the table name for the completion to work.
However, the default schema is well selected.
I wasn't supposed to do it with version 6.0.0.
Thank you in advance for your help.

![capture_db](https://user-images.githubusercontent.com/16609450/65130710-41c71f00-d9fe-11e9-8d7e-e325da569be0.JPG)

**Comment by uslss** [comment]
isn't reproducible anymore. ticket closed
