### ISSUE TITLE
Erd diagrams: not fully export png

### ISSUE THREAD

**Issue by damienpolizzi** [dbeaver/dbeaver#6772]
Linux debian 10
Dbeaver 6.2
Postgresql 11

#### Describe the problem you're observing:
When I try to export erd diagrams to png format, sometimes the diagram is not fully export

#### Steps to reproduce, if exist:
Makes a diagram with tables containing a few tables with columns
- try to export to png
- moves the tables and try to export again... a few times
You will see that, depending of the position of tables, sometimes the diagram is fully printed, sometimes not.

**Comment by uslss** [comment]
still actual (6.3.2)

**Comment by serge-rider** [comment]
Duplicate of #7300
