### ISSUE TITLE
[BUG] scrolling down with mouse wheel on results panel grid makes it jump to the first row

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6774]
Not selecting any row in results panel grid; limit to 40 rows (don't know if this matters).
If i scroll down on results, when i get to he end of the "paging" (as said, 40th result), new dataset is load, BUT jumps panel grid goes to the first result, does not continues scrolling.

Mate 18.04, DBeaver 6.2.0

**Comment by wiwwo** [comment]
Correction: not "first row", but "row hilighted", "row selected", however you want to say that... :-D

If i click on a cell in the 10th row, scrolling down will bring the results panel back at 10th row

**Comment by uslss** [comment]
is it still actual?

**Comment by wiwwo** [comment]
Seems being fixed
