### ISSUE TITLE
Cancelled data filter views

### ISSUE THREAD

**Issue by rdp** [dbeaver/dbeaver#6777]
OS X DBeaver	6.2.0.201909081341

#### Connection specification:

Postgres, no tunnels

#### Describe the problem you're observing:

Cancelled filters can't be run again.

If you go to a table "data" tab, select a "filter", start it, then hit "cancel" it says "SQL Error [57014]: ERROR: canceling statement due to user request" which is right.  However you cannot "run it again" to "try again" since the "run" icon button is greyed out after that point.  It is confusing.  Thanks.

<img width="613" alt="Screen Shot 2019-09-18 at 9 55 49 AM" src="https://user-images.githubusercontent.com/12496/65164639-8650bb80-d9fa-11e9-8018-3ea1874c73e6.png">

**Comment by uslss** [comment]
is it still actual?

**Comment by rdp** [comment]
after glancing at it, seems it may be fixed now, I'll reopen if I run into it, thanks!
