### ISSUE TITLE
Read epxensive properties (row count) on demand.

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6778]
For now we have pref option "Show row count for tables".
It is disabled by default by performance reasons (it may overload server cpu by just clicking on different tables).
But sometimes you need these properties for a particular table.
We can add extra command "Read statistics" or "Read row count" in table editor toolbar. It will read expensive props for current editor only.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/65593884-25952600-df9a-11e9-91b5-a9a0a64bdab6.png)

**Comment by kseniiaguzeeva** [comment]
Verified
