### ISSUE TITLE
PostgreSQL 11 - Can't edit JSON column

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#6779]
Hi Serge

Using DBeaver 6.2.0 on Mac I run into an error when trying to edit a json column in the JSON Editor.

I have set up a table as follows:

create table tjson(myid int8, myjson json);

alter table tjson add primary key (myid);

select * from tjson;

Then I inserted a new record using the editor. After that I tried to edit the record and get the following error when trying to save using the save button on the bottom left:

![image](https://user-images.githubusercontent.com/38714600/65176678-921d9b80-da55-11e9-91e3-65b8839814a1.png)

**Comment by serge-rider** [comment]
Just refresh database metadata before editing the table (<kbd>f5</kbd>) on your schema in database navigator tree. Or reconnect.

**Comment by JamesInform** [comment]
Already did.

But it is still not working. I am getting the same error even after completely restarting DBeaver.

What can I do to help you digging into this issue?

**Comment by JamesInform** [comment]
Hi Serge!

I digged a little bit deeper into the issue and have now identified the cause.

In my example I have a simple table WITHOUT a primary key. So when you generate an update statement you take all columns and do something like this:

`UPDATE public.tjson
	SET myjson=$1
	WHERE myid=$2 AND myjson=$3`

But PostgreSQL has no built-in compare for JSON, so the

`myjson=$3`

throws an error

`operator does not exist: json = unknown`

If you want to compare JSON type columns, you need to cast them as JSONB (or as text):

`UPDATE public.tjson
	SET myjson=$1
	WHERE myid=$2 AND myjson::jsonb=$3::jsonb`

Then everything works as expected.

Hope this helps!

**Comment by felipebraga** [comment]
I think this is a bug, since I can't copy, set null or edit a column with jsonb

**Comment by LonwoLonwo** [comment]
We have auto-casting in DBeaver 21.0.2 for jsonb columns.

![2021-04-14 11_01_57-Window](https://user-images.githubusercontent.com/45152336/114675674-2f63b300-9d11-11eb-9418-9d1f75578f2b.png)

**Comment by LonwoLonwo** [comment]
Closed as duplicate https://github.com/dbeaver/dbeaver/issues/11704
