### ISSUE TITLE
[Bug][Oracle] PL/SQL Create or replace Package semicolon lost when end is annotated

### ISSUE THREAD

**Issue by DragonStorm97** [dbeaver/dbeaver#6782]
#### System information: 
 - Windows 10
- DBeaver 6.1.2

#### Connection specification:
- Database Oracle 12C
- Oracle

#### Describe the problem you're observing:
When writing a package, if an end statement is annotated with the name of the package, the semicolon is lost.
#### Steps to reproduce, if exist:
Running the following will result in the semicolon being lost (and the package failing to compile):

```
create or replace package test_missing_semicolon is

end test_missing_semicolon;
create or replace package body test_missing_semicolon is

end test_missing_semicolon;
```

The following works fine:

```
create or replace package test_missing_semicolon is

end;
create or replace package body test_missing_semicolon is

end;
```

**Comment by serge-rider** [comment]
Must be fixed by now.
