### ISSUE TITLE
DB2: table name field remains editable after creation

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6785]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.1 CE

#### Connection specification:
- Database name and version db2/zOS

#### Describe the problem you're observing:
Table name is available for editing after table creation, but changes couldn't be saved. Issue isn't reproducible after reopening table
#### Steps to reproduce, if exist:
1. Create table with columns and save it.
2. Change table name.
3. Save changes - Save button is greyed. Changes cannot be saved. After reopening - issue disappears.
![table_ren](https://user-images.githubusercontent.com/31996417/65376864-e91dad80-dcad-11e9-8235-b646eecc65ae.gif)

**Comment by serge-rider** [comment]
It use DB2 for zOS driver. You must use DB2 LUW for this database.
Anyhow, name remains editable because you can rename table after creation.
