### ISSUE TITLE
DB2: autoinc option for column cannot be saved

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6786]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.1 CE

#### Connection specification:
- Database name and version db2/zOS

#### Describe the problem you're observing:
Autoinc column becomes unchecked after saving changes
#### Steps to reproduce, if exist:
1. Create int column and check Autoincrement option 
2. Save changes and check mentioned option - it is unchecked
![autoinc](https://user-images.githubusercontent.com/31996417/65376919-9ee8fc00-dcae-11e9-937d-db2fc5291ac4.gif)

**Comment by serge-rider** [comment]
You can't use DB2 zOS driver for LUW database.
