### ISSUE TITLE
db2: some on delete/on update option cannot be saved when trying to create FK

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6788]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.1

#### Connection specification:
- Database name and version db2/zOS

#### Describe the problem you're observing:
When trying to create FK and set 'Set Default' option for On Delete FK couldn't be created.
Also FK couldn't be created when 'Cascade' OR 'Set NULL' or 'Set default' option is chosen for 'On update'

**Comment by serge-rider** [comment]
You must use LUW driver
