### ISSUE TITLE
SAP HANA support improvements

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6791]
Support of Query Planner, structure assistant, synonyms, error recovery and system views.
Most of this was contributed by https://github.com/kai-morich in https://github.com/dbeaver/dbeaver/pull/6780

**Comment by kai-morich** [comment]
I can see my changes in 6.2.1 source-code.zip, but the binary version includes the old org.jkiss.dbeaver.ext.hana_1.0.46.201909221630.jar 

ok for me, if my feature comes with 6.2.2 because then I have additional time to add more functionality, but is this source vs. binary mismatch intended?

**Comment by serge-rider** [comment]
@kai-morich Branch `devel` contains all recent contributions. But for version releases we use separate branches (e.g. `release_6_2_1` which was created a few days before the release). 
So, yes, HANA improvements will be released along with 6.2.2.

**Comment by kai-morich** [comment]
I assume you built binaries from release_6_2_1 branch, but you put the '6.2.1' label on latest change in devel branch. this very likely caused the mismatch between binaries and source-code.zip

I just wanted to inform you about that observation, to avoid issues if you or someone else later want's to rebuild this version

**Comment by serge-rider** [comment]
Yes, there is an inconsistency. When we do release we create a tag on the default branch (devel), sources and binaries archives are made from devel branch. While real DBeaver releases (e.g. on dbeaver.io or in Github release artifacts) are made from special release branches.

In fact some 3rd party dbeaver distributions are based on tags in devl branch and it is a problem. We still not sure how to do this better.

Anyhow, you don't need release branches during development. Use devel branch only.

**Comment by p91paul** [comment]
why don't you tag the release branch then? even if you later destroy the branch, the tag will remain there pointing to the right commit.

**Comment by serge-rider** [comment]
@p91paul Yes, we will tag release branches starting from the next release. It will require to name release branches in a very strict way but we can deal with it.
