### ISSUE TITLE
No default column values in the generated DDL 

### ISSUE THREAD

**Issue by FredNM** [dbeaver/dbeaver#6793]
System information:
 * Operating system (distribution) and version: Windows 10
 * DBeaver version: 6.2.0

Connection specification:
 * Database name and version: PostgreSQL-11.5.1-windows-x64 
 * Driver name: org.postgresql.Driver 
 * Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

Describe the problem you're observing:
Generate SQL DDL does not adds column default values into create table script.

**Comment by sspam60** [comment]
I have a same problem: 
DBeaver version: 6.2.2.201910072100
Database: Microsoft SQL Server 2017 (RTM-GDR) (KB4293803) - 14.0.2002.14 (X64)

**Comment by uslss** [comment]
issue isn't reproducible.
ticket closed
