### ISSUE TITLE
Auto-commit and isolation level are not selected properly in connection settings

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#6794]
- Operating system (distribution) and version Windows 10 home
- DBeaver version 6.2.1
- Additional extensions xls

#### Connection specification:
- Database name and version MySQL 8
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? yes

#### Describe the problem you're observing:
1. changes in auto-commit checkbox are skipped after pressing "test connection" btn (way: connection settings>initialisation)

2. values in "isolation level" window are doubled if to select some value, press "test connection", and then open "isolation level" window again (way: connection settings>initialisation)

Thank you in advance!

<img width="960" alt="isolation level" src="https://user-images.githubusercontent.com/51405061/65385940-a1defd80-dd3d-11e9-9547-1585b7580f41.png">

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
