### ISSUE TITLE
retry object lookup if not found, or at least offer the "retry" option to the user

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#6795]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when...  objects (tables, functions, views etc.) created outside of dbeaver (say through flyway upgrades) are not found with F4/go to definition. dbeaver fails to find them unless I do a refresh.

**Describe the solution you'd like**
If not found, DBeaver should do a metadata lookup and return an error if indeed the object is not found instead of immediately returning an error if the object is not in the cache. If not already the case (did not check) - the same should apply for objects no longer existing - they should be checked against the DB and removed from the cache if really missing.

This can be an option in the preference letting user to choose whether to auto lookup if not found (yes! yes!) or not. Or if you're really scared about performance implications - add a "retry" button on the "Find object node by reference" not found pop up.

**Describe alternatives you've considered**
Having to refresh the schema/functions multiple times a day is not fun.

**Additional context**
'Find object node by reference' not found in schema 'myschema'
Table 'mytable' not found in schema 'myschema'

**Comment by pyrocks** [comment]
@serge-rider Bump. Lately dbeaver more often than not fails to find an existing object. 
It may be related to switching vpns, switcing DBs, creating/dropping objects - not sure what causes it - but it is **really frustrating**.
Pretty please add a configuration option to always lookup the object in the DB if not found.

**Comment by uslss** [comment]
probably, will be fixed in the scope of #6398

**Comment by uslss** [comment]
closed as #6398 duplicate
