### ISSUE TITLE
SQL2000 Can not get DDL of the VIEW

### ISSUE THREAD

**Issue by wuqingxiang2225** [dbeaver/dbeaver#6796]
OS Version Windows10
DBeaver Version 6.2.1
Database SQL Server 2000 sp4

When I try to get DDL of the VIEW
They refer to me "/* ERROR WHILE READING SOURCE:
SQL 错误 [2812] [37000]: 未能找到存储过程 'sys.sp_helptext'。
*/"

**Comment by uslss** [comment]
is it still actual?

**Comment by wuqingxiang2225** [comment]
Yes it is.

**Comment by wuqingxiang2225** [comment]
And now the DBeaver Version is 6.3.2

**Comment by LonwoLonwo** [comment]
Can't reproduce
![2020-11-17 12_34_10-DBeaver Enterprise 7 3 0 - emp_35000](https://user-images.githubusercontent.com/45152336/99372504-4f618880-28d1-11eb-8d24-9bb3ca9622cc.png)
Can you please try execute this query "SHOW CREATE TABLE TableName" with name of your view?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional details.
