### ISSUE TITLE
Sqlserver adds table fields, field description are lost when saving

### ISSUE THREAD

**Issue by leihenshang** [dbeaver/dbeaver#6797]
#### System information: 
- Operating system (distribution) and version
win10 1903
- DBeaver version
6.2.1
- Additional extensions
no

#### Connection specification:
- Database name and version
microsoft sqlserver 2012
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:
1.alter table
2.add fields
3.set description
4.save
5.result:There is no description

#### Include any warning/errors/backtraces from the logs
no warning/errors/backtraces

**Comment by uslss** [comment]
not reproducible anymore. closed
