### ISSUE TITLE
Last Export Parameter Not Saved

### ISSUE THREAD

**Issue by VrigaChabibi** [dbeaver/dbeaver#6798]
#### System information: 
- Windows 10 Pro x64 1903
- DBeaver version 6.2.1
- Darkest Dark Theme

#### Connection specification:
- PostgreSQL (Old)
- Intranet connection

#### Describe the problem you're observing:
After I updated from 6.2.0 to 6.2.1, every time I'm doing export result, the export parameter always set to the most default even though I changed it.

#### Steps to reproduce, if exist:
Just simply change the export folder.

#### Include any warning/errors/backtraces from the logs
No such thing.

**Comment by serge-rider** [comment]
Thanks for the bug report. I believe this bug was already fixed as a part of recent major changes in data transfer wizard. Fix will be included in the next version.

**Comment by kseniiaguzeeva** [comment]
Verified.
