### ISSUE TITLE
Last file export name/path not remembered

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#6805]
**Steps to reproduce:**
* Run some query.
* Export the result set in a non-default folder in CSV format.
* Run some other query.
* Try to export it with the same settings as the first query.

**Expected results:** should remember the last folder and file name, and use them as default settings.

**Actual results:** defaults to the default folder and default file name.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report. Such ticket already exists: https://github.com/dbeaver/dbeaver/issues/6798. The bug will be fixed in 6.2.2.
