### ISSUE TITLE
Change file name

### ISSUE THREAD

**Issue by Ferrox12** [dbeaver/dbeaver#6806]
Hello,
how can I change the name of my script in relation of the project I'm working about?
Es. project's name is "House"; when I save my sheet, DBeaver save it as "Script-1". Can i change the output name?

**Comment by serge-rider** [comment]
No, there is no such config option.
Probably we should add it. 
Any ideas what parameters we should use on new script names?

**Comment by Ferrox12** [comment]
I think this will be a big improvement of the software. For the moment I have no other ideas. Congratulations for the work you've done. Dbeaver in my opinion is the best SQL client that I have tried

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
If preferences are opened and closed with "Apply and close" button, file name pattern will be erased

![QdFfNheiZW](https://user-images.githubusercontent.com/82543000/145195790-617aeeff-e744-4f7e-b930-7bcc7e127bbe.gif)

**Comment by Matvey16** [comment]
Verified
