### ISSUE TITLE
www.virustotal.com report dbeaver-ce-6.2.1-x86_64-setup.exe Backdoor.AndroidOS.adxw

### ISSUE THREAD

**Issue by MarcoDelCorto** [dbeaver/dbeaver#6807]
#### System information: 
- Operating system (distribution) and version => Windows 10 Pro (10.0.17763 build 17763)
- DBeaver version => Community Edition 6.2.1 - Released on September, 23 2019 (Milestones).

#### Connection specification:
- Database name and version

#### Describe your question:
www.virustotal.com report dbeaver-ce-6.2.1-x86_64-setup.exe Backdoor.AndroidOS.adxw
Is it a false positive or better wait to install the new release?
thanks

**Comment by serge-rider** [comment]
I don't see it: https://www.virustotal.com/gui/url/2f3530d67427570b403059fc30637f34cb9dfbb1311db83a314945771968b32d/detection
All clean.

What exactly antivirus engine detects it?

**Comment by MarcoDelCorto** [comment]
[VirusTotal_1_of_68.pdf](https://github.com/dbeaver/dbeaver/files/3645577/VirusTotal_1_of_68.pdf)

antivirus engine: Jiangmin - see attachment (1 positive and 68 negative)

**Comment by MarcoDelCorto** [comment]
done a few seconds ago a new scan and now no viruses are highlighted. even the Jiangmin antivirus engine does not report any viruses (see attachment).
It was probably a false positive ...
[VirusTotal_0_of_64.pdf](https://github.com/dbeaver/dbeaver/files/3645632/VirusTotal_0_of_64.pdf)

**Comment by serge-rider** [comment]
Yep
