### ISSUE TITLE
Cannot restore backup with bytea column - "could not find block ID"

### ISSUE THREAD

**Issue by zbidwell** [dbeaver/dbeaver#6808]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro
- DBeaver version: 6.2.0
- Additional extensions: None

#### Connection specification:
- Database name and version
- Driver name: Postgres (9.6, 10.5, 11.2)
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No, I'm using a local postgres server.

#### Describe the problem you're observing:
restoring a backup of a table with a bytea column made with pg_dump or PgAdmin3 gives the error:
```
pg_restore: processing data for table "public.test"
pg_restore: [custom archiver] could not find block ID 2117 in archive -- possibly corrupt archive
```

This doesn't happen if the backup was made using DBeaver.

I've tried using different combinations of postgres versions (9.6, 10.5, and 11.2) when backing up and restoring, but it doesn't seem to make a difference.

#### Steps to reproduce, if exist:
create a database
right click -> tools -> restore
select the backup file in [test.zip](https://github.com/dbeaver/dbeaver/files/3643330/test.zip)
start

#### Include any warning/errors/backtraces from the logs
Nothing relevant shown in the error logs

**Comment by uslss** [comment]
reproducible 
```

> Task 'PostgreSQL restore' started at Wed Apr 22 16:43:44 MSK 2020
> pg_restore: [custom archiver] could not read from input file: end of file
> Task 'PostgreSQL restore' finished at Wed Apr 22 16:43:45 MSK 2020
> 2020-04-22 16:43:45.092 - IO error: Process failed (exit code = 1). See error log.
> 2020-04-22 16:43:45.093 - java.io.IOException: Process failed (exit code = 1). See error log.
> 	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:182)
> 	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:237)
> 	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:52)
> 	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
> 	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
> 

```

**Comment by uslss** [comment]
not reproducible anymore
