### ISSUE TITLE
Weird number's order in column filter  in data in view

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#6809]
#### System information: 
- Operating system (distribution) and version Windows 10 Home
- DBeaver version 6.2.1

#### Connection specification:
- Database name and version MySQL, Postgres, Oracle, Exasol
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  yes

#### Describe the problem you're observing:
Column filter of data view has weird number's order.

#### Steps to reproduce, if exist:
Open any table where a column with more then 20 numbers exists;
Click filter icon in the column header;
Scroll to see the number's order in the filter list.

#### Include any warning/errors/backtraces from the logs
<img width="960" alt="filtering numbers int" src="https://user-images.githubusercontent.com/51405061/65481048-95bd8200-de9c-11e9-91fd-93c6b77b22e4.png">

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
