### ISSUE TITLE
Drag to reorder result tabs

### ISSUE THREAD

**Issue by nicchristeller** [dbeaver/dbeaver#6810]
My general workflow involves a single editor, with the results of several queries open in several tabs below. I find the result tabs' UI generally lacking and non-intuitive (e.g. tab UX similar to modern browsers is the norm for most tabbed UIs, but the current implementation isn't anything like this).

One thing that I often find myself trying to do is simply dragging the tabs to change their display order. The only other option is to close the tabs and re-run the queries in the order I would like the tabs to be displayed.

**Comment by serge-rider** [comment]
Done

**Comment by uslss** [comment]
verified
