### ISSUE TITLE
Crash at startup (Eclipse CSS SWT Support)

### ISSUE THREAD

**Issue by Rafal1** [dbeaver/dbeaver#6811]
Hello, exactly at this point (screen) DBeaver disappears and starts work in background indefinitely. I updated yesterday to 6.2.0 and face this issue. I make an update to 6.2.1 today in hope that this solves the issue. I have Windows 7. 

![strtup](https://user-images.githubusercontent.com/3114927/65488926-60b82c00-deaa-11e9-9362-c1e592dec124.PNG)

**Comment by serge-rider** [comment]
Please attach error/debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by Rafal1** [comment]
Here is a log:

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3647206/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Thanks. 
Seems to be the same issue as in #5723. See for workarond in comments.

I'll add extra error handling to resolve problem with app start. But it won't fix the dashboard view.

**Comment by Rafal1** [comment]
This reset workspace procedure works for me, thanks for advice. You do a great job!

https://github.com/dbeaver/dbeaver/wiki/Reset-workspace
