### ISSUE TITLE
Columns that match SQL keywords are exported with extra quotes

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#6815]
**Steps to reproduce:**
* Execute a query that would produce column names that are SQL keywords, e.g.
```sql
select '1' as col1, '2' as "source"
```
(alternatively, don't enquote `source`)
* Export the result to CSV.

**Expected behavior:** the columns that match to SQL keywords should appear normally, e.g.
```
"col1","source"
"1","2"
```

**Actual behavior:** the columns that match to SQL keywords have extra quotes which are redundant in CSV format:
```
"col1","""source"""
"1","2"
```

**Comment by uslss** [comment]
Hi @david-cortes ,
could you add DBeaver version and connection type where issue appears?

**Comment by david-cortes** [comment]
> Hi @david-cortes ,
> could you add DBeaver version and connection type where issue appears?

Version: 6.2.1 and 6.2.0
Running on windows 10
Connecting to postgres (PostgreSQL JDBC Driver)
Exporting as CSV with UTF-8 encoding

**Comment by serge-rider** [comment]
Fixed
