### ISSUE TITLE
Error when execute search with metadata wizard

### ISSUE THREAD

**Issue by darlynvailatti** [dbeaver/dbeaver#6816]
I'm using version **6.2.1.201909221630**

The problem is when I execute some search in metadata objects, I'm receiving this message:

![ERROR_METADATA_SEARCH_WIZARD_DBEAVER](https://user-images.githubusercontent.com/12027058/65512933-9bbd5e00-deb0-11e9-9b20-b543d7835cee.png)

I saw in the release notes that this problem already solved, but actually it's persist.
![DBEAVER_RELEASE_NOTES_6 2 1](https://user-images.githubusercontent.com/12027058/65513201-39189200-deb1-11e9-96bf-cd76a4e2f220.jpg)

I tried to find the original issue but I could't, so sorry if this isse is duplicated.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report. The mistake appears for constraints and foreign keys in Oracle.
Error window:
"SQL Error [904] [42000]: ORA-00904: "CONSTRAINT_NAME": invalid identifier
Error : 904, Position : 81, Sql = SELECT  OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM ALL_VIEWS
WHERE CONSTRAINT_NAME like :1 , OriginalSql = SELECT  OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM ALL_VIEWS
WHERE CONSTRAINT_NAME like ?, Error Msg = ORA-00904: "CONSTRAINT_NAME": invalid identifier
ORA-00904: "CONSTRAINT_NAME": invalid identifier"

![ig9i7RK3T8](https://user-images.githubusercontent.com/51405061/74643534-ef915200-5185-11ea-9b61-143993081252.png)
[.log](https://github.com/dbeaver/dbeaver/files/4212994/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4212995/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
