### ISSUE TITLE
phoenix queries with UDF

### ISSUE THREAD

**Issue by eddie759** [dbeaver/dbeaver#6817]
I am not able to run queries against phoenix using user defined functions (UDF). A ClassNotFoundException is thrown for the class where the function is defined. Using plain java everything works as expected (The function has been created, phoenix.functions.allowUserDefinedFunctions and the path to the jar is set in hbase-client.xml).

Is there a way to get this working with dbeaver?

Windows 7
Dbeaver 4.2.2 (I know - a bit old but I have to use it currently. If this has been solved in newer versions just let me know)
Phoenix 5.0 (part of HDP 3.1.1)

**Comment by serge-rider** [comment]
Maybe you need to add jar with your UDF in driver classpath (on driver edit dialog).
