### ISSUE TITLE
[BUG] Create a root folder in Database Navigator is impossible

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6818]
Creating a connection folder in the root, or move an existing sub-folder to the root, is impossible...

**Comment by zanonjonascodes** [comment]
There is a workaround... Drag a connection to the root so that the connection is not in any folder. Then select it and click in the new folder icon.

**Comment by Chealer** [comment]
I confirm this bug in version 6.2.5.
This can be worked around as mentioned by @zanonjonascodes by selecting a connection which is outside all folders before creating the folder to put at the root.

**Comment by wiwwo** [comment]
What it i am a very organized person and i don't have any connection in the root?

**Comment by Chealer** [comment]
Then you need to move a connection there temporarily, or create one. Obviously, this only **works around** the problem.

**Comment by millsoft** [comment]
can confirm this in the latest version, but the above workaround works.

**Comment by ThaDaVos** [comment]
This is still bugged - when will this be fixed?

**Comment by uslss** [comment]
already implemented

**Comment by dankochetov** [comment]
I still have this issue on version 22.0.3.202204170718 - can't create or move new folders in the connections root. The same workaround still works.

**Comment by belspirit** [comment]
`CTRL + Left Click` to deselect the current folder or database in the tree and click `New Folder` button.

**Comment by battmush** [comment]
This is still an issue in Version 22.2.5.202211202223

**Comment by pgalbraith** [comment]
Still does not work
