### ISSUE TITLE
Oracle Quotated Strings Support

### ISSUE THREAD

**Issue by andrewwellsdfj** [dbeaver/dbeaver#6819]
Quoted strings are used heavily in oracle where the user doesn't want to have to double single quote around identifiers. Currently DBeaver does not support them and it breaks our scripts and prevents us from running anything with a quoted identifier in Dbeaver

Examples:
https://livesql.oracle.com/apex/livesql/file/content_CIREYU9EA54EOKQ7LAMZKRF6P.html

**Comment by serge-rider** [comment]
Currently you can use Q identifiers, but you need to select full query before executing it (as dbeaver can't parse it properly).

**Comment by serge-rider** [comment]
Generally it works now.
Please test this in Early Access version (https://dbeaver.io/files/ea).

**Comment by andrewwellsdfj** [comment]
Thanks for the quick addition of the feature. I ran several quick tests and they all worked great in the EA version.
