### ISSUE TITLE
open connections in navigator and editor not in sync

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#6824]
1) open db connection in "DB Navigator" view
2) expand tables tree
3) right click on a table and select "Read data in SQL console"
RESULT: editor with query opens, results are shown below
4) let sit for an hour or so
5) again, right click on a table and select "Read data in SQL console"
RESULT: an error popup with varying messages, all boiling down to that the connection to the DB has been lost
6) repeat again to no avail
7) go to previously opened editor with query and execute query
RESULT: a blue info popup about reestablishing connection and shortly after results appear
8) again, right click on a table and select "Read data in SQL console"
RESULT: basically same error

Issues here:
1) connections between editors and view need to be in sync
2) failing attempt from view should not produce empty editor, but at least contain query - or no editor at all
3) _all_ error popups here should contain a button to reconnect to DB

IMO it is not only inconsistent, but rightout dangerous that executing a query from a previously opened editor reconnects to DB and executes -- together with the still unexpected switching of active connections when just clicking another connection in the view, I more than once executed a query against the wrong DB.
Thankfully, so far I never destroyed any data, but that's been mostly luck.
I'll file another bug report against the changing DB connection of editors as well.

**Comment by kseniiaguzeeva** [comment]
Please tell your OS and Database.

**Comment by 2019-05-10** [comment]
Debian/SID
PostgreSQL

**Comment by uslss** [comment]
Cannot reproduce it for now
if the issue is still actual - feel free to reopen it
