### ISSUE TITLE
selecting different DB connection in view should not change DB connection of active editor

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#6825]
1) select DB connection in "DB navigator" view
2) expand tables
3) right click on a table and select "Read data in SQL console"
4) select a different DB connection in view
RESULT: the active DB connection of the active editor changed w/o notification

In 4) I just expand another DB to check the columns of a table, I do not expect that to change the connection I use in my active editor -- since the editor tabs are rather uninformative labelled, starting with host name, it is not easily spotted that the DB changed and you are in danger to run a potentially destructive query against the wrong DB, just because you innocently checked a different DB's structure.
I am using DBeaver for along time now, I know about that and yet, I constantly keep forgetting that, because it is so counter-intuitive.

See #6824 for a related rationale.

**Comment by uslss** [comment]
Hi @2019-05-10 ,
unfortunately, I can't reproduce the issue. Could you add video or gif to make steps clearer? Thanks in advance

**Comment by uslss** [comment]
ticket closed.
there is no update on ticket more than a month
