### ISSUE TITLE
Oracle XMLTYPE preview panel is broken since 6.2.1

### ISSUE THREAD

**Issue by LeoLozes** [dbeaver/dbeaver#6826]
#### System information: 
- Windows 10 18362.19h1
- dBeaver 6.2.1

#### Connection specification:
- Oracle Database 11g Release 11.2.0.3.0 - 64bit
- Oracle drivers (xdb6.jar, ojdbc7.jar, orai18n.jar, ucp.jar, xmlparserv2.jar)

#### Describe the problem you're observing:
When previewing a large XML field, an "Error loading text value" error appears on the bottom and the value tab in the preview panel is empty. 
When the XML is small (I guessed less than 4.000 chars) the preview works just fine. 

#### Steps to reproduce, if exist:
Query a table with an XMLTYPE column with more than 4.000 chars. Open the preview panel, observe that it's empty.  

The only related thing I can see in the logs is this:
```
!ENTRY org.jkiss.dbeaver.model 2 0 2019-09-25 11:03:12.202
!MESSAGE Unknown predefined type: XMLTYPE
```

**Comment by serge-rider** [comment]
Thanks for the bug report.

**Comment by uslss** [comment]
verified

**Comment by LeonardoDarkVinchi** [comment]
Still actual. 
System:
- Windows 10 19045.4170
- DBeaver 24.0.1.202403241413

Connection specification:
- Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
- Oracle drivers (xdb6.jar - 18.3.0.0 , ojdbc11.jar - 23.2.0.0, orai18n.jar - 23.2.0.0, xmlparserv2.jar - 18.3.0.0)

Same problem, same steps to reproduce.
