### ISSUE TITLE
Closing preview dialog closes whole application instead of just the dialog

### ISSUE THREAD

**Issue by tobias47n9e** [dbeaver/dbeaver#6827]
#### System information: 
- Operating system (distribution) and version: Linux, Ubuntu 19.04
- DBeaver version:  6.2.1.201909221630 (Flatpak)
- Additional extensions: -

#### Describe the problem you're observing:

Clicking on the "x" in the preview dialog closes the whole application. Pressing "close" only closes the dialog. Both buttons should only close the dialog.

Pressing "Escape" when this dialog is open also closes the whole application.

![preview_closes_window](https://user-images.githubusercontent.com/6953323/65587630-73a02e80-df86-11e9-8c89-56604f270993.png)

#### Steps to reproduce, if exist:

Change a cell, click on preview, press the "x".

**Comment by serge-rider** [comment]
This looks like an internal error, dbeaver process dies by some reason.
Please try to find JVM fatal log file (see last section in https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by tobias47n9e** [comment]
The DBeaver logs don't write anything when the crash happens. Journalctl has a detailed log:

Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: #
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: # A fatal error has been detected by the Java Runtime Environment:
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: #
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: #  SIGSEGV (0xb) at pc=0x00007f9b3dfdb5ad, pid=22, tid=23
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: #
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: # JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11)
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: # Java VM: OpenJDK 64-Bit Server VM (11.0.4+11, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: # Problematic frame:
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: # C  [libgobject-2.0.so.0+0x3a5ad]  g_type_check_instance+0x1d
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: #
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /home/tobias/core.22)
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: #
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: # An error report file with more information is saved as:
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: # /tmp/hs_err_pid22.log
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: Compiled method (c1)   45015 5245   !   3       org.eclipse.swt.internal.gtk.OS::g_object_get_qdata (32 bytes)
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]:  total in heap  [0x00007f9b4daec710,0x00007f9b4daecc88] = 1400
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]:  relocation     [0x00007f9b4daec888,0x00007f9b4daec8f0] = 104
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]:  main code      [0x00007f9b4daec900,0x00007f9b4daecaa0] = 416
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]:  stub code      [0x00007f9b4daecaa0,0x00007f9b4daecb78] = 216
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]:  oops           [0x00007f9b4daecb78,0x00007f9b4daecb80] = 8
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]:  metadata       [0x00007f9b4daecb80,0x00007f9b4daecb90] = 16
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]:  scopes data    [0x00007f9b4daecb90,0x00007f9b4daecbf8] = 104
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]:  scopes pcs     [0x00007f9b4daecbf8,0x00007f9b4daecc68] = 112
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]:  dependencies   [0x00007f9b4daecc68,0x00007f9b4daecc70] = 8
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]:  handler table  [0x00007f9b4daecc70,0x00007f9b4daecc88] = 24
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: #
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: # If you would like to submit a bug report, please visit:
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: #   http://bugreport.java.com/bugreport/crash.jsp
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: # The crash happened outside the Java Virtual Machine in native code.
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: # See problematic frame for where to report the bug.
Sep 30 17:57:29 i7 io.dbeaver.DBeaverCommunity.desktop[3078]: #
Sep 30 17:57:29 i7 systemd[2943]: flatpak-io.dbeaver.DBeaverCommunity-3846.scope: Succeeded.
Sep 30 17:57:34 i7 systemd-resolved[30838]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.

**Comment by tobias47n9e** [comment]
@serge-rider Can "wait for response" tag be removed, or do you need more information?

**Comment by uslss** [comment]
still cannot reproduce it. Is it still actual for you against recent version?

**Comment by tobias47n9e** [comment]
@uslss I just tried it again. Now I am on 7.0.2.202004051509 (Flatpak) and using Ubuntu 20.04 Gnome-Wayland shell. Seems to have been resolved by one of the changes. Perhaps it was an issue with Ubuntu 19.04 and 19.10.
