### ISSUE TITLE
under scripts tab -sorting option is missing in latest 6.2.1

### ISSUE THREAD

**Issue by krsbalu** [dbeaver/dbeaver#6828]
Earlier i used to sort all the scripts based on last modified date, but now the option is not coming in that window.

can you let me know.. how to enable here.
[](url)

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
Right click on table header->Configure columns->Add column "Modified".

**Comment by krsbalu** [comment]
is it possible to share screenshots, as i couldn't get table header.. i am on MAC

i am not finding table header itself

**Comment by uslss** [comment]
hi @krsbalu ,
probably it should look like this, hope it is the same on mac 
![image](https://user-images.githubusercontent.com/31996417/65727507-959dcc00-e0c0-11e9-8ef3-89dfa02385dd.png)

**Comment by krsbalu** [comment]
i am not getting this header option like name, oath etc? itself. Thats the issue for me.. is their anyway i can enable?

**Comment by krsbalu** [comment]
Hey i able to get that , need to use project explorer view instead of projects view.

![image](https://user-images.githubusercontent.com/25248552/65828046-14a72600-e2b4-11e9-9362-f2e15cf1e88d.png)
