### ISSUE TITLE
Cannot select record separator for CSV export

### ISSUE THREAD

**Issue by lifeboy** [dbeaver/dbeaver#6831]
#### System information: 
- Windows 8 and Ubuntu 18.04
- DBeaver Version 6.2.1.201909221630
- Java version: Windows 8 update 181, Ubuntu java.runtime.version=11.0.4+11-post-Ubuntu-1ubuntu218.04.3

#### Connection specification:
- Database name and version:  Any (MySql, MariaDB, Postgres, etc)

#### Describe the problem you're observing:
When exporting data to csv, there is not option to select the record separator.  It is always set to cr/lf (the windows style), even on Linux.  This is a problem.  We need to be able to select the format of the separator.

![image](https://user-images.githubusercontent.com/4822951/65605824-0bfbda80-dfaa-11e9-9e0d-8f46837c2d67.png)

**Comment by Dookie78** [comment]
Tried your suggested method, it does not work.

**Comment by lifeboy** [comment]
What do you mean, Dookie78? I did not suggest a method and "it doesn't work" is not helpful.

**Comment by serge-rider** [comment]
We don't support such option yet. Generally DBeaver always use OS-specific line separator so it should be ok on Linux.
Anyway, having such option would be a good addition.

**Comment by serge-rider** [comment]
Done
![image](https://user-images.githubusercontent.com/6398845/67949738-51d73e80-fbf9-11e9-9a17-21618bec595e.png)

**Comment by lifeboy** [comment]
*Excellent, thank you and well done!*

**Comment by uslss** [comment]
verified
