### ISSUE TITLE
sql server 2000 jdbc

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6835]
![image](https://user-images.githubusercontent.com/26621087/65672057-fbfffb80-e07a-11e9-9528-11f2480fceb8.png)
![image](https://user-images.githubusercontent.com/26621087/65672182-2fdb2100-e07b-11e9-9ddc-edbe2805a2bd.png)

SQL sever 2000 connection which JDBC, currently through the artifact download, test connection failed, request god help

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
hi @Pengchenghua ,
if I understand correctle you're using standard SQL Server driver, probably you can try old driver. Hope it'll help.
![image](https://user-images.githubusercontent.com/31996417/65725360-1fe33180-e0bb-11e9-8fb9-d2dff3c4838b.png)
Looking back for you response.

**Comment by Pengchenghua** [comment]
> 嗨@Pengchenghua，
> 如果我知道您使用的是标准SQL Server驱动程序，则可以尝试使用旧的驱动程序。希望能对您有所帮助。 回顾您的回应。
> ![图片](https://user-images.githubusercontent.com/31996417/65725360-1fe33180-e0bb-11e9-8fb9-d2dff3c4838b.png)

I used the old drive and it still doesn't work

**Comment by uslss** [comment]
@Pengchenghua is issue still reproducible against 6.2.5v?
Sorry for the late response

**Comment by uslss** [comment]
there is bo any updates. issue closed
