### ISSUE TITLE
from navicat to dbeaver!

### ISSUE THREAD

**Issue by jviure** [dbeaver/dbeaver#6836]
Hi people, this is not an issue, is  some doubts I ve.. how I can:

- If I change a text in a cell and change of row, can this change be saved directly without having to click Save ?
- How can I change from one cell to the next with the "tab" key?
- It's possible to remove one row without having to click "Save"? similar as first question..
- Can I double click one table and open the "view data"?

That's all, thanks a lot, keep up that good! :)

**Comment by kseniiaguzeeva** [comment]
Hi jviure!
I hope you will find DBeaver useful and usable. Now to your questions:

**Comment by uslss** [comment]
Hi @jviure ,
by the way you can use Window - Preferences - General - Keys to set shortcuts that are suitable and comfortable for you. :)
