### ISSUE TITLE
Remote connection lost connection after some minutes idle

### ISSUE THREAD

**Issue by rodrigoguariento** [dbeaver/dbeaver#6837]
I believe this is not exactly an error, but I'm used to use Workbench and now I'm migrating slowly to DBeaver, getting used to. The only problem I'm facing with DBeaver with remote MySQL (in my case, I'm connecting with Dreamhost MySQL Server database), after some minutes idle with my database connection opened, I can't even fetch table data. Nothing happens. I'm forced to click "Invalidate/Reconnect" button to establish connection again. With Workbench it does not happen. I don't know internally how DBeaver or Workbench works, or if I forgot of set something configuration in DBeaver. I've the impression that Workbench stays connected sending some "ping" to server when we idle for some minutes, maintaining the connection established. Is there something to do with DBeaver to this "problem" does not occur anymore? Thank you.

#### System information: 
- Operating system (distribution) and version: Linux guari 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- DBeaver version: 6.2.1.201909221630
- Additional extensions: none

#### Connection specification:
- Database name and version: MySQL [5.7.25-log]
- Driver name: MySQL Connector Java [mysql-connector-java-5.1.44 ( Revision: b3cda4f864902ffdde495b9df93937c3e20009be )]
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
After a remote connection established (like with Dreamhost MySQL Server for example), let connection idle for some minutes, DBeaver will lost connection. To solve we are forced to click on "Invalidate/Reconnect", and sometimes it doesn't work. We need to close and reopen DBeaver and our connection.

#### Steps to reproduce, if exist:
After a remote connection established (like with Dreamhost MySQL Server for example), let connection idle for some minutes, try refresh some table.

#### Include any warning/errors/backtraces from the logs
> org.jkiss.dbeaver.model
> Error
> Tue Sep 24 13:41:59 BRT 2019
> No operations allowed after connection closed.
> 
> com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
> 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
> 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
> 	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1187)
> 	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1182)
> 	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4071)
> 	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4040)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
> 	at org.jkiss.dbeaver.ext.mysql.model.MySQLTable.loadAdditionalInfo(MySQLTable.java:275)
> 	at org.jkiss.dbeaver.ext.mysql.model.MySQLTable.getAdditionalInfo(MySQLTable.java:181)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyGroupDescriptor.getGroupObject(ObjectPropertyGroupDescriptor.java:79)
> 	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:263)
> 	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:231)
> 	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:180)
> 	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$5.evaluate(TabbedFolderPageForm.java:375)
> 	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$5.evaluate(TabbedFolderPageForm.java:1)
> 	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
> 	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 

![image](https://user-images.githubusercontent.com/25516653/65691804-e1605f00-e047-11e9-8644-37c8fc6ef04c.png)

**Comment by lemon-juice** [comment]
Try setting keep-alive interval in Connection settings > Initialization. If you use SSH then you can set a separate keep-alive for SSH connection in the SSH tab. When I have problems like yours I set the keep-alive to 60 seconds then and all works fine. I suppose this is equivalent of the ping that Workbench probably does by default.

**Comment by rodrigoguariento** [comment]
> Try setting keep-alive interval in Connection settings > Initialization. If you use SSH then you can set a separate keep-alive for SSH connection in the SSH tab. When I have problems like yours I set the keep-alive to 60 seconds then and all works fine. I suppose this is equivalent of the ping that Workbench probably does by default.

Excelent! Thank you.

I'd like to suggest for developer team to set 600 seconds as default for new connections.

**Comment by eddyfrancisco** [comment]
I was having this problem all te time, and this solution, from @lemon-juice , (60 seconds on Keep-alive) solved wonderfully! Thank you so much for sharing!

But, @rodrigoguariento , i belive that you post  a wrong value in your answer, because you type 600, not 60 seconds, is that right? PS: 600 dosen't work for me.
