### ISSUE TITLE
Table lock after update and select on same record

### ISSUE THREAD

**Issue by LukasBreit** [dbeaver/dbeaver#6838]
### System information: 
- IBM I series 7.2
- DBeaver version 5.2.4

#### Connection specification:
- DB2

#### Describe your question:
Hi,
we had a problem with table locks. If I do an update on a table, the table isn't locked. But when I do a select on the updated record afterwards, the table is locked until I end the job/close DBeaver. The lock on the table occurs only if the select-statement is on the updated record and no other record(s).
Is it a bug or is there a way to change the preferences that the problem doesn't occur any longer?

If you need further information, just let me know. Thanks for your help!

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer. Looks like a bug, but I cannot reproduce it in DBeaver 7.0.3. Is it still actul for you?

**Comment by uslss** [comment]
issue hasn't been updated more than a month.
If it is still actual for you - feel free to reopen the ticket
