### ISSUE TITLE
How to remove SQL query from Copy as HTML output?

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#6839]
#### System information: 
- DBeaver 6.2.1 CE

#### Connection specification:
- MySQL

#### Describe your question:
Is it possible to remove the SQL query from the 'Advanced Copy\Copy as HTML' output?

Thanks for your time.

**Comment by uslss** [comment]
issue is obsolete

**Comment by gouravkr** [comment]
I came looking for this same issue, and I don't understand the response. Copy as HTML still copies with the query. Has there been any addition of `Copy as HTML without query` option which I can't find?

I regularly copy-paste data from the output to Excel and have to take the additional step of removing the query from the first row. Would be nice to be able to define a keyboard shortcut for `Copy as HTML without query`.
