### ISSUE TITLE
Default dark theme is not working well

### ISSUE THREAD

**Issue by rodrigoguariento** [dbeaver/dbeaver#6842]
I'm used to Dark theme for everything. After I set Dark theme as default in DBeaver, the colors are not working well. There is a lot of places with is not being possible to read the content and comments.

#### System information: 
- Operating system (distribution) and version: Linux guari 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- DBeaver version: Version 6.2.1.201909221630
- Additional extensions: none

#### Connection specification:
- Database name and version: not applicable
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Its not being possible to read labels, inputs, combos, selects and others when default Dark theme is selected.

#### Steps to reproduce, if exist:
Window > Preferences > General > Appearance > Theme: Dark

![image](https://user-images.githubusercontent.com/25516653/65763675-52f8e580-e0fa-11e9-9bf3-f3ce2bfc5b36.png)

![image](https://user-images.githubusercontent.com/25516653/65763747-758afe80-e0fa-11e9-9e2e-bde7a8e0107c.png)

![image](https://user-images.githubusercontent.com/25516653/65763770-80de2a00-e0fa-11e9-9f9f-08d251e39cb4.png)

![image](https://user-images.githubusercontent.com/25516653/65763862-abc87e00-e0fa-11e9-9fa6-b2971310b41b.png)

![image](https://user-images.githubusercontent.com/25516653/65763903-c1d63e80-e0fa-11e9-96d9-509385fa4567.png)

#### Suggests
The dark theme and colors of "Eclipse for PHP Developers" for example is awesome. DBeaver theme would be nice if follow the same color palette.

**Comment by fabiopand** [comment]
It should look awesome and beautiful like [this](https://www.eclipse.org/community/eclipse_newsletter/2018/june/darktheme.php)

**Comment by scollovati** [comment]
I'm using it on Windows10 and the Dark theme has the same issue.

**Comment by pmiranda-geo** [comment]
Similar problem here (Windows 7):
![image](https://user-images.githubusercontent.com/49686165/69084331-c6481500-0a22-11ea-948a-db2e37965071.png)
Plus, there are a lot of english text, I'm using the spanish version.

**Comment by rodrigoguariento** [comment]
It looks great!

![image](https://user-images.githubusercontent.com/25516653/69415983-5cff2500-0cf4-11ea-80e8-53bceecd395d.png)

![image](https://user-images.githubusercontent.com/25516653/69416010-6ee0c800-0cf4-11ea-9ed8-7f79b3f46af2.png)

![image](https://user-images.githubusercontent.com/25516653/69416135-b49d9080-0cf4-11ea-9e53-12de364b2d12.png)

Thank you very much!

**Comment by thosky** [comment]
Still many issues with dark mode fx data view. Any status when this will be fixed?

**Comment by salarconb** [comment]
When applying a new theme, some text doesn't display correctly after restart. I have observed that this is general behaviour whether it is applying a default dark theme or one of the DevStyle ones.

Before restart
![image](https://user-images.githubusercontent.com/26559732/100487420-3d5cc280-30e7-11eb-98c0-dc881cbedd9a.png)
![image](https://user-images.githubusercontent.com/26559732/100487449-69784380-30e7-11eb-8912-54cb9a2f534b.png)


After restart
![image](https://user-images.githubusercontent.com/26559732/100487391-1f8f5d80-30e7-11eb-9fd2-905e5ef4d33e.png)
![image](https://user-images.githubusercontent.com/26559732/100487466-801e9a80-30e7-11eb-823c-454ee76f84a4.png)
