### ISSUE TITLE
Toggle Panel Layout button not working 

### ISSUE THREAD

**Issue by goxr3plus** [dbeaver/dbeaver#6843]
![image](https://user-images.githubusercontent.com/20374208/65764531-8c4b4880-e12e-11e9-8e06-8bc2f84c3365.png)

The toggle panels layout button is not working :) 

DBeaver 6.2.1 , Windows 10

**Comment by kseniiaguzeeva** [comment]
Unfortunately canot reproduce in version 7.0.1. Is it still actual for you?

**Comment by goxr3plus** [comment]
Now i got it : 

 
![2020-03-24_14-30-51](https://user-images.githubusercontent.com/20374208/77425896-1de4fb80-6ddc-11ea-91c2-dfa96d1d7b88.gif)
