### ISSUE TITLE
Basemap in non web mercator projection 

### ISSUE THREAD

**Issue by dominijk** [dbeaver/dbeaver#6846]
**Is your feature request related to a problem? Please describe.**
Where my data has spatial components stored in an known SRID (but not web mercator) it would be nice to enable a basemap for that supports that projection

**Describe the solution you'd like**
Basemap re-projects to match projection in geometry column

**Describe alternatives you've considered**
Duplicating column or creating view with geometry reprojected to webmercator as basemap

**Comment by uslss** [comment]
@dominijk could you check if the feature request is still actual for you against the recent version (21.0.2)?

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info

**Comment by dominijk** [comment]
I'm still not getting the basemap that works for the project but this could be user error so will report back
