### ISSUE TITLE
Athena leaves temporary files in S3 directory

### ISSUE THREAD

**Issue by ravikrishna-odh** [dbeaver/dbeaver#6848]
Dbeaever 6.2.1 on MacOS.

When I connect to Athena via dbeaver and run a query like
select * from table limit 100;
this causes dbeaver to leave leftovers .csv file in the S3 directory.  In our case this happens in Apache ORC files and that causes subsequent queries to break as these csv files are non ORC.

Here is a screenshot of the S3 bucket before the query was run.
<img width="1280" alt="Screen Shot 2019-09-25 at 9 27 52 AM" src="https://user-images.githubusercontent.com/54145300/65795411-354a7100-e138-11e9-8b5e-ebd08345401c.png">

Here after the query was run.  One can see the left over files.

<img width="1280" alt="Screen Shot 2019-09-25 at 9 32 01 AM" src="https://user-images.githubusercontent.com/54145300/65795435-41cec980-e138-11e9-87c2-1efa55459899.png">

Subsequent queries return this error:

![image001](https://user-images.githubusercontent.com/54145300/65795457-4d21f500-e138-11e9-83a0-a66e88e48fb0.jpg)

**Comment by serge-rider** [comment]
I'm afraid we can't fix this from DBEaver side.
This is how Simba JDBC driver works (it is a driver recommended by Amazon).

**Comment by ravikrishna-odh** [comment]
OK fair enough.  Thanks.

**Comment by bradlywilson** [comment]
There's a property in the driver to set the output location for query results. To change this setting in DBeaver go to the "Driver properties" tab you can set a value for S3OutputLocation.  To find what your default is go to the Athena page in your AWS console and look in "settings" for "Query result location".
