### ISSUE TITLE
Disconect from database every minute

### ISSUE THREAD

**Issue by andreysneg** [dbeaver/dbeaver#6852]
#### System information: 

- Operating system (distribution) and version:  Win 7 and Win 10
- DBeaver version:  6.1 and early
- Additional extensions:  Local server: Openserver, XAMP , WAMP, Remote servers  with Cpanel 

#### Connection specification:
- Database name and version; all mysql 5.5-8.0 and mariadb 10-10.0.3
- Driver name: mysql and mariadb
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:

Disconect from database every 1 minute. This problem 3 years old. Always i test new DBeaver and always this problem. I used ALL sql programm in the world. Nobody dont have this problem.
I must click this smaaaaaaaal icon - reconect every 1 minute. Imposible use programm.

Settings "Database - Error handle" dont work absolutly.

Error Image:
http://bit.ly/2lQ4OwR

How Heidisql and others absolutly never has`t this problem ?

#### Steps to reproduce, if exist:
1. Connect to db
2. Change table field
3. Wait 1 minute
4. Change table field  - no connection

#### Include any warning/errors/backtraces from the logs

[db.log](https://github.com/dbeaver/dbeaver/files/3665321/db.log)
 -->

**Comment by serge-rider** [comment]
I can't reproduce this. But there can be several different causes of this problem.

It may be the server configuration (close idle connections after 1 minute). In this case configuring Kepp-Alive in connection settings may help (it is on Initialization page of connection settings dialog). Set it to 10-20 seconds.

It may be the driver problem (MariaDB). You could try another driver (MySQL, MySQL 8).

Did you try to enable connection auto-recovery option? It usually works (if server returns proper error code) and you don't need to click reconnect manually.

Please send debug.log file (https://github.com/dbeaver/dbeaver/wiki/Log-files) - it may contain some additional clues.

**Comment by kseniiaguzeeva** [comment]
@andreysneg Please tell is this issue still actual for you?

**Comment by uslss** [comment]
there is no update on ticket for a long time. ticket closed.
if issue is still actual for you - feel free to reopen the ticket
