### ISSUE TITLE
Virtual foreign keys lost when reopen project

### ISSUE THREAD

**Issue by Vant1032** [dbeaver/dbeaver#6854]
**Is your feature request related to a problem? Please describe.**

When I reopened the project, the previous created virtual foreign key was lost. So I have to create it again. I created it because I want see the ER diagram.

**Describe the solution you'd like**

save virtual foreign keys into disk so it can be use later

**Comment by serge-rider** [comment]
Do you use the most recent DBeaver version?
Can you reproduce this problem?

Virtual foreign keys (as well as other virtual schema configuration) must be persisted. If it is reproducible then it is a bug.

**Comment by Vant1032** [comment]
I use dbeaver 6.2.1.201909221630.

It is easy to reproduce this problem.

You can create two table and then create virtual foreign keys between the two table.Save it,Then reopen the project and you can find the virtual foreign keys lost.

**Comment by serge-rider** [comment]
What do you mean under "reopen the project"? Do you work in standalone version of DBeaver or in Eclipse plugin?

**Comment by Vant1032** [comment]
I'm sorry I didn't describe it clearly. I'm work in standalone version of DBeaver.

**Comment by serge-rider** [comment]
Ok. Then it is still not clear what is "reopen project". We don't have "close/open project" feature in standalone version. Do you mean dbeaver restart? Or table editor close/open?

Does this problem happen if you connect two existing tables? (not new created ones)

I still can't reproduce this issue although I've tried very different use-cases.

**Comment by Vant1032** [comment]
I find it is because I use General(the default project) project.If I create virtual foreign keys in my own project, then it will not lost.
![General](https://user-images.githubusercontent.com/20537302/65835381-418d2480-e318-11e9-9ceb-5d01a073d548.png)

**Comment by serge-rider** [comment]
Thanks, now I've reproduced that. 
But this happens only if I create connection in a custom project by copy-pasting it from General project.

**Comment by kseniiaguzeeva** [comment]
Fixed
