### ISSUE TITLE
avoid re-registering databases when driver moved to different plugin.xml?

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#6855]
To fix #6781 I implemented here https://github.com/kai-morich/dbeaver/commits/hana02 an eclipse extension point dataSourceProvider for HANA to show 'schemas' icon and eventually more.

I also had to move the driver from generic plugin to HANA plugin. Previously existing HANA systems now fail with "Can't create driver instance" because the old driver in generic plugin does not exist any more. Newly registered HANA systems show 'HANA' in Connection->Edit Driver Settings->Driver Type, whereas the old show 'Generic'. 

Is it possible to avoid re-registering databases when driver moved to different plugin.xml?

**Comment by serge-rider** [comment]
You should use tag
```xml
<replace provider="generic" driver="sap_hana"/>
```
in your new driver configuration. You can find a loft of similar replacements in other plugins.
If new HANA plugin will fail to load (by any reason) then old driver will be used.

**Comment by kai-morich** [comment]
:+1:
