### ISSUE TITLE
The Chinese will not show correctly in the table of Impala db when import data from csv or external table? 

### ISSUE THREAD

**Issue by zuoinlv** [dbeaver/dbeaver#6858]
#### System information: 
- Operating system (distribution) and version
Windows 7 64bit
- DBeaver version
6.1.5.201908191349
#### Connection specification:
- Database name and version
oracle 10g
impala 3.2.0
#### Describe your question:
When I try to import data from csv or oracle to impala with dbeaver, after the import process finish, the data(Chinese) will not show correct, how to  set the word encoding ?
![微信图片_20190929153356](https://user-images.githubusercontent.com/3855382/65828543-91df9480-e2ce-11e9-96e1-25e13ecb6be3.png)

**Comment by uslss** [comment]
Hi @zuoinlv ,
when i saved CSV file in UTF-8 and import it to oracle - it helps. 
Unfortunately, i have no possibility to check oracle-impala flow

**Comment by zuoinlv** [comment]
> Hi @zuoinlv ,
> when i saved CSV file in UTF-8 and import it to oracle - it helps.
> Unfortunately, i have no possibility to check oracle-impala flow

I tried to import data to mysql db in dbeaver, it works well, but when import to impala db, the Chinese character will not show correctly

**Comment by E1izabeth** [comment]
Does it still reproducible in the latest DBeaver version? We expect that it may be solved it with #21513

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
