### ISSUE TITLE
H2GIS: spatial viewer

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6860]
We need to add support of H2GIS geometry data type

**Comment by serge-rider** [comment]
![Screenshot 2019-09-29 at 15 12 37](https://user-images.githubusercontent.com/6398845/65832398-99ea0500-e2cb-11e9-902e-78903ecd26aa.png)

**Comment by SPalominos** [comment]
@serge-rider Great job !

**Comment by uslss** [comment]
verified
