### ISSUE TITLE
auto_increment Extra not removed after uncheck the Auto Increment

### ISSUE THREAD

**Issue by erlangp** [dbeaver/dbeaver#6864]
#### System information: 
- Windows 8
- DBeaver version 6.2.1

#### Problem:
`auto_increment` _Extra_ not removed after uncheck the _Auto Increment_.
After click _Save_, _Auto Increment_ remain checked.

#### Steps to reproduce:
_Properties_, uncheck _Auto Increment_

#### Temporary solution:
Manually remove `auto_increment` text below _Extra_

**Comment by uslss** [comment]
Hi @erlangp ,
thanks for the bug report.
Unfortunately, cannot reproduce the issue. Could you say what db do you use?
Thanks in advance

**Comment by erlangp** [comment]
MySQL 5.7.24-winx64

**Comment by erlangp** [comment]
Screenshot how to reproduce: https://imgur.com/a/wIBmprw

**Comment by erlangp** [comment]
Temp fix: Uncheck the Auto Increment checkbox, then remove Extra 'auto_increment' text manually, then Save.

**Comment by uslss** [comment]
Thanks for assistance and bug report :)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by erlangp** [comment]
Thanks all :smiley: :+1:
