### ISSUE TITLE
Task management: Task could be saved with empty name

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6865]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.2 EA

#### Describe the problem you're observing:
Task could be saved with emty name - it causes error when trying to Run task (in the scope of #6865)
#### Steps to reproduce, if exist:
1. Open Database task and start task creation
2. Save Task with empty name - Task is successfully saved
3. Try to run previously saved Task - an error appears

[empty_name.log](https://github.com/dbeaver/dbeaver/files/3667888/empty_name.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
