### ISSUE TITLE
Task Management: Run task is available in Context menu when no task is chosen 

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6866]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.2 EA
in scope of #2372 
#### Describe the problem you're observing:
"Run task" is always available in context menu, even if no task is chosen or exists
#### Steps to reproduce, if exist:
1. Open DB Tasks Tab
2. Check Context menu 
no task is chosen:
![image](https://user-images.githubusercontent.com/31996417/65837358-ec90e480-e2fe-11e9-8f98-bedd9d1a9330.png)
no tasks exist
![image](https://user-images.githubusercontent.com/31996417/65837359-f581b600-e2fe-11e9-9887-52c06f0b4827.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
