### ISSUE TITLE
DB Tasks: error appears if any option is changed when Run previously created task

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6867]
#### System information:  
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.2
#2372 

#### Describe the problem you're observing:
If i open previously created task - change any option (name/ exporter settings/ etc.) - save it - Data transfer cannot be continued (error appears)
#### Steps to reproduce, if exist:
![DBtasks-changing](https://user-images.githubusercontent.com/31996417/65837457-5eb5f900-e300-11e9-9492-54accbef8cd6.gif)
[changing.log](https://github.com/dbeaver/dbeaver/files/3667912/changing.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
