### ISSUE TITLE
Inconsistent behaviour with custom data types (omit schema) in PostgreSQL

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#6868]
- Operating system (distribution) and version: Ubuntu 18.04
- DBeaver version: 6.2.1
- Java version: 11
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 11.5
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc): no 

#### Describe the problem you're observing:

Data types within schemes incorrect behaviour 

#### Steps to reproduce, if exist:

I try to rename function via F2, type new name, press Enter. Window with SQL command appear and the command is, e.g.:

ALTER FUNCTION vme.p_calc_stats_countries(d_bool, d_period_decade) RENAME TO p_calc_stats_countries_old;

This command fails, but when I manually run command with "schemed" types, all is ok - e.g. vme.d_bool,vme.d_period_decade.

The second bug is - when I editing table fields I see "unschemed" types too, and the combobox for select data type does not contain any custom type (both "schemed" and not). Typing manually solves the problem (but does not allow to type with scheme - only without, and only current scheme will be used thus data types could reside in different).

**Comment by plotn** [comment]
[tst_bug.zip](https://github.com/dbeaver/dbeaver/files/3669277/tst_bug.zip)

Try to rename or drop function s3.f_test2 and you should get error. Whilst f_test1 will be renamed successfully.
Try to edit table s3t1 and add new field. Custom types does not present in dropdown list. When typing them manually they are picked from that scheme, where it could be found, but e.g. that type d_int exists both in s1 and s2 schemes (it was chosen from first in result script).

**Comment by plotn** [comment]
Hi @uslss! Have database backup helped to reproduce?

**Comment by uslss** [comment]
Hi @plotn ,
thanks a lot! It was very helpful :)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
