### ISSUE TITLE
Scripts panel does not update script list

### ISSUE THREAD

**Issue by kamiyubidan** [dbeaver/dbeaver#6870]
#### System information: 
- Windows 10
- DBeaver 6.2.1 CE
- DevStyle

#### Connection specification:
- MySQL

#### Describe the problem you're observing:
The script panel does not update the list of scripts correctly.

The script list is not updated under the following conditions:

- When saving a script.
- Using the 'Refresh' option in the right-click menu in the script panel.
- Restarting DBeaver.

The script list is only updated when:
- Using the 'Refresh' option in the right-click menu in the Project panel.

#### Steps to reproduce, if exist:
- Create a new script using the menu option: 'SQL Editor\New SQL Editor'
- Save the script using the menu option: 'SQL Editor\Save SQL Script'
- The script will not be listed in the Scripts panel.

- If Ctrl-S or the 'Save' option in the right-click menu in SQL editor is used to save the script, then a "Script-_n_.sql" will be saved and listed in the Scripts panel.

**Comment by serge-rider** [comment]
It is not a bug. "Save SQL Script" saves script in some external file, not in workspace. We probably should rename this action into "Export SQL script".

**Comment by uslss** [comment]
verified

**Comment by Moby01** [comment]
This issue as reported by ghost has resurfaced since the last update... Current work around is to save multiple times, once it finally saves you can rename the script file.

**Comment by p91paul** [comment]
Friendly suggestion: open a new issue, old closed ones might be overlooked.
