### ISSUE TITLE
Creating trigger in SQL console

### ISSUE THREAD

**Issue by Dookie78** [dbeaver/dbeaver#6871]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
DBeaver 6.2.0 on Windows 64-bit
#### Connection specification:
- MySQL 8.0

#### Describe your question:
i'm trying to create the trigger in DBeaver but it giving me SQL error [1064][42000]:
![image](https://user-images.githubusercontent.com/35907473/65857137-c9fdda80-e395-11e9-874c-388ca9139acb.png)

I tried typing in the statement using the MySQL command line and it works
![image](https://user-images.githubusercontent.com/35907473/65857240-02051d80-e396-11e9-92b3-d3d7fa115f9b.png)

Any ideas on how do i create triggers/procedures in DBeaver???

**Comment by uslss** [comment]
duplicates #2590

**Comment by AdemirMonsivais** [comment]
@Dookie78 
I tried using your approach, but...

<img width="902" height="286" alt="Image" src="https://github.com/user-attachments/assets/f7cfb3c2-8dbf-4157-adfc-8854310a2427" />
