### ISSUE TITLE
Show database prefix on database export Target container

### ISSUE THREAD

**Issue by goxr3plus** [dbeaver/dbeaver#6873]
![image](https://user-images.githubusercontent.com/20374208/65863408-babc6400-e378-11e9-86da-87ed8c5db73a.png)

On source container on `Source` i can see the source database `l10_lottery_nl` but on the other side on `Target` i can't see on which database the tables will be created/modified and as this is the final step i want to be sure not mistakes are made.

What i do now to double check is go backwards and check 1-2 times . Can you add the prefix there as it is shown in `Source`

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer and thank you for the suggestion.

**Comment by kseniiaguzeeva** [comment]
@goxr3plus  The Target column displays schema name in DBeaver 7.2.1. Please try.

**Comment by kseniiaguzeeva** [comment]
Please write if the issue appears again
