### ISSUE TITLE
Compiled successfully message even with syntax errors

### ISSUE THREAD

**Issue by rpalloni** [dbeaver/dbeaver#6875]
### System information: 
- Windows10
- 6.3

#### Connection specification:
- Oracle11

#### Describe the problem you're observing:
As you see in the image, I get the 'compiled successfully' message even when there are errors
![compile_bug](https://user-images.githubusercontent.com/17080117/65891578-0b49b680-e3a5-11e9-91bb-38508a09b7d2.png)

#### Steps to reproduce, if exist:
Create a package and try whatever error

**Comment by p91paul** [comment]
6.3 AFAIK doesn't exist, could you check your version number? a fix for this should have landed in 6.2.1.

**Comment by rpalloni** [comment]
You are right, it is 6.0.3
Thanks
