### ISSUE TITLE
How to connect DBeaver to sqlite3 db through ssh tunnel

### ISSUE THREAD

**Issue by MkLHX** [dbeaver/dbeaver#6876]
#### System information: 
- Client Windows 10 / Server Raspbian 10 rpi3
- DBeaver version 6.2.1 release 23/09/2019

#### Connection specification:
- Database SQLITE3 through SSH

#### Describe your question:
Hi there!
I'm trying to connect on sqlite3 database through ssh on remote server.
My ssh tunnel is working, but what is the syntax and where paste it on the db.sqlite3 file in DBeaver.
DBeaver connection informations :
![image](https://user-images.githubusercontent.com/17542841/65893469-4699b480-e3a8-11e9-97ac-b860d1d6a233.png)

SSH connection informations:
![Annotation 2019-09-30 173456](https://user-images.githubusercontent.com/17542841/65893711-b871fe00-e3a8-11e9-8f6c-a74ffe940a67.png)
![image](https://user-images.githubusercontent.com/17542841/65893635-8eb8d700-e3a8-11e9-97df-ab0fa87afa7f.png)

**Comment by dmitrygribenchuk** [comment]
Hey. I'm have the same issue with error "Can't initialize tunnel
  Database port not specified and no default port number for driver 'SQLite'"

**Comment by DraftProducts** [comment]
I've the same issue

**Comment by MkLHX** [comment]
If somebody can help us it will be awesome...

**Comment by serge-rider** [comment]
You cannot use SSH with SQLite. 
SQLite is embedded database, there is no such thing as SQLite server. 
So SSH doesn't make any sense for SQLite.

**Comment by MkLHX** [comment]
So there isn’t any way to manage sqlite db from remote...

**Comment by likeawindrammer** [comment]
> SQLite is embedded database, there is no such thing as SQLite server.

This is true, but something like git over ssh *might* be possible. Could send commands using `sqlite3` (as in the command line interface for SQLite) in the host machine to manipulate an sqlite database over ssh without any actual server at all other than the ssh deamon. 
Just my uneducated thought, im not even sure inserting binary data is even possible with something like that.

**Comment by alun** [comment]
> > SQLite is embedded database, there is no such thing as SQLite server.
> 
> This is true, but something like git over ssh _might_ be possible. Could send commands using `sqlite3` (as in the command line interface for SQLite) in the host machine to manipulate an sqlite database over ssh without any actual server at all other than the ssh deamon.
> Just my uneducated thought, im not even sure inserting binary data is even possible with something like that.

That's a good point. I'm just thinking DBeaver is limited to JDBC use. But it probably should be possible to create a [custom JDBC driver](https://www.infoworld.com/article/2074249/create-your-own-type-3-jdbc-driver--part-1.html) sending SQL to a `ssh sqlite3` pipe.

**Comment by Kavarenshko** [comment]
From what I understand the 'Path' field expects a simple path (no IPs etc.). So I managed to solve (on linux) by:

1. Establishing a SFTP connection with the server (easily doable with the UI, on Ubuntu 'Other Locations' -> 'Connect to server' -> `sftp://<server_name_or_ip>:<ssh_port>`)

2. Creating a link from the local computer to the server root (`ln -s <remote_dir> <link_name>`).

**Note:** the remote_dir (i.e. the server root directory) is created when connecting with SFTP; mine, for example, is located at `/run/user/1000/gvfs/<server_name>` . The link is needed because that folder has weird chars/spaces in it, which DBeaver rejects.

So for example: let's say that your SQLite db is located at `/projects/db.sqlite` on the remote server and the link that points to `/run/user/....` is located at `/home/john/sv_root` on your local machine. The final path you'll have to put in DBeaver is `/home/john/sv_root/projects/db.sqlite`.

**Comment by ngochieu642** [comment]
I can confirm that @**Kavarenshko**'s workaround works

**Comment by philshem** [comment]
Another solution for mac/linux is to use `sshfs`, which mounts a folder via ssh.

    sshfs username@hostname:/remote/directory/path /local/mount/point -ovolname=NAME

([source](https://apple.stackexchange.com/a/193043/124094))

**Comment by M3-Coordinator** [comment]
I have tried the solution posted by @Kavarenshko but I get an error saying path to '/home/user/remote_root/projects/project1/group1/sqlite3database.db': '/home/user/remote_root' does not exist. 

1. The Tunnel Configuration Test results in "Connected!"
2. I was able to mount the remote root directory with: `sftp://<server_name_or_ip>:<ssh_port>`
3. I made a link to the root directory in my local home directory with: `ln -s <remote_dir> <link_name>`
4. I then navigated to my db file through the link to get the path and entered that path in the path field of the Main tab.
5. I get a message saying that there is no defaut port, so I click the Edit Driver Settings button and enter 22.
6. Test connection again, and then get the "path does not exist" message.

Thanks in advance for any help!

**Comment by Lonniebiz** [comment]
As, @philshem said, try [sshfs](https://stackoverflow.com/a/66156035/217867).

**Comment by MkLHX** [comment]
i'm using this great tool because i'm using sqlite db in iot devices.
sqlite-web
https://github.com/coleifer/sqlite-web

**Comment by leimao** [comment]
> So there isn’t any way to manage sqlite db from remote...

Is this still the case using DBeaver in 2022? I just wanted to view the sqlite file on my Linux computer remotely from my Windows laptop. Thank you.

**Comment by flambchap** [comment]
I think we can try implementing the approach proposed by @Kavarenshko.

**Comment by ShadelessFox** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/35821147/189554532-89af39ed-def7-4a77-b592-47d6dc9be911.png)

**Comment by iTem186** [comment]
@ShadelessFox Hi there! In which version it's available ? In my versions 22.2.1 on Mac and Windows I don't see `SQLite Remote` in possible connections.
<img width="783" alt="image" src="https://user-images.githubusercontent.com/26230210/194759817-d6ef6ca3-a1f1-40a2-a1f8-fe24808fff25.png">

**Comment by ShadelessFox** [comment]
Hello @iTem186,

The SQLite Remote driver is only available in DBeaver PRO versions which aren't yet released.

You can download early access versions here: https://dbeaver.com/files/ea/

**Comment by argarcia-ottersoft** [comment]
has this been scheduled for a release version yet?

**Comment by flambchap** [comment]
Scheduled for 22.3.

**Comment by cPanelBenjamin** [comment]
Are there any plans to make the SQLite Remote driver available in DBeaver Community Edition? or will this remain in PRO versions only?

**Comment by ShadelessFox** [comment]
We don't have plans on making the driver available in non-PRO products.

You can try a 14-day free trial: https://dbeaver.com/trial/

**Comment by andreborracha** [comment]
Hi friends. I had the same issue, while waiting for SQLite remote in nom-PRO Dbeaver, my workaround was mount a NFS Filesystem between the machines, sharing de same SQLite db file. It works fine!

**Comment by sjas** [comment]
use sshfs

however mount it to somewhere in your ${HOME} and not i.e. under /mnt

dbeaver will not be able to open it otherwise
