### ISSUE TITLE
Task cannot be executed if added query is not the first item 

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6879]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.2 #2372 
#### Describe the problem you're observing:
if query is added to task NOT from result set in specific cases - it cannot be executed
Add second query to Task
![query_exp1](https://user-images.githubusercontent.com/31996417/65911195-e66d3780-e3d4-11e9-8240-5684c28edc70.gif)

[tesr.log](https://github.com/dbeaver/dbeaver/files/3673010/tesr.log)

**Comment by serge-rider** [comment]
Fixed as a part of other bug fix
