### ISSUE TITLE
Error appears if tables from different DB are added to task

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6880]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.2
#2372 
#### Describe the problem you're observing:
Task couldn't be executed if tables are from different dbs
#### Steps to reproduce, if exist:
1. Open existing task
2. Add some table from another connection
![query_exp1](https://user-images.githubusercontent.com/31996417/65911960-1d901880-e3d6-11e9-8920-b1f33e474711.gif)

[tst.log](https://github.com/dbeaver/dbeaver/files/3673053/tst.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
