### ISSUE TITLE
Why a new Connection in MySQL for a specific DB lets later access all the rest of DBs?

### ISSUE THREAD

**Issue by manueljordan** [dbeaver/dbeaver#6881]
#### System information: 
- Operating system (distribution) and version
   Macbook Pro - 10.11.3 - El Capitan
- DBeaver version: 2.6.1

#### Connection specification:
- Database name and version
   MySQL Community - 5.7.22 Homebrew
#### Describe your question:

* Huge thanks for this tool!!!

I have installed the `STS` IDE (based on `Eclipse`) and the `DBeaver` plugin version 2.6.1.

Taking the following figure from your own documentation:

![Wizard-MySQL-settings](https://user-images.githubusercontent.com/2552795/65926218-c4b28700-e3b9-11e9-867b-47884ae48d72.png)

From above observe the title of the window is `Connect to database` 

I did realise the following (how **root**):

* If I leave the `Database` empty, the connection can be created. Here I can assume the DBeaver can access any db. It does happen. I confirmed this behavior. I would assume that this field must be mandatory, it is the correct approach.

* If my memory does not fail me, If I put an invalid db name. The connection fails. Well it is expected.

* What is confuse for me is when I define a specific db. The connection is created and through the `DBeaver` perspective in the IDE I am able to select the other databases from the _same_ connection to MySQL. 

**Problem**

Consider if MySQL has the following databases 

* A1
* B2 
* C3
* D4

If I create a specific connection for B2, it is created how is expected but and I am able access the others DBs (yes I know the user is root). For me has no sense this behavior because consider the scenario if other team member through his IDE do a connection to D4 and by mistake later  _selects_  (with the _same_ connection opened of course) through the IDE (from the list of the DBs) other DB (assume A1 or even the mine B2) and do anything serious (delete data or drop tables - worst scenario)

Yes I know, with `mysql -u root -p` is possible to acces to MySQL and therefore all the DB, but then is mandatory select the DB to prior to work. It with the `use dbname` command. 

This same approach should be applied for each New connection with DBeaver. Therefore each connection must only let access to the db selected from the beginning and not the others. Even is the root user is used.

Please let me know your thoughts

Thank you

**Comment by serge-rider** [comment]
We could add an option "Show all databases" - we have similar one for PostgreSQL. It is `On` by default as in most cases users need to see all databases on server. 
In MySQL these databases may have even cross-references (foreign-keys).

**Comment by serge-rider** [comment]
Also database name is not mandatory and I don't think we should make it mandatory. It is quite often situation when you don't remember the exact name of the database.

**Comment by manueljordan** [comment]
Hello Serge

Thanks for the reply.

I understand the point, but the point was security. Of course the other implicit security control is the `User` permission from the `MySQL` itself.

Even when the `root` has all the access to any database, it would be problematic if selects the wrong Db from the list once the connection through `DBeaver` has accomplished.

And yes, has sense the suggested checkbox. Of course it applies for `root` and other `User` with permission to multiple databases.

Thank you.
