### ISSUE TITLE
Data export is broken if data import was made before it

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#6882]
#### System information:  
- Operating system (distribution) and version Windows 10 home
- DBeaver version 6.2.2

#### Connection specification:
- Database name and version MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? yes

#### Describe the problem you're observing:
An error appears and data export is not executed if data import was made before (it doesn't mean whether import was sucessful or not; whether import/export were made using task or not)
Workaround: Export will be work properly again if to execute any saved export task 
#### Steps to reproduce, if exist:
1. import any table
2. export any table after it
#### Include any warning/errors/backtraces from the logs
![export after import](https://user-images.githubusercontent.com/51405061/65935385-9799bf00-e421-11e9-8d4a-a37e779e4820.png)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3674477/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed in #6909

**Comment by kseniiaguzeeva** [comment]
Verified
