### ISSUE TITLE
If execute "import task", values "NULL" are imported in the table

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#6883]
#### System information: 
 Operating system (distribution) and version Windows 10 Home
- DBeaver version 6.2.2

#### Connection specification:
- Database name and version MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? yes

#### Describe the problem you're observing:
If execute "import task" from "database task" window:
a) values "NULL" are imported in the table
b) task type is changed on "export" after import task reopening

#### Steps to reproduce, if exist:
-create (and save) an import task in "Database task window" and execute it;
-check how values were imported into the table
-reopen the task again and check its type.

#### Include any warning/errors/backtraces from the logs
![task type](https://user-images.githubusercontent.com/51405061/65935878-4a1e5180-e423-11e9-81d6-28965dd9ecf2.png)

**Comment by serge-rider** [comment]
Fixed in #6909

**Comment by kseniiaguzeeva** [comment]
Still reproducing..

**Comment by serge-rider** [comment]
One more fix pushed

**Comment by kseniiaguzeeva** [comment]
Verified
