### ISSUE TITLE
Error while deleting of a function with a quoted custom type

### ISSUE THREAD

**Issue by bravikov** [dbeaver/dbeaver#6884]
#### System information: 
- Ubuntu 18.04
- DBeaver Version 6.2.0.201909081341

#### Connection specification:
- PostgreSQL 9.6.8 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0, 64-bit.
- The default driver.
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Answer: No.

#### Describe the problem you're observing:

Cannot delete a function with a quoted custom type.

#### Steps to reproduce, if exist:

1. Create a quoted custom type with comma:
`CREATE` TYPE "my,type" AS (a INTEGER, b TEXT);`
2. Create a function:
`CREATE FUNCTION test(a "my,type") RETURNS INTEGER LANGUAGE SQL AS $$ SELECT 1 $$;`
3. Update a functions list in DBeaver.
4. Delete the function.

#### Include any warning/errors/backtraces from the logs

"ERROR: type "my" does not exist".

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by kseniiaguzeeva** [comment]
Verified
