### ISSUE TITLE
org.jkiss.dbeaver.DBException: Can't find reference node ... for virtual foreign key

### ISSUE THREAD

**Issue by krkhnh** [dbeaver/dbeaver#6885]
#### System information: 
- Operating system (distribution) and version: Windows 10 v1903
- DBeaver version: 6.2.1
- Java version: OpenJDK v11.0.2
- Additional extensions: None

#### Connection specification:
- Database name and version: SQL Server v11.0.2218.0
- Driver name: SQL Server
![image](https://user-images.githubusercontent.com/5172480/65940257-064b3c80-e463-11e9-8f03-ab7ab5fa5ff0.png)
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:
After renaming a virtual foreign key referenced table, the referencing the table cannot be added to ERDs. On the table view, ER Diagram tab throws an error like below. I couldn't find a way to remove the virtual foreign key, so I created another same connection.

```
org.jkiss.dbeaver.DBException: Can't find reference node database://mysql8-16a34696134-2e52b48456342260/org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog/FOO/org.jkiss.dbeaver.ext.mysql.model.MySQLTable/cms-role_master for virtual foreign key
Can't find reference node database://mysql8-16a34696134-2e52b48456342260/org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog/FOO/org.jkiss.dbeaver.ext.mysql.model.MySQLTable/cms-role_master for virtual foreign key
Can't find reference node database://mysql8-16a34696134-2e52b48456342260/org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog/FOO/org.jkiss.dbeaver.ext.mysql.model.MySQLTable/cms-role_master for virtual foreign key
```

#### Steps to reproduce, if exist:
This may be not exact, but I'll try to explain.

1. Add a virtual foreign key referencing table B to table A.
2. Change the name of table B
3. Table A cannot be added to ERDs. On the table view, ER Diagram tab throws an error.

**Comment by serge-rider** [comment]
Now we update virtual model on entity rename in real database model.

This won't work if table was renamed outside of dbeaver but there is nothing we can do in this situation.

**Comment by uslss** [comment]
verified
