### ISSUE TITLE
Sorting in "database task" window uses task addition time for order

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#6887]
#### System information: 
- Operating system (distribution) and version Windows 10 Home
- DBeaver version 6.2.2

#### Connection specification:
- Database name and version MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? yes

#### Describe the problem you're observing:
Sorting in "database task" window sorts asc/desc using time of task addition (but not column values order)
#### Steps to reproduce, if exist:
-open "database task" window and create several tasks
-try to sort rows using column headers in"database task" window
#### Include any warning/errors/backtraces from the logs
![HhjKgaDcdD](https://user-images.githubusercontent.com/51405061/65948601-3be02d80-e443-11e9-8999-3175a6aa4216.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
