### ISSUE TITLE
SQL editor tab width is only wide enough to display database name

### ISSUE THREAD

**Issue by kamiyubidan** [dbeaver/dbeaver#6889]
#### System information: 
- Windows 10
- 6.2.1 CE
- DevStyle

#### Connection specification:
- MySQL

#### Describe the problem you're observing:
The SQL editor tab width is only wide enough to accommodate the database name or about 16 characters. The script name is therefore never visible. With several SQL scripts open, all you can see is many tabs with identical database names.

This makes switching between scripts a matter of memory, guessing, or reopening a script from the Scripts panel or the breadcrumb dropdown.

#### Steps to reproduce, if exist:
Open several SQL scripts that are associated to a database.

**Comment by uslss** [comment]
Hi @kamiyubidan ,
btw, you could modify tab title in Preferences - Database - SQL Editor - Scripts.
![image](https://user-images.githubusercontent.com/31996417/65984213-f4c85b80-e487-11e9-8f6b-62f0ee9667c9.png)

**Comment by kamiyubidan** [comment]
Thanks. I changed the setting to just display the filename. It does help, but the character limit per tab title is quite low.

Also, even after a restart, the previous naming pattern is retained until each tab is clicked. 

Thanks again.
