### ISSUE TITLE
cell click sum

### ISSUE THREAD

**Issue by jviure** [dbeaver/dbeaver#6891]
Hi! maybe this feature works but I don't find it. I am looking if it's possible that.. if I check some cells with to see it's total (if the cell is an int or numeric), could be possible? now if I want to do this  I've to copy the table, go to excel and do this there. Thanks! :)

**Comment by uslss** [comment]
Hi @jviure ,
you can sum cells value using Panels - Calc (https://dbeaver.com/docs/wiki/Panels/)
![image](https://user-images.githubusercontent.com/31996417/65983493-453eb980-e486-11e9-880d-3ad169c41d43.png)

**Comment by jviure** [comment]
great! thanks :)
