### ISSUE TITLE
DB Tasks: floating NPE when opening task from DB tasks tab

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6894]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.2 CE
#2372 
#### Describe the problem you're observing:
Time to time NPE appears when trying to open previously created tabs. Steps to reproduce are unclear.

[log_npe.txt](https://github.com/dbeaver/dbeaver/files/3678039/log_npe.txt)

**Comment by serge-rider** [comment]
Most likely it was fixed along with #6896.Please reopen if you will see this NPE again.

**Comment by uslss** [comment]
issue isn't reproducible for now
