### ISSUE TITLE
Permissions for read-only connection aren't saved

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6895]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.2
#### Steps to reproduce, if exist:
1. Open Edit connection
2. Check read-only connection
3. Change some permissions by clicking Edit Permissions button
4. Re-connect and do steps 1-3 once again - all checkbox in Edit permissions pop-up are unchecked,

**Comment by serge-rider** [comment]
The problem is in permission load in edit dialog. Actual settings is working,
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
