### ISSUE TITLE
Imopssible to export table to another db

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6896]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.2

#### Describe the problem you're observing:
It is impossible to choose target container when export table to another db (please, see attached gif)
![export_fail](https://user-images.githubusercontent.com/31996417/65999149-81354700-e4a5-11e9-89ef-c52748b266cb.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
