### ISSUE TITLE
DBeaver showing default database schema when creating new database

### ISSUE THREAD

**Issue by amitnair5886** [dbeaver/dbeaver#6897]
#### System information: 
- Operating system (distribution) and version - Windows Server 2008 R2 DataCenter Service Pack 1
- DBeaver version :Version 6.2.1.201909221630
- Java version :JRE8

#### Connection specification:
- Database name and version: Redshift 
- Driver name : RedshiftJDBC42-no-awssdk-1.2.27.1051.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I create a bunch of schemas and tables under the default database (ri). When I go and create a new database its showing up with all the schemas and tables of the default database when it should actually be just an empty database
This is showing correctly in SQLWorkbench and Navicat. Screenshot attached

![DBeaver](https://user-images.githubusercontent.com/56049968/66001409-6b0c9400-e46f-11e9-9f6d-b54df405bad7.png)
![Navicat](https://user-images.githubusercontent.com/56049968/66001410-6b0c9400-e46f-11e9-822a-366aa86af0c9.png)

**Comment by uslss** [comment]
Issue isn't reproducible anymore.
Ticket closed
