### ISSUE TITLE
Impala driver ignoring SOCKS proxy config after the 20190922 update

### ISSUE THREAD

**Issue by DzamoNorton** [dbeaver/dbeaver#6898]
#### System information: 
- Debian testing
- DBeaver IDE 6.2.1.201909221630 installed as an extension to Eclipse 2018-12 (4.10.0)

#### Connection specification:
- Cloudera Impala
- `com.cloudera.impala.jdbc41.Driver`
- SOCKS

#### Describe the problem you're observing:
In the past (I _think_ before the update in the title) DBeaver would respect my SOCKS proxy settings when connecting to Impala.  Now DBeaver ignores the SOCKS proxy (which is provided by SSH) and connects directly.

#### Steps to reproduce, if exist:
1. Configure a Cloudera Impala connection to use a SOCKS proxy.
2. Either disable the proxy or watch debug ouput on the proxy.
3. Connect to Impala from DBeaver and observe that the connection does not use the proxy.

#### Include any warning/errors/backtraces from the logs
None

**Comment by serge-rider** [comment]
Thanks for the bug report
