### ISSUE TITLE
Data grid view: Data sorting bug

### ISSUE THREAD

**Issue by sefacan** [dbeaver/dbeaver#6899]
#### System information: 
- Windows 10 Pro 1903
- DBeaver 6.2.1

#### Connection specification:
- PostgreSQL 10.7
- PostgreSQL JDBC Driver

#### Describe the problem you're observing:
When I open a table, the order of the data listed in the data tab is shown in the following figure.
![Image](https://cdn1.imggmi.com/uploads/2019/10/2/1eed914c23d72d4ee5d68cc45931d0b2-full.png)

#### Steps to reproduce, if exist:
1. Connect PostgreSQL.
2. Open some table from database.

#### Include any warning/errors/backtraces from the logs

None

**Comment by palbr** [comment]
I am no dbeaver developer. I am just another dbeaver user, who is looking whether the bug I found has been reported before.

@sefacan:
Looking at your bug report, I cannot identify the problem. What did you expect and what actually happened?

**Comment by tati-kru** [comment]
@palbr you are right, thank you for your assistance.

@sefacan the data is not sorted by default. If you need to sort data in some order you can add this condition to your query or just use a sorting button at the column header in the data viewer.
