### ISSUE TITLE
Scientific notation not colored as number

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#6901]
**Steps to reproduce:**
* Open an SQL editor.
* Write some query involving a number in scientific notation, e.g.
```sql
select 1e-5
from some_table
```

**Expected behavior:** the whole number should be colored according to number color settings.

**Actual behavior:** the `e` and the `+` or `-` take on text color instead of number color.

**Comment by serge-rider** [comment]
Fixed
