### ISSUE TITLE
ClickHouse driver is buggy since 0.1.55 (typo inside)

### ISSUE THREAD

**Issue by sarbash** [dbeaver/dbeaver#6902]
#### System information: 
- Debian GNU/Linux bullseye/sid (Linux debian 5.2.0-2-amd64 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux)
- Version 6.2.2.201909281047

#### Connection specification:
- ClickHouse 19.1.6
- ClickHouse
- No tunnels or proxies

#### Describe the problem you're observing:
I'm unable to get a column list from DB.
DBeaver shows me an error message: "no column default_expresseion in columns list database table name type default_type default_expression".

#### Steps to reproduce, if exist:
Try to open column list from a non-system table.

#### Include any warning/errors/backtraces from the logs
I think this piece should be enough to fix this issue:

```
!ENTRY org.jkiss.dbeaver.model 4 0 2019-10-02 14:47:39.191
!MESSAGE Can't read attributes
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-10-02 14:47:39.191
!MESSAGE no column default_expresseion in columns list database table name type default_type default_expression
!STACK 0
java.lang.RuntimeException: no column default_expresseion in columns list database table name type default_type default_expression
        at ru.yandex.clickhouse.response.ClickHouseResultSet.asColNum(ClickHouseResultSet.java:616)
        at ru.yandex.clickhouse.response.ClickHouseResultSet.getString(ClickHouseResultSet.java:251)
        at ru.yandex.clickhouse.ClickHouseDatabaseMetadata.getColumns(ClickHouseDatabaseMetadata.java:863)
```
I've found the typo in the file `ClickHouseDatabaseMetadata.java`.

**Comment by GithubUser5462** [comment]
Probably related to https://github.com/ClickHouse/clickhouse-jdbc/issues/381
