### ISSUE TITLE
Script type in list does not match script type in properties

### ISSUE THREAD

**Issue by amivanovano** [dbeaver/dbeaver#6907]
Phrase **SQL File** carries no information for me ( unlike **Linked File** ! )

![image](https://user-images.githubusercontent.com/28041955/66124372-dc258600-e5ec-11e9-90ef-4d0d3df81e5f.png)

**Comment by kseniiaguzeeva** [comment]
@amivanovano Sorry for the long answer. You can create a separate folder for linked files and keep them there.
![dbeaver_uq2lOdtlgM](https://user-images.githubusercontent.com/51405061/78010600-3a88b280-734b-11ea-94b4-d22a124017ba.png)

**Comment by amivanovano** [comment]
Thanks, Kseniia.
That 's exactly what I did.
But I think this decision is workaround.

Best regards,
Alex
