### ISSUE TITLE
Explain Plan output not working

### ISSUE THREAD

**Issue by snojha** [dbeaver/dbeaver#6908]
Explain plan output showing 

Node Type                                          Cost
Status: Legacy query optimizer       Null - Null

Just ran explain plan on a simple query

select * from pg_tables;

Env: Greenplum Database version 5.21

**Comment by serge-rider** [comment]
This looks like an issue with server configuration.
What do you see when you execute `explain select * from pg_tables;` ?

**Comment by snojha** [comment]
In the output window.

Header

Node Type                                     |    Entity
 |Cost              |Rows    |Time     |Condition
=====================================================================
Status:Legacy query optimizer     |                             |null -
null        |             |             |


Regards
Sachchida (Sachi) N Ojha

This is a PRIVATE message. This message, and any attachments, is for the
intended recipient(s) only, may contain information that is privileged,
confidential and/or proprietary. If you are not the intended recipient,
please delete without copying and kindly advise us by e-mail of the mistake
in delivery.

**Comment by serge-rider** [comment]
Yep. Exactly as I said - this is server-side issue.
Check this article about GP planner config: https://community.pivotal.io/s/article/Pivotal-Query-Optimizer-Explained

**Comment by snojha** [comment]
OK.  Now its working for some users but not for all users. Is there any
user specific setting?

Regards
Sachchida (Sachi) N Ojha

This is a PRIVATE message. This message, and any attachments, is for the
intended recipient(s) only, may contain information that is privileged,
confidential and/or proprietary. If you are not the intended recipient,
please delete without copying and kindly advise us by e-mail of the mistake
in delivery.

**Comment by ghost** [comment]
Hello,

I have to configure Dbeaver to use SSO (Single sign On) login without
password.  I was able to configure pgadmin4 and psql to use SSO but dbeaver
as always asking for a password. Can you assist or provide me with a
document to configure Dbeaver for SSO. We are using the Greenplum database
on RHEL7.
Regards
Sachchida (Sachi) N Ojha

This is a PRIVATE message. This message, and any attachments, is for the
intended recipient(s) only, may contain information that is privileged,
confidential and/or proprietary. If you are not the intended recipient,
please delete without copying and kindly advise us by e-mail of the mistake
in delivery.
