### ISSUE TITLE
Task for imprort from CSV isn't saved correctly.

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6909]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.2
#### Describe the problem you're observing:
Task for "Import from CSV" isn't saved correctly. Import info in Task window is empty
#### Steps to reproduce, if exist:
1. Start import from CSV to some table from Context menu in DB nsvigator
2. Choose CSV, Save task
3. Open task from DB tasks tab -> Import info is empty - no table here, import couldn't be started

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified, but ticket 6883 is still reproducing.
