### ISSUE TITLE
Load and execute script with special character

### ISSUE THREAD

**Issue by filipemanuelofs** [dbeaver/dbeaver#6910]
#### System information: 
- Operating system (distribution) and version
Windows 10 Pro
- DBeaver version
6.1.1.201906240635

#### Describe your question:
Hi, I'm investigating an error on my application and discover that is because an special character (NULL) in SQL script (pic. 1). I wondering if is possible to reproduce those characters on DBeaver editor.

Picture 1
![image](https://user-images.githubusercontent.com/1047292/66141350-eab67200-e5d9-11e9-8274-cfadbba69637.png)

**Comment by kseniiaguzeeva** [comment]
Is this issue still actual for you?
Null can be used in DBeaver SQL Editor.

**Comment by uslss** [comment]
there is no update on ticket for a long time. if issue is still actual for you - feel free to reopen the ticket
