### ISSUE TITLE
Glitchy UI bug(s) makes DBeaver unusable

### ISSUE THREAD

**Issue by rmainseas** [dbeaver/dbeaver#6913]
When writing a SQL query, the SQL window is completely beige so I can't see the text I'm writing. 
![dbeaver](https://user-images.githubusercontent.com/50675045/66169698-464f2280-e60f-11e9-87fe-0cc45321a912.gif)

Additionally, the results grid is also totally beige so I can't see query results (though, the text based results table works okay)

Clicking on a tab to change SQL windows causes the whole UI to break like so:
![image](https://user-images.githubusercontent.com/50675045/66169752-739bd080-e60f-11e9-96b8-4a69e9d27a6e.png)

When I open dbeaver I also get this message(not sure if it's related):
![image](https://user-images.githubusercontent.com/50675045/66169660-27e92700-e60f-11e9-8e27-54b1110ee4b5.png)

I get that window every time I open dbeaver, I've tried clearing out the relevant temp files from ~/.config, ~/.dbeaver, ~/.local etc. and it still happens.

---

#### System information: 
- Operating system (distribution) and version: Debian 9 - Stretch
- DBeaver version: 6.2.1
- Additional extensions: None.

#### Connection specification:
- Database name and version: Postgres
- Driver name: Postgresql (though it happens to MariaDB as well)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

#### Steps to reproduce, if exist:
1. Open dbeaver
1. Connect to a PostgreSQL database
1. Write a SQL query and/or open a table to view data

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/50675045/66169850-cf665980-e60f-11e9-84ab-690119e51040.png)

**Comment by serge-rider** [comment]
The problem with UI glitches caused by GTK config issues.
Please check for solution in #6640.

Error with locked workspace may happen if some other DBeaver process is running. Try to kill it or to reboot.

**Comment by rmainseas** [comment]
Just for anyone who finds this in future:

Looks like the solution for the GUI problems described in here were caused  by a misconfigured input device. Running `im-config` as my own user and selecting `ibus` fixed it for me.
