### ISSUE TITLE
Inverse reference lookup

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#6915]
Right now when I setup a foreign key (virtual or physical), I'm able to navigate from the child table to the parent one; this way navigation should always show 1 line since the parent table is accessed through an unique key.

It would be really nice to do the reverse: from the parent table to be able to show all the child rows. This is currently not working, at least for virtual foreign keys, I don't have physical ones to try with.

Possibly related, ER Diagram for parent table doesn't show the child table. I can open a different ticket for this one.

**Comment by p91paul** [comment]
Sorry I put the bug label by mistake, this is more likely a feature request.

**Comment by serge-rider** [comment]
You could try reference panel. Or <kbd>ctrl+1</kbd> which show both imported and exported keys.

**Comment by p91paul** [comment]
My bad, I was still on 6.2.0, on 6.2.2 it works.
