### ISSUE TITLE
Long and incomplete fetch of Sybase IQ stored procedures and view sources

### ISSUE THREAD

**Issue by zolovey** [dbeaver/dbeaver#6916]
#### System information:
- DBeaver version: 6.2.1.201909221630

#### Connection specification:
- Database name and version: Sybase IQ SAP IQ/16.1.030.1437
- Driver: jConnect (TM) for JDBC(TM)/16.0 SP03 PL02 (Build 27403)/P/EBF27518/JDK 1.6.0/jdbcmain/OPT/Mon Aug 28 18:41:14 PDT 2017

#### Describe your question:
In current version of DBeaver the sources of views and stored procedures are read with following query:
```sql
SELECT
    "sc"."text"
FROM
    "iqbdw"."dbo"."sysobjects" AS "so"
    ,"iqbdw"."dbo"."syscomments" AS "sc"
WHERE
    "user_name"("so"."uid") = :p0
    AND "so"."name" = :p1
    AND "sc"."id" = "so"."id"
```
The problem with the "text" field - if the DB option PRESERVE_SOURCE_FORMAT is set to OFF, then it contains unformatted source text (originally in SYS.ISYSPROCEDURE.PROC_DEFN). Meaning that it is not the same as deployed
The second problem is with the performance - usually it takes up to 40 seconds to see the source of view/procedure.

Wouldn't it be possible to change the query that reads sources to the following one?
```sql
SELECT S.source
  FROM DBO.SYSOBJECTS AS SO
  JOIN SYS.SYSUSER    AS U ON U.user_id   = SO.UID
  JOIN SYS.SYSSOURCE  AS S ON S.object_id = SO.id
 WHERE user_name(so.uid) = :p0
   AND so.name = :p1
```
This query works pretty fast and contains original source code for view/procedure.

**Comment by serge-rider** [comment]
Yes, we need to fix this. Thanks for query suggestion

**Comment by serge-rider** [comment]
Fixed.
Unfortunately I don't have SAP IQ server for testing, only SAP ASE. And it has different system objects model (there are no sysobjects and sysuser views). Thus I can't check the fix.
Could you test it in Early Access version (https://dbeaver.io/files/ea)?

I check SAP IQ server by testing product version for "SAP IQ" substring (product version is printed in the Test Connection dialog).

**Comment by zolovey** [comment]
tested EA version.

it still reads data using old way
```sql
SELECT
    "sc"."text"
FROM
    "iqbdw"."dbo"."sysobjects" AS "so"
    ,"iqbdw"."dbo"."syscomments" AS "sc"
WHERE
    "user_name"("so"."uid") = :p0
    AND "so"."name" = :p1
    AND "sc"."id" = "so"."id"
```

Here is the connection info.
![image](https://user-images.githubusercontent.com/56155099/75136369-2e2a8d80-56ed-11ea-88c4-d2a8ce09253b.png)

Maybe this has to be changed

**Comment by serge-rider** [comment]
@zolovey Please try new EA. I fixed IQ server detecttion but still not sure how sQL query will work

**Comment by zolovey** [comment]
@serge-rider unfortunately it still reads using old way

**Comment by serge-rider** [comment]
Thanks. 
I give up for now. 
We need to have Sybase IQ server to implement and test it.

**Comment by zolovey** [comment]
@serge-rider tried to identify what `dataSource.getInfo().getDatabaseProductName()` prints out.
added `log.warn(dataSource.getInfo().getDatabaseProductName());` into SQLServerMetaModel.java and in log i see:
`2020-02-26 09:15:30.453 - Sybase IQ`

**Comment by zolovey** [comment]
any news about the issue?

**Comment by zolovey** [comment]
@serge-rider please change product name from "IQ SAP" back to "SAP IQ" in SQLServerMetaModel.java. (line 75)

Prior to version 16.1.040 product name was "Sybase IQ"

after that product is "SAP IQ"

**Comment by EmaD-2306** [comment]
Any news about this issue? It is a real shame not to be able to use this functionality with SAP IQ.
Thanks

**Comment by serge-rider** [comment]
Fixed
