### ISSUE TITLE
import task couldn't be saved - name == null

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6918]
#### System information: 
- Operating system (distribution) and version win 10 x64

#### Steps to reproduce, if exist:
1. Start import from csv
2. Try to save import - click Save
3. Enter task name - Try to save - error appears
[log_namenull.log](https://github.com/dbeaver/dbeaver/files/3690377/log_namenull.log)

**Comment by serge-rider** [comment]
Can't reproduce. Perhaps fixed along with other DT-related bugfix.
