### ISSUE TITLE
PostgreSQL and PostGIS, point and line gets converted to _float8[] ?

### ISSUE THREAD

**Issue by sirber** [dbeaver/dbeaver#6919]
#### System information: 
- Operating system (distribution) and version
Ubuntu 18.04 x64
- DBeaver version
6.2.1

#### Connection specification:
- Database name and version
PostgreSQL 11.5

#### Describe your question:
On a postgis-enabled database, when I create a table with 'point' and 'line' colums, they get converted into 'float8[]' colums. Why? pgAdmin3 dones't have this behavior.

pgAdmin3:
```
CREATE TABLE public.newtable
(
  id integer NOT NULL,
  point point,
  line line,
  CONSTRAINT newtable_pk PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.newtable
  OWNER TO homestead;
```

dBeaver:
```
CREATE TABLE public.newtable (
	id int4 NOT NULL,
	point float8[] NULL,
	line float8[] NULL,
	CONSTRAINT newtable_pk PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.newtable OWNER TO homestead;
GRANT ALL ON TABLE public.newtable TO homestead;
```

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
