### ISSUE TITLE
ER Diagram: No relations in PostgreSQL

### ISSUE THREAD

**Issue by azzamsa** [dbeaver/dbeaver#6920]
#### System information: 
- Debian GNU/Linux 10 (buster) x86_64
- DBeaver 6.2.1

#### Connection specification:
- PostgreSQL 11 
- PostgreSQL JDBC Driver

#### Describe your question:

I've seen people successfully generated ER-Diagram and it's relations in PostgreSQL with Dbeaver .e.g [1](https://stackoverflow.com/a/48397209/6000005). There are some issue related to ER-Diagram and postgreSQL but already fixed, e.g [1](https://github.com/dbeaver/dbeaver/issues/1554).

I've successfully install and run [gitea](https://docs.gitea.io/en-us/#components) without any problem with PostgreSQL database. all feature served me well. I use dbeaver to see it's database.

But when It comes to generating ER-Diagram, I can't find any relations.

![Untitled](https://user-images.githubusercontent.com/17734314/66251748-a2d05000-e77d-11e9-97ea-f241011068c6.png)

and, dbeaver seems can't find the foreign keys, is this the clue?

![image](https://user-images.githubusercontent.com/17734314/66251765-c8f5f000-e77d-11e9-818e-1b7d34da1144.png)

Thanks for DBeaver.

**Comment by uslss** [comment]
Unfortunately, cannot reproduce the issue.
Probably you could share an example of db with the issue or anything else that could help to investigate the issue?

**Comment by azzamsa** [comment]
Sorry for the late reply. I still manage some other tasks.

I manage to dump the schema only using: `$ pg_dump --username=gitea --dbname=gitea --host=localhost --password -s > gitea.txt`

[gitea.txt](https://github.com/dbeaver/dbeaver/files/3929894/gitea.txt)

I always use dbeaver, the ER diagrams work for my other project. I don't have any idea why it didn't work in gitea schema. Feel free to tell me if you need other thing to make it reproducible.

**Comment by kseniiaguzeeva** [comment]
@azzamsa Sorry for the long answer. Is it still actual for you?

**Comment by azzamsa** [comment]
updated to 7.0.5 this morning and I still have the same issue.

Have you tried to reproduce in your end using this [gitea.txt schema](https://github.com/dbeaver/dbeaver/files/3929894/gitea.txt)?

**Comment by daniel-meppiel-sonarsource** [comment]
Hi, I have exactly the same issue on a new installation of DBeaver 7.1.3 on macOS, using PostgreSQL.

**Comment by kseniiaguzeeva** [comment]
@azzamsa Unfortunately I cannot restore the database you sent. Can you dump it one more time? 
Can you create FK via DBeaver? Are they dispalyed in this case?

**Comment by azzamsa** [comment]
Isn't the [dump file](https://github.com/dbeaver/dbeaver/files/3929894/gitea.txt) in my [previous comment](https://github.com/dbeaver/dbeaver/issues/6920#issuecomment-562390401) not accessible?

**Comment by azzamsa** [comment]
This is the displayed diagram and fk. in my first comment: https://github.com/dbeaver/dbeaver/issues/6920#issue-502930080

**Comment by uslss** [comment]
seems that there is no any foreign key in your db (as far as I see there are no any FK mentioned in your dump file).
All relations at ERD = db foreign keys, Seems that it is not dbeaver issue.
Relation is shown if I create some random FK in your DB sample
![image](https://user-images.githubusercontent.com/31996417/89654438-54c23680-d8d1-11ea-88b3-7f84e11ac733.png)

**Comment by azzamsa** [comment]
Actually, I don't create this db my self. I take it from [gitea](https://docs.gitea.io/en-us/)

If we look closer. Take on example of `comment` table. there we have `issue_id`. But the "FK" column of `comment` table is empty. 

![image](https://user-images.githubusercontent.com/17734314/89673393-77277480-d910-11ea-80fb-e9565fd9e58f.png)

I think I will close this issue for now. Since you can create the relation if the FK exists. 
Currently I don't have a time to see deeper how Gitea works. I will re-open if necessary.
