### ISSUE TITLE
Tables are created in a different database

### ISSUE THREAD

**Issue by abis866i** [dbeaver/dbeaver#6923]
#### System information: 
- Operating system (distribution) and version: Window 10 Home
- DBeaver version: 6.2.1
- Java version: 1.8
- Additional extensions: whatever dbeaver downloads for connecting to PostgreSQL

#### Connection specification:
- Database name and version: PostgreSQL 10.3 running in a Ubuntu Docker container
- Driver name: default PostgreSQL driver that Dbeaver has
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Tables that I create show in two databases. If I delete in one database, they get deleted in both. Actually they are created in a single database, that is not the active one but just shows in both.

#### Steps to reproduce, if exist:
- I start with a default database,say"test1"
- In dbeaver, I create a new database "test2"
- I set "test2" as active.
- I create a table "mytable" in "test2"
- I check both "test1" and "test2" and "mytable" is in both databases
- I check with pgadmin 4 and table is actually only in "test1" which was not active in dbeaver
- I delete "mytable" in "test1" and it disappears in both database.

**Comment by uslss** [comment]
cannot reproduce the issue. is it still actual for you against the recent version (6.3.0)?

**Comment by uslss** [comment]
there is no update on an issue more than a month.
Ticket closed.
If the issue still actual - feel free to reopen the ticket
