### ISSUE TITLE
No "Install New Software" menu item under help in 6.2.0.201909040839

### ISSUE THREAD

**Issue by ThistleApps** [dbeaver/dbeaver#6924]
I am trying to resolve the problem mentioned here https://github.com/dbeaver/dbeaver/issues/3917 and the instructions note to use "Help > Install New Software" but my client doesnt have that menu item.  Version 6.2.0.201909040839

Noting this is installed on Windows 64 from app store. I am running the app as an Administrator.

**Comment by ThistleApps** [comment]
Uninstalled that version, downloaded the Zip and installed from the zip.  Chose not to migrate settings.  I now have the install new software menu item from Help.

**Comment by numbworks** [comment]
I have the same issue on `DBeaver Version 24.3.3.202501201034` (2024).

Would it be possible for somebody here to explain why "`Help`" -> "`Install New Software`" is not present in the version installed via Microsoft Store? And if is it going to be fixed?

Thanks!
