### ISSUE TITLE
DBeaver lacks query execution plan for SQL server

### ISSUE THREAD

**Issue by ralebhattushar** [dbeaver/dbeaver#6925]
The version information of DBeaver, which I use, is as follows:
![image](https://user-images.githubusercontent.com/45413542/66285686-720e2900-e8eb-11e9-968d-8adb456fee23.png)

Currently, it is not possible to see the execution plan for SQL queries for SQL server database. Is there any reason for not having this feature? Only for this feature, it is required to use SQL Server Management Studio. So it will be nice to have this feature in DBeaver.

**Comment by serge-rider** [comment]
It is available in EE version only
