### ISSUE TITLE
Sorting from data viewer produces wrong SQL

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#6927]
**Steps to reproduce:**
* Run some select query from the SQL editor that would have: a) an `order by` clause, b) ordering from an aliased colum (`orig_name as other_name`), c) having present another aliased column (other than the one being sorted by).
* In the data viewer, sort by the other aliased column by clicking on the up arrow.

**Expected behavior:** should sort by the new column in the data viewer.

**Actual behavior:** throws an SQL error saying that it cannot sort by `table_name.aliased_name` (i.e. it's trying to sort by sending the aliased column name as if it were named like that in the table, instead of `table_name.orig_name`).

**Setup:** dbeaver 6.2.2, running on windows 10, connecting to postgresql.

Bug is not present in 6.2.0.

**Comment by serge-rider** [comment]
I can't reproduce this. please send a sample SQL query  (use system tables from pg_catalog)

**Comment by david-cortes** [comment]
Example problem query:
```sql
select
	*
	, ct.conname as "col1"
	, ct.connamespace as indatts
from pg_catalog.pg_constraint ct
left join pg_catalog.pg_index ix on ct.conparentid = ix.indnatts-1
```

(Try sorting by the last column from the results pane)

**Comment by serge-rider** [comment]
Fixed (now we check that column actually belongs to the ref table)

Workaround: 
![image](https://user-images.githubusercontent.com/6398845/81108083-d5634680-8f20-11ea-8d8f-0597ec63087e.png)

**Comment by kseniiaguzeeva** [comment]
verified
