### ISSUE TITLE
Date Format Result

### ISSUE THREAD

**Issue by oguzgogus** [dbeaver/dbeaver#6930]
Hello thanks for answers! 

Whatever i do i could not manage to change the date result format ''03-OCT-19 23:59:00'' to regular one like  03-10-2019 23:59:00 when i try to convert it with TO_DATE(XXX , 'dd/mm/yyyy hh24:mi:ss') it converts like "03-10-**0**019 23:59:00". Please help me!

i changed format time from properties to dd-MM-yyyy and timestamp to dd-MM-yyyy HH:mm:ss

**Comment by kseniiaguzeeva** [comment]
Hi, what is your DBeaver version and OS?
Did you check "Datasource settings" if apply to one database only (or uncheck if you applied changes in "global settings")?
Could you also send a printscreen of your "Data Formats" settings?

**Comment by uslss** [comment]
there is no update on ticket more than a month,
ticket closed.
if issue still actual for you - feel free to reopen the ticket
