### ISSUE TITLE
DBeaver crashes trying to display large multipolygon

### ISSUE THREAD

**Issue by ssrebelious** [dbeaver/dbeaver#6933]
#### System information: 
- openSUSE Leap 15.0
- DBeaver version 6.2.2, 6.2.1

#### Connection specification:
- PstgreSQL 10, PostGIS 2.5.2
- JDBC
- No
#### Describe the problem you're observing:

When viewing table with a huge polygon in it after clicking `Spatial` tab to view it on map DBeaver crashes. Smaller polygons and other geometries do not crash program. I believe couple of months ago everything worked fine.

#### Steps to reproduce, if exist:

Create a spatial table and insert a polygon with a huge amount of points in it. [See this sql](https://pastebin.com/3EbB9A8Y).

After that go to the table tab and click "Spatial" view -> DBeaver crashes.

#### Include any warning/errors/backtraces from the logs

[Crash log is here](https://pastebin.com/08y52Bsg).

**Comment by serge-rider** [comment]
Unfortunately I can't reproduce this. SQL script fails with error
`SQL Error [XX000]: ERROR: can not mix dimensionality in a geometry
  Hint: "...46, 35.237589 56.033435, 35.237707 56" <-- parse error at position 13472 within geometry
  Position: 43`

Could you make a database dump?

**Comment by ssrebelious** [comment]
Looked deeper into the issue and it seems that not the polygon itself is the issue, but a presence of an array record in the other column. If an array column is removed from the table DBeaver does not crash and display the polygon.

[Here is the dump](https://controlc.com/32d4e017).

**Comment by serge-rider** [comment]
I believe it is the same error as in #6949
It was fixed in 6.2.3, could you please test it?

**Comment by ssrebelious** [comment]
I confirm that the issue is gone with the version 6.2.3.
