### ISSUE TITLE
Mixed global and datasource settings in "Connection configuration"

### ISSUE THREAD

**Issue by n8falke** [dbeaver/dbeaver#6934]
In "Edit Connection" (in context menu of connection in Database Navigator) most settings belong to the data-source:
![grafik](https://user-images.githubusercontent.com/29731593/66321236-8b7d9800-e920-11e9-8897-d40a39207df5.png)

In the sub-menus below "Result Sets" and "SQL Editor" global settings are shown:
![grafik](https://user-images.githubusercontent.com/29731593/66321465-e57e5d80-e920-11e9-9f55-e53d3fc152ec.png)

To edit the data-source settings the link must be selected and the data source again.

Probably this was not intended. 

#### System information: 
- Operating system: Windows 10
- DBeaver version: 6.2.2.201910061950
- Additional extensions: Debugger + Office

#### Connection specification:
- Database name and version: Oracle 12.1; Postgresql 11
- Driver name: Oracle 12.2; Postgres: 42.2.5
- Do you use tunnels or proxies: No

**Comment by uslss** [comment]
Thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
