### ISSUE TITLE
DBeaver close everytime !!!

### ISSUE THREAD

**Issue by mcunha98** [dbeaver/dbeaver#6936]
Let me know where I found logs or something like that to show , after update to 6.2.2 during simple operations (like move from data tab to properties) DBeaver simply close and exit...

Ok, I don't lose anything important, but is strange, never this happen in previous versions.
I have this problem:

- editing data in data tab and press enter
- navegate into data tab and switch to properties

**Comment by serge-rider** [comment]
Seems to be very similar to #6928

However I can't reproduce second case (switch to properties tab).

**Comment by serge-rider** [comment]
Hotfix version has been published today.
