### ISSUE TITLE
Table column type autocomplete misbehaving

### ISSUE THREAD

**Issue by RoroTiti** [dbeaver/dbeaver#6937]
#### System information: 
- Operating system (distribution) and version
**macOS Mojave and Windows 10**
- DBeaver version
**6.2.2.201910061950**
- Additional extensions
**None**

#### Connection specification:
- Database name and version
**MySQL 8.0.17**
- Driver name
**mysql:mysql-connector-java:RELEASE 8.0.17**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
**No**

#### Describe the problem you're observing:
The column type autocomplete seems to be buggy, as the following GIF demonstrates :

![](https://i.imgur.com/73odnfC.gif)

#### Steps to reproduce, if exist:
Just do like on the screenshot.

**EDIT**

I would like to add something : the modification of the data type does not allow the user to save changes by clicking the **Save** button. In order to make the **Save** button clickable, it's necessary to, for example, change the name of the column and retablish it (in my example, let's say remove the Y from __id_category__ and re-add it in order to allow saving changes)

**Comment by uslss** [comment]
Thanks for the bug report

**Comment by RoroTiti** [comment]
I would like to add something : the modification of the data type does not allow the usser to save chnages by clicking in **Save** button. In order to make the save button clickable, it's necessary to, for example, change the name of the column and retablish it (in my example, let's say remove the Y from __id_category__ and re-add it in order to allow saving changes)

**Comment by uslss** [comment]
issue is fixed.
Ticket closed
