### ISSUE TITLE
[Oracle] Code completion in select table or view

### ISSUE THREAD

**Issue by norlancd** [dbeaver/dbeaver#6939]
#### System information: 
- Windows 10 x64
- DBeaver version - 6.2.2.201910061950
- Additional extensions

#### Connection specification:
- Database name and version  - Oracle 11g
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When writing in a query and using the table/view completion, an "AS" is being wrongly added between the table/view name which generates an ORA-00933 error. Example SELECT * FROM PARTNER **AS** p.

**Comment by uslss** [comment]
Hi @norlancd ,
btw, you can disable table aliases inserting in Preferences - Databases - SQL Editor - SQL Completion (for all connections) or  from context menu in SQL editor for defined connection.
![image](https://user-images.githubusercontent.com/31996417/66374667-26738200-e9b4-11e9-9645-172d682c8a86.png)

**Comment by serge-rider** [comment]
We'll disable this option by default.

**Comment by uslss** [comment]
verified

**Comment by norlancd** [comment]
> We'll disable this option by default.

@serge-rider. Include the alias as the option selected by default is not bad. The error is that when the option "Insert table aliases (in FROM clause)" is selected in ORACLE, only the alias should be included without the "AS".

- **Wrong**

SELECT * FROM "Partner" AS p

- **Right**

 SELECT * FROM "Partner" p
