### ISSUE TITLE
[Oracle] Comments disappear when I try to persist a create table

### ISSUE THREAD

**Issue by dnroldan** [dbeaver/dbeaver#6940]
#### System information: 
- Windows 7 64 bits Enterprise
-   DBeaver	6.2.2.201910061950

#### Connection specification:
- Oracle 11.2.0.3.0
- Driver name --> JDBC Thin Client
- Do you use tunnels or proxies (SSH, SOCKS, etc)? --> No

#### Describe the problem you're observing:
When I create a new table, I put the columns, types and comments for each column.
When I generate the DDL to persist, there isn't the comments and after I persist it, the comments have disappeared.

**Comment by uslss** [comment]
Thanks for the bug report!

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
