### ISSUE TITLE
Field only accepts first line

### ISSUE THREAD

**Issue by zombiesbyte** [dbeaver/dbeaver#6941]
#### System information: 
- Windows 10
- 6.2.0

#### Describe the problem you're observing:
When trying to edit the data on existing rows and double clicking into the field (Varchar). I would paste in the new content that has multi-lines and the result would only receive the first line.

#### Steps to reproduce, if exist:
Create a table with a simple varchar field. Add a row containing anything you like but then edit that row by double clicking and pasting in this comment:

This is the first sentence
This is the second sentence
This is the third sentence

The result will be that only "This is the first sentence" is saved and "This is the second sentence
This is the third sentence" will be missing.

Guess: It seems that varchar is assumed to never contain new lines and perhaps an incorrect entry field has been used in the application.

**Comment by serge-rider** [comment]
@zombiesbyte This is not a bug. You can edit multi-line string in inline editor.
Solutions:
- Just paste value without opening the editor (select a cell, press <kbd>ctrl+v</kbd>).
- Open value edit panel (f7 + click on Value icon on the right sidebar). You can edit multiline string there.
