### ISSUE TITLE
The auto-incrementation number is not correct

### ISSUE THREAD

**Issue by Paulo30500** [dbeaver/dbeaver#6942]
#### System information: 
- Operating system (distribution) and version Windows 10 Pro
- DBeaver version 6.2.2
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

When I open a file, I see that the auto-incrementation  is the same that the total of lines in the data page... And not total of lines + 1

![image](https://user-images.githubusercontent.com/56126343/66383177-d220d000-e9bc-11e9-9057-8618e06b981e.png)
![image](https://user-images.githubusercontent.com/56126343/66383230-ed8bdb00-e9bc-11e9-9091-abde18519f25.png)
![image](https://user-images.githubusercontent.com/56126343/66383269-fe3c5100-e9bc-11e9-9117-e20b89a0d4c6.png)

**Comment by rafafr** [comment]
Please correct me if I am wrong, but I think this the correct behaviour. The value shown is the CURRVAL of the sequence/identity and the database will get the NEXTVAL (CURRVAL + interval) at next row insert.

**Comment by Paulo30500** [comment]
yes you are right but actually the NEXTVAL is not correct...
Sometimes the NEXTVALL = CURRVAL
Sometimes the NEXTVAL = CURRVAL - Interval
And never the NEXTVAL = CURRVAL + Interval

**Comment by uslss** [comment]
not reproducible anymore
