### ISSUE TITLE
Very slow startup on enterprise version

### ISSUE THREAD

**Issue by majkinetor** [dbeaver/dbeaver#6943]
#### System information: 
- Operating system (distribution) and version:  
Microsoft Windows 10 Enterprise  10.0.17763 N/A Build 17763
- DBeaver version:  
6.2.0

#### Describe the problem you're observing:
I have ~10s latency during startup where dBeaver is frozen. This doesn't happen on community version.

#### Include any warning/errors/backtraces from the logs

Freeze happens after first line and lasts ~13s:
```
2019-10-08 13:27:03.113 - > Start Equinox Provisioning UI Support [org.eclipse.equinox.p2.ui 2.5.500.v20190220-1158]
2019-10-08 13:27:15.098 - Error checking license DB-721MOZLM-ZPIQ status: No such host is known (dbeaver.com)
```

I am behind corporate proxy, which is set in properties. Tried different proxy with same results

This is lic screen:

![image](https://user-images.githubusercontent.com/85767/66392518-5d579100-e9d0-11e9-85ec-520e4a1a4cb3.png)

**Comment by serge-rider** [comment]
his happens because DBeaver can't connect to the license server for license validation. We need to do this in background to avoid main process block.

**Comment by majkinetor** [comment]
Definitelly in the backgound. Not sure why it can't connect, other network functions (i.e. drivers) work OK.

**Comment by uslss** [comment]
verified
