### ISSUE TITLE
Error after updating to macOS Catalina

### ISSUE THREAD

**Issue by Avani10** [dbeaver/dbeaver#6945]
#### System information: 
- Operating system : macOS Catalina
- DBeaver version : 6.2.2

#### Problem Description: 
DBeaver can't be opened as Apple can't check it for malicious software (check attached image)
<img width="424" alt="Screen Shot 2019-10-08 at 1 36 56 PM" src="https://user-images.githubusercontent.com/32087361/66425295-e375d680-e9d4-11e9-8da6-1b805f208e63.png">

**Comment by serge-rider** [comment]
Apple added something called "Notarization" in Catalina.
We'll try to do this before the next release.

**Comment by serge-rider** [comment]
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution
https://developer.apple.com/news/?id=09032019a

**Comment by Avani10** [comment]
Wished to check the timeframe of when would this happen? Is there any quick fix at the moment so that I can go ahead with using DBeaver on Catalin?

**Comment by tati-kru** [comment]
You can run DBeaver on Catalina through the right click menu. The same alert message will be shown but you will be able to press Open button and run installation process.

**Comment by Avani10** [comment]
Thanks worked :)

**Comment by serge-rider** [comment]
We'll added app notarization since 6.2.3

**Comment by y-tee** [comment]
Hi, I still get this at version 7.2.2. Any idea? 
I installed with brew with ```brew cask install dbeaver-community``` with jdk8 already installed. 
I am on Catalina 10.15.7

**Comment by y-tee** [comment]
> Hi, I still get this at version 7.2.2. Any idea?
> I installed with brew with `brew cask install dbeaver-community` with jdk8 already installed.
> I am on Catalina 10.15.7
Solved this. Need to enable this at Security and Privacy.

**Comment by toera** [comment]
Any plans to re-add notarization? By policy, I'm not allowed to bypass this requirement on my mac

**Comment by tati-kru** [comment]
All new product versions have notarization for macOS.
