### ISSUE TITLE
Data types selection limited to (cid, oid, tid, varchar, xid) for column definition - Version 6.2.2.201910061950 - ops Debian 10 - Postgresql version 11 -  This issue occurs sporadically, it happened in a previous version 

### ISSUE THREAD

**Issue by wrhcash** [dbeaver/dbeaver#6946]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
there is no update for the ticket more than a month. ticket closed
