### ISSUE TITLE
Impala views sometimes show up as tables in the Database Navigator

### ISSUE THREAD

**Issue by dzamo** [dbeaver/dbeaver#6947]
#### System information: 
- Debian testing
- DBeaver IDE 6.2.2.201910061950 installed as an extension to Eclipse 2019-09 R (4.13.0)

#### Connection specification:
- Cloudera Impala CDH-6.1.1-1.cdh6.1.1.p0.875250
- com.cloudera.impala.jdbc41.Driver
- SOCKS

#### Describe the problem you're observing:
Impala views do often, but don't always, show up as _tables_ in the Database navigator.  Running an `ALTER VIEW` statement on an existing view and then refreshing in the navigator seems to make the navigator display the view in the right place.  But this will only be temporary and when you next open DBeaver the view will be in the wrong place.

#### Steps to reproduce, if exist:
Create some Impala tables and views using `CREATE TABLE` and `CREATE VIEW` then find them in Database Navigator.

**Comment by uslss** [comment]
@dzamo , unfortunately we've got no env to test.
Is it still actual?

**Comment by dzamo** [comment]
> @dzamo , unfortunately we've got no env to test.
> Is it still actual?

I'm afraid I can no longer test Impala either, so I can't say if the issue still exists.

**Comment by uslss** [comment]
if issue is still actual - feel free to reopen this issue or create a new one
