### ISSUE TITLE
[BUG-Postgres] Generating (or watching) procedure/function source does not show grants

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6948]
Grants are not shown when viewing or generation functions or procedures DDL

**Comment by serge-rider** [comment]
Click on "Show Permissions" in the bottom toolbar:
![image](https://user-images.githubusercontent.com/6398845/66583168-8f612280-eb8b-11e9-87a1-c37034c7082a.png)

**Comment by wiwwo** [comment]
Ok, got it.
Just to bother a little :-), from a UX point of view, it is not coherent: wether you always have it activated by default, as from "tables" view, or you never activate by default.
Just my 2 cents... :-)
BTW, is there a way to enable/disable it by default? (Sorry for the OT)

**Comment by wiwwo** [comment]
Sorry to bother guys, but this inconsistent behavior is making me 1) go crazy, 2) loose important information...
Is there a way to show proc/funcs grants by default, just like with all other DB objects?

**Comment by wiwwo** [comment]
Really...
PLEASE :-D

**Comment by wiwwo** [comment]
I lost an hearth bear reading 
"
PostgreSQL:
    Schema privileges were added in DDL 
"
in 6.3.5 Release ontes, thinking it was about this ticket.
It was not.
Me sad :-(

**Comment by wiwwo** [comment]
Please ... ... ...
![image](https://user-images.githubusercontent.com/3930671/75232830-2f74bc80-57b8-11ea-9b15-e7aabc8f52a7.png)

**Comment by wiwwo** [comment]
![image](https://user-images.githubusercontent.com/3930671/75860758-a3d4de80-5dfc-11ea-8ed9-945b656b42c2.png)

**Comment by serge-rider** [comment]
This makes sense :)

Now all options (like "show permissions") will be saved in preferences. So you need to enable it just once.

**Comment by uslss** [comment]
verified
