### ISSUE TITLE
Map viewer not available when integer[] and geometry in resultset

### ISSUE THREAD

**Issue by HannesMas** [dbeaver/dbeaver#6949]
#### System information: 
- Operating system: windows10 x64 Enterprise
- DBeaver 6.2.2.201910072100
- Additional extensions

#### Connection specification:
- PostgreSQL 11.5 (Debian 11.5-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
- Postgis: POSTGIS="2.5.2 r17328" [EXTENSION] PGSQL="110" GEOS="3.5.1-CAPI-1.9.1 r4246" SFCGAL="1.3.0" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.1.2, released 2016/10/24" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" TOPOLOGY RASTER
- PostgreSQL JDBC Driver 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
When writing a query which returns spatial data (linestrings and polygon) as well as an array of integers, the Value panel does not show the 'Map' button to view the geometry. Also navigating through the fields in the Result Grid is acting very slowly. 
When leaving out the array from the query, the behavior is as usual: Map viewer is available for geometry fields and navigating through the  fields in the Result Grid is smooth.

#### Steps to reproduce, if exist:
I assume this issue shows with every resultset having a geometry column and an array column. I'm adding the necessary data in below sql file to be able to replicate the issue. It contains table and function setup, the query without array in resultset and query with array in resultset.

[sql_for_issue_replication.txt](https://github.com/dbeaver/dbeaver/files/3706360/sql_for_issue_replication.txt)
--edit--
Actually, no need to make it this complicated. Just select a geometry and integer[] from nothing. Also then the issue shows at my end. Ie:
`SELECT ST_GeomFromText('LINESTRING(-57.6080247 -25.3058286,-57.6081362 -25.3060854)', 4326), ARRAY[1,2];`
--end of edit--

#### Include any warning/errors/backtraces from the logs
When running the query, the stacktrace in below txt file shows up (extracted from dbeaver .log file. The same stacktrace shows in the dbeaver-debug.log
[stacktrace_from_dbeaver_log.txt](https://github.com/dbeaver/dbeaver/files/3706323/stacktrace_from_dbeaver_log.txt)

**Comment by HannesMas** [comment]
I'm not sure if this is related to the latest release specifically. This is the first query I wrote with the latest release. I did not try the same query in the previous release I had (6.2.1).

**Comment by uslss** [comment]
verified
