### ISSUE TITLE
Connections persist when switching active databases

### ISSUE THREAD

**Issue by korrisscontext** [dbeaver/dbeaver#6950]
When I right click a different database and "set active", I look in pg_stat_activity and I can see that I have two connections, one to the newly active database and also the database I came from (no longer active). I'd expect that the old connection would be dropped. 

#### System information: 
- Windows 7 Professional - SP1
- DBeaver 6.2.2

#### Connection specification:
- PostgreSQL 9.4
- postgresql-42.1.4.jar
- localhost connection

#### Steps to reproduce
- Connect to connection (db1)
- SELECT * FROM pg_stat_activity (shows one connection, correct)
- Set db2 as active database
- SELECT * FROM pg_stat_activity (shows two connections, incorrect)

**Comment by serge-rider** [comment]
Unfortunately it is not that easy. 
Old connection still may be needed (e.g. to read database metadata when you browse database navigator tree).
We can add new option, something like "shutdown old database on activate database change". It will disconnect and collapse database navigator elements.
WDYT?

**Comment by korrisscontext** [comment]
I have my connection setup to use only one connection (shared between tabs, and to read the metadata). If you feel it needs an extra option, I'd personally expect that as default behavior but as long as it works then I don't mind having another setting.

**Comment by Pengchenghua** [comment]
the same is true hive

**Comment by serge-rider** [comment]
It is PG-driver specific behavior. PostgreSQL needs separate physical connection to each database.

**Comment by serge-rider** [comment]
I don't see how we can fix this. 
We can't just drop previous connection.
Changing "Active" database doesn't mean that previous database is not needed - it still may be used by SQL editor(s) or open metadata object editors or some background database tasks.
Perhaps we can implement some sort of "connection garbage collection" but it won't be easy to implement.

Workaround: do Disconnect to close all extra connections or use separate dbeaver connection for each PG database.
