### ISSUE TITLE
ResultSet is closed

### ISSUE THREAD

**Issue by xfzhaoxd** [dbeaver/dbeaver#6952]
#### System information: 
- windows10
- DBeaver version 6.2.1
- Additional extensions

#### Connection specification:
- MS SqlServer2008R2 
-  MS JDBC Driver 
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
When I  use select command query data  and append record in console in table style,click  sort button, open the dialog to comfirm update to database，I found "sql execute error":ResultSet is closed,but I found  data is updated in the table.

**Comment by xfzhaoxd** [comment]
If  I configure  to keep connection 5 seconds, I will  reslove this problem.
network problem?

**Comment by serge-rider** [comment]
Please post error log (with stack). It is not clear where exactly this error happens (in driver or on dbeaver side).
Potentially it can be caused by network issues, keep-alive may solve this problem in some cases. But other reasons are also possible.

**Comment by uslss** [comment]
there is no update on ticket more than a month. ticket closed
