### ISSUE TITLE
Open SQL sheet

### ISSUE THREAD

**Issue by Ferrox12** [dbeaver/dbeaver#6954]
Is there a method that when I start a connection to a database, DBeaver automatically opens me the SQL sheet of that connection?

**Comment by serge-rider** [comment]
No, there is no such option.
I'm not sure that we should add it. E.g. it is not clear:
- What exactly SQL file should be opened? (new, recent, sql console)
- Should we open a script if connection was opened indirectly (e.g. in search dialog, by virtual foreign key reference, etc)?
- What if some SQL file for this connection is already opened?

**Comment by Ferrox12** [comment]
Example:
Connection name: DBOracle
When I start the connection, DBeaver opens me the sheet where I can work on the DBOracle database

**Comment by uslss** [comment]
This behaviour could be changed in Preferences
![image](https://user-images.githubusercontent.com/31996417/88226329-949fe180-cc74-11ea-90ef-654f9a565aad.png)
