### ISSUE TITLE
Auto completion problem [D3]

### ISSUE THREAD

**Issue by eliodamico** [dbeaver/dbeaver#6961]
If I type the following sql:
select * from persona where mat
the autocompletion writes:
select * from persona where matricolaat
instead of
select * from persona where matricola

It looks like it inserts the column name matricola between "m" and "at" instead of replacing mat.

This problem was introduced in one of the last updates. Before auto completion was acting fine.

DBeaver version: 6.2.2.201910072100
OS: windows 10 pro

**Comment by uslss** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D3. Do not remove or edit.` [D3](https://dbeaver.testquality.com/project/8805/result/1548512/defect/5537)

**Comment by serge-rider** [comment]
Can't reproduce.
I saw such behavior a couple of times but I can't remember in which circumstances.
@uslss maybe you have some test-case?

**Comment by serge-rider** [comment]
I've reproduced this on slow PG connection. This happened because of database system schema lookups during text typing.
Fixed.

**Comment by uslss** [comment]
verified

**Comment by alesc2000** [comment]
This seems the same as: #4952
