### ISSUE TITLE
postgres stored procedures folder not visible

### ISSUE THREAD

**Issue by mharol** [dbeaver/dbeaver#6962]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
We keep procedures along with functions. Folder "Functions". Procedures have different icon.

**Comment by aaguero64** [comment]
why I cannot get the Procedures folder in DBeaver ?
