### ISSUE TITLE
Unset search filter

### ISSUE THREAD

**Issue by powelleric** [dbeaver/dbeaver#6963]
I was tinkering with the search feature and right-clicked on a search result and it took me to a page where I could specify which files to include/exclude.  I think I messed up the settings in that window and now all my search results come back empty.  That means there is nothing to right-click in order to reverse the settings.

**Comment by kseniiaguzeeva** [comment]
Hi, do you apply a filter in Navigator tree? 
The filtered folder is marked by 3 dots. Please try to find it and then right click and find "Filter" in context menu.
![dbeaver_DMO8kvpJKa](https://user-images.githubusercontent.com/51405061/71351656-4ebb5780-2585-11ea-9bac-4447dfca5321.png)

**Comment by uslss** [comment]
there is no update on ticket more than a month,
ticket closed.
if issue still actual for you - feel free to reopen the ticket
