### ISSUE TITLE
[BUG-Postgres] Getting away the precision of a varchar column has no effect

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#6967]
When changing the precision of a (varchar) column in table view, removing the limit (100 in the screenshot) and clicking on Save restores the values in the description and does nothing.

![image](https://user-images.githubusercontent.com/3930671/66649928-b2451280-ec2f-11e9-8301-6cefd5217501.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
