### ISSUE TITLE
Named parameters bug

### ISSUE THREAD

**Issue by Barosky** [dbeaver/dbeaver#6969]
#### System information: 
- Windows 10 Home 64 bit
- 6.2.2.201910101958

#### Connection specification:
- PostgreSQL

#### Describe the problem you're observing:
In version 6.2.2 the named parameters don't work as expected.
If I use @set to set a value for a parameter and then execute the script, the 'Bind parameters' dialog pops-up asking for parameter values. In previous versions this didn't happen, since the parameter values were correctly pulled from @set command.

#### Steps to reproduce, if exist:
@set val=10

select :val

"Bind parameters" dialog pops-up: val is null.

![image](https://user-images.githubusercontent.com/18073194/66662314-e37e0c80-ec48-11e9-9670-dee03bba7563.png)

**Comment by serge-rider** [comment]
Thanks for the bug report.
It was a side effect of new UI for parameters processing.

**Comment by uslss** [comment]
verified
