### ISSUE TITLE
More than two query results

### ISSUE THREAD

**Issue by iioftexas** [dbeaver/dbeaver#6970]
If I run a script or stored procedure that returns more than two query results, the Results pane shows only two tabs which contain only the first two query's results.  Ideally, it would create as many tabs as are necessary for the number of query results returned by the script.  Is this configurable, or does this require a feature request?

For example, if I run the following script in MariaDB 10.2, it returns only two panes with the values "1" and "2" in them, respectively.  "3" goes into the ether:

```
BEGIN NOT ATOMIC
	SELECT 1;
	SELECT 2;
	SELECT 3;
END;
```

I am running DBeaver 6.2.2.201910061950 on Windows.

**Comment by serge-rider** [comment]
I can't reproduce this:
![image](https://user-images.githubusercontent.com/6398845/66682232-3ffb1f00-ec7d-11e9-92f8-c3cb8dd66671.png)
What DBeaver version do you use?

**Comment by uslss** [comment]
there is no update on ticket for a long time.
ticket closed
