### ISSUE TITLE
Error connecting to datasource  Reason: Unknown database

### ISSUE THREAD

**Issue by M4NS0** [dbeaver/dbeaver#6971]
Hello Beavers!
I'm a DB learner and installed xampp and dbeaver (Linux lite kernel 5.3), but i'm facing an issue and i could not find the solution for it.... I really don't know if I'm doing something wrong or is a bug (probably I'm its my fault somehow) ... can you guys help me, please? 

My problem starts when i create a new data base with MySql 8+, when i click the arrow down in database navigator, the error: 'Unknown database ' appears, with a small red 'x' beyond it, as above:

![image](https://user-images.githubusercontent.com/47955752/66694111-9751bd00-ec86-11e9-8d17-25c582914004.png)

I already using mysql in Linux terminal, with the workbench, they work perfectly. 

please guys your platform is fantastic and I intent to use it..Could u help me? 

Have a nice weekend!

**Comment by serge-rider** [comment]
When you create a connection in dbeaver it doesn't create a new database. Database dbase must exist on server.
You may leave database parameter (on connection properties page) empty to connect to the server.
You can create new database by using right click on Databases folder->Create->Database.

**Comment by M4NS0** [comment]
Thank you Serge-rider! It works! :D

**Comment by rawy02** [comment]
Me funciono!

**Comment by arioul89** [comment]
Real G @serge-rider 👍
