### ISSUE TITLE
Backup/restore: save configuration as tasks

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6972]
Database backup/restore wizards (PostgreSQL, MySQL) should be made similarly to Data Transfer wizard.
It must be possible to save backup/restore configuration in a task and then run it with single click.

**Comment by serge-rider** [comment]
There are too many changes. Don't have time till 6.3 release. moving to 6.3.1

**Comment by serge-rider** [comment]
In 6.3.1 we will add this feature only for MySQL backup tasks.
Will add the rest in the next release.

**Comment by uslss** [comment]
can not create task using db tasks tab
![image](https://user-images.githubusercontent.com/31996417/71162264-f40bbe00-225b-11ea-972d-ab42bdca5b01.png)

**Comment by uslss** [comment]
verified
