### ISSUE TITLE
When folding is enabled, it will automatically expand from time to time during editing, especially when upper layer is folded and lower layer is edited

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6973]
![image](https://user-images.githubusercontent.com/26621087/66701156-bc4c3b80-ed2b-11e9-9c03-2dd12c49f807.png)

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
unfortunately, cannot catch the issue.
if it is still actual for you - feel free to reopen the ticket
