### ISSUE TITLE
Sorting on fields when scrolled right jumps to left

### ISSUE THREAD

**Issue by markuszeller** [dbeaver/dbeaver#6977]
#### System information: 
- Microsoft Windows [Version 10.0.18362.418]
- Version 6.2.2.201910061950

#### Connection specification:
- 10.2.12-MariaDB-10.2.12+maria~xenial-log
- org.mariadb.jdbc:mariadb-java-client:RELEASE 1.5.5
- Direct connect

#### Describe the problem you're observing:
When any table is opened and I am able to scroll to the right in the gridview, it scrolls automatically to the left side when using the columns to sort or filter.

This happens **only, if the result set is paginated.**

#### Steps to reproduce, if exist:
- open a table (data grid view)
- scroll right
- click any sorting on header column **or** use a filter

Now it has been scrolled to left.

#### Include any warning/errors/backtraces from the logs
No error logged

**Comment by markuszeller** [comment]
This also happens, when scrolling down and the result set paginates. After loading, the scrollbar jumps to the left, instantly.

It looks for me like a problem of the paginator.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by markuszeller** [comment]
Issue sadly is still there. Paginating scrolls left.
Please reopen.

Version 6.2.4.201911031605
Microsoft Windows [Version 10.0.18362.10024]

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report. Investigating.

**Comment by kseniiaguzeeva** [comment]
Caught. Now paginating scrolls left if any filtering/ordering were not used in a table (if filtering/ordering are used, or used and then removed, the horizontal scrolling works properly).

**Comment by serge-rider** [comment]
Fixed

**Comment by markuszeller** [comment]
Almost fixed. Hitting the paginator next line or page scrolls still to left. (compiled your devel branch)

**Comment by markuszeller** [comment]
> Fixed

Almost fixed. Hitting the paginator next line or page scrolls still to left.
(tested compiling current devel branch)

**Comment by kseniiaguzeeva** [comment]
Thank you for your time and attention. It happens when a selected cell was hidden on the left. It is the expected result - the current cell is shown in this way.

**Comment by markuszeller** [comment]
Oh yes, and the top left is preselected, when no one is selected by intent.

**Comment by kseniiaguzeeva** [comment]
A table scrolls up and to the left in Data Editor if:
-apply/remove a filter (by Column Header(and upper filter line) or Custom Filter);
-apply/remove ordering by Custom Filter;
P.S. Table scrolling in Resultset of SQL Editor is ok.
![FHs18PsOy2](https://user-images.githubusercontent.com/51405061/68387001-560dd980-016e-11ea-9f8c-b32214694ba9.gif)

**Comment by markuszeller** [comment]
Thanks for visualizing this. For me as user this is unwanted scrolling behavior.

**Comment by serge-rider** [comment]
Fixed (that was a different bug).

**Comment by markuszeller** [comment]
Yes! ♥
