### ISSUE TITLE
Cancelling Redshift Queries Hangs

### ISSUE THREAD

**Issue by michaelcbennett** [dbeaver/dbeaver#6982]
#### System information: 
- Operating system (distribution) and version: MacOS 10.14.6 (But also observed on Windows 10)
- DBeaver version: 6.2.2.201910072100 (Also observed as far back as 6.2.1.201909221630)
- Java version:  1.8.0_152-b16
- Additional extensions: None

#### Connection specification:
- Database name and version Amazon Redshift Cluster version 1.0.10480
- Driver name com.amazon.redshift:redshift-jdbc42:RELEASE version 1.2.36.1060
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No, but SSL enabled.

#### Describe the problem you're observing:
When using the latest JDBC drivers from Redshift, if I try to cancel a query, the UI grays out the cancel button but does not return. Looking at the Redshift cluster, the query is still executing in the background.

#### Steps to reproduce, if exist:
Using the redshift driver RedshiftJDBC42-1.2.27.1051.jar works fine. This only occurs with the newest versions of the redshift JDBC driver downloaded as an artifact.

#### Include any warning/errors/backtraces from the logs
No log messages were logged.

**Comment by uslss** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D2. Do not remove or edit.` [D2](https://dbeaver.testquality.com/project/8805/result/1548027/defect/5536)

**Comment by serge-rider** [comment]
I think this was fixed in #7885
