### ISSUE TITLE
How to generate DDL right sequence related foreign key of tables?

### ISSUE THREAD

**Issue by hoangdangduy** [dbeaver/dbeaver#6984]
#### System information: 
- Operating system: Ubuntu 18.04
- DBeaver version: 6.1.3

#### Connection specification:
- Database name and version: Postgres 10.10

#### Describe your question:
I have 2 table is **table_a** and **table_b** and generate DDL as below.

```
CREATE TABLE table_a (
	id serial NOT NULL,
	table_b_id int4 NULL,
	CONSTRAINT table_a_pk PRIMARY KEY (id),
	CONSTRAINT table_a_fk FOREIGN KEY (table_b_id) REFERENCES table_b(id)
);
CREATE TABLE table_b (
	id serial NOT NULL,
	CONSTRAINT table_b_pk PRIMARY KEY (id)
);
```

With script above I will receive error when run because **table_a** will be created before **table_b** but table_a connect table_b through by foreign key **table_b_id**.
I think when generate DDL on dbeaver the correct sequence of script will be below, but how do I do to have that ?
```
CREATE TABLE table_b (
	id serial NOT NULL,
	CONSTRAINT table_b_pk PRIMARY KEY (id)
);

CREATE TABLE table_a (
	id serial NOT NULL,
	table_b_id int4 NULL,
	CONSTRAINT table_a_pk PRIMARY KEY (id),
	CONSTRAINT table_a_fk FOREIGN KEY (table_b_id) REFERENCES table_b(id)
);

```

Thanks!

**Comment by uslss** [comment]
You could choose needed tables in db navigator (Ctrl+Click), then in the context menu choose Generate SQL -> DDL. You'll get something like this:
![image](https://user-images.githubusercontent.com/31996417/71912289-4880ca00-3186-11ea-8025-220359146f2b.png)
