### ISSUE TITLE
"Column sort" icon in editor view inverted

### ISSUE THREAD

**Issue by palbr** [dbeaver/dbeaver#6985]
#### System information: 
- Operating system (distribution) and version: Windows
- DBeaver version: 6.2.2.201910072100
- Additional extensions: none

#### Connection specification:
- Database name and version: Oracle
- Driver name: ojdbc7.jar (oracle.jdbc.OracleDriver)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Steps to reproduce, if exist:

1. create testdata:
```sql
CREATE TABLE order_test (col1 NUMBER, col2 VARCHAR2(20));

INSERT INTO order_test (col1, col2) VALUES (1, 'one');
INSERT INTO order_test (col1, col2) VALUES (3, 'three');
INSERT INTO order_test (col1, col2) VALUES (5, 'five');
INSERT INTO order_test (col1, col2) VALUES (4, 'four');
INSERT INTO order_test (col1, col2) VALUES (2, 'two');
```
2. open table in editor view, data is not sorted via column `col1`: 
![grafik](https://user-images.githubusercontent.com/2083705/66895119-504f2900-eff2-11e9-9e98-171d66cb81fd.png)
3. click button "sort by column `col1`"

#### Actual behaviour:
- data in column 1 is sorted ascending (numbers start with low values und number values **go up** to higher values)
- sort icon "arrow **down**" is shown: 
![grafik](https://user-images.githubusercontent.com/2083705/66895536-585b9880-eff3-11e9-8871-ee9627b80e8f.png)

#### Expected behaviour:
- data in column 1 is sorted ascending (everything ok with this)
- sort icon "arrow **up**" ![grafik](https://user-images.githubusercontent.com/2083705/66895708-bd16f300-eff3-11e9-86af-a9cd95ec6090.png) should be shown

"ascending" means "values go up", so I would expect an "arrow up" as icon to indicate ascending sorting.

#### Additional information:

The old dbeaver (Version 4.2.3) showed the sort icon as I would expect it:
![grafik](https://user-images.githubusercontent.com/2083705/66895958-39113b00-eff4-11e9-9b8a-9ba3a91eabb1.png)

(And MS Excel does so, too: 
![grafik](https://user-images.githubusercontent.com/2083705/66896111-87bed500-eff4-11e9-94af-975ec76b2eb2.png) )

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
