### ISSUE TITLE
Compatibility with Greenplum 6.0 easy fix (new pg_catalog.pg_get_table_distributedby)

### ISSUE THREAD

**Issue by buravchenko** [dbeaver/dbeaver#6986]
Hello! Unfortunately, there were changes in Creenplum 6.0 and now DBeaver generates incorrect "distributed by" DDL for this new version of the DB. Can you please improve this? Using the method mentioned in https://github.com/dbeaver/dbeaver/issues/5526 (psql --echo-hidden database_name), you can generate necessary SQL statements for direct selects from the DB. For instance, I received the following statements:

gpadmin@pd-db-1:~$ psql --echo-hidden test
psql (9.4.24)
Type "help" for help.

test=# \d+ test_table
********* QUERY **********
SELECT c.oid,
  n.nspname,
  c.relname
FROM pg_catalog.pg_class c
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relname OPERATOR(pg_catalog.~) '^(test_table)$'
  AND pg_catalog.pg_table_is_visible(c.oid)
ORDER BY 2, 3;
**************************

********* QUERY **********
select pg_catalog.version()
**************************

********* QUERY **********
select oid from pg_catalog.pg_class where relnamespace = 11 and relname  = 'pg_attribute_encoding'
**************************

********* QUERY **********
SELECT c.relchecks, c.relkind, c.relhasindex, c.relhasrules, c.relhastriggers, c.relhasoids, pg_catalog.array_to_string(c.reloptions || array(select 'toast.' || x from pg_catalog.unnest(tc.reloptions) x), ', ')
, c.reltablespace, CASE WHEN c.reloftype = 0 THEN '' ELSE c.reloftype::pg_catalog.regtype::pg_catalog.text END, c.relpersistence, c.relreplident
, c.relstorage as relstorage FROM pg_catalog.pg_class c
 LEFT JOIN pg_catalog.pg_class tc ON (c.reltoastrelid = tc.oid)
WHERE c.oid = '16544';
**************************

********* QUERY **********
SELECT a.attname,
  pg_catalog.format_type(a.atttypid, a.atttypmod),
  (SELECT substring(pg_catalog.pg_get_expr(d.adbin, d.adrelid) for 128)
   FROM pg_catalog.pg_attrdef d
   WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum AND a.atthasdef),
  a.attnotnull, a.attnum,
  (SELECT c.collname FROM pg_catalog.pg_collation c, pg_catalog.pg_type t
   WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation) AS attcollation,
  NULL AS indexdef,
  NULL AS attfdwoptions,
  a.attstorage ,
  CASE WHEN a.attstattarget=-1 THEN NULL ELSE a.attstattarget END AS attstattarget,
  pg_catalog.col_description(a.attrelid, a.attnum)
FROM pg_catalog.pg_attribute a
LEFT OUTER JOIN pg_catalog.pg_attribute_encoding e
ON   e.attrelid = a .attrelid AND e.attnum = a.attnum
WHERE a.attrelid = '16544' AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum;
**************************

********* QUERY **********
SELECT c2.relname, i.indisprimary, i.indisunique, i.indisclustered, i.indisvalid, pg_catalog.pg_get_indexdef(i.indexrelid, 0, true),
  pg_catalog.pg_get_constraintdef(con.oid, true), contype, condeferrable, condeferred, i.indisreplident, c2.reltablespace
FROM pg_catalog.pg_class c, pg_catalog.pg_class c2, pg_catalog.pg_index i
  LEFT JOIN pg_catalog.pg_constraint con ON (conrelid = i.indrelid AND conindid = i.indexrelid AND contype IN ('p','u','x'))
WHERE c.oid = '16544' AND c.oid = i.indrelid AND i.indexrelid = c2.oid
ORDER BY i.indisprimary DESC, i.indisunique DESC, c2.relname;
**************************

********* QUERY **********
SELECT c.oid::pg_catalog.regclass FROM pg_catalog.pg_class c, pg_catalog.pg_inherits i WHERE c.oid=i.inhparent AND i.inhrelid = '16544' ORDER BY inhseqno;
**************************

********* QUERY **********
SELECT c.oid::pg_catalog.regclass FROM pg_catalog.pg_class c, pg_catalog.pg_inherits i WHERE c.oid=i.inhrelid AND i.inhparent = '16544' ORDER BY c.oid::pg_catalog.regclass::pg_catalog.text;
**************************

********* QUERY **********
SELECT pg_catalog.pg_get_table_distributedby('16544')
**************************

                         Table "public.test_table"
 Column  |  Type   | Modifiers | Storage  | Stats target | Description
---------+---------+-----------+----------+--------------+-------------
 address | inet    | not null  | main     |              |
 rating  | integer | not null  | plain    |              |
 info    | text    |           | extended |              |
Indexes:
    "test_table_pkey" PRIMARY KEY, btree (address, rating)
Distributed by: (address)

**Comment by buravchenko** [comment]
For this table DBeaver incorrectly generates "DISTRIBUTED BY (address, port)". The true value is "DISTRIBUTED BY (address)".

**Comment by buravchenko** [comment]
So, to get correct "distributed by" statement, you can simply use the last SQL command:
SELECT pg_catalog.pg_get_table_distributedby('16544');
The result looks like the following:

 pg_get_table_distributedby
----------------------------
 DISTRIBUTED BY (address)
(1 row)

**Comment by serge-rider** [comment]
Unfortunately we don't have GP 6 server to test it. pg_get_table_distributedby is not supported by earlier versions.

Currently we use `SELECT attrnums FROM pg_catalog.gp_distribution_policy` and list column names after DISTRIBUTED BY CLAUSE (see https://github.com/dbeaver/dbeaver/blob/a11fac61bbb4f291ebb1cdb14500f32b8465157a/plugins/org.jkiss.dbeaver.ext.greenplum/src/org/jkiss/dbeaver/ext/greenplum/model/GreenplumTable.java)

**Comment by buravchenko** [comment]
Yes, pg_get_table_distributedby is not supported by Greenplum versions prior to 6.0. But you have to use it for 6.0, because there were changes mentioned here in the official documentation:
https://gpdb.docs.pivotal.io/6-0/install_guide/migrate.html

Here is a quote:
In the gp_distribution_policy system table, the attrnums column is renamed to distkey and its data type is changed to int2vector. A backend function pg_get_table_distributedby() was added to get the distribution policy for a table as a string.

**Comment by buravchenko** [comment]
I can test it if you send me a new version of DBeaver.

**Comment by maratkalibek** [comment]
@buravchenko please, can you check DDL for latest version of DBeaver.

It was fixed with this commit - https://github.com/dbeaver/dbeaver/commit/9356d433e5ee04650e4a02cc2ca6aacfb649c37a#diff-4e7804994ff1023d0717bd20fb5746e0

**Comment by uslss** [comment]
verified
