### ISSUE TITLE
DBeaver password encryption

### ISSUE THREAD

**Issue by cbraudy** [dbeaver/dbeaver#6991]
DBeaver (Community Edition) 6.2.2 (Release date: October 7, 2019) stores the password in an encrypted json file. (credentials-config.json).  However from some web sites, this file was encrypted by DBeaver using a published static encryption key and can easily be decrypted by a savvy programmer.

**Anyone know if there is a way to change the encryption key that DBeaver uses to encrypt these files?** It is essential that these files on developer and analysts workstations be NOT possible to decrypt (and therefore see the user's database / Db2 password)!

**Comment by rdp** [comment]
You could change the key and recompile DBeaver...custom copies for everybody :) but a very savvy programmer could still extract the key from the compiled java...but another layer anyway :)

**Comment by leehenderson** [comment]
Does the Enterprise Edition handle this differently? This is sort of awful.

**Comment by serge-rider** [comment]
@leehenderson EE has special option "Advanced security". If enabled dbeaver stores passwords in local OS (Eclipse actually) storage in encrypted form. It cannot be decrypted with some universal hack program.

Also we are planning to add master-password support (not Eclipse-based) in EE 6.3.

**Comment by skocherry** [comment]
Can the ability to save the password be turned off?

**Comment by Aex12** [comment]
This should be revised, it's shamefully easy to decrypt the default credentials file. Just made a Google search and I could find a working code example and tutorial to decrypt the file. I've barely written any Java code before and it took me less than 5 minutes to decrypt my credentials file. There should be a way to define a master password and encrypt-decrypt this file using AES256 at program startup.
