### ISSUE TITLE
how to change right click filter to old style?

### ISSUE THREAD

**Issue by secreal** [dbeaver/dbeaver#6995]
#### System information: 
- Operating system (distribution) and version
Windows 10 Pro 64-bit )10.0, Build 17763)
- DBeaver version
![image](https://user-images.githubusercontent.com/586113/66980398-f70ef480-f0da-11e9-94fc-7988aba942de.png)

#### Connection specification:
- Database name and version
Oracle 12c

#### Describe your question:
my context filter is grouped by three, and this slow down my work
![image](https://user-images.githubusercontent.com/586113/66980347-c75fec80-f0da-11e9-96a9-a3d4c675619c.png)

how to change to my friend dbeaver style like this image
![image](https://user-images.githubusercontent.com/586113/66980492-4a814280-f0db-11e9-8d64-d54679560c73.png)

**Comment by kseniiaguzeeva** [comment]
Your friend has a different DBeaver version.
Your context menu is similar with current version 7.0.3 and cannot be customized.
Something else I can help you with?
