### ISSUE TITLE
Add option to use comma as decimal separator in CSV

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#6997]
**Is your feature request related to a problem? Please describe.**

Looks like there is no way to export large CSV-like files, where numbers are formatted using comma as decimal separator.

**Describe the solution you'd like**

Add option to use comma as decimal separator in _Data Formats_ window. Currently there is no such option.

![obraz](https://user-images.githubusercontent.com/20753183/66993794-8365eb00-f0cc-11e9-9456-07bd7d7d6ee0.png)

**Comment by maln0ir** [comment]
I just noticed that importing is also problematic. In case of file like below decimal part is stripped when value is imported to NUMBER column (Oracle):

```
"COLUMN1";"COLUMN2"
1,234;2,345
```

Data after import looks like this:

| COLUMN1 | COLUMN2 |
|---------|---------|
|       1 |       2 |

Changing commas to dots makes it work, but it is sometimes very problematic to do in large files.

**Comment by palbr** [comment]
Using DBeaver Version 6.3.4, the format dialog looks a little bit better: It shows a comma as decimal separator in the "Sample" Textbox.
But in the exported file, there is still no comma.

**Comment by palbr** [comment]
I am on Windows and connect to an Oracle Database via "ojdbc7.jar".
My language in DBeaver is set to "de - German" and country "DE - Germany". So the used locale ist "de_DE".

**Comment by axelkohonen** [comment]
Same problem with the Finnish locale en-Fi. DBeaver shows the sample with a comma, but the separator is a dot in the exported .csv file

**Comment by palbr** [comment]
Update: I just tested dbeaver 7.3.5 and my CSV-export-file now contains numbers with comma as decimal separator.

I used the following settings in "Data Formats" :

![DBeaver Data Format properties](https://user-images.githubusercontent.com/2083705/108860566-9bb61600-75ee-11eb-886b-8c07e007b09a.png)

Especially: 
- Locale = "de_DE" 
- "Disable numeric formatting" is disabled (seems to be unimportant for this issue)

My settings in "Data Transfer Settings" / "Exporter settings":

![DBeaver format number](https://user-images.githubusercontent.com/2083705/108858941-036b6180-75ed-11eb-876b-224c31fb0a60.png)

Be sure to set "Format numbers" to "true"!

Example:
Database float (value = "1,234.56") gets exported to CSV textfile as "1234,56".

So I would say, this issue can be closed now.

**Comment by Midnighit** [comment]
Either I'm doing something wrong or this issue reappeared.
I'm using DBeaver version 25.2.0.202508311659
Under Windows > Preferences > Editors > Data Editor > Data Formats
I set `Language` to `de` and `Country` to `DE`
The sample preview below says `1.234.567.890,012` so everything *looks* fine.
In the Data view, numbers still show as `1234567890.012` and using the export option also yields the same result.

Export target settings:
```
Files settings:
	Write to the single file: No
	Directory: C:\Users\username\Downloads
	File name pattern: ${table}_${timestamp}
	On object data file name conflict: Ask
	On blob value file name conflict: Ask
	Encoding: UTF-8
	Timestamp pattern: yyyyMMddHHmm
	Insert BOM: Yes
	Compress: No
	Binaries: INLINE
	Encoding: BINARY
CSV settings:
	File extension: csv
	Delimiter: ;
	Row delimiter: default
	Header: top
	Header format: label
	Header case: as is
	Characters escape: quotes
	Quote character: "
	Quote always: strings
	Quote never: false
	Format numbers: true
	Format arrays: { }
```

Did I miss something? How can I help diagnose the issue? I already tried with German as GUI language and restarted DBeaver several times.

**Comment by glidingjoe** [comment]
I have the same problem as "midnight" quoted on Sep 17  2025. My version is 25.1.5.202508171444.
The sample preview below says 1.234.567.890,012 so everything looks fine.
In the Data view, numbers still show as 1234567890.012 and using the export option also yields the same result.

<img width="598" height="642" alt="Image" src="https://github.com/user-attachments/assets/1b2a6954-dbc2-4863-8efd-3494ee056b02" />

<img width="942" height="99" alt="Image" src="https://github.com/user-attachments/assets/7bd4f62b-6b28-4a99-8384-32131ef941aa" />
