### ISSUE TITLE
Frequently crashing  - version 6.2.2.201910061950

### ISSUE THREAD

**Issue by petervalencic** [dbeaver/dbeaver#7000]
¸¸#### System information: 
- Operating system (distribution) and version: Windows 10, 
- DBeaver version: Version 6.2.2.201910061950
- Additional extensions. No extensions

#### Connection specification:
- Database name and version: Postgres 9.4
- Driver name: postgresql-42.2.5.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? VPN 

#### Describe the problem you're observing:
From the main window, I select the database, schema and desired table. 
Then I navigate to some field and change some values.
When hitting "save" (commit) the app close (crash without any info)

#### Steps to reproduce, if exist:
Select schema, table. Modify some value inside the table and save it.

#### Include any warning/errors/backtraces from the logs
SQL Error [08006]: An I/O error occurred while sending to the backend.
An exception stack trace is not available.
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by maciey** [comment]
We have also same problem with frequent crashes in  v. 6.2.2.2 
Happens in many places (eg editing data in dataset, pressing some shortcut etc)

**Comment by maln0ir** [comment]
See #6928 for possible solution

**Comment by uslss** [comment]
Hi, unfortunately there was an issue with migration to new Eclipse platform (2019-09). Hotfix version  already published . Just re-download 6.2.2 version from dbeaver.io.

**Comment by petervalencic** [comment]
Thank you.. works now.. 👍
