### ISSUE TITLE
Unable to Export Query Results

### ISSUE THREAD

**Issue by zpappas** [dbeaver/dbeaver#7003]
#### System information: 
- Operating system (distribution) and version - Windows 10 64 Bit
- DBeaver version -  6.2.2.201910061950
- Additional extensions

#### Connection specification:
- Database name and version - Athena
- Driver name - jdbc:awsathena
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  - Not that I am aware of

#### Describe the problem you're observing:
I ran a query and would right click, execute, Export From Query, CSV, Next, Directory, File Name, Next, Start.   It attempts to execute the query with the bar going back and forth, but then I get the error: "Data transfer failed. 
Reason: SQL Error: The requested fetchSize is more than the allowed value in Athena.  Please reduce the fetchSize and try again.  Refer to the Athena documentation for valid fetchSize values."

Before updating to the newest version of DBeaver, I was able to export queries, and now I am unable to.   Any idea why this is occurring?

**Comment by zpappas** [comment]
> 
> 
> Hi @zpappas could you specify your driver version?

Sure, I am using the Simba Athena ODBC Driver, and it says it is V1.0.2.1003 (64 bit)

![image](https://user-images.githubusercontent.com/56689742/67024137-e4dc8880-f0d1-11e9-9066-e475dc1c41d0.png)

**Comment by uslss** [comment]
It seems it is driver issue. Try to decrease fetch size in export settings (it should be less than 1000) 
![image](https://user-images.githubusercontent.com/31996417/67025208-50dce200-f10e-11e9-99d7-82d34317b428.png)

**Comment by zpappas** [comment]
That looks to be it! Just decreased it to 500 and it worked, but never had to mess with it previously! Thank you @uslss
