### ISSUE TITLE
Add import option in Data tab in table view

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#7010]
**Is your feature request related to a problem? Please describe.**

This could make importing more convenient. Currently I can import data into table i.e. from _Database Navigator_, but not when browsing data in table. I can do export, but not import, because this option is not available.

**Describe the solution you'd like**

Add option to import data to _right-click_ menu in _Data_ tab (and to toolbar below).

**Describe alternatives you've considered**

This can be done from _Database Navigator_, but it requires a few more clicks.

**Additional context**

![obraz](https://user-images.githubusercontent.com/20753183/67091748-c9df4680-f1ad-11e9-8cf1-02de9a4fa0f1.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by uslss** [comment]
It could be done from the context menu at Properties Tab
![image](https://user-images.githubusercontent.com/31996417/171188993-2712e5a1-81bb-4fb3-ad08-3c7964121537.png)
