### ISSUE TITLE
Decimal part gets stripped when importing CSV-like file

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#7011]
#### System information: 
- Operating system (distribution) and version: Windows 10.0.17763.720
- DBeaver version: 6.2.3.201910122038
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle 12c
- Driver name: JDBC Thin Client
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Decimal part gets stripped when importing CSV-like file.

#### Steps to reproduce

1. Create table like this (I used Oracle 12c):
    ``` sql
    CREATE TABLE test_table(column1 NUMBER, column2 NUMBER)
    ```
2.  Import data from file like below, separator set to ';'

    ```
    "COLUMN1";"COLUMN2"
    1,234;2,345
    ```

3. Data after import looks like this:

    | COLUMN1 | COLUMN2 |
    |---------|---------|
    |       1 |       2 |

Changing commas to dots makes it work, but it is sometimes very problematic to do in large files and there is no option to change decimal separator (see #6997)

**Comment by uslss** [comment]
as a workaround you could change your locale to de, here comma is used as a decimal separator
![image](https://user-images.githubusercontent.com/31996417/79993210-315bb300-84bd-11ea-86aa-c876bdd4e353.png)
