### ISSUE TITLE
Version 6.2.2 - canvas not show anything in Debian 9 

### ISSUE THREAD

**Issue by erfelipe** [dbeaver/dbeaver#7012]
#### System information: 
- Debian 9
- DBeaver version: 6.2.2
- Additional extensions: none

#### Connection specification:
- localhost 
- PostgreSQL version: 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - None

#### Describe the problem you're observing:
The dbeaver canvas do not show anything in SQL editor and query result, just a gray color in entire canvas. In fact, the interface have a problem in Linux release. It's is easy to see. 
Obs: Database navigation and connection guides, are ok. They are visible.

#### Steps to reproduce, if exist:
Using Debian (9) or perhaps other release, just install dbeaver last version (6.2.2). Try to query anything. (in my case, a postgre connection).

**Comment by uslss** [comment]
is it still actual?

**Comment by erfelipe** [comment]
I'm changed for DataGrip. I appreciate your attention and I'll close ticket. Regards,
