### ISSUE TITLE
Export of Oracle 11.2 to sqllite creates unnecessary primary key

### ISSUE THREAD

**Issue by Kristof5933** [dbeaver/dbeaver#7013]
#### System information: 
- Windows 10
- DBeaver 6.2.2
- Oracle ojdbc6 
- sqlite 3.8.11.2

##### Source
- Oracle 11.2g
- ojdbc6 
- VPN connexion
##### Target
- Sqlite 
- jdbc 3.8.11.2 
- local file

#### Describe the problem you're observing:
I'm trying to export remote Oracle tables to a local sqllite database for testing purposes. The export functionnality creates the table in the sqllite database, but it also creates a primary key on the first column, while there is no primary key in the source table.

The export then fails, because the primary key constraint fails.

On the other hand, when there's a primary key on the source table, everything seems to run fine.

##### Oracle DDL
This is the original DDL for the table :
```
  CREATE TABLE "SCHEMA"."THE_TABLE" 
   (	"OFFER" VARCHAR2(30) NOT NULL ENABLE, 
	"TARGET" VARCHAR2(255) NOT NULL ENABLE, 
	"TYPE" NUMBER(3,0) NOT NULL ENABLE, 
	"FORMAT" VARCHAR2(200), 
	"SOURCE" VARCHAR2(500), 
	"NUM_VALUE" NUMBER(20,0), 
	"BOOL_VALUE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SPACETABLE" ;
```
##### SQL-LITE DDL
```
CREATE TABLE THE_TABLE(
	OFFER VARCHAR2(30) NOT NULL,
	TARGET VARCHAR2(255) NOT NULL,
	TYPE NUMBER(3,0) NOT NULL,
	FORMAT VARCHAR2(200),
	"SOURCE" VARCHAR2(500),
	NUM_VALUE NUMBER(20,0),
	BOOL_VALUE NUMBER(1,0),
       PRIMARY KEY (OFFER)
)
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by serge-rider** [comment]
Fixed.
In fact the problem was in Oracle extension and in a way dbeaver determine identifying constrains.

**Comment by uslss** [comment]
verified
