### ISSUE TITLE
Show all rows in Record with horizontal scrolling Mode like a spreadsheet

### ISSUE THREAD

**Issue by juarezr** [dbeaver/dbeaver#7014]
**Is your feature request related to a problem? Please describe.**

Sometimes when inspecting rows with many fields seeing them in a vertical fashion is the best way the visualize.

For doing this DBeaver has a Record Mode when displaying rows from a query.
But in this mode one can see just 1 row at time and cant compare the field values side by side or among rows.

Today in grid mode all fetched rows are shown and is possible to scroll using mouse and scrollbars.
But in record mode just 2 columns (Name/Value) representing 1 row are displayed.

**Describe the solution you'd like**

It would be a nice feature enhancement to have the ability to show all fetched rows from the query resultset in record view.
So the Record/Grid mode would be transformed in a Vertical/Horizontal mode scroll direction.
After this DBeaver would display/handle rows more like a spreadsheet app like excel.

Here is what a query result looks like in `Grid Mode` today:

```
col1 |col2 |
-----|-----| ^
  a  |  w  | |
  b  |  x  | |
  c  |  y  | |
  d  |  z  | v
```

Here is what a query result looks like in `Record Mode` today:

```
Name|Value|
----|-----|
col1|  a  |
col2|  w  |

 << < > >>
```

After the desired feature enhancement in `Record Mode`:

```
Name|  1  |  2  |  3  |  4  |
----|-----|-----|-----|-----|
col1|  a  |  b  |  c  |  c  |
col1|  w  |  x  |  y  |  z  |
< ------------------------- >
```

**Describe alternatives you've considered**

Dbeaver already is wonderful and powerfull.
This is just a extension of current funcionality.
I can't remember any tool doing than other than spreadsheets, excel...

**Additional context**

SQL for playing with the idea:
```
select '  a  ' as col1, '  w  ' as col2
union all
select '  b  ' as col1, '  x  ' as col2
union all
select '  c  ' as col1, '  y  ' as col2
union all
select '  d  ' as col1, '  z  ' as col2
order by 1;


select 'col1' as Name, '  a  ' as '1', '  b  ' as '2', '  c  ' as '3', '  c  ' as '4'
union all
select 'col1' as Name, '  w  ' as '1', '  x  ' as '2', '  y  ' as '3', '  z  ' as '4';
```

Thanks for creating the best query/database tool in world!

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/123289022-bfe02000-d518-11eb-855e-9317655a7136.png)

**Comment by uslss** [comment]
1. No values are shown in case no cells were chosen in data grid before switching to record mode.
![2021-06-25_14h59_36](https://user-images.githubusercontent.com/31996417/123423040-b5c92a80-d5c7-11eb-8939-5bab2ff073bf.gif)

2. Last table row is shown only when it was chosen before switching to the record mode. In case the 
user switch to another row in record view, the row before the last will be shown twice, the last row will not be shown
![2021-06-25_15h10_45](https://user-images.githubusercontent.com/31996417/123423369-26704700-d5c8-11eb-8211-bff72f0d33e1.gif)

3. Empty view when the row was dropped in record mode. Save/Cancel buttons remain active, but row is dropped.
![2021-06-25_15h19_56](https://user-images.githubusercontent.com/31996417/123424006-ec537500-d5c8-11eb-9883-ae7cfe21593e.gif)

4. Record view switches from multi to single in case of adding row. 
![2021-06-25_15h23_04](https://user-images.githubusercontent.com/31996417/123424303-5409c000-d5c9-11eb-921a-ae5232031fa0.gif)

5. Plain text view becomes empty if the new row was added and canceled then in record view in grid mode. 
![2021-06-25_15h27_55](https://user-images.githubusercontent.com/31996417/123424905-207b6580-d5ca-11eb-97c0-49f332f35649.gif)

6. Only the first chosen row is exported in case of export with selected rows only enabled
![image](https://user-images.githubusercontent.com/31996417/123425318-ac8d8d00-d5ca-11eb-9f76-1f6d3ddf6574.png)

7. All values from column are exported in case of export from grid view with selected columns only option enabled
![image](https://user-images.githubusercontent.com/31996417/123425534-ee1e3800-d5ca-11eb-8467-8f8858be3fd6.png)

8. Columns are resized after clicking at grid button in record view
![2021-06-25_15h37_41](https://user-images.githubusercontent.com/31996417/123425891-5705b000-d5cb-11eb-96ad-ca8acd0f0c23.gif)

9. Fetch buttons are available, after switching to record view dbeaver automatically fetch next rows, but newly fetched rows are shown only after switching to table mode and then back to the record mode. Multi record view switches to single record view after table refresh.
![2021-06-25_15h43_16](https://user-images.githubusercontent.com/31996417/123426521-2ffbae00-d5cc-11eb-92cb-df81064d5047.gif)

**Comment by uslss** [comment]
If switch to record mode on single row option is enabled, no values are shown.
![2021-06-25_15h49_26](https://user-images.githubusercontent.com/31996417/123427272-160e9b00-d5cd-11eb-9296-da5b36b40e73.gif)

**Comment by serge-rider** [comment]
Let's create separate tickets for 7 and 9. The rest is done.

**Comment by uslss** [comment]
verified. related issues created.
