### ISSUE TITLE
Mass-update passwords

### ISSUE THREAD

**Issue by alexnerd123** [dbeaver/dbeaver#7015]
My company uses a ton of oracle DB connections. We have around 60-70 databases, with a synchronized password for all of them. This changes every 90 days. In version 6.1.2 (where the creds are stored in XML) this is not too bad. I simply disconnect from all DBs, update it for ONE connection, close dbeaver, load the XML in a text editor, find-and-replace the encrypted passwords, and relaunch dbeaver. Not the prettiest flow, but it works very well, and isn't too much of a pain (WAY better than updating one at a time). I understand that new versions of dbeaver store connections in a plaintext JSON, and store creds in a separate JSON thats encrypted at the file-level, rather than the password-level. That is a TOTAL deal breaker for me. I CANNOT update my dbeaver. I 100% cannot survive having to update 70 passwords every 3 months, one by one, and risking locking myself out if a few too many old connections poke thru.

Could there be a way to "tie" databases together? Either make them share one common password, or make an option to "blast" a password to members of the group? I'm well aware that I'm living proof of https://xkcd.com/1172/, but like I said, this is an abject dealbreaker for me. I cannot upgrade past 6.1.2 unless a feature or a workaround (honestly, I'm not picky about the difference) is added.

I wouldnt want it to blast to ALL databases, since I have plenty other database connections that don't fall in that bucket. I'd only want to blast to predefined databases

**Comment by p91paul** [comment]
you probably want https://github.com/dbeaver/dbeaver/issues/2092, which is currently scheduled for 6.3.0
In the meantime, have a look at #6465
