### ISSUE TITLE
Advanced copy missing rows after sort in column

### ISSUE THREAD

**Issue by weixingdeemail** [dbeaver/dbeaver#7017]
#### System information: 
- windows 7 x64
- DBeaver 6.15
- no extensions

#### Connection specification:
- MySql 5.6
- mysql-connector-java, version 5.1.44
- Do not use tunnels or proxies.

#### Describe the problem you're observing:
As we can see in the gif picture below, after sorted in result column, advanced copy missed rows. But if we reset column sort, we can copy correct result.

#### Steps to reproduce, if exist:
![tyMgYSpYJa](https://user-images.githubusercontent.com/20130140/67139470-2f513700-f283-11e9-919d-8b6d429e47e6.gif)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
