### ISSUE TITLE
ERD incorrectly marks foreign key relationship as optional

### ISSUE THREAD

**Issue by msorens** [dbeaver/dbeaver#7019]
#### System information: 
- Operating system (distribution) and version: macOS mojave 10.14.6
- DBeaver version:   6.2.1.201909221630
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 9.6.11 on x86_64-pc-linux-gnu, compiled by gcc.real (GCC) 8.2.0, 64-bit
- Driver name: github.com/lib/pq
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Not sure; probably SSH

#### Describe the problem you're observing:

When I generate an entity-relationship diagram of my database, dbeaver is consistently--but incorrectly--noting foreign key relationships as optional when they should not be.
If the foreign key field has a `NOT NULL` constraint then the relationship must be one-to-many and cannot be zero-to-many, I believe; thus, the highlighted diamond should not be present.

![image](https://user-images.githubusercontent.com/6817500/67162162-61f83f80-f316-11e9-9b6a-9d14fe28554e.png)

Here is the DDL for the two tables, according to dbeaver:
```
CREATE TABLE public.iam_project_rules (
	db_id serial NOT NULL,
	id text NOT NULL,
	name text NOT NULL,
	"type" text NOT NULL,
	project_id int4 NOT NULL,
	CONSTRAINT iam_project_rules_id_key UNIQUE (id),
	CONSTRAINT iam_project_rules_pkey PRIMARY KEY (db_id),
	CONSTRAINT iam_projects_db_id_fkey FOREIGN KEY (project_id) REFERENCES iam_projects(db_id) ON DELETE CASCADE
);

CREATE TABLE public.iam_projects (
	db_id serial NOT NULL,
	id text NOT NULL,
	"name" text NOT NULL,
	"type" iam_policy_type NOT NULL DEFAULT 'custom'::iam_policy_type,
	CONSTRAINT iam_projects_id_key UNIQUE (id),
	CONSTRAINT iam_projects_pkey PRIMARY KEY (db_id)
);
```

Here is a bigger picture of my whole DB. There are six foreign key relationships noted. Five of them, the highlighted ones, all have `NOT NULL` constraints on those fields, so should not have the diamond.

![image](https://user-images.githubusercontent.com/6817500/67162407-9ff66300-f318-11e9-93ef-b9a5196fc2e0.png)

#### Steps to reproduce, if exist:

Create two tables above.
Generate ERD diagram.

#### Include any warning/errors/backtraces from the logs

No errors or warnings.

**Comment by Harunoki** [comment]
I have the same issue

**Comment by serge-rider** [comment]
It waited for too long time :(

Fixed

**Comment by uslss** [comment]
verified
