### ISSUE TITLE
db2: colums is always created with Not Null checked [D4]

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7020]
System information:

- Operating system (distribution) and version win 10 x64

- DBeaver version 6.2.3

Connection specification:

\- Database name and version db2 LUW

<br>

Describe the problem you're observing:

All created columns has Not Null option enabled, it is causes error when trying to save created column

Steps to reproduce, if exist:

1, Open Table

2\. Create Column -> Check enabled options (Not null is checked)

<br>

**Comment by uslss** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D4. Do not remove or edit.` [D4](https://dbeaver.testquality.com/project/8805/result/1554897/defect/5557)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
