### ISSUE TITLE
db tasks: task couldn't be changed - Save button is greyed out

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7021]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.3

#### Describe the problem you're observing:
When i'm trying to add tables to the db task and save it - i'm not able to do that - Save button is greyed out. If i try to continue without saving - NPE appears, (see gif attached)
#### Steps to reproduce, if exist:
1. Create task and save it
2. Open task and make add table
3. Try to save it - button is greyed.
4. Try to continue without saving - export fails
[tasks_log.log](https://github.com/dbeaver/dbeaver/files/3748067/tasks_log.log)
![save_dbt](https://user-images.githubusercontent.com/31996417/67162824-a9abb500-f370-11e9-9611-78480b656899.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
