### ISSUE TITLE
Redshift - Unload and Copy presenting syntax error

### ISSUE THREAD

**Issue by BarryEdwards** [dbeaver/dbeaver#7024]
#### System information: 
- Operating system (distribution) and version: MacOS 10.14.16
- DBeaver version: Version 6.2.1.201909221630

#### Connection specification:
- AWS Redshift: Server PostgreSQL 08.00.0002
- Driver: RedshiftJDBC 01.02.34.1058

#### Describe your question:
The following command fails:
UNLOAD 
('select * from mcd_analytics.venue')
TO 's3://XXXX-bucket/venue_XXX.csv'
iam_role 'arn:aws:iam::XXXXXXXXX:role/mcd_redshift_s3_role'
;

With the error:

SQL Error [42601]: ERROR: syntax error at or near "UNLOAD"

When I run the same on another SQL client (DataGrip), no errors. Command executes.

BTW: Same happens with the AWS Redshift 'COPY' command.
 COPY mcd_analytics.users
     FROM 's3://awssampledbuswest2/tickit/allusers_pipe.txt'
     CREDENTIALS 'aws_iam_role=arn:aws:iam::XXXXX:role/mcd_redshift_s3_role'
     delimiter '|' region 'us-west-2';

Is this  that UNLOAD and COPY commands are AWS Redshift specific, and not 'standard SQL', and so this is a compatibility issue?  (The UNLOAD and COPY keywords are not highlighted in the DBeaver GUI.)

**Comment by serge-rider** [comment]
I can't reproduce this (UNLOAD command fails with valid Redshift error `[500310] [Amazon](500310) Invalid operation` because of lack of user permissions).

What driver do you use - AWS Redshift or standard PostgreSQL driver? You should use Redshift one.

**Comment by BarryEdwards** [comment]
I believe I am using redshift: redshift-jdbc42-1.2.34.1058.jar

**Comment by uslss** [comment]
is it still acual?

**Comment by uslss** [comment]
there is no update on an issue more than a month.
Ticket closed.
If the issue still actual - feel free to reopen the ticket

**Comment by jadenguyen0128** [comment]
I experienced the similar issue. And it turned out that it's the user error. Specifically, I used the UNLOAD command in SQL editor page that is connected to the wrong database. For example, I need to unload the data from 1 table from Redshift cluster A to S3. But I executed the UNLOAD command in the SQL editor page that is connected to Redshift cluster B.
