### ISSUE TITLE
SQL connection timeout

### ISSUE THREAD

**Issue by resquej** [dbeaver/dbeaver#7026]
#### System information: 
- Windows 10
- DBeaver Community 6.2.1 and EE 6.2.0

#### Connection specification:
- SQL Server 14
- Microsoft JDBC Driver for SQL Server

#### Describe the problem you're observing:
When connecting to the server the recurrent connection from other sources raises a timeout error.

#### Steps to reproduce, if exist:
- The SQL Server is a production server. The backend app is using the server.
- After some time (not immediately) the backend app raises time out error.
- When disconnecting DBeaver, automatically the backend works.

Thank you

**Comment by lc2796** [comment]
Same issue with Mac dbeaver 6.2.3

Error: Error connecting to datasource Reason:
Connection attempt timed out.

**System information:**
MacOS Mojave 10.14.6
DBeaver Community 6.2.1 and EE 6.2.0
**Connection specification:**
PostgreSQL on AWS RDS

**Describe the problem you're observing:**
When connecting to the DB showing the error raises a timeout error. "Error connecting to datasource Reason:
Connection attempt timed out."
Start time: 11pm EST 10/29/2019, working fine before that

But when I use another SQL runner to run/open the DBs, it works fine, so only on DBeaver is working weird

**Steps to reproduce, if exist:**
The AWS RDS server is a production server. 
Cannot reconnect after 10+ times trail
I have 3 different data connections on AWS RDS, none of them can connect

**Comment by hamidmustafa** [comment]
I 'm having the exact same problem. I have one RDS instance and can't connect through DBWeaver

**Comment by uslss** [comment]
Please, change Keep-Alive value in connection properties to non-null.
![image](https://user-images.githubusercontent.com/31996417/92582354-885dfb00-f299-11ea-9e31-ea565bd7b177.png)

**Comment by hamidmustafa** [comment]
@uslss Thank you

**Comment by NulledExceptions** [comment]
Thank you!!
