### ISSUE TITLE
No finish message after export

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#7027]
**Steps to reproduce:**
* Run some query.
* Export the query to csv by right-clicking the results pane and selecting 'export'.
* In the export dialog, tick the options for "Show finish message" and for "Open output folder at end".
* Go through the whole process until the file is exported.

**Expected behavior:** should show a finish message and open the output folder once it's done, with the output file selected in that folder.

**Actual behavior:** it opens the output folder (file is not pre-selected there though), but doesn't show any finish message.

**Setup:** dbeaver 6.2.3, running on windows 10, connecting to postgre11.

**Comment by uslss** [comment]
Hi, @david-cortes ,
unfortunately, i cannot reproduce the issue - finish message is shown as usual :(
![image](https://user-images.githubusercontent.com/31996417/67203921-006aca80-f415-11e9-9338-022a44f12ed2.png)
Probably, you could try to Reset UI Settings.

**Comment by david-cortes** [comment]
Oh, I see now, was expecting to see the old notification pop-up message that had an Ok button.
