### ISSUE TITLE
When Connect Remote to Windows from macOS, DBeaver Crash

### ISSUE THREAD

**Issue by oguzhankircali** [dbeaver/dbeaver#7028]
Hi DBeaver Team,

My personal laptop is Macbook with MacOS Catalina
My work pc is Windows 10.
When I use Microsoft Remote app on macOS for connecting my work PC,
DBeaver has been crashed. 

#### System information: 
- Windows 10, Version 10.0.17763
- DBeaver version: 6.2.1
- Microsoft Remote App

**Comment by serge-rider** [comment]
Please provide more iformation.

- Does it crash on startup or after some actions?
- Are there any error messages or logs?

**Comment by oguzhankircali** [comment]
- No any action. Just i connect my Windows PC, I saw my desktop then DBeaver crash
- Message: DBeaver has been stopped.
- I will try to most recent version, after that i will write again to you.

**Comment by uslss** [comment]
@oguzhankircali do you have any updates? is issue reproducible on current version?

**Comment by uslss** [comment]
there is no any updates more than a month. ticket closed
