### ISSUE TITLE
Postgresql error with ; in string

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#7029]
#### System information: 
- Windows 7 Pro SP1
- DBeaver 6.2.3.201910201831
- No additional extensions

#### Connection specification:
- PostgreSQL 9.5.16
- Driver: org.postgresql:postgresql:RELEASE [9.4.1212.jre7]; net.postgis:postgis-jdbc:RELEASE [2.2.1]
- No tunnels or proxies

When string in query contains ";" an error occurs "SQL Error: Internal jdbc driver error"
Example `SELECT ');'`

**Comment by serge-rider** [comment]
Thanks for the bug report.
This seems to be caused by recent strings parser.

Workaround: select your query before execute.

**Comment by uslss** [comment]
verified

**Comment by serge-rider** [comment]
We just released hotfix version with the fix (6.2.3.201910211155)
