### ISSUE TITLE
[Oracle] DDL Generator doesn't include the GRANTS

### ISSUE THREAD

**Issue by dnroldan** [dbeaver/dbeaver#7031]
**Is your feature request related to a problem? Please describe.**
When I generate de DDL of any table, GRANTS aren't included.

**Describe the solution you'd like**
Include the GRANTS on generated DDL

**Comment by ceinmart** [comment]
Waiting for this *basic* feature...

**Comment by LonwoLonwo** [comment]
And what type of grants are you looking for? 

We can use SELECT DBMS_METADATA.GET_DEPENDENT_DDL('SYSTEM_GRANT',object_name, owner) or
SELECT DBMS_METADATA.GET_DEPENDENT_DDL('OBJECT_GRANT',object_name, owner)

**Comment by dnroldan** [comment]
I don't know, I tried your queries but I don't know how to use it correctly

**Comment by LonwoLonwo** [comment]
Hello @dnroldan 
Please use table name as object_name and schema/user name as owner.
like 
SELECT DBMS_METADATA.GET_DEPENDENT_DDL('OBJECT_GRANT','EMPLOYEE', 'HR')

**Comment by dnroldan** [comment]
Hello @LonwoLonwo, i tried it but I have a "SQL Error [923] [42000]: ORA-00923"

If I put the "select * from DBMS... i get a SQL Error [933] [42000]: ORA-00933

**Comment by LonwoLonwo** [comment]
Hello  @p91paul 
As our best Oracle Consultant, what do you think, what GRANTS should it be shown in the Table DDL tab? May be you know a suitable query? I would like to implement this FR.

**Comment by ceinmart** [comment]
Not sure if this SQL cover all situations, but I think is the basic for any Oracle version... 


```
  select 'grant '||privilege||' on '||owner||'.'||table_name||' to '||grantee
           ||case when grantable = 'YES' then ' with grant option' else null end
           ||';'
  from dba_tab_privs
  where 1=1
  -- and table_name = 'XPTO'
  -- and grantee in ( select role from dba_roles )
  -- and grantee = 'USER_XPTO'
  order by grantee, owner ; 
```

**Comment by dnroldan** [comment]
> Not sure if this SQL cover all situations, but I think is the basic for any Oracle version...
> 
> ```
>   select 'grant '||privilege||' on '||owner||'.'||table_name||' to '||grantee
>            ||case when grantable = 'YES' then ' with grant option' else null end
>            ||';'
>   from dba_tab_privs
>   where 1=1
>   -- and table_name = 'XPTO'
>   -- and grantee in ( select role from dba_roles )
>   -- and grantee = 'USER_XPTO'
>   order by grantee, owner ; 
> ```

Hi @ceinmart ,

I cant obtain results with your query because my user haven't privilleges to acces "dba_tab_privs".
I only comment it because I imagin that the final solution may be for credentials with minor permissions.

Regards.

**Comment by ceinmart** [comment]
ouch, my bad , try this :


```
 select 'grant '||privilege||' on '||table_schema||'.'||table_name||' to '||grantee
           ||case when grantable = 'YES' then ' with grant option' else null end
           ||';'
  from all_tab_privs p
  where 1=1
  -- and table_name = 'XPTO'
  -- and grantee in ( select role from dba_roles )
  -- and grantee = 'USER_XPTO'
  --order by grantee, table_schema ; 
```

**Comment by p91paul** [comment]
> 
> 
> Hello @p91paul
> As our best Oracle Consultant, what do you think, what GRANTS should it be shown in the Table DDL tab? May be you know a suitable query? I would like to implement this FR.

Wow, didn't know I had that title 😀 

This one looks fine (in your previous comments, the FROM DUAL part was missing which is why probably the other guys couldn't try it).
```
SELECT DBMS_METADATA.GET_DEPENDENT_DDL('OBJECT_GRANT',object_name, owner)
FROM DUAL
```

Based on my test, it extracts all grants when the user has DBA privileges, and only the ones to your user when executed by an unprivileged user. Should be equivalent to @ceinmart queries, except easier.

SYSTEM_GRANT in my tests just throws an error, it's probably not to be used on object like tables.

**Comment by dnroldan** [comment]
Thanks @p91paul ,

I had this error:

SQL Error [31608] [99999]: ORA-31608: no se ha encontrado el objeto especificado de tipo OBJECT_GRANT
ORA-06512: en "SYS.DBMS_METADATA", línea 5088
ORA-06512: en "SYS.DBMS_METADATA", línea 7681
ORA-06512: en línea 1

Regards.

**Comment by p91paul** [comment]
and does the @ceinmart latest query return some rows instead?

**Comment by p91paul** [comment]
According to stackoverflow, that exception is thrown when there are no grants for your user on that table. So it must be handled gracefully on Dbeaver side if they choose the DBMS_METADATA query.

**Comment by dnroldan** [comment]
> and does the @ceinmart latest query return some rows instead?

If I comment the subquery with "dba_roles", it´s works.

**Comment by dnroldan** [comment]
> According to stackoverflow, that exception is thrown when there are no grants for your user on that table. So it must be handled gracefully on Dbeaver side if they choose the DBMS_METADATA query.

I don't know, I tried with grantor and granted schemas and fails with both of them.

Thanks

**Comment by p91paul** [comment]
@dnroldan could you provide sample ddl? the create table and grants, then the exact dbms_metadata query you are running and with which user you are connected while running it. Of course without including sensitive details.

**Comment by dnroldan** [comment]
> @dnroldan could you provide sample ddl? the create table and grants, then the exact dbms_metadata query you are running and with which user you are connected while running it. Of course without including sensitive details.

For example:

GRANT INSERT, SELECT , UPDATE, DELETE ON SCHEMA_OWNER_NAME.TABLE_NAME TO SCHEMA_NAME_GRANTED;

Thanks

**Comment by p91paul** [comment]
@dnroldan sorry can't reproduce anything with just that.
From what I can see on my system dbms_metadata works awesomely, I leave further analysis to the dbeaver developers. One thing for certain, you must be prepared to the function failing and throwing exceptions if the object has no grants on it.
Or you could query dba/all tab privs, depending on user preferences, and handle quoting in dbeaver.

**Comment by renezito** [comment]
> Hello @LonwoLonwo, i tried it but I have a "SQL Error [923] [42000]: ORA-00923"
> 
> If I put the "select * from DBMS... i get a SQL Error [933] [42000]: ORA-00933

May be it's not too late to post this, but the query sent by @LonwoLonwo can't be executed in a simple select.  And about what kind of grants?  I put an image of another app that shows all grants that an object has:

It doesn't matter the object/owner, just can't use that kind of query:
![image](https://user-images.githubusercontent.com/37661233/122127977-f673b780-ce01-11eb-84f4-95d6a42aa42e.png)

In SQL Developers GRANTs are displayed in tab "Permisos" (Grants).  Of course it would be a really appreciated feature if you can add it to Dbeaver:
![image](https://user-images.githubusercontent.com/37661233/122129757-8e72a080-ce04-11eb-8551-a5c495550eea.png)

**Comment by p91paul** [comment]
@renezito Dbeaver already has a permissions tab in the table editor.

This is to get grants in table ddl. Also, the query lacked a FROM DUAL, see correction a few comments later.

**Comment by renezito** [comment]
Thanks @p91paul  !!!  I haven't seen the tab.   I saw the query FROM DUAL too, thanks again!
And as you say, this is to get grant query in table DDL... so I'm going to wait for this  :-)

**Comment by serge-rider** [comment]
After all I added usage of GET_DEPENDENT_DDL with OBJECT_GRANT
It is visible only when FULL DDL is selected
