### ISSUE TITLE
[Oracle] DDL Generator doesn't include the INDEXES

### ISSUE THREAD

**Issue by dnroldan** [dbeaver/dbeaver#7032]
Is your feature request related to a problem? Please describe.
When I generate de DDL of any table, INDEXESaren't included.

Describe the solution you'd like
Include the INDEXES on generated DDL

Thanks.

**Comment by LonwoLonwo** [comment]
Now indexes are read in table DDL as well as main part with columns, constraints etc.
They are read at any DDL format (both in FULL and compact).
Changed reading comments. Now we do not request a database for them, and read comments on the object and object columns on your own. To avoid errors in logs for those objects that have no comments.

**Comment by uslss** [comment]
verified
