### ISSUE TITLE
[BUG] Pinned tabs in results grid have very funny behavior

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#7035]
Many funny thing happen with tabs, will just report the easyer to reproduce:
0) from a "clean" situation
1) run a query
2) pin result tab (T0)
3) run another query, it generates tab T1; Tab order now is T1, T0
4) move pinned tab T0 on the right of T1, so it is the leftest tab
Which is pinned tab now? T1:-)

Many other funny behavior encourred, harder to explain but on the same topic

Linux Mint 18.04, dbeaver 6.2.3

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
Verified
