### ISSUE TITLE
Finish message after export is shown even if it is disabled in export settings

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7036]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.3
#### Steps to reproduce, if exist:
1, Start export to CSV from some result query
2. Uncheck "Show finish message on finish" and start export -> finish message is shown anyway

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
