### ISSUE TITLE
Bug in Execute + Export, with @set commands

### ISSUE THREAD

**Issue by knwpsk** [dbeaver/dbeaver#7038]
Just updated from v6.05 to v6.23, on Windows 10.
Functionality that formerly worked is now broken.

Example query:

**@set o = Order
select * from "${o}" limit 100**

BUG:
If I highlight all, right-click > Execute > Export From Query, it throws error saying:

_Data transfer failed
Reason:
SQL Error [42P01]: ERROR: relation "${o}" does not exist_

COUNTER EXAMPLE:
If I simply Execute As Script (Alt-x), it works ok (without exporting).

IMPORTANCE:
When executing very long queries, I need to be able to execute and export in one step.  If I have to wait to execute first, view results, then export, this takes way too long.

Thanks!

**Comment by knwpsk** [comment]
Another issue, probably related.
Use same script as above.

Alt-x to execute the script, see results in app window.
Right-click results and choose Export Data.

Throws error:  

_SQL Error [42P01]: ERROR: relation "Orderrr" does not exist
  Position: 15
  ERROR: relation "Orderrr" does not exist
  Position: 15
  ERROR: relation "Orderrr" does not exist
  Position: 15_

Notice the table name has been garbled to "Orderrr" somehow in the Export Data process.

**Comment by knwpsk** [comment]
Another permutation, also probably the same bug:

Use same script as above.
Alt-x to execute, see first set of results in app window.
**Scroll to the bottom of results, app tries to load more results.**

Throws error:

_SQL Error [42P01]: ERROR: relation "Orderr" does not exist
  Position: 15_

So, this may not be directly related to Export?

**Comment by serge-rider** [comment]
Thanks for the bug report.
Fixed

**Comment by uslss** [comment]
verified

**Comment by knwpsk** [comment]
Thanks guys!

**Comment by knwpsk** [comment]
Confirmed this is fixed in release 6.2.4.
Thanks for the quick turnaround, folks!
