### ISSUE TITLE
 dbms_metadata.get_ddl returns clob

### ISSUE THREAD

**Issue by andrewwellsdfj** [dbeaver/dbeaver#7040]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 6.1,6.2,6.2.3 early access
- Additional extensions

#### Connection specification:
- Database name and version Oracle 11g
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
 dbms_metadata.get_ddl returning Clob that is unparsable 
#### Steps to reproduce, if exist:
     select dbms_metadata.get_ddl('PROCEDURE',<PROECDUREANME>) from dual;

this returns [CLOB] which we can then not translate into DDL code

**Comment by serge-rider** [comment]
It is the same bug as in #7029
We'll probably release the hotfix version shortly.
