### ISSUE TITLE
"Create procedure" command actually creates a function, not а procedure

### ISSUE THREAD

**Issue by megabooster6** [dbeaver/dbeaver#7041]
#### System information: 
- Operating system: Windows 7 SP1
- DBeaver version: 6.2.3.201910191000

#### Connection specification:
- PostgreSQL 11.5.3
- PostgreSQL JDBC Driver

#### Describe the problem you're observing:
1. Open Database->Schemas->Functions in the treeview
2. Right-click, then "Create procedure object"
3. Type a name, then select Type=PROCEDURE and Language=plpgsql and press OK
* Observed behaviour:
New window opens with the text CREATE OR REPLACE **FUNCTION** ...
* Expected behaviour:
New window opens with the text CREATE OR REPLACE **PROCEDURE** ...

![2019-10-21_18-43-59](https://user-images.githubusercontent.com/56837666/67221672-88ac9800-f434-11e9-8f17-e50568ec3777.png)

**Comment by FernandaCG** [comment]
Hi! Can I work on this?

**Comment by gvey** [comment]
"Create Function" creates a Procedure:
![dbeaver](https://user-images.githubusercontent.com/10639641/76252407-0d9b2100-621f-11ea-81d7-3b1f4c069772.PNG)
![image](https://user-images.githubusercontent.com/10639641/76252415-13910200-621f-11ea-9c2a-f69332e2d712.png)

**Comment by serge-rider** [comment]
Thanks for the bug report (and sorry for long delay, I missed the original ticket).

**Comment by uslss** [comment]
there is no ability to choose function or procedure. function is created always
![image](https://user-images.githubusercontent.com/31996417/76634987-c8952880-6557-11ea-9cb1-d67676898d32.png)

**Comment by serge-rider** [comment]
@uslss Procedures were added in PG 11. For earlier version we don't show type selector.

**Comment by uslss** [comment]
verified
