### ISSUE TITLE
Fully qualified names are always used in generated DDL for Oracle tables

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7042]
### System information:  
- Operating system (distribution) and version  win 10 x64
- DBeaver version 6.2.3

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
Fully qualified names are used for generated DDL even in case option is disabled
![image](https://user-images.githubusercontent.com/31996417/67222040-26a06280-f435-11e9-9ab9-67159aae2665.png)

**Comment by uslss** [comment]
#3164

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
