### ISSUE TITLE
cannot leave open parentheses inside string

### ISSUE THREAD

**Issue by jbuckles** [dbeaver/dbeaver#7043]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
6.2.3
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
PostgreSQL
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
sometimes, but not in this instance

#### Describe the problem you're observing:
Cannot run select query with open parenthesis. For example: select 'hello(world'; hangs indefinitely, while select 'hello() world' works . This was not an issue in DBeaver 6.2.2.
#### Steps to reproduce, if exist:
select 'hello(';

#### Include any warning/errors/backtraces from the logs

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42601]: Unterminated string literal started at position 220 in SQL

**Comment by serge-rider** [comment]
It is the same bug as in #7029
Thanks for the bug report anyway.

We'll release hotfix version tomorrow morning.
