### ISSUE TITLE
Execution time exceeded run time cap

### ISSUE THREAD

**Issue by lukaskohl9** [dbeaver/dbeaver#7044]
Hello, please can anybody tell me how to extend runtimecap while importing data from Vertica DB to MySQL. It said Execution time exceeded run time cap of 02:00 (2 hours) and something about jkiss.

Thank you for help

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer. Is it still actual for you?

**Comment by lukaskohl9** [comment]
Hello,

no more actual. Thank you :)
Have a nice day
Lukas

čt 23. 4. 2020 v 11:34 odesílatel Kseniia <notifications@github.com> napsal:
