### ISSUE TITLE
File close on 6.2.3 does not allow sql file to be closed without saving

### ISSUE THREAD

**Issue by kiravi** [dbeaver/dbeaver#7045]
When closing a popup launces a save file window and does not have do not save button to dismiss saving file opened for oracle connection.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce. Is this issue still actual for you?

**Comment by uslss** [comment]
If I catch you correctly, you could uncheck all the scripts and click Save button - so no scripts will be saved
