### ISSUE TITLE
missing functions in oracle scheme

### ISSUE THREAD

**Issue by kstechlinski** [dbeaver/dbeaver#7046]
HI,
I'm missing functions in my oracle scheme. 

Operating system (distribution) and version - windows 10
- DBeaver version - newest 6.2.3

#### Connection specification:
- Database name and version - Oracle 12c
- Driver name : Oracle JDBC driver - ojdbc8.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - no

**Comment by p91paul** [comment]
functions are usually in the folder "procedures", did you look there
