### ISSUE TITLE
GUI Colors Messed Up

### ISSUE THREAD

**Issue by chasen-bettinger** [dbeaver/dbeaver#7047]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18
- DBeaver version: 6.2
- Additional extensions: none

#### Describe the problem you're observing:

The colors are all messed up: https://i.imgur.com/R7TTcPe.png

**Comment by orione1974** [comment]
I have a similar problem with my Linux Mint 19.2 
In Text Mode, is visible ![image](https://user-images.githubusercontent.com/1917307/67276013-15526700-f4c4-11e9-8c81-30ff2d436dc3.png)
In Grid Mode is not visibile 
![image](https://user-images.githubusercontent.com/1917307/67276093-3f0b8e00-f4c4-11e9-8988-31dec3b4f65b.png)

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
if issue is still actual for you - feel free to reopen the ticket
