### ISSUE TITLE
Grid Column Displayed As Select Column Alias

### ISSUE THREAD

**Issue by iambudi** [dbeaver/dbeaver#7048]
#### System information: 
- MacOS Catalina
- DBeaver 6.2.3 Community

#### Connection specification:
- MySQL v 8.0.18 ~ Connection Driver MySQL 8+

#### Describe your question:
When aliasing column the result grid column does not display the alias name, but original column name so it's confusing when there are a lot of same column name select from different join table.
Is there any config to set the grid column as aliased?

```sql
SELECT
 -- <# this works
	DATE_FORMAT(insert_date, ‘%d/%m/%Y’) AS so_date,
 -- # It should be displayed as product_id but the grid show product_map_id
	product_map_id AS product_id
FROM table_x
```

**Comment by kseniiaguzeeva** [comment]
DBeaver does not have such function, but you can assign a custom name using operator AS:
select columnname as somename from tablename
![dbeaver_CmhvkMHJNV](https://user-images.githubusercontent.com/51405061/81311016-871f8600-908d-11ea-98f2-086f894078fc.png)

Please reopen the ticket if you have any other questions.

**Comment by iambudi** [comment]
DBEaver Version 7.0.4.202005031953
Alias `AS` still does not work.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/31809529/81512094-13f56880-9348-11ea-84a5-2e92dd28b922.png">

**Comment by tati-kru** [comment]
We cannot reproduce this on Mac in version 7.1. 
Please, check that your database itself supports this feature.

**Comment by iambudi** [comment]
Hi @tati-kru,

I use mysql client cli and the alias feature is well supported.
Is there any DBEaver preference that i might change mistakenly and effect this behaviour?

<img width="571" alt="image" src="https://user-images.githubusercontent.com/31809529/83206978-54dce200-a17c-11ea-9250-3dd6fa5280ad.png">

**Comment by serge-rider** [comment]
@iambudi please check this pref option:
![image](https://user-images.githubusercontent.com/6398845/83260699-e66f4280-a1c2-11ea-999d-cc5ddcd1f694.png)


It suppresses column labels and shows original column names only.

**Comment by iambudi** [comment]
@serge-rider That's perfect. Thanks a lot.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/31809529/83314616-8077cf00-a245-11ea-8f57-e70d707a5970.png">

**Comment by DarthSHO** [comment]
> 
> #### System information:
> 
>     * MacOS Catalina
> 
>     * DBeaver 6.2.3 Community
> 
> 
> #### Connection specification:
> 
>     * MySQL v 8.0.18 ~ Connection Driver MySQL 8+
> 
> 
> #### Describe your question:
> 
> When aliasing column the result grid column does not display the alias name, but original column name so it's confusing when there are a lot of same column name select from different join table. Is there any config to set the grid column as aliased?
> 
> ```sql
> SELECT
>  -- <# this works
> 	DATE_FORMAT(insert_date, ‘%d/%m/%Y’) AS so_date,
>  -- # It should be displayed as product_id but the grid show product_map_id
> 	product_map_id AS product_id
> FROM table_x
> ```

I just started experiencing this today after using the same version of DBeaver for months. Some existing scripts still work, but I cannot get new scripts to use "As".

Windows 10
Dbeaver 21.2.0.202109061154
MariaDB 10.5

This is really odd. Checking the MariaDB log I can clearly see it being passed to the server.

Example

SELECT c.CUST as customerID
FROM CUSTOMER c

Column shows as CUST not customerID. This just started happening. No updates to anything.
