### ISSUE TITLE
Disconnect all connections context menu option at folder connection level

### ISSUE THREAD

**Issue by yevon** [dbeaver/dbeaver#7051]
There is already an option for disconnecting all connections, but i really miss an option that sqldeveloper has, and is to disconnect only connections of a folder when you perform a right click over it. The idea is having a "Disconnect connections" in the context menu at folder level, here:

![image](https://user-images.githubusercontent.com/121157/67267111-f3e87f80-f4b1-11e9-99d4-d269e9b60d0c.png)

**Comment by serge-rider** [comment]
Makes sense, thanks for idea.

**Comment by kseniiaguzeeva** [comment]
Verified.
