### ISSUE TITLE
SQL Editors mixed up

### ISSUE THREAD

**Issue by petrvalkoun-gooddata** [dbeaver/dbeaver#7053]
Latest DBeaver 6.2.3 is messing up the SQL Editors, showing different editor for connections. I am using every day that DBeaver remembers all editors for each connection (its pretty cool!!). After latest upgrade, its mixing up the editor, showing one editors for wrong connections.

First of all, I lost many custom settings after the upgrade from 6.2.2, such as what to do when I double client on connection (I want to open latest editor). during setting that back, I enabled this feature: Database -> Editors -> Auto-sync editor connection with navigator selection.

It is very well possible that this caused the issue.

**Comment by p91paul** [comment]
looks like you just need to disable that option then! Its purpose is to link editor with navigator, so clicking on a new connection on the navigator changes the editors to that connection.

**Comment by petrvalkoun-gooddata** [comment]
so, this ticket actually contained two independent issues:
1) loosing settings (repeatedly) during upgrade, which is annoying
2) behavior of setting Database -> Editors -> Auto-sync

The part two was misunderstanding on my part, part one is still issue

**Comment by uslss** [comment]
for the first issue #7251 is already created
