### ISSUE TITLE
Column order is wrong in csv export

### ISSUE THREAD

**Issue by mioux** [dbeaver/dbeaver#7054]
#### System information: 
- Operating system (distribution) and version : Ubuntu 18.10
- DBeaver version : 6.2.3 from dbeaver repo `deb https://dbeaver.io/debs/dbeaver-ce /`
- Additional extensions : none

#### Connection specification:
- Database name and version : MariaDB 10.4.7 from official repo
- Driver name : MariaDB 2.5.0 (org.mariadb.jdbc:mariadb-java-client)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : I use a SSH tunnel opened by hand with `ssh isolated-server -L 3306:db-server:3306`

#### Describe the problem you're observing:

When I export data in CSV, the order of the colums are wrong. It does it only for a specific query, the first columns are ordered alphabetically, but not all

#### Steps to reproduce, if exist:

Run this query :

    select  p.id,
            p.nom,
            p.prenom,
            p_col.nom as nom_collaborateur,
            p_col.prenom as prenom_collaborateur,
            v.id as id_vente,
            v.contrat,
            v.ouverture,
            v.cloture,
            pr.libelle as prestation
    from    v inner join
            p on p.id = v.titulaire inner join
            col on col.id = v.collaborateur inner join
            p_col on p_col.id = col.personne inner join
            pr on v.prestation = pr.id
    where   exists (select  1
                    from    sl
                    where   sl.vente = v.id and
                            date_add(import, interval 20 day) < NOW()) and
            v.group = 76

![image](https://user-images.githubusercontent.com/6904170/67275491-0919da00-f4c3-11e9-8fc2-ee7c81de2b47.png)

Result CSV :
`"id";"id_vente";"nom";"nom_collaborateur";"prenom";"prenom_collaborateur";"contrat";"ouverture";"cloture";"prestation"`
Expected CSV
`"id";"nom";"prenom";"nom_collaborateur";"prenom_collaborateur";"id_vente";"contrat";"ouverture";"cloture";"prestation"`

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by serge-rider** [comment]
I can't reproduce this..

**Comment by serge-rider** [comment]
The problem was in duplicated column names (`id`). 
Fixed.

**Comment by kseniiaguzeeva** [comment]
Verified
