### ISSUE TITLE
extension (5) should not be presented in certificate_request

### ISSUE THREAD

**Issue by wxw9868** [dbeaver/dbeaver#7055]
![image](https://user-images.githubusercontent.com/33060200/67275497-5747d100-f4f5-11e9-8a0c-a3cf7088f643.png)
![image](https://user-images.githubusercontent.com/33060200/67275461-3f704d00-f4f5-11e9-8500-95945822c4ba.png)
![image](https://user-images.githubusercontent.com/33060200/67275537-69c20a80-f4f5-11e9-90c2-b5bba1956805.png)

**Comment by florence-crl** [comment]
This is probably due to this issue: https://github.com/golang/go/issues/35722
