### ISSUE TITLE
Separate procedures and functions in different folders for Oracle

### ISSUE THREAD

**Issue by yevon** [dbeaver/dbeaver#7058]
Also it would be nice having oracle functions and procedures in separate folders, just for better organization. Every object type, should be in its own folder. In oracle, functions and procedures are clearly different types, and is a bit confusing seeing them at same level in same folder in the object tree. I think you have another similar open issue opened (Issue 7046).

![image](https://user-images.githubusercontent.com/121157/67278098-9b70ac80-f4c8-11e9-87f6-4dedab7fe2ff.png)

**Comment by ShadelessFox** [comment]
Will be implemented in #11408
