### ISSUE TITLE
workspace corrupted

### ISSUE THREAD

**Issue by lekoala** [dbeaver/dbeaver#7062]
I'm using DBeaver 6.2.3 on Win10

Today, when opening DBeaver I get an error message:
In database navigator:  Failed to create the part's controls
In workspace log Failed to read the project description file (.project) for 'General'.  The file has been changed on disk, and it now contains invalid information.  The project will not function properly until the description file is restored to a valid state.

> java.lang.Exception: Failed to read the project description file (.project) for 'General'.  The file has been changed on disk, and it now contains invalid information.  The project will not function properly until the description file is restored to a valid state.
> 	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
> 	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
> 	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:915)
> 	at org.eclipse.core.internal.resources.SaveManager.restoreMetaInfo(SaveManager.java:892)
> 	at org.eclipse.core.internal.resources.SaveManager.restore(SaveManager.java:763)
> 	at org.eclipse.core.internal.resources.Project.open(Project.java:1056)
> 	at org.eclipse.core.internal.resources.Project.open(Project.java:1102)
> 	at org.jkiss.dbeaver.registry.ProjectMetadata.ensureOpen(ProjectMetadata.java:137)
> 	at org.jkiss.dbeaver.model.navigator.DBNProject.getChildren(DBNProject.java:124)
> 	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:69)
> 	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorContentProvider.getChildren(DatabaseNavigatorContentProvider.java:120)
> 	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorContentProvider.getElements(DatabaseNavigatorContentProvider.java:74)
> 	at org.eclipse.jface.viewers.StructuredViewer.getRawChildren(StructuredViewer.java:940)
> 	at org.eclipse.jface.viewers.ColumnViewer.getRawChildren(ColumnViewer.java:704)
> 	at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1397)
> 	at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:350)
> 	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:846)
> 	at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:620)
> 	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:814)
> 	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:604)
> 	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:765)
> 	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpand(AbstractTreeViewer.java:1679)
> 	at org.eclipse.jface.viewers.AbstractTreeViewer.setSelectionToWidget(AbstractTreeViewer.java:2543)
> 	at org.eclipse.jface.viewers.AbstractTreeViewer.setSelectionToWidget(AbstractTreeViewer.java:3012)
> 	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1398)
> 	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:363)
> 	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1352)
> 	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1452)
> 	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:526)
> 	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1411)
> 	at org.jkiss.dbeaver.ui.controls.ViewerColumnController.recreateColumns(ViewerColumnController.java:225)
> 	at org.jkiss.dbeaver.ui.controls.ViewerColumnController.createColumns(ViewerColumnController.java:199)
> 	at org.jkiss.dbeaver.ui.navigator.project.ProjectExplorerView.lambda$0(ProjectExplorerView.java:191)
> 	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
> 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
> 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
> 	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
> 	at org.eclipse.jface.window.Window.open(Window.java:799)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.CreateConnectionDialog.open(CreateConnectionDialog.java:83)
> 	at org.jkiss.dbeaver.core.application.WorkbenchInitializerNewConnection.initializeWorkbenchWindow(WorkbenchInitializerNewConnection.java:32)
> 	at org.jkiss.dbeaver.core.application.ApplicationWorkbenchWindowAdvisor.lambda$1(ApplicationWorkbenchWindowAdvisor.java:241)
> 	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
> 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
> 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
> 	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:226)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
> 

changing workspace works fine, but if I try to copy settings from data-sources.json, it crashes again (and removing the copied data keeps it crashed, i have to create another workspace)

downgrading does not seem to help (workspace still corrupted)

potential duplicate of https://github.com/dbeaver/dbeaver/issues/6820 and https://github.com/dbeaver/dbeaver/issues/6751 but i'm not sure

not sure what to do to get back my data sources, any way to import them through dbeaver since manual changes to json files does not seem to work?

**Comment by lekoala** [comment]
actually, creating a new workspace doesnt work either, as soon as I add a couple of connections, i close dbeaver, open again : corrupted

i only added two maria db servers and one mysql. both with ssh tunnels. nothing special, but it crashes anyway.

**Comment by serge-rider** [comment]
Could you try to run dbeaver with parameter `-data data_path` where data_path is some local folder path where all cofigurations will be stored?
Maybe there are some issues with your default appdata folder.

**Comment by michimartini** [comment]
I had the same problem, and the "-data data_path" approach worked for me.

**Comment by lekoala** [comment]
@serge-rider well, it's starting just fine if i change the workspace (or the data_path). My issue is : how to migrate settings from my previous workspace?
and also, even if I start on a fresh workspace or data_path, it seems to get corrupted anyway (I haven't tried since last time, it's really annoying to add manually the connections and see they all got lots with no way to retrieve them)

how can I export/import these settings so I can easily add a couple of connections, save them somewhere in case my workspace get corrupted again?

**Comment by serge-rider** [comment]
You can just copy all files from default <a href="https://github.com/dbeaver/dbeaver/wiki/Workspace-Location">worksapce location</a> to your data path.

**Comment by serge-rider** [comment]
Also you can change default workspace location by adding lines
```
-data
data_path
```
in dbeaver.ini file (before -vmargs line)

**Comment by lekoala** [comment]
@serge-rider trying to import "fresh" files from the default workspace to a corrupted workspace seemed to work so far!
