### ISSUE TITLE
Is my 15k table Oracle 12C database too large for DBeaver? 

### ISSUE THREAD

**Issue by mz10001** [dbeaver/dbeaver#7065]
Hello, My Oracle 12C DB has about 15,000 tables and 10,000 tables in the schema I operate out of. 
DB Beaver is extremely slow and is constantly loading results metadata. Querying a one record table takes about 5 minutes. I am guessing this is due to the high number of tables in my DB causing slow metadata lookups.

Is there a way around this or do I need to try different software? Maybe if it's possible to turn off metadata lookups? I've tried the various metadata performance improvement checkboxes but they don't seem to have any impact. 

I have been using Golden 6 from Benthic software without issues, but need a new free for commercial use solution if anyone has any recommendations if DBeaver cannot not work. 

Thanks!

**Comment by mz10001** [comment]
As I suspected it's in the Metadata- it's hanging on : 

SELECT  * FROM ALL_OBJECTS WHERE OBJECT_TYPE='PACKAGE' AND OWNER='XYZ';

**Comment by lucasMesquitaBorges** [comment]
I'm recently new to DBeaver, for smaller databases it's great, but for your case I don't now if there's a way to disable it. At my work the database is huge, but there I have to use a commercial SQL Client.

This "indexing" should be in background and with some type of low priority after a period of indexing (querying the database), paginating results and only when not the user is querying the Db... And of course, having a way to disable the indexing whenever we think it's necessary.

If no-one who is already involved with the project get these feature/hotfix assigned, I would be glad of taking those.

**Comment by maln0ir** [comment]
DBeaver just runs some pretty basic queries to fetch metadata. If they take minutes to complete, like this query on `all_objects`, then I would say you have problem with database performance.

**Comment by serge-rider** [comment]
@mz10001 Try to play with performance options:
![image](https://user-images.githubusercontent.com/6398845/67626321-46c78b80-f852-11e9-9733-c543e3d4f051.png)
