### ISSUE TITLE
Fetch All Bind Variable Issue

### ISSUE THREAD

**Issue by j-coates** [dbeaver/dbeaver#7068]
#### System information: 
- Windows 7
- DBeaver version 6.2.3
- DevStyle installed (Darkest Dark Theme)

#### Connection specification:
- Oracle 11g database

#### Describe the problem you're observing:
Running a query with the default 200 rows with bind variable in the query works fine. When I click the Fetch All button, it brings the bind variables screen up again and then throws some sort of error (depending on how I'm using the bind variables). Based on the query that comes up the second time the bind variables screen appears, it looks like parts of the query are getting replaced by the value in the bind variable:

Query:
SELECT *
FROM TABLE ITL
WHERE ITL.COMPANY = :COMPANY
	AND ITL.LOCATION = :LOCATION
	AND :TEST1 = :TEST1;

First time the bind variables screen comes up:
SELECT *
FROM TABLE ITL
WHERE ITL.COMPANY = 1590
	AND ITL.LOCATION = 'STRM1'
	AND 1 = 1

After clicking fetch all:
SELECT *
FROM TABLE ITL
WHERE ITL.COMPANY = 1590ND ITL.LOCATION = 'STR'STRM1' 1 = 1

**Comment by p91paul** [comment]
I confirm this issue, quite annoying.

**Comment by bierbo** [comment]
Seems like the same bug occurs when clicking on "Excel" (with installed Office plugin)

**Comment by j-coates** [comment]
Confirmed fixed in 6.2.4
