### ISSUE TITLE
Adding "add to filter" menu item into dropdown menu of a datagrid

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#7069]
The idea is shown at the screenshot - possibility to add quick filter while browsing values in the data grid
![add_to_f](https://user-images.githubusercontent.com/11477081/67370301-172f2f80-f583-11e9-94e8-3dd5a7043c61.png)

**Comment by p91paul** [comment]
look at the filter submenu, roughly at half your context menu. It is also bound to the f11 key.

**Comment by plotn** [comment]
thank you! closing
