### ISSUE TITLE
Double compilation of declaration and body package Oracle

### ISSUE THREAD

**Issue by yevon** [dbeaver/dbeaver#7072]
#### System information: 
- Operating system (distribution) and version. Windows 10 may 2019
- DBeaver version 6.2.3
- Additional extensions
 
#### Connection specification:
- Database name and version Oracle 12.2 

#### Describe the problem you're observing:
1 - The package compilation is executed twice when you compile oracle package headers, I see two compiled successfully windows when I just persist changes once.
2 - When you compile the package  body or package header, it should only compile body, or header, not both, or have an option for choosing this behaviour. Most of the times you only compile one or another, and waiting for compiling the header is useless when you are just compiling the package body.

#### Steps to reproduce, if exist:
I have the persist dialog disabled:

![image](https://user-images.githubusercontent.com/121157/67384598-bd823180-f591-11e9-8f31-713eaceb1f5f.png)

1 - Open oracle package body, if you compile multiple times, just one compiled sucessfully window appears.
2 -  If you compile package header, the compiled successfully windows appears twice, compilation is executed twice. After that, if you compile the body, the confirmation always appear twice from here.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
vrerified
