### ISSUE TITLE
PG regex bracket expression not working

### ISSUE THREAD

**Issue by HannesMas** [dbeaver/dbeaver#7073]
#### System information: 
- Windows 10
- DBeaver version 6.2.3
- Additional extensions

#### Connection specification:
- Postgres 9.6
- PostgreSQL standard driver 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When using bracket expression in postgres regex, DBeaver requests a bind parameter instead of applying the right character class.

#### Steps to reproduce, if exist:
This one works: 
`SELECT regexp_replace('blabla errorCode":"APPLICATION_ERROR: this is not going right', '^.*errorCode":"([a-zA-Z_]*).*', '\1');`
while this one does not and used to work in previous versions:
`SELECT regexp_replace('blabla errorCode":"APPLICATION_ERROR: this is not going right', '^.*errorCode":"([[:alpha:]_]*).*', '\1');`
It's basically the same regex, only using [:alpha:] within the characters class instead of a-zA-Z

**Comment by kseniiaguzeeva** [comment]
Please tell, do you reproduce it in later DBeaver versions?  I have the same result for both expressions on version 6.2.5.

**Comment by uslss** [comment]
there is no update more than a month. Ticket closed.
If issue is still actual feel free to reopen the ticket or create a new one.
