### ISSUE TITLE
View Algorithm is reset to UNDEFINED

### ISSUE THREAD

**Issue by livedota** [dbeaver/dbeaver#7074]
#### System information: 
- windows 7 SP1
- DBeaver version: 6.2.3 CE
- Java version: 8 update 231

#### Connection specification:
- Database name and version: MySQL 8
- Driver name: com.mysql.cj.jdbc.Driver 8.0.17
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
After edited a view and then saved view algorithm is always set to UNDEFINED
#### Steps to reproduce, if exist:
Step 1: create a view with this query: CREATE OR REPLACE algorithm=merge VIEW `myview` 
AS
SELECT * FROM table1
Step 2: change the source of myview as you wish
Step 3: Save the changes
Step 4: Refresh
As you can noticed at this point the algorithm of the view is set to UNDEFINED

**Comment by serge-rider** [comment]
Thanks for the bug report!

**Comment by uslss** [comment]
verified
