### ISSUE TITLE
'Ingore' button in 'Bind parameter(s)' dialog not working as expected

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#7075]
dbeaver 6.2.3

the ignore tool tip says **ignore parameters and execute script as is**
but it doesn't work as expected: **it always replaces the key with the value**

**Comment by serge-rider** [comment]
Thanks for the bug report.
This function was broken in 6.2.3.

**Comment by kseniiaguzeeva** [comment]
Verified
