### ISSUE TITLE
Floats not displaying properly for SQL Server Connections

### ISSUE THREAD

**Issue by jhughe25** [dbeaver/dbeaver#7076]
#### System information: 
- OS: Windows 7 Pro Service Pack 1
- DBeaver version: 6.2.3
- Additional extensions: None, using default Dark theme

#### Connection specification:
- Database name and version: Multiple MS Sql Server versions (2008, 2012 and 2016)
- Driver name: Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When viewing large float data from SQL Server, the last several digits display differently than the source value. This only happens with floats (int and bigint display correctly), and does not occur on the Oracle server I have connected. I have also confirmed using MS SQL Server Management Studio that the source data is stored correctly in the database. 

I have attached pictures of a query with a known value in it where it displays a different value in the results. I've also attached my current Data Format settings for Numbers. 

Is there a setting I'm missing, or is this a different issue? I'll also add this is not new to this version of DBeaver, I've only recently noticed this due to the integration of a new database. 

![DBeaver Float Issue 1](https://user-images.githubusercontent.com/46527934/67403384-d5e95080-f57f-11e9-8c46-ab5893eb6c03.png)
![DBeaver Number Settings](https://user-images.githubusercontent.com/46527934/67403385-d681e700-f57f-11e9-949f-5c3c58e98650.png)

#### Steps to reproduce, if exist:
Storing a large ID value as a float in SQL server and display table in viewer.

**Comment by jhughe25** [comment]
I wanted to provide a quick update to this: I switched to the jtds driver and it fixed the issue. I'll leave this open for a few days in case anyone has any idea _why_ this would fix it.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report. I also can't reproduce it now. Doesn't the problem occur again?

**Comment by uslss** [comment]
there are no updates for a month. ticket closed
