### ISSUE TITLE
Multiple instances of the "Tip of the day" dialog box

### ISSUE THREAD

**Issue by WellspringCS** [dbeaver/dbeaver#7077]
#### System information: 
- Linux Ubuntu 18.04
- DBeaver version 6.2.2

#### Describe the problem you're observing:
Multiple instances of the "Tip of the day" dialog box open. One per DBeaver window. And they only close in a certain order, so it becomes like minesweeper, clicking away on any and all of them so as to figure out which one is willing to close.

The bug fix would be to open (at most) one instance of that dialog upon app open.

#### Steps to reproduce, if exist:
Re-open DBeaver when two or three windows were open on the last session.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
