### ISSUE TITLE
hangs when competing tasks collide

### ISSUE THREAD

**Issue by WellspringCS** [dbeaver/dbeaver#7078]
#### System information: 
- Ubuntu 18.04
- DBeaver version 6.2.2.201910072100	
- PostgreSQL 11.x
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Not in this case, it's a local install

#### Describe the problem you're observing:
If I run a script that opens a transaction, I find sometimes that actions elsewhere produce some kind of deadlock. Most recent example: I tried to script the DDL of a table using the right-click menu on that table in the tree -- did this while a script (wrapped in a transaction) was deleting data. The menu action produced a lock situation where I could neither get the result of the DDL request nor, indeed, even click into any window open in DBeaver. It was hung, not happy, and refused ever to come back. I did get periodic dialogs asking me if I wanted to force quit or to wait. After 15 minutes I gave up and forced the quit. This happens to me at least once a day, always when I have something running wrapped in a transaction.

#### Steps to reproduce, if exist:

I suppose one would need only to wrap a sufficiently interesting set of actions in a transaction, presumably that affect the table that one next tries to script. It is my assumption that both processes get into a deadlock, each waiting on the other before proceeding, and neither ever going to give up.

#### Include any warning/errors/backtraces from the logs

eclipse.buildId=unknown
java.version=11.0.4
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.eclipse.core.resources
Warning
Wed Oct 23 11:28:17 CDT 2019
The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

**Comment by uslss** [comment]
cannot reproduce issue for now.
if it is still reproducible for you - feel free to reopen the ticket
