### ISSUE TITLE
Ability to rename a data type via the gui

### ISSUE THREAD

**Issue by WellspringCS** [dbeaver/dbeaver#7079]
In pgAdmin it is possible to rename a data type via the gui.

This would be a nice feature to see in DBeaver. Currently I go back and forth between the two apps, because features like this can be done easily in pgAdmin but not so easily in DBeaver.

**Comment by LonwoLonwo** [comment]
Ability to rename, drop and comment data type added.

**Comment by uslss** [comment]
verified
