### ISSUE TITLE
Sql2000 open ER to report an error

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#7080]
![image](https://user-images.githubusercontent.com/26621087/67447633-119b1d80-f647-11e9-852c-f17d0114b465.png)

#### System information: 
- Operating system (distribution) and version win10
- DBeaver version  6.23
- Additional extensions 

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update more than a month. Ticket closed.
If issue is still actual feel free to reopen the ticket or create a new one.
