### ISSUE TITLE
Is there a way to make dbeaver UI readable on KDE dark mode

### ISSUE THREAD

**Issue by danielwestermann** [dbeaver/dbeaver#7082]
Hi,

I am using KDE in dark mode as my graphical user interface on Linux. The dbeaver UI looks like this and it is almost not usable:

![image](https://user-images.githubusercontent.com/13865881/67459278-7b5ffb00-f638-11e9-9c47-84c8aa822e92.png)

Is there an option (I did not find one) to make this looking better?

dbeaver version is: 6.2.3

Thanks in advance
Daniel

**Comment by nicoschl** [comment]
This is not a native fix but a workaround I use. And it is a slight pain because you have to install the plugin again after each upgrade. You can install the "DevStyle Darkest Theme" plugin from http://www.genuitec.com/updates/devstyle/ci/

**Comment by danielwestermann** [comment]
Hi Nico,

thanks for the work around, but, as you said, that seems not be a solution.

Cheers,
Daniel


________________________________

**Comment by serge-rider** [comment]
You could try to install Darkest Dark theme, on some systems it is much better. See main menu Help->Install new software->Choose "Darkest Dark Theme" in drop down.

**Comment by danielwestermann** [comment]
That is much better, thank you

________________________________

**Comment by hnavia** [comment]
> You could try to install Darkest Dark theme, on some systems it is much better. See main menu Help->Install new software->Choose "Darkest Dark Theme" in drop down.

Unfortunately, Darkest Dark Theme is not working anymore in DBeaver 21.1.0.

Everytime I install the theme, DBeaver enters in a boot loop that never ends.

**Comment by ASHspace** [comment]
> Unfortunately, Darkest Dark Theme is not working anymore in DBeaver 21.1.0.
> 
> Everytime I install the theme, DBeaver enters in a boot loop that never ends.

I am using flatpak **Version 21.1.3.202107181810** and Darkest Dark working fine.

**Comment by hnavia** [comment]
> > Unfortunately, Darkest Dark Theme is not working anymore in DBeaver 21.1.0.
> > Everytime I install the theme, DBeaver enters in a boot loop that never ends.
> 
> I am using flatpak **Version 21.1.3.202107181810** and Darkest Dark working fine.

Yeah, the solution was to install DBeaver for a single user rather than all
