### ISSUE TITLE
Table aliases autocompletion are wrong with Oracle

### ISSUE THREAD

**Issue by ZeGuigui** [dbeaver/dbeaver#7084]
#### System information: 
- Ubuntu 19.04
- DBeaver version 6.2.2.201910061950
- Additional extensions: none

#### Connection specification:
- Database: Oracle database 11g 11.2.0.3.0
- Driver name: Oracle jdbc driver 12.1.0.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When using autocomplete for table names with automatic aliases creation, the editor adds the AS keyword between table name and table alias. This syntax is not allowed by Oracle, the AS keyword should be omitted. 

#### Steps to reproduce, if exist:
Connect to an Oracle database
Use this query : `SELECT 1 FROM DUAL AS d;`
You should see the error `SQL Error [933] [42000]: ORA-00933`
Correct SQL query: `SELECT 1 FROM DUAL d`

#### Expected behavior
Either make the AS keyword insertion an option or add an option to drivers to disable the AS keyword for table aliases

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
