### ISSUE TITLE
Syntax highlighting lost for plpgsql function

### ISSUE THREAD

**Issue by danielwestermann** [dbeaver/dbeaver#7085]
Hi, 

just installed dbeaver 6.2.3 on Linux. The actual code in a plgsql functions appears as a comment now:

![image](https://user-images.githubusercontent.com/13865881/67468088-32b13d80-f64a-11e9-9031-c56e0367cd71.png)

Would be great to have syntax highlighting back for the actual code of functions.

Thanks in advance
Daniel

**Comment by uslss** [comment]
Duplicate.
Fixed in scope of #7050
