### ISSUE TITLE
SQL Error [42601]: Unterminated string literal started at position

### ISSUE THREAD

**Issue by plvnv** [dbeaver/dbeaver#7086]
#### System information: 
- Macos Catalina
- Dbeaver 6.2.3

#### Connection specification:
- Postgres Professional 11.4
- Java JDBC 4.1 (JRE 7+) driver for PostgreSQL database (42.2.8.jre7)

#### Describe the problem you're observing:
Can't generate sql with semicolon:
 
select 'time:'||current_timestamp||';'

Error:
SQL Error [42601]: Unterminated string literal started at position

**Comment by masebu** [comment]
Hi,

I have the same error on 6.2.3 / Windows10 with an Oracle connection: statement parsing is broken.
It shows well in the bind dialog.

6.2.2 was okay.

![image](https://user-images.githubusercontent.com/19706602/67558048-85f0c200-f716-11e9-9d15-4606eb2d6799.png)

![image](https://user-images.githubusercontent.com/19706602/67558080-943ede00-f716-11e9-8027-32c2c138579e.png)

regards,

**Comment by uslss** [comment]
We released hotfix version with the fix (6.2.3.201910211155).
So you can just download 6.2.3 version once again. The mentioned issue should be fixed there
