### ISSUE TITLE
App closes when connecting remotely 

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#7088]
Me and my team mmates noticed app closes when Im starting remote session (Windows / RDP)
It might be related with resolution change

**Comment by kseniiaguzeeva** [comment]
@maciey thank you for the bug report. Similar issues are described in #5872 and #6407

**Comment by maciey** [comment]
Closing as duplicate. Further discussion on: https://github.com/dbeaver/dbeaver/issues/5872
