### ISSUE TITLE
MongoDB, Grid view, title row shifted relative content rows 

### ISSUE THREAD

**Issue by foal** [dbeaver/dbeaver#7090]
## System information: 
- Windows 10 v.1903 (b. 18362.10024)
- DBeaver EE Version 6.2.0.201909220738
- nothing

#### Connection specification:
- MongoDB 3.6.3
- Driver name: MongoDB Java Driver [3.11.0]
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
title row shifted relative content rows 
![image](https://user-images.githubusercontent.com/458209/67547103-6e0d4400-f6fe-11e9-80a2-b30c493bdba2.png)

#### Steps to reproduce, if exist:
Open table with complicate structure, move to the end

#### Include any warning/errors/backtraces from the logs
Nothing, it is a visual issue

**Comment by uslss** [comment]
Unfortunately, I cannot reproduce the issue. Probably you can add some additional info that could be helpful?

**Comment by foal** [comment]
I found the place there shift starts
![image](https://user-images.githubusercontent.com/458209/67561922-0666f100-f71e-11e9-8711-9b3aad5ccd91.png)

The whole broken header (the ent is out of the screen. Is the same as on the first image) 
![image](https://user-images.githubusercontent.com/458209/67562644-6e6a0700-f71f-11e9-8dec-2e59aa37ea2d.png)

**Comment by uslss** [comment]
Reproduced against 7.2.0 EA
collection db1.qa.123
![image](https://user-images.githubusercontent.com/31996417/89194838-950f7500-d5b0-11ea-9c2a-5db88b002db6.png)

**Comment by serge-rider** [comment]
Seems to be fixed. Can't reproduce anymore.

**Comment by uslss** [comment]
seems that not all "columns" are shown in grid view for now
![image](https://user-images.githubusercontent.com/31996417/90625315-09d5e680-e222-11ea-843d-826c73dc5fda.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
