### ISSUE TITLE
Function / Procedure drill down

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#7093]
I love drill down options for view and tables (CTRL+Click)
Cant you do same with functions ?

Im using PostgreSql

**Comment by maciey** [comment]
Would this be possible ?
WIll help a lot...

**Comment by maciey** [comment]
No hope for this ?

**Comment by maciey** [comment]
bump ...

**Comment by maciey** [comment]
Hello is it possible to implement that ?
If you can do that for tables / views - why not stored procedures ?

**Comment by maciey** [comment]
I still do miss that functionality ... :(

**Comment by maciey** [comment]
Is that really so difficult yo implement ?

functions suggestions and drill down possibility is what I miss most in this tool.

**Comment by serge-rider** [comment]
Sorry, missed this ticket.

It shouldn't be too hard to implement.

**Comment by serge-rider** [comment]
Generally we already support this feature for PostgreSQL:
![image](https://user-images.githubusercontent.com/6398845/102018259-5d45e480-3d7d-11eb-9b48-d3a87118c56a.png)

Work on cltl+click.
Could you write a bit more details about the issue and about your envionment?

**Comment by maciey** [comment]
Oh actually this started working ! 
Not sure this is change in recent versions or something was refreshed - but Im sure this didnt work on time ive written post(s)

Anyway - MANY thanks - Im so happy having this working.
Dbeaver is so great tool 

My env:
pg 12 / pg 9.6 hosted on Linux
Dbeaver works on Windows 10
