### ISSUE TITLE
Missing Procedure, Function

### ISSUE THREAD

**Issue by nouchutm** [dbeaver/dbeaver#7096]
Hi Team,

I am facing problem in DBeaver which not showing all procedure & Function from schema.

In Oracle SQL Developer, I am able to see many procedure but the same schema in DBeaver not showing.

Regards,
Noushad

**Comment by mstup** [comment]
I have faced with the same issue for Postgres 9.4
Ctrl+Shift+D shown the function by partial name. After that I pressed **Enter** to move to the definition and nothing has happened (even no errors in **Errors Log** view). 

DBeaver: 7.0.4
JVM: Oracle 1.8.0_141
OS: Fedora 26

**Comment by uslss** [comment]
@nouchutm is it still actual against 7.2.2?

**Comment by mstup** [comment]
For me on Postgres this problem still exist. I see my procedure in the list, but there are nothing happened after press on OK button. Just popup dialog gone.
![pg](https://user-images.githubusercontent.com/16793676/95458396-17fdd480-0940-11eb-920c-91ac936e3053.png)

**Comment by uslss** [comment]
cannot reproduce it against 7.2.4.
What OS do you use?

**Comment by mstup** [comment]
I don't see the any changes on version 7.2.4.
The same behavior as I described.
Bug still exist!

**Comment by mstup** [comment]
OS in the same as in the initial message.

**Comment by serge-rider** [comment]
Can't reproduce. Maybe it is OS-specific or database specific.
@mstup could you check error logs for any related messages/warnings? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by p91paul** [comment]
I usually get this on Oracle if I:

1. Load the list of tables/proc/func in the database navigator
2. Create a new object with sql
3. Search it with ctrl + d

And I "fix" it by reloading the list of objects in the db navigator, so that it shows there. When the table is present in db navigator, ctrl + d opens it, otherwise it doesn't. Maybe it can be reproduced if the table/proc/function is hidden by a filter?

I am referring to the issue raised by @mstup, which is entirely different from the original @nouchutm one.

**Comment by nouchutm** [comment]
Hi @p91paul ,

Still SQL Developer we can see those procedure and function. The issue happen while access in production db, I have developer permission, i cannot able execute those procedure or Function in SQL Developer, only i can view the procedure or function.

Regards,

**Comment by p91paul** [comment]
@nouchutm for your issue you can very likely solve it by enabling this option in connection properties:
![immagine](https://user-images.githubusercontent.com/2157006/107574881-74734800-6bef-11eb-970d-00944363a7b8.png)

DBA_* views (es DBA_TABLES) allow you to see object which you have no GRANTS over. They are also faster to query; however, Oracle requires some specific system grants to access them which not all users have, so dbeaver defaults to ALL_* views for reading objects.

**Comment by nouchutm** [comment]
Great! Thank you so much :). 
its working now

**Comment by mstup** [comment]
> Can't reproduce. Maybe it is OS-specific or database specific.
> @mstup could you check error logs for any related messages/warnings? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

There are nothing in log files that could be related to this issue.
