### ISSUE TITLE
Query run time does not shown after query without resultset

### ISSUE THREAD

**Issue by Hubbitus** [dbeaver/dbeaver#7097]
#### System information: 
- Operating system (distribution) and version: Fedora Linux 31
- DBeaver version: 6.2.3
- Additional extensions: no

#### Connection specification:
- Database name and version: Postgres, but I hope it irrelevant

#### Describe the problem you're observing:
Normally DBeaver show time run query progress like:
![image](https://user-images.githubusercontent.com/720349/67662264-15df7780-f974-11e9-8b07-bea8539cfd49.png)

But if you run that after query which does not return any value, there only button `Cancel` appeared! Without timing (f.e. `SET statement_timeout TO 0`):

![image](https://user-images.githubusercontent.com/720349/67662810-31974d80-f975-11e9-9a2a-a81d887e1da0.png)

Please compare with traditional flow, said after `SELECT 1`:

![image](https://user-images.githubusercontent.com/720349/67662708-f9900a80-f974-11e9-8202-83c8c665a34c.png)

**Comment by uslss** [comment]
cannot reproduce it for now.
if it is still actual for you - feel free to reopen the ticket
