### ISSUE TITLE
Edit Connection is affected by previous Edit connection, and no longer possible until restart

### ISSUE THREAD

**Issue by gngchrs** [dbeaver/dbeaver#7098]
#### System information: 
- MacOS Catalina version 10.15 (19A602)
- DBeaver Version Version 6.2.3.201910211155
- Additional extensions - N/A

#### Connection specification:
- Postgres 10
- Driver name 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I duplicated a connection by copying and pasting so that I can edit the connection for a new connection to a postgres database. 

However, it seems the `Edit Connection` dialog affects the next scenario it will be open, and If I leave it in the General Settings, area, I can no longer edit the connection settings, since I cannot see the settings. 

#### Steps to reproduce, if exist:
1. Create a connection. (I used postgres).
2. Duplicate the connection through copy and paste. 
<img width="337" alt="Screen Shot 2019-10-28 at 10 14 58" src="https://user-images.githubusercontent.com/3910877/67666766-c77aaa80-f96c-11e9-9cbb-20702a12ce21.png">
3. Edit the first postgres connection (Right click > edit connection), but leave the sidebar at the General (In the left navbar), and save.
<img width="1515" alt="Screen Shot 2019-10-28 at 10 15 17" src="https://user-images.githubusercontent.com/3910877/67666810-d9f4e400-f96c-11e9-967c-c195c3c5b5c9.png">
4. Now go to edit second connection.
<img width="623" alt="Screen Shot 2019-10-28 at 10 15 35" src="https://user-images.githubusercontent.com/3910877/67666932-19233500-f96d-11e9-859c-425217f307f4.png">
5. Notice the left sidebar start at the general section where it was left. And you cannot scroll. It's like part of the sidebar menu has dissapeared. 

<img width="1170" alt="Screen Shot 2019-10-28 at 10 15 46" src="https://user-images.githubusercontent.com/3910877/67666984-335d1300-f96d-11e9-8cae-0f09fa76f890.png">

I am only able to get the whole menu back after a restart.

**Comment by uslss** [comment]
cannot reproduce it anymore.
if issue is still actual for you - feel free to reopen the ticket
