### ISSUE TITLE
Ampersands are stripped out of results tooltips

### ISSUE THREAD

**Issue by sauntimo** [dbeaver/dbeaver#7101]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro v1903 build 18362.418
- DBeaver version: 6.2.3.201910191000
- Additional extensions: n/a

#### Connection specification:
- Database name and version:  PostgreSQL 9.6.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
- Driver name:  org.postgresql:postgresql:RELEASE [42.2.5] net.postgis:postgis-jdbc:RELEASE [2.2.1]
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Ampersands do not show up in tooltips
![image](https://user-images.githubusercontent.com/2720466/67674400-46271600-f974-11e9-90f1-fecf4bf4f038.png)

![image](https://user-images.githubusercontent.com/2720466/67674498-87b7c100-f974-11e9-9f04-c0f7dce5fed4.png)

#### Steps to reproduce, if exist:
- Run a query which returns a text field which contains an amerpsand but is longer than the width of the column in the results
```sql
SELECT '..........................&';
```
- Tooltips with column content only show when the content is longer than the column is wide so 
```sql
SELECT '&';
```

probably won't let you view the error as there won't be a tooltip

#### Include any warning/errors/backtraces from the logs
n/a visual error

**Comment by serge-rider** [comment]
SWT has special trick about this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=188271
Thanks for the bug report. Fixed

**Comment by uslss** [comment]
verified
