### ISSUE TITLE
Snowflake: SCIM Protocol support

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#7103]
Docs: https://docs.snowflake.net/manuals/user-guide/scim-intro.html

Maybe this shouldn't be just Snowflake-specific.

**Comment by LonwoLonwo** [comment]
So, SCIM is a System for Cross-domain Identity Management.
SCIM provides a defined schema for representing users and groups and a RESTful API to run CRUD operations on those user and group resources.
The goal of SCIM is to securely automate the exchange of user identity data between your company's cloud applications and any service providers, such as enterprise SaaS applications.

SCIM can be used with Okta or Azure or custom in Snowflake. You can configure SCIM and use it with an external browser and SSO authentications in DBeaver.

Also, I do not see a special section for SCIM here https://docs.snowflake.com/en/user-guide/jdbc-configure.html

And I do not see any functional approach to using SCIM as an authentication way with JDBC and DBeaver.

https://developer.okta.com/docs/concepts/scim/
https://docs.snowflake.com/en/user-guide/scim-okta.html
https://docs.snowflake.com/en/user-guide/scim-intro.html
