### ISSUE TITLE
DDL for Materialized View is showing as Table

### ISSUE THREAD

**Issue by andrewwellsdfj** [dbeaver/dbeaver#7104]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version Oracle 11g
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Materialized views are showing in the list for table. When you click on them to show the declaration, the ddl is incorrect and shows a table DDL instead of a materialized view.
#### Steps to reproduce, if exist:
create a materialized view, double click on the object ( in the table list instead of the materialized view list). It will show an incorrect DDL statement

**Comment by kseniiaguzeeva** [comment]
Unfortunately cannot reproduce. Is it still actual for you?

**Comment by uslss** [comment]
thanks for the bug report
![image](https://user-images.githubusercontent.com/31996417/79872031-ede64380-83ed-11ea-8753-76da5857f363.png)

**Comment by serge-rider** [comment]
Fixed (we need to use DBMS_METADATA proc instead of ALL_MVIEWS for DDL.

**Comment by uslss** [comment]
declaration is shown incorrectly
![image](https://user-images.githubusercontent.com/31996417/80584977-34095b80-8a1b-11ea-88ae-a8af9b4deb7e.png)

**Comment by serge-rider** [comment]
It is server-side issue (it is out of memory). Try another Oracle server.

**Comment by uslss** [comment]
verified

**Comment by fernandodelvalle** [comment]
Sorry to bother with this closed issue, but I'm having this troubble with last public version 23.0.0 and also previous version 22.3.3 (my first use of dbeaver).  Database is Oracle 19c (exact version 19.16.0.0.0).  I'm in a developement environment, where my user has granted DBA permissions.  In others database tools like Toad or sqldeveloper correctly presents both options (table or mat-view) when ctrl-clicking the objects, or when traversing dependencies show mat-view, and then it can extract dll correctly.

example when viewing with sqldeveloper
![image](https://user-images.githubusercontent.com/7956997/225899856-6d914593-5823-495c-9c2d-d786ab779d16.png)

example with dbeaver:
![image](https://user-images.githubusercontent.com/7956997/225900205-b7317d1f-3577-4ba4-98f4-49b3a7b3bb1f.png)

whe have created a normal view PMX_EMPLEADOS which inside has a mat-view PMX**VM**_EMPLEADOS.  In dbeaver only shows dependency to the snapshot table of mat-view, so there's no way to access that object and it's DDL.

in a select from all_objects you can see there's a public synonym, and both mat-view and snapshot table
![image](https://user-images.githubusercontent.com/7956997/225900822-847f01f6-b833-4e94-88a1-2ea6e1b8f87a.png)

I wanted to recheck with you before cloning/reopening this issue
