### ISSUE TITLE
Why isn't it displaying Generate SQL for some tables?

### ISSUE THREAD

**Issue by okwie** [dbeaver/dbeaver#7105]
#### System information: 
- Operating system (distribution) and version
Windows 7 Persistent
- DBeaver version
6.1.4
#### Connection specification:
- Database name and version
IBM iSeries, DB2
#### Describe your question:
All of my coworkers have the generate SQL option when they right click on an entry, however, it isn't giving me the option to generate SQL (as seen in the picture attached). I don't understand why it won't work for me but everyone around me who has the same access as myself is able to generate SQL. Either way it's becoming quite inconvenient and there is no explanation anywhere online for this exact issue.
![nogeneratesql](https://user-images.githubusercontent.com/51001828/67692771-aca93580-f96e-11e9-9900-0f9b8ce61b31.png)

**Comment by uslss** [comment]
is it still actual?

**Comment by 13pass** [comment]
Still an issue for me:

System information:
Operating system (distribution) and version
uname -a 
Linux tuctuco 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
DBeaver version
6.3.3
Connection specification:
Database name and version
PostgreSQL and MySql8+

**Comment by uslss** [comment]
cannot reproduce an issue for now.
If it is still actual for you - feel free to reopen the ticket
