### ISSUE TITLE
DB metadata search does not remember all object types

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#7106]
dbeaver 6.2.3

when doing a metadata search not all selecting object types are restored when opening the search window again.

e.g. if all items were selected, only these are selected when the search window is opened again

HANA: ![grafik](https://user-images.githubusercontent.com/25850372/67708771-ffa9d980-f9bc-11e9-9822-3e3210732539.png)
Sql-Server: ![grafik](https://user-images.githubusercontent.com/25850372/67708813-13edd680-f9bd-11e9-999e-ce8db58af475.png)
...

Looks like items returned by ...StructureAssistant.getSupportedObjectTypes internally using the same object type are only counted once

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce in 6.3.5. Could you try the latest DBeaver version?
If it still reproduces, please tell your OS.

**Comment by kai-morich** [comment]
issue is solved
