### ISSUE TITLE
Version 6.2.3 - PostgreSQL $$ handling is broken

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#7107]
The changes to the $$ handling seem to have broken the standard behaviour.

In PostgreSQL $$ or anything like $anything$ is used as a replacement for single quotes.

After the update to 6.2.3. the simple following anonymous codeblock is not executed:

```
do
$$
begin
	raise notice 'test';
end
$$
;

SQL Error [42601]: Unterminated dollar quote started at position 4 in SQL end
$$
. Expected terminating $$
```

Putting something between $$ like e.g. $f$ makes the statement work:

```
do
$f$
begin
	raise notice 'test';
end
$f$
;
```

Many standard PostgreSQL scripts rely on the $$ for quotation, so this can hopefully be fixed as soon as possible.

Greeting
James

**Comment by uslss** [comment]
Duplicate.
Fixed in the scope of #7050
