### ISSUE TITLE
Mysql tinyint(1) is exported as tinyint(4)

### ISSUE THREAD

**Issue by mfrascati** [dbeaver/dbeaver#7108]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 6.2.3
- Additional extensions

#### Connection specification:
- Database name and version Mysql 8
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  

#### Describe the problem you're observing:
When syncing dev and production db with Export data -> Database, fields that on the original schema are declared as TINYINT(1) UNSIGNED are imported on destination as TINYINT(4) UNSIGNED.
This creates problems with frameworks as the boolean type mapping of the first one is different from the integer type of the second.

#### Steps to reproduce, if exist:
create a table, add a tinyint(1) unsigned column, export data and import on another database

#### Include any warning/errors/backtraces from the logs

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report. While you can correct it manually in Tables mapping  as workaround.
![lmjA8TChDJ](https://user-images.githubusercontent.com/51405061/68574939-17349800-047c-11ea-8869-de7a37cf7689.png)

**Comment by serge-rider** [comment]
In fact it was mapped into tinyint without modifiers. Which stands for tinyint(4).
Fixed (now we use exacly the same data type when transfering between datasources of the same type)

**Comment by uslss** [comment]
verified
