### ISSUE TITLE
Missing info about number of updated rows in execution log

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#7109]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 6.2.3.201910191000
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle 12c

#### Describe the problem you're observing:

Execution log does not contain number of updated rows while this info is available in _Statistics_ tab.

![obraz](https://user-images.githubusercontent.com/20753183/67751835-222a0a00-fa32-11e9-97ae-542842be450c.png)

![obraz](https://user-images.githubusercontent.com/20753183/67751726-f73fb600-fa31-11e9-8727-72ba797f83c1.png)

**Comment by uslss** [comment]
cannot reproduce it anymore.
if it is still actual for you - feel free to reopen the ticket
