### ISSUE TITLE
JDBC driver is missing

### ISSUE THREAD

**Issue by devopsdymyr** [dbeaver/dbeaver#7110]
JDBC driver is not avaliables in 
![image](https://user-images.githubusercontent.com/41105507/67755214-c07f9500-fa5d-11e9-98f6-234066b28c5f.png)

#### System information: 
- windows 10
- DBeaver version 6.2.3

#### Connection specification:
- Database name -  db2
- Driver name 

I have deployed my db2 server in aws using db2 aws marketplace ami and able to login to db2 and tested with sample database.
![image](https://user-images.githubusercontent.com/41105507/67755398-13f1e300-fa5e-11e9-8fa0-7931e6843fee.png)

then i want to test connection from dbeaver gui tool getting jdbc missing error

**Comment by devopsdymyr** [comment]
if you have any documentation for get JDBC from IBM and connect db2 from dbeaver.

I am stuck to find JDBC driver in IBM web

**Comment by uslss** [comment]
probably you could find something helpful [there](https://www.ibm.com/support/pages/db2-jdbc-driver-versions-and-downloads)
