### ISSUE TITLE
RAW(16) does not show up properly in oracle 11g

### ISSUE THREAD

**Issue by andrewwellsdfj** [dbeaver/dbeaver#7112]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Raw(16) datatype does not show up properly in dbeaver 6.1
#### Steps to reproduce, if exist:
create table dropme (a int,b raw(32) default sys_guid(), c raw(16) default sys_guid()); 
insert into dropme(a) values(1); 
select * from dropme;

**Comment by serge-rider** [comment]
DBeaver supports different binaries representation.
If you need to see it as hex you can switch presentation in preferences:
![image](https://user-images.githubusercontent.com/6398845/81212641-d4441f00-8fdd-11ea-9995-d7b85a5d5094.png)
