### ISSUE TITLE
Are there plans to support DynamoDB from Amazon?

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#7113]
DBeaver - Version 6.2.3 CE
Operating System: Windows 10
JDBC Driver: mssql-jdbc 7.0.0.jre10
Database: Microsoft SQL Server Database

@serge-rider : Does Dbeaver have any plans to support DynamoDB from AWS ?

**Comment by serge-rider** [comment]
We already support DynamoDB in DBeaverEE.
There are no plans to implement it in CE in near future. 

There are many reasons why. One of them is big number of dependencies one AWS SDK (bigger than DBeaver CE distribution itself).

**Comment by dinmukhamed09** [comment]
@serge-rider Hi! It would be greate to support AWS DynamoDB in DbeaverCE. 

Is it possible that you will come back to this issue?

I really like your software. I wouldn't like to install other IDE to work with DynamoDB.
