### ISSUE TITLE
Ordering in Grouping panel not applied after refresh

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#7116]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 6.2.3.201910191000
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle 12c
- Driver name: Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Ordering in _Grouping_ panel is not applied after refreshing data in table.

Here is how it looks when I set ordering manually:

![obraz](https://user-images.githubusercontent.com/20753183/67847773-b617d680-fb03-11e9-9491-e40343d8493f.png)

And here is how it looks just after refreshing table data (_not_ grouping panel):

![obraz](https://user-images.githubusercontent.com/20753183/67847758-adbf9b80-fb03-11e9-949f-d26247f655f3.png)

Notice that ordering indicator is still shown.

#### Steps to reproduce

1. Open some table
2. Set some grouping columns
3. Sort by some column in _Grouping_ panel
4. Refresh table data (_not_ data in grouping panel)

**Comment by serge-rider** [comment]
Thanks for the bug report.
Fixed

**Comment by uslss** [comment]
verified
