### ISSUE TITLE
Confirmation Dialog and button focus on table drop

### ISSUE THREAD

**Issue by RepoNico** [dbeaver/dbeaver#7117]
When you try to drop a table with DBeaver a confirmation dialog is shown: on this dialog, the focus is set on "Yes" button.
To prevent accidental confirmation, for expample hitting "Canc" and "Enter" in sequence on the keyboard, the focus should be set on "No" button.
This could be a good practice on all confirmation dialog related to important operation such as schema modification or massive data deleting.

**Comment by uslss** [comment]
Already implemented
