### ISSUE TITLE
Parameter input issue

### ISSUE THREAD

**Issue by goodale** [dbeaver/dbeaver#7121]
I have a SQL statement in which I'd like DBeaver to prompt me for several parameters;  an integer and several dates.   The integer prompts work just fine using a variable such as :xyz.    But the date parameters do not work and instead DBeaver throws an error 

The SQL looks like... .... to_days(b.someDate) between to_days(:from) and to_days(:to)

I'd like DBeaver to prompt me for :from and :to 

Note: in Editors/SQL Editor/SQProcessing I have all of these options checked:
1. Enable SQL parameters
2. Anonymous SQL parameters
     Anonymous parameter mark: ?
     Named parameter mark : 
3. Enable parameters in DDL
4. Enable variables

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce in 7.0.4. Is it still actual for you?

**Comment by goodale** [comment]
It works now.  however, it does require wrapping the date with single-quotes.  I would expect DBeaver to 'know' the field is a date and to wrap the value as appropriate (similar to the way you pass a date object to a preparedStatement and don't pass it a string version of  a date surrounded with single-quotes
