### ISSUE TITLE
Connect Mac to SQL Server using Windows Authentication

### ISSUE THREAD

**Issue by b-upah** [dbeaver/dbeaver#7122]
I'm trying to connect to SQL Server using Windows Authentication from the CE version of DBeaver on a Mac. I'm getting a "This driver is not configured for integrated authentication" error when trying to connect. I realize that a Mac won't have the native Windows libraries, but would imagine this can still be done. I've tried adding domain and useNTLMv2 as User Properties to the Driver itself, but that does not seem to be fixing it. Any ideas?

**Comment by coopr** [comment]
Check that these version numbers match:
![FXIOC-PROD-PER-VDI](https://user-images.githubusercontent.com/94904/85170874-de834b00-b222-11ea-953a-bdedaa2f02bc.jpg)
