### ISSUE TITLE
Metadata Panel not showing visible text, but it is still 'copyable' (azure sql server)

### ISSUE THREAD

**Issue by dhorrall** [dbeaver/dbeaver#7123]
#### System information: 
- Operating system (distribution) and version
- DBeaver version  6.2.3.201910211155
- Additional extensions

#### Connection specification:
- Database name and version: Azure MS SQl Server
- Driver name: Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
In the Metadata panel, very recently, the text is not visible after running a query, but I can COPY it as if it was there and as I click around the 'empty' metadata list, the columns in the result set are highlighted.  So, something is there in the MetaData panel, but the text is not visible.
![dbeaver_meta_data_missing](https://user-images.githubusercontent.com/22561698/67887743-3e0cd900-fb22-11e9-8b5b-83ae0b773350.png)

**Comment by serge-rider** [comment]
I saw it once but can't reproduce anymore.

**Comment by dhorrall** [comment]
Is there any type of Meta-Data cache I could try clearing?

**Comment by dhorrall** [comment]
More info in case I forgot to mention.  This seems to happen with Azure SQL Server databases.  It doesn't happen with on-prem SQL server

**Comment by uslss** [comment]
there is no update on ticket for a long time. and cannot reproduce.
if it is still actual for you - feel free to reopen the ticket.
