### ISSUE TITLE
Grid column sorting icons overlaps name in "calculate column width by cell values"

### ISSUE THREAD

**Issue by Hubbitus** [dbeaver/dbeaver#7125]
#### System information: 
- Operating system (distribution) and version: Fedora Linux 31
- DBeaver version: 6.2.3
- Additional extensions: no

#### Connection specification:
- Database name and version: Postgres

#### Describe the problem you're observing:
When option `Preferences` ➜ `Database` ➜ `Editors` ➜ `Data editor` ➜ `Presentation` ➜ `calculate column width by cell values` enabled results grid looks like:
https://github.com/dbeaver/dbeaver/issues/new?
![image](https://user-images.githubusercontent.com/720349/67926027-fd669b80-fbc5-11e9-877f-69354bb3c70b.png)

There are several issues:
1. Icons for sorting results overlaps column names
2. Columns width often less than name of column

I suggest:
1. Icons make not persistent and just show on column header hover (to do not waste space in header). Possibly configurable.
2. Add sub-option like `calculate column width by cell values - not less than column name width`

**Comment by serge-rider** [comment]
This is not a bug. Main idea of this option is to exclude column names from column width calculation.
It makes sense in databases which have very long column names (by some historical reasons).
Column name tail will be cut (and probably overlapped by sort icons).

**Comment by Hubbitus** [comment]
Strange. It is very useful adjust column width by content to do not just have useless horizontal scrolling!! It may be cool feature (I have used "Always adjust column width" in Squirell SQL and it works very well). Why you speak only about old databases?
