### ISSUE TITLE
Ubuntu repo out of date

### ISSUE THREAD

**Issue by LorisZ** [dbeaver/dbeaver#7126]
I installed dbeaver over the ubuntu repo and everytime I start dbeaver I get notified of a new update, but it won't update with apt.

My system: Kubuntu 18.04 (amd64)
apt source: http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu bionic main

I've seen this happen before with hotfixes, but the minor and patches usually get updated reasonably fast, but I'm still on 6.2.2 and get notified about 6.2.3 on every start.

Thanks for the great software, keep it up (to date ;)).

**Comment by serge-rider** [comment]
Thanks for the bug report. We'll fix it with 6.2.4 release

**Comment by mbnoimi** [comment]
Currently it's out of date again.

**Comment by LorisZ** [comment]
This keeps happening. Honestly not that big of a problem, that I'm a version behind for a little bit, but every time I open DBeaver I get a notification about an update that I might want to download...

But I don't really care about downloading updates, when it should be taken care of by an apt upgrade...
