### ISSUE TITLE
"Open Database Object..." (Shift + Ctrl + D) won't open synonym objects

### ISSUE THREAD

**Issue by andrzejdziekonski** [dbeaver/dbeaver#7127]
As in the topic. While using "Open database object" search engine for my MSSQL database objects, option "Synonym" founds correctly tables that are marked as synonyms. But When you try to "open" them - nothing happens.

Would be great to be able to open the synonym table if you already managed to find them ;)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
