### ISSUE TITLE
Data Editor: History navigation

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7132]
**Step 2 Fail** of Data Editor:
Clicking (in Data view tab of MySQL) <kbd>Ctrl+Left</kbd> or <kbd>Ctrl+Right</kbd> doesn't switch filter history - switch rows- upper and below

**Comment by kseniiaguzeeva** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D5. Do not remove or edit.` [D5](https://dbeaver.testquality.com/project/8805/result/1592263/defect/5720)

**Comment by uslss** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D6. Do not remove or edit.` [D6](https://dbeaver.testquality.com/project/8805/result/1593138/defect/5721)

**Comment by uslss** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D13. Do not remove or edit.` [D13](https://dbeaver.testquality.com/project/8805/result/1594500/defect/5728)

**Comment by serge-rider** [comment]
In fact navigation works but with other shortcuts. You can see them in main/context menu Navigate (navigate forward/backward history).
So the problem is in incorrect shortcut for nav tool elements.

**Comment by kseniiaguzeeva** [comment]
Alt+Left, Alt+right work correctly
