### ISSUE TITLE
Default values are displayed not properly

### ISSUE THREAD

**Issue by renyxadarox** [dbeaver/dbeaver#7133]
**System information:** 
- Windows 7 (64-bit) Build 7601 (Service Pack 1)
- DBeaver 6.2.0.201909081341

**Connection specification:**
- PostgreSQL 10.9
- PostgreSQL JDBC Driver 42.2.0.jre7

**Describe the problem you're observing:**
Default values of function peremeters are diplayed for wrong parameters

**Steps to reproduce, if exist:**
Create a function with IN parameter and default value + any OUT parameter
Default value for IN parameter is displayed against OUT parameter. For example:
```
CREATE OR REPLACE FUNCTION public.test(p_in boolean DEFAULT false, OUT p_out integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
begin
	p_out := 0;
end;
$function$;
```
Look at Function parameters Tab, you'll see:
```
Name   Parameter Type  Parameter Kind  Ordinar position  Default
p_in   bool            IN              1                 
p_out  int4            OUT             2                 false
```

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
