### ISSUE TITLE
ODBC Connection Selector

### ISSUE THREAD

**Issue by Dogeron** [dbeaver/dbeaver#7136]
Add button to ODBC connection wizard to allow user to select  Database/Schema by reading defined/available ODBC connections.

Would be especially helpful to new Windows users as will only list the correct 32/64 bit ODBC connections that match the version of DBeaver being used.

**Comment by ShadelessFox** [comment]
This feature is available in PRO products:
https://dbeaver.com/docs/dbeaver/ODBC-JDBC-Driver/#creating-odbc-connections-in-dbeaver
