### ISSUE TITLE
Misalignment between arrows direction in Custom filters window and Data Grid

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7137]
#### System information:

- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.4

#### Describe the problem you're observing:

If I order some column DESC, than arrow in Custom filter window will be pointed up and at Column Header in Data Grid it will be pointed down. The same thing with ASC order.<br>

![image](<https://user-images.githubusercontent.com/31996417/68026088-9c22f300-fcbf-11e9-8729-e193c557d5ff.png>)

**Comment by uslss** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D7. Do not remove or edit.` [D7](https://dbeaver.testquality.com/project/8805/result/1593141/defect/5722)

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D25](https://dbeaver.testquality.com/project/8805/result/1743880/defect/6051). Do not remove or edit.

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D38](https://dbeaver.testquality.com/project/8805/result/1760359/defect/6092). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D41](https://dbeaver.testquality.com/project/8805/result/1760955/defect/6095). Do not remove or edit.

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D65](https://dbeaver.testquality.com/project/8805/result/1761111/defect/6121). Do not remove or edit.

**Comment by austin-beer** [comment]
I've verified that this is still a bug in DBeaver 7.0.0. It was quite confusing at first, until I figured out what was going on.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
