### ISSUE TITLE
NPE appears after changing active datasource [D8]

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7138]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.4

#### Describe the problem you're observing:
Npe appears when I switch in SQL editor from current DB (e.g. hana) to another (e.g. PostgreSQL) and back to first DB (hana). The issue has no affection for UI
#### Steps to reproduce, if exist:
1. Execute some script
2. Change datasource to another (e.g. Hana - PostgreSQL)
3. Try to execute script - get error that item doesn't exist
4. Switch back to the previous DB - try to execute the script. - The script is successfully executed, but there is NPE in Error log
[npe_changedatasource.log](https://github.com/dbeaver/dbeaver/files/3798444/npe_changedatasource.log)

**Comment by uslss** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D8. Do not remove or edit.` [D8](https://dbeaver.testquality.com/project/8805/result/1593177/defect/5723)

**Comment by serge-rider** [comment]
Already fixed in some previous commit.

**Comment by uslss** [comment]
verified
