### ISSUE TITLE
SAP Hana: Column couldn't be added

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7139]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.4

#### Connection specification:
- Database name and version SAP Hana

#### Describe the problem you're observing:
The column cannot be added using UI
#### Steps to reproduce, if exist:
1. Create column in already created Table
2. Try to save changes - Error Appears.
Generated SQL: ALTER TABLE TESTDB.NEWTABLE_1 ADD COLUMN3 VARCHAR(100); - Fails
SQL that works ALTER TABLE TESTDB.NEWTABLE_1 ADD (COLUMN3 VARCHAR(100))
[error_column.txt](https://github.com/dbeaver/dbeaver/files/3799020/error_column.txt)

**Comment by uslss** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D9. Do not remove or edit.` [D9](https://dbeaver.testquality.com/project/8805/result/1593210/defect/5724)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
