### ISSUE TITLE
SAP Hana: Incorrect behavior with FK's On Delete/On Update actions [D11]

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7141]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.4

#### Connection specification:
- Database name and version SAP Hana

#### Describe the problem you're observing:
1. On Delete/On Update option could be Set only to Restrict. If other values are chosen - FK creation fails,
2. If No Action are chosen for both options after FK saving they are transformed to Restrict
![image](https://user-images.githubusercontent.com/31996417/68046214-66483380-fcec-11e9-8dc2-2b3492f9e728.png)

**Comment by uslss** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D11. Do not remove or edit.` [D11](https://dbeaver.testquality.com/project/8805/result/1593213/defect/5726)

**Comment by kai-morich** [comment]
not reproducible with dbeaver 7.0.2 + HANA 2SPS04

All options except 'No Action' work as expected. There is no 'No Action' in HANA, if nothing is specified the default is 'Restricted'.

By providing a HANA specific ForeignKeyConfigurator class, the 'No Action' could be removed from DBSForeignKeyModifyRule list. Is there a simpler solution to remove this value?
