### ISSUE TITLE
SAP Hana: Unique index couldn't be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7142]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.4

#### Connection specification:
- Database name and version SAP Hana

#### Describe the problem you're observing:
The unique checkbox is ignored when trying to create Unique index
#### Steps to reproduce, if exist:
1. Start index creation
2. Check Unique option and needed column
3. Save index - check index properties - it is unchecked
![unique_index](https://user-images.githubusercontent.com/31996417/68046506-1ae25500-fced-11e9-963c-0b3526800324.gif)

**Comment by uslss** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D12. Do not remove or edit.` [D12](https://dbeaver.testquality.com/project/8805/result/1593215/defect/5727)

**Comment by kai-morich** [comment]
not reproducible with dbeaver 7.0.2 + hana 2sps04. unique index is created correctly

**Comment by LonwoLonwo** [comment]
@kai-morich thanks!
