### ISSUE TITLE
"ctrl+alt+left" and "ctrl+alt+right" rotate DBeaver window

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7146]
#### System information:  
- Operating system (distribution) and version Windows 10 Home
- DBeaver version 6.2.4

#### Describe the problem you're observing:
"ctrl+alt+left" and "ctrl+alt+right" shortkeys turn  DBeaver window over monitor to the left/right
 instead of switching to previous/next row in Data Editor (as written in Main menu (Navigate))

1. Open Data Editor
2. Press "ctrl+alt+left" or "ctrl+alt+right" shortkeys

![HftvEiBXCv](https://user-images.githubusercontent.com/51405061/68070431-3302b480-fd7f-11e9-9ba8-1c5d19b7e4d0.gif)

**Comment by serge-rider** [comment]
These are system (Windows) shortcuts. DBeaver has nothing to do with them and it can't affect them.

Workaround: disable screen rotation shortcuts in system preferences.
