### ISSUE TITLE
Search: DB Full-Text Search

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7149]
An error "Data soarces load" appears after pressing DB Full-text search. But the Search goes properly after closing error window 
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3801289/dbeaver-debug.log)
![3](https://user-images.githubusercontent.com/51405061/68081359-ce4a6700-fe1d-11e9-8748-ead7c638c63b.png)

**Comment by kseniiaguzeeva** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D18. Do not remove or edit.` [D18](https://dbeaver.testquality.com/project/8805/result/1598598/defect/5751)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
I reproduced it again..
![bcUjhJpEo0](https://user-images.githubusercontent.com/51405061/68178859-89017300-ff9e-11e9-99a5-c376312dc2d8.gif)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3807264/dbeaver-debug.log)
[.log](https://github.com/dbeaver/dbeaver/files/3807265/default.log)

**Comment by serge-rider** [comment]
Fixed again :)

**Comment by kseniiaguzeeva** [comment]
Verified
