### ISSUE TITLE
Error in the "version update" dialog

### ISSUE THREAD

**Issue by Cris70** [dbeaver/dbeaver#7155]
#### System information: 
- Operating system (distribution) and version: openSUSE Tumbleweed 20191101 (rolling)
- DBeaver version: 6.2.3
- Additional extensions: Office Support, SSHJ, SVG Extensions

#### Connection specification:
Irrelevant to the issue at hand

#### Describe the problem you're observing:
The "Version update" dialog shows the message '**Press "More Info" to open the web page where you can download 6.2.4**'. However there is no more a "More Info" button.

Also, at the bottom of the dialog, you can see three buttons: "**Update...**", "**Close**", and "**Upgrade...**". It is not clear what the difference is between the "Update..." and the "Upgrade..." buttons. My trials have shown no difference.

#### Steps to reproduce, if exist:
Click on the "Help" menu option and choose "Check for updates". Look at the dialog that opens.

#### Include any warning/errors/backtraces from the logs
Irrelevant to the issue at hand

![image](https://user-images.githubusercontent.com/5107224/68111275-09689b00-feef-11e9-8538-ec583adf4cd1.png)

**Comment by serge-rider** [comment]
I can't reproduce this screen (Update and Upgrade buttons). I can't even find "Update ..." string in sources.
However label with "More info" is invalid, now this button has name "Details", thanks for the bug report.

**Comment by Cris70** [comment]
Hi @serge-rider, thank you for the fix.
I suspect the upgrade mechanism is at fault, somehow generating a "hybrid" between the old and the new java code. Otherwise, how do you explain the "Version update" dialog I am getting?
Maybe this is the same problem that is/was causing bug #3546 here.
I'll try to uninstall 6.2.3, delete everything under ~/.eclipse and then install 6.2.4 and see what happens.

**Comment by Cris70** [comment]
I did it, and now I'm supposedly running a "clean" version of DBeaver 6.2.4.
Everything seems well, but obviously now I cannot summon the upgrade dialog because there's no update available. As soon as 6.2.5 (or whatever version is the next release) is available I'll see what happens.

**Comment by uslss** [comment]
verified

**Comment by Cris70** [comment]
Just one more comment to let you know that today, with the program proposing the update to 6.2.5, the dialog was correct. 
It has three buttons: "Details", "Close" and "Upgrade".
Thank you
