### ISSUE TITLE
Interval not set correctly in event

### ISSUE THREAD

**Issue by livedota** [dbeaver/dbeaver#7156]
#### System information: 
- windows 7 SP1
- DBeaver version: 6.2.4 CE
- Java version: 8 update 231

#### Connection specification:
- Database name and version: MySQL 8
- Driver name: com.mysql.cj.jdbc.Driver 8.0.17
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Interval  Value and Interval field are not set correctly
#### Steps to reproduce, if exist:
1)Create an event with this script:
CREATE EVENT event1
ON SCHEDULE EVERY 2 MONTH
STARTS now()
ON COMPLETION NOT PRESERVE
ENABLE
DO SELECT 1
2) refresh
As you can noticed either in tab Properties and in Source  interval are set to 1 DAY

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
