### ISSUE TITLE
Suppressing parameter binding for character classes in regular expressions

### ISSUE THREAD

**Issue by eatyourchocolate** [dbeaver/dbeaver#7160]
#### System information: 
- Operating system (distribution) and version
Windows 10 Pro
- DBeaver version
6.2.3.201910201831

#### Connection specification:
- Database name and version
PostgreSQL 9.4.2 on x86_64

#### Describe the problem you're observing:
When executing queries from the editor content is scanned for parameters. If any parameter is detected, an appearing dialog enables the user to fill in values to be used in the query. Parameters are detected by e.g. leading question marks (?) or colons (:). However, if the query cointains regular expressions with character classes in it, these [:digit:], [:alnum:], etc. are seen as paramters, too.

Unfortunately, pressing "Ignore" in the dialog internal alters the query. Also leaving no input to the detected parameter and pressing 'OK' has the same effect.

#### Steps to reproduce, if exist:
The simple query

`select '123' ~ '^[[:digit:]]+$'`

should give the result true, as the string '123' contains only numbers. But, hitting either Ignore or OK in the dialog results in false.

When "Activating SQL-Parameters" in seetings is switched off, the query results are as expected.

#### Suggestions & guesses
Maybe, the parsing for parameters must be enhanced, e.g. parameters can be ignored when they are surrounded by ' or square brackets.

Further, the Ignore button still seems to change the query which is not what I am expecting.

**Comment by uslss** [comment]
Hi @eatyourchocolate , could you check if issue is reproducible for you against 6.2.4?

**Comment by eatyourchocolate** [comment]
Just installed 6.2.4 and phew, the problem has vanished. How did you do that? :D
