### ISSUE TITLE
DBeaver - Active Directory - Password Fails

### ISSUE THREAD

**Issue by jmarchione** [dbeaver/dbeaver#7165]
DBeaver Support:

Cannot seem to get connected via Active Directory Password.  We have been using RazorSQL for many years and have not had any issues with this connection.  This is a fresh install with latest DBeaver Community Edition (6.2.4) version and latest JDK (13.0.1).

![Screenshot 2019-11-05 10 41 51](https://user-images.githubusercontent.com/17055697/68222915-cf180000-ffb9-11e9-9e4f-444993a4c68d.png)

ping PRUSDEVSQL005
PING prusdevsql005.prllc.com (10.251.101.15): 56 data bytes
64 bytes from 10.251.101.15: icmp_seq=0 ttl=127 time=33.152 ms
64 bytes from 10.251.101.15: icmp_seq=1 ttl=127 time=32.155 ms

Any help would be much appreciated.

Thanks

john

**Comment by serge-rider** [comment]
AD Password auth method used mostly by Azure SQL Database/Data Warehouse.
Try NTLM auth, enter user name as user@domain
