### ISSUE TITLE
make it easier to expand or contract the size of the output window

### ISSUE THREAD

**Issue by WellspringCS** [dbeaver/dbeaver#7166]
**Is your feature request related to a problem? Please describe.**
It is frustratingly (insanely?) difficult to grab the (what... five pixels high?) slender grey bar (the one that has an even tinier set of up an down arrows embedded in it) that separates the output window from your sql instructions in the script editor. The mouse movement overwhelms and I find myself playing for sometimes as long as 10 seconds, screaming in my head, trying to get "just so" so that I can click on the bar and move the bottom output window higher or lower.

**Describe the solution you'd like**
Make the bar twice as big. At 10 pixels or whatever it is, that would hardly impact screen real estate much, but it'd make it ever so much easer to grab the bar... so as to move it. Or even just increase the buffer *around* the bar so that the mouse click action is triggered a bit below and above the bar, making it easier for users to grab the blasted thing and move it.

If there is a place in preferences where this feature is customizable... I didn't find it.

**Comment by WellspringCS** [comment]
I should add that sometimes it's easier than others. I haven't figured out why it's so hard some of the time but not all of the time.

**Comment by uslss** [comment]
will be fixed in #12768
