### ISSUE TITLE
SET TERM on Firebird

### ISSUE THREAD

**Issue by Pecaas** [dbeaver/dbeaver#7170]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 6.2.3

#### Connection specification:
- Database name and version Firebird 2.5

#### Describe your question:
It is impossible to run sql script:
`
SET TERM ^
CREATE OR ALTER TRIGGER PERSONINSERT FOR PERSON BEFORE INSERT AS
DECLARE VARIABLE V Integer;
DECLARE VARIABLE D Date;
BEGIN
  if ((new.PERSONNUM1 is null) or (new.PERSONNUM1 = 0)) then
    new.PERSONNUM1 = gen_id(PERSONGENER,1);

  V = gen_id(PERSONGENERV,1);
  new.SYSVER = V;
  D = 'now';
  new.SYSDAT = D;
  if (( new.DATNEW is null) or (new.DATNEW <= '1/1/1900')) then new.DATNEW = D;
  if (( new.DATMOD is null) or (new.DATMOD <= '1/1/1900')) then new.DATMOD = new.DATNEW;
END ^
CREATE OR ALTER TRIGGER PERSONEDIT FOR PERSON BEFORE UPDATE AS
DECLARE VARIABLE V Integer;
DECLARE VARIABLE D Date;
BEGIN
  V = gen_id(PERSONGENERV,1);
  D = 'now';
  new.SYSVER = V;
  new.SYSDAT = D;
  if (( new.DATMOD is null) or (new.DATMOD <= '1/1/1900')) then new.DATMOD = D;
END ^
SET TERM ;`
It raises error: Dynamic SQL Error; SQL error code = -104; Token unknown - line 17, column 1; CREATE. What is wrong? Thanks

**Comment by Pecaas** [comment]
Is there anybody, who knows execute DDL scripts for stored procedures via DBeaver? Thank you.

**Comment by mrotteveel** [comment]
Remove both `SET TERM` statements, and replace `END ^` with just `END`, and then just execute. This works. `SET TERM` is not actually part of the Firebird SQL syntax. It is a local command specific to the ISQL tool (and some other Firebird tools support it as well).
