### ISSUE TITLE
Missing columns in DDL generation for PostgreSQL

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#7172]
#### System information: 
- Operating system: Linux Mint 19.2
- DBeaver version: 6.2.4
- Additional extensions: Office Support, SSHJ, SVG, Git intergration

#### Connection specification:
- Database: PostgreSQL 11
- Driver name: Postgresql JDBC community driver
- Do you use tunnels: no

#### Describe the problem you're observing:
As you can see in the attached screen copy, there are missing columns in the generated DDL code, compared with the table properties in the database properties tab.
Here, the "clz" column is missing in the generated DDL:
![image](https://user-images.githubusercontent.com/12892581/68278801-6b054280-0072-11ea-9d4d-e651b28273cc.png)

This issue does not happen on every table, but several other tables are concerned by the bug. It does not seem to be related to column type, since different types are affected.
Perhaps is it related to the following bug: https://github.com/dbeaver/dbeaver/issues/6510

Thanks in advance for your help.

Cedric

**Comment by uslss** [comment]
cannot reproduce it for now.
if issue is still actual for you - feel free to reopen the ticket

**Comment by ced75** [comment]
Sorry but for me, the problem remains exactly the same as I described it last year.
Could you give me the query used to generate the DDL code, in order to try it on my PostgreSQL server and find where the problem could come from?

Thank in advance.
