### ISSUE TITLE
[BUG] "Table does not exists" when exporting datagrid data with `set search_path` and selecting just one cell

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#7175]
Ok guys, for this a deserve a premium subscription, lifetime :-D

When working with Postgres, before runing a query i ran
`set search_path=whatever` to avoid specifying schema in queries.

I execute a query, all ok.
i got to the datagrid (results) to export (as csv, but might happen in all cases), and i receive a "table does not exist" on a table that (of course, query executed...) do exists...
BUT
Things get funny: when i select the full datagrid, it works!
if i select a row, or all of them, it works.
If i select just one cell, right click, "export as csv", then i receive the "table does not exists" error. 
(Fact, DBEaver re-executes the query!)

Have fun :-)

**Comment by uslss** [comment]
hi,
unfortunately, cannot reproduce the issue. Is it actual against 6.2.4 version?

**Comment by wiwwo** [comment]
yes, latest 6.2.4

**Comment by kseniiaguzeeva** [comment]
Is it possible to give more details about:
- executed query after search_path
-table example or description.
Thank you in advance

**Comment by wiwwo** [comment]
![image](https://user-images.githubusercontent.com/3930671/68394778-bf8de800-016e-11ea-87b1-b693a57021be.png)

After executing the the select, right click on the "1" in the datagrid, advanced copy, copy as csv.
Query is executed again, and error occours.
Do not try with "puvlic" schema, since it is the default search_path... ;-)

**Comment by uslss** [comment]
thanks for help and for the bug report :)

**Comment by serge-rider** [comment]
This happens because you enable option "Open new connection" in data export wizard. DBeaver opens a new connection for export task and of course it doesn't know about your current search_path.
This works fine if you have some selected cells because in this case dbeaver exports only these selected cells.

Anyhow, we need to disable "Open new connection" option for Copy As commands.

**Comment by uslss** [comment]
verified
