### ISSUE TITLE
Compilation errors when running create or replace command

### ISSUE THREAD

**Issue by andrewwellsdfj** [dbeaver/dbeaver#7177]
**Is your feature request related to a problem? Please describe.**
There has been multiple instances where i run a create or replace procedure/package command. After running there are no apparent error messages. I do not realize until i refresh the procedure list that there was in fact an error when creating the procedure
**Describe the solution you'd like**
There should be the same error message when you run create or replace as if you would right click and compile the object. Right now there is no way to discern whether the command was successful or not. 
**Describe alternatives you've considered**

**Additional context**

**Comment by uslss** [comment]
seems issue is obsolete
