### ISSUE TITLE
How can I access graphical execution plan?

### ISSUE THREAD

**Issue by leehach** [dbeaver/dbeaver#7179]
#### System information: 
Linux Mint 19.2
DBeaver CE 6.2.4

#### Connection specification:
PostgreSQL 10.10

#### Describe your question:
Two blog posts from the past year show a graphical version of the execution plan:

* https://dbeaver.com/2019/03/12/dbeaver-6-0-is-a-new-big-step-forward/
* https://dbeaver.com/2019/06/11/start-your-summer-with-new-dbeaver-6-1/

According to the first link, this is available for PostgreSQL (and other databases).

However, when I explain the execution plan, I *only* get the "Simple" version. In the blog post images, there is a "Graph" tab in the Execution plan pane which I just do not see.

Why would this be missing? Do I have to do something to enable this feature? Is this an EE feature only?

Not calling this a bug report because I'm not sure what the expected behavior is.

**Comment by uslss** [comment]
Hi @leehach ,
yes, graphical version of the execution plan is EE feature only
