### ISSUE TITLE
Column names with capital letters are set to small letters

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#7184]
**Steps to reproduce:**
* Run some select query with column names aliased to something with capital letters, e.g.
```sql
select 1 as c1, 'a' as BIGCOL
```
* Look at the results pane and/or try to export the results to CSV.

**Expected behavior:** should produce columns named `c1`, `BIGCOL`.

**Actual behavior:** produces columns named `c1`, `bigcol`.

**Setup:** dbeaver 6.2.4, querying postgres, running on windows 10.

**Comment by uslss** [comment]
Hi, btw it is expected behavior.
Query should look like select 1 as c1, 'a' as "BIGCOL" to get expected result

**Comment by Igor180** [comment]
Hello,
This same issue seems to continue in 2021 with Dbeaver version 21.1.4  (02.08.2021).
When trying to alias field names with mixed letters i.e. field_name as "Field_Name" it returns it with all lowercase i.e. field_name.
Any thoughts on how to overcome the issue?

**Comment by benneteapen** [comment]
I'm using Version 23.3.2 (and it's 2024). This issue seems to still be there.
