### ISSUE TITLE
pair of doubts

### ISSUE THREAD

**Issue by jviure** [dbeaver/dbeaver#7185]
Hi! I've two doubts:

- When I create a foreign key, I do not see where I can change the foreign key name, right now I only can create one foreign key through the GUI, the next through code changing the name to avoid name conflict
- If I open a table, I go to the data tab and I filter i.e.  locality_id = 5..  it's possible to have an autocomplete there? of the fields? would be great, I've tables with too many columns and sometimes I dont remember the exact name of the column.

To finish..  if I scroll right and then scroll down (and more rows are lazy loaded..).. I lose the horizontal position cause the window focus on the first column, I don t know If I am explaining..  lol :P 

Thanks a lot! great job

**Comment by eatyourchocolate** [comment]
When you enter text in the filter field of data tab, you can hit <ctrl> + <space>. You get suggestions for autocomplition where you can navigate with cursor keys and select the fitting one with <enter>.

**Comment by jviure** [comment]
many thanks, is very useful that, I think was automatic.. I came from Navicat, I've to learn this new soft for me. 
What about my first and last doubts? :P

**Comment by eatyourchocolate** [comment]
Regarding your first question, it should be possible to change the name. First you have to open the edit dialog for your foreign key. Either you find it in the database navigation tree, right click on it and find edit, or open the table for editing and find the foreign key in the properties tab. Once you have the properties pane of ypur object, edit as you desire. However, I am not sure if it works for the database your are using, but basically that is what I would try.

The third question is also easy to solve: You can prevent the reposition to the first column by first clicking a table cell in the column of your interest.

**Comment by jviure** [comment]
ok great, very usefull too, mmm,  why I cannot edit i.e the last value of a sequence? the input's are in gray, thanks!

**Comment by serge-rider** [comment]
@jviure this depends on a database. For some databases table properties edit is not supported.

**Comment by jviure** [comment]
> @jviure this depends on a database. For some databases table properties edit is not supported.

oh! a pitty, with navicat I could, thanks!
