### ISSUE TITLE
Sorting in results pane produces wrong order

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#7186]
**Steps to reproduce:**
* Run some select query that would have an unnamed column that concatenates two or more strings.
* Sort the results in the results pane according to that column by clicking the arrow button next to the column name.

**Expected results:** should sort the results according to that column, in ascending or descending order as specified.

**Actual results:** results are randomly sorted, not according to the column that was supposed to be sorting it. In previous versions it was producing wrong SQL too: https://github.com/dbeaver/dbeaver/issues/6927

**Setup:** dbeaver 6.2.4, querying postgres, running on windows 10.

**Comment by serge-rider** [comment]
Thanks for the bug report.
#6927 is different.

**Comment by uslss** [comment]
verified
