### ISSUE TITLE
Errore creating more connection "DB2 z/OS connection settings"

### ISSUE THREAD

**Issue by paskd** [dbeaver/dbeaver#7187]
#### System information: 
- Windows 10 PRO
-     DBeaver Community Edition	6.2.4.201911031605	org.jkiss.dbeaver.ce.feature.feature.group	JKISS
- Additional extensions : NOTHING

#### Connection specification:
- Database DB2
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
When I create more connection of type  "DB2 z/OS connection settings" the JDBC URL is referred always to the jdbc url of the last connection created.
The previus connection change the configuration and so I can use only one connection of this type.

#### Steps to reproduce, if exist:
Create more "DB2 z/OS connection settings"

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
@paskd please, specify, did you mean changing URL in Driver Settings?
![image](https://user-images.githubusercontent.com/31996417/68620208-103e7180-04de-11ea-9966-981c635f5ebe.png)

**Comment by paskd** [comment]
Yes ... when I change this option it is chenged on all other connection created.
Maybe I'm using it incorrectly ... but I couldn't figure out how to do it.

**Comment by uslss** [comment]
@paskd btw it is expected behavior, changes of the driver settings should effect on all connections that using this driver
