### ISSUE TITLE
Incorrect America/Sao_Paulo timezone (DST)

### ISSUE THREAD

**Issue by ohrlando** [dbeaver/dbeaver#7188]
Brazil finished DST adjust but Dbeaver are showing incorrectly (with -02:00 and the correct is -03:00).

**Comment by serge-rider** [comment]
This was fixed (updated) on OpenJDK 11.0.5. We will upgrade to this version in DBeaver 6.2.5.
Or you can install Java separately and use portable version of DBeaver.
