### ISSUE TITLE
Liquibase Changelog: Changes Diagram isn't shown

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7190]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.4

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
1, Compare/Migrate - Liquibase changelog
2. Choose any item - Generate Changelog
3. Switch to Diff Type: Changes Diagram - Diagram isn't shown
![image](https://user-images.githubusercontent.com/31996417/68416100-d7805e80-01a4-11ea-9cc7-95971ae20432.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
