### ISSUE TITLE
Auto generate alias for JOIN table as it is done for FROM table

### ISSUE THREAD

**Issue by amplexdenmark** [dbeaver/dbeaver#7191]
Today autocomplete adds an alias for the table after a FROM clause.
It propose that similarly an alias are added for tables referenced in JOIN clauses.

add alias a in this example:

SELECT * FROM sometable s
JOIN anothertable a

**Comment by LonwoLonwo** [comment]
Please check new [DBeaver versions](https://dbeaver.io/).
If I understood you correctly, the addition of aliases after JOIN is already implemented

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you - feel free to reopen it.
