### ISSUE TITLE
@include feature fails on oracle sequencers

### ISSUE THREAD

**Issue by mseele** [dbeaver/dbeaver#7195]
#### System information: 
- Operating system (distribution) and version: Windows 10 1903
- DBeaver version: 6.2.4.201911031605
- Additional extensions: DBeaver Office Support 1.1.51.201908060542

#### Connection specification:
- Database name and version: Oracle Database 19c Enterprise Edition
- Driver name: Oracle JDBC driver 19.3.0.0.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

We have a "setup.sql" file which adds all sequencers, tables & views:

```
-- This script needs to be run as the user xxx.

-- Create the sequencers.
-- @include sequencers/change_ids.sql
-- @include sequencers/approval_ids.sql
-- ...

-- Create the tables.
-- @include tables/domains.sql
-- @include tables/status.sql
-- @include tables/apps.sql
-- ...

-- Create the views.
-- @include views/v_changes.sql
-- @include views/v_approvals.sql
-- ...
```

This script doesn't continue after going into the first sequencer include file and does not continue/waits forever.
It's even not possible to cancel the script.

#### Steps to reproduce, if exist:

Save the following 3 files as ".sql" (github doesn't allow .sql files to upload) in one directory and execute setup.sql as "Execute SQL Script". dbeaver no tries to create sequence change_ids and does not continue/waits forever.

[setup.sql.txt](https://github.com/dbeaver/dbeaver/files/3824166/setup.sql.txt)
[approval_ids.sql.txt](https://github.com/dbeaver/dbeaver/files/3824168/approval_ids.sql.txt)
[change_ids.sql.txt](https://github.com/dbeaver/dbeaver/files/3824169/change_ids.sql.txt)

**Comment by uslss** [comment]
seems to be fixed.
correlated issue #8313
