### ISSUE TITLE
MS SQL Server browser lost metadata after edit

### ISSUE THREAD

**Issue by SpikeBerlin** [dbeaver/dbeaver#7196]
#### System information: 
- Win 10 pro
- 6.2.4

#### Connection specification:
- MS SQL 2014
- mssql jdbc 7.1.4

#### Describe the problem you're observing:

In browser selected trigger on table is hidden after editing.

#### Steps to reproduce, if exist:

select table->trigger in browser
edit trigger source
compile trigger 
trigger is invisible in browser under Tables ( under Table Triggers is available )

Refresh has not effect. 

After restart dbeaver is ok.

**Comment by uslss** [comment]
cannot reproduce it for now.
if it is still actual for you - feel free to reopen the ticket
