### ISSUE TITLE
Informix Text Blob Type 2 ( addition to #1983 )

### ISSUE THREAD

**Issue by amivanovano** [dbeaver/dbeaver#7197]
### System information: 
- Operating system Window 10
- DBeaver version 6.2.4

#### Connection specification:
- Database          Informix Dynamic Server 12.10.FC7
- Driver name     Informix JDBC Driver for Informix Dynamic Server 4.50.JC2
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No
- CLIENT_L0CALE ru_RU.1251

#### Describe the problem you're observing:

Blob Text column contains UTF-8 symbols. If text contains Cyrillic capital letter I ( hex D0 98 ) Data Editor shows **[NULL]**. Setting UTF-8 for **LOB Editors -> String Encoding** has no effect. 
All OK in UTF-8 temp Informix file Programs Files\DBeaver\IfxTmpFile_xxxxxxxxxxxxxxxxxxxx
Is it DBeaver or JDBC Driver bug ?

**Comment by liaosnet** [comment]
It's NOT bug. Informix JDBC 's environment variables LOBCACHE with default value 4096（4KB). If your data's  size exceeds the LOBCACHE value, the data is stored in a temporary file. You can set it to -1 or a value great your data. This is no IfxTmpFile_xxxxxxxxxxxx.

LOBCACHE ref to : https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.jdbc_pg.doc/ids_jdbc_040.htm

**Comment by amivanovano** [comment]
Addition.
I have not DBEaver BLOB/CLOB problem with smart binary objects. DBEaver Blob editor works nice.
Problems are with simple binary objects stored in Informix column types Text/Byte which DBeaver views in data editor ( sometimes )

**Comment by liaosnet** [comment]
> Addition.
> I have not DBEaver BLOB/CLOB problem with smart binary objects. DBEaver Blob editor works nice.
> Problems are with simple binary objects stored in Informix column types Text/Byte which DBeaver views in data editor ( sometimes )

Yes. Byte/Text data too.
