### ISSUE TITLE
Restore crashes desktop

### ISSUE THREAD

**Issue by joeyz** [dbeaver/dbeaver#7199]
#### System information: 
- Ubuntu 19.10/Gnome 3.34.1
- DBeaver version 6.2.4.201911031605

#### Connection specification:
- Postgresql 10
- PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH Tunnel)? 

#### Describe the problem you're observing:
When trying to restore from a backup, once I click the field to choose my backup file it freezes and then crashes every single program I have open ... except for Terminal, for some reason. 
#### Steps to reproduce, if exist:
- Right Click a database
- Hover over "Tools"
- Click "Restore"
- In the resulting window that opens, click the folder icon next to the "Backup File:" Input

#### Include any warning/errors/backtraces from the logs
Event loop exception->Widget is disposed

**Comment by uslss** [comment]
cannot reproduce it anymore.
if it is still actual for you - feel free to reopen the ticket
