### ISSUE TITLE
Is dbeaver converting NULL date values to zero?

### ISSUE THREAD

**Issue by lalato** [dbeaver/dbeaver#7200]
#### System information: 
- MacOS 10.14.6
- DBeaver version 6.2.3

#### Connection specification:
- mysql

#### Describe your question:

Strange issue I just encountered.  I have some date columns in a table which can be NULL.  When I select on the table, the results clearly show the NULL in the results.  However, when I try to only pull NULL values in the WHERE clause... "date_column is NULL" no records return.  However, if I instead enter "date_column = 0" in the WHERE clause, then all the NULLs are returned.

Is there a setting in dBeaver that I might have missed that would cause this behavior?

**Comment by uslss** [comment]
hi @lalato ,
cannot reproduce issue against recent version. could you tre if it is reproducible for you?

**Comment by uslss** [comment]
there is no update on ticket for a long time. if issue is still actual for you - feel free to reopen the ticket
