### ISSUE TITLE
The semicolon and Chinese mark are not obvious

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#7201]
![image](https://user-images.githubusercontent.com/26621087/68523403-a2ceed00-02f3-11ea-8209-d4a43911730c.png)
The semicolon is not obvious, leading to errors

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by mkgrgis** [comment]
Problem with Unicode rendering?

**Comment by uslss** [comment]
unfortunately, cannot reproduce. if it is still actual - feel free to reopen the ticket.
