### ISSUE TITLE
Autocommit for script

### ISSUE THREAD

**Issue by michalk-k** [dbeaver/dbeaver#7202]
Since I'm used to pgAdminIII I'm looking for a DBeaver configuration which ensure the same transaction behaviour when running scripts.

Main demands:
1 run whole script if nothing selected
2 run selected part of script if anything selected
3 autocommit if there is no explicit BEGIN transaction called
4. autorollback in case of error

I almost succeeded except of: 
- no auto-rollback if explicit BEGIN was issued and error is raised during execution (regardless running sql command or script)
- when running script, it commits every single line, regardless of settings "Scripts/Commits type" set to "At script end".

So far I found following settings which might help to reach requested behaviour but, as said, with no full success:

Settings: 
- Autocommit set in toolbar
- In preferences Editors/SQL Editors/SQL Processing/Scripts: 
-- Commit type: At script end
-- Error handling: Stop+rollback
-  In preferences Error handle/Execute errors
-- Rollback on Error: true

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer. Is it possible to give a Script example?

**Comment by uslss** [comment]
there is no update on issue. if it is still actual for you - feel free to reopen the issue
