### ISSUE TITLE
Same name for differents scripts

### ISSUE THREAD

**Issue by KMLessa** [dbeaver/dbeaver#7205]
Multiple scripts in SQL Console are being opened with the same name "Source", overwriting the contents of the first saved file.

Clicking on a role in Database Navigator opens a new window with the role specification, allowing me to click the "Open in SQL" Console button (bottom of the window), repeat this operation with another function and you will have two scripts named "Source"

I am using version 6.2.4.201911031605 for Windows 64.

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
Fixed. Now we will include object name in editor title

**Comment by uslss** [comment]
verified
