### ISSUE TITLE
preferences filter doesn't show some desired options

### ISSUE THREAD

**Issue by rdp** [dbeaver/dbeaver#7206]
#### System information: 
- OS X 10.14.6 mojave
- DBeaver version 6.2.4
- Additional extensions: none

#### Describe the problem you're observing:

I am opening preferences and "searching" for the setting "Open separate connection for each editor" by typing the word "connection" in the filter box.
It does not filter in a way that allows me to find that setting to modify it.

#### Steps to reproduce, if exist:
Type "connection" in the filter box ("type filter text here")

<img width="727" alt="Screen Shot 2019-11-11 at 10 26 55 AM" src="https://user-images.githubusercontent.com/12496/68607528-0b41d980-046e-11ea-85d3-48a78fa0287b.png">
<img width="729" alt="Screen Shot 2019-11-11 at 9 32 50 AM" src="https://user-images.githubusercontent.com/12496/68607543-10068d80-046e-11ea-96bd-6fa2359da364.png">

Thanks!

**Comment by serge-rider** [comment]
#7206 Preference page keywords

**Comment by serge-rider** [comment]
I've added a few extra keywords for SQL editor and data editor pages.
However we need to fill this gap and provide proper keywords for all pages.
Will be tracked in #7283

**Comment by uslss** [comment]
verified
