### ISSUE TITLE
db export, no cancel button

### ISSUE THREAD

**Issue by sirber** [dbeaver/dbeaver#7207]
#### System information: 
- Operating system (distribution) and version
Windows 10 x64
- DBeaver version
6.4.2
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/3911428/68611123-5ae0cf00-0487-11ea-8295-aa1ceaa20795.png)

**Comment by uslss** [comment]
Hi, as far as I can see you could find Cancel button here
![image](https://user-images.githubusercontent.com/31996417/68674605-38be7e00-0567-11ea-941f-b248fe9b1720.png)

**Comment by sirber** [comment]
oh, lol. thank you!
