### ISSUE TITLE
find extended ASCII character in CSV

### ISSUE THREAD

**Issue by Dookie78** [dbeaver/dbeaver#7209]
#### System information: 
- Operating system (distribution) and version
WINDOWS 10
- DBeaver version
DBEAVER 6.6.4

#### Connection specification:
- CSV

#### Describe your question:
![image](https://user-images.githubusercontent.com/35907473/68653386-98685980-0566-11ea-9331-bec688eb2ade.png)

any ideas on detecting those special characters highlighted in yellow?

**Comment by mkgrgis** [comment]
This is Windows-specific problem. No need for Linux, where Unicode is by default. You can set input encoding option in options.
