### ISSUE TITLE
regexp_replace format error

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#7212]
![image](https://user-images.githubusercontent.com/26621087/68677900-d92c9680-0597-11ea-97c4-3d60b3241da3.png)

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
Please provide more info
1. What is your database?
2. What exactly is wrong with formatting?

**Comment by Pengchenghua** [comment]
> 请提供更多信息
> 
> 1. 你的数据库是什么？
> 2. 格式化到底有什么问题？

hive ,
regexp_replce(a,'-',''),
nvl(a,'')，
coalesce(a,0),
substr(1,0)
Several other functions are also problematic。
![image](https://user-images.githubusercontent.com/26621087/69505039-845b2980-0f62-11ea-8cde-da19f25084bf.png)

**Comment by LonwoLonwo** [comment]
Part of the problem was solved in this ticket https://github.com/dbeaver/dbeaver/issues/7509 
it remains to add functions to Hive

**Comment by LonwoLonwo** [comment]
And we have ticket already https://github.com/dbeaver/dbeaver/issues/6439 for this
