### ISSUE TITLE
Doubt not to round

### ISSUE THREAD

**Issue by thiagokz** [dbeaver/dbeaver#7214]
#### Describe your question:
I'm creating a table with a float field

CREATE TABLE teste (
	valor float NULL
) GO

after entering a value, it is rounding the value.

INSERT INTO teste (valor) VALUES(9999999999);

Result: 
valor
10,000,000,000

even using Rouding mode UNNECESSARY.

Could help in this situation  

thanks. 

#### System information: 
- Operating system (distribution) and version
Windows 10 
- DBeaver version
Version 6.2.4.201911031605

#### Connection specification:
- Database name and version
MSSQL

**Comment by serge-rider** [comment]
This happens because SQL Server driver provides wrong information about data type (4 byte float instead of 8 byte float). This leads to precision loose.

**Comment by uslss** [comment]
verified
