### ISSUE TITLE
RSA Key Authentication for Snowflake

### ISSUE THREAD

**Issue by lutzkuen** [dbeaver/dbeaver#7215]
Hello,

There has been some interest in using RSA Key Authentication for Snowflake through dbeaver. See this discussion in snowflake community:
https://support.snowflake.net/s/question/0D50Z00009Z3dfVSAR/does-anyone-know-if-it-is-possible-to-use-key-pair-authentication-with-an-sql-tools-such-ad-dbeaver-or-squirrelsql

As of now only one factor password authentication and MFA by using the duo mobile app are supported in dbeaver. The latter is a hassle since you have to edit the connection every time you connect.

Snowflake supports the usage of RSA Keys which should give a hassle free and safe experience via dbeaver. 
There is sample code at the end of the section in the snowflake docs which describes how to connect with jdbc and RSA Key:
https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html#using-key-pair-authentication

I will try to get it done myself, but due to my lacking java experience that might take a while.

BR

**Comment by sertaco** [comment]
this looks relatively easy to implement.
- add two input boxes for private_key_file and private_key_file_pwd
- build jdbc url accordingly similar to this:
`"jdbc:snowflake://exampleaccount.snowflake.com/?private_key_file=/tmp/rsa_key.p8&private_key_file_pwd=dummyPassword");`
   
if you agree I can give it a try

**Comment by lutzkuen** [comment]
Yes, that would be awesome. Thank you very much

**Comment by armyofda12mnkeys** [comment]
> The latter is a hassle since you have to edit the connection every time you connect.

@lutzkuen 
just curious, I am using TOAD to connect to Oracle and we always get a Duo Mobile popup to accept.
With DBeaver, I just get a invalid user/password error immediately (i dont even get a Duo Mobile popup on my phone). Just curious if you had to setup any custom settings to get Duo Mobile to work with DBeaver (realize you using Snowflake and Im using Oracle but thought maybe there is some common thing Im missing).

**Comment by lutzkuen** [comment]
I have tried this: https://docs.snowflake.com/en/user-guide/security-mfa.html#using-mfa-with-jdbc
You generate a passcode and pass it in the connection string. jdbc:snowflake://xy12345.snowflakecomputing.com/?user=demo&passcode=123456
It works but it is a pain

**Comment by rumbin** [comment]
Is there any progess on this topic?

**Comment by ArianHojatAES** [comment]
@rumbin
FYI I wasn't sure if your question above is more about Snowflake DuoMobile auth... or general DuoMobile auth (for me i needed latter for Oracle connection).
This solved for Oracle 2FA DuoMobile auth (adding to Driver Properties tab in DBeaver):
Name/key                                             value
oracle.net.authentication_services        RADIUS

**Comment by LonwoLonwo** [comment]
Hello.

Snowflake private key/password authentication is available in the DBeaver PRO versions: https://dbeaver.com/download/

![2022-10-17 13_47_30-DBeaver Ultimate 22 2 0 - RETURN_GREATER(NUMBER_1 NUMBER, NUMBER_2 NUMBER)](https://user-images.githubusercontent.com/45152336/196158872-8fcde998-af95-4cf7-ab82-cfa74ae84096.png)

**Comment by sfc-gh-hachouraria** [comment]
Just for posterity, the DBeaver community edition too supports private key auth through its ability to configure JDBC properties: https://community.snowflake.com/s/article/Using-Private-Key-authentication-in-DBeaver
