### ISSUE TITLE
Microsoft Store Updates

### ISSUE THREAD

**Issue by yvangg** [dbeaver/dbeaver#7218]
Hi, I have installed DBeaver 6.2.0 through the Microsoft Store on my Windows 10 machine.

Is there a reason why I'm not receiving the latest updates?

What are the policies that define what software updates should be released through Microsoft Store?

Regards.

**Comment by gsandino** [comment]
I found the same issue. It would be great to know the update policy for the Microsoft Store updates.

Thanks!

**Comment by serge-rider** [comment]
We will update MS Store with major DBeaver CE releases. Next update will be for 6.3 (early December).

We can't make updates more frequent because it takes a lot of time and it cannot be automated.
It has nothing to do with MS policy.

**Comment by yvangg** [comment]
Hi Serge, thanks for your response.
