### ISSUE TITLE
DB2 - Listing schemas error 

### ISSUE THREAD

**Issue by fmatosic** [dbeaver/dbeaver#7219]
#### System information: 
- Windows 10 Pro
- DBeaver version - Version 6.2.0.201909040839

#### Connection specification:
- Database name and version -DB2 DSN10015
- Driver name - IBM Data Server Driver for JDBC and SQLJ 4.19.26
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  - No

#### Describe the problem you're observing:
After successfully connecting to DB click on the Schemas in the Database navigator it shows an error:
SQL Error [42704]: SYSCAT.SCHEMATA IS AN UNDEFINED NAME. SQLCODE=-204, SQLSTATE=42704, DRIVER=4.19.26
  SYSCAT.SCHEMATA IS AN UNDEFINED NAME. SQLCODE=-204, SQLSTATE=42704, DRIVER=4.19.26
  SYSCAT.SCHEMATA IS AN UNDEFINED NAME. SQLCODE=-204, SQLSTATE=42704, DRIVER=4.19.26
    THE DESCRIBE STATEMENT DOES NOT SPECIFY A PREPARED STATEMENT. SQLCODE=-516, SQLSTATE=26501, DRIVER=4.19.26
    THE CURSOR SQL_CURLH200C1 IS NOT IN A PREPARED STATE. SQLCODE=-514, SQLSTATE=26501, DRIVER=4.19.26

#### Include any warning/errors/backtraces from the logs
![Capture](https://user-images.githubusercontent.com/3234580/68766778-d2496680-061f-11ea-8a9a-b5653be0fb17.PNG)
![Capture1](https://user-images.githubusercontent.com/3234580/68766787-d4132a00-061f-11ea-9af5-b8e559155fa4.PNG)

**Comment by hgdebie** [comment]
No problems here:
![afbeelding](https://user-images.githubusercontent.com/19188530/68887864-0d2fc500-071a-11ea-8d92-d54aa18db4ad.png)

Are you sure it is not a privilege/authorisation issue ?

**Comment by fmatosic** [comment]
The same user on other DB Tools works just fine.

**Comment by serge-rider** [comment]
@fmatosic What DB2 server do you use? Is it DB2 LUW or DB2 i or DB2 z/OS?

**Comment by fmatosic** [comment]
DB2 z/OS

**Comment by serge-rider** [comment]
@fmatosic Then you should use DB2 for z/OS driver. Currently you are trying to use DB2 LUW driver. 
DB2 LUW and DB@ z/OS have very different system catalogs.

**Comment by fmatosic** [comment]
Great this worked, I was using my db2 jars for zos but I chosen the DB2 LUW when selecting the Database. Thnx
