### ISSUE TITLE
DBeaver deleting script files

### ISSUE THREAD

**Issue by Mohan7490** [dbeaver/dbeaver#7220]
#### System information: 
- Operating system (distribution) and version
- DBeaver version

#### Connection specification:
- Database name and version

#### Describe your question:

I was working in DBeaver, storing my scripts in H:/dbeaver/General/Scripts/, but then Dbeaver stopped responding, I closed it, and it seemed to delete all of my scripts that were open in SQL editor windows.  
 
I'm pretty sure I was saving the scripts periodically -- my guess is that DBeaver deleted the script contents when it stopped responding, and then removed the empty files... 
 
Do you know anything about this behavior, and how I might avoid this in the future / recover the script files?

**Comment by serge-rider** [comment]
DBeaver doesn't delete scripts. But files cache may be corrupted because of unexpected restart.
Just try to refresh Scripts folder (select it and press F5).
