### ISSUE TITLE
Import data from a csv or another external source into a NEW table

### ISSUE THREAD

**Issue by alankar7** [dbeaver/dbeaver#7221]
It'd be nice to import data from an external source such as a csv file or an Excel worksheet into a NEW table. It appears that one can import data only into an existing table.

It would be something similar to the feature that already exists in SQL Server Management Studio as shown on the page in this link: https://docs.microsoft.com/en-us/sql/relational-databases/import-export/import-flat-file-wizard?view=sql-server-ver15

Usually when we receive data from an external source, it is a flat file containing a lot of columns. It is too much work for someone to create a table with those columns first and then import the file.

**Comment by kseniiaguzeeva** [comment]
Sorry for the lomg answer. Thank you for the suggestion.

**Comment by kseniiaguzeeva** [comment]
Already implemented:
1. Open a table context menu in DB Navigator tree
2. Press New btn in Tables mapping step
![dbeaver_UkLluEQdu9](https://user-images.githubusercontent.com/51405061/91274413-50c65d80-e787-11ea-9e08-a5c3f331bef0.png)

Please feel free to write any other ideas etc.
