### ISSUE TITLE
Incorrect information is shown for Data Types

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7226]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.5 

#### Connection specification:
- Database name and version Oracle, PostgreSQL

#### Describe the problem you're observing:
Virtual Columns Settings and ER Diagram are available for Data Types (PostgreSQL, Oracle)
PostgreSQL:
![image](https://user-images.githubusercontent.com/31996417/68871118-0189d180-070d-11ea-9c4a-1788214405c6.png)
Oracle:
![image](https://user-images.githubusercontent.com/31996417/68871145-0babd000-070d-11ea-83d7-332ed9a2ed38.png)

**Comment by serge-rider** [comment]
Fixed (we need this editor only for tables)

**Comment by uslss** [comment]
verified
