### ISSUE TITLE
Oracle Data Types Couldn't be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7227]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.5

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
New Data type couldn't be created using UI
#### Steps to reproduce, if exist:
1. Open Global Metadata - Types
2. Try to create new type - error appears
![image](https://user-images.githubusercontent.com/31996417/68871456-82e16400-070d-11ea-8617-b0b6043373dd.png)

Stack trace is empty
```
> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.jkiss.dbeaver.model
> Error
> Thu Nov 14 18:34:47 MSK 2019

```

**Comment by serge-rider** [comment]
Fixed (global data type cannot be created, only schema type)

**Comment by uslss** [comment]
verified
