### ISSUE TITLE
Oracle: View with the name of already existing view could be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7229]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.5

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
 View with the name of already existing View could be created and save. Existing view is replaced by the new one.
#### Steps to reproduce, if exist:
1. Create View named e.g. NEW_VIEW and save it
2. Create View with the same name that contains another info and save it
3. Check View that was created at the step 1 - it contains all the info from view created at the step 2.

**Comment by serge-rider** [comment]
Fixed (+ new view name validation added)

**Comment by uslss** [comment]
verified
