### ISSUE TITLE
Not able to connect to Snowflake 

### ISSUE THREAD

**Issue by vinayisnaga** [dbeaver/dbeaver#7230]
#### System information: 
- Operating system (distribution) and version: Windows 7
- DBeaver version: 5.2.3.
- Additional extensions

#### Connection specification:
- Database name and version: snowflake 
- Driver name: snowflake jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing: Am getting error to connect to snowflake.Its throwing error SAML error. Please contact administrator 
 
![Dbeaver](https://user-images.githubusercontent.com/57777807/68906625-ccc04f00-06f9-11ea-8b1c-52e1356a87cb.JPG)

**Comment by spacharya** [comment]
@vinayisnaga can you go directly to your snowflake UI and log in successfully?
Was there some change inyour setup that made this stop working?

**Comment by serge-rider** [comment]
@vinayisnaga Most likely it is a result of connection misconfiguration. 
Please check this: support.snowflake.net/s/question/0D50Z00009T38Z5SAJ/when-i-try-to-connect-to-snowflake-using-snowsql-with-using-user-credentials-getting-error-message-related-to-saml-response-is-this-user-privilege-issue 
This error may happen if your user name is incomplete (e.g. domain name is missing).
