### ISSUE TITLE
Properties: Columns (Structure): Drag & drop row to change field order

### ISSUE THREAD

**Issue by erlangp** [dbeaver/dbeaver#7232]
(like phpMyAdmin)

**Comment by serge-rider** [comment]
I believe you meant "drag & drop column".

This is already supported.
You can drag by column icon or with CTRL key pressed.

**Comment by erlangp** [comment]
@serge-rider i tried & it does not work

**Comment by erlangp** [comment]
OS: Windows 8
DBeaver: 6.2.5

**Comment by erlangp** [comment]
how to re-open this issue? :(

**Comment by erlangp** [comment]
waiting for respose @serge-rider
