### ISSUE TITLE
Query not run after connecting to DB

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#7233]
**Steps to reproduce:**
* Configure DBeaver to have at least 2 DB connections saved.
* Connect to one database, run some query from the SQL editor.
* Switch to the other database from the drop-down menu above the SQL editor.
* Run the same query by pressing Ctrl + Enter.

**Expected behavior:** should connect to the new database and run the query on it once it's connected.

**Actual behavior:** will connect to the new database, but the query will not be run until a further Ctrl + Enter or run button is pressed after the connection is already established.

**Setup:** DBeaver 6.2.4, running on windows 10. I recall this was not an issue on previous versions.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by serge-rider** [comment]
Can't reproduce. Perhaps you have non-standard settings. E.g. disabled "connect on editor activation" and enabled "connect on query execute" options.
Please provide more info.

**Comment by david-cortes** [comment]
I think I'm using the default settings:
![sql_editor_settings](https://user-images.githubusercontent.com/11860098/69214814-a161b800-0b70-11ea-9688-affbb26d91b1.png)

**Comment by uslss** [comment]
seems that issue isn't reproducible.
if it is still actual for you - feel free to reopen the ticket
