### ISSUE TITLE
Appending extra precisions in real values in Ms SQL

### ISSUE THREAD

**Issue by soundarraj92** [dbeaver/dbeaver#7237]
![DBeaver real issue 2019-11-18 120124](https://user-images.githubusercontent.com/47522802/69031717-bfa8a600-0a00-11ea-9861-7e10c7949746.jpg)

#### System information: 
- Operating system (distribution) and version
Microsoft Windows 10 Version 1809
- DBeaver version
DBeaver Version 6.2.4.201911031605
- Additional extensions
Nothing

#### Connection specification:
- Database name and version
Microsoft SQL Server - Microsoft SQL Azure (RTM) - 12.0.2000.8 
- Driver name
mssql-jdbc-7.4.1.jre8.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
Organizational proxy
#### Describe the problem you're observing:
Real values from DB are shown with extra duplicate precisions that are not present in table.
DBeaver just appends precision values automatically. These values are not coming when checking DB from JPA or DBVisualizer tool.

#### Steps to reproduce, if exist:
Declare @Lat real ='11.04897'
Select @Lat

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
This happens because of float->double conversion. This conversion happens in Java DecimalFormat, it don't support float formatting and converts it to double first.

Perhaps we need "native numbers format" option to eliminate such problems.

**Comment by serge-rider** [comment]
Also related to #7214

**Comment by kseniiaguzeeva** [comment]
Resultset still shows "extra" numbers. (chevked on SQL Server
![dbeaver_3Y61TP3J4Y](https://user-images.githubusercontent.com/51405061/70687541-8a6e3b80-1cc0-11ea-9b19-0fffbf02de30.png)
)

**Comment by serge-rider** [comment]
We definitely need "native numbers format" option. We'll try it in the next release.

Workaround: use double precision numbers (DOUBLE PRECISION instead of REAL).

**Comment by serge-rider** [comment]
Done
![image](https://user-images.githubusercontent.com/6398845/74057054-2633d380-49f4-11ea-95ce-685e341985a5.png)

**Comment by uslss** [comment]
verified
