### ISSUE TITLE
Fix 'Version update' dialog text: "More Info" button is not present

### ISSUE THREAD

**Issue by MrGroovy** [dbeaver/dbeaver#7238]
#### System information: 
- Windows 10
- 6.2.4
- Additional extensions: None

#### Connection specification:
None

#### Describe the problem you're observing:
The 'Version Info' dialog contains te text:

> Press "More Info" to open the web page where you can download 6.2.5

But, only the buttons 'Upgrade...', 'Details...' and 'Close' are present.

#### Steps to reproduce, if exist:
None

#### Include any warning/errors/backtraces from the logs
None

**Comment by nmat** [comment]
I reported the same in: https://github.com/dbeaver/dbeaver/issues/6451

**Comment by serge-rider** [comment]
It was fixed in #7155
But by weird accident the fix presents only in 6.2.4 branch. Now moved to devel.

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by mikedepetris** [comment]
![image](https://user-images.githubusercontent.com/19190720/70135753-f7fbe580-168a-11ea-9051-b97114d8f8ed.png)
Again from 6.2.5.2... to 6.3.0
