### ISSUE TITLE
PPA upgrade warning: Directory not empty

### ISSUE THREAD

**Issue by skyghis** [dbeaver/dbeaver#7239]
## System information: 
- Ubuntu v19.10
- DBeaver v6.2.5
- No plugins or extension installed manually.

#### Describe the problem you're observing:

When updating using the PPA, some plugins files are not removed and create a warning when trying to remove directory.

```log
Unpacking dbeaver-ce (6.2.5~ubuntu16.04) over (6.2.4~ubuntu16.04) ...
dpkg: warning: unable to delete old directory '/usr/share/dbeaver/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.1000.v20190125-2016': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/dbeaver/plugins/org.eclipse.equinox.security.linux.x86_64_1.1.200.v20181106-0957': Directory not empty
```

The files `eclipse_1801.so` and `libkeystorelinuxnative.so` locks directory deletion.

I guess that theses files need to be added to the list of files to remove, or a `rm -rf`should be used in the upgrade script.

For information I report this issue only now but multiples upgrades lead to the same kind if warning.

Previous upgrade have warnings about these directories:
- `/usr/share/dbeaver/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.1100.v20190907-0426/`
- `/usr/share/dbeaver/plugins/org.eclipse.equinox.security.linux.x86_64_1.1.300.v20190830-1238/`

#### Steps to reproduce, if exist:

Upgrade version from PPA from console to see warnings.

**Comment by uslss** [comment]
if the issue is still actual - feel free to reopen the ticket or create a new one.
