### ISSUE TITLE
Oracle NUMBER column without precision/scale rendered as zero

### ISSUE THREAD

**Issue by oniony** [dbeaver/dbeaver#7240]
#### System information: 
- Windows 10
- DBeaver 6.2.1.201909221630
- Additional extensions

#### Connection specification:
- Oracle
- ojdbc-full Oracle JDBC Thin 12.1.0.2 

#### Describe the problem you're observing:

When I query a table that has a column of type NUMBER (no precision/scale) and the data is less than zero (e.g. 0.0005), the value is rendered as exactly zero. Even if I set the minimum number of decimal places it's still shown as zero.

#### Steps to reproduce, if exist:

CREATE TABLE example
(
    num NUMBER
)

INSERT INTO example
VALUES (0.0005);

SELECT * FROM num;

Value displayed as zero in grid. (Displayed correctly in text view.)

**Comment by serge-rider** [comment]
Can't reproduce.
Please upgrade to the most recent version. If it still won't work - check data formatting property page:
![image](https://user-images.githubusercontent.com/6398845/69126131-7f0c6380-0ab8-11ea-9f21-91bb4793017c.png)

**Comment by oniony** [comment]
My apologies. You are indeed correct it is fixed in 6.2.5.
