### ISSUE TITLE
Timestamp column editing scale doesn't persist

### ISSUE THREAD

**Issue by gareth-ib** [dbeaver/dbeaver#7242]
#### System information: 
Windows 10
DBeaver version 6.2.4
#### Connection specification:
Postgres 11
#### Steps to reproduce, if exist:

Setting scale for a timestamp doesn't save the timestamp. This is needed to remove the microseconds from a timestamp field in postgres. I mostly use this to set it to zero, but it also doesn't work with positive numbers.

![image](https://user-images.githubusercontent.com/29517750/69079811-a4816a80-09ef-11ea-8098-b769943831a5.png)

That resulting command should be
```sql
ALTER TABLE exacttarget.message ALTER COLUMN update_date TYPE timestamp(0) USING update_date::timestamp;
```

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
