### ISSUE TITLE
Mysql: SQL_NO_CACHE directive doesn't work

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#7243]
The problem happens in MySQL 5.7. When I execute a query with SQL_NO_CACHE directive the directive has no effect. For example:

`SELECT SQL_NO_CACHE DISTINCT shipping FROM orders;`

The table is quite large and query normally executes in about 300ms but on subsequent runs it executes very fast - a few ms. The problem is it should always run 300ms because SQL_NO_CACHE should disable the cache. It seems I can't turn off the query cache when I run queries from DBeaver.

I tested the same in other database tools on the same server and the SQL_NO_CACHE directive is respected.

**Comment by uslss** [comment]
is it still actual?

**Comment by lemon-juice** [comment]
I've just checked with the latest version and it still is. But I remember that on many occasions SQL_NO_CACHE worked so after doing a few tests it looks like queries with DISTINCT are problematic:

`SELECT SQL_NO_CACHE DISTINCT shipping FROM orders;`

in the above query SQL_NO_CACHE has no effect. But in this query:

`SELECT SQL_NO_CACHE SUM(shipping_cost) FROM orders;`

it works.

**Comment by uslss** [comment]
It seems issue is obsolete for now
