### ISSUE TITLE
postgres invalid date format is converted to "random" date

### ISSUE THREAD

**Issue by fasmit** [dbeaver/dbeaver#7244]
Hi,

When editing a postgres date column and entering an erroneous date like 20-03-2020 (march 20th 2020 the wrong way around) DBeaver will replace this with 0025-09-10 (sep 10 25AD), presumably 0020-03-01 plus 2020 days. I'd expect an error on invalid date.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by serge-rider** [comment]
Good point. 
Java date parser is lanient by default. In some cases it parses poorly-formed dates in Julian calendar.
I'll disable this behavior.

**Comment by kseniiaguzeeva** [comment]
Verified
