### ISSUE TITLE
Oracle: Table trigger couldn't be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7245]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.5

#### Connection specification:
- Database name and version oracle

#### Describe the problem you're observing:
Table trigger couldn't be created using UI due to error
![image](https://user-images.githubusercontent.com/31996417/69132929-10360700-0ac6-11ea-8496-6218f5c3271c.png)
error log is empty

**Comment by serge-rider** [comment]
Fixed (it is not possible to create table trigger on schema level)

**Comment by uslss** [comment]
verified
