### ISSUE TITLE
allow installation of plugins

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#7246]
I miss being able to convert strings to different formats.
In Eclipse this feature is provided by AnyEdit Tools but I was unable to install it in DBeaver.

Would it be possible to either add a similar functionality or just allow installation of plugins?

**Comment by 2019-05-10** [comment]
![convert_string](https://user-images.githubusercontent.com/50481865/69136047-73ba3780-0aba-11ea-9f2c-1507e718a9c3.png)

Screenshot of AnyEdit's convert options

**Comment by serge-rider** [comment]
Please describe whay exactly your weren't able to install plugin in dbeaver. This feature is there for years (main menu Help->Install new software).

**Comment by 2019-05-10** [comment]
Using 
http://andrei.gmxhome.de/eclipse/
directly or via marketplace ends in both cases with the same error:

![marketplace](https://user-images.githubusercontent.com/50481865/69235256-442a2e80-0b91-11ea-8af3-63132839fbfe.png)

**Comment by 2019-05-10** [comment]
Forgot: I was able to install that same plugin via marketplace in Eclipse!

**Comment by serge-rider** [comment]
Thanks for details. 
Indeed we missed a couple of P2 plugins which are used for proper discover legacy P2 update sites (however dbeaver works fine with all modern update sites formats).
Will add in the next version.

**Comment by uslss** [comment]
verified
