### ISSUE TITLE
Liquibase changelog: Non-DDL report isn't refreshed according to the changes

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7247]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.5

#### Describe the problem you're observing:
Non-DDL report isn't refreshed according to the changes
#### Steps to reproduce, if exist:
1. Generate Changelog
2. Uncheck some items - refresh report
3. Check DDL report - unchecked item isn't shown
4. Check non-DDL report - unchecked item still shown. Report isn't refreshed

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
