### ISSUE TITLE
Connection Settings do not save after upgrading from v6.2.4 -> v6.2.5

### ISSUE THREAD

**Issue by charukiewicz** [dbeaver/dbeaver#7251]
#### System information: 
- Operating system (distribution) and version: Arch Linux
- DBeaver version: 6.2.5
- Additional extensions

#### Connection specification:
- Database name and version: MySQL 5.*
- Driver name: JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH tunnel

#### Describe the problem you're observing:

After upgrading DBeaver from v6.2.4 to v6.2.5 (by downloading the latest `.tar.gz` and replacing the contents of `/usr/share/dbeaver`), any edits to the connection settings do not persist between DBeaver restarts. For example, I can rename or edit a connection host and it will save for the duration of the DBeaver session, but when closing and re-opening the program, the settings revert to what they were prior to the edit.

Note that I have used this upgrade method for 6.1.3, 6.1.4, 6.1.5, 6.2.0, 6.2.1, 6.2.2, 6.2.3, and 6.2.4 and never experienced this issue.

#### Steps to reproduce, if exist:

1. Have existing connection settings from DBeaver 6.2.4
2. Edit connection setting (e.g. rename or change host)
3. Save edit
4. Restart DBeaver 6.2.5

#### Include any warning/errors/backtraces from the logs

N/A

**Comment by plao** [comment]
Hi, same issue for me! Version 6.2.5.201911102152

**Comment by serge-rider** [comment]
I can't reproduce it. Please check error/debug logs for anything related.
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by charukiewicz** [comment]
Looks like this was caused by the existence of a `.data-sources.json.bak` file (according to Java error in `~/.local/share/.DBeaverData/workspace6/.metadata/dbeaver-debug.log`

The fix for this issue:

```
rm ~/.local/share/.DBeaverData/workspace6/<project name>/.dbeaver/.data-sources.json.bak
```

**Comment by plao** [comment]
Hi @charukiewicz , many thx! I will have a look tomorrow and I will provide here my feedback.

**Comment by anderssnp** [comment]
> Looks like this was caused by the existence of a `.data-sources.json.bak` file (according to Java error in `~/.local/share/.DBeaverData/workspace6/.metadata/dbeaver-debug.log`)
> 
> The fix for this issue:
> 
> ```
> rm ~/.local/share/.DBeaverData/workspace6/<project name>/.dbeaver/.data-sources.json.bak
> ```

@charukiewicz Thanks!

I had exactly the same problem on my Mac, and this helped me solve the problem. Some minor differences:
location of the file was:
~/Library/DBeaverData/workspace6/General/.dbeaver/.data-sources.json.bak

So, on Mac, please do rm ~/Library/DBeaverData/workspace6/General/.dbeaver/.data-sources.json.bak.

**Comment by plao** [comment]
@charukiewicz: as promised, here the last feedback from my side: deleting this .bak file does the trick, now all then changes are saved and retained after a restart...

One more time, thanks a lot!

**Comment by jzielke84** [comment]
@serge-rider So bug is confirmed?

**Comment by serge-rider** [comment]
Thanks for the details.

@charukiewicz coudl you post exact java error from the log? with stacktrace.

**Comment by serge-rider** [comment]
Never mind, I found it.
If anyone still have thus problem please test Early Access version (https://dbeaver.io/files/ea)

**Comment by JulienFr** [comment]
On Linux Fedora with snap, solved by

- deleting  ~/snap/dbeaver-ce/225/.local/share/DBeaverData/workspace6/General/.dbeaver/data-sources.json.old
- adapting permissions on data-sources.json
