### ISSUE TITLE
URL Template for AWS Athena Isn't Used

### ISSUE THREAD

**Issue by shawnweeks** [dbeaver/dbeaver#7252]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: Eclipse Plugin 6.2.5.201911171645
- Additional extensions

#### Connection specification:
- Database name and version: AWS Athena
- Driver name: com.simba.athena.jdbc.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Tried both ways

#### Describe the problem you're observing:

I need to specify a custom URL for Athena but any changes to the URL Template are ignored and the url tried still includes jdbc:awsathena://AwsRegion=[Region];

**Comment by shawnweeks** [comment]
On a related note SSH Tunnel also doesn't work for Athena and looking in the source it doesn't even try. This breaks things if you're trying to use Athena from inside of AWS and need to specify a custom endpoint.

**Comment by serge-rider** [comment]
Indeed, we build Athena URL according to connection parameters, URL isn't used by driver.
Because it is usually used in AWS environment where you don't need to provide custom URL.

The tricky part is Simba driver. Anyhow, we need to take a look into it.

**Comment by shawnweeks** [comment]
I think if you just use the URL Template and set it to AWSRegion= we'll be fine. The Simba driver says if you specify AWSRegion it overrides any other parameters. One reason to need a custom url is if your running DBeaver on a machine at AWS and need to specify a custom vpc endpoint. Or if your running on prem with custom endpoints due to security requirements.

**Comment by shawnweeks** [comment]
No idea what to do about the port 444 going over ssh though. We have an issue where port 444 is blocked on our entire network and we're not able to get it changed so sshing to an AWS box was the easiest way to make it work.

**Comment by serge-rider** [comment]
Fixed. Now DBeaver uses URL template from driver settings.
Also I've updated driver version to the most recent (2.0.9).

In regards to SSH tunnels. I didn't test it as we don't have such environment.
But you could try to play with `StreamingEndpointOverride` parameter (use `{port}` variable in URL template to let dbeaver to override it in case of enabled SSH tunnel):
See docs https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.9/docs/Simba+Athena+JDBC+Driver+Install+and+Configuration+Guide.pdf

Please let me know if it works.

**Comment by uslss** [comment]
closed without testing
