### ISSUE TITLE
Why is viewing data tab modifying data?

### ISSUE THREAD

**Issue by stevewarsa** [dbeaver/dbeaver#7254]
DBeaver 6.0.4.201905052017 (Windows 10 64bit).

Just curious why when viewing the table data (not a SQLEditor tab), the minute I click on the 'Data' tab, DBeaver creates a pending transaction (which is just a select statement in the form of "SELECT x.*,x.ROWID FROM SCHEMA.TABLE"?

**Comment by serge-rider** [comment]
DBeaver doesn't create any explicit transactions. If you are in non-auto-commit mode then such transaction is started implicitly by database server. No data modifications are needed for that.

Perhaps transaction manager UI (in main toolbar) confuses you.
Its behavior was changed in version 6.2.

**Comment by SebAlbert** [comment]
I think (and hope) the title of this issue is misleading. It would be very alarming if data were *modified* when viewed. Opening a transaction is not the same as really modifying data.
