### ISSUE TITLE
Impala driver template's queries parameter makes errors

### ISSUE THREAD

**Issue by dzzzzzy** [dbeaver/dbeaver#7255]
#### System information: 
- Operating system (distribution) and version:  Windows 10
- DBeaver version: 6.2.5
- Additional extensions: none

#### Connection specification:
- Database name and version: impala
- Driver name: com.cloudera.impala.jdbc41.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
Impala schema selection "Mark as Active" broken
#### Steps to reproduce, if exist:
1. Set up working JDBC connection to Cloudera Impala.
2. Expand the new data source.
3. Right click on a schema which does not on active, click Mark as Active.

Show errors:
![48517b2511e5c44710d8bbf832b98cf](https://user-images.githubusercontent.com/19354905/69206536-ea713680-0b87-11ea-8d59-e7b5b1cfbca0.png)

I think the default driver template's queries parameter was worng:

![de92988647d2f2be69e2142e2a13e87](https://user-images.githubusercontent.com/19354905/69206624-23111000-0b88-11ea-872a-869908d99c3d.png)

After change the `Set active database` value from `use [?]` to `use ?`, then do the steps again, it works!

**Comment by serge-rider** [comment]
Thanks for the bug report.
Fixed
