### ISSUE TITLE
the menu disapeared after mvn package

### ISSUE THREAD

**Issue by mxwmwx** [dbeaver/dbeaver#7256]
use eclipse debug,it was this
![image](https://user-images.githubusercontent.com/37258498/69212942-a12be180-0b9d-11ea-8a3b-bfcbbe8921f1.png)
after mvn package
![image](https://user-images.githubusercontent.com/37258498/69213001-d0425300-0b9d-11ea-8837-921463fdd1b2.png)
Would  you like to  tell me where is the relevant plugin configured? (I modified some codes,but never touch the code in features and product)

**Comment by serge-rider** [comment]
Try to reset UI settings (menu File).

**Comment by mxwmwx** [comment]
after mvn package the whole menu deapeared, there is no File menu and others menu

**Comment by mxwmwx** [comment]
> Try to reset UI settings (menu File).

after mvn package the whole menu deapeared, there is no File menu and others menu

**Comment by uslss** [comment]
@mxwmwx you could try this https://dbeaver.com/docs/wiki/Reset-UI-settings/

**Comment by mxwmwx** [comment]
> @mxwmwx you could try this https://dbeaver.com/docs/wiki/Reset-UI-settings/

thank you! I got it
