### ISSUE TITLE
Diagram relationship notation connect to columns

### ISSUE THREAD

**Issue by Snewbik** [dbeaver/dbeaver#7257]
Dbeaver actualy uses only IDEF1X notation in DB diagram view and I am really missing the "connect to columns" available in MySQL Workbench. Even if Workbench is slow and especially buggy and not fully compatible with other DB, not even mariadb, I am still forced to use it because of this only feature. And I didn't find any better replacement yet. Dbeaver is fast, reliable and to me as a eclipse using developer is very intuitive and comfortable, but still I need some other tool to work with DB, if this feature is not implemented 
 
I am working with databases and especially with MySQL and later its fork mariadb more than 15 years and (re)designed couple of complex relationship dbmodels. By designing new DB model, or reversed engineering of existing one it is very important to see exact column relationships directly from the picture. Especially when foreign keys have not the same or similar names as the keys to which they are connected (not everybody is following good and readable naming conventions). The IDEF1X has not the ability to show it directly and get the right view. 

I would like to have the possibility to switch between the relationship notation views, like it is possible in MySQL workbench. 

If it is possible, I would like to contribute as developer or leader to implement this feature, because it will save me a lot of time switching between different tools in future development. So if is already someone working on this feature just contact me for any help that I can provide. 

Thanks

**Comment by serge-rider** [comment]
Probably will be a part of our planned general ERD rendering redesign.

**Comment by hhhien2903** [comment]
Hoping this feature request will be released soon. Thanks so much for created DBeaver.

**Comment by Destrolaric** [comment]
Got an update about this functionality. This was added as experimental feature in recent versions of DBeaver. This can be enabled by using Mikami-Tabuchi as routing algorithm.

**Comment by Destrolaric** [comment]
Will be closed with #16493

**Comment by sleazonator** [comment]
Hi, I am new to GitHub, so apologies if I am not commenting on this correctly. Was #7257 resolved to diagrammatically show the relations between columns (such as with mySQL)? For me its very annoying this functionality is not present in the latest version. 22.1.1

**Comment by Destrolaric** [comment]
@sleazonator Currently it is disabled by default, due to being in need of polishing you can change routing settings in ERD Settings 
![image](https://user-images.githubusercontent.com/20579256/177288064-9d179d1a-2aef-4653-8515-f6c90126f4bd.png)

**Comment by ddoddsr** [comment]
Is this available in version   Version 26.0.0.202603011816 ? Is there a  setting to make this option show?
