### ISSUE TITLE
Editor layout not restored after restart.

### ISSUE THREAD

**Issue by Evil2000** [dbeaver/dbeaver#7258]
#### System information: 
- Windows 10
- DBeaver 6.2.5
- w/ Office integratiom

#### Connection specification:
- Database: Firebird or MySQL but doesn't matter

#### Describe the problem you're observing:
When selecting the vertical layout in the editor (having the script on the left side and the results on the right) and closing/opening DBeaver again, the layout is horizontal again. When selecting the context menu and looking into the "Layout" submenu it still states the layout should be vertical.
To get the vertical layout back again, "horizontal" must be selected first and "vertical" second.

#### Steps to reproduce, if exist:
See problem desctiption.

#### Include any warning/errors/backtraces from the logs
![grafik](https://user-images.githubusercontent.com/697191/69221958-c0fcde80-0b78-11ea-89ba-3fca7954dad8.png)
![20191120_0943_08](https://user-images.githubusercontent.com/697191/69223327-70d34b80-0b7b-11ea-9c79-a16025b93de2.gif)

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by serge-rider** [comment]
Fixed (we'll use global prefs store for this option)

**Comment by uslss** [comment]
verified
