### ISSUE TITLE
DBeaver Crash after loading screen 

### ISSUE THREAD

**Issue by mamahnxarya201** [dbeaver/dbeaver#7259]
#### System information: 
- Pop OS 19.10
- DBeaver version Community Edition 6.2.5

#### Describe the problem you're observing:
I installed DBeaver via .deb package after the installation is complete i try to open.
Loading screen was show up but after loading screen complete the DBeaver crash and make the OS hang

**Comment by serge-rider** [comment]
This is probably related to Pop OS. It is not officially supported.
Are there, by any chance, any logs/error messages left?

**Comment by mamahnxarya201** [comment]
unfortunately no after the crash i have to restart the laptop because the OS just hangs 
the OS itself is Ubuntu based so i think it should handle it very well

**Comment by SebAlbert** [comment]
Can you observe memory usage while starting DBeaver? e.g. via a small window running `htop` or similar? "Out of memory" is oftentimes also perceived as "the OS hangs" (and quite terribly so) on Linux.

**Comment by mamahnxarya201** [comment]
> Can you observe memory usage while starting DBeaver? e.g. via a small window running `htop` or similar? "Out of memory" is oftentimes also perceived as "the OS hang

![IMG_20191130_172509](https://user-images.githubusercontent.com/55610290/69899273-6ba1a800-1396-11ea-90f0-32e9fabd25d8.jpg)

now it can runs ! i dont know why sometimes it just make my laptop crash (i am gonna try on 8 GB ram with same Linux Distro to see if its my laptop problem)
meanwhile iam gonna update to 6.2.5 and see if the problem solved
