### ISSUE TITLE
[Wayland/GTK] Massive titlebar

### ISSUE THREAD

**Issue by p1u3o** [dbeaver/dbeaver#7262]
#### System information: 
- Fedora 31 (31.20191121.0) 
- Dbeaver 6.2.5

#### Describe the problem you're observing:

Under Wayland, the GTK backend seems to have a massive title bar, this didn't occur under 6.2.4. 

#### Steps to reproduce, if exist:

Run 6.2.5 under GNOME Wayland and observe the titlebar.
![dbeaver_titlebar](https://user-images.githubusercontent.com/38067056/69324848-1a304500-0c41-11ea-84f0-2cda7a786376.png)

**Comment by serge-rider** [comment]
Well, I don't understand what is wrong with title bar. How did it look before?

**Comment by p1u3o** [comment]
Here's how 6.2.4 looked.

I've highlighted over maximize as it makes the bug easier to see.

![Screenshot-20191125092331-1606x885](https://user-images.githubusercontent.com/38067056/69528087-82df3080-0f65-11ea-8bae-4e5a59f2e4c3.png)

This might actually be a SWT bug.

**Comment by uslss** [comment]
@p1u3o is it still actual?

**Comment by p1u3o** [comment]
![image](https://user-images.githubusercontent.com/38067056/80288201-41c69480-872e-11ea-84cb-3a6a043e33c4.png)


Yep with 7.0.3. I spun up a quick Fedora 32 VM in GNOME Boxes.

That's Rhythmbox behind it, both are running natively on Wayland.

**Comment by jonnyso** [comment]
Same problem here, managed to reproduce it flatpack, snap and rpm versions, only on wayland.

**Comment by p1u3o** [comment]
Upstream SWT issue

https://bugs.eclipse.org/bugs/show_bug.cgi?id=563401

**Comment by uslss** [comment]
seem it is duplicate of #6581
