### ISSUE TITLE
Navigation through SQLEditor tabs 

### ISSUE THREAD

**Issue by michalk-k** [dbeaver/dbeaver#7263]
Is there a feature allowing easy navigation across opened documents?
I didn't find anything quick to use. There is a list of all opened scripts but it's pretty cumbersome.

1. Mostly I don't get a convention of marking some files with "bold" style on this list. It's really hard to find the file 'cause it seems it moves from one location on the list to another
2. I would like to be able to quickly navigate through the tabs. For example scroll them using mouse roller. Is it possible? Does it depend on OS (Ubuntu and Windows in my case) or on application's implementation
3. Filename of a script loaded into tab cannot fit a tab, because it's prefixed by db name the script is connected to. Is there a way to configure this appearance? ie smaller font? I know the name is finally displayed on application bar, but it doesn't help in  finding particular tab to be enabled.

with regards

**Comment by serge-rider** [comment]
1. Could you show some examples? I don't think we mark editor tabs with bold. At least intentionally.
2. Generally there are <kbd>CTRL+E</kbd> and <kbd>CTRL+SHIFT+E</kbd> commands for editor switch.
3. You can customize it in preferences: 
![image](https://user-images.githubusercontent.com/6398845/69438575-55706800-0d56-11ea-934c-ef0c57c979c5.png)

**Comment by uslss** [comment]
there is no updates on ticket more than a month.
ticket closed
