### ISSUE TITLE
NPE when connect to Mysql (old)

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7265]
#### System information:  
- Operating system (distribution) and version Windows 10
- DBeaver version 6.2.5

#### Connection specification:
- Database name and version Mysql (old)

#### Describe the problem you're observing:
1. JNPE appears if make double click on Mysql (old) in New Database connection.
2. Database connection Wizard btns stop working if to select Mysql (old) in New Database connection and press Next btn:
Steps:
Open New Database connection, select Mysql (old) and Press Next btn
Actual result:
-Next step of Wizard doesn't open.
-Next, Finish btns become non-active on other Databases too. 
#### Include any warning/errors/backtraces from the logs
 
![2TTgYBWqxb](https://user-images.githubusercontent.com/51405061/69323554-004e2c80-0c58-11ea-9817-16e39bd979be.gif)
![X2gg4G87mn](https://user-images.githubusercontent.com/51405061/69323555-004e2c80-0c58-11ea-9f63-7186010f9006.png)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3873814/dbeaver-debug.log)
[.log](https://github.com/dbeaver/dbeaver/files/3873815/default.log)

**Comment by stefanuhrig** [comment]
I'm having the same issue.

Seems to have stopped working with 34f261bd85eb2a0b9ac1c6195c73a7ce0ff7dd13.

**Comment by serge-rider** [comment]
Fixed (it happened only in EA version)

**Comment by kseniiaguzeeva** [comment]
Verified
