### ISSUE TITLE
Schema permissions

### ISSUE THREAD

**Issue by michalk-k** [dbeaver/dbeaver#7266]
Schema properties lacks information about access rights (at least in postgresql)
Can be added?

**Comment by serge-rider** [comment]
Done

**Comment by uslss** [comment]
reopened.
incorrect statement is used to grant/revoke priveleges. Table is used instead of schema
![image](https://user-images.githubusercontent.com/31996417/73186273-7e372400-4130-11ea-854c-9c94163365e7.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
