### ISSUE TITLE
MySQL show .0 in datetime

### ISSUE THREAD

**Issue by sirber** [dbeaver/dbeaver#7268]
### System information: 
- Operating system (distribution) and version
Windows 10 x64
- DBeaver version
6.2.5
- Additional extensions

#### Connection specification:
- Database name and version
MySQL 5.7
- Driver name
MySQL 5.1.44
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
Datetime simetimes shows with a .0 suffix

![image](https://user-images.githubusercontent.com/3911428/69338809-f44f7400-0c31-11ea-8757-233d9c5dd2a6.png)
![image](https://user-images.githubusercontent.com/3911428/69338820-f9acbe80-0c31-11ea-9076-be593b11a38a.png)

not showing in HeidiSQL or plain mysql
![image](https://user-images.githubusercontent.com/3911428/69338831-003b3600-0c32-11ea-9418-b59b06fa5ea8.png)
![image](https://user-images.githubusercontent.com/3911428/69338844-05988080-0c32-11ea-9962-0325f2cada50.png)

#### Steps to reproduce, if exist:
Save a datetime like: "2016-01-01 01:01:01.12"
Save a datetime like: "2016-01-01 01:01:01[space]"

**Comment by uslss** [comment]
hi @sirber , do you have any specific settings in date formats preferences?
for me this issue is reproducible only in case of change timestamp pattern
![Screenshot 2019-11-21 16:38:28](https://user-images.githubusercontent.com/31996417/69342801-61d4c200-0c7d-11ea-9dad-31c84bd28e4f.png)

**Comment by sirber** [comment]
I'm on defaults:

![image](https://user-images.githubusercontent.com/3911428/69352683-58326680-0c4b-11ea-833c-957620682f1b.png)
![image](https://user-images.githubusercontent.com/3911428/69352701-5d8fb100-0c4b-11ea-8449-b3b40ac42076.png)

**Comment by serge-rider** [comment]
@sirber please check the same settings in the connection configuration (select connection, press F4).

**Comment by sirber** [comment]
it's the 3rd screenshot

![image](https://user-images.githubusercontent.com/3911428/69357574-4e146600-0c53-11ea-8472-8483a8102fa5.png)

**Comment by R2-G2** [comment]
**System information:**
- Operating system (distribution) and version
Ubuntu 19.04 x64 (Gnome)
Kubuntu 19.04 x64 (KDE)
- DBeaver version
6.1.5
6.3.4
6.3.5
- Additional extensions
no

**Connection specification:**
- Database name and version
Percona/MySQL 5.7
- Driver name
MySQL 5.1.44
- Do you use tunnels or proxies (SSH, SOCKS, etc)?
no
yes (SSH)

**Describe the problem you're observing:**
On Linux we switched from HeidiSQL to DBeaver lately. Using default settings all the way, datetimes and timestamps are shown with a trailing ".0".

**Comment by uphlewis** [comment]
I experience this on Ubuntu + OSX. Default formatting (no trailing `.f`) just like the OP

**Comment by uphlewis** [comment]
Here's a screenshot showing formatting settings, some timestamp columns and their values in DBeaver, and the same data in a mysql shell. This is a fresh DBeaver install on OSX Catalina 10.15.3 (19D76), but experienced exactly the same problem on Ubuntu 18.04 and 19.10.

![image](https://user-images.githubusercontent.com/43346009/75868570-21e6b480-5e00-11ea-8ac9-2ea800c975da.png)

**Comment by serge-rider** [comment]
It is a native timestamp format for old MySQL driver.
Solutions:
- Use MySQL 8 driver
- Disable "Use native date/time format" option in data format settings for your connection

**Comment by uphlewis** [comment]
For anyone else encountering this issue- in my case despite having "Use native date/time format" disabled in global preferences, it was enabled for some reason in the connection settings for each of my databases by default.

![image](https://user-images.githubusercontent.com/43346009/81282062-96351280-9052-11ea-8eea-361ab70607e5.png)

To fix this for a connection, go to "Edit Connection" (right-click in connections pane, or F4) then under "Result Sets -> Data Formatting" enable the checkbox "Datasource {connection_name} settings" which will allow you to disable "Use native date/time format".

![image](https://user-images.githubusercontent.com/43346009/81282758-8669fe00-9053-11ea-9bd9-82bcd171c258.png)

**Comment by sirber** [comment]
thank you!
