### ISSUE TITLE
ResultSet fetch size not editable

### ISSUE THREAD

**Issue by ul3violet** [dbeaver/dbeaver#7269]
Hi everybody,

I've got a little question :
In my toolbar the ResultSet fetch size input is not editable by default, i've got to run once a request in order the input to be editable.

I'm currently using dbeaver 6.2.5 (same pb in 6.2.0)

Do you have an idea how to enable by default this input ?

Thanks in advance

**Comment by ul3violet** [comment]
Solved the problem with 6.1.4 version

**Comment by serge-rider** [comment]
Good point

**Comment by uslss** [comment]
verified
