### ISSUE TITLE
Issue tracking system does not allow exact string search

### ISSUE THREAD

**Issue by Chealer** [dbeaver/dbeaver#7270]
[This issue tracking system](https://github.com/dbeaver/dbeaver/issues) visibly does not allow exact searches. For example, I used the query string "is:issue is:open "connection folder"" to search for all issues about connection folders, but this found 8 open tickets, while only 2 are relevant. This is apparently because GitHub does not feature exact searches (which search engines such as Google web search typically allow by surrounding exact strings with double quotes).

This makes it difficult to search tickets efficiently in a project of this size. I would recommend a project of this size to use a proper issue tracker engine.

**Comment by serge-rider** [comment]
It is GitHub, we can't fix GitHub :)
We have plans to migrate issue tracking to some standalone engine on dbeaver.com/io. Maybe JIRA, maybe something more lightweight.
But till then we can't change anything in issue tracker UI.

**Comment by Chealer** [comment]
@uslss, why was this ticket closed? I just searched using query "is:issue is:open Link with editor", and while ticket #2054 has these 3 words at the start of its title, I had to scroll a page down to see it, below irrelevant reports, in pre-last position.
