### ISSUE TITLE
Confusing "Close" button when creating connection

### ISSUE THREAD

**Issue by Chealer** [dbeaver/dbeaver#7272]
When creating a connection, the "Connect to database" dialog offers a number of buttons at the bottom, including "Finish", "Close" and "Test Connection ...":
![DBeaver Connect to database](https://user-images.githubusercontent.com/486141/69370584-38f80100-0c6c-11ea-800d-5b88798b14b8.PNG)

 The Close button is confusing since it is unclear how its role differs from Finish's. It would be clearer to rename it "Simply close", or with the more standard label "Cancel".

This affects DBeaver 6.2.5.

**Comment by serge-rider** [comment]
Agreed

**Comment by kseniiaguzeeva** [comment]
Verified
