### ISSUE TITLE
not all Triggers are shown

### ISSUE THREAD

**Issue by kstechlinski** [dbeaver/dbeaver#7274]
Hi is htere a bug in dbeaver or only my is having this problem, not all of triggers created on the database are shown in Dbeaver in Schema triggers or table Triggers.

#### System information: 
- WIndows 10
- DBeaver version newest

#### Connection specification:
- Oracle 12c

**Comment by uslss** [comment]
seems that issue is duplicate by #8132 
This ticket will be closed
