### ISSUE TITLE
Sorting issues

### ISSUE THREAD

**Issue by felangga** [dbeaver/dbeaver#7276]
I'm having some sorting issues with int8 column on Postgresql database. 
Number 10 and 30 sorted as varchar I think, but not number 20

![image](https://user-images.githubusercontent.com/14814984/69398437-c8f58380-0d1c-11ea-9af8-bd75e337b09d.png)

![image](https://user-images.githubusercontent.com/14814984/69398473-f17d7d80-0d1c-11ea-8064-52f706a29f2e.png)

**Comment by kseniiaguzeeva** [comment]
Unfortunately can't reproduce it. Please tell your OS.

**Comment by SebAlbert** [comment]
Are there more columns? Maybe you have sorted by another column first. As far as I can tell from two days of using DBeaver, it supports sorting by multiple columns and uses the order in which you clicked on the sorting headers.

**Comment by felangga** [comment]
> Are there more columns? Maybe you have sorted by another column first. As far as I can tell from two days of using DBeaver, it supports sorting by multiple columns and uses the order in which you clicked on the sorting headers.

Hey I just know this feature, and yes this because multiple sorting. Thank you for your information
