### ISSUE TITLE
[BUG] Executing a commented changes data grid

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#7278]
As from screenshot
![image](https://user-images.githubusercontent.com/3930671/69421134-88980480-0d20-11ea-8360-b44f68287812.png)

If i had a datagrid and (accidentally) executed a commented string, i loose datagrid...

**Comment by serge-rider** [comment]
Well, what exactly is a bug? 
If database allows to execute comments (e.g. MySQL) then we can't restrict this. It makes sense in some cases.

**Comment by wiwwo** [comment]
problem is not "executing a comment", problem is loosing the datagrid.
Expected behiavour: "empty query string" in the status bar, no change in the datagrid.

**Comment by SebAlbert** [comment]
Whenever I execute a query, I expect to get a new data grid as a result. If the query happens to be empty, I don't mind (or would maybe even expect it) if I get an empty datagrid as a result.

Why would you execute a query at all (even if it happens to be empty or a comment only) if you don't want to lose your previous datagrid?

**Comment by serge-rider** [comment]
@wiwwo it is not an empty query string, it is a regular query. Comment may be a valuable query.

If you want to see your query on a new tab you can use "Execute in new tab" command (<kbd>CTRL+\</kbd>).
Or you can pin your already open tab and new query will open a new one.

**Comment by wiwwo** [comment]
@serge-rider my point is that this situation should be handled same as
https://github.com/dbeaver/dbeaver/issues/6463 :-)

**Comment by serge-rider** [comment]
@wiwwo This ticket and #6463 are completely different. Because, again, comment is a 100% valid SQL query (in some databases). It has nothing to do with empty query.

**Comment by wiwwo** [comment]
Ok
