### ISSUE TITLE
Unable to start GUI 6.2.5

### ISSUE THREAD

**Issue by AnrDaemon** [dbeaver/dbeaver#7279]
#### System information: 
- Windows 10 64-bit
- DBeaver 6.2.5 portable
- java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

#### Describe the problem you're observing:
Starting `dbeaver.exe`, this message appears:
```
---------------------------
Dbeaver
---------------------------
The Dbeaver executable launcher was unable to locate its 
companion shared library.
---------------------------
ОК   
---------------------------
```

6.2.3 and 6.2.4 do not exhibit such issue, `dbeaver-cli.exe` also works fine.

**Comment by serge-rider** [comment]
Perhaps something went wrong during installation. Try to remove current version completely and install it from scratch (your data won't be lost).

**Comment by AnrDaemon** [comment]
This is a portable install, and I did confirm that files are not changed.

Turned out, it was INI file. I strongly recommend removing version-specific options from it.

**Comment by serge-rider** [comment]
ini file must be replaced in every new version. We cannot avoid version-specific stuff there (it is required by Eclipse platform).

Windows installer makes ini backup.
