### ISSUE TITLE
Feature Request: Improved filter of result set

### ISSUE THREAD

**Issue by GTGeek88** [dbeaver/dbeaver#7281]
When using the small filter icon in the column header of a result set, DBeaver acts like you can filter on multiple column values. It says "Choose value(s) to filter by".  However, you can't shift click or control click, or in any other way that I can see, select multiple values to filter on. But that would be a nice feature. Of course, you can manually type them in, but being able to check them off so that you could filter on two or three or more column values certainly would be sweet.

**Comment by uslss** [comment]
already implemented
