### ISSUE TITLE
[Feature request] "Execute SQL Script from cursor"

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#7286]
There seem to be no way to execute a script starting from a certain point on the editor.
If is either "all or nothing"
I would love the possibility to execute only half script.
It would be amazing to have a "Execute SQL Script from selection", but that might be too much asking.

**Comment by serge-rider** [comment]
You can select part of script and execute it.
So you can select scritp from cursor position to the end (<kbd>ctrl+shift+end</kbd> on windows) and run it with <kbd>alt+x</kbd>.

**Comment by rjdangelo** [comment]
I upgraded to 6.3.2, and observed the behaviour described by wiwwo in macOS 10.15.2 and java 8 update 231.

I reinstalled 6.2.5 where Execute SQL Statement works as intended: it executes the statement where the cursor is located, or the selected text.
