### ISSUE TITLE
Theming problem with colors and texts - Dark

### ISSUE THREAD

**Issue by Yousha** [dbeaver/dbeaver#7287]
### System information: 
- Operating system (distribution) and version: Windows 10 Pro 1903 64-bit on x64 hardware
- DBeaver version: 6.2.5.201911171645
- Additional extensions: -

#### Connection specification:
- Database name and version: SQLite 3
- Driver name: org.xerial:sqlite-jdbc:RELEASE
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Theming problem with colors and texts:

![Untitled](https://user-images.githubusercontent.com/18091267/69530545-71a71b80-0f87-11ea-8790-06f298946536.png)

#### Steps to reproduce, if exist:
1- Open DbEaver
2- Go to Window menu -> Preferences -> click on Appearance tab.
3- Check Enable Theming checkbox and **change Theme to Dark.**
(Keep Color and Font Theme to Default)
4- Click on Apply & Close button.
5- Create a connection (any type)
6- Go to Connection Detail
7- Change Connection Type to **Production**.
8- Finish the wizard.
9- Open your created connection.

#### Include any warning/errors/backtraces from the logs
Nothing.

**Comment by slokhorst** [comment]
This has improved a lot with 6.3.0. There are still some issues though:
![dbeaver](https://user-images.githubusercontent.com/8083666/69947336-beda3e80-14ed-11ea-9e5b-089e5f442145.png)

**Comment by serge-rider** [comment]
Agreed, it looks ugly in dark theme (and honestly it doesn't look very good in light theme as well).
We need some better styling. And probably other default colors.

**Comment by digitaldreamer** [comment]
There's some readability issues with the current dark theme.

https://github.com/dbeaver/dbeaver/issues/6441

Based off of this closed ticket it sounds like it's hard if not impossible to change. If that's the case then I would consider not making it the default.

https://github.com/dbeaver/dbeaver/issues/5114

**Comment by serge-rider** [comment]
Tab folder coloring was fixed.
I also thinking about changing default connection type colors.

**Comment by kseniiaguzeeva** [comment]
Verified
