### ISSUE TITLE
Impossible to select Native Client in MAC OS Catalina

### ISSUE THREAD

**Issue by lherreranetlink** [dbeaver/dbeaver#7288]
#### System information: 
Mac OS Catalina 10.15.1
- DBeaver version: 6.2.5

#### Connection specification:
MySQL

#### Describe your question:
I understand that in order to use mysqldump function I have to specify the path where mysql and mysqldump are, but how am I supposed to select it if i have no access to it from the Finder application.

<img width="1417" alt="Captura de Pantalla 2019-11-25 a la(s) 10 10 30" src="https://user-images.githubusercontent.com/30661966/69557218-d6ed1380-0f6b-11ea-83bf-faf6e05fb815.png">

I mean, how should I select `/usr/local/bin` from here ? 

Is there any way to put the raw path in some text field or something ?

Thanks in advance.

**Comment by tati-kru** [comment]
You need to press Command+Shift+G in the opened Finder window and copy-paste the raw path to appeared pop-up.

**Comment by lqnham** [comment]
> You need to press Command+Shift+G in the opened Finder window and copy-paste the raw path to appeared pop-up.

you are save my life :D

**Comment by eciosilva-pharmanexo** [comment]
> 

Thank you! This solved my issue.

**Comment by eciosilva-pharmanexo** [comment]
> You need to press Command+Shift+G in the opened Finder window and copy-paste the raw path to appeared pop-up.

Thank U! This solved my issue.

**Comment by loftywaif002** [comment]
Solved my issue on Mac Ventura  for DBeaver version: 23.1.2.202307091549

I provided the following path:

`/usr/local/bin/`
