### ISSUE TITLE
Values are mixed up/changed after Data Editor reopening

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7290]
### System information: 
- Windows 10
- DBeaver version 6.3.0
- Postgres, MySQL

#### Describe the problem you're observing:
Values of Varchar, int8, data types are changed in a table after Data Editor reopening:
-the raw order is changed;
-some cell values are removed, other cell values are copied in other cells of the same column.

#### Steps to reproduce, if exist:
1.  Create a new /open an existed table in Data Editor.
2. Fill/edit some values of varchar/int8/data types in a table of Data Editor
3. Reopen the table.

**Comment by serge-rider** [comment]
It is not actually a bug. Side effect of virtual PK + unique value duplicate
