### ISSUE TITLE
[Regression bug] Double clicking on a table in DB Navigator always shows table data

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#7291]
If i select to see table properties, i expect that every time i double click on a table in DB nav, i always see the properties, not the data. This was default behavior i am pretty sure to remember.

**Comment by uslss** [comment]
hi @wiwwo 
you could change this behavior in Preferences
![image](https://user-images.githubusercontent.com/31996417/80001601-39205500-84c7-11ea-9a84-d8c5f37eaab2.png)
sorry for the late response
