### ISSUE TITLE
6.2.5 performance issues while openinng tables in MSSQL

### ISSUE THREAD

**Issue by andrzejdziekonski** [dbeaver/dbeaver#7292]
While opening the table view there is always "Read data" background job starting. Problem is when it's big table it runs very long. It's impossible to do any operations on data (filtering/sorting) during that time. It's a pain to always klick there and kill the job to do soemthing. It wasn't like that in previous releases. 

Ubuntu 16.04

**Comment by serge-rider** [comment]
If you open editor by <kbd>F4</kbd> or conext menu->Edit object then previous active tab will be opened.

Also you can change default ab in preferences: 
![image](https://user-images.githubusercontent.com/6398845/69817212-2b61ee80-120b-11ea-9c7b-d577802e8b2d.png)
