### ISSUE TITLE
SQL Editor templates UTF8 support

### ISSUE THREAD

**Issue by abutic** [dbeaver/dbeaver#7294]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.2.5
- Java version: openjdk version "11.0.5"

#### Describe the problem you're observing:
SQL Editor templates are not persisted using UTF-8 encoding.

#### Steps to reproduce, if exist:
1) save a new SQL Editor template, containing non-ASCII characters
2) use a template by typing its name in SQL Editor, followed by a TAB -> everything works fine
3) restart DBeaver
4) use a template again, the same way used in step 2) -> non-ASCII characters are not shown right

**Comment by uslss** [comment]
thanks for the bug report

**Comment by ArtyomPanfutov** [comment]
I would like to tackle this one

**Comment by serge-rider** [comment]
@ArtyomPanfutov thanks for PR

**Comment by uslss** [comment]
verified for newly created templates.
still reproducible for the previously created
