### ISSUE TITLE
[BUG] ER-Diagram keeps throwing exception "Cannot find table" for tables that are long gone

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#7295]
I keep getting this error
![image](https://user-images.githubusercontent.com/3930671/69633298-3f152580-1050-11ea-8150-815e88a02cc6.png)
but tables mentioned in error are gone since long time, and i cannot find a way to tell diagram editor to ignore them.
Hitting "refresh" does not solve the problem.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by wiwwo** [comment]
As realted (?) bug, i cannot save a Diagram as png, i have this error:
![image](https://user-images.githubusercontent.com/3930671/69647202-590f3200-1069-11ea-9aa1-b6dcafab9a50.png)
And file .png is generated empty

**Comment by uslss** [comment]
cannot reproduce it on win. What is your OS? Is this issue appears both for custom and usual ERDs?

**Comment by wiwwo** [comment]
Keeping trying with othe3r formats, and now i receive
![image](https://user-images.githubusercontent.com/3930671/69647462-d470e380-1069-11ea-825b-36ba0fe1fdeb.png)

Linux Ubuntu Mint 18.04.
Not sure what you mean with "custom and usual ERDs"

**Comment by uslss** [comment]
Custom ERD - diagram created by user, and as usual i mean ERD that available for table/schemas/etc.
btw, it reproducible for both of it.
thanks for bug report once again :)

**Comment by serge-rider** [comment]
This error must disappear once you will save your diagram again.

Anyhow, I'll replace this error message with debug warning to avoid dummy error messages.

**Comment by uslss** [comment]
verified
