### ISSUE TITLE
Turkish characters 

### ISSUE THREAD

**Issue by HakanDOGAN1981** [dbeaver/dbeaver#7298]
Turkish charaters are garbled.

when i run SQL editor SELECT 'ŞŞğğĞĞİİÜÜÖÖüüööÇÇçç' aa FROM dual;
result panel shows ������������

## System information: 
- Windows 10
- v6.2.5
- Additional extensions

#### Connection specification:
- Firebird v3.04
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
seems to be duplicate of #6683 
Press alt+enter to see file character set (cp1251 or UTF-8 is ok).
You can configure default charset in preferences:
![image](https://user-images.githubusercontent.com/31996417/69729725-e5882600-1137-11ea-897a-185db2996b76.png)

**Comment by HakanDOGAN1981** [comment]
I tryed but didnt work. 

when i copy and paste text in dbeaver editor and when i used my program for write data, this problem is exist too. 


Thank you.

**Comment by HakanDOGAN1981** [comment]
Pls try to paste "ğ, Ğ, ı, İ, ü, Ü, ş, Ş, ö, Ö, ç, Ç" to database table.

**Comment by mehmeet43** [comment]
Hello, although I changed the text file encoding as explained in the screenshot, I see the result set with Turkish characters incorrectly. How can we fix this problem, does anyone know?

<img width="745" alt="Screen Shot 2020-12-03 at 11 16 14" src="https://user-images.githubusercontent.com/7474020/100982357-03614580-3559-11eb-8f6d-e06ab1988159.png">

**Comment by HakanDOGAN1981** [comment]
*DBEAVER TÜRKÇE KARAKTER SORUNU ÇÖZÜMÜ*
1-Edit Connection
2-Driver Properties
3-Encoding Value = WIN1254

Mehmet Ş. Taşkesen <notifications@github.com>, 3 Ara 2020 Per, 11:19
tarihinde şunu yazdı:

**Comment by cci-etunca** [comment]
Hocam siz bu problemi çözdünüz mü

**Comment by HakanDOGAN1981** [comment]
> 

Evet, çözdüm. Şu şekilde düzelte bilirsin.
1-Bağlatınızda sağ tıklayarak/Edit Connection 
2-Driver Properties
3-Encoding Value = WIN1254

**Comment by sinancakir** [comment]
@HakanDOGAN1981 driver properties de Encoding Value yok. Kendim ekledim ama olmadı. Siz nasıl yaptınız.

**Comment by cci-etunca** [comment]
ben de birkaç varyasyon denedim olmadı, en son kullandığım db inin asistanına geçtim. dbeaver da başaramadım.

**Comment by HakanDOGAN1981** [comment]
> ben de birkaç varyasyon denedim olmadı, en son kullandığım db inin asistanına geçtim. dbeaver da başaramadım.

@sinancakir @cci-etunca @mehmeet43 
encoding = WIN1254  şeklinde denermisin...

**Comment by sinancakir** [comment]
> > ben de birkaç varyasyon denedim olmadı, en son kullandığım db inin asistanına geçtim. dbeaver da başaramadım.
> 
> @sinancakir @cci-etunca @mehmeet43 encoding = WIN1254 şeklinde denermisin...

![image](https://user-images.githubusercontent.com/4346887/194485723-541c6e87-f5f9-42df-912a-418f2d73223f.png)

![image](https://user-images.githubusercontent.com/4346887/194485797-e607d17a-ac99-46a8-92d3-4e211c83eff0.png)

**Comment by gorkemerdem** [comment]
Merhabalar, mevcut bağlantınıza gelip Edit Connection dedikten sonra Driver Properties kısmında Add new property deyip Property Name: CHARSET, Value kısmına da UTF8 yazarak çözebilirsiniz. Teradata bağlantısı için bu şekilde çözdüm. Kolay gelsin.
