### ISSUE TITLE
[bug] Properties: Columns (Structure): "drag & drop column" to change (alter) field order: not work

### ISSUE THREAD

**Issue by erlangp** [dbeaver/dbeaver#7299]
https://github.com/dbeaver/dbeaver/issues/7232#issuecomment-557807154
> 
> 
> I believe you meant "drag & drop column".
> 
> This is already supported.
> You can drag by column icon or with CTRL key pressed.

@serge-rider i tried but it does not work https://imgur.com/a/lgVtwyb

**Comment by uslss** [comment]
hi, if i understand you right you could use Custom filter to change columns order
![image](https://user-images.githubusercontent.com/31996417/69727791-3bf36580-1134-11ea-82eb-8afac2a445c4.png)

**Comment by erlangp** [comment]
thanks @uslss, but it's not what i meant.
sir @serge-rider say "drag & drop column" feature already suported to **alter** the db structure by pressing **Ctrl**, but currently does not work

**Comment by p91paul** [comment]
I believe he wants to change columns order at the database level from the table properties. This can be done e.g. in mysql with the following statements https://stackoverflow.com/questions/2934312/how-to-rearrange-mysql-columns, but drag & drop would be a nicer way of achieving the goal.
Not all databases supports it though.

**Comment by serge-rider** [comment]
@erlangp We support columns reordering for MySQL and Firebird. You can do it in table editor (see bottom toolbar):
![image](https://user-images.githubusercontent.com/6398845/69890754-89c0c700-1308-11ea-811b-ab0d4fb3ef36.png)
Agreed, not very obvious function. Probably we should make it more "visible".

@p91paul thanks)

**Comment by erlangp** [comment]
@serge-rider thanks sir.. i already know by using reordering buttons..

**Comment by erlangp** [comment]
may to reopen this issue https://github.com/dbeaver/dbeaver/issues/7232 sir? because there i tag with FeatureRequest drag and drop.. thanks
