### ISSUE TITLE
[BUG] "Switch to auto-commit" is saved across Dbeaver sessions

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#7302]
I have a DB connection marked as "Production", which means "NO AUTO COMMIT" set.
I temporarily changed this behavior from the menu bar, switching on the option "Switch to auto-commit".
Day ended, closed DBeaver, shutdown my pc, went home.
Today i went to work, and dropped a table IN PRODUCTION. The switch was still on, even i made *no change at all* in connection configuration, which still correctly shows "No auto commit".

**Comment by wiwwo** [comment]
This is what i have from a *fresh DBeaver start*
![image](https://user-images.githubusercontent.com/3930671/69711543-8b6c6e00-1101-11ea-998e-9718944ca880.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
This option changes auto-commit mode for active connection only.  And this option overrides default value (which comes from connection type). So it is not actually a bug, it works as expected.

The only question - should we change this option permanently for the connection or only for current DBeaver session.
Generally disabled commit/rollback buttons shows that you are in auto-commit mode. We can also use some extra coloring to visualize "unsafe" mode.

**Comment by p91paul** [comment]
for those who know the connection-level option, the most reasonable expectation is that the connection-level option is permanent while the top toolbar is a temporary switch.

I believe there are 2 choices: if the top toolbar should be permanent, then changing it should affect the connection preferences page as well. Otherwise the toolbar switch should become temporary (which is more expected behavior IMHO).

Status quo is not correct, because basically changing the option in connection options has no effect since the toolbar menu overrides it.

**Comment by wiwwo** [comment]
Totally agree with @p91paul 
Status quo is unacceptable.
I dropped a table IN PRODUCTION, and we had to restore our DB, since i was safely -and wrongly- thinking that transactions are on, as specified in configuration

Changing from menu bar should be related to the current Dbeaver "session" only (even better, to the current sql editor, but that would be asking too much)

**Comment by serge-rider** [comment]
I like the idea to make it current open editor related.

**Comment by wiwwo** [comment]
News update: following yesterday's incident, the CTO of my company is about to forbid *company whise* the use of DBeaver. I will try to fight for him to change idea.

**Comment by serge-rider** [comment]
I've changed auto-commit toggle behavior. Now it doesn't persist auto-commit option in connection.

It also works for active connection only. If you have option "open separate connection for each editor" enabled then it will work only for active editor.

@wiwwo unfortunately nothing can protect you from dropping a table on a production server. I believe most of people did this at least once. However we have to minimize chances. Hopefully this improvement will help.

**Comment by wiwwo** [comment]
@serge-rider before having the very bad idea of trusting the switc will be disabled after dbeaver restart, i used (and still use) to drop tables in production all the time, knowing that if the script i am executing founds some problem, i have the option to rollback. That is the magic of postgresql... Of course, if the UI you are using does not betray you... :-)

**Comment by wiwwo** [comment]
P.s.: this will defently help, yes :-)

**Comment by uslss** [comment]
verified
