### ISSUE TITLE
Database connection not being saved at version 6.2.5

### ISSUE THREAD

**Issue by pipinfitriadi** [dbeaver/dbeaver#7303]
System information:

    Mac OS
    DBeaver 6.2.5

Describe the problem you're observing:

Every time I start dbeaver I have to configure the database connection again
Steps to reproduce, if exist:

Start dbeaver, follow the wizard to configure a PostgreSQL connection. Connect, maybe make some query, close dbeaver. Next time you start dbeaver, it presents the same wizard again. This issue raise again, its happen before in https://github.com/dbeaver/dbeaver/issues/6960.

I should reinstall DBeaver to version 6.2.2 to make this issue gone.

**Comment by uslss** [comment]
thanks for the bug report. 
fixed in scope of #7251 
you could test Early Access version (https://dbeaver.io/files/ea)
