### ISSUE TITLE
Cannot download driver from https://dbeaver.io/files/jdbc/

### ISSUE THREAD

**Issue by namviet3210** [dbeaver/dbeaver#7305]
Hi there,

After installation of DBeaver, I added an ODBC connection, however the program report drivers were missing. The issue is that the link to driver in dbeaver.io is not working:
https://dbeaver.io/files/jdbc/

403 Forbidden
nginx/1.4.6 (Ubuntu)

I have tried to download driver from other sources but it is not working.
Could you please fix the access to https://dbeaver.io/files/jdbc/ please!!!!

Many thanks!
Donki

**Comment by serge-rider** [comment]
We do not provide any 3rd party JDBC driver on dbeaver.io for a long time.
You need to download drivers from their vendors web sites. Most of drivers have download URLs on driver editor dialog.

**Comment by kseniiaguzeeva** [comment]
Please reopen ticket if you need any other assistance.
