### ISSUE TITLE
Oracle 9.0.7 issue expanding schema tree

### ISSUE THREAD

**Issue by mbrucco** [dbeaver/dbeaver#7307]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.2.5
- Java version 1.8
- Additional extensions: no

#### Connection specification:
- Database name and version: Oracle 9.0.7
- Driver name: ojdbc8
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
When I try to expand schema node to see table or view it raise an exception

#### Steps to reproduce, if exist:
Connect to DB
open "Schemas" on left side tree
Select a schema
open a schema
open "Tables"

#### Include any warning/errors/backtraces from the logs
ORA-01460: unimplemented or unreasonable conversion requested

details:

SQL Error [1460] [72000]: ORA-01460: unimplemented or unreasonable conversion requested

  Error : 1460, Position : 465, Sql = 	SELECT  t.OWNER,t.TABLE_NAME as TABLE_NAME,'TABLE' as OBJECT_TYPE,'VALID' as STATUS,t.TABLE_TYPE_OWNER,t.TABLE_TYPE,t.TABLESPACE_NAME,t.PARTITIONED,t.IOT_TYPE,t.IOT_NAME,t.TEMPORARY,t.SECONDARY,t.NESTED,t.NUM_ROWS 
	FROM ALL_ALL_TABLES t
	WHERE t.OWNER=:1  AND NESTED='NO'
UNION ALL
	SELECT  o.OWNER,o.OBJECT_NAME as TABLE_NAME,'VIEW' as OBJECT_TYPE,o.STATUS,NULL,NULL,NULL,'NO',NULL,NULL,o.TEMPORARY,o.SECONDARY,'NO',0 
	FROM ALL_OBJECTS o 
	WHERE o.OWNER=:2  AND o.OBJECT_TYPE='VIEW'
, OriginalSql = 	SELECT  t.OWNER,t.TABLE_NAME as TABLE_NAME,'TABLE' as OBJECT_TYPE,'VALID' as STATUS,t.TABLE_TYPE_OWNER,t.TABLE_TYPE,t.TABLESPACE_NAME,t.PARTITIONED,t.IOT_TYPE,t.IOT_NAME,t.TEMPORARY,t.SECONDARY,t.NESTED,t.NUM_ROWS 
	FROM ALL_ALL_TABLES t
	WHERE t.OWNER=? AND NESTED='NO'
UNION ALL
	SELECT  o.OWNER,o.OBJECT_NAME as TABLE_NAME,'VIEW' as OBJECT_TYPE,o.STATUS,NULL,NULL,NULL,'NO',NULL,NULL,o.TEMPORARY,o.SECONDARY,'NO',0 
	FROM ALL_OBJECTS o 
	WHERE o.OWNER=? AND o.OBJECT_TYPE='VIEW'
, Error Msg = ORA-01460: unimplemented or unreasonable conversion requested

  ORA-01460: unimplemented or unreasonable conversion requested

**Comment by serge-rider** [comment]
Does it happen with any schema? Or only with some particular ones.

**Comment by mbrucco** [comment]
On all schemas

Inviato da iPhone

**Comment by serge-rider** [comment]
Most likely it is caused by driver version mismatch.
Oracle 9.0 is too old and modern drivers may work incorrectly.
Try to download older JDBC driver version (or get it from Oracle 9 distribution).
Similar problem description: https://community.oracle.com/thread/3724859
