### ISSUE TITLE
 Editing the index does not work

### ISSUE THREAD

**Issue by puyueyuan** [dbeaver/dbeaver#7308]
dbeaver 6.2.5
MySQL 5.6.39
driver MySQL Connector/J mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec)

Nothing happens when I click the editor index

**Comment by serge-rider** [comment]
Can't reproduce. Some steps to reproduce would be helpful.

**Comment by givihuda** [comment]
Where did you get the MySQL 5.6 driver?
