### ISSUE TITLE
[BUG] (in PG) selecting tables from DB navigator and asking to generate sql -> DDL does not include table grants

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#7311]
As from subject...

**Comment by serge-rider** [comment]
You can get this info on table's DDL tab.

**Comment by wiwwo** [comment]
i know. but selecting multiple tables because i want to copy them to another schema (for example) does not include grants, and i have to copy them one by one

**Comment by serge-rider** [comment]
You can also view postgresql schema ddl.
I believe it contains all tables combined.

However ddl gen for just a few tables still makes sense.

**Comment by yoni-yad2** [comment]
It will be very useful and time saving to have this feature (which exists in other DB clients such as Toad for Oracle)

**Comment by LonwoLonwo** [comment]
It looks like we can do it in the latest DBeaver version:

![2024-03-12 16_30_04-DBeaver Ultimate 24 0 0 - _postgres 6 1 2_ Script-184](https://github.com/dbeaver/dbeaver/assets/45152336/bbedddcc-b5aa-4e84-b901-1706e1857be3)

Is this what you are looking for?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
