### ISSUE TITLE
Changes to connections aren't saved

### ISSUE THREAD

**Issue by realdanielgrace** [dbeaver/dbeaver#7315]
#### System information: 
- Win10 64bit
- DBeaver 6.2.5 64-bit

#### Connection specification:
- Any type of connection

#### Describe the problem you're observing:
Changes to connections aren't saved on exit.
#### Steps to reproduce, if exist:

Reproduced in two different computers. Downgrading to 6.2.4 fixed the issue.
Try a minor change such as a connection name change. Restarting dbeaver doesn't show the changes.

**Comment by MrGroovy** [comment]
Was about to create this issue myself.

**Comment by uslss** [comment]
hi, issue is fixed in scope of #7251 .
you can test Early Access version (https://dbeaver.io/files/ea)
