### ISSUE TITLE
Impossible to change password after it be stored

### ISSUE THREAD

**Issue by felipebraga** [dbeaver/dbeaver#7317]
#### System information: 
- Manjaro 18.1.3 - Kernel 5.3.12
- DBeaver 6.2.5.201911171645

#### Connection specification:
- Postgresql

#### Describe the problem you're observing:
When I try to set a new a password on a saved connection and then close the application the old password is set.

**Comment by serge-rider** [comment]
Most likely it is the same issue as in #7251
Already fixed (see 6.3 Early Access version).
