### ISSUE TITLE
Oracle: Incorrect Declaration for Functions

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7321]
#### System information:  
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.0

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
When I try to create function Procedure is declared instead by default
![image](https://user-images.githubusercontent.com/31996417/69904110-a6660900-13b3-11ea-8ea7-7b727cbd97b3.png)

Also Function/Procedure name in declaration is always "New_procedure" even if user enter another name
![image](https://user-images.githubusercontent.com/31996417/69904154-4facff00-13b4-11ea-88ad-f26707d00dfe.png)

**Comment by serge-rider** [comment]
Fixed. Also CREATE OR REPLACE was added in the beginning.

**Comment by uslss** [comment]
verified
