### ISSUE TITLE
Auto-commit switches to manual commit when import is finished

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7323]
## System information:  
- Operating system (distribution) and version Windows 10
- DBeaver version 6.3.0

#### Connection specification:
- Database name and version SQLite

#### Describe the problem you're observing:
Auto-commit switches to manual commit when import is finished.

#### Steps to reproduce, if exist:
Precondition: auto-commit is selected

1. Go through wizard to iImport CSV file to a table in SQLite (DB Navigator, DB task panel)

Actual result: Auto-commit switches to manual commit when Start btn is pressed at the end of the Wizard.

**Comment by serge-rider** [comment]
Fixed (note: this happens only when you reuse main datasource connection).

**Comment by kseniiaguzeeva** [comment]
Fixed
