### ISSUE TITLE
Database task panel: custom directory cannot be saved

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7324]
### System information:  
- Operating system (distribution) and version Windows 10
- DBeaver version 6.3.0

#### Steps to reproduce, if exist:
1. Open Database task panel
2. Click "Create new task icon" and select export task
3. Make all necessary settings and select a custom directory to save the file.
4. Press start at the end of the Wizard
5. Click "Create new task icon" and select export task again, go through Wizard and check directory.

Expected result: Custom directory is offered.

Actual result: Default directory is offered
![LHFR2G9rY2](https://user-images.githubusercontent.com/51405061/69906437-551a4180-13d4-11ea-9d4e-5bca3564bbbd.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
