### ISSUE TITLE
XLSX exports without column headers

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7325]
#### System information:  
- Operating system (distribution) and version Windows 10
- DBeaver version 6.3.0

#### Describe the problem you're observing:
XLSX exports without column headers

#### Steps to reproduce, if exist:
Try to export a table in XLSX format from Data viewer or from Task Panel

**Comment by serge-rider** [comment]
Fixed. It was broken during some time (I believe after we switched to tasks)

**Comment by kseniiaguzeeva** [comment]
verified
