### ISSUE TITLE
6.3.0 fails launch after installation...

### ISSUE THREAD

**Issue by kiravi** [dbeaver/dbeaver#7330]
#### System information: 
- Operating system (distribution) and version
Windows 10 enterprise
- DBeaver version
6.3.0
- Additional extensions

Error during launch: Error file attached.
[1575261549816.log](https://github.com/dbeaver/dbeaver/files/3909483/1575261549816.log)

**Comment by serge-rider** [comment]
What type of installation do you use? (installer, zip archive).
Did you try to reinstall it? In some cases some old version of DBeaver app may hang and you need to reboot (or use task manager to kill the process) before new installation.

**Comment by e-martin** [comment]
I have the same problem, when I launch DBeaver begin to restart indefinitely in the splash screen.

I have installed portable 64 bit version. 

Thanks.

**Comment by serge-rider** [comment]
@e-martin make sure than you removed previous DBeaver version before installing new one. You can't copy/extract new version over old one.

**Comment by e-martin** [comment]
@serge-rider always I copied the new version over the previous and never I had a problem, in this case I'll try that.

Thanks.

**Comment by e-martin** [comment]
@serge-rider I can confirm that copying in a new folder works, may that updating from 6.1.2 to 6.3.0 without migration have problems.

Thanks.

**Comment by serge-rider** [comment]
Good.
You should never copy new version over previous one. You were lucky that it worked for some versions.
