### ISSUE TITLE
Mask "*" doesn't work in field "include" of DB Navigator filter

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7332]
#### System information:  
- Operating system (distribution) and version Windows 10
- DBeaver version 6.3.0

#### Connection specification:
- Database name and version SQLite

#### Describe the problem you're observing:
Mask "*" doesn't work in field "include" of DB Navigator filter (but everything is ok for MySQL, Postgres)
#### Steps to reproduce, if exist:
1. Open Filter in context menu of DB Navigator in SQLite tre
![mask](https://user-images.githubusercontent.com/51405061/69940916-75d9b880-14f4-11ea-9c91-46f0781485a3.gif)
e.
2. Write any existed table name in field  "include" of the filter and change some sign of table name by mask "*".
3. Press Ok

Expected result: Relevant table name (s) will be displayed in DB Navigator tree ("*" allows to insert any signs on its place).
Actual result: No table names is displayed in DB Navigator tree for SQLite.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
