### ISSUE TITLE
v6.3 breaks editing table value with custom data type 

### ISSUE THREAD

**Issue by VBP8501** [dbeaver/dbeaver#7333]
#### System information: 
- Operating system (distribution) and version: Win 10 v1909
- DBeaver version: v6.3.0.201912011827
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgreSQL 9.6.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28), 64-bit
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Since upgrading to v6.3 it is no longer possible to change the value of a cell that is based on a custom data type. 

#### Steps to reproduce, if exist:
Run this query:

```
CREATE TYPE public.custom_type AS ENUM ('Type1', 'Type2');

CREATE TABLE type_tester (
	id serial NOT NULL,
	type public.custom_type,
	CONSTRAINT "type_tester_pkey" PRIMARY KEY (id)
);

insert into type_tester (type) values ('Type1');
```
Open the table type_tester in dbeaver and open the Data tab if not open by default. 
Try to change Type1 into Type2

**Comment by serge-rider** [comment]
thanks for the bug report. This error happens only with enum data types.

**Comment by uslss** [comment]
verified
