### ISSUE TITLE
Multiple unnamed parameters

### ISSUE THREAD

**Issue by ClodoaldoPinto** [dbeaver/dbeaver#7335]
Is it possible to use multiple unamed parameters by order? My problem is that I need the queries to work unchanged in Visual Studio connecting to DB2 LUW and VS only accepts ordered unamed `?` parameters for that connection. What I would like to do:
```sql
@set ? = '2019-01-01'
@set ? = '2019-12-31'
select column
from myTable
where theDate between ? and ?
```

**Comment by serge-rider** [comment]
I understand the point but this would be a very frustrating feature. And you will have to use the same order always.
I'm not sure how to handle this issue in a better way...

**Comment by ClodoaldoPinto** [comment]
Ok. Not a big deal. Thanks.
