### ISSUE TITLE
How to bind variables to a SQL query while using Database tasks feature?

### ISSUE THREAD

**Issue by ajay-ramaswamy** [dbeaver/dbeaver#7336]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.3.0.201912011827

#### Connection specification:
- Database name and version: Oracle 11g

#### Describe your question:
I want to add a query to a new database task, that has date variables in it. When I save the task and run it, instead of asking for the values for the variable, error "**ORA-01008: not all variables bound**" is thrown.

How to I add values to the variables while running the database task?

Thanks!

**Comment by ajay-ramaswamy** [comment]
Hi,

Can somebody reply on this thread?

**Comment by serge-rider** [comment]
At the moment we do not support variables binding for saved tasks.
It is not possible to do any user interactions during task execution (because task can be run from command line, scheduler, etc).
So variables binding dialog cannot be used. But we can save variables from script execution context into task configuration (as constants). Perhaps we turn make this ticket into feature request. 
WDYT?

**Comment by p91paul** [comment]
it would be nicer if command line could be able to pass parameters to tasks as well, while scheduler should set parameters in its own configuration. Overall being able to execute a task many times with different parameters would be very useful!

**Comment by ajay-ramaswamy** [comment]
@serge-rider 
The ability to bind variables during task execution from GUI, along with the idea @p91paul has written. It would be a nice combo feature.
So, yes. Could you please turn this ticket into a feature request?

**Comment by serge-rider** [comment]
Generally it is not a big deal to add variables to task input objects configuration (some extra tab similar to SQL variable binding dialog).
However I'm not sure that I fully understand the use-case. Having variables looks like more complicated config than just some SQL query with filled parameter values. Do you want to change these variables for a saved task? Or do you want to create many different tasks with the same query but different variable values?

**Comment by p91paul** [comment]
I would like to be able to choose different values for the variables every time I launch the saved task.
My use case: I need to transfer data from 2 databases. Many tables are involved, and they contain historical data, i.e. each row has a date field. I usually need to transfer just one day of data, but which day changes every time I need to launch the data transfer.
If I could save a task with many source queries, each with a :day parameter, I could then launch the task knowing it would ask for the day parameter, and then run data transfer for that day on all tables. For this to work nicely, multiple instances of the same variable in the same task should be asked only once of course.

**Comment by ajay-ramaswamy** [comment]
That is exactly what my use-case is.

**Comment by ajay-ramaswamy** [comment]
@serge-rider so will you take this as a feature request?

**Comment by ajay-ramaswamy** [comment]
@serge-rider will you please take this as a feature request?

**Comment by ashwinn226** [comment]
Hi @ajay-ramaswamy and @p91paul I have the exact same use case, and I wanted to know if any resolution came up? This seems like a really obvious feature to have!
