### ISSUE TITLE
Firebird 3 boolean datatype - unable to select "true" in dbgrid

### ISSUE THREAD

**Issue by dogriz** [dbeaver/dbeaver#7337]
#### System information: 
- Linux Mint Xfce 19.2
- DBeaver version 6.3.0

#### Connection specification:
- Firebird 3.0.4 64-bit
- Jaybird 3.0.8

#### Describe the problem you're observing:
When trying to set value for boolean datatype field, only "false" pops up.

![image](https://user-images.githubusercontent.com/7532492/69970428-86068d80-151e-11ea-99ea-450d0fedf076.png)

**Comment by uslss** [comment]
if issue is still actual - feel free to reopen the ticket
