### ISSUE TITLE
Mac Os Catalina Firebird 2.5

### ISSUE THREAD

**Issue by electrocoder** [dbeaver/dbeaver#7340]
#### System information: 
- Operating system : Max Os Catalina 10.15.1
- DBeaver version : 6.3.0.201912021731

#### Connection specification:
- Database name and version : Firebird 2.5
- Driver name  : jdbc:firebirdsql

#### Describe the problem you're observing:
Error while trying to open file; Operation not permitted

**Comment by serge-rider** [comment]
Do you use server or embedded Firebird?
Please post error stacktrace (you can get it in Error Log view).

**Comment by uslss** [comment]
there is no update on ticket for a long time. If issue is still actual for you - feel free to reopen the ticket
