### ISSUE TITLE
Feature request - unset variable

### ISSUE THREAD

**Issue by jugglerscott** [dbeaver/dbeaver#7341]
I'm using Postgres. If I call an unset variable in a query, it pops up a Bind parameters window. If I use @set to define the variable, it runs the query with the value I set. I'd like to be able to now unset the variable so it'll give me the Bind parameters again. The only thing that's worked is to quit DBeaver and restart it.

**Comment by serge-rider** [comment]
New command @unset will be added in the next version.

Thanks for bringing this up.

**Comment by kseniiaguzeeva** [comment]
Verified
