### ISSUE TITLE
Export Crash  upper to version 6.2.3

### ISSUE THREAD

**Issue by jcarrasco-odf** [dbeaver/dbeaver#7343]
#### System information: 
- Ubuntu 18.04.3 LTS (Bionic Beaver) 
- upper to DBeaver 6.2.3
- Java 1.8.0_161 
- Additional extensions

The export data crash with the following message:
```
The program 'DBeaver' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 25350 error_code 11 request_code 130 (MIT-SHM) minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

#### Steps to reproduce, if exist:
When I open the data export menu, the program suddenly closes, before choosing the type of export

Thanks

**Comment by SNeugberYoti** [comment]
I have the same issue.

**System information:**

- Ubuntu 18.04.4 LTS
- DBeaver 6.3.4.202002011957

**Comment by SNeugber** [comment]
I have the same issue, down to the exact same error message.

**System information:**

- Ubuntu 18.04.4 LTS
- DBeaver 6.3.4.202002011957

**Comment by uslss** [comment]
is issue still actual against recent versions?

**Comment by SNeugber** [comment]
Can't reproduce this any more either on version 7.0.1.202003211804

**Comment by tati-kru** [comment]
@SNeugber thank you for the check

**Comment by jcarrasco-odf** [comment]
This issue still happens.

System information:
Ubuntu 18.04.4 LTS
DBeaver 7.1.0.202005311732

**Comment by kerhong** [comment]
I managed to narrow down this issue, it seems to fail only when exporting with very long lines in the query.

Steps:
1. Connect to database
2. Open query editor
3. Query for `select 'xxxxxxxxxxxx...xxxxxxxxxx';` (not writing the whole query, but I always get the crash with 4000 "x" and it never crashes with 3000 "x")
4. In context menu of the query result select 'export data'
5. Crash
    ```
    (DBeaver:10666): Gdk-ERROR **: 23:35:47.243: The program 'DBeaver' received an X Window System error.
    This probably reflects a bug in the program.
    The error was 'BadAlloc (insufficient resources for operation)'.
      (Details: serial 42125 error_code 11 request_code 130 (MIT-SHM) minor_code 5)
      (Note to programmers: normally, X errors are reported asynchronously;
       that is, you will receive the error a while after causing it.
       To debug your program, run it with the GDK_SYNCHRONIZE environment
       variable to change this behavior. You can then get a meaningful
       backtrace from your debugger if you break on the gdk_x_error() function.)
    ```

DBeaver Version 7.2.4.202011080312
Manjaro linux

**Comment by rodanConafor** [comment]
Same behavior in my machine with Ubuntu 18.04.06 and dbeaver:
22.0.4.202205011839
with java jdk1.8.0_221, happens same error as above described, I changed java to: 
java-11-openjdk-amd64
and with that export data just works fine.
