### ISSUE TITLE
PostgreSQL EXIT keyword not recognized

### ISSUE THREAD

**Issue by ALDamico** [dbeaver/dbeaver#7344]
#### System information: 
- Windows 10 version 10.0.18363.476
- 6.2.5

#### Connection specification:
- PostgreSQL 11
- PostgreSQL JDBC Driver
- No.

When writing a SQL stored procedure or function for a PostgreSQL database, the editor doesn't recognize and highlight the EXIT keyword.
![image](https://user-images.githubusercontent.com/33159753/70043969-b6533800-15c1-11ea-9c68-01f4436cdd56.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
