### ISSUE TITLE
Development preset Connection type can show wrong color

### ISSUE THREAD

**Issue by Chealer** [dbeaver/dbeaver#7348]
The Connection Types pane in Preferences sometimes shows the wrong color. DBeaver comes with a preset "Development" connection type which seems to have no color assigned. However, when Development is selected, there is sometimes a color displayed. It seems that if one selects a connection type with color x, then selects connection type Development, the color displayed (for Development) will remain x. For example, if I click on Test, then on Development, the color displayed for Development is green.

This affects DBeaver 6.3.0.

**Comment by serge-rider** [comment]
I can't reproduce this. Could you post some explaining screenshot/video?

**Comment by Chealer** [comment]
I've created a screencast of DBeaver 6.2.5: https://drive.google.com/file/d/1T3CKL02uc8U-QVmczk4HUxOjRpTMTSeE/view?usp=sharing

**Comment by kseniiaguzeeva** [comment]
Unfortunately I can't reproduce either. What is your OS and database?

**Comment by kseniiaguzeeva** [comment]
@Chealer Could you please reopen the ticket if the bug appears in newer versions again?

**Comment by Chealer** [comment]
Unfortunately not currently @kseniiaguzeeva

**Comment by Chealer** [comment]
I believe that won't be needed. I upgraded my stand-alone DBeaver to 6.3.2 and cannot reproduce. I am therefore crossing fingers that this is solved.

I note a strange behavior in the Connection types dialog. In the table at the top, when a row is selected, the background color of its right column (Description) becomes white, no matter what color is assigned to that connection type.
