### ISSUE TITLE
Exporting to single file breaks on timestamp change

### ISSUE THREAD

**Issue by gumblex** [dbeaver/dbeaver#7352]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.3.0
- Additional extensions: None

#### Connection specification:
- Database name and version: MySQL 8.0.12
- Driver name: MySQL 8+
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:

"Write to the single file" in Export actually writes to multiple file when the timestamp in the filename changes, eg. minute change. There will be files like "export_201912031336.sql" and "export_201912031337.sql".

Expected to be one file with the start time as the filename.

#### Steps to reproduce, if exist:

* Select some tables
* Export Data
  * Select "SQL" format
  * Select "Write to the single file"
  * Set the filename to "${table}_${timestamp}"
* When the clock reads 50+ seconds, press Start.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by serge-rider** [comment]
Fixed (time of data transfer process start will be used).
Additionally I've added configuration for timestamp pattern (you can use seconds/milliseconds there if you need).

**Comment by kseniiaguzeeva** [comment]
Tables are still exported to a different files (try to begin export of several tables at 57 sec.)

**Comment by serge-rider** [comment]
One more fix added

**Comment by kseniiaguzeeva** [comment]
Verified.
