### ISSUE TITLE
named do block in postgres does not work

### ISSUE THREAD

**Issue by for7raid** [dbeaver/dbeaver#7353]
#### System information: 
- windows 10 x64
- DBeaver  6.3

#### Connection specification:
- PostgreSQL 10
- Driver name PostgreSQL JDBC Driver

#### Describe the problem you're observing:
Named do block interpreted $name$ as a parameter prompt
 
#### Steps to reproduce, if exist:

Paste code with named do block, like this
```
DO $uuid12f82206b07649cc$
BEGIN
	DELETE FROM "metamodel" WHERE name in ('Version');
	INSERT INTO "metamodel" ("name", "value") VALUES
	('Version', '2019.08.29.0835');
EXCEPTION WHEN OTHERS THEN
	RAISE NOTICE 'SQLSTATE: %, %', SQLSTATE, 'uuid12f82206b07649cc';
	RAISE;
END $uuid12f82206b07649cc$;
```
and try execute. DBeaver asks to fill parameter $uuid12f82206b07649cc$, 
press Skip, sql execution fails

#### Additional information
In 6.2.2.201910072100 it works normal, next version not normal

**Comment by serge-rider** [comment]
Thanks for the bug report.
It happens because block name contains digits.

**Comment by uslss** [comment]
verified

**Comment by for7raid** [comment]
resolved and works correctly!
Thank you for support and realy good application.
