### ISSUE TITLE
DB2 Error to export on csv

### ISSUE THREAD

**Issue by veldevelop** [dbeaver/dbeaver#7355]
Hi, i have problem to export data to csv.

The export generate strange values: 

60.66
----->   27.455.400.000.000.000
6.852.384
13.68

**Comment by veldevelop** [comment]
![image](https://user-images.githubusercontent.com/8342637/70125533-40a9a380-1677-11ea-8b89-1a2b7a86c045.png)

**Comment by serge-rider** [comment]
Please provide more details.
This looks just like some very big number, generally it is not a bug.

Can you post some SQL to reproduce this problem?

**Comment by veldevelop** [comment]
I have installed version 6.2.4 and it works perfectly I send the same capture

![image](https://user-images.githubusercontent.com/8342637/70129761-a732bf80-167f-11ea-8d3b-26665bc21173.png)

**Comment by serge-rider** [comment]
Does this happen after CSV export only or you see the same issue in results grid?

**Comment by veldevelop** [comment]
It only happens in csv export

**Comment by serge-rider** [comment]
Thanks. Could you say data type of numeric columns?
Is there anything related in error or debug logs? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by veldevelop** [comment]
I really do not indicate the type of data, when exporting it only generates the document and when I open it it is when I see it

This is my configuration tu export csv file 
![image](https://user-images.githubusercontent.com/8342637/70161802-f6e3ac00-16bc-11ea-9a63-a1320d7d7a18.png)

![image](https://user-images.githubusercontent.com/8342637/70161873-0ebb3000-16bd-11ea-9052-88ce74cde6b7.png)

![image](https://user-images.githubusercontent.com/8342637/70161924-20043c80-16bd-11ea-8559-1f52cedfbbd7.png)

**Comment by serge-rider** [comment]
You can see data types in metadata panel of results viewer:
![image](https://user-images.githubusercontent.com/6398845/70163092-e426a280-16cf-11ea-8403-dd2661f3c3bd.png)

What DB2 server version do you use? LUW, z/OS, iSeries?

**Comment by uslss** [comment]
there is no update on ticket more than a month.
Ticket closed.
If issue still actual for you - feel free to reopen the ticket
