### ISSUE TITLE
requires 'bundle com.sun.jna 0.0.0' on Eclipse 4.6

### ISSUE THREAD

**Issue by ebnerbenoit** [dbeaver/dbeaver#7358]
I try to install dBeaver into a 4.6 Eclipse.
I take the latest version and try the installation of:

- dBeaver IDE
- dBeaver SSHJ
- dBeaver Office Support
- dBeaver SVG Extension

And, I have this error during the install process:
`
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver SSHJ 1.0.43.201912011827 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.43.201912011827)
  Missing requirement: DBeaver SSH tunnels 1.0.43.201912011827 (org.jkiss.dbeaver.net.ssh 1.0.43.201912011827) requires 'bundle com.sun.jna 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver SSH implementation (SSHJ) 1.0.43.201912011827 (org.jkiss.dbeaver.net.ssh.sshj 1.0.43.201912011827)
    To: bundle org.jkiss.dbeaver.net.ssh 0.0.0
  Cannot satisfy dependency:
    From: DBeaver SSHJ 1.0.43.201912011827 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.43.201912011827)
    To: org.jkiss.dbeaver.net.ssh.sshj [1.0.43.201912011827]
`

I try the same plugin version into a 4.8 Eclipse version, and it work fine.

#### System information: 
- Windows 10
- 6.3
- Installed in Eclipse 4.6

**Comment by serge-rider** [comment]
does this error happens only during SSHJ installation or even DBeaver IDE can't installed?

Now sure how we can handle it better from DBeaver side. As JNA is required is has to be in the platform.
I think we could try to include it in the base DBeaver distribution. But it may lead to potential conflicts in JNA version in newer Eclipse versions.

Possible workaround is to install JNE separately from Orbit repository https://download.eclipse.org/tools/orbit/downloads/drops/R20191126223242/repository

**Comment by ebnerbenoit** [comment]
When I try to install dBeaver alone, it complain about the sshj that is not there. I can send you a sample of the error.

I try your link asap.

Thanks

**Comment by ebnerbenoit** [comment]
I try to install dBeaver only without any plugins, and here is the message I have

`Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver IDE 6.3.0.201912011827 (org.jkiss.dbeaver.ide.feature.feature.group 6.3.0.201912011827)
  Missing requirement: DBeaver SSH tunnels 1.0.43.201912011827 (org.jkiss.dbeaver.net.ssh 1.0.43.201912011827) requires 'bundle com.sun.jna 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver IDE 6.3.0.201912011827 (org.jkiss.dbeaver.ide.feature.feature.group 6.3.0.201912011827)
    To: org.jkiss.dbeaver.runtime.feature.feature.group [6.3.0.201912011827]
  Cannot satisfy dependency:
    From: DBeaver Runtime 6.3.0.201912011827 (org.jkiss.dbeaver.runtime.feature.feature.group 6.3.0.201912011827)
    To: org.jkiss.dbeaver.net.ssh [1.0.43.201912011827]`

**Comment by serge-rider** [comment]
Did you try to install JNA libraries from Orbit?

**Comment by ebnerbenoit** [comment]
I just finish to download the zip file and try to install dBeaver with the zip file in the Software Site. And, it work fine now.

When I look in the Plug-in panel in the about dialog, I see "Eclipse Orbit - Java Native Access - 4.5.1" and the dBeaver is installed now.

The workaround work fine for me, thanks

**Comment by serge-rider** [comment]
We'll include JNA jars in dbeaver runtime in 6.3.2.

**Comment by uslss** [comment]
verified

**Comment by gab444** [comment]
@serge-rider :getting this error while installing the latest eclipse plugin, is there a way to install previous eclipse versions?
![image](https://user-images.githubusercontent.com/69998999/135355109-21ede41a-44d4-47a1-b086-a5f2f8d221cc.png)
