### ISSUE TITLE
Firebird Datatype Numeric using Stored Procedures

### ISSUE THREAD

**Issue by EternalSoldier01** [dbeaver/dbeaver#7364]
#### System information: 
- Operating system (distribution) and version : Wondows 10
- DBeaver version: 6.1.4
- Additional extensions

#### Connection specification:
- Database name and version Firebird 2.5
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

#### Describe the problem you're observing:
When you create a stored procedure with either input variables and/or output variables of data type: Numeric(15,2) when you now save the procedure on the db the data type is now changed to only Numeric: without the parameters, the problem is when you copy the procedure now to change something and you copy over the data types as Numeric and not Numeric(15,2) those data types would be treated as whole numbers and not as a numeric value with decimals.
This causes problems every time you are editing a procedure, as you can forget to change the numeric back to Numeric(15,2)
#### Steps to reproduce, if exist:
Create a procedure with a return variable of type Numeric(15,2)
Save the procedure
Go to the procedure's source, see it is now only Numeric

**Comment by tarbul** [comment]
This is the same bug as described in #5532. No one seems to care about it. At least for now :)

**Comment by tarbul** [comment]
@serge-rider, this bug was solved in #5532.

**Comment by serge-rider** [comment]
@tarbul thanks for checking!
