### ISSUE TITLE
[BUG] Autocommit ON in configuration, but sql editor start with autocommit OFF

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#7366]
As from subject...

**Comment by serge-rider** [comment]
Do you mean connection type configuration or connection itself?
I mean this prefs page:
![image](https://user-images.githubusercontent.com/6398845/70162211-57c7b000-16ce-11ea-928c-1d7189997f5a.png)

**Comment by wiwwo** [comment]
Yes.
Configuration is

![image](https://user-images.githubusercontent.com/3930671/70162718-66a66680-16be-11ea-9349-ff7dc0b0fbac.png)



But opening a sql editor shows
![image](https://user-images.githubusercontent.com/3930671/70162783-89387f80-16be-11ea-80e3-b305d900c3e1.png)

**Comment by serge-rider** [comment]
It is connection type configuration. 
It can be overrided by connection configuration (see my screenshot)

**Comment by wiwwo** [comment]
If i setup a connection as "DEVELOP", it has autocommit on.
If i connect to that connection, i expect this connection to have... autocommit ON.
If autocommit is off, it is not what it sais in config.

**Comment by serge-rider** [comment]
Well, you can override this settings for a particular connection.
If you don't need it - just don't do it :) I don't see what can be fixed here..

**Comment by wiwwo** [comment]
LOL
i honestly can't understand why you don't understand me.

Create a connection. Set it as "Development"; that means, autocommit is ON.
Close Dbeaver.
Open it.
Connect to the connection you just created.
How do you expect "Autocommit" to be?
ON
If it is not ON, why on earth you put the option in the connection definition?!?

**Comment by serge-rider** [comment]
I don't get it. Auto-commit will be defined by connection type until you will change it (manually) for a particular connection.
Some people want to change default settings for a particular connection (any settings, auto-commit is just one of them).

**Comment by wiwwo** [comment]
I did not change it manually, that is waht i am saying! :-)

**Comment by serge-rider** [comment]
I believe you changed it manually in previous DBeaver version (when we persisted this change whenever you changed auto-commit mode in the main toolbar). 
Since 6.3 we no longer do that. Now the only way to turn it back is in connection properties.

**Comment by wiwwo** [comment]
No

**Comment by serge-rider** [comment]
You definitely did that (see ticket #7302). As a result of discussion in 7302 we decided that it is a bad idea to persist this change. But actual connection settings weren't reverted after this change. 
So you may have this option turned on for a particular connection.
We can fix something in configuration but I just can't realize what can be fixed.

**Comment by wiwwo** [comment]
Look... whatever :-)
How can i have autocommit ON for this connection in sql editor?

**Comment by serge-rider** [comment]
Just change it in the connection settings (see first screenshot).

**Comment by wiwwo** [comment]
Look, really...
Have you seen my screenshots?
Autocommit is on already in connection settings!!!
But if i open a sql editor window, autocommit is OFF!!!

**Comment by serge-rider** [comment]
You didn't post a screenshot with connection settings. You posted a screenshot with connection type settings.
These are different settings pages. Connection type settings are shared among all connections, connection settings are specific for a particular connection.

**Comment by wiwwo** [comment]
Now i see! That makes sense!

**Comment by wiwwo** [comment]
Sorry to make you loose your time!

**Comment by serge-rider** [comment]
That's ok, I assume that some other people may be also confused with this settings change, this thread will help them.

**Comment by besteakdik** [comment]
dude you got insane patient. thanks for solution btw
