### ISSUE TITLE
Query Manager only storing partial query

### ISSUE THREAD

**Issue by b-upah** [dbeaver/dbeaver#7367]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: EE 6.2.0.201909220738
- Java version: 
- Additional extensions: None

#### Connection specification:
- Database name and version: NA
- Driver name: NA
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:
The Text portion of Query Manager looks like it is not storing the full SQL for long queries. Not sure if there is a character limit on the column in the local DB, but can I increase that size. We often have long queries we use.

#### Steps to reproduce, if exist:
Create a query that is long (seems like even about 50 lines gets cut off).

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
The bug is in UI component which shows full query text. 
Actual query stored correctly (there is no query length limit).

You will be able to see all your historic queries in full lengths after UI fix will be published.

**Comment by uslss** [comment]
verified

**Comment by andrewjacobsonpfe** [comment]
This issue is present in Version 25.2.0.202508311659 Windows 11. I get exactly 4000 chars from query, no more.
