### ISSUE TITLE
Add filename distinction option on execute > export results

### ISSUE THREAD

**Issue by knwpsk** [dbeaver/dbeaver#7370]
(Ref release 6.3.0 and ticket 6041,  which have fully enabled exporting results from multiple queries, using @set commands to alter the tables or parameters in between queries)

When I run a script with multiple queries, and export the results, it's possible that the exported results files will overwrite each other.  We need a new parameter in the export > filename dialog that will let us give each file a distinct name.

My recommendation here would be a parameter called {exportCounter} that simply starts at 1 and increments with each file created in the script.  So, my filename string might look like:

MyFileName_{date}_{exportcounter}

The resulting files for one run of the script would be called

MyFilename_20191204_1.csv
MyFilename_20191204_2.csv
MyFilename_20191204_3.csv
etc

--

Why not use {timestamp} ?  I do use it; but sometimes two queries in a script may finish quickly and have the same ts.  Especially if the second query returns no results, it will overwrite the results of the first query.

What about {tablename} ?  My multiple queries often use the same table name, so that's not distinct.

**Comment by serge-rider** [comment]
Good point

**Comment by serge-rider** [comment]
New variable ${index} was introduced.
Also you can configure timestamp pattern and use milliseconds there (e.g. HHmmssSSS).

**Comment by knwpsk** [comment]
Thanks Serge.  
**How** do you configure the timestamp?  What would that look like in the filename dialog?

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/70471888-20e30700-1adf-11ea-8c43-68fbb8f3a345.png)

**Comment by knwpsk** [comment]
You are THE MAN.

**Comment by kseniiaguzeeva** [comment]
Verified.

**Comment by vnair01** [comment]
is there any way we can just stop the wizard to pop up for every export? since we are already providing all the necessary parameters in the @export command.

**Comment by FredAmouzgar** [comment]
Hello, is there a way to automate this process (if we don’t have it already)? I need to run multiple queries at once, save them in different files and then feed them to a program for analysis and plotting. It’d be great to have a command like export that we can automatically export the result of each set of queries in different files with predefined names.
