### ISSUE TITLE
Fatal error on table's Properties "Search Panel"

### ISSUE THREAD

**Issue by pb87crvs** [dbeaver/dbeaver#7371]
A fatal error happens on table's Properties "Search Panel"

**#### System information:** 
- Operating system (distribution) and version: Windows 10, ver 1903
- DBeaver version: Version 6.2.2.201910061950
- Additional extensions: none

**#### Connection specification:**
- Database name and version: <unknown> but an Oracle one
- Driver name: Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)?:  No

**#### Describe the problem you're observing:**
I open a table (usually one that was there from previous session), open its "ER Diagram" Tab, switch to the "Properties" Tab, then Open the Search Panel (Ctrl + F) , Close the Search Panel, and Reopen the Search Panel. The app dies without warning.

**#### Steps to reproduce, if exist:**
1. Open a table
2. Open its "ER" Tab
3. Switch to its "Properties" Tab
4. Open the Search Panel (Ctrl + F), then Close it (Press x right the search bar)
5. Repeat 4. one or two times

**#### Include any warning/errors/backtraces from the logs**
See attachment
[hs_err_pid16028.log](https://github.com/dbeaver/dbeaver/files/3925707/hs_err_pid16028.log)

**Comment by serge-rider** [comment]
Can't reproduce . Please check how it works in DBeaver 6.3.

**Comment by serge-rider** [comment]
Also we use Java 11 by default. It is included in the Windows installer.

**Comment by pb87crvs** [comment]
> DBeaver 6.3

With 6.3 on my machine the bug does not happen anymore:  i switched to it right now, thanks.
PS: I use the zip version (not the one that comes with the installer) so that's probably why it was not using Java11.
