### ISSUE TITLE
dbeaver often prompts SQL errors and must be disconnected and reconnected to recover. My data source is presto

### ISSUE THREAD

**Issue by elonlo** [dbeaver/dbeaver#7372]
e.g. org.jkiss.dbeaver.DBException: SQL Error: primary keys not supported
![image](https://user-images.githubusercontent.com/5669148/70225277-ac7c3100-1789-11ea-9ccc-c99f99a3c646.png)

**Comment by elonlo** [comment]
Version 6.3.0.201912021731

**Comment by serge-rider** [comment]
We'll fix error logging (for unsupported features).

**Comment by elonlo** [comment]
Why did this happen, it was normal before the same query error

**Comment by elonlo** [comment]
Why this problem occurs, the same query sometimes runs successfully and sometimes fails

**Comment by serge-rider** [comment]
This error happened because presto driver (PrestoDB driver) throws unexpected SQL errors. Now they are handled.

**Comment by elonlo** [comment]
hmm. okay
