### ISSUE TITLE
Decimal value update from "Data" tab (editable grid) seems to set wrong values

### ISSUE THREAD

**Issue by pvoisin** [dbeaver/dbeaver#7376]
#### System information: 
- Operating system (distribution) and version: Mac OS `10.14.6 (18G95)`
- DBeaver version: `6.2.5.201911171645`
- Additional extensions: ø

#### Connection specification:
- Database name and version: Microsoft SQL Server `14.0.3048.4` (from `mssql-server:2017` Docker image, id: `sha256:6814ae202f53512d09fa97d2a8b29ef1f31d8637287bb1cef5e938f5ca48f242`)
- Driver name: "Microsoft JDBC Driver for SQL Server"
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Nope!

#### Steps to reproduce, if exist:

Having a record with a field being a decimal number like `InvoiceItem.priceValue` (see usage below), when setting the field value in DBeaver "Data" tab (the editable result grid), the actual value _seems_ to have rounding issues when being submitted to the server.

For example, when having the field value set to "0.05" in the UI (editable grid), the field seems to be set with "0.05000000074505806" instead. Generated query (little "script" button at the bottom of the UI showing the change preview) seems to be fine though so I don't know where the problem actually is. My assumption is that the generated query differs from the actual query that is eventually run against the server (even if the transaction log from DBeaver UI shows that same queries are run).

Generated query:
```
-- Auto-generated SQL script #201912051502
UPDATE CommerceAPI.dbo.InvoiceItem
   SET priceValue=0.05
   WHERE invoiceId='787c8424-d79f-4680-b36a-52f14fc9cf2c' AND [rank]=0 GO
```

Result I'm reading when placing a breakpoint in my API server (using Knex/Tedious driver): 
```
{
    "id": "787c8424-d79f-4680-b36a-52f14fc9cf2c",
    ...,
    "items": [
        {
            "rank": 0,
            ...,
            "price": {
                "value": 0.05000000074505806,
                "currency": "CAD"
            }
        },
        ...
    ]
```

When running the very same generated query manually in a script tab, the value is fine!..
```
{
    "id": "787c8424-d79f-4680-b36a-52f14fc9cf2c",
    ...,
    "items": [
        {
            "rank": 0,
            ...,
            "price": {
                "value": 0.05,
                "currency": "CAD"
            }
        },
        ...
    ]
```

#### Include any warning/errors/backtraces from the logs

Transaction log gotten from the UI:
```
Dec.-05 15:34:05	SQL / User	-- Auto-generated SQL script #201912051526
UPDATE CommerceAPI.dbo.InvoiceItem
	SET priceValue=0.05
	WHERE invoiceId='0991c37d-a780-4da9-b23d-45a1520ec68d' AND [rank]=0 	6	1	Success	[local] Commerce	Main
Dec.-05 15:33:47	SQL / User	UPDATE CommerceAPI.dbo.InvoiceItem
	SET priceValue=0.05
	WHERE invoiceId='0991c37d-a780-4da9-b23d-45a1520ec68d' AND [rank]=0	7	1	Success	[local] Commerce	Main
```

**Comment by serge-rider** [comment]
Could you try latest version (6.3.0). We had a couple of fixes of numeric data type handle (for SQL Server) there (#7214, #7237)

**Comment by pvoisin** [comment]
Cool, 6.3 fixed that!

Thanks for the quick reply and good work!
