### ISSUE TITLE
corrupt driver settings

### ISSUE THREAD

**Issue by shearerp** [dbeaver/dbeaver#7381]
#### System information: 
- MacOS High Sierra 10.13.6
- DBeaver 6.3.0

#### Connection specification:
- Vertica
- SSL

#### Describe the problem you're observing:
This morning I upgraded from DBeaver 6.2.1 to 6.3.0. Upon opening the new version, none of my connections worked anymore, reporting "authentication failed". 

In our org we connect to Vertica by modifying the driver settings in DBeaver, particularly truststorepassword, truststorepath, and tls-mode. Since these settings don't exist in DBeaver's default Vertica menu, I add the settings for truststorepassword etc. by renaming existing settings, (e.g. streamingbatchinsert to truststorepassword).

After the upgrade, these settings no longer "take". I change streamingbatchinsert to truststorepassword and add the appropriate value, but when I press OK and then reopen settings, the settings name is reverted to streamingbatchinsert.

There are other ways in which my DBeaver configuration is now corrupted as well. In some projects, for example, all connections have been completely deleted.

I tried to downgrade from 6.3.0 to 6.2.1, my last working version, but the installation of 6.2.1 failed.

**Comment by serge-rider** [comment]
Could you provide more info?

- How exactly you modify driver settings?
- What `no longer "take"` means? Some screenshot would be very helpful
- Is there anything in the Error Log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)
- What is wrong with 6.2.1 installation, what exactly `failed` means?
- How do you install new dbeaver version? (pkg installer, dmg image)

**Comment by shearerp** [comment]
I ended up working around this by upgrading the Vertica driver. Will re-open if problem recurs later.
