### ISSUE TITLE
Term "table" used to refer to real tables only or views too, interchangeably (PostgreSQL)

### ISSUE THREAD

**Issue by Chealer** [dbeaver/dbeaver#7383]
The term _table_ is ambiguous in the database world, since it can include views or not. In PostgreSQL, [a view is a table](https://www.postgresql.org/docs/11/rules-views.html), so one could expect that when listing a schema's tables, DBeaver would show views there. I personally think there should be a way to list all relations together, whether tables or views.

In any case, if DBeaver wants to use "table" in its restrictive sense, then it is currently misleading since it sometimes uses it in its wide sense. For example, if I go to the Dependencies panel of a real table on which a view is based and open the _RETURN ON rule which defines the view, the Properties tab displays the view's name in a field called "Table", as can be seen in the screenshot below:
![DBeaver terminology](https://user-images.githubusercontent.com/486141/70341689-84d8a780-1821-11ea-9ca1-b9c784b68b5c.PNG)

This affects DBeaver 6.2.5 and 6.3.0.

**Comment by serge-rider** [comment]
Generally it is a kind of philosophical question.
What exactly do you propose? Replace all mentions of `Table` with `Table or view`? 
Then what about materialized views - are they tables or views? 
What about foreign tables? There are too many different types of tables, how should we refer them in general?

In regards to listing tables/views/materialized views together - we have such feature in plans (so called `simplified UI`).

**Comment by Chealer** [comment]
> 
> 
> Generally it is a kind of philosophical question.
> What exactly do you propose? Replace all mentions of `Table` with `Table or view`?

No. Some current uses of the term "table" are in the narrow sense.

> Then what about materialized views - are they tables or views?

Materialized views are hopefully views.

> What about foreign tables? There are too many different types of tables, how should we refer them in general?

I am far from a database expert (I barely used RDMBS-s other than SQL Anywhere, MySQL and PostgreSQL) and don't feel in a position to say what the best solution is. But the unambiguous term used by PostgreSQL is "relation": https://en.wikipedia.org/wiki/Relation_(database)
 
> In regards to listing tables/views/materialized views together - we have such feature in plans (so called `simplified UI`).

That is great. I think that should be the default behavior.

**Comment by serge-rider** [comment]
> That is great. I think that should be the default behavior.

Unfortunately we have too many different use-cases, different people work with tables in a different manner. 

Sometimes you need explicit separation of all possible relation types on tables, views, foreign tables, etc. Sometimes you don't. I'd say that for DBAs it is more convenient to have strict separation. Programmers usually prefer to have one list. Other people may want both representation at once.

Anyhow, we'll make some improvements in #7387.
Closing this one.

**Comment by Chealer** [comment]
> > That is great. I think that should be the default behavior.
> 
> Unfortunately we have too many different use-cases, different people work with tables in a different manner.
> 
> Sometimes you need explicit separation of all possible relation types on tables, views, foreign tables, etc. Sometimes you don't.

Sorry but I fail to understand. Are you saying the default behavior cannot be to show tables/views/materialized views together? Because some people do not want that?

**Comment by Chealer** [comment]
Is this issue supposed to be solved?

**Comment by Chealer** [comment]
I'm afraid this persists, even in DBeaver 7.2.1. Why is this ticket closed?
