### ISSUE TITLE
Export > filename > ${table} produces strange results with @set command

### ISSUE THREAD

**Issue by knwpsk** [dbeaver/dbeaver#7384]
When I export a results file and put ${table} param in the filename, it produces weird/unwanted results if I have @set t = tablename in the query/script.

Example:

_@set t = orders
select * from $"{t}"_

Get results. Highlight results and click Export to:
_MyFilename_${table}_

Filename looks like this:
_MyFileName_set_t_orders_

Recommend looking at this at the same time as issue #7370 because they're undoubtedly in the same code.

**Comment by serge-rider** [comment]
You have a wrong query (opening quote must be before dollar sign).
It has to be `select * from "${t}"`

**Comment by knwpsk** [comment]
Ach.  Sorry, Serge.
