### ISSUE TITLE
CSV Import broken

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7385]
System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 6.3.0. EE
KS, etc)? 

#### Describe the problem you're observing:
Btn "Next" is not active on step "preview data import", if to import a file using context menu of DB Navigator 

#### Include any warning/errors/backtraces from the logs
![NPsGr1rvD6](https://user-images.githubusercontent.com/51405061/70374567-035a4580-1905-11ea-95e8-107f1e94084b.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified.
