### ISSUE TITLE
How to display decimal point with comma

### ISSUE THREAD

**Issue by thiagofernando** [dbeaver/dbeaver#7386]
Hi, 

in my language the number format is  1.000,00
with "." as a thousand separator and "," as a decimal separator.

but i cant found a way to format number in this format on query results. always is displayed as 1,000.00

how can i resolve this issue?

**Comment by serge-rider** [comment]
It is controlled by locale settings in Data Formatting preference page:
![image](https://user-images.githubusercontent.com/6398845/70388961-1c78fa00-19ca-11ea-8608-8980b22b541f.png)
![image](https://user-images.githubusercontent.com/6398845/70388973-3ca8b900-19ca-11ea-9f15-6e01c1e67f48.png)

**Comment by thiagofernando** [comment]
my bad, i didnt inform to you my language, is pt-br and isnt supported.

can i change manually?

![image](https://user-images.githubusercontent.com/11356440/70398290-9d4eea80-19f8-11ea-9257-95e2c270d2c9.png)

**Comment by spascual86** [comment]
The same problem to export csv numbers. I wanted export like this 12,4.

![format](https://user-images.githubusercontent.com/58771011/70611730-f2138080-1c05-11ea-89a6-0480c5acc07f.PNG)

**Comment by thiagofernando** [comment]
hi, my bad, i didn't tell to you my language. i can't capable to change this settings inside my language. In this language is not possible to use on this format?

![image](https://user-images.githubusercontent.com/11356440/70675428-ee184a80-1c67-11ea-82ad-461007410b9e.png)

**Comment by serge-rider** [comment]
I've just realized that this problem is caused by our Java (11.0.5) bundled in CE version.
Locale-specific number formattings are not working with it.

**Comment by serge-rider** [comment]
I'll add locales support for pt and ru locales.

**Comment by thiagofernando** [comment]
thanks Serge

**Comment by uslss** [comment]
verified

**Comment by kharkot** [comment]
Hello, could you add locales for pl (Poland)?

**Comment by AdamFonagy** [comment]
@serge-rider can you add locales for Hungary as well?
