### ISSUE TITLE
Database navigator view enhancements

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#7387]
We need to support:
1. Simplified view (only tables are visible)
1. Tables grouping - view all tables types in one folder (#7383)
1. Possibility to hide/show folder(s).
1. Use view templates (so view settings could be applied globally or for particular connections).

**Comment by uslss** [comment]
Simplified view (only tables are visible) - verified; 
Tables grouping - view all tables types in one folder (#7383) - verified;
Possibility to hide/show folder(s). - verified
