### ISSUE TITLE
When I use a VPN to connect to the database on my computer, DBeaver cannot connect to the database. Can you tell me why?

### ISSUE THREAD

**Issue by EasyProgramming** [dbeaver/dbeaver#7389]
When I use a VPN to connect to the database on my computer, DBeaver cannot connect to the database. Can you tell me why?

**Comment by EasyProgramming** [comment]
hey，i need help :)

**Comment by uslss** [comment]
hi @EasyProgramming ,
sorry for the late response.
could you post log or error that appears? 
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by uslss** [comment]
there is no update on issue more than a month.
Ticket closed.
If issue still reproducible for you - feel free to reopen the ticket

**Comment by rirjkl19** [comment]
Hi! I can't seem to connect to our office database using dbeaver in mac. I am using a IPsec vpn to access our database in windows in dbeaver as well. But in mac environment I cant. Please help

**Comment by huwangliang** [comment]
i have the same problem in mac environment! the err is connection time out every time

**Comment by EasyProgramming** [comment]
> 嗨@EasyProgramming，
> 很抱歉收到您的回复。
> 您可以重置出现的日志或错误吗？
> [https://github.com/dbeaver/dbeaver/wiki/日志文件](https://github.com/dbeaver/dbeaver/wiki/Log-files)

hi,the problem desc:

Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
  connect timed out
  connect timed out

i can use our vpn client to connect my company's ip,but Dbeaver can't
