### ISSUE TITLE
Properties btn in ERD: attributes visiability, attribute style, restore defaults don't work

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7391]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 6.3.0 EE

#### Describe the problem you're observing:
If ERD Properties are opened by btn in the lower right corner, changing "attributes visiability", "attribute style", "restore defaults" don't work after pressing "apply and close" btn.

Note:
Changes are applied if to press F5 after pressing "apply and close" btn as described above.

![dbeaver_tw0aYXeVL1](https://user-images.githubusercontent.com/51405061/70418551-abdae780-1a74-11ea-8bea-62e88f4b2463.png)

**Comment by serge-rider** [comment]
fixed

**Comment by kseniiaguzeeva** [comment]
"Attributes visiability", "attribute style" are ok now, but "restore defaults" still changes nothing..

![7A4rvntckg](https://user-images.githubusercontent.com/51405061/70827568-99f19f80-1dfa-11ea-933f-fefadc957cca.gif)

**Comment by serge-rider** [comment]
We need another ticket for that. In fact we have quite many pref pages which don't support "Restore defaults" action.

**Comment by kseniiaguzeeva** [comment]
Verified
