### ISSUE TITLE
PostgreSQL column data type NUMERIC(p,s) auto mapped to INTEGER of Snowflake. 

### ISSUE THREAD

**Issue by tkang007** [dbeaver/dbeaver#7393]
Hi there, 

Thanks for your contributions for very valuable solution, data transfer between DBMS.

I found an issue need to be fixed as soon as possible.

When export PostgreSQL table to Snowflake table, I found NUMERIC(p,s) mapped to INTEGER.

Is there any workaround for this abnormal case for temporary until resolve it, except manual data type mapping ?

Thanks.

**Comment by tkang007** [comment]
We can apply any PostgreSQL NUMERIC, NUMERIC(p,s) type without converting. 
Just apply as is with NUMERIC, NUMERIC(p,s) or  NUMBER, NUMBER(p,s) for Snowflake.  
Thanks.

**Comment by LonwoLonwo** [comment]
Currently, DBeaver recognizes very few Snowflake data types. Only those returned by the driver. So this ticket is more about adding more data types to Snowflake.
https://docs.snowflake.com/en/sql-reference/data-types.html

**Comment by uslss** [comment]
not actual for 22.0.1
