### ISSUE TITLE
Missing syntax highlighting for Sybase IQ double slash (//) comments

### ISSUE THREAD

**Issue by zolovey** [dbeaver/dbeaver#7394]
**Is your feature request related to a problem? Please describe.**
DBeaver missing syntax highlighting for Sybase IQ double slash (//) comments

http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc38151.1510/html/iqrefbb/X315928.htm

**Comment by LonwoLonwo** [comment]
Double slash comments indicators for Sybase implemented in DBeaver 21.0.3

**Comment by uslss** [comment]
verified
