### ISSUE TITLE
Add possibility to have different syntax highlighting for Functions and Data types.

### ISSUE THREAD

**Issue by zolovey** [dbeaver/dbeaver#7395]
**Is your feature request related to a problem? Please describe.**
Add possibility to have different syntax highlighting for Functions and Data types.

Currently both are controlled by SQL datatype color.

At least when using Sybase IQ DB

**Comment by E1izabeth** [comment]
We added the separate color setting for functions. It will be available in DBeaver 24.1.2
The color is the same as for data types by default. However, you can change it now.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/dd9313a9-57fd-4c49-b75e-5869d1311f07)

**Comment by zolovey** [comment]
@E1izabeth , thanks now it is better, however DBeaver still does not interpret some SAP IQ functions as functions, and colors them as Keyword or ordinary text

i.e. CAST/COALESCE/ISNULL
![image](https://github.com/dbeaver/dbeaver/assets/56155099/c03733f9-e406-4ce0-8206-0e2fdca84a78)

I hope that case  #7396 could be solved soon
