### ISSUE TITLE
When switching back to a database in Navigator, the connection is lost

### ISSUE THREAD

**Issue by jyinpci** [dbeaver/dbeaver#7397]
Starting from 6.2.5 (and still happening in 6.3.0), when switching back to a database that has been accessed before, any query from already opened SQL editor tabs will encounter "not connected to database" error.  This is with Postgresql and the "auto-sync connection with navigator" is selected.

I can switch to a database in the navigator that has not been accessed in the current session of DBeaver and queries would work.  But if I use the navigator to switch back to a previous database accessed in the current session of DBeaver, I would get the error - even though the navigator shows the database as activated.  I have to restart DBeaver to access that database.

Thank you for your help!

**Comment by serge-rider** [comment]
Probably I'm doing it wrong. Anyhow - I can't reproduce this problem.
Some screenshot/video would be very helpful.

**Comment by jyinpci** [comment]
Thank you very much for looking into this.  I attached a series of screenshots taken in the order of steps to reproduce the issue:
1-SQLEditor-setting.jpg:  shows the SQL Editor setting of auto-sync connection with navigator.
2-access-acme.jpg: shows successful access to the acme database in navigator.  The query worked.
3-access-adirect.jpg: shows successful access to another db after switching to it in navigator.
4-access-acme-again.jpg: shows the connection error when running the same query after switching back to acme db in navigator.

Please let me know if more information is needed.
![1-SQLEditor-setting](https://user-images.githubusercontent.com/12385381/71287161-8b910f80-2335-11ea-9a96-7f379de44873.jpg)
![2-access-acme](https://user-images.githubusercontent.com/12385381/71287171-9481e100-2335-11ea-9b83-654cf3bc0a03.jpg)
![3-access-adirect](https://user-images.githubusercontent.com/12385381/71287181-9ba8ef00-2335-11ea-9e0c-7b57cc8b7a27.jpg)
![4-access-acme-again](https://user-images.githubusercontent.com/12385381/71287188-a19ed000-2335-11ea-836f-a1fa85f80b32.jpg)

**Comment by uslss** [comment]
cannot reproduce it against 7.0.3. If issue is still actual for you - feel free to reopen the ticket
