### ISSUE TITLE
Cannot save function edit because no function header comes up

### ISSUE THREAD

**Issue by ANTGOMEZ** [dbeaver/dbeaver#7398]
#### System information: 
- Operating system (distribution) and version: Windows 7
- DBeaver version: 6.3.0.201912021731

#### Connection specification:
- Database name and version: Postgresql

#### Describe your question:
I'm trying to edit my function. I double click on it and what comes up is the function code from the DECLARE clause onward. So when I try to save I get an error because the function header is not in the code. In prior versions of DBeaver I could edit and save without issues because the function header would show with all the code.

Is there a setting or something I need to do in this newer version to edit the function with the header?

**Comment by serge-rider** [comment]
There is a toggle in the bottom toolbar:
![image](https://user-images.githubusercontent.com/6398845/70713964-3aab6680-1cf8-11ea-82f6-06f942f5688d.png)
