### ISSUE TITLE
Can't connect hive

### ISSUE THREAD

**Issue by Junvn** [dbeaver/dbeaver#7399]
#### System information: 
- Operating system (distribution) and version:
windows7 
- DBeaver version:
6.3.0

#### Connection specification:
- Database name and version
hive 2.3.6

#### Describe your question:
After config hive driver jar:
hive-jdbc-2.3.6.jar

I get an error:
Unexpected driver error occurred while connecting to the database
  org/apache/hive/service/rpc/thrift/TCLIService$Iface
  org/apache/hive/service/rpc/thrift/TCLIService$Iface
    org.apache.hive.service.rpc.thrift.TCLIService$Iface
    org.apache.hive.service.rpc.thrift.TCLIService$Iface

please help me slove it!!!

**Comment by Junvn** [comment]
whether i must use hive-jdbc-uber-2.6.5.0-292.jar???

**Comment by serge-rider** [comment]
It is recommended to user uber jar 2.6.5 driver (which is preconfigured in dbeaver). You can try some other version iv 2.6.5 doesn't work with your server.
Could you send error stacktrace? It can be found in Error Log view.

**Comment by Junvn** [comment]
I had sloved my issues by using driver jar: hive-jdbc-2.3.6-standalone.jar

thx
