### ISSUE TITLE
Export results in TXT file without trailing spaces

### ISSUE THREAD

**Issue by v1nc3n4** [dbeaver/dbeaver#7401]
Hi,
Actually when exporting results of a SELECT query in a TXT file, the file contains extra trailing spaces, due to settings in the dialog below:

![dbeaver](https://user-images.githubusercontent.com/5869062/70626665-26e30000-1c25-11ea-940f-46b27c0007a9.png)

The result is that the user must trim trailing spaces in the exported file.
The request is DBeaver trim each line if the maximum length is not reached, either as the default behaviour, or as an option in the dialog.

Thank you for your help!
BR,
Vincent

**Comment by calfzhou** [comment]
meet the same issue now...

**Comment by kseniiaguzeeva** [comment]
The similar feature request https://github.com/dbeaver/dbeaver/issues/7345

**Comment by ShadelessFox** [comment]
Implemented in #11027
