### ISSUE TITLE
alias name doesn't work with same name as column name on using ST_AsGeoJSON

### ISSUE THREAD

**Issue by csbako-gl** [dbeaver/dbeaver#7403]
#### System information: 
- Operating system (distribution) and version: Windows 10 Professional x64
- DBeaver version: 6.3.0.201912042122
- Java version: 1.8.0_231
- Additional extensions: plpgsql, postgis

#### Connection specification:
- Database name and version: PostgreSQL 10.4
- Driver name 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
this request returns with null in geometry column:
`SELECT id, ST_AsGeoJSON(geometry)::jsonb AS geometry FROM saved_places`

this request returns with valid values in geometry2 column:
`SELECT id, ST_AsGeoJSON(geometry)::jsonb AS geometry2 FROM saved_places`

#### Steps to reproduce, if exist:
try to create a table with geojson data, and run the first request.

**Comment by uslss** [comment]
Hi @csbako-gl , 
unfortunately, cannot reproduce an issue. is it still actual for you against 7.0 version?

**Comment by csbako-gl** [comment]
Hi @uslss,
It works fine in 7.0 version. Thanks!
