### ISSUE TITLE
[ESTHETIC] table alias autocomplete should take into consideration reserved words

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#7405]
Hi!
When auto-completing table names, i receive an alias.
In case my table name is - example - `orders_received`, the alias gets `or`, which is a reserved wird, which makes the query fail.
Both use `"` to surround the alias (bad), or call it like `or1` (ugly) or else :-)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by kseniiaguzeeva** [comment]
Verified
