### ISSUE TITLE
Dbeaver throws errors when there are spaces in code

### ISSUE THREAD

**Issue by eriklanegithub** [dbeaver/dbeaver#7406]
I use dbeaver 5 to query redshift and other databases and notice that it is very fussy. It throws an error if I have a space in my code, a blank line. Very frustrating since I came from SQL Server world and no problem there like this ever happens.
Also creating #temp tables in sql is so handy, totally eliminating the 'with' requirement, and letting us test portions of code quickly.  Dbeaver is much more difficult to work with because of this.

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
hi @eriklanegithub ,
if i understand you correctly - unchecking of highlighted option could help 
![image](https://user-images.githubusercontent.com/31996417/70725124-de067680-1d0c-11ea-87b6-60c82a6a6ca3.png)
Also, if you use DBeaver 5.x version you could try most recent version (6.3.0)

**Comment by eriklanegithub** [comment]
aha, wow, thank you, that works great...

**Comment by eriklanegithub** [comment]
I am in a bit of a crisis, I had dbeaver 5, and copied out the database
connections xml file, then installed DB 6.3.1 and have attempted multiple
times to load the old connection file, but cannot. How do I do this? I am
using a VM. I first copied it to the c:/user/dbeaver4/general folder, but
then I wonder if db 6 is in that folder, or if it's in the Program files
folder? And if the latter, then where do I copy this file?

**Comment by serge-rider** [comment]
@eriklanegithub generally you don't need to copy anything. DBeaver must do it for you. You can just delete new workspace (https://github.com/dbeaver/dbeaver/wiki/Workspace-Location) and restart dbeaver - it has to perform migration process.

If, by some reason, it won't work:
- Please send any errors/logs which occurs during migration.
- You can copy datasource.xml into new workspace/general (it has to be empty) manually. Then restart dbeaver and it must catch all connections in the xml file.

**Comment by eriklanegithub** [comment]
I now see the dbeaver-data xml file but the actual connections to the 12
databases I had before are not there in the db navigator window. How do I
make them reappear and be active as they were prior to the upgrade?

So hugely frustrating that these things aren't easier to do. I have
literally spent all day on this. Does the data-sources.xml file need to be
converted to json? If so, how?

E
