### ISSUE TITLE
Cannot edit JSON cells in data viewer (PostgreSQL/Mac OS X)

### ISSUE THREAD

**Issue by roelofreinders** [dbeaver/dbeaver#7407]
Hi,

Since 6.3.0 I have become unable to edit JSON cells in the data viewer. When I double click in the cell I don't get a typing cursor, and when I open the 'Value' dialog the layout is warped and not readable.

PostgreSQL 11 / Mac OS X

**Comment by uslss** [comment]
hi,
this issue was already fixed and released as a hotfix. you could re-download 6.3.0 once again
