### ISSUE TITLE
Copy rows as json doesn't support reverse sorting by id

### ISSUE THREAD

**Issue by megabyte0** [dbeaver/dbeaver#7408]
#### System information: 
- Operating system (distribution) and version
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
$uname -a
Linux topagent8-Lenovo-ideapad-100-15IBD 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- DBeaver version
Version 6.3.0.201912021731
- Additional extensions

#### Connection specification:
- Database name and version
$ mysql --version
mysql  Ver 14.14 Distrib 5.7.28, for Linux (x86_64) using  EditLine wrapper
- Driver name
MySQL Connector/J [mysql-connector-java-8.0.11 (Revision: 6d4eaa273bc181b4cf1c8ad0821a2227f116fedf)])
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
Copying wrong rows with context menu - advanced copy - copy as JSON
when sorted by id desc

#### Steps to reproduce, if exist:
1. In an arbitrary database create table test with field id primary key
2. Fill the table with 50 consecutive ids 1 through 50
3. double-click on the table in the database navigator
4. select 'Data' tab on the right
5. Change order to be descending by id
6. Select the two upper rows with ids 50 and 49
7. Context menu - advanced copy - copy as JSON
8. Expected result:
{
"test": [
	{
		"id" : 50
	},
	{
		"id" : 49
	}
]}
Actual result:
{
"test": [
	{
		"id" : 2
	},
	{
		"id" : 1
	}
]}

#### Include any warning/errors/backtraces from the logs

Nothing relevant in the logs.

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on issue more than a month.
Ticket closed.
If issue still reproducible for you - feel free to reopen the ticket

**Comment by megabyte0** [comment]
Fixed in 7.0.0

**Comment by OysteinBrandt** [comment]
I have a similar issue where if I sort by any column and then select two rows and do a _Copy as JSON_, they are from a different area of the table from those I have selected.

DBeaver version:  7.0.0.202003021717
