### ISSUE TITLE
DBeaver: Updating requested SQL grid data from SQL command using user parameters ask for parameter(s) again

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#7409]
DBeaver - **Version 6.3.0 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

When I update a requested SQL grid data based on a SQL command using user parameter(s), *DBeaver* ask for the parameter(s) again.

**o** Execute the SQL command below:

&nbsp;&nbsp;&nbsp;`SELECT :HelloMessage AS Message;`

**o** *DBeaver* ask for the parameter value.

**o** Click to set focus in the result grid.

**o** Press the **F5** key to update the data.

**o** *DBeaver* as for the parameter value again. This is **annoying/unnecessary**.

**o** In the result grid, enter a filter below and press **ENTER**:

&nbsp;&nbsp;&nbsp;`Message IS NOT NULL`

**o** *DBeaver* as for the parameter value again. This is **annoying/unnecessary**.

*DBeaver* ought to run the grid update (either way it is updated) with the same parameter value(s). If the user want to change the parameter(s) value, he has to rerun the SQL command.

**PS**. I kind of remember this misbehaviour from a previous version of *DBeaver* and kind of remember that it was fixed too.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed.
I don't think that it worked before with simple parameters. But it could work with variables (${varName}).

**Comment by kseniiaguzeeva** [comment]
Verified
