### ISSUE TITLE
Table data editor: Row edition buttons hidden

### ISSUE THREAD

**Issue by wpomier** [dbeaver/dbeaver#7410]
#### System information: 
- Operating system (distribution) and version: Linux 4.15.0-70-generic #79~16.04.1-Ubuntu SMP x86_64 GNU/Linux.
- DBeaver version: 6.3.0.201912011827
- Additional extensions: None

#### Connection specification:
- Database name and version: mysql Ver 8.0.16 for Linux on x86_64 (MySQL Community Server - GPL)
- Driver name: MySQL (lib: mysql-connector-java-5.1.44.jar)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
In the Table Data Editor, the edition buttons (add, duplicate, delete) aren't shown when the view is opened, independently of the screen/window size. 
![bug01](https://user-images.githubusercontent.com/10353008/70735622-59583000-1ced-11ea-9cb8-d33823d49527.png)

But the buttons come back if you change the view type (Grid to Text and to Grid again) or if you maximize the view and restore it again (i.e. pressing Ctrl+M twice)
![bug02](https://user-images.githubusercontent.com/10353008/70735670-71c84a80-1ced-11ea-9f3b-d3705f8c4321.png)

#### Steps to reproduce, if exist:
See problem description.

**Comment by uslss** [comment]
thanks for the bug report. 
it seems disabled buttons aren't shown. so if in mentioned case Next button is clicked, Previous button appears

**Comment by uslss** [comment]
#7260
