### ISSUE TITLE
Table Name

### ISSUE THREAD

**Issue by Ferrox12** [dbeaver/dbeaver#7411]
Hello,
why when I write the name of a table in a SQL sheet Dbeaver automatically put a letter after the table name?
Example:
SELECT *
FROM USERS x;
Can I disabilitate this feature?

**Comment by kseniiaguzeeva** [comment]
Hello,
It is a table alias. You can disable the function in Window>Preferences>SQL Editor> SQL Completion.
![yhNay0Yp3t](https://user-images.githubusercontent.com/51405061/71320772-46014d80-24c1-11ea-9232-cc04b5e6a2bf.png)

**Comment by Ferrox12** [comment]
OK thank you very much
