### ISSUE TITLE
UI bug: Grids don't show changes made to its content.

### ISSUE THREAD

**Issue by pomgui** [dbeaver/dbeaver#7414]
#### System information: 
- Operating system (distribution) and version: Linux 4.15.0-70-generic #79~16.04.1-Ubuntu SMP x86_64 GNU/Linux.
- DBeaver version: 6.3.0.201912011827
- Additional extensions: None

#### Connection specification:
- Database name and version: mysql Ver 8.0.16 for Linux on x86_64 (MySQL Community Server - GPL)
- Driver name: MySQL (lib: mysql-connector-java-5.1.44.jar)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Some fields (containing text, checkboxes, comboboxes, etc.) in different grids of Dbeaver (dialogs and views) allow edition, but they don't show the modification until Enter is pressed or the focus is moved to another place. E.g. clicking on a checkbox the visual remains intact, but the value was already changed, or after opening the list of a combobox and selecting a different value, the old value is still shown whereas its value has changed.

This leads to confusion, because it seems that the field is readonly when it effectively can be changed.

This happens with:
* The "properties" grid in the New Column Editor dialog box (all the properties). 
  * Here the probable solution is enabling the column editor view as a modal dialog for the new columns instead of the grid.
* The columns tab in the table editor view (name of a not saved new column, data type, default, comment, etc.)
* The foreign keys in the table editor view (the name of a still not saved new FK)
* The "columns" grid in the New Index dialog box (order)
* Etc.

#### Steps to reproduce, if exist:
Just open any of the grids mentioned in the description and try to edit the field content. E.g. if it's a text field you won't see any echo of the pressed keys until the Enter is pressed or the focus is changed.

**Comment by uslss** [comment]
seems to be similar to #5742
