### ISSUE TITLE
how to do one to many and one to one in ER diagram?

### ISSUE THREAD

**Issue by rc9047** [dbeaver/dbeaver#7415]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by rc9047** [comment]
I am using 6.24

**Comment by kseniiaguzeeva** [comment]
Is it still actual for you? Could you give more info?

**Comment by uslss** [comment]
there is no update on issue for a long time. if it is still actual for you - feel free to reopen the ticket.
BR
