### ISSUE TITLE
Universal Cross-database query possible?

### ISSUE THREAD

**Issue by Lathoudero** [dbeaver/dbeaver#7416]
#### System information: 
- Windows 10
- DBeaver 6.3.0

#### Connection specification:
- Database Intersystems Cache database and SQLite database

#### Describe your question:
This wouldn't be a query-feature, but maybe there's a DBeaver-feature I'm overlooking:

Is it possible to:
1) SELECT a brandA.databaseX.table
2) store the result of this query in memory
3) UPDATE a brandB.dababaseY.table

In my case, BrandA would be the SQL-layer of Inersystems Cache database, and brandB a local SQLite database.

**Comment by serge-rider** [comment]
It is possible but complicated.
We have a ticket for that - #1804 
Generally the same task can be solved by Presto - at least in some form.

**Comment by Lathoudero** [comment]
Thank you very much, I'm looking into it.
www.prestodb.io
