### ISSUE TITLE
Transaction Log, Pending Transactions, Query Manager unreadable in Dark Theme

### ISSUE THREAD

**Issue by ethanherbertson** [dbeaver/dbeaver#7417]
#### System information: 
- Windows 10
- DBeaver 6.3.0

#### Connection specification:
- PostgreSQL

#### Describe the problem you're observing:
Light gray row text is unreadable against the green and yellow row-highlighting used by the Transaction Log, Pending Transactions, and Query Manager components.

#### Steps to reproduce, if exist:
Do a couple of queries.
Enable the dark theme.
Open the Transaction Log, and check 'Show all queries'.

Result:
![image](https://user-images.githubusercontent.com/6392396/70825776-d5647d80-1daa-11ea-9e67-7e620328b09b.png)

Similar issue, in the Query Manager component (though the slightly darker text helps a certain amount):
![image](https://user-images.githubusercontent.com/6392396/70825855-0a70d000-1dab-11ea-935b-2d20b748784a.png)

#### Include any warning/errors/backtraces from the logs
None relevant.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
