### ISSUE TITLE
DBeaver Password

### ISSUE THREAD

**Issue by McMallen** [dbeaver/dbeaver#7418]
I installed DBeaver on Kali linux operating system, but the password is incorrect Please help

**Comment by uslss** [comment]
hi @McMallen ,
what password are you talking about?
sorry for the late response

**Comment by uslss** [comment]
there is no update on ticket for a long time. if issue is still actual for you - feel free to reopen the ticket with additional info

**Comment by McMallen** [comment]
Thank you. For your attention. I got it


15 May 2020 Cum 22:40 tarihinde uslss <notifications@github.com> şunu yazdı:
