### ISSUE TITLE
case when format for 6.3.0 is bad,this bug haved 6.2.4, fixd by 6.2.5(#7181) ,but 6.2.5 also bed

### ISSUE THREAD

**Issue by hopezhangbo** [dbeaver/dbeaver#7420]
![image](https://user-images.githubusercontent.com/20311966/68440258-6b821280-0205-11ea-9941-2b6c00d59dbe.png)
this is 6.2.3 version,format "case when".it's ok.

---------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/20311966/70872511-a5ec8580-1fe3-11ea-8478-ce8a1ca89350.png)

this is 6.2.4 ,6.2.5  and 6.3.0 version,format "case when". it's different and is bad.

**Comment by kseniiaguzeeva** [comment]
Hi, can't reproduce it. Do you use "Format>Format SQL" in context menu of SQL Editor to receive such view? Please tell your OS and database.

**Comment by uslss** [comment]
there is no update more than a month - issue closed.
if issue still actual for you - feel free to reopen an issue
