### ISSUE TITLE
How do I set Trigger to disabled or enabled?

### ISSUE THREAD

**Issue by skyookys** [dbeaver/dbeaver#7421]
System information:
Windows 10
DBeaver version 6.3.0
Java version 1.6
Connection specification:
Database name and version Oracle 11g

There is a great tool for me!
But  a little question, I don't know the trigger how to change the state,and the navigate show the trigger list icon is the same,it is not to look ditectly .
Thank you!

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer. You need to drop a trigger to disable it. Please open new ticket if you have any other questions.

**Comment by p91paul** [comment]
wait a minute, there is no need to drop triggers to disable them. 'alter trigger ... disable' will do!
