### ISSUE TITLE
Why not show any tables or views in DBeaver After connecting apache phoenix???

### ISSUE THREAD

**Issue by Junvn** [dbeaver/dbeaver#7422]
#### System information: 
- Operating system (distribution) and version:
windows 7
- DBeaver version
6.3.0

#### Connection specification:
- Database name and version
apache phoenix
4.14.3

#### Describe your question:
After connecting phoenix, I can't see any tables or views in DBeaver.
It just show "SYSTEM".However my phoenix exist some tables and views,and also exist some data. 
It's strange I can create table and upsert data by sql editer in DBeaver,and even I can query from this table.But it still not show table in DBeaver GUI.
Why???
for help!!!

By the way,
other question is it looks must restart DBeaver,otherwise it will report error below when build connect:
Unexpected driver error occurred while connecting to the database
  java.lang.RuntimeException: class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider
  java.lang.RuntimeException: class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider
    class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider
    class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider

**Comment by vowor** [comment]
System information:
Operating system (distribution) and version:
windows 10
DBeaver version
6.3.1
Connection specification:
Database name and version
apache phoenix 5.0.0
HBase 2.1
After connecting phoenix, I can't see any tables or views in DBeaver.
It just show "SYSTEM".However my phoenix exist some tables and views,and also exist some data.
It's strange I can create table and upsert data by sql editer in DBeaver,and even I can query from this table.But it still not show table in DBeaver GUI.

**Comment by vowor** [comment]
兄弟，我现在也遇到了同样的问题，你有替代的方式了没？

**Comment by Junvn** [comment]
@vowor  建议使用SQuirreL SQL Client吧，虽然界面没有DBeaver华丽，但是功能至少能基本保障噢~，我现在连hive和phoenix（hbase）都是用这个工具了

**Comment by vowor** [comment]
> @vowor 建议使用SQuirreL SQL Client吧，虽然界面没有DBeaver华丽，但是功能至少能基本保障噢〜，我现在连hive和phoenix（hbase）都是用这个工具了

我找到办法了，，只要不把表建在  SYSTEM模式中就行了，，，比如新建一个  text  模式，然后再在里面建表，里面的表就都能看到了

**Comment by serge-rider** [comment]
Fixed in #7512
