### ISSUE TITLE
Data filter doesn't work in resultgrid of SQL Editor if AS is used

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7423]
#### System information:  
- Operating system (distribution) and version Windows 10
- DBeaver version 6.3.0

#### Connection specification:
- Database name and version PostgreSQL, SQL Server, SQLite

#### Describe the problem you're observing:
Data filter doesn't work for a column in resultgrid of SQL Editor if other name was given to the column using "AS" (for PostgreSQL, SQL Server, SQLite).

Steps:
1. Execute in SQL Editor: SELECT column_name AS new_name from table_name
2. Apply a filter criteria for the column in result grid

Expected result: 
The column is filtered

Actual result: 
1. Error appears: SQL Error [207] [S0001]: Invalid column name.
2. Filtering is failed.

![fqlFfHTyuD](https://user-images.githubusercontent.com/51405061/70891906-36819080-1ff9-11ea-8a05-8e378e22bf44.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by serge-rider** [comment]
It must work with workaround described in #6652

**Comment by kseniiaguzeeva** [comment]
You are right, the workaroand works. Thanks!
