### ISSUE TITLE
Foreing key edit displays as Read-Only

### ISSUE THREAD

**Issue by Daniel-Yonkov** [dbeaver/dbeaver#7425]
#### System information: 
- Operating system (distribution) and version - **Manjaro, Kernel - 4.19.88-1**
- DBeaver version - **6.2.5.201911190036**

#### Connection specification:
- Database name and version - 10.3.13-MariaDB

#### Describe your question:
Whenever I try to edit a foreing key from within the UI I get a read-only access to the information and cannot make changes. Is this due to configuration or an issue?

**Comment by kseniiaguzeeva** [comment]
Hi, it is due to configuration

**Comment by Daniel-Yonkov** [comment]
@kseniiaguzeeva - Thanks for the response, can you give me a hint where I should look for configurations which may affect this behaviour?
P.S. I am able to modify Foreing keys with a Query

**Comment by kseniiaguzeeva** [comment]
@Daniel-Yonkov, 2 ways exist:
1. to use Query as you already do.
2. to delete FK and create a new one with necessary settings.

**Comment by kseniiaguzeeva** [comment]
Please tell if you need any help with FK creating using DBeaver.
