### ISSUE TITLE
MySQL: events cannot be saved - no active db

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7428]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 6.3.1

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
Cannot save edited or newly created event - no active db is founded
![image](https://user-images.githubusercontent.com/31996417/70919925-ca238300-2032-11ea-825b-97057e5e0bef.png)

**Comment by uslss** [comment]
verified

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
