### ISSUE TITLE
"UNIQUE KEY" vs "UNIQUE" - Suspected incompatibility with firebird 3.0.3/Jaybird 3.0.8

### ISSUE THREAD

**Issue by Psi-nz** [dbeaver/dbeaver#7432]
#### System information: 
- Operating system (distribution) and version  Win10 Pro 10.0.18362 
- DBeaver version 6.3.0.201912042122
- Additional extensions none

#### Connection specification:
- Database name and version  Firebird 3.0.3
- Driver name Jaybird 3.0.8
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  nope

#### Describe the problem you're observing:

The Firebird server rejects DBeaver's SQL if i created or add any unique keys to a table.

*Example SQL created by DBeaver GUI*
CREATE TABLE TESTTABLE (
	ID INTEGER NOT NULL,
	TESTUNIQUE VARCHAR(100),
	CONSTRAINT TESTTABLE_PK PRIMARY KEY (ID),
	CONSTRAINT TESTTABLE_UN UNIQUE KEY (TESTUNIQUE)
);

*Error returned"
SQL Error [335544634] [42000]: Dynamic SQL Error; SQL error code = -104; Token unknown - line 5, column 33; KEY [SQLState:42000, ISC error code:335544634]
  Dynamic SQL Error; SQL error code = -104; Token unknown - line 5, column 33; KEY [SQLState:42000, ISC error code:335544634]
  Dynamic SQL Error; SQL error code = -104; Token unknown - line 5, column 33; KEY [SQLState:42000, ISC error code:335544634]
    Dynamic SQL Error
    Dynamic SQL Error
      SQL error code = -104
      Token unknown - line 5, column 33
      KEY

*Reason for error*
It looks to me like Firebird does not want the word KEY after UNIQUE.
If i remove the word "KEY" and run the same SQL the statement is accepted by server.
Unless i'm being an idiot and have not setup some protocol correctly somewhere?

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed (we'll use ADD UNIQUE syntax by default as it seems to be more standard than ADD UNIQUE KEY).

**Comment by kseniiaguzeeva** [comment]
Verified
