### ISSUE TITLE
Use visual code to open Chinese garble code, please tell me DBEAVER is not using utf-8 format

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#7433]
![image](https://user-images.githubusercontent.com/26621087/70969998-44f2a980-20d8-11ea-9720-48e941552bcd.png)
Use visual code to open Chinese garble code, please tell me DBEAVER is not using utf-8 format
#### System information: 
- Operating system (distribution) and version    win10
- DBeaver version  6.30
- Additional extensions

#### Connection specification:
- Database name and version   
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
You can see and change SQL script encoding in script properties.
Just press alt+enter when cursor is in editor.

Also you can change default encoding in workspace settings:
![image](https://user-images.githubusercontent.com/6398845/71207241-7aa1b900-22b7-11ea-8508-320a67cbd1d6.png)

**Comment by Pengchenghua** [comment]
Can you convert, I set, direct garbled code

**Comment by Pengchenghua** [comment]
> 您可以在脚本属性中查看和更改SQL脚本编码。
> 光标在编辑器中时，只需按alt + enter。
> 
> 您还可以在工作区设置中更改默认编码：
> ![图片](https://user-images.githubusercontent.com/6398845/71207241-7aa1b900-22b7-11ea-8508-320a67cbd1d6.png)

Can you convert, I set, direct garbled code

**Comment by Pengchenghua** [comment]
Can you convert, I set, direct garbled code

**Comment by serge-rider** [comment]
What about your particular file encoding? It may differ if you use external scripts.
![image](https://user-images.githubusercontent.com/6398845/71306448-95784880-23f1-11ea-97f3-a52e7a78bad7.png)
