### ISSUE TITLE
Highlighted table names have no text

### ISSUE THREAD

**Issue by david-cortes** [dbeaver/dbeaver#7434]
**Steps to reproduce:**
* Expand the databases pane to show tables of some DB.
* Resize the pane so that the table names would not display entirely without scrolling.
* Hover the mouse over some table so that it would show its full name in a pop-up.

**Expected behavior:** Should show a small pop-up with the complete table name, and the pop-up should disappear as soon as the mouse is moved off the table.

**Actual behavior:** Shows a pop-up with the size of the full table name, but without the actual text:
![table_name_highlight](https://user-images.githubusercontent.com/11860098/71000442-019e3800-20e4-11ea-9840-f3216543b75e.png)

**Setup:** DBeaver 6.3.0, running on windows 10.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Seems to be a bug in Eclipse dark theme styling. Not sure we can fix it from our side..

**Comment by serge-rider** [comment]
Fixed. Additionally tooltip icon was added and popup delay time was reduced.

**Comment by uslss** [comment]
verified
