### ISSUE TITLE
Database changes in SQL editor only after tab reopening

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7435]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.1

#### Connection specification:
- Database name and version MySQL, PostgreSQL

#### Describe the problem you're observing:
When i change db using ctrl+0 - it stays the same until i switch between tabs. if db is changed using dropdown list  (for MySQL) everything works ok
![2019-12-17_17h09_51](https://user-images.githubusercontent.com/31996417/71010525-0cb19200-20fd-11ea-9d93-03243e3123eb.gif)

**Comment by serge-rider** [comment]
Can't reproduce. Please check it on the latest build

**Comment by uslss** [comment]
still reproducible
![2019-12-19_13h07_02](https://user-images.githubusercontent.com/31996417/71164635-8a41e300-2260-11ea-93ae-4184f32335d6.gif)
