### ISSUE TITLE
DBeaver: Remove annoying popup for SQL script parameter values when moving to next segment

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#7436]
#### System information: 
- Operating system  : Windows10
- DBeaver version : Version 6.3.0 

The following issue reoccurred. 

https://github.com/dbeaver/dbeaver/issues/4887

It has been confirmed that this does not occur in version 6.2.0.

Please confirm.
Thank you for making a good program available.

**sample sql**

**SELECT :msg , rownum 
  FROM dict
 WHERE 1 = 1
 AND rownuM < 300**

**Comment by serge-rider** [comment]
The same issue as #7409
You can test the fix in Early Access version.
