### ISSUE TITLE
Export from query cannot be executed if active db is not similar to db in sql editor

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7439]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.1

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
Export from query cannot be executed if active db is not similar to db in sql editor
![image](https://user-images.githubusercontent.com/31996417/71087783-15ae6c00-21ae-11ea-96ff-f0bb707071c2.png)

**Comment by uslss** [comment]
the same issue appears for mongodb

**Comment by serge-rider** [comment]
This is not a bug. In order to run export you need to set proper active database in your SQL editor (using main toolbar).
Active database in database navigator has nothing to do with editor's active database.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
still reproducible

**Comment by uslss** [comment]
verified
