### ISSUE TITLE
MySQL: Incorrect pop-up appears when choosing active db

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7440]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.1

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
Incorrect window appears for mysql, so for db changing it is needed to choose db, then choose table that seems quite strange. If only db is changed - nothing happens
![image](https://user-images.githubusercontent.com/31996417/71088629-e7319080-21af-11ea-949b-ff1f8d8f73f8.png)
the same window in 6.3.0
![image](https://user-images.githubusercontent.com/31996417/71088656-ffa1ab00-21af-11ea-967b-0770af2a0179.png)

**Comment by uslss** [comment]
the same issue appears for mongodb

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
