### ISSUE TITLE
Limit number of records of a table

### ISSUE THREAD

**Issue by nazeemmohammed** [dbeaver/dbeaver#7441]
I am using enterprise edition 6.2 for redshift, in the database navigator when I select an object and click on view data it opens a the tab for data/properties/er diagram. And it tries to get the data from the full table, i.e. issues select * from <table>, without any limit clause.

Does the resultSet fetch size property not applied in this case?

**Comment by Trane9991** [comment]
Faced the same issue. In my case, this checkbox was unchecked by default.
Checking it seems to solve the problem, however, it is very weird (and potentially dangerous) to have it unchecked by default.
<img width="282" alt="settings" src="https://user-images.githubusercontent.com/9948629/79437270-a1a89700-7fda-11ea-9e2e-ac447f946d1b.png">

**Comment by nazeemmohammed** [comment]
Thanks
