### ISSUE TITLE
[PostgreSQL] Unique constraints are listed under "Indexes" and treated incorrectly

### ISSUE THREAD

**Issue by cpburnz** [dbeaver/dbeaver#7443]
#### System information: 

- OS: Ubuntu 18.04 64bit
- Java: OpenJDK 11.0.4
- DBeaver: 6.3.0.201912011827
- Additional extensions: No

#### Connection specification:

- DB: PostgreSQL 9.4.7
- Driver: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

The DDL for unique constraints is displayed properly on tables, and under the "Constraints" tab. However, when examining the unique constraint object under the "Indexes" tab, its DDL is incorrectly being interpreted as a *unique index* which is subtly different.

The simplest solution would be to not list unique constraints under the "Indexes" tab (or tree view).

#### Steps to reproduce, if exist:

Create a table with both a unique constraint and unique index. The unique index is just to show the distinction from the unique constraint.

```sql
CREATE TABLE test_table (
	name text
);

ALTER TABLE test_table ADD CONSTRAINT test_table_name_key UNIQUE (name);

CREATE UNIQUE INDEX test_table_name_idx ON test_table (COALESCE(name, ''));
```

Under the "Constraints" tab of *test_table*, *test_table_name_key* is properly listed, and performing any action uses the proper DDL to manage the object.

Under the "Indexes" tab of *test_table*, both *test_table_name_key* (unique constraint) and *test_table_name_idx* (unique index) are listed. Actions on *test_table_name_idx* (unique index) use the proper DDL to manage the object. However, actions on *test_table_name_key* (unique constraint) use the wrong DDL because it is a unique constraint, not a unique index.

For example, trying to delete *test_table_name_key* from the "Indexes" tab generates the DDL:

```sql
DROP INDEX public.test_table_name_key;
```

which should be (as is properly generated from the "Constraints" tab):

```sql
ALTER TABLE public.test_table DROP CONSTRAINT test_table_name_key;
```

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
