### ISSUE TITLE
Hover over time zone shows daylight not standard

### ISSUE THREAD

**Issue by FireInWinter** [dbeaver/dbeaver#7447]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows 8.1 Enterprise and Microsoft Windows Server 2016 Datacenter
- DBeaver version: 6.3.0.201912042122 (Community)
- Additional extensions: None

#### Describe the problem you're observing:
At the bottom of the screen it show MST (which is correct), but hovering above it shows Mountain Daylight Time (which isn't correct).

**Comment by serge-rider** [comment]
By some reason we used timezone with daylight shift for tooltips.
Thanks for the bug report.

**Comment by kseniiaguzeeva** [comment]
Verified
