### ISSUE TITLE
The btn "gallery" dissapears in "select your database" Window

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7448]
Windows 10<br>

DBeaver 6.3.0, 6.3.1

The btn "gallery" dissapears in "select your database" Window after the view was switched to "classic" by the btn.

Steps:

Press btn "create new connection" > "select your database" Window appears as "Gallery" view.<br>

Press btn "classic".<br>

Expected result: Databases are represented in "classic view"<br>

Btn "gallery" exists to switch view back to default

Actual result: there is no Btn "gallery" in upper right corner.<br>

Note: The btn appears if reopen the window.

![B2NTuHaRb7](<https://user-images.githubusercontent.com/51405061/71235273-badf5680-230c-11ea-9687-52c99dec2c25.gif>)

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D23](https://dbeaver.testquality.com/project/8805/result/1743864/defect/6049). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D24](https://dbeaver.testquality.com/project/8805/result/1743606/defect/6050). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D28](https://dbeaver.testquality.com/project/8805/result/1744507/defect/6054). Do not remove or edit.

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D37](https://dbeaver.testquality.com/project/8805/result/1760343/defect/6091). Do not remove or edit.

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D64](https://dbeaver.testquality.com/project/8805/result/1761095/defect/6120). Do not remove or edit.

**Comment by kseniiaguzeeva** [comment]
Cannot be reproduced in 7.0.1 EA
