### ISSUE TITLE
Filter menu item not present in Database Navigator Context Menu

### ISSUE THREAD

**Issue by sjivan** [dbeaver/dbeaver#7452]
#### System information: 
- Operating system (distribution) and version : OSX Mojave 10.14.6
- DBeaver version : DBeaver EE 6.3.0.201912081802
- Java version : 1.8

#### Connection specification:
Microsoft SQL Server 14.00.3162

#### Describe the problem you're observing:
The Filter Context Menu as documented here https://github.com/dbeaver/dbeaver/wiki/Configure-Filters does not appear on the Database Navigator Context Menu. I have a saved filter but I don't see a "Filter" entry in the Context Menu

**Comment by serge-rider** [comment]
Can't reproduce (on Windows at least).
Is there anything in error/debug log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by sjivan** [comment]
No errors in logs.

![image](https://user-images.githubusercontent.com/2387369/71382923-18db9a80-25a8-11ea-82e4-55d326b1e8ba.png)

**Comment by sjivan** [comment]
I think the issue is that for Sybase and SQL Server various databases are seen, as opposed to a single database with different schemas. So in my case I would like a filter on top level menu that filters on databases

**Comment by sjivan** [comment]
You can close this. While the named filter is not appearing for SQL Server and Sybase, setting the filters at the connection level works.
