### ISSUE TITLE
"Reevaluate" btn doesn't work in execution plan

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7454]
## System information:

- Operating system (distribution) and version Windows 10
- DBeaver version 6.3.1

#### Describe the problem you're observing:

"Reevaluate" btn doesn't work in execution plan

#### Steps to reproduce, if exist:

1. Execute any statement in SQL Editor
2. Open execution plan
3. Change the statement and execute it again.
4. Press "Reevaluate" btn

Actual result: the data is not updated in Execution Plan window.

![5fqTcxQSLJ](<https://user-images.githubusercontent.com/51405061/71304697-0d874400-23db-11ea-8fec-712b6f7b6fcf.gif>)

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D29](https://dbeaver.testquality.com/project/8805/result/1743948/defect/6056). Do not remove or edit.

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D45](https://dbeaver.testquality.com/project/8805/result/1760427/defect/6099). Do not remove or edit.

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D68](https://dbeaver.testquality.com/project/8805/result/1761222/defect/6124). Do not remove or edit.

**Comment by serge-rider** [comment]
For me it works as expected. Reevaluate just refreshes execution plan for the old query (it is useful when you create indexes and do other optimizations).
To view plan for new query just run "Explain plan"
