### ISSUE TITLE
Use All columns button doesn't work as expected

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7455]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.1

#### Describe the problem you're observing:
Use All columns button doesn't work as expected when virtual FK is created - check and uncheck this column has no effect.
Use all columns is checked - no column is chosen. ok button is inactive - VFK couldn't be created
![image](https://user-images.githubusercontent.com/31996417/71310018-ff0f4b80-241f-11ea-8f4d-00948d2736e1.png)
Select All button is worked as expected
![image](https://user-images.githubusercontent.com/31996417/71310027-3b42ac00-2420-11ea-9b56-da2b908b20dc.png)

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D31](https://dbeaver.testquality.com/project/8805/result/1744539/defect/6058). Do not remove or edit.

**Comment by serge-rider** [comment]
In fact "Use All Columns" doesn't check any columns. It works in runtime using all actual table columns. Because table columns may change after setting this option and still must use all table columns.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D42](https://dbeaver.testquality.com/project/8805/result/1760971/defect/6096). Do not remove or edit.

**Comment by uslss** [comment]
VFK couldn't be created using Use all columns: when this option is checked ok button isn't available

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D57](https://dbeaver.testquality.com/project/8805/result/1761652/defect/6112). Do not remove or edit.
