### ISSUE TITLE
'Set active' is always available in the context menu

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7456]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.1

#### Describe the problem you're observing:
'Set active' is always available in the context menu even for the active dbs
![image](https://user-images.githubusercontent.com/31996417/71311654-d98b3d80-2431-11ea-8442-d3dd38272757.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
