### ISSUE TITLE
Updating Extensions Continuously Flashing Startup During Restart

### ISSUE THREAD

**Issue by RGAlexander216** [dbeaver/dbeaver#7457]
I have had this issue on Several different laptops (all Windows). I have a screen recording of it, but it's been doing this for over 20 minutes and I cannot work on my laptop because each time it pops up it takes the focus from whatever I'm doing. It's taken me over 4 minutes to type these three sentences.,.

Where can I send this video (.avi)?

**Comment by galzab** [comment]
I have same problem (W10)

**Comment by serge-rider** [comment]
It is a known issue. And it happens when dbeaver installed in write-protected folder.

Workaround: install dbeaver for current user only or in some folder other than program files.

**Comment by hennie7863** [comment]
Same problem here
