### ISSUE TITLE
 'Load sql script' btn doesn't work in DDL view

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7458]
#### System information:  
- Operating system (distribution) and version Windows 10
- DBeaver version 6.3.1

#### Describe the problem you're observing:
 'Load sql script' btn doesn't work in DDL view of Object Editor.

#### Steps to reproduce, if exist:
1. Open a table in Object Editor.
2. Open Properties>DDL of the table

Actual result:
1.  'Load sql script' btn is not active in DDL view.
2. No visiable changes after pressing the btn.

#### Include any warning/errors/backtraces from the logs
![dbeaver_1nXhWsniE6](https://user-images.githubusercontent.com/51405061/71327417-42011a00-2519-11ea-8df9-ce5594bb68d4.png)

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D36](https://dbeaver.testquality.com/project/8805/result/1744100/defect/6071). Do not remove or edit.

**Comment by serge-rider** [comment]
It is now a bug actually. Load from file action enabled only in editable DDL (e.g. for views/triggers). It is never enabled for tables.
