### ISSUE TITLE
No Output tab

### ISSUE THREAD

**Issue by pcoenen** [dbeaver/dbeaver#7461]
When executing a query, the output tab is missing ? How can I put it back? Resetting the window settings doens't seem to work.

![image](https://user-images.githubusercontent.com/17742895/71357541-621af280-2586-11ea-895c-b3d0b2c1ce4d.png)

**Comment by serge-rider** [comment]
Press <kbd>ctrl+shift+o</kbd> or click on "show server output" icon at the bottom of left toolbar.

**Comment by pcoenen** [comment]
I pressed the `show server output` multiple times, but the output tab does not appear ?

**Comment by serge-rider** [comment]
Could you check Error Log view (https://github.com/dbeaver/dbeaver/wiki/Log-files) for any errors?
