### ISSUE TITLE
Crash on startup with "Error in `/usr/bin/java': free(): invalid pointer"

### ISSUE THREAD

**Issue by acspike** [dbeaver/dbeaver#7463]
#### System information: 
- Operating system: openSUSE Leap 15.1
- DBeaver version: All released versions greater than 6.2.4
- Java version: OpenJDK Runtime Environment (build 11.0.5+10-suse-lp151.3.9.2-x8664)
- Additional extensions: Unknown

#### Connection specification:
- Database: PostgreSQL 9.6
- Driver name: org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Every release since 6.2.4 has crashed on startup. (6.2.4 works fine.) When I start dbeaver from the console, I see the following message:

```
~> /usr/share/dbeaver/dbeaver
2019-12-23 09:58:25.566 - > Start DBeaver Standalone [org.jkiss.dbeaver.core.application 6.3.1.201912221734]
2019-12-23 09:58:25.568 - > Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.0.v20191024-1147]
2019-12-23 09:58:25.572 - > Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.600.v20191025-1525]
2019-12-23 09:58:25.586 - Create display
2019-12-23 09:58:25.602 - > Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.600.v20191026-0839]
*** Error in `/usr/bin/java': free(): invalid pointer: 0x0000564cbdf827d0 ***
```

#### Steps to reproduce, if exist:
While searching for solutions online I stumbled upon the environment variable MALLOC_CHECK_. This variable is set to 3 on my system. Running `~> MALLOC_CHECK_=3 /usr/share/dbeaver/dbeaver` results in a crash. Whereas running `~> MALLOC_CHECK_=1 /usr/share/dbeaver/dbeaver` does not.

#### Include any warning/errors/backtraces from the logs

It appears to be dying before logs are generated and I'm not certain how to turn up the debug level on the logs.

**Comment by acspike** [comment]
This problem persists with DBeaver 6.3.4. Is there additional information I can gather? Would this problem report be more appropriate for a different project, perhaps OpenSuSE or Eclipse?

**Comment by vinyanalista** [comment]
I can confirm that happens with me too.

Same symptom: `/usr/bin/java': free(): invalid pointer`

**System information:**

- Operating system: openSUSE Leap 15.2 Beta
- DBeaver version: 6.2.5 or later (6.2.4 works)
- Java version: OpenJDK JRE 11.0.6 or Oracle JRE 8 Update 241
- Additional extensions: Unknown

**Comment by vinyanalista** [comment]
[DBeaver 7.0.2](https://github.com/dbeaver/dbeaver/releases/tag/7.0.2), released on Apr, 5 2020 is still affected by this issue.

**Comment by markus-mnm** [comment]
I had the same issue, but was able to run dbeaver with:
`MALLOC_CHECK_=0 dbeaver`
The same helped me resolve eclipse issues version 2019.06 and up (from memory)
(In my situation, the problem might be self inflected since I often play around with library version)
Relate eclipse bug report link: https://bugs.eclipse.org/bugs/show_bug.cgi?id=551652

**Comment by vinyanalista** [comment]
With this workaround, [DBeaver 7.0.3](https://github.com/dbeaver/dbeaver/releases/tag/7.0.3) works for me.

Here is what I did.

I removed the RPM package I was using and installed DBeaver using [Flatpak](https://flatpak.org/):

```
$ flatpak install flathub io.dbeaver.DBeaverCommunity
```

(just because I'm trying Flatpak, because I believe it's easier to update, nothing against the RPM package, which may work as well)

Then I copied its `.desktop` file to my home folder:

```
$ cp /var/lib/flatpak/app/io.dbeaver.DBeaverCommunity/current/active/export/share/applications/io.dbeaver.DBeaverCommunity.desktop ~/.local/share/applications/
```

Opened it with a text editor:

```
$ gedit ~/.local/share/applications/io.dbeaver.DBeaverCommunity.desktop
```

And added `MALLOC_CHECK_=0` right at the beginning of the `Exec=` line:

```
Exec=MALLOC_CHECK_=0 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/dbeaver/dbeaver io.dbeaver.DBeaverCommunity
```

For reference, here is the full file:

```desktop
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=DBeaver Community
Comment=Universal Database Manager and SQL Client.
Icon=io.dbeaver.DBeaverCommunity
StartupWMClass=DBeaver
StartupNotify=true
X-Desktop-File-Install-Version=0.24
Categories=IDE;Development;
Keywords=Database;SQL;IDE;JDBC;ODBC;MySQL;PostgreSQL;
GenericName=Database Manager;
MimeType=application/sql;
Exec=MALLOC_CHECK_=0 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/dbeaver/dbeaver io.dbeaver.DBeaverCommunity
X-Flatpak=io.dbeaver.DBeaverCommunity
```

Logged out from GNOME and logged in again.

Now I'm able to start DBeaver using its own icon.

**Comment by vinyanalista** [comment]
I promise I won't update my comment above again :sweat_smile:

Finally I got it exactly as I wanted.

[DBeaver 7.0.4](https://github.com/dbeaver/dbeaver/releases/tag/7.0.4), released 2 days ago, is still affected by this issue.

But I got it working with the workaround suggested by @markus-mnm, thanks!

**Comment by acspike** [comment]
This issue appears to be fixed as of [DBeaver 7.1.2](https://github.com/dbeaver/dbeaver/releases/tag/7.1.2). Thank you!

**Comment by acspike** [comment]
A similar issue has returned in (DBeaver 7.1.3)[https://github.com/dbeaver/dbeaver/releases/tag/7.1.3]. I notice that the Eclipse Platform version change was reverted.

```~> /usr/share/dbeaver/dbeaver
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 7.1.3.202007192031]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.200.v20200205-1503]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.700.v20200113-1422]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.700.v20200106-1020]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.17.0.v20200217-1511]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 7.1.3.202007192031]
> Start Core File Systems [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
> Start Core Resource Management [org.eclipse.core.resources 3.13.700.v20200209-1624]
2020-07-21 10:22:54.476 - Initializing DBeaver 7.1.3
2020-07-21 10:22:54.477 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 7.1.3.202007192031
2020-07-21 10:22:54.477 - Initialize Core...
2020-07-21 10:22:54.477 - Can't find BC security provider. Use default JCE.
2020-07-21 10:22:54.477 - BouncyCastle not registered, using the default JCE provider
2020-07-21 10:22:54.547 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.37.202007192031]
2020-07-21 10:22:54.561 - Core initialized (84ms)
2020-07-21 10:22:54.562 - Create display
*** Error in `/usr/bin/java': free(): invalid pointer: 0x000055bcb2193e70 ***```

**Comment by vinyanalista** [comment]
I'm facing this issue again with [DBeaver 7.2.1](https://github.com/dbeaver/dbeaver/releases/tag/7.2.1).

But doing that [workaround](https://github.com/dbeaver/dbeaver/issues/7463#issuecomment-622052913), I'm able to use it.

**Comment by acspike** [comment]
This issue continues to exist as of [DBeaver 7.2.3](https://github.com/dbeaver/dbeaver/releases/tag/7.2.3) (202010181902).

**Comment by uslss** [comment]
cannot reproduce it against 7.3.0.

**Comment by acspike** [comment]
I'm still experiencing the issue with 7.3.0.

```
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 7.3.0.202011291229]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.200.v20200205-1503]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.700.v20200113-1422]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.700.v20200106-1020]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.17.0.v20200217-1511]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 7.3.0.202011291229]
> Start Core File Systems [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
> Start Core Resource Management [org.eclipse.core.resources 3.13.700.v20200209-1624]
2020-12-11 08:45:03.178 - Initializing DBeaver 7.3.0
2020-12-11 08:45:03.179 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 7.3.0.202011291229
2020-12-11 08:45:03.179 - Initialize Core...
2020-12-11 08:45:03.179 - Can't find BC security provider. Use default JCE.
2020-12-11 08:45:03.179 - BouncyCastle not registered, using the default JCE provider
2020-12-11 08:45:03.249 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.46.202011291229]
2020-12-11 08:45:03.263 - Core initialized (84ms)
2020-12-11 08:45:03.264 - Create display
*** Error in `/usr/bin/java': free(): invalid pointer: 0x000055b3e481d000 ***
```

**Comment by acspike** [comment]
This problem is not reproducible in 7.3.1 and 7.3.2. Thank you.

**Comment by serge-rider** [comment]
@acspike thanks for the update

**Comment by vinyanalista** [comment]
Today I was able to install DBeaver 25.1.0 via Flatpak on openSUSE Leap 15.6 and the workaround was not needed.

Just:

```
$ flatpak install flathub io.dbeaver.DBeaverCommunity
```

And start it using its icon, as usual.
