### ISSUE TITLE
Export output folder not work when export database

### ISSUE THREAD

**Issue by netifork** [dbeaver/dbeaver#7464]
#### System information: 
- Windows 10 x64 (version 1909)
- DBeaver version 6.3.1

#### Connection specification:
- Mariadb version 10.4.11
- Driver name: mariadb-java-client version 2.4.3
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Dump Database function allway export .sql file to default path (in windows is C:\Users\[username]) despite i set Output Folder to another place. This bug just appear in dbeaver 6.3.1, i test with dbeaver 6.3.0 and .sql file is exported to the right path i set in Output Folder.
#### Steps to reproduce, if exist:
Dump a mariadb database, try set output folder path to another place

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by kseniiaguzeeva** [comment]
Verified
