### ISSUE TITLE
Copy multiple cells from excel to data editor

### ISSUE THREAD

**Issue by fabianMendez** [dbeaver/dbeaver#7467]
When I copy multiple cells from excel and paste them into the data editor all the content gets copied to all the selected columns.

![image](https://user-images.githubusercontent.com/32204060/71384152-b2f21180-25ad-11ea-967f-2b0893c75dd0.png)

![image](https://user-images.githubusercontent.com/32204060/71384166-cd2bef80-25ad-11ea-80d5-78f771bb71ad.png)

**Describe the solution you'd like**
I would like the content of the copied cells to be distributed in each selected column.

![image](https://user-images.githubusercontent.com/32204060/71384187-ecc31800-25ad-11ea-9d39-af68d153f69a.png)

**Comment by p91paul** [comment]
try ctrl+shift+v, or right click -> advanced paste

**Comment by fabianMendez** [comment]
> 
> 
> try ctrl+shift+v, or right click -> advanced paste

It worked, thank you so much

**Comment by poltpolt** [comment]
working once per 10 tries in latest v22.3.2
