### ISSUE TITLE
The result set filter data is invalid

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#7471]
![image](https://user-images.githubusercontent.com/26621087/71428643-f8712480-26fc-11ea-8924-9029da7a1efa.png)

#### System information: 
- Operating system (distribution) and version
- DBeaver version   6.31
- Additional extensions

#### Connection specification:
- Database name and version  6.31
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
hi, could you add some additional info like db type and table ddl?

**Comment by Pengchenghua** [comment]
I'm filtering from the post-query result set, I can't query, and it's normal to filter from the DDL or directly from the table

**Comment by uslss** [comment]
can't reproduce.
is it still actual for you?

**Comment by uslss** [comment]
there is no update on issue more than a month.
Ticket closed.
If issue still reproducible for you - feel free to reopen the ticket
