### ISSUE TITLE
 Connection Settings -> Initialization -> Default database/schema not work in 6.3.1 CE (after update from 6.2.4)

### ISSUE THREAD

**Issue by nekkiy** [dbeaver/dbeaver#7472]
#### System information: 
- Operating system (distribution) and version 
```
$ uname -a 
Linux nk 5.0.0-37-generic #40-Ubuntu SMP Thu Nov 14 00:14:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- DBeaver version
```
6.3.1.201912221734 CE
```
- Additional extensions are absent

#### Connection specification:
- Database name and version
```
PostgreSQL 11.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit
```
- Driver name
```
PostgreSQL JDBC Driver 42.2.5
```
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
```
No
```

#### Describe the problem you're observing:
Changing `Connection Settings -> Initialization -> Default database/schema` not work in 6.3.1 CE. Recently I  updated DBearer from version 6.2.4, but in 6.2.4 it works. 

#### Steps to reproduce, if exist:
1. Create connection to DB.
2. Change default schema in `Connection Settings -> Initialization -> Default database/schema`.
3. Connect to db.
4. Default schema is not chanched(((

![iss7472](https://user-images.githubusercontent.com/2129439/71443343-72180b00-271b-11ea-87cd-3765580f5192.png)

#### Include any warning/errors/backtraces from the logs
Logs is empty

**Comment by serge-rider** [comment]
We need to have 2 default selectors (database and schema).

**Comment by uslss** [comment]
Reopened. Default schema value changing is ignored (Oracle, PostgreSQL)
![2019-12-26_16h33_27](https://user-images.githubusercontent.com/31996417/71477897-b67bd780-27fd-11ea-8997-fd65af2773a3.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
