### ISSUE TITLE
DBeaver 6.3.1 / Active database/schema change now affects current editor only

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#7473]
Hi Serge,

merry Christmas!

I think the whole thing doesn't work as one would expect, at least for PostgreSQL.

If you have an active Editor and you change the PostgreSQL database by e.g. choosing "Set Active" from Navigator's Context Menu, then nothing happens to the editor.

I am not able to switch the database and execute my sql statement on another database.

James

**Comment by serge-rider** [comment]
Yes, changing active database in the navigator doesn't affect editor. As expected. If you need to change active database/schema in the editor - use main toolbar.

**Comment by JamesInform** [comment]
Thanks for your response.

So it breaks the previous behaviour. Good to know, so I can adjust my workflow.

Btw. the "Active Catalog/Schema" in the main toolbar is not updated. Although I can change the database of the current editor, it still shows the database from where the editor was opened the first time.

(I only talking about using DBeaver with PostgreSQL 12.)

**Comment by JamesInform** [comment]
So the menus
 **SQL Editor/Set Connection from Navigator** 
and
 **SQL Editor/Auto-Sync Connection with Navigator**
also don't have any impact on the current SQL Editor Window anymore, right?

James

**Comment by serge-rider** [comment]
@JamesInform how do you change current database? Do you use toolbar or sql queries?
I can't reproduce problem with active schema change, could you write a bit more details?

Both "SQL Editor/Set Connection from Navigator" and "SQL Editor/Auto-Sync Connection with Navigator" should work as well. If they don't then it is a bug. But I also can't reporduce this.

**Comment by JamesInform** [comment]
Hi Serge,

first of all, Happy New Year.

**SQL Editor/Set Connection from Navigator
and
SQL Editor/Auto-Sync Connection with Navigator**

probably work as expected when I switch between two connections. If I just switch between PostgreSQL databases in the same connection, it doesn't. But from what I understand, this behaviour is intended.

Before 6.3.1, I was able to set **SQL Editor/Auto-Sync Connection with Navigator** and that was very convenient for me, because I could have an SQL Editor open with a statement that I wanted to test on different databases of the same connection.

I simply had to do one click in the navigator and the editor switched to that database. Now I have to do much more clicks. But if you can't change the behaviour back (or don't want to) I can live quite well with the new one.

Thanks for your effort and keep on the valuable work on this extraordinary great tool!

James

**Comment by michalk-k** [comment]
> Yes, changing active database in the navigator doesn't affect editor. As expected. 
If it is expected, why the option is still available in context menu?

> If you need to change active database/schema in the editor - use main toolbar.
It doesn't work. Any attempt to open a drop list with database, closes the window immediately.

> Both "SQL Editor/Set Connection from Navigator" and "SQL Editor/Auto-Sync Connection with Navigator" should work as well. If they don't then it is a bug. But I also can't reporduce this.

None of those options work. It doesn't change connection nor their visualization (valid for v6.3.2)

**Comment by AOne-T** [comment]
Before upgrading to 6.3 it was convenient to change the active database in the editor through 'set as active' in navigator. Since the 'Choose catalog/schema' window closes when trying to choose clicking database combobox (see https://github.com/dbeaver/dbeaver/issues/7522).

**Comment by ianamac** [comment]
V 6.3.2 - Every time I open a script, it defaults back to the public schema, even though the schema has been set in Navigator, and on the Menu Bar. Surely, if it is set (preferably in navigator, which should update the menu bar), it should stay on that schema until manually changed. Thanks for your efforts, this is becoming a very good product.

**Comment by JamesInform** [comment]
Yep, with 6.3.3 it is very cumbersome. If you open a PostgreSQL connection, you see all that nice databases in the navigator. And then you think: "Hey, I am eager to run a script on the nice third database in the list."

But you just can't:
1. You have to open a new sql editor.
2. This sql editor default to the default database set in the connection profile.
3. You must go to the toolbar and make some clicks here and there.
4. Finally you can run the script in the database you want.

Well, works but is really cumbersome.

What about a simple additonal menu item in the context menu of the navigator, which enables me to open a new SQL editor for the database I right-clicked on? I think that would solve the problem.

Just my two cents,

James
