### ISSUE TITLE
Other boolean display forms

### ISSUE THREAD

**Issue by mkgrgis** [dbeaver/dbeaver#7474]
Add some not true/false text forms for boolean display/edit. Variants
1. Like LibreOffice (it can be from Unicode line 2610 like ☐ ☒ )
![изображение](https://user-images.githubusercontent.com/41448637/71446807-90d8ca80-2738-11ea-9e7a-c420cc11d3aa.png)
In LibreOffice Base there is changing value by whitespace.
2. NLS localised forms
3. Math/old office notation "+"=true , "-"=false, " "=NULL

In GUI this option can be placed near options for timestamp/time/date forms.

**Comment by serge-rider** [comment]
This makes sense

**Comment by mkgrgis** [comment]
It seems, LibreOffice use this symbols ▣☑☐, but icons is more universal.

**Comment by serge-rider** [comment]
Done.
![image](https://user-images.githubusercontent.com/6398845/73360768-b7989c80-42b4-11ea-8701-a566671025be.png)

To represent NULL values we use 3-state toggle.
Value can be changed by single click or by <kbd>space</kbd> key.

**Comment by uslss** [comment]
verified

**Comment by mkgrgis** [comment]
What about NLS text forms and "+/-/ "? I think it's simpler, than icons.

**Comment by pyrocks** [comment]
@serge-rider I personally don't like the null values as a box with a question mark inside. I prefer nulls to be shown as nulls. I turned off "Show booleans as checkboxes", but it would be nice to choose a 2-state toggle active only when the value is not null.
