### ISSUE TITLE
"Database import progress" window of Restore Wizard is empty

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7475]
"Database import progress" window of Restore Wizard:
1. in DB Navigator:
 is empty before process beginning. Then it shows logs when process runs.
2. in Database Task panel:
is empty before process beginning and closes as soon as "start" btn is pressed.

Maybe it will be more user friendly not to show "Database import progress" window before process beginning.
![ZMTXJbXAjA](https://user-images.githubusercontent.com/51405061/71447278-8836c300-273d-11ea-8b82-d129db8362c3.png)

**Comment by serge-rider** [comment]
Done

**Comment by kseniiaguzeeva** [comment]
Verified.
