### ISSUE TITLE
Not responding (randomly)

### ISSUE THREAD

**Issue by sk-dataocean-online** [dbeaver/dbeaver#7480]
#### System information: 
Linux Mint 18.3 Cinnamon 64-bit
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
DBeaver 6.3.1.201912221734
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~16.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

#### Describe the problem you're observing:
Around 3 minor updates before (not sure exactly) DBeaver started to use 100% CPU in 1-20 minutes after start up. Freezing is irreproducible: it could be even after paste command or in the background. All previous DBeaver versions worked fine.
Example thread dump is enclosed (I was forced to use -J-d64 option because the process was not responding).

[thread-dump.txt](https://github.com/dbeaver/dbeaver/files/4002099/thread-dump.txt)

**Comment by serge-rider** [comment]
Please test it in the recent Early Access version (https://dbeaver.io/files/ea)
We've upgraded Eclipse version (which we explicitly changed a few minor releases ago), potentially this issue can be fixed automatically.
