### ISSUE TITLE
Problem with alias suggestion

### ISSUE THREAD

**Issue by remimoncayo** [dbeaver/dbeaver#7484]
#### System information: 
- Ubuntu 18.04
- DBeaver	6.3.1.201912221734

#### Connection specification:
- Mysql 5.5.47

#### Describe your question:
The db I'm working on uses both camelCase as well as underscore_notation for table names. 
The alias or  'short name suggestion' that DBeaver gives me seems to work fine for the tables with underscore notation(I love this feature, btw) but sucks for the table(s) with camelCase in which it would  use a '2' after the first letter of the name. This is really annoying and it's happening since the last update. 

Is there any way to either get rid of that suggested '2' or make dbeaver recognize camelCase the same way it does with underscores?

![capture20192612_125429](https://user-images.githubusercontent.com/6709596/71475107-1d3dc880-27df-11ea-8dc0-0a6266b2842a.png)

**Comment by serge-rider** [comment]
Good point. And easy to implement.

**Comment by uslss** [comment]
verified
