### ISSUE TITLE
Innovative ideas and suggestions

### ISSUE THREAD

**Issue by hktalent** [dbeaver/dbeaver#7485]
Hello, I have a good idea
The master and slave network versions are implemented by overloading classloader, and the server always listens to the service
Then give your tool a very small startup, which is at most a few kilos in size to more developers. When there is no local class to use, you can go to the server to request again. The advantage of this is that the client is very lightweight

**Comment by serge-rider** [comment]
I'm afraid it will take enormous amount of time to load full client code. There are hundreds of thousands of classes, tens of megabytes of class files. Loading them in lazy mode over network doesn't sound right.

Even lazy loading of entire plugins could be very disappointing for users.
