### ISSUE TITLE
Upgrade from 6.1.1 to 6.3.1 and now get Null Reference exception when connecting to DB2

### ISSUE THREAD

**Issue by xantari** [dbeaver/dbeaver#7486]
#### System information: 
- Operating system (distribution) and version
Win 10 64bit 1903
- DBeaver version
6.3.1
- Additional extensions

#### Connection specification:
- Database name and version
DB2 IBMi V7R3
- Driver name
JT400 10.1 driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:

Get this error when connecting to DB after upgrade from 6.1.1 to 6.3.1:

![image](https://user-images.githubusercontent.com/6610039/71480549-55cdaa00-27bf-11ea-83be-9d7606792e40.png)

![image](https://user-images.githubusercontent.com/6610039/71480556-64b45c80-27bf-11ea-8f61-c25622b8fed0.png)

![image](https://user-images.githubusercontent.com/6610039/71480564-70a01e80-27bf-11ea-91d4-e36c0f827b07.png)

**Comment by serge-rider** [comment]
Thanks for the bug report. 
Workaround: disable "open separate connection" option.
![image](https://user-images.githubusercontent.com/6398845/71487752-11c5be00-282e-11ea-8416-21df30e19d9c.png)

**Comment by xantari** [comment]
That setting "open seperate connection for each editor" fixed it! Thanks
