### ISSUE TITLE
Windows 10 + dbeaver 6.3.1 CE doesn't start after sucessfull installation

### ISSUE THREAD

**Issue by Slach** [dbeaver/dbeaver#7489]
#### System information: 
- Operating system (distribution) and version
Windows 10 - 1903
- DBeaver version
6.1.3

#### Describe the problem you're observing:
when try run dbeaver-cli.exe
![image](https://user-images.githubusercontent.com/105560/71504005-681c1680-2899-11ea-9671-6856cdcc39a5.png)

when try run dbeaver.exe
![image](https://user-images.githubusercontent.com/105560/71504069-b4ffed00-2899-11ea-8764-c7b645451fa2.png)

#### Steps to reproduce, if exist:
just download and run dbeaver-ce-6.3.1-x86_64-setup.exe from github releases page

**Comment by Slach** [comment]
use ".zip" instead of ".exe" and all works fine

**Comment by serge-rider** [comment]
Looks like a broken installation. Or dbeaver.ini file doesn't correspond to the installed version.
Try to reinstall from exe.
