### ISSUE TITLE
NPE appeas after pressing "Dump database" in context menu of MySQL connection

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7490]
## System information:  
- Operating system (distribution) and version Windows 10
- DBeaver version 6.3.1

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
NPE appeas after pressing "Dump database" in context menu of a connection
#### Steps to reproduce, if exist:
Click in context menu of MySQL connection: tools> dump database
![uVs3EF6YrQ](https://user-images.githubusercontent.com/51405061/71509214-a9adc100-289b-11ea-9bd6-e2dbdeb36b5f.gif)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4004767/dbeaver-debug.log)
[.log](https://github.com/dbeaver/dbeaver/files/4004770/default.log)

**Comment by serge-rider** [comment]
Some databases or tables must be selected before export.
Fixed.

**Comment by kseniiaguzeeva** [comment]
Verified
