### ISSUE TITLE
DBeaver 6.3.1 / $$ Handling breaks ALT-Down

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#7491]
Hi Serge,

I encounter another problem in 6.3.1 with PostgreSQL.

Lets say I have the following script:

> select 1;
> 
> do
> $$
> begin
> 	select 1 into tab1;
> 	select 2 into tab2;		
> end
> $$
> ;

When the cursor is on the first "select 1;" and I press Alt-Down to select the next statement, then DBeaver only select text from "do" until the frist ";" at "select 1 into tab1;"

![image](https://user-images.githubusercontent.com/38714600/71515547-1a58db80-28a4-11ea-9f12-244bdb6678e6.png)

The problem is that I cannot execute my scripts anymore.

**Comment by serge-rider** [comment]
Was fixed in #7460 
Additional fix (previous query detection) submitted.

**Comment by JamesInform** [comment]
Hi Serge,

I have checked the early access version. And now everthing works like a charme again.

Thank you very much.

James
