### ISSUE TITLE
Restore task (MySQL): log level "Normal" can't be changed

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7495]
# System information:  
- Operating system (distribution) and version Windows 10
- DBeaver version 6.3.1

#### Connection specification:
- Database name and version MySQL 

#### Describe the problem you're observing:
Restore task (MySQL): log level "Normal" can't be changed.

#### Steps to reproduce, if exist:
-Open task wizard and create a MySQL restore task
-Change log level "Normal" on some other type from drop-down list (Script Configuration window of the task wizard)
-Save the task and then reopen it.

Actual result: 
Log level "Normal" is displayed in Script Configuration window of the task wizard.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
