### ISSUE TITLE
Incorrectly filled Script/Backup/Restore tasks fields don't show a mistake.

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7496]
#### System information:  
- Operating system (distribution) and version Windows 10
- DBeaver version 6.3.1

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
Incorrectly filled Script/Backup/Restore tasks fields don't show a mistake.
#### Steps to reproduce, if exist:
1. Create a Script/Backup/Restore task
2. Write some wrong data in fields "Extra command args"/"input file"
3. Execute the task.

Actual result:
1. Status "Success" is displayed for the task.
2. The task is not executed except backup (see Note below).

Note: 
Backup (from Navigator or task panel) creates an sql file if wrong "Extra command args" are written, but without a database content.

![5HE7YxmSNO](https://user-images.githubusercontent.com/51405061/71571560-f4be1300-2aeb-11ea-957a-260cfaf9a001.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
The error window is displayed now, but it appears twice, if backup/restore/script is executed in DB Navigator.
![G8mYloJrT7](https://user-images.githubusercontent.com/51405061/71645978-28b65580-2cf1-11ea-891e-d10206cca472.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
