### ISSUE TITLE
Unable to browse table metadata through table name in the editor.

### ISSUE THREAD

**Issue by raman002** [dbeaver/dbeaver#7497]
#### System information: 
- Windows 10 Home
- DBeaver 6.3.1

#### Connection specification:
- PostgreSQL 10.7

Problem: When I want to see the table structure of a particular table from query editor, I use either F4 or CTRL + Click  on the table name which does not seem to be working since version 6.3.1, I'm able to do the same with version 6.3.0.

**Comment by uslss** [comment]
already fixed in the scope of #7545.
anyway, thanks for the bug report :)
