### ISSUE TITLE
Row coloring doesn't work on some calculated columns

### ISSUE THREAD

**Issue by negora** [dbeaver/dbeaver#7498]
Row coloring doesn't work on some calculated columns. By "calculated column", I'm referring to a column calculated on the fly during a `SELECT` query.

For example, if I run this query:

```sql
SELECT age, count (*)
FROM student
GROUP BY age;
```

And then, I choose to color the rows whose column `count` equals 10, coloring doesn't work. If I apply the coloring on `age`, it doesn't work either.

Curiously, if I remove the column `age` from the query, it works:

```sql
SELECT count (*)
FROM student;
```

I'm not 100% sure, but I believe that coloring fails when you mix physical columns with calculated ones. If all columns are physical or all calculated, it seems to work fine.

I've tested this issue also with virtual columns, and the situation looks like the same. I guess that, from the point of view of DBeaver, calculated columns are, after all, virtual columns. Is that right?.

Thank you!

**Comment by serge-rider** [comment]
Fixed

**Comment by serge-rider** [comment]
The problem was caused by mixing tables metadata and custom queries metadata. Now they are stored separately.

Side effect: colors for direct table data reading and for custom query `SELECT * FROM table` will be different.

**Comment by negora** [comment]
Great! Thank you a lot.

**Comment by kseniiaguzeeva** [comment]
Colors are applied after refreshing.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
