### ISSUE TITLE
DBeaver 6.3.1 - MariaDB "Database Import" (Restore from contextual menu) gives a socket connection error connecting via SSH tunnel

### ISSUE THREAD

**Issue by zedee** [dbeaver/dbeaver#7501]
#### System information: 
- Ubuntu 19.10 Eoan
- DBeaver 6.3.1
- No extensions AFAIK

#### Connection specification:
- MariaDB 10.3.21 (`10.3.21-MariaDB-1:10.3.21+maria~bionic-log`)
- Using driver MariaDB 1.5.5 (`org.mariadb.jdbc:mariadb-java-client:RELEASE`)
- Connection using SSH Tunnel with public key.

#### Describe the problem you're observing:
I have set up 3 connections (production, test, local). Problem is with "Test" connection.

When I try to restore a database which I access via SSH tunnel, via "Tools" -> "Restore Database", I get a connection error and cannot restore it.

Reverting to Dbeaver 6.3.0 resolves the issue (took me a whiiiile to find out, even tried to reinstall my server database :sweat: )

#### Steps to reproduce, if exist:
If you have already a database connection which you usually use:
- Connect to a MariaDB database via SSH tunnel.
- Try to restore the database using the contextual menu ("Tools" -> "Restore Database")

#### Include any warning/errors/backtraces from the logs
Until version 6.3.0, I had no problems importing databases. The result log was always like this:
(Port changes in different connections because of tunnelling I guess)
```
/usr/bin/mysql --no-beep --host=127.0.0.1 --port=24006 -u root my_database
Database Import started at Mon Dec 30 20:48:02 CET 2019
Database Import finished at Mon Dec 30 20:48:51 CET 2019
```

But in version 6.3.1 The result log is the following:
```
/usr/bin/mysql --no-beep --host=localhost --port=3306 -u root my_database
Broken pipe
Database Import started at Mon Dec 30 20:59:39 CET 2019
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Database Import finished at Mon Dec 30 20:59:39 CET 2019
Process exit code: 1
```

I changed in the connection configuration (General -> Server Host) `localhost` by `127.0.0.1` and misteriously it connected to a weird IP (I was running Docker containers on my computer, so I guess that's Docker serving as localhost)
```
/usr/bin/mysql --no-beep --host=127.0.0.1 --port=3306 -u root my_database
Broken pipe
Database Import started at Mon Dec 30 21:02:33 CET 2019
ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.1' (using password: YES)
Database Import finished at Mon Dec 30 21:02:33 CET 2019
Process exit code: 1
```

Notice on both "Port 3306" and different error messages by changing `localhost` by `127.0.0.1`

It's like 6.3.1 skips SSH tunnelling and tries to execute the commands as if were on local machine?

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by serge-rider** [comment]
@uslss please test it on linux

**Comment by uslss** [comment]
verified

**Comment by NormanEdance** [comment]
I'm using 7.0.3  + Docker. For some reason Dbeaver was skipping auth for mysql.
Changing host from `localhost` to `127.0.0.1` helped.
