### ISSUE TITLE
Support for MongoDB Views

### ISSUE THREAD

**Issue by dmitrye** [dbeaver/dbeaver#7503]
#### System information: 
- Mac OSX Latest
- DBeaverEE 6.3.0
- Java version 13

#### Connection specification:
- NA

#### Describe the problem you're observing:
Can't open Views. They come up as collections but you can't do anything with them. I was hoping DBeaver could handle Mongo so I can use the EE version and replace NoSQLBooster or Studio3T with just 1 IDE for Databases. But not having proper Mongo View support is a pain. 

#### Steps to reproduce, if exist:
Open a view under collections

#### Include any warning/errors/backtraces from the logs
Can't read field names
  Command failed with error 166 (CommandNotSupportedOnView): 'Namespace **[redacted]** is a view, not a collection' on server**[redacted]**. The full response is {"operationTime": {"$timestamp": {"t": 1577772434, "i": 1}}, "ok": 0.0, "errmsg": "Namespace **[redacted]** is a view, not a collection", "code": 166, "codeName": "CommandNotSupportedOnView", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1577772434, "i": 1}}, "signature": {"hash": {"$binary": "9XPyTZ5uaqgNRgi4QRiON4A2/1A=", "$type": "00"}, "keyId": {"$numberLong": "6748113896621473793"}}}}

**Comment by uslss** [comment]
not actual for 22.0.0
