### ISSUE TITLE
no serveroutput shown in 6.3.1 for oracle plsql and it works  on 6.3.0

### ISSUE THREAD

**Issue by tatod** [dbeaver/dbeaver#7504]
#### System information: 
- Operating system (distribution) and version - Linux Mint 19.3 Tricia 64-bit
- DBeaver version - 6.3.1
- Additional extensions  - Excel

#### Connection specification:
- Database name and version - oracle 12.1.0.2.0
- Driver name - JDBC Thin Client
- Do you use tunnels or proxies (SSH, SOCKS, etc)? nope 

#### Describe the problem you're observing:
 show serveroutput is turned on and no output is reported against dbms_output command in plsql
 when doing exactly same in 6.3.0 it works for the same database connection

#### Steps to reproduce, if exist:
BEGIN
	dbms_output.put_line('tsting');
END;

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
