### ISSUE TITLE
Dbeaver not saving database name to filename when exporting to csv

### ISSUE THREAD

**Issue by Escondido** [dbeaver/dbeaver#7506]
#7349 ## System information: 
- Operating system (distribution) and version - Ubuntu 16.04 
- DBeaver version - 6.3.1
- Additional extensions - not applicable

#### Connection specification:
- Database name and version - Mysql 5.7
- Driver name - no idea how to check this. Does it matter? I'm running Dbeaver locally.
- Do you use tunnels or proxies (SSH, SOCKS, etc)? -nope

#### Describe the problem you're observing:
My file output for exporting csv files of my databases is as follows. 
${schema}_${table}_${timestamp}

The file ends up showing like this.
_tablename_201912311432

#### Include any warning/errors/backtraces from the logs
I don't see any errors reported when exporting the file because output the file. It just doesn't include the database name as expected.

**Comment by mkgrgis** [comment]
The same Ubuntu 18 + PosgreSQL + DBeaver 6.3.1

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
