### ISSUE TITLE
Create column gui create wrong SQL if you fill default field (GUI)

### ISSUE THREAD

**Issue by SurmaAa** [dbeaver/dbeaver#7507]
#### System information: 
- Operating system (distribution) and version - Windows 10 ver. 1809 compilation 17763.914
- DBeaver version - 6.3.1
- Additional extensions - n/a

#### Connection specification:
- Database name and version - postgresSQL, 11.6
- Driver name - node-postgres but it's gui problem
- Do you use tunnels or proxies (SSH, SOCKS, etc)? ssl

#### Describe the problem you're observing:
When I create new column by gui and fill the default field it generated wrong SQL. 
#### Steps to reproduce, if exist:
1. Create any table.
2. Go to table properties tab
3. Right click on the grid and click `Create new column`
4. Fill the default field with any **string** it's important (number can work)
5. Click Ok 
**Problem**:
You received wrong SQL eg. `ALTER TABLE public.logging_tries ADD mysupercolumn varchar NULL DEFAULT I am default field;`
If you click persist now you will get an error.
Expected:
No error, ok button should generate proper SQL e.g.
`ALTER TABLE public.logging_tries ADD mysupercolumn varchar NULL DEFAULT 'I am default field';`
will work

**Comment by serge-rider** [comment]
It is not a bug.
You need to quote your string in UI before save.
Because column default value is SQL expression, not just a string literal.
