### ISSUE TITLE
the table'name in the DDL script contains the blanks spaces.

### ISSUE THREAD

**Issue by findidea** [dbeaver/dbeaver#7508]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
Please provide more details. 
What is your database?

**Comment by uslss** [comment]
there is no update on ticket for a long time,
if issue still actual for you feel free to reopen the ticket and provide more details.
