### ISSUE TITLE
format problem 

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#7509]
The contents of concat, substr\regexp_raplce () are not displayed on the same line, but on a new line!
![image](https://user-images.githubusercontent.com/26621087/71655522-1fb99880-2d72-11ea-9570-1fd1f84a7c56.png)

#### System information: 
- Operating system (distribution) and version  win10
- DBeaver version 6.31
- Additional extensions   HIVE

#### Connection specification:
- Database name and version
- Driver name  hive
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
verified
