### ISSUE TITLE
Column data type does not show UNSIGNED

### ISSUE THREAD

**Issue by Stoumfou** [dbeaver/dbeaver#7510]
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version : 6.3.1
- Additional extensions : None

#### Connection specification:
- Database name and version : MySQL 8.0.16
- Driver name : MySQL 8+
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
I have a column create to int unsigned : "visits int(11) UNSIGNED NOT NULL,"
In "Edit Table" i am not able to see if an int(11) column is unsigned or not
![image](https://user-images.githubusercontent.com/9539370/71671762-26e1a600-2d74-11ea-9aeb-37a8443a9211.png)

It would be great to show a column "Unsigned" with a checkbox like "Not Null", and can be shown or not in "Configure columns"
![image](https://user-images.githubusercontent.com/9539370/71671938-b8e9ae80-2d74-11ea-9ef5-311ce2c3e434.png)

#### Steps to reproduce, if exist:
1.
CREATE TABLE dev_ga.properties_visits (
  advert_id varchar(30) NOT NULL COMMENT 'id of the advert in the table adverts',
  visits int(11) UNSIGNED NOT NULL,
  yesterday_visits int(11) DEFAULT NULL,
  last_update timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  lang char(2) NOT NULL DEFAULT 'fr',
  nb_favorites int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (advert_id, lang)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 58,
CHARACTER SET utf8,
COLLATE utf8_general_ci

2. Right click in table "Edit Table"

3. Can't see if int(11) is unsigned or not.

**Comment by uslss** [comment]
cannot reproduce an issue. works ok for me
![image](https://user-images.githubusercontent.com/31996417/73204085-7044cb80-414f-11ea-8bd7-b4181b17524f.png)
probably you could provide some additional info?

**Comment by Stoumfou** [comment]
Oh yes you right, it's write in Data Type column, sorry i send a wrong image. 
I come from DBFroge Studio 2019 and i expected to see a column with checkbox 'Unsigned' 
![DbForge](https://user-images.githubusercontent.com/9539370/73343252-93bb6380-4280-11ea-91c5-135d9331d09e.PNG)

It's just an habit to see unsigned in Data Type, it's worked perfectly indeed.
![DBeaver2](https://user-images.githubusercontent.com/9539370/73343303-a766ca00-4280-11ea-9364-5ef142e4a8d2.PNG)
