### ISSUE TITLE
Scipts with a "BEGIN" statement execute more than one query at a time.

### ISSUE THREAD

**Issue by jk3us** [dbeaver/dbeaver#7511]
#### System information: 
- Win 10
- 6.3.1
- I have the query separator set to semi-colon, and the "Blank line is statement delimiter" option turned off.

#### Connection specification:
- postgresql/enterprisedb 9.4 (but the same behavior happens with sqlite, at least)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
If you have a `begin` statement in your sql editor, running any query *after* that will execute all queries after (and including) the `begin`.  I think this behavior is a very recent change. 

#### Steps to reproduce, if exist:
Put this in your editor:
```
select 1;
begin;
select 2;
select 3;
rollback;
select 4;
```

If you put your cursor on `select 1` and press ctrl+enter, that one query executes as expected.  If you put your cursor on the begin or anything after it, including the `select 4` command, it executes from the begin statement to the end of the script.

#### Include any warning/errors/backtraces from the logs
In the example above, I placed my cursor on `select 4` and hit ctrl+enter, and got 3 results tabs with values 2, 3, and 4, and this in the Query Manager:

```
begin;¶select 2;¶select 3;¶rollback;¶¶select 4;
```

**Comment by serge-rider** [comment]
This happens because dbeaver treats `begin` keyword as block statement (and looking for corresponding `end` statement).
We need to process `begin` differently - depending on the script context.

**Comment by jk3us** [comment]
Just to clarify, will the corrected behavior be to always execute exactly one statement when you "Execute SQL Statement"?  An additional "Execute block" could be useful, if it would search up to a `begin` and execute through either `rollback` or `commit`, but otherwise, I would prefer dbeaver not try to be too smart when I want it to execute only the statement my cursor is currently in.

**Comment by serge-rider** [comment]
Well, a lot of people use blocks like
`declare ... begin .. end` or `do begin $$ $$ end;` . we have to be smart enough to process such blocks as a single statement.

Unfortunately in postgresql begin has two different meanings.

**Comment by uslss** [comment]
verified
