### ISSUE TITLE
Bind variables to a SQL query while using Database tasks feature

### ISSUE THREAD

**Issue by ajay-ramaswamy** [dbeaver/dbeaver#7513]
**Is your feature request related to a problem? Please describe.**
I have a huge table which contains historical data identified by date. I need to generate a txt/csv file everyday which will contain specific records from that table of that date. If I use the database task feature, I have to hard-code dates in the SQL and then run the task as currently its not allowing the use of variable binding.

**Describe the solution you'd like**
If the SQL query can take variables, values of which, can be supplied during execution of the database task from GUI, then daily task execution would not mean changing the underlying query of the task.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/72208041-6c5a4d80-34af-11ea-8445-ae50bf70a2c0.png)

**Comment by uslss** [comment]
works for mysql

**Comment by uslss** [comment]
verified
