### ISSUE TITLE
While migrating database table from Postgresql to Mysql, Foreign keys are not getting migrated, in DDL generation on mysql part, foreign keys are skipped.

### ISSUE THREAD

**Issue by anirudh1604** [dbeaver/dbeaver#7516]
While migrating database table from Postgresql to Mysql, Foreign keys are not getting migrated, in DDL generation on mysql part, foreign keys are skipped.
![Screenshot from 2020-01-03 12-50-55](https://user-images.githubusercontent.com/11210206/71711590-b6945c80-2e27-11ea-89d0-bef06076d755.png)
![Screenshot from 2020-01-03 12-51-29](https://user-images.githubusercontent.com/11210206/71711612-cb70f000-2e27-11ea-84e6-42df35a2d675.png)
![Screenshot from 2020-01-03 12-51-39](https://user-images.githubusercontent.com/11210206/71711616-d0ce3a80-2e27-11ea-8f6d-5acc42fb6ff5.png)

**Comment by serge-rider** [comment]
Data migration doesn't migrate schema structure. It is just not designed for that. Schema migration itself is a very complicated task. As foreign keys and other constraints may require some specific sequence of data insert.
Especially for cycled foreign keys or rows hierarchies (trees).

Workaround: 
1. migrate schema (manually)
1. disable schema constraints
1. migrate the data
1. enable constraints
