### ISSUE TITLE
Very old snap package version

### ISSUE THREAD

**Issue by thiras** [dbeaver/dbeaver#7518]
**Is your feature request related to a problem? Please describe.**
The current snap version is 5.x which is very old.

**Describe the solution you'd like**
Upgrade the snap package

**Comment by serge-rider** [comment]
Current snap version is 6.3.1 (https://snapcraft.io/dbeaver-ce)
We update it with every release.

**Comment by thiras** [comment]
Yes. It's my bad. Sorry for the wrong report.
