### ISSUE TITLE
script window invalid after connection parameters changed

### ISSUE THREAD

**Issue by terado** [dbeaver/dbeaver#7519]
#### System information: 
- Windows Version	10.0.18363 Build 18363
- DBeaver version: 6.3.1.201912221734
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name: Postgres
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
When a script window is open against a connection and the connection password and hostname are changed and reconnection made, the script window is no longer valid for the same database

#### Steps to reproduce, if exist:
1. Create a valid connection called database1
2. Open a script window on database1 and write some valid sql
3. Hit F4 on database1 and change the host and password
4. Reconnect
5. Try running any of the sql in the same script window it will not work, a new script window must be created

**Comment by serge-rider** [comment]
Can't reproduce. 
What exactly error do you see?

**Comment by terado** [comment]
sorry I wasn't explicit enough about how the script window change. So for example:
After reconnection if I set the active database within the connection to "mydb" then run
  select current_database();
it will return `postgres`. and 
  select current_schema();
returns `public`
No changes to what is active on the left affect the script window on the right.

Opening a new script window will and running the above will return `mydb` as the correctly selected active database.

**Comment by serge-rider** [comment]
Do you mean that active database setting is not applied to open editors after reconnect?

**Comment by terado** [comment]
not just that, you cannot change the active database or schema from the left side against the script window on the right. Opening a new script window you can change and it will take affect on the right.
Again sorry for not being clear on the report on that element

**Comment by serge-rider** [comment]
This behavior was changed recently. 
Now each script has its own active database/schema. Active database in navigator tree is just the default  one for new scripts.
Use main toolbar/menu for script active database switch. Or disable option "open separate connection for each editor".

**Comment by terado** [comment]
Ah I see. disabled that now, feels a bit unintuitive to me as it is under the same connection just the properties of the connection have changed - but I doubt most people would be changing properties as often as I do on my scenario. Thanks
