### ISSUE TITLE
Imported table is not opened when CSV import is finished

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7525]
#### System information:

- Operating system (distribution) and version Win 10
- DBeaver version 6.3.2

#### Connection specification:

- Database name and version MySQL

#### Describe the problem you're observing:

Imported table is not opened when CSV import is finished

#### Steps to reproduce, if exist:

1. Create a CSV file to import
2. Create an import task>select CSV format
3. Check that "open table on finish" is checked
4. Run the task

Actial result :<br>

 Imported table is not opened when the import is finished

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D48](https://dbeaver.testquality.com/project/8805/result/1761190/defect/6103). Do not remove or edit.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
