### ISSUE TITLE
Hive: column couldn't be added and delted using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7529]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.2

#### Connection specification:
- Database name and version Hadoop Hive

#### Describe the problem you're observing:
The column couldn't be added to the existing table using UI - the incorrect statement is used.
Generated statemen that doesn't work:
> ALTER TABLE retail_demo.test ADD Column1 VARCHAR(100);

Statement, that works as expected:
> ALTER TABLE `default`.test ADD COLUMNS (Column1 VARCHAR(100));

Also columns couldn't be deleted - drop statement doesn't work in hive https://stackoverflow.com/questions/34198114/alter-hive-table-add-or-drop-column

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D53](https://dbeaver.testquality.com/project/8805/result/1761728/defect/6108). Do not remove or edit.

**Comment by serge-rider** [comment]
We don't support Hive table edit at the moment. Hive uses non-standard SQL dialect.
It should look like this:
```sql
ALTER TABLE name ADD COLUMNS (col_spec[, col_spec ...]);
```
Mark as FR

**Comment by uslss** [comment]
duplicates #9935
