### ISSUE TITLE
Column couldn't be sorted ASC/DESC

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7533]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version  6.3.2

#### Connection specification:
- Database name and version Hadoop Hive

#### Describe the problem you're observing:
Column couldn't be sorted ASC/DESC - error appears
[error.log](https://github.com/dbeaver/dbeaver/files/4023590/error.log)

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D56](https://dbeaver.testquality.com/project/8805/result/1761637/defect/6111). Do not remove or edit.

**Comment by serge-rider** [comment]
Duplicate of #6423
