### ISSUE TITLE
Binary / hex editor uses hardcoded colors

### ISSUE THREAD

**Issue by tobia** [dbeaver/dbeaver#7535]
#### System information: 
- Xubuntu 18.04.3 LTS, amd64
- DBeaver CE 5.2.5 installed from snap edge

#### Describe the problem you're observing:
The binary / hex editor uses hard-coded colors (such as `SWT.COLOR_BLUE` aka. `#0000ff`) which are difficult to see in a dark theme.

Example with Adwaita-dark GTK theme and DBeaver theming turned off:

![Screenshot_2020-01-05_18-04-52](https://user-images.githubusercontent.com/48756/71783531-42ed7d80-2fe8-11ea-8387-4958218fa9df.png)

Example with DBeaver's own dark theme:

![Screenshot_2020-01-05_18-28-08](https://user-images.githubusercontent.com/48756/71783606-59e09f80-2fe9-11ea-8b8b-eb055ca54df5.png)

#### Proposed solution:

The hex editor should borrow its color palette, as well as the font selection, from either the SQL Editor or the Query Result Grid, which are already highly configurable in the Preferences.

The relevant code seems to be in [HexEditControl.java](https://github.com/dbeaver/dbeaver/blob/93f809cef69729aba8da439eee584dab70df84a0/plugins/org.jkiss.dbeaver.ui.editors.hex/src/org/jkiss/dbeaver/ui/editors/binary/HexEditControl.java), for example at lines [438](https://github.com/dbeaver/dbeaver/blob/93f809cef69729aba8da439eee584dab70df84a0/plugins/org.jkiss.dbeaver.ui.editors.hex/src/org/jkiss/dbeaver/ui/editors/binary/HexEditControl.java#L438) and [941](https://github.com/dbeaver/dbeaver/blob/93f809cef69729aba8da439eee584dab70df84a0/plugins/org.jkiss.dbeaver.ui.editors.hex/src/org/jkiss/dbeaver/ui/editors/binary/HexEditControl.java#L941).

**Comment by uslss** [comment]
verified

**Comment by serge-rider** [comment]
Colors in hex editor were broken (for light theme at least), also it broke cell editor dialog (#7669).
Please retest. I think we need to fix both light and dark theme colors (I've fixed main colors but in some cases hex editor is still unreadable).

**Comment by serge-rider** [comment]
Isn't very good looking :(

![image](https://user-images.githubusercontent.com/6398845/72562698-0d387680-38bd-11ea-9b29-3ea0794ad7c8.png)

![image](https://user-images.githubusercontent.com/6398845/72562730-26d9be00-38bd-11ea-8701-70d0c5e1d11d.png)

**Comment by maratkalibek** [comment]
Colors in hex editor changed.

![image](https://user-images.githubusercontent.com/4571314/72634316-85b63a80-3984-11ea-9697-985dd8434ca7.png)

![image](https://user-images.githubusercontent.com/4571314/72634275-6ddeb680-3984-11ea-8683-d044bb41d400.png)

**Comment by kseniiaguzeeva** [comment]
Reproduced with some difference
![Win light](https://user-images.githubusercontent.com/51405061/72667619-de421200-3a2e-11ea-811c-15355884e2c1.png)
![dbeaver_80Yrx3ArGj](https://user-images.githubusercontent.com/51405061/72667620-e0a46c00-3a2e-11ea-9c13-ed2b01f987a0.png)

**Comment by kseniiaguzeeva** [comment]
Verified with some nuances.
