### ISSUE TITLE
DBeaver: Using the IDE to update procedures, functions, triggers etc. broken in version 6.3.1 and 6.3.2 for SQL Server

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#7538]
DBeaver - **Version 6.3.1 and 6.3.2 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Using the **DBeaver** IDE to update procedures, functions, triggers etc. are broken in version **6.3.1** and **6.3.2**.

**o** Create a test database and a test procedure.

```
CREATE DATABASE TestDb;
GO
USE TestDb;
GO

CREATE PROCEDURE dbo.TestProc
AS BEGIN
  SELECT 'TestProc' AS Message;
END;
GO
```

**o** Update the **Database Navigator** tree for the new database, by pressing the **F5** key.

**o** Expand the database tree for **TestDb** -> **Schemas** -> **dbo** -> **Procedures**.

**o**  Double click on the procedure **TestProc** to view its **Source**.

**o** Changed the procedure source code to (add a comment):

```
CREATE PROCEDURE dbo.TestProc
AS BEGIN
  -- Test procedure
  SELECT 'TestProc' AS Message;
END;
GO
```

**o** Choose to persist the change by pressing the **Save** button in the lower right corner in *Dbeaver*.

**o** An error message is shown.

```
SQL Error [208][S0002]: Invalid object name 'TestProc'
Invalid object nam 'TestProc'.
```

The above example worked fine in *DBeaver* version **6.3.0**.

A similair error message are shown when persisting stored functions or triggers.

My guess is something became broken when the change with active connection for different consoles was added to version **6.3.1**. In the above example I guess the "console window" for the test procedure source code points to the **master** database even though the **TestProc** window shows the "breadcrumb" **SQL Server** -> **TestDb** -> **Schemas** -> **dbo** -> **Procedures** -> **TestProc**.

**Comment by serge-rider** [comment]
This may happen if main datasource connection = SQL editor connection (option "use separate connection for each editor" is off) and you run "USE database" query.

DBeaver still thinks that active database wasn't changed and doesn't change it explicitly.
We need to pass active connection in metadata change commands to detect active database properly.

**Comment by serge-rider** [comment]
Fixed.
Please check Early Access version (https://dbeaver.io/files/ea).

**Comment by uslss** [comment]
verified
