### ISSUE TITLE
DBeaver: Opening a console window broken in version 6.3.1 and 6.3.2 for SQL Server in that master database always selected

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#7541]
DBeaver - **Version 6.3.1 and 6.3.2 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Opening a new console window in *Dbeaver* for a **SQL Server** datasource, always connect to the **master** database. No consideration is made what database is active.

This worked ok in *DBeaver* version **6.3.0**.

**o** Create a test database.

```
CREATE DATABASE TestDb;
GO
USE TestDb;
GO
```

**o** Update the *DBeaver* **Database Navigator** (by pressing the **F5** key).

**o** Right click on the **TestDb** database and choose **Set Active**.

**o** Choose to open a **SQL Editor** by pressing the **F3** key and choose **New Script**.

**o** The new SQL Editor is connected to the **dbo@master** database. This is an **ERROR**.

In *DBeaver* version **6.3.0** it correctly conntected to the active database (ie. the **TestDb** database).

**PS**. If trying out the above using a *postgreSQL* database it workes as expected.

**Comment by serge-rider** [comment]
It is not an error. Since 6.3.1 each SQL editor has its own active database/schema. So you may have multiple open scripts and each of them may have different active database.

Changing active database in the editor doesn't change global default database and visa versa.

Changing active database in the navigator view affects changes default database for new editors only. 

You can disable this behavior by turning off "Use separate connection for each editor" option in SQL Editor preferences.

**Comment by serge-rider** [comment]
Note: use main toolbar to change active database in current SQL editor.

**Comment by pdanie** [comment]
**1**. I can buy that you can have multiple different connections for different consoles.

**2**. But it is really illogical that be connected to **master** database for a new SQL Editor. It ought to use the active connections as start up connection / default. After it is created it is ok that the conections may change in different editors.

Don't you think so too ?

**Comment by serge-rider** [comment]
New SQL editor uses "global" default database (the one specified in connection settings or the one which was explicitly set active in navigator).

This seems to be logical for me. But I'm open for any other suggestions :)

**Comment by pdanie** [comment]
I just compare the behaviour in *Microsoft Server Management Studio* which is even better in that you don't even have to activate the database. There the database that is selected in its **Object Explorer** are choosen as the startup database in the new **Query Window**.

**Comment by serge-rider** [comment]
dbeaver never worked like that. 
You could make a feature request (get new editor default database for from current database navigator node).

dbeaver can determine active database change (by USE X). Enable option "Refresh active schema after SQL execution" option in SQL Processing preferences.

**Comment by pdanie** [comment]
Can't I have the same behaviour that *DBeaver* datasource for **postgreSQL** then ? This is what I want.

**Comment by serge-rider** [comment]
It is the same for all databases.

**Comment by pdanie** [comment]
Try it with a *postgreSQL* database:

**o** Connect to a **postgreSQL** database server/datasource that contain multiple databases.
**o** Set one of the databases (other than the **postgres** database).
**o** Choose to open a **New Script** / SQL Editor window.
**o** The database is set to the active database. This even if I have set the default database for my datasource to the **postgres** database.

**Comment by serge-rider** [comment]
Well, it works as expected in my env. 
DBeaver uses active database (the one which is bold in the navigator) for new SQL editor. For both PostgreSQL and SQL Server. And for any other database too.

**Comment by pdanie** [comment]
In my environment (Windows 7) it does not.

I attached two MP4 films (packed as <zip-archive files). One for MSSQL and one for POSTGRESQL.

[DBeaver_MSSQL_7541.zip](https://github.com/dbeaver/dbeaver/files/4026753/DBeaver_MSSQL_7541.zip)

[DBeaver_PSQL_7541.zip](https://github.com/dbeaver/dbeaver/files/4026751/DBeaver_PSQL_7541.zip)

**Comment by serge-rider** [comment]
This is probably a bug, I'll check it on SQL Server a bit later.

**Comment by serge-rider** [comment]
I think we'll remove "Set Active Object" context menu in the next version. It confuses users (they try to use old feature which is no longer exists).
So active schema can be switched only thru main toolbar/main menu or in connection bootstrap settings.

**Comment by pdanie** [comment]
If you go for removing **Set Active Object** context menu, you really must implement that when opening a **SQL Editor** window it connects to the choosen (the one selected) database selected in the *Database Navigator*.

I hope you agree with this.

**Comment by uslss** [comment]
verified.
@pdanie according to your last comment mentioned feature will be implemented in scope of #7599
