### ISSUE TITLE
DBeaver FR: Update indication of active database in SQL Editor when using USE sql command for SQL Server

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#7544]
DBeaver - **6.3.2 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

It would be really great if the indication of active database at the top of the **SQL Editor** changed after running the *SQL Server* sql **USE** command.

Today the *DBeaver* **SQL Assistant/Completion** shift after the use of the **USE** command, but the indication at top of the **SQL Editor** does not get updated.

**PS**. I have the global setting **Editors** -> **SQL Editor** -> **SQL Processing** -> **Refresh
active schema after SQL execution** set to **checked** (which seems to be the *DBeaver* default).

**Comment by uslss** [comment]
verified
