### ISSUE TITLE
DBeaver: Use of OPEN DECLARATION in SQL EDITOR is broken in version 6.3.1 and 6.3.2 for SQL Server

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#7545]
DBeaver - **Version 6.3.1 and 6.3.2 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Use of **Open Declaration** in a **SQL Editor** is broken in version 6.3.1 and 6.3.2 for SQL Server.

Previous I could write SQL script in SQL Editor and put the cursor on a table name and use **Open Declaration** to view the table data in a new data grid window. But now nothing happens.

**This works for postgreSQL**

**o** Open a datasource to a **PostgreSQL** database.

**o** Open a **SQL Editor** and runt the SQL command below:

&nbsp;&nbsp;&nbsp;&nbsp;`CREATE DATABASE testdb;`

**o** Update the **Database Navigator** and set the new database as **active**. Make sure the **SQL Editor** is connected to the new database!

**o** Create a table with the SQL command below:

&nbsp;&nbsp;&nbsp;&nbsp;`CREATE TABLE testtable(id INTEGER, message VARCHAR(255));`

**o** After the database and table is created, write the SQL command below in the SQL window (don't execute/run it):

&nbsp;&nbsp;&nbsp;&nbsp;`SELECT * FROM testtable;`

**o** Place the cursor in the **testtable** name/text, and right click and choose **Open Declaration**.

**o** A new tab/window is opened up showing the content for the table.

**o** This is **OK** and a really great *DBeaver* functionality.

**This does not work anymore for SQL Server**

**o** Open a datasource to a **SQL Server** database.

**o** Open a **SQL Editor** and runt the SQL command below:

&nbsp;&nbsp;&nbsp;&nbsp;`CREATE DATABASE TestDb;`
&nbsp;&nbsp;&nbsp;&nbsp;`GO`

**o** Update the **Database Navigator** and set the new database as **active**. Make sure the **SQL Editor** is connected to the new database!

**o** Create a table with the SQL command below:

&nbsp;&nbsp;&nbsp;&nbsp;`CREATE TABLE TestTable(Id INTEGER, Message VARCHAR(255));`
&nbsp;&nbsp;&nbsp;&nbsp;`GO`

**o** After the database and table is created, write the SQL command below in the SQL window (don't execute/run it):

&nbsp;&nbsp;&nbsp;&nbsp;`SELECT * FROM TestTable;`

**o** Place the cursor in the **TestTable** name/text, and right click and choose **Open Declaration**.

**o** Noting happens any more.

**o** This is an **ERROR**.

**Summary**

**o** This worked in *DBeaver* version **6.3.0**.
**o** This works in *DBeaver* version **6.3.2** for at least **postgreSQL**, **SQLite** and **MariaDB** datasources.

**Comment by serge-rider** [comment]
I think this was already fixed in #7537

**Comment by uslss** [comment]
verified
