### ISSUE TITLE
Snap package doesn't have native client

### ISSUE THREAD

**Issue by thiras** [dbeaver/dbeaver#7548]
#### System information: 
- Operating system (distribution) and version: **Ubuntu 18.04** (up-to-date)
- DBeaver version: **Version 6.3.2.202001051908**
- **Snap installation**

#### Connection specification:
- Database name and version: **MySQL 5.6.10**
- Driver name: **MySQL Connector Java mysql-connector-java-5.1.44 ( Revision: b3cda4f864902ffdde495b9df93937c3e20009be )**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **No**

#### Describe the problem you're observing:
For dumping a database, the application needs a native MySQL client. But the snap package doesn't contain that. As intended, non-classic snap packages cannot execute something on the system. So the snap package should contain native clients too.

#### Steps to reproduce, if exist:
Try to dump something with the snap package.

**Comment by alexandrtovmach** [comment]
The same issue works for postgresql, any possible fix?

**Comment by Shaltz** [comment]
DBeaver 7.3.4 via snap still has this issue for mysql... any update ??
