### ISSUE TITLE
URL Configuration Broken for Snowflake

### ISSUE THREAD

**Issue by wallygator470** [dbeaver/dbeaver#7549]
I downloaded the new version of DBeaver and now when I open up a connection to snowflake it requires me to declare the Schema every time a new sql window is opened.  I noticed that the URL that is created does not have ampersand delimiters around the different parameters.
it looks like this:
/?db=MY_DATABASEwarehouse=MY_WAREHOUSEschema=MY_SCHEMArole=MY_ROLE

and it should be like:
/?db=MY_DATABASE&warehouse=MY_WAREHOUSE&schema=MY_SCHEMA&role=MY_ROLE

This used to work and now with the new update it no longer does.  This makes it slightly less convenient.

**Comment by wallygator470** [comment]
I should say that each connection I use I declare the DB, warehouse and schema in the connection information.

**Comment by serge-rider** [comment]
Did this happen with some old connection only? What if you create a new Snowflake connection?
