### ISSUE TITLE
Reference variable value problems

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#7550]
![图片](https://user-images.githubusercontent.com/26621087/71865719-a8ec1900-313e-11ea-9896-5a76ff880a69.png)

Can I quote directly? You do not need to enter variables manually
#### System information: 
- Operating system (distribution) and version  WIN 10 64
- DBeaver version 6.32
- Additional extensions

#### Connection specification:
- Database name and version  HIVE
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on issue. if it is still actual for you - feel free to reopen the issue
