### ISSUE TITLE
Volatile Preferences/General/Network Connections 

### ISSUE THREAD

**Issue by pijoter** [dbeaver/dbeaver#7551]
#### System information: 
- Operating system (distribution) and version
Windows 10, version 1809
- DBeaver version
DBeaver 6.3.2
- Additional extensions
none

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Proxy servers defined in Preferences/General/Network Connections  are lost during DBeaver upgrade. Meanwhile, proxy defined in Preferences/DBeaver/Drivers persists.

#### Steps to reproduce, if exist:
define proxy (Preferences/General/Network Connections) then upgrade

**Comment by uslss** [comment]
#8519

**Comment by uslss** [comment]
closed as duplicate.
thanks for the bug report
