### ISSUE TITLE
phoenix can't create indexes

### ISSUE THREAD

**Issue by qq459673705** [dbeaver/dbeaver#7554]
#### System information: 
- ubuntu 18.04
- DBeaver 6.3.1

#### Connection specification:
- Hbase 1.4.11
- Hadoop 2.8.5
- driver 4.14.3-HBase-1.4
- Do you use tunnels or proxies (not)? 

#### Describe the problem you're observing:
I create a new table, this is success. but when i create a index for this table, this report a error modal.
Error creating new object.
and the detial info is null.
![2020-01-07 17-51-01 的屏幕截图](https://user-images.githubusercontent.com/6657548/71885971-59c1da80-3176-11ea-9b8d-7883da4d1b56.png)

**Comment by qq459673705** [comment]
i know why,  because i create this table in the "SYSTEM" namespace, i am sorry.
but other bug is show, i can't directly create a table whith another namespace, and when i create another namespace table in sqlline shell, the tables in "SYSTEM" namespace connot visit now.

**Comment by serge-rider** [comment]
Fixed in #7512

**Comment by uslss** [comment]
verified
