### ISSUE TITLE
Turkish charaters are garbled (Your solutions not worked)

### ISSUE THREAD

**Issue by HakanDOGAN1981** [dbeaver/dbeaver#7555]
Turkish charaters are garbled. 
I said before and i used your solutions but not worked.
please fix that

Here is the screenshot abouth problem.
Left Up (RedExpert)-Right Up (Database Workbench 5)

https://drive.google.com/file/d/1Kwt0TiwDSl0YCG4oWh850193MXVtSPef/view?usp=sharing

System information: Windows 10 v6.3.2.202001051908
Connection specification:Firebird v3.04

**Comment by serge-rider** [comment]
I'm no sure what exactly solution do you mean.
Anyhow - did you try to set another connection encoding (it is UTF-8 by default)?

Here is a list of supported encodings: http://www.destructor.de/firebird/charsets.htm

![image](https://user-images.githubusercontent.com/6398845/72104149-d2be5f00-333b-11ea-93cd-44e5715ed2a5.png)

**Comment by HakanDOGAN1981** [comment]
Hi,

Finally i fixed.

i changed encoding to "WIN1254" and it worked.

Thankyou.
