### ISSUE TITLE
Copying tables slowed by cache refresh

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#7556]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.3.1
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle 12c/18c
- Driver name: JDBC Thin Client
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

I sometimes need to copy quite a lot of tables between databases (using Export feature) and noticed that schema cache seems to be refreshed every time table is created. This slows down whole process significantly, because it looks like DBeaver spends most of the time constantly refreshing cache instead of actually copying data. This is especially visible when target schema is large and cache refreshing take a few seconds to complete.

There is also second issue: if number of records is relatively small there is no way to stop export process, because button that cancels operation in inactive, because it refers to cacheing operation rather than exporting.

**Comment by serge-rider** [comment]
Mostly it will be covered in #7745

**Comment by LonwoLonwo** [comment]
@maln0ir the export process has been partially changed. perhaps the problem with long export is now missing. I can not reproduce. you can check if the problem is in newer versions https://dbeaver.io/download/

**Comment by uslss** [comment]
Issue closed - no updates for a long time.
If it is still actual - feel free to reopen the ticket
