### ISSUE TITLE
Restoring database runs mysql in verbose mode

### ISSUE THREAD

**Issue by brtastic** [dbeaver/dbeaver#7557]
#### System information: 
- OpenSUSE Leap 15.1
- DBeaver 6.3.2

#### Connection specification:
- MySQL 8+
- mariadb-client package as native client

#### Describe the problem you're observing:
Importing a database seems to always force a -v (verbose) flag on mysql native client, regardless on verbosity settings, which forces it to print all the queries made to the stdout, which then are viewed in dbeaver. This slows down the entire operation immensely to a point of being completely useless. Dbeaver 6.2.5 (and probably some later ones) doesn't have this issue.
Adding --silent doesn't help. Adding any non-existent flag causes the operation to end in error, which allows you to see the flags with which the mysql is ran.

#### Steps to reproduce, if exist:
Import any file via tools -> restore database. All the queries are printed out.

**Comment by zedee** [comment]
I can confirm it happens to me as well:

**Sys info:**
- Ubuntu 19.10 Eoan
- DBeaver 6.3.2

**Connection specification:**
- MySQL 8.0.18 (dockered in dev machine)
- com.mysql.jdbc.Driver

I attach a screenshot too, as a lot of garbled output is seen on the window. The process, as @brtastic explains, is quite slow.

![dbeaver_6_3_2_garbled_output_text_20200108_154554](https://user-images.githubusercontent.com/5777239/71987632-de702f80-322e-11ea-96bb-8f73d240f7a2.png)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
