### ISSUE TITLE
Feature request : Import & Export of connection 

### ISSUE THREAD

**Issue by slavus** [dbeaver/dbeaver#7558]
It would be nice if Dbeaver would have Import & Export of connection to a file.
Than this file could be shared to team members. 

This feature is very useful when you have complicated conection propreties.

**Comment by serge-rider** [comment]
This is already supported. Main menu File->Export->DBeaver->Project

Also you can just copy file data-sources.json from dbeaver project: https://github.com/dbeaver/dbeaver/wiki/Admin-Manage-Connections
