### ISSUE TITLE
Open new editor and default schema of connection is not taken

### ISSUE THREAD

**Issue by LukasBreit** [dbeaver/dbeaver#7559]
#### System information: 
- IBM I series 7.2
- DBeaver version 6.3.2

#### Connection specification:
- DB2

#### Describe the problem you're observing:
The connection is set up with a defaultschem in the tab "Initialisation", but when opening a new sql editor of the connection the defined schema is not set. Maybe another setting is just missing to solve the problem, but in a previous version the schema was taken correclty with same settings.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by kseniiaguzeeva** [comment]
Verified
