### ISSUE TITLE
DBeaver should allow PK, FK and INDEX renaming for PostgreSQL

### ISSUE THREAD

**Issue by iulg** [dbeaver/dbeaver#7563]
DBeaver (at least version  6.3.2.202001051908) does not permit renaming of index, foreign keys and primary keys on PostgreSQL although PostgreSQL permits this.

DBeaver should add an menu item on the right click menu item that would open a simple dialog with an edit box with the current name of index/fk/pk and the user should change the name and DBeaver should issue on the DB the corresponding SQL (for example: ALTER TABLE table_name RENAME CONSTRAINT "old_constraint_name" TO "new_constraint_name").

**Comment by kseniiaguzeeva** [comment]
Similar ticket for MariaDB https://github.com/dbeaver/dbeaver/issues/3293

**Comment by LonwoLonwo** [comment]
Implemented in DBeaver 21.0.5
Will be available [here](https://dbeaver.io/) at 2021-05-17

**Comment by uslss** [comment]
verified
