### ISSUE TITLE
SSH tunnel does not allow a passphrase any more

### ISSUE THREAD

**Issue by emerika** [dbeaver/dbeaver#7564]
#### System information: 
- Operating system (distribution) Ubuntu 18.04
- DBeaver 6.3.2
- Java version openjdk 13 2019-09-17
- Additional extensions

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
 trying to

#### Describe the problem you're observing:
When creating a new connection -- the tunnel section does not have a place to enter a passphrase. Existing connections with passphrases show the place to enter one -- it's only a problem when you are creating a new connection.
![Screenshot from 2020-01-07 14-45-42](https://user-images.githubusercontent.com/838851/71932379-fd9e8c80-315c-11ea-8eb5-5477d19f054c.png)

This shows an existing connection -- notice the difference?
![Screenshot from 2020-01-07 14-50-48](https://user-images.githubusercontent.com/838851/71932499-3179b200-315d-11ea-8aa7-f7832878a15a.png)

**Comment by serge-rider** [comment]
It is a bug in dialog components layout. Thanks for the bug report.

Workaround: try to resize dialog window after auth method change.

**Comment by uslss** [comment]
verified
