### ISSUE TITLE
BUG?

### ISSUE THREAD

**Issue by jyoisamu** [dbeaver/dbeaver#7565]
There is also a phenomenon that records that have already been updated are displayed as past data.

**Comment by mkgrgis** [comment]
In Postgres and SQLite this is element of DB logic. DBeaver is transparent for cortage (row) order.

**Comment by jyoisamu** [comment]
Thank you for your comment.
I use  the DBeaver for Mysql, so  it is  Inconvenient.

Can be improved with  the refresh setting ?
![image](https://user-images.githubusercontent.com/59637821/72305343-cd07a700-36b6-11ea-8b36-11c66904c541.png)

**Comment by mkgrgis** [comment]
You can create an view "SELECT * FROM ... " with ORDER block you need and edit the view.

**Comment by dail8859** [comment]
I have also been running into this issue lately and has caused me alot of headache! Hitting the refresh button, or having it auto refresh every second **does not work**. I have to "Invalidate/Reconnect" in order for the data to refresh.

I can even close the "Edit Table" window, open it back up, redo my filter, and it still shows the old data. I am using MySQL v8.0.18

**Comment by jyoisamu** [comment]
> I have also been running into this issue lately and has caused me alot of headache! Hitting the refresh button, or having it auto refresh every second **does not work**. I have to "Invalidate/Reconnect" in order for the data to refresh.
> 
> I can even close the "Edit Table" window, open it back up, redo my filter, and it still shows the old data. I am using MySQL v8.0.18

As you said. I'm in big trouble. 
I have evacuated this problem in exactly the same way, but it's cumbersome.
Not good for updating data and examining tables.
