### ISSUE TITLE
The result set is limited to 200 rows, and if you pull down, you get an error

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#7567]
The result set is limited to 200 rows, and if you pull down, you get an error
![图片](https://user-images.githubusercontent.com/26621087/71969475-ade5c100-3241-11ea-863e-74283b2faa0e.png)

#### System information: 
- Operating system (distribution) and version WIN10 64
- DBeaver version 6.32
- Additional extensions

#### Connection specification:
- Database name and version hive
- Driver name  impala
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by serge-rider** [comment]
Please attach full debug/error log. It is not clear what is this issue about.

**Comment by uslss** [comment]
there is no update on issue more than a month.
Ticket closed.
If issue still reproducible for you - feel free to reopen the ticket
