### ISSUE TITLE
Output window does not update during run, only afterwards

### ISSUE THREAD

**Issue by martijn1247812** [dbeaver/dbeaver#7568]
No updates during run in Output window. Only when run finished
Running functions with RAISE INFO. This info is not being shown in the Output window. With version 6.3.0 no problems.

#### System information: 
- Windows 10
- DBeaver version: 6.3.2
- Additional extensions: none

#### Connection specification:
- Postgres EDB 9.6
- Driver name: default
-

#### Describe the problem you're observing:
No updates during run in Output window. Only when run finished

**Comment by serge-rider** [comment]
Thanks for the bug report
Fixed

**Comment by uslss** [comment]
verified

**Comment by martijn1247812** [comment]
Version 6.3.4.202002011957
Still has the problem
