### ISSUE TITLE
DB2 Timestamp Causes Query to Fail

### ISSUE THREAD

**Issue by Zeshue** [dbeaver/dbeaver#7570]
#### System information: 
Windows 10 Enterprise Version 1809
DBeaver 6.3.2

#### Connection specification:
DB2 for z/OS

#### Describe the problem you're observing:
When trying to query a timestamp column in the format of yyyy-MM-dd HH:mm:ss.ffffff (the standard format for our databases) from DB2 table (including table data preview) I get an error "SQL Error: Internal jdbc driver error". Excluding these columns from the query returns the expected results.

#### Steps to reproduce, if exist:
Execute query against DB2 table and include timestamp formatted column.

#### Include any warning/errors/backtraces from the logs
Error: SQL Error: Internal jdbc driver error
Session Data:
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

[Error Log.txt](https://github.com/dbeaver/dbeaver/files/4035517/Error.Log.txt)

**Comment by serge-rider** [comment]
As far as I see the error happens during column value decoding:
`java.nio.charset.UnsupportedCharsetException: Cp1027`
This is  known issue with DB2 z/OS driver. It has nothing to do with dbeaver (I think). Perhaps some additional driver config is needed.

https://www.ibm.com/support/pages/javaniocharsetunsupportedcharsetexception-thrown-if-rtjar-not-included-classpath

https://stackoverflow.com/questions/36354899/unsupportedcharsetexception-cp1027-with-db2-jdbc-driver

**Comment by Zeshue** [comment]
Yes, it appears that you are correct about it not being a DBeaver issue. After some more digging it appears that there's a specific version of JRE that must be used to be fully compatible with my company's DB2 servers.
