### ISSUE TITLE
Smart auto-commit for "Main session"

### ISSUE THREAD

**Issue by haugs** [dbeaver/dbeaver#7571]
As I mentioned there the introduction of the smart auto-commit https://github.com/dbeaver/dbeaver/issues/1562 left out the "Main session" of DBeaver and only affects sessions of the SQL scripts/editors.

> It works fine for sessions associated with a SQL Editor. But when I double-click a table in the "Database Navigator", the new tab does not have the "Smart auto-commit" option in its GUI at all. The feature should be available for the "Main session" too.

Affects DBeaver 6.3.2
Steps to reproduce:
- Double click on any table in the "Database Navigator". A new tab will appear showing the properties or data of that table.
- Open the menu Database > Transaction mode. There are only the two options "Auto-Commit" and "Manual Commit" available. The "Smart auto-commit" option is missing.

Suggestions for the resolution:
The "Main session" probably derives its transaction mode from the settings of the database connection. Therefore I assume that it is necessary to add the "Smart auto-commit" property to the properties of the database connection? (Right click on a connection > Edit connection > Connection settings > Initialization > Next to Auto-Commit ?).

**Comment by serge-rider** [comment]
Done. Now smart commit option is available for table editors as well.
Also new preference page "Transactions" was added. It contains settings for smart commit and transaction notifications.

![image](https://user-images.githubusercontent.com/6398845/73119816-51401100-3f78-11ea-98a5-7e7fd53333e5.png)

**Comment by kseniiaguzeeva** [comment]
verified
