### ISSUE TITLE
GitHub private respositories access

### ISSUE THREAD

**Issue by guillermodangelo** [dbeaver/dbeaver#7572]
AFAIK DBeaver can't access private GitHub repositories, it would be great if it was possible to access them, just like the public repos.

**Comment by serge-rider** [comment]
What do you mean "DBeaver can't access"? 

Is it about Git integration module? 
Generally any problems with Git itself should be addressed to EGit authors (https://www.eclipse.org/egit/)
BTW I can work with public/private/non-github repositories without any issues.

**Comment by guillermodangelo** [comment]
Ok, I'll close this issue. Thank you!.
