### ISSUE TITLE
Reset Smart auto-commit after end of transaction

### ISSUE THREAD

**Issue by haugs** [dbeaver/dbeaver#7573]
The feature "Smart auto-commit" introduced with https://github.com/dbeaver/dbeaver/issues/1562 is currently only applied automatically for the first use of a connection.

When you use the "Auto-Commit plus Smart auto-commit" setting it switches into "Manual Commit" mode once you use an UPDATE statement (or equivalent). To re-enable the "Smart auto-commit" functionality after that you need to manually set the transaction mode back to "Auto-commit".

It would be great that this happens automagically when you hit ROLLBACK (or COMMIT) as now there are no more executed modifying statements.

"Affects" DBeaver 6.3.2

Two additional suggestions:
1. The name "Smart auto-commit" is somewhat misleading. Since what it actually does is NOT auto-commit anything. I suggest to rename it to "Smart Manual Commit" :) because it behaves like "Manual Commit" but with the addition of avoiding an open transaction as long as there is nothing of substance to commit.

2. [The documentation](https://github.com/dbeaver/dbeaver/wiki/Auto-and-Manual-Commit-Modes) should be updated to include this great new feature.

**Comment by serge-rider** [comment]
Done.
Now we have the following options:
![image](https://user-images.githubusercontent.com/6398845/73120098-ffe55100-3f7a-11ea-8cec-d20794141269.png)

Additionally you can disable commit/rollback notifications in task bar.
Documentation was updated.

**Comment by uslss** [comment]
verified
