### ISSUE TITLE
Can't insert tab anymore in editor

### ISSUE THREAD

**Issue by mosesontheweb** [dbeaver/dbeaver#7574]
Hi,

I'm using DBeaver 6.3.2 CE as my most favorite SQL database manager and editor. For some reason I can't use tabs anymore for indenting my code. I already tried to enable/disalbe "Insert spaces for tabs" or change the indent size, no effect at all. Whenever I press TAB nothing happens in the editor.

The only way to have parts of the SQL code indented is by using "Format SQL".

Any hints why? Connection used is to a PostgreSQL DB.

Regards, Thomas

**Comment by kseniiaguzeeva** [comment]
Unfortunately, can't reproduce it. Does it affect on any SQL expression? What is your OS?

**Comment by mosesontheweb** [comment]
It does not effect the expression itself, however, I cannot format the statement with indents myself. OS is MacOS High Sierra, Java is OpenJDK12, Dbeaver is 6.3.2 (latest).

Regards, Thomas

**Comment by uslss** [comment]
hi @mosesontheweb ,
probably you could try to reset UI settings (https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings)

**Comment by uslss** [comment]
there is no update on issue more than a month.
Ticket closed.
If issue still reproducible for you - feel free to reopen the ticket
