### ISSUE TITLE
Colorize  is missing in dbeaver  6.3.2.202001051908

### ISSUE THREAD

**Issue by chr1xm** [dbeaver/dbeaver#7577]
#### System information: 
- Windows 10 64
-6.3.2.202001051908
- Java version 
- Additional extensions

#### Connection specification:
- Postgresql
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I tried to use Coloring by Data Types but in this version 6.3.2.202001051908 that option seems to be not display 
#### Steps to reproduce, if exist:
Run a query and click on the results the context menu and look for View / Format 
View Format option is missing.
![imagen](https://user-images.githubusercontent.com/17755187/72021485-ba631d00-3233-11ea-8b95-67156e7145a7.png)

**Comment by serge-rider** [comment]
Agreed, we should return view/format sub-menu in the main context menu.

Workaround: you can find this menu in the bottom toolbar, dropdown after the cog icon.

**Comment by kseniiaguzeeva** [comment]
Verified.
