### ISSUE TITLE
Missing "Format SQL" keyboard shortcut

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [dbeaver/dbeaver#7578]
1. as of `dbeaver` v 6.3.2 there is no shortcut assigned to:
* `Format` -> `Format SQL`

2. most editors follow Eclipse keyboard shortcut convention of:
* `Format` -> `Ctrl+Shift+F`

**Comment by kseniiaguzeeva** [comment]
Unfortunately cannot reproduce it. What OS and database do you use?
Please also check shortcut settings in Preferences>General>Keys
![JOgdvtTUk7](https://user-images.githubusercontent.com/51405061/72048775-97d21200-32ce-11ea-8469-d81033c64b54.png)
![CCQQ89qFdZ](https://user-images.githubusercontent.com/51405061/72048780-9a346c00-32ce-11ea-8a51-42dccfa16a93.gif)
