### ISSUE TITLE
The window is closed and the daemon is still executing

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#7582]
![图片](https://user-images.githubusercontent.com/26621087/72045550-54d56600-32f1-11ea-9960-413a48d35a47.png)

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version HIVE
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by mkgrgis** [comment]
This is not bug without context. If there will context, it can be a bug.
