### ISSUE TITLE
View/Format in ResultSet: "column formats" and "row colors" do not work properly

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7584]
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.2

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
View/Format in ResultSet:
1. When you change a data format using "column formats", it is applied after sql expression reexecution.
Steps:
a. Open "View/Format">"column formats.." in context menu of ResultSet
b. select a column in the opened window > set a new format for it>press "Ok".
Expected result: The changes are applied according settings.
Actual result: The changes are applied after sql expression reexecution.

2. "row colors.." function does not work
Steps:
a. Open "View/Format">"row colors.." in context menu of ResultSet
b. select a column in the opened window > set colors>press "Ok".
Expected result: The changes are applied according settings.
Actual result: No visible changes in ResultSet

Pls see gif for "row colors.." function
![nmgjV7JWHM](https://user-images.githubusercontent.com/51405061/72046955-81c25280-32ca-11ea-8dd6-6fee191633cc.gif)

**Comment by serge-rider** [comment]
Can't reproduce p1.
p2 fixed.

@kseniiaguzeeva Please test entity coloring in MySQL, PostgreSQL, SQLite and Oracle.

**Comment by kseniiaguzeeva** [comment]
p1 - have you tried exactly way : ""View/Format">"column formats.." in context menu of ResultSet"?
Because way ""View/Format">"set "column_name" format" in context menu of ResultSet" works properly.

![02Ao14gSCt](https://user-images.githubusercontent.com/51405061/72104577-cd154900-333c-11ea-9fa1-5cba89f94f75.gif)

**Comment by kseniiaguzeeva** [comment]
p2
I see 2 mistakes:
1. a color cannot be set (from time to time). In order to apply a color, it is nesessary to set a color for the table in Object editor at first. Then the color can be changed through "row colors.." in ResultSet too.
2. a color is set, but the field "colors" of   "row colors.." in ResultSet is empty after DBeaver relaunching.

**Comment by serge-rider** [comment]
Column config save was fixed

**Comment by kseniiaguzeeva** [comment]
Verified
