### ISSUE TITLE
Configuration: Connection Types permission entries will not be saved

### ISSUE THREAD

**Issue by RiedelTh** [dbeaver/dbeaver#7585]
#### System information: 
- Operating system (distribution) and version: **Windows 10 Version 1809**
- DBeaver version: **6.3.2 (Community Edition)**
- Additional extensions: **No**

#### Connection specification:
- Database name and version: **not important**
- Driver name: **not important**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **No**

#### Describe the problem you're observing:
- Preferences -> DBeaver -> Connection Types -> Edit permissions ...
Entries will not be saved.

#### Steps to reproduce, if exist:
- Take a fresh install of DBeaver
- Start DBeaver
- Menu: Window -> Preferences -> DBeaver -> Connection Types
- Mark entry Development
- Click Edit permissions ...
- Check any 2 entries
- Click OK
- Click Apply and Close
- Exit DBeaver
- Start DBeaver
- Take a look at the Connection Types Entry Development -> Edit permissions ...
- File **data-sources.json** at **%appdata%\DBeaverData\workspace6\General\.dbeaver** did not receive the configuration change

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.
Workaround: edit permissions using: Edit connection> General> Edit connection types> Edit permissions in Database context menu of DB Navigator.
![dbeaver_yNOJZEcTnc](https://user-images.githubusercontent.com/51405061/72057202-0fa83880-32df-11ea-9a5b-f8352579f5f6.png)

**Comment by RiedelTh** [comment]
> Workaround: edit permissions using: Edit connection> General> Edit connection types> Edit permissions in Database context menu of DB Navigator.
> ![dbeaver_yNOJZEcTnc](https://user-images.githubusercontent.com/51405061/72057202-0fa83880-32df-11ea-9a5b-f8352579f5f6.png)

Your workaround does work under Windows 10 Version 1809 - thank you.
I am using DBeaver also under **Windows Server 2012 R2, where this workaround doesn't work** - can someone please confirm this?

**Comment by kseniiaguzeeva** [comment]
In any case your ticket (Window -> Preferences -> DBeaver -> Connection Types) is a bug and should be fixed.

**Comment by serge-rider** [comment]
Fixed.
Note: we copy connection type configuration in project settings. Changing connectio ntype in global preferences will update connection-types.xml as well as data-sources.json in all projects which rely on changed connection types.

**Comment by kseniiaguzeeva** [comment]
Verified, if way  "Window -> Preferences -> DBeaver -> Connection Types" is used to enable permissions.
