### ISSUE TITLE
Restore problem postgres

### ISSUE THREAD

**Issue by andrejCepl** [dbeaver/dbeaver#7586]
When create new database and try to restore from file program restores latest restored database, not selected.

**Comment by serge-rider** [comment]
What is "latest restored database"?

**Comment by andrejCepl** [comment]
That was restored ok(can't find logic). Try to create  aa database and restore it from file. After that create bb  and try to restore it. Second restore will be to aa.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
