### ISSUE TITLE
[Firebird] created unique index is not displayed in Properties of Object Editor

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7587]
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version: Firebird 

#### Describe the problem you're observing:
Create a Unique index using Object Editor> Press "Save" btn.

Actual result:
The created index dissapears after saving.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
