### ISSUE TITLE
[Postgres] Open Declaration from editor shows error "Can't find metadata object for name 'schema.table'"

### ISSUE THREAD

**Issue by LorisZ** [dbeaver/dbeaver#7588]
#### System information: 
- Kubuntu 18.04
- DBeaver 6.3.2

#### Connection specification:
- Database: PostgreSQL 9.6.12
- Driver: PostgreSQL

#### Describe the problem you're observing:

When writing a query in the editor and i move the cursor to the identifier inside the from part, i could by pressing F4 (or right clicking and choosing `Open Declaration`) go to the declaration of the table. This does not seem to work anymore since 6.3.2.

#### Steps to reproduce, if exist:

write a simple select query, for example: 

```sql
select *
from information_schema.tables
```
move cursor inside `tables` and click F4 or use context menu like specified above.

##### Note: Opening the declaration from the Database Navigator tree still works.

**Comment by uslss** [comment]
issue seems to be fixed in scope of #7545 and fix will be included in 6.3.3.
anyway, thanks for the bug report :)

**Comment by serge-rider** [comment]
Thanks for the bug report.
Fixed

**Comment by uslss** [comment]
verified

**Comment by jmriego** [comment]
same issue here. if it's any help, the current workaround for that is to add the database name.

`schema.table` doesn't work for opening the declaration
`database.schema.table` works
