### ISSUE TITLE
Oracle Connection not respecting Role with JDBC string

### ISSUE THREAD

**Issue by wdahlenburg** [dbeaver/dbeaver#7589]
#### System information: 
- Kali Linux Rolling
- DBeaver version 6.3.1

#### Connection specification:
- Oracle
- Oracle JDBC Driver 11.2.0.3.0

#### Describe the problem you're observing:
DBeaver provides a Custom section when setting up Oracle database connections. A JDBC URL can be entered.

A JDBC URL can include the username and password to the database. Directly below the GUI to enter in the JDBC URL is a Security section where the user can add the username and password. The role can also set to Normal, SYSDBA, and SYSOPER. 

As a user I would expect the username and password from the JDBC URL to be respected when choosing a Role. The current behavior is to disregard whatever the Role dropdown is set to when the username and password are not set in the Security section. When using a JDBC URL with the credentials it's unintuitive that the Role will be passed as Normal unless you additionally fill out the credentials in the Security portion.

#### Steps to reproduce, if exist:
1. Gather a JDBC string with username and password in it
2. Setup a new Oracle connection within DBeaver
3. Paste the JDBC under Custom -> JDBC URL
4. Select Role as SYSDBA or SYSOPER
5. Click Test Connection or OK
6. Observe that the GUI settings appear to be set for a SYSDBA or SYSOPER user, although you get connected with a Normal role.

#### Include any warning/errors/backtraces from the logs

N/A

**Comment by mkgrgis** [comment]
It seems, there is the same bug with Firebird. The FB JDBC have connection roles.

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on issue.
if it is still actual for you - feel free to reopen it
