### ISSUE TITLE
Check for Updates reports "There is no new version of DBeaver." when new version was ignored

### ISSUE THREAD

**Issue by Chealer** [dbeaver/dbeaver#7590]
I very much appreciate DBeaver's discreet update checker, which allows to dismiss new versions. Today, I was offered upgrading to 6.3.2, but chose not to, asking not to be asked again for 6.3.2. Unfortunately, it seems that feature is breaking intentional requests to update. After dismissing a version, if I use Help -> Check for Updates, the Version update dialog shows:
> There is no new version of DBeaver.
> Current version: 6.2.5.201911171645
> New version: 6.2.5.201911171645
... even if, obviously, at least 6.3.2 should be offered.

Note that "New version" should read "Highest version".
#### System information: 
- Windows 8.1
- DBeaver 6.2.5

**Comment by uslss** [comment]
verified
