### ISSUE TITLE
Fails to start with error "Invalid Configuration Location" (after upgrade from Zip install on Windows)

### ISSUE THREAD

**Issue by Chealer** [dbeaver/dbeaver#7591]
After trying to upgrade my DBeaver 6.2.5 to 6.3.2, I can no longer launch it. dbeaver.exe fails showing an "Invalid Configuration Location" dialog which contains:

> The configuration area at 'c:\Program Files\dbeaver\configuration' is not writable. Please choose a writable location using the '-configuration' command line option.

I manually installed from dbeaver-ce-6.3.2-x86_64-setup.exe. My previous installation was done with dbeaver-ce-6.2.5-win32.win32.x86_64.zip.

The c:\Programmes\dbeaver\configuration\ directory exists, however I cannot create files in it or edit its files. I need administrator permissions. I am an administrator on this Windows install.

If this is the result of something wrong I did, I definitely do not see what (I did not fiddle with DBeaver's install).

#### System information: 
- Microsoft Windows 8.1 Entreprise

**Comment by japark84** [comment]
I also have same issue. 
Please somebody reply answer for this issue. Thanks.

**Comment by serge-rider** [comment]
If you installed previous version from zip file then you need to delete it before new version install.

Also you could try to install dbeaver for current user only (it will be installed in your local user home app folder).

**Comment by Chealer** [comment]
Ah, congratulations @serge-rider that must have been it. I had indeed installed from dbeaver-ce-6.2.5-win32.win32.x86_64.zip.

I managed to workaround by uninstalling DBeaver, then deleting its directory and finally executing the new version's installer (again).

**Comment by Chealer** [comment]
@serge-rider why was this ticket closed?

**Comment by spasmsagain** [comment]
Hi

I have the same problem with configuration area but from the EXE file (not the ZIP)

I've been noticing this for several version upgrades (even from 6.x to 7.x

Windows 10
dbeaver 7.x series

I have administrator rights to my local machine. 

My workaround is simply to reset the permissions on the folder C:\Program Files\dbeaver\configuration for read and write access

**Comment by TomYule** [comment]
I have a similar problem
I unloaded and reloaded and still couldn't fix it
dbeaver-ce-22.2.0-x86_64-setup.exe
I installed the option for my own use and finally solved it

**Comment by craig-tx** [comment]
This is still happening, I got this just now updating to the latest. For anyone not wanting to install as local user, a workaround is to grant your specific user full control over the dBeaver installation folder. At an administrative command prompt enter:

`icacls "C:\Program Files\DBeaver\*" /grant:r machinename\username:F /T`
