### ISSUE TITLE
CSV Export with quotes on text fields

### ISSUE THREAD

**Issue by Rufh** [dbeaver/dbeaver#7593]
#### System information: 
- Windows 10
- DBeaver Version 6.3.2.202001051908

#### Connection specification:
- Oracle 11

#### Describe your question:
Hello,
I try to export a data set from a query in CSV format.
I expect to have quotes arround every text fields et no quotes on number like:
1452,"text",14.5,"text long",147.142898

but what i got is :
1452,text,14.5,text long,147.142898

How can i configure the csv export to got quotes on every fields that are not numerical ?

Thanks for your help.

**Comment by kseniiaguzeeva** [comment]
Seems that it is a bug. Thank you for your report.

**Comment by serge-rider** [comment]
Probably we'll need new option for that. E.g. "Quote all but numbers".
Or maybe even more flexible, "Quote [all|strings|all but numbers]".
WDYT?

**Comment by Rufh** [comment]
Hello,
The feature will be great wiht the multiple choice. ("Quote [all|strings|all but numbers]").

**Comment by uslss** [comment]
verified
