### ISSUE TITLE
Explain Execution plan menu is disabled for DB2

### ISSUE THREAD

**Issue by jmandawg** [dbeaver/dbeaver#7594]
Hi all,

I'm connecting to DB2 with  the JCC jar.  When i try to get Explain plan, the menu item is grayed out.  Is there something special you have to do to enable it?

Version 6.3.2.202001051908

![Screen Shot 2020-01-09 at 1 58 20 PM](https://user-images.githubusercontent.com/3180928/72096401-230bd180-32e8-11ea-986e-7b5460715408.png)

**Comment by jmandawg** [comment]
update: it does not show up for the z/OS driver, but it does show up for the LUW driver.  Unfortunately it throws an error when attempting to run it:

SQL Error [42612]: THE SQL STATEMENT IS NOT SUPPORTED. SQLCODE=-142, SQLSTATE=42612, DRIVER=3.68.61
  THE SQL STATEMENT IS NOT SUPPORTED. SQLCODE=-142, SQLSTATE=42612, DRIVER=3.68.61
  THE SQL STATEMENT IS NOT SUPPORTED. SQLCODE=-142, SQLSTATE=42612, DRIVER=3.68.61
    THE DESCRIBE STATEMENT DOES NOT SPECIFY A PREPARED STATEMENT. SQLCODE=-516, SQLSTATE=26501, DRIVER=3.68.61
    THE CURSOR SQL_CURLH200C1 IS NOT IN A PREPARED STATE. SQLCODE=-514, SQLSTATE=26501, DRIVER=3.68.61

**Comment by kseniiaguzeeva** [comment]
I use db2jcc4.jar driver for DB LUW, and Execution plan works correctly. What is your OS?

**Comment by jmandawg** [comment]
I'm using OSX, but our DB2 is def hosted on z/OS.  Maybe there is some incompatibility.  

For now i'm manually running the EXPLAIN statement and querying the explain tables to get the total cost.

**Comment by uslss** [comment]
duplicates #3328
