### ISSUE TITLE
Query auditing

### ISSUE THREAD

**Issue by niclarcipretti** [dbeaver/dbeaver#7595]
Hi,

I need to audit all querys executed in a DBeaver instance. What would be the recommended way to achieve this? Should I create an Eclipse plugin? Is there an extension point I could benefit of?

Thanks in advance

Nikao

**Comment by sglebs** [comment]
I also need to log the queries so they can't be deleted by the "operator" (support people). Much like Hashcorp Vault does - everything is logged to a safe place. I could implement my own mechanism (say log to ELasticSearch) and have DBeaver take my extension/plugin.

If this is already supported please let me know the details. Maybe all I need to do is implement an existing java interface and plug it in?

Thanks!

**Comment by uslss** [comment]
if i understand you correct, you could use Query Manager to see all the queries executed
