### ISSUE TITLE
[postgresql] newly opened SQL editor doesn't follow selected object connection

### ISSUE THREAD

**Issue by michalk-k** [dbeaver/dbeaver#7596]
When I select an object in Database Navigator and then open new SQL Editor, I expect the editor will be connected to the same database than selected object.
But it is not. It is connected to database marked as "active", with exception of the known bug in current version, when even this could not be true.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce in version 7.0.1. Is this still actual for you?

**Comment by michalk-k** [comment]
Yes and no.
In normal circumstances it works as expected.
However in response of your question I've tried it again and it failed.

I have postgresql cluster (I mean a few databases served by single postgresql instance) with one database selected as default.
Then I opened tree of other database selected schema and pressed CTRL+]. New tab has been opened but without database connected:

![obrazek](https://user-images.githubusercontent.com/7868445/78020988-afabb600-7352-11ea-9644-04438300f20c.png)

Please note, this image shows databases in the left column. Usually, if everything works fine, left column contain schema names, with database selector above it.

It's possible that the connection to the database was failed in the meantime. But looks it's not able to  recover (ie by retry when needed)

**Comment by michalk-k** [comment]
One additional information:
I cannot open new editor for all databases from picture above except the last one.
I don't know why, since all those dbs sits in the same cluster. 

Invalidate/reconnect doesn't help.
Disconnect from database takes ages and cannot end.
Looks like the only way to recover from this situation is to close and reopen DBeaver
At the same time there are 2 connections to db cluster created

![obrazek](https://user-images.githubusercontent.com/7868445/78023855-b1c44380-7357-11ea-9821-1348b38438b3.png)

**Comment by kseniiaguzeeva** [comment]
Trying to reproduce.
Please tell me your OS.

**Comment by michalk-k** [comment]
Kubuntu 18.04.

**Comment by kseniiaguzeeva** [comment]
I can reproduce it if a connection is failed when I'm trying to open SQL Editor. Please confirm.

**Comment by michalk-k** [comment]
very likely it's the trigger of the issue

**Comment by uslss** [comment]
![2020-04-10_14h29_45](https://user-images.githubusercontent.com/31996417/78987854-e1cdcc80-7b37-11ea-966e-c01bccc79ce4.gif)

**Comment by serge-rider** [comment]
Well, I'm sure we fixed the original problem somewhere around 6.3.x version.

When connection is broken there is no active schema obviously (as it is not possible to get it from the database). So I don't think that this particular issue is a bug.

**Comment by michalk-k** [comment]
Don't you think application should try to reconnect first, then to show error message if failed?  
Or do you think that showing unexpected content of db/schema selector is good enough cue to user about what is happening?

BTW I reported it when using v7.0.1. Have no idea what exactly has been fixed in 6.3

with regards

**Comment by uslss** [comment]
@michalk-k is Connected on Editor activation option enabled?
![image](https://user-images.githubusercontent.com/31996417/80208577-2ded3680-8639-11ea-984d-5f0dc1fb45cf.png)
