### ISSUE TITLE
Tables open in the Navigator pane instead of the Editor pane

### ISSUE THREAD

**Issue by 18549** [dbeaver/dbeaver#7598]
#### System information: 
- Win 10
- 6.3.2.202001051908
- No extensions

#### Connection specification:
- SQL Server Express
- Driver name: No idea. Where would I find this information?
- Local connection no tunnels or proxies.

#### Describe the problem you're observing:
I have an open connection to my database.
I see the Database Navigator on the left and the Editor pane on the right.
I double click a table in my database.
The table is opened as an additional tab in the Database Navigator pane on the left.

Prior to updating to the latest version of DBeaver tables always opened in the main content view, what I'm calling the Editor pane.

Tables opening in the left hand Database Navigator view is not at all useful as that view is tall and narrow so you can't see a useful number of table columns.

**Comment by 18549** [comment]
The main content area of the application now also appears to be a view inside another view.

If you look at this image at the top right you see I have one set of Minimise/Restore icons inside another set of Minimise/Restore icons. Despite this, pressing either of the minimize buttons just minimizes everything, I don't seem to be able to access the outer or inner views independently of each other, which seems to make the outer view completely pointless and a waste of vertical screen space as it uses an entire strip of the display taken up by a pair of redundant Minimize/Restore buttons.

![DBeaverIssue](https://user-images.githubusercontent.com/46347740/72150098-a2f37380-339c-11ea-99a5-be0979c32c7c.png)

**Comment by 18549** [comment]
I got it back to normal by opening the Resource persective, dragging the Database Navigator into the left hand pane, and closing the other panes I didn't want to look at.

So now it looks like this again, and tables open correctly in the right hand pane. But no idea what screwed it up in the first place.
![DBeaverIssue](https://user-images.githubusercontent.com/46347740/72150574-b2bf8780-339d-11ea-8f9a-f58d3fb04438.png)

**Comment by BendRJ** [comment]
I encountered the same issue. The described solution did not work for me.

**Comment by svonjoi** [comment]
> I encountered the same issue. The described solution did not work for me.

same here. Helped: window -> reset perspective

**Comment by petewoolley-kraken** [comment]
> > I encountered the same issue. The described solution did not work for me.
> 
> same here. Helped: window -> reset perspective

This. thank you
