### ISSUE TITLE
dbeaver connect sqlserver2008 error

### ISSUE THREAD

**Issue by dyd-git** [dbeaver/dbeaver#7603]
![1](https://user-images.githubusercontent.com/59757534/72199615-6ea1b500-3479-11ea-8c41-789a0f9d6c83.png)
![2](https://user-images.githubusercontent.com/59757534/72199631-86793900-3479-11ea-808f-74852b424921.png)
![3](https://user-images.githubusercontent.com/59757534/72199632-8da04700-3479-11ea-98d7-65e279f4eee9.png)

**trustServerCertificate value true can't modify false**

**Comment by dyd-git** [comment]
System information:
deepin linux version:15.10
DBeaver 6.3.2.202001051908
Java openjdk version "1.8.0_181"
Connection specification:
Database name and version: SQL Server 2008
Driver name: MS SQL Server / SQL Server
Do you use tunnels or proxies (SSH, SOCKS, etc)? No
Describe the problem you're observing:
Create a SQL Server connection ,I cannot modify Driving attribute trustServerCertificate value true to false

**Comment by uslss** [comment]
cannot reproduce an issue for now.
if it is still actual for you - feel free to reopen the ticket
