### ISSUE TITLE
DBeaver for Raspberry Pi ?

### ISSUE THREAD

**Issue by JacoFourie** [dbeaver/dbeaver#7606]
Hi.

I have done a lot of Googling and can not find how to install DBaever on the Raspberry Pi ?
I have a Pi with 4GB ram and it develops like a charm. I read in some questions back in 2016 you waited for Eclipse to be available on the Pi. 

It is available https://www.digikey.com/en/maker/blogs/2018/how-to-install-eclipse-on-a-raspberry-pi

So how can in install DBeaver on the Pi ?

**Comment by Jens2205** [comment]
Hi,
have found an installation option via snap (https://snapcraft.io/install/dbeaver-ce/raspbian):
`sudo snap install dbeaver-ce`

But at the moment only 5.2.4 is available for raspberry pi and poorly it is not working.

Is it possible to provide the latest snap dbeaver version (6.3.1) also for this environment?

Thanks in advance!

**Comment by hms5232** [comment]
Have same issue, too.

I use snap install DBeaver on my Raspberry Pi 4 (8GB) with Raspbian (32 bit) yesterday. From edge channel, latest version is still 5.2.4 and doesn't work.

By the way, [snapcraft](https://snapcraft.io/install/dbeaver-ce/raspbian) site says use `sudo snap install dbeaver-ce` to install DBeaver, but it can't be installed without `--edge` parameter. Does the website miss this?

**Comment by serge-rider** [comment]
DBeaver is based on Eclipse platform. It doesn't support ARM builds officially yet. So all builds are experimental at the moment.

Good news is that Eclipse platform (SWT) was ported to ARM: [
Eclipse is coming to Raspberry Pi](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=284879)

Hopefully Eclipse Foundation will include ARM builds to the official repository soon. Then we'll be able to ship Raspberry builds along with other distributions.

**Comment by flambchap** [comment]
You can now download the official build from our website. Yahoo!

**Comment by hms5232** [comment]
Saddly, Raspberry Pi OS is 32bit. It still can't run on PRi if you are using official OS. 
Good news is that 64bit version RPi OS is in beta.

**Comment by bcutter** [comment]
> Saddly, Raspberry Pi OS is 32bit. It still can't run on PRi if you are using official OS. Good news is that 64bit version RPi OS is in beta.

**64 bit OS is now considered stable/production ready. See https://www.raspberrypi.com/news/raspberry-pi-os-64-bit
+1 reason to migrate to x64 so DBeaver can finally be used on a RPi.**


_(I performed the steps listed at https://dbeaver.io/download/..._
```
wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list
sudo apt-get update && sudo apt-get install dbeaver-ce
```
_...just to find out there's no `dbeaver-ce` in the package. Download page has some indications because all Linux downloads listed are named "64 bit".)_
