### ISSUE TITLE
Task works incorrect in case default and active databases aren't the same

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7609]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version postgresql

#### Describe the problem you're observing:
Error like "ERROR: relation "actor" does not exist" appears when trying to execute export in case default and active database aren't the same
[log.txt](https://github.com/dbeaver/dbeaver/files/4050750/log.txt)

**Comment by serge-rider** [comment]
We need to save active database and active schema in task configuration.

**Comment by serge-rider** [comment]
Fixed.

**Comment by uslss** [comment]
verified
