### ISSUE TITLE
Dont restore backup

### ISSUE THREAD

**Issue by cabritto** [dbeaver/dbeaver#7610]
#### System information: 
- Operating system (distribution) and version, Linux mint 19.1 mate 64 bits
- DBeaver version,  6.3.2
- Additional extensions

#### Connection specification:
- Database name and version , PostgreSql 9.3
- Driver name. PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? use ssh tunnel

#### Describe the problem you're observing:
At restore backup do not take  database restore path

#### Steps to reproduce, if exist:
1-  Generate backup to de local database
2 - Restore backup to remote database

#### Include any warning/errors/backtraces from the logs

Data transfer failed

Razón:
 Error executing process

**Comment by cabritto** [comment]
I downgrade to 6.2.2 version

**Comment by serge-rider** [comment]
I believe we already fixed this in some other ticket.
Could you test it Early Access version? (https://dbeaver.io/files/ea)

**Comment by kseniiaguzeeva** [comment]
Cannot restore a schema in Postgresql. An error: 
"Task execution failed
Reason:
Error executing process
Task execution failed"

**Comment by serge-rider** [comment]
@kseniiaguzeeva full error log needed. Perhaps some restore error happened (not related to the active/non-active database/schema)

**Comment by kseniiaguzeeva** [comment]
as I see, restoring the whole schema does not work. Please try:

**Comment by serge-rider** [comment]
This is not an error in dbeaver:
```
pg_restore: [archiver (db)] could not execute query: ERROR:  schema "test2601" already exists
...
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "newtable" already exists
```

**Comment by kseniiaguzeeva** [comment]
Verified
