### ISSUE TITLE
View and Procedure definitions not available for Netezza

### ISSUE THREAD

**Issue by DragonStorm97** [dbeaver/dbeaver#7611]
"view definition not available for db netezza" (https://github.com/dbeaver/dbeaver/issues/391) is closed, but is still an issue.
I commented on the issue post-closure to no-avail, so i'm logging this issue.

- Windows 10 17134
- DBeaver 6.1.2
- Netezza
- NZJDBC driver
- No tunnels or proxies

Issue:
Most views and procedures show "-- Netezza view definition not found"/"-- Netezza procedure source not found"

Reproduction:
open the definition for any view or procedure on Netezza that was not created by your user.

In Netezza, the owner of a database object is not the schema, but a user. 
I see that when trying to get the definitions, the owner is filtered to the current user, this means that only objects owned (i.e. created) by the current user are shown. This should rather be a filter based on the database/schema.

My comment on the other issue:
"the problem with the query to get the definition is that it is filtering on owned objects, which i feel is incorrect as my user might need to pull a view DDL and not own it. the owner is a user and not a schema, so only if a user creates a view,etc themself will the DDL be visible.
Would it not be better to just pull from _v_view instead of joining to _v_objs_owned?
the current query is SELECT v.definition FROM _v_view v, _v_objs_owned o WHERE v.objid = o.objid AND o.DATABASE='DB_NAME' AND v.VIEWNAME='VIEW_NAME';
but it can be: SELECT v.definition FROM _v_view v where v.VIEWNAME='VIEW_NAME';"

**Comment by DragonStorm97** [comment]
I also mentioned the owner filter in https://github.com/dbeaver/dbeaver/issues/3658 for procedures, which should rather be a filter on the database and schema.

**Comment by serge-rider** [comment]
Unfortunately I can't test this as I don't have access to a live Netezza instance.
However I've pushed the proposed fix. I'm not 100% sure that it is correct (ignoring schema name is odd).
Please test how it works in the Early Access version (https://dbeaver.io/files/ea)
