### ISSUE TITLE
Stop reconnecting to non-reachable databases

### ISSUE THREAD

**Issue by Sitethief** [dbeaver/dbeaver#7612]
#### System information: 
- Ubuntu 18.04
- DBeaver 6.3.2
- Java version 
> openjdk version "1.8.0_232"
> OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
> OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

#### Describe the problem you're observing:
I sometimes use SSH tunnels to connect to remote databases. These auto close after a set time.
DBeaver tries to reconnect to these remote databases, but can't because the tunnel is no longer present. it mostly tries to reconnect when I wake my laptop up or restart/reopen DBeaver, but also when connecting to any other unrelated database.  So far so good.

_Note: these SHH tunnels are not present in DBeaver its self because I don't just use the SSH tunnel just for my database. For example a tunnel like this to GCloud:
`'gcloud compute ssh testserver -- -N -p 22 -L 5055:localhost:3306 -f`_

Now here is my problem:
If I want to prevent these annoying, useless reconnect attempts, I have to open the ssh tunnel, click "Reconnect" for that database and then click "Disconnect". I have to do that for each lost connection and each unreachable database, some ssh tunnels have multiple associated databases.

I can't stop DBeaver trying to connect to these databases without connecting to each remote database and ssh tunnel first. Both the Invalidate/Reconnect and Disconnect options are greyed out 
I would like to be able to stop trying to connect to a database without needing access to said database first.

**Comment by serge-rider** [comment]
You can disable auto-reconnect: 
![image](https://user-images.githubusercontent.com/6398845/72245086-c0c11280-3600-11ea-9c34-289f39e473b7.png)

Also you can try to do "Disconnect All" or disconnect all connections in a folder or project.

**Comment by Sitethief** [comment]
- "Disconnect all" does nothing for the not connected databases.
- Unchecking "Connection auto-recover enabled" gives me another "Connection refused" when clicking "OK". Afterwards the problem does not go away for that database and the same error keeps showing up.

![2020-01-13 10:51:13 ](https://user-images.githubusercontent.com/389290/72246285-ab44ec00-35f2-11ea-9d14-c3daf2098e05.png)

**Comment by uslss** [comment]
is it still actual against the recent version?

**Comment by uslss** [comment]
if issue is still actual for you - feel free to reopen the ticket
