### ISSUE TITLE
mysql with gbk gibberish 

### ISSUE THREAD

**Issue by shuqian** [dbeaver/dbeaver#7613]
platform :windows 10 && MacOs Chinese
MySQL:mysql 5.*

for history reason mysql data table Charset is latin1 and Collation is latin1_swedish_ci
but my data insert with gbk ,Collation gbk_chinese_ci,

I change the driver properties(characterEncoding,characterSetResults,connectionCollation…) setting many times ,and also set the 'Result Sets' Data Formatting  language is  zh-Chinese ,but  failed  at all 

![173810](https://user-images.githubusercontent.com/5841112/72245661-01825100-362c-11ea-9f1e-5d459e849f2b.jpg)

**Comment by serge-rider** [comment]
If your table has charset latin_1 then it can't contain Chinese characters.
I don't see what can we do here from dbeaver side..
