### ISSUE TITLE
Materialized view does not save changes

### ISSUE THREAD

**Issue by slawapro** [dbeaver/dbeaver#7615]
#### System information: 
- Operating system (distribution) and version
Windows 7 
- DBeaver version
6.2.3
- Additional extensions
none
#### Connection specification:
- Database name and version
Postgresql 9.6
- Driver name
PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
I need to make changes to the query materialized view. I am editing the source code. I click the "Save" button (Ctrl-S). After updating the window, i see that the changes were not saved.
#### Steps to reproduce, if exist:
Select and change Materialized view. Save changes. Refresh Window.

**Comment by serge-rider** [comment]
Fixed (in fact mat view alter = drop+create so be careful with this)

**Comment by uslss** [comment]
verified
