### ISSUE TITLE
Selecting a table to display adds "order by 13" during the select?

### ISSUE THREAD

**Issue by michael-newsrx** [dbeaver/dbeaver#7616]
In the table browser I open a table to display it's data w/o any filters or predefined ordering and the query which gets executed looks like:

```sql
SELECT * FROM database.table
ORDER BY 13
LIMIT 0, 200
```

#### System information: 
- Linux Mint Mate
- DBeaver 6.3.2
- No additional extensions

#### Connection specification:
- MariaDB
- I do not use tunnels or proxies.

#### Describe the problem you're observing:

Unexpected order by being added to sql query

#### Steps to reproduce, if exist:

Not sure.

#### Include any warning/errors/backtraces from the logs
The log files do not show any warnings or errors.

**Comment by michael-newsrx** [comment]
Work around: downgrade to 6.2.5

**Comment by michael-newsrx** [comment]
Weirdness. I downgraded to 6.2.5 and the problem remained.

So I put in a 1=1 order by pk in the filter input line on the table.
then I hit "clear filter" and the unexplained "order by 13" is no longer happening.

I then upgraded to 6.3.2 and the problem returned with the unexplained "order by 13".
I then repeated the "1=1 order by pk" followed up by the clear filter and the unexplained "order by 13" disappeared.

I then closed the table and reopened it and the "order by 13" came back.

**Comment by tati-kru** [comment]
Order by 13 is a sorting by column with number 13 that has some complicated name (perhaps contains special characters or spaces).
It seems you have some saved filter for ordering by this column. You can find saved filters it if you press the "Customize filters..." button near the filter line. Could you please check?

**Comment by michael-newsrx** [comment]
Shows blank.

**Comment by michael-newsrx** [comment]
May have found a "fix" for the weirdness.

I did a "1=1" in the filter line and it returned a result set w/o the "order by 13" 

I then cleared the filter then hit "save filter"

Closed the table, reopened it and the "order by 13" did not occur again.

Restarted dbeaver-ce and the problem did not occur again.

**Comment by tati-kru** [comment]
Thank you for letting us know.
