### ISSUE TITLE
Error when setting xml type null(setnull())

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#7618]
**System Information:**
- Operation System
  Windows 10
- DBeaver version
   6.3.1
- Additional extensions
  No

**Connection specification:**
- Database name and version
  Oracle 12c
- Driver name
  Oracle JDBC Driver
- Do you use tunnels or Proxies(SSH, SOCKS, etc) ?
  No

An error occurred when setting null to xml type column.

1. Error when executing set null command after right clicking on Result Grid.
 ![setnull](https://user-images.githubusercontent.com/59002295/72300950-a6427400-36a8-11ea-867d-c3f6a3bbd727.gif)

2. An error occurs when saving after deleting data in the Results cell value Viewer.
![setnull1](https://user-images.githubusercontent.com/59002295/72300954-a8a4ce00-36a8-11ea-81a6-dcb0bd18e5ee.gif)

thank you for reading.    :)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
