### ISSUE TITLE
unable to filter resultset without query refresh 

### ISSUE THREAD

**Issue by arunkr16** [dbeaver/dbeaver#7619]
#### System information: 
- Operating system (distribution) and version
Mac OS 10.14.6
- DBeaver version
6.3.1
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I want to apply filters to Hive query output, but when I select a value to filter the result set it submits another Hive query to refresh the results. I was able to filter results in older version without auto query refresh but I can't seem to find the setting in this new version.
#### Steps to reproduce, if exist:
please see screenshot
<img width="305" alt="p1" src="https://user-images.githubusercontent.com/59853920/72304969-1e685580-3627-11ea-8f33-123e8649496c.png">

**Comment by serge-rider** [comment]
Thanks for the bug report.
As far as I understand the problem is in filter popup window close (because of an error during filter loaded).
Fixed

**Comment by uslss** [comment]
verified
