### ISSUE TITLE
Cannot connect to MariaDB/MySQL with SSL

### ISSUE THREAD

**Issue by phil93883** [dbeaver/dbeaver#7620]
#### System information: 
- macOS Catalina 10.15.2 and Windows 10
- DBeaver version - 6.3.2.202001051908
- Additional extensions - None

#### Connection specification:
- AWS RDS (MariaDB 10.1.26)
- Driver name - MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - No 

#### Describe the problem you're observing:

DBeaver will not connect to MariaDB via SSL.  I'm using the AWS RDS certificate "rds-combined-ca-bundle.pem" to connect.  It works fine with HeidiSQL on Windows, MySQL Workbench, and Sequel Pro on MacOS.  Non-SSL connections work fine.  The error is:

<img width="855" alt="Screen Shot 2020-01-13 at 21 43 53" src="https://user-images.githubusercontent.com/59853419/72310219-3653cf80-364f-11ea-83e8-405dd15aba79.png">

#### Steps to reproduce, if exist:

Setup a new connection, enable SSL, and point the "CA certificate" field to the AWS RDS certificate.  Try to connect and get error.

#### Include any warning/errors/backtraces from the logs

Nothing recorded in the error log.

**Comment by phil93883** [comment]
Seriously, am I the only one using SSL to connect to a database?

**Comment by agrisvv** [comment]
> Seriously, am I the only one using SSL to connect to a database?
Do workbench and HeidiSQL use SSL? because AWS DB allow also without SSL. 

i'm using for log period. And my database always work with SSL
Fedora 31
DB Beaver 6.3.3 community RPM.
AWS Mariadb 10.3 default options.

Config:
CA /home/xxx/rds-ca-2019-root.pem ( it is 2019 ca)
Required SSL: checked
Verify server certificate: checked
____
And one warning for you, when  dbeaver dump DB check command is it with ssl or without.

**Comment by phil93883** [comment]
Heidi, MySQLWorkbench, Sequel Pro, TablePlus, etc ALL work properly using SSL.

**Comment by phil93883** [comment]
Can you attach a screenshot of your settings?

**Comment by phil93883** [comment]
<img width="1392" alt="Untitled" src="https://user-images.githubusercontent.com/59853419/74595171-6acef880-500c-11ea-94c8-580e3881d425.png">

**Comment by phil93883** [comment]
<img width="1477" alt="Untitled" src="https://user-images.githubusercontent.com/59853419/74595213-b84b6580-500c-11ea-89cc-792f3120ce52.png">

**Comment by agrisvv** [comment]
> Can you attach a screenshot of your settings?

Handshake i think are something with tls version and chiper keys.
![connection](https://user-images.githubusercontent.com/8926651/74661115-00e75800-51a0-11ea-91ef-6a710bd1c122.jpg)

**Comment by phil93883** [comment]
I suspect I am the only one in the world having this issue.  I will have to find another database utility.  Thanks

**Comment by phil93883** [comment]
So how can I change the TLS versions?  This does not work in Windows either.

**Comment by phil93883** [comment]
I have solved the issue. For anyone interested, I deleted the connection and re-created it as a MySQL connection (not a MariaDB connection), even though I am connecting to MariaDB.

**Comment by Tintwo** [comment]
I think your problem is more interesting than you think. You gave a working trick to "solve" it, but it doesn't change the fact that MariaDb driver has a problem.

Maybe it's a problem inside the driver itself, maybe it's the dbeaver implentation. This issue should stay open until an answer si given.

**Comment by phil93883** [comment]
Sure.  I'll reopen it.

**Comment by stratos528** [comment]
I just ran into this issue as well.  I am using Version 7.0.1.202003211804.

**Comment by serge-rider** [comment]
What version of MariaDB driver do you use?

**Comment by stratos528** [comment]
The work around worked for me.

I am using this version of MariaDB: mariadb-java-client-2.4.3.jar

Not sure if this additional information helps, but I get this error when attempting to use SSL through an SSH tunnel.

Could not connect to 127.0.0.1:19419 : Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
  Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
  Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
    the trustAnchors parameter must be non-empty
    the trustAnchors parameter must be non-empty

**Comment by stratos528** [comment]
@serge-rider   You sir are brilliant.  Updating the driver to a newer version resolved the issue.  I am now using mariadb-java-client-2.6.0.jar and connecting successfully.

**Comment by serge-rider** [comment]
I've reproduced this. MariaDB driver uses different connection parameters and probably different certificate store approach. 
I made it work in non-validating mode but I still don't understand how exactly truststore differs from MySQL..

**Comment by tastyqbit** [comment]
The problem may be down to OSX Catalina enforcing certificates with a validity date shorter than the Amazon RDS bundle - https://support.apple.com/en-us/HT210176. So far, I haven't found a solution. Seems stupid by apple..

**Comment by phil93883** [comment]
I will reiterate that other database management apps on the Mac work.

**Comment by Tintwo** [comment]
> I think your problem is more interesting than you think. You gave a working trick to "solve" it, but it doesn't change the fact that MariaDb driver has a problem. (We got the same issue on our side)
> 
> Maybe it's a problem inside the driver itself, maybe it's the dbeaver implentation. This issue should stay open until an answer is given.

I forgot to mention I'm not using macOS but Linux (Ubuntu here).

**Comment by serge-rider** [comment]
There are several workarounds for MariaDB driver:
- Disable server certificate validation checkbox (many DB tools do this implicitly to avoid such problems)
- Provide all certs (CA, user SSL certificate and its private key)
- Use MySQL driver

So far I have no other ideas..

**Comment by tati-kru** [comment]
It looks like we can't fix it on DBeaver side. Please, use workarounds.

**Comment by rm3nchaca** [comment]
> There are several workarounds for MariaDB driver:
> 
> * Disable server certificate validation checkbox (many DB tools do this implicitly to avoid such problems)
> * Provide all certs (CA, user SSL certificate and its private key)
> * Use MySQL driver
> 
> So far I have no other ideas..

I had the same problem with ubuntu 18.04, Dbeaver 7.1.1 and java 11, the solution was to disable server certificate validation.
I have java 8 and java 11 and sometimes  I made a switch between versions (using update-alternatives --config java). There is no problem with java 8, only with 11.
