### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by Spoelle** [dbeaver/dbeaver#7622]
#### System information: 
- WIN10 64 bit
- DBeaver version Version 6.3.3.202001140839
- Additional extensions : /

#### Connection specification:
- SQL-Server

#### Describe the problem you're observing:
When changing the UI to for example Classic =>all is ok but when restarting DBeaver an ugly "stone red" color is cluttering the interface

First all is ok
![image](https://user-images.githubusercontent.com/19902865/72334228-41454900-36bd-11ea-84fd-2b5bfa40ddb9.png)

But after restart the stone red color comes in
![image](https://user-images.githubusercontent.com/19902865/72334056-093e0600-36bd-11ea-9cc2-169b9079bc4c.png)

**Comment by tati-kru** [comment]
It seems that Production type is applied for your connection. By default the production type is colored red in the Classic theme. 

You can change Connection type in the connection preferences:
"Edit connection" in the context menu of connection >> Connection Settings >> General >> Connection type dropdown.

Also, you can change color of particular Connection type:
"Edit connection" in the context menu of connection >> Connection Settings >> General >> Connection type >> "Edit connection types" link >> Color.

**Comment by Spoelle** [comment]
Ooohhh, thank you tati-kru; not a bug but a very fine setting, very useful!
