### ISSUE TITLE
Query error

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#7623]
![图片](https://user-images.githubusercontent.com/26621087/72335672-52607b00-36fa-11ea-8b09-9c76d61c421f.png)
![图片](https://user-images.githubusercontent.com/26621087/72335679-57bdc580-36fa-11ea-8ee2-9f536cc4371a.png)

#### System information: 
- Operating system (distribution) and version  WIN1064
- DBeaver version  6.32
- Additional extensions

#### Connection specification:
- Database name and version hive1.1
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
unfortunately, it is not enough information for investigation this issue. if it is still actual for you - feel free to reopen the ticket
