### ISSUE TITLE
Missing files for OSX on Download page (404 Not Found dbeaver-ce-6.3.3-macos.dmg)

### ISSUE THREAD

**Issue by kivagant-ba** [dbeaver/dbeaver#7624]
.dmg and .pkg files are missed for MacOs, https://dbeaver.io/download/:
- https://dbeaver.io/files/6.3.3/dbeaver-ce-6.3.3-installer.pkg
- https://dbeaver.io/files/6.3.3/dbeaver-ce-6.3.3-macos.dmg

Thank you for so useful product!

**Comment by serge-rider** [comment]
Thank you for the bug report.
It was a human error during early access version publishing. At the moment latest dbeaver version is 6.3.2.
Now fixed.
