### ISSUE TITLE
different colors for connections?

### ISSUE THREAD

**Issue by jviure** [dbeaver/dbeaver#7625]
Hi! I don't know if it's possible but would be good the possibility of give different colors to different connections. I.e, I work with two databases (test and production), sometimes during the day I apply some sql sentences to the editor to the wrong connection :S , if I have i.e every sql editor or table view of a different color (the tab i.e.) would be great to minimize this mistakes! : ) it's only an idea! thanks!

**Comment by serge-rider** [comment]
This feature already exists (it is one of the oldest, i think).

![image](https://user-images.githubusercontent.com/6398845/72343206-5c28b500-36df-11ea-9e72-e2eb669f27ef.png)
