### ISSUE TITLE
search for a column

### ISSUE THREAD

**Issue by jviure** [dbeaver/dbeaver#7626]
Hi! it's possible to search a column? I ve some tables with many columns (too much..) and sometimes to find an specific columns I waste a lot of time..  would be great, thanks! :)

**Comment by uslss** [comment]
hi @jviure ,
you could use DB Metadata Search for this
![image](https://user-images.githubusercontent.com/31996417/79779167-9dfe7280-8342-11ea-8162-056b97be3bd2.png)
Sorry for the late response
