### ISSUE TITLE
direct Cellvalue filter

### ISSUE THREAD

**Issue by Kaennchen** [dbeaver/dbeaver#7627]
It would be great if there was a shortcut to filter the current Cellvalue (Cellvalue = '...').
In addition, with the Filter by Value, the current cell value could be pre-assigned directly below, so you could simply confirm it with enter.

**Comment by uslss** [comment]
Hi @Kaennchen ,
if I understand you right, you could use F11 and then choose needed value
![image](https://user-images.githubusercontent.com/31996417/72736069-191e8400-3bae-11ea-8f1b-681cf0a1dc35.png)
Also you could use icon near the column name 
![image](https://user-images.githubusercontent.com/31996417/72736201-57b43e80-3bae-11ea-9101-34f7631619b4.png)

**Comment by Kaennchen** [comment]
Yes thats right but it is very cumbersome, to make two or more steps.

**Comment by uslss** [comment]
Maybe Ctrl+F11 is suitable for you?

**Comment by uslss** [comment]
there is no update in issue for a month.
Ticket closed.
If you want to suggest any feature - feel free to create ticket
