### ISSUE TITLE
Binding parameters dont work while creatting temp table

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#7628]
ver 6.3.2, engine: pgsql

parameters generally work, but do not when using below statement 

![image](https://user-images.githubusercontent.com/5410448/72348461-c3903600-36da-11ea-83e2-a16b130f2e30.png)

**Comment by serge-rider** [comment]
You need to enable option "Enable parameters in DDL":
![image](https://user-images.githubusercontent.com/6398845/72446453-a9cb1d80-37c4-11ea-9ca2-07f6c1d5aba9.png)

**Comment by maciey** [comment]
Thank you - indeed now it is working.
Closing issue then
