### ISSUE TITLE
Restore broken because of wrong dbname in restore command

### ISSUE THREAD

**Issue by GitRon** [dbeaver/dbeaver#7629]
Hi guys,

I have no idea why but from one second to the next the restore function for my Postgres connection was setting a wrong database name param `--dbname`. It was the db name of a different connection which was closed at this time.

No chance to tell him otherwise, not with specifiying the param or restarting the tool.

Happended on version 6.3.2 (Win10 64bit), working on 6.3.0.

I needed to restore something fast, so I unfortunately cannot provide any more details.

Maybe this helps anyway.

PS: I checked all the issues in github, hope I'm not creating a duplicate.

**Comment by uslss** [comment]
Probably, it is already fixed.
You could test it in EA Version (https://dbeaver.io/files/ea/)

**Comment by potterpg** [comment]
Problem for me also...
Annoying bug I hadn't noticed why a restore was failing... into a dbase not even on this server.
does the ea version work?

**Comment by potterpg** [comment]
OK, ea version appears to work, although now not setting active database is a bit un-nerving after getting used to having to do that.
