### ISSUE TITLE
Autocomplete in Eclipse Extension

### ISSUE THREAD

**Issue by angelotodaro** [dbeaver/dbeaver#7630]
**Is your feature request related to a problem? Please describe.**
I've recently switched to using the Eclipse extension from the full DBeaver application and I noticed that the autocomplete function isn't available.

**Describe the solution you'd like**
Would it be possible to enable this or is it a limitation due to it being an extension.

**Describe alternatives you've considered**
For the time being I have gone back to the full DBeaver installation, but for the few devs in our shop we'd like to have essentially a One Stop Shop for all development and Eclipse loaded with the plugins we use would be a perfect solution.

**Additional context**

**Comment by angelotodaro** [comment]
Is this something that was already built in and needs to be enabled?

**Comment by uslss** [comment]
seems the issue is outdated.
Autocompletion is working in the eclipse extension for now.
