### ISSUE TITLE
Update Database-Navigator active connection when moving to next SQL-Editor widow

### ISSUE THREAD

**Issue by pijoter** [dbeaver/dbeaver#7632]
DBeaver - 6.3.3 CE
DBeaver driver: Hive / SQLite / Postgers
Operating System: Windows 10

It would be really great if the indication of active database in database-navigator changed after sql-editor window change.

Today the indication at the top of the sql-editor is updated correctly (#7544 fixed in 6.3.3) but active connection in database-navigator does not.

Also, menu checkbox SQL Editor ->Auto-sync connection with navigation does not work as expected.

**Comment by serge-rider** [comment]
Active connection in database navigator is now unrelated to SQL editor active connection. Each SQL editor has its own active connection (as it has its own physical database connection).
You can change this behavior by disabling "Open separate connection for each editor" option in SQL editor preferences.
