### ISSUE TITLE
Neo4j, value-view/panel results show messed up values

### ISSUE THREAD

**Issue by pijoter** [dbeaver/dbeaver#7635]
#### System information: 
- Operating system (distribution) and version
Windows 10, version 1809
- DBeaver version
 6.3.3.202001121117
- Additional extensions
none

#### Connection specification:
- Database name and version
Neo4j Community Edition 3.5.14 (linux, dockerized)
- Driver name
org.neo4j:neo4j-jdbc-driver version 3.4.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
yes, ssh tunnel (but without ssh tunnel program behave the same)

#### Describe the problem you're observing:
related to #7543

#### Steps to reproduce, if exist:
MERGE (a:Station{name:"King's Cross St. Pancras"})
SET a.latitude = 51.5308,a.longitude = -0.1238
MERGE (b:Station{name:"Euston"})
SET b.latitude = 51.5282, b.longitude = -0.1337
MERGE (c:Station{name:"Camden Town"})
SET c.latitude = 51.5392, c.longitude = -0.1426
MERGE (d:Station{name:"Mornington Crescent"})
SET d.latitude = 51.5342, d.longitude = -0.1387
MERGE (e:Station{name:"Kentish Town"})
SET e.latitude = 51.5507, e.longitude = -0.1402
MERGE (a)-[:CONNECTION{time:2}]->(b)
MERGE (b)-[:CONNECTION{time:3}]->(c)
MERGE (b)-[:CONNECTION{time:2}]->(d)
MERGE (d)-[:CONNECTION{time:2}]->(c)
MERGE (c)-[:CONNECTION{time:2}]->(e);

MATCH(s:Station)
RETURN collect([s.name,s.latitude,s.longitude])

Then show value view in result panels.

expected:
0 [King's Cross St. Pancras, 51.5308, -0.1238], 
1 [Euston, 51.5282, -0.1337], 
2 [Camden Town, 51.5392, -0.1426], 
3 [Mornington Crescent, 51.5342, -0.1387], 
4 [Kentish Town, 51.5507, -0.1402]]

got:
![neo4j_dbeaver6 3 3](https://user-images.githubusercontent.com/455859/72368503-7de56480-36fe-11ea-833a-5d62118e66c0.jpg)

**Comment by serge-rider** [comment]
Fixed (the problem was caused by non-standard array values in JDBC ResultSet).

**Comment by uslss** [comment]
verified
