### ISSUE TITLE
Eclipse expects SQL files to be connected (adds "<none>" before SQL file tab names)

### ISSUE THREAD

**Issue by Chealer** [dbeaver/dbeaver#7637]
## System information: 
- Windows 8
- DBeaver 6.3.2

#### Describe the problem you're observing:
When a .sql file is opened with Eclipse, Eclipse uses a SQL editor in a tab which has the file's name as its name (if the file is /root/install.sql, the tab's name will be "install.sql").

When DBeaver is installed, the "SQL Editor" changes. The augmented "SQL Editor" becomes more of a rich console. Initially, these consoles have no associated connection. When a SQL file has no connection, the tab is poor:
1. The name of the tab (the tab itself) starts with "\<none\>", as a result of the _Script title pattern_ in the Scripts panel of the SQL Editor preferences group defaulting to "<${connectionName}> ${fileName}".
2. All normal console features at the left are offered. Ctrl+Enter, for example, is offered, even though it results in a "No active connection" error.

After a long time, I figured out that a script could be associated with a connection using the _Active datasource_ widget in the _DataSource Selector_ section of the main toolbar. Initially, that widget is on option "N/A":
![DBeaver Eclipse SQL editor](https://user-images.githubusercontent.com/486141/72386286-2095e700-36ef-11ea-858f-89db05e343df.PNG)
It took me a lot of time to find it because I was looking for it in the _Project Explorer_ view.

In the end, I don't think associating a file helps with the 2 ultimate problems :
1. Space in the tab strip is lost because "<${connectionName}>" adds many characters.
2. The least important part of the tab name is at the start, which causes the important part (the one which allows to distinguish it from other SQL tabs in the same project) to be easily truncated (with an ellipsis) when too many tabs are opened.

I recommend at least 1 of the following changes:

1. Not showing "<${connectionName}>" when there is no connection
2. Changing the default Script title pattern to remove "<${connectionName}>"
3. Changing the default Script title pattern to move "<${connectionName}>" at the end

#### Steps to reproduce, if exist:
1. Open a .sql file which has no datasource selected

**Comment by p91paul** [comment]
Just FIY, the **project**  cannot be associated with a connection. The association is made for the single sql editor, that's why you cannot find it in project properties.

**Comment by Chealer** [comment]
> Just FIY, the **project** cannot be associated with a connection. The association is made for the single sql editor, that's why you cannot find it in project properties.

Thank you
I adjusted the description, but it remains impossible to associate from the Project Explorer view.

**Comment by uslss** [comment]
Script title could be modified in Preferences
![image](https://user-images.githubusercontent.com/31996417/80036285-1c514500-84fa-11ea-99c4-a452bdc5326a.png)

**Comment by Chealer** [comment]
@uslss why was this ticket closed?

**Comment by uslss** [comment]
@Chealer , you could change script title pattern name in preferences

**Comment by Chealer** [comment]
> 
> 
> @Chealer , you could change script title pattern name in preferences

Thanks @uslss I realized that while reporting this. That does allow to workaround most of this issue.
