### ISSUE TITLE
Save active database/schema for SQL editor

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#7638]
We need to save and load selected catalog//schema for each SQL editor (the same way we save active connection).

**Comment by serge-rider** [comment]
Implemented in #4792

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by mikkk3l** [comment]
Hi. I've checked this functionality in 6.3.4 and it does not work. When I restart DBeaver, default schema is gone.

**Comment by mikkk3l** [comment]
Update: It does work with DB2 JDBC driver but not with Oracle ojdbc8.jar.

**Comment by mikkk3l** [comment]
It does not work:

I attach a gif to see the behaviour.
![2020-02-24_dbeaver_schema_db2_not_working](https://user-images.githubusercontent.com/15341836/75674513-7c0f3a80-5c85-11ea-9012-04a591fd105a.gif)

**Comment by kseniiaguzeeva** [comment]
Duplicates #8084
