### ISSUE TITLE
SSH Tunnel Permission denied

### ISSUE THREAD

**Issue by chrisjimallen** [dbeaver/dbeaver#7640]
#### System information: 
- Ubuntu 19.10
- DBeaver version - 6.3.2

#### Connection specification:
- Database name and version - MySQL (10.1.41-MariaDB)
- Driver name - MySQL8+
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes

#### Describe the problem you're observing:

When I try to connect to my server via SSH tunnel, it gives me a 'Permission denied' error. The ssh key works fine when using the `ssh` command via terminal, and also works in MySQL Workbench. Permissions are 600.  See attached screenshots.

#### Steps to reproduce, if exist:
- Choose SSH Tunnel in connection settings.
- Enter hostname, port and ssh username. 
- Enter path of SSH key eg. `/usr/share/dbeaver/id_rsa`
- Click connect.

#### Include any warning/errors/backtraces from the logs
```
Cannot establish tunnel
  java.io.FileNotFoundException: /usr/share/dbeaver/id_rsa (Permission denied)
  java.io.FileNotFoundException: /usr/share/dbeaver/id_rsa (Permission denied)
    /usr/share/dbeaver/id_rsa (Permission denied)
    /usr/share/dbeaver/id_rsa (Permission denied)
```
![Screenshot from 2020-01-15 08-50-31](https://user-images.githubusercontent.com/1681063/72420036-e6235d00-3775-11ea-8922-303a3dd909fc.png)
![Screenshot from 2020-01-15 08-51-04](https://user-images.githubusercontent.com/1681063/72420039-e6235d00-3775-11ea-90ae-9c8fd470609c.png)

**Comment by chrisjimallen** [comment]
Can be closed, this is the fix: https://github.com/dbeaver/dbeaver/issues/5845#issuecomment-503481448

**Comment by jaybeaton** [comment]
FYI, I had this same error when running the Snap installation of dbeaver for Ubuntu, and I was not able to get that working even after trying the suggestions in the linked issue above.  I had to uninstall the Snap version and install the version downloaded directly from the dbeaver.io website.  That worked fine after installing SSHJ per this comment: https://github.com/dbeaver/dbeaver/issues/5845#issuecomment-541593022

**Comment by rajeshisnepali** [comment]
@jaybeaton That's fine. But I don't recommend uninstalling the snap version & installing it from the site. I mean just look how easier snap has made to our apps (auto-update); they need to fix the problem (for the snap).

**Comment by lemosluan** [comment]
If someone want to use ssh keys with snap install, put the private_key on the snap directory - on ubuntu: `/home/your_user_dir_name/snap/dbeaver-ce/.ssh`. So, the dbeaver installation can read by key.
It worked for me. ;)

**Comment by rajeshisnepali** [comment]
@lemosluan I also had to do.

**Comment by alex789** [comment]
@lemosluan  - thanks, worked for me too

**Comment by Cognaiscance** [comment]
Thank you, putting it in the snap directory worked for me.

**Comment by JRRS1982** [comment]
Dont add your private ssh key to snap, where it could be sent to an app and made public. I don't think that is good practice.

**Comment by lemosluan** [comment]
> Dont add your private ssh key to snap, where it could be sent to an app and made public. I don't think that is good practice.

Thanks for you advise, brô. I made a specific ssh key for this purpose and its has as passphrase as well. But it is a serious thing to think. ;)

**Comment by sskharate** [comment]
This still an issue with latest 7.3 version installed using snap.

Uninstalling snap installation then re-install from https://dbeaver.io/download/ has worked with no more permission denied issue.

**Comment by guipassos** [comment]
Guys, I had the same problem on Ubuntu 20.04, so I needed to change the permissions of the dbeaver application as the image:
![Screenshot from 2021-02-08 13-10-55](https://user-images.githubusercontent.com/9012209/107247989-9fec0c00-6a10-11eb-9d1a-1490262bfa7a.png)

It worked for me

**Comment by rashidhussainshah** [comment]
in ubuntu open software store, open dbeaver and open file permissions and enable ssh-keys
![Screenshot from 2021-03-31 15-16-06](https://user-images.githubusercontent.com/39673127/113129408-49db5e00-9234-11eb-9867-468e098451e6.png)

**Comment by abkrim** [comment]
> If someone want to use ssh keys with snap install, put the private_key on the snap directory - on ubuntu: `/home/your_user_dir_name/snap/dbeaver-ce/.ssh`. So, the dbeaver installation can read the key. It worked for me. ;)

This works, but that is a very bad practice.

The real solution is to fix a permission problem (bug) that the application has.

Anyway, thanks for the tip, which is very common in other snap-based apps or cordova apps and the like, which requires the use of ssh keys.

**Comment by pouriamoosavi** [comment]
You can run this command in terminal to give dbeaver, access to ~/.ssh directory:
`sudo snap connect dbeaver-ce:ssh-keys`

This is equivalent to the gui method mentioned here

> Guys, I had the same problem on Ubuntu 20.04, so I needed to change the permissions of the dbeaver application as the image: ![Screenshot from 2021-02-08 13-10-55](https://user-images.githubusercontent.com/9012209/107247989-9fec0c00-6a10-11eb-9d1a-1490262bfa7a.png)
> 
> It worked for me
