### ISSUE TITLE
Change UI for multi-values filters

### ISSUE THREAD

**Issue by tati-kru** [dbeaver/dbeaver#7642]
1. Keep checked and unchecked values after search
2. Keep only one value panel
3. Keep only two buttons: Select all/none and Apply
4. Delete Cancel button and add Close button for dialog
5. Move the search panel to the top and add placeholder to the panel
6. Add search by numbers

**Comment by serge-rider** [comment]
Done.
Partially implemented in #6427

**Comment by uslss** [comment]
Verified
Keep checked and unchecked values after search - ok
Keep only one value panel - ok
Keep only two buttons: Select all/none and Apply - ok
Delete Cancel button and add Close button for dialog - ok
Move the search panel to the top and add placeholder to the panel - ok
Add search by numbers - ok
