### ISSUE TITLE
[PostgreSQL] Autocomplitition empty result (doesn't displays all columns of table)

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#7643]
#### System information: 
- Windows 7 Pro x64
- DBeaver 6.3.3
- No additional extensions

#### Connection specification:
- PostgreSQL 9.3
- PostgreSQL default driver (9.4.1212.jre7)
- No tunnels or proxies

#### Describe the problem you're observing:
"ctrl+space" doesn't displays all columns of table if table in not current schema

#### Steps to reproduce, if exist:
Typing query below.
```
select 
from oth_schema.some_table
```
Stay after select and press "ctrl+space". This method does not display all columns of the table. If i type any character - column names matching the character are returned.

**Comment by uslss** [comment]
Hi @ems2811 ,
if you want all columns to be shown, you should use query like:
```
select *
from oth_schema.some_table
```
and stay after * and press ctrl+space

**Comment by ems2811** [comment]
Hi @uslss ,
This method will replace the "*" character with all columns in the editor. I would like to see a list of all the columns in the modal window to select one, as happens when searching by coincidence like in screenshot.
![01](https://user-images.githubusercontent.com/22142845/72546784-71970e00-389c-11ea-9c6c-89e2a8a936a6.jpg)

**Comment by uslss** [comment]
oh, sorry, didn't catch you right.
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
