### ISSUE TITLE
Viewing BLOB fields

### ISSUE THREAD

**Issue by sigzero** [dbeaver/dbeaver#7645]
I am using DBeaver 6.3.1 64bit.

I am connecting to an Oracle 11g (11.2.0.4) database.

I am viewing a BLOB field using:

select id, utl_compress.lz_compress(XML) as XML from object;

That brings up the results and the XML column shows [BLOB]. If I click on some of them it expands to the contents of the BLOB field while others just remain [BLOB].

Something like this:

| ID  | XML                            |
-----------------------------
| 1   | <! -- member object   |     <--- this was [BLOB] until I clicked on it
-----------------------------
| 2  | [BLOB]                        |     <--- this does not expand when I click on it

If I open the VALUE viewer, I can see all of the XML for both.

Why does one expand and the other not?

**Comment by serge-rider** [comment]
You can change "Maximum LOB length to keep in memory" in preferences.
DBeaver shows LOBs shorter than this value inline.

![image](https://user-images.githubusercontent.com/6398845/72606858-7b6a5100-3930-11ea-84c3-74a630a7307c.png)

**Comment by sigzero** [comment]
You are a life saver.
