### ISSUE TITLE
Commit on exports

### ISSUE THREAD

**Issue by Ferrox12** [dbeaver/dbeaver#7646]
Hi,
is there a function to put a line with the instruction
commit;
on a large export maybe after some rows?

**Comment by serge-rider** [comment]
You can configure it for data import:
![image](https://user-images.githubusercontent.com/6398845/72606976-b7051b00-3930-11ea-94d2-1584442db8d1.png)

But what's the point of doing commit during export?

**Comment by Ferrox12** [comment]
I think it would be useful when you export a large amount of updates and then launch them in a separate SQL sheet.

Example:
SELECT 'UPDATE ...'
FROM...;
This query returns me 1000 update.
I think insert a commit every 100(for example) lines it's very usefull

**Comment by p91paul** [comment]
for your specific use case (1000 rows) I'd say committing every 100 is overkill.

Still, if the count rises to many thousands statements and/or you need to run the script on a different machine (e.g. on an isolated production database you can't connect from dbeaver), committing every x rows can save you from running out of undo space.
