### ISSUE TITLE
New Request : "Connect As"  Shortcut

### ISSUE THREAD

**Issue by sivaswami** [dbeaver/dbeaver#7647]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

I used to switch between users for a connection. It would be helpful if we have some shortcut/menu option to quickly change connection to new user

#### Steps to reproduce, if exist:
Right now the only option is hardcoded user and password in connection dialog.

**Comment by serge-rider** [comment]
Possibly can be done as an extension to #2092.

**Comment by E1izabeth** [comment]
It's possible using DBeaver profiles feature (available in DBeaver PRO) https://github.com/dbeaver/dbeaver/wiki/Authentication-DBeaver-profile
