### ISSUE TITLE
PostgreSQL Unterminated dollar quote started

### ISSUE THREAD

**Issue by PBekleshov** [dbeaver/dbeaver#7649]
System information:
Operating system (distribution) and version Windows 8.1
DBeaver version 6.3.2
Additional extensions
Connection specification:
Database name and version PostgreSQL 11.5
Driver name PostgreSQL JDBC Driver
Do you use tunnels or proxies (SSH, SOCKS, etc)?
Describe the problem you're observing:
Large procedures dos not compile
The problem with $$
Tries to work out part of the procedure and does not reach the closing $$

Steps to reproduce, if exist:

[p_report_not_payed_contracts.txt](https://github.com/dbeaver/dbeaver/files/4068975/p_report_not_payed_contracts.txt)

Include any warning/errors/backtraces from the logs
SQL Error [42601]: Unterminated dollar quote started at position 113 in SQL CREATE OR REPLACE PROCEDURE

**Comment by serge-rider** [comment]
Thank you for the details.
This problem was fixed in #7511
Please check the fix in the Early Access version.
