### ISSUE TITLE
bytes with default uuid_v4() 

### ISSUE THREAD

**Issue by mxwmwx** [dbeaver/dbeaver#7650]
Database: cockroach
add a default value uuid_v4() to the column which data type is bytes in order to create random id,
but in database,it shows this 
![image](https://user-images.githubusercontent.com/37258498/72487557-5f3fb480-3849-11ea-8d34-39eadef29065.png)
in Dbeaver it shows :
![image](https://user-images.githubusercontent.com/37258498/72487588-80a0a080-3849-11ea-9bb3-a1b8659dffcc.png)

**Comment by serge-rider** [comment]
You can use column format for this:
![image](https://user-images.githubusercontent.com/6398845/72587895-b1470f80-3907-11ea-85d2-7c3e6dfd6868.png)

We slightly changed context menu structure recently so it may be in a bit different place of it.
