### ISSUE TITLE
How to remove all the previous results before executing new statements.

### ISSUE THREAD

**Issue by nlpsuge** [dbeaver/dbeaver#7651]
#### System information: 
- Operating system (distribution) and version
Fedora 31
- DBeaver version
Version 6.3.2.202001051908
#### Connection specification:
- Database name and version
MySQL [5.6.32-78.0-log]
#### Describe your question:
I'm used to executing multiple statements via 'Execute - Execute Statements In Separate Tabs'. If I execute the same statements second time, the Tab name is xxx - N, N is a number like 2.

Old and new results both present in Results Panel, So I'm very confused which one is the result this time.

Is there any option to avoid this behaviour? I mean remove all the previous results before executing new statements.

**Comment by serge-rider** [comment]
It closes open tabs if you execute statements as script (<kbd>alt+x</kbd>).

`Execute Statements In Separate Tabs` is specially made to open results in new tabs always.

**Comment by nlpsuge** [comment]
Thank you @serge-rider , this is just what I need to learn.

I'll close this issue.

Thanks again.
