### ISSUE TITLE
Skip or merge on database export

### ISSUE THREAD

**Issue by jesperbruunhansen** [dbeaver/dbeaver#7652]
I'm using the Export Data for migrating an old database to a new, and during this process I have some records in the new database that already exists. When the process hits the record that already exists, it raises an Unique Constraint exception, and is giving me a popup where I can choose skip or ignore.

Is it possible for DBeaver to say "skip all" or "merge all" when such a constraint is met, so I don't have to make an active click every time it happens?

**Comment by genkadama** [comment]
i am very interested in this as well

**Comment by uslss** [comment]
already implemented
