### ISSUE TITLE
Authorization the use DBeaver in Trainning Academy

### ISSUE THREAD

**Issue by PJCAfonso** [dbeaver/dbeaver#7655]
Can we as a trainner use DBeaver in a Academy with my strudants?
Which email I must used to install in each machine? Mine ou other email?

Which computer on desk are used by several students, in this case is not clear to used personnal email?

Please can't you clarify what can we do to used your product?

Thanks in advance.

**Comment by tati-kru** [comment]
The standard Academic license is individual and cannot be used for workstations in Academy classes. If you want to use DBeaver in your university you need to send a request to support@dbeaver.com and ask a Group Academic license.
