### ISSUE TITLE
NPE appears in case of creating schema without owner chosen

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7656]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
NPE appears in case of creating schema without owner chosen
Try to create the schema and don't choose any owner - NPE appears

[npe_schema.log](https://github.com/dbeaver/dbeaver/files/4071550/npe_schema.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
