### ISSUE TITLE
NPE appears when open newly created schema

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7657]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
NPE appears when trying to open Tables folder in newly created schema
![image](https://user-images.githubusercontent.com/31996417/72530365-84471e00-386f-11ea-820e-78370609b016.png)
[npe_schema_new.log](https://github.com/dbeaver/dbeaver/files/4071594/npe_schema_new.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
