### ISSUE TITLE
Foreign Key Couldn't be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7658]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
An error appears when trying to create Foreign Key
#### Steps to reproduce, if exist:
Try to create FK from UI
[fail_fk.log](https://github.com/dbeaver/dbeaver/files/4071649/fail_fk.log)

![image](https://user-images.githubusercontent.com/31996417/72531082-0b48c600-3871-11ea-8837-a4fbeaa28526.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
