### ISSUE TITLE
Incorrect name is shown for newly created Partition Column

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7659]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
Incorrect name is shown for newly created Partition Column
![image](https://user-images.githubusercontent.com/31996417/72532196-421fdb80-3873-11ea-8fad-6c93f05fae78.png)

**Comment by serge-rider** [comment]
Fixed (partition column cannot be created for now)

**Comment by uslss** [comment]
verified
