### ISSUE TITLE
Partition Column Tab is shown incorrectly

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7660]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/31996417/72532446-b9556f80-3873-11ea-8b13-e8eaa2eb0f33.png)

**Comment by serge-rider** [comment]
Can't reproduce. Probably fixed in #7659
