### ISSUE TITLE
New view couldn't be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7662]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
Case 1:
When trying to create view using select statement like SELECT * FROM RETAIL.ARTICLE (it works in other dbs like postgresql, mysql) - it looks like view is saved, but it disappears after refresh
DDL on View Saving in mentioned case:
![image](https://user-images.githubusercontent.com/31996417/72534513-3afacc80-3877-11ea-9ab1-9d3fd625a9a7.png)
Case 2:
Create view using statement CREATE OR REPLACE VIEW my_view as SELECT * FROM RETAIL.ARTICLE ends with:
![image](https://user-images.githubusercontent.com/31996417/72534667-7ac1b400-3877-11ea-8524-618d9a2d9d7a.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
