### ISSUE TITLE
"Row colors..." setting is removed if Next page is fetched

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7663]
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:

"Row colors..." setting is removed if Next page is fetched

#### Steps to reproduce, if exist:
1. Open a table with several pages in Data Editor
2.  Set a gradient color for the whole table using"Row colors..." function
3. Press "Fetch Next page" btn/scroll down to the next page.

Actual result: Coloring is removed.

#### Include any warning/errors/backtraces from the logs
![G5Cqp0Tnxf](https://user-images.githubusercontent.com/51405061/72535497-af3e6b80-3889-11ea-9ebe-8963eb557b4d.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
