### ISSUE TITLE
Schema is created instead of Virtual Schema

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7664]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3
#### Connection specification:
- Database name and version Exasol
#### Describe the problem you're observing:
When I create schema using 'Create New Virtual Schema' it appears in Schema folder.
#### Steps to reproduce, if exist:
1. Choose Create New Virtual Schema in context menu
2. Choose owner and name - click OK
3. Check created object - it appears as usual Schema, not Virtual

**Comment by serge-rider** [comment]
Virtual schemas create not supported. We'll show proper error instead of wrong object create,

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/72733023-16b92b80-3ba8-11ea-824f-1b3d7a4e6bc1.png)
