### ISSUE TITLE
Comment couldn't be set for Exasol connection

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7665]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
If I change comment for already existing connection - it is always set to empty
Statement generated by Dbeaver is always **COMMENT ON CONNECTION TEST is '';** even if another value is used
![image](https://user-images.githubusercontent.com/31996417/72537069-7fdd2e00-388c-11ea-9c85-1b590578e851.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
