### ISSUE TITLE
Password for exasol connection is shown as is

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7666]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
When I create new connection user's password is shown as 'dots', but when the connection is saved it is shown as is
![image](https://user-images.githubusercontent.com/31996417/72537343-0a259200-388d-11ea-8977-4276bf55c4b1.png)

**Comment by serge-rider** [comment]
Fixed. We'll show passwords in a hidden form.

**Comment by uslss** [comment]
Reopened.
Password isn't shown as is.
But it disappears after Connection page refreshing

**Comment by serge-rider** [comment]
It is not a bug. We don't load passwords from database (they are visible only during after connection create or after password change).
