### ISSUE TITLE
Oracle Error ORA-12650

### ISSUE THREAD

**Issue by shortduck** [dbeaver/dbeaver#7668]
#### System information: 
- Operating system (distribution) and version : Win 10 Enterprise
- DBeaver version: Version 6.3.2.202001051908

#### Connection specification:
- Database name and version: Oracle 11, 

#### Describe your question:

I have just started learning using DBeaver,

I can do a successful connection using TOAD, however I get this error while connecting to DBeaver : Io exception: Oracle Error ORA-12650

I am adding screen shot of TOAD for your reference: Here DBA_LAMDA is the schema name. Can you please look into this and let me know what could be causing this issue ?

![image](https://user-images.githubusercontent.com/5105356/72538215-78e1fb80-384b-11ea-8970-384a12b3bec6.png)

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer. Is it still actual for you?

**Comment by p91paul** [comment]
Are you using TNS LDAP resolution? Dbeaver apparently does not support that, you should provide hostname + port + service_name/sid. tnsping will give you the information you need.

**Comment by shortduck** [comment]
Hello Thanks for your time and response.

I am getting the following issue:
[image: image.png]
and here are my settings:

[image: image.png]
Can you please see whats going on?


Thanks
Ankit Bhurat

**Comment by shortduck** [comment]
Hello

Please ignore my previous email, I was able to connect it this time.

However, when I try to execute the SQL, I am getting error as: SQL Error
[942] [42000]: ORA-00942: table or view does not exist

Although, I can execute the same sql in TOAD. This table is under a
particular schema:
I tried the following:
select * from DBA_LAMDA.PARCEL_INVOLVED_PARTY



Thanks
Ankit Bhurat

**Comment by kseniiaguzeeva** [comment]
Could you try the latest version https://dbeaver.io/?
I can't reproduce the issue.

**Comment by uslss** [comment]
there are not any updates on issue for a long time.
ticket closed. If the issue is still reproducible for you - feel free to reopen the ticket
