### ISSUE TITLE
"Edit cell value in separate dialogue" function does not work properly

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7669]
## System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.3

#### Describe the problem you're observing:
"Edit cell value in separate dialogue" function stops working for Varchar type if you press it second time.

#### Steps to reproduce, if exist:
1. Open a table in Data Editor
2. Select a cell with VARCHAR value in the table and open a separate dialogue window to edit it using "Edit cell value in separate dialogue" function.
3. Close the window
4. Try to repeat step 2.

Actual result:
-Error window appears "An internal error has occurred. Argument not valid" instead of  Edit Dialogue.

#### Include any warning/errors/backtraces from the logs
![WyiQfbT4Yw](https://user-images.githubusercontent.com/51405061/72543330-9e482700-3896-11ea-9e9d-f4c0f702f09d.gif)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4072376/dbeaver-debug.log)
[.log](https://github.com/dbeaver/dbeaver/files/4072379/default.log)

**Comment by serge-rider** [comment]
This error was caused by incorrect Hex editor colors dispose. It was broken in #7535

**Comment by kseniiaguzeeva** [comment]
Verified
