### ISSUE TITLE
[MySQL] It is not offered to define Virtual Keys

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7670]
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
Window with proposal to define Virtual Keys doesn't appear 

#### Steps to reproduce, if exist:
1. Create a table with some content without primary/unique/virtual key
2. Reopen the table
3. Make any changes
4. Save the changes

Actual result: 
-The table is saved
-No window appears to define Virtual Keys
![Virtual-key-warning](https://user-images.githubusercontent.com/51405061/72548724-529a7b00-38a0-11ea-9714-7670e9937f5d.png)

**Comment by serge-rider** [comment]
Can't reproduce.

@kseniiaguzeeva Please check what key (which columns) where used yo update the table (you can see it in Query Manager view).
Perhaps there was virtual unique key defined for the table with the same name previously. You can check it in virtual keys editor.
If so then we have another bug - we need to delete logical keys (and all other virtual properties) when we drop table(s).

**Comment by kseniiaguzeeva** [comment]
Now I know it is for line deleting/editing only. Thank you for your advice!

**Comment by mndree** [comment]
how do i change the virtual keys ?? 
this documentation doesnt help at all 

https://dbeaver.com/docs/dbeaver/Data-Viewing-and-Editing/
