### ISSUE TITLE
Calculate total row count - result truncated

### ISSUE THREAD

**Issue by bozo16** [dbeaver/dbeaver#7672]
Double-click on a table with 292,408 rows; on the data tab click on Calculate total row count at the bottom and I get 292,40 - result has right side truncated - might've been 292,400,000 etc.?
DBeaver Version 6.3.0.201912042122
Connecting to Microsoft SQL Azure 12.0.2000.8
Windows 10 Enterprise Version	10.0.17763 Build 17763

**Comment by uslss** [comment]
Hi @bozo16 ,
could you add a screenshot? BTW, what is your screen resolution?
Thanks in advance

**Comment by bozo16** [comment]
![image](https://user-images.githubusercontent.com/47603510/72795948-634b4800-3c36-11ea-92a5-6d4a8fa1ede4.png)
If I double-click on the count I get
![image](https://user-images.githubusercontent.com/47603510/72796057-94c41380-3c36-11ea-9372-9a6a0227cff1.png)

My screen resolution is 3840 x 2160

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed (row count control now resizes on update)

**Comment by kseniiaguzeeva** [comment]
verified
