### ISSUE TITLE
Adding a blank line to a query causes the query to error

### ISSUE THREAD

**Issue by Izzzzy** [dbeaver/dbeaver#7674]
When running query (without highlighting what to run - meaning all the text in the editor), this
 ```
SELECT * 

FROM categories c2
```
 fails

Unlike 
```
SELECT * 
FROM categories c2
``` 
which does not.

**Comment by uslss** [comment]
Hi @Izzzzy ,
probably you've got 'Blank line is statement delimiter option enabled'
![image](https://user-images.githubusercontent.com/31996417/72625107-3575b300-3959-11ea-9409-579fb8ede299.png)

**Comment by Izzzzy** [comment]
Thank you @uslss !
