### ISSUE TITLE
Informix 14.10 doesn't expand table tree

### ISSUE THREAD

**Issue by ceinmart** [dbeaver/dbeaver#7675]
#### System information: 
- **Windows 8** 
- DBeaver version **6.3.2**

#### Connection specification:
- Database **Informix 14.10.FC3**
- Driver name **Informix JDBC 4.10 , 4.50 , etc...**
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  **No**

#### Describe the problem you're observing:
Unable to expand the objects over the object tree
#### Steps to reproduce, if exist:
Over the object tree, when click to expand the list of tables, only appear "(...)" and stay over there. 
The little rolling image doesn't appear.

The same version/drivers work fine over Informix 12.10.

#### Include any warning/errors/backtraces from the logs
No log is updated at **%appdata%\DBeaverData\workspace6\.metadata** , so there is no log include here....

![screenshot](https://i.imgur.com/B8ZS7xy.jpg)

**Comment by uslss** [comment]
Hi @ceinmart ,
probably you've got some incorrectly configured filter enable for Tables folder.
In this case it works like you describe or me
![image](https://user-images.githubusercontent.com/31996417/72630302-17ad4b80-3963-11ea-8ba5-252e8c8402c2.png)

**Comment by ceinmart** [comment]
ouch!!! you are right!!! 
I forgot a filter there from weeks ago... 

Should help if they show "(filtered)" when having a filter active.
