### ISSUE TITLE
Default Schema not working 6.3.2

### ISSUE THREAD

**Issue by mikkk3l** [dbeaver/dbeaver#7679]
#### System information: 
- Operating system (distribution) and version. Windows 10
- DBeaver version: 6.3.2
- Java version: 
1.8.0_231 64 bit
- Additional extensions

#### Connection specification:
- Database name and version
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
- Driver name
ojdbc7.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

I select a default schema in the connection / Initialization / Default schema and in the dropdown menu of the editor called "Active catalog/schema" it is not automaticallý loaded. Each time I connect I have to select the default schema in the ""Active catalog/schema" combo again. In 6.2.1 it worked like a charm.
It happens both in oracle and ibm db2. I haven´t tried with other databases.

**Comment by serge-rider** [comment]
Since 6.3.2 each SQL editor has its own default schema (it can be changed in the main toolbar).
You can set default schema in connection properties (tab "Initialization").

Also we will add per-editor active schema save feature (see #7638)

**Comment by mikkk3l** [comment]
Thank you, Serge. You're a master!

**Comment by Pebaar** [comment]
The default schema in connection properties (tab "Initialization") does not seem to propagate in 6.3.3
The editor loads with no schema selected even though the connection has a default schema defined.

**Comment by mikkk3l** [comment]
It does not work. I attach a gif.
![2020-02-24_dbeaver_schema_db2_not_working](https://user-images.githubusercontent.com/15341836/75674321-1cb12a80-5c85-11ea-8796-e37dad262f37.gif)
