### ISSUE TITLE
Unexpected driver error occurred while connecting to the database

### ISSUE THREAD

**Issue by krsbalu** [dbeaver/dbeaver#7683]
Hello Team , the above error comes each time whenever i try to create a new connection with postgresql driver . whet ever i do i couldn't succeed with new connection.

I followed many steps suggested online and in this support area but no luck in resolving the issue.

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Hi @krsbalu ,
could you post some additional info (like screenshots or video, error stacktrace) that could help to reproduce an issue?

**Comment by krsbalu** [comment]
![Screen Shot 2020-01-19 at 12 08 35](https://user-images.githubusercontent.com/25248552/72749459-23597600-3be0-11ea-9888-26fd1e4897f6.jpg)

**Comment by krsbalu** [comment]
![Screen Shot 2020-01-20 at 23 51 09](https://user-images.githubusercontent.com/25248552/72749524-4b48d980-3be0-11ea-91c1-e0225a9b28b3.jpg)

**Comment by dorbae** [comment]
Hi @krsbalu !
How about trying to check whether the connector(TCP) of your database is working?

Try like this

1. Open CMD or terminal
2. telnet [Database Host] [Database Port]

If you could not connect it by telnet, please check the status of your database again. Thank you.

**Comment by krsbalu** [comment]
I could establish connection through command line using psql.. No issue in
this. I feel it's taking my existing  ssl connections even when I try to
create new one.

**Comment by uslss** [comment]
@krsbalu is there anything in log file?
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by krsbalu** [comment]
i have uploaded the logs, this is something driver is not accetping non SSL connections


[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4151658/dbeaver-debug.log)

[log.log](https://github.com/dbeaver/dbeaver/files/4151664/log.log)

**Comment by uslss** [comment]
@krsbalu is it still actual for you?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it.

**Comment by krsbalu** [comment]
It's resolved.... For now
