### ISSUE TITLE
Incorrect Status details values

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7684]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Describe the problem you're observing:
1. Incorrect value is shown for queries that weren't executed. In the mentioned case I didn't insert or delete any values but number of this operation is -1, not zero.
2. Number of updated values isn't shown
![image](https://user-images.githubusercontent.com/31996417/72680915-07ff4580-3ad0-11ea-8ab3-299712de006a.png)

**Comment by serge-rider** [comment]
Fixed (we'll show `N/A` instead of -1)

**Comment by uslss** [comment]
verified
