### ISSUE TITLE
New Tables couldn't be added to existing task

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7685]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Describe the problem you're observing:
When I trying to add a table to existing task - it couldn't be done
#### Steps to reproduce, if exist:
1. Create Task
2. Start Edit task and add table to it
3. Click Next button - Source type screen is empty
![image](https://user-images.githubusercontent.com/31996417/72681667-d178f900-3ad6-11ea-9cbd-e1a070c14c58.png)
[taskediting.log](https://github.com/dbeaver/dbeaver/files/4082706/taskediting.log)

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D71](https://dbeaver.testquality.com/project/8805/result/1782037/defect/6171). Do not remove or edit.

**Comment by serge-rider** [comment]
Fixed. I had to redo task UI configurator. A few other bugs were fixed (including data import configurator)

Please test data transfer + data transfer tasks in different combinations.
Export
  - To table
  - To file
  - From table
  - From query
Import
  - From table
  - From file

+ Task export/import reconfiguration

**Comment by uslss** [comment]
Verified
Export
- To table - ok
- To file - ok
- From table - ok
- From query - ok

Import
- From table - ok
- From file - ok

Task export/import reconfiguration - created issue #7715
