### ISSUE TITLE
Snowflake: cannot save created index

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7687]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version Snowflake

#### Describe the problem you're observing
Error appears when trying to save new index

```

> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.jkiss.dbeaver.model
> Error
> Sun Jan 19 16:47:44 MSK 2020
> SQL Error [1003] [42000]: SQL compilation error:
> syntax error line 1 at position 7 unexpected 'INDEX'.

```

**Comment by serge-rider** [comment]
Snowflake doesn't support indexes. Removing them from navigator.

**Comment by uslss** [comment]
verified
