### ISSUE TITLE
Incorrect strings for description are used in Select dashboard database window

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7691]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/31996417/72684023-0775a780-3aee-11ea-9a71-72b1daf3a7dd.png)
![image](https://user-images.githubusercontent.com/31996417/72684038-30963800-3aee-11ea-8f0e-b7ead6093ba0.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
