### ISSUE TITLE
"Select all Rows"  does not work.

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#7694]
**System Information:**
- Operation System
  Windows 10
- DBeaver version
   6.3.3
- Additional extensions
  No

**Connection specification:**
- Database name and version
  Oracle 12c
- Driver name
  Oracle JDBC Driver
- Do you use tunnels or Proxies(SSH, SOCKS, etc) ?
  No

A doesn't work after upgrading DBeaver 6.3.3.
Not working when using "bind Parameter" with "With" keyword.

For example
**Select all Rows Not Executed**
> WITH test AS
> (
>     SELECT rownum 
>       FROM dict 
>      WHERE rownum < :rownum
> )
> SELECT * 
>   FROM test
> ;

**Select all Rows Executed**

> WITH test AS
> (
>     SELECT rownum 
>       FROM dict 
>      WHERE rownum < 500
> )
> SELECT * 
>   FROM test
> ;
> 

Thanks for reading.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
I can't reproduce this..

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
