### ISSUE TITLE
Unable to sorl last column in Data view [GUI]

### ISSUE THREAD

**Issue by fxc1** [dbeaver/dbeaver#7695]
#### System information: 
- Operating system (distribution) and version
Xubuntu 18.04 / xfce
- DBeaver version
6.3.3
- Additional extensions
No

#### Describe the problem you're observing:
When I try to sort last column in Data view, sidebar is onverlaying filter and sort icons.

![image](https://user-images.githubusercontent.com/44489672/72712922-582be580-3b6c-11ea-9af8-f707c665c82d.png)

#### Steps to reproduce, if exist:
In description...

Thanks.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
