### ISSUE TITLE
Batch data transfer. Multiple rows per INSERT.

### ISSUE THREAD

**Issue by somsomers** [dbeaver/dbeaver#7696]
Hello. 

How about create an option for using multiple rows with per INSERT statement during table transfer to another database? That would speed up transfer exponentially. I know, there may be issues with DEFAULT values and triggers, but it would be just an option for those, who know the risks.
I use some app that transfers tables with bulk INSERTs and it is about 10 times faster, then DBeaver's transfer.
Thank you.

**Comment by mkgrgis** [comment]
xf:datatransfer ?

**Comment by somsomers** [comment]
Sorry. By "data transfer" I mean export table/tables to another database. When you have move/copy 1000k row table it takes forever, because DBeaver send one INSERT query per exported row. But it could  send "INSERT INTO table_name (column1, column2) VALUES (value1, value2), (value3, value4), etc ...;"

**Comment by mkgrgis** [comment]
There is group INSERT by your count
Table->export data -> SQL format -> next
![изображение](https://user-images.githubusercontent.com/41448637/73135863-6db37a80-4058-11ea-9b80-ab533935fc70.png)

**Comment by somsomers** [comment]
Yes, I know about that one. But you have to 
1) export to SQL
2) pack it
3) upload it
4) unpack on destination server
5) finally import
Not that simple, right? (:

I talk about Table->Export data->Database.
I've even looked through the source code. I does send rows one by one in anyway. Maybe it is a driver restriction. Hope not.

**Comment by mkgrgis** [comment]
This mechanism will be useful. It seems there is not some restriction by jdbc drivers.

**Comment by uslss** [comment]
![image](https://user-images.githubusercontent.com/31996417/162735737-5eed9a29-1464-43b3-869e-b78f78c30097.png)
already implemented in 22.0.1
