### ISSUE TITLE
horizontal scrolling with "shift+mouse-scroll" in a data grid doesn't go completely left or right

### ISSUE THREAD

**Issue by wim154** [dbeaver/dbeaver#7697]
Hi,

First, thank you for making and supporting dbeaver, it is a great tool for database exploration & management. I like to share the following observation, perhaps bug.

When I work with dbeaver in Ubuntu 18.04, I noticed that horizontal scrolling in a data grid with "shift+mouse-scroll" doesn't go completely left or right. See  ![ubu18 04-horscrollbar-issue](https://user-images.githubusercontent.com/44837739/72722003-9bdb1b00-3b7d-11ea-9952-43a2ffa4dbde.png) as illustration.  The hor scrollbar does not go into the yellow highlighted zone.  A bit annoying when you have to see the last or first column and have to use another method than "shift+mouse-scroll".

However, when I logged into my Ubuntu 18.04 with Wayland (is option in the login screen) the "shift+mouse-scroll" method worked perfectly like it should. See ![ubu18 04-horscrollbar-no-issue-wayland](https://user-images.githubusercontent.com/44837739/72722060-c036f780-3b7d-11ea-96af-2a92091ffcfe.png)  as illustration. Where you see that the hor scrollbar does go into the yellow highlighted zone so one can see the last column.

Of course, this is about a table grid with more columns than can fit on one screen, otherwise, we don't need a hor scrollbar. It would be nice if the hor scrollbar with "shift+mouse-scroll" worked fine in both environments - if it is something dbeaver can fix of course.

**Comment by uslss** [comment]
similar to #8209
