### ISSUE TITLE
ORA-00933:SQL command not properly ended with CASE..END expression in statement

### ISSUE THREAD

**Issue by fniessen** [dbeaver/dbeaver#7701]
First of all, thank you for this great, great, great tool.  The fact I can use the same tool to connect to MS SQL Server and Oracle, and that I can use templates, is simply magic!

#### System information: 
- Windows 10 Pro
- DBeaver version 6.3.3.202001140839
- No additional extensions

#### Connection specification:
- Database name and version: Oracle 12c
- Driver name: ojdbc7.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No: everything local on my machine

#### Describe the problem you're observing:
Running the request:

SELECT
    pct_id,
    CASE
        WHEN bl_id IS NOT NULL
        THEN bl_id
        ELSE 'bl was null'
    END                                 AS bl_truc,
    user_name
FROM rmpct;

returns:

ORA-00933:SQL command not properly ended

This is "because" of the CASE..END expression; without it, it does work...

(I've also noted that, for Oracle, the CASE..END couldn't be the last expression in the SELECT list: sometimes, I do have to add a string before the FROM for the request to be correctly parsed.

#### Steps to reproduce, if exist:
Put the above request in the editor, and run it with Alt-x.

#### Include any warning/errors/backtraces from the logs

Error ORA-00933:SQL command not properly ended

**Comment by uslss** [comment]
thanks for the bug report

**Comment by shintakezou** [comment]
Some more test maybe useful to identify the issue (DBeaver 6.3.3.202001191557 on Windows)

```
SELECT 
   CASE WHEN 'a' = 'b' THEN 'eq'
        WHEN 'c' = 'c' THEN '='
        ELSE 'fi' end
FROM dual;
```

This is fine as long as `end` stay **lowercase**. In the moment it's been made all uppercase,  I obtain 

    SQL Error [911] [22019]: ORA-00911: invalid character

**Comment by fniessen** [comment]
Dear @shintakezou,

Wouw, you found it…

Executing your version of the code does return '='.

Executing the same code, but with 'END' uppercased, returns 'SQL Error [933] [42000]: ORA-00933: la commande SQL ne se termine pas correctement'.

**Comment by shintakezou** [comment]
To be more precise, it gives error only if it is all uppercase; `End`, `ENd`, `eND`, ... all seems fine.

**Comment by fniessen** [comment]
And this bug must be rather new, because I don't think I had it with 6.3.2 - and positive about 6.3.1.

I'm reusing the same SQL code over and over, well sometimes in SQL Server, and sometimes in Oracle.

**Comment by speedyflipper** [comment]
It does not effect 6.3.2. I reverted back to 6.3.2 to avoid changing my code

**Comment by Jthovn** [comment]
speedyflipper, how did you revert back?

**Comment by speedyflipper** [comment]
I use the portable version and just removed 6.3.3 and unzipped 6.3.2

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
