### ISSUE TITLE
Separate sessions for Database Navigator is a regression for role-dependent users

### ISSUE THREAD

**Issue by spkendall** [dbeaver/dbeaver#7705]
#### System information: 
- Operating system (distribution) and version
Observed on Windows and Mac
- DBeaver version
6.3.3
- Additional extensions

#### Connection specification:
- Database name and version
PostgreSQL 10.6 (RDS)
- Driver name
JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
Under previous versions, users could keep "Open separate connection for each editor" unchecked, and then do their `set role ... ;` in SQL Editor and Set Active in Database Navigator to get full power to work in that database as that role. Now that Database Navigator always has its own connection(s) to the database, that isn't possible anymore in Navigator.

Example environment (fictional names, but this describes a real production environment):
* Production instance databases
** `shoe` database (role `shoe` owns all schemas and objects)
** `boot` database (role `boot` owns all schemas and objects)
* Production instance users
** `asmith` (granted role `boot`, and option NOINHERIT)
** `bjones` (granted roles `shoe` and `boot`, and option NOINHERIT)

Under previous versions, users could keep "Open separate connection for each editor" unchecked, and then do their `set role ... ;` in SQL Editor and Set Active in Database Navigator to get power to work in a database as the role that owns objects in the databases they are assigned to.

In the example database above, `bjones` can connect to to the instance and set the shoe database active in Database Navigator, then run `set role shoe ;` in the SQL Editor, and can now create objects and change data in that database.

Now that 6.3.3 has made the Database Navigator connections totally separate from the SQL Editor, no matter how the checkbox is set, there is no obvious way to run `set role ... ;` for the Database Navigator's connection. Now the Navigator can often not access objects in the databases, since that requires the privileges of the assumed role; the users can't access them by default.

(This security model is needed so that each user can only access their assigned database or databases, and so that users don't create objects owned by their username in databases that no other normal user can access.)

#### Steps to reproduce, if exist:
See above.

#### Include any warning/errors/backtraces from the logs
This is a feature regression. No warnings/errors/backtraces are generated.

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on issue.
If it is still actual - feel free to reopen it
