### ISSUE TITLE
PostgreSql support for Stored Procedures not showing up

### ISSUE THREAD

**Issue by scottprugh** [dbeaver/dbeaver#7709]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: Version 6.3.0.201912081940

#### Connection specification:
- Database name and version: 
PostgreSQL JDBC Driver PG 
PostgreSql version 11.6

#### Describe your question:
According to https://github.com/dbeaver/dbeaver/issues/4446 stored proc support was implemented.  But in the current version of DBeaver I cannot get the Procedures node to show up.

This is what DBeaver looks like:
![image](https://user-images.githubusercontent.com/7747695/72816062-3cd4df00-3c2d-11ea-9ca0-300771889b87.png)

In pgAdmin4 it looks like this:
![image](https://user-images.githubusercontent.com/7747695/72816146-59711700-3c2d-11ea-9e87-2bb19b536a9f.png)

Are there other settings that need to be configured?  Thanks.

**Comment by scottprugh** [comment]
Nevermind.  I see that procs come underneath the Functions node.

**Comment by Chealer** [comment]
So, to clarify, it is possible to create stored procedures using DBeaver's GUI; however, one needs to use "Create Function" to achieve that. I am far from mastering PostgreSQL and stored procedures, but given that starting from PostgreSQL 11 stored procedures have a specific syntax (CREATE [ OR REPLACE ] PROCEDURE), my impression is that stored procedures should no longer be considered functions, and therefore, should have a specific group like in pgAdmin.
