### ISSUE TITLE
View is outdated (stale cache) until manual refresh or program restart (PostgreSQL)

### ISSUE THREAD

**Issue by Chealer** [dbeaver/dbeaver#7710]
#### System information: 
- Windows 8
- DBeaver 6.3.3
- No additional extensions

#### Connection specification:
- PostgreSQL 10.10
- PostgreSQL JDBC Driver
- No tunnels or proxies

#### Describe the problem you're observing:
A query modified my _msp_masas_alertage_regions_v_ view while I was viewing its source in Eclipse. When I closed and reopened the view to see the new source, the old source showed. This continued for several minutes, until I closed Eclipse to restart it.

I reproduced this the very next time I did the same using DBeaver itself (not Eclipse), also at version 6.3.3.

#### Include any warning/errors/backtraces from the logs
None relevant

**Comment by p91paul** [comment]
did you try pressing F5 while on the view source to refresh it?

**Comment by Chealer** [comment]
> 
> 
> did you try pressing F5 while on the view source to refresh it?

Thank you @p91paul 

The Refresh action (which can be invoked either using the File menu or pressing F5) works around this.

**Comment by Chealer** [comment]
This persists in 7.0.4. Materialized views are also affected.

**Comment by uslss** [comment]
cannot reproduce it for now.

**Comment by Chealer** [comment]
This unfortunately persists in 21.1.4. Why is this ticket closed?

**Comment by Chealer** [comment]
@uslss thanks for reopening this ticket
