### ISSUE TITLE
keyboard shortcut "ctrl+shift+A" Removed ?

### ISSUE THREAD

**Issue by rafaelsplinter** [dbeaver/dbeaver#7713]
System information:

    Operating system (distribution) and version
    Ubuntu 18.04
    DBeaver version
     6.3.3.202001191557
    Additional extensions
    dark theme
Connection specification:

    Database name and version
    PostgreSQL 10.6 (RDS)
    Driver name
    JDBC

Describe the problem you're observing:
shortcut ctrl + shift + A to change active database has been discontinued?

doesn't work anymore.

**Comment by nicchristeller** [comment]
See #7638
