### ISSUE TITLE
UI Bug: Column sorting arrows in Record mode, go missing

### ISSUE THREAD

**Issue by bobbyphilip** [dbeaver/dbeaver#7714]
#### System information: 
- Debian 9.11
- 6.3.3
- 1.8.0_232

#### Describe the problem you're observing:
  In Record view mode, the column sorting arrows go missing after entering grid mode from the text mode

#### Steps to reproduce, if exist:
1. Switch to record View
2. Grid mode is selected by default, on top of the column names, up/down arrows are visible to sort the column names
3. Click on Text to show query results as formatted text
4. Click on Grid, up/down arrows are no longer visible.

**Comment by uslss** [comment]
Thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
