### ISSUE TITLE
Export from different PG databases in a single task.

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7715]
#### System information: 
- Operating system (distribution) and version win 10x64
- DBeaver version 6.3.4

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
If I try to add a query to existing export task it is always associated with default schema
#### Steps to reproduce, if exist:
1. Create task with export from query from non-default db.
2. Execute task - query results are successfully exported
3. Add another query to the task - the table from task is looked for in default db, first query is successfully executed and exported.

**Comment by serge-rider** [comment]
I assume you mean PostgreSQL.
You can't mix queries from different databases there. Because they require different connections and can't be specified as table FQN.
So this is a kind of dbeaver limitation for now.
