### ISSUE TITLE
Cannot edit cell content with double click and inline editor

### ISSUE THREAD

**Issue by nmoreaud** [dbeaver/dbeaver#7716]
#### System information: 
- Ubuntu 19.04, Wayland, gnome shell with some extensions
- DBeaver Version 6.3.3.202001191557

#### Connection specification:
- Postgres

#### Describe the problem you're observing:
Open a table data
**Double click on a cell : the inline editor pops and disappears instantly.**
Press "enter" : I can edit the cell
Change editor in Preferences>DBeaver>Edoitors>Results>Presentation>Double click behaviour : set "Editor" : the double click works again (opens an editor popup).

**Comment by dirkesquire** [comment]
Maybe the same issue as #7597

**Comment by uslss** [comment]
cannot reproduce it against 7.0.1 on Ubuntu 19.04.
is it still actual for you?

**Comment by nmoreaud** [comment]
I just upgraded, the glitch is still here.
I have Wayland enabled, you can choose it in the session selector.
I have gnome shell "dash to panel" extension, but I guess it doesn't matter.
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.119.04, mixed mode, sharing)

**Comment by uslss** [comment]
duplicates #5322
