### ISSUE TITLE
Selecting "Read data in SQL console" on a table opens a query set to a different schema

### ISSUE THREAD

**Issue by gustavbertram-prodigyfinance** [dbeaver/dbeaver#7717]
#### System information: 
- MacOS 10.14.6
- DBeaver version: 6.3.3
- Additional extensions

#### Connection specification:
- Database name and version: Postgres 12

#### Describe the problem you're observing:
When I click "Read data in SQL console" on a table, it opens the query set to a different schema.

#### Steps to reproduce, if exist:
1. Default schema is postgres. (Not sure how to change anymore.)
2. Open "other_database.public" schema in the database navigator
3. Left click on any table
4. Select "Read data in SQL console"
5. See the error "SQL Error [42P01]: ERROR: relation "public.table" does not exist" because the query editor is still pointing to the "postgres.public" default schema instead of "other_database.public".

#### Include any warning/errors/backtraces from the logs

SQL Error [42P01]: ERROR: relation "public.table" does not exist

**Comment by serge-rider** [comment]
Fixed in #4792

**Comment by uslss** [comment]
verified
