### ISSUE TITLE
Dbeaver 6.3.3 - Postgres Backup - Selection of Tables for Backup Not Working

### ISSUE THREAD

**Issue by igormorse** [dbeaver/dbeaver#7718]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.3.3
- Additional extensions: None

#### Connection specification:
- Database name and version: Postgres 11
- Driver name: PG11
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : Yes

#### Describe the problem you're observing:

When you are going to Backup the Entire Database, Unmarking some tables from the list does not except them for Backup and instead Dbeaver Backups the entire database.

#### Steps to reproduce, if exist:

Tools -> Backup -> Select Schema -> Unselect Some Tables -> Look Dbeaver Calling pg_backup without ignoring the tables you told to

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by serge-rider** [comment]
Fixed.
@kseniiaguzeeva please test full schema damp too

**Comment by kseniiaguzeeva** [comment]
NPE appears after pressing "Start" btn for full schema backup.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
works for an active schema only.

**Comment by serge-rider** [comment]
@kseniiaguzeeva please retest in the latest EA

**Comment by kseniiaguzeeva** [comment]
Verified
