### ISSUE TITLE
dbeaver Version 6.3.3.202001191557 ORA-00933: SQL command not properly ended (Case Statements)

### ISSUE THREAD

**Issue by Jthovn** [dbeaver/dbeaver#7720]
#### System information: 
- Windows 10 Enterprise x64
- dbeaver Version 6.3.3.202001191557

#### Describe the problem you're observing:
When executing scripts with Case Statements, the following SQL Error is returned.
- ORA-00933: SQL command not properly ended

The same scripts work in older versions of dbeaver and SQL Developer with no error.

**Comment by uslss** [comment]
seems that issue duplicates #7701
