### ISSUE TITLE
DBeaver CE UWP Java heap

### ISSUE THREAD

**Issue by zlobby** [dbeaver/dbeaver#7722]
DBeaver CE UWP (Windows 10 Store) won't expose settings to increase Java heap size, and often DBeaver runs out of heap space.

In the 'Configuration' menu I'm getting these settings:
```
C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_6.3.0.0_x64__1b7tdvn0p0f9y\\plugins/org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar
--launcher.overrideVmargs
-nl
en
-nl
en
-vm
C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_6.3.0.0_x64__1b7tdvn0p0f9y\jre\bin\server\jvm.dll
eclipse.home.location=file:/C:/Program Files/WindowsApps/DBeaverCorp.DBeaverCE_6.3.0.0_x64__1b7tdvn0p0f9y/
eclipse.launcher=C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_6.3.0.0_x64__1b7tdvn0p0f9y\dbeaver.exe
eclipse.launcher.name=Dbeaver
eclipse.p2.data.area=@config.dir/../p2
eclipse.p2.profile=DefaultProfile
eclipse.product=org.jkiss.dbeaver.core.application.appstore
eclipse.startTime=1579722074465
eclipse.stateSaveDelayInterval=30000
eclipse.vm=C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_6.3.0.0_x64__1b7tdvn0p0f9y\jre\bin\server\jvm.dll
eclipse.vmargs=-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx1024m
```
The '-Xmx1024m' is visible only in the export and nowhere else, as least as far as I could see.

Any options to change the '-Xmx' setting?

**Comment by serge-rider** [comment]
This option is in dbeaver.ini file. I'm not sure that it is possible to change it contents in case of Windows Store application..

**Comment by zlobby** [comment]
Hello Serge!

I can easily navigate to the dbeaver.ini file and change its permissions, just to be able to modify it.

Sadly, this is not the case on boxes where I don't have administrator rights. On these boxes I can't even open the folder as Windows is barking with 'Access denied' stuff... :`(

I'd like to kindly request a feature where these options are available for modification through DBeaver itself. You know, some tiny, itsy-bitsy field in the 'Settings' dialog, which once applied will simply modify the dbeaver.ini file for me.

Please consider it as it's a huge show-stopper for cases where users don't have administrator rights and only Windows Store apps are allowed. I don't think it's really that hard to implement. :P

Thanks a bunch in advance!
