### ISSUE TITLE
CSV mapping ignored and entered in CSV header order

### ISSUE THREAD

**Issue by ggjersund** [dbeaver/dbeaver#7725]
#### System information: 
- Ubuntu 18.04.3 LTS
- DBeaver 6.3.3.202001191557

#### Connection specification:
- Local MySQL database
- com.mysql.jdbc.Driver

#### Describe the problem you're observing:
Mappings for CSV import does not work. The CSV order overrides the mapping. In my case the columns in the CSV are: `id, cid, ip_from, ip_to` and the DB columns are `id, ip_from, ip_to, cid`. The mapping wont go in the correct order.

#### Steps to reproduce, if exist:

Import a CSV with different order than that of the table?

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by patrickmdnet** [comment]
I can reproduce in 6.3.4 Community.  This bug does not happen in 6.3.3 EE.

System information:
- Windows 10 x64
- 6.3.4.202001291506

Connection specification:
- SQLLite (org.xerial.sqlite-jdbc:RELEASE)

To repro, make a small CSV and call it "sample.csv"

```
"ID",Visits,"Location"
"00123",1123,"Many Places"
"132567",1213,"Tinseltown"
"00999",3333,"LAX"
```

Make a tiny SQLite DB (or whatever DB, it doesn't matter) where the order of the first two columns is swapped:

```
# sqlite script to create table for sample.csv
# sqlite-tools-win32-x86-3310100\sqlite3 < sample.sqllite
create table sample(visits int, id varchar(10), location varchar(20));
.save sample.db
.quit
```

1. In DBeaver, connect to the SQLlite DB. 
2. Choose "Import Data" for the SQLLite table `sample`.  
3. At "Source type and format", choose CSV then Next
4. At "Input file(s)", choose "sample.csv", then Next
5. At "Settings (Files to Database, CSV") choose Next
6. At Preview Data Import, set `visits` to be bound to `ID`, and `id` to be bound to `Visits`.  You will notice that the "Preview data" pane doesn't change in order.  On 6.3.3 EE the preview pane does change.  So the bad behavior is here, somewhere.

![image](https://user-images.githubusercontent.com/858798/73487096-4fa98b00-4374-11ea-87c7-8dee3743cc10.png)

7. Hit Next, then Start.  
8. You will get the following in the `sample` table:

visits|id  |location   |
------|----|-----------|
   123|1123|Many Places|
132567|1213|Tinseltown |
   999|3333|LAX        |

which is wrong.

**Comment by koienergyspa** [comment]
I can reproduce this bug on MacOS Catalina as well. Details:
- Version: 6.3.4.202002011957
- Database: Local PostgreSQL 
- Driver:  PostgreSQL JDBC Driver `org.postgresql.Driver`

**Comment by negora** [comment]
Reproducible with the latest version in Debian 10:

- DBeaver 6.3.5.202002151353.
- Debian GNU/Linux 10.3 (Buster).
- PostgreSQL 11 (postgresql-11.7-0+deb10u1).
- PostgreSQL JDBC Driver 42.2.5.

**Comment by serge-rider** [comment]
This bug was caused by commit 14c5f1d6681650125c50f5ddbc52970a78d5bfc7
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
