### ISSUE TITLE
BigTable: Variables aren't working for connection settings

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7729]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.4
#### Connection specification:
- Database name and version BigTable

#### Describe the problem you're observing:.
Variables aren't working for connection settings
![image](https://user-images.githubusercontent.com/31996417/72985784-c9cb9400-3df7-11ea-8864-2164582216c3.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
