### ISSUE TITLE
TIMESTAMP format wrong in resultset

### ISSUE THREAD

**Issue by SLAinfor** [dbeaver/dbeaver#7732]
Hello,
I use Dbeaver to access DB2 z / os
When I do advanced copying to SQL, it changes the TIMESTAMP format to the short format with only 3 digits (.SSS) in milliseconds. But, I need the format that I use with 6 digits in the millisecond (.ffffff)
I can't find where it changes.
wrong: '2019-12-14 11:46:52.188'
I need: '2019-12-14-11.46.52.123456' how i was defined yyyy-MM-dd-HH.mm.ss.ffffff

**Comment by uslss** [comment]
you could change it in Connection Properties (F4)
![image](https://user-images.githubusercontent.com/31996417/73202441-1db5e000-414c-11ea-95b1-5223ef398756.png)

**Comment by SLAinfor** [comment]
uslss, tks, but...
My problem is in resultset... For example... When i do "advanced copy (SQL)" it made wrong format:
'2019-12-14 11:46:52.188'
See... The format is modified, without miliseconds (6 digits)
I found nowhere to change the resultset setting.

**Comment by SLAinfor** [comment]
![image](https://user-images.githubusercontent.com/40411847/73379656-6cc15980-42a1-11ea-8e26-a1dd59f39329.png)
INSERT INTO HTR_CUS_OPR (CD_EMPGCB,CD_FIL,CD_ESPMCR,CD_SETMCR,TS_HCOPR_INI_CAD,TS_HCOPR_FIM_CAD,VR_HCOPR,DT_HCOPR_INI_VIG,CD_EMPGCB_FUN,CD_FUN,ST_HCOPR_TIP_ACA,CD_HCOPR_PGM,CD_HCOPR_CHV) VALUES (
21,1850,2000,10,'**2020-01-27 13:29:24.932**',NULL,0.00,'2020-01-07',77,125008,'I','CARGA   ','0001002000');

**Comment by SLAinfor** [comment]
It's a new problem. This did not happen in versions prior to 6.3 (with DB2)

**Comment by uslss** [comment]
will be fixed in scope of #9293
