### ISSUE TITLE
dBeaver should be able to use ligature

### ISSUE THREAD

**Issue by REIMSMetropole** [dbeaver/dbeaver#7734]
We'd like to be able to use ligature in editor. That could make our dev job little easier. 
Maybe dbeaver already is able to use ligature, but I didn't find how to enable it. 
See this font for example of ligature : https://www.jetbrains.com/lp/mono/#how-to-install. 

Maybe an option in apparence setting could be implemented ? Or an advanced setting where we could check which ligature we would like to use (see Scribus which have such an option setting).

Thanks in advance.

**Comment by mc51** [comment]
You can set your editor font by editing "Text Font" in the screenshot. If you chose a font with ligatures that should do the job.

![image](https://user-images.githubusercontent.com/25569117/73066520-81b77a80-3ea6-11ea-90f1-6b0adcde3e95.png)

**Comment by REIMSMetropole** [comment]
Well. That don't. 
I've tried with monospace fonts with ligature (Fire Code, jetBrains, CamingoCode).

**Comment by mc51** [comment]
Ok, sorry. Then I guess this has to be implemented so that the editor chooses ligatures over normal symbols when appropriate.

**Comment by akilovich** [comment]
Hello @REIMSMetropole. I've tried to use JetBrains Mono with the latest DBeaver version on macOS and Windows and ligatures seem to work. Are you still experiencing issues with fonts with ligatures? Thank you.

**Comment by tomstock1337** [comment]
I submitted an EE ticket about this.  Do only certain ligature fonts work?  I am attempting to use FiraCode.  I just tried JetBrains Mono with DBeaver 7.3 and I can't get it working.  I can see that it is using the new font, however, I am not seeing the ligatures.

**Comment by tomstock1337** [comment]
I just did some more testing, and it looks like DBeaver can do some but not all ligartures.  I've been primarily wanting the ligature for arrows and logical comparisons: <- <== <= with FiraCode, and they are not working.  I can see them working for ==, ===, !=.

**Comment by akilovich** [comment]
Thank you for your investigation. It seems to be a Windows-related problem. I'll see what we can do.

**Comment by akilovich** [comment]
Fixed in the scope of #10535.

**Comment by tomstock1337** [comment]
Thanks @akilovich!!  Do you know when this will be available in the EE Early Adopter build?

**Comment by akilovich** [comment]
Approximately within the next two days.

**Comment by REIMSMetropole** [comment]
Thanks ! Great news. Can't wait to see beautiful ligature in a beautiful soft. 👍

**Comment by uslss** [comment]
verified

**Comment by tomstock1337** [comment]
Verified

**Comment by ghost** [comment]
Is there any setting to disable using ligatures?

**Comment by REIMSMetropole** [comment]
> Is there any setting to disable using ligatures?

Maybe by using a font without ligature ?
