### ISSUE TITLE
Windows 10 overall scaling problem

### ISSUE THREAD

**Issue by filipbekic01** [dbeaver/dbeaver#7738]
I have Windows 10 build 1909 laptop with external monitor. Laptop display scaling is set on 125% and monitor is 100% as usual. When i open DBeaver on laptop display, everything is scaled perfectly clear.

However, when i drag to external monitor (it switches from 125% back to 100%) whole UI goes blury as hell. Leaving screenshot below:

![Screenshot_2](https://user-images.githubusercontent.com/16108768/73076994-8d636b00-3ebf-11ea-980b-de1fb5d7e80f.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Similar to #6581.
Eclipse scales wrong on multiple monitors with different zoom factors.
