### ISSUE TITLE
SQL Server: Must declare the scalar variable... when DECLARE lines end with ';'

### ISSUE THREAD

**Issue by fniessen** [dbeaver/dbeaver#7739]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version: SQL Server, whichever version

The code

DECLARE @AcceptableSymbols VarChar(100);
SET @AcceptableSymbols = '_0123456789';

SELECT
    'ColumnName'                        AS Type,
    Table_Name + '.' + Column_Name      AS Problem
FROM INFORMATION_SCHEMA.COLUMNS
WHERE Column_Name LIKE '%[^a-z' + @AcceptableSymbols + ']%'
UNION ALL
SELECT
    'TableName',
    Table_Name
FROM INFORMATION_SCHEMA.TABLES
WHERE Table_Name LIKE '%[^a-z' + @AcceptableSymbols + ']%';

returns "Must declare the scalar variable @AcceptableSymbols".
… while this is valid code in SSMS...

Workaround: remove the ending ';' from the first 2 lines… and that works...

**Comment by serge-rider** [comment]
It is not a bug.
In order to execute TSQL scripts you need to run them as a single query.
You can select entire script and run it with <kbd>ctrl+enter</kbd>.

Otherwise dbeaver splits script on separate queries (using delimiter ;) and executes them one by one.

**Comment by djong0** [comment]
I got same problem in version 7.1.2.
It will work by delete space line.

DELETE!!!
![image](https://user-images.githubusercontent.com/3746553/88127538-769b9800-cc06-11ea-9e2a-7d5da6772082.png)

WORKED!!!
![image](https://user-images.githubusercontent.com/3746553/88127625-b5c9e900-cc06-11ea-86e8-2a50eb35780e.png)

**Comment by Beaglefoot** [comment]
I believe the default behavior should be the same as in ssms.
There are lots of code examples online, which don't work simply because you run them with DBeaver.

In the meanwhile here's another workaround.

![image](https://user-images.githubusercontent.com/15833833/89207550-95fdd200-d5c3-11ea-9ec8-60e34bbf699c.png)
