### ISSUE TITLE
Impossible to filter a Catalog/Schema list

### ISSUE THREAD

**Issue by lhuber72** [dbeaver/dbeaver#7740]
I've just started to use the 6.3.3 version. This version doesn't allow me to set a schema of a database as an active one. The way to select the desired database in the SQL editor's tab doesn't allow me to filter the list of databases typing any letters from the database name. Please add this meaningful feature. You know, it's very convenient when the list of databases can be restricted (filtered) when I type any part of their names into the text edit box.

![image](https://user-images.githubusercontent.com/60269501/73091747-23ad8600-3eec-11ea-980d-27038d826a63.png)

Even better if I select a particular node of the desired database in the object tree and click either a button on the toolbar or a menu item in the context menu to open a new SQL editor window, then the necessary database and schema would be selected automatically.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/79049135-48cbae00-7c2a-11ea-9ef1-0adafcdc776d.png)

**Comment by uslss** [comment]
verified
