### ISSUE TITLE
Oracle: error editing a TIMESTAMP WITH TIME ZONE column

### ISSUE THREAD

**Issue by mrgatto** [dbeaver/dbeaver#7741]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.3.2
- Additional extensions: No

#### Connection specification:
- Database name and version: Oracle Database 12c Enterprise Edition Release 12.2.0.1.0
- Driver name: ojdbc8-12.2.0.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

When editing an Oracle TIMESTAMP WITH TIME ZONE column i got the message:  **Can not bind statement parameter**.

I can do it through SQL like:
`UPDATE TABLE_TZ SET DATE = to_timestamp_tz('01/01/20 00:00:00,000000000 -03:00','DD/MM/RR HH24:MI:SSXFF TZR')`

#### Include any warning/errors/backtraces from the logs

The only log is:

Can not bind statement parameter
  invalid column type
  invalid column type

eclipse.buildId=unknown
java.version=1.8.0_231
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=pt_BR
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
Reopened.
Changes couldn't be saved.
1. Open table with auto-commit mode on.
2. Change value and try to save it. - Auto-commit mode changes to manual,
Result couldn't be commited or rollbacked. Mode couldn't be changed back to Auto.
In case user trying to disconect from db - npe appears.
![2020-02-26_18h27_07](https://user-images.githubusercontent.com/31996417/75359913-1ce8a900-58c6-11ea-9bab-04ae0c4aafa3.png)

> `java.lang.NullPointerException
> 	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.setAutoCommit(JDBCExecutionContext.java:315)
> 	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceTransactionModeContributor$TransactionAutoCommitAction$1.lambda$0(DataSourceTransactionModeContributor.java:141)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
> 	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceTransactionModeContributor$TransactionAutoCommitAction$1.run(DataSourceTransactionModeContributor.java:139)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

**Comment by serge-rider** [comment]
Few more fixes committed.

@uslss Note: this NPE is unrelated to the TIMESTAMP issue.

**Comment by uslss** [comment]
verified
