### ISSUE TITLE
Copy & paste creating extra curly braces in results grid

### ISSUE THREAD

**Issue by markjackson02** [dbeaver/dbeaver#7743]
#### System information: 
- Operating system: Windows 7
- DBeaver version 6.3.3
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgreSQL 10.9
- Driver name: PostgreSQL JDBC Driver

#### Describe the problem you're observing:
Copy & Paste does not work correctly in Results Grid for data types TEXT, VARCHAR, and JSONB (possibly others?).

For TEXT and VARCHAR, I am storing options in a text field like this: `{Option 1,Option 2}`. When I copy the value from one row to another in the Results Grid after querying for these rows, the pasted value looks like this: `{{Option 1, Option 2}}` (it adds extra curly braces)

Similar issue with JSONB. If my object looks like this `{{name:"one",color:"blue"},{name:"two",color:"red"}}` and copy/paste it, the result looks like `{{{name:"one",color:"blue"},{name:"two",color:"red"}}}` (it adds extra curly braces) and in the Value pane the result is way different because of the way it is parsing it.

**Comment by uslss** [comment]
unfortunately, cannot reproduce the issue? 
could you add some special steps or video that could help to reproduce the issue?

**Comment by uslss** [comment]
there is no update on issue for a long time, ticket closed. 
if issue is still actual for you - feel free to reopen the ticket with additional info
