### ISSUE TITLE
Data transfer: use table manager for DDL (db->db)

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#7745]
Currently we generate DDL for new tables manually. We need to reuse table managers model to do it smarter.
Additionally we won't need to refresh meta model after each table creation.

**Comment by mkgrgis** [comment]
There is the issue with (db->db) for data block https://github.com/dbeaver/dbeaver/issues/7696 In complex it will be system for full table export db->db.

**Comment by serge-rider** [comment]
Will be implemented in #8556

**Comment by kseniiaguzeeva** [comment]
impemented (a couple of separatetickets with small bugs will be created)
