### ISSUE TITLE
Query Manager shows incorrect Duration for previously executed queries

### ISSUE THREAD

**Issue by coldenol** [dbeaver/dbeaver#7747]
#### System information: 
- Operating system (distribution) and version: Windows 10, 1903
- DBeaver version: 6.3.3

#### Connection specification:
- Database name and version: AWS RDS MySQL 5.7

#### Describe the problem you're observing:
Every time a new query is being executed, duration for the previously executed query changes its value to the amount of milliseconds between these two queries.

#### Steps to reproduce, if exist:
1. Open Query Manager,
2. Execute queries consistently and observe the Duration field behavior.
![query_manager](https://user-images.githubusercontent.com/49859188/73175505-03134500-4113-11ea-8277-d2ca7f0126cd.jpg)

**Comment by serge-rider** [comment]
This is a bug in cursors processing. It happens when option "Keep open cursors" is enabled.
Thanks for the bug report.

BTW this option doesn't make sense for MySQL (it was added for Oracle client-side cursors).

**Comment by serge-rider** [comment]
However I don't know how to fix this issue. As statement (and resultset) kept open until you execute a new query or end a transaction. So technically statistics is correct.

Workaround: turn this option off if you don't need client-side cursors.

**Comment by coldenol** [comment]
Confirm, shows correct duration after disabling "**Keep open cursors in SQL editor**" in Preferences > Editors > Data Editor > Miscellaneous.
Thanks a lot. 

Please close this issue if there is nothing else to do.
