### ISSUE TITLE
Title bar and buttons aren't shown in Choose connection/db pop-ups

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7748]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.4
#### Describe the problem you're observing:
Title bar and buttons aren't shown in Choose connection/db pop-ups
![image](https://user-images.githubusercontent.com/31996417/73177111-2e039600-411f-11ea-85a8-994135c66f34.png)
![image](https://user-images.githubusercontent.com/31996417/73177122-3360e080-411f-11ea-8289-4ec9519a682c.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
