### ISSUE TITLE
Default DB is shown instead of active when use "Read Data in SQL console"

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7749]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.4

#### Connection specification:
- Database name and version Cassandra CQL

#### Describe the problem you're observing:
When I use Read Data in SQL console for table from non-default table, active db is shown firstly in toolbar, but after query execution - default db is shown instead

![2020-01-27_16h21_55](https://user-images.githubusercontent.com/31996417/73178080-93588680-4121-11ea-8752-bd2dedb0b6c9.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
