### ISSUE TITLE
Error executing row count: duplicate column name

### ISSUE THREAD

**Issue by slokhorst** [dbeaver/dbeaver#7750]
If I execute the following query:
```sql
SELECT * FROM a
JOIN b ON b.foo = a.foo
```
And then click "Calculate total row count" below the result set, it says: `Error executing row count`.

When checking out the error, it turns out that this is the generated query for the row count:
```sql
SELECT COUNT(*) FROM (SELECT * FROM a
JOIN b ON b.foo=a.foo
) dbvrcnt
```

Which results in the following error on server:
```
[1060] (conn:99533643) Duplicate column name 'foo'
Query is: SELECT COUNT(*) FROM (SELECT * FROM a
JOIN b ON b.foo=a.foo
) dbvrcnt
```

DBeaver 6.3.3
MariaDB server

**Comment by slokhorst** [comment]
e.g. phpMyAdmin does give a row count for the same query. I'm not sure what method they use to obtain it.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by slokhorst** [comment]
Wow you guys are fast. I can confirm that the issue is fixed in the latest git build. Thanks!!

**Comment by uslss** [comment]
verified
