### ISSUE TITLE
Get an error and Dbeaver is being hung when trying to save modified view

### ISSUE THREAD

**Issue by coldenol** [dbeaver/dbeaver#7754]
#### System information: 
- Operating system (distribution) and version: Windows 10, 1903
- DBeaver version: 6.3.3

#### Connection specification:
- Database name and version: AWS RDS MySQL 5.7

#### Describe the problem you're observing:
Trying to save changes in view via "Persist changes" window throws error message and Dbeaver is being hung until the process is killed.
![modify_view](https://user-images.githubusercontent.com/49859188/73283753-41d0fa00-41fc-11ea-8ec0-43fe6c1de965.jpg)

#### Steps to reproduce, if exist:
1. go to your_connection > your_database > Views
2. double click on a view to open its properties
3. make some changes in the view statement
4. click "Save" button

#### Error Log:
[errorlog.txt](https://github.com/dbeaver/dbeaver/files/4123475/errorlog.txt)

**Comment by coldenol** [comment]
@uslss This bug is reproduced even for column/table modifications. It occurs mostly on every second attempt to persist changes for modified database object. For instance, I modify a column, click on "**Persist**" - everything is ok, then open another table, modify its column and now get an error.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
