### ISSUE TITLE
SQL Assist issue on Eclipse

### ISSUE THREAD

**Issue by deveborn** [dbeaver/dbeaver#7757]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 6.3.3
- Java version: 8
- Additional extensions: Using the eclipse extension

#### Connection specification:
- Database name and version: SQL Server
- Driver name: Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I am new to DBeaver and cannot get SQL Assist to work properly. I have googled this several hours without founding a solution. I get no code assistance at all in the SQL Editor. In the context menu the SQL assist option is out grayed and I get no response on ctrl+space. There is a messages in the Eclipse error log that seams to be correlated to this (attached).  Hopefully there is a solution to the problem because except this DBeaver looks really great!

#### Steps to reproduce, if exist:
To trigger the error. Select the Server connection, right click and select SQL editor.

#### Include any warning/errors/backtraces from the logs

[eclipse.log](https://github.com/dbeaver/dbeaver/files/4123564/eclipse.log)

**Comment by uslss** [comment]
Hi @deveborn ,
unfortunately cannot reproduce an issue. What eclipse version do you use?

**Comment by deveborn** [comment]
Thanks for the response @uslss 
My eclipse version is Neon.3 Release (4.6.3).

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
