### ISSUE TITLE
Long running query finishes on the database but not on DBeaver

### ISSUE THREAD

**Issue by lmacedo-pivotal** [dbeaver/dbeaver#7759]
#### System information: 
- OS: MacOS 10.15.2 Catalina
- DBeaver version: 6.3.2
- Additional extensions: None

#### Connection specification:
- Database name and version: Greenplum  Database 5.23
- Driver name: Built in driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
A long running query (> 1 hour) finishes at the database but DBeaver does not known  that it finished and still shows as running. In this case insert-select type of query that don't return rows.

#### Steps to reproduce, if exist:
Run an insert-select query that runs for over one hour

**Comment by uslss** [comment]
@lmacedo-pivotal , is issue still actual for you?

**Comment by uslss** [comment]
seems that issue is fixed in the scope of #9121
