### ISSUE TITLE
DB2 Alter Table Column VARCHAR not including length

### ISSUE THREAD

**Issue by bellds** [dbeaver/dbeaver#7761]
#### System information: 
- Operating system (distribution) and version: Mac OS X
- DBeaver version: 6.3.3.202001191557
- Additional extensions: None

#### Connection specification:
- Database name and version DB2 v11.1
- Driver name: DBeaver Embedded DB2
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
In the Table Properties view I change a VARCHAR field length and the generated ALTER SQL does not include the VARCHAR length.

#### Steps to reproduce, if exist:
1) Go to Table Properties View
2) Change a column that is VARCHAR to a different length
3) Generated SQL does not execute

#### Include any warning/errors/backtraces from the logs
Generated SQL was:
ALTER TABLE FTM.PAYMENT_MESSAGE_TYPE ALTER COLUMN NAME SET DATA TYPE VARCHAR;

Expected SQL was:
ALTER TABLE FTM.PAYMENT_MESSAGE_TYPE ALTER COLUMN NAME SET DATA TYPE VARCHAR(30);

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
