### ISSUE TITLE
Can`t connect to Hive 1.1.0 (client_protocol is unset)

### ISSUE THREAD

**Issue by mikhail-akimov** [dbeaver/dbeaver#7762]
Hello!
I can not fix the error 'client_protocol' is unset. 
I manually downloaded the driver suitable for my version (from https://github.com/timveil/hive-jdbc-uber-jar/releases), but I can’t install it in the Driver settings. DBeaver continually downloads the latest from the git-repo. And when downloading / updating the driver there is no way to download the correct version (i choose from ). 
Can i fix it somehow? Or maybe DBeaver could choose driver based on server-version? 

Thank you!

**Comment by mikhail-akimov** [comment]
I fix it with actual driver.

**Comment by lramos** [comment]
Hi how fix it?
