### ISSUE TITLE
Lines in ER Diagrams

### ISSUE THREAD

**Issue by bclothier** [dbeaver/dbeaver#7763]
I quite like ER diagrams but I don't like how the lines simply connects two tables without considering the columns to be mapped. When setting up a diagram with multiple tables & foreign key constraints, it can be tiresome trying to determine what columns participates in what foreign key constraints.

One possible solution is to make the lines connect to the column(s) rather than some generic point on the table's edge to make it clear what column(s) participate in what key columns.

**Comment by rdeese** [comment]
I'm looking for a similar feature. Another approach would be to add text labels to the edges themselves. The label could be auto-populated with the names of the column(s) participating from each table.

A minimal (but still helpful) addition would be to export a table describing the edges, e.g.:

A smaller request would be a way to export a table of all of the edge connectivity, something like:

| Table | Reference Table | Column | Reference Column |
| -- | -- | -- | -- |
| users | organizations | orgid | id |
| plans | organizations | orgid | id |
| sessions | users | userid | id |

Thank you very much for maintaining DBeaver, it's a great tool.

**Comment by kseniiaguzeeva** [comment]
@bclothier you already can see which columns connect tables. Please click a line between tables, and columns with foreign key and primary key will be highlighted.

@rdeese thank you for the suggestion.

**Comment by bclothier** [comment]
@kseniiaguzeeva Thanks. I was aware of that, but it is not practical when you want to look at the diagram for the big picture and not have to click on each line to get that additional information. Also, it wouldn't work if it's on paper or on a PDF.

**Comment by kseniiaguzeeva** [comment]
Thank you for clarifying

**Comment by uslss** [comment]
duplicates #7257
