### ISSUE TITLE
select query is giving cached output

### ISSUE THREAD

**Issue by praveensatti** [dbeaver/dbeaver#7766]
When I fire select query on a table, it is giving the same output even if the table is being continuously inserted with new records

**Comment by p91paul** [comment]
The process inserting records probably didn't issue a commit statement. Uncommitted inserts exist only on the session that is performing the insert itself.

**Comment by praveensatti** [comment]
Its transactional DB, it is in auto commit mode. Application will be punching logs to it.

**Comment by serge-rider** [comment]
@praveensatti dbeaver doesn't cache any data (it would be a vary hard task even theoretically), everything comes from the server when you execute a query.
So, most likely your DBeaver connection is not in auto-commit state. If buttons Commit/Rollback are enabled then you can just click on one of them to get fresh results.

Also it is possible that connection which inserts the data doesn't perform commit.

**Comment by praveensatti** [comment]
why should be there auto commit for select query ?

**Comment by serge-rider** [comment]
@praveensatti to disable transactions. Transactions affect visibility of changes made by other connections.

**Comment by praveensatti** [comment]
Thank a lot for info
