### ISSUE TITLE
Autocomplete doesn't work after subquery

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#7768]
#### System information: 
- Windows 7 Pro x64
- DBeaver 6.3.4
- No additional extensions

#### Connection specification:
- PostgreSQL 9.3
- PostgreSQL default driver (9.4.1212.jre7)
- No tunnels or proxies

#### Describe the problem you're observing:
Doesn't work ctrl+space autocomplete after subquery. Type query below, stay after subquery and press ctrl+space - no field searching result (doesn't display all columns of table. returns search matching of default schema)

#### Steps to reproduce, if exist:
select (select max(id) from table2), 
from table1

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed (now we'll show columns completion for the nearest table for cursor position)

**Comment by ems2811** [comment]
@serge-rider This method returns columns from a subquery (tested in 6.3.5)

**Comment by ems2811** [comment]
@serge-rider 
Tested in 6.3.5 - comletion returns column from subquery (incorrect). Steps:
1) Create testing tables:
```
drop table if exists supp.tmp_test1;
drop table if exists supp.tmp_test2;
create table supp.tmp_test1(id int, name1 text);
create table supp.tmp_test2(id int, name2 text);
insert into supp.tmp_test1(id, name1)
select generate_series(1,10), generate_series(1,10);
insert into supp.tmp_test2(id, name2)
select generate_series(1,10), generate_series(1,10);
```
2) disconnect from db
3) open new editor, type query below and press ctrl+space
```
select (select id from supp.tmp_test1 where id=t2.id limit 1), 
from supp.tmp_test2 t2
where t2.id=10
```
![изображение](https://user-images.githubusercontent.com/22142845/74128567-80988400-4bee-11ea-9e46-3df405157efb.png)

**Comment by uslss** [comment]
@ems2811 cannot reproduce mentioned issue
![image](https://user-images.githubusercontent.com/31996417/74132136-fb659d00-4bf6-11ea-94dc-f7ae508f2037.png)
probably, there is no fix in the current version of EA

**Comment by ems2811** [comment]
@uslss will wait not EA version 6.3.5 and test in it. If reproduces - i’ll record a video

**Comment by uslss** [comment]
Reopened according to https://github.com/dbeaver/dbeaver/issues/7768#issuecomment-583987114

**Comment by serge-rider** [comment]
We need to add smart semantic analysis here. For now we show column proposals for the "table found after cursor" in the current query.

Workaround: use table aliases.

**Comment by ems2811** [comment]
@serge-rider , in example after cursor table supp.tmp_test2, but column proposals returns for table before cursor position supp.tmp_test1

![изображение](https://user-images.githubusercontent.com/22142845/75415913-17c74080-593e-11ea-9b53-9c98da75ca69.png)

**Comment by ems2811** [comment]
Maybe, #7876 the same problem?
column proposals returns for table before cursor postition

**Comment by ems2811** [comment]
still reproduced in 7.0.0.202003021717

**Comment by uslss** [comment]
still reproducible in 23.0.3

**Comment by LonwoLonwo** [comment]
Case from #13151

```
= not work query
SELECT *
FROM (
SELECT *
FROM TB.TEST_TABLE TT
WHERE TT. --> auto-completion not work (If press the ctrl+space key, message popup 'no proposals'
) T2
, TB.TEST2_TABLE --> Insert table aliases(in FROM clause) function don't work (my_table mt)
WHERE 1=1
AND T2. --> auto-completion not work (If press the ctrl+space key, message popup 'no proposals'
```

**Comment by E1izabeth** [comment]
Case from  #21262
![269557992-39284c47-43ae-4962-9d58-ea1dd61755a4](https://github.com/dbeaver/dbeaver/assets/28875055/6284d5d2-4ab9-4095-a26b-00f4640722a6)

**Comment by LonwoLonwo** [comment]
Case from #22104

```sql
create table tmp_tab1(
	id int,
	field1 text,
	field2 text);

create table tmp_tab2(
	id int,
	field3 text,
	field4 text);

select *
from tmp_tab1 t1
	join lateral (select t2.id
		from tmp_tab2 t2
		where t2. --<--- here ctrl+space
where t1.id > 1;
```

**Comment by E1izabeth** [comment]
We will solve this issue in scope of #21654
