### ISSUE TITLE
"Create new connection" (Ctrl+N) doesn't work in Main menu

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7769]
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.4

#### Describe the problem you're observing:
"Create new connection" (Ctrl+N) doesn't work in Main menu
#### Steps to reproduce, if exist:
Try to create a new connction using shortcut "Ctrl+N" or via Main Menu.

Actual result: Error Window appears:
"The selected wizard could not be started.
Plug-in "org.jkiss.dbeaver.core" was unable to instantiate class "org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionWizard".
org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionWizard."
<init>()
![jSZHMNA2Gf](https://user-images.githubusercontent.com/51405061/73430044-20802300-434e-11ea-9245-81f59b9f8448.png)
[.log](https://github.com/dbeaver/dbeaver/files/4132766/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4132767/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
