### ISSUE TITLE
[SQLite] SQL Editor doesn't execute statements

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7770]
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.4

#### Connection specification:
- Database name and version SQLite (embedded)

#### Describe the problem you're observing:
SQL Editor doesn't execute statements
#### Steps to reproduce, if exist:
1. Try to execute a statement in SQL Editor.

Actual result: "Can't execute query" window appears with message "Not connected to database"

[.log](https://github.com/dbeaver/dbeaver/files/4132901/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4132902/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
