### ISSUE TITLE
[SQLite] Confirmation is not needed when "confirm data changes" is enabled

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7771]
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.4

#### Connection specification:
- Database name and version SQLite (embedded)

#### Describe the problem you're observing:
Data Editor: Confirmation is not needed when "confirm data changes" is enabled if:
1. make any changes
2. press Ctrl+S in the same cell (not switching to other cells).

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
