### ISSUE TITLE
Autocomplete after truncate not implemented

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#7775]
Autocomplete after truncate not implemented. DBeaver 6.3.3. Postgresql.
![truncate](https://user-images.githubusercontent.com/3856344/73449305-e88bd680-4373-11ea-9ae7-b4ebe4445b40.gif)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by greenpeas** [comment]
And more (with FROM):
![from](https://user-images.githubusercontent.com/3856344/73516507-ac0aba00-4409-11ea-8c51-1fb778866ca9.gif)

**Comment by serge-rider** [comment]
Truncate bug fixed.
Please create separate ticket for another completion bug.

**Comment by kseniiaguzeeva** [comment]
Verified (truncate)
