### ISSUE TITLE
Selection of Backup table

### ISSUE THREAD

**Issue by Jnb2387** [dbeaver/dbeaver#7781]
#### System information: 
- Operating system (distribution) and version linux mint
- DBeaver version 6.3.3
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When doing a backup you able to select a schema and table but it does not hold true during the backup. I am not able to just backup a single table.
#### Steps to reproduce, if exist:
Right click table > tools> backup Select the schema and table to back up click start and all tables will be backed up only if one is selected

**Comment by uslss** [comment]
Hi @Jnb2387 ,
cannot reproduce an issue. could you test it against 6.3.4 version?

**Comment by Jnb2387** [comment]
Downloaded 6.3.4 and now unable to backup any table.
Error received says no matching tables were found, when I am selected the table via a checkbox.

/usr/lib/postgresql/12/bin/pg_dump --verbose --host=px-geo02-d --port=5432 --username=dpsdata --format=c -t "permit_review.permit_tracker" geocoder
Task 'PostgreSQL dump' started at Mon Feb 03 12:06:29 MST 2020
pg_dump: last built-in OID is 16383
pg_dump: error: no matching tables were found
Task 'PostgreSQL dump' finished at Mon Feb 03 12:06:29 MST 2020
2020-02-03 12:06:29.418 - IO error: Process failed (exit code = 1). See error log.
2020-02-03 12:06:29.418 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:182)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:237)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:52)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by amkisko** [comment]
Got the same issue `pg_dump: error: no matching tables were found` when tried to backup few tables from schema. Backup works fine when all available schemas and tables are selected.

**Comment by Jnb2387** [comment]
With 6.3.3 I was able to only backup all tables in the schema, in 6.3.4 I cant backup anything.

**Comment by serge-rider** [comment]
@Jnb2387 @amkisko does pg_dump command look valid for you? 
Are database/schema/table names correct?

I still can't reproduce this problem but I didn't test it on PG 12 yet.

**Comment by amkisko** [comment]
> @Jnb2387 @amkisko does pg_dump command look valid for you?
> Are database/schema/table names correct?
> 
> I still can't reproduce this problem but I didn't test it on PG 12 yet.

I copied generated command to console and it worked. :)

**Comment by Jnb2387** [comment]
Yeah same with me, copying the generated command and using it in a terminal worked without issue.

**Comment by rolandknapp** [comment]
I am experiencing the same behavior (DBeaver version 6.3.4 on Linux Ubuntu 18.04). When all database tables are included in backup the routine completes successfully. When one table is excluded from backup, the routine fails with message, "pg_dump: no matching tables were found". Here are the generated commands from both backup types (text in <> is text that I am providing here instead of the user-specific text in the generated commands): 

All tables included in backup:
`/usr/bin/pg_dump --verbose --host=<host> --port=5432 --username=<username> --format=c -n "<dbschema>" <dbname>`

One table removed from backup:
`/usr/bin/pg_dump --verbose --host=<host> --port=5432 --username=<username> --format=c -t "<dbschema.table1>" -t "<dbschema.table2>" -t "<dbschema.table3>" -t "<dbschema.table4"  <dbname>`

**Comment by serge-rider** [comment]
This seems to be PostgreSQL 12 specific.

**Comment by rolandknapp** [comment]
I'm actually using PostgreSQL version 10.

**Comment by serge-rider** [comment]
@rolandknapp Ok.
What is your local PG client version then?
```
/usr/bin/pg_dump --version
```
Maybe the problem is in pg_dump and server version mismatch

**Comment by amkisko** [comment]
More info regarding my case: MacOS, PostgresApp
```
% pg_dump --version
pg_dump (PostgreSQL) 11.5
```

And please note:
> I copied generated command to console and it worked.

**Comment by rolandknapp** [comment]
@ serge-rider. The pg_dump version on the client is 10.12 and the PG version on the host is 10.11.

**Comment by Jnb2387** [comment]
Still having pg_dump issues with version 7.0.0 on Postgres 12

**Comment by serge-rider** [comment]
@Jnb2387 "quoting capitals" - is it incorrect? Could you write some example?

@amkisko 
> And please note:
> > I copied generated command to console and it worked.

Yes, this made me think that pg_dump invoked directly is a different version of pg_dump.
Otherwise I can't realize what magic brings this bug to life.  
Maybe it be caused by invalid identifiers quoting?

**Comment by Jnb2387** [comment]
I am no longer experiencing this issue with version 7.1.*, any table is now able to be selected and dumped including quoted tables "Test_Table"
