### ISSUE TITLE
Ghost tables, deleted but not gone (Postgres)

### ISSUE THREAD

**Issue by mkortink** [dbeaver/dbeaver#7782]
I am using version 6.3.3.202001191557.

This is what happens.
1) In an SQL window on a Postgres database connection.
2) Drop database "db1" which had a table called "tb" in it.
3) In explorer "db1" is gone.
4) Create a database called "db2" ( not "db1").
5) In explorer "db2" exists but has no tables.
5) Try to create a table called "tb", errors saying "tb" already exists.
!) The ghost table "tb" is in DBeaver even though its original database "db1" is gone!
6) Go to pgAdmin and see "db2" exists and is empty, and I can create "tb".
7) I go back to DBeaver, refresh, and "tb" is there in "db2".

I have tried:-
a) Reconnecting to Postgres.
b) Restarting DBeaver.
c) Rebooting machine.

![image](https://user-images.githubusercontent.com/27032470/73498957-e3ca2f80-4412-11ea-83db-f2e4a6a928a7.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
issue isn't reproducible now.
@mkortink if issue is still actual for you against recent version - feel free to reopen the ticket
