### ISSUE TITLE
Feature request: Execute sql statement saving script file before execution

### ISSUE THREAD

**Issue by cumanacr** [dbeaver/dbeaver#7783]
Hi, I would like dbeaver to have an option for saving the script file where **ctrl+x** have been run before execution.

I'm requesting this because I just lost a huge query I wrote, I ran the script but notice that it would take a lot of time, so I canceled the execution, but sometimes dbeaver takes a lot to cancel, so for me, it's easy just close the whole application, doing that closes connections and asks me always to save the files before close.

But this time I mistakenly click on the **NOT** save button, losing the query.

I looked for an option to save script before **execute sql statement** but I had no luck.

To give an example, this feature is present on Pentaho PDI it saves the transformation file before execution.

Regards,

**Comment by cerebel** [comment]
@cumanacr 
Dbeaver (6.1x) has : Database->Editors->SqlEditos:   AutoSave  [+]"Save editor on query execute".

Hint:  in case of "sometimes dbeaver takes a lot to cancel" - you could close forcibly the connections 
, in M$  I use ProcessHacker -under tab networks close connections.

**Comment by carlosspohr** [comment]
@cumanacr , see this:

![image](https://user-images.githubusercontent.com/637767/73537834-36eab500-4408-11ea-94ed-32bb6f5d3270.png)

**Comment by cumanacr** [comment]
Hi, @cerebel and @carlosspohr thanks that's what it wanted I tested and it works!

But @cerebel this M$ I don't understand what it is and that **ProcessHacker** thing, I cannot find it

**Comment by cerebel** [comment]
@cumanacr
M$ - Microsoft  [ ..windows 7.. ]   :) 
Process Hacker [dowload](https://processhacker.sourceforge.io/downloads.php)

**Comment by cumanacr** [comment]
@cerebel ahhhh, but, I'm using linux, so, I use xkill app or command line for that purpose thank you very much
