### ISSUE TITLE
Wildcard object privileges not listing for MariaDB/MySQL

### ISSUE THREAD

**Issue by mcdamo** [dbeaver/dbeaver#7784]
#### System information: 
- Operating system (distribution) and version
  Ubuntu 19.10
- DBeaver version
  6.3.3.202001191557
- Additional extensions

#### Connection specification:
- Database name and version
  MariaDB 10.2
- Driver name
  MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
  Yes

#### Describe the problem you're observing:
User Privileges on wildcard objects are not listed when selecting the Catalog and Tables, the Table Privileges only list non-wildcard privileges.

MariaDB/MySQL allows wildcards in the 'ON' and 'TO' parts of a GRANT. Privileges with wildcards in the 'ON' part are not showing in DBeaver.

Relevant documentation on wildcard privileges: https://dev.mysql.com/doc/refman/5.6/en/grant.html#grant-quoting

#### Steps to reproduce, if exist:
This presumes you have default 'test' user and 'test' database, and 'test' user is not granted ALTER privileges.

Grant ALTER on all tables in databases named 'test*':
```sql
GRANT ALTER ON `test%`.* TO 'test'@'%';
FLUSH PRIVILEGES;
```
Refresh/Reconnect DBeaver and open the privileges for user 'test'@'%' and database named 'test': ALTER privilege is not listed.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by nokiomanz** [comment]
Hi, 

I have the same problem.
Tried version 6.3.1 6.3.3 and 6.3.5

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by nokiomanz** [comment]
Hi, 

Not sure it is fixed.

Here is a screenshot under6.1.1
![image](https://user-images.githubusercontent.com/17622903/75706356-060dd200-5c8b-11ea-8cb1-95a057b7066d.png)

Here is the same screenshot under 7.0.0
![image](https://user-images.githubusercontent.com/17622903/75706427-1e7dec80-5c8b-11ea-9a8d-a63802c72646.png)
