### ISSUE TITLE
[PostgreeSQL] Incorrect show all data type "timestamp with time zone" in case from current time zone, setted comands: set timezone = '+05';

### ISSUE THREAD

**Issue by TimurChik73** [dbeaver/dbeaver#7785]
#### System information: 
- MS Windows 10 x64 1607
- DBeaver version 6.3.3
- Additional extensions

#### Connection specification:
- Database name and version PostgreeSQL 10
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:
CREATE TABLE public."TestTimeZone"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Date" timestamp with time zone
);
set TimeZone = '+08';

insert into "TestTimeZone" ("Date")
select CURRENT_TIMESTAMP;

insert into "TestTimeZone" ("Date")
select localtimestamp;
select
	"Id"
	, "Date"
from "TestTimeZone";

**Comment by kseniiaguzeeva** [comment]
Please enable "Use native date/time format" (DB Navigator>database context menu> Edit connection> Result Sets> Data Formatting). It should help.
![8bNuoPnE7f](https://user-images.githubusercontent.com/51405061/73664143-f8772380-46af-11ea-9e7f-883c98146e81.png)
