### ISSUE TITLE
Export as CSV fails with blank error for SQL statements ending with semicolon

### ISSUE THREAD

**Issue by ggjersund** [dbeaver/dbeaver#7786]
#### System information:

* Ubuntu 18.04.3 LTS
* DBeaver 6.3.3.202001191557

#### Connection specification:

* Local MySQL database
* com.mysql.jdbc.Driver

#### Describe the problem you're observing:

Queries would not run for SQL statements that ended with a semicolon during export query as CSV. Normal SQL queries works. Similar SQL statements (copy & paste) with / without semicolon worked accordingly.

#### Steps to reproduce, if exist:

Try to export as CSV with SQL statement that ends with semicolon.

**Comment by j-coates** [comment]
Might be a duplicate of 7731:
https://github.com/dbeaver/dbeaver/issues/7731

**Comment by uslss** [comment]
hi @ggjersund ,
could you try it against 6.3.4 version?

**Comment by ggjersund** [comment]
@uslss That looks like the same issue yes. My bad. Closing this bug report :)
