### ISSUE TITLE
--single-transaction does not work with mysqldump anymore

### ISSUE THREAD

**Issue by Powerhamster** [dbeaver/dbeaver#7789]
The Option --single-transaction will not be appended to the mysqldump command anymore in Version
6.3.3.202001191557 on MacOS.

Mysqldump is from Homebrew Mysql-Client@5.7, Server Version is 5.6 connected via SSH Tunnel.

**Comment by serge-rider** [comment]
Thanks for the bug report.

**Comment by uslss** [comment]
verified
