### ISSUE TITLE
[SQLite]"Double click" doesn't work for cell edit if a table is with FK.

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7790]
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.4

#### Connection specification:
- Database name and version SQLite

#### Describe the problem you're observing:
"Double click" doesn't work for cell edit if a table is with FK and Reference panel is opened. Only multiple click can be used or alternatives (click+Enter etc.)

#### Steps to reproduce, if exist:
1. Open a table with FK or Virtual FK in Data Editor or Result set
2. Open reference panel
3. Double click on a cell.

Actual result: The cell cannot be edited.

![AI2VVE1spE](https://user-images.githubusercontent.com/51405061/73537155-d2941980-4438-11ea-9c64-e88150bb2d9d.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
