### ISSUE TITLE
[SQLite] Truncate function doesn't work for import/export

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7791]
## System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.4

#### Connection specification:
- Database name and version SQLite

#### Describe the problem you're observing:
Truncate function doesn't work for import/export

#### Steps to reproduce, if exist:
Import into a table with some content a data (from table or CSV file)  using "Truncate" function.

Actual result: 
-The data is imported to the table
-Existed table's content is not removed

![EQxj1hkfWb](https://user-images.githubusercontent.com/51405061/73540900-25260380-4442-11ea-860b-446f08652d14.gif)

**Comment by kseniiaguzeeva** [comment]
The "truncate" function is not represented in SQLite. It is needed to execute a DELETE statement without a WHERE clause.

**Comment by serge-rider** [comment]
DELETE FROM is a different command and it may take a lot of time. TRUNCATE is not supported for SQLite so just don't use it.

**Comment by SuperBrain** [comment]
Why does it matter if DELETE FROM takes a long time if that's what's required to utilize the TRUNCATE functionality? We need this to work, otherwise this option should be removed/disabled when using SQLite. Please consider re-opening this and make it work using DELETE FROM.

**Comment by p91paul** [comment]
Also, falling back to delete (possibly with a warning) would be useful when you don't have truncate grants (e.g. oracle uses different grants for delete and truncate)
