### ISSUE TITLE
Hot key F3 doesn't work for the fisrt time

### ISSUE THREAD

**Issue by renyxadarox** [dbeaver/dbeaver#7792]
**System information:**

- Windows 7 (64-bit) Build 7601 (Service Pack 1)
- DBeaver 6.3.3.202001191557

**Connection specification:**

PostgreSQL 10.10
PostgreSQL JDBC Driver 42.2.9

**Describe the problem you're observing:**

Occasionally after the first (initial) press of hot key F3 ("SQL Editor") on Database Navigator over Connection, the window of "SQL Scripts" temporary appears and immediately closes. After the second press F3, it appears again and stays permanently.

However, I observe, a click "SQL Editor" from the right-mouse pop-up menu never causes such behaviour.

Perhaps, it could be related to killing DBeaver as a process from Task Manager in former times and incorrect "SQL Scripts" link to the Connection saving. And not necessary that DBeaver was killed directly the last time. May the last several times DBeaver was closed correctly, but "SQL Scripts" stay linked in incorrect way and the issue appears only when F3 is pressed.

**Comment by serge-rider** [comment]
This problem was already fixed in 6.3.4. Fix can be tested in the Early Access version.

**Comment by uslss** [comment]
verified

**Comment by renyxadarox** [comment]
The problem wasn't fixed in 6.3.4
