### ISSUE TITLE
Oracle: query couldn't be exported

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7794]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.4

#### Connection specification:
- Database name and version oracle

#### Describe the problem you're observing:
Export from simple query like select * from [table] fails with next message
![image](https://user-images.githubusercontent.com/31996417/73548495-ef891680-4451-11ea-9885-9cde5a04feb4.png)
In case it is saved as task - export ends successfully
#### Steps to reproduce, if exist:
1. Open SQL editor with query select * from [table]
2. Execute Export from query
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4139974/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
