### ISSUE TITLE
version control for functions

### ISSUE THREAD

**Issue by cefetra-valstar** [dbeaver/dbeaver#7795]
Hi!

I've managed to set up version control for my project using the eclipse GIT extension. However, this includes only my scripts and not my tables DDL, views DDL and most importantly my functions/procedures. 

In order to get them in version control as well, should I copy the DDL of my tables, views and functions to separate .sql files and then include them in my project? What is best practise?

Thanks a lot, really enjoying DBeaver!!
Nick

**Comment by p91paul** [comment]
I do it that way, I save DDL for every object as a file under git.
