### ISSUE TITLE
[SQL Server] Column of Geography/Geometry data type cannot be created.

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7801]
#### System information: 
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.4

#### Connection specification:
- Database name and version SQL Server

#### Describe the problem you're observing:
Column of Geography/Geometry data type cannot be created.

#### Steps to reproduce, if exist:
Try to create Column of Geography/Geometry data type using table Object editor.

Actual result:
1. Error message appears: "Column, parameter, or variable #4: Cannot specify a column width on data type geometry"
2. Column creation is failed.

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4142784/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
1 Impossible to insert value 'POINT(4 5)',0  in geometry/geography column: Error synchronizing data with database
Reason:
SQL Error [6522] [S0001]: A .NET Framework error occurred during execution of user-defined routine or aggregate "geometry":
System.ArgumentException: 24100: недопустимый идентификатор spatial reference identifier (SRID). Значения SRID должны находиться в диапазоне от 0 до 999999.
Я вставляю неверное значение?
2 не стереть в пропертис тип столбца, чтобы вписать новый=> тип столбца указать можно, только выбрав его из списка (а напечатать нельзя)

**Comment by serge-rider** [comment]
It is not a bug. You need to specify valid SRID (or specify it in column definition).
This is beyond dbeaver data validation.,

**Comment by kseniiaguzeeva** [comment]
verified
