### ISSUE TITLE
Latest Dbeaver Enterprise unusable with MongoDB Atlas

### ISSUE THREAD

**Issue by vasiliyb** [dbeaver/dbeaver#7802]
#### System information: 
- OSX latest
- DBeaver version Version 6.3.0.202001141657
- Additional extensions

#### Connection specification:
- MongoDB Atlas or local docker container
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When connecting to MongoDB atlas, the following error constantly opens:

```
Command failed with error 8000 (AtlasError): 'CMD_NOT_ALLOWED: mapreduce' on server cluster0-shard-xxxxxxxxxxxxx. The full response is {"ok": 0, "errmsg": "CMD_NOT_ALLOWED: mapreduce", "code": 8000, "codeName": "AtlasError"}
```

**Comment by Nisgrak** [comment]
I have the same problem.

```
Command failed with error 8000 (AtlasError): 'CMD_NOT_ALLOWED: $eval' on server cluste-xxxxxx. The full response is {"ok": 0, "errmsg": "CMD_NOT_ALLOWED: $eval", "code": 8000, "codeName": "AtlasError"}
```

**Comment by uslss** [comment]
is it still actual against 7.0.0 for you?

**Comment by Nisgrak** [comment]
Woh, it's works now. Thanks!
