### ISSUE TITLE
[SQL Server] Metadata search cannot find tables

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7803]
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.4

#### Connection specification:
- Database name and version SQL Server

#### Describe the problem you're observing:
[SQL Server] Metadata search cannot find tables.

#### Steps to reproduce, if exist:
1. Search an existed table using Metadata search (check "table")> the table is not found
2. Reopen Metadata search > "system base table" is checked

![hheta20OVr](https://user-images.githubusercontent.com/51405061/73598704-a36ecc80-454c-11ea-8a56-91a0d134f363.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
