### ISSUE TITLE
[Oracle] Adding notnull to column using alter table causes a checkbox bug

### ISSUE THREAD

**Issue by AlbertKozera** [dbeaver/dbeaver#7804]
System information: 
- Operating system: `Windows 10`
- DBeaver version `6.3.1`
- Additional extensions `none`

#### Connection specification:
- Database name and version: `Oracle 11g`
- Driver name: `ojdbc6`
- Do you use tunnels or proxies (SSH, SOCKS, etc)? `no`

#### Describe the problem you're observing:
If you will change column properties from **not null** to **null** using following script:
`ALTER TABLE table MODIFY column NULL;`
Then that column in table will be updated properly but checkbox will be still set as **not null**

As you can see column isn't set as **not null**
![image](https://user-images.githubusercontent.com/52701021/73606525-638b0200-45ab-11ea-9f9b-382bb80da96f.png)

but checkbox showing it is
![image](https://user-images.githubusercontent.com/52701021/73606482-f5ded600-45aa-11ea-9649-c90e4b2cbbe0.png)

**Comment by uslss** [comment]
Hi @AlbertKozera ,
unfortunately, cannot reproduce an issue. Could you try it against 6.3.4?

**Comment by uslss** [comment]
there is no update on ticket for a long time. ticket closed.
if issue still reproducible for you - feel free to reopen the ticket.
