### ISSUE TITLE
[BUG-PG] Comment on procedure is "comment on function"

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#7805]
When geting the DDL of a procedure in postgresql, if any comment the DDL shows
"COMMENT ON FUNCTION", which is wrong and generates an error when applying the code change in another environment.
Correct should be "COMMENT ON PROCEDURE".

**Comment by megabooster6** [comment]
I confirm the bug is still reproducible with DBeaver 7.0.0.202003021717 and Postgresql 11.6

**Comment by wiwwo** [comment]
Might even got worste: when changing a procedure with a comment (from procedure propery window), it is impossible to save the new proc, since the comment line is shown, but shoinng `function` instead of procedure`

![image](https://user-images.githubusercontent.com/3930671/75860424-185b4d80-5dfc-11ea-85c6-7011226d1d58.png)
etc etc
![image](https://user-images.githubusercontent.com/3930671/75860493-31fc9500-5dfc-11ea-8479-cae5996f3a9c.png)

**Comment by wiwwo** [comment]
(this behaviour  might have been there in the past, cannot guarantee it is new )

**Comment by uslss** [comment]
cannot reproduce it for now. COMMENT ON PROCEDURE is used in mentioned case.
If it is still actual for you - feel free to reopen the ticket

**Comment by wiwwo** [comment]
```
create procedure dummy() 
LANGUAGE plpgsql
as  $procedure$
begin
  select 1;
end
$procedure$

comment on procedure dummy() is 'broken';
```

DBeaver 7.0.4
![image](https://user-images.githubusercontent.com/3930671/81164180-3b3ae700-8f90-11ea-8d77-449c661e50d6.png)

**Comment by wiwwo** [comment]
```
create procedure dummy() 
LANGUAGE plpgsql
as  $procedure$
begin
  select 1;
end
$procedure$

comment on procedure dummy() is 'broken';
```

DBeaver 7.0.4
![image](https://user-images.githubusercontent.com/3930671/81164289-69202b80-8f90-11ea-92a5-35932945a7cc.png)

**Comment by wiwwo** [comment]
But still present in 7.1.0
