### ISSUE TITLE
DBeaver: System setting EXTRA SPACES has no effect when viewing data grid in TEXT and ONE RECORD a time

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#7807]
DBeaver - **Version 6.3.4 CE EA**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

The systemsetting for **Extra spaces** has no effect when viewing a table grid data in text and records as one record a time (ie. vertical grid).

System setting in question is:

&nbsp;&nbsp;**DBeaver** -> **Editors** -> **Presentation** -> **Plain text** -> **Extra spaces**

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
