### ISSUE TITLE
Table of information_schema not showing

### ISSUE THREAD

**Issue by jazuly** [dbeaver/dbeaver#7811]
#### System information: 
- System Operation (Pop!_OS 19.10 (based Ubuntu 19.10))
- DBeaver version (Version 6.3.4.202002011957)

#### Connection specification:
- Database name and version (MySQL 8.0.19-0)
- Driver name (MySQL)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? (nope)

#### Describe the problem you're observing:
i dont know if im missconfigure or anything else.
i can see all tables of my databases but not for table database information_schema?

#### Steps to reproduce, if exist:
i just make local connection and checked "show system object"

#### Include any warning/errors/backtraces from the logs
nothing error.

![Screenshot from 2020-02-03 22-25-57](https://user-images.githubusercontent.com/23066200/73665737-2f5f3080-46d4-11ea-95d2-1d67ef1b4997.png)

how i can fix this?

**Comment by serge-rider** [comment]
There are no table in information_schema, only views.

**Comment by jazuly** [comment]
> There are no table in information_schema, only views.

ya, i cant see list table of information_schema database..
for other databases i can see it..

**Comment by uslss** [comment]
You could see all the views in Views folder
![image](https://user-images.githubusercontent.com/31996417/79771453-77870a00-8337-11ea-937d-e0c5841946a5.png)
