### ISSUE TITLE
dbeaver 6.3.4 on macOS 10.15.3 Catalina fails to open with message "Failed to create the Java Virtual Machine."

### ISSUE THREAD

**Issue by jesimone57** [dbeaver/dbeaver#7812]
#### System information: 
- Operating system (distribution) and version .   macOS version 10.15.3 Catalina
- DBeaver version:  6.3.4 macOS
- Java version : openjdk version "11.0.6" 2020-01-14
- Additional extensions: none

#### Connection specification:
- Database name and version:  mariabDB 10.1
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Steps to reproduce, if exist:
1.  use brew install to get the latest open JDK openjdk version "11.0.6" 2020-01-14
2. download dbeaver macOS version DMG 6.3.4 and install
3. double click on dbeaver in applications
4.  Alert pop-up Failed to create the Java Virtual Machine.

#### Include any warning/errors/backtraces from the logs

Alert pop-up Failed to create the Java Virtual Machine.

**Comment by jesimone57** [comment]
cd /Applications/DBeaver.app/Contents/MacOS
./dbeaver
Error: could not find libjava.dylib
Failed to GetJREPath()

**Comment by dorbae** [comment]
Hell, @jesimone57 
Could you check whether there is '**jre**' directory in your **/Applications/DBeaver.app/Contents/Eclipse** directory.
If '**jre**' directory exists, please, let me know the contents of **Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini** file.

**Comment by jesimone57** [comment]
cat dbeaver.ini
-startup
../Eclipse/plugins/org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar
--launcher.library
../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.1100.v20190907-0426
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx1024m
-XstartOnFirstThread

**Comment by jesimone57** [comment]
there is no jre directory in that dir

pwd
/Applications/DBeaver.app/Contents/Eclipse

ls
configuration	dbeaver.ini	features	licenses	p2		plugins		readme.txt

**Comment by jesimone57** [comment]
i have installed and uninstalled several times both 6.3.3 and 6.3.4.  It looks like the adoptoptjdk 11 latest version is killing it.

**Comment by dorbae** [comment]
@jesimone57 
As you mentioned, there is a problem when DBeaver runs on adoptopjtjdk 11.0.6.
In my case, I run DBeaver on adoptoptjdk 11.0.5 in DBeaver directory and below option is on dbeaver.ini file.

```
-vm
../Eclipse/jre/Contents/Home/bin/java
```

But, I faced the same problem when I set adoptoptjdk 11.0.6 as the path of vm option.
So, I think that there are 2 ways to solve your problem.

* Solution 1. 
  * Downgrade your system default jre 11.0.6 -> 11.0.5
  * If you have other problems from it, try Solution 2.

* Solution 2. 
  * 2.1. [Download 11.0.5 jre](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jre_x64_mac_hotspot_11.0.5_10.tar.gz) and unzip it
  * 2.2. Move 11.0.5 jre directory in **/Applications/DBeaver.app/Contents/Eclipse**
  ```
  mv jdk-11.0.5+10-jre/ /Applications/DBeaver.app/Contents/Eclipse/jre
  ```
  * 2.3. Add this option in your dbeaver.ini file
  <pre>
  <b>-vm</b>
  <b>../Eclipse/jre/Contents/Home/bin/java</b>

  -startup
  ../Eclipse/plugins/org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar
  --launcher.library
  ../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.1100.v20190907-0426
  -vmargs
  -XX:+IgnoreUnrecognizedVMOptions
  --add-modules=ALL-SYSTEM
  -Xms64m
  -Xmx1024m
  -XstartOnFirstThread
  </pre>

<br />

Thank you.

**Comment by jesimone57** [comment]
I downleveled my adopt open jdk to 11.0.5 as suggested from this page:

https://adoptopenjdk.net/archive.html?variant=openjdk11&jvmVariant=hotspot

and was able to bring up dbeaver.   I uninstalled the brew cask and now when I do a brew cask upgrade it will not be updating 11.0.5 to 11.0.6.   That fixes my issue.

As to why DBeaver does not work with 11.0.6 that is another issue.  For now I am sticking with 11.0.5.

Cheers1

**Comment by stephane-dereppe** [comment]
Hi,

If found an easier (for me workaround) [here](https://github.com/dbeaver/dbeaver/issues/6353#issuecomment-584366475)

Just installed a Java 10 version and pointed to it in the `Info.plist` file.

**Comment by sasuw** [comment]
This issue is still around, with dbeaver 7.1.5 on macOS Catalina 10.15.6. I managed to solve it with stephane-dereppe's solution above. I added the following line to the Info.plist

<string>-vm</string><string>/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java</string>

above the line starting with

<string>-keyring

**Comment by nixlim** [comment]
I encoutered this problem today.

Instead of messing with Info.plist, I combined the solutions above:

Per [this solution](https://github.com/dbeaver/dbeaver/issues/7812#issuecomment-581557342) by @dorbae above, I copied the following to the top of `dbeaver.ini`:

**-vm
/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin**

(from @sasuw 's post we learn that basically, it is looking for java executable and version 1.8 would do - and therefore any version below adoptopenjdk11.06 would do, I think).

Like so:

```
-vm
/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin

-startup
../Eclipse/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar
--launcher.library
../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.1100.v20190907-0426
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx1024m
-XstartOnFirstThread
```

Thank you all, worked like a charm :)

**Comment by pcnorb** [comment]
Big Sur upgrade broke mine.

Adding my jdk as @nixlim above suggested worked for me.

`-vm
/Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home/bin`

**Comment by RollsBean** [comment]
@pcnorb same issue, after upgraded Big sur, it didn't work, your solution is works, thanks.

**Comment by bkielbasa** [comment]
any fix for this without this hack? :)

**Comment by gilmar-mmj** [comment]
I was with the same problem, but I uninstalled it and install again using the DBeaver(Installer), and now it is work.
My OS is Mac Big Sur.

**Comment by shivlakhanpatel** [comment]
Steps:
1. Go to Applications from Finder
2. Select DBeaver
3. Click Ctrl+2 finger 
4. Select Show Package Contents, it lands in Contents folder
5. Select Eclipse and look for dbeaver.ini
6. Open dbeaver.ini file and below lines at beginning. Bingo!

> -vm
/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/bin/java

**Comment by nandhini-nataraj** [comment]
>   -vm
>   ../Eclipse/jre/Contents/Home/bin/java

Fixed the issue
