### ISSUE TITLE
Error restore POSTGRES

### ISSUE THREAD

**Issue by msisolucoes** [dbeaver/dbeaver#7813]
pg_restore: error: found unexpected block ID (174744874) when reading data -- expected 14953

If you do it via CMD or pgAdmin4 it works

**Comment by uslss** [comment]
is it reproducible with special data or with any data?

**Comment by msisolucoes** [comment]
[msi_0203.zip](https://github.com/dbeaver/dbeaver/files/4160279/msi_0203.zip)

**Comment by uslss** [comment]
still reproducible against 7.3.4

**Comment by adminsyszg** [comment]
> 
> 
> still reproducible against 7.3.4

reproduceble in version  21.0.2.202104042040

C:\Users\a\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\12\pg_restore.exe --verbose --host=10.3.14.4 --port=5432 ****** --data-only --format=c --dbname=a13dev

Task 'PostgreSQL restore' started at Thu Apr 08 10:52:38 MSK 2021
pg_restore: warning: restoring tables WITH OIDS is not supported anymore
pg_restore: warning: ftell mismatch with expected position -- ftell used
pg_restore: connecting to database for restore
pg_restore: processing data for table "apteka.DEL_ret"
pg_restore: error: found unexpected block ID (-965837764) when reading data -- expected 12960
Task 'PostgreSQL restore' finished at Thu Apr 08 10:52:39 MSK 2021

with option --schema-only restored succesesful

**Comment by sknextcode** [comment]
Like @adminsyszg said:
Reproducable in: Version 21.0.2.202104042040

Schema will be imported, but upon first dataset restore getting:
**pg_restore: error: unrecognized data block type (152) while searching archive**

Used different Postgres binaries (last used was psql (PostgreSQL) 13.2), but getting same error. Using Pg Admin or cmd.exe (Windows 10) is working fine with same binaries.

However: Using same dBeaver Version on MAC OS X is working fine when restoring, so it seems to be Windows 10 related in combination with dBeaver.

Checked old backups too that where already approved: Same error.

**Comment by SergioSuarezGil** [comment]
same here on windows dbeaver 21.0.2
**pg_restore: error: found unexpected block ID (2116052607) when reading data -- expected 4803**

**Comment by sknextcode** [comment]
Just tried with new version 21.0.3.202104181339 just in case (no mentioned bugfix in changelog, but bugfix on read of array datatype), but error remains.

**Comment by diracsol** [comment]
Issue remains. I got this error message "pg_restore: error: found unexpected block ID (939559745) when reading data -- expected 4600". Any fix??

**Comment by flambchap** [comment]
The fix is scheduled for the next release.

**Comment by flambchap** [comment]
The problem turned out to be a lot harder to resolve than we expected. It's related to our mechanism which shows the progress for dump/restore tasks. We've decided to disable it as a temporary measure.

**Comment by Matvey16** [comment]
Verified

**Comment by elsheikh21** [comment]
for anyone who might be facing the problem of not being able to push their local postgreSQL to heroku (WINDOWS), hear me out

 1. Create an Addon on Heroku using GUI or CLI
 2. OPEN CMD AS ADMINISTRATOR 
 3. First, `dump` SCHEMA ONLY using `pg_dump -s -f <DB_OUTPUT_NAME_ONLY_SCHEMA> --no-owner --no-acl -U <USERNAME> <LOCAL_DB_NAME>`
 4. SECOND, restore your db on heroku using `heroku pg:psql --app <APP_NAME> < <DB_OUTPUT_NAME_ONLY_SCHEMA>`
 5. THIRD, `dump` **DATA ONLY** using `pg_dump -a -f <DB_OUTPUT_NAME_ONLY_DATA> --no-owner --no-acl -U <USERNAME> <LOCAL_DB_NAME>`
 6. FORTH, restore your data on heroku using`heroku pg:psql --app <APP_NAME> < <DB_OUTPUT_NAME_ONLY_DATA>`
