### ISSUE TITLE
AWS Athena: display error line number in relation to the entire script

### ISSUE THREAD

**Issue by Camden-Lee** [dbeaver/dbeaver#7815]
**Is your feature request related to a problem? Please describe.**
The problem is that when debugging, the error message shows the line number from the statement block, but in a large script with many statements or essentially anytime the statement being run doesn't start on the first line, the statement line number isn't that immediately helpful. It's too frustrating when the "offset" between the statement line and the error line is minimal, but it get's more annoying when the offset is larger. 

![Screen Shot 2020-02-03 at 11 43 15 AM](https://user-images.githubusercontent.com/42618819/73685189-99e38280-467a-11ea-9ec6-1c9711adac39.png)

![Screen Shot 2020-02-03 at 11 49 57 AM](https://user-images.githubusercontent.com/42618819/73685698-766d0780-467b-11ea-8c19-d7bf0789e00b.png)

**Describe the solution you'd like**
I think it would be really helpful if the error line number in relation to the entire script was included in the error message. 

**Describe alternatives you've considered**
I could keep doing the mental math. If the highlighting jumped to the "right" spot in the editor then maybe the error line number in the message wouldn't matter as much.

**Additional context**
I'm connecting to an Athena DB.

**Comment by serge-rider** [comment]
Done.
This feature is already presents for many other databases, Athena support was added.

**Comment by uslss** [comment]
verified

**Comment by Camden-Lee** [comment]
So awesome...thank you!! 🙏
