### ISSUE TITLE
Error Where clause("case when end" statement)

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#7816]
System Information:

* Operation System
 Windows 10
* DBeaver version
 6.3.4
* Additional extensions
 No
* Connection specification:

* Database name and version
 Oracle 12c
* Driver name
 Oracle JDBC Driver
*Do you use tunnels or Proxies(SSH, SOCKS, etc) ?
 No

An error occurs a DBeaver 6.3.4

An error occurs if you use the "CASE WHEN END" statement at the end of the "WHERE" clause.

For example

**Error...**
```
SELECT 'SUCCESS' 
  FROM dual
 WHERE 1 = 1
   AND 'Y' = CASE WHEN 'Y' = 'Y' THEN 'Y' ELSE 'N' END
;
```
![image](https://user-images.githubusercontent.com/59002295/73719453-d8546c80-4762-11ea-8b2a-71db7d116bea.png)

**Not Error**
```
SELECT 'SUCCESS' 
  FROM dual
 WHERE 1 = 1
   AND 'Y' = CASE WHEN 'Y' = 'Y' THEN 'Y' ELSE 'N' END
   AND 1 = 1           ---------- Add condition
;
```
Perhaps there is a problem with the case when parsing the where clause.

Thanks for reading.

**Comment by uslss** [comment]
thanks for the bug report.
as a workaround, you could use **end** word in lower case

**Comment by podoni** [comment]
> thanks for the bug report.
> as a workaround, you could use **end** word in lower case

thanks for reply.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
