### ISSUE TITLE
DB2 to MySQL database migration: Syntex error

### ISSUE THREAD

**Issue by subesingh1981** [dbeaver/dbeaver#7817]
Detail: 
Error starting data transfer
  Can't create target table:

    SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1048576),
                is_internal VARCHAR(1),
                created_on BIGINT NOT NULL,
                created_by INT' at line 5
    SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1048576),
                is_internal VARCHAR(1),
                created_on BIGINT NOT NULL,
                created_by INT' at line 5
      You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1048576),
                is_internal VARCHAR(1),
                created_on BIGINT NOT NULL,
                created_by INT' at line 5
      You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1048576),
                is_internal VARCHAR(1),
                created_on BIGINT NOT NULL,
                created_by INT' at line 5

#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.3.4 Community version
- Additional extensions: None

#### Connection specification:
- Database name and version: DB2(Dash DB)  and MySQL 8.0.19 community server
- Driver name: Db2cc.jar, MySQL JDBC Driver(MySQL Connector JAVA 8.0.19.jar)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
This is no exactly a bug. 
DBeaver failed to determine correct target data type for MySQL column, But you can set target data type in columns mapping dialog/tree.

Current type detector will be improved in #7745 but it won't be started till 7.0 release.

**Comment by LonwoLonwo** [comment]
@subesingh1981 Hello
Can you check, please, [new DBeaver version](https://dbeaver.io/). Is problem still actual?
If so, what DDL did the exported table have?
Thanks for advance!

**Comment by LonwoLonwo** [comment]
There was no response for a long time, so the ticket is closed.
You can reopen the ticket if the problem occurs again.
