### ISSUE TITLE
Could you please share the steps migrate DB2 database into MySQL using DBeaver?

### ISSUE THREAD

**Issue by subesingh1981** [dbeaver/dbeaver#7818]
Hi,

Could you please share the steps migrate DB2 database into MySQL using DBeaver?
We need to migrate Tables, Views, Sequence, Triggers, PL/SQL procedures and functions.

#### System information: 
- Operating system (distribution) and version: Linux
- DBeaver version: 6.x

#### Connection specification:
- Database name and version: DB2(Dash DB) and MySQL Latest version

**Comment by uslss** [comment]
Hi @subesingh1981 ,
you could try Compare/Migrate Tools in our EE version. (https://dbeaver.com/)
