### ISSUE TITLE
DBeaver Unique Key Handling With Snowflake

### ISSUE THREAD

**Issue by BarneyLawrence** [dbeaver/dbeaver#7820]
**Issue**
DBeaver's interface allows for the display and creation of primary keys on tables but not unique keys. This is limiting both in that the only way to gain a full picture of a table's properties is through reading the raw DDL and that to create a unique key it must be either coded by hand or created as a primary key and then edited.
Virtually all our tables require both types of keys because while Snowflake does not enforce these constraints at present we are using the two key types to identify synthetic and business keys within out data vault implementation helping to make the design clearer from within the database. 

**Solution**
My ideal solution would be for the Unique Keys section of DBeaver to display both primary and unique keys and offer an option to create either. The current context menu in this section gives a 'Create Unique Key' option but this only creates a primary key. I would suggest either a second option in the context menu or the ability to choose between primary and unique keys under the existing process.

**Alternatives**
The only alternative I can find at present to identify business keys is to view the full table creation statement in the DDL tab of the table view. TO create them we either edit this DDL statement and run it or we use the DBeaver interface to create a primary key and then edit the statement to create a unique key.

**Supporting Information**
We have noticed from the query history that DBeaver uses the following command to identify the columns used within the unique key of a table:
`show /* JDBC:DatabaseMetaData.getPrimaryKeys() */ primary keys in table [Table Name]`
Show is a documented command but primary keys are not covered as an object it applies to. I have discovered that the following provides a list of business keys and columns involved in them. This would be a possible option to allow the needed source data to be collected.
`show unique keys in table [Table Name]`

**Comment by LonwoLonwo** [comment]
UK support implemented in EE Dbeaver version for Snowflake.

![2021-09-15 10_47_08-DBeaver Enterprise 21 2 1 - UK](https://user-images.githubusercontent.com/45152336/134339842-1bee4e94-c926-4523-b0c8-6880551b2461.png)

Unique keys are in a special tab in the table viewer. They can be created via UI.

Also, better schema support is implemented in the EE version.

More schema information in Schema tab, ability to create and delete schemas via UI. Ability to add a comment to schema via UI added. And the ability to change some schema parameters.

![2021-09-15 10_32_36-TEST_AS - Persist Changes](https://user-images.githubusercontent.com/45152336/134340046-0f866204-e22a-4b0b-8db5-a7d42a05abe9.png)

**Comment by Matvey16** [comment]
Verified
