### ISSUE TITLE
Error message "Not connected to database" when executing from script editor

### ISSUE THREAD

**Issue by mefernandez** [dbeaver/dbeaver#7822]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04.4
- DBeaver version: 6.3.4
- Additional extensions: None

#### Connection specification:
- Database name and version: Sybase ASE 11
- Driver name: jtds
- Do you use tunnels or proxies (SSH, SOCKS, etc)? yes

#### Describe the problem you're observing:
Can't execute SQL in editor.

#### Steps to reproduce, if exist:
1. Connect to database. A database is selected as active object.
2. Open new SQL editor
3. Write "select 1"
4. CTRL+ENTER
5. Get a window with error message "Not connected to database"
6. Database selector above editor shows "N/A"
7. Pick a database from list
8. Still shows "N/A"
9. Still get a window with error message "Not connected to database"

**Comment by mefernandez** [comment]
# Additional info

I've just installed version 6.3.1 and it works just fine.

**Comment by alFReD-NSH** [comment]
I had a the same exact problem and downgrading to 6.3.3 solved it for me.

System information:

- Operating system (distribution) and version: MacOS 10.14.6
- DBeaver version: 6.3.4
- Additional extensions: None

Connection specification:

- Database name and version: Redshift
- Driver name: AWS / Redshift
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

**Comment by SprdNils** [comment]
I also have the same problem:

System information:

    Operating system (distribution) and version: Ubuntu 18.04
    DBeaver version: Version 6.3.4.202002011957
    Additional extensions: None

Connection specification:

    Database name and version: Mysql
    Driver name: MySQL Connector Java mysql-connector-java-5.1.38 ( Revision: fe541c166cec739c74cc727c5da96c1028b4834a )
    Do you use tunnels or proxies (SSH, SOCKS, etc)? no

**Comment by umphy** [comment]
I have the same problem with Sybase ASE.

System information:
-     Operating system: Windows 10
-     DBeaver version: 6.3.4

Connection specification:
    Database name and version: Sybase ASE 15
    Driver name: Sybase jConnect 7.0
    Do you use tunnels or proxies (SSH, SOCKS, etc)? no

**Comment by serge-rider** [comment]
I can't reproduce this.
Possibly it was caused by change of default preference settings. Now we open separate connection for each SQL editor.
There was a bug in this procedure (no error message was shown is separate connection open fails).

1. Try to disable "Open separate connection option":
![image](https://user-images.githubusercontent.com/6398845/74110658-6c796600-4b9f-11ea-9cd4-216e3c683951.png)

2. If it doesn't help - please attach error/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by umphy** [comment]
I can confirm that it is now working with the above config disabled. Thanks @serge-rider

**Comment by serge-rider** [comment]
@umphy thanks for testing. I think we have to make this option more obvious (or less hidden). As it may cause problems in some environments (e.g. when connection number is very limited).

Perhaps we need this option somewhere in the main menu/toolbar.

**Comment by garethnic** [comment]
@serge-rider your suggestion helped resolve this issue for me. Thank you.
