### ISSUE TITLE
Can I use custom variable in bootstrap queries? 

### ISSUE THREAD

**Issue by yonarad** [dbeaver/dbeaver#7823]
Hi,
I want to run query right after the connection started.
I see the Connection settings->Initialization>Bootstrap queries
I see that I can use predefined variables there.
I want to ask:
Can I use variables that I created?
I tried to set user properties in driver properties section and access it in bootstrap using ${my_parameter}, but did not see that it worked.

Can you help me please?

Thanks!

**Comment by kseniiaguzeeva** [comment]
Try using environment variables. This should work.
