### ISSUE TITLE
how to disable greeting window

### ISSUE THREAD

**Issue by verajosemanuel** [dbeaver/dbeaver#7829]
working with i3 window manager here. When opening DBeaver the greeting window get stuck and I have to move to other workspace to use DBeaver.

is there any option to disable the greeting window at init?

**Comment by fabianMendez** [comment]
What do you mean by the greeting window?

Is it the tip of the day window?

If so you can disable it by changing the following property in the `WORKSPACE/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.jkiss.dbeaver.core.prefs` file:

```properties
ui.show.tip.of.the.day.on.startup=false
```

**Comment by verajosemanuel** [comment]
No. Not the tip. A window with an image and artwork saying "dbeaver
community" and a progress bar

**Comment by fabianMendez** [comment]
Oh, that is the splash screen.

You can disable it by putting `-nosplash` in the first line of the `dbeaver.ini` file inside your DBeaver installation directory
