### ISSUE TITLE
Dbeaver gets stuck while doing a database backup

### ISSUE THREAD

**Issue by dramirezgmd** [dbeaver/dbeaver#7830]
#### System information: 
- Windows 10 Pro
- Dbeaver 6.3.4

#### Connection specification:
- Postgresql 11
- No tunnels or proxies  

#### Problem:

While doing a backup, Dbeaver gets stuck in the backup log screen. The log screen shows the command that Dbeaver executes to do the backup. If I copy that command to the window's command line, the command executes but asks me a password. 

#### Steps to reproduce:

1. Choose postgresql as a database manager
2. Add a database connection
3. Right-click the database then choose tools, backup, click start

**Comment by serge-rider** [comment]
Can't reproduce.

**Comment by uslss** [comment]
if issue is still actual for you - feel free to reopen the ticket

**Comment by WoLfulus** [comment]
Also happening for me

**Comment by pascaldls** [comment]
Happening For me Too 
when selected tar

**Comment by umbe1987** [comment]
> Happening For me Too
> when selected tar

thumbs up for the "tar" thing.  I did not try with other formats as I realized after killing dbeaver process and restarting it that my tables were restored in the remote db, but it would be interesting to test...

**Comment by soninishank** [comment]
Happening for me too. Its stuck from last 30 mins. 

![Screenshot 2023-09-13 at 6 15 14 PM](https://github.com/dbeaver/dbeaver/assets/39820546/33e395aa-0eb7-42ff-8c19-883b1d61fb7e)

**Comment by soninishank** [comment]
using latest version of dbeaver and postgres 14.7

**Comment by AnthonyTsang** [comment]
happens to me

OS: macOS Sonnoma 14.1
DBeaver 24.0.3
DB: Aurora PostgreSQL 14.9
Client: libpq 16.2_1

**Comment by icaroperetti** [comment]
> Happening for me too. Its stuck from last 30 mins.
> 
> ![Screenshot 2023-09-13 at 6 15 14 PM](https://github.com/dbeaver/dbeaver/assets/39820546/33e395aa-0eb7-42ff-8c19-883b1d61fb7e)

Happening to me

OS: Windows 11
DBeaver: 26.2.0.202608301738
Postgres: 15

It get stuck in the same screen
