### ISSUE TITLE
Darkest dark theme

### ISSUE THREAD

**Issue by jamesRUS52** [dbeaver/dbeaver#7832]
How to change color of menu bar and scrollings to dark color in darkest dark theme?
and light borders around the fields?
it looks strange in dark theme

![darkest dark](https://user-images.githubusercontent.com/39707635/73783968-aca6a600-47a5-11ea-9a95-1125be6fa5fc.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for your question. It doesn't look very pretty.

**Comment by serge-rider** [comment]
I'm afraid we can'f fix this. All customizations come from DarkestDark and/or Eclipse Dark theme .
