### ISSUE TITLE
Commit Errors

### ISSUE THREAD

**Issue by Jnb2387** [dbeaver/dbeaver#7833]
#### System information: 
- Operating system (distribution) and version Linux Mint 19.2
- DBeaver version 6.3.4 but had this issue for the last couple releases
- Additional extensions

#### Connection specification:
- Database name and version Postgres Multiple Version and happens on all (9.5, 10, 12)
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Something changed recently for Postgres commits. Auto commit keeps turning off and switching to manual with no warning, Postgres states an update occurs but it did no persist through, and will not show in the table until manually switching back to auto-commit. 
#### Steps to reproduce, if exist:
Update a record in the database, it happens randomly and I can not find what triggers it.

**Comment by uslss** [comment]
Probably, ypu've got smart commit mode enabled?
![image](https://user-images.githubusercontent.com/31996417/73821734-a21bf900-4805-11ea-8c6c-64bb434c3854.png)

**Comment by Jnb2387** [comment]
@uslss, I do not and have never enabled smart commit. Just today I was editing a table via the data editor and also using sql updates and it switch from auto-commit to manual commit, the only way I would know this is if I query an end or the commit tab at the top changes from Auto to None, even though I did not make any changes
![image](https://user-images.githubusercontent.com/17630656/73857513-485f0300-47f4-11ea-993a-a7b9d8f1a861.png)

**Comment by uslss** [comment]
still cannot reproduce an issue. if it is still actual for you against recent version - feel free to reopen the ticket
