### ISSUE TITLE
Driver name disappears and hence not able to load

### ISSUE THREAD

**Issue by rajputvishwas** [dbeaver/dbeaver#7836]
#### System information: 
- Operating system (distribution) and version: Windows 10 x 64 bit
- DBeaver version: 6.3.4
- Additional extensions 

#### Connection specification:
- Database name and version: Apache Ignite 2.7.0
- Driver name: org.apache.ignite.IgniteJdbcThinDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
I want to connect to Apache Ignite and following steps given at [readme](https://apacheignite-sql.readme.io/docs/sql-tooling). 

First I am configuring Driver using Driver Manager
![image](https://user-images.githubusercontent.com/15668995/73818127-af8bb000-4812-11ea-99b7-b3c1386401ab.png)

While creating database connection, when I click on test connection
![image](https://user-images.githubusercontent.com/15668995/73818449-6d16a300-4813-11ea-8fe9-81bf63719654.png)

It says can't load driver. When I click edit driver I found that the driver name is missing when I click on find class then only class names comes up, but this is temporary.  As soon as I closed driver tab driver name dis appears.

![image](https://user-images.githubusercontent.com/15668995/73818572-a9e29a00-4813-11ea-86d5-140945a28868.png)

**Comment by intheravine** [comment]
I have the same issue in DBEE 7.0.4 - the driver class is not saved and thus cannot be used in DBeaver.

**Comment by serge-rider** [comment]
This is Ignite driver issue, it is described here: https://stackoverflow.com/questions/50639471/using-ignite-on-jdk-9
Hopefully it will be fixed in future versions of Ignite driver.

Workaround: 
Add following lines in the end of dbeaver.ini file:
```
--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED 
```
