### ISSUE TITLE
Data export to SQL does not work as expected

### ISSUE THREAD

**Issue by Alterant-zz** [dbeaver/dbeaver#7837]
#### System information: 
- Windows 10 Pro 1909
- DBeaver version 6.3.4.202002011957
- Java version 11

#### Connection specification:
- PostgreSQL 11.6, compiled by Visual C++ build 1914, 64-bit
- Driver: PostgreSQL, org.postgresql:postgresql:RELEASE, 42.2.5
- No tunnels or proxies (SSH, SOCKS, etc)

#### Describe the problem you're observing:
Have a table with 17967 records.
Data export to CSV works as expected.
But Data export to SQL produces only 14956 number of rows. Taking into account that there are 2 extra rows per statement there should be approx. 19400 linrs in the file.
The file content is strange. On the the row 1798 there are 491515 NUL symbols.
Export settings:
Table settings:
	Open new connection(s): No
	Extract type: SINGLE_QUERY
	Select row count: Yes
	Selected rows only: No
	Selected columns only: No
Files settings:
	Write to the single file: No
	Directory: D:\Temp
	File name pattern: ${table}_${timestamp}
	Encoding: UTF-8
	Timestamp pattern: yyyyMMddHHmm
	Insert BOM: No
	Compress: No
	Binaries: SKIP
	Encoding: HEX
SQL settings:
	Include generated columns: false
	File extension: sql
	Dates/numbers format: native
	Omit schema name: false
	Data rows per statement: 25

**Comment by Alterant-zz** [comment]
Table structure is quite simple:
CREATE TABLE public.city (
	id int8 NOT NULL,
	"name" varchar(255) NOT NULL,
	national_code varchar(255) NOT NULL,
	active bool NOT NULL,
	deleted bool NOT NULL,
	region_district_id int8 NULL,
	region_id int8 NOT NULL,
	country_id int8 NOT NULL,
	CONSTRAINT city_pkey PRIMARY KEY (id)
);

ALTER TABLE public.city ADD CONSTRAINT fk_city_country_id FOREIGN KEY (country_id) REFERENCES country(id);
ALTER TABLE public.city ADD CONSTRAINT fk_city_region_district_id FOREIGN KEY (region_district_id) REFERENCES region_district(id);
ALTER TABLE public.city ADD CONSTRAINT fk_city_region_id FOREIGN KEY (region_id) REFERENCES region(id);

**Comment by Alterant-zz** [comment]
The same for 6.3.5.202002151353.
Screenshots attached.
![PGExportCSV](https://user-images.githubusercontent.com/1001060/74628626-2f950c80-5167-11ea-9944-d34091c28052.png)
![PGExportSQLBegin](https://user-images.githubusercontent.com/1001060/74628641-3885de00-5167-11ea-8e65-9b2bac49ddcd.png)
![PGExportSQLCont](https://user-images.githubusercontent.com/1001060/74628652-40458280-5167-11ea-9022-66a3704f8907.png)

**Comment by uslss** [comment]
cannot reproduce an issue.
if issue is still actual for you - feel free to reopen the ticket
