### ISSUE TITLE
Export Data task number format issue

### ISSUE THREAD

**Issue by ntoumpan** [dbeaver/dbeaver#7838]
Hello, 

I created a export data task in csv file format and in the export settings I use the same export profile I use "export from Query" option.
My settings are Locale german in order to have the number decimal format as comma.

For some reason when I export data from the "Export from Query" option the number format is correct (Decimal is ",") but when I export from the created task the decimal is "."
All export settings are the same , the query is the same so I can't figure out what is the problem.

Note that the default Locale after the initial installation was English so is like the export task uses the default no matted what the export settings of the task is.

Can you help me with this problem?

Thank you

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed (the bug was in incorrect option "formatNumbers" parse.

**Comment by uslss** [comment]
verified
