### ISSUE TITLE
Unable to import CSV file with czech number format

### ISSUE THREAD

**Issue by zeleznypa** [dbeaver/dbeaver#7839]
In the Czech Republic, we are using different number delimiter between integer and float, the comma character and space character as a separator of thousands (groups).

So the number can look like this "10 237,65" 

But the DBeaver have no possibility to set up the character that is used for, so every float numbers are rounded in the import of CSV file.

**Comment by Darker** [comment]
This doesn't sound like a valid CSV file though. The comma delimiter is used to separate individual values. Is there a chance you could use different settings when exporting the CSV?

**Comment by zeleznypa** [comment]
@Darker Because you can change the delimiter even in the DBeaver to the ";" character, it is no problem to use the "," to separate the parts of a number.

Sure you can change the import data as a "hotfix" for this case, but the problem of "missing possibility to set up the "," as a delimiter to show in the output, to export and to import" still persist.

**Comment by patrickmdnet** [comment]
Possible dup of #7153

**Comment by uslss** [comment]
duplicates #6997
