### ISSUE TITLE
I need use .pgpass during connect to PostgreSQL database

### ISSUE THREAD

**Issue by mshurutov** [dbeaver/dbeaver#7841]
Hello

As I described in subject, I need use ~/.pgpass file to store passwords for access to any databases on any PoastgreSQL servers, because I have several thousand databases on hundreed  servers. So it is difficult to enter credentials (username / password) twice.
I see checkbox "use ~/.pgpass" (on UNIX-like systems). If this checkbox is active, thenfield "password" should be inactivity.

Sorry for my English

UPD. Link to docs (current PostgreSQL): https://www.postgresql.org/docs/current/libpq-pgpass.html

**Comment by mkgrgis** [comment]
https://postgrespro.ru/docs/postgrespro/12/libpq-pgpass

**Comment by serge-rider** [comment]
This feature can be implemented only after #2092 . 
We need some extra UI to configure source of user name/password.

We'll start doing it after 7.0 release.

**Comment by serge-rider** [comment]
In fact we don't need user profiles. We need special auth model for pgpass (#8128).

**Comment by serge-rider** [comment]
Done

**Comment by uslss** [comment]
verified
