### ISSUE TITLE
DBeaver FR: Add setting to not include HTML table header when using Open With Web browser

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#7845]
DBeaver - **Version 6.3.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

It would help me if there where som system setting checkbox where I could set/clear if I want the HTML page shown when using the context menu **Open With** -> **Web browser** should include a table header or not.

Some time after *DBeaver* version **6.0.0 CE** the rendered HTML page was changed so that it now include a table header stating either the table name or the SQL query executed, this followed with a grid for the selected data grid columns.

I sometimes send the HTML document to customer when requested to generate some special report. Now I have to edit the HTML document to remove the table header.

**Comment by uslss** [comment]
verified
