### ISSUE TITLE
Native client not found when backing up or restoring Postgres 11 database

### ISSUE THREAD

**Issue by jdudley1123** [dbeaver/dbeaver#7846]
#### System information: 
- Windows 10 Home 1909 64bit
- DBeaver version 6.3.4.202002011957

#### Connection specification:
- PostgreSQL 11 (on Heroku)
- PostgreSQL JDBC Driver

#### Describe the problem you're observing:
When trying to make a backup of a Postgres 11 database, or restoring one, I get the following error:

```
Task execution failed

Reason:
Native client home 'postgresql-x64-11' not found
```

#### Steps to reproduce, if exist:
Right click on a database -> tools -> backup
Select all views
Click start

OR

Right click on a database -> tools -> restore
Select backup file
Click start

#### Include any warning/errors/backtraces from the logs
```
2020-02-05 18:33:54.614 - org.jkiss.dbeaver.model.exec.DBCException: Native client home 'postgresql-x64-11' not found
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateClientHome(AbstractNativeToolHandler.java:104)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:229)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:52)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

#### Partial workaround
Changing the client in the backup process to `PostgreSQL Binaries` as suggested here https://github.com/dbeaver/dbeaver/issues/4106#issuecomment-416759677 seems to resolve the backing up part of the problem. However, when restoring from a backup created in this way and using `PostgreSQL Binaries` for the client, I get an error saying `[archiver] input file does not appear to be a valid archive`

**Comment by nickyapp** [comment]
can you solve it ?

**Comment by Tri125** [comment]
If you click "Client..."
![image](https://user-images.githubusercontent.com/2048645/74270217-d6e1f180-4cd8-11ea-9c11-5863adc2bd93.png)

and then select the empty value in the dropdown:
![image](https://user-images.githubusercontent.com/2048645/74270246-e3664a00-4cd8-11ea-8cec-7e69c882dcef.png)

you can then restore/backup.

**Comment by jyupanquil** [comment]
I solved this by adding a new home directory. At first followed the steps @Tri125 recommended, selecting browse instead of the blank option, then clicked the **Add Home** button and selected the bin directory (**C:\Program Files\PostgreSQL\12\bin** in my case) then selected that created home as the client to do the backup and it worked fine.
![image](https://user-images.githubusercontent.com/44411479/79680480-b56c1d00-81d5-11ea-8de9-75605a2aa420.png)
Note: the **PostgreSQL 12** home directory was pointing to **C:\Program Files\PostgreSQL\12\**

**Comment by mrtonks** [comment]
I was having the same problem just now and what @jyupanquil suggested worked perfectly in my Windows 10 env.

**Comment by ITHALADQ** [comment]
It worked well. Click the client button.

**Comment by wub** [comment]
On macOS with PostgreSQL installed via homebrew, you can click on "Local Client...", click on the dropdown, click "Browse...", click "Add Home", press CMD+shift+G to open the folder jumper, then navigate to `/opt/homebrew/bin`, and add that folder.

**Comment by hf-krechan** [comment]
@wub thank you very much. You saved my day 👍

**Comment by przzz27** [comment]
Adding to wub's answer in MacOS (Catalina) i had to find the bin folder at  (Ex)`/usr/local/Cellar/postgresql@14/14.5_5`, not sure if the path would be the same for further versions like Monterey

**Comment by maxi-89** [comment]
if you type in a terminal pg_config --bindir. this command give you the path to psql home. then you can add the home path in local client config.

**Comment by sanchezzzhak** [comment]
step 1 instal postgress
install posgress-client https://www.postgresql.org/download/linux/ubuntu/
step 2 install psql client is not exist command
```
sudo apt-get install -y postgresql-client
```
step 3
set local client  `/usr/bin` for add home button for dbeaver
![image](https://github.com/dbeaver/dbeaver/assets/1337066/651f6055-8db4-40ac-ad8a-bce5b8d84b0f)

**Comment by popovs** [comment]
For DBeaver 23.2+ (and possibly also lower versions), there is no option to choose a client in the 'Restore' GUI. I've tried adding all the paths I can think of to the 'Native Client' pane as suggested in above replies (Right click connection > Edit connection > Connection Settings/Main > Driver Settings > Native Client) to no avail. Still getting "Native client home '/usr/local/Cellar/postgresql@14/14.1_1' not found" despite the fact that I have only Postgres 13 installed.

**EDIT:** Got it to work by specifying which version of SQL to use under "Connection Settings / Main / Advanced / Local Client" !

*DB Connection settings*
<img width="1176" alt="image" src="https://github.com/dbeaver/dbeaver/assets/19844383/720a4087-03d8-4173-ba3c-826491338830">


*Restore pane*
<img width="1106" alt="image" src="https://github.com/dbeaver/dbeaver/assets/19844383/3308f5c0-7e04-4929-a820-92165489cc9d">

*DB client homes pane*
<img width="943" alt="image" src="https://github.com/dbeaver/dbeaver/assets/19844383/c613f3f7-0620-4893-b09c-193fb9da5f21">

**Comment by sekroots** [comment]
Hello. I am trying to use dbeaver to backup a postgres 12 but I cannot use it.

I configured local client to /usr/bin and it automatic loaded it ( /run/user/1000/doc/6f337d65/bin ) but It failed to use it.

HOW CAN I SOLVE THIS MESS PLEASE?
