### ISSUE TITLE
DBeaver FR: Disable Auto SQL Assistant/Completion for table aliases

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#7847]
DBeaver - **Version 6.3.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

The automatic **SQL Assistant/Completion** annoyingly suggest table names for table aliases, this should not be done.

**1**) Start to write "**SELECT * FROM MyTable MT**"
**2**) If you now stop typing (with our *DBeaver* configuration there is a 500ms delay),
&nbsp;&nbsp;&nbsp;&nbsp;the automatic **SQL Assistant** pops up and suggest  table names that start with "MT".

The automatic **SQL Assistant** should stop to suggest database tables when I start to write table aliases.

**Comment by kseniiaguzeeva** [comment]
Thank you for your suggestion.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
