### ISSUE TITLE
MySQL 8.x - DEFAULT_GENERATED appears in "Extra" column and causes errors on further edits

### ISSUE THREAD

**Issue by Darker** [dbeaver/dbeaver#7850]
#### System information: 
- OS: Win 10 Pro
- DBeaver version: 6.3.4.202002011957

#### Connection specification:
- MySQL server 8.0.15
- MySQL 8+

#### Describe the problem you're observing:

If I create and persist a new column like this:

![image](https://user-images.githubusercontent.com/5508988/73877780-95c18b80-4859-11ea-9711-1db8eda0bad2.png)

Then the extra column will contain `DEFAULT_GENERATED`. Trying to edit further, like add a comment, causes error:
```
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT_GENERATED NOT NULL COMMENT 'test'' at line 1
  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT_GENERATED NOT NULL COMMENT 'test'' at line 1
  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT_GENERATED NOT NULL COMMENT 'test'' at line 1
```
The SQL query is:

```
ALTER TABLE my_db.my_table MODIFY COLUMN test_time timestamp DEFAULT CURRENT_TIMESTAMP DEFAULT_GENERATED NOT NULL COMMENT 'test';
```

I don't know much about databases, so I'm not sure what the `DEFAULT_GENERATED` is.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by Darker** [comment]
Interesting observation: When I ask DBeaver to export me the whole table as a query, this error is not there. The query is correct.

**Comment by uslss** [comment]
cannot reproduce it anymore
