### ISSUE TITLE
Can I make the SQL editor the default double-click action when clicking on a connection?

### ISSUE THREAD

**Issue by int-a** [dbeaver/dbeaver#7851]
I'm using the Mac version of dbeaver. Basically I have a bunch of SQL server connections and want the default action when I double click on them to be what's currently assigned to `F3`, open a SQL editor on the main database. Currently it expands the connection and shows me the database, users, administer, and system info folders.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/73946661-55b8e200-4907-11ea-92e3-b3a16eaf335e.png)
