### ISSUE TITLE
How could I change sql editor behavior about apostrophe

### ISSUE THREAD

**Issue by moron-gay** [dbeaver/dbeaver#7852]
i'm using window dbeaver
in some time
i have sql like SELECT * FROM XXX WHERE OOO = :parameter
the question is that when i type apostrophe
expected SELECT * FROM XXX WHERE OOO = ''
BUT lastest version become
SELECT * FROM XXX WHERE OOO = ':parameter'

how can i turn of this option

**Comment by kseniiaguzeeva** [comment]
Sounds like a bug. What database do you use?

**Comment by moron-gay** [comment]
> Sounds like a bug. What database do you use?

sql server

**Comment by kseniiaguzeeva** [comment]
I re-read your issue again and I'm not sure that understood you correctly. Could you right steps to reproduce or make a video?

**Comment by moron-gay** [comment]
> I re-read your issue again and I'm not sure that understood you correctly. Could you right steps to reproduce or make a video?

[https://i.imgur.com/0raSVDZ.jpg](url)
[https://i.imgur.com/iL1w3QM.jpg](url)
[https://i.imgur.com/S7cmDX6.jpg](url)

but I just expected SELECT * FROM XXX WHERE OOO = ''
so I need to clear every parameter first

**Comment by serge-rider** [comment]
@moron-gay please copy-paste or drag-n-drop images (not image urls) directly in the comment area.
Otherwise it is very hard to understand your use-case.

**Comment by serge-rider** [comment]
You can disable this behavior in preferences:
![image](https://user-images.githubusercontent.com/6398845/81074609-e9438400-8ef1-11ea-9785-335158caa369.png)

Note: you need to reopen SQL editor to let these changes take effect.
Note2: I've pushed enhancement: now preference change will be applied immediately.

**Comment by uslss** [comment]
verified
