### ISSUE TITLE
Add PostgreSQL-specific generate SQL

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#7853]
I am talking about:

Specific-merge: insert ... on conflict do update ... excluded
Specific delete: DELETE FROM table USING another_table
Specific update: update .. from ...

![gensql](https://user-images.githubusercontent.com/11477081/73916037-aa3f6b80-48cd-11ea-9742-2a612fd4a0b8.png)

PS: It may require additional user's input, e.g. "specific delete" needs to request "another_table" real name, thus field list should be generated from primary key columns...

**Comment by serge-rider** [comment]
Please write full examples of these queries.

We'll introduce SQL generators model in the next version. So it will be easy to add new generators (global or database-specific). But I need more precise examples.

**Comment by plotn** [comment]
1. Update with merge syntax is:
Vanilla doc: https://postgrespro.ru/docs/postgresql/9.6/sql-insert
How I think it should work:
insert into [selected_table] ([field_list])
select [field_list] from [another_table]
on conflict ([comma_separated_key_field_list_from_selected_table]) do //nothing [I think it would be useful to put it here - "commented nothing"]
update set
non_key_field_1 = excluded.non_key_field_1
non_key_field_n = excluded.non_key_field_n

Notes: selected table should not be "aliased", though [another_table] - can be.
Suggested user input - "selected table" (via select from tree), "another table" - via user input or, possible, via double select from tree (though it is too complicated), "another table alias" - it could be useful.

**Comment by plotn** [comment]
2. Update from syntax:

UPDATE [selected_table]
SET non_key_field_1 = [another_table].non_key_field_1,
 non_key_field_n = [another_table].non_key_field_n
FROM
   [another_table]
WHERE
   [another_table].key_field_1= [selected_table].key_field_1 and
 [another_table].key_field_n= [selected_table].key_field_n

Note is the same as above

**Comment by plotn** [comment]
3. Delete from syntax:
DELETE FROM [selected_table]
USING [another_table]
[another_table].key_field_1= [selected_table].key_field_1 and
[another_table].key_field_n= [selected_table].key_field_n

Note is the same as above
