### ISSUE TITLE
PostgreSQL add value to enum

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#7856]
Hi! I cant find (and it is possible missing) interface to add values to PostgreSQL enum types. Could it be realised?
There is only "view only" interface, but it could be suitable adding a button with "Add value" functionality, that does: ALTER TYPE this_enum_type ADD VALUE 'new_enum_value_in_type'

**Comment by uslss** [comment]
feature will be implemented in the scope of #10903
