### ISSUE TITLE
Selecting from Oracle synonym gives ORA-00942: table or view does not exist

### ISSUE THREAD

**Issue by AndrewGabelliTR** [dbeaver/dbeaver#7857]
DBeaver 6.3.4

Oracle 12cR2

I have a synonym A in schema B that points to a view C in schema D.

SELECT * FROM A; -- gives the table or view not found error

SELECT * FROM B.A; -- works

SELECT * FROM D.C; -- works

**Comment by uslss** [comment]
Hi @AndrewGabelliTR ,
what schema is active in the toolbar?

**Comment by AndrewGabelliTR** [comment]
I was logged in as user B so I guess it would have been B. I have since rolled back to 6.2.5. which does not have the issue so I can't be 100% certain, but I think 99.999%.

**Comment by uslss** [comment]
cannot reproduce it for now.
if the issue is still actual - feel free to reopen it.
