### ISSUE TITLE
Generate SQL:  additional Template Update by Unique Key

### ISSUE THREAD

**Issue by pgutsche** [dbeaver/dbeaver#7858]
As far as I understand, with the current UPDATE generation feature in the Generate SQL Option of the result grid no WHERE part is generated. It has to be added manually:

Add an "Update by Unique Key" Option with the following behavior:
	• similar to the current option but additionally the 
	• WHERE part is generated from the primary/unique key of the table (if it exists for the table and is part of the result grid) or with all columns in the result set of the grid (if no unique key exists for the table or it is not part of the result grid)

Alternatively, there could be an even more useful feature:
Add an "Update (set marked) by Unique Key (or unmarked)" option:
	• In the result grid, it is possible to mark different cells in different columns
	• This option should only generate update statements from rows that have at least one marked cell
	• The SET part of the generated update statement should only hold the column_name and value of the marked cells
	• The WHERE part of the generated update statement contains only the column_name and value of the unique key (if it exists for the table) or the column_name and value of all columns of the specific row that are NOT MARKED in that specific row.

The requested new option "Update (set marked) by Unique Key (or unmarked)" would have the following result on the table shown in the screenshot (file GenerateSQLUpdate1.jpg):
	• Assumption table (table_name=test) has an uniqe column ID 
Update test set kzfa='H', pversion =1999 where ID=1903;
Update test set pversion =1999, pnr=300 where ID=1906;
Update test set pnr=600, pabschn='G' where ID=1909;
Update test set pnr=700, pabschn='G' where ID=1910;
Update test set pnr=1000, pabschn='G' where ID=1911;
or
• Assumption table (table_name=test) has NO uniqe Key 
Update test set kzfa='H', pversion =1999 where ID=1903 and abschn = '51' and stg = '048' and vert is null, and schwp is null and pnr = 200 and pabschn='G';
Update test set pversion =1999, pnr=300 where ID=1906 and abschn = '51' and stg = '048' and vert is null, and schwp is null and kzfa='H' and pabschn='G';
Update test set pnr=600, pabschn='G' where ID=1909 and abschn = '51' and stg = '048' and vert is null, and schwp is null and kzfa='H' and pversion=1999;
Update test set pnr=700, pabschn='G' where ID=1910 and abschn = '51' and stg = '048' and vert is null, and schwp is null and kzfa='H' and pversion=1999;
Update test set pnr=1000, pabschn='G' where ID=1911 and abschn = '51' and stg = '048' and vert is null, and schwp is null and kzfa='H' and pversion=1999;

**Comment by pgutsche** [comment]
Could not upload the screenshot. so I describe it here:
Screenshot shows the resultgrid with a table having the following columns:
ID, abschl, stg, vert schwp, kzfa, pversion, pnr, pabschn

in row 4 columns kzfa and pversion are marked
in row 7 columns pversion and pnr are marked
in rows 10 to 11 columns pnr and pabschn are marked.

**Comment by serge-rider** [comment]
Hint: you can just paste screenshot in the comment text.

We will add custom SQL generators model in 6.3.5 (see #7853). So it will be easy to add a new one.

**Comment by pgutsche** [comment]
If it will be possible in this feature to distinguish between marked and unmarked columns per row, unique key columns of the table(s) and to request a user input (as requested in the issue you referenced (see #7853) that would be great.

Remark: must have a browser problem, can neither past nor dragg or drop or select a *.jpg file.

**Comment by uslss** [comment]
already implemented
