### ISSUE TITLE
Generate SQL: additional Template Insert without Unique Key

### ISSUE THREAD

**Issue by pgutsche** [dbeaver/dbeaver#7859]
sometimes new rows are required in a table, where only a few values are different to existing rows.
A quick way to do this is the current Generate SQL -> INSERT feature on a result grid from a select * from target_table where <only useful rows are filtered>

But you have to eliminate the unique key columns and values manually to get the generated insert statements to work. (assuming the unique key is generated automatically with sequences)

A solution would be to add an  "Insert without Unique Key" Option:
	• It works similarly to the current Insert option but the Unique Key columns are not part of the columns in the generated insert statements,
(regardless of unique key columns that are part of the result set, unique key columns are just not generated into the INSERT statement)

**Comment by LonwoLonwo** [comment]
Duplicate for https://github.com/dbeaver/dbeaver/issues/10489
