### ISSUE TITLE
Index columns are displayed in random order in case of Oracle DB

### ISSUE THREAD

**Issue by allati** [dbeaver/dbeaver#7860]
#### System information: 
- Operating system (distribution) and version: Win7 64
- DBeaver version: DBeaver IDE 6.3.4.202002011957, installed on top of Eclipse 2020-03 (4.15), I20200110-0905

#### Connection specification:
- Oracle DB 11.2.0.4

#### Describe the problem you're observing:
Index columns order is random in index details view -> "index columns" tab or table details view -> "indexes" tab. They should be ordered according to all_ind_columns.column_position values.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by kseniiaguzeeva** [comment]
Sorry, but after a more careful reading I can not reproduce the issue. I have the same column order in index view and using SQL Editor. Please tell:
-How many columns does an index have?
-Which exactly SQL expression do you use?

**Comment by allati** [comment]
Thanks for looking into this. I was trying to reproduce the issue locally on 19c (I won't have access to production environment for the next several weeks) and the only way I managed to do something similar was to... sort indexes in table details view. Maybe I did the same thing in case of production DB and never noticed that, I'm not sure now, my memory may be failing me :) I will check again in several weeks.

To better illustate, I create such table and indexes:
```sql
create table test_table (a varchar2(1), b varchar2(1), c varchar2(1));

create unique index test_index on test_table(a, b, c);
create unique index test_index_2 on test_table(c, b, a);
create unique index test_index_3 on test_table(c, b, trim(a));
```

When indexes in table details view are opened initially, they are displayed like this (which corresponds to indexes structure):
* TEST_INDEX
  * A
  * B
  * C
* TEST_INDEX_2
  * C
  * B
  * A
* TEST_INDEX_3
  * C
  * B
  * SYS_NC00004$

And when I click on "Index Name" column, the order changes:
* TEST_INDEX
  * A
  * B
  * C
* TEST_INDEX_2
  * A
  * B
  * C
* TEST_INDEX_3
  * B
  * C
  * SYS_NC00004$

IMHO, current behavior is worth reviewing, because for me as for the user it was surprising. If I do sorting by column "index name", I would expect only indexes order to be changed, not order of columns within them, because columns order within an index is significant in Oracle from performance perspective. I think that it is true for other RDBMS, but I have no such experience with them. So change in columns order coveys wrong information about an index. Maybe the following changes can be evaluated?
1. keep index columns order in index tab of table details view when indexes are sorted
2. display column position in an index in table and index details view

**Comment by serge-rider** [comment]
@allati I agree in general. But it is not that easy to fix.
First of all we have the same sorting algorithm for all kinds of elements (so this behavior is not specific to Oracle index columns). Potentially we could make property "Name" special and sort only elements on the first level. but even can make more harm than good in some cases (image that you have tens of nested elements and you want to order them alphabetically).

Workaround: there is property "Position" of index column. It is hidden by default but you can make it visible in column settings:
![image](https://user-images.githubusercontent.com/6398845/74109800-a21a5100-4b97-11ea-9c36-cbc02a206972.png)

![image](https://user-images.githubusercontent.com/6398845/74109810-bb230200-4b97-11ea-9c7b-69985cba2c24.png)

**Comment by allati** [comment]
I knew that columns can be configured, even used that feature frequently when analyzing execution plans. But in this case thought to check for hidden columns hadn't crossed my mind even once. Feel so stupid.

Once I made column position visible, I don't think the issue is valid any longer. On table details view, index tab, ordering by column position first orders indexes by name, just perfect. I'm inclined to just close the issue if you don't mind. I'll reopen it if I find problem I was telling about on production environment, but the chances are low. I'm almost 100% sure that I accidentally sorted indexes and hadn't noticed that. Multiple times.

Thank you very much!

**Comment by alexlaedi** [comment]
As far as I see, my issue relates to this discussion and I consider the behaviour as a bug. I try to create a foreign key constraint in table CH_DA_DIM_orders..

![grafik](https://user-images.githubusercontent.com/25525546/74714759-849a5680-522b-11ea-8d5d-5d8bf982a611.png)

.. on the primary key of table CH_DA_DIM_warehouses:

![grafik](https://user-images.githubusercontent.com/25525546/74714818-9da30780-522b-11ea-8a78-f2f563be2f3c.png)

Issue: As you can see, the UI suggests a reordering of the columns to generate the foreign key contraint on the primary key and thereafter produces the error at commit:

![grafik](https://user-images.githubusercontent.com/25525546/74715135-33d72d80-522c-11ea-9963-0df3ff505e66.png)

To me, the creation of a foreign key on a primary key of another table should take the same column order. Else you have to change that in the SQL-Query behind the UI-behaviour manually each time. Would you agree on my view of things or do I oversee something relevant?

**Comment by alexlaedi** [comment]
P.S.: Dont' think this is database architecture related, I'm working with MS SQL server.

**Comment by allati** [comment]
@serge-rider I found what the problem was: seems that I enabled DBeaver -> Navigator -> "Order elements alphabetically" option some time ago. With it DBeaver is sorting all trees alphabetically, at least indexes and their columns in the table details view. To my excuse, from the context (preferences page name and meaning of all other options there) it seemed that this option only affects "Database Navigator" view.

In case someone happens to face the same problem as me, maybe you can consider making "Position" column visible by default for indexes? And renaming it to "#" even, like it is done for table columns? This way it will occupy very little screen space and provide indication on the sorting applied.

Anyway, thank you for helping me!
