### ISSUE TITLE
SQL editor font size in column selection mode different

### ISSUE THREAD

**Issue by NetGiant** [dbeaver/dbeaver#7862]
First issue reported - ever. I hope it makes sense ...

#### System information: 
- Operating system (distribution) and version: Windows 10 Pro version 1809, build 17763.973
- DBeaver version: (latest) 6.3.4.202002011957
- Java version: (run-time came with DBeaver) java.runtime.version=11.0.5+10
- Additional extensions: none

#### Connection specification:
- Database name and version: SQL Server 2017 - 14.0.2014.14 (X64)
- Driver name: mssql-jdbc-7.0.0.jre8.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Not a critical bug! Appearance/annoyance only.
I increased the font size of the SQL editor. Works fine. When I switch to column select (CTRL+SHIFT+A) the font size shrinks (to original size?) until I switch back to normal selection mode.

#### Steps to reproduce, if exist:
1) Increased the font size of the SQL editor.
2) Switch to column select (CTRL+SHIFT+A)
3) Observe the reduced font size
4) Switch back to normal selection mode
5) Observe the font size applied in step 1

#### Include any warning/errors/backtraces from the logs
None

**Comment by uslss** [comment]
Hi @NetGiant ,
could you clarify what does "Column select" (step 2) mean? probably you could make video?
thanks in advance :)

**Comment by NetGiant** [comment]
I can't make a video at this time - technical issues. Here are screen captures at each step.
![Font 1 - normal size](https://user-images.githubusercontent.com/17996256/74172238-1d5a2200-4bed-11ea-9ad8-50bb3dcb0b84.png)
This shows the normal SQL editor.

![Font 2 - size increased by CTRL plus](https://user-images.githubusercontent.com/17996256/74172277-2e0a9800-4bed-11ea-987c-e8066a011399.png)
This shows the SQL editor after increasing the font size using CTRL-+

![Font 3 - showing normal selection mode](https://user-images.githubusercontent.com/17996256/74172311-3e227780-4bed-11ea-9886-5842887f2b9f.png)
This shows normal selection mode

![Font 4 - switched to column select mode - shows smaller font size](https://user-images.githubusercontent.com/17996256/74172330-4aa6d000-4bed-11ea-9af3-2f45c7ba5b40.png)
This shows switching to column selection mode using ALT+SHIFT+A. Notice the smaller fonts.

![Font 5 - switched back to normal selection mode - shows large fonts from first step](https://user-images.githubusercontent.com/17996256/74172465-8772c700-4bed-11ea-8b76-1570699babb1.png)
This shows the screen after switching back to normal selection mode. ALT+SHIFT+A

I used the wrong keyboard shortcut for toggling selection mode in my original description. Sorry if that was confusing.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Looks like Eclipse bug/or sort of feature.
Similar to this one: https://bugs.eclipse.org/bugs/show_bug.cgi?id=278831

Anyhow, we can't fix it from DBeaver side.
