### ISSUE TITLE
Function bodies not compared when comparing only structure

### ISSUE THREAD

**Issue by theldberg** [dbeaver/dbeaver#7863]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.3.4.202002011957
- Java version: 1.8.0_191-b12 
- Additional extensions: None

#### Connection specification:
- Database name and version: Postgresql
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc): No

#### Describe the problem you're observing:

I'm trying to run a sql compare that compares two databases. I dont want it to compare object ids or row counts so I choose to compare only structure. I also check the compare scripts/procedures check box. However, results do not include function body comparison.

The issue is similar to #3292, which is marked as resolved.

#### Steps to reproduce, if exist:

1. Select 2 sql functions with different body
2. Right click and choose Compare/Migrate->Simple Compare
3. Check Compare only structure and Compare scripts/procedures
4. Run the compare
5. Notice that the function bodies were not compared

#### Include any warning/errors/backtraces from the logs
No errors logged.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
