### ISSUE TITLE
Function source comparison shows diffs when there are none

### ISSUE THREAD

**Issue by theldberg** [dbeaver/dbeaver#7864]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.3.4.202002011957
- Java version: 1.8.0_191-b12
- Additional extensions: None

#### Connection specification:
- Database name and version: Postgresql
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc): No

#### Describe the problem you're observing:

When I compare two identical functions using the Simple Compare tool with the Compare functions/scripts option, it always shows the source as being different.

#### Steps to reproduce, if exist:

1. Create a function
2. Create an identical function with a different name
3. Select the two functions
4. Right click and choose Compare/Migrate->Simple Compare
5. Check Compare scripts/procedures
6. Run the compare
7. Compare report will show the source as a mismatch

I attached an example.
[Function Compare.docx](https://github.com/dbeaver/dbeaver/files/4168144/Function.Compare.docx)

#### Include any warning/errors/backtraces from the logs
There are none.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
If functions have different names then these functions are different.
But in your sample they have the same name (probably they are in different database).  
But I can't reproduce this bug then.

**Comment by theldberg** [comment]
In the example that I attached I was using two different databases and the same function with the same name.  Updated reproduction steps:

1. Apply the function below to 2 different databases
2. Select the two functions
3. Right click and choose Compare/Migrate->Simple Compare
4. Check Compare scripts/procedures
5. Run the compare
6. Compare report will show the source as a mismatch


CREATE OR REPLACE FUNCTION public.min_uuid(uuid, uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 STABLE
AS $function$
BEGIN
    -- if they're both null, return null
    IF $2 IS NULL AND $1 IS NULL THEN
        RETURN NULL ;
    END IF;

    -- if just 1 is null, return the other
    IF $2 IS NULL THEN
        RETURN $1;
    END IF ;
    IF $1 IS NULL THEN
        RETURN $2;
      END IF;

    -- neither are null, return the smaller one
    IF $1 > $2 THEN
        RETURN $2;
    END IF;

    RETURN $1;
END;
$function$

**Comment by uslss** [comment]
@theldberg 
is it still actual?

**Comment by uslss** [comment]
there are not any updates on issue. Ticket will be closed.
If issue is still actual for you - feel free to reopen the ticket
