### ISSUE TITLE
Cannot enable any Editor toolbar buttons.

### ISSUE THREAD

**Issue by 18549** [dbeaver/dbeaver#7868]
#### System information: 
- Operating system (distribution) and version: Win 10  Pro
- DBeaver version: 6.3.4.202002011957
- Additional extensions: None

#### Connection specification:
- Database name and version: SQL Server Express 
- Driver name: No idea.
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

There are no editor buttons on the toolbar, Save, Revert etc.
Attempting to enable any editor buttons in Window -> Customize Perspective -> Toolbar Visibility returns and incomprehensive error message about 'action sets'.

![Screenshot_1](https://user-images.githubusercontent.com/46347740/74031467-7e91b380-49a9-11ea-88b9-17bbf80f5297.png)

**Comment by uslss** [comment]
hi @18549 ,
could you try to Reset UI settings (File -> Reset UI settings)?

**Comment by 18549** [comment]
Done that. Makes no difference.

**Comment by uslss** [comment]
cannot reproduce an issue for now.
if it is still actual for you - feel free to reopen the ticket

**Comment by p91paul** [comment]
@uslss try clicking on "Edit actions" on the customize perspective modal dialog.
All the other sections work (you first need to enable them from "Action set availability" tab), but edit actions cannot be enabled from there.

**Comment by uslss** [comment]
@p91paul thanks for answer. Undo and Redo action really couldn't be enabled. Issue reopened.
![2020-04-22_23h10_02](https://user-images.githubusercontent.com/31996417/80028971-b3b09b00-84ee-11ea-9174-388a8cb84ff0.gif)

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/81098706-6e3e9580-8f12-11ea-9a71-c92cbb71e7b2.png)

You need to switch perspective or restart dbeaver to let changes take effect.

**Comment by huyz** [comment]
Man, what are action sets? And why are some of my toolbars hidden and unselectable.  I wish DBeaver would explain this stuff right from the get-go
