### ISSUE TITLE
Unable to connect to 2nd instance

### ISSUE THREAD

**Issue by ONE-AIM** [dbeaver/dbeaver#7869]
When trying to connect to a MS SQL Server 2nd instance I get all kinds of errors. Works fine in SSMS. 

MSSQLSERVER\SECOND_INSTANCE

The TCP/IP connection to the host MSSQLSERVER, port 57049 has failed. Error: "connect timed out. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".

I assume the _ in the 2nd instance name is causing the issue as I can connect to other servers who do not have any characters in the name.

Thanks

**Comment by serge-rider** [comment]
Please provide more information:
- What SQL Server driver do you use in dbeaver?
- What type of authentication do you use?
- Do you use any proxy or tunnel?

**Comment by ONE-AIM** [comment]
1.  Microsoft JDBC Driver for SQL Server
  2.  Windows Authentication
  3.  No

Thanks,

Alex Rich | DATABASE ADMINISTRATOR, AVP
t: 812-468-1124 | c: 812-480-5330 | f: 812-468-1104
Alex.Rich@oldnational.com<mailto:Alex.Rich@oldnational.com>
Old National Bank
101 N.W. 4th Street | Evansville, IN 47708

[Old National | Your bank. For life]<https://www.oldnational.com/>

[Learn More]<http://www.oldnational.com/webtracking/email-signature/campaign-2.asp>

**Comment by serge-rider** [comment]
You need to use TCP/IP ports in order to connect from dbeaver.
I see that you use port 57049 while standard port number is 1433. Is it correct?

Is your first instance (which connects ok) deployed on the same port?

**Comment by ONE-AIM** [comment]
There are 2 instanced. The default is on 1433. The 2nd is on 57049. The port is open and I can connect to both with SSMS just not the 2nd with DBeaver.

Thanks,

Alex Rich | DATABASE ADMINISTRATOR, AVP
t: 812-468-1124 | c: 812-480-5330 | f: 812-468-1104
Alex.Rich@oldnational.com<mailto:Alex.Rich@oldnational.com>
Old National Bank
101 N.W. 4th Street | Evansville, IN 47708

[Old National | Your bank. For life]<https://www.oldnational.com/>

[Learn More]<http://www.oldnational.com/webtracking/email-signature/campaign-2.asp>

**Comment by serge-rider** [comment]
Could you post debug log?
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by ONE-AIM** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4319211/dbeaver-debug.log)

**Comment by serge-rider** [comment]
I think you have a wrong server name in connection settings.
It is not a Windows network path but a host name or IP address. You need to enter it instead of `PRDSQLSERVER\2nd_Instance`.

**Comment by ONE-AIM** [comment]
I am entering servername\instance_name. I removed the actual names due to this being a public forum.

**Comment by serge-rider** [comment]
DBeaver uses JDBC driver. Being a TCP/IP driver it supports only plain domain names or IP addresses as server names.
While SSMS can work with local notwork paths and can use different network protocols.

You can ask your DBA about IP address of this second instance.
