### ISSUE TITLE
Database Navigator - blue arrow on some of my MySQL connections

### ISSUE THREAD

**Issue by cumanacr** [dbeaver/dbeaver#7870]
#### System information: 
- Operating system (distribution) and version
Description:    KDE neon User Edition 5.17
Release:        18.04
Codename:       bionic

- DBeaver Version 6.3.4.202002011957

#### Connection specification:
- MySQL any version

#### Describe your question:
I want to know why is there a blue arrow on some of my MySQL connections?

I looked on the wiki ***Database Navigator*** but I didn't find anything about it

![Selection-02-2020-02-07](https://user-images.githubusercontent.com/6874136/74072430-6b440f80-49cc-11ea-9735-9eecaaf49f77.jpg)

![Selection-04-2020-02-07](https://user-images.githubusercontent.com/6874136/74072670-210f5e00-49cd-11ea-8173-75acdd797a7f.jpg)

Regards

**Comment by p91paul** [comment]
If I remember correctly, those arrow indicate that the connection uses a ssh tunnel

**Comment by cumanacr** [comment]
Yep, thank you very much
