### ISSUE TITLE
PostgreSQL - (F4) "Open Declaration" Error with multiple databases

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#7871]
Hi Serge,

I am experiencing the following issue in 6.3.4 (at least on Mac).

Steps to reproduce:
1. Ensure that you have at least two databases in your PG Server (e.g. DB1, DB2). DB2 should have a table that is not available in DB1.
2. Set up a PG Connection with default database DB1.
3. Now connect to this database but let DB1 be set as default (i.e. it is shown in bold)
4. Select DB2 in the navigator by just doing a single click on it.
5. Open a new SQL editor for DB2
6. Run a simple query on the table that only exists in DB2, in my case "vo_layout": select * from vo_layout
7. Right click on the table name on the sql editor and choose "Open Declaration" or press F4
8. ERROR is thrown: "Find object node by reference"

![image](https://user-images.githubusercontent.com/38714600/74099139-cb4bca80-4b20-11ea-8198-83af4658a892.png)

(If I do the same with DB1 then everything is fine!)

I think there is an issue concerning which database is bound to a specific SQL editor.

James

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by JamesInform** [comment]
Just tested the early access version 6.3.5.

(Database PostgreSQL on Mac)

Now ALL sql editors are bound to the same database, i.e. the database that is marked as default in the navigator.

When I select another database from the navigator and open up a new sql editor, the new sql editor is opened up for the database marked as default (bold) in the navigator and not the database I selected.

If I have more than one sql editor open and I choose a different database for one of them, then the database of all editors is changed to the new database.

**Comment by serge-rider** [comment]
You need to enable multi-connection mode in main menu (for a particular connection) or in preferences (globally):

![image](https://user-images.githubusercontent.com/6398845/74215833-86a46880-4cb3-11ea-8d7f-6a159c8db1fc.png)

![image](https://user-images.githubusercontent.com/6398845/74215848-9459ee00-4cb3-11ea-95bd-1a71433ed49f.png)

This mode is enabled by default.

**Comment by JamesInform** [comment]
Good Morning!

Yep! My fault! 

I disabled this option by mistake.

Everything works fine now. Thanks for your effort.

**Comment by kseniiaguzeeva** [comment]
verified
