### ISSUE TITLE
Dblink Error (Oracle)

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#7872]
* System Information:

* Operation System
 Windows 10
* DBeaver version
 6.3.4
* Additional extensions
 No
* Connection specification:

* Database name and version
 Oracle 12c
* Driver name
 Oracle JDBC Driver
* Do you use tunnels or Proxies(SSH, SOCKS, etc) ?
 No

After upgrading to Dbeaver 6.3.4, I get an error in a sql statement using "dblink".
In Dbeaver 6.3.3, it confirmed that it works properly.

![image](https://user-images.githubusercontent.com/59002295/74115560-1cc48a00-4bf3-11ea-9947-7fc497658414.png)

Example Sql

```
SELECT a.*
  FROM EMIHPTMI@ORA920@EDISAGENT a 
 WHERE 1 = 1
   AND rownum = 1
;
```

Thank for reading.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
As far as I know it is server-side error, can't figure out how it can be related to dbeaver version.

It may be a result of wrong dblink config or wrong tnsnames config.
