### ISSUE TITLE
Can not find sql execute button in toolbar

### ISSUE THREAD

**Issue by cjk87927** [dbeaver/dbeaver#7873]
#### System information: 
- Operating system (distribution) and version: MACOS 10.15
- DBeaver version: 6.3.4

#### Connection specification:
- Database name and version MYSQL 5.7

#### Describe your question:
Can not find sql execute button in toolbar, in customize perspective - toolbar visibility, I also can not find it

**Comment by serge-rider** [comment]
We don't have custom toolbar with SQL execute action.
Why do you need it? What's wrong with the standard one?

![image](https://user-images.githubusercontent.com/6398845/74125355-2267a300-4be6-11ea-9996-f0001cd5f4ed.png)

**Comment by cjk87927** [comment]
I have this button in the previous version, it may be a very old version.
I didn't notice the button on the left, thank you for your reply
