### ISSUE TITLE
[PostgreSQL] Editing in result table

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#7874]
#### System information: 
- Windows 7 Pro x64
- DBeaver 6.3.5.202002081854 (EA)
- No additional extensions

#### Connection specification:
- PostgreSQL 9.3
- PostgreSQL default driver (9.4.1212.jre7)
- No tunnels or proxies

#### Describe the problem you're observing:
The primary key icon on the column is not displayed in the result table. Fields in the selection from one table are not edited (the primary key is in the list of fields). There is no way to switch to another table by foreign key.

#### Steps to reproduce, if exist:
```
drop table if exists supp.tmp_tab2;

drop table if exists supp.tmp_tab1;

create table supp.tmp_tab1(
	id int primary key,
	code text);

create table supp.tmp_tab2(
	id int primary key,
	name text,
	tab1_lnk int references supp.tmp_tab1(id));

insert into supp.tmp_tab1(id, code)
values(1,'1');

insert into supp.tmp_tab2(id, name, tab1_lnk)
values(1,'1',1);

select *
from supp.tmp_tab2
```
Screen from version 6.3.5 (as it became) and 6.3.4 (as it was):
![01](https://user-images.githubusercontent.com/22142845/74130305-d0794a00-4bf2-11ea-8b6b-e947901a8765.JPG)
![02](https://user-images.githubusercontent.com/22142845/74130309-d2dba400-4bf2-11ea-8775-fd228f1119b4.JPG)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by ems2811** [comment]
It works correctly in 6.3.5.202002151353

**Comment by serge-rider** [comment]
@ems2811 thanks for checking this

**Comment by kseniiaguzeeva** [comment]
verified
