### ISSUE TITLE
[Postgresql] Autocompletion in select after insert

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#7876]
#### System information: 
- Windows 7 Pro x64
- DBeaver 6.3.5.202002081854 (EA)
- No additional extensions

#### Connection specification:
- PostgreSQL 9.3
- PostgreSQL default driver (9.4.1212.jre7)
- No tunnels or proxies 

#### Describe the problem you're observing:
In select after insert statement autocompletion reutrns fields from inserting table

#### Steps to reproduce, if exist:
```
drop table if exists supp.tmp_tab1;

drop table if exists supp.tmp_tab2;

create table supp.tmp_tab1(
	id int,
	name1 text);

create table supp.tmp_tab2(
	id int,
	name2 text);
```
Reconnect DB
Open new editor and type query below
```
insert into supp.tmp_tab2(id, name2)
select id,         
from supp.tmp_tab1
```
![изображение](https://user-images.githubusercontent.com/22142845/74133929-ac216b80-4bfa-11ea-8e8c-b4e33ed31021.png)

**Comment by uslss** [comment]
hi @ems2811 , probably you should add ';' delimiter after insert statement?

**Comment by ems2811** [comment]
Hi, @uslss , nothing changed
![изображение](https://user-images.githubusercontent.com/22142845/74234840-d3e9ff80-4cde-11ea-9181-e5100c781ee9.png)

**Comment by ems2811** [comment]
It works correctly in 6.3.5.202002151353

**Comment by ems2811** [comment]
still reproduced in 6.3.5.202002151353

put ";" like in query below - incorrect
```
insert into supp.tmp_tab2(id, name2);
select id,         
from supp.tmp_tab1
```

**Comment by ems2811** [comment]
still reproduced in 7.0.0.202003021717

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Workaround: use table aliases

**Comment by serge-rider** [comment]
Very similar to #7768. So closing as duplicate.
