### ISSUE TITLE
Output window does not update during run, only afterwards (same: #7568)

### ISSUE THREAD

**Issue by martijn1247812** [dbeaver/dbeaver#7880]
No updates during run in Output window. Only when run finished
Running functions with RAISE INFO. This info is not being shown in the Output window. With version 6.3.0 no problems.

System information:
Windows 10
DBeaver version: Version 6.3.4.202002011957
Additional extensions: none
Connection specification:
Postgres EDB 9.6 & PostgreSQL 11
Driver name: default (local client: Postgres 11 and/or Built in 9-6 version)
Describe the problem you're observing:
No updates during run in Output window. Only when run finished

**Comment by uslss** [comment]
cannot reproduce it for now.
if the issue is still actual - feel free to reopen the ticket.
