### ISSUE TITLE
Eclipse Marketplace - fails to install due to invalid certificate

### ISSUE THREAD

**Issue by adhomdom** [dbeaver/dbeaver#7881]
Figured I'd log this, should anyone else come across it.

When trying to install DBeaver (IDE & runtime @6.3.4) into Eclipse via the Marketplace, I get the following:

> Connection to https://dbeaver.jkiss.org/update/debug/latest/p2.index failed on Certificate for <dbeaver.jkiss.org> doesn't match any of the subject alternative names: [dbeaver.io, jkiss.org]. Retry attempt 0 started

The result, is that the DBeaver installation fails.

Some of my Eclipse session data captured during the above:
eclipse.buildId=4.14.0.I20191210-0610
java.version=10.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_GB

Given this tells me the URI, I navigated to https://dbeaver.jkiss.org/update/debug/latest to see what was going on with the SSL certificate. I note that I get redirected to https://dbeaver.io/update/debug/latest/ - and on the latter, the SSL certificate is perfectly valid.

My conclusion: The DBeaver update site has moved, and the Eclipse Marketplace hasn't updated (yet?).

As a workaround for this, I added the new Update Site URL manually, and was then able to successfully install DBeaver (Help > Install New Software, rather than Help > Eclipse Marketplace). In the Update Site dialog, add https://dbeaver.io/update/latest/ and then select the installation candidates you wish.

This issue may not be explicitly caused by DBeaver, and may be resolved once the Eclipse Marketplace updates following the 301/302 response.

**Comment by serge-rider** [comment]
Thanks for the bug report. Eclipse marketplace app listing is fixed (the error was only in SQL debugger plugin).

**Comment by uslss** [comment]
verified
