### ISSUE TITLE
Autocomplete with Oracle Public Synonyms

### ISSUE THREAD

**Issue by ADegele** [dbeaver/dbeaver#7882]
#### System information: 
- Operating system (distribution) and version: Windows 7 Enterprise, SP1
- DBeaver version: 6.3.4.202002011957
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production
- Driver name: ojdbc7-12.1.0.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - No

#### Describe the problem you're observing:
When having a view and a public synonym both with the same name, the autocomplete for columns does not work when pressing [CTRL+Space], it just displays "no proposals". However, autocomplete does work ritght after typing a letter.

Expected: Autocomplete proposes columns both when typing and when pressing [CTRL+Space].

#### Steps to reproduce, if exist:
1. Create DB-Objects
```sql
CREATE TABLE V3AADM.TESTTABLE (
   ID LONG NOT NULL,
   VORNAME VARCHAR2(100),
   NACHNAME VARCHAR2(100)
);

CREATE OR REPLACE VIEW V3AADM.TESTTABLE_V
(ID,VORNAME,NACHNAME)
AS
SELECT  data.ID, data.VORNAME, data.NACHNAME FROM TESTTABLE DATA

CREATE OR REPLACE PUBLIC SYNONYM TESTTABLE_V FOR V3AADM.TESTTABLE_V
```
2. Restart dbeaver to reload the metadata
3. Start a query with `SELECT * FROM testtable_v t WHERE t.` After typing the dot, you should see proposals for the three columns of TESTTABLE
4. Press [ESC] and then press [CTRL+Space]. There will be no proposals.

On a note: When having the table name in upper case, the autocomplete does work: `SELECT * FROM TESTTABLE_V t WHERE t.[CTRL+Space]` shows the columns

#### Include any warning/errors/backtraces from the logs
No `.log` was written during these steps. There is no output in the error protocol neither.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
