### ISSUE TITLE
Support drivers pre-configuration

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#7886]
In some environments we need to preconfigure set of dbeaver drivers (e.g. when you need to install dbeaver with some preconfigured proprietary driver for a number of users).

It can be accomplished by passing extra parameter to dbeaver.ini file.
We can reuse existing parser of drivers.xml file.

**Comment by serge-rider** [comment]
New system property `dbeaver.drivers.configuration-file` was added.
Line like `-Ddbeaver.drivers.configuration-file=c:\some-=path\dbeaver-drivers.xml` can be added in the end of dbeaver.ini file.

**Comment by serge-rider** [comment]
https://github.com/dbeaver/dbeaver/wiki/Admin-Manage-Drivers#provide-predefined-drivers-configuration

**Comment by uslss** [comment]
verified
