### ISSUE TITLE
Import data into DB2 zOS table- date format

### ISSUE THREAD

**Issue by mahadea** [dbeaver/dbeaver#7889]
#### System information: 
- Windows 10 Enterprise
- 6.3.3.202001191557

#### Connection specification:
- DB2 zos v10

#### Describe your question:
I am trying to import data into a table using csv source. I am not able to figure out the right format for date. I used '2009-01-01' and I get the message 
Error occurred during Error occurred during data load

Reason:
SQL Error: [jcc][1093][10425][3.68.61] Invalid data conversion: Parameter instance '2009-01-01' is invalid for the requested conversion to java.sql.Date. ERRORCODE=-4220, SQLSTATE=null

What should be the right format?

**Comment by uslss** [comment]
hi @mahadea ,
what is column type for column that you try to import?

**Comment by mahadea** [comment]
Hi it's DATE.  
Anyways I was going to update this ticket today.  I was successfully able to accomplish what I wanted to do by putting the date value in double quotes and not having quotes or apostrophes for any of the other fields.  So something like this
VAL1,123,"2009-01-01",VAL2,345
Very unintuitive- but what I did was to export an existing row and modeled my import data on that.
Thank you
