### ISSUE TITLE
Data Editor Reorder Column by Drag

### ISSUE THREAD

**Issue by Jnb2387** [dbeaver/dbeaver#7890]
#### System information: 
- Operating system (distribution) and version  Linux Mint 19.2
- DBeaver version 6.3.4

#### Connection specification:
- Database name and version PostgreSQL 12

#### Describe your question:
In the previous version of Dbeaver I was able to reorder or move a column in the data editor by dragging it over another column. In the latest couple version it seems that this feature is no longer working. I can click and drag the column but it will not set it to a new position. I have tried on multiple different database and different version numbers.
 I am still able to reorder the columns through the customize filters dialog which is still nice but it was super helpful to be able to drag the column to where I want.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by ShadelessFox** [comment]
Hello @Jnb2387,

Can you please verify that the issue persists on the latest version?

**Comment by Jnb2387** [comment]
@ShadelessFox 
I am on version 21.2.5 with no change, I am still **not** able to drag a column to set it in a new position.

**Comment by ShadelessFox** [comment]
@Jnb2387

That's unfortunate. Is it possible to record a video showing this behavior?

**Comment by Matvey16** [comment]
Reproducible only on Linux

**Comment by Skydiveroid** [comment]
@Jnb2387, could you please record a video.

**Comment by Matvey16** [comment]
No need to record a video. I reproduced it, but this is actual only for Linux

**Comment by ShadelessFox** [comment]
Fixed in #15421

**Comment by dexy86** [comment]
> Fixed in #15421
didn't got fixed

Same here fedora 35 can't drag columns in results tab (to rearrange them), mac works
Can't even resize the column, only double click on the border between two columns extends the column width to full data width.
