### ISSUE TITLE
Views/Tables folders missing from Connection

### ISSUE THREAD

**Issue by lalato** [dbeaver/dbeaver#7891]
#### System information: 
- MacOS 10.15.2
- 6.3.4
- Java 8 Update 221
- Additional extensions

#### Connection specification:
- Teradata

#### Describe the problem you're observing:

Created a connection and all was fine.  Was timed out after a long spell of inactivity, when I returned to DBeaver, the Views and Tables folders within my connection did not have the small expand triangle to the right so I refreshed the connection.

After refreshing, the folders for Tables, Views, Stored Procs, etc. all disappeared... and now I do see all the objects, but they are directly underneath the connection... without any of those folders.

Apart from uninstalling and re-installing the application, is there some easy way to get those folders back?

**Comment by uslss** [comment]
hi @lalato ,
unfortunately, we've got no test Teradata db.
Is issue reproducible if you create new connection that is the same?

**Comment by lalato** [comment]
I created a new connection and it had the same issue.  I should note that I’ve been using dbeaver with Teradata for years, and I’ve  never seen this before.

**Comment by uslss** [comment]
Could you provide logs?
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by lalato** [comment]
I uninstalled, then re-installed.  This corrected the issue.  Closing this ticket.
