### ISSUE TITLE
MySQL DB encoding problem

### ISSUE THREAD

**Issue by eloscuro** [dbeaver/dbeaver#7894]
#### System information: 
- 4.2.0-35-generic #40~14.04.1-Ubuntu
- DBeaver ver. 6.3.4.202002011957

#### Connection specification:
- MySQL ver. 5.7.19
#### Describe your question:

Hello,

I have several legacy MySQL databases which are created in **latin1** charset but in fact data is stored in **UTF8** encoding.

So I have to use "_SET NAMES latin1_" query each time I connect to these databases, no matter I do it manually or from scripts. After that query everything is alright with encoding.

But in DBeaver I cannot change the encoding using "SET NAMES latin1".

![image](https://user-images.githubusercontent.com/18717992/74316562-cdb15d00-4d8a-11ea-9efb-92189b2bdf8e.png)

(by the way, MySQL Workbench shows database contents in proper encoding after "SET NAMES latin1" query)

**So the question is: may there be any kind of workaround for this situation?**

```
mysql> select @@character_set_client, @@character_set_results, @@character_set_connection;                                                                                                                                                   +------------------------+-------------------------+----------------------------+
| @@character_set_client | @@character_set_results | @@character_set_connection |
+------------------------+-------------------------+----------------------------+
| utf8                   | utf8                    | utf8                       |
+------------------------+-------------------------+----------------------------+
1 row in set (0,00 sec)

mysql> select * from roles limit 3;
+--------+----------+----------------------------------------------------------+
| idrole | rolename | roletitle                                                |
+--------+----------+----------------------------------------------------------+
|      1 | admin    | ÐÐ´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¾Ñ€                               |
|      2 | guest    | Ð“Ð¾ÑÑ‚ÑŒ                                               |
|      3 | default  | ÐŸÐ¾ ÑƒÐ¼Ð¾Ð»Ñ‡Ð°Ð½Ð¸ÑŽ                                  |
+--------+----------+----------------------------------------------------------+
3 rows in set (0,00 sec)

mysql> SET NAMES latin1;
Query OK, 0 rows affected (0,00 sec)

mysql> select * from roles limit 3;
+--------+----------+----------------------------+
| idrole | rolename | roletitle                  |
+--------+----------+----------------------------+
|      1 | admin    | Администратор              |
|      2 | guest    | Гость                      |
|      3 | default  | По умолчанию               |
+--------+----------+----------------------------+
3 rows in set (0,00 sec)

mysql> SHOW CREATE TABLE roles;
| roles | CREATE TABLE `roles` (
  `idrole` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rolename` varchar(45) NOT NULL,
  `roletitle` varchar(254) NOT NULL,
  PRIMARY KEY (`idrole`),
  UNIQUE KEY `rolename` (`rolename`)
) ENGINE=MyISAM AUTO_INCREMENT=22 DEFAULT CHARSET=utf8 |
```

**Comment by frops** [comment]
I have the same problem

**Comment by fkulakov** [comment]
Wow guys, I'm work the same job as you but I haven't got those problem because I'm use DataGrip

**Comment by dorbae** [comment]
Hey guys @eloscuro @frops 
I'm not sure that it will be working properly. But, try it

How about changing your driver property option **characterEncoding** and **Cp1252** is Java-Style Character Encoding Name and also it is associated with **latin1** 

<img width="819" alt="Screenshot 2020-02-12 at 18 11 50" src="https://user-images.githubusercontent.com/25657896/74320387-d83c1880-4dc3-11ea-9460-b90708a222ba.png">

<br />

MySQL documentation says that

Warning
Do not issue the query SET NAMES with Connector/J, as the driver will not detect that the character set has been changed by the query, and will continue to use the character set configured when the connection was first set up.

And I referred to [5.6 Using Character Sets and Unicode](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-charsets.html)

**Comment by mkgrgis** [comment]
[Feature request] Warning if "SET NAMES" with MYSQL. Message will be with url https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-charsets.html
Similar mechanism can be in PostgreSQL and Oracle DB.

**Comment by eloscuro** [comment]
> Hey guys @eloscuro @frops
> I'm not sure that it will be working properly. But, try it
> 
> How about changing your driver property option **characterEncoding** and **Cp1252** is Java-Style Character Encoding Name and also it is associated with **latin1**

Hello @dorbae , thank you for your answer.

I tried to change this option but I am unable to change anything inside that tab ("Driver properties").

These properties are just not editable at all. :-(

**Comment by eloscuro** [comment]
> [Feature request] Warning if "SET NAMES" command with MYSQL. Message will be with url https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-charsets.html
> Similar mechanism can be in PostgreSQL and Oracle DB.

Well, that might be a good idea, at least it will be less confusing, but it doesn't solve the problem.. :-(

**Comment by serge-rider** [comment]
@eloscuro 
> These properties are just not editable at all. :-(

What OS do you use, could you post a screenshot? They must be editable (as it is one of the main instruments for connection configuration).

**Comment by eloscuro** [comment]
@serge-rider 

Linux Mint 18.3 Sylvia KDE 64-bit

When I click to this field nothing happens...
![image](https://user-images.githubusercontent.com/18717992/74426312-2bff3e00-4e66-11ea-8a67-6deaed0f25a3.png)

![image](https://user-images.githubusercontent.com/18717992/74426348-40dbd180-4e66-11ea-8f99-b89a9866a044.png)

**Comment by serge-rider** [comment]
@eloscuro it seems to be a Linux-specific issue. However it works fine on Ubuntu.
Could you check error/debug logs for any errors? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by frops** [comment]
@serge-rider I have the same problem on Mac OS.

**Comment by serge-rider** [comment]
@frops you mean problem with MySQL encoding or problem with properties eitor?
Do you use the most recent dbeaver version? what is your MacOS version?

**Comment by dorbae** [comment]
Hello, @eloscuro @frops @serge-rider 
I tried it as you did and I also had the same problem.
However, other options were changed exactly. So, I tried to change **characterEncoding** as not Cp1252 but **cp1252** (I used a lowercase letter 'c' and I don't know why 'Cp1252' is not applied)
And it worked. I'm not still sure that this change can solve your encoding problem. But try it!
Thank you
