### ISSUE TITLE
Remove automatic grave accent from column name on autocomplete of mysql database

### ISSUE THREAD

**Issue by Consir-Informatica** [dbeaver/dbeaver#7895]
In previous version of DBeaver, it doesn't put the grave accent in column name, but now, after some updates i realize that it always puts a grave accent in column name and i always have to remove it manually when i copy and paste in my code.
I already try to change a lot of configuration but it doesn't work.
Someone know how can i remove it?
Example:
![image](https://user-images.githubusercontent.com/55191943/74341605-c1c39c00-4d86-11ea-9984-77af472f5ac1.png)

**Comment by serge-rider** [comment]
It is actually a bug in identifiers quote algorithm. We shouldn't quote identifiers in MySQL server is in case-insensitive mode.

**Comment by serge-rider** [comment]
Identifiers will be quoted only if lower_case_table_names=0.

```sql
SHOW VARIABLES like 'lower_case_table_names'
```

**Comment by uslss** [comment]
verified
