### ISSUE TITLE
Cannot modify cells in resultset

### ISSUE THREAD

**Issue by Fatbob73** [dbeaver/dbeaver#7896]
I'm using version 6.3.4 and I'm no longer able to edit cells directly in the resultset. I was able to do it a few versions ago. I can't remember which version exactly this stopped working for me. My connection is not read-only. I'm working with SQL Server 2016 and JDBC driver version 6.2.

**Comment by uslss** [comment]
seems to be duplicate of #7597 
Ticket closed
