### ISSUE TITLE
Oracle's select sysdate from dual results error

### ISSUE THREAD

**Issue by tomkidd517** [dbeaver/dbeaver#7900]
#### System information: 
- Operating system (distribution) and version : windows10
- DBeaver version : 6.3.5
I updated it to 6.3.5 because of an error in 6.3.4 

#### Connection specification:
- Database name and version : oracle 11.2 

#### Describe your question:
The result of 'select sysdate from dual' is:
It comes out as below.
2020-02-13 00:00:00

The other tool comes out like 2020-02-13 12:02:09.
Type from preferences / data formats: date
I tried to modify it to pattern :yyyy-MM-dd HH:mm:ss, but still have the same result.

![2](https://user-images.githubusercontent.com/51102284/74398575-73340180-4e5b-11ea-9a21-10dea16a9625.png)
![1](https://user-images.githubusercontent.com/51102284/74398578-74652e80-4e5b-11ea-9cdd-977f1d382188.png)

**Comment by uslss** [comment]
hi @tomkidd517 ,
unfortunately, cannot reproduce an issue. 
Could you try if something changes after checking "Use native date/time format" at Data Formats Settings

**Comment by tomkidd517** [comment]
Formatting is not expressed in the form yyyyy/mm/dd hh:mm:ss, but the data representation is correct.
I hope this issue will be dealt with as soon as possible.
Thank you for your answer.

**Comment by serge-rider** [comment]
@tomkidd517 Still can't reproduce this problem.
Please check Timestamp data type formatting (SYSDATE is TIMESTAMP).
Also check error/debug logs for any related messages (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by uslss** [comment]
there is no update on issue for a long time.
if issue is still actual for you - feel free to reopen the ticket

**Comment by tomkidd517** [comment]
![image](https://user-images.githubusercontent.com/51102284/77376630-1c074200-6db4-11ea-85ce-9ff48afee2d5.png)


Update to dbeaver7.0.1, although some modifications were made,
This is not the format of the desired data.
The desired format is 2020-03-24 09:21:58.0 => 2020-03-24 09:21:58. The last part of DATA, the '.0', is removed. This is the part shown in the picture.
However, if you check the use native date/time format option, it will come out right like 2020-03-24 09:21:58.

In addition, an example of the Preference option (blue square) is showing the wrong example.

But I'm really happy that there's some data that I want
Thank you for your efforts.

If we solve some of the problems described above, it will be done in a neat manner.
