### ISSUE TITLE
DBeaver: Grid EXPORT DATA as HTML and OPEN WITH WEB BROWSER is missing character set information

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#7902]
DBeaver - **Version 6.3.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

When using *DBeaver* to **Export data as HTML** or **Open with Web Browser**, the resulting HTML file does not contain information on what character set to use.

This has the effect that characters like the swedish ÅÄÖ characters is presented the wrong way.

![2020-02-13 09-27-45](https://user-images.githubusercontent.com/31191374/74416339-4ecd2a80-4e45-11ea-9635-4187d4b58a29.png)

**PS**. This feels like a regression error in *DBeaver*, since I have reported (and it was fixed) in ISSUE #5058.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
