### ISSUE TITLE
Connection to MariaDB via PAM failed since MariaDB Connector/J 2.5.1

### ISSUE THREAD

**Issue by Step-65** [dbeaver/dbeaver#7903]
- DBeaver version 6.3.2.202001051908
- Maxscale Version 2.4.5 and 2.4.6
- MariaDB Version 10.4.10_4
- MariaDB Connector/ J (trying versions 2.4.3, 2.5.0, 2.5.1 - 2,5,4
- Connection to Maxscale via SSL

I connect to  MariaDB over MaxScale.

Connecting via Connector/J 2.4.3 - 2.5.0 works, but Connector/J 2.5.1+ does not and that MariaDB support mentioned a new feature was added which DBeaver may need to recheck its implementation for to ensure compatibility with 2.5.1+ (and provide them the link to https://jira.mariadb.org/browse/CONJ-738)

First connection via PAM works,after that I get error message:
Could not connect to HostAddress{host='mdb-tx.ads.provinzial.com', port=33012, type='master'}. PAM authentication request multiple passwords, but 'password3' is not set

The number after "password" growth by every new try.

Don't get entries in error log files..log

**Comment by kcbaltz** [comment]
@Step-65 any luck on this?  Did you just have to downgrade your Connector until this is implemented?

**Comment by Step-65** [comment]
Nothing changed but the versions of the involved products, for example I use the newest dbeaver 7.1.2
We get still the same error I wrote above.

**Comment by kcbaltz** [comment]
@Step-65 Thanks.  I was using 2.6.0 and ran into this.  I was able to avoid it using 2.5.0 but I may try upgrading to 2.6.1 to see if that fixes it.

**Comment by Step-65** [comment]
Sorry, my last statement wasn't correct:
I get the errors with connector 2.6.1., too.



Von:	"KC Baltz" <notifications@github.com>
An:	"dbeaver/dbeaver" <dbeaver@noreply.github.com>
Kopie:	"Step-65" <Schnur@provinzial.com>, "Mention"
            <mention@noreply.github.com>
Datum:	16.07.2020 21:56
Betreff:	Re: [dbeaver/dbeaver] Connection to MariaDB via PAM failed
            since MariaDB Connector/J 2.5.1 (#7903)



@Step-65 Thanks. I was using 2.6.0 and ran into this. I was able to avoid
it using 2.5.0 but I may try upgrading to 2.6.1 to see if that fixes it.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.




Provinzial Rheinland Versicherung AG – Die Versicherung der Sparkassen ; Amtsgericht Düsseldorf HRB 41241;
Vorsitzende des Aufsichtsrats: Ulrike Lubek
Provinzial Rheinland Lebensversicherung AG – Die Versicherung der Sparkassen; Amtsgericht Düsseldorf HRB 41741;
Vorsitzender des Aufsichtsrats: Rainer Jahnke
Sitz der Gesellschaften: Provinzialplatz 1, D-40591 Düsseldorf;

Vorstände: Patric Fedlmeier, Vorsitzender; Guido Schaefers (Stv. Vors.), Dr. Volker Heinke, Sabine Krummenerl

www.provinzial.com

Bitte denken Sie an die Umwelt, bevor Sie diese E-Mail ausdrucken!

**Comment by amitghosh-inwt** [comment]
I am having the same issue with DBeaver 7.1.4 & Connector/J 2.6.2. The server is MariaDB 10.4.x. Switching back to Connector/J 2.5.0 did also avoid the issue for me.

**Comment by houndegnonm** [comment]
I have the same issue with DBVisualizer 12.0.5 and MariaDB Connector/J 2.7.3 works for me

**Comment by uslss** [comment]
Seems to be fixed for now (22.0.1)
