### ISSUE TITLE
Results set value viewer doesn't get updated in some cases

### ISSUE THREAD

**Issue by renyxadarox** [dbeaver/dbeaver#7904]
**System information:**

Windows 7 (64-bit) Build 7601 (Service Pack 1)
DBeaver 6.3.4.202002011957

**Connection specification:**

PostgreSQL 10.10
PostgreSQL JDBC Driver 42.2.9

**Describe the problem you're observing:**

When I consistently call 2 SQLs with the equal result sets (means the same set of columns), the content of Results set value viewer doesn't update the value after the 2nd SQL executed, the value of 1st SQL remains.

It refreshs the value after forced click on any value in the Grid.

![IMG_20200213_155045_521](https://user-images.githubusercontent.com/42196270/74441606-cec0b800-4e78-11ea-90a8-8b81497074ed.PNG)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
