### ISSUE TITLE
Allow More Control over Tab Names (without default prefixes)

### ISSUE THREAD

**Issue by Lonniebiz** [dbeaver/dbeaver#7905]
DBeaver: 6.3.4.202002011957

I generally have a lot of unsaved SQL Editors open at the same time and it is difficult to distinguish between tabs. You can right-click on a tab and rename it, but I'd like the ability to control exactly what is displayed on each tab instead of what is displayed by default.

For example, in the screenshot below, I renamed the tab in red to "Profit.sql":
![tabs](https://user-images.githubusercontent.com/151919/74454443-850ca900-4e49-11ea-8348-59d2811f22f8.png)

As you can see, the tab now displays `<ODBC databasName> Profit`. I'd like the ability to Rename the tab just "Profit", for example. I'm usually working in one database at a time, so the other prefixed info is always obvious and the default prefix is clutter to me. So I'd like the ability to rename new tabs any arbitrary thing I want without those default prefixes.

**Comment by uslss** [comment]
Hi @Lonniebiz ,
you could change Script title pattern in preferences
![image](https://user-images.githubusercontent.com/31996417/74543726-f5552080-4f56-11ea-92b7-191e063df2f2.png)

**Comment by Lonniebiz** [comment]
@uslss Thank you for directing me to that preference. This will do just fine.
