### ISSUE TITLE
Hot key F3 doesn't work for the fisrt time - continuance (#7792)

### ISSUE THREAD

**Issue by renyxadarox** [dbeaver/dbeaver#7908]
**System information:**

Windows 7 (64-bit) Build 7601 (Service Pack 1)
DBeaver 6.3.4.202002011957

**Connection specification:**

PostgreSQL 10.10
PostgreSQL JDBC Driver 42.2.9

**Describe the problem you're observing:**

Occasionally after the first (initial) press of hot key F3 ("SQL Editor") on Database Navigator over Connection, the window of "SQL Scripts" temporary appears and immediately closes. After the second press F3, it appears again and stays permanently.

However, I observe, a click "SQL Editor" from the right-mouse pop-up menu never causes such behaviour.

See https://youtu.be/ALuZm5EDDaU for more details.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed.
This bug was caused by new tooltips renderer. It forces focus change on tooltip hide and thus close popup panel.

**Comment by kseniiaguzeeva** [comment]
verified
