### ISSUE TITLE
Advanced copy> partial JSON copy 

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7909]
## System information:  
- Operating system (distribution) and version Win10
- DBeaver version 6.3.5
 
#### Describe the problem you're observing:

Advanced copy> JSON doesn't work for a part of a table.

#### Steps to reproduce, if exist:
1. Select several cells in a table of Data Editor
2. Select Copy as JSON in Data Editor context menu

Actual result:
1. Error message appears "Error while exporting table row  Index 1 out of bounds for length 1"
2. Selected data is not copied.

P.S. The same situation with Data export:
1. select several cells
2. select "export data" in Context Menu for the cells
3. select Json
4. check "Selected columns only"
5. go through other steps of the wizard and press "Start"

![0JDLo29Ac7](https://user-images.githubusercontent.com/51405061/74517176-b73e0980-4f22-11ea-9792-c69529a6bbdf.gif)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4203642/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
