### ISSUE TITLE
Data Transfer JSON Export contains unescaped control characters in string

### ISSUE THREAD

**Issue by AlexMax** [dbeaver/dbeaver#7914]
#### System information: 
- macOS 10.14.6 (18G3020)
- DBeaver version 6.3.4

#### Connection specification:
- MariaDB 10.2.12
- org.mariadb.jdbc:mariadb-java-client:RELEASE [2.3.0]
- Yes, SSH tunnel.

#### Describe the problem you're observing:
I have a TEXT column in a table that is currently encoded as latin1 that I am attempting to export to JSON using the Data Transfer wizard option "Export to JSON file(s)".  Attempting to parse this JSON file with PHP fails with an error, and after some time running my file through various JSON validators, I was able to discover that one of the string values in the output JSON file has unescaped raw byte `0x01` in the string.

I have verified that the source data in the database does indeed have this `0x01` byte in the string - as you can imagine, the source data is not properly encoded.  However, regardless of whatever encoding problems there might be with the original data, I think that the JSON that the wizard outputs should always be well formed JSON, which according to [the standard](https://www.json.org/json-en.html) means escaping `\`, `"`, and all control characters, of which `0x01` would be considered a control character.

Byte sequences that aren't valid unicode codepoints should also be taken into account, but I'm not sure what the correct play is here.

**Comment by kseniiaguzeeva** [comment]
Could you please write an example of source data and the converted result to JSON?

**Comment by uslss** [comment]
there is no update on the issue for a long time
additional info is needed to reproduce an issue.
ticket will be closed. feel free to reopen an issue and add info that could help to investigate it.

**Comment by zzossig** [comment]
I have the same issue
![CleanShot 2023-06-15 at 20 13 43](https://github.com/dbeaver/dbeaver/assets/52706977/6fec62a1-85bf-46c0-a157-25d628f090f3)
In the image, left side red square is the expected result.

![CleanShot 2023-06-15 at 20 17 31](https://github.com/dbeaver/dbeaver/assets/52706977/801a3341-d4f5-4d26-a775-f7001b36e7d1)
I just exported mongodb data to json
How can I export to json that is not include unicode characters?
I'm using
DBeaver Ultimate	23.1.0.202306120813
