### ISSUE TITLE
Persist changes on save?

### ISSUE THREAD

**Issue by rzfzr** [dbeaver/dbeaver#7915]
Ctrl+S brings up the "persist changes" window (after a delay), giving the options to either cancel, copy or persist.
Is there a way to not see this dialog? So that whenever I Ctrl+S it just persists the changes?
Thanks

**Comment by serge-rider** [comment]
This feature is already there:
![image](https://user-images.githubusercontent.com/6398845/80131384-d4d2c380-85a2-11ea-807b-1cbdc6f6eaae.png)
