### ISSUE TITLE
Windows x64 insaller for 6.3.4 not working

### ISSUE THREAD

**Issue by noelhibbard** [dbeaver/dbeaver#7916]
#### System information: 
- Windows 10 Pro 1909 x64
- DBeaver 6.3.4 x64

#### Connection specification:
- ODBC

#### Describe the problem you're observing:
When doing a clean install using the 6.3.4 installer you are unable to make a connection using ODBC.

#### Steps to reproduce, if exist:
- Clean install DBeaver 6.3.4 on new machine.
- Configure ODBC connection
- Try to connect

#### Include any warning/errors/backtraces from the logs
https://i.imgur.com/NZTrJlF.png
https://pastebin.com/raw/WQ5CvhWW

#### Other notes.
I first noticed this on my production machine when upgrading from 6.3.2 to 6.3.4 using Chocolaty. After upgrading to 6.3.4 my connection was no longer working. So using Chocolaty I rolled back to 6.3.2 and I was working again. Then a few days later I was installing DBeaver 6.3.4 (with choco) on a new machine and it wouldn't connect. So I rolled back to 6.3.3 and the connection started working. Then out of curiocity I upgraded from 6.3.3 to 6.3.4 and it my connection was still working. It's as if there is a new installer dependency needed for 6.3.3^ but was left out of the 6.3.4 installer.

**Comment by serge-rider** [comment]
What ODBC driver do you use?
Could you send error stacktrace? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by uslss** [comment]
there is no update for a long time.
if issue is still actual for you - feel free to reopen the ticket
