### ISSUE TITLE
Environment/connection of each tab cannot be distinguished (despite connection color)

### ISSUE THREAD

**Issue by Chealer** [dbeaver/dbeaver#7917]
DBeaver allows each connection to have a type (defined in the General settings), and each connection type to have a color. This allows associating a color to any connection, to easily and quickly distinguish several connections (see ticket #7271 for a screenshot).

While the current implementation prevents sending a request to the wrong environment, it could be even more useful if it allowed quickly identifying which editor/console the user wants to go to. For example, I can have 2 editors both on the "group" table open at the same time, but in different environments. Currently, both just have the name "group", and they both have the same text and background colors, so to determine which one is on the environment I want, I would have to know the tab's position by heart, check the tooltip, or try until I get to the right one.

It would be a lot more efficient if the tab (itself) conveyed its associated connection through color - whether that is using the connection type's color as the tab's background color or otherwise.

This issue applies to DBeaver 6.3.4.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by leonjanzen-work** [comment]
I would also love to see the background colour of the tabs match the connection type colour of the rest of the tab (when connection type colours are used). It would make it much easier to see at a glance which tabs are connected to which databases.

**Comment by uslss** [comment]
will be implemented in #15760

**Comment by xavt** [comment]
This issue https://github.com/dbeaver/dbeaver/issues/16827 is the new one to follow for the connection colored tabs.
