### ISSUE TITLE
DBeaver Connection to Postgres and Redshift Does Not Appear to Accurately Indicate Transaction Time

### ISSUE THREAD

**Issue by dt-trehman** [dbeaver/dbeaver#7919]
#### System information: 
- **Operating system (distribution) and version:** Windows 10 1830 17134.1246
- **DBeaver version:** 6.3.4, also appeared in 6.2.3
- **Additional extensions**: None

#### Connection specification:
- **Database name and version:** Redshift
- **Driver name:** AWS Redshift JDBC Driver
- **Do you use tunnels or proxies (SSH, SOCKS, etc)?** No

#### Describe the problem you're observing:
The transaction management in DBeaver appears to suddenly be working very differently and I am not sure how this occurred, or what I can do about it.

I have my connection set to manual commit, read uncommitted.
![image](https://user-images.githubusercontent.com/44380699/74570480-8a055180-4f4a-11ea-868c-e5ed29f24f8d.png)

When I first connect, I am able to both commit and rollback without running any other commands. The popup indicates an incredibly long time period, which seems wrong.
![image](https://user-images.githubusercontent.com/44380699/74570252-47dc1000-4f4a-11ea-9d9f-3b99c72ddc09.png)

Running commands does not increment the counter. However, running the commands BEGIN and ROLLBACK does. In this example, you see BEGIN and ROLLBACK increment the counter, but pg_user does not.
![image](https://user-images.githubusercontent.com/44380699/74570967-30515700-4f4b-11ea-8793-0a8016def019.png)

Normally, if you mess something up, you would need to ROLLBACK before opening a new transaction. However, that doesn't seem to be true in my version.
![image](https://user-images.githubusercontent.com/44380699/74571449-d43b0280-4f4b-11ea-8eb3-6ee1e33aef48.png)

If I look in the log, with show all queries and show previous transactions, I see this:
![image](https://user-images.githubusercontent.com/44380699/74571499-eddc4a00-4f4b-11ea-9357-c292b0a6df62.png)

It looks like it rolled back the failed one (with the appropriate message), and then ran it again for me.

Maybe this is intended behavior, although the 26 million minute transaction makes me think probably not - weirdly, that seems to line up almost like it's using minutes since January 1, 1970. I know this is probably going to be difficult to debug and I am happy to provide additional help as I can. I saw this behavior in both PostgreSQL and Redshift.

#### Steps to reproduce, if exist:
Connect to a Redshift cluster, and then hit either commit or rollback. No commands are needed. But I haven't seen anyone else able to do this.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
