### ISSUE TITLE
Refresh objects in tree reloads object text in editor window (even edited)

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#7920]
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.3.4

#### Connection specification:
- Database name and version: PostgreSQL 12
- Driver name: standard
- Do you use tunnels or proxies (SSH, SOCKS, etc): No

#### Describe the problem you're observing:

I have opened editor window with some object's text and I am editing it (e.g. view).
Then I notice, that object tree does not contain object (another) that I need. I decide to right click on the "Views", then press "Refresh (f5)".
Object list successfully refreshes BUT active (and maybe not only) editor reload its text replacing my changes with saved in database version. And I lost everything I wrote without any warning.
Is it a bug or maybe I need to change some setting? Its very annoying default behaviour.

**Comment by uslss** [comment]
hi @plotn ,
unfortunately, cannot reproduce an issue. could you add the video that helps to do that?
thanks in advance

**Comment by plotn** [comment]
![dbeaver7920_1](https://user-images.githubusercontent.com/11477081/74632501-8e12b880-5170-11ea-9355-49ad3fb48ada.png)
![dbeaver7920_2](https://user-images.githubusercontent.com/11477081/74632500-8d7a2200-5170-11ea-87d4-85789be95d43.png)
![dbeaver7920_3](https://user-images.githubusercontent.com/11477081/74632502-8eab4f00-5170-11ea-8fa4-daee039513a5.png)

here is 3 pics. When I press "refresh" the object's text becomes in "initial state" without any warning

**Comment by uslss** [comment]
thanks for the help and for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified.

**Comment by kseniiaguzeeva** [comment]
The fix affected on table renaming. The pop-up "Revert changes" appears after adding/deleting of a sign in "Table name" field (Object Editor>Properties)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
