### ISSUE TITLE
Connection process with a wrong variable cannot be interrupted

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7921]
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.5

#### Connection specification:
- Database name and version MySQL 

#### Describe the problem you're observing:
Connection process cannot be interrupted if a wrong variable is used.

#### Steps to reproduce, if exist:

1. Open Database connection settings
2. Write "${host}" in "server host" field of Main tab
3. Press Ok btn
4. Open Background tasks and press "Cancel operation". 

Actual result:
The operation is not interrupted.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
