### ISSUE TITLE
Why the trigger is not shown here?

### ISSUE THREAD

**Issue by mxwmwx** [dbeaver/dbeaver#7922]
Before click the button "SAVE" , such as create a new column,it shows:
![image](https://user-images.githubusercontent.com/37258498/74633776-5f5f0700-519d-11ea-87e6-71fbd55f88a7.png)
it means not saved
but when trigger,it shows:
![image](https://user-images.githubusercontent.com/37258498/74633869-97fee080-519d-11ea-8e1d-6ff98677b8f3.png)
I want to know how to set the settings

**Comment by kseniiaguzeeva** [comment]
It is a bug. Thank you for the report.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Now the window to create trigger opens, but  the trigger is not displayed in the list after its creating.

_P.S. postgres.public.emp_audit, 
        trigger: CREATE TRIGGER emp_audit
AFTER INSERT OR UPDATE OR DELETE ON emp
FOR EACH ROW EXECUTE PROCEDURE process_emp_audit();)_

![FVlUx4ChEL](https://user-images.githubusercontent.com/51405061/75095162-527a5300-55a3-11ea-8ca7-15fac2e6d458.gif)

**Comment by serge-rider** [comment]
@kseniiaguzeeva you have a wrong trigger text after copy-paste (it creates trigger in a different table).
Trigger body generation was fixed.

**Comment by mxwmwx** [comment]
Thanks
