### ISSUE TITLE
Not able to change View for Dashboard for Oracle

### ISSUE THREAD

**Issue by progsurfer** [dbeaver/dbeaver#7923]
Hi, 

I'm not able to change view e.g. Pie for dashboard in Oralce see screnshot.

I have the last version.

Is this feature only avaible in the EE ?

Thanks in adnvance

![grafik](https://user-images.githubusercontent.com/24592280/74642292-07130f80-5173-11ea-8f83-1a0fc84ed362.png)

**Comment by kseniiaguzeeva** [comment]
Yes, the feature is available in EE version only.
