### ISSUE TITLE
View as BOOLEAN transformation

### ISSUE THREAD

**Issue by tati-kru** [dbeaver/dbeaver#7927]
It will resolve #7848

**Comment by serge-rider** [comment]
Done
![image](https://user-images.githubusercontent.com/6398845/74970396-5b4a1800-542f-11ea-895a-18f5cac197f8.png)

**Comment by kseniiaguzeeva** [comment]
Seems, the feature affects on View/Format>Column Formats. This item of context menu cannot be opened.
![flOFE2u5w3](https://user-images.githubusercontent.com/51405061/75093612-6d919680-5594-11ea-88aa-9f8df357f3a7.gif)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4239424/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
