### ISSUE TITLE
Connecting to Open Edge Database

### ISSUE THREAD

**Issue by nikolas-jose** [dbeaver/dbeaver#7928]
I'm trying to connect to Open Edge Database, running on Lunix.
```
# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:44064           0.0.0.0:*               LISTEN      13196/_progres
```
In driver settings of DBeaver 6.3.3 I choosed OpenEdge, class com.ddtek.jdbc.*
Settings of connection:
![image](https://user-images.githubusercontent.com/61151437/74659840-1c556180-51a6-11ea-9eed-e6ad82c2a285.png)
After that I press "connect" and see just "connect to OpenEdge 33%", no errors. I waited for a day, nothing changed.
Can't see any logs.
What can be a reason of unconnecting to database?

**Comment by uslss** [comment]
is it still actual for you?

**Comment by nikolas-jose** [comment]
> is it still actual for you?

yes, actual

**Comment by uslss** [comment]
Unfortunately, we've got no env to test.
@nikolas-jose Could you please check if it is still present for you against the recent version?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still present - feel free to reopen it.
