### ISSUE TITLE
Leading and trailing whitespace trimmed when generating DDL

### ISSUE THREAD

**Issue by cbartolome** [dbeaver/dbeaver#7930]
#### System information: 
- Linux Mint 19.3 (Ubuntu 18.04.1)
- DBeaver 6.3.4 and 6.3.5

#### Connection specification:
- Microsoft SQL Server 2014
- MS SQL Server / SQL Server (Old driver, jTDS)

#### Describe the problem you're observing:

When generating DDL, some leading and trailing whitepsace is being trimmed. When generating DDL for multiple objects at once, this leads to the generated DDL separating each object with a single blank line. In contrast, DBeaver version 6.3.3 preserved such whitespace, so the generated DDL had more obvious breaks between objects.

(This is important for us because we're exporting everything at once, then using a script to work around #5693 and break the big script into one script per object. Without the larger breaks between objects, the script can't reliably tell which object a leading or trailing comment belongs to.)

#### Steps to reproduce, if exist:

1. Create two or more views and add five or so blank lines at the start of each.
1. Select all the views in the Database Navigator.
1. Right-click and choose "Generate SQL → DDL".

In version 6.3.3, the blank lines are preserved. Starting with 6.3.4, they are trimmed and condensed into single blank lines.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
I think we'll keep trim. Because sometimes DDL contains a lot of leading/trailing whitespaces, especially when it is auto-generated by database engine (e.g. in Oracle).

For better readability I'll add comments before every object DDL + extra line feed

**Comment by uslss** [comment]
verified
