### ISSUE TITLE
Wrong procedure parameter length shown

### ISSUE THREAD

**Issue by tarbul** [dbeaver/dbeaver#7931]
#### System information: 
- Operating system (distribution) and version Win7
- DBeaver version 6.3.5

#### Connection specification:
- Database name and version Firebird 2.5.9

#### Describe the problem you're observing:

Procedure parameters shows wrong data type in column _Length_ if **numeric** data type is used. If I use NUMERIC(15,4) then the length of 8 is shown instead of 15, 4:

![slika](https://user-images.githubusercontent.com/58310674/74683898-9861a080-51ca-11ea-925c-56108d6b87ca.png)

I already mentioned this glitch in #5532

#### Steps to reproduce, if exist:
Create stored procedure P_PONOVI_DEPOZIT as

```
CREATE OR ALTER PROCEDURE P_PONOVI_DEPOZIT (P_RACUN_ID INTEGER, P_ZNESEK NUMERIC(15,4))
RETURNS (
	P_RACUN_ID_NOV INTEGER
)...
```

**Comment by uslss** [comment]
hi @tarbul , 
accordingly to https://firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref25-datatypes.html
this is not length, but precision and scale `NUMERIC (precision, scale)`, so you could make these columns shown using "Configure column" button.
![image](https://user-images.githubusercontent.com/31996417/74765313-5c930d80-5294-11ea-8294-e09cf5d3fb10.png)
![image](https://user-images.githubusercontent.com/31996417/74765138-1178fa80-5294-11ea-98c6-5eb6e6a083a4.png)

**Comment by tarbul** [comment]
@uslss, you are right. Length probably means the number of bytes taken by that data type + scale + precision.

If I change parmeter's type to `...P_ZNESEK NUMERIC(6,4)...` then _Length_ drops to 4
![slika](https://user-images.githubusercontent.com/58310674/74773263-dece0280-5291-11ea-983d-6aab58e031d0.png)

But I thing I found a bug in caching procedure parameters scale / precision. When I change it to `...P_ZNESEK NUMERIC(12,4)...` - via Execute SQL script -  I have to disconnect and then connect to see the changed scale / precision. Refresh (F5) does not work, neither in _Source_ nor _Procedure parameters_ view. Could you check it?

**Comment by tarbul** [comment]
Hi @uslss, could you please add the bug label?

**Comment by tarbul** [comment]
> Hi @uslss, could you please add the bug label?

**Comment by tarbul** [comment]
Hi @tati-kru, could you please add a bug label?

**Comment by serge-rider** [comment]
So, the bug is in procedure information refresh?

**Comment by tarbul** [comment]
In procedure parameters info, to be precise.

Dne, 06. marec 2020 10:20:49 GMT+01:00, Serge Rider <notifications@github.com> sporoča:
>So, the bug is in procedure information refresh?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dbeaver/dbeaver/issues/7931#issuecomment-595677753

-- 
Poslano s programom K-9 Mail.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by tarbul** [comment]
The bug is fixed. Thanks.
