### ISSUE TITLE
DBeaver hangs when new sql script is created

### ISSUE THREAD

**Issue by sgarbarini** [dbeaver/dbeaver#7933]
#### System information: 
- Operating system (distribution) and version: Xubuntu 19.10
- DBeaver version: 6.3.4.202002011957
- Additional extensions: "Eclipse Runner Feature" version 1.3.4

#### Connection specification:
- Database name and version: Postgresql 11
- Driver name: postgresql-42.2.8.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
When creating a new script Eclipse will hang, but it only seems to hang when the "Eclipse Runner Feature" plugin is installed and the plugin view is visible.  The hang sometime leaves the "Choose SQL Script" dialog displayed, but sometimes that dialog disappears and then things hang.  I don't think this occurred with older versions of DBeaver, but I was unable to confirm that because I couldn't figure out how to revert back to an older version of DBeaver.

#### Steps to reproduce, if exist:
Make sure the "Eclipse Runner" view is a visible view within Eclipse.  Then, right click on the PostgreSQL connection and select "Sql Editor" and then, in the "Choose SQL Script" dialog, select "New Script".

**Comment by serge-rider** [comment]
Probably the same issue as in #7965

**Comment by serge-rider** [comment]
Please check Early Access version (https://dbeaver.io/files/ea)

If the bug is still there then please attach error/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files) or thread dump (https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump).

**Comment by sgarbarini** [comment]
The 7.0.0 early access version seems to fix the problem.

Thank you very much.
