### ISSUE TITLE
Installer run while OSX is in dark mode is user un-friendly

### ISSUE THREAD

**Issue by wreppun** [dbeaver/dbeaver#7935]
#### System information: 
- OSX 10.15.2 (Catalina)
- 6.3.5

#### Describe the problem you're observing:
I just upgraded via the pkg installer.  It ran and I was able to install, but it was difficult to read the text (see image)

#### Steps to reproduce, if exist:
I didn't try to reproduce :\

DBeaver's theme is set to Dark[Linux], while the general OS is in dark mode -- not sure which controls the theme of the installer.

<img width="632" alt="Screen Shot 2020-02-17 at 8 54 01 PM" src="https://user-images.githubusercontent.com/1791503/74711649-a2829f80-51c8-11ea-877e-38a5ab7a5bee.png">

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
issue still reproduces

**Comment by tati-kru** [comment]
fixed
