### ISSUE TITLE
Advanced copy - Copy as JSON - Date converted to DateTime UTC

### ISSUE THREAD

**Issue by ovirta** [dbeaver/dbeaver#7937]
#### System information: 
- Operating system (distribution) and version
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363

- DBeaver version
Version 6.3.5.202002151353
- Additional extensions

#### Connection specification:
- Database name and version
MS SQL
- Driver name
MS SQL Server / SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
NA
#### Describe the problem you're observing:
Date column data is incorrectly changed to DateTime when copying it to json format.

#### Steps to reproduce, if exist:
Select row containing a Date column
Select Advanced Copy
Select Copy to JSON
Paste data to text editor
Compare original data to pasted data.
2019-12-30 is changed to "2019-12-29T22:00:00Z"

#### Include any warning/errors/backtraces from the logs
NA

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
By default dbeaver uses ISO format because it is a standard way to represent dates in JSON.
If you need other date format you can use Export data->JSON->disable "Format dates in ISO 8601"->Start.

**Comment by kseniiaguzeeva** [comment]
Please reopen the ticket if you still need in additional comments.
