### ISSUE TITLE
Placeholders in PREPARE statement prompt for bind parameters

### ISSUE THREAD

**Issue by VoidSignal** [dbeaver/dbeaver#7938]
#### System information: 
- Elementary OS 5.1.2 (Ubuntu 18.04.3)
- DBeaver 6.3.5
- No additional extensions

#### Connection specification:
- DB: Greenplum 5.22
- Driver: org.postgresql:postgresql:RELEASE 42.2.10
- No tunnels or proxies

#### Describe the problem you're observing:
Placeholders in `PREPARE` statement prompt for bind parameters.

#### Steps to reproduce, if exist:
```SQL
PREPARE query (INT) AS
  SELECT $1, :param
;
```
will prompt to bind both `1` and `param`, where only prompt for `param` is expected.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
@VoidSignal what is the expected behavior?
You can press "Ignore" in parameter binding dialog and query will be executed as is. But it doesn't compile as `:param` can't be parsed properly.

Note: you can disable prefix `:` as named parameters prefix in SQL editor preferences.

**Comment by VoidSignal** [comment]
@serge-rider the expected behavior is that DBeaver asks for the value of `param` and not for the value of `1` as `1` is filled later in `EXECUTE` statement, not when I submit prepared query.

I can work around this issue by setting value of `1` to `$1`.
