### ISSUE TITLE
Installer restarts when setting up "for all users"

### ISSUE THREAD

**Issue by vdtoorn** [dbeaver/dbeaver#7939]
#### System information: 
- Operating system (distribution) and version
Windows 10 Enterprise 1903 18362.657
- DBeaver version
6.5.3 community
- Java version 
1.8.0_241
- Additional extensions

#### Connection specification:
non-applicable

#### Describe the problem you're observing:
Installer starts all over when installing for "all users". This is confusing and makes me wonder if I accidentally started a second installer. 

#### Steps to reproduce, if exist:
Start the installer, choose "for all users". You have to go through the whole process again.

Proposed solution: Make the "for all users" the first question, or start the elevated installer with the options provided in the first installer steps.

**Comment by serge-rider** [comment]
This is known issue with NSIS installers. Installer restarts as it needs to raise permission level to admin in order to install into program file folder.

I'm afraid we can't fix this.
We have plans to migrate to MSI installers before dbeaver 8.
