### ISSUE TITLE
Result Saving and Manual Commits broken on Update

### ISSUE THREAD

**Issue by dev-whiteflag** [dbeaver/dbeaver#7940]
#### System information: 
- Windows 10 Pro 1909
- DBeaver 6.3.5.202002151353
- No Additional Extensions

#### Connection specification:
- Database: Oracle
- Driver: oracle12c
- No Tunnels and Proxys, direct connection.

#### Describe the problem you're observing:

After the latest update, somehow manual commiting broke; transaction counter stays on none or one forever; result editing automatically saves without even asking.

![image](https://user-images.githubusercontent.com/13810730/74736779-3f2d5780-5232-11ea-9a80-d90722deef73.png)
![image](https://user-images.githubusercontent.com/13810730/74736843-66842480-5232-11ea-811d-70f8a1698b4a.png)
![image](https://user-images.githubusercontent.com/13810730/74736904-8582b680-5232-11ea-83fe-daa404409246.png)

#### Include any warning/errors/backtraces from the logs

The Log keeps showing a FrameworkEvent Error from Apache Felix.

**Comment by uslss** [comment]
hi @dev-whiteflag ,
unfortunately, cannot reproduce an issue. Is issue reproducible for UPDATE query only?

**Comment by dev-whiteflag** [comment]
No, the problem persists independently if it is a SELECT or a UPDATE query.

**Comment by serge-rider** [comment]
I also can't reproduce this. 
- When exactly commit happens? 
- Do you edit data in data editor or by SQL queries?
- If you use data editor then in what presentation, panel, etc?

Some short video would be very helpful.

**Comment by dev-whiteflag** [comment]
Data editor is working properly again, don't know what happened. But manual committing isn't working still. The short video you asked is in the zip, as Github doesn't allow any video uploading.
[DBeaver 6.3.5 - _Oracle - CPO_ Script 2020-02-20 10-29-22.mp4.zip](https://github.com/dbeaver/dbeaver/files/4230913/DBeaver.6.3.5.-._Oracle.-.CPO_.Script.2020-02-20.10-29-22.mp4.zip)

**Comment by dev-whiteflag** [comment]
Data editor is working properly again, but manual committing isn't still. I've tested with another version of DBeaver (5.2.3.201810232047) and is working properly. There's a zip with the short video you asked.
[DBeaver 6.3.5 - _Oracle - CPO_ Script-14 2020-02-20 10-36-38.mp4.zip](https://github.com/dbeaver/dbeaver/files/4230943/DBeaver.6.3.5.-._Oracle.-.CPO_.Script-14.2020-02-20.10-36-38.mp4.zip)

**Comment by dev-whiteflag** [comment]
On another note, doesn't seems to be a problem with Oracle Database, because still happens when I change databases.

**Comment by dev-whiteflag** [comment]
Issue was fixed on version 7.0.0. Thanks!
