### ISSUE TITLE
Oracle - Issues with PL/SQL in BEGIN/END

### ISSUE THREAD

**Issue by benjminer** [dbeaver/dbeaver#7944]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro 1909
- DBeaver version: 6.3.5

#### Describe the problem you're observing:
With the 6.3.5 update, I'm unable to enable or disable scheduled jobs in a begin/end block.  This block of code works in 6.3.4.

![image](https://user-images.githubusercontent.com/8846747/74763472-1e1e3400-523d-11ea-8b0e-49ed8480c44e.png)

**Comment by benjminer** [comment]
This also appears to be affecting other code blocks in BEGIN/END blocks, not just scheduled job.

![image](https://user-images.githubusercontent.com/8846747/74764538-224b5100-523f-11ea-9c8f-486ade633f18.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Result of fix of #7816 
Fixed.

**Comment by serge-rider** [comment]
Workaround: select full query  and execute with <kbd>ctrl+enter</kbd>.

**Comment by uslss** [comment]
verified
