### ISSUE TITLE
Table cell value viewer: "Auto-apply value" loses last change in some cases

### ISSUE THREAD

**Issue by Chealer** [dbeaver/dbeaver#7947]
#### System information: 
- Windows 8
- DBeaver 6.3.5
- No additional extensions

#### Connection specification:
- PostgreSQL 10.10 with PostGIS 3.0.0
- PostgreSQL JDBC Driver
- No tunnels or proxies

#### Describe the problem you're observing:
When viewing a table, the Data tab has a Value panel which allows to not only view cell contents but also edit them. The "Auto-apply value" option button at the top (with a green floppy disk icon) allows to apply changes without having to use the "Apply cell changes" button each time.

Unfortunately, depending on how edition ends and what is edited, the last change is lost is some circumstances. This happens at least in the scenario described below.
#### Steps to reproduce, if exist:
1. Open a table with an array column on a PostgreSQL connection
2. Click on an array column of a row
1. Ensure the Value panel shows
1. Select a value
1. Change the value
1. Click the "Close" X to the right of the Value tab to close the panel

**Comment by uslss** [comment]
hi @Chealer ,
am I understand you right and value isn't saving only in case you didn't finish editing (like in the first case at attached animation)?
![2020-02-19_14h10_50](https://user-images.githubusercontent.com/31996417/74829357-edfc9100-5321-11ea-8a90-f18b5f8b2055.gif)

**Comment by Chealer** [comment]
Hi @uslss,

> hi @Chealer ,
> am I understand you right and value isn't saving only in case you didn't finish editing (like in the first case at attached animation)?

Oh, yes, sorry, I forgot to specify that.
Thank you

**Comment by Chealer** [comment]
Why is this report closed?

**Comment by Chealer** [comment]
@uslss can you explain why you closed this ticket?
