### ISSUE TITLE
SAP HANA: Drop Column Syntax Error

### ISSUE THREAD

**Issue by iambudi** [dbeaver/dbeaver#7948]
SQL Syntax to drop table column in HANA Database (com.sap.db.jdbc.Driver) does not work. DBEaver produces sql :

```sql
ALTER TABLE EMPLOYEE.REGISTRATION DROP COLUMN REGISTER_DATE;
```
It will throw this error on execute : 
```bash
sql syntax error: incorrect syntax near "COLUMN"
```

This one works when run in SQL Editor:
```sql
ALTER TABLE EMPLOYEE.REGISTRATION DROP (REGISTER_DATE);
```

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
The column cannot be deleted. Seems the brackets are needed (Dbeaver produces: ALTER TABLE TESTDB.NEWTABLE_3 DROP REGISTER_DATE);
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4250722/dbeaver-debug.log)
![q6AoIZjYSK](https://user-images.githubusercontent.com/51405061/75261128-a67f7480-57fb-11ea-87d8-8c85f0ceddd7.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
