### ISSUE TITLE
Cannot connect to a database in editor, but can connect and run scripts in another editor

### ISSUE THREAD

**Issue by armienarend** [dbeaver/dbeaver#7950]
Hello

I'm using DBeaver version 6.3.5. I think that my problem started in 6.3.4.

I have a few script edit tabs open and the scripts connections across all are connected to 2 databases. 
Eg: 
**script1.sql** is connected to connection **DEV1**, **Dev01** database
**script2.sql** is connection to connection **DEV2**, **Dev02** database
**script3.sql** is connected to connection **DEV2**, **Dev02** database

So script2.sql and script3.sql are both connected to the same database via the same connection setup as DEV2, but script3.sql is able to run sql queries, but script2.sql gets the following error:
Can't open editor connection
Reason:
SQL Error [942] [S1000]: Database 'Dev02' cannot be opened because it is offline. 

If I change script2.sql to use the DEV1 connection pointing to Dev01 DB I can run my query, but pointing back to DEV2 and re-selecting the DB in the active schema selection gives me the same error as before. Yet, I can still use other edit windows (script3.sql) to execute sql queries successfully. I can also open a new window and successfully execute sql queries. 

If I close DBeaver, and even restart my machine, and open script2.sql after restart, I still cannot execute sql queries to Dev02

I almost need to find the memory settings from script2.sql and have them deleted so that script2.sql may start fresh.

I hope that my explanation is satisfactory. I changed names slightly for ease of explanation

kind regards

**Comment by kseniiaguzeeva** [comment]
Please tell which database do you use?

**Comment by armienarend** [comment]
I connect to MS SQL server.

**Comment by armienarend** [comment]
Hi, this problem seems to have been fixed by community edition version 7.0.1

**Comment by kseniiaguzeeva** [comment]
Thank you for testing. Please reopen the ticket, if it happens again.
