### ISSUE TITLE
Cannot copy column/table/etc name with keyboard

### ISSUE THREAD

**Issue by Xymanek** [dbeaver/dbeaver#7951]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.3.5
- Additional extensions: none (i think?)

#### Connection specification:
- Database name and version: MSSQL
- Driver name: the default (?)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

Cannot copy names of objects using keyboard - it seems that the shortcuts are not there:

![image](https://user-images.githubusercontent.com/2865341/74811303-dd382500-52f9-11ea-80ce-0d227e38902c.png)

![image](https://user-images.githubusercontent.com/2865341/74811336-f2ad4f00-52f9-11ea-9b59-026b55c36916.png)

![image](https://user-images.githubusercontent.com/2865341/74811379-09ec3c80-52fa-11ea-884e-fe65f01983e1.png)

If I attempt to press them anyway, nothing happens

#### Steps to reproduce, if exist:

See above

#### Include any warning/errors/backtraces from the logs

Nothing

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
