### ISSUE TITLE
Subquery column with same name of integer column table always return null

### ISSUE THREAD

**Issue by Consir-Informatica** [dbeaver/dbeaver#7954]
#### System information: 
- Windows 10 Home Single Language
- DBeaver 6.3.5
- Additional extensions: Nothing

#### Connection specification:
- Mysql 5.7.11
- Driver name: Mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When you bring a column in subquery with the same name of column table, the return is always 'null'.
Below I have a test script  to reproduce this bug.

#### Steps to reproduce, if exist:
CREATE TABLE test (
id SERIAL,
description VARCHAR(200),
idCity INTEGER
);

CREATE TABLE city (
id SERIAL,
name VARCHAR(200)
);

INSERT INTO test SET description = 'test 1', idCity = 1;
INSERT INTO city SET name = 'city test';

SELECT id, description, idCity,
(SELECT name FROM city WHERE test.idCity = city.id) idCity,  
(SELECT name FROM city WHERE test.idCity = city.id) idCity2 FROM test;

![image](https://user-images.githubusercontent.com/55191943/74831422-f8079b00-52f3-11ea-9bc9-9a9dc948d0f9.png)

**Comment by uslss** [comment]
thanks for the bug report

_note:db1.7954_

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
