### ISSUE TITLE
Filter problem. Replace field name with autocomplete

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#7957]
DB 6.3.5
PostgreSQL
![filterDB](https://user-images.githubusercontent.com/3856344/74842649-ce726200-533b-11ea-8f72-02c71f50c6fd.gif)

**Comment by serge-rider** [comment]
It happens with quoted identifiers only.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
