### ISSUE TITLE
An exception occurred when I deleted the clickhouse view

### ISSUE THREAD

**Issue by xjl456852** [dbeaver/dbeaver#7959]
#### System information: 
- Operating system (distribution) and version: windows 10
- DBeaver version: 6.3.5.202002151353
- Additional extensions: 

#### Connection specification:
- Database name and version: Clickhouse (version 19.17.4.11)
- Driver name: ru.yandex.clickhouse.ClickHouseDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
When I created a clickhouse view, I tried to delete it by right-clicking dbeaver, and an exception occurred
Exception:
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 6: VIEW jindie2.test_view. Expected one of: DATABASE, TEMPORARY, TABLE, DICTIONARY (version 19.17.4.11)

Detail info:
SQL 错误 [62]: ClickHouse exception, code: 62, host: myip, port: 8123; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 6: VIEW jindie2.test_view. Expected one of: DATABASE, TEMPORARY, TABLE, DICTIONARY (version 19.17.4.11)

  ClickHouse exception, code: 62, host: myip, port: 8123; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 6: VIEW jindie2.test_view. Expected one of: DATABASE, TEMPORARY, TABLE, DICTIONARY (version 19.17.4.11)

  ClickHouse exception, code: 62, host: myip, port: 8123; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 6: VIEW jindie2.test_view. Expected one of: DATABASE, TEMPORARY, TABLE, DICTIONARY (version 19.17.4.11)

    java.lang.Throwable: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 6: VIEW jindie2.test_view. Expected one of: DATABASE, TEMPORARY, TABLE, DICTIONARY (version 19.17.4.11)

    Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 6: VIEW jindie2.test_view. Expected one of: DATABASE, TEMPORARY, TABLE, DICTIONARY (version 19.17.4.11)

#### Steps to reproduce, if exist:

create database jindie2;
use jindie2;
create table test_table(a String,b String) ENGINE=MergeTree() PARTITION BY a ORDER BY b;
create view test_view as select a from test_table;

 to view through the database navigation -> Clickhouse-> -> clickhouse-> to view -> right-click to delete the view

Abnormal image
https://ibb.co/nBGyH5R
https://ibb.co/3c1dkt8

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
not reproducible anymore
