### ISSUE TITLE
Internal Error Creating Teradata Connection

### ISSUE THREAD

**Issue by jquirk812** [dbeaver/dbeaver#7961]
#### System information: 
- Operating system (distribution) and version - windows 7
- DBeaver version 
6.3.5.202002151353

#### Connection specification:
- Database name and version 
Teradata 15.10

#### Describe your question: 
When trying to create a Teradata connection I get the message "Internal error when opening connection wizard". Reason is "java.lang.NullPointerException". See attached file with screenshot of message. Note i have tried to uninstall and reinstall DBeaver but no change. I can create a MySql connection without an issue but not Teradata. Thank you.
[DBeaver_Issue_For_TD_Connection.docx](https://github.com/dbeaver/dbeaver/files/4226334/DBeaver_Issue_For_TD_Connection.docx)

**Comment by uslss** [comment]
hi @jquirk812 ,
unfortunately, I cannot reproduce an issue. Could you share log/debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by uslss** [comment]
there is no update on an issue more than a month.
ticket closed.
if the issue is still actual for you - feel free to reopen the ticket
