### ISSUE TITLE
MSSQL Unable to import for Table with IDENTITY-enabled columns

### ISSUE THREAD

**Issue by eksla** [dbeaver/dbeaver#7962]
#### System information: 
- Operating system (distribution) and version : Windows10 Pro 1903
- DBeaver version : 6.3.5
- Additional extensions

#### Connection specification:
- Database name and version : Microsoft SQL Server 2016 (SP2-GDR) (KB4505220) - 13.0.5101.9 (X64)
- Driver name : mssql-jdbc:RELEASE 7.4.1.jre8
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
Even if "Transfer auto-generated columns" is checked, importing a CSV file into a table that has columns with "IDENTITY" settings will always fail.
If I exclude IDENTITY-enabled columns in the import settings, the import will succeed.
It has been resolved in https://github.com/dbeaver/dbeaver/issues/2193, but the problem still exists.

#### Steps to reproduce, if exist:
See description above?

#### Include any warning/errors/backtraces from the logs

Task execution failed

 class org.jkiss.dbeaver.tools.transfer.stream.model.StreamTransferSession cannot be cast to class
  org.jkiss.dbeaver.model.exec.jdbc.JDBCSession
   (org.jkiss.dbeaver.tools.transfer.stream.model.StreamTransferSession is in unnamed module of loader
   org.eclipse.osgi.internal.loader.EquinoxClassLoader @6ee2dfa4;
    org.jkiss.dbeaver.model.exec.jdbc.JDBCSession is in unnamed module of loader
     org.eclipse.osgi.internal.loader.EquinoxClassLoader @140220cc)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
