### ISSUE TITLE
Eclipse deadlocks and hangs when DBeaver extension is installed

### ISSUE THREAD

**Issue by paulenka-aleh** [dbeaver/dbeaver#7965]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro x64
- DBeaver version: Dbeaver 6.3.4 installed on Eclipse IDE Version: 2019-12 (4.14.0) Build id: 20191212-1212
- Additional extensions: see attached eclipse configuration for other installed plugins if they could interfere

#### Connection specification:
- Database name and version - not required to reproduce
- Driver name - not required to reproduce
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - not required to reproduce

#### Describe the problem you're observing:
Eclipse operations such as build and clean start hanging when 

#### Steps to reproduce, if exist:
Start eclipse with DBeaver installed. Create some maven projects if workspace is empty. Clean all projects (several times if not reproducible right away). Eventually "Project '<name>' sync job." should appear. Cleaning or building will hang and you won't be able to cancel it. Uninstall DBeaver. Observe cleaning and building no longer hangs.

Unfortunately I cannot share my workspace and don't have time at the moment to experiment and create minimal one to reproduce.

#### Include any warning/errors/backtraces from the logs
See attached thread dump (with preceding logs) and eclipse configuration.
[eclipse-configuration.txt](https://github.com/dbeaver/dbeaver/files/4230181/eclipse-configuration.txt)
[eclipse-thread-dump.txt](https://github.com/dbeaver/dbeaver/files/4230182/eclipse-thread-dump.txt)

At the moment I either have to stop using DBeaver altogether or create a separate eclipse and separate empty workspace for it.

#### Additional note:

This might be related to the issue #7898 or might not. Since it doesn't hangs for me at startup and since all the threads involved seems to be waiting I believe it's actually a deadlock and might be a different issue from #7898.

**Comment by serge-rider** [comment]
Thanks for the bug report.
It is a bug in threads sync.

**Comment by uslss** [comment]
verified
