### ISSUE TITLE
How do you reattach a detached window

### ISSUE THREAD

**Issue by GTGeek88** [dbeaver/dbeaver#7968]
I have Googled this to no avail. Perhaps my choice of search terms was bad. I'm simply wanting to know if you can reattach a window that you have detached from the main DBeaver window. On some apps, you can just drag it back to the main window. Sometimes there is a reattach option. In the case of DBeaver, I can't figure out how to do this. Is it possible? Thanks.

**Comment by podoni** [comment]
Like eclipse "Drag and Drop"  :)

![reattach](https://user-images.githubusercontent.com/59002295/74989594-2ae09900-5484-11ea-9d1f-bd69523bb8bc.gif)

**Comment by GTGeek88** [comment]
I got a helpful reply on this . . . yet I'm not seeing it here.  Are people able to send you mail directly? I'll have to check my settings on that.

Anyway, the reply did not seem to work, but what I was not paying attention to at first was that the person was showing how to do this via drag and drop and was dragging the tab, whereas I'd been dragging the window. I guess I didn't really notice I was doing that or was thinking it didn't matter. So that works and I tested in Chrome, where you can tear off a tab and then add more tabs to that window, and the behavior is the same there. You have to drag the tab. If you can't add additional tabs in DBeaver to the resulting window when you tear off a tab, it might be nice for it to reattach regardless of whether you drag the window or the tab. And a right-click option to reattach might be nice. Ultimately, I just didn't notice I was dragging the window and not the tab.

Thanks to the person who replied, Podoni. I don't know why the reply is not showing up here. The email looks like the normal notification email and has the normal section that says:

You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe

(with proper, active links that are not shown here)

**Comment by podoni** [comment]
I'm sorry.
I deleted because it was difficult to express because I could not speak English.
I still write using Google Translator.

**Comment by GTGeek88** [comment]
It was fine. You sent the video, so that made me realize I was dragging the window, not the tab. Thanks for your help.

**Comment by solsticesteve** [comment]
Never would have figured this out if it wasn't for this post!  Thanks!!!

**Comment by drtalon123** [comment]
Thank you guys, this was driving me nuts haha. I can't believe I didn't try dragging the tab. definitely not as intuitive as dragging the whole window!
