### ISSUE TITLE
Can we get the same SSMS messages in Output window?

### ISSUE THREAD

**Issue by LRHF** [dbeaver/dbeaver#7971]
When executing a script in SSMS I get a Message like this:
```
MSO-15532 RELEASE DATA : MSO-15769 ELC Visits - UI default behaviour for ePortal & COL ,EXECUTION DATE: 21 Feb 2020 ,SERVER NAME: PEGDEVSQLD2\QA ,USER NAME: xxxx\xxxx
UPDATING HOLIDAY DATES FROM WEEKEND TO WEEKDAY
(1 row affected)
(1 row affected)
(1 row affected)
(1 row affected)
(1 row affected)
(1 row affected)
(1 row affected)
The database update succeeded
```
But in DBeaver 6.3.5 the text is different (without the "row affected" messages), confusing me, because I don't know if the rows were updated successfully. 
```
Changed database context to 'PMG'.
MSO-15532 RELEASE DATA : MSO-15769 ELC Visits - UI default behaviour for ePortal & COL ,EXECUTION DATE: 21 Feb 2020 ,SERVER NAME: PEGDEVSQLD2\DEV ,USER NAME: xxxx\xxxx
UPDATING HOLIDAY DATES FROM WEEKEND TO WEEKDAY
The database update succeeded
```
I know I can get more info from Statistic windows, but I would like to have the same messages as I have in SSMS. 

Can you please provide an option to achieve this?

Thank you!

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by E1izabeth** [comment]
Output window shows only the response from server. Seems server doesn't return these information.
Have you tried using our SQL Terminal, which combines server output, statistics and data returned?
You can check info about this feature here https://github.com/dbeaver/dbeaver/wiki/SQL-Terminal

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
