### ISSUE TITLE
Dbeaver adds 1 year to date column result

### ISSUE THREAD

**Issue by ppakawatk** [dbeaver/dbeaver#7973]
#### System information: 
- Operating system (distribution) and version
Windows 10 Pro
- DBeaver version
5.1.5

#### Connection specification:
- Database name and version
MS SQL Server

#### Describe your question:
I use Dbeaver to query result from MS SQL Server tables. 
I just noticed some strange in result of the table which contain date column. 
The date '2020-12-30' is shown in result, while the value is actually '2019-12-30' (I tested this by using bcp to get data from SQL Server, and also tried to query with where date = '2020-12-30', no result) 

Unfortunately, I cannot reproduce more cases due to company's restriction to access data tables and read only permission.

However, as I mentioned that I tried using bcp to get data from server and date is '2019-12-30', so I just guess that there is something with Dbeaver.

Could someone suggest what's actually happening with the result, or how should I deal with it?

Thank you.

**Result in DBeaver**
![Dbeaver_date](https://user-images.githubusercontent.com/46512476/75014071-16b68f00-54b8-11ea-997b-8658fc62ef7d.jpg)

**Result from BCP**
![Dbeaver_date_bcp](https://user-images.githubusercontent.com/46512476/75014083-1ae2ac80-54b8-11ea-9939-4cb9327e915b.JPG)

**Comment by kseniiaguzeeva** [comment]
Unfortunately cannot reproduce it. Could you please make a screenshot of "Data Formats" page (File>Properties>Editors> Data Editor> Data Formats)?
Also you can try the latest version - 6.3.5 (https://dbeaver.io/download/).

**Comment by ppakawatk** [comment]
> Unfortunately cannot reproduce it. Could you please make a screenshot of "Data Formats" page (File>Properties>Editors> Data Editor> Data Formats)?
> Also you can try the latest version - 6.3.5 (https://dbeaver.io/download/).

Please refer to below.
![Dbeaver_data_format](https://user-images.githubusercontent.com/46512476/75021860-b0396d00-54c7-11ea-9b48-14782fa14746.JPG)

Unfortunately, I cannot install other versions due to (company's policy -- again :( ). 
However, if it can be proved that the problem come from this version, that may be the case.

**Comment by uslss** [comment]
ticket will be closed. feel free to reopen an issue if it is reproducible for you against recent version
