### ISSUE TITLE
date = '0000-00-00' is shown as NULL in dbeaver

### ISSUE THREAD

**Issue by aardbol** [dbeaver/dbeaver#7974]
#### System information: 
- Operating system (distribution) and version: manjaro
- DBeaver version: 6.3.3 ce
- Additional extensions: none

#### Connection specification:
- Database name and version
- Driver name: mysql 5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? ssh tunnel

#### Describe the problem you're observing:
dbeaver shows '0000-00-00' date values as null. phpymadmin for example shows the values correctly.

This causes a lot of confusion when running 

> select * where date is not null

 queries

**Comment by uslss** [comment]
hi @aardbol ,
unfortunately, I cannot reproduce an issue. Works ok for me against 6.3.5
![image](https://user-images.githubusercontent.com/31996417/75114597-6a67da80-5668-11ea-8f09-aeae0deb7a0a.png)
could you check it against the recent version?

**Comment by aardbol** [comment]
I will get back to you as soon as I can. Unfortunately, the 6.3.5 version isn't in the repos of Manjaro yet. Not is 6.3.4.

**Comment by uslss** [comment]
if issue is still actual for you against recent vesion - feel free to reopen the ticket
