### ISSUE TITLE
Native client is not specified for connection - Mac

### ISSUE THREAD

**Issue by skyvondave** [dbeaver/dbeaver#7976]
#### System information: 
- Mac OS X Catalina 
- DBeaver version 6.3.5

#### Connection specification:
- this is proprietary, I don't know why you'd want this

#### Describe your question:

I'm trying to just import a database by right-clicking it then Tools > Restore Database, but the pop-up box says under Script configuration "Native client is not specified for connection"... I click the "Client..." button, it pops up "Configure local client", I click the drop-down by Native client, it's empty except for Browse, I click that, it pops up another box named Database Client Homes, which has empty fields (I'm more confused at this point), I then click Add Home, and it opens up a Finder Open box...

I read in the docs that "Native client" just means DBeaver needs some mysql exe from somewhere to run the mysqldump stuff (why this is necessary when it can do all the other things already, I don't know), but I'm not sure where to look at this point. The docs imply DBeaver will just find it if it exists in the normal places or if I have MySQL Workbench installed, which I do (version 6 and 8), but it doesn't.

I've been using MySQL Workbench for normal database stuff, then Sequel Pro for importing (because the progress bar actually works), and I had DBeaver recommended to me yesterday, but this particular feature has been vexing. I'm typing this while importing databases using Sequel Pro. Sorry that I don't know what to select for my Mac's Native MySQL client, I don't run mysql commands on it because I use GUIs that make it easier and for some reason they're just able to do import/export no problem.

**Comment by orgoldfus** [comment]
Any update on that?
I get the same error when trying to dump a MySQL DB using latest DBeaver (7.1.0)

**Comment by serge-rider** [comment]
We need to improve native client management on MacOS.

**Comment by anurag2pirad** [comment]
Any update on this?

**Comment by uslss** [comment]
@anurag2pirad function should be implemented in 7.3.1

**Comment by OlivierRicca** [comment]
Same problem on linux mint 20 and dbeaver 7.2.3 (today's update), for postgresql,  native client drop down is empty

**Comment by benzkji** [comment]
ame here, postgres on linux. 7.2.4

**Comment by benzkji** [comment]
neither in 7.2.3 nor in 7.0.0. strange, didnt notice. may be another problem?

**Comment by benzkji** [comment]
nevermind, just hit client, left bottom, browse, add /usr/bin (where the psql lives on linux)...then, choose the /usr/bin (it may be empty on initial selection!)...

**Comment by burtonboucher** [comment]
Work around for Mac:  CAN BE DANGEROUS
1. Open Terminal program
type  which mysql 
will return something like: /usr/local/bin/mysql
2. copy portion of path before bin/mysql. '/usr/local/bin' for above example
3. Open Finder. Select Go -> Go to Folder and paste in your location  /usr/local/bin
4. drag folder bin from path bar (bottom bar. if not visible turn on using Finder View -> Show Path Bar) to Finder Side Bar 
bin folder should now appear in sidebar. If not make sure you did not move bin folder! (In Finder Edit -> Undo Move of "bin") and try again. 
5. In DBeaver when you Browse to add home select bin from sidebar. Database Client home will now show /usr/local/bin

**Comment by akilovich** [comment]
Native client management on macOS has been improved. Now DBeaver tries to find Postgres, MySQL, or MariaDB in the places they are most commonly installed.

**Comment by kseniiaguzeeva** [comment]
Could you please think about following improvements:
1. Now dump via task becomes possible only after running it from context menu>Tools at first (error appears: "Native client is not found")
2. What do you think about selecting a client by default in the dump wizard? Now an additional click is needed to select it
![Screenshot 2020-12-09 at 11 24 40](https://user-images.githubusercontent.com/51405061/101603838-313f0200-3a11-11eb-95e8-6f28d1d5a34e.png)
3. Can SQL extension be available by default when you select a file for Restore (now backup is offered, but exported files have SQL extension)
![Screenshot 2020-12-09 at 11 15 06](https://user-images.githubusercontent.com/51405061/101603252-5717d700-3a10-11eb-8435-b701e5d3e082.png)
4. Can you add an option to run Dump/restore task for non-default database for PostgreSQL (now dump works only for default database in Database Task Panel)?

**Comment by akilovich** [comment]
Points 1 and 2 are valid only for connections added before my fix. You can easily bypass those problems by selecting a local client manually. Unfortunately, there is no good solution here. Points 3 and 4 are not related to this particular ticket and require their own.

**Comment by kseniiaguzeeva** [comment]
Closed. New tickets will be created for 3 and 4

**Comment by kseniiaguzeeva** [comment]
The client disappeared from EA version 7.3.1.202012162110

**Comment by akilovich** [comment]
It seems to me that this is somehow related to the upcoming dmg redesign, but the exact root cause is a mystery to me. More investigation needed.

**Comment by serge-rider** [comment]
The problem was in the mysql/psql process spawn.
Actual error was `java.io.IOException: error=316, posix_spawn failed`.

Apparently problem wa in the missing executable bit on the `jspawnhelper` binary in the bundled jre.

Fixed.

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by lotar94** [comment]
I'am using DBeaver version 7.3.3 and when i try to load a script file from. rigth click on my data base > Tools > Execute script, y select my file but i can't start the button is disable and the window show me = Native client is not specified for connection. idon't know if i'm making something wrong o is this bug still is?.

<img width="692" alt="Screen Shot 2021-01-27 at 22 02 02" src="https://user-images.githubusercontent.com/49959803/106074917-6b608200-60eb-11eb-8044-9eda90fc6cf7.png">

**Comment by kseniiaguzeeva** [comment]
Please try to press Local Client.. in the left bottom corner and select Native Client there.

**Comment by lotar94** [comment]
@kseniiaguzeeva don't show me the Native Client option, only Browse and not present. Well my postgresql is on docker container. i don't know if this maybe could be the problem.

<img width="692" alt="Screen Shot 2021-01-28 at 08 43 28" src="https://user-images.githubusercontent.com/49959803/106134959-071edc00-6146-11eb-9ef1-08fd7546dc63.png">

<img width="692" alt="Screen Shot 2021-01-28 at 08 44 52" src="https://user-images.githubusercontent.com/49959803/106134979-0ede8080-6146-11eb-8cd6-08dc547a6dce.png">

**Comment by Lemmynjash** [comment]
Was this issue solved?

**Comment by kseniiaguzeeva** [comment]
@lotar94 The docker container is the reason. DBeaver doesn't have an access to its file system. You should install the client on your local machine, and Script execute will work.

**Comment by lotar94** [comment]
@kseniiaguzeeva Thanks, yes this is the problem, i installed the client on my local machine and work fine.

**Comment by tate801** [comment]
Hi 

I am trying to setup Dbeaver for the first time and I am trying to connect to my local PC mysql server. Not sure what I am missing on this local setup

![image](https://user-images.githubusercontent.com/78865187/107531304-5ee92880-6bc5-11eb-8d80-e3fbb0768536.png)

![image](https://user-images.githubusercontent.com/78865187/107531342-69a3bd80-6bc5-11eb-98bd-4718436cb23e.png)

Anyone able to help?

**Comment by kseniiaguzeeva** [comment]
This ticket is overloaded. Could you please create a new one? Also please tell what is your issue about? Which DBeaver version do you use? Logs are often can be helpfull too  https://github.com/dbeaver/dbeaver/wiki/Log-files.

**Comment by felix-penrose** [comment]
I don't see why this is closed - this issue has been present for me on ubuntu 20.10 for a good 2 months. I literally can't dump or restore any sql files with this software. Why do I need to specify anything like this? It's not even clear what I'm expected to do to fix this (not that the user should need to)

Version 21.0.0.202102281712

**Comment by guigons** [comment]
Hi Folks! 

This steps bellow solved my problem on Mac for Postgres database:

1 - Install PostgresSQL, download here: https://www.postgresql.org/download/macosx/

2 - on DBeaver: Local Client -> Choose /Library/PostgreSQL/XX/bin

**Comment by Goddard** [comment]
I pointed the "home" to my /usr/bin folder expecting it to execute mysqldump but it doesn't find it.

I even added a ln -sf mysqldump /usr/bin/mysqldump to my home folder if it was having permission issues.  Does this operation not execute as my user?

**Comment by corleroux** [comment]
I wouldn't waste my time with this. DBeaver is an awesome tool for other things. This is not one of those things.
Just do this through the command line - here is what I did after a very long struggle, installing the deb, then the flatpak then back to the deb - and a whole lot of looking for mysql client files... I managed to land my db server in a masked state - at least I know what that is now.

Anyway - here is what worked for me:

cd /usr/bin (or where ever your mysql command is - probably right here and not at all correct from dbeaver's assessment)
mysql -u usr -p dbname < /path/to/filename.sql

et voila

I do think the issue is with mariadb and the way that the whole shebang is aliased through mysql... but I have absolutely no proof of this and am not about to dig deeper. I've spent way more time trying to restore a db by being lazy than I should have...

Good luck good people

**Comment by shashinvision** [comment]
> Work around for Mac: CAN BE DANGEROUS
> 
> 1. Open Terminal program
>    type  which mysql
>    will return something like: /usr/local/bin/mysql
> 2. copy portion of path before bin/mysql. '/usr/local/bin' for above example
> 3. Open Finder. Select Go -> Go to Folder and paste in your location  /usr/local/bin
> 4. drag folder bin from path bar (bottom bar. if not visible turn on using Finder View -> Show Path Bar) to Finder Side Bar
>    bin folder should now appear in sidebar. If not make sure you did not move bin folder! (In Finder Edit -> Undo Move of "bin") and try again.
> 5. In DBeaver when you Browse to add home select bin from sidebar. Database Client home will now show /usr/local/bin

Work for me :D Thanks

**Comment by hoanghog** [comment]
Alternative fix for Mac users with (mariaDB but will works for every dialect i think) and using brew for applications -> 
`brew install mariadb`
Restart DBeaver and choose Local Client -> your client
<img width="691" alt="image" src="https://user-images.githubusercontent.com/18429520/145559776-f304919e-088a-483d-bc0a-7678bb672c6f.png">

**Comment by Matvey16** [comment]
#14620
#15092 
#15093

**Comment by guiqui** [comment]
Well I solved the issue by clicking in Local client and typing the path to where my pg and pg_dump are installed in my local machine that in my case was /opt/bin/pg_dump

**Comment by jethrobarroso** [comment]
> Work around for Mac: CAN BE DANGEROUS
> 
> 1. Open Terminal program
>    type  which mysql
>    will return something like: /usr/local/bin/mysql
> 2. copy portion of path before bin/mysql. '/usr/local/bin' for above example
> 3. Open Finder. Select Go -> Go to Folder and paste in your location  /usr/local/bin
> 4. drag folder bin from path bar (bottom bar. if not visible turn on using Finder View -> Show Path Bar) to Finder Side Bar
>    bin folder should now appear in sidebar. If not make sure you did not move bin folder! (In Finder Edit -> Undo Move of "bin") and try again.
> 5. In DBeaver when you Browse to add home select bin from sidebar. Database Client home will now show /usr/local/bin

This is still an issue on the latest macos and dbeaver versions. But ^ worked like a charm! Thanks @burtonboucher!
Got mysql-client installed through homebrew which puts it in `/opt/homebrew/opt/mysql-client/bin`, but the client selecter in the app can't see these directories.

**Comment by ynnsnr** [comment]
On Mac, after clicking `Add Home`, you can use `command + shift + G` to go directly to any hidden folder. I'm using homebrew so I had to type `/opt/homebrew/bin`.
Solution found [here](https://david.raleche.com/web-consulting/how-to-fix-dbeaver-native-client-is-not-specified-for-connection), tested on Monterey.

**Comment by bessa3301** [comment]
https://github.com/dbeaver/dbeaver/issues/7976#issuecomment-725436879
> nevermind, just hit client, left bottom, browse, add /usr/bin (where the psql lives on linux)...then, choose the /usr/bin (it may be empty on initial selection!)...

It worked for me using docker! 🐳 🐋

**Comment by sondoskareem** [comment]
> On Mac, after clicking `Add Home`, you can use `command + shift + G` to go directly to any hidden folder. I'm using homebrew so I had to type `/opt/homebrew/bin`. Solution found [here](https://david.raleche.com/web-consulting/how-to-fix-dbeaver-native-client-is-not-specified-for-connection), tested on Monterey.

Perfectly worked for me

**Comment by ammarfaris** [comment]
> On Mac, after clicking `Add Home`, you can use `command + shift + G` to go directly to any hidden folder. I'm using homebrew so I had to type `/opt/homebrew/bin`. Solution found [here](https://david.raleche.com/web-consulting/how-to-fix-dbeaver-native-client-is-not-specified-for-connection), tested on Monterey.

Thanks for the solution

**Comment by lincoln310** [comment]
Why do I have to install postgresql on my Mac? Does it only need a client?

**Comment by azdream** [comment]
Localclient set this "/Users/{account}/Library/DBeaver/drivers"

**Comment by baditaflorin** [comment]
Can it be made to search for the path directly, using 
```
which MySQL
```
in my case this returns /opt/homebrew/bin/mysql

**Comment by BlaineOmega** [comment]
> On Mac, after clicking `Add Home`, you can use `command + shift + G` to go directly to any hidden folder. I'm using homebrew so I had to type `/opt/homebrew/bin`. Solution found [here](https://david.raleche.com/web-consulting/how-to-fix-dbeaver-native-client-is-not-specified-for-connection), tested on Monterey.

This is probably the most useful thing I've learned all year. Never knew I could do that. You are a God send!

**Comment by AliRazaLilani** [comment]
What I did on mac ? 
I am running mysql on docker .. 
`brew install mysql-client`
it gave me output 
echo 'export PATH="/usr/local/opt/mysql-client/bin:$PATH"' >> ~/.zshrc
I just added this to home and it worked
`/usr/local/opt/mysql-client/bin`

**Comment by briancalma** [comment]
On my part I import it using the command line `mysql -u user -p database_name < database_dump.sql` dbbeaver is a great tool, but its somehow frustrating that doing this simple task require such hacky solutions.

**Comment by michael1593** [comment]
Hi All, You can use `brew install mysql-client` and set `local Client` => `Home` to `/usr/local/opt/mysql-client/bin`, problem will be solved.

**Comment by jmada** [comment]
> nevermind, just hit client, left bottom, browse, add /usr/bin (where the psql lives on linux)...then, choose the /usr/bin (it may be empty on initial selection!)...

Worked for me using docker and mysql.

**Comment by davin-mcdonald-rocketlab** [comment]
Using Postgres I was able to solve this by pointing load client to `/opt/homebrew/opt/libpq/bin`

**Comment by isalmanhaider** [comment]
for me 'opt/homebrew/bin' worked

**Comment by taufikmuharrom** [comment]
> On Mac, after clicking Add Home, you can use command + shift + G to go directly to any hidden folder. I'm using homebrew so I had to type /opt/homebrew/bin.
Solution found [here](https://david.raleche.com/web-consulting/how-to-fix-dbeaver-native-client-is-not-specified-for-connection), tested on Monterey.

this is work for me ! thanks @ynnsnr

**Comment by souravpakhira2** [comment]
> > nevermind, just hit client, left bottom, browse, add /usr/bin (where the psql lives on linux)...then, choose the /usr/bin (it may be empty on initial selection!)...
> 
> Worked for me using docker and mysql.

How did you run your docker container Even im using docker with mysql but getting error mysql not found

**Comment by akbarginanjar** [comment]
bagus

**Comment by francwalter** [comment]
> > On Mac, after clicking `Add Home`, you can use `command + shift + G` to go directly to any hidden folder. I'm using homebrew so I had to type `/opt/homebrew/bin`. Solution found [here](https://david.raleche.com/web-consulting/how-to-fix-dbeaver-native-client-is-not-specified-for-connection), tested on Monterey.
> 
> This is probably the most useful thing I've learned all year. Never knew I could do that. You are a God send!

Me too! I always wondered why I couldnt choose a folder like /usr/local/ etc in the Finder's File Dialog.
Thanks a lot for that hint, now it works with /opt/homebrew/bin
Normally I use HeidiSQL where Backup is better integrated.
