### ISSUE TITLE
error -419962271

### ISSUE THREAD

**Issue by myron934** [dbeaver/dbeaver#7977]
I can't open anything

What's the meaning of this?
====
 Can't open entity 'Connections'
原因：
 -419962271

====
Can't open resource 'Script.sql'
原因：
 -419962271

**Comment by uslss** [comment]
hi @myron934 ,
could you share log/debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files) and any screenshots/videos that could help to reproduce the issue?

**Comment by myron934** [comment]
Sorry, the log is missing. 
I uninstalled the application, and I reinstalled it next day.  it worked now!
thank you!
