### ISSUE TITLE
Cannot Open Application: Startup Appears But Fails

### ISSUE THREAD

**Issue by RGAlexander216** [dbeaver/dbeaver#7980]
I'm not sure how this hasn't been reported (from what I can tell) as a large-scale issue, so I'm guessing it's just an issue that I'm having even after updating, uninstalling, reinstalling, and restarting my device. Please advise as to the logs or information that you might need to assist me or if you would prefer I use other means to get assistance.

Additionally, I attempted the suggestion in the readme.txt to run dbeaver-cli.exe -clean to clear the caches, but this did not resolve the issue either.

**Comment by uslss** [comment]
Hi @RGAlexander216 ,
could you share log/debug-log (https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by uslss** [comment]
there is no update on an issue for almost a month.
if the issue is still actual for you - feel free to reopen the ticket with additional info

**Comment by RGAlexander216** [comment]
It was until I changed the permissions to the Program Files directory. It
worked immediately after that. But if I hadn't it would have likely
continued to do as described for up to an hour I'm sure.

It's been this way for many version releases so I suspect it is still an
issue.
