### ISSUE TITLE
Delete Cascade doesn't seem to do anything (Derby db)

### ISSUE THREAD

**Issue by maphew** [dbeaver/dbeaver#7981]
#### System information: 
- Win10 x64 Home
- DBeaver version 3.5, 2020-Feb-17

#### Connection specification:
- Derby embedded db

#### Describe your question:

I'm trying to delete a table row which has several foreign key dependences. 
I select 1 row, press [Alt-Del], then [Script] button, then check "Delete Cascade" box,
then push [Persist] button, after which is error:

> SQL Error [30000] [23503]: DELETE on table 'MEDIA_ITEM' caused a violation of foreign key constraint 'GI_ITEM_FOREIGN_KEY' for key (6459).  The statement has been rolled back.
>   ERROR 23503: DELETE on table 'MEDIA_ITEM' caused a violation of foreign key constraint 'GI_ITEM_FOREIGN_KEY' for key (6459).  The statement has been rolled back.
>   DELETE on table 'MEDIA_ITEM' caused a violation of foreign key constraint 'GI_ITEM_FOREIGN_KEY' for key (6459).  The statement has been rolled back.

![image](https://user-images.githubusercontent.com/486200/75100413-0834aa00-5582-11ea-8115-be9a21c2ac8d.png)

.
On re-opening the [Script] preview the "Delete Casade" box is unchecked again.

Based on on [a postgres issue](https://github.com/dbeaver/dbeaver/issues/5783) I appended `CASCADE` to the delete statement and executed in SQL Editor panel. That yields a syntax error.
~~~
DELETE FROM APP.MEDIA_ITEM
	WHERE ID=6459 CASCADE;
~~~

Am I not using this feature correctly?
Or perhaps it's not implemented for Derby db?

**Comment by uslss** [comment]
Hi @maphew ,
unfortunately, cannot reproduce an issue. Works ok for me.
![image](https://user-images.githubusercontent.com/31996417/78887504-a4e6d480-7a68-11ea-9c2a-13753e01413b.png)
Probably you could post tables ddl that could be helpful with reproducing an issue?

**Comment by uslss** [comment]
works ok for me.
if issue is still actual for you - feel free to reopen the ticket
