### ISSUE TITLE
Building on AIX: X509CertInfo cannot be resolved to a type 

### ISSUE THREAD

**Issue by arozehnal** [dbeaver/dbeaver#7985]
#### System information: 
- Operating system (distribution) and version: AIX 7.2.0.0, IBM J9 VM (build 2.9, JRE 1.8.0 AIX )
- DBeaver version: dbeaver-devel

[err.gz](https://github.com/dbeaver/dbeaver/files/4242505/err.gz)

#### Describe the problem you're observing:
Build on AIX  ends with an error X509CertInfo cannot be resolved to a type 

#### Steps to reproduce, if exist:
git clone https://github.com/dbeaver/dbeaver.git dbeaver
cd dbeaver
mvn package

**Comment by serge-rider** [comment]
1. We don't support AIX officially, as well as IBM JRE.
2. Packages sun.security.x509 must present in your JRE (they definitely were in Java 1.8). So this may be an incorrect Java installation.
3. Can you try the same with OpenJDK?

**Comment by arozehnal** [comment]
OK, I understand - you don't  support AIX.
The my build dbeaver on AIX with OpenJDK finished OK See out_openjdk.gz.
Binaries are in product/standalone/target/products. But this are binaries for supported platform. 
Do I have the opportunity to run my build of dbeaver on the AIX?
How could I do that? I have X window subsystem working.

[out_openjdk.gz](https://github.com/dbeaver/dbeaver/files/4251370/out_openjdk.gz)

**Comment by serge-rider** [comment]
Unfortunately Eclipse platform doesn't support AIX anymore.
You could try to use older Eclipse platform (Neon?) - you can change it in the root pom.xml.

But there is no guarantee that it will work as we don't test against old platform version.
