### ISSUE TITLE
ctrl+enter only executes the first command if there are mutliple commands on a single line separated by semicolon

### ISSUE THREAD

**Issue by abolognino** [dbeaver/dbeaver#7987]
#### System information: 
- Operating system (distribution) and version: Ubuntu 19.10
- DBeaver version: 6.3.5
- Additional extensions: Vrapper

#### Connection specification:
- Database name and version: PostgreSQL 11
- Driver name: PostgreSQL Standard Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
I have an editor with multiple commands on a single line, separated by a semicolon.
I'd expect ctrl+enter to execute all of them, not just the first one.

#### Steps to reproduce, if exist:
open an editor, type

```
create table foo (id serial); create table foo2 (id serial);
```

press `ctrl+enter`

only foo gets created

**Comment by uslss** [comment]
Hi @abolognino ,
this is expected behavior. To execute all the commands you should use "Execute SQL Script" (Alt+X)

**Comment by abolognino** [comment]
@uslss I'll explain my usecase: I have a list of commands to execute provided by someone else, I paste them and execute them one by one with ctrl+enter. If there are multiple commands on a single line only the first one is executed and I'll often miss that.

I understand that alt+x executes the whole script, but there are cases where I want to check each command first and execute them one by one.

Selecting the whole line and pressing ctrl+enter does what I expect.

This is a design decision more than anything else though. Feel free to close it.

**Comment by p91paul** [comment]
@abolognino alt+x doesn't always execute the whole script: if you select some statements, it will execute only the selected portion of the script.
