### ISSUE TITLE
PostgresSQL timestamp without timezone problem in result set

### ISSUE THREAD

**Issue by neilnsmith** [dbeaver/dbeaver#7989]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.3.5
- Java version: 11.0.5
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgresSQL 12
- Driver name: PostgreSQL JDBC Driver 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
If I have a table with a column of type TIMESTAMP (without time zone), the values should be shown in the result set as the contents of the column, with no conversions.  However, what is actually happening is that in some cases it is being converted to a local time, as though it were a TIMESTAMP WITH TIME ZONE.  For instance where the time does not exist in local timezone due to daylight saving (and possibly other instances).

#### Steps to reproduce, if exist:
This demonstrates the issue, at least if you're in the UK
```
--drop table ts_tz_test;

create table ts_tz_test (
    ts_without_tz timestamp without time zone,
    ts_with_tz timestamp with time zone
);

insert into ts_tz_test values ('2020-03-29 00:00:00+00', '2020-03-29 00:00:00+00');
insert into ts_tz_test values ('2020-03-29 01:00:00+00', '2020-03-29 01:00:00+00');
insert into ts_tz_test values ('2020-03-29 02:00:00+00', '2020-03-29 02:00:00+00');
insert into ts_tz_test values ('2020-03-29 03:00:00+00', '2020-03-29 03:00:00+00');

commit;

--SET TIMEZONE='Europe/London';

select * from ts_tz_test;
```
*if you're not in the UK, just substitute times that span the Spring daylight saving clock change.*

I'd expect the output to be:

| ts_without_tz | ts_with_tz |
|----------------|------------|
| 2020-03-29 00:00:00 | 2020-03-29 00:00:00 |
| 2020-03-29 01:00:00 | 2020-03-29 02:00:00 |
| 2020-03-29 02:00:00 | 2020-03-29 03:00:00 |
| 2020-03-29 03:00:00 | 2020-03-29 04:00:00 |

The first column is not timezone aware, so should just be whatever value is in the table, and the second column is time zone aware, so should be converted to the local time.  At 01:00 on March 29th the clock, in UK time, jumps forward to 02:00.

However, what is actually shown is 

| ts_without_tz | ts_with_tz |
|----------------|------------|
| 2020-03-29 00:00:00 | 2020-03-29 00:00:00 |
| 2020-03-29 **02:00:00** | 2020-03-29 02:00:00 |
| 2020-03-29 02:00:00 | 2020-03-29 03:00:00 |
| 2020-03-29 03:00:00 | 2020-03-29 04:00:00 |

If the first column is "without time zone" then no assumption should be made about what time zone it is actually from, so why is it changing to 02:00?

Viewing the same data in psql, or HeidiSQL, confirms that it is a display problem in dbeaver, and the saved data in the table is as expected.

#### Include any warning/errors/backtraces from the logs
None

**Comment by austin-beer** [comment]
I just ran into this same issue with DBeaver 7.0.0 with PostgreSQL 10. It took me quite awhile before I realized that DBeaver was incorrectly displaying the timestamps in my "timestamp without time zone" columns, but just during the 1 hour where the local clock sprung forward in time. During other times it displayed the timestamps correctly.

To work around the issue I enabled "Use native date/time format."

**Comment by uslss** [comment]
thanks for the bug report
dev1. postgres.public.ts_tz_test
![image](https://user-images.githubusercontent.com/31996417/78889226-f04eb200-7a6b-11ea-9a0f-bdf1d8bff191.png)

**Comment by serge-rider** [comment]
PostgreSQL JDBC driver uses local machine timezone. All timestamp values (with tz or without tz) are converted. 
See https://stackoverflow.com/questions/18447995/postgresql-9-2-jdbc-driver-uses-client-time-zone

Workaround: set local timezone to UTC (add `-Duser.timezone=UTC` in the end of dbeaver.ini). Thus all timestamps will be converted to UTC (or another tz on your choice).

I don't see how can we fix it from dbeaver side..

**Comment by austin-beer** [comment]
That makes sense. However, I was able to work around this issue by enabling **Use native date/time format**, _without_ using `-Duser.timezone=UTC`. If the issue is with the JDBC driver, then why did that work? Does that option bypass the timezone conversion in the JDBC driver?
