### ISSUE TITLE
Find window Hidden

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#7992]
Find window(Ctrl+F) is hidden from view when "Result panel" is maximized.

Can you tell me how to fix it?

![image](https://user-images.githubusercontent.com/59002295/75217429-6360d980-57da-11ea-8806-8b1c7f09c280.png)

**Comment by uslss** [comment]
hi @podoni ,
unfortunately cannot reproduce an issue. Find window is always shown at the front of app for me.
Probably you could add some special steps or videos that could help to reproduce an issue?

**Comment by podoni** [comment]
hi @uslss 

I'm sorry.
Occurs when the "inline Search" option is set after installing the "DevStyle" plugin.
The default DBeaver "Find Window" is no problem.

![image](https://user-images.githubusercontent.com/59002295/75297817-2e08ca00-5874-11ea-91cc-c28cbb4e2c9f.png)

DevStyle "inline Search"
![image](https://user-images.githubusercontent.com/59002295/75297826-3234e780-5874-11ea-8b56-5753f2c66501.png)


Thank for reply.
