### ISSUE TITLE
Export data error for queries Using variable

### ISSUE THREAD

**Issue by akgarg511** [dbeaver/dbeaver#7995]
#### System information: 
- Operating system (distribution) and version : Windows 10 Pro
- DBeaver version : 6.3.5
- Additional extensions

#### Connection specification:
Using Postgresql 9.6.

#### Describe the problem you're observing:

While doing csv export for queries having variables, it is not working. it is saying syntax error.  Simple execute works and getting the data.
Query used is:
@set var_sid = 4
select * from <Table_Name> where <column_name> =:var_sid;

#### Steps to reproduce, if exist:

Select the Query and right click on it > Execute > Export from Query > CSV export.

and I got this error

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/61458761/75243753-7b435800-57f0-11ea-9b7f-73b696c2cf5e.png)

**Comment by uslss** [comment]
thanks for the bug report.
as a workaround you could select set and select statements and then execute Export from, query
![image](https://user-images.githubusercontent.com/31996417/75249255-fd2e8380-57e6-11ea-8f5d-358e202d5ffb.png)

**Comment by akgarg511** [comment]
> 
> #### System information:
> 
>     * Operating system (distribution) and version : Windows 10 Pro
> 
>     * DBeaver version : 6.3.5
> 
>     * Additional extensions
> 
> 
> #### Connection specification:
> 
> Using Postgresql 9.6.
> #### Describe the problem you're observing:
> 
> While doing csv export for queries having variables, it is not working. it is saying syntax error. Simple execute works and getting the data.
> Query used is:
> @set var_sid = 4
> select * from <Table_Name> where <column_name> =:var_sid;
> #### Steps to reproduce, if exist:
> 
> Select the Query and right click on it > Execute > Export from Query > CSV export.
> 
> and I got this error
> #### Include any warning/errors/backtraces from the logs
> 
> ![image](https://user-images.githubusercontent.com/61458761/75243753-7b435800-57f0-11ea-9b7f-73b696c2cf5e.png)

Hello @uslss ,

Thanks for the response. But, by selecting set and select both statements, I'm getting the same error.

Regards,
Amit Kumar

**Comment by serge-rider** [comment]
Can't reproduce this anymore.
Please check version 7.0 - there were several fixes of data export task.
