### ISSUE TITLE
Autocompletion isn't working for Views if columns' names aren't in English

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7996]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.5

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
It seems that autocompletion isn't working for Views in SQL editor for columns if names are e.g. in Russian. But it works in View filter fields

![image](https://user-images.githubusercontent.com/31996417/75245955-dfa9eb80-57df-11ea-99af-7fc1c84335da.png)

**Comment by zkelo** [comment]
Same problem. But in my case I can't use autocomplete also in filter field

![1582632602](https://user-images.githubusercontent.com/13527447/75246583-1f250780-57e1-11ea-8c4b-ee5492ca2e4c.png)

**Comment by serge-rider** [comment]
First problem caused by space in table name. Non-latin letters are fine.
Second problem caused by a very different reason (autocomplete popup is triggered only by latin letters).

**Comment by serge-rider** [comment]
Unfortunately we can't fix any of these issues. 

First one is a limitation of our SQL parse algorithms. Probably we need a FR ticket for this.

Second one is a limitation of Eclipse platform (it is not possible to specify all possible unicode characters as triggers + it is not possible to redefine popup trigger behavior).
