### ISSUE TITLE
As a superuser,how could I grant the Privileges(such as create/drop) of the database to a normal user

### ISSUE THREAD

**Issue by mxwmwx** [dbeaver/dbeaver#7999]
The UI shows :
![image](https://user-images.githubusercontent.com/37258498/75318561-ac319480-58a5-11ea-8180-d9645b27bfc2.png)
I think it should like this which used in the trigger:
![image](https://user-images.githubusercontent.com/37258498/75318718-029ed300-58a6-11ea-83bb-def338ce714c.png)

**Comment by uslss** [comment]
seems that this is the same ticket as #7986 
closed as duplicate
