### ISSUE TITLE
PostgreSQL: include permissions in database DDL

### ISSUE THREAD

**Issue by mxwmwx** [dbeaver/dbeaver#8000]
Hi,

Would it be possible to add grants in database DDL for PostgreSQL?

Thanks in advance.

**Comment by uslss** [comment]
you could see permissions using "Show permissions" button
![image](https://user-images.githubusercontent.com/31996417/75328135-91075a80-588e-11ea-9376-2cb8321148e5.png)

**Comment by mxwmwx** [comment]
it about the schema , I want to show the statements like this :
Grant USEAGE on database dbname to user,
as a superuser,I think I could grant the (DROP/CREATE) to normal user,so that when the normal user log in , the user can create or drop a database

**Comment by uslss** [comment]
thanks for suggestion

**Comment by LonwoLonwo** [comment]
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/17206
