### ISSUE TITLE
Remove automatic grave accent from source view of mariadb database

### ISSUE THREAD

**Issue by mjjong** [dbeaver/dbeaver#8001]
#### System information: DBeaver 6.3.5
- Operating system (distribution) and version
- DBeaver version

#### Connection specification: MariaDB 10.2.29
- Database name and version

#### Describe your question:

Hi, Why don't I put in a grave accent in the Source view of DBeaver, but it looks automatic?

I want remove the grave accent.

![image](https://user-images.githubusercontent.com/61495657/75328776-de50ef80-58c1-11ea-9b51-4131bf7e5fde.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
We use `SHOW CREATE TABLE` for table DDL.
This is how MySQL/MariaDB server generates table DDL, we can't affect it from dbeaver side.
