### ISSUE TITLE
Templates: when you update an existing template (title or body), 'templates' view does not refresh until you create a new one.

### ISSUE THREAD

**Issue by mikkk3l** [dbeaver/dbeaver#8002]
#### System information: 
- Operating system (distribution) and version. Windows 10.0.17134 
- DBeaver version 6.3.5
- Additional extensions

#### Connection specification:
- Database name and version: not relevant
- Driver name: not relevant
- Do you use tunnels or proxies (SSH, SOCKS, etc)? not relevant

#### Steps to reproduce, if exist:
Open templates view.
Create new Template with parameters.
Save template.
Edit template.
Change name.
Templates view does not change.

**Comment by uslss** [comment]
hi @mikkk3l ,
unfortunately, cannot reproduce an issue. could you post any screenshot or video that could help to reproduce it?

**Comment by mikkk3l** [comment]
I attach a gif with the problem:

**Comment by mikkk3l** [comment]
I don' know why but I canno attach a vídeo...
I've tried, gif, avi, zip, encripted zip.... no way
"Something went really wrong, and we can't process that file"

Any help for this meta-issue?

**Comment by mikkk3l** [comment]
I've uploaded here:
https://ibb.co/KmzD9vM

**Comment by mikkk3l** [comment]
![2020-02-28_tempates dbeaver](https://user-images.githubusercontent.com/15341836/75531880-7959de80-5a14-11ea-92aa-172adbae49d4.gif)
It works in Firefox...

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Templates view comes from Eclipse platform. We can't fix it.
Workaround:  use preferences page DBeaver->Editors->SQL Editor->Templates

**Comment by mikkk3l** [comment]
Thank you. Btw, are you considering migrating to IntelliJ in the future?
