### ISSUE TITLE
Add Artifact fails to download non .jar files

### ISSUE THREAD

**Issue by nazar554** [dbeaver/dbeaver#8003]
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise 1909 18363.657
- DBeaver version: 6.3.5
- Additional extensions

#### Connection specification:
- Database name and version: Microsoft SQL Server 2019
- Driver name: mssql-jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

In order to use Windows authentication I need to add [`.dll`](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc_auth/8.2.0.x64) file from maven. But DBeaver tries to download `.jar` file instead.

#### Steps to reproduce, if exist:

Click add artifact, enter 
Group ID: `com.microsoft.sqlserver`
Artifact ID: `mssql-jdbc_auth`
Release: `8.2.0.x64`

#### Include any warning/errors/backtraces from the logs
```
Driver file download failed.
Do you want to retry?

Reason:
Can't open 'https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc_auth/8.2.0.x64/mssql-jdbc_auth-8.2.0.x64.jar': Not Found
```

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
It is already fixed as a part of SQL Server driver update.

**Comment by uslss** [comment]
verified
