### ISSUE TITLE
PostgreSQL Export from query binding parameters issue

### ISSUE THREAD

**Issue by joblolabinette** [dbeaver/dbeaver#8006]
#### System information: 
- Operating system (distribution) and version : Windows 7
- DBeaver version: 6.3.5
- Additional extensions

#### Connection specification:
- Database name and version : PostgreSQL 10.9
- Driver name: DBeaver default
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When I use the "Export from Query" with parameters ( : ). I get the pop up at the end to put my parameters. However, it fails with an error.

If instead I run the query and right click on the results to export results it still asks for parameters but then it works.

#### Steps to reproduce, if exist:
select :variable
from table
limit 100

Right click and select export from query.

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/3724319/75358489-f81e1280-5880-11ea-9d14-51f1434d7e58.png)

**Comment by uslss** [comment]
Hi @joblolabinette ,
unfortunately, cannot reproduce an issue. Could you post a video?

**Comment by joblolabinette** [comment]
Tried to reproduce in 7.0.0 and was not able to.
