### ISSUE TITLE
Client is not found if MySQL/Postgresql script runs via Task.

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8008]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 6.3.5

#### Connection specification:
- Database name and version MySQL, Postgres

#### Describe the problem you're observing:
Client is not found if MySQL/Postgresql script runs via Task.

#### Steps to reproduce, if exist:
Steps:
1. Create  mysql/postgresql script/dump task
2. Select Mysql (or postgresql) Binaries in "Native client" field
3. Run the task

Actual result: 
1. the run is failed
2. Error appears "Error executing process
  Utility 'mysql.exe' not found in client home 'MySQL Binaries' :\Users\ksu1\AppData\Local\DBeaverEE\MySQL Binaries)"

Workaround:
Run the same script/dump using context menu of DB Navigator.

Actual result:
The Dump/Script procedure runs successfully
The task with the same procedure can be run after it.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce anymore

**Comment by billyfan** [comment]
This exact error happened to me.

I found that it only appears when I tried to run script in the connections that connect via SSH tunnel
