### ISSUE TITLE
Cannot open Query Builder in Enterprise Edition

### ISSUE THREAD

**Issue by billjwilliamson** [dbeaver/dbeaver#8009]
I have purchased and paid for EE, but Query Builder does not open up. 

lic issued 15/02/20 6:41 PM
Version 6.3.0.202001141657

On ubuntu 18.0x

Pres CTRL-B or select SQLEDITOR|QUERYBUILDER and nothing new.

**Comment by serge-rider** [comment]
I can't reproduce this issue. But it may be somehow related to your system configuration.
Could you check error view (or log file) for any errors? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by billjwilliamson** [comment]
Hi Serge, 
figured out the gotcha. Requires an active SQL Editor window open before the Query Builder becomes active.  Is not a bug, just an obscured command.
