### ISSUE TITLE
out of sync left and right part of interface

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#8011]
#### System information: 
- Operating system (distribution) and version WINDOWS 10 64bit
- DBeaver version EE 6.3.0

#### Describe the problem you're observing:
In the left part of interface right click on object CONNECTION in object tree. 
I see the following menu items
CONNECT this item is hidden
CHECK CONNECT
DISCONNECT

I guess that the connection is work. But if i click on view or materialized view in object tree and go to the source tab of this object, i look next message:

/* ERROR WHILE READING SOURCE:
Error reading view definition: Соединение уже было закрыто(The connection has already been closed)
*/

Item CONNECT  in objects menu still not available

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed (connection recovery added in SQL source loading)

**Comment by uslss** [comment]
verified
