### ISSUE TITLE
oracle 11g systimestamp return null

### ISSUE THREAD

**Issue by minrenkon** [dbeaver/dbeaver#8012]
#### System information: 
- Windows 10 
- DBeaver 6.3.5.202002151353
- Additional extensions

#### Connection specification:
- Database: Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
- Driver name: ojdbc6.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
Using systimestamp funtion, but execute return null.

#### Steps to reproduce, if exist:
SELECT sysdate, systimestamp(6), to_char(systimestamp, 'yyyy-mm-dd hh24:mi:ssxff') FROM dual;
SYSDATE            |SYSTIMESTAMP(6)|TO_CHAR(SYSTIMESTAMP,'YYYY-MM-DDHH24:MI:SSXFF')|
-------------------|---------------|-----------------------------------------------|
2020-2-27 14.58.9.0|         [NULL]|2020-02-27 14:58:09.691790                     |

**Comment by uslss** [comment]
@minrenkon , is it still actual?
It is not reproducible for me against oracle 12.

**Comment by minrenkon** [comment]
thx
