### ISSUE TITLE
Show only "my" databases under the connection [PostgreSQL maybe other]

### ISSUE THREAD

**Issue by Vlczech** [dbeaver/dbeaver#8013]
**Is your feature request related to a problem? Please describe.**
On the PostgreSQL connections settings, I have choice "Show all databases" - so I have the choice between display only one DB or all databases.
![obrazek](https://user-images.githubusercontent.com/10884140/75421095-d0d74c00-5939-11ea-9311-158e7131499b.png)

**Describe the solution you'd like**
There are more possible solutions, which databases to display:
* display those, where I'm the owner
* display those, where I'm granted to connect (preferred)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
Option to show/not show database not available for the current user is available in preferences for now
![image](https://user-images.githubusercontent.com/31996417/162742009-cb2e38a3-62e3-4d3a-ace9-713337b2e495.png)
