### ISSUE TITLE
[PostgreSQL] Database permissions

### ISSUE THREAD

**Issue by Vlczech** [dbeaver/dbeaver#8014]
**Is your feature request related to a problem? Please describe.**
I don't know, if this is a bug or missing feature, so I decided to mark a feature. There are permissions, on tables and also on schemas, but database permissions missing. This functionality is only in <some database> - Roles - <some role>.

Schema permissions:
![obrazek](https://user-images.githubusercontent.com/10884140/75422330-991dd380-593c-11ea-8775-882c3b8f6e3b.png)

Database permissions missing (can be achieved through roles, which is not so user-friendly: open role, change permission, close role, open another role, ...):
![obrazek](https://user-images.githubusercontent.com/10884140/75422445-e26e2300-593c-11ea-9ce8-fa2e9ceadc0f.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
duplicates #7994
