### ISSUE TITLE
DBeaver 6.3.x does not execute bootstrap queries for me

### ISSUE THREAD

**Issue by amivanovano** [dbeaver/dbeaver#8015]
#### Connection specification:
- Database name and version: Informix Dynamic Server 12.10.FC7
- Driver name: Informix JDBC Driver for Informix Dynamic Server 4.50.JC3
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Subj.
I returned to 6.2.5

![image](https://user-images.githubusercontent.com/28041955/75425483-db9eda80-5953-11ea-8541-33cb1459d5ea.png)

**Comment by serge-rider** [comment]
@amivanovano I can't reproduce this. how do you know it doesn't execute queries?

You can open Query Manager view to see all queries executed during connection init.

**Comment by amivanovano** [comment]
I use Informix SQL command SET ROLE xxx during connection ( in bootstrap queries ).
This role grands me permissions for some database objects ( tables for example ).
When I try to do SELECT from these tables I get error: no SELECT permission for 
( all versions 6.3.x and 7.0.0 ). 
I always got permissions in versions prior 6.3.x but I never seen SET ROLE in Query Manager (may be  this is my wrong look!)

**Comment by uslss** [comment]
@amivanovano , is it still reproducible in 7.0 or 7.0.1 versions for you?

**Comment by amivanovano** [comment]
Yes, it is. 
It reproducible in all 6.3x, 7.0, 7.01
But I did not try uninstall DBeaver and install it from scratch.
One day it helped me.

**Comment by uslss** [comment]
cannot reproduce an issue. if it is still actual for you - feel free to reopen the ticket

**Comment by GameHab** [comment]
My software version is 23.3.3,issue still actual.
Db type is Hive,and the query is `set hive.execution.engine=spark;`
but when it connected,i query the config.
```sql
set hive.execution.engine
--output
hive.execution.engine=mr
```
The bootstrap queries does not execute yet.
