### ISSUE TITLE
Auto-commit works always when script is executed

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8017]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 6.3.5

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
Even if I disable Auto-commit for script, and run task with two update scripts (first - correct, second - incorrect), results of first script are always commited.

**Comment by serge-rider** [comment]
@uslss how can I validate this?
