### ISSUE TITLE
No functions with oracle 19 c

### ISSUE THREAD

**Issue by gregorn** [dbeaver/dbeaver#8018]
#### System information: 
- Operating system (distribution) and version
  MAC OS 10.15.3
- DBeaver version
 6.3.5.202002151353
- Additional extensions

#### Connection specification:
- Database name and version
 oracle 19 c
- Driver name
 instant driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no
#### Describe the problem you're observing:
I can't see functions / the folder is missing

**Comment by uslss** [comment]
Hi @gregorn ,
you could find both functions and procedures in Procedures folder
