### ISSUE TITLE
Why does DBeaver reformat statements when creating a view in PostgreSQL?

### ISSUE THREAD

**Issue by tdauth** [dbeaver/dbeaver#8020]
#### System information: 
- Operating system (distribution) and version: ubuntu 5.3.0-40-generic #32~18.04.1-Ubuntu
- DBeaver version: Version 6.3.5.202002151353

#### Connection specification:
- Database name and version: PostgreSQL 10

#### Describe your question:

When I create a new view, DBeaver reformats my source by adding explicit type conversions such as `::text`.
It also adds LATERAL to from statements such as `jsonb_array_elements` etc.
How can I prevent it from reformatting my PostgreSQL statement? I want to keep my original statement in the schema.

**Comment by kseniiaguzeeva** [comment]
Could you please write an example of such view statement?

**Comment by uslss** [comment]
there are not any updates for a long time. 
If issue is still actual for you - feel free to reopen the ticket
