### ISSUE TITLE
Refresh is needed to apply changes in "auto-fetch next segment"

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8021]
#### System information: 
- Operating system (distribution) and version Win 10
- DBeaver version 7.0.0

#### Describe the problem you're observing:
Refresh is needed to apply changes in "auto-fetch next segment"
#### Steps to reproduce, if exist:

1. Open a table with several pages in data editor
2. Scroll to the next page> the next page is fetched
3. Disable "auto-fetch next segment"
4. Scroll to the next page

Actual result:
The next page is fetched.
Note: "auto-fetch next segment" becomes disabled after refreshing the table.

![LYh8dBTxqY](https://user-images.githubusercontent.com/51405061/75450422-d48dc180-597f-11ea-9c0a-df74ba092f1e.gif)

**Comment by serge-rider** [comment]
It was made to keep performance high. Fetch may occur on any cell paint + checking preference settings for every cell is too expensive.
So, this option, as some other UI/behavioral options, takes effect only after refresh.

**Comment by serge-rider** [comment]
We handled this in #8279 
Prefs change must work now

**Comment by uslss** [comment]
verified
