### ISSUE TITLE
[ERD] Dbeaver collapses when the column header color is changed

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8022]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.0

#### Describe the problem you're observing:
[ERD] Dbeaver collapses when the column header color changes
#### Steps to reproduce, if exist:
1. Open a ERD
2. Select "Customize" in a table context menu.
3. Set a color
4. Press OK

Actual result:
Dbeaver collapses

![KiNb19L5Nm](https://user-images.githubusercontent.com/51405061/75455168-5cc49480-5989-11ea-85e4-2d381cc1fe30.gif)

**Comment by serge-rider** [comment]
Can't reproduce in my env.
However I have a clue. Please test the fix.

**Comment by kseniiaguzeeva** [comment]
DBeaver blinks now, but doesn't collapse. Verified.
