### ISSUE TITLE
[SQL Editor] "Bind Parameters" Window appears after every fetched page

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8023]
Win10
DBeaver 7.0.0 
#### Describe the problem you're observing:
"Bind Parameters" Window appears after every fetched page if SQL Statement is with a bind parameter. 

#### Steps to reproduce, if exist:

1. Execute an SQL Statement with bind parameter for a table in order to 2 or more its pages will be shown in Resultset
2. Scroll the table to the next fetched page in Resultset

Actual result:
"Bind Parameters" Window appears.

![I0sTNyfxfA](https://user-images.githubusercontent.com/51405061/75460571-a9f93400-5992-11ea-9896-1214a5e75efb.gif)

**Comment by serge-rider** [comment]
Fixed.
This problem happened with anonymous parameters only.

**Comment by kseniiaguzeeva** [comment]
verified
