### ISSUE TITLE
JSON editor not opening

### ISSUE THREAD

**Issue by Raidar** [dbeaver/dbeaver#8024]
#### System information: 
- Operating system (distribution) and version:
Microsoft Windows 10 Pro, Version 10.0.16299 Build 16299
- DBeaver version: Version 6.3.5.202002151353
- Additional extensions: no

#### Connection specification:
- Database name and version: PostgreSQL 11.1 x64
- Driver name: don't know
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:
Error after open editor to edit json column

The error looks like another issues:
https://github.com/dbeaver/dbeaver/issues/6738
https://github.com/dbeaver/dbeaver/issues/2880

#### Steps to reproduce, if exist:
see screenshots below:

![DBeaver_error_shot0](https://user-images.githubusercontent.com/1207873/75469782-a371b900-59a0-11ea-8b87-9e2c91c50435.jpg)
![DBeaver_error_shot1](https://user-images.githubusercontent.com/1207873/75469792-a5d41300-59a0-11ea-9caa-9527412a485b.jpg)
![DBeaver_error_shot2](https://user-images.githubusercontent.com/1207873/75469797-a66ca980-59a0-11ea-9c8e-1e7ac907766f.jpg)

**Comment by serge-rider** [comment]
I can't reproduce it. Perhaps something went wrong right before opening editor.
Please attach error/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by Raidar** [comment]
It's strange but I don't reproduce bug this day.
But I reproduce bug with clean inline editor for json field in select result window.
![DBeaver_empty_shot1](https://user-images.githubusercontent.com/1207873/76088610-5b1e5080-5fc9-11ea-88b0-2cb821581d61.jpg)
![DBeaver_empty_shot2](https://user-images.githubusercontent.com/1207873/76088614-5c4f7d80-5fc9-11ea-9f55-fff6d2f978d0.jpg)

**Comment by uslss** [comment]
cannot reproduce last mentioned issue
is it still actual against v7.0.0?

**Comment by Raidar** [comment]
No, thanks
