### ISSUE TITLE
Data format change does not apply to open data editors

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#8027]
#### System information: 
- MacOS 10.4.6
- Version 6.3.5.202002151353
- Additional extensions

#### Connection specification:
- MariaDB 10.3
- driver JDBC
- no proxies

#### Describe the problem you're observing:

when "data editor" grouping preference is changed and applied, current open data editors don't get updated. Data editors must be closed and re-opened to have changes applied.

#### Steps to reproduce, if exist:

go into "preferences" on data editor panel, check/uncheck grouping and apply. Gropuing will not change.

**Comment by uslss** [comment]
hi @rotorboy ,
unfortunately, cannot understand your issue. could you add screenshots that will make your issue more clear?
thanks in advance

**Comment by rotorboy** [comment]
Photos likely won't help but I will provide more detail to better explain the issue;

Query-produced Integer fields displayed in data editors, by default, appear as "grouped": e.g "1000" is displayed as "1,000". There is a checkbox option in preferences->data editor->data formats preference panel titled "Use Grouping" that toggles between displaying the comma or not. 

If a data editor is already displaying an integer, and the checkbox state is changed, even if the change is "applied", the CURRENT data editor integer display will NOT be changed to respect the new "use grouping" setting.  This means that if the editor is displaying "1,000", and the checkbox is cleared in the preference, the editor will CONTINUE to display "1,000". To effect the change, the editor must be closed and reopened, and then the effect will take place, and the integer will now be displayed as "1000".

I hope that provides enough detail...

**Comment by rotorboy** [comment]
> hi @rotorboy ,
> unfortunately, cannot understand your issue. could you add screenshots that will make your issue more clear?
> thanks in advance

Photos likely won't help but I will provide more detail to better explain the issue;

Query-produced Integer fields displayed in data editors, by default, appear as "grouped": e.g "1000" is displayed as "1,000". There is a checkbox option in preferences->data editor->data formats preference panel titled "Use Grouping" that toggles between displaying the comma or not.

If a data editor is already displaying an integer, and the checkbox state is changed, even if the change is "applied", the CURRENT data editor integer display will NOT be changed to respect the new "use grouping" setting. This means that if the editor is displaying "1,000", and the checkbox is cleared in the preference, the editor will CONTINUE to display "1,000". To effect the change, the editor must be closed and reopened, and then the effect will take place, and the integer will now be displayed as "1000".

I hope that provides enough detail...

**Comment by uslss** [comment]
thanks for clarifying and the bug report

**Comment by serge-rider** [comment]
Fixed in #8279

**Comment by uslss** [comment]
verified
