### ISSUE TITLE
Microsoft version 6.3.0

### ISSUE THREAD

**Issue by boan-jfm** [dbeaver/dbeaver#8029]
The version in Microsoft Store is DBeaver CE 6.3.0 from 2019-09-04.

Why is it called CE? And why is it not updated to match the releases manually downloaded which is currently 6.3.5?

Thanks

**Comment by serge-rider** [comment]
We update Miscrosoft Store only for major releases (once per 3 months). Mostly because it is a relatively long process with a lot of manual work.
Next major version is 7.0.

**Comment by serge-rider** [comment]
CE = Community Edition

**Comment by Silic0nS0ldier** [comment]
Appreciate listing this on the MS Store, takes the pain of manually updating away (even if in-app update notifications still appear).

Any thought put into automating more of the Microsoft Store release process?
