### ISSUE TITLE
Multiple result tabs: make last tab active by default instead of first one

### ISSUE THREAD

**Issue by btanner2** [dbeaver/dbeaver#8030]
Hi,

I often have to use multiple SQLs separated by a “;” in a single execution in PostgreSQL. It looks like this:

SQL1; 
SQL2; 
SQL3; 

The first SQLs make something useful, like creating temporary tables or calling functions. But there is no useful output generated by these calls. The most important SQL is always the last one, because it operates on the created temporary tables created before. DBeaver creates a single result tab for every SQL, which is good. Unfortunately always the FIRST one is active. This is really frustrating. Since the useful information are always in the LAST tab.

Possible solution 1:
Make last tab active by default. This should be more natural because it is the last executed SQL. This is even the default behavior from the pgAdmin client for PostgreSQL. 

Possible solution 2:
Create an additional option in preferences, which let the user decide by himself, which result tab should be active by default (first or last one).

Possible solution 3:
Make first pinned tab active by default. This solution is less comfortable than 1 or 2 but it would benefit users like me anyway in a great way. If I pin a result tab, it would be natural to let this tab active all the time. Right now DBeaver just ignore the pinning of the tab by choosing again the first result tab as the active one, if a new SQL is fired up.

Thanks

Kind regards
Brian

**Comment by btanner2** [comment]
THis is how it looks by default: 
![dbeaver_result_tabs](https://user-images.githubusercontent.com/36444364/75538585-1a4a9880-5a19-11ea-89ec-9c13ab512e84.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by E1izabeth** [comment]
Does this issue still actual for the latest DBeaver version?

**Comment by uslss** [comment]
It seems it is not actual for 23.1.0
