### ISSUE TITLE
[PostgreSQL] Autocompletion returns values of previous column

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#8034]
#### System information: 
- Windows 7 Pro x64
- DBeaver 6.3.5.202002151353
- No additional extensions

#### Connection specification:
- PostgreSQL 9.3
- PostgreSQL default driver (9.4.1212.jre7)
- No tunnels or proxies

#### Describe the problem you're observing:
Autocompletion returns values of previous column

#### Steps to reproduce, if exist:
execute query below, reconnect, stay after "id, " and press ctrl+space
```
drop table if exists supp.tmp_test1;

create table supp.tmp_test1(id int, oth_id int, name1 text);

insert into supp.tmp_test1(id, oth_id, name1)
select generate_series(1,10), generate_series(11,20), generate_series(21,30);

select id,  from supp.tmp_test1
```
![изображение](https://user-images.githubusercontent.com/22142845/75547550-2f84ee80-5a3c-11ea-9fd5-23ff5fc5d55c.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed.
Now value proposals are shown after WHERE/AND/OR/ON keywords only.

**Comment by uslss** [comment]
verified
