### ISSUE TITLE
Defining virtual keys: "Use all columns" btn doesn't work

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8035]
## System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 7.0.0

#### Describe the problem you're observing:
Defining virtual keys: "Use all columns" btn doesn't work

![ZtLpmVXm1k](https://user-images.githubusercontent.com/51405061/75548472-6eb43f00-5a3e-11ea-9659-54c3de601aa7.gif)

**Comment by kseniiaguzeeva** [comment]
Seems, it is not a bug as I described above, but is it expected result that the created virtual primary key by such way does not appear in Properties> Virtual tab?

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
