### ISSUE TITLE
[Data Search] Unable to perform "replace" function if the table pages have to be fetched

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8036]
Win 10
Dbeaver 7.0.0
PostgreSQL

[Data Search] Unable to perform "replace" function if the table pages have to be fetched

Steps:
1. Open a table which a repeatable sign in its content and where pages have to be fetched.
2. Press Ctrl+F
3. Enter the repeatable sign in Find field
4. Press Find btn
5. Enter another sign in Replace with field
6. Press Replace all btn7. 

Actual result:
1. The cells with the repeatable sign are not highlighted anymore
2. The table content doesn't apply the change.

![e4AjoJtyTE](https://user-images.githubusercontent.com/51405061/75551158-93abb080-5a44-11ea-8561-540cd4dd898d.gif)

**Comment by serge-rider** [comment]
Replace causes scrolling which causes data refresh.

It is not a bug by itself. However we shouldn't do auto-scroll on find/replace (this is a bug)

If option "Refresh data on next page reading" is on then we clear all present data on scrolling.

![image](https://user-images.githubusercontent.com/6398845/76650349-7d890e80-6573-11ea-8b8b-9d3d96a0a0a4.png)

We could try to keep existing changes by merging current changes in refreshed data set (matching rows by unique keys). We need a feature request for this.

**Comment by kseniiaguzeeva** [comment]
Unfortunately now only fetched data can be replaced. Steps:

1. Open a table which a repeatable sign in its content and where pages have to be fetched.
2. Press Ctrl+F
3. Enter the repeatable sign in Find field
4. Press Find btn
5. Enter another sign in Replace with field
6. Press Replace all btn.

Actual result:
The changes are applied among fetched data only.
![3bfXnGqkVX](https://user-images.githubusercontent.com/51405061/76764742-6b42e680-67a6-11ea-97e2-6c9dcc7b2d27.gif)

**Comment by serge-rider** [comment]
This is how it works. It finds/replaces only in fetched data. 
We won't change this behavior.

**Comment by kseniiaguzeeva** [comment]
Thank you for the explanation.
Verified.
