### ISSUE TITLE
"Save changes pop-up is shown endlessly if editor open for some value in table

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8037]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.0 EA

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
1. Open any table that contains JSON/JSONB column
2. Open value from JSON/JSONB column in editor
3. Try to refresh table - Save changes window appears
4. Choose Yes - window appears once again. It will appear until you choose No or Cancel
![2020-02-28_16h51_29](https://user-images.githubusercontent.com/31996417/75554107-bf319980-5a4a-11ea-9024-3f93ce342527.gif)

**Comment by serge-rider** [comment]
Can't reproduce.
Do I need to modify some column? In table or in the separate editor?

**Comment by uslss** [comment]
STR:
1. Open value from json/jsonb column in editor - "Save"/"Revert" buttons become active even if there were no changes made.
2. Try to refresh table (Editor is still open) - pop up appears - click Yes

**Comment by uslss** [comment]
issue is still reproducible in 7.0.2

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
