### ISSUE TITLE
[MySQL] Dropdowns in Trigger properties doesn't change anything

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8038]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.0 EA

#### Connection specification:
- Database name and version win 10 x64
- Driver name MySQL

#### Describe the problem you're observing:
There are two dropdowns in trigger's properties - Timing and Type. It seems that i could change these parameters in trigger by choosing values from dropdowns. But they didn't change anything as it could be seen in the attached gif.
![2020-02-28_17h19_31](https://user-images.githubusercontent.com/31996417/75556230-d96d7680-5a4e-11ea-84c6-48c2a277f0de.gif)

**Comment by serge-rider** [comment]
We do not support trigger properties change as all of them are in trigger definition text.
So I just disable these properties editor.

**Comment by uslss** [comment]
verified
