### ISSUE TITLE
Data transfer db->db: quoted identifiers handle bug

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8040]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.0 EA

#### Describe the problem you're observing:
Export task from a query to an existed table doesn't work.

#### Steps to reproduce, if exist:
1. Create export task from query (SELECT * FROM "Ks".newtable_3 (postgres) can be used) to Database
2. Select an existed table as target ("Ks".newtable_3exported (postgres) can be used)

Actual result:
1. Error appears.
2. The task cannot be executed.

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4267632/dbeaver-debug.log)
[.log](https://github.com/dbeaver/dbeaver/files/4267638/default.log)
![vJ5xSliRJY](https://user-images.githubusercontent.com/51405061/75559521-a62de600-5a54-11ea-927c-5edbc31f126b.gif)

**Comment by serge-rider** [comment]
I suppose the problem is in quoted column names (which clash with reserved keywords).

**Comment by serge-rider** [comment]
But I can't reproduce the bug with missing table.
@kseniiaguzeeva please provide steps to reproduce (for fresh dbeaver start)

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it anymore (DBeaver 7.0.0.202002291848) neither with quoted column names nor with column names without quotes.
