### ISSUE TITLE
Output tab isn't switched to Result tab if select query was executed 

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8042]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.0 EA

#### Steps to reproduce, if exist:
1. Open output tab in SQL editor
2. Execute some Select query - Result tab appears but focus is still on output tab. But focus is changed in case e.g. Execution plan was opened before
![2020-02-28_18h14_51](https://user-images.githubusercontent.com/31996417/75560658-a62ee580-5a56-11ea-931f-7683eb84c33c.gif)

**Comment by serge-rider** [comment]
It is not a bug.  Output tab behavior was changed in #7704
If you need to see data just switch to data tab.
