### ISSUE TITLE
NPE appears when trying to create task if task with the same name already exists

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8045]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.0.0 EA
#### Steps to reproduce, if exist:
1.  Start task creation: Database - Tasks - Create New Task - DB Export
2. Fill-in Name field with the name of already existing task
3. Click Next - [NPE](https://github.com/dbeaver/dbeaver/files/4270551/npe.txt)
 appears in log 
4. Change task to DB import - Click Next - Than click Back - another
[NPE](https://github.com/dbeaver/dbeaver/files/4270552/npe2.txt) appears
![2020-02-29_19h00_48](https://user-images.githubusercontent.com/31996417/75610837-0c366e00-5b26-11ea-8d8c-955c9f965247.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
