### ISSUE TITLE
Foreign Key fields can show and edit the dictionary value, not just the key id

### ISSUE THREAD

**Issue by msluser** [dbeaver/dbeaver#8046]
Often I copy and paste date from a spreadsheet that has a column that refers to another table, however the value in the cell is text, not a number or id.

Example

tbl_person
| id | name|
| ------------- | ------------- |
| 101 | John |
| 102| David |

tbl_pet
| id | name|owner|
| ------------- | ------------- | ------------- |
| 114 | Ren | John
| 115 | Stimpy | David

Before I paste this into DBeaver, I need to modify the data to be something like
tbl_pet
| id | name|owner|
| ------------- | ------------- | ------------- |
| 114 | Ren | 101
| 115 | Stimpy | 102

I would like the table cell to display the table's dictionary string rather than the ID.
Also, I would like to paste the dictionary string into the cell and have the editor determine the ID and write that id to the table when I persisting to the database.

The behavior would be similar to online spreadsheet/table applications like https://coda.io and https://airtable.com. But these applications lack the power of a SQL database.

Thank you,

-Mark

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
will be resolved in the scope of #10765
