### ISSUE TITLE
unable to see internal MySQL/MariaDB schema "mysql"

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#8047]
#### System information: 
- Operating system (distribution) and version: MacOS 10.14.6
- DBeaver version: 6.3.5.202002151353
- Additional extensions: JDBC

#### Connection specification:
- Database name and version: MariaDB 10.3 
- Driver name: JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:

MariaDB has several "internal" schema it uses for itself; "performance_schema" and "mysql". performance schema is visible in navigator panel "databases" folder element, but "mysql" is not.

I've looked in preferences for "view internal schema", as well as any connection-related settings, or driver related settings that would be responsible for it, but have found none.

**Comment by serge-rider** [comment]
Go to connection properties (f4), tab "General", turn on "Show system objects".

**Comment by rotorboy** [comment]
Thanks! That indeed enabled viewing them.

It would be nice to have that relationship highlighted on page 121, that describes the connection configuration panel, as I would not normally refer to those as “system objects” (which to me seems like something to with with DBeaver itself, NOT the DB), but rather “internal schema”.

Thanks again.

**Comment by rotorboy** [comment]
Seems like there is still an issue displaying "information_schema" database tables. The "tables" icon in the DB navigator has a '>' to the left indicating there are tables, but when I click on it, they are not displayed in the navigator. 

Additionally, going into "edit connection", and clicking on tables shows a blank grid, i.e. that there are no tables. 

The tables are clearly there, so not sure why they aren't displaying

**Comment by uslss** [comment]
@rotorboy , there are no Tables in Information_schema, only views. You could see them in Views folder
![image](https://user-images.githubusercontent.com/31996417/79771592-adc48980-8337-11ea-9421-b9e7c1cd7a4b.png)
