### ISSUE TITLE
Changing column order moves a table to the left

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8048]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.0

#### Describe the problem you're observing:
Changing column order moves a table to the left if the table pages are have to be fetched.

#### Steps to reproduce, if exist:
1. Open a table in Data Editor where horizontal scrolling is needed and pages have to be fetched.
2. Scroll the table view to the right and change a column order using column header.

Actual result:
the table view moves back to the left

Workaround:
Fetch all pages before order changing.
![ordermovestabletotheleft](https://user-images.githubusercontent.com/51405061/75619986-34f54c80-5b94-11ea-882c-bd6d26854bae.gif)

**Comment by maffe** [comment]
Scrolling to the left also occurs when the user scrolls down to the end of the fetched rows and DBeaver loads more rows.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
