### ISSUE TITLE
[Oracle] Schema's name looks like editable but couldn't be edited

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8049]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.0 EA
#### Connection specification:
- Database name and version Oracle 12c
#### Describe the problem you're observing:
Schema's name looks like it could be edited, user could change name value in field, but changes couldn't be saved. No error appears in log
![image](https://user-images.githubusercontent.com/31996417/75624089-08582980-5bc2-11ea-9c75-a4adca41336f.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
