### ISSUE TITLE
Foreign Key

### ISSUE THREAD

**Issue by boukenka** [dbeaver/dbeaver#8051]
Hello,

Today it is possible to generate ER diagrams. And that's great. 😄 
Could you please plan to have a dedicated icon / indication in the future 
to see the Foreign Key when the ER has been generated.
It would be a big '_plus_' from my point of view.

Thanks.

**Comment by kseniiaguzeeva** [comment]
Hello,
Foreign keys are already displayed as "connections" (lines) between tables.
Or do you want to see which column  FK belongs to (for example as Primary key is displayed now (context menu>Show attributes))?  

![dbeaver_Ojvf6I3i3A](https://user-images.githubusercontent.com/51405061/75661631-bc1eef00-5c7e-11ea-875e-374464a50eb6.png)

**Comment by boukenka** [comment]
Yes. Exactly. Something like that (or any other type of indication):

![Example](https://user-images.githubusercontent.com/16502423/75673473-4a956f80-5c83-11ea-86b0-b8e5654ba8f2.png)

**Comment by kseniiaguzeeva** [comment]
We have the similar feature. Please click on connection (line) between tables and you will see which columns are connected.

![image](https://user-images.githubusercontent.com/51405061/75681437-a1f80780-5ca4-11ea-95d9-13246ee4f381.png)

**Comment by boukenka** [comment]
Thank you for this information. I didn't know that feature.
But it would be even better to see the FK information without using this feature.
So that a clear overview is displayed for all the database schema, including this one. 😄

**Comment by boukenka** [comment]
For example something like that. What do you think ?
![new](https://user-images.githubusercontent.com/16502423/75753206-951df700-5d2a-11ea-8600-cc479697aa53.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by boukenka** [comment]
@kseniiaguzeeva Hello. Is there an update? Is there any hope that this feature will ever be implemented?

**Comment by uslss** [comment]
#7257

**Comment by boukenka** [comment]
@kseniiaguzeeva Hello. Could you provide an update on this request please?

**Comment by boukenka** [comment]
@uslss Hello. Could you provide an update on this request please?

**Comment by Destrolaric** [comment]
@boukenka, Hi, new routing was added what uses attributes for paths, write me, if it solves your issue.  It can be enabled via ERD preferences -> Routing type

**Comment by boukenka** [comment]
@Destrolaric Hello. Thank you for your message. Is the correct configuration ?

![image](https://user-images.githubusercontent.com/16502423/170982853-5dc84b20-7bf8-4362-a252-fc88b427cfb9.png)

When selecting this option, there are issues when I try to change the lines positions of the connectors.
Also I see nowhere the '**FK**' indication (like [here](https://user-images.githubusercontent.com/16502423/75753326-d1e9ee00-5d2a-11ea-9bbe-ded0e330716f.png))

![image](https://user-images.githubusercontent.com/16502423/170984139-790099af-767b-4c50-a9f5-d074d9a84c73.png)

PS : I am using DBEAVER 22.0.5.

**Comment by Destrolaric** [comment]
@boukenka Ah, this is a known bug, in https://github.com/dbeaver/dbeaver/issues/16493 it will be fixed. Foreign key status can be seen from association itself, black square means that this is foreign key association.

**Comment by boukenka** [comment]
@Destrolaric The black square is a good point to show the foreign key association.

**Comment by boukenka** [comment]
@Destrolaric Thank you for the implementation. Closing the issue because it has been solved.
