### ISSUE TITLE
SQL editor border color does not properly set with connection type

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#8052]
#### System information: 
- Operating system (distribution): MacOS 10.14.6
- DBeaver version: 6.3.5
- Additional extensions: 

#### Connection specification:
- Database name and version: MariaDB 10.3
- Driver name: JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes. SSH

#### Describe the problem you're observing:

When a new SQL editor is created for a color-coded connection type, the sql editor borders do not get set with the connection type color. see enclosed photo

#### Steps to reproduce, if exist:

open a SQL editor with a connection type color set.

<img width="1383" alt="Screenshot at Mar 01 22-57-47" src="https://user-images.githubusercontent.com/34849704/75644627-e639c800-5c10-11ea-9459-cdf67eda50cf.png">

**Comment by uslss** [comment]
hi @rotorboy ,
unfortunately, cannot reproduce an issue. Is it still actual against the recent version?

**Comment by rotorboy** [comment]
Yes still occurring in current release. The upper panel does not have the color of the profile for that connection. 

-Avi

**Comment by rotorboy** [comment]
Also, screen shot

You can see sql editor frame is still grey, while resultset frame is proper color..

**Comment by kseniiaguzeeva** [comment]
Can be fixed together with https://github.com/dbeaver/dbeaver/issues/10724

**Comment by LonwoLonwo** [comment]
Duplicate of https://github.com/dbeaver/dbeaver/issues/15971
