### ISSUE TITLE
 PG: schema permissions

### ISSUE THREAD

**Issue by mxwmwx** [dbeaver/dbeaver#8053]
The UI from role and user:
![image](https://user-images.githubusercontent.com/37258498/75654969-d87d5480-5c9b-11ea-94fc-6417bc66aedb.png)
we can see the root has the privileges(drop/create/usage)
but the UI from schema:
![image](https://user-images.githubusercontent.com/37258498/75655176-475aad80-5c9c-11ea-81ba-60157393577d.png)
I think it should be the seem.

the privileges of the table is the same。As is shown from the pictures:
![image](https://user-images.githubusercontent.com/37258498/75655309-87219500-5c9c-11ea-8943-11af94932f28.png)
![image](https://user-images.githubusercontent.com/37258498/75655343-9a346500-5c9c-11ea-96ca-f4fbb913aace.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
Can't reproduce in DBeaver 7.2.5
Information about schema permissions in tab "Permission" in Roles is the same as information about current schema permissions in tab "Permissions" in schema info.

**Comment by LonwoLonwo** [comment]
@mxwmwx If problem is still actual for you in new DBeaver versions - you are free to reopen this ticket.
