### ISSUE TITLE
MSSQL/Windows Auth - missing mssql-jdbc_auth-8.2.0.jar

### ISSUE THREAD

**Issue by ddugovic** [dbeaver/dbeaver#8054]
#### System information
* Windows 7, Java 8
* Version 7.0.0.202002292132

#### Connection specification
* MS SQL Server 2019(?)
* Windows authentication

#### Question
How do I find and install mssql-jdbc_auth-8.2.0.jar which seems to be required for Windows authentication?
![image](https://user-images.githubusercontent.com/1834123/75673833-772c9580-5c49-11ea-9f51-2c21a1a7d1f8.png)

**Comment by WilliamNoad** [comment]
Seeing the same issue myself.

The MS SQL auth DLL changed its name between 7.4.1 and 8.2.x.

As a workaround, manually download the appropriate version of the DLL from https://github.com/microsoft/mssql-jdbc/releases and copy the file `mssql-jdbc_auth-8.2.0.x64.dll` into the directory that contains the DBeaver.exe file.

Note that you must use correct DLL with the name matching the JDBC version you're using.

**Comment by serge-rider** [comment]
It is a bug in recent SQL Server driver integrated authentication.
Since 8.x native DDL has changed and its version now must correspond to the driver version.
We will update default sqljdbc_auth.dll reference in the driver configuration.

Workarounds:
- downgrade driver to 7.x version (you can do it in Driver Editor dialog).
- download dll library manually 

@WilliamNoad you can add `mssql-jdbc_auth-8.2.0.x64.dll` to the driver configuration on Libraries tab (it is safer and easier than copying it to program files).

**Comment by serge-rider** [comment]
I've made a hotfix of 7.0.0 version toady (revert to 7.4.1 driver version).

We'll add native artifact (https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc_auth) in 7.0.1.

**Comment by uslss** [comment]
verified

**Comment by ceinmart** [comment]
Hi, 
My SQL SERVERs connection became with this issue, but they are set with version 7.4.2.
I tried back to 6.1 and the problem still occurring when is set to "Windows Authentication" . 

```
This driver is not configured for integrated authentication. ClientConnectionId:195be2ca-de18-43fe-9af3-92bfc390294d
  no sqljdbc_auth in java.library.path

```

Any tips about how to work around this?

**Comment by coopr** [comment]
I had the same issue at @ceinmart with DBeaver 7.1.0 (I encountered the "This driver is not configured for integrated authentication" error when attempting to connect to SQL Server with Windows Authentication)
 
I'm not sure where I found this tip, but I was advised to ensure that the version numbers here roughly match (like as shown) - when you change the version number, I think you need to then download the drivers (possibly with the Force overwrite flag on)

![FXIOC-PROD-PER-VDI](https://user-images.githubusercontent.com/94904/85170823-cca1a800-b222-11ea-9edf-158c2f7dfd22.jpg)

**Comment by Yahatix** [comment]
If i'm on linux i don't think that the dll is very helpfull. Shouldn't there be a jar version somewhere?
![Screenshot from 2020-06-30 09-07-51](https://user-images.githubusercontent.com/21371842/86094754-3dfa1a00-bab1-11ea-8ae2-be7c92903fd4.png)

**Comment by p91paul** [comment]
I believe Microsoft driver does not support windows auth on Linux. You can use jtds driver, which is however limited in other ways.

**Comment by MatchPoint** [comment]
> I believe Microsoft driver does not support windows auth on Linux. You can use jtds driver, which is however limited in other ways.

ODBC driver on linux supports windows auth. JDBC leverages ODBC so it should be possible. Example of configuring ODBC connection on linux for windows auth: https://stackoverflow.com/questions/59965444/is-it-possible-to-connect-to-mssql-with-windows-auth-mode-from-a-nodejs-app-runn
