### ISSUE TITLE
Create user SQL out of order

### ISSUE THREAD

**Issue by harryshepard** [dbeaver/dbeaver#8055]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
7.0
- Additional extensions
None

#### Connection specification:
- Database name and version
MariaDB

#### Describe the problem you're observing:
When you create a user and assign schema privileges the SQL is in the wrong order and can't run. It doesn't put the create user SQL first, then tries to run commands against a user that doesn't exist.

It either needs to run the create as the first line, or block the schema privileges tab until the user exists. I would prefer the first option

#### Steps to reproduce, if exist:
Create a user, set some schema privileges, save user

**Comment by uslss** [comment]
hi @harryshepard ,
unfortunately, cannot reproduce an issue. Works ok for me.
![image](https://user-images.githubusercontent.com/31996417/75774528-3de74900-5d61-11ea-8df5-99bfa502a49e.png)
Probably you could provide some additional info that will help to reproduce an issue?

**Comment by harryshepard** [comment]
Yes it's working correctly for me now so it's obviously going to have some obscure steps to reproduce the behaviour.

I had another issue while trying to reproduce. If you do a new user then click % from the schema column then % from the tables column, then check all, uncheck all, then select a specific schema, % in tables and check all, it's applying to all schemas for some reason. This continues after restarting dbeaver so you should be able to reproduce this one consistently

**Comment by uslss** [comment]
ticket closed.
related issue #8250
