### ISSUE TITLE
DBeaver FR: Add setting to not include HTML table header when using Open With Web  (2nd try)

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#8058]
DBeaver - **Version 7.0.0 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

This is a second try with this feature request, since my first try with #7845 got closed and indicating that it was completed for version **7.0.0**. I can not see any change in its behaviour and can not find any system setting either.

**From issue #7845**:

It would help me if there where som system setting checkbox where I could set/clear if I want the HTML page shown when using the context menu **Open With** -> **Web browser** should include a table header or not.

Some time after *DBeaver* version **6.0.0 CE** the rendered HTML page was changed so that it now include a table header stating either the table name or the SQL query executed, this followed with a grid for the selected data grid columns.

I sometimes send the HTML document to customer when requested to generate some special report. Now I have to edit the HTML document to remove the table header.

**Comment by uslss** [comment]
hi @pdanie ,
btw, feature was implemented for HTML Export
![image](https://user-images.githubusercontent.com/31996417/75775330-d3370d00-5d62-11ea-9a5d-02167dfa80f3.png)

**Comment by pdanie** [comment]
That is great. But would be even more nice if there where some setting for the **Open with** -> **Web browser** too.

**Comment by serge-rider** [comment]
Done.
Now Open With will use default export settings for particular format.
You need to export as HTML once and then Open in browser will use the same configuration.

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by pdanie** [comment]
Now when I tested it I notice that when I remove the check box for **Output table header** I loose the header with column header (the column name) too.

I wanted only that the **table name** header shoudl be removed (and the column man kept).

Any more thoughts on this?

**Comment by kseniiaguzeeva** [comment]
Thank you for the creating a new ticket for this.
