### ISSUE TITLE
PostgreSQL: Show DB Collate & CType without F5

### ISSUE THREAD

**Issue by KuznetsovaNV** [dbeaver/dbeaver#8061]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro Version 1803 OS build 17134.590
- DBeaver version: 7.0.0
- Additional extensions: no

#### Connection specification:
- Database name and version: PostgreSQL 11.2
- Driver name: PostgreSQL JDBC Driver
- Do not use tunnels or proxies (SSH, SOCKS, etc). 

#### Describe the problem you're observing:
View Database(F4) do not show Collate and Ctype without F5. These properties are empty.

#### Steps to reproduce, if exist:
Right-click on existing DB => View Database. "Collate" and "Ctype" properties are empty.
I managed to see these properties with refreshing connection (right-click on existing connection or DB-name). Would be nice to show these properties on the first calling without F5. Thank you.

#### Include any warning/errors/backtraces from the logs
Error log is empty.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
