### ISSUE TITLE
Switching into Manual Commit after "Copy to CSV"

### ISSUE THREAD

**Issue by spooder87** [dbeaver/dbeaver#8064]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by kseniiaguzeeva** [comment]
Unfortunately cannot reproduce. 
Please tell your DB and OS. 
Did you use Auto-commit or Smart auto-commit in this issue?

**Comment by spooder87** [comment]
Postgress; Windows 10
It's switching from Auto-Commit to Manual Commit after clicking on "copy to csv"

**Comment by kseniiaguzeeva** [comment]
I can see it on a table when copy process is running. As soon as copy is finished, commit goes back to Auto-Commit.
Do you have some sort of "select" query?

**Comment by kseniiaguzeeva** [comment]
Please also tell your DBeaver version?

**Comment by spooder87** [comment]
version 6.3.5 and also on the new version 7.0
The  query contains select, and after it finished it doesn’t switch back

**Comment by spooder87** [comment]
currently using version 7

**Comment by uslss** [comment]
seems that issue is solved
