### ISSUE TITLE
unexpected quotes added for field called 'interval'

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#8065]
#### Describe the problem you're observing:

when you typing `prd.interval` quoted are added

#### Steps to reproduce, if exist:

Try to write:

			date_trunc( 'MONTH', docdate -prd.INTERVAL ),

Actual:

			date_trunc( 'MONTH', docdate -prd."INTERVAL" ),

**Comment by uslss** [comment]
hi @KES777 ,
what database do you use?

**Comment by KES777** [comment]
Postgres

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
@KES777 ,
cannot reproduce an issue. Is it quoted in case you use autocompletion or always?
Do you have column named interval? Probably, you could post example of query?
Thanks in advance

**Comment by uslss** [comment]
there is no update on issue. 
if it is still reproducible for you - feel free to reopen the ticket
