### ISSUE TITLE
DDL feature from table's 'Properties' tab does not contain square brackets in MSSQL and misses trailing spaces in field names

### ISSUE THREAD

**Issue by whobscr** [dbeaver/dbeaver#8066]
#### System information: 
- "Ubuntu 19.04"
- DBeaver Version 7.0.0.202003021717

#### Connection specification:
- Microsoft SQL Server 2016 of any version
- Driver SQL Server 7.4.1.jre8

#### Describe the problem you're observing:
DDL feature from the table's 'Properties' tab does not contain square brackets in MSSQL and misses trailing spaces in field names.
My table contains trailing spaces in all fields which I wanted to indicate and remove, but I tried to select from this table and the click with the right mouse button and select 'Copy field name' option and it copied my field names without those trailing spaces. Then I tried to find the spaces in DDL tab but it just gave me the DDL with field names without square brackets which means that it truncated all spaces in the end of field names. Here's the similar example of the DDL from Microsoft Management Studio and from DBeaver:

CREATE TABLE MsMS_DDL_Example(
	[id ] [int] NOT NULL,
	[name ] [string] NULL
)

CREATE TABLE DBeaver_DDL_Example (
	id int IDENTITY(1,1) NOT NULL,
	name string NULL
)

#### Steps to reproduce, if exist:
Create any table with fields containing spaces in the end. It will then be displayed in the DDL feature of the 'Properties' tab without square brackets and thus will cut the spaces in the end.

**Comment by serge-rider** [comment]
I can't reproduce this. DBeaver always quotes identifiers which contain any special chgaracters.
![image](https://user-images.githubusercontent.com/6398845/75788654-9b878f80-5d79-11ea-94a1-4d669418ff77.png)

Do you use pre-configured SQL Server driver?
Is this space character a real space (ascii code 32) or it is some special unicode character?

**Comment by whobscr** [comment]
> I can't reproduce this. DBeaver always quotes identifiers which contain any special chgaracters.

Sorry, I just found out that I didn't use the latest version when I was checking the table DDL. And when I updated I checked the different table without spaces at the end of fields.
I think that this is fixed in the latest version. I'm closing this issue, thanks!
