### ISSUE TITLE
Wildcard object privileges not listing for MySQL 

### ISSUE THREAD

**Issue by nokiomanz** [dbeaver/dbeaver#8068]
Hi, 

It is said to be fixed in version 7.0.0 as per issue #7784.

Here is a screenshot under 6.1.0
![image](https://user-images.githubusercontent.com/17622903/75794512-e6d07c80-5d3e-11ea-9b25-8cbc300fa238.png)

Here is the same screenshot under 7.0.0
![image](https://user-images.githubusercontent.com/17622903/75794540-ed5ef400-5d3e-11ea-8c51-3978f4b5e80f.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
This issue was caused by #6275 fix (we had a wrong condition for catalog-based privileges)

**Comment by uslss** [comment]
verified
