### ISSUE TITLE
[PgSQL] Copy and paste (integer) array

### ISSUE THREAD

**Issue by Vlczech** [dbeaver/dbeaver#8071]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.0
- Additional extensions: -

#### Connection specification:
- Database name and version: PostgreSQL 11
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When I have int array (type _int4) and copy (inline in table data) from one row to another row, in the row where it is pasted, there are additional brackets, specifically `{`as a prefix and `}`as a suffix (see attachment bellow).

#### Steps to reproduce, if exist:
CREATE TABLE test (
	x _int4 NOT NULL,
);

INSERT INTO test(x) VALUES ({1,2});

...then manually from table data editor copy this value and paste into new row...

#### Include any warning/errors/backtraces from the logs
![obrazek](https://user-images.githubusercontent.com/10884140/75812810-2b840400-5d8f-11ea-9de1-ba94a5127395.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
