### ISSUE TITLE
DBeaver FR: Be able to add previous stored SQL scripts in Menu/Database Navigator

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#8072]
DBeaver - **Version 7.0.0 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Today we have created a bunch of **SQL Editor Templates** to help collegues to do repetitive work and some system administrator work. Something like get size of all database tables, set database in single/multi user etc.

But only a few collegues remember/understand how to start an **SQL Editor** and to choose to import **SQL Templates**.

One way to make it easier can be to extend the way **SQL Editor Templates** work. Add a menu/short name for the templates and then be able to hook them into a separate new **Main menu** node or to add them to the **Database Navigator** database **Administration** node. When a template was choosen there would be no need to have an **SQL Editor** open, the SQL script was just executed.

Would be nice if the **colon paramers** like ":MyParameter" and **inserted variables** like "${table}" was parsed when a template was executed. 

**PS**. The SQL script should be run as **Execute Script** not **Execute Statement**. This so that *SQL Server* "**GO**" command could be included.

Hope the idea does not sound too far fetched.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
seems to be similar to #5291
