### ISSUE TITLE
DBeaver: Seems that MSSQL driver is still version 7.2.1 not 8.2 in DBeaver 7.0.0

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#8073]
DBeaver - **Version 7.0.0 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

Maybe I'm missing something, but to me it looks like the Microsoft MSSQL driver included/downloaded for my newly installed *DBeaver* 7.0.0 is still the old version 7.2.1.

**Comment by uslss** [comment]
hi @pdanie ,
it was downgraded due to issues with Win authentication (#8054).

**Comment by pdanie** [comment]
Ok. I was just wondering since the update was mentioned in the 7.0.0 release documentation (whats new on the webpage).

**Comment by serge-rider** [comment]
@pdanie It was. We made a hotfix for CE (just reverted to version 7). 
We will upgrade to version 8 again in version 7.0.1. New binary Maven artifact was added. We need to test it before release.

**Comment by jeremyhdr** [comment]
HEllo

did it works with the driver 7.4.1? 
kind regards
