### ISSUE TITLE
Unable to change display column width? 

### ISSUE THREAD

**Issue by mickeyjf** [dbeaver/dbeaver#8075]
I have DBeaver on2 different machines. Each PC has the same version of Debian, a copy of the identical postgres DB, and the same version of DBeaver (7.0.0).

On one of these I am able to grab the vertical bar between column headings on the display, and slide it to change the width of the displayed column.

On the other (my primary machine) I am not able to, and some columns are not wide enough to display the complete data. On moving over the vertical bar the cursor changes to right-left arrows, but moving it does not effect the column width. 

I started using DBeaver several versions ago, and have never been able to adjust the column widths on this machine.

I imagine this is some simple setting, but I have no idea where it would be. What am I missing?

**Comment by uslss** [comment]
unfortunately cannot reproduce an issue, is it still actual?

**Comment by uslss** [comment]
there is no update on ticket for a long time. if it is still actual for you, feel free to reopen the ticket
