### ISSUE TITLE
Snowflake + schema compare

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#8076]
We need to add Snowflake Liquibase extension in order to compare Snowflake schemas.
https://forum.liquibase.org/topic/how-to-use-snowflake-extension

**Comment by serge-rider** [comment]
Unfortunately event with Snowflake extension it doesn't work.
https://forum.liquibase.org/topic/snowflake-documenttaion-error

**Comment by LonwoLonwo** [comment]
But we have it now! We can compare Snowflake schemas in DBeaver EE version.
