### ISSUE TITLE
DBeaver versions greater than 6.3.0 onwards Postgres Search Path not getting set

### ISSUE THREAD

**Issue by VadiHub** [dbeaver/dbeaver#8078]
Hi

I found that in DBeaver versions greater than 6.3.0, the search path is not getting set
properly for postgres connections.

For example, if the Login Role name and schema name are same, the schema name was being 
added to the search path automatically up to version 6.3.0. So we could query a table
without prefixing the schema name.

In new versions of Dbeaver, we have to provide the schema name in the query or else the data is not fetched.

Regards
Vadi

**Comment by serge-rider** [comment]
I can't reproduce this bug.
DBeaver sets search_path and in most cases it works ok.
Please provide more information. Steps to reproduce would be very helpful.

Also you can open Query Manager view to see what queries dbeaver executes internally in order to switch active schema.

**Comment by VadiHub** [comment]
Hi Serge

Thanks for the reply.

Please check the attached files.

Regards
Vadi

[DBeaver_Issue.zip](https://github.com/dbeaver/dbeaver/files/4298286/DBeaver_Issue.zip)

**Comment by Vlczech** [comment]
@VadiHub: It seems, that it works for me (DBeaver 7.0 / Windows 10 x64 / PostgreSQL 11.7)
![obrazek](https://user-images.githubusercontent.com/10884140/76359458-8c758400-631b-11ea-92b3-cbafdb92d76b.png)

**Comment by Vlczech** [comment]
@serge-rider: ...another thing is that search paths in DBeaver and in `psql` are in different, specifically reverse, order: 
![obrazek](https://user-images.githubusercontent.com/10884140/76360811-060e7180-631e-11ea-8ec6-558527993f84.png)

**Comment by serge-rider** [comment]
@Vlczech dbeaver executes `SELECT current_schema()` to get active schema.

`current_schema returns the name of the schema that is first in the search path (or a null value if the search path is empty). This is the schema that will be used for any tables or other named objects that are created without specifying a target schema.`

After getting current schema dbeaver makes it the fist one in search path (if it is not the first already). This is made for UI consistence (as we show current schema in the main toolbar).

What current_schema returns in your case?
