### ISSUE TITLE
Database compare returns wrong DDL

### ISSUE THREAD

**Issue by Speirs47** [dbeaver/dbeaver#8080]
System information: 
- openSUSE Leap 15.1
- DBeaver version 6.3.0 EE
- Additional extensions - none
- Database - MariaDB

So I made a change in one table - I added two TINYINT(1) columns. I wanted to check if DBeaver compares schemas correctly and as it turned out it doesn't. Here's the result DDL from comparing two exactly the same databases  (except those new columns):

> ALTER TABLE `robocze`.`kartoteki` ADD `wydrukowane` TINYINT(3) DEFAULT 0 NOT NULL;
>
> ALTER TABLE `robocze`.`kartoteki` ADD `do_druku` TINYINT(3) DEFAULT 0 NOT NULL;

As you can see it results in migrating TINYINT(1) column to TINYINT(3) column. No idea why.

And here's a screenshot from other application I use to compare schemas (after I compared and migrated it using DBeaver):
![image](https://user-images.githubusercontent.com/40421338/75865592-12696a80-5e04-11ea-919b-aec023f6f849.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
We need to upgrade Liquibase library for better MariaDB support.

**Comment by serge-rider** [comment]
We need to upgrade to Liquibase 4. There is a large number of API changes. We don't have time to adopt them in 7.2.

**Comment by LonwoLonwo** [comment]
We have updated Liquibase version to 4.2, but unfortunately this did not solve the problem.

This is partly a problem of the MariaDB driver, which always returns 3 as column size for columns TINYINT type. And now this is partially a problem of Liquibase, which does not return parameters for TINYINT for MariaDB.

Now comparison with similar columns looks something like this:
![2021-02-17 11_49_08-Schema Compare](https://user-images.githubusercontent.com/45152336/108185863-ce0ed180-711d-11eb-9bc9-e07c74ea76c2.png)

**Comment by LonwoLonwo** [comment]
https://github.com/liquibase/liquibase/issues/2037
