### ISSUE TITLE
Connection type background color only updates when changing focus

### ISSUE THREAD

**Issue by dr-1** [dbeaver/dbeaver#8081]
#### System information: 
- Windows 10 1909
- DBeaver Community Edition 7.0.0
- No extensions

#### Connection specification:
- SQL Server 2017
- Microsoft JDBC Driver for SQL Server (MSSQL)
- No tunnels or proxies

#### Describe the problem you're observing:
When either
1) opening a new SQL editor with a specific data source type, or
2) changing the data source type of an existing SQL editor,

the corresponding Results panel initially does not get the background color that is set for that data source type. It retains the color associated with the previous connection type, or in the case of a new SQL editor the color remains unset. The right background color only appears when moving focus to a different panel.

**Comment by uslss** [comment]
hi @dr-1 ,
unfortunately, cannot reproduce an issue. Probably you could add a video that will help to reproduce an issue?
Thanks in advance

**Comment by dr-1** [comment]
![capture](https://user-images.githubusercontent.com/24420610/76068653-70738a80-5f89-11ea-8811-24d3e2fda410.gif)

**Comment by uslss** [comment]
seems that issue appears only if dark theme is enabled.
thanks for the bug report

**Comment by serge-rider** [comment]
Seems to be one of dark theme glitches..

**Comment by uslss** [comment]
still reproducible against 21.0.3

**Comment by wiwwo** [comment]
Also, changing from a DB that has colors to one that does not have (Say, PROD to Development) does not "restore" the color to "blank"

**Comment by E1izabeth** [comment]
Does this issue still reproducible on the latest DBeaver version 23.0.0?

**Comment by dr-1** [comment]
Yes, I observe the same issue in version 23.0.0.

**Comment by dr-1** [comment]
This appears to be solved in version 23.2.3 and possibly earlier. Background color changes immediately when I change the data source type of an open SQL editor.

**Comment by E1izabeth** [comment]
Thank you for update
