### ISSUE TITLE
Save active database/schema for SQL editor not working

### ISSUE THREAD

**Issue by mikkk3l** [dbeaver/dbeaver#8084]
#### System information: 
- Operating system (distribution) and version: Windows 10.0.17134
- DBeaver version: 7.0.0
- Additional extensions

#### Connection specification:
- Database name and version: both PRO and DEV envs: IBM DB2 DSN12015
- Driver name: db2jcc.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Default schema does not get saved in DB2 PRO environment. Surprisingly, in DB2 DEV environment it works.
![dbeaver_default_scheam_issue](https://user-images.githubusercontent.com/15341836/75875352-d3dbac00-5e13-11ea-8408-ef1cab62a233.gif)

**Comment by mikkk3l** [comment]
[dbeaver_not_saving_default_schema.zip](https://github.com/dbeaver/dbeaver/files/4287029/dbeaver_not_saving_default_schema.zip)

**Comment by kseniiaguzeeva** [comment]
Do you select Default schema in connection settings or in DB Navigator tree?

**Comment by mikkk3l** [comment]
I was only doing in navigation tree.
If I configure connection / initialization it works
![imagen](https://user-images.githubusercontent.com/15341836/75974838-bec85100-5ed7-11ea-95be-b0b84b9f8c71.png)

Thanks!
