### ISSUE TITLE
Generate SQL -> JOIN : Selectable on foreign keys

### ISSUE THREAD

**Issue by Soft-View** [dbeaver/dbeaver#8088]
Could you please create a feature:  Generate SQL: JOIN based on selectable foreign keys.

Menu-->Database Navigator--> Connection--> Schema--> Table--> ER Diagram: (Generate SQL/JOIN) : SQL Statement should be based on selectable foreign keys.

This feature will require some UI improvements.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
Implemented in [Visual Query Builder](https://github.com/dbeaver/dbeaver/wiki/Visual-Query-Builder) in EE version
