### ISSUE TITLE
Oracle Spatial data is shown as oracle.sql.struct

### ISSUE THREAD

**Issue by Kermit** [dbeaver/dbeaver#8093]
**System information:**
Windows 10 Pro 1909 x64

**DBeaver version:**
 7.0.0 CE installed from Microsoft Store

**Connection specification:**
Connect to Oracle 11g with 12.1.0.2 OJDBC7 driver

Describe the problem you're observing:
Spatial data is shown as "oracle.sql.STRUCT@6aa060f6".
It was ok in previous version. Now it's broken. It's same bug as #6315

**Comment by serge-rider** [comment]
Can't reproduce (I see geometry data type structure with separate fields like coordinates).
Could you post some sample query? 

Note: I use ojdbc8 driver.

**Comment by Kermit** [comment]
I used simple SELECT query like:
`SELECT GEOM_COLUMN FROM TEST_TABLE;`
And result is:
![image](https://user-images.githubusercontent.com/62873/75966519-c7665a80-5eca-11ea-96e7-261b0c135270.png)

BUT if it works different on new tables.
I created new table with data from TEST_TABLE:
`CREATE TABLE NEW_TEST AS (SELECT * FROM TEST_TABLE);`
and after simple SELECT query result is:
![image](https://user-images.githubusercontent.com/62873/75966766-24faa700-5ecb-11ea-9baa-fa2c7c01cab2.png)

**Comment by Kermit** [comment]
Ok, it works now.
It was my fault - I filtered out all schemas except one. DBeaver couldn't get information from MDSYS schema:
`Data type 'MDSYS.SDO_GEOMETRY' isn't resolved as structured type. Use synthetic attributes.`
`Error evaluating expression 'object.system' on node 'Schemas': 1:7 unsolvable property 'system'`

And it was in debug.log file. I was reading old debug.log file from standalone version (not from Microsoft Store). 

I'm sorry for wasting your time.
Best regards.

**Comment by bwoostdam** [comment]
Hello, I am heving the same problem when exporting SDO_Geometrie data. Teh data is written as oracle.sql.STRUCT@xxxxxxxx  instead of coordinates.  I do not understand the solution you are reffering to. Could you please elaborate on it ?  I am hoping this will work for me as well.  Thank you.

**Comment by rbroth** [comment]
It's a few years too late, but in case this helps anyone else:

You may have set up a filter for the list of schemas in the Database Navigator. If that filter also filters out the the schema `MDSYS`, DBeaver won't show the proper geometry data. 

Make sure that you can see the schema `MDSYS` in your list of schemas in the Database Navigator window, and it should work.
