### ISSUE TITLE
Rollback on Error doesn't work

### ISSUE THREAD

**Issue by michalk-k** [dbeaver/dbeaver#8094]
_Rollback on Error_ option doesn't work in Postgresql, regardless running a script  or statement (set of statements)

To reproduce the error run the simple script using either "Execute SQL Statement" or "Execute SQL Script"

```
BEGIN;
SELECT a a;
```
It raises the error:
`SQL Error [42703]: ERROR: column "a" does not exist`

Now run any simple query let's say
`SELECT 1`

It ends up with
`SQL Error [25P02]: ERROR: current transaction is aborted, commands ignored until end of transaction block`

In case of running script it has additional impact. Running script offers "retry" option. Which obviously is useless because of error above.

**Comment by serge-rider** [comment]
I can't reproduce it.
What dbeaver version do you have?

Are you in the smart-commit mode?

**Comment by michalk-k** [comment]
Using 7.0.0.202003021717

It behaves the same regardless smart-commit mode.

**Comment by uslss** [comment]
still cannot reproduce an issue. could you post a video?
thanks in advance

**Comment by uslss** [comment]
ticket closed. if it is still actual for you - feel free to reopen the ticket
