### ISSUE TITLE
[Bug][Oracle] PL/SQL Create or replace Package can't be executed with Alt+X

### ISSUE THREAD

**Issue by borisbrodski** [dbeaver/dbeaver#8095]
#### System information: 
- Operating system: Windows 10 x64
- DBeaver 7.0.0
- No additional extensions

#### Connection specification:
- Database: Oracle 12
- Driver name: oracle-jdbc-12.1.0.2 (ojdbc7.jar)
- No tunnels or proxies.

#### Describe the problem you're observing:

Pressing Alt+X to execute following SQL-script results in an error.
PL/SQL DBeaver parser can't find the begin and the end of the statements correctly.

Selecting and executing (Ctrl+Enter) both CREATE-statements manually works fine.

#### Steps to reproduce, if exist:

```sql
CREATE OR REPLACE PACKAGE MIG2 AUTHID CURRENT_USER AS
    PROCEDURE LOG(SEVERITY VARCHAR2, MSG CLOB);
END;


CREATE OR REPLACE PACKAGE BODY TEST_PACKAGE AS
    TYPE TABLE_OF_NUMBERS_TYPE IS TABLE OF NUMBER;

    PROCEDURE LOG(SEVERITY VARCHAR2, MSG CLOB) IS
    BEGIN
        NULL;
    END;

END;
```

#### Include any warning/errors/backtraces from the logs

The error message ("Execution error")

```
Error occurred during SQL script execution

Reason:
SQL Error [900] [42000]: ORA-00900: invalid SQL statement
```

Also in the SQL editor the following part of the script is selected:

```sql
    PROCEDURE LOG(SEVERITY VARCHAR2, MSG CLOB) IS
    BEGIN
        NULL;
    END;
```

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
This will require better PL/SQL parser implementation (nested blocks and packages support).

**Comment by uslss** [comment]
verified
