### ISSUE TITLE
Generate SQL (for SELECT) doesn't show columns anymore in SQL Preview

### ISSUE THREAD

**Issue by AdrianoBortoloto** [dbeaver/dbeaver#8096]
#### System information: 
- Microsoft Windows 10 Pro 10.0.18362 Compilação 18362
- DBeaver 6.3.5 and forward
- Java version 1.8.0_211
- No extensions

#### Connection specification:
- PostgreSQL 10.6
- org.postgresql.Driver 9.4.1212.jre7
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
The Generate SQL for SELECT option doesn't show the columns anymore in SQL Preview, it shows the '*' instead. I believe it may be configured in any preferences option, but I didn't found that.

#### Steps to reproduce, if exist:
It can be reproduced right clicking table on Database Navigator, select Generate SQL > SELECT.

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/12927584/75982114-9be07180-5ec4-11ea-93b1-47cd5dc90a7e.png)

![image](https://user-images.githubusercontent.com/12927584/75982172-b7e41300-5ec4-11ea-93c8-6a8e5b32b448.png)

**Comment by serge-rider** [comment]
I think it never generated column names.

Perhaps you mean "Generate SQL" from data - right click on resultset -> Generate SQL -> SELECT .. WHERE ..). It includes all column names

**Comment by AdrianoBortoloto** [comment]
I tested in previous versions (6.3.3 and 6.3.4) and the behavior was show all columns in SQL Preview using the Database Navigator.

**Comment by serge-rider** [comment]
@AdrianoBortoloto You are right

**Comment by rafaelcarmoribeiro** [comment]
Indeed in the DBeaver 6.3.4 the fields are shown when this option is selected.

![image](https://user-images.githubusercontent.com/13237436/75983409-478ac100-5ec7-11ea-9217-537161494fe6.png)

**Comment by Quickzx** [comment]
I hope they revert/fix this, I use the generate SQL daily to easily source all the column for scripting.

**Comment by uslss** [comment]
verified
