### ISSUE TITLE
org.jkiss.dbeaver.git.feature cannot be installed on Oxygen (Eclipse 4.7)

### ISSUE THREAD

**Issue by vincent-zurczak** [dbeaver/dbeaver#8097]
Hi,

#### System information: 
- Operating system (distribution) and version: Ubuntu 19.04, but also verified on other systems
- DBeaver version: latest
- Additional extensions: org.jkiss.dbeaver.git.feature
- Eclipse version: 4.7 (Oxygen)

#### Problem description:

It is said in the documentation that DBeaver can be installed on older Eclipse versions, from 4.2 to 2019-09. I am trying to install DBeaver with the **org.jkiss.dbeaver.git.feature** feature in Eclipse Oxygen.  

Unfortunately, the following error occurs.

```
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10054 Cannot complete the install because of a conflicting dependency.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:426)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:338)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:811)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3827)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3755)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3736)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3629)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:585)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:711)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1583402985191
  ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
    ERROR: org.eclipse.equinox.p2.director code=0 Git integration for Eclipse - Core 4.9.2.201712150930-r (org.eclipse.egit.core 4.9.2.201712150930-r)
    ERROR: org.eclipse.equinox.p2.director code=0 Git integration for Eclipse - Core 5.6.0.201912101111-r (org.eclipse.egit.core 5.6.0.201912101111-r)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1583402985191
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.egit.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1583402985191
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.git.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Git integration for Eclipse 4.9.2.201712150930-r (org.eclipse.egit.feature.group 4.9.2.201712150930-r)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.egit.core [4.9.2.201712150930-r,4.9.2.201712150930-r]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: DBeaver Git support 1.0.16.202003021717 (org.jkiss.dbeaver.git.feature.feature.group 1.0.16.202003021717)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.egit.core [5.6.0.201912101111-r,5.6.0.201912101111-r]
```

The same error should occur with any other version than the last one.

#### Steps to reproduce:

1. Download [Eclipse Oxygen](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-java-oxygen-3a-linux-gtk-x86_64.tar.gz).
2. Add https://dbeaver.io/update/latest/ in the list of repositories.
3. Try to install DBeaver with the **Git Support** extension.

The installer will try to find a solution to eventually indicate it cannot install the Git support plug-in.

#### Solution:

This error happens because the **dbeaver.git** feature group [includes official Eclipse plug-ins](https://github.com/dbeaver/dbeaver/blob/301a69a9285e602dc04e5e1db4b219d29e8359ff/features/org.jkiss.dbeaver.git.feature/feature.xml#L34). When the feature is built, it sets the plug-in version to the current one available: `5.6.0.201912101111-r` in this case. 

I guess it was done this way to have everything in the same place.  
One solution would be to split this feature, having one with only DBeaver plug-ins and the second one for Eclipse git plug-ins. Another option is to simply remove these plug-ins from the feature. People will get them from official repositories, or reuse the ones already installed.

**Comment by serge-rider** [comment]
Well, this extension was originally developed for installing into DBeaver standalone version, not Eclipse.
That's why all dependencies (egit and jgit) are included. 

Probably we should use standard Eclipse P2 repo for external deps though.

**Comment by serge-rider** [comment]
I've changed git feature configuration.

**Comment by uslss** [comment]
verified

**Comment by vincent-zurczak** [comment]
Thanks. :+1:

**Comment by vincent-zurczak** [comment]
How will it work if there is another version of the egit feature installed (i.e.  not `1.0.0`)?  
Maybe setting the version to `0.0.0` would be more flexible? And work no matter the Eclipse version.

**Comment by AlexLasher** [comment]
How can I install git plugin for dbeaver locally on my PC? I cannot get access to https://dbeaver.io/update/latest/ because of security policy in my company? Can I add manually other resources for dependencies in istallation process?
