### ISSUE TITLE
Data Editor Number Format Regression (not using scientific notation)

### ISSUE THREAD

**Issue by austin-beer** [dbeaver/dbeaver#8099]
#### System information: 
- Operating system (distribution) and version: Ubuntu 19.04
- DBeaver version: 6.3.5 Standalone
- Additional extensions: N/A

#### Connection specification:
- Database name and version: PostgreSQL 10.6
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes, an SSH tunnel

#### Describe the problem you're observing:
Very small numbers are not being displayed with scientific notation in the data editor which makes it very difficult to see the actual value of the numbers with any degree of precision.

DBeaver 6.2.5 (works correctly):
![DBeaver_Floating_Point_6 2 5](https://user-images.githubusercontent.com/22201316/75994334-0d65f300-5eb8-11ea-943b-c1c7d6f5f103.png)

DBeaver 6.3.0 (does not use scientific notation):
![DBeaver_Floating_Point_6 3 0](https://user-images.githubusercontent.com/22201316/75994363-1951b500-5eb8-11ea-9bb3-cd7020e559d2.png)

DBeaver 6.3.5 with Native Numeric Format enabled (uses scientific notation only for some numbers):
![DBeaver_Floating_Point_6 3 5_Native_Numeric_Format](https://user-images.githubusercontent.com/22201316/75994424-32f2fc80-5eb8-11ea-95a1-2c3c7d54004e.png)

Also, DBeaver 6.3.5 with Native Numeric Format enabled in the above example outputs the following error repeatedly: `Error converting number to string: Rounding needed with the rounding mode being set to RoundingMode.UNNECESSARY`.

**Comment by uslss** [comment]
hi @austin-beer ,
what data type do you use?

**Comment by austin-beer** [comment]
The data types of these three fields are all **float8**, so 64-bit floating-point numbers.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by austin-beer** [comment]
You are very welcome. Thank you for following up so quickly.

**Comment by uslss** [comment]
Reopened.
Scientific notation in the data editor for small numbers still doesn't used.
Small values are always shown as 0 or -0 in Value panel.
![image](https://user-images.githubusercontent.com/31996417/76740585-2bb4d400-677f-11ea-9040-498a63d7e33f.png)

**Comment by uslss** [comment]
verified

**Comment by austin-beer** [comment]
In my testing with DBeaver 7.0.4 this is still a bug and so I opened a new issue for it: #8670.
