### ISSUE TITLE
SQL Server extension

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#810]
We need fully-functional SQL Server (MSSQL) extension.
And it can be used for Sybase as well (with some limitations).

**Comment by cniweb** [comment]
+1

**Comment by jest** [comment]
Does this involve switching to the newer open-sourced version of Microsoft's driver (https://github.com/Microsoft/mssql-jdbc)? Currently downloaded driver seems pretty old (according to modification dates of files inside driver JAR).

**Comment by serge-rider** [comment]
@jest Yes. Perhaps new driver version will be included in the next DBeaver version, thanks for reminding.
We'll still keep old jTDS driver for some time for backward compatibility.

**Comment by tati-kru** [comment]
Unfortunately, this issue is too big for the version 5.0. Hope, we will be able to do this until 5.1.

**Comment by marcgise** [comment]
+1

**Comment by esequiel-ferreira** [comment]
+1

**Comment by ido-ran** [comment]
+1

**Comment by AugustoNeves** [comment]
+1

**Comment by serge-rider** [comment]
First version of SQL Server extension will be presented in 5.2.5.
I'll re-check all referencing tickets and close the ones which were fixed along with this ticket.

This was one of the most long-playing and heavies tickets in DBeaver. Closing it - finally!

**Comment by Jogai** [comment]
> This was one of the most long-playing and heavies tickets in DBeaver. Closing it - finally!

Thank you for your work (on this, but also on the whole project)! <sub>I'm hesitant to ask, but how do I enable it?</sub>

**Comment by serge-rider** [comment]
Now there are 3 SQL Server  drivers:
- Microsoft
- jTDS
- Legacy (this is the driver whic was used in prrevious versions of DBeaver)

Just use the first one unless you have some specific reasons to use jTDS or Generic.

Note: this is the first version on new SQL Server extension and it has a few known bugs. We going to resolve most of them till DBeaver 5.3 release.

**Comment by krkhnh** [comment]
After I updated DBeaver and download drivers via prompted driver settings popup, I'm having "SQL Error: The value is not set for the parameter number 1." message when I trying to connect to SQL Server. I can't connect.

**Comment by adbakke** [comment]
Will "Modify Stored Procedure" be something added on to 5.3? Unless I'm missing something that's not available yet in 5.2.5. I'm a new user of DBeaver (and I'm really enjoying using it), and arrived here trying to find how to modify procedures easily.

**Comment by pfurini** [comment]
Sorry for posting in a closed issue, but how about #2193 ? 
I cannot find any option to deal with `IDENTITY_INSERT` when importing data, and it (importing) constantly fails. I'm on DBeaver 6.0.4

**Comment by ngoclamnn** [comment]
seems like the "create new database" is still not avaiable. :(
