### ISSUE TITLE
Editor in separate window won't give focus to primary window

### ISSUE THREAD

**Issue by knwpsk** [dbeaver/dbeaver#8100]
When I drag one or more editor tabs to a separate window, I can no longer get focus on the primary window, unless I drag the second window out of the way.  

Another way to describe it:  When the second window is in focus, and I click to select the primary window (either on the primary window's title bar, or in the task bar), nothing happens -- the second window stays on top, and I can't see the primary window.

It's *almost* like the second window is modal.  BUT:  If I then drag the second window completely out of the way (onto my second screen), I can select items (tabs, rows, buttons, etc) in the primary window.

Also, not an issue, but possibly a clue the behavior:  Windows does not show the second window in the task bar (like it does for other apps, when you have multiple windows open for those apps).

I'm using dbeaver 7.0.0 on Windows 10.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
1. It is Eclipse-specific behavior. I believe that multiple windows were designed specifically for multi-monitor environment.
2. You can start multiple instances of dbeaver with different workspaces (see File->Switch Workspace).
