### ISSUE TITLE
Database Navigator - Does not show all SYSIBM tables for DB2 for z/OS

### ISSUE THREAD

**Issue by db2zosuser** [dbeaver/dbeaver#8102]
#### System information: 
- Win 10
- DBeaver CE Version 6.3.4.202002011957

#### Connection specification:
- DB2 12 for z/OS - FUNCTION LEVEL (V12R1M505 ) 
- IBM Data Server Driver for JDBC and SQLJ 4.15.105

#### Describe the problem you're observing:
DBeaver CE Version 6.3.4.202002011957 (Win 10) seems to have an issue on DB2 12 for z/OS to display ALL DB2 catalog tables. We are using IBM Data Server Driver for JDBC and SQLJ 4.15.105. However issue seems not to be related to driver version (see later). 

When displaying the tables for schema SYSIBM only 93 out of 302 objects are showed. The displayed objects are of Table Type equals ALIAS, AUXILIARY TABLE or GLOBAL TEMPORARY TABLE.

All the other system tables (for instance SYSIBM.SYSDATABASE, SYSIBM.SYSTABLES, SYSIBM.SYSTABLESPACE, SYSIBM.SYSINDEXES, …) are missing:
![image](https://user-images.githubusercontent.com/61581747/76064838-c0068600-5f8a-11ea-9e5a-34279102da04.png)

Same issue (with missing tables) is encountered when using table name auto completion when typing in an SQL stmt:
![image](https://user-images.githubusercontent.com/61581747/76064875-cbf24800-5f8a-11ea-97e6-47544511b756.png)

Having traced the communication between DBeaver and DB2 for z/OS it looks that DBeaver is using stored procedure SYSIBM.SQLTABLES to query the DB2 catalog tables. Stored procedure SYSIBM.SQLTABLES does then, query the catalog using following SQL stmts with a case clause to set the Table Type:
![image](https://user-images.githubusercontent.com/61581747/76064898-d44a8300-5f8a-11ea-8d12-57d665288e91.png)

According to IBM product documentation (https://www.ibm.com/support/knowledgecenter/SSEPEK_10.0.0/odbc/src/tpc/db2z_fntables.html) table type SYSTEM TABLE did already exist in DB2 10 for z/OS and most probably already in the version before. Hence there was no recent change by IBM DB2 triggering this issue. 

#### Steps to reproduce, if exist:
1. Connect to DB2 for z/OS 
2. In Database Explorer search for schema SYSIBM and display the tables
 
#### Include any warning/errors/backtraces from the logs
No warning/errors found in the log files

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
@db2zosuser Do you have "Show system tables" option enabled?
![image](https://user-images.githubusercontent.com/6398845/77881212-253a5800-7267-11ea-893f-9a8b9f176b65.png)

**Comment by Sargul** [comment]
Verified in our that when activating "Show system objects" the regular system tables are viewable:
Activates Flag:
![image](https://user-images.githubusercontent.com/5595511/78255505-a445bf80-74f7-11ea-9680-4c827e02ea0e.png)

Deactivated Flag:
only ALIAS, AUXILIARY TABLE or GLOBAL TEMPORARY TABLE are shown:
![image](https://user-images.githubusercontent.com/5595511/78255634-da833f00-74f7-11ea-8522-8fccfeab8841.png)

**Comment by db2zosuser** [comment]
Hi @serge-rider and @Sargul 
Thanks for the hint and the confirmation. Yes, you are right when enabling "show system objects" in the config settings all SYSIBM objects are displayed.  
However I wonder why this settings is not enabled by default and if the current distinction in system objects and non system objects is really correct. The differentiation is done based on the 'Table Type' returned by the stored procedure SYSIBM.SQLTABLES. However by design all objects in schema SYSIBM are system objects. 

It is true that the tables SYSCONTROLS_DESC and SYSCONTROLS_DESC_H are auxiliary tables, but they are at the same time also system objects:
![image](https://user-images.githubusercontent.com/61581747/78266429-102f2480-7506-11ea-90cd-9ff7b8d470c5.png)

Hence that differentiation based on the table type is not completely correct ant might lead to misunderstandings. Hence I would appreciate if you consider to change/improve it ;-)

**Comment by Sargul** [comment]
The classification comes from the driver meta data API. However for the db2 zos plugin it makes totally to display system objects as default as mainframe people make heavy use of the system tables in their daily work routine

**Comment by serge-rider** [comment]
@Sargul @db2zosuser thanks for testing.

In 7.0.2 we will add new navigator view configuration (#7387).
In Advanced mode (for now it is the default mode) system objects will be visible by default.

So, closing this ticket.
