### ISSUE TITLE
Error when editing enum columns in PostgreSQL

### ISSUE THREAD

**Issue by koffmoff** [dbeaver/dbeaver#8104]
#### System information: 
- Win 10 Latest
- DBeaver 7.0.0

#### Connection specification:
- PostgreSQL 11.7
- PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Cannot create or add enum columns in table data view.

#### Steps to reproduce, if exist:
1. Create test table
```sql
create type "test_enum" as enum('A', 'B', 'C');
create table "test_table" ("id" character varying not null, "val" "test_enum", primary key("id"));
```
2. Open data grid view for `test_table`.
3. Create a new row.
4. Enter some values and click save.
5. An error dialog pops up with this error:

> Error synchronizing data with database
> 
> Reason:
> SQL Error [42804]: ERROR: column "val" is of type test_enum but expression is of type character varying
>   Hint: You will need to rewrite or cast the expression.
>   Position: 52

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
@koffmoff If you edit results of query "select * from test_table) then you need to refresh metadata on client side before editing. Click on your schema in database navigator and press f5.
As dbeaver doesn't know that data type "test_enum" exists yet and tries to edit this column as string.

**Comment by koffmoff** [comment]
@serge-rider Problem remains even after refresh. Also after a restart of DBeaver. It is not a matter of editing a newly created DB. It is the same problem if I connect to an existing DB. Doesn't matter if I edit the result of a query or just click my way to the table data view.

**Comment by serge-rider** [comment]
Yep, I've reproduced this issue.

**Comment by uslss** [comment]
verified
