### ISSUE TITLE
error every 10-15minutes  before update to 7 version

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#8106]
#### System information: 
- Operating system (distribution) and version WINDOWS 10 64bit
- DBeaver version  7.0.0.202002292132

#### Describe the problem you're observing:
I'm just looking at the table parameters.

Every 10-15minutes IDE show the window with error
Произошла внутренняя ошибка: "Периодическое сохранение рабочей области.".
Cannot set lower sequence number for root (previous: 39, new: 38). Location: C:\Users\Professional\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins\org.eclipse.core.resources\.safetable\org.eclipse.core.resourcesTimestamps and tree sequence numbers from file:
#Fri Mar 06 11:55:12 YEKT 2020
/.tree=39
#Fri Mar 06 11:55:12 YEKT 2020
/.tree=39

**Comment by uslss** [comment]
Hi @detkliff ,
please try to reset workspace (https://github.com/dbeaver/dbeaver/wiki/Reset-workspace),
looking forward for your response if it was helpful or not

**Comment by detkliff** [comment]
On version 7.0.1 problem is not repeated

**Comment by NemchinovSergey** [comment]
I faced with the issue on 7.1.4

**Comment by detkliff** [comment]
> 
> 
> I faced with the issue on 7.1.4

Посмотрите https://github.com/dbeaver/dbeaver/issues/8548
Разработчики говорят, что будет добавлена специальная кнопка для этого в версии 7.2.0. 
Конечно не понятно почему бы этот процесс не сделать каким то автоматическим.
