### ISSUE TITLE
Vertical scrollbar is not at edge of screen

### ISSUE THREAD

**Issue by hlascelles** [dbeaver/dbeaver#8107]
#### System information: 
- Operating system Mint Linux 19.3
- DBeaver version 7.0.0

#### Describe the problem you're observing:

The vertical scrollbar is not on the edge of the screen, so involves a "hunt and click" to grab it. We should be able to move the mouse quickly to the right and be able to click.

#### Steps to reproduce, if exist:

Open any SQL Editor window and enter enough text to produce a vertical scrollbar.

The scrollbar is present, but is very thin, and is a few pixels in from the edge.

**Comment by uslss** [comment]
hi @hlascelles , 
do you use dark theme?

**Comment by hlascelles** [comment]
No, ordinary theme. Pic:

![image](https://user-images.githubusercontent.com/299102/76144289-9d519b80-6076-11ea-96f9-f398a70581f6.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
This behavior is controlled by Eclipse platform. We can't fix it.

**Comment by hlascelles** [comment]
I can open an issue with them... Which [repo is it](https://github.com/eclipse) of theirs you are using as the host framework?
