### ISSUE TITLE
Massive debug log files generated

### ISSUE THREAD

**Issue by piaste** [dbeaver/dbeaver#8108]
DBeaver 7.0.0 generated 10GB of debug log files in a few days of activity.

I'm guessing a debug flag got left turned on somewhere?

![image](https://user-images.githubusercontent.com/12280683/76077804-b50b2000-5fa1-11ea-9fe5-2ba213f6346c.png)

#### System information: 
- Win10 x64 Insider 2004
- DBeaver 7.0.0

**Comment by serge-rider** [comment]
Probably some error with huge stacktrace was spammed.
Could you post a sample of debug log content?

You can disable debug log in preferences:
![image](https://user-images.githubusercontent.com/6398845/76097962-a9d3e680-5fd9-11ea-92c8-1cafa8f67b8e.png)

**Comment by piaste** [comment]
Ok. I had to wipe it as my disk was full, I've installed a large file editor and next time it happens I'll grab a chunk, then I'll remove the flag.

Thanks.

**Comment by uslss** [comment]
ticket will be closed.
if issue reproduce once again - feel free to reopen the ticket
