### ISSUE TITLE
Allow disable autocomplete in connection settins

### ISSUE THREAD

**Issue by ceinmart** [dbeaver/dbeaver#8110]
I work with a lot of versions of multiple databases vendors. 
For old oracle databases (8i, 9i) the autocomplete/sql assistant is a pain because they are slow and frequently freeze my connection. 
I need the option to disable the autocomplete/assistant only for theses connections only, which my suggestion is to add this option into the "edit connection" -> "sql editor"
Another way to workaround is adding a button in the toolbar to enable/disable the assistant for the current session, this way I can disable only if it is annoying me.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by LonwoLonwo** [comment]
You can do it in Preferences, just use "Datasource settings"

![2021-06-03 19_13_54-Properties for Script-31 sql](https://user-images.githubusercontent.com/45152336/120677668-ff7a9580-c49f-11eb-834f-97895b90ebff.png)

Tell us if it helps to solve your problem.

**Comment by ceinmart** [comment]
> You can do it in Preferences, just use "Datasource settings"
> 
> ![2021-06-03 19_13_54-Properties for Script-31 sql](https://user-images.githubusercontent.com/45152336/120677668-ff7a9580-c49f-11eb-834f-97895b90ebff.png)
> 
> Tell us if it helps to solve your problem.

Hi, thanks for the suggestion, but if I understand I will need to execute this step for each script I opened ???? inviable... 
However, If I can setup a button on toolbar for quick set/unset this option or define a key shortcut, that solves for me, because is quick/fast to switch. 
I'm looking here how to do and found no way for any of both options.

**Comment by ceinmart** [comment]
> > You can do it in Preferences, just use "Datasource settings"
> > ![2021-06-03 19_13_54-Properties for Script-31 sql](https://user-images.githubusercontent.com/45152336/120677668-ff7a9580-c49f-11eb-834f-97895b90ebff.png)
> > Tell us if it helps to solve your problem.
> 
> Hi, thanks for the suggestion, but if I understand I will need to execute this step for each script I opened ???? inviable...
> However, If I can setup a button on toolbar for quick set/unset this option or define a key shortcut, that solves for me, because is quick/fast to switch.
> I'm looking here how to do and found no way for any of both options.

I'm testing this solution and looks they keep the setting . 
What is weird is why this setting not appear in the properties of the connection ? 
If the behavior is that, then ok, this works for me. 
We can close this request.

**Comment by LonwoLonwo** [comment]
I've added "SQL Formatting" and "Code Completion" tabs in Connection settings in DBeaver 21.1.1.
Now the necessary settings will be easier to find for datasource.

![2021-06-07 14_01_12-Window](https://user-images.githubusercontent.com/45152336/121029677-78843080-c7b1-11eb-97cb-5de0b422760a.png)

Now the ticket will check testers and will close it on their own.

Thanks for feedback!

**Comment by ceinmart** [comment]
awesome!!
thank you very much!!!!
have a nice day!

**Comment by uslss** [comment]
verified
