### ISSUE TITLE
Changing Theme Breaks Data Transfer Wizard.

### ISSUE THREAD

**Issue by tetra-archos** [dbeaver/dbeaver#8113]
#### System information: 
- Operating system (distribution) and version 
Windows 10 w/ Latest Patches
- DBeaver version
Community Edition Version 7
- Additional extensions
Darkest Dark Theme
#### Connection specification:
- Database name and version
N/A
- Driver name
N/A
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
N/A

#### Describe the problem you're observing:
Changing the Theme seems to break the Data Transfer Wizard used to export results to another table or file. The wizard still works but will only export to csv and will not let you select another file or format. Neither reseting the UI nor changing the theme back to default resolves the issue.

#### Steps to reproduce, if exist:
Change Theme, Click Data Export Toolbar button at bottom of results.

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
will be resolved in the scope of #9223
