### ISSUE TITLE
[Hive] It is written that Grouping isn't supported, but it works

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8115]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.0 EA

#### Connection specification:
- Database name and version Apache Hive

#### Describe the problem you're observing:
It is written that Grouping isn't supported, but it works
![2020-03-06_20h44_28](https://user-images.githubusercontent.com/31996417/76108463-b3fee080-5feb-11ea-9d94-ae81bbb2fa27.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
