### ISSUE TITLE
Access denied for user 'root'@'localhost' Linux Mint DBeaver community v7 MariaDB

### ISSUE THREAD

**Issue by catalin560** [dbeaver/dbeaver#8116]
Linux Mint DBeaver community v7 MariaDB Access denied for user 'root'@'localhost'

**Comment by catalin560** [comment]
tried this http://www.daniloaz.com/en/how-to-create-a-user-in-mysql-mariadb-and-grant-permissions-on-a-specific-database/
and I still get `Access denied for user 'admin'@'localhost' to database 'mydb'`

**Comment by uslss** [comment]
Does it work for you in the previous version?

**Comment by uslss** [comment]
cannot reproduce an issue. if it is still actual for you - feel free to reopen the ticket
