### ISSUE TITLE
Connecting per SSH key without providing a user name

### ISSUE THREAD

**Issue by dschuessler** [dbeaver/dbeaver#8120]
#### System information: 
- macOS 10.14.6
- 7.0.0
- openjdk 13.0.2

#### Connection specification:
- MySQL 5.7.25
- MySQL 8+
- SSH

#### Describe the problem you're observing:

The MySQL database is hosted on the Google Cloud Platform. To access the database I had to install and initialize the Google Cloud SDK, which put a key pair into my `~/.ssh`. I can successfully connect to the database via TablePlus by providing the private key and no user or password. When I try to connect via DBeaver the same way I get the error "SSH user not specified."

Here are the connection details as provided to TablePlus. This succeeds.

![Bildschirmfoto 2020-03-07 um 13 26 39](https://user-images.githubusercontent.com/5774545/76143424-a42cde00-6077-11ea-963a-a9014d49800f.png)

Here are the SSH details as provided to DBeaver. This fails.

![Bildschirmfoto 2020-03-07 um 13 34 23](https://user-images.githubusercontent.com/5774545/76143542-84e28080-6078-11ea-92c3-72d8db73df0a.png)

#### Include any warning/errors/backtraces from the logs

![Bildschirmfoto 2020-03-07 um 13 38 50](https://user-images.githubusercontent.com/5774545/76143594-02a68c00-6079-11ea-94ea-b4289af7d343.png)

**Comment by serge-rider** [comment]
I assume that in case of empty user name current OS user name is used. Could you confirm that?

If this assumption is correct than it would be easy to implement.

**Comment by dschuessler** [comment]
This seems indeed to be the case. Thanks for that tip!

**Comment by serge-rider** [comment]
Done. We'll use current user name by default.

**Comment by kseniiaguzeeva** [comment]
verified
