### ISSUE TITLE
Unable to name / rename indexes in MariaDB

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#8123]
#### System information: 
- Operating system (distribution) and version: MacOS 10.14.6
- DBeaver version: 7.0.0
- Additional extensions 

#### Connection specification:
- Database name and version: MariaDB
- Driver name: JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? occasionally

#### Describe the problem you're observing:

When creating a table index in MariaDB, there is no field available in the pop-up editor to name the index. Additionally, once the index has been named, there is no "rename index" menu item to rename the index. 

As indexes can be named and renamed, it would be good to have the ability to do so from the UI

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by rotorboy** [comment]
When will this be released?

-Avi

**Comment by serge-rider** [comment]
https://github.com/dbeaver/dbeaver/milestones

**Comment by kseniiaguzeeva** [comment]
Verified
