### ISSUE TITLE
Show how many selected rows in data editor.

### ISSUE THREAD

**Issue by Jnb2387** [dbeaver/dbeaver#8125]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
When I select rows in the data editor show a count of how many rows are selected on the toolbar at the bottom or so.

**Describe alternatives you've considered**
Alternate way I do it now is pick some column and select multiple rows, open the panels for Calc there is a count and distinct.

**Additional context**

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
Done. Rows/columns/cells selection size is now shown in the data viewer status bar.

**Comment by uslss** [comment]
verified

**Comment by awvalenti** [comment]
Can't see it here, it only shows fetched rows count, not selected. Where can I enable it?
<img width="1924" height="99" alt="Image" src="https://github.com/user-attachments/assets/52cecc77-578d-46f6-a8b7-ae769afdb832" />
