### ISSUE TITLE
Indexes no longer visible

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#8126]
#### System information: 
- Operating system (distribution) and version - mac
- DBeaver version 7.0.0
- Additional extensions

#### Connection specification:
- Database name and version pg 11.2,11.6
- Driver name default
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  doesn't work with/without ssh

#### Describe the problem you're observing:
When F4 on a table - going to indexes tab doesn't show indexes on the table
![image](https://user-images.githubusercontent.com/18515297/76163329-cb55df00-614d-11ea-8c97-db5a6d1d4332.png)
but it does have an index:
![image](https://user-images.githubusercontent.com/18515297/76163339-df014580-614d-11ea-9069-33ba764ab2f1.png)

tried to refresh - did not help. tested on the same table, 2 different databases.
index definition is 
`CREATE UNIQUE INDEX user_group_permissions_uq ON user_group_permissions USING btree (col1, col2, col3, col4) --not the real column names.`

**Comment by serge-rider** [comment]
In #7443 we stopped showing indexes which correspond to unique constraints (created by `ADD CONSTRAINT worksheet_un UNIQUE ...`). Because they are "implicit". We shouldn't show them in DDL or in index list as they can't be managed explicitly (e.g. dropped).

If your index was created without a constraint then it is a bug. But I can't reproduce it. 
Could you post sample table DDL?

**Comment by pyrocks** [comment]
`We shouldn't show them in DDL or in index list as they can't be managed explicitly (e.g. dropped).`
Totally disagree with this statement. Disable editing - fine (although the DB won't let you even if you tried - since it is used by the constraint - so you don't really HAVE TO) - but not show it as if it doesn't exist? This makes no sense.

**Comment by serge-rider** [comment]
Well, this makes sense. I think we should show some special error/warning on contraint-based index drop attempt (decrypting server errors can be tricky).

Let's make it enhancement. It is not a bug as currently it works as designed, but we need to change current behavior.

**Comment by pyrocks** [comment]
Thanks. Please never ever hide indexes.
I would argue the same for anything which is implicitly created - like  pg trigger constraints should also be shown. If I were you I wouldn't bother parsing the DB error - just present it to the user and he will know/learn what needs to be done from there.

**Comment by uslss** [comment]
verified
