### ISSUE TITLE
TextEditor Copy/Paste is not working under wayland/swaywm

### ISSUE THREAD

**Issue by atmouse-** [dbeaver/dbeaver#8129]
#### System information: 
- Operating system (distribution) and version

Archlinux, swaywm 1.4, wlroots 0.10.0
wayland 1.18.0

exec environ
```
ALACRITTY_LOG=/tmp/Alacritty-1205.log
BEMENU_BACKEND=wayland
COLORTERM=yes
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=sway
DISPLAY=:0
EDITOR=vim
GDMSESSION=sway
GDM_LANG=en_US.UTF-8
GPG_TTY=/dev/pts/6
HOME=/home/user
I3SOCK=/run/user/1000/sway-ipc.1000.1147.sock
LANG=en_US.UTF-8
LESS_TERMCAP_mb=[01;31m
LESS_TERMCAP_md=[01;31m
LESS_TERMCAP_me=[0m
LESS_TERMCAP_se=[0m
LESS_TERMCAP_so=[01;44;33m
LESS_TERMCAP_ue=[0m
LESS_TERMCAP_us=[01;32m
LOGNAME=user
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MAGICK_OCL_DEVICE=OFF
MAIL=/var/spool/mail/user
PAGER=less
PATH=/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
PS1=%B%F{red}%(?..%? )%f%b%B%F{blue}%n%f%b@%m %B%40<..<%~%<< %b%# 
PWD=/home/user
PYTHONTRACEMALLOC=1
QT_QPA_PLATFORM=wayland
SHELL=/bin/zsh
SHLVL=2
SWAYSOCK=/run/user/1000/sway-ipc.1000.1147.sock
TERM=screen-256color
TMUX=/tmp//tmux-1000/default,1234,0
TMUX_PANE=%9
TMUX_PLUGIN_MANAGER_PATH=/home/user/.tmux/plugins/
USER=user
USERNAME=user
WAYLAND_DISPLAY=wayland-0
XCURSOR_SIZE=24
XDG_CURRENT_DESKTOP=Unity
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=sway
XDG_SESSION_ID=2
XDG_SESSION_TYPE=wayland
XDG_VTNR=2
_=/usr/bin/env
_JAVA_AWT_WM_NONREPARENTING=1
CLOUDSDK_ROOT_DIR=/opt/google-cloud-sdk
CLOUDSDK_PYTHON=python2
CLOUDSDK_PYTHON_ARGS=-S
GOOGLE_CLOUD_SDK_HOME=/opt/google-cloud-sdk
VDPAU_DRIVER=va_gl
HG=/usr/bin/hg
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
LC_MESSAGES=
```

- DBeaver version

dbeaver 6.3.5

- Additional extensions

#### Connection specification:
- Database name and version

mysql 5.7

- Driver name

Driver for MySQL 4.x-5.7

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

no

#### Describe the problem you're observing:

Copy text from chrome-browser by Ctrl+C,
cannot paste to TextEditor in Dbeaver.  

#### Steps to reproduce, if exist:

1. open chrome-browser and copy something
2. check clipboard status
```
% wl-paste --list-types
text/plain;charset=utf-8
text/plain
```

3. paste in dbeaver text-editor box, paste nothing!

***BUT***, following Step works
1. 
```
% echo -en "aaaaaa" | wl-copy -t STRING
% wl-paste --list-types
STRING
text/plain
text/plain;charset=utf-8
TEXT
UTF8_STRING
```

2. paste into dbeaver is working~!

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
@atmouse- is it still actual?

**Comment by atmouse-** [comment]
> @atmouse- is it still actual?

The issue is gone under dbeaver 21 :handshake:  with wayland 1.19 and swaywm 1.6

**Comment by Hippo0o** [comment]
copying from firefox
```
$ wl-paste --list-types
text/html
text/_moz_htmlcontext
text/_moz_htmlinfo
text/plain;charset=utf-8
text/plain
text/plain;charset=utf-8
text/plain
text/x-moz-url-priv
```
does not work for me in version 22

**Comment by Hippo0o** [comment]
copy/paste from firefox
```
$ wl-paste --list-types
text/html
text/_moz_htmlcontext
text/_moz_htmlinfo
text/plain;charset=utf-8
text/plain
text/plain;charset=utf-8
text/plain
text/x-moz-url-priv
```
or from my clipboard manager copyq
```
$ wl-paste --list-types
text/html
text/plain
application/x-copyq-owner
text/plain;charset=utf-8
```

do not work for me in version 22

**Comment by poltpolt** [comment]
Regression in 22.1 at least this is when I switched to wayland and noticed this bug

**Comment by biji** [comment]
same issue , I'm using  `22.1.5.202208211008`

**Comment by Neemaul** [comment]
Same issue under `22.1.3.202207311845`. Same conditions - using wayland and swaywm.

Can someone reopen?

**Comment by brauliobo** [comment]
same with 22.2.0 + wayland

**Comment by akhiljalagam** [comment]
same issue

```
{\rtf1\ansi\uc1\deff0{\fonttbl{\f0\fnil Monospace;}}
{\colortbl\red0\green0\blue0;\red255\green255\blue255;\red232\green242\blue254;\red240\green216\blue168;}
{\f0\fs20 \fi0\ql {\chshdng0\chcbpat2 {\cf0 }{\cf0\chshdng0\chcbpat3 data}}
}}
```

**Comment by gqcdm** [comment]
+1 gnome+wayland+dbeaver

**Comment by serfreeman1337** [comment]
Possible workaround:
* Copy text from DBeaver to LibreOffice Writer
* Copy text from LibreOffice Writer

**Comment by bvdeenen** [comment]
I can confirm this issue with 22.2.5

**Comment by serfreeman1337** [comment]
~~With dbeaver 22.3.0 I have copy working on kde wayland, but I can't paste anything back.
Found workaround as to paste first in "Database Navigator" filter, copy from filter and then paste in TextEditor.~~

UPD: It's only a problem with paste from Kate . Paste from VS Code or Firefox works fine.

**Comment by benmotyka2** [comment]
Temporary workaround is to paste text to VS Code, and then copy from VS Code and paste to dbeaver

**Comment by 1Jo1** [comment]
I have the same issue, paste doesn't work with sway(wayland), however all other ui applications firefox VS Code, IntellJ, Thunderbird works fine
my workaround is just paste that in a file via terminal and open the file in dbeaver :)
version:  22.3.4.202302111842

**Comment by SilvaMinor** [comment]
Same issue. Dbeaver CE Version 22.3.4.202302111842. Pasting from LibreOffice Writer, Kate and terminal doesn't work. Workaround with browsers.

**Comment by ebrake** [comment]
Same issue, Dbeaver v22.3.5.202302171528 can't do basic copy/paste most of the time under Wayland

**Comment by pipe99f** [comment]
Same issue, Dbeaver 22.3.4.202302111842, paste doesn't work.

**Comment by lkraav** [comment]
Y, same in 23.0.0. This issues should not be Closed.

**Comment by glenson** [comment]
Please fix. I'm using version 23.

**Comment by ja-silveira** [comment]
Issue persists on KDE Plasma with Wayland. I can´t paste from any other application.
KDE Plasma 5.27.3
KDE Frameworks 5.104.0
DBeaver 23.0.1

**Comment by scippio** [comment]
Dbeaver version 23.0.2 I can't paste.

**Comment by ccoVeille** [comment]
I confirm the bug is still present cc @scippio 

Should we reopen a ticket ?

**Comment by ccoVeille** [comment]
just noticed that #16766 seems to be the new ticket about this

**Comment by mohammadgh1370** [comment]
23.1.4

cant copy paste

**Comment by TheParthMaru** [comment]
Couple of workarounds are as follows:
1. Use vscode to open the text file and we can directly copy and paste to Dbeaver (Best method)
2. On terminal use, `cat filename`, copy the text and paste in Dbeaver.
3. Copy the text and paste in any browser and again copy and paste it in Dbeaver.

**Comment by sentientmachin3** [comment]
23.2.2 bug still occurs

**Comment by rsmaximiliano** [comment]
22.2.3 same

**Comment by akizminet** [comment]
23.2.4 bug still occurs

**Comment by DrRamm** [comment]
23.2.5 bug still occurs

**Comment by domsch1988** [comment]
One and a half years later this is still a Problem.
25.0.2
Trying to paste from LibreOffice Calc on Debian Trixie, running Plasma under Wayland.
Pasting to Excel 365 in Browser first and then into DBeaver works.

**Comment by bytehoarder** [comment]
I had this issue exclusively with the `flatpak` version, after installing DBeaver with the official `snap` not only it runs much better in general but no issues whatsoever copy-pasting.
