### ISSUE TITLE
procedure description box

### ISSUE THREAD

**Issue by pocelka** [dbeaver/dbeaver#8130]
**Is your feature request related to a problem? Please describe.**
I'm using dbeaver with MySQL database. When procedure contains comment, this is displayed in "Description" during editing procedure. This box is however very small.

**Describe the solution you'd like**
It should be possible to resize description box with procedure description

**Describe alternatives you've considered**
Alternatively it could be pop-up to new window.

**Additional context**
It is very hard to read procedure description in that small box.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by LonwoLonwo** [comment]
Hello @pocelka 
as workaround you can use button "Hide" under "Description" field.
![2020-12-15_10h17_35](https://user-images.githubusercontent.com/45152336/102183467-f3355880-3ebe-11eb-9841-f734ac80b989.gif)
