### ISSUE TITLE
Oracle - Procedures and table triggers are missing

### ISSUE THREAD

**Issue by macolu** [dbeaver/dbeaver#8132]
#### System information: 
- Ubuntu 18.04 LTS
- DBeaver v7.0.0
- No extensions

#### Connection specification:
- Oracle Database 11g
- Oracle JDBC driver 18.3.0.0.0
- No proxies or SSH tunnels

#### Describe the problem you're observing:

All table triggers and procedures are missing. I can see them with other software (SQL Developer).

According to Query Manager, DBeavers looks for triggers in SYS.ALL_TRIGGERS. They are not listed in this table. However, they are listed in SYS.DBA_TRIGGERS. But it seems that DBeaver doesn't look there.

Same for procedures: they are missing from SYS.ALL_PROCEDURES, but they are visible in SYS.DBA_PROCEDURES.

These triggers/procedures are not in the schema of the user I'm logged with.

Here are a few info about logged user, in case it helps:

`SELECT * FROM USER_SYS_PRIVS;`

Returns:

USERNAME|PRIVILEGE            |ADMIN_OPTION|
--------|---------------------|------------|
xxxxxx  |SELECT ANY DICTIONARY|NO          |
xxxxxx  |SELECT ANY TABLE     |NO          |
xxxxxx  |UNLIMITED TABLESPACE |NO          |`

Thanks

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
It is not a bug, you can force DBA_ views usage:
![image](https://user-images.githubusercontent.com/6398845/80088399-2197a980-8565-11ea-9f62-a3b2956b3105.png)

**Comment by macolu** [comment]
Oh, I missed this settings. My bad.
It fixes my issue, thanks!

**Comment by antonio-petricca** [comment]
This option should be the default!!!
