### ISSUE TITLE
[PostgreSQL] Granting schema generates grant table <schema_name>.<schema_name> query

### ISSUE THREAD

**Issue by Vlczech** [dbeaver/dbeaver#8134]
#### System information: 
- Operating system (distribution) and version: Windows 10 x64
- DBeaver version: 7.0
- Additional extensions: -

#### Connection specification:
- Database name and version: PgSQL 11.7
- Driver name: PgSQL JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Open user under <some database> - Roles - <specific user>. Under permissions tab, select some schema and for example usage permissions and save it. It generates this BUGGED query:
GRANT USAGE ON **TABLE** test **.test** TO someuser;

instead of right query:
GRANT USAGE ON **SCHEMA test** TO someuser;

#### Steps to reproduce, if exist:
...see above...

#### Include any warning/errors/backtraces from the logs

![obrazek](https://user-images.githubusercontent.com/10884140/76217931-9ca23c00-6213-11ea-8e49-021a411f6c10.png)

**Comment by uslss** [comment]
Permissions aren't saved after its changing. Ticket reopened.
![2020-03-16_11h37_45](https://user-images.githubusercontent.com/31996417/76738352-84826d80-677b-11ea-9d39-0de883f92e08.gif)

**Comment by Vlczech** [comment]
@uslss: Yes, but this is another bug (created #8197), which does not obtain properly granted information for schema - thus schema is not bold same as checkboxes are not properly checked...

See `dn+` in `psql` or `SELECT * FROM pg_namespace;`

```
test=# \dn+
                            Seznam schémat
   Jméno    | Vlastník |   Přístupová práva   |         Popis
------------+----------+----------------------+------------------------
 public     | postgres | postgres=UC/postgres+| standard public schema
            |          | =UC/postgres         |
 testschema | vlczech  | vlczech=UC/vlczech  +|
            |          | testrole=UC/vlczech  |
(2 rows)
```

_(On `testrole` was granted `testschema` to create and usage by me (=> there is correct entry **testrole=UC/vlczech**) via DBeaver)_

**Comment by serge-rider** [comment]
@Vlczech you are right

**Comment by uslss** [comment]
verified
