### ISSUE TITLE
Inserting a template with the  variable ${schema} fails in 7.0

### ISSUE THREAD

**Issue by Moridin11** [dbeaver/dbeaver#8135]
#### System information: 
- Operating system (distribution) and version  --> Windows 10
- DBeaver version --> 7.0

#### Connection specification:
- Database name and version -- PostGres
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When adding a template that references a ${schema} it fails with 'Resolve Object references] has encountered a problem java.lang.StackOverflowError

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
