### ISSUE TITLE
SELECT considered modifying statament in GUI

### ISSUE THREAD

**Issue by mireczatko** [dbeaver/dbeaver#8136]
#### System information: 
- Operating system (distribution) and version
ubuntu 19.10
- DBeaver version
7.0.0

#### Connection specification:
- oracle

#### Describe the problem you're observing:
not modifying SELECT statement considered as modifying. This was working pretty nice in previous version. It is annoying to rollback even SELECT statements...

#### Steps to reproduce, if exist:
run any SELECT (e.g. SELECT 'test' FROM dual;)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
It is not a bug.
See https://github.com/dbeaver/dbeaver/issues/8070#issuecomment-594469575
