### ISSUE TITLE
Duplicate list of fields 

### ISSUE THREAD

**Issue by mcunha98** [dbeaver/dbeaver#8138]
I'm working into a task about the creation of Virtual Foreign Keys (in my case, working on MariaDB and MyISAM Engine, so I cannot create logical FKs).

During the job, I notice the field list always load duplicated (nothing that a simple F5 resolve, but is good to check it).

![image](https://user-images.githubusercontent.com/6831010/76242775-fe63a580-6215-11ea-88e0-6be30d50f0a3.png)

I notice that happen when I go to ER Diagram (to check the Virtual FK creation) and back to properties window (or when I load another table)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by serge-rider** [comment]
I can't reproduce this anymore. 
Do you have any additional details/steps to reproduce?

**Comment by mcunha98** [comment]
Basically
1) Select a table
2) Properties / Virtual / Add
3) Go to ERDiagram
4) All fields will be listed duplicated (if you back to Properties / Columns will be duplicated too)

**Comment by uslss** [comment]
Still cannot reproduce it.
@mcunha98 is it still actual for you?

**Comment by mcunha98** [comment]
@uslss I did the steps again, everything works fine now.
DBeaver version  7.1.1.202006211844
