### ISSUE TITLE
DBeaver does not connect to secure CockroachDB cluster using SSH

### ISSUE THREAD

**Issue by florence-crl** [dbeaver/dbeaver#8139]
#### System information: 
- Operating system (distribution) and version: macOS Catalina 10.15.3
- DBeaver version: 7.0.0 (but also 5.2.5 and 6.3.4)
- Additional extensions

#### Connection specification:
- Database name and version: CockroachDB 20.1.0-beta.2 which uses go 1.12
- Driver name: CockroachDB JDBC driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
When connect with SSH, get following error:

```
extension (5) should not be presented in certificate_request
```

This error is also mentioned in this question issue: https://github.com/dbeaver/dbeaver/issues/7055
This error is probably due to this Go issue: https://github.com/golang/go/issues/35722
which says:
> As a workaround it is possible to disable TLS 1.3 on the JAVA client by setting -Djdk.tls.client.protocols=TLSv1.2

Issue 35722 is fixed in Go 1.14. Since CockroachDB 20.1 is not built with 1.14. DBeaver does not work with CockroachDB 20.1.0-beta2 and most likely will not work with the 20.1.0 release version coming up.

#### Steps to reproduce, if exist:
https://www.cockroachlabs.com/docs/stable/dbeaver.html

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
I can't reproduce this as I don't have such environment. 

If adding `-Djdk.tls.client.protocols=TLSv1.2` works then it can be added in dbeaver.ini.

I don;t know how we can fix it inside dbeaver..

**Comment by vy-ton** [comment]
@serge-rider For MacOS, where can I find `dbeaver.ini`?

**Comment by Nican** [comment]
I can confirm that adding `-Djdk.tls.client.protocols=TLSv1.2` fixed it for me on Windows.

**Comment by esaad** [comment]
@vy-ton - you can find it at  `/Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini`
