### ISSUE TITLE
Auto-sync connection with navigator is not working

### ISSUE THREAD

**Issue by mutigozel** [dbeaver/dbeaver#8140]
#### System information: 
- Windows 10 64Bit
- DBeaver EE 7.0.0

#### Connection specification:
- PostgreSQL
- PostgreSQL JDBC Driver - latest version
- Do tunnel / proxy / ssh ...

#### Describe the problem you're observing:

App Menu > SQL Editor > Auto-sync connection with navigator option is checked but does not work as the previous version.

In previous version the editor's active database and active schema catalog was automatically changed to my selection in navigator. This behavior is lost in this version. Is there an option to bring this behavior back?

**Comment by uslss** [comment]
thanks for the bug report

**Comment by mutigozel** [comment]
Thanks for solving it. 

This functionality is my main reason for choosing DBeaver over its competitors. If it is possible I would like you to add it pre-release quality checking. This feature sometimes goes away and returns for some version updates. I often find my self returning to prev version because of it.

Regards,

**Comment by Gungrave223** [comment]
Lol was just about to ask about this. I notice with v 7.0 the active connection would auto sync, but the schema would remain the default. Glad to see there is already a fix in.

**Comment by uslss** [comment]
Reopened.
In case, I choose schema in another (not current) Catalog without clicking at Catalog first, schema changes, but catalog stays the same - so we have incorrect combination.
Maybe not a bug, but n mysql, in case of choosing table from some db without clicking at it - default schema is shown at toolbar. 
![2020-03-12_16h00_08](https://user-images.githubusercontent.com/31996417/76525029-26ecd900-647c-11ea-806c-e1ae0fbf4505.gif)

**Comment by uslss** [comment]
verified

**Comment by mutigozel** [comment]
I tried 7.1 Early Access, It does switch the connection in editor in sync with with database navigator but does not highlight ( making bold ) the selected entry in navigator. FYI

**Comment by nacesprin** [comment]
What auto-sync with navigator does exactly?
