### ISSUE TITLE
Domains and enums in column type combobox

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#8142]
- Operating system (distribution) and version: Ubuntu 19
- DBeaver version: 7.0
- Additional extensions: No

- Database name and version: PostgreSQL 12
- Driver name: standard
- Do you use tunnels or proxies (SSH, SOCKS, etc): No

There's no domains and enums in column type combobox - see attached picture.

![dbeaver_domains](https://user-images.githubusercontent.com/11477081/76288536-fb20f600-62b7-11ea-9f9d-f3f9f23b0123.png)

**Comment by uslss** [comment]
it has not been implemented yet.
thanks for suggestion

**Comment by uslss** [comment]
already implemented
![image](https://user-images.githubusercontent.com/31996417/111149998-9cfbb280-859e-11eb-8374-3223a4dd1bb2.png)
