### ISSUE TITLE
Unreadable Oracle schema names in Schema list

### ISSUE THREAD

**Issue by timgabets** [dbeaver/dbeaver#8146]
#### System information: 
- macOS Catalina version 10.15.3
- DBeaver Version 6.3.4.202002011957
- No additional extensions

#### Connection specification:
- Oracle 18.4
- Driver name: Oracle JDBC driver
- No SSH/SOCKS/proxies to connect to the database ? 

#### Describe the problem you're observing:
The Schema list contains cryptic names like '? 1001079851', not the schema names:
<img width="395" alt="Screenshot 2020-03-10 at 16 15 47" src="https://user-images.githubusercontent.com/1743663/76315926-b19dce80-62ea-11ea-89b0-8ddeb5b584dc.png">

#### Steps to reproduce, if exist:
Select Oracle database -> Schemas.

**Comment by majkyyx** [comment]
![image](https://user-images.githubusercontent.com/14957734/77762802-5bdf5b00-703a-11ea-9c17-371f23d2b07a.png)

I have same problem, only on oracle 18 + . (on oracle 12c i don't have any problems)

Maybe it's bacause in oracle 18 is new user named: **XS$NULL**, special char **$** is new - but it's only theory. 

dbeaver version: Dbeaver 7.0.1 
ojdbc: ojdbc10.jar (i tried 8 too, same problem)
oracle client: 19.5.0.0
os:
```
            .-/+oossssoo+/-.               majkyyx@hoze-t470s 
        `:+ssssssssssssssssss+:`           ------------------ 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.4 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 20HF0047MC ThinkPad T470s 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.3.0-40-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 10 days, 4 hours, 5 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2828 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.20 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080, 1920x1080, 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Budgie 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter(Budgie) 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Ant [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Papirus-Light [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: terminator 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel i7-7500U (4) @ 3.500GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: Intel HD Graphics 620 
    .ossssssssssssssssssdMMMNysssso.       Memory: 15032MiB / 15777MiB 
      -+sssssssssssssssssyyyssss+- 
        `:+ssssssssssssssssss+:`                                   
            .-/+oossssoo+/-. 
```

**Comment by majkyyx** [comment]
YES, i have **workaround!!**. It's problem with combination oracle 18up and ojdbc8.jar or ojdbc10.jar.

**Use ojdbc7.jar** (its for 12c, here: https://www.oracle.com/database/technologies/jdbc-drivers-12c-downloads.html), and ist's works fine. 

In this situation i don't now it's problem with oracle ojdbc driver or dbeaver. But if i user ojdbc10.jar in sqldeveloper, its works too.

**Comment by timgabets** [comment]
I've just updated DBEAVER to Version 7.0.1.202003211804 (Release 23.03.2020), and the problem is gone - all the schemas in a list are displyed with their proper names.

**Comment by majkyyx** [comment]
![image](https://user-images.githubusercontent.com/14957734/78329628-883b3000-7582-11ea-8813-c9248cfd7a32.png)

I'm sorry, but It's not true... same version with ojdbc10.jar (same with 8) 

Try it yourself
![image](https://user-images.githubusercontent.com/14957734/78330043-5d9da700-7583-11ea-88e8-2ffe00f836f6.png)

In this archive are both ojdbc drivers 8 and 10.
[ojdbc10-full.tar.gz](https://github.com/dbeaver/dbeaver/files/4425331/ojdbc10-full.tar.gz)

**Comment by majkyyx** [comment]
And there is screen with ojdbc7.jar

![image](https://user-images.githubusercontent.com/14957734/78330157-9fc6e880-7583-11ea-81b3-7dfe9d550c66.png)

**Comment by gaiguodonfbu** [comment]
just try to put all jars from here(https://www.oracle.com/database/technologies/appdev/jdbc-drivers-archive.html) as following, then it works for me, my dbeaver version is ce-23.0.3
![image](https://user-images.githubusercontent.com/43609169/234596259-3c5c5194-5d28-4512-b739-3344a60bb0bd.png)
![image](https://user-images.githubusercontent.com/43609169/234596584-d4c0199c-cc89-4696-b3ad-466da70cb00d.png)

**Comment by rahidzeynal** [comment]
Hello guys,
I had same problem with Oracle 9i version while connecting via DBeaver 23.1.1. I just changed driver to ojdbc7.jar and it fixed my problem.
Thank U @majkyyx 👍

**Comment by majkyyx** [comment]
> Hello guys, I had same problem with Oracle 9i version while connecting via DBeaver 23.1.1. I just changed driver to ojdbc7.jar and it fixed my problem. Thank U @majkyyx 👍

Try "ojdbc11.jar" for oracle 21c - it's back compatible with older versions of oracle and work with every version i think.

**Comment by rahidzeynal** [comment]
Tried but doesn't work with "ojdbc11.jar" for oracle 21c.

![image](https://github.com/dbeaver/dbeaver/assets/44039543/4ca47d34-c9d2-4e63-981e-ae2b85faf094)

**Comment by majkyyx** [comment]
https://www.oracle.com/cz/database/technologies/appdev/jdbc-downloads.html

It's last released odbc driver from oracle.


Try switch drivers from local libraries to online rep.:

![image](https://github.com/dbeaver/dbeaver/assets/14957734/092c9eae-b14b-4f9b-9d45-b542b90e7e26)


If this will not help, i really don't know what to do :-D
