### ISSUE TITLE
Can't delete postgres polygon record via GUI

### ISSUE THREAD

**Issue by mickeyjf** [dbeaver/dbeaver#8147]
DBeaver Version 7.0.0.202002292132, Postgres 11, Debian 9.

I have a postgres table that has an integer id column and a column of postgres data type polygons. If I attempt to delete a record using the GUI, I get this error:

SQL Error [42883]: ERROR: operator does not exist: polygon = polygon
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.

I am able to truncate the table via SQL. 
I am able to delete individual records via SQL : "DELETE FROM table-name WHERE id = blah..." 
However, selecting a row, clicking the 'delete' icon at the bottom of the page, then the 'save' icon brings up the above error and the record is not deleted.

CREATE TABLE v5facility.location_polygons (
	location_id int8 NULL,
	cad_handle text NULL,
	polygon polygon NULL,
	CONSTRAINT location_polygons_un UNIQUE (location_id)
);

**Comment by Vlczech** [comment]
@mickeyjf: Show your create table script

**Comment by uslss** [comment]
@mickeyjf could you provide some insert statement with example of data you use?

**Comment by uslss** [comment]
cannot reproduce an issue. if it is still actual for you - feel free to reopen the ticket

**Comment by kyanokashi** [comment]
I have the same issue
