### ISSUE TITLE
Extend single record view grid

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#8148]
Hi!
Here is a pic from oracle PLSQL developer. The idea is to extend single record view - now it has only 2 columns and there is a place for some useful metadate column - comment, type.

![dbeaver_single_record_view](https://user-images.githubusercontent.com/11477081/76323157-60dfa300-62f5-11ea-840e-cdaec4deff8e.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
Will be implemented in #7014
