### ISSUE TITLE
[BUG-postgresql] DBeaver always grants "execute on function" to schema public (even when schema public does ont exists)

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#8149]
This is a big security issue guys... :-)
In every function, when getting the permissions (Please see feature request [6948](https://github.com/dbeaver/dbeaver/issues/6948)  ), i always see a `grant execute on .... to public;`
Funny thing is: i never gave those grant.
Funnyer thing is: i dropped schema/role `public` from my DB

**Comment by serge-rider** [comment]
I can't reproduce this.
DBeaver gets proc grants information from pg_proc.proacl.

By default each PG tables/procedure owner have ALL permissions on this object. Check what role owns your procedure (proowner).
