### ISSUE TITLE
How to connect to SQL Azure with Azure Active Directory Login with Multi-Factor-Authentication

### ISSUE THREAD

**Issue by Sally-Xu** [dbeaver/dbeaver#8150]
Hi, I'm trying to connect SQL Azure with ADD-password authentication. but got "Failed to authenticate the user"  error because we use two-factor authentication. 

I also tried to use ADD-Integrated authentication method, got "KrbException: Cannot locate default realm" error.

How do we connect to SQL Azure with 2-factor authentication?

**Comment by MikeB2019x** [comment]
Hi Sally-Xu.  I have the same question and it looks like issue #8128 will be addressing it.  Basically this is a 'feature request' so nothing exists yet.

**Comment by uslss** [comment]
seems to be duplcate of #5754 .
ticket closed
