### ISSUE TITLE
[PostgreSQL, ...]: Refreshing data after save (commit)

### ISSUE THREAD

**Issue by Vlczech** [dbeaver/dbeaver#8155]
#### System information: 
- Operating system (distribution) and version: Windows 10 x64
- DBeaver version: 7.0
- Additional extensions: -

#### Connection specification:
- Database name and version: PostgreSQL 11.7
- Driver name: PostgreSQL JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Data in table editor should be selected /refreshed from table after it was saved, otherwise the added / generated values (for example generated values by function, serials, other specified default values ) values remain empty until enforced by manual refresh.

#### Steps to reproduce, if exist:
..follows from the previous..

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
already implemented
