### ISSUE TITLE
The problem when using the ksql-jdbc-driver

### ISSUE THREAD

**Issue by samyujialiu** [dbeaver/dbeaver#8156]
#### System information: 
- Operating system (distribution) and version
- DBeaver version

#### Connection specification:
- Database name and version
KSQL-jdbc-driver to access to Kafka  Dbeaver 7.0.0 
#### Describe your question:
Hi, we are just trying to connect to Kafka stream or tables through ksql-jdbc-driver. But there are some problms:  select command cant ends and cant see tables.Hope you can help us to fix that .Thanks a lot 
![image](https://user-images.githubusercontent.com/28554109/76369972-47dcfd80-639a-11ea-8532-17c331cfd0bc.png)

![image](https://user-images.githubusercontent.com/28554109/76369986-53c8bf80-639a-11ea-91e4-64a866b73f12.png)

**Comment by uslss** [comment]
@samyujialiu ,
kafka isn't supported by dbeaver yet.
Also it seems that mentioned issues are driver issues.
