### ISSUE TITLE
Add a button to "save changes dialog"

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#8158]
... as shown in the picture. The main idea - to shorten scenario with "copy".
Now we should "copy", then find (or open new) sql window, then "paste".
Maybe it could be suitable to add an option to change behaviour of "copy" button (copy to clipboard or copy to new sql window) - in the options dialog.
![dbeaver_new_button](https://user-images.githubusercontent.com/11477081/76394940-5c63ca80-6387-11ea-9965-0b9447722d99.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
Done

**Comment by kseniiaguzeeva** [comment]
Verified
