### ISSUE TITLE
Data Presentation can't be changed in Data Editor for nested attributes

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8159]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.0

#### Connection specification:
- Database name and version DynamoDB

#### Describe the problem you're observing:
Data Presentation couldn't be changed in Data Editor. 
![2020-03-11_11h05_32](https://user-images.githubusercontent.com/31996417/76395399-4b678900-6388-11ea-901f-342bfb8e1ab7.gif)

**Comment by serge-rider** [comment]
This is not just about DynamoDB but about any "nested" columns. And it is true for all document-based databases.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
