### ISSUE TITLE
driver proxy somehow used for database connection

### ISSUE THREAD

**Issue by wumpz** [dbeaver/dbeaver#8162]
Using dbeaver 6.5.3 we needed to download the database driver (PostgreSQL) via proxy. This worked.

Now we configured a database connection to this database without specified "using proxy". Therefore we assumed that this one will try to connect directly with the database. This does not work.

Now we removed the proxy settings from  our general settings. 

Without this "global" proxy setting the connection to the database worked.

**Comment by kseniiaguzeeva** [comment]
I'm not sure I understood you clearly enough. Please tell what expected result you would like to see.
Can you also write steps to reproduce?

**Comment by wumpz** [comment]
IMHO the expected result would be that there is no proxy used for the database connection if I didn't configured one in the connection but have configured a global one for plugin downloads.

**Comment by wumpz** [comment]
Strange that you are unable to reproduce it. Maybe a users error.

**Comment by kseniiaguzeeva** [comment]
Sorry for the long answer. Where do you set global Proxy?
It can be done here:
Preferences>DBeaver>Drivers
Preferences>General>Network connections.

**Comment by wumpz** [comment]
I set it for the driver download settings and not global. But it was used for the database connection itself. 
But maybe I am mistaken and set it globally instead.

**Comment by uslss** [comment]
@wumpz is it still actual for you?

**Comment by wumpz** [comment]
Since then it did not happened again. So I assume my fault. Sorry.
