### ISSUE TITLE
DBCException when handling bit type

### ISSUE THREAD

**Issue by VoidSignal** [dbeaver/dbeaver#8163]
#### System information: 
- Xubuntu 19.10
- DBeaver 7.0
- No additional extensions

#### Connection specification:
- Greenplum 5.22
- org.postgresql:postgresql:RELEASE [42.2.11]
- No proxies

#### Describe the problem you're observing:
There is an issue with handling PostgreSQL bit type. I'm not sure whether it's the driver or DBeaver. When bit string is long enough I get this error as query result:

```
DBCException: SQL Error [22003]: Bad value for type byte : 1111
```

I cannot reproduce this error when connecting with psql.

#### Steps to reproduce, if exist:

```SQL
SELECT B'1111';
```
There are no messages in log.

**Comment by VoidSignal** [comment]
@uslss I've just tried it on real PostgreSQL (not GP) and the error isn't present. I can only trigger it in GP.

**Comment by serge-rider** [comment]
It is not reproducible on GP 6+ too
