### ISSUE TITLE
Not GIS view anywhere

### ISSUE THREAD

**Issue by jtiai** [dbeaver/dbeaver#8164]
#### System information: 

DBeaver 7.0.0

#### Connection specification:

Oracle 11g + 12c

#### Describe your question:

DBeaver 7.0.0 was promoted with GIS editor and Oracle is supported but can't find it anywhere even my tables do contain spatial data (SDO_GEOMETRY fields)

**Comment by uslss** [comment]
Hi @jtiai ,
It is supported in EE version only

**Comment by jtiai** [comment]
I tried to find any information about this being EE only but there is no mention of that in 7.0.0 release notes (is there even 7.0.0 EE released on March 2nd?), Same for wiki help pages. They list some options to be EE only but there are no markers nor text in help page that would indicate GIS being EE only feature.
