### ISSUE TITLE
CTRL+Z undo too many changes

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#8165]
When I write `prd.inte` and select `interval` by pressing ENTER I got

    prd."interval"

But I do not need quotes. I press CTRL+Z and get again `prd.inte`

Here two changes:

      prd.interval
      prd."interval"  -- quotes are added by editor

So I expect `prd.interval` instead of `prd.inte` when press CTRL+Z

**Comment by uslss** [comment]
thanks for the bug report

**Comment by pyrocks** [comment]
This is somewhat similar to #7730

**Comment by KES777** [comment]
yes, it is similar. Vote up there.
