### ISSUE TITLE
Right click on breadcrumb buttons should show the same menu as right click on the corresponding node in the navigation tree

### ISSUE THREAD

**Issue by ddekany** [dbeaver/dbeaver#8166]
When you open a database object (like a table), there's a "bread crumbs" above it. Right clicking on nodes there should should bring up the same context menu as right clicking the same node in the navigation tree.

*Why is it useful?*

In many real world data bases the navigation tree is quite useless for opening tables, views, etc. There's hundreds of them per schema, and dozens of schemas, not to mention synonyms, etc. So you use "Open Datadase Object", type the table name, see the hits, open the database object. However, without the tree showing the object as well, you have nothing to right click on in the navigation tree, so the database object operations there (generate DDL, etc.) are unavailable. One workaround that I tried is to click "Link with editor". Other than it would be needless extra mouse movement and clicking, my main problem is that for me, that button often has no effect for some reason. But that's a completely different issue from this one, and building on that would be just a workaround anyway.

It's also a pretty standard convention in IDE-s, I think.

**Comment by serge-rider** [comment]
Good point

**Comment by serge-rider** [comment]
Done. Context menu is similar to navigator context menu.
@uslss please test it on Linux.

**Comment by uslss** [comment]
Reopened.
Ubuntu 19.04:
Context menu isn't shown for current item. If table is opened, context menu for it isn't shown
![image](https://user-images.githubusercontent.com/31996417/78040303-e942e800-7377-11ea-9afb-cbc4ef2126a5.png)

**Comment by serge-rider** [comment]
It is GTK-specific behavior (no context menu for disabled elements)

**Comment by uslss** [comment]
verified
