### ISSUE TITLE
[Vertica] Invalid sql stmt for meta-function when "Use SQL to limit fetch size" is enabled

### ISSUE THREAD

**Issue by denissk** [dbeaver/dbeaver#8167]
Connection Type: Vertica

Execution of [Vertica meta-functions](https://www.vertica.com/docs/9.3.x/HTML/Content/Authoring/SQLReferenceManual/Functions/VerticaFunctions/VerticaMeta-functions.htm) fails when "Use SQL to limit fetch size" is enabled. Queries with meta-functions cannot contain other clauses, such as FROM, WHERE or LIMIT.

Example:
`SELECT CLOSE_ALL_SESSIONS()` is executed as `SELECT CLOSE_ALL_SESSIONS() LIMIT 200` causing:

`SQL Error [5297] [0A000]: [Vertica][VJDBC](5297) ERROR: Unsupported use of LIMIT/OFFSET clause`

Thank you for the great tool!

**Comment by uslss** [comment]
thanks for the bug report

**Comment by vityank** [comment]
Added pull request #11787 for this issue

**Comment by serge-rider** [comment]
Fixed.

@vityank After all I've decided to make new limit transformer specifically for Vertica. See 0d654fd21696ecaa4e5b70c684bb99ecd96cf989 .
I partially used code from your PR, thank you for the contribution.

**Comment by vityank** [comment]
Great.
Thanks.

**Comment by uslss** [comment]
verified
