### ISSUE TITLE
can't create database with encoding through UI

### ISSUE THREAD

**Issue by ADeeeee** [dbeaver/dbeaver#8168]
#### System information: 
- Operating system (distribution) and version
Windows 10 1909
- DBeaver version
7.0.0 latest release

#### Connection specification:
- Database name and version
PostgreSQL 9.3.6
#### Describe your question:
There is no options in "encoding". What should I do besides creating DB with SQL query in editor?
![image](https://user-images.githubusercontent.com/35981633/76486204-a321f500-6459-11ea-9f00-99507dc9be2e.png)

**Comment by kseniiaguzeeva** [comment]
Looks like a bug.

**Comment by ADeeeee** [comment]
Back here now with an upgraded version 7.1.0 of DBeaver. Tried with two different Server of PostgreSQL 9 and it's the same. 

You can see the default encoding is N/A for an exsit database with UTF-8 or SQL_ASCII.
![image](https://user-images.githubusercontent.com/35981633/87532615-ffc24480-c6c5-11ea-9033-f2ffe71f4238.png)

The encoding page in system info is totally empty as below.
![image](https://user-images.githubusercontent.com/35981633/87532789-3b5d0e80-c6c6-11ea-909c-61a085ae9b83.png)

I have to particularly use PgAdmin III or use SQL query for creating new databases on the servers of PostgreSQL 9 so far. Any progress would be really appreciated. Please let me know if you need any information.

**Comment by kseniiaguzeeva** [comment]
Thank you for the additional comment. We are going to fix it.

**Comment by serge-rider** [comment]
@ADeeeee coudl you execute query 
`SELECT c.contoencoding as encid,pg_catalog.pg_encoding_to_char(c.contoencoding) as encname` in SQL editor? Are there any encoding returned?
Also please check error log for any related errors (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by ADeeeee** [comment]
@serge-rider 
Pardon me for delay reply. Here is it:

1. I tried to query it in SQL editor in database postgres, which shows and so does the pgAdmin III and psql:

```sql
SQL Error [42P01]: ERROR: missing FROM-clause entry for table "c" Position: 8
```

I'm not sure it's normal or not for PostgreSQL 9. Mine is default on a Synology device. 

2. There's no related error log in DBeaver.

**Comment by serge-rider** [comment]
Sorry, wrong query, it has to be

```sql
SELECT c.contoencoding as encid,pg_catalog.pg_encoding_to_char(c.contoencoding) as encname
FROM pg_catalog.pg_conversion c
GROUP BY c.contoencoding
ORDER BY 2
```

**Comment by ADeeeee** [comment]
Got it and tried. The PostgreSQL 9 runing in docker is doing well with this query which shows all the encoding list, but not for the one in Synology devices (empty at all).

Question: 
So why does the pgAdmin shows the correct encoding if the data doesn't exist at all? Is there another way to get it?

**Comment by LonwoLonwo** [comment]
Hello @ADeeeee 

Does this issue still actual for you? I can't reproduce it in the latest DBeaver versions.

**Comment by ADeeeee** [comment]
Thanks for the reply. Unfortunately yes with DBeaver 23.0.4.

The main issue is that there's no such data in the PGDB on Synology devices, so the client couldn't get the information correctly. 

It's not a general issue for DBeaver, however I'm just wondering why pgAdmin can get it and perhaps DBeaver could just do the same thing. It's okay if no plans for surveying, you could close this issue at anytime.

BTW, I'm really surprised that this issue is still on the list and appreciated for the reply.

**Comment by LonwoLonwo** [comment]
Probably PGAdmin uses the list of default encodings. But we can't do it, unfortunately, because our code works not only with Postgres but also with its forks. 

Does the query `select * from pg_catalog.pg_conversion` also return nothing in your case?

**Comment by ADeeeee** [comment]
> Does the query select * from pg_catalog.pg_conversion also return nothing in your case?

Yes, it's empty. NVM, we could just forget it. Thanks for the investigation.
