### ISSUE TITLE
drop and add primary key bug

### ISSUE THREAD

**Issue by xfzhaoxd** [dbeaver/dbeaver#8169]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- SQLServer 2018
- Microsoft SQL Server JDBC 
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
 I open table and drop unique key successfully,then I add unique key with the same name，dbeaver was not successful，get the message:'contains the name constraint'

I stop connection and reconnect，add unique key successfully with the same same.

**Comment by xfzhaoxd** [comment]
dbeaver version 7.0，windows 10

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
