### ISSUE TITLE
Inacurate domains metadata

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#8170]
#### System information: 
- Operating system (distribution) and version: ubuntu 19
- DBeaver version: 7.0.0

#### Connection specification:
- Database name and version: PostgreSQL 12

#### Describe the problem you're observing:

Inacurate domains metadata - size of varchar is missing, see pic
![dbeaver_domain_metadata](https://user-images.githubusercontent.com/11477081/76495999-238c2a00-6449-11ea-9aa8-8ce991d53ef7.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed (now we read base type full name using `format_type`

**Comment by uslss** [comment]
verified
