### ISSUE TITLE
[ERD] Tables are shown incorrectly if they are resized and then arranged

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8172]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.1 EA
#### Steps to reproduce, if exist:
1. Open any ERD
2. Change table size to smaller
3. Arrange diagram - Problem is solved after refreshing
![2020-03-12_15h35_04](https://user-images.githubusercontent.com/31996417/76522781-3cf89a80-6478-11ea-92ec-a4c2940badb6.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
