### ISSUE TITLE
When editing descriptions with MS SQL should generate as `schema` where `user` is

### ISSUE THREAD

**Issue by esanfordwss** [dbeaver/dbeaver#8174]
#### System information: 
- Operating system:  Windows 10
- DBeaver version:   DBeaver IDE 7.0.0.202003021717 in Eclipse 2019-12 (4.14.0)
- Java version: 1.8 151 
- Additional extensions: plenty - not relevant though 

#### Connection specification:
- Database name and version: 
   Microsoft SQL Server 2016 (SP2-CU11) (KB4527378) - 13.0.5598.27 (X64) 
	Nov 27 2019 18:09:22 
	Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 x64 (Build 14393)

- Driver name: com.microsoft.sqlserver.jdbc.SQLServerDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
When saving changes to descriptions, DBeaver still uses 
```
EXEC Clarkitbiz.sys.sp_addextendedproperty 'MS_Description', 'descriptive test', 'user', 'scheamaName', 'table', 'tableName', 'column', 'columnName'
```
When should be
```
EXEC Clarkitbiz.sys.sp_addextendedproperty 'MS_Description', 'descriptive test', 'schema', 'scheamaName', 'table', 'tableName', 'column', 'columnName'
```

#### Steps to reproduce, if exist:

- Enter text into column table or proc description field
- Choose to save changes
- Copy/paste generated SQL

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed 
https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-addextendedproperty-transact-sql?view=sql-server-ver15#schema-vs-user

**Comment by kseniiaguzeeva** [comment]
verified
