### ISSUE TITLE
Missing filter history in result table

### ISSUE THREAD

**Issue by Lheana** [dbeaver/dbeaver#8178]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 7.0.0
- Additional extensions: None

#### Connection specification:
- Database name and version: MySQL
- Driver name: jdbc:mysql

#### Describe the problem you're observing:
Since few versions DBeaver no more proposes filter history in the filter dropdown list, on top of the result table.

#### Steps to reproduce, if exist:
Simply open table data from database navigator, perform a filter then open filter dropdown list.

![image](https://user-images.githubusercontent.com/11537611/76567339-d04cc280-64ae-11ea-84d6-49e1537f546b.png)

(Sorry if the english is not perfect)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D74](https://dbeaver.testquality.com/project/8805/result/1906224/defect/6486). Do not remove or edit.

**Comment by serge-rider** [comment]
Fixed

**Comment by serge-rider** [comment]
Note: this bug is reproducible only if your query has line feeds or comments inside.

**Comment by uslss** [comment]
verified
