### ISSUE TITLE
Broken GUI with missing data

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#8182]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.0.0
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle 18c
- Driver name: ojdbc8.jar (from instantclient 19.5)
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:

Just look at this screenshot:

![obraz](https://user-images.githubusercontent.com/20753183/76623910-9a522180-6534-11ea-9bb9-82f7a31df0ca.png) 

Probably some libraries are missing. Is this some kind of incompatibility between OpenJDK and Oracle's jars?

#### Steps to reproduce, if exist:

Nothing very specific. Completely fresh Windows 10 installation.

**Comment by uslss** [comment]
cannot reproduce it against 7.0.5.
@maln0ir , is it sill actual for you?
sorry for the late response

**Comment by maln0ir** [comment]
Yes, I can reproduce it using newest instantclient (version 19.6) on DBeaver 7.0.5. Jars downloaded automatically (version 12.2) work correctly.

**Comment by serge-rider** [comment]
Still can't reproduce.
Some log files with errors/stacktraces would be super-helpful.
