### ISSUE TITLE
Aborting a slow query causes the connection to break

### ISSUE THREAD

**Issue by idlesysman** [dbeaver/dbeaver#8187]
#### System information: 
- Operating system (distribution) and version：win 10 X64
- DBeaver version:5.1.0
- Additional extensions:no

#### Connection specification:
- Database name and version：sql server 2012(sp1)
- Driver name:Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? :no

#### Describe the problem you're observing:

After aborting a slow query,the database connection was interrupted,i shoud reconnect  to database.

@tks

**Comment by uslss** [comment]
hi, @idlesysman ,
could you try more recent DBeaver version (7.0) and check if an issue is still reproducible?

**Comment by idlesysman** [comment]
it‘s ok on 7.0.1
