### ISSUE TITLE
Record count button

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#8188]
Take a look to IBExpert.
Can we do "record count" button for ourselves? Sometimes it is usable...
![dbeaver_ibexpert](https://user-images.githubusercontent.com/11477081/76678953-52db9c00-65ed-11ea-8330-e9d6eb1de28c.png)
![dbeaver_rec_count](https://user-images.githubusercontent.com/11477081/76678955-566f2300-65ed-11ea-83ea-fb9b0bffec81.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
this info is already available in the statistics tab
![image](https://user-images.githubusercontent.com/31996417/128181713-c99b2562-15b2-4932-b492-5a92e8c8e83f.png)
