### ISSUE TITLE
Wrong tab count message

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#8189]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.0.0

#### Connection specification:
- Database name and version: PostgreSQL 12

... as shown
![dbeaver_tab_count](https://user-images.githubusercontent.com/11477081/76679845-d3ea6180-65f4-11ea-92c3-30c0b7e7fa66.png)

**Comment by plotn** [comment]
and add "м" to "выполнениеМ" please :)

**Comment by plotn** [comment]
Maybe it would be better to change to: "Открытых вкладок с результатами запросов: 3"
instead of find word forms for "Открыто 3 вкладКИ"

**Comment by uslss** [comment]
thanks for the bug report.
also error appears when executing all statements in separate tabs. 
![image](https://user-images.githubusercontent.com/31996417/76742083-9b2bc300-6781-11ea-85de-10e5c59febd5.png)
"выполнить 3 запросы паралЛельно" sounds quite bad

**Comment by plotn** [comment]
Вы собираетесь выполнить несколько параллельных запросов (количество: 3)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
Verified
Related issue #8206
