### ISSUE TITLE
Import bug at 7.0.0 version

### ISSUE THREAD

**Issue by wvolkov** [dbeaver/dbeaver#8190]
#### System information: 
- Windows 10 Pro
- 7.0.0
- Git Extension

#### Connection specification:
- PostgreSQL 9

#### Describe the problem you're observing:
While importing .csv ([crash_smpl.zip](https://github.com/dbeaver/dbeaver/files/4334399/crash_smpl.zip)) to table with following DDL:
`CREATE TABLE rt.trusting_reconcilation (
	id numeric NULL,
	phone text NULL,
	bank_code text NULL,
	telco_score int4 NULL,
	created_at timestamp NULL
);`
I am getting error:
![dbeaver_7_import_crush](https://user-images.githubusercontent.com/49549154/76704012-27d57300-66e7-11ea-9a9f-69e946bcb566.png)
at version 7.0.0.

At version 6.2.3 import works fine.

#### Steps to reproduce, if exist:
1. Open table in left pallet (project viewer)
2. right-click -> import data
3. specidy .csv template from attachement 
4. error

**Comment by uslss** [comment]
hi,  @wvolkov ,
it seems that you try to import not a number value ("cash_wagon_contract") to the numeric column "telco_score".
You could try to change mapping of columns to proceed import
![image](https://user-images.githubusercontent.com/31996417/76741576-d4affe80-6780-11ea-83c4-1c623622d628.png)

**Comment by uslss** [comment]
there is no update on ticket more than a month. if issue is still actual for you - feel free to reopen the ticket
