### ISSUE TITLE
UTF8 Encoding Question

### ISSUE THREAD

**Issue by BobInCT** [dbeaver/dbeaver#8191]
#### System information: 
- Operating system (distribution) and version W-10 single user
- DBeaver version: 7.0.0.202003021717

#### Connection specification:
- Database name and version: Postgres version 15.x

**Comment by uslss** [comment]
hi, @BobInCT ,
could you post an example of query that returns the mentioned error?

**Comment by BobInCT** [comment]
Example:

select distinct type as Buyer_Seller_Carrier, R.Code, R.name as Company_Name, T.Person as Person, 
T.email as Email, T.Ship_mgr_phone as Phone, T.Emer_numbers as Emergency 
from wwrdex R 
join wwtrans T on T.parent_ID = r.ID and T.inactive <> '1' and 
	(T.Contract_auth = '1' or T.Dist_con = '1' or T.Ship_mgr = '1' or T.Dist_ship = '1' or Freight_Quote = '1' or T.Freight_Mgmt = '1') 
where (r.status = 'A' or rtrim(r.status) = '') and rtrim(T.email) <> '' 
Order by R.name;

**Comment by uslss** [comment]
could you provide ddl to create these tables?
sorry for the late response

**Comment by BobInCT** [comment]
I honestly don't think this will help because the problem is very intermittent and seems to be data related.  I can go for weeks without seeing the problem and then one record throws the error.  If I do the same query in Admin4 for the same record I get no error.  In fact I haven't seen the problem in the past couple of weeks, maybe something was changed that inadvertently fixed the problem?

**Comment by uslss** [comment]
Seems that issue was solved (Hope so :))
Ticket closed.
