### ISSUE TITLE
Documentation: List of supported DBs an versions.

### ISSUE THREAD

**Issue by skfd** [dbeaver/dbeaver#8192]
Could you please make a list of supported databases and minimal versions? Right now it just says 80+ and lists some flavours.

**Comment by serge-rider** [comment]
Partially you can see this list here: https://dbeaver.com/databases/ 

You can see all databases and drivers in the new connection wizard (first page, tab "All").

![image](https://user-images.githubusercontent.com/6398845/76756782-6e82a600-6797-11ea-8057-cd7cee219015.png)

**Comment by skfd** [comment]
Thank you, will try that!

I'm asking because I want to survey if it supports older Microsoft SQL Servers. It would be nice to document so people can see this without installing the product first.
