### ISSUE TITLE
A variable name is displayed above status bar during connection testing

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8195]
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 7.0.0

#### Describe the problem you're observing:
A variable name is displayed above status bar instead of real value during connection testing.
#### Steps to reproduce, if exist:

1. Open Connection settings>Main for a database
2. Enter a variable in Database field
3. Press "Test connection" btn

Actual result:
A variable name is displayed above status bar during connection testing.
Expected:
A real value is displayed above status bar during connection testing.

![CBDngIglYK](https://user-images.githubusercontent.com/51405061/76761523-9de9e080-67a0-11ea-92b9-9b1141b5e5c7.png)
![V0iW4DeldI](https://user-images.githubusercontent.com/51405061/76761535-a2ae9480-67a0-11ea-9b0f-e1d2002755ed.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
