### ISSUE TITLE
[PostgreSQL] Schema permissions is not shown properly

### ISSUE THREAD

**Issue by Vlczech** [dbeaver/dbeaver#8197]
#### System information: 
- Operating system (distribution) and version: Windows 10 x64
- DBeaver version: 7.0
- Additional extensions: -

#### Connection specification:
- Database name and version: PosgtreSQL 11.7
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Properly schema permissions obtaining by SQL: ` select * from pg_namespace [WHERE nspname = '<schemaname>'];`

#### Steps to reproduce, if exist:
![76738352-84826d80-677b-11ea-9d39-0de883f92e08 1](https://user-images.githubusercontent.com/10884140/76773515-e1dde500-67a2-11ea-9556-bab5c3708b58.gif)
( https://user-images.githubusercontent.com/31996417/76738352-84826d80-677b-11ea-9d39-0de883f92e08.gif by @uslss )

**Comment by serge-rider** [comment]
Fixed.

**Comment by uslss** [comment]
verified
