### ISSUE TITLE
MariaDb/mysql blob dump/export error since 6.3.1

### ISSUE THREAD

**Issue by urikjaro** [dbeaver/dbeaver#8198]
OS = Linux mint 19
version = 7.0.0 , also reported on 6.3.1
Additional extensions = No

db version= mysqld  Ver 10.1.44-MariaDB-0ubuntu0.18.04.1 for debian-linux-gnu on x86_64 (Ubuntu 18.04)
driver= MariaDB connector/J 1.5.5

I have just encountered a problem where all binary blobs are damaged after restoring a mariaDb dump. The dump was a plaintext, created also by dBeaver, version 6.3.0. I have just now migrated to v 7.0 and noticed that my program does not start. My colleague reported me similar behavior on 6.3.1. After downgrading to 6.3.0 it works.

fill db tables with some blobs (my case pdfs + png images), do db dump with version < 6.3.1.
Then restore with version 7.0.0

**Comment by serge-rider** [comment]
Fixed (indeed there was an issue with binary data ransfer)

**Comment by uslss** [comment]
verified
