### ISSUE TITLE
the hotkey to switch tabs

### ISSUE THREAD

**Issue by jyoisamu** [dbeaver/dbeaver#8199]
**Is your feature request related to a problem? Please describe.**
Right now I have to click to switch tabs.

**Describe the solution you'd like**
I want a hotkey to switch tabs.

**Describe alternatives you've considered**
I want to switch to the previous tab with Alt + W.

**Additional context**
I want to contribute a small idea to the growth of this software

**Comment by uslss** [comment]
Hi @jyoisamu ,
it is already implemented. You could use Ctrl+PgUp/PgDown by default to switch to the previous/next tab. You could assign keys you needed
![image](https://user-images.githubusercontent.com/31996417/76846520-abab6e80-6851-11ea-9cee-48e1fd933a48.png)

**Comment by jyoisamu** [comment]
Thank you.
