### ISSUE TITLE
Can't edit data in Data Editor for SQL connections

### ISSUE THREAD

**Issue by ajpuerta** [dbeaver/dbeaver#8201]
The problem that I explain in issue #7597 is still producing in latest release (7.0.0).

I'm available if you need some help to reproduce or if you need some logs.

**Comment by uslss** [comment]
hi, @ajpuerta ,
could you check if it is reproducible for you in EA version (https://dbeaver.io/files/ea/)?

**Comment by crapp** [comment]
I already mentioned in the other bug report that the problem still exists with the early access version

**Comment by ajpuerta** [comment]
As @crapp has said here, the problem still exists with the early access version

**Comment by kseniiaguzeeva** [comment]
Do you have steps to reproduce? I cannot reproduce issue  "database.schema.table it works, schema.table not" on the latest version any more.

**Comment by crapp** [comment]
But it should work without specifying a schema or database. So it has to be possible to edit the Dataset that you get by a simple query like this

`SELECT * from users;`

This works with version 6.3.0 and doesn't work with any later version including early access

**Comment by kseniiaguzeeva** [comment]
It works in 7.0.0 for me (pls see video).
![aGBnWwoskh](https://user-images.githubusercontent.com/51405061/77155976-77cd8480-6aaf-11ea-9545-e199d13aaec2.gif)
Is it only case where you meet the issue?

**Comment by crapp** [comment]
@kseniiaguzeeva Which SQL Server version and sql driver are you using? All my colleagues have the same problem. I tried with SQL Server 2016 Express and latest jdbc driver. 

Could  you tell my which version of DBEaver the about screen of your installation shows?

**Comment by kseniiaguzeeva** [comment]
I use the latest realease -  Dbeaver 7.0.0. SQL Server Express 2017.
Please tell which schema your tables in? And dbo? 
Which schema is active in DB Navigator tree?

**Comment by ajpuerta** [comment]
My tables are in imp schema and I connect with imp user. Conversely, the scheme active in DB Navigator tree is dbo@xxxxx

**Comment by kseniiaguzeeva** [comment]
Finally I caught it. Thank you!

_Steps:
1 Create a table "table_name" not in **dbo** schema.
2. Execute **select * from "schema_name"."table_name"** in SQL Editor._

![6eUdaCUR7Y](https://user-images.githubusercontent.com/51405061/77224281-28518c00-6b75-11ea-8ae3-2eaf30e1878f.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by crapp** [comment]
Ah yes sorry we were always talking about tables that are not in the dbo scheme. Great to hear that @serge-rider was able to fix this. I'll be happy to test  the fix on my machine whenever there is a new early access version. 

Thanks for your efforts and patience!

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by ajpuerta** [comment]
Thanks guys, it's working now with version 7.0.1
