### ISSUE TITLE
GIS / Map view not available on Oracle SDO_GEOMETRY fields

### ISSUE THREAD

**Issue by jtiai** [dbeaver/dbeaver#8202]
#### System information: 
- Windows 10 Pro
- DBeaver 7.0.0
- No additional plugins

#### Connection specification:
- Oracle 11g and Oracle 12c
- oracle.jdbc.OracleDriver (Standard oracle jdbc distribution)
- No proxies or tunnels

#### Describe the problem you're observing:

When selecting column that contains spatial information (MDSYS.SDO_GEOMETRY types) no map appears.

#### Steps to reproduce, if exist:

Create or pick table with spatial data and try to show value on map.

### Notes

This was first said to be EE only feature #8164 but it works with PostGIS db just fine.

Documentation on wiki page says that Oracle is supported: https://github.com/dbeaver/dbeaver/wiki/Working-with-Spatial-GIS-data#supported-databases

**Comment by uslss** [comment]
Hi @jtiai ,
unfortunately, it is available in EE version only

**Comment by jtiai** [comment]
What is available in EE only? Whole mapview? (If true, why it works in community edition and PostGIS) or Oracle and Mapview?

**Comment by serge-rider** [comment]
GIS support for Oracle is included in EE only. 
Oracle uses non-standard geometry type storage and it requires additional libraries.

CE version supports GIS data types for PostgreSQL, MySQL, HANA, Exasol, H2GIS.
EE version adds support of Oracle and SQL Server.

**Comment by jtiai** [comment]
Excellent. Thank you for information. Though I have used Oracle SDO_GEOMETRY type geometries through standard Oracle JDBC libraries (over 10 years ago) so I'm not sure what special it would require.
