### ISSUE TITLE
Connection deleted when dragged to new Project

### ISSUE THREAD

**Issue by knwpsk** [dbeaver/dbeaver#8205]
Had several Connections present in "General" project.  Wanted to organize them.
Created a new Project.
Dragged one Connection from General into New Project.
Connection disappeared from dBeaver completely.  No warnings/popups.

Repeated this with a second Connection, same thing happened again.

#### System information: 
Windows 10
dBeaver 7.0.0

#### Connection specification:
MySQL (both times)

**Comment by uslss** [comment]
hi @knwpsk,
cannot reproduce an issue (see gif attached). Probably, some special steps are required?
![2020-03-17_14h34_02](https://user-images.githubusercontent.com/31996417/76866853-c55ead00-6875-11ea-82ac-b7b376883bab.gif)

**Comment by knwpsk** [comment]
Hi @uslss 
In the "source" project, I had the connections in a folder.  Dragged them into top-level Connections folder in the "target" project.

Mine were MySQL connections, vs yours above is MariaDB.

I can't think of what else might be different...??

**Comment by knwpsk** [comment]
Dammit.
I found them.  Nevermind, and I'm sorry for the false alert!
You can close this ticket.
