### ISSUE TITLE
Counter shows incorrect value in SQL Editor

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8206]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.0.1 EA

#### Describe the problem you're observing:
Counter shows incorrect value in SQL Editor.
#### Steps to reproduce, if exist:
1. Open SQL Editor
2. Execute script (e.g. `select 1; select 2; select 3;` )using Alt+X - 3 tabs+ Statistic appears
3. Try to execute script once again - Confirmation pop-up appears. Number of unpinned tabs is incorrect. Probably value is number of open tabs+number of tabs that will be open
![image](https://user-images.githubusercontent.com/31996417/76870300-93037e80-687a-11ea-9d06-0ac57d158370.png)

**Comment by serge-rider** [comment]
Duplicate of #8189

**Comment by uslss** [comment]
Reopened. #8189 is about the incorrect translation to Russian.
This ticket is about Incorrect value in counter

**Comment by serge-rider** [comment]
Yep. It was a stupid typo.
Fixed

**Comment by uslss** [comment]
verified
