### ISSUE TITLE
Incorrect DDL after adding function for column Default.

### ISSUE THREAD

**Issue by busby666** [dbeaver/dbeaver#8207]
Running on Windows 10
MariaDB <not sure of the version right now>

Create Table as such
CREATE TABLE testing (
   stamp TIMESTAMP DEFAULT current_timestamp() NOT NULL,
   id varchar(35) NOT NULL DEFAULT MD5(stamp))
ENGINE=Aria TRANSACTIONAL=0 PAGE_CHECKSUM=1 DEFAULT CHARSET=utf32 COLLATE=utf32_general_ci;

When I am in DBeaver 7.0.0.2020... released on March 2 if I right click on the table and generate DDL I get this:
-- qualys.testing definition

CREATE TABLE `testing` (
  `stamp` timestamp NOT NULL DEFAULT current_timestamp(),
  `id` varchar(35) NOT NULL DEFAULT 

Not a huge issue but does cause some issues.
Please let me know if I can provide additional information.

**Comment by busby666** [comment]
Linux is 7 and Mariadb version is “10.4.8-MariaDB”

**Comment by uslss** [comment]
thanks for the bug report

**Comment by busby666** [comment]
> thanks for the bug report

Let me know if I can do anything?

**Comment by serge-rider** [comment]
WE can't fix this. 
We read table DDL from server (`show create table testing`). So this seems to be a MariaDB issue.
