### ISSUE TITLE
Oracle DROP PROCEDURE in script 

### ISSUE THREAD

**Issue by Pecaas** [dbeaver/dbeaver#8208]
DBeaver 7.0 , Oracle 19
Hi, this script end with error:  SQL Error [933] [42000]: ORA-00933: SQL command not properly ended. I am not abble to run it without this. 

CREATE OR REPLACE PROCEDURE XXX.GETSERIALREPORTITEM
 (ASERIAL OUT INTEGER)
AS
BEGIN
  SELECT XXX.REPORTITEMGENER.NEXTVAL INTO ASERIAL FROM DUAL;
END;

DROP PROCEDURE XXX.GETSERIALREPORTITEM;

**Comment by MaikMichel** [comment]
Did you try it with a trailing "/"?

CREATE OR REPLACE PROCEDURE XXX.GETSERIALREPORTITEM
(ASERIAL OUT INTEGER)
AS
BEGIN
SELECT XXX.REPORTITEMGENER.NEXTVAL INTO ASERIAL FROM DUAL;
END;
/

**Comment by p91paul** [comment]
dbeaver does not support sqlplus syntax, / is only going to make things worse!

**Comment by uslss** [comment]
thanks for the bug report

**Comment by maln0ir** [comment]
@p91paul DBeaver can be configured to use `/` as command delimiter and it works quite nicely for queries. It is certainly better than `;` or blank line in some situations.

**Comment by p91paul** [comment]
yes, unless you need to make a division in one of your queries :)

**Comment by Pecaas** [comment]
No DROP PROCEDURE does not work, even if you have configurued it with delimiter /. Another command works.

**Comment by serge-rider** [comment]
It was broken in #2590
Fixed.

**Comment by uslss** [comment]
verified
