### ISSUE TITLE
Horizontal scroll not full scrolled (using: Shift + MouseScroll)

### ISSUE THREAD

**Issue by erlangp** [dbeaver/dbeaver#8209]
#### System information: 
- Ubuntu 18.04.4 LTS `4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- DBeaver `7.0.0`

#### Connection specification:
- Database: MariaDB
- `127.0.0.1` localhost `3306`

#### Describe the problem you're observing:
Linux (Ubuntu): **bug**. Horizontal scroll not full scrolled (using: **Shift** + **MouseScroll**).
Windows: **normal**. No problem.

#### Steps to reproduce, if exist:
1. Open **Data** tab
2. Scroll horizontally using **Shift** + **MouseScroll**

**Comment by serge-rider** [comment]
Probably caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=491167

**Comment by uslss** [comment]
seems that issue is fixed

**Comment by superDuperCyberTechno** [comment]
Shift+scroll is still (again) borked in the results in v21.3.4.202202051448.

Both when accessing/browsing data directly from the database explorer and from SQL queries.
