### ISSUE TITLE
Saved data filter file sometimes contains quotes in column names

### ISSUE THREAD

**Issue by austin-beer** [dbeaver/dbeaver#8210]
#### System information: 
- Operating system (distribution) and version: Ubuntu 19.04
- DBeaver version: 7.0.0
- Additional extensions: N/A

#### Connection specification:
- Database name and version: PostgreSQL 10.6
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes

#### Describe the problem you're observing:

The `saved-data-filter.xml` file saves some column names with embedded quotes. This causes the saved filter settings to be ignored when the associated table is re-opened. Example:

```
<?xml version="1.0" encoding="UTF-8"?>
<data-filters>
	<filter objectId="SSA PostgreSQL as monics@@/@@rf@@/@@public@@/@@tdoafdoa" anyConstraint="false" order="primary_rx_time desc, primary_ant_id, secondary_ant_id" where="primary_rx_time &gt;= &#39;2020-03-17&#39;">
		<constraint name="rec_id" visible="false" pos="0" order="0"/>
		<constraint name="rec_timestamp" visible="false" pos="1" order="0"/>
		<constraint name="sat_id" pos="5" order="0"/>
		<constraint name="primary_ant_id" pos="6" order="0"/>
		<constraint name="secondary_ant_id" pos="7" order="0"/>
		<constraint name="primary_rx_time" pos="8" order="0"/>
		<constraint name="tdoa" pos="9" order="0"/>
		<constraint name="tdoa_dot" pos="11" order="0"/>
		<constraint name="&quot;valid&quot;" pos="15" order="0" criteria="= true"/>
	</filter>
</data-filters>
```
Note that the `valid` vield contains quotes in its name, even though the underlying database table name does not contain quotes. When I re-open this table the 'valid = true' criteria is ignored.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
We need to unquote column names on load.
Fixed.

**Comment by uslss** [comment]
verified
