### ISSUE TITLE
Multiple outputs in same Result grid

### ISSUE THREAD

**Issue by LRHF** [dbeaver/dbeaver#8212]
In both SSMS and SqlDbx I am able to see multiple outputs in the same Result grid. In DBeaver I cannot. I would like to have this option. I know there is a workaround splitting the window, but it's not practical for 3 or more queries. Thanks!

Example in SSMS:
![image](https://user-images.githubusercontent.com/22406500/76916384-23969900-6925-11ea-8c79-b181a91a9f89.png)

Example is SqlDbx:
![image](https://user-images.githubusercontent.com/22406500/76916393-28f3e380-6925-11ea-87cb-ae33def4c717.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
duplicates #6328
