### ISSUE TITLE
Can't read tables

### ISSUE THREAD

**Issue by zhouyang1017** [dbeaver/dbeaver#8215]
#### System information: 
- Operating system (distribution) and version 
     **windows 10**
- DBeaver version 
  6.2.4
#### Connection specification:
- Database name and version
   **Oracle Database 10g Enterprise Edition Release 10.2.0.1.0**
#### Describe your question:
**An error occurred when I wanted to open the table view**
![1584523292(1)](https://user-images.githubusercontent.com/28047230/76945125-14234a00-693d-11ea-8b8b-fafa9829b054.jpg)

**Comment by kseniiaguzeeva** [comment]
Unfortunately cannot reproduce on the latest version 7.0.0.
Could you please write steps to reproduce if it happens in special cases or try download 7.0.0 https://dbeaver.io/download/

**Comment by uslss** [comment]
there is no updates on ticket for more than a month.
Issue closed. If it is still reproducible for you - feel free to reopen the ticket with additional info that could be helpful for issue reproducing
