### ISSUE TITLE
[SQL Server] driver must be updated every time DBeaver starts

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8217]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.0

#### Connection specification:
- Database name and version SQL Server
- Driver name jdbc_8.2.0jre8 and  jdbc_auth-8.2.0x64.dll
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
SQL Server driver must be updated every time DBeaver starts
#### Steps to reproduce, if exist:
Connect to SQL Server

Actual result:
1. Connection fails
2. An error message appears

Workaround
1. Open Edit Driver Settings
2. Delete existed drivers
3. Press Reset to Defaults
4. Press Download/Update for jdbc_auth-8.2.0x64.dll
5. Press Ok
6. Connect to the database 

#### Include any warning/errors/backtraces from the logs
![r8M9YsrPWQ](https://user-images.githubusercontent.com/51405061/76966129-86446080-6936-11ea-959d-9d17bf09e4ae.gif)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4349240/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
