### ISSUE TITLE
Import data into temporary tables from a CSV

### ISSUE THREAD

**Issue by ivanelson** [dbeaver/dbeaver#8218]
Hi,

My database is postgresql and I want a quick way to import into temporary tables from a CSV.

In the Import/Export wizard it doesn't seem to support temp tables.

It may be possible to run [psql](https://www.postgresql.org/docs/9.4/app-psql.html) (copy) from the SQL Editor, but I haven't found how to do it.

Any suggestion?

Grateful

**Comment by uslss** [comment]
hi @ivanelson , 
you could try to execute script using Tools - Execute Script
