### ISSUE TITLE
VIM-like editor bindings

### ISSUE THREAD

**Issue by sojournerc** [dbeaver/dbeaver#8219]
**Is your feature request related to a problem? Please describe.**
VIM is my primary code editor, but I like to rely on dbeaver for writing/editing SQL. The difference in keybindings often takes me out of my flow as some funny things happen when I start VIMing in dbeaver.

**Describe the solution you'd like**
This request is probably pie-in-the-sky, but VIM(ish) key bindings in the script editor would be lovely. 

**Describe alternatives you've considered**
I can use vim plugins to get sql completion, auto-complete table names etc etc in vim, but dbeaver's GUI is much better for exploring data, seeing query plans, etc. etc.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by ceinmart** [comment]
Today I already use this with dbeaver. 
What you need to do is install Eclipse Marketplace :
    **Help -> install new software -> search for market**
The into marketplace menu , search for Vrapper plugin.

![image](https://user-images.githubusercontent.com/7062410/77167287-83f81880-6a94-11ea-9a2e-a24a57abfffa.png)

**Comment by sojournerc** [comment]
Awesome! 

I first had to install Eclipse Marketplace by going to "Help" > "Install New Software"

Then searched for the eclipse repo and the marketplace client:
![image](https://user-images.githubusercontent.com/1697422/77207018-efa2ab80-6abd-11ea-824d-984ac956c69e.png)

After that I was able to add the Vrapper plugin

Thanks so much!

**Comment by saywebsolutions** [comment]
This doesn't seem to work for me; I get

```
Cannot complete the install because of a conflicting dependency.
  Software being installed: Marketplace Client 1.8.2.v20200309-0038 (org.eclipse.epp.mpc.feature.group 1.8.2.v20200309-0038)
  Software currently installed: DBeaver 21.0.0.202102281937 (org.jkiss.dbeaver.core.product 21.0.0.202102281937)
  Only one of the following can be installed at once: 
    Equinox Provisioning Discovery UI 1.1.400.v20191213-1911 (org.eclipse.equinox.p2.ui.discovery 1.1.400.v20191213-1911)
    Equinox Provisioning Discovery UI 1.2.0.v20200916-1234 (org.eclipse.equinox.p2.ui.discovery 1.2.0.v20200916-1234)
  Cannot satisfy dependency:
    From: Marketplace Client 1.8.2.v20200309-0038 (org.eclipse.epp.mpc.feature.group 1.8.2.v20200309-0038)
    To: org.eclipse.equinox.p2.iu; org.eclipse.epp.mpc.ui [1.8.2.v20200309-0038,1.8.2.v20200309-0038]
  Cannot satisfy dependency:
    From: Marketplace Client 1.8.2.v20200309-0038 (org.eclipse.epp.mpc.ui 1.8.2.v20200309-0038)
    To: osgi.bundle; org.eclipse.equinox.p2.ui.discovery [1.0.0,1.2.0)
  Cannot satisfy dependency:
    From: Equinox p2, Discovery UI support 1.2.800.v20200916-1234 (org.eclipse.equinox.p2.discovery.feature.feature.group 1.2.800.v20200916-1234)
    To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.p2.ui.discovery [1.2.0.v20200916-1234,1.2.0.v20200916-1234]
  Cannot satisfy dependency:
    From: DBeaver Community Edition 21.0.0.202102281937 (org.jkiss.dbeaver.ce.feature.feature.group 21.0.0.202102281937)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [21.0.0.202102281937,21.0.0.202102281937]
  Cannot satisfy dependency:
    From: DBeaver 21.0.0.202102281937 (org.jkiss.dbeaver.core.product 21.0.0.202102281937)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [21.0.0.202102281937,21.0.0.202102281937]
  Cannot satisfy dependency:
    From: DBeaver Standalone 21.0.0.202102281937 (org.jkiss.dbeaver.standalone.feature.feature.group 21.0.0.202102281937)
    To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.p2.discovery.feature.feature.group [1.2.800.v20200916-1234,1.2.800.v20200916-1234]
```

**Comment by ceinmart** [comment]
See #10987 . 
After version 7.3.1 the marketplace become incompatible . 
However the workaround is add the http://download.eclipse.org/mpc/releases/1.9.0 as repository and install the marketplace from there. 
Then all works again.

**Comment by verajosemanuel** [comment]
vrapper not working on dbeaver version 21.0.3.202104181339
Installed but after reboot no new binding is available.

**Comment by RollieParrish** [comment]
I just updated to DBeaver version 21.0.4.202105021514 and was able to install the eclipse marketplace and vrapper again as noted above

**Comment by diegoortizmatajira** [comment]
Installed Vrapper and it asked to restart.... it keeps restarting once and again automatically until I rebooted the computer. Dbeaver was rendered unusable. Had to remove the Vrapper files manually

**Comment by domidimi** [comment]
> Installed Vrapper and it asked to restart.... it keeps restarting once and again automatically until I rebooted the computer. Dbeaver was rendered unusable. Had to remove the Vrapper files manually

Try the unstable version of Vrapper

**Comment by reinaldocoelho** [comment]
Vrapper works like a charm, but when update dbeaver version I always lost the plugin and need to install again.

Does someone having this too?

**Comment by ceinmart** [comment]
> Vrapper works like a charm, but when update dbeaver version I always lost the plugin and need to install again.
> 
> Does someone having this too?

Hi, Yes!
And I also open a issue , then was found it duplicated... this issue is already  planned . 
 https://github.com/dbeaver/dbeaver/issues/5317

**Comment by reinaldocoelho** [comment]
> > Vrapper works like a charm, but when update dbeaver version I always lost the plugin and need to install again.
> > Does someone having this too?
> 
> Hi, Yes! And I also open a issue , then was found it duplicated... this issue is already planned . #5317

Great!! Thanks! :-)

**Comment by johnathanz** [comment]
> Awesome!
> 
> I first had to install Eclipse Marketplace by going to "Help" > "Install New Software"
> 
> Then searched for the eclipse repo and the marketplace client: ![image](https://user-images.githubusercontent.com/1697422/77207018-efa2ab80-6abd-11ea-824d-984ac956c69e.png)
> 
> After that I was able to add the Vrapper plugin
> 
> Thanks so much!

Thanks a lot, that's what I needed!

**Comment by JanetMatsen** [comment]
How do you find the Eclipse Marketplace in newer versions?  I've installed it but I can't figure out how to interact with it.  (It is not showing up under the `Help` menu.

**Comment by d0zingcat** [comment]
Hey, hope this post helps: https://shehuawwal.com/installing-vim-extension-module-for-dbeaver-with-vrapper/

**Comment by ricardowolff** [comment]
> Hey, hope this post helps: https://shehuawwal.com/installing-vim-extension-module-for-dbeaver-with-vrapper/

This is the quickest solution, but the website does not exist anymore. So I used wayback machine to read it. And I'll make it available here for the next time I upgrade DBeaver. LOL 

### How To Install Vrapper On DBreaver

- Click on Help from the Menu Icon > Install New Software
- You will see Work With and paste the following URL: http://vrapper.sourceforge.net/update-site/stable
- And Select the full Vrapper option:

![](http://web.archive.org/web/20240314094746im_/https://cdn.shehuawwal.com/uploads/2021/03/f6d04dd9.png)

- Just Wait And Click On Next And follow the on-screen help, And that's all.

----

If you want to check the website for yourself:
http://web.archive.org/web/20240314094746/https://shehuawwal.com/installing-vim-extension-module-for-dbeaver-with-vrapper/

**Comment by lispercat** [comment]
Looks like the plugin only provides bindings in SQL script windows, but not for the rest of editing (like stored procedures etc)

**Comment by willxy** [comment]
I came here after finding, as well, that vrapper bindings apparently don't work in the stored procedure editor.

Is that something that needs to be fixed on the DBeaver side, or on the vrapper side?
