### ISSUE TITLE
Provide JSON (and XML) formatting for binary columns

### ISSUE THREAD

**Issue by nilskp** [dbeaver/dbeaver#8220]
**Is your feature request related to a problem? Please describe.**
For a textual column, there are formatting options of JSON and XML, but not for binary columns, even though JSON data is often stored as binary UTF-8 (one should arguably always store XML as binary, since the encoding is embedded inside the document itself).

**Describe the solution you'd like**
Having the JSON/XML formatting options available on binary columns.

![image](https://user-images.githubusercontent.com/74843/77013047-3d43da80-693d-11ea-8b1c-ebded9dc0cfc.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
duplicates #7994
