### ISSUE TITLE
Microsoft JDBC Driver for SQL Server doesn't work with AD login

### ISSUE THREAD

**Issue by Husssar** [dbeaver/dbeaver#8221]
#### System information: 
- Operating system (distribution) and version
Linux Mint 19.3 Tricia
- DBeaver version 
7.0.0

#### Connection specification:
- Database name and version
Microsoft SQL Server 2016 (SP2-GDR) (KB4532097) - 13.0.5102.14 (X64)   Dec 31 2019 22:39:35   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

#### Describe your question:
I'm having a problem to connect to our server when I'm using the AD directory username/password.
![image](https://user-images.githubusercontent.com/57284163/77050928-c2290580-69ca-11ea-8df7-3d8f8a2bd657.png)
![image](https://user-images.githubusercontent.com/57284163/77051082-06b4a100-69cb-11ea-837f-ac75b4daf074.png)

I'm using the driver included in dbeaver
![image](https://user-images.githubusercontent.com/57284163/77050984-dc62e380-69ca-11ea-8220-c29d01158ece.png)

When I try to change to latest driver (8.2.0) from Microsoft, everything that's happening is that dbeaver requesting to download 7.4.1 again.

![image](https://user-images.githubusercontent.com/57284163/77053155-32855600-69ce-11ea-9ef9-6d286dc11600.png)

Thank you.

**Comment by serge-rider** [comment]
AD integration won't work on Linux (as driver uses native Windows binaries for that).

Note 1: We fixed problem with SQL Server driver download in 7.0.1.
Note 2: We are going to add native Kerberos/AD support for SQL Server in DBeaver EE  7.1
