### ISSUE TITLE
[SQL Server] Data cannot be changed in ResultSet if a table name has space

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8222]
## System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.1 EA

#### Connection specification:
- Database name and version SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Data cannot be changed in ResultSet if a table name has space
#### Steps to reproduce, if exist:
1. Create a table with a space in its name (e.g. "test space") using Object Editor
2. fill in the table with data and save the table
3. Open the table in ResultSet and try to edit its data

Actual result:
1. The table is read-only
2. The message "No corresponding table column appears"
![dbeaver_5C7Gr6shKb](https://user-images.githubusercontent.com/51405061/77057481-15a84d00-69e5-11ea-82d1-d8624baa404c.png)

**Comment by serge-rider** [comment]
Fixed. 
Problem was cased by square brackets (not by space character itself). New versions of @jsqlparser have special flag for that.

**Comment by kseniiaguzeeva** [comment]
Verified
