### ISSUE TITLE
[Exasol] FK (date type) throws an error when trying to open value from referenced table

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8224]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.1

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
![2020-03-19_14h22_47](https://user-images.githubusercontent.com/31996417/77064445-8d2fa980-69f0-11ea-8c81-7053cc398b5b.png)
We've got fk (date type), when i try to open it using link in data viewer or open reference table - error apears (see picture below).
Generated query:
```
SELECT x.* FROM RETAIL.DIM_DATE x
WHERE x.SALES_DATE = 2015-01-24
```
In case I quote value and execute statement in SQL editor - everything works ok.

**Comment by Sargul** [comment]
will look into this

**Comment by uslss** [comment]
verified
