### ISSUE TITLE
[ERD][Exasol] Columns that are connected by FK, aren't higlighted

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8226]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.0.1

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
Connected columns aren't highlighted when connection is chosen
![image](https://user-images.githubusercontent.com/31996417/77066629-902c9900-69f4-11ea-839e-3c31ef0d1384.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
