### ISSUE TITLE
Close all connections under a project

### ISSUE THREAD

**Issue by krilim** [dbeaver/dbeaver#8227]
I know we can close all connections ... My request is a **Close connections** from a project context menu to close only connections in the project.

Thanks.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
It is already there:
![image](https://user-images.githubusercontent.com/6398845/77292916-4b557a80-6cf2-11ea-8092-4e4d79b17cfa.png)
