### ISSUE TITLE
Informix - syntax error - get offset

### ISSUE THREAD

**Issue by ceinmart** [dbeaver/dbeaver#8232]
For Informix database, when ran a big statement and get "syntax error" it is painful to find out the place with the error. 
However, the Informix driver provide the offset of the position of the error. 
My request is to retrieve this offset and point or mark someway the position of the syntax error. 

Quoting the[ informix jdbc manual](https://www.ibm.com/support/knowledgecenter/en/SSGU8G_14.1.0/com.ibm.jdbc.doc/ids_jdbc_111.htm) ; 

> To determine the exact location of a syntax error, use the getSQLStatementOffset() method to return the syntax error offset.
> 
> The following example shows how to retrieve the syntax error offset from an SQL statement (which is 10 in this example):
> try {
>   Statement stmt = conn.createStatement();
>   String command = "select * fom tt";
>   stmt.execute( command );
> }
> catch(Exception e)
> {
>   System.out.println
>   ("Error Offset :"+((IfmxConnection conn).getSQLStatementOffset() );
>   System.out.println(e.getMessage() );
> }

**Comment by uslss** [comment]
thanks for suggestion

**Comment by ShadelessFox** [comment]
Please note that this is an Enterprise Edition extension.

**Comment by uslss** [comment]
verified
