### ISSUE TITLE
Hive - tables not appears in Database Navigator

### ISSUE THREAD

**Issue by wlasiukk** [dbeaver/dbeaver#8234]
#### System information: 
- Windows 10
- DBeaver version : 7.0.0.202003021717
- Java version 1.8.0_202
- Additional extensions: none

#### Connection specification:
- Database name and version : HIVE version 3.1.0 from HDP 3.1 
- Driver name version : tested with two versions
  * https://github.com/timveil/hive-jdbc-uber-jar/releases/download/v1.9-2.6.5/hive-jdbc-uber-2.6.5.0-292.jar
  * hive-jdbc-standalone.jar from HDP 3.1

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
Yes, but connection is working fine

#### Describe the problem you're observing:
On one database user can't see any tables while issuing statement show tables in database_name gives full list of tables. User also can qurey that tables.
In other databases tables are present in Database Navigator list 

#### Include any warning/errors/backtraces from the logs
error log is empty
Query Manager shows :
-- Load tables [null, earnix, %, null] # this one is ok, 4 tables appears
-- Load tables [null, sandbox_shared, %, null]  # no tables appears

**Comment by balookrd** [comment]
in version 7.0.2.202004051509 same problem, tables not show, driver ClouderaHiveJDBC-2.6.10.1012

**Comment by uslss** [comment]
is it still actual?

**Comment by wlasiukk** [comment]
No, we do not have problem with this issue any more.

pon., 30 sie 2021, 20:45 użytkownik Dziyana ***@***.***>
napisał:
