### ISSUE TITLE
SQLite unimplemented ROWID

### ISSUE THREAD

**Issue by kezyr** [dbeaver/dbeaver#8235]
#### System information: 
- Operating system (distribution) and version: Windows 7
- DBeaver version: 7.0.0
- Additional extensions: none

#### Connection specification:
- Database name and version: db1
- Driver name: SQLite DBeaver internal
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
DBeaver shows an error message "There is no unique physical unique key defined for ......" in case I do update of some row. In case SQLite this is not true because SQLite implements primary key column for every table automatically. The column name is "rowid" and it is hidden. So it should be possible to do changes also in tables without visible primary key.

#### Steps to reproduce, if exist:
Do an empty copy of any existing table:
CREATE TABLE tbl_copy AS SELECT * FROM tbl_existing WHERE 0;

Table tbl_copy doesn't have any (visible) unique column now so it is not possible to change data without error/warning. If DBeaver use internal "rowid" column this can be solved

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.
DBeaver offers to create a virtual primary key if there is not Primary Key in a table.  You can use this option as workaroud.
How:
1. Popup appears when you make changes in a table without Primary key.
![Wtb2tR7HtK](https://user-images.githubusercontent.com/51405061/78017220-99065e80-7354-11ea-9ccc-7b0d950413a7.png)
2. You can create virtual primary key in table Properties> Virtual tab.
![AKpEMmxppI](https://user-images.githubusercontent.com/51405061/78017407-eaaee900-7354-11ea-8c36-af24cf6784e1.png)

This key exists in DBeaver only.

**Comment by serge-rider** [comment]
Done.
We will use ROWID only if SQLite table doesn't have an explicit primary key.

**Comment by uslss** [comment]
verified

**Comment by Cheney-77** [comment]
> Done. We will use ROWID only if SQLite table doesn't have an explicit primary key.

@serge-rider  hello,i just want to know is there any plan to support other database type,like postgresql ? looking forward to your reply,tkx!!
