### ISSUE TITLE
[Derby] Unique Index couldn't be created using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8236]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7,0,1

#### Connection specification:
- Database name and version Derby

#### Describe the problem you're observing:
Unique Index couldn't be created using UI
#### Steps to reproduce, if exist:
1. Open table
2. Try to create index (check Unique field)
3. Save index - generated SQL is for usual, not UNIQUE index 
Generated sql:
> CREATE INDEX NEWTABLE_1_COLUMN2_IDX ON APP.NEWTABLE_1 (COLUMN2);

Expected sql:
> CREATE **UNIQUE** INDEX NEWTABLE_1_COLUMN2_IDX ON APP.NEWTABLE_1 (COLUMN2);

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D73](https://dbeaver.testquality.com/project/8805/result/1906375/defect/6485). Do not remove or edit.

**Comment by serge-rider** [comment]
Fixed. It was broken for all Generic drivers.

**Comment by uslss** [comment]
verified
