### ISSUE TITLE
Bookmark cannot be created using shortcut Ctrl+Alt+Shift+D 

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8238]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.1 EA

#### Describe the problem you're observing:
Bookmark cannot be created using shortcut Ctrl+Alt+Shift+D
#### Steps to reproduce, if exist:

1. Click on a table in DB Navigator tree
2. Press Ctrl+Alt+Shift+D

Actual result: no visible changes
Expected: Bookmark Name dialog box appears.

**Comment by serge-rider** [comment]
Can't reproduce. Moreover this bug not about bookmark creation but about shortcut.
Can you create bookmark using context/main menu?

**Comment by kseniiaguzeeva** [comment]
Closed with nuances: only shotcut Ctrl+Alt+Shift+D or F doesn't work (Ctrl+Alt+Shift+S etc work correctly)
