### ISSUE TITLE
[Derby] Execution plan button is active, but does nothing on click

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8243]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.1

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
In SQL Editor Execution plan button is active but does nothing on click. Also no error appears in Error log

**Comment by serge-rider** [comment]
It is a more generic issue. We do not support disabled actions for vertical toolbars.
We need to add this support.

**Comment by uslss** [comment]
verified
