### ISSUE TITLE
quick search tool

### ISSUE THREAD

**Issue by tibztibz** [dbeaver/dbeaver#8244]
#### System information: 
- Operating system (distribution) and version : Ubuntu 18
- DBeaver version 7.0.0
- openjdk version "1.8.0_242"
- OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
- OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

#### Possible evolution
Hello !

I think it should be very cool if we could make a quick search on the table name (and more if you can) like phpstorm (double Maj taping, display a search input in a pop up).

And navigate between main tabs opened with a shortcode should be cool too.

thanks !
Bye!

**Comment by serge-rider** [comment]
Thanks for bringing this up.
Since 4.13 Eclipse has Quick Search tool (https://marketplace.eclipse.org/content/quick-search-eclipse) out of the box. 
We'll include it in the next dbeaver version.

**Comment by p91paul** [comment]
@tibztibz try ctrl+d, it offers search on database objects (tables, views, etc)

**Comment by tibztibz** [comment]
@serge-rider perfect !

@p91paul yes it's exactly what i need ! thx a lot !

**Comment by uslss** [comment]
verified
