### ISSUE TITLE
Mention MacPorts as install option on dbeaver.io/download

### ISSUE THREAD

**Issue by lhaeger** [dbeaver/dbeaver#8245]
Please consider mentioning [MacPorts](https://www.macports.org) as alternative install option on [https://dbeaver.io/download](https://dbeaver.io/download), similar to "brew cask". The command to install dbeaver-community via MacPorts is
`sudo port install dbeaver-community`

**Comment by serge-rider** [comment]
This makes sense

**Comment by serge-rider** [comment]
Done
