### ISSUE TITLE
not clear interface in SQL editor

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#8246]
For example, I want to partly enlarge the window for displaying query results.

Intuitively not clear how to do this. Only two litle battons "Hide" named. This battons hang on a white background - it is not clear what they relate to. 

There is an opportunity to stretch the results window, but I have to find some unknown area in the tab area "Results" and stretch her.

It is all non comfortable in use.

![изображение](https://user-images.githubusercontent.com/61137576/77286093-62956780-6cf4-11ea-95b5-d24c036c566d.png)

**Comment by serge-rider** [comment]
You can maximize any tab in dbeaver by double-clicking on it. And return it back by second double-click.
This is a standard behavior in many programs, that's why we didn't make any other special menus/buttons.

**Comment by detkliff** [comment]
Thanks, but i think that this button is "other special menus/buttons"
![изображение](https://user-images.githubusercontent.com/61137576/77289104-1863b480-6cfb-11ea-8f21-f4c534a81f64.png)

I used only partial window resizing and it is very probably if i working in central part of the interface

![изображение](https://user-images.githubusercontent.com/61137576/77289751-662cec80-6cfc-11ea-8baa-72c794449ced.png)
