### ISSUE TITLE
Incorrect behaviour when trying to assign schema priveleges

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8250]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.1 EA

#### Connection specification:
- Database name and version Maria DB

#### Describe the problem you're observing:
Accordingly to [comment](https://github.com/dbeaver/dbeaver/issues/8055#issuecomment-593926842):
> I had another issue while trying to reproduce. If you do a new user then click % from the schema column then % from the tables column, then check all, uncheck all, then select a specific schema, % in tables and check all, it's applying to all schemas for some reason. This continues after restarting dbeaver so you should be able to reproduce this one consistently

**Comment by serge-rider** [comment]
Fixed.
This bug was caused by fix of #7784

**Comment by uslss** [comment]
verified.
related issue #8298
