### ISSUE TITLE
Error on a table data choise

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#8253]
System information:

    Operating system (distribution) and version WINDOWS 10 64 bit
    DBeaver version 7.0.1 CE

Describe the problem you're observing:

Click on the table in the right part of the interface, show up modal window with error message, but show table data on background.

![изображение](https://user-images.githubusercontent.com/61137576/77415436-4f61c500-6de4-11ea-8b4e-b6f9df6c98e8.png)

**Comment by uslss** [comment]
hi @detkliff ,
does issue appear right after you open data viewer?

**Comment by detkliff** [comment]
yes. Double click on table in the objects tree -> show modal window with error and show data table in the background after that.

**Comment by detkliff** [comment]
> 
> 
> hi @detkliff ,
> does issue appear right after you open data viewer?

yes. Double click on table in the objects tree -> show modal window with error and show data table in the background after that.

**Comment by uslss** [comment]
anyway, cannot reproduce. :(
Does the issue appear always?  Probably any special steps are needed? Does "Invalidate connection" solve the problem?

**Comment by detkliff** [comment]
> 
> 
> anyway, cannot reproduce. :(
> Does the issue appear always? Probably any special steps are needed? Does "Invalidate connection" solve the problem?

yes she does, issue appear always.

1. Create 2 database on server.
2. Work with database1 20-60 minutes
3. Choise database2 in the objects tree
4. Double click on table in the objects tree -> show modal window with error and show data table in the background after that.

In what cases does this window appear? In this cases autoreconnect started and show error window?

**Comment by uslss** [comment]
please, change Keep-Alive in Connection properties to non-null value
![image](https://user-images.githubusercontent.com/31996417/92725287-96cd1500-f374-11ea-9d72-913526f3cead.png)
