### ISSUE TITLE
[Oracle] Show column comments in autocompletion flyout

### ISSUE THREAD

**Issue by AnrDaemon** [dbeaver/dbeaver#8254]
**Is your feature request related to a problem? Please describe.**
In a way, this is a problem. In a big database, it is not always clear, what column stores which values. Column/table comments come in handy.

**Describe the solution you'd like**
I'd like to see table/column comments, when available, in the flyout when choosing from suggested items.

![20200324-144751-Clipboard](https://user-images.githubusercontent.com/6532485/77423209-d5c7d800-6ddf-11ea-862c-3881fc23fcda.png)

**Describe alternatives you've considered**
Well, the only real alternative is to keep database documentation handy.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by AnrDaemon** [comment]
It seems, the feature already exists, but does not always show column comments when they are available.

**Comment by LonwoLonwo** [comment]
> It seems, the feature already exists, but does not always show column comments when they are available.
Can you please describe this cases, when column comments are not available?

**Comment by AnrDaemon** [comment]
When table data was not received for one or another reason.

**Comment by AnrDaemon** [comment]
First attempt at autocompleting the data
![image](https://user-images.githubusercontent.com/6532485/101144849-fd876500-3629-11eb-9b10-45928991414a.png)

Same completion state but after the "Properties" tab of the relevant table was opened and all data populated.
![image](https://user-images.githubusercontent.com/6532485/101145146-6e2e8180-362a-11eb-944d-a9e72197c83b.png)


The database in question is Oracle.

**Comment by LonwoLonwo** [comment]
Ok, I get it.
We use lazy initialization for Oracle table comments, because we read them a separate query in the database.
At the moment there is no good solution for this problem.

**Comment by AnrDaemon** [comment]
Though so, thanks for clarification.

**Comment by Falke-Design** [comment]
Would be still a very helpful feature

**Comment by AnrDaemon** [comment]
It IS an actual feature, if you have read the thread. Just so that it is not readily available at all times due to technical constaints.

**Comment by Falke-Design** [comment]
I had read the thread and still a feature which is not working properly (for Oracle) is not a feature ...
