### ISSUE TITLE
Tuple fields are not populated 7.0.1 while populated in 7.0.0

### ISSUE THREAD

**Issue by muhannedmaayeh** [dbeaver/dbeaver#8256]
#### System information: 
- Operating system (distribution) and version
Mac OS X Mojave 10.14.6
- DBeaver version
7.0.1
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When running the query
select * from pg_tables where tablename = '<table_name>'; then you get unpopulated data:
schemaname	tablename	tableowner	tablespace	hasindexes	hasrules	hastriggers
{}	{}	{}	NULL	false	false	false

**Comment by uslss** [comment]
hi @muhannedmaayeh ,
cannot reproduce an issue. works ok for me. probably any additional steps is needed?
![image](https://user-images.githubusercontent.com/31996417/77463913-6cfc5200-6e17-11ea-90fc-55a86db30816.png)

**Comment by muhannedmaayeh** [comment]
> hi @muhannedmaayeh ,
> cannot reproduce an issue. works ok for me. probably any additional steps is needed?
> ![image](https://user-images.githubusercontent.com/31996417/77463913-6cfc5200-6e17-11ea-90fc-55a86db30816.png)

Is it possible my java dependencies is not correct for DBeaver.  Let me try uninstalling DBeaver and re-install from the Mac installer with jre to assure dependencies are correct.

**Comment by muhannedmaayeh** [comment]
I tried re-installing by moving the old to Trash and running the package installer with JRE and I still have the same issue.  What is the other areas to check or other troubleshooting steps required.

running information_schema.tables shows:
![Screen Shot 2020-03-25 at 9 52 58 AM](https://user-images.githubusercontent.com/62610760/77513938-913f4980-6e7e-11ea-9645-df969faf221c.png)


And, running the pg_tables/pg_views query I still get empty tuples:
![Screen Shot 2020-03-25 at 9 53 04 AM](https://user-images.githubusercontent.com/62610760/77513959-9bf9de80-6e7e-11ea-901d-489b9efc919d.png)

**Comment by muhannedmaayeh** [comment]
@uslss Did you get a chance to see how to reproduce?  Is it something with my dependencies?  Is there a way I can trouble shoot this because I am unable to see results and really need to utilize this to get results for a project.

**Comment by muhannedmaayeh** [comment]
@uslss, if you can give this a look and see if there is anything unusual in my error log that may explain my issue.

[dbeaver_errorlog_20200331.log](https://github.com/dbeaver/dbeaver/files/4407083/dbeaver_errorlog_20200331.log)

**Comment by muhannedmaayeh** [comment]
@uslss ,

I have uninstalled 7.0.1 and re-installed 7.0.0 and now the tuples for data are now working:
![Screen Shot 2020-03-31 at 12 40 32 PM](https://user-images.githubusercontent.com/62610760/78011857-d5ce5780-734c-11ea-838f-9a04da016394.png)

**Comment by muhannedmaayeh** [comment]
I can confirm that this is now resolved in 7.0.2 CE release.  Thank you very much.
