### ISSUE TITLE
Error in order of column names in declaration of foreign key

### ISSUE THREAD

**Issue by viktor-krasikov** [dbeaver/dbeaver#8259]
1) Click on a table name in Database navigator
2) Open tab "Properties"
3) Click "DDL" button"
4) If table contain a foreign key with 2 or more columns then these columns may be have different order in declaration part and in reference part:
For example:
...
CONSTRAINT FK__XXXXXX__176F17C2 FOREIGN KEY (**COL1,COL2**) REFERENCES YYYYY_OTHER_TABLE(**COL2,COL1**),
...

DBMS: Microsoft SQL Server 2017 (RTM-CU19) (KB4535007) - 14.0.3281.6 (X64) 
	Jan 23 2020 21:00:04 
	Copyright (C) 2017 Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: )

DBeaver version: 7.0.1.202003211804

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Can't reproduce. We use `ORDER BY constraint_object_id, constraint_column_id` when querying foreign_key_columns.
Could you post table DDL which will let to reproduce the issue?
