### ISSUE TITLE
Add shorcut to "Export from query"

### ISSUE THREAD

**Issue by mikkk3l** [dbeaver/dbeaver#8263]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually navigate via right button / Execute / Export from query as I do it frequently.

**Describe the solution you'd like**
I'd love to hace a customizable shortcut to open the export dialogue directly from my keyboard.

**Describe alternatives you've considered**
Doing it manually with some clicks, but I'm lazy :P.

**Additional context**

**Comment by uslss** [comment]
Hi @mikkk3l ,
you could set any shortcut you want to Export from query in preferences
![image](https://user-images.githubusercontent.com/31996417/77528970-e63f8780-6e9f-11ea-83c2-c367a8f5b1d4.png)

**Comment by mikkk3l** [comment]
Thank you very much and sorry.
