### ISSUE TITLE
[*Possible* BUG] - Did DBeaver lost its "smart home key" funcionality?

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#8264]
Is it me, or hitting the "HOME" key used to go to the first character of the line, and now it goes to the begginning of line? :-S

**Comment by uslss** [comment]
Hi @wiwwo ,
what version do you use?
In 7.0.1 it works ok for me - hitting Home button still used to go to the first character

**Comment by wiwwo** [comment]
7.0.1
Linux Mate 18.04.

**Comment by Physikuss** [comment]
Same here with 7.0.2 on Windows x64

**Comment by uslss** [comment]
Hm, reproduced for me after default formatter changing. Also reset UI settings helps me.
btw, @wiwwo , @Physikuss what formaters do you use?

**Comment by wiwwo** [comment]
"I don't know"
which spells
"The default one"
:-D ;-)

**Comment by Physikuss** [comment]
A bit late, but I was also using the default formatter.

**Comment by serge-rider** [comment]
Can't reproduce. `Home` always navigates to the first non-whitespace character (spaces, tabs).
You can enable "Show whitespace characters" in text editor preferences to see what is actually in the beginning of the line.

**Comment by kseniiaguzeeva** [comment]
@wiwwo , @Physikuss Did Serge's advice help you?

**Comment by uslss** [comment]
there is no update on issue for a long time. Probably, it is solved.
If it is still actual for you - feel free to reopen the ticket
