### ISSUE TITLE
[BUG?] Newly-created-table has read-only grid

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#8266]
Creating a new table, then selecting and trying to change the value is not possible. I had to right-clink on the schema name and call "refresh" to have datagrid in read-write.

![image](https://user-images.githubusercontent.com/3930671/77526881-8f2fb780-6e8b-11ea-90c3-dc3a8a7ac8b4.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
It is not a bug. DBeaver doesn't refresh database metamodel on SQL exeucte.
We have a feature request for that: #7924
