### ISSUE TITLE
In 7.0.1 bugFix broke Default schema / Active catalog/schema dropdown

### ISSUE THREAD

**Issue by mikkk3l** [dbeaver/dbeaver#8268]
#### System information: 
- Operating system (distribution) and version windows 10
- DBeaver version 7.0.1
- Additional extensions

#### Connection specification:
- Database name and version IBM DB2 11
- Driver name db2jcc.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
I have an schema with my user (eg: MYUSER) and configured initiliazation to point to another (ANOTHER_SCHEMA) 
Even with correct active schema selected in Active C/S dropdown selector, the query sends MYUSER schema and, obviously, the query fails because that table does not exist within that schema. 
If you reselect in the dropdown Active C/S again with ANOTHER_SCHEMA (it was already selected) it gets fixed until you relaunch the program and reconnect when the same thing happens.
It works correctly in 7.0.0.

**Comment by uslss** [comment]
hi @mikkk3l ,
unfortunately, cannot reproduce an issue. Probably some special steps are needed?

**Comment by kngmat004** [comment]
having the same problem, am going to need to rollback versions

**Comment by mikkk3l** [comment]
It stills happens in 7.3.0. Could you please try to reproduce it with a connection of DB2 z/OS driver?
You have to execute a query, wait a little and then try to execute the same again. Within the same session (no need to restart Dbeaver) it fails because even if the dropdown points to the correct schema, you have to **reselect the same** again. 

Thank you very much :), it is quite annoying.

**Comment by eli-tsikel** [comment]
Same happen to me in 7.5.3
