### ISSUE TITLE
Dark theme glitchy font

### ISSUE THREAD

**Issue by filipbekic01** [dbeaver/dbeaver#8269]
- Linux Arch / Manjaro 
- DBeaver 7.0.0

https://i.imgur.com/zGH9Kmh.png

**Comment by hurie** [comment]
Dialog font in Windows 10

![image](https://user-images.githubusercontent.com/651842/86874251-3dddc800-c10a-11ea-944f-36d8c95eb465.png)

**Comment by filipbekic01** [comment]
What?

**Comment by uslss** [comment]
cannot reproduce it against 21.0.3.
If it is still actual for you - feel free to reopen an issue
