### ISSUE TITLE
How to work with BLOBs in Postgre ???

### ISSUE THREAD

**Issue by RIS2000** [dbeaver/dbeaver#8271]
I didn't found any information elsewhere!

Do not offer Bytea. I need exactly LO functionality, ie.:
How to create BLOB ? How to import/export file ? Is there visual tools for this in DBeaver exists ?

Thanks in advance!

**Comment by kseniiaguzeeva** [comment]
@RIS2000 The application supports PostgreSQL functionality. The equivalent of BLOB is Bytea as you already noticed, but it does not suit you.
Please reopen the ticket or create a new one if I can help you with smth else.
