### ISSUE TITLE
Redshift name datatype in the resultset is displaying as empty arrays

### ISSUE THREAD

**Issue by appleseed4** [dbeaver/dbeaver#8275]
#### System information: 
- DBeaver version - 7.0.1

#### Connection specification:
- Database name and version - Redshift

#### Describe the problem you're observing:
"select usename from pg_user;" works fine in DBeaver 6.3.
But in DBeaver 7.0.1 the resultset has empty arrays for all rows. When I right-click the column header to "set format" the only option is "array".
A hack to get it to work in 7.0.1 is to cast it as varchar like "select usename::varchar(1000) from pg_user;"

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed.
In fact we had a wrong data type meta info for Redshift.

**Comment by uslss** [comment]
verified

**Comment by Hammond95** [comment]
I have the same problem, there is a quick fix available?

**Comment by Hammond95** [comment]
ok just saw the `usename::varchar(1000)` hack
