### ISSUE TITLE
SQL Server - Export Data - Timestamp column should be skipped when "Include generated columns" is unchecked

### ISSUE THREAD

**Issue by DanielAdeniji** [dbeaver/dbeaver#8278]
#### System information: 
- Operating System :- MS Windows 10
- Dbeaver :- 7.1 and 6.2.4- 

#### Connection specification:
- Microsoft SQL Server 2017
- Microsoft JDBC Driver for SQL Server

#### Describe the problem you're observing:
When DBeaver is used to export data and the source table contains a timestamp column, that timestamp column should be skipped as SQL Server does not allow one to insert data into a timestamp column.

#### Steps to reproduce, if exist:

**Create Table**

use [tempdb]
go
 
create schema [column.timestamp] authorization [dbo];
go
 
create table [column.timestamp].[person]
(
          [id] int not null identity(1,1)
        , [ts] timestamp not null        
)
 
go

**Add Data**
truncate table [column.timestamp].[person]
go
 
insert into [column.timestamp].[person]
default values
 
insert into [column.timestamp].[person]
default values
 
go

**In Dbeaver, generate SQL**

1. Choose a table
2. Choose to Export Data
3. In the "Settings Tables to Files, SQL" window, please uncheck "Include generated columns"
4. Generate the SQL

**Sample generated SQL**
INSERT INTO tempdb.[column.timestamp].person (ts) VALUES
(0x00000000000007DA)
,(0x00000000000007DB)
;

**Errors**
Msg 273, Level 16, State 1, Line 1
Cannot insert an explicit value into a timestamp column.
Use INSERT with a column list to exclude the timestamp column, or insert a DEFAULT into the timestamp column.

**Comment by uslss** [comment]
thanks for the bug report and sorry for late response

**Comment by serge-rider** [comment]
Fixed
