### ISSUE TITLE
Autocomplete adding extra characters

### ISSUE THREAD

**Issue by timatanu** [dbeaver/dbeaver#8283]
#### System information: 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
DBeaver 7.0.1

#### Connection specification:
MS SQL Server
com.microsoft.sqlserver.jdbc.SQLServerDriver
Connected via VPN 

#### Describe the problem you're observing:
When using Autocomplete to complete a Table name in the SQL Editor extra characters are being appended at the end.

Initial value with selection drop down displayed: SELECT * FROM ESB_RES
Expected value: SELECT * FROM ESB_RESOURCE_EVENT_SUMMARY 
Actual value: SELECT * FROM ESB_RESOURCE_EVENT_SUMMARY eres 

<img width="543" alt="DBeaver AutoComplete Issue Select" src="https://user-images.githubusercontent.com/39357224/77708826-44de4000-701d-11ea-98bd-7128337c21c4.png">

<img width="429" alt="DBeaver AutoComplete Issue Result" src="https://user-images.githubusercontent.com/39357224/77708845-545d8900-701d-11ea-8e2d-099ff16cb501.png">

**Comment by podoni** [comment]
Maybe "Insert table Alias (in From clause)" is set.

![image](https://user-images.githubusercontent.com/59002295/77722048-f8503000-702f-11ea-9964-bd531b384d1d.png)

**Comment by LonwoLonwo** [comment]
yes, it is table aliases at the end
