### ISSUE TITLE
Transaction log getting cleared when upgrading dbeaver

### ISSUE THREAD

**Issue by xhafan** [dbeaver/dbeaver#8284]
#### System information: 
- Operating system (distribution) and version: Windows 7 SP1
- DBeaver version: 7.0.1

#### Connection specification:
- Database name and version: Postgres 9.6
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Upgrading dbeaver to a new version clears transaction log.

#### Steps to reproduce, if exist:
1) Execute some sql statements, check you can see them in the transaction log.
2) Upgrade dbeaver to a new version.
3) Check the transaction log - all cleared even when options `show all queries` and `show previous transactions` are checked.

It very handy to be able to go back to a history of executed sql statements which go months back. It is annoying that upgrading dbeaver clears this transaction log history.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Transaction log lives just in current dbeaver session. Restarting dbeaver will clear it.

In EE version we keep query history in local embedded database. Do you mean this feature? Query history is stored in .metadata folder in dbeaver workspace. 
Version upgrade shouldn't affect it.

Please provide more details to track this issue.

**Comment by xhafan** [comment]
Thanks for the clarification, I didn't know that the transaction log is getting cleared after each application restart. I'm usually running DBeaver for weeks, so I thought the transaction log is able to keep history between restarts. Please feel free to close this issue.

**Comment by xhafan** [comment]
Thanks for the clarification, I didn't know that the transaction log is getting cleared after each application restart. I'm usually running DBeaver for weeks, so I thought the transaction log is able to keep history between restarts.
