### ISSUE TITLE
Replace linebreaks with regular spaces in .csv export settings

### ISSUE THREAD

**Issue by parkypoo** [dbeaver/dbeaver#8285]
Hi,

Would it be possible to incorporate a feature that replaces line breaks with regular spaces in the .csv exporter settings? There's a bug in Excel 2010 and other versions which treats line breaks as delimiters and there doesn't seem to be a way to fix it on excel's end. I've got a few exports I want to link through but any string columns with line breaks make the columns become misaligned.

In the meantime I'll be editing the script to replace the characters within each string but I have a lot of scripts I need to amend and this feature being in the export settings would be very useful to me in the future!

The menu I'm referring to is the below:

![image](https://user-images.githubusercontent.com/62740456/77742310-350b2f80-700e-11ea-8c4f-9b600895927c.png)

Thank you!

Tom

**Comment by uslss** [comment]
Hi @parkypoo ,
probably Row delimiter option could solve your problem?
![image](https://user-images.githubusercontent.com/31996417/77745828-094b7200-702d-11ea-8dec-2c54371cbe61.png)

**Comment by parkypoo** [comment]
I tried re-running the export with \n and \r and problems persisted, I've not tried with the bottom 2 though so I'll give that a shot soon and feedback,

Thank you.

**Comment by parkypoo** [comment]
This didn't work with "\r \n" or "\n \r" either :(

**Comment by parkypoo** [comment]
Any suggestions? :)

**Comment by parkypoo** [comment]
bump

**Comment by serge-rider** [comment]
@parkypoo If you need regular space then you need to enter regular space as row delimiter. 
Both \n and \r are line feeds. And you cannot put space between \r and \n.

**Comment by parkypoo** [comment]
I changed the row delimiter to a space and now the csv is empty in excel except for column headers. The results window still shows the data but just not the export.

Am I inputting it correctly? I literally just hit spacebar, any special characters I need to use?
![image](https://user-images.githubusercontent.com/62740456/78510965-e63d6280-7790-11ea-87ef-62ef74709dd1.png)

Thank you,
