### ISSUE TITLE
SQLite: Dictionary not working

### ISSUE THREAD

**Issue by kezyr** [dbeaver/dbeaver#8286]
Dictionary not working (no rows inside) in case all these conditions are fullfilled:
- table has at least 2 column referencing to the same (other) table
- during creation of the table foreign keys have not been defined by named constraint

**Example:**

Let's create this table for look-up of strings:
```
CREATE TABLE txt (
	id INTEGER PRIMARY KEY,
	value TEXT
);
INSERT INTO txt(value) VALUES ('text1');
INSERT INTO txt(value) VALUES ('text2');
INSERT INTO txt(value) VALUES ('text3');
```

Not working dictionary:
```
CREATE TABLE foo_dict_bug (
	id INTEGER PRIMARY KEY,
	txtid1 INTEGER,
	txtid2 INTEGER
	FOREIGN KEY (txtid1) REFERENCES txt(id)
	FOREIGN KEY (txtid2) REFERENCES txt(id)
);
```

Same table but with working dictionary:
```
CREATE TABLE foo_dict_ok (
	id INTEGER PRIMARY KEY,
	txtid1 INTEGER,
	txtid2 INTEGER
	CONSTRAINT foo_dict_ok_FK_1 FOREIGN KEY (txtid1) REFERENCES txt(id),
	CONSTRAINT foo_dict_ok_FK_2 FOREIGN KEY (txtid2) REFERENCES txt(id)
);
```

Database: SQLite
DBeaver version: 7.0.1

**Comment by kseniiaguzeeva** [comment]
@kezyr 2nd and 3d statements give me a mistake when trying to execute.
Are you sure that this statement is successfully executed?:
CREATE TABLE foo_dict_ok (
	id INTEGER PRIMARY KEY,
	txtid1 INTEGER,
	txtid2 INTEGER
	CONSTRAINT foo_dict_ok_FK_1 FOREIGN KEY (txtid1) REFERENCES txt(id),
	CONSTRAINT foo_dict_ok_FK_2 FOREIGN KEY (txtid2) REFERENCES txt(id)
);

**Comment by kezyr** [comment]
@kseniiaguzeeva thank you yes there is a small mistake - missing columns. Here is the correct tested 2nd code:
```
CREATE TABLE foo_dict_bug (
	id INTEGER PRIMARY KEY,
	txtid1 INTEGER,
	txtid2 INTEGER,
	FOREIGN KEY (txtid1) REFERENCES txt(id),
	FOREIGN KEY (txtid2) REFERENCES txt(id)
);
```

Here is corrected 3rd code block:
```
CREATE TABLE foo_dict_ok (
	id INTEGER PRIMARY KEY,
	txtid1 INTEGER,
	txtid2 INTEGER,
	CONSTRAINT foo_dict_ok_FK_1 FOREIGN KEY (txtid1) REFERENCES txt(id),
	CONSTRAINT foo_dict_ok_FK_2 FOREIGN KEY (txtid2) REFERENCES txt(id)
);
```

I am sorry for mistakes in code - I believed I can write it without testing. Now my codes works I double tested it... You can see the Dictionary problem.

**Comment by kseniiaguzeeva** [comment]
I see both tables. Or do you mean smth other? Please see pic.
![dbeaver_h2Jdfn0aAH](https://user-images.githubusercontent.com/51405061/77909661-69911c80-7296-11ea-8104-8cfa7789ef93.png)

**Comment by kezyr** [comment]
Yes, I mean problem that with one table I can see dictionary for foreign keys during insert/edit of rows and with other I can not see. See pictures:
![image](https://user-images.githubusercontent.com/62434319/77911128-980bf900-7290-11ea-8133-687ff2494142.png)

![image](https://user-images.githubusercontent.com/62434319/77911198-b671f480-7290-11ea-88ff-bc752cad6688.png)

**Comment by kezyr** [comment]
This is the main difference between tables as seen in DBeaver:

![image](https://user-images.githubusercontent.com/62434319/77911410-0c469c80-7291-11ea-8498-09580f482183.png)

![image](https://user-images.githubusercontent.com/62434319/77911506-326c3c80-7291-11ea-9cd4-2c14b2657797.png)

**Comment by kseniiaguzeeva** [comment]
Now I see. Thank you for the bug report.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
