### ISSUE TITLE
DBeaver becomes irresponsive when scrolling through file with one very long line (MacOS)

### ISSUE THREAD

**Issue by MathiasVersichele** [dbeaver/dbeaver#8287]
Hi, I love DBeaver as an environment, but I've had lots of trouble with SQL files that contain long lines. I attached a file to this ticket. When I open it in Beaver 7.0.1 and try scroll to the bottom, it freezes up when it reaches line 168, and stays irresponsive for minutes almost melting my cpu.

Is this a bug, or a known limitation ?

[dbeaver_crash.txt](https://github.com/dbeaver/dbeaver/files/4394006/dbeaver_crash.txt)

**Comment by MathiasVersichele** [comment]
I run macOS High Sierra (10.13.6)

**Comment by uslss** [comment]
Hi @MathiasVersichele ,
cannot reproduce it. Is it still actual for you?

Sorry for the late response

**Comment by uslss** [comment]
probably similar to #7777 .
Closed as duplicate
