### ISSUE TITLE
autocomplete not closing

### ISSUE THREAD

**Issue by rdenxx** [dbeaver/dbeaver#8290]
dbeaver v7, firebird

in the database navigator table data browser entering filter criteria the autocomplete has become annoying by not going away when it should

![shot1](https://user-images.githubusercontent.com/19288921/77818851-0629b200-7111-11ea-9449-a130ffd7c4a2.png)
start typing a name, auto complete shows is OK

![shot2](https://user-images.githubusercontent.com/19288921/77818864-193c8200-7111-11ea-9426-f640fcc599f4.png)
but now I've finished typing the name and typed the close brace, why is auto complete still showing

![shot3](https://user-images.githubusercontent.com/19288921/77818883-35d8ba00-7111-11ea-8bda-7fa27aa60035.png)
typed a space, autocomplete still showing, why?

![shot4](https://user-images.githubusercontent.com/19288921/77818890-49842080-7111-11ea-8ad2-ec48922d5343.png)
now I press Enter as if to execute the filter (yeah I know it's not a complete statement yet)
..but autocomplete has decided to insert what it felt like, so now I've got to go back and erase the added thing

seems this is a new behavior in 7, don't remember earlier versions having this

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

To reproduce you can use Firebird table COUNTRY.
_Steps:
1. Type in filter field "currency ="
2. Press Space
3. Press Enter
P.S. it is reproduced in different databases._

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
