### ISSUE TITLE
View could not be opened: org.jkiss.dbeaver.tasks

### ISSUE THREAD

**Issue by wo4861069** [dbeaver/dbeaver#8293]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Include any warning/errors/backtraces from the logs

Out of order  hint View could not be opened: org.jkiss.dbeaver.tasks

**Comment by kseniiaguzeeva** [comment]
@wo4861069 Please write steps to reproduce.

**Comment by uslss** [comment]
there is no update on ticket for a long time. ticket closed.
if issue is still actual for you - feel free to reopen the ticket
