### ISSUE TITLE
Isolation level drop-down values in Edit connection (Postgres) multiplies after 'Test connection'

### ISSUE THREAD

**Issue by remibos** [dbeaver/dbeaver#8295]
#### System information: 
- MacOS Mojave 10.14.6
- DBeaver version - 7.0.1

#### Connection specification:
- Postgres

#### Describe the problem you're observing / Steps to reproduce:
1. In a existing Postgres connection right click the connection and click 'Edit Connection'
2. In the Connection Settings -> Initialisation section you will find the Isolation Level drop down box
3. Default you see 4 values here.
4. Now click the Test Connection... button on the left bottom section of the Edit Connection pop-up
5. You can see that the values in the Isolation Level drop down box  are now duplicated. Looks like they are appended instead of replaced during the test connection. You can keep clicking the test connection button and the list in the drop down is keep getting longer

See image attached

![image](https://user-images.githubusercontent.com/62850715/77856683-1917b180-71f9-11ea-9e08-f484b1867917.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
