### ISSUE TITLE
[MySQL] User with the name of the existing user could be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8298]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.0.1

#### Connection specification:
- Database name and version MySQL, MariaDB

#### Steps to reproduce, if exist:
1. Try to create new user - name by default is "user" and user with the same name is already created
2. Check some privileges and save newly created user - changes are saved without any error message
3. Refresh User tab - newly created user disappears

**Comment by mkgrgis** [comment]
The same for postgres. It seems for all DBs with metaobject "user".

**Comment by serge-rider** [comment]
Fixed for MySQL.
Can't reproduce this issue for PG. It ha very different UI. You can try to create user with the same name but it will fail (with server error).

**Comment by mkgrgis** [comment]
Yes, i have tried, Dbeaver "pg create user" UI is not similar to MySQL. But we can check before server error for many DB's.

**Comment by uslss** [comment]
verified
