### ISSUE TITLE
Bootstrap query, PostgreSQL "search_path" setting incorrectly overwritten by changing script data source

### ISSUE THREAD

**Issue by tsiuch-acp** [dbeaver/dbeaver#8308]
#### System information: 
- Operating system (distribution) and version: **WIN10 64-bit**
- DBeaver version **Version 7.0.1.202003211804**
- Additional extensions: **nothing extra installed**

#### Connection specification:
- Database name and version: **PostgreSQL v.12**
- Driver name: **Java JDBC 4.2 (JRE 8+) driver for PostgreSQL version 42.2.5**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - **NO**

#### Describe the problem you're observing:
I have two connections with bootstrap query [BSQ]:

- **ConnectionA** BSQ:  _set search_path to '**foo**', **'bar'**;_
![ConnA](https://user-images.githubusercontent.com/62951751/78059486-36c85080-738a-11ea-890e-8bf73c7c2799.png)

- **ConnectionB** BSQ: _set search_path to '**lorem**',**'ipsum'**;_
![ConnB](https://user-images.githubusercontent.com/62951751/78059518-4778c680-738a-11ea-8d52-98c3ce0f9a3d.png)

- When I create new script (_script1_) on **ConnectionA**, search path is **correctry** set to **"foo","bar"**.
![Scr1-ConnA](https://user-images.githubusercontent.com/62951751/78064638-595e6780-7392-11ea-96a5-fcb101a54485.png)

- When I create new script (_script2_) on **ConnectionB**, search path is **correctly** set to **"lorem","ipsum"**.
![Scr2-ConnB](https://user-images.githubusercontent.com/62951751/78064665-64b19300-7392-11ea-9c7b-a9a4c15028f1.png)

- **But** when I change DataSource on already connected script (ex. script1) to another connection (ex. ConnectionB) search path is **incorrectly** **set to "foo","lorem","ipsum"!!! instead of "lorem","ipsum"**. 
![Scr1-ConnB-error](https://user-images.githubusercontent.com/62951751/78070884-d55dad00-739c-11ea-9f1f-a1eef4b96cce.png)

**Problem** is, that in such situation Query Manager shows that bootstrap query for ConnectionB is executed properly, but after this, some embeded search_path is set. That last/wrong search_path overwrites that good one and is redundant.
I suppose that problem only applies to 'search_path' not other types of bootstrapQry because its responsible for setting ActiveCatalog/.

My observations show that there are two types of "set search path":
- first (lowercase) defined directly in bootstrap query
- second (uppercase) 'embeded' in DBeaver/driver. I've no idea where it comes from.

#### Steps to reproduce, if exist:
```
psql -U postgres -h _IP_ -p _port_ -d postgres
postgres=# create database testdb;
postgres=# create role test_user login password 'pass123';
postgres=# grant connect on database testdb to test_user;
\c test_db
postgres=# create schema foo authorization test_user;
postgres=# create schema bar authorization test_user;
postgres=# create schema lorem authrorization test_user;
postgres=# create schema ipsum authorization test_user;

```

**Comment by tsiuch-acp** [comment]
Setting search path is very important from me. 
Exact target bootstrap query will be:
- SET ROLE XYZ;
- SET SEARCH_PATH to 'A','B','C'; --- required by role XYZ

I can't use feature "Default Schema''. It hast to be set dynamically. 
Search_path in my case is multi-item.
![Default_schema](https://user-images.githubusercontent.com/62951751/78109208-1b485e80-73f9-11ea-9a5e-9b4856f5419b.png)

Setting role works fine. Problem is with setting search_path.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

Steps: 
1. Create 2 connections for Postgres 12
2. Open Query Builder
3. Set bootstrap query **set search_path to 'foo', 'bar';** for Connection 1
4. Set bootstrap query **set search_path to 'lorem','ipsum';** for Connection 2
5. Open new SQL Editor 1 for Connection 1 and execute **SHOW search_path;**
6. Open new SQL Editor 2 for Connection 2 and execute **SHOW search_path;**
7. Change Connection 2 on Connection 1 in SQL Editor 2 and execute **SHOW search_path;** again.

![dbeaver_XImpMelBqp](https://user-images.githubusercontent.com/51405061/78120027-f7454700-7411-11ea-88bf-c8b30cd3e5af.png)

**Comment by serge-rider** [comment]
This happens because of:
1. DBeaver saves active schema for every SQL script. So when you reopen this script active schema is the same as it was before close
1. There is a bug in this routine. We mustn't restore active schema when user changes connection (as it doesn't make sense).

Bug is fixed.
Workaround: disable active schema save/restore:
![image](https://user-images.githubusercontent.com/6398845/80377242-ad7e3e00-88a3-11ea-8ce8-6860961e1da1.png)

**Comment by uslss** [comment]
verified
