### ISSUE TITLE
phoenix didn't show the default table group in linux os

### ISSUE THREAD

**Issue by qq459673705** [dbeaver/dbeaver#8309]
#### System information: 
- ubuntu18.04 lts
- DBeaver 7.01
- Additional extensions

#### Connection specification:
- phoenix
- phoenix-4.14.3-HBase-1.4-client.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no
#### Describe the problem you're observing:
I don't find the default table group when i linked the phoenix db.

**Comment by uslss** [comment]
unfortunately, we've got no env to test it.
Is the issue still reproducible?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual - feel free to reopen it
