### ISSUE TITLE
7.0.1 Executing script using @include hangs

### ISSUE THREAD

**Issue by jdani015** [dbeaver/dbeaver#8313]
#### System information: 
- Operating system (distribution) and version: Windows 7 Pro SP1 64 bit
- DBeaver version: 7.0.1 x64
- Additional extensions

#### Connection specification:
- Database name and version Vertica 8.1
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Steps to reproduce, if exist: Upgraded to 7.0.1 from 6.2.2.  From SQL Editor execute script from @include.  New tab opens displaying code to execute (normal behavior).  Nothing happens.  Worked prior to upgrade.

example:
1) from SQL editor execute the following command:  @include 'path name/sql script name'
2) new SQL editor tab opens displaying code from 'sql script name'
3) expecting script to begin running but it never does.  No messages of any sort displayed.

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
reopened
query execution is endless in case script that mentioned in path is already opened
![2020-04-02_13h14_48](https://user-images.githubusercontent.com/31996417/78237769-71460080-74e4-11ea-97a4-719da61bb08d.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
reopened
script isn't executed at first attempt (if tab with script is closed)
![2020-04-02_14h16_22](https://user-images.githubusercontent.com/31996417/78244270-ef5ad500-74ed-11ea-8564-430df0419691.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
Reopened.
Script that opens in new tab isn't executed automatically. It could be executed manually only
![2020-04-05_14h38_58](https://user-images.githubusercontent.com/31996417/78473721-76f14f80-774b-11ea-89b9-46e75aeed60a.gif)

**Comment by jdani015** [comment]
Hi.  Is there an ETA for fixing this bug?

**Comment by jdani015** [comment]
Hi. Is there an ETA for fixing this bug?

**Comment by uslss** [comment]
hope, the issue will be fixed in the scope of #13180
Close this issue
