### ISSUE TITLE
Parameterized stored procedures wrong argument number

### ISSUE THREAD

**Issue by jgranduel** [dbeaver/dbeaver#8316]
#### System information: 
- Operating system (distribution) and version 
Win10/1909
- DBeaver version
5.3.4, 7.0.0, 7.0.1
- Additional extensions

#### Connection specification:
- Database name and version : PostgreSQL-12.2.1
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I met two issues wihen running stored procedure from the Project window>**Functions** tree. They have a wrong argument number, anonymous parameters (?,?) being added.

Another issue (might be a request) is about `RETURNS TABLE` result. See example below.

#### Steps to reproduce, if exist:
```
create table tbl (a text, b int, c int);
insert into tbl values ('one', 1, 10);

create function get_tbl (param text)
    returns table(a text, b int, c int) as $$
    begin
        return query
        select t.a, t.b, t.c from tbl t where t.a = param;
    end
$$ language plpgsql;

-- (1)
select get_tbl('one');
get_tbl   |
----------|
(one,1,10)|
-- (2)
select * from get_tbl('one');   -- or select * from get_tbl(:param);
a     |b     |c     |
------|------|------|
one   |     1|    10| 
```
In Functions in tree > Execute Stored Procedure, I get extra params in SQL Editor:
```
SELECT public.get_tbl(:param,?,?,?);
````
Where do the "?" come from ? 
How to get result as in query (2), `SELECT * from public.get_tbl(:param);` and get proper grid display as a record, even without opening the query the SQL Editor if optional?

Thanks!

#### Include any warning/errors/backtraces from the logs
NA

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
