### ISSUE TITLE
I10n : small typo in bundle_fr.properties

### ISSUE THREAD

**Issue by jgranduel** [dbeaver/dbeaver#8320]
not an OS or dbeaver per se issue.

#### Describe the problem you're observing:
The tiny `c` in 'pro**c**édure' was lost in translation of `Execute Store Procedure`

plugins\org.jkiss.dbeaver.core\OSGI-INF\l10n\bundle_fr.properties :
```
command.org.jkiss.dbeaver.core.procedure.execute.name = Ex\u00E9cuter la pro\u00E9dure stock\u00E9e
                                                                            ^
```
I find "Exécuter la proédure stockée" very funny, but, well...

#### Update
Found another one :
file: plugins\org.jkiss.dbeaver.ui.editors.data\src\org\jkiss\dbeaver\ui\controls\resultset\internal\ResultSetMessages_fr.properties
```
pref_page_database_resultsets_label_show_connection_name = Afficher le nom de la connexion dans le statu
```
Missing 't' in statu (should be statu**t**)

Thanks

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by jgranduel** [comment]
you're welcome! Thanks
