### ISSUE TITLE
How can I port db-connections to Mac/DBeaver 7.0.1 (.dbeaver-data-sources.xml) 

### ISSUE THREAD

**Issue by MeboGit** [dbeaver/dbeaver#8321]
Hi,

I tried to copy/overwrite .dbeaver-data-sources.xml in ../.dbeaver4/General.

But when restarting DBeaver I still have the old connections even if I delete .dbeaver-data-sources.xml on Mac still the old connections.

So where are the connections held for 7.0.1 or what am I missing?

Thanks and regards

**Comment by mdahlman** [comment]
Probably here:
`~/Library/DBeaverData/workspace6/General/.dbeaver/data-sources.json`

Documented here:
https://github.com/dbeaver/dbeaver/wiki/Admin-Manage-Connections

**Comment by MeboGit** [comment]
Yes, I could not find this for Mac, works find now.
Thank you, Mebo
