### ISSUE TITLE
Booleans not displaying correctly

### ISSUE THREAD

**Issue by g24swint** [dbeaver/dbeaver#8324]
I found one potential issue about alternate forms of boolean, but it seemed tied to language translations for non-English languages.

In Enterprise 7.0, it seems that booleans no longer display correct "true" or "false" but display a unicode non-character. 

Correct behavior in this case would have been to display "false" since the condition is False.

![image](https://user-images.githubusercontent.com/82784/78326189-5fde1200-753f-11ea-9e8e-75a33b5b7d07.png)

#### System information: 
- Windows 10 
- DBeaver 7.0.0

#### Connection specification:
- Postgres 11
- Postgres
- No tunnels

#### Include any warning/errors/backtraces from the logs

Other issues: I found one potential issue about alternate forms of boolean, but it seemed tied to language translations for non-English languages

My issue
In Enterprise 7.0, it seems that booleans no longer display correct "true" or "false" but display a unicode non-character. 

Correct behavior in this case would have been to display "false" since the condition is False.

Screen shot:
![image](https://user-images.githubusercontent.com/82784/78326189-5fde1200-753f-11ea-9e8e-75a33b5b7d07.png)

**Comment by uslss** [comment]
hi @g24swint ,
sorry, didn't catch you. 
Do you talk about this?
![image](https://user-images.githubusercontent.com/31996417/78906713-5fd29a80-7a88-11ea-916d-bdcc473de290.png)

**Comment by g24swint** [comment]
Yes that's correct - I suppose a unicode character is not displaying correctly? I'm on the latest version of Win10, so I'd expect most unicode characters to render correctly. Very odd

**Comment by uslss** [comment]
@g24swint this is not Unicode character, this is icon that shown false value. if the value is true icon changes
![image](https://user-images.githubusercontent.com/31996417/79867983-e91e9100-83e7-11ea-82f5-47308901785c.png)
You could disable this behavior in Preferences.
![image](https://user-images.githubusercontent.com/31996417/79868113-1b2ff300-83e8-11ea-9154-ef2c3588f872.png)

**Comment by g24swint** [comment]
Thanks I've changed it and it looks like it's correct now. I'd vote for the
default being the "standard" true / false presentation.
___________________
Galen S. Swint, Ph.D.
galen.swint@gmail.com

**Comment by uslss** [comment]
thanks for answer.
In case you need some enhancement - feel free to create new ticket
BR
