### ISSUE TITLE
Specials characters in mssql

### ISSUE THREAD

**Issue by loboaureo** [dbeaver/dbeaver#8325]
### System information: 
- Operating system (distribution) and version WIN10 PRO/ENT (Spanish layout)
- DBeaver version 7.0.1

#### Connection specification:
- Database name and version MSSQL

#### Describe your question:
When i execute a query from Dbeaver i don't receive the special characteres as it should be.
A query in dbeaver returns me the following string
El dni estÃ¡ vacÃ­o en el origen
The same query in MS management studio returns
El dni está vacío en el origen

I tried modify the connection options in 
![image](https://user-images.githubusercontent.com/681482/78333942-17e4dc80-758b-11ea-8c32-b53140789194.png)
But nothing happens.

What i'm doing wrong?

Regards

**Comment by uslss** [comment]
unfortunately, cannot reproduce.
could you provide ddl? what datatype is used?

**Comment by loboaureo** [comment]
Sorry, I was on holidays.

After update to 7.0.2 i'm neither can reproduce it
