### ISSUE TITLE
NPE appears when reference panel is opened and source table row selection is changed

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8327]
stem information: 
- Operating system (distribution) and version Win10, Ubuntu
- DBeaver version 7.0.2 EA

#### Connection specification:
- Database name and version SQL Server, MySQL

#### Describe the problem you're observing:
NPE appears when reference panel is opened and other rows have been selected in source table
#### Steps to reproduce, if exist:
1. Open a table with a foreign key
2. Open Reference panel
3. Select 2 or more rows in source table

Actual result:
Error message appeas:
"Update status line" has encountered a problem.
An internal error has occurred.
java.lang.NullPointerException
![DqVElhPOMW](https://user-images.githubusercontent.com/51405061/78363995-69aa5880-75c5-11ea-99a1-e93669d67f5d.gif)
[.log](https://github.com/dbeaver/dbeaver/files/4427372/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4427373/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
