### ISSUE TITLE
section with comments DDL has disappeared while generating table DDL

### ISSUE THREAD

**Issue by plvnv** [dbeaver/dbeaver#8329]
#### System information: 
- Operating system: MacOS, Windows, Linux
- DBeaver version: 7.0.1

#### Connection specification:
- Database name and version: PostgresPro Standart 11.7.1

#### Describe the problem you're observing:
section with comments DDL has disappeared in Dbeaver version 7.0.1 while generating table DDL

#### Steps to reproduce, if exist:
Create table
Add comments to table and columns
Open table properties -> DDL

section with comments DDL has disappeared in Dbeaver version 7.0.1 while generating table DDL

![image](https://user-images.githubusercontent.com/52536610/78366489-3f5a9a00-75c9-11ea-85d2-43055b6eb855.png)

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/78369130-5ef3c180-75cd-11ea-804f-5ae32c250649.png)

**Comment by plvnv** [comment]
Thks! How to enable this by default? (in previous it was default behaviour to show comment DDL)

**Comment by serge-rider** [comment]
Once you enable it it will be saved and enabled by default

**Comment by greenpeas** [comment]
> Once you enable it it will be saved and enabled by default

DB 7.1.2. Postgres. This does not work. I have to turn on the display comments every time. 🤔

**Comment by kseniiaguzeeva** [comment]
You are right, the bug has come back

**Comment by mkgrgis** [comment]
Table with comments there is in Oracle, Postgres, Firebird, MariaDB. MySQL. I think general verifying will be useful. Oracle views has comments too.

**Comment by uslss** [comment]
verified
