### ISSUE TITLE
[SQL Server] Source table doesn't show references

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8330]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.0.2 EA

#### Connection specification:
- Database name and version SQL Server

#### Describe the problem you're observing:
Most probably it correlates with #8327 
Source table doesn't show references.

#### Steps to reproduce, if exist:
1. Create 2 tables with a FK between them
2. Open Reference panel in Source table
3. Open References tab in Properties of Source table
Actual result: 
Reference is not displayed in Reference table and in References tab in Properties

**Comment by serge-rider** [comment]
It is not a bug. References in properties are foreign keys in another tables which refer current one.

Data references panel includes both own FKs and referencing FKs.
