### ISSUE TITLE
Pluggable GIS viewers for datasources

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#8333]
We need to support puggable GIS data viewers for different datasources.
Currently it is not possible to add new viewer and link it to datasource type.

**Comment by mkgrgis** [comment]
What about different tilelayers from http://leaflet-extras.github.io/leaflet-providers/preview/ ?

**Comment by serge-rider** [comment]
I'm not sure what tiles make sense.

However extra tiles can be easily contributed. Just add new tiles definition in this extension: https://github.com/dbeaver/dbeaver/blob/217d095855bf34cc39c0a8fe44eca8aec0f4a554/plugins/org.jkiss.dbeaver.data.gis.view/plugin.xml#L36

It is just a couple of lines in XML. Pull requests are welcome :)
