### ISSUE TITLE
[SQL Server] Execution btns become grey when a bind parameter is used.

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8336]
## System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.2 EA

#### Connection specification:
- Database name and version SQL Server

#### Describe the problem you're observing:
Execution btns become grey after executing a statement with bind parameters.

#### Steps to reproduce, if exist:
1. Execute select * from "table_name" where "column_name" =:test;
2. Insert a valid value in the opened bind parameter window and press ok.

Actual result: Execution btns are grey. Please see gif.
![u7d5cedWow](https://user-images.githubusercontent.com/51405061/78424441-2e1b9700-7676-11ea-9913-0ac109948332.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
