### ISSUE TITLE
Table editing inconvenience

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#8338]
User story is:
1. I open table editor;
2. Begin to edit fields, e.g. setting field comments;
3. Ocasionally I press enter and FIELD edit dialog appears;
4. Okay, I fill comment inside it, closing;
5. Save changes dialog appears;
6. I agreed;
7. Field changes saved, but WHOLE table editor was REFRESHED;
8. So I lost comments, that I wrote while I were in table editor :(

**Comment by uslss** [comment]
hi @plotn ,
thanks for the bug report.
by the way, as a workaround, at step 7 comments are not visible, but if you press save button - previously written comments appear

**Comment by LonwoLonwo** [comment]
Hello @plotn 

Does this issue still actual for you? I can't reproduce it in the latest DBeaver versions.

**Comment by plotn** [comment]
I'll check, Ok.

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still actual for you - feel free to reopen it.
