### ISSUE TITLE
Impossible to open Driver Preferences

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8340]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.0.2 EA

#### Describe the problem you're observing:
Error appears when I try to open Driver Preferences.

#### Steps to reproduce, if exist:
Open Window>Preferences>Drivers>Maven

Actual result: an error appears without any other content.

![g2du7qquke](https://user-images.githubusercontent.com/51405061/78451089-09321e80-768c-11ea-8f8b-43ab9f17cfa0.png)

[.log](https://github.com/dbeaver/dbeaver/files/4431337/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4431338/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
