### ISSUE TITLE
DBeaver 7.0.2 - Unable to install DevStyle

### ISSUE THREAD

**Issue by PratimGhosh86** [dbeaver/dbeaver#8345]
#### System information: 
- `Windows 10 Pro 1909 18363.753`
- `dbeaver-ce-7.0.2-win32.win32.x86_64.zip`
- `openjdk 11.0.6`

#### Steps to reproduce:

1. Download and unzip the [distribution](https://github.com/dbeaver/dbeaver/releases/download/7.0.2/dbeaver-ce-7.0.2-win32.win32.x86_64.zip) into a folder
2. Launch `dbeaver.exe`
3. Navigate to `Help > Install New Software`
4. Select `Darkest Dark` repository
5. Select `DevStyle` and hit `Next`

#### Details:
```
Cannot complete the install because of a conflicting dependency.
  Software being installed: DevStyle (includes Darkest Dark Theme) 1.11.0.202003261823 (com.genuitec.eclipse.theming.feature.feature.group 1.11.0.202003261823)
  Software currently installed: DBeaver 7.0.2.202004051509 (org.jkiss.dbeaver.core.product 7.0.2.202004051509)
  Only one of the following can be installed at once: 
    Apache Ant minimum package 1.10.0 (org.apache.ant 1.10.0)
    Apache Ant 1.10.7.v20190926-0324 (org.apache.ant 1.10.7.v20190926-0324)
  Cannot satisfy dependency:
    From: DevStyle (includes Darkest Dark Theme) 1.11.0.202003261823 (com.genuitec.eclipse.theming.feature.feature.group 1.11.0.202003261823)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group 4.6.0
  Cannot satisfy dependency:
    From: Eclipse Platform 4.14.0.v20191210-0610 (org.eclipse.platform.feature.group 4.14.0.v20191210-0610)
    To: org.eclipse.equinox.p2.iu; org.apache.ant [1.10.7.v20190926-0324,1.10.7.v20190926-0324]
  Cannot satisfy dependency:
    From: DBeaver Community Edition 7.0.2.202004051509 (org.jkiss.dbeaver.ce.feature.feature.group 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [7.0.2.202004051509,7.0.2.202004051509]
  Cannot satisfy dependency:
    From: DBeaver 7.0.2.202004051509 (org.jkiss.dbeaver.core.product 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [7.0.2.202004051509,7.0.2.202004051509]
  Cannot satisfy dependency:
    From: DBeaver RCP 2.1.105.202004051509 (org.jkiss.dbeaver.rcp.feature.feature.group 2.1.105.202004051509)
    To: org.eclipse.equinox.p2.iu; org.apache.ant [1.10.0,1.10.0]
  Cannot satisfy dependency:
    From: DBeaver Standalone 7.0.2.202004051509 (org.jkiss.dbeaver.standalone.feature.feature.group 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.rcp.feature.feature.group [2.1.105.202004051509,2.1.105.202004051509]
```

Works fine with `DBeaver 7.0.1` with the above system configuration.

**Comment by ceesvl** [comment]
I got something similar with installing DBeaver Git extension. Also "Cannot satisfy dependency"

Cannot complete the install because of a conflicting dependency.
  Software being installed: DBeaver Git support 1.0.18.202004051509 (org.jkiss.dbeaver.git.feature.feature.group 1.0.18.202004051509)
  Software currently installed: DBeaver 7.0.2.202004051509 (org.jkiss.dbeaver.core.product 7.0.2.202004051509)
  Only one of the following can be installed at once: 
    Apache Ant minimum package 1.10.0 (org.apache.ant 1.10.0)
    Apache Ant 1.10.7.v20190926-0324 (org.apache.ant 1.10.7.v20190926-0324)
  Cannot satisfy dependency:
    From: Git integration for Eclipse - UI 5.6.0.201912101111-r (org.eclipse.egit.ui 5.6.0.201912101111-r)
    To: osgi.bundle; org.apache.ant [1.10.5,2.0.0)
  Cannot satisfy dependency:
    From: DBeaver Community Edition 7.0.2.202004051509 (org.jkiss.dbeaver.ce.feature.feature.group 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [7.0.2.202004051509,7.0.2.202004051509]
  Cannot satisfy dependency:
    From: DBeaver 7.0.2.202004051509 (org.jkiss.dbeaver.core.product 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [7.0.2.202004051509,7.0.2.202004051509]
  Cannot satisfy dependency:
    From: DBeaver Git support 1.0.18.202004051509 (org.jkiss.dbeaver.git.feature.feature.group 1.0.18.202004051509)
    To: org.eclipse.equinox.p2.iu; org.eclipse.egit.ui [5.6.0.201912101111-r,5.6.0.201912101111-r]
  Cannot satisfy dependency:
    From: DBeaver RCP 2.1.105.202004051509 (org.jkiss.dbeaver.rcp.feature.feature.group 2.1.105.202004051509)
    To: org.eclipse.equinox.p2.iu; org.apache.ant [1.10.0,1.10.0]
  Cannot satisfy dependency:
    From: DBeaver Standalone 7.0.2.202004051509 (org.jkiss.dbeaver.standalone.feature.feature.group 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.rcp.feature.feature.group [2.1.105.202004051509,2.1.105.202004051509]

**Comment by serge-rider** [comment]
Thanks for the bug report. 
It is a side effect of #8274 .

**Comment by kseniiaguzeeva** [comment]
Unfortunately I do not see any visible changes after installing Darkest Dark Theme ( http://www.genuitec.com/updates/devstyle/ci/)

![m3Mv9SWMvm](https://user-images.githubusercontent.com/51405061/78582813-87cebd80-783e-11ea-95c6-cec6f4ee11c1.png)

**Comment by serge-rider** [comment]
If you can install DevStyle then problem is resolved.

**Comment by kseniiaguzeeva** [comment]
Ok. Thank you.

**Comment by stu177** [comment]
I'm getting this same issue on 7.0.2:

````
Cannot complete the install because of a conflicting dependency.
  Software being installed: DevStyle (includes Darkest Dark Theme) 1.11.0.202003261823 (com.genuitec.eclipse.theming.feature.feature.group 1.11.0.202003261823)
  Software currently installed: DBeaver 7.0.2.202004051509 (org.jkiss.dbeaver.core.product 7.0.2.202004051509)
  Only one of the following can be installed at once: 
    Apache Ant minimum package 1.10.0 (org.apache.ant 1.10.0)
    Apache Ant 1.10.7.v20190926-0324 (org.apache.ant 1.10.7.v20190926-0324)
  Cannot satisfy dependency:
    From: DevStyle (includes Darkest Dark Theme) 1.11.0.202003261823 (com.genuitec.eclipse.theming.feature.feature.group 1.11.0.202003261823)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group 4.6.0
  Cannot satisfy dependency:
    From: Eclipse Platform 4.14.0.v20191210-0610 (org.eclipse.platform.feature.group 4.14.0.v20191210-0610)
    To: org.eclipse.equinox.p2.iu; org.apache.ant [1.10.7.v20190926-0324,1.10.7.v20190926-0324]
  Cannot satisfy dependency:
    From: DBeaver Community Edition 7.0.2.202004051509 (org.jkiss.dbeaver.ce.feature.feature.group 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [7.0.2.202004051509,7.0.2.202004051509]
  Cannot satisfy dependency:
    From: DBeaver 7.0.2.202004051509 (org.jkiss.dbeaver.core.product 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [7.0.2.202004051509,7.0.2.202004051509]
  Cannot satisfy dependency:
    From: DBeaver RCP 2.1.105.202004051509 (org.jkiss.dbeaver.rcp.feature.feature.group 2.1.105.202004051509)
    To: org.eclipse.equinox.p2.iu; org.apache.ant [1.10.0,1.10.0]
  Cannot satisfy dependency:
    From: DBeaver Standalone 7.0.2.202004051509 (org.jkiss.dbeaver.standalone.feature.feature.group 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.rcp.feature.feature.group [2.1.105.202004051509,2.1.105.202004051509]
````

Rolling back to 7.0.1 and installing these works so definitely seems to be introduced in 7.0.2.

**Comment by mmorris-sd** [comment]
The timing of this bug is really bad.  We just recently had our entire organization (200 users) switch to DBeaver expressly for the GIT support.  Can you please expedite a fix for this.  Our users downloaded the latest CE version (7.0..2) and could not load the GIT plugin.  We need this urgently.

**Comment by joaomath** [comment]
I can confirm this on 7.0.2, used previous versions without any problem, now i'm getting this very same error. Currently i'm using Linux Mint 19 Cinnamon.

`Cannot complete the install because of a conflicting dependency.
  Software being installed: DevStyle (includes Darkest Dark Theme) 1.11.0.202003261823 (com.genuitec.eclipse.theming.feature.feature.group 1.11.0.202003261823)
  Software currently installed: DBeaver 7.0.2.202004051509 (org.jkiss.dbeaver.core.product 7.0.2.202004051509)
  Only one of the following can be installed at once: 
    Apache Ant minimum package 1.10.0 (org.apache.ant 1.10.0)
    Apache Ant 1.10.6.v20190516-0412 (org.apache.ant 1.10.6.v20190516-0412)
  Only one of the following can be installed at once: 
    Eclipse IDE UI Application 1.3.300.v20190513-2118 (org.eclipse.ui.ide.application 1.3.300.v20190513-2118)
    Eclipse IDE UI Application 1.3.400.v20190818-1234 (org.eclipse.ui.ide.application 1.3.400.v20190818-1234)
    Eclipse IDE UI Application 1.3.500.v20191122-2109 (org.eclipse.ui.ide.application 1.3.500.v20191122-2109)
    Eclipse IDE UI Application 1.3.500.v20191014-1638 (org.eclipse.ui.ide.application 1.3.500.v20191014-1638)
  Cannot satisfy dependency:
    From: DevStyle (includes Darkest Dark Theme) 1.11.0.202003261823 (com.genuitec.eclipse.theming.feature.feature.group 1.11.0.202003261823)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group 4.6.0
  Cannot satisfy dependency:
    From: Eclipse Platform 4.12.0.v20190605-1801 (org.eclipse.platform.feature.group 4.12.0.v20190605-1801)
    To: org.eclipse.equinox.p2.iu; org.eclipse.ui.ide.application [1.3.300.v20190513-2118,1.3.300.v20190513-2118]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.13.0.v20190916-1323 (org.eclipse.platform.feature.group 4.13.0.v20190916-1323)
    To: org.eclipse.equinox.p2.iu; org.eclipse.ui.ide.application [1.3.400.v20190818-1234,1.3.400.v20190818-1234]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.14.0.v20191101-0301 (org.eclipse.platform.feature.group 4.14.0.v20191101-0301)
    To: org.eclipse.equinox.p2.iu; org.eclipse.ui.ide.application [1.3.500.v20191014-1638,1.3.500.v20191014-1638]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.14.0.v20191210-0610 (org.eclipse.platform.feature.group 4.14.0.v20191210-0610)
    To: org.eclipse.equinox.p2.iu; org.apache.ant [1.10.7.v20190926-0324,1.10.7.v20190926-0324]
  Cannot satisfy dependency:
    From: DBeaver Community Edition 7.0.2.202004051509 (org.jkiss.dbeaver.ce.feature.feature.group 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [7.0.2.202004051509,7.0.2.202004051509]
  Cannot satisfy dependency:
    From: DBeaver 7.0.2.202004051509 (org.jkiss.dbeaver.core.product 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [7.0.2.202004051509,7.0.2.202004051509]
  Cannot satisfy dependency:
    From: DBeaver RCP 2.1.105.202004051509 (org.jkiss.dbeaver.rcp.feature.feature.group 2.1.105.202004051509)
    To: org.eclipse.equinox.p2.iu; org.apache.ant [1.10.0,1.10.0]
  Cannot satisfy dependency:
    From: DBeaver Standalone 7.0.2.202004051509 (org.jkiss.dbeaver.standalone.feature.feature.group 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.eclipse.ui.ide.application [1.3.500.v20191122-2109,1.3.500.v20191122-2109]
  Cannot satisfy dependency:
    From: DBeaver Standalone 7.0.2.202004051509 (org.jkiss.dbeaver.standalone.feature.feature.group 7.0.2.202004051509)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.rcp.feature.feature.group [2.1.105.202004051509,2.1.105.202004051509]`

**Comment by kseniiaguzeeva** [comment]
The bug will be fixed in 7.0.3 version (release date 20.04.20).
If Git is your constant need, I recommend to consider Enterprise Edition https://dbeaver.com/.
Integration with Git is included in Enterprise package and better adapted to it.

Or you can use version 7.0.1 while waiting for release 7.0.3

**Comment by dufferzafar** [comment]
Was this really fixed? I'm still facing errors while trying to install DevStyle.

I'm using DBeaver Version 7.0.4.202005071533

**Comment by kseniiaguzeeva** [comment]
Yes, it was already fixed. Please download thelatest version https://dbeaver.io/download/
![dbeaver_3vjitM37Ve](https://user-images.githubusercontent.com/51405061/84137829-e807f880-aa55-11ea-9b3c-c863593af82a.png)
