### ISSUE TITLE
Exasol View DDL: Whitespace not retained

### ISSUE THREAD

**Issue by kst83** [dbeaver/dbeaver#8352]
#### System information: 
- Windows 10
- 7.0.2

#### Connection specification:
- Exasol
- Exasol JDBC driver 5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When opening a View and switching to the Source Tab, the View DDL doesn't retain whitespace.
Expected: The View DDL should be exactly the same as entered when creating the view.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
