### ISSUE TITLE
Inconsistent number format (0.0000000000000000) starting with 7.0.2

### ISSUE THREAD

**Issue by n8falke** [dbeaver/dbeaver#8353]
#### System information: 
- Windows 10
- DBeaver version 7.0.2

#### Connection specification:
- Oracle Database 12.1
- Oracle Client 12.2

#### Describe the problem you're observing:
NUMBER without length specification is displayed short (0 => "0") when table metadata is not loaded otherwise with leading zeroes (0 => "0,0000000000000000" with German locale).

#### Steps to reproduce, if exist:
```
CREATE TABLE num_format_test
(
  num NUMBER,
  num8 NUMBER(8),
  num8_4 NUMBER(8,4)
);

INSERT INTO num_format_test VALUES ( 0, 0, 0 );

COMMIT; -- btw: manual commit does not reset the commit counter in title

SELECT * FROM num_format_test;
```
Results in:
|NUM|NUM8|NUM8_4|
|---|----|------|
|0|0|0|

After refreshing (F5) Schemas with open tables in Database Navigator (with enabled metadata) the displayed values are:

|NUM|NUM8|NUM8_4|
|---|----|------|
|0,0000000000000000|0|0,0000

**Comment by uslss** [comment]
hi @n8falke ,
it is reproducible for me only if "Use data type scale for fraction digits" is enabled. Is it the same for you?
![image](https://user-images.githubusercontent.com/31996417/78552622-7f5f8e00-7810-11ea-95a0-ff6183c51b5d.png)

**Comment by n8falke** [comment]
Yes, you are right. Without "Use data type scale for fraction digits" it looks good. Can't tell you why I had it turned on.
