### ISSUE TITLE
DBCException: SQL Error [S1009]: Invalid value for getInt() on varchar column

### ISSUE THREAD

**Issue by p4scu41** [dbeaver/dbeaver#8356]
#### System information: 
- Linux version 4.19.0-8-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.98-1 (2020-01-26)
- DBeaver Version Version 7.0.2.202004051509

#### Connection specification:
- MySQL 14.14 Distrib 5.6.33, for debian-linux-gnu (x86_64)
- mysql-connector-java-5.1.44

Getting this error on varchar column when moving to the next page of results on the grid:
> DBCException: SQL Error [S1009]: Invalid value for getInt() - 'user@email.com'

![image](https://user-images.githubusercontent.com/1633236/78570558-c33f9c80-77ea-11ea-91e3-ab7c822160e1.png)

**Comment by uslss** [comment]
hi @p4scu41 , could you post table ddl? or any additional info that could help to reproduce an issue?
thanks in advance

**Comment by p4scu41** [comment]
This is happening with a view, I am using Wordpress and created a view based on the wp_users table

**Comment by uslss** [comment]
@p4scu41 , thanks. but still not reproducible.
could you post ddl? 
As it seen at the screenshot 'user_email' column is non-varchar type

**Comment by uslss** [comment]
there is no update on ticket for a long time. if issue is still actual for you - feel free to reopen the ticket
