### ISSUE TITLE
SQL-Error [42601]

### ISSUE THREAD

**Issue by christophdellavalle** [dbeaver/dbeaver#8357]
DBeaver 7.0.2 on MacBookPro Catilina
I get an SQL-ERROR [42601], which as I found out is "illegal character". 
I removed some Tabstopps from my script, the next error was further down, then I deleted some spaces - and it worked!
Note: I wrote the entire script in DBeaver, no copying from another editor.

Do I have to adjust a setting in order to have no Problems with characters on a Mac?

Thanks a lot for every suggestion.

**Comment by kseniiaguzeeva** [comment]
Am I right, that the Sctipt worked correctly for another OS, but it gave the error on MacBookPro?

**Comment by christophdellavalle** [comment]
No, I wrote this script in DBeaver on the same machine. We had this before on Mac, when opening old scripts written in pgAdmin, we had to remove the comments, then it worked (on the same machine).

**Comment by kseniiaguzeeva** [comment]
Is it possible to send me an example of a statement?

**Comment by christophdellavalle** [comment]
I’ve removed the problematic „characters“, so it is working now. I can’t reproduce it. I’ll send you a script as sonn as I come across the problem again

**Comment by kseniiaguzeeva** [comment]
Ok, please reopen the ticket in this case.
