### ISSUE TITLE
Wrong comment interpretation / not honuring new lines

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#8358]
I think this started to happen since version 7.x

I have to remove comments lines from SQL because this disables part of SQL statement.
Even simple case (as shown below) - adding '-- Comment' at SQL begin disables entire script (doesnt honor new lines between).
This worked great in previous versions.

When I selected to display whitespaces it seems only carriage returns are there (no new lines)
This is not copy / past issue. No new line is shown even if I press Enter

Dbeavier 7.0.1, DB: PgSQL 9.6

![image](https://user-images.githubusercontent.com/5410448/78577994-2d7a3080-782f-11ea-916e-2de877ebac6c.png)

**Whitespaces example**

![image](https://user-images.githubusercontent.com/5410448/78634623-a5cf0900-78a4-11ea-8394-6988a40158b5.png)

**Comment by uslss** [comment]
Hi @maciey , cannot reproduce an issue.
Could you save your script to file and post it? It could be very helpful to investigate an issue

**Comment by maciey** [comment]
Attaching example script 

Again - in Notepad++ i can see only CR but nit LF

![image](https://user-images.githubusercontent.com/5410448/78656055-20108500-78c7-11ea-98ed-ab6068bc29b2.png)


[SQL Comments issue.zip](https://github.com/dbeaver/dbeaver/files/4443379/SQL.Comments.issue.zip)

**Comment by uslss** [comment]
@maciey what os do you use?
do you create script in dbeaver?

**Comment by maciey** [comment]
Im using Windows.

I noticed this happens mostly when I copy query from Visual studio debugger.
So my query in VS looks like 
`\t\t select * \r\n from table`

When I copy it to dbEaver it is well formatted but Im loosing LF's

Maybe this is some track...

**Comment by uslss** [comment]
@maciey 
could you try to use Convert delimiters to option after you paste your script?
![image](https://user-images.githubusercontent.com/31996417/80973529-2ba08e80-8e28-11ea-9141-c502258da5dd.png)

**Comment by maciey** [comment]
Works in this way.
Question is why it changes delimiters once I paste code from Visual Studio Debbugger

**Comment by maciey** [comment]
I confirm changing delimiters fixing problem, but this quite annoying  - have to do that almost each time I paste code from VS

Might this be because string contains special chars ? (\r \n \t) ?

![image](https://user-images.githubusercontent.com/5410448/81656855-ac1e4b00-9437-11ea-8675-86a112686bac.png)

**Comment by maciey** [comment]
I know where is the problem.
Try copy paste below code to editor:

`"select * \r\n from sample_table"`

As you can see in this case we are loosing new lines chars:

![image](https://user-images.githubusercontent.com/5410448/82018301-50490180-9685-11ea-9cc6-7463d0e73953.png)

it should look as follow:

![image](https://user-images.githubusercontent.com/5410448/82018342-65259500-9685-11ea-97e8-a0343fea379b.png)

**Comment by uslss** [comment]
@maciey  thanks for the bug report and investigation

**Comment by serge-rider** [comment]
This issue was caused by SQL extraction routine.

Fixed.

@maciey I've fixed the case with sample query posted. But I didn't test it with Visual Studio Debugger.

**Comment by uslss** [comment]
verified

**Comment by maciey** [comment]
I confirm this was fixed in 7.1.1
Thank you !
