### ISSUE TITLE
Version update: "More Info" button got replaced with "Update"

### ISSUE THREAD

**Issue by swatantra** [dbeaver/dbeaver#8361]
#### System information: 
- Operating system (distribution) and version: Windows 8.1 Enterprise
- DBeaver version: 6.2.3.201910191000
- Additional extensions: N/A

#### Connection specification:
- Database name and version: MySQL 8.x
- Driver name: com.mysql.cj.jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I have been using the DBeaver v6.2.3 for some time. Today I clicked on "Check for updates", and saw a new community edition is ready for download. 
Community Edition 7.0.2 (06.04.2020) Released on April 06, 2020 (today). I downloaded Windows 64 bit installer. During installation, got the popup asking
1. Press "More Info" to open the web page where you can download 7.0.2, While there was no "More info" button.
2. Instead, I see there are two buttons "Upgrade ..." and "Update ...". How does these two differs? A big philosophic question.

#### Steps to reproduce, if exist:
I have been using the DBeaver v6.2.3 for some time. Today I clicked on "Check for updates", and saw a new community edition is ready for download. 
Community Edition 7.0.2 (06.04.2020) Released on April 06, 2020 (today). I downloaded Windows 64 bit installer. During installation, got the popup asking
1. Press "More Info" to open the web page where you can download 7.0.2, While there was no "More info" button.
2. Instead, I see there are two buttons "Upgrade ..." and "Update ...". How does these two differs? A big philosophic question.

#### Include any warning/errors/backtraces from the logs

![Uploading dBeaver version update.png…](Version update)

**Comment by swatantra** [comment]
![dBeaver version update](https://user-images.githubusercontent.com/1787572/78586253-789a4080-783b-11ea-8aa2-a665366b2694.png)

**Comment by serge-rider** [comment]
I think this bug was fixed long time ago (in 6.x version)

**Comment by swatantra** [comment]
If it was fixed in 6.x, then how come this popped. Please checkout the screen attached.

**Comment by uslss** [comment]
hi @swatantra , this issue was fixed in 6.2.5 only in scope of #7155, it is the reason error appears in 6.2.3.
I'll close this ticket as duplicate.
BR
