### ISSUE TITLE
MySQL: User-defined variables not working

### ISSUE THREAD

**Issue by Nezteb** [dbeaver/dbeaver#8364]
#### System information: 
- Operating system (distribution) and version

Mac OS X 10.14.4

- DBeaver version

7.0.1

#### Connection specification:
- Database name and version

MySQL 5.6

- Driver name

mysql:mysql-connector-java:RELEASE [5.1.44]

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

Nope.

#### Describe the problem you're observing:

User-defined variables appear do not work, despite them working with SequelPro and MySQL Workbench.

I have the "Enable variables" box checked under `SQL Processing`.

#### Steps to reproduce, if exist:

```
SET @TESTVAR = 21;
SELECT @TESTVAR
```

Result should be a single row/column with "21" in it, but instead DBeaver throws an error.

#### Include any warning/errors/backtraces from the logs

<img width="949" alt="Screen Shot 2020-04-06 at 5 36 04 PM" src="https://user-images.githubusercontent.com/3588798/78611887-8ba61400-782d-11ea-89cf-0acc53c6715b.png">

**Comment by uslss** [comment]
hi @Nezteb ,
could you try to execute script using Alt+X or "Execute SQL Script" button?
![image](https://user-images.githubusercontent.com/31996417/78652377-54d20b80-78ca-11ea-9751-b0c71c8774f2.png)

**Comment by Nezteb** [comment]
Ah, that works. I didn't realize there was a difference between those two. Microsoft SQL Server and MySQL Workbench have a single button/hotkey for both depending on context: "Execute the selected portion of the script or everything, if there is no selection"

If that's the agreed upon functionality of DBeaver, I have no qualms. If anything I'd put in a feature request to combine the two buttons based on context, but it's not a huge deal.
