### ISSUE TITLE
DDL blocking UI

### ISSUE THREAD

**Issue by lhcneto** [dbeaver/dbeaver#8365]
#### System information: 
- Windows 10
- DBeaver Enterprise 7.0.0

#### Connection specification:
- Postgresql 10.7

#### Describe the problem you're observing:
When I try to run a ddl statement by editing the source of a view ou column of a table, the UI blocks. If there's somebody else view the item and I get a metadata lock, my entire UI gets blocked, so I can't even open a new window to kill my own process

#### Steps to reproduce, if exist:
- Start 2 connections
- Create a table
- Open a transaction in Repeatable Read and select from the table
- Open the table editor in DBeaver and try to drop a column (Using a separate connection)

Usually I get around this by copying the ddl and running it as a common sql statement in an open connection. But I'd like to use the editor as it is intended without having this annoying bug.

Let me end on a positive note, DBeaver is an amazing tool, this is just an annoying bug, hopefully it will be fixed in coming releases.

Best,

Luis

**Comment by uslss** [comment]
hi @lhcneto ,
unfortunately cannot reproduce an issue. probably, you could post a video or gif?

**Comment by uslss** [comment]
there is no update on issue for a long time. if it is still actual for you - feel free to reopen the ticket
