### ISSUE TITLE
Dark theme issue with Win10

### ISSUE THREAD

**Issue by yelled1** [dbeaver/dbeaver#8366]
#### System information: 
- Windows 10 Enterprise 19.09 (Using Dark Theme on Windows itself)
- 7.0.2
- vrapper

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/2314710/78617175-8e603380-7844-11ea-89d9-96966f2f7ef2.png)

#### Steps to reproduce, if exist:
Set the Windows to Dark Theme & do same for DBeaver

I cannot read font on the tabs (Properties), Active Data Source, Active Schema.
Tab is the bigger problem than Actives.
Light Green background & White letters just don't work well.
If there is a way to just change the background or font color, I will be good. I have played around few settings but could not find the right setting from "Colors and Fonts" in Properties.
Still an excellent SW by any comparison. I had 1/2 of my colleagues switching it in last few weeks.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by mkgrgis** [comment]
Not only Windows, not only this problem with dark theme https://github.com/dbeaver/dbeaver/issues/8299

**Comment by serge-rider** [comment]
Totally agreed. We need different default background colors for light and dark themes.

**Comment by serge-rider** [comment]
Workaround: set custom connection type color in preferences.

**Comment by uslss** [comment]
issue is still reproducible for DB Navigator
![image](https://user-images.githubusercontent.com/31996417/80470501-c55ccd00-894a-11ea-8635-f23cf56f6cd3.png)

**Comment by serge-rider** [comment]
You probably had a saved connection types config and these colors came from there.
I've added check for old colors, now it should be ok.

Note: if you changed connection type color to some custom value then it will be used in both Light and Dark themes.

**Comment by serge-rider** [comment]
PROD should look like this:
![image](https://user-images.githubusercontent.com/6398845/80627018-f5de5d00-8a57-11ea-9f78-260818bcc7f4.png)

**Comment by uslss** [comment]
verified
