### ISSUE TITLE
DBeaver 7.0.2 When adding a field to a table, the data type is not displayed

### ISSUE THREAD

**Issue by vowor** [dbeaver/dbeaver#8367]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 7.0.2
- Additional extensions 

#### Connection specification:
- Database name and version Phoenix 5.0.0
- Driver name phoenix-5.0.0-HBase-2.0-client.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  
     OpenVPN

#### Describe the problem you're observing:
Data types are not displayed in DBeaver 7.0.2, but data types can be displayed in DBeaver 6.3.3
DBeaver 6.3.3 image
![image](https://user-images.githubusercontent.com/25870084/78639079-ebf58e00-78df-11ea-8cd8-d8d7b47c1252.png)
DBeaver 7.0.2 image
![image](https://user-images.githubusercontent.com/25870084/78639228-23fcd100-78e0-11ea-8c32-f7e1fe107f8c.png)

**Comment by uslss** [comment]
hi @vowor ,
is there any error in error log?

**Comment by vowor** [comment]
> 嗨@vowor，
> 错误日志中是否有任何错误？

There are no errors

**Comment by vowor** [comment]
> hi @vowor ,
> is there any error in error log?

There are no errors.

**Comment by LonwoLonwo** [comment]
Hello, @vowor is problem is still actual in [new DBeaver version](https://dbeaver.io/)? 
Thanks in advance.

This can also be a driver error, it is he who provides the data types for the database. Perhaps an update can help.

**Comment by vowor** [comment]
> Hello, @vowor is problem is still actual in [new DBeaver version](https://dbeaver.io/)?
> Thanks in advance.
> 
> This can also be a driver error, it is he who provides the data types for the database. Perhaps an update can help.

new DBeaver version  still has problems

**Comment by vowor** [comment]
@LonwoLonwo 

> Hello, @vowor is problem is still actual in [new DBeaver version](https://dbeaver.io/)?
> Thanks in advance.
> 
> This can also be a driver error, it is he who provides the data types for the database. Perhaps an update can help.

@LonwoLonwo new DBeaver version still has problems

**Comment by vowor** [comment]
> Hello, @vowor is problem is still actual in [new DBeaver version](https://dbeaver.io/)?
> Thanks in advance.
> 
> This can also be a driver error, it is he who provides the data types for the database. Perhaps an update can help.

@LonwoLonwo There is no problem with the same driver in version 6.3.3

**Comment by LonwoLonwo** [comment]
Now, unfortunately, we do not have a test base. We'll try to change something when base appears

**Comment by uslss** [comment]
@vowor could you check if it is still actual for you against the recent version?

**Comment by uslss** [comment]
There has been no update on the issue for a long time.  If it is still reproducible - feel free to reopen it
