### ISSUE TITLE
Caused by: java.security.NoSuchAlgorithmException: Cannot find any provider supporting 1.2.840.113549.1.5.13

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#8368]
# System information: 
- Debian/Sid
- DBeaver Version 7.0.2.202004051509

#### Connection specification:
- PostgreSQL 12

#### Describe your question:
Hi,

this is sort of a follow-up to issue #2859.
I used the openssl command to convert my key into DER, but this results in
Caused by: java.security.NoSuchAlgorithmException: Cannot find any provider supporting 1.2.840.113549.1.5.13

Don't know if it is a bug, so I am posting as a question.

**Comment by serge-rider** [comment]
Perhaps you need install this extension: https://marketplace.eclipse.org/content/dbeaver-sshj-support

It contains Bouncycastle security extensions.

**Comment by fgalan** [comment]
I think I have the same problems than @2019-05-10 . I has some problems with the key file, I converti it to DER format but now I get:

![imagen](https://user-images.githubusercontent.com/1534240/79345456-6e5dfd80-7f31-11ea-8a26-4d3950108bd0.png)

I'm using DBeaver in Windows 10 version Versión7.0.2.202004051509

I read your comment @serge-rider but I'm not sure what should do... I'm not using Eclipse, so that link doesn't have too much sense to me. Could you provide some assistance, please? Thanks!

**Comment by 2019-05-10** [comment]
> I read your comment @serge-rider but I'm not sure what should do... I'm not using Eclipse, so that link doesn't have too much sense to me. Could you provide some assistance, please? Thanks!

DBeaver is based on Eclipse RCP, hence you can install Eclipse plugins. 
I did not try this (after trying several things suddenly the certificate worked and I couldn't even repoduce the issue anymore).
But given that @serge-rider posted a Marketplace link, you should be able to install from there easily.
- open the URL in your browser while DBeaver runs
- click and hold the "Install" button and drag to DBeaver
![Screenshot_20200415_195354](https://user-images.githubusercontent.com/50481865/79370575-35cf1b80-7f53-11ea-9f45-5d3db2eab52c.png)

**Comment by fgalan** [comment]
At the end I solved the problem without installing any new plugin.

It seems that converting to DER is not enough, the `-nocrypt` parameter has to be specified. This is the command I used:

```
openssl pkcs8 -topk8 -inform PEM -outform DER -nocrypt -in postgresql.key -out postgresql.unprotected.pk8
```

I'm posting here, in the hope it can be useful to other people :)

**Comment by xorb0ss** [comment]
Can confirm @fgalan solution works!

**Comment by Lauviah0622** [comment]
2022 still has problem in using postgreSQL with ssl, but @fgalan solution is work fine !!
