### ISSUE TITLE
Error when opening SQL Editor

### ISSUE THREAD

**Issue by abhishek-pandey** [dbeaver/dbeaver#8371]
#### System information: 
- Operating system (distribution) and version: Win 10 64 bit
- DBeaver version: 7.0.2
- Additional extensions: None
bcprov-ext-jdk15on-160.jar
OpenClient_15.5-ESD7_win64\jConnect-7_0\classes\jconn4.jar

#### Connection specification:
- Database name and version: Sysbase jConnect
- Driver name: com.sybase.jdbc4.jdbc.SybDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I can successfully connect to server and browse databases/tables/rows. But when i try to launch the SQL Editor, it fails with the error below.

#### Include any warning/errors/backtraces from the logs

Can't open editor connection

Reason:
JZ006: Caught IOException: java.io.IOException: JZ0TS: Truncation error trying to send DBeaver 7.0.2 - SQLEditor <Script.sql>.

**Comment by uslss** [comment]
Hi @abhishek-pandey ,
cannot reproduce an issue. Does it happen always or any special steps are needed?

**Comment by uslss** [comment]
there is no update on ticket for a long time.
if issue is still actual for you - feel free to reopen the ticket with additional info that could help to investigate the ticket

**Comment by jorgediazjd** [comment]
the problem still occurs.

Can't open editor connection

Razón:
 JZ006: Se ha detectado IOException: java.io.IOException: JZ0TS: Error de truncamiento al intentar enviar DBeaver 7.2.5 - SQLEditor <Script-7.sql>.

**Comment by raquelliszet** [comment]
The problem still occurs.
Can't open editor connection

Razón:
 JZ006: Se ha detectado IOException: java.io.IOException: JZ0TS: Error de truncamiento al intentar enviar DBeaver 7.2.5 - SQLEditor <Script-7.sql>.

**Comment by raquelliszet** [comment]
This problem occurs when I want to do a query on a sybase database.

**Comment by jjerin** [comment]
Make sure you're using the correct driver jar version.  the problem stopped after I updated the driver jar file.

**Comment by XuHaijwill** [comment]
> Make sure you're using the correct driver jar version. the problem stopped after I updated the driver jar file.

Could you share the link where can download the correct jconn4.jar?
