### ISSUE TITLE
Column ordering not saved alongside custom filters

### ISSUE THREAD

**Issue by t-o-o-m** [dbeaver/dbeaver#8373]
As already commented here (https://github.com/dbeaver/dbeaver/issues/1569#issuecomment-513507363) column ordering is not saved alongside custom filters. 

saved-data-filter.xml doesn't change whatsoever upon changing column ordering from ASC to DESC, so this is maybe less a bug report than a feature request :)

**Comment by uslss** [comment]
hi @t-o-o-m ,
cannot reproduce it with PostgreSQL. What is your database?

**Comment by t-o-o-m** [comment]
Hi,
doesn't work for me with PostgreSQL and MSSQL. How would a DESC-ordering be reflected in saved-data-filter.xml or is it saved somewhere else? I'm using 7.0.2 on Windows; installed via Chocolatey.

**Comment by austin-beer** [comment]
I just ran into this same issue with **DBeaver 7.0.4** using **PostgreSQL 10**. Steps to reproduce:

- Use the "Customize filters..." button to set a column to be sorted in **descending** order (arrow pointed down).
- Use the "Save filter settings" button to save the filter settings.
- Close and reopen DBeaver.
- Observe that the column is sorted in **ascending** order (arrow pointed up).

It's frustrating to not be able to save the sort order of a column along with the filter settings. Thank you very much in advance for taking a look at this!

**Comment by uslss** [comment]
thanks for the bug report
@austin-beer , thanks for clear steps

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
