### ISSUE TITLE
New Script Button's Plus Sign is Not Big Enough

### ISSUE THREAD

**Issue by Lonniebiz** [dbeaver/dbeaver#8376]
I do not like the "new script" button's icon because it is hard for me to see the plus sign it contains. I use a dark theme and 4K monitors.

I wish this icon was just a giant plus sign instead of a page-icon with a small plus sign.

It is too similar to the icons near it and it is hard to distinguish without moving my head closer to the screen. I've been enduring this for a long time, but finally decided to report.

**Video:** [New-Script-Icon-Plus-Too-Small](https://youtu.be/FpmTBWOzVDg)

**Screenshot:**

![plusNotBigEnough](https://user-images.githubusercontent.com/151919/78772910-12efa680-7958-11ea-89ae-a3f561b17192.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by Lonniebiz** [comment]
@uslss : Thank you for always given fair consideration to suggestions.

**Comment by serge-rider** [comment]
I think  that the main problem is wrong zoom factor in GTK + 4k monitors. Looks like small icon (16x16) was used instead of big one (which looks quite good on 4k monitors).

**Comment by Lonniebiz** [comment]
@serge-rider : It is true that I use 4K monitors. However, I'm connecting to another computer in order to use Dbeaver. Please watch this [video](https://www.youtube.com/watch?v=ku7f_9OnHB8).

**Comment by Lonniebiz** [comment]
@serge-rider : Video link updated to:
https://youtu.be/FpmTBWOzVDg

**Comment by uslss** [comment]
seems to be obsolete for now
![image](https://user-images.githubusercontent.com/31996417/132685657-a2daa99d-1f69-45af-90da-bbe4d2623959.png)

**Comment by Lonniebiz** [comment]
Yes, and I like this much better. Thank you.
