### ISSUE TITLE
Vertical Pane for SQL Edit/Results

### ISSUE THREAD

**Issue by christatedavies** [dbeaver/dbeaver#8377]
I have a large widescreen monitor and I would love to use the space better. When I edit a large SQL it'd be fantastic if I could split the SQL and the results using a vertical pane. At the moment it seems to only be horizontal (and I have looked everywhere for the option/button)

**Describe the solution you'd like**
An option to switch between horizontal or vertical splits.

I attach a redacted copy of my app so you can see it

I use MacOS 10.15.3 (19D76)
I use DBeaver 7.0.2.202004051509

Thanks in advance.

**Comment by christatedavies** [comment]
Sorry - forgot the screenshot. Doh!

![what_a_waste](https://user-images.githubusercontent.com/1114343/78776320-94166000-798f-11ea-94b1-28957b9b6eb3.jpg)

**Comment by uslss** [comment]
hi @christatedavies ,
it is already implemented. You could switch layout to vertical using context menu in sqk editor - Layout- Vertical
![image](https://user-images.githubusercontent.com/31996417/78795697-f71eeb80-79bd-11ea-8a29-3364c88aa171.png)

**Comment by christatedavies** [comment]
Super. I have found it thanks. Closing with a big grin
