### ISSUE TITLE
Add ability to auto-format json-like strings

### ISSUE THREAD

**Issue by wvolkov** [dbeaver/dbeaver#8378]
Current version of dbeaver auto format in value viewer panel only json / jsonb values for postgres db. Sometimes jsons are stored like strings and currently it necessary to cast type from string to jsonb in order to see auto formatted result in the value panel. It would be great if dbeaver could auto format strings that is actually jsonbs. Thanks

**Comment by uslss** [comment]
seems to be duplicate of #7994 .
anyway, thanks for suggestion
