### ISSUE TITLE
Some actions becomes unavailable for some items in case Simple mode view is on

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8379]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.2

#### Describe the problem you're observing:
In case of switching connection view to Simple some button disappear.
MySQL (Paste, Delete, Rename actions):
![image](https://user-images.githubusercontent.com/31996417/78799570-f6d51f00-79c2-11ea-867e-b5677d3b3a13.png)
PostgreSQL:
![image](https://user-images.githubusercontent.com/31996417/78800044-a4e0c900-79c3-11ea-8464-6c1409380012.png)

**Comment by pasqal** [comment]
In the time in the same bug maybe, I can't access on the schema with the simple view. No problem with advanced view.
![image](https://user-images.githubusercontent.com/41213762/78995196-1d6d9400-7b42-11ea-8a6b-fa35dab00bf5.png)

**Comment by serge-rider** [comment]
Metadata modifications (like table/constraints create) are disabled for simple view mode.
Because most of metadata objects (constraints, indexes) are not visible and we want to have consistent UI.
Updated in #8381.

**Comment by uslss** [comment]
verified
