### ISSUE TITLE
Not all items are shown in Data Viewer after switching to Simple mode

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8380]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.2

#### Describe the problem you're observing:
When I switch to Simple mode - only Column are shown in Property Viewer
![image](https://user-images.githubusercontent.com/31996417/78800716-6dbee780-79c4-11ea-9bbe-c5cb113c0986.png)

**Comment by serge-rider** [comment]
This was made on purpose. Simple view removes everything but schemas, tables and columns.
