### ISSUE TITLE
Incorrect icon is shown for newly created database 

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8381]
#### System information: 
- Operating system (distribution) and version  win 10 x64
- DBeaver version 7.0.2

#### Connection specification:
- Database name and version MySQL, Oracle, MariaDB

#### Describe the problem you're observing:
Incorrect icon is shown for newly created db iin Simple View
![image](https://user-images.githubusercontent.com/31996417/78801270-21c07280-79c5-11ea-9885-4f20cf566891.png)

**Comment by serge-rider** [comment]
Metadata modifications are disabled in simple view mode

**Comment by uslss** [comment]
verified
