### ISSUE TITLE
New items (execept databases) couldn't be created in Simple view

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8383]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.2

#### Describe the problem you're observing:
When trying to create items in Simple View error appears:
Schema (PostgreSQL):
![2020-04-08_18h29_07](https://user-images.githubusercontent.com/31996417/78802845-f5a5f100-79c6-11ea-88f9-65893df73f54.gif)
Table (MySQL):
![image](https://user-images.githubusercontent.com/31996417/78802998-2423cc00-79c7-11ea-9a60-5c924935bbd8.png)

**Comment by serge-rider** [comment]
It is not a bug, see #8381
UI inconsistency fixed
