### ISSUE TITLE
Newly created Constraints, FK and others appears in Column tab in Simple View

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8384]
#### System information: 
- Operating system (distribution) and version Win 10 x64
- DBeaver version 7.0.2
#### Describe the problem you're observing:
When I try to create Constraint or FK or index - it appears in Column Tab in Simple view
Constraint (Oracle):
![image](https://user-images.githubusercontent.com/31996417/78803242-6e0cb200-79c7-11ea-8584-6b69f0e4be50.png)
FK (mysql):
![image](https://user-images.githubusercontent.com/31996417/78803880-318d8600-79c8-11ea-8cc3-58866355b7a7.png)
Index (PostgreSQL):
![image](https://user-images.githubusercontent.com/31996417/78803984-4e29be00-79c8-11ea-8fd7-ec6267c42bd3.png)

**Comment by serge-rider** [comment]
Fixed in #8381
