### ISSUE TITLE
Table items begin to shown in DB Navigator in Simple View

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8385]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.2

#### Describe the problem you're observing:
Table items start to shown in db navigator when trying to create some new item like constraints, FK or any others
![image](https://user-images.githubusercontent.com/31996417/78804543-efb10f80-79c8-11ea-8b6c-cc7c76bb8355.png)

**Comment by serge-rider** [comment]
It is not a bug, see #8381
UI inconsistency fixed
