### ISSUE TITLE
wIndows authentication on UBUNTU connecting to sqlserver

### ISSUE THREAD

**Issue by yoboro** [dbeaver/dbeaver#8389]
Hi,

I am trying to connect to a sqlserver from UBUNTU using tool Dbeaver. Can I use windows authentication? is it possible to use a AD account to connect as well? Someone has any good article I can use?

**Comment by uslss** [comment]
Hi @yoboro ,
unfortunately, it is not supported on linux as it depends on native Windows libraries

**Comment by mmorris-sd** [comment]
Hello:
The jTDS JDBC connector works perfectly for windows authentication   There is an option to specify windows authentication that works in Ubuntu

**Comment by serge-rider** [comment]
You could try to use NTLM authentication on linux. It is similar to jtds.
