### ISSUE TITLE
Oracle session termination fails due to incorrect syntax

### ISSUE THREAD

**Issue by kzalewski** [dbeaver/dbeaver#8390]
#### System information: 
- Windows 10
- DBeaver 7.0.2

#### Connection specification:
- Oracle 10g
- JDBC driver: ojdbc8-19.3
- Direct connection to database on port 1521

#### Describe the problem you're observing:
The SQL command that is issued to kill an Oracle session has a small syntax error, which causes the kill operation to fail.  The problem is that Oracle (at least, Oracle 10g) expects a session ID of the form `'<sid>, <serial#>'`, but DBeaver is providing it as `'<sid>, <serial#>, @1'`.  This results in a "missing or invalid session ID" error.

Oracle's own documentation specifies the parameter as `'<sid>, <serial#>'` as shown here: https://www.oracle.com/ocom/groups/public/@otn/documents/webcontent/283689.htm

When I type the same command into SQLPlus, but using (for example) `'511,8765'` as the session ID, instead of what DBeaver is using (`'511,8765,@1'`), the kill command works fine.

#### Steps to reproduce, if exist:
* Go to Database -> Tools -> Sessions
* Right-click on the session that is to be killed and select "Kill Session" from the context menu.
(Alternatively, left-click on the session, then click the "Kill Session" button at the bottom.)
* Click Yes on the confirmation dialog.
* The operation fails with `ORA-00026: missing or invalid session ID`

#### Include any warning/errors/backtraces from the logs
The full error message is:
`Error: 26, Position 0, Sql = ALTER SYSTEM KILL SESSION '511,8765,@1', OriginalSql = ALTER SYSTEM KILL SESSION '511,8765,@1', Error Msg = ORA-00026: missing or invalid session ID`

In this case, I am trying to kill the session with SID=511 and SERIAL#=8765.  It looks like DBeaver is adding `,@1` to the session ID as an optional instanceID, but that optional instanceID is not valid in a non-RAC environment.  It is that inclusion of the optional instanceID that is the cause of the error.

This issue is similar to #6327, where @serge-rider indicates knowledge of the <instanceID> optional parameter in a RAC environment.  However, this optional parameter does not exist in our non-RAC version of Oracle, and instead causes an error.  So I have opened this as a separate ticket.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
@1 means Instance 1. In fact in non-RAC environment it is always 1.
Fixed.

**Comment by uslss** [comment]
verified
