### ISSUE TITLE
CSV export converts characters like apostrophe and hyphan

### ISSUE THREAD

**Issue by DDEversana** [dbeaver/dbeaver#8391]
#### System information: 
- Operating system: windows 10 pro
- DBeaver version: 7.0.1.202003211804

#### Connection specification:
- Database name and version: MariaDB 10.1.19

#### Describe your question:
When I export data from MariaDB table to csv using DBeaver csv export feature some characters are getting messed up. Please find example below:

E.g. See how apostrophe is converted 
Database value: "Alzheimer’s Disease"  CSV export: "Alzheimerâ€™s Disease"
Encoding settings:
![image](https://user-images.githubusercontent.com/56367111/78871850-f772c180-7a65-11ea-841f-edac6b675d85.png)

I tried using ISO-8859-1 encoding but then it replaces apostrophe by question mark. This issue is with some other characters also but I hope the root cause could be same. Could you please let me know what is the workaround to avoid this character conversion?

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce. Please tell which locale do you use?
You can see it here: Properties>Editors>Data Editor>Data Formats
![rW4btkDA3F](https://user-images.githubusercontent.com/51405061/78893800-9c949680-7a74-11ea-9ce5-1a0466446818.png)

**Comment by DDEversana** [comment]
Here you go:
[cid:image001.png@01D60E97.C70F0830]

**Comment by kseniiaguzeeva** [comment]
Could you please attach the picture to the ticket?

**Comment by DDEversana** [comment]
![image](https://user-images.githubusercontent.com/56367111/78901699-594b1f80-7a96-11ea-97d3-dfe2f9979ac4.png)

**Comment by kseniiaguzeeva** [comment]
Is it possible to try our 7.0.2 version https://dbeaver.io/download/? "Alzheimer’s Disease" is exported correctly to CSV,

**Comment by DDEversana** [comment]
I did that. Now I am on Version 7.0.2.202004051509
But issue persist.

**Comment by uslss** [comment]
@DDEversana what encoding is used in application where expoted csv i opened? issue is reproducible for me in case I use UTF-8 in export settings and ANSI in Notepad++
![image](https://user-images.githubusercontent.com/31996417/78987559-0aa19200-7b37-11ea-9b7d-1f1d74c84a6b.png)
