### ISSUE TITLE
[Bug-Mysql] Opening a new Sql Editor in a readonly connection rises error

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#8392]
As from subject: opening a new Sql Editor in a readonly connection rises error below

![image](https://user-images.githubusercontent.com/3930671/78873943-e9b04280-7a4b-11ea-8a2f-c3ded42cd503.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.
Steps:
1. Open SQL Editor for MySQL and select a schema
2. Enable Read-only connection function for the connection

Actual result:
1. schema name dissapears
2. error appears on an attempt to select a schema.

**Comment by serge-rider** [comment]
It is a silly MySQL driver. It doesn't allow to execute USE query in read-only mode (although USE doesn't modify anything).
I've added a workaround.

**Comment by uslss** [comment]
databases still could be changed, but changes didn't applied. Probably, it will be better if it couldn't be possible to change db in this case oth from db navigator and from toolbar

**Comment by serge-rider** [comment]
@uslss I don't think that we should do this because it is clearly a MySQL bug. Read-only connection shouldn't restrict active database change.

**Comment by uslss** [comment]
verified
