### ISSUE TITLE
Connection using complex custom JDBC URL throws I/O error

### ISSUE THREAD

**Issue by Neonchen** [dbeaver/dbeaver#8393]
#### System information: 
- Operating system (distribution) and version: MacOS and Windows 10, both Up-to-date and earlier
- DBeaver version: 7.0.2
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle 11g - 11.2.0.4.0
- Driver name: ojdbc8 12.2.0.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Using a complex connection URL results in IO Error.

Used URL in Connection Settings > Custom:
jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=OFF)(CONNECT_TIMEOUT=5)(RETRY_COUNT=3)(RETRY_DELAY=1)(TRANSPORT_CONNECT_TIMEOUT=3)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=XXXX)(PORT=YYYY))(ADDRESS=(PROTOCOL=TCP)(HOST=XXXX2)(PORT=YYYY2)))(CONNECT_DATA=(SERVICE_NAME=DUMMY)))

#### Include any warning/errors/backtraces from the logs
I/O-Error: The Network Adapter could not establish the connection
  The Network Adapter could not establish the connection
  The Network Adapter could not establish the connection
    Socket read timed out, socket connect lapse 5 ms. XXXX YYYY 3 2 true
    Socket read timed out, socket connect lapse 5 ms. XXXX YYYY 3 2 true
      Socket read timed out
      Socket read timed out

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
I think the problem is in URL itself.
At least I can connect to our test server with custom URL.

Parameters like RETRY_COUNT, RETRY_DELAY and TRANSPORT_CONNECT_TIMEOUT may cause IO errors, try to remove them.
Also you could try to leave just one target host name.

**Comment by Neonchen** [comment]
> I think the problem is in URL itself.
> At least I can connect to our test server with custom URL.
> 
> Parameters like RETRY_COUNT, RETRY_DELAY and TRANSPORT_CONNECT_TIMEOUT may cause IO errors, try to remove them.
> Also you could try to leave just one target host name.

Removing RETRY_COUNT, RETRY_DELAY and TRANSPORT_CONNECT_TIMEOUT worked. Thx!

**Comment by sunlynx** [comment]
But it was woking fine for 7.0.0 with RETRY_COUNT, RETRY_DELAY and TRANSPORT_CONNECT_TIMEOUT

**Comment by fabiogalera** [comment]
JDBC8 changed the TRANSPORT_CONNECT_TIMEOUT to milliseconds. JDBC 7 this value is in seconds

Change your connection string to TRANSPORT_CONNECT_TIMEOUT=5000 and you are grand.
