### ISSUE TITLE
Preferences issues - incorrect strings

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8395]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.2
#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/31996417/78896465-3100f800-7a79-11ea-94d2-4fb8e65f64b7.png)
![image](https://user-images.githubusercontent.com/31996417/78896525-4544f500-7a79-11ea-8d06-ca95b9461cb9.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
