### ISSUE TITLE
[Translation] unacurrate French translation for "wrap text" (Ctrl + Alt + Shift + W)

### ISSUE THREAD

**Issue by robobobeng** [dbeaver/dbeaver#8396]
"Enable wrap text" (default hotkey : Ctrl + Alt + Shift + W) is unaccurately translated in French, to "Césure de mot douce". A better translation would be "Retour à la ligne automatique".

**Comment by uslss** [comment]
thanks for the bug report

**Comment by robobobeng** [comment]
technically it's not a bug but I didn't know how to contribute to a better translation in another way than opening an issue here.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/79218149-a47b7e80-7e58-11ea-82fd-fcd54915d6e1.png)
