### ISSUE TITLE
Cannot save comment on procedure (PostgreSQL)

### ISSUE THREAD

**Issue by megabooster6** [dbeaver/dbeaver#8399]
DBeaver 7.0.2
When we have edited a comment in a procedure window and are going to save it, the resulting SQL comes out malformed (procedure parameters are missed in SQL).
`COMMENT ON PROCEDURE public.test() IS 'Test';`
This leads to the error "ERROR: procedure public.test() does not exist"

Expected SQL is
`COMMENT ON PROCEDURE public.test("integer", "text") IS 'Test';`

This bug is new to 7.0.2; it worked correct in 7.0.1.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
It is a side effect of #8169 fix. Procedure parameters are cleared on save.
Now fixed.

@uslss also please check that #8169 is ok.

**Comment by uslss** [comment]
verified both #8399 and #8169
