### ISSUE TITLE
Do not suggest to save view if I disconnect from database

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#8400]
![image](https://user-images.githubusercontent.com/799021/78917636-d4610580-7a97-11ea-93ac-b08af47abb59.png)

I do not close the program and continue to work.

I just want to reconnect to database. 

DBeaaver should not suggest to save view

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
Yeah, it annoys me too.
Fixed

**Comment by uslss** [comment]
verified
