### ISSUE TITLE
Avoid reconnections and open tabs at startup

### ISSUE THREAD

**Issue by Mizar01** [dbeaver/dbeaver#8405]
Hello. 

I'm using DBeaver 7.0.1, but the same happened to 6.x versions.

I can't find a way to tell Dbeaver to NOT reconnect to the previous databases opened in the last closed session and to NOT open the tabs left open in the last closed session.

I tried to follow and change any possible related setting, but by now, the only way is:
 - remember to close all tabs before closing
 - remember to click on 'Disconnect All' in the Database Menu.

I think there should be an easy way to set this (like 'start with a clean session' option or similar)

**Comment by tati-kru** [comment]
@Mizar01 you can change this behavior in the global preferences: 
![image (9)](https://user-images.githubusercontent.com/30336552/78978360-4e3dd100-7b22-11ea-83a9-8a1bf98ffaec.png)
![image (8)](https://user-images.githubusercontent.com/30336552/78978373-53028500-7b22-11ea-9c9c-da7eeac73e05.png)

**Comment by jdvor** [comment]
It does not seem too fix the issue. Here are my settings:
![s3](https://user-images.githubusercontent.com/5578726/81146472-a8428280-8f78-11ea-9265-b252ec264d94.png)
![s2](https://user-images.githubusercontent.com/5578726/81146478-abd60980-8f78-11ea-8d56-c54599cea019.png)

and it still leads to

![s1](https://user-images.githubusercontent.com/5578726/81146501-b4c6db00-8f78-11ea-805b-4fba404f8858.png)

**Comment by jdvor** [comment]
How do I re-open the issue? Should I create new one and link it?

**Comment by serge-rider** [comment]
Could you write more details. Does it mean that SQL editors still tries to establish connection on activation?
Then please check connection settings (they may overwrite global settings):
![image](https://user-images.githubusercontent.com/6398845/81147950-045ed400-8f84-11ea-8b2a-c08221a8675b.png)

If this still doesn't help then please post error stacktrace (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by jdvor** [comment]
Yes, it just tries to open connection to local postgres (one of my saved connections) every time the application starts.

I don't think I have any connection-level settings overrides:
![s4](https://user-images.githubusercontent.com/5578726/81151517-5c480b80-8f81-11ea-80e3-f7b0d22015b4.png)

Here are the logs:
[logs.zip](https://github.com/dbeaver/dbeaver/files/4585503/logs.zip)

**Comment by jdvor** [comment]
Additional information: at the end I've deleted the offending saved connection. It kept trying to open non-existing host & port until DBeaver restart after which the problem finally disappeared.

**Comment by merlinrabens** [comment]
A little bit late to the party but I observed exactly the same behaviour as @jdvor did. Nothing helped, until I deleted the affected connection completely.

**Comment by florent-bonenfant** [comment]
Hi,

I have a similar problem, all my windows sql are closed, i have change my configuration like your posts.
But at all start of the software i have a message "domaine.xxx.com: Nom ou service inconnu", the database is accessible with a vpn like others projects on my computer.

**Comment by JenuelDev** [comment]
I am also having issues with this one... So I have 5 connections. I turned off other connections, and want to use the other connection. The problem is everytime I do that, every time I open the app it always shows this error.

![Image](https://github.com/user-attachments/assets/10d6d10a-d322-4e71-b33d-c477d94d5a40)

**Comment by ysalitrynskyi** [comment]
Is it possible to change these setting directly in the configuration files somewhere to prevent reopening on launch?

**Comment by LucienChu** [comment]
It is 2026, I had a disconnected db due to I shut down the docker container. And whenever I try to typing queries on a connected db, the Connection refused modal will pop up which stops me from typing. I don't know, it is very annoying.
