### ISSUE TITLE
Error switching active page - 7.0.2 in Db2 zOS connection setting

### ISSUE THREAD

**Issue by GeriZ** [dbeaver/dbeaver#8406]
#### System information: 
- Windows 2016
- DBeaver version 7.0.2
- Office extension

#### Connection specification:
- Db2 zOS
- db2jcc4.jar from Db2 11.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

![image](https://user-images.githubusercontent.com/31589944/78984097-c22da880-7b25-11ea-88e6-dc2de1eec0fe.png)

#### Steps to reproduce, if exist:
Open the connection definition of a Db2 zOS connection. Click on General or Metadata and then click back on Connection settings. After that a window appears with the error message "Error switching active page". This error message does not appear in a Db2 LUW onnection

[drivers.zip](https://github.com/dbeaver/dbeaver/files/4461126/drivers.zip)

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report. I can reproduce it for MySQL, PostgreSQL, SQL Server.

**Comment by serge-rider** [comment]
Fixed

**Comment by GeriZ** [comment]
Thanks for your help, you're really fast ;-))

Could you please also take a look on my other open issue #8291 Import DB2-Connections from 6.0.4 which I've opened two weeks ago. Thanks a lot!!
