### ISSUE TITLE
Just want to output the schema to a .sql file.

### ISSUE THREAD

**Issue by squatcobbler** [dbeaver/dbeaver#8411]
I want to output the schema to an .sql file. No data, just the schema. So the:

DROP DATABASE suchandsuch;
CREATE DATABASE suchandsuch;
DROP TABLE suchandsuch;
CREATE TABLE suchandsuch (
(columns)
);

etc etc.  I can do that in every other DB creating/editing application so obviously I can do it in dbeaver but I can't find either in the docs or just clicking around in the ide.  Sorry for such a simple question but it's not under "export". It can let me export individual tables and their data but I don't care about that, I want the entire schema in a standard .sql file.  

Thanks

**Comment by uslss** [comment]
Hi @squatcobbler ,
this feature is available in EE version only. It is available in Compare/migrate context menu for connection.
You could try Trial 14 day version https://dbeaver.com/

**Comment by squatcobbler** [comment]
Haha ok thanks.  We were going to get licenses for the EE version if we liked the CE version, but the CE version is apparently crippled in a fundamental way and that says something about the company. 

Well, the CE version is open source, right? So I couple presumably just branch it and write that feature in?    

thanks

**Comment by GarryGibson** [comment]
If you multi select all the tables then right click, Generate SQL -> DDL, then it seems to do exactly what you want.

**Comment by Pixy123** [comment]
> If you multi select all the tables then right click, Generate SQL -> DDL, then it seems to do exactly what you want.

With sql server not work, for example not export default value of column
