### ISSUE TITLE
Typo in resource string 

### ISSUE THREAD

**Issue by youloveads** [dbeaver/dbeaver#8414]
#### System information: 
- Operating system (distribution) and version MacOS Catalina
- DBeaver 6.0.0
- Additional extensions

#### Connection specification:
- Snowflake
- Snowflake
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  

#### Describe the problem you're observing:
Title of the dialog is misspelled. Should be "Snowflake connection settings" instead of "Sno**wlf**ake"
#### Steps to reproduce, if exist:
Create new connection. Select Snowflake -> Next
![Screen Shot 2020-04-10 at 1 33 21 PM](https://user-images.githubusercontent.com/19511358/79012327-0c1d8b00-7b34-11ea-9276-d33250c4f7de.png)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/79216716-55cce500-7e56-11ea-92de-e3c8ed713739.png)
