### ISSUE TITLE
Transaction commit: do not ask for select-only sessions.

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#8416]
Currently we ask for transaction commit/rollback for all non-autocommit transactions. Even if only SELECT/SHOW queries were executed.
It is annoying.

**Comment by uslss** [comment]
verified

**Comment by nbros** [comment]
This still seems broken.
I have DBeaver version 21.1.1.202106210824 and I still see the uncommitted transactions count increasing even when I only do a very basic SELECT statement (on a DB2 database).

**Comment by Orco666** [comment]
same in   DBeaver	23.2.1.202309260508	org.jkiss.dbeaver.core.produc
