### ISSUE TITLE
SQL Commands which are running in Dashboard

### ISSUE THREAD

**Issue by dev-santosh** [dbeaver/dbeaver#8417]
Hi Team,
I was thinking if it is possible to have a graph with time and no of SQL command count with info as a label which shows those SQL queries

**Comment by serge-rider** [comment]
What database do you use?

**Comment by surpavan** [comment]
I guess output from the query manager/query history would do suffice this. Good to have thing to know what all things we ran, start and end times and other related stats if we are storing already.
Format could be excel or json or things like that -  but csv will be effected if ',' commas are present in query.
![Capture](https://user-images.githubusercontent.com/37795549/79382282-ea336680-7f80-11ea-81ce-b9f96bfd4ec9.PNG)
