### ISSUE TITLE
DB2 some binary fields not properly formatted since 6.3.5

### ISSUE THREAD

**Issue by gsaulmon** [dbeaver/dbeaver#8418]
Since version 6.3.5 (including 7.x) columns that are defined as datatype `CHAR(13) FOR BIT DATA` no longer get formatted according to the `Binary data formatter` setting (global or connection specific). All 6.3.x versions prior to 6.3.5 work as expected.  

#### System information: 
- Linux / Mac
- DBeaver v6.3.5 or greater
- DB2 LUW driver with default settings

The following examples are with the binary data formatter set to `Hex` formatting.
![image](https://user-images.githubusercontent.com/730440/79085643-599e2180-7d07-11ea-9b03-047baeed5b71.png)

Both columns displayed the same values prior to 6.3.5. But that version or higher show garbled text instead of hex formatting the binary value.

```
SELECT mycolumn AS the_column, hex(mycolumn) AS the_column_cast_as_hex FROM mytable LIMIT 5;
```

Result in version 6.3.4
![image](https://user-images.githubusercontent.com/730440/79085460-a46b6980-7d06-11ea-9886-d5e57d78f229.png)

Result in 6.3.5
![image](https://user-images.githubusercontent.com/730440/79085478-b220ef00-7d06-11ea-8f27-d1544a2c3bc2.png)

**Comment by gsaulmon** [comment]
# Full reproduction steps.

Tested on 7.0.2

#### Optional: setup a db2 server
This will create a db2 server that you can connect to at `localhost` with a database of `testdb`, username of `db2inst1` and password of `test`
```
docker run -it --rm --name db2 --cap-add IPC_LOCK --cap-add IPC_OWNER -p 50000:50000 -e LICENSE=accept -e DB2INST1_PASSWORD=test -e DBNAME=testdb ibmcom/db2
```


### Create a DB2 LUW connection to the db2 instance
- Edit the connection and set Result Sets -> Editors -> Binary data formatter to `Hex`


### Create some data
```
CREATE SCHEMA "MYTEST";
CREATE TABLE "MYTEST"."MYTABLE" ( "MYFIELD" CHAR(13) FOR BIT DATA NOT NULL );
INSERT INTO mytest.MYTABLE  (MYFIELD) VALUES (generate_unique()), (generate_unique());
```

### Query it
```
SELECT myfield, hex(myfield) AS myfield_as_hex FROM mytest.mytable;
```

That query will return with both columns matching and properly formatted as hex; **only until** you disconnect the first time.

_Once you've disconnected/reconnected or closed/reopened dbeaver the formatting is no longer applied to the results of that query._

It should also be noted that creating temporary binary data in a query is always formatted correctly.
Results from `SELECT generate_unique() FROM SYSIBM.sysdummy1;` are formatted correctly

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
@gsaulmon did you check binaries presentation settings:
![image](https://user-images.githubusercontent.com/6398845/81099243-4439a300-8f13-11ea-8b66-2f2635b2f420.png)

Although we didn't change default presentation for a very long time.

**Comment by gsaulmon** [comment]
@serge-rider

I just tested again in a fresh fedora 32 vm using v7.0.4 installed via flatpak.
I can still reproduce it using the steps in my most recent comment. I tested both the global and connection specific binary formatter options.

Once dbeaver is closed/reopened `CHAR(13) FOR BIT DATA` fields are not correctly formatted.

**Comment by gsaulmon** [comment]
It looks like it also will start formatting them correctly once dbeaver fetches more than the first set of 200 results.

Here's a video showing the first 200 results are not being formatted correctly until after dbeaver fetches the next set.


![screencast](https://user-images.githubusercontent.com/730440/81109645-636f0b00-8ee8-11ea-8be2-95726a35e335.gif)

**Comment by serge-rider** [comment]
Yep. I've reproduced this issue

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
