### ISSUE TITLE
“Save” button and "Revert" button

### ISSUE THREAD

**Issue by mxwmwx** [dbeaver/dbeaver#8426]
Dbeaver version:7.0.1
Database:pg or cockroach
Description: I create a new column,and then  I delete it immediately without pressing the "SAVE" or "REVERT" button. I found that the "SAVE" and "REVERT" button are still clickable. 
However,when click "SAVE" button,nothing happened.
when click "REVERT" button, the columns I have deleted come back,but I can't operate any more.
As is shown below:
![image](https://user-images.githubusercontent.com/37258498/79181944-21e6c500-7e40-11ea-881a-130a7588bded.png)
![image](https://user-images.githubusercontent.com/37258498/79181975-332fd180-7e40-11ea-9f88-3600f8a4fb3b.png)
![image](https://user-images.githubusercontent.com/37258498/79182146-b2250a00-7e40-11ea-9749-54f43c90d690.png)

This phenomenon is ubiquitous.I create a new column,and try to modify it without saving.Now,I try to delete it  directly，when click the "SAVE" button,nothing happened.But "REVERT" button is useable.As is shown below: 
create:
![image](https://user-images.githubusercontent.com/37258498/79182344-23fd5380-7e41-11ea-8e4a-0f65e80df687.png)
modify and then delete
![image](https://user-images.githubusercontent.com/37258498/79182386-44c5a900-7e41-11ea-8e33-1876c0b08f2c.png)
revert
![image](https://user-images.githubusercontent.com/37258498/79182643-e0571980-7e41-11ea-819c-6e0e33cb1e3a.png)

I think there must be something wrong  when merging the "modify" and "delete".

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
It is not a bug. Changes merge has to be improved to support such "mutually collapsing" changes.
Unfortunately it is not that easy to do. Moving forward.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
