### ISSUE TITLE
SOCKS proxy setting is not working for Oracle or AWS Redshift connections

### ISSUE THREAD

**Issue by michaelford** [dbeaver/dbeaver#8427]
#### System information: 
- Operating system (distribution) and version MacOS 10.14.6 (18G103)
- DBeaver version: 7.0.0.202003081756 Enterprise
- Additional extensions

#### Connection specification:
- Database name and version: Oracle or AWS Redshift
- Driver name: default drivers provided by DBeaver.
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes, will be using SOCKS when working

#### Describe the problem you're observing:
SOCKS proxy setting is not working for Oracle or AWS Redshift connections

For Oracle, using the ojdbc6.jar instead of ojdbc8.jar appears to be a workaround however I've only tested making the initial connection. Further testing has found it doesn't work for returning the result sets.

#### Steps to reproduce, if exist:
Use SOCKS proxy setting for Oracle or AWS Redshift connections using the default drivers provided by DBeaver. 

#### Include any warning/errors/backtraces from the logs
No errors shown in 'Error log' view.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Proxy config doesn't work when:
- Git integration is installed (it overwrites dbeaver config)
- PostgreSQL in multi-database mode

Fixed.

**Comment by serge-rider** [comment]
Proxy is also doesn't work for newer Oracle drivers as they use new non-blocking sockets (which doesn't support Cocks proxy at all).
The workaround is to downgrade driver version. Unfortunately there are no other solutions at the moment.

**Comment by uslss** [comment]
verified
