### ISSUE TITLE
Error resolving dependencies

### ISSUE THREAD

**Issue by raptr55** [dbeaver/dbeaver#8429]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.0.2.202004051509
- Additional extensions DBeaver Office Support

#### Connection specification:
- Database name and version 
- Driver name Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? VPN

#### Describe the problem you're observing:
![bug (2)](https://user-images.githubusercontent.com/49353954/79207060-7e49e480-7e40-11ea-9f65-85bd9f96e44f.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Driver config fixed.

**Comment by uslss** [comment]
verified
