### ISSUE TITLE
Export database rows as php array

### ISSUE THREAD

**Issue by burzum** [dbeaver/dbeaver#8431]
**Is your feature request related to a problem? Please describe.**
It would be awesome if we would be able to export rows as php array.

**Describe the solution you'd like**
An export option like the others for php arrays. Just add it here?

![image](https://user-images.githubusercontent.com/162789/79226895-6766ba80-7e5f-11ea-882d-ef39df47eaf6.png)

**Describe alternatives you've considered**
Using another tool for the job that has this feature like Maria DB.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
Error appears if Selected columns only option is checked
![image](https://user-images.githubusercontent.com/31996417/86136698-10cf5b00-baf5-11ea-98ce-21468326f2fc.png)

**Comment by uslss** [comment]
verified
