### ISSUE TITLE
Error refreshing node Reason:  java.lang.NullPointerException

### ISSUE THREAD

**Issue by Angelinkaxx** [dbeaver/dbeaver#8432]
#### System information: 
- Linux angelina-Lenovo-ideapad-320-15IKB 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- DBeaver Version 7.0.2.202004051509

#### Connection specification:
- Database name and version: ClickHouse, PostgresQL
- Driver name
 
#### Describe the problem you're observing:
After "refresh" data base - i recieve an error "Error refreshing node Reason:  java.lang.NullPointerException"

**Comment by uslss** [comment]
hi @Angelinkaxx ,
unfortunately cannot reproduce an issue. Could you post video or any special steps that could help to reproduce an issue?

**Comment by uslss** [comment]
there is no update on issue more than a month.
if it is still actual for you - feel free to reopen it
