### ISSUE TITLE
Import DB2-Connections from 6.0.4 

### ISSUE THREAD

**Issue by GeriZ** [dbeaver/dbeaver#8433]
System information:

    Windows 10
    DBeaver 6.0.4 migration to 7.0.1

Connection specification:

    DB2 11.1
    db2jcc4.jar

Describe the problem you're observing:

I've tried to migrate the .dbeaver-data-sources.xml into the new JSON format as described by serge-rider in issue #6599. I've deleted the DBeaverData folder and the old XML file will be migrated during the start of DBeaver 7.0.1. Migration seems to work fine but when I want to connect to an existing DB2 LUW data source a window opens which says that the DB2 LUW driver files are missing and I can download a 11.5 JDBC driver now although I've already had defined a 11.1 driver for this data source in 6.0.4. It seems the migration adds this new driver and sets him as the default driver for DB2 LUW.

![image](https://user-images.githubusercontent.com/31589944/79240054-938b3700-7e71-11ea-824c-b8ba99978428.png)

I've already defined a DB2 11.1 JDBC driver in the old 6.0.4 configuration and I don't want that my dummy users must download a new 11.5 driver or play with the driver settings.

![image](https://user-images.githubusercontent.com/31589944/79240122-a30a8000-7e71-11ea-91f6-ce39aaab4889.png)

I know that I could delete the 11.5 driver in the driver manager. But I want a seamless migration for my users who don't even know what a JDBC driver is ;-) What can I do that the 7.0.1 migration process does not set the 11.5 driver instead of the 11.1 driver as the default driver?

It's interesting that the 11.5 driver will not be shown for DB2 z/OS in the driver manager and the z/OS data sources are working fine.

**Comment by uslss** [comment]
hi @GeriZ ,
probably unchecking of the higlighted option could help you
![image](https://user-images.githubusercontent.com/31996417/79354278-dd911d00-7f44-11ea-8132-e0b3b7a4e611.png)

**Comment by GeriZ** [comment]
Hi Uslss,

this setting is not active in my 6.0.4 installation.  I would need a solution which does not cause interactions with the preferences for my 6.0.4 users after migrating to 7.0.2.  A solution would be that the migration process checks the user definitions for existing Db2 drivers. If a Db2 driver is already defined then it should still be the default driver. If no one is defined then it should add the new Db2 11.5 maven driver.

It's interesting that the new 11.5 maven driver does only appear for Db2 LUW but not for Db2 zOS:

![image](https://user-images.githubusercontent.com/31589944/79452383-5dbc8e80-7fe8-11ea-8dd4-1624c3efd82a.png)


![image](https://user-images.githubusercontent.com/31589944/79452476-7fb61100-7fe8-11ea-98d6-f4d02347b369.png)

Regards
Geri

**Comment by GeriZ** [comment]
Uslss, do you have any idea? Why is the maven driver displayed for Db2 LUW and not for Db2 zOS? It should not be displayed in ALL cases when a driver is already defined....

**Comment by serge-rider** [comment]
@GeriZ you can redefine driver libraries in your DBeaver deployment, see https://github.com/dbeaver/dbeaver/wiki/Admin-Manage-Drivers#provide-predefined-drivers-configuration

You can automate this by patching dbeaver.ini in all end-user deployments.

**Comment by GeriZ** [comment]
Hi Serge-Rider,

this seems to work. Thank you!!!!!

Regards
GeriZ
