### ISSUE TITLE
Easily execute a query across multiple connections

### ISSUE THREAD

**Issue by PopeJareth** [dbeaver/dbeaver#8435]
It is common to need to execute a single query on multiple connections client 1, client 2, dev, prod etc.

Request for an execute method that would take the selected query / script and run on a selected list of connections.

Results could be either displayed across multiple tabs (one tab per connection) or ideally consolidated into a single screen or exported to a csv/output file for viewing.

Ex)
Search for every record across all connections where table id = 11.
Select * from DB.TABLE where id = 11 runs on the selected connections and output is consolidated for review.

To help indicate where the data is from the first column could be the connection name that results came from.

**Comment by uslss** [comment]
Hi @PopeJareth ,
probably you could create task Database - Tasks - Create New Task and choose SQL Script there. You could choose SQL Script and databases you want execute it on

**Comment by PopeJareth** [comment]
The only options I see are below. Thank you for your advice!

-Data Transfer
  -- Type: Data export (looks promising, maybe I am doing something wrong here) 
    --- I am able to add queries but not able to indicate different connections to run the queries on. I am locked into the first selection I made when clicking "Add Query..." 
  -- Type: Data Import
    --- Does not seem applicable.
-MySQL
-- Type: Database export
--- Not allowed to do anything even if selecting a database

<img width="605" alt="capture" src="https://user-images.githubusercontent.com/63672999/79358189-8704ee00-7f06-11ea-8421-356c8a147212.png">

**Comment by uslss** [comment]
@PopeJareth , in case with MySQL you should choose Native client in mentioned window.
btw, in EE version Composite Tasks are implemented. This feature makes possible to execute task that contains simple export tasks you needed. You could try 14 day trial EE version (https://dbeaver.com/)

**Comment by PopeJareth** [comment]
Thank you. I will have to look at the EE version, although I am not sure if this is enough grease to get that rusty wallet open haha.

Thanks again! Have a good day.
