### ISSUE TITLE
Avoid sql editor opening connections

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#8436]
I normaly, as everyone, develop something, try it in DEV, and when done (after tests etc etc etc), I apply it in PROD.
Now, if I re-open a sql file that was last executed in PROD, DBeaver opens the sql file and *automatically* connects to prod.
This can be extremely dangerous.
Is there a way to disable it?

**Comment by surpavan** [comment]
You can disable it by unchecking 'Connect on Editor Activation'
Option is in Windows>Preferences>Editors>SQL Editor pane.

But is acts the same for production and test connections, so no control for prod separately.
