### ISSUE TITLE
data import want to add update option

### ISSUE THREAD

**Issue by ChuTerry** [dbeaver/dbeaver#8437]
First,thanks  for apply this free database tool.
When I use data import to import cvs data  ,I want set options likes :insert data,update data or both insert and update.
but now since the DBeaver 7.0.2 only can insert data，what I want to confirm is whether there is a problem with the way I use this tool or is it not supported temporarily?

**Comment by uslss** [comment]
thanks for suggestion

**Comment by LonwoLonwo** [comment]
@ChuTerry Hello. What database are you using?
We added some update options in this ticket, but not for all databases.
https://github.com/dbeaver/dbeaver/issues/10533

**Comment by uslss** [comment]
there is no update on issue for a long time. 
if the implemented feature doesn't cover your need- feel free to reopen it
