### ISSUE TITLE
An error occurred while restoring a database from a dump.

### ISSUE THREAD

**Issue by ASYOU99** [dbeaver/dbeaver#8440]
#### System information: 
- Operating system (distribution) and version
Win 10 ver. 1909 build-18363.720
- DBeaver version
7.0.0.202003021717
- Additional extensions
No
#### Connection specification:
- Database name and version
postgres v.9.6
- Driver name
PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No
#### Describe the problem you're observing:
 I restore from the tar archive which is made by the standard posgre pg_dump function. It restores everything normally only at the end such an error appears and the start button is active again. if you click cancel the database is restored normally without jambs.

![Screenshot_1](https://user-images.githubusercontent.com/12735688/79344529-a3ba1980-7f38-11ea-970c-31a0133f41b2.png)
![Screenshot_2](https://user-images.githubusercontent.com/12735688/79344534-a452b000-7f38-11ea-86a7-4cc8e0768746.png)
#### Include any warning/errors/backtraces from the logs

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4481552/dbeaver-debug.log)

**Comment by mkgrgis** [comment]
Some issues with postgres restore/dump
https://github.com/dbeaver/dbeaver/issues/8069
https://github.com/dbeaver/dbeaver/issues/8143

**Comment by LonwoLonwo** [comment]
@ASYOU99 i think, this problem solved in https://github.com/dbeaver/dbeaver/issues/9182
if this problem is still actual for you since DBeaver version 7.1.5, you can reopen this ticket
