### ISSUE TITLE
No itens on database navigator for other schema

### ISSUE THREAD

**Issue by RodolfoCCarvalho** [dbeaver/dbeaver#8441]
I'm using DBeaver with a JDBC connection on Oracle. On database navigator only on my schema itens are visible, when I navigate in another schema all groups, such as table, are empty.

My user has privileges to all schemas, I'm using the very same user in other tools and I can access everything from there.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
@RodolfoCCarvalho if it is still reproducible - please check what metadata queries are executed in dbeaver.

You can see them in the Query Manager view (main menu Window->Show View->Query Manager).
You can enable hidden metadata queries in the context menu

**Comment by uslss** [comment]
Issue closed - no updates for a long time.
If it is still actual - feel free to reopen the ticket
