### ISSUE TITLE
Not displaying table data when using extended ASCII characters in object names

### ISSUE THREAD

**Issue by AndrewGabelliTR** [dbeaver/dbeaver#8446]
#### System information: 
- Windows 10 Enterprise 1903
- DBeaver 7.0.0
- None

#### Connection specification:
- Oracle 12c

#### Describe the problem you're observing:

With certain table names the dbeaver sql editor displays null when selecting from columns that contain non-null character data. In both of the examples below, the data can be seen by using the dump function, which returns Typ=1 Len=9 CharacterSet=WE8ISO8859P15: 6d,69,e9,72,63,6f,6c,65,73 in both cases. 

#### Steps to reproduce, if exist:

This snippet causes null to be displayed from the SELECT:

DROP TABLE ÇORDÒBÀ;

CREATE TABLE ÇORDÒBÀ (Ñiño varchar2(30 char));

INSERT INTO ÇORDÒBÀ (Ñiño) values ('miércoles');
COMMIT;

SELECT * FROM ÇORDÒBÀ;

This snippet, which differs only in the table name being one character shorter, works as expected, and the non-null text is displayed by the SELECT:

DROP TABLE ÇORDÒB;

CREATE TABLE ÇORDÒB (Ñiño varchar2(30 char));

INSERT INTO ÇORDÒB (Ñiño) values ('miércoles');
COMMIT;

SELECT * FROM ÇORDÒB;

**Comment by uslss** [comment]
Hi @AndrewGabelliTR ,
unfortunately cannot reproduce an issue. Could you try it against 7.0.3?
![image](https://user-images.githubusercontent.com/31996417/79760259-7e5a5080-8328-11ea-9f8f-b9daef1208da.png)

**Comment by uslss** [comment]
there is no update on issue. if it is still actual for you - feel free to reopen the ticket
