### ISSUE TITLE
Ubuntu - apt tries to update to a lower version

### ISSUE THREAD

**Issue by dcamachoj** [dbeaver/dbeaver#8447]
#### System information: 
- Pop!_OS 18.04 LTS x86_64 (Ubuntu based)
- dbeaver-ce_7.0.2_amd64.deb

#### Connection specification: (NA)
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Problem:
Each time I install/upgrade from deb package, my system indicates that there is an update.
When I go to the Package Manager it shows that it's dbeaver-ce 6.1.0 - feb 25 8368.
And it shouldn't, because I'm installing 7.x.x.

#### Steps to reproduce, if exist:
- Install DBeaver from the downloaded deb installer.
- Wait a minute and the system will indicate that there is an update. Or refresh the package manager to look for updates.

![Screenshot from 2020-04-16 05-40-41](https://user-images.githubusercontent.com/10841852/79441293-0c3ee000-7fa5-11ea-9d64-bef17968ea67.png)
![Screenshot from 2020-04-16 05-40-48](https://user-images.githubusercontent.com/10841852/79441320-13fe8480-7fa5-11ea-8237-898268901947.png)

**Comment by uslss** [comment]
hi @dcamachoj ,
is it still reproducible?

**Comment by uslss** [comment]
there is not any updates for a long time. If issue is still actual for you - feel free to reopen the ticket

**Comment by guilmour-asc** [comment]
Ummmmmm, the problem still exists...

**Comment by p91paul** [comment]
I'd say the bug is in how pop os handles versions, not in dbeaver. It should not propose the repository version if the installed version is greater. Actually, that's pretty unusual because it's not how apt works, so I'm guessing this is a bug in some pop os specific tool.

**Comment by adbarbosa** [comment]
I have the same problem.
when i run `sudo apt upgrade` the output is the following:
The following packages will be DOWNGRADED:
dbeaver-ce
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.
Need to get 0 B/93,7 MB of archives.

I am runing Pop!_OS 21.04 x86_64

**Comment by Knase** [comment]
@adbarbosa  Look this article https://askubuntu.com/questions/18654/how-to-prevent-updating-of-a-specific-package
Run command for lold update:
`echo "dbeaver-ce hold" | sudo dpkg --set-selections`
