### ISSUE TITLE
A second sorted column cannot be returned to a default order

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8450]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.0.3 EA

#### Describe the problem you're observing:
A second sorted column cannot be returned to a default order
#### Steps to reproduce, if exist:
1. Open a table in Data Editor (e.a Exasol RETAIL.MARKETS)
2. Sort a column with repeatable values Asc using column header (e.a AREA)
3. Sort another column Asc, then Desc, then return to default order (e.a LATITUDE)

Expected: the second column returns to default order
Actual result: the second column can be sorted ASC/DESC only.
![jsrsCqk6jr](https://user-images.githubusercontent.com/51405061/79453970-1a1b5200-7ff3-11ea-89a5-83c1abea4989.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
