### ISSUE TITLE
[Oracle] Database type SID couldn't be saved

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8452]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.3 EA

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
When trying to create connection with type SID it couldn't be connected - error appears when trying to connect or Test Connection
![image](https://user-images.githubusercontent.com/31996417/79459973-d299c380-7ffc-11ea-9bf2-6eac1804f8a4.png)
After saving this connection with SID chosen and reopening its properties - Service Name is chosen
![2020-04-16_13h12_10](https://user-images.githubusercontent.com/31996417/79460184-1db3d680-7ffd-11ea-8645-e9ad9d05f63a.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
