### ISSUE TITLE
Data types cannot be colorized

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8453]
#### System information:  
- Operating system (distribution) and version Win10 Home
- DBeaver version 7.0.3 EA

#### Describe the problem you're observing:
Data types cannot be colorized

#### Steps to reproduce, if exist:
1. Open a table with a content in Data Editor
2. Select **Colorize Data Types** in its context menu.

Actual result: no visible changes.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
I still can reproduce the issue ( DBeaver	7.0.3.202004181046	org.jkiss.dbeaver.core.product	null)

**Comment by serge-rider** [comment]
Preferences change handle fixed

**Comment by kseniiaguzeeva** [comment]
verified
