### ISSUE TITLE
[Reference panel] filters icon disappeared

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8454]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.3 EA

#### Describe the problem you're observing:
Filters icon disappeared in column header of Reference panel

#### Steps to reproduce, if exist:
1. open a table with a FK
2. select a column
3. open reference panel

Actual result:
No filter icon in column header in Reference panel
![dbeaver_JDH0B7EWnE](https://user-images.githubusercontent.com/51405061/79466298-0f69b880-8005-11ea-9720-9494ae7aeca4.png)

**Comment by serge-rider** [comment]
It is not a bug, they were removed on purpose. 
Filters were disabled for ref panel long time ago, these icons were rudimentary.
