### ISSUE TITLE
Missing refresh in "table > ddl" - view

### ISSUE THREAD

**Issue by bmaehr** [dbeaver/dbeaver#8455]
If I make a change of DDL by script I would like to refresh the DDL view of the table properties to see the changed DDL.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
Workaround: press `F5`

**Comment by bmaehr** [comment]
> Workaround: press `F5`

I should have thought about this possibility myself. 
It is ok for me to close the ticket.

**Comment by serge-rider** [comment]
I still think we should have unified UI for all tabs including DDL.
So I'll add refresh button there too.

**Comment by uslss** [comment]
verified
