### ISSUE TITLE
[Exasol] Ingoing reference is not displayed in table ERD and Reference panel

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8457]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.3 EA

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
Ingoing reference is not displayed in table ERD and Reference panel

#### Steps to reproduce, if exist:
1. Open a table  which PK is used as FK for another table in Data Editor (e.g. RETAIL.SALES)
2. Select several rows and open Reference panel
3. Try to find the table with FK in dropdown list

Actual result: the table is not displayed in the list
![dbeaver_QgYtUx6YYk](https://user-images.githubusercontent.com/51405061/79468604-cbc47e00-8007-11ea-8337-3d2448d2ba16.png)
![dbeaver_S7rDnL8Arl](https://user-images.githubusercontent.com/51405061/79468609-ccf5ab00-8007-11ea-9837-5de48109f9b7.png)

**Comment by Sargul** [comment]
Could it be that this has been fixed?

I just verified this behavior and wanted to have a detailed look at this.

But when I merged the newest changes from the current dbeaver repository and started debugging I noticed that this bug was gone:

![image](https://user-images.githubusercontent.com/5595511/80912286-3978e580-8d3c-11ea-8a66-7bd16b967399.png)

**Comment by kseniiaguzeeva** [comment]
The issue is in a table with a primary key. If you open table SALES, you do not see ingoing references on it in Dropdown menu of Reference panel.
I created 2 simple tables to show it:
![FLOkoRDxIl](https://user-images.githubusercontent.com/51405061/80957108-31d44200-8e0b-11ea-879c-b4845013254c.gif)

**Comment by ar-jan** [comment]
I confirm the same issue with both PostgreSQL and SQLite. Drop the primary key on the child table, and the parent table will start showing referencing rows from the child table. The reference panel also works correctly with a composite primary key on the child table.

**Comment by ar-jan** [comment]
To clarify: in my test there's no problem with having a primary key in parent table, and referencing it with a foreign key in the child table; it's just the presence of a primary key in the referencing table.

**Comment by ar-jan** [comment]
Ooh, I see it is fixed in the just released 7.0.4.

**Comment by Sargul** [comment]
Fixed in #9131 
![image](https://user-images.githubusercontent.com/5595511/86208427-ce4b6400-bb70-11ea-8553-b6cddcf3986f.png)

![image](https://user-images.githubusercontent.com/5595511/86211342-87606d00-bb76-11ea-9461-8461a08c3a4e.png)
