### ISSUE TITLE
Saved SQL editor

### ISSUE THREAD

**Issue by dinosubasic** [dbeaver/dbeaver#8458]
- win10
- DBeaver 6.00

#### Connection specification:
- DB2 and version
- DB2 iSeries/AS 400 

#### Describe the problem you're observing:
"To open an SQL editor for some connection: * Click this connection in the Database Navigator view and press F3 or click SQL Editor -> SQL Editor on the main menu. Alternatively, you click SQL Editor on the context menu of this connection. DBeaver opens the Choose SQL script editor with saved SQL scripts linked to this connection. CLick the SQL script to open it in a separate tab."

It doesnt work when I work remotely. When i cklick, nothing happen. The "Recent SQl Editor" option works and I have to work non stop in the same editor which becomes too big and orientation is difficult.

**Comment by uslss** [comment]
Hi @dinosubasic ,
could you add screenshot how New SQL Editor pop-up looks for you? Also, could you try if issue is reproducible for you against recent version (7.0.3)?
As for me, New SQL Editor pop-up contains New script button that opens New Editor.
![image](https://user-images.githubusercontent.com/31996417/79754779-bd84a380-8320-11ea-92e8-fa740f0fdf24.png)

**Comment by dinosubasic** [comment]
Because COVID-19, we are working remotely. And when i go remote, i can't see pop-up. In office, it look exactly like yours. Poslano iz programa Pošta za Windows 10 Pošiljatelj: uslssPoslano:20. travnja 2020. 15:05Primatelj: dbeaver/dbeaverKopija: dinosubasic; MentionPredmet: Re: [dbeaver/dbeaver] Saved SQL editor (#8458) Hi @dinosubasic ,could you add screenshot how New SQL Editor pop-up looks for you? Also, could you try if issue is reproducible for you against recent version (7.0.3)?As for me, New SQL Editor pop-up contains New script button that opens New Editor.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 



	
		
			
				
			
		
		
			
				Ova e-pošta je provjerena na viruse Avast protuvirusnim programom.
				www.avast.com

**Comment by uslss** [comment]
did you try to change pop-up size, or it is invisible at all?

**Comment by dinosubasic** [comment]
it is invisible at all Lijepi pozdrav Dino Subašić Pošiljatelj: uslssPoslano:21. travnja 2020. 13:40Primatelj: dbeaver/dbeaverKopija: dinosubasic; MentionPredmet: Re: [dbeaver/dbeaver] Saved SQL editor (#8458) did you try to change pop-up size, or it is invisible at all?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by uslss** [comment]
@dinosubasic try to reset UI Settings using File - Reset UI Settings

**Comment by dinosubasic** [comment]
Ok, I will.

I forget to answer:

Version newer than 6.0.0. isn't working by me. Double click to open
application, the loading screen appears and just goes off. Installer or
zip, result is same.


Dino Subašić

čet, 23. tra 2020. 17:26 uslss <notifications@github.com> je napisao:

**Comment by uslss** [comment]
@dinosubasic ,
could you post logs after you attempt to start version newer then 6.0.0?
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by uslss** [comment]
@dinosubasic ,
could you post logs after you attempt to start version newer then 6.0.0?
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by dinosubasic** [comment]
Sorry, but where can I find logs? I was trying yet, but unsuccessful..

Dino Subašić

pon, 4. svi 2020. 15:39 uslss <notifications@github.com> je napisao:

**Comment by dinosubasic** [comment]
Here is logs (Windows 64 bit (zip) is downloaded this time): !ENTRY org.eclipse.e4.ui.workbench 4 0 2020-05-11 13:56:50.042!MESSAGE Unable to retrieve the bundle from the URI: bundleclass://com.dbeaver.ee.runtime.ui/com.dbeaver.ee.runtime.internal.ui.LicenseStartupAddon !ENTRY org.eclipse.e4.ui.workbench 2 0 2020-05-11 13:56:50.608!MESSAGE Removing PartDescriptorImpl with the "org.eclipse.ui.views.ProgressView" id and the "Background Tasks" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled !ENTRY org.eclipse.e4.ui.workbench 2 0 2020-05-11 13:56:50.634!MESSAGE Removing PartDescriptorImpl with the "org.eclipse.ui.texteditor.TemplatesView" id and the "Templates" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled!SESSION 2020-05-11 13:57:54.054 -----------------------------------------------eclipse.buildId=unknownjava.version=1.8.0_251java.vendor=Oracle CorporationBootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_USCommand-line arguments:  -os win32 -ws win32 -arch x86_64 !ENTRY org.eclipse.e4.ui.workbench 4 0 2020-05-11 13:57:55.869!MESSAGE Unable to retrieve the bundle from the URI: bundleclass://com.dbeaver.ee.runtime.ui/com.dbeaver.ee.runtime.internal.ui.LicenseStartupAddon !ENTRY org.eclipse.e4.ui.workbench 2 0 2020-05-11 13:57:56.474!MESSAGE Removing PartDescriptorImpl with the "org.eclipse.ui.views.ProgressView" id and the "Background Tasks" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled !ENTRY org.eclipse.e4.ui.workbench 2 0 2020-05-11 13:57:56.525!MESSAGE Removing PartDescriptorImpl with the "org.eclipse.ui.texteditor.TemplatesView" id and the "Templates" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled Lijepi pozdrav Dino Subašić Pošiljatelj: uslssPoslano:4. svibnja 2020. 15:39Primatelj: dbeaver/dbeaverKopija: dinosubasic; MentionPredmet: Re: [dbeaver/dbeaver] Saved SQL editor (#8458) @dinosubasic ,could you post logs after you attempt to start version newer then 6.0.0?https://github.com/dbeaver/dbeaver/wiki/Log-files—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by uslss** [comment]
hi @dinosubasic ,
still cannot reproduce an issue. Is it still actual for you?

**Comment by dinosubasic** [comment]
Hey..yeah, still actual unfortunately. Poslano iz programa Pošta za Windows 10 Pošiljatelj: uslssPoslano:23. lipnja 2020. 16:38Primatelj: dbeaver/dbeaverKopija: dinosubasic; MentionPredmet: Re: [dbeaver/dbeaver] Saved SQL editor (#8458) hi @dinosubasic ,still cannot reproduce an issue. Is it still actual for you?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 



	
		
			
				
			
		
		
			
				Ova e-pošta je provjerena na viruse Avast protuvirusnim programom.
				www.avast.com

**Comment by uslss** [comment]
could you try to reset workspace? 
https://github.com/dbeaver/dbeaver/wiki/Reset-workspace

**Comment by uslss** [comment]
there are not any updates on issue. Ticket will be closed.
If issue is still actual for you - feel free to reopen the ticket
