### ISSUE TITLE
How to disable auto-complete in filter box

### ISSUE THREAD

**Issue by MedicOP** [dbeaver/dbeaver#8461]
How do I completely disable this auto-complete feature in the filter? It keeps auto-completing when I don't want it to, I just want it completely turned off. Don't see an option for it in the Preferences

![Screenshot_1](https://user-images.githubusercontent.com/18251099/79511726-2d084380-8040-11ea-88c2-ac7b2070a3bc.png)

**Comment by serge-rider** [comment]
There is no such option. But we probably should add one.

**Comment by LonwoLonwo** [comment]
![2020-04-22 09_18_07-DBeaver 7 0 3 - actor](https://user-images.githubusercontent.com/45152336/79947518-c38e9780-847a-11ea-9e82-1a3775fc3158.png)

**Comment by uslss** [comment]
verified
