### ISSUE TITLE
[EXASOL] Foreign key cannot be created via Object Editor

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8463]
## System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.3 EA

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
Foreign key cannot be created via Object Editor

#### Steps to reproduce, if exist:
Precondition: use tables TEST1.EXPORT_TO and TEST1.Export
Steps:
Create FK in table TEST1.EXPORT_TO using PK of TEST1.Export via Object Editor

Actual result: 
Nothing appears after pressing Ok btn

![IJs2YXBc95](https://user-images.githubusercontent.com/51405061/79549676-f8c46f80-809f-11ea-97db-970670542ec5.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
