### ISSUE TITLE
Disabling script-to-database relationship.

### ISSUE THREAD

**Issue by januszrut** [dbeaver/dbeaver#8464]
Hello, 

#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04
- DBeaver version: 7.0.2

#### Connection specification:
- Database name and version: Postgresql

#### Describe your question:

First, THANK YOU  for DBeaver!

My question is:
how do I disable the SQL script-to-database relationship that is saved in workspace data.
This feature got me into trouble by running queries against a database different from one I was intending to use. 
Even worse, the database switch occurs silently :\

Best regards
Janusz Rut

**Comment by kseniiaguzeeva** [comment]
I'm not sure I understand you correctly. You can use Ctrl+O to change database in SQL Editor.
![vmA4PEhrEy](https://user-images.githubusercontent.com/51405061/79772446-c2ede800-8338-11ea-85a7-1a64ad54dc47.png)

Or please write steps to reproduce the issue.

**Comment by januszrut** [comment]
Dear Ksenia
thank you for your reply.

Here's the example of my problem.
Let's say we have a script 'truncate_all.sql' that truncates all tables in the database. Very dangerous, right?
1. Now, I set up the PRODUCTION system for first run and execute this script against the PRODUCTION database. Database clean, users may start using the system.
2. Users start saving data in production database.
3. A few days later I'm opening the DEVELOPMENT database and want to get rid of trash data from tables.
4. So, I'm connected to DEVELOPMENT database, I open the same 'truncate_all.sql' and hit Run button. 
Here the disaster begins.
Dbeaver reads metadata of the 'truncate_all.sql' file and finds out it was used with PRODUCTION database, switches to the PRODUCTION database - with no warning whatsoever! - and sends all users' precious data to hell by truncating all tables...

The Preferences -> Scripts window says:
"by default association of your SQL scripts with database connections is kept in internal workspace files"
And you may only pick the option saving this information in a SQL script.
You cannot disable completely this feature.

I would like to 
- disable use of
or 
- have DBeaver ignore 
the file-related metadata and NOT SWITCH the databases without my explicit decision.

Best regards
Janusz

**Comment by kseniiaguzeeva** [comment]
Thank you for the detailed explanation. I can offer you 2 ways:
1. You can use **Associate with data source** function before opening Script (you should right click on the script and select the function)
![dbeaver_FABJTlYttI](https://user-images.githubusercontent.com/51405061/80211049-95a58080-863d-11ea-8354-ae0ea6909a4f.png)

2. You can save Script out of DBeaver (SQL Editor context menu>File> Export SQL Script)  and insert it in a database you wish. In this case only SQL expression is inserted.
![dbeaver_MQ6knWWuNv](https://user-images.githubusercontent.com/51405061/80211386-5166b000-863e-11ea-8cf7-d4c1af7e36d3.png)

Please tell if I can help you with something else.
