### ISSUE TITLE
Refreshing partitions window

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#8466]
PostgreSQL
DBeaver 7.0.2
Windows 10x64
![dbBugPartitionsScreen3](https://user-images.githubusercontent.com/3856344/79567968-bdd13480-80bd-11ea-972f-84bf00fca4b8.gif)

**Comment by uslss** [comment]
hi @greenpeas ,
unfortunately cannot reproduce an issue. it is reproducible after reseting UI settings (File - Reset UI Setting)?

**Comment by greenpeas** [comment]
Yes. I reset the interface settings and the problem is still there. I missed one point: I used a filter in the table tree. Then I erased the filter and the problem remains. I think the problem is due to the filter of the table tree.

**Comment by uslss** [comment]
still cannot reproduce it.
is it reproducible for you against 7.0.4?

**Comment by greenpeas** [comment]
In version 7.1.0 all good.
