### ISSUE TITLE
[Oracle] Clear button isn't working for filters in Property Viewer

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8467]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.3

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
Clear button isn't working for filters in Property Viewer. Reproducible for Schemas, Global Data Types.
#### Steps to reproduce, if exist:
1. Open Schemas in Property viewer
2. Choose some schema and choose filter Show [chosen_schema] only - Filter applied, only schema is shown
3. Try to clear filter - Nothing happens, applied after refresh only. In DB navigator works ok.

**Comment by serge-rider** [comment]
@uslss Can't reproduce
