### ISSUE TITLE
Edit connection: SSH tab bad UI 

### ISSUE THREAD

**Issue by ngoclamnn** [dbeaver/dbeaver#8471]
#### System information: 
- Ubuntu 19.10
- DBeaver version 7.0.2
- Additional extensions: N

#### Connection specification:
- Database name and version: any
- Driver name: any
- Do you use tunnels or proxies: SSH

#### Describe the problem you're observing:
Bad UI on Keep Alive Interval (ms) input field.

#### Steps to reproduce, if exist:
Click on SSH tab when config database connection and look at: Keep Alive Interval (ms) input field.

![image](https://user-images.githubusercontent.com/29177632/79587950-79fe1f80-80fd-11ea-92ff-619435b59c7a.png)

**Comment by uslss** [comment]
thanks for the bug report.
and sorry for the late response

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
