### ISSUE TITLE
Formatting using external formatter / SQLWorkbench

### ISSUE THREAD

**Issue by FriscoDesi** [dbeaver/dbeaver#8472]
DBeaver Version - CE 7.0.1.202003211804
SQLWorkbench Version - 125.2
Database Connection Type - Oracle

**Issue** - When formatting the SQL code using external formatter like SQLWorkbench, the semicolon is stripped off whenever there is ORDER BY clause. I am attaching 3 screenshots to show the behavior.

Before Formatting
![image](https://user-images.githubusercontent.com/63867324/79590245-56ef5380-809c-11ea-8309-dc1a8cc58592.png)

1st Formatting - Both the semicolons are gone.
![image](https://user-images.githubusercontent.com/63867324/79590288-679fc980-809c-11ea-9a01-5269dc695515.png)

2nd Formatting - Statements for concatenated since the semicolon is missing.
![image](https://user-images.githubusercontent.com/63867324/79590336-7dad8a00-809c-11ea-9035-2b3cdfbd9b3a.png)

I tried these steps directly in SQLWorkbench to see if the issue originates these.

1st Formatting - Semicolons are still there
![image](https://user-images.githubusercontent.com/63867324/79590836-455a7b80-809d-11ea-8dc1-ba9d0852c431.png)

2nd Formatting - Semicolons are still there!
![image](https://user-images.githubusercontent.com/63867324/79590898-63c07700-809d-11ea-9b55-607940c13be9.png)

So this must be a DBeaver and SQLWorkbench integration issue. Can you please check?

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
I think it is SQL Workbench specific.
dbeaver passes entire script to external formatter and then gets formatted text back - no additional processing is performed.
Or maybe we call SQL Workbench formatter API incorrectly (see class SQLWorkbenchJManager). But I have no clues has to do this correctly so far.

Anyway, I thin we need to change the default behavior:
1. Format active query by default
1. Add preferences option to switch to back behavior

**Comment by uslss** [comment]
in case "Format active query only" is unchecked, formatting still applied for active query only

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
