### ISSUE TITLE
Autocomplete doesn't go away when pasting value in table viewer filter box

### ISSUE THREAD

**Issue by MedicOP** [dbeaver/dbeaver#8475]
This keeps happening to me where I start to type something in the filter box, such as: `itemid=` and then **ctrl+v** in some value like `123`. The auto-complete box shows up immediately after typing the equals sign and doesn't go away even though more text has already been typed.

![Screenshot_1](https://user-images.githubusercontent.com/18251099/79613808-8be0c200-80ff-11ea-946a-c59f07dcc54e.png)

I've already tried completely disabling autocomplete in the settings, but that only seems to affect SQL editors, and not the table viewer filter box.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
verified
