### ISSUE TITLE
Display password expiry ORA-28002 error to users prior to password expiration

### ISSUE THREAD

**Issue by bshreve** [dbeaver/dbeaver#8476]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my Oracle password expires without warning.

**Describe the solution you'd like**
When I connect to an Oracle database using DBeaver, I'd like to receive a warning that my password is about to expire in X days.

When I connect using Oracle SQL Developer a dialogue box appears with the warning message.

**Additional context**

![image](https://user-images.githubusercontent.com/37194973/79614509-afd7df80-80ce-11ea-8457-36de26697932.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by shungabubus** [comment]
Hello All,

+1 vote.

Thanks

**Comment by tnatanael** [comment]
+1 THIS FEATURE IS A MUST HAVE PLEASE LOOK INTO THIS s2
