### ISSUE TITLE
Metadata search doesn't work for Exasol

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8479]
#### System information:   
- Operating system (distribution) and version Win10
- DBeaver version 7.0.3

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
Metadata searchdoesn't work for Exasol
#### Steps to reproduce, if exist:
1. Open DB Metadata search
2. Select Exasol
3. Check all objects
4. Type an existed table name
5. Press Search btn

Actual result:
the table is not found.
![WwfjfHcbCP](https://user-images.githubusercontent.com/51405061/79635166-03523800-8178-11ea-8f87-cdfc671a5c09.gif)

**Comment by Sargul** [comment]
Unfortunately you are right. I had do remove Metadata search in the Exasol plugin some versions ago because it was so terribly slow due to poor meta data query performance in Exasol.

I will have a look and try to integrate this in the Exasol plugin again.

**Comment by kseniiaguzeeva** [comment]
Thank you!

**Comment by Sargul** [comment]
added functionality into #9131 

![meta_search](https://user-images.githubusercontent.com/5595511/86208066-1a49d900-bb70-11ea-9bed-0d37bd16cbdb.gif)
