### ISSUE TITLE
[Exasol] Default schema cannot be assigned

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8480]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.3 EA

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
Default schema cannot be assigned
#### Steps to reproduce, if exist:
1. Select **Set as default** in schema context menu

Actual result:
No visiable changes

![i4GPMyItFu](https://user-images.githubusercontent.com/51405061/79635347-04d03000-8179-11ea-92f4-cae2a849a511.gif)

**Comment by Sargul** [comment]
Hi,

weird. No changes made to schema selection in any of the latest versions.

Also I could not reproduce this issue.
![set_schema](https://user-images.githubusercontent.com/5595511/80448911-08547b80-891e-11ea-9451-50fafe8ab780.gif)


Can you take a look at the Query Manager and look if you can see that "open schema" commands are issued:
![image](https://user-images.githubusercontent.com/5595511/80448986-3a65dd80-891e-11ea-8503-63e6431fa2c2.png)

Can you also provide log files
[DBeaver Logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by kseniiaguzeeva** [comment]
I also cannot reproduce it in 7.0.4 ea. So, the ticket is closed.
