### ISSUE TITLE
Subsequent generated ER Diagrams are wrong if DB schema modified after generating first ER Diagram

### ISSUE THREAD

**Issue by mbmast** [dbeaver/dbeaver#8482]
<!--
Thank you for reporting an issue.

*IMPORTANT* -  *before* creating a new issue please look around:
 - DBeaver documentation: https://github.com/dbeaver/dbeaver/wiki
 and
 - open issues in Github tracker: https://github.com/dbeaver/dbeaver/issues
  
If you cannot find a similar problem, then create a new issue. Short tips about new issues can be #### System information: 
- Windows 10 Operating V1903
- DBeaver version 7.0.2
- Eclipse  2019-12 (4.14.0)

#### Connection specification:
- MySQL 5.7.21
- com.mysql.jdbc.Driver 5.1.44
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
From Eclipse I generate an ER diagram: File > New > Other > DBeaver ER Diagram and then select a single DB instance from the subsequent menu of data bases.  This generated an accurate ER diagram.

If I subsequently modify a foreign key(s) definition in the DB without exiting Eclipse and then re-generate the ER diagram, the diagram will not reflect the changes made to the foreign key(s).  Hitting Refresh on the ER Diagram window does not correct the problem.

#### Workarounds:
Exit Eclipse and restart it.  Now any newly generated ER Diagrams will reflect changes made to foreign keys.

#### Steps to reproduce, if exist:
See Description of problem.

#### Include any warning/errors/backtraces from the logs
None.  The directory %APPDATA%\DBeaverData\workspace6\.metadata does not exist.  In fact, there is no sub-directory named DBeaverData anywhere on the hard drive.

**Comment by uslss** [comment]
hi @mbmast ,
could you add picture that could illustrate your issue?

**Comment by uslss** [comment]
there is no update on issue. if it is still actual for you - feel free to reopen the ticket
