### ISSUE TITLE
add empty space bottom in table view. because there are horizontal scrollbar

### ISSUE THREAD

**Issue by erlangp** [dbeaver/dbeaver#8484]
https://imgur.com/a/NjR1xWL

currently dificult to edit last record because the horizontal scrollbar will shown if my cursor there

dbeaver 7.0.2

**Comment by uslss** [comment]
hi @erlangp ,
what os do you use? also issue isn't clearly shown at the picture, could you add another one?

**Comment by uslss** [comment]
probably duplicate of #4839
