### ISSUE TITLE
Autocomplete doesn't work for PrestoSQL

### ISSUE THREAD

**Issue by shanikovalsky** [dbeaver/dbeaver#8485]
- Operating system (distribution) and version: OSX Catalina 10.15.4
- DBeaver version: 7.0.2
- Additional extensions: same thing happened on previous version I had I think it was 6.x

#### Connection specification:
- Database name and version: PrestoSQL
- Driver name: PrestoSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
The auto-complete of columns doesn't work when connected to Presto DB. In the same time, if I connect to other connections, like MySQL, Redshift and Athena, the auto-complete of column names **does** work

I searched previous issues and I saw something similar with SnowFlake and Oracle DB: https://github.com/dbeaver/dbeaver/issues/6073

**Comment by serge-rider** [comment]
Did you try to use fully qualified table names (with schema name prefix)? There is no default schema in presto so dbeaver can't find your table in database metadata without it.
