### ISSUE TITLE
Visually Distinguish Between Nulls and an Array of Null

### ISSUE THREAD

**Issue by kdonavin** [dbeaver/dbeaver#8487]
**Is your feature request related to a problem? Please describe.**

A `NULL` value is indistinguishable from an array with a single `NULL` element in it. 

A `NULL`: 

<img width="280" alt="post_to_dbeaver__null_looks_like_array" src="https://user-images.githubusercontent.com/16674499/79702045-18ee5d00-825f-11ea-9a94-e1df361fbc7a.png">

An array of `NULL`:

<img width="356" alt="post_to_dbeaver__array_null_looks_like_array" src="https://user-images.githubusercontent.com/16674499/79702055-24da1f00-825f-11ea-9ef9-b72a71704e1d.png">

This can be confusing when working with arrays containing `NULL` values. Especially when those arrays contain sub-arrays. Then is the element `NULL` or is it an array with nothing in it?

**Describe the solution you'd like**

Some other way to indicate `NULL`. <- Perhaps just that. Or, `(NULL)`, or `{NULL}`, or `|NULL|`.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by E1izabeth** [comment]
Seems to be implemented.
