### ISSUE TITLE
Find/Replace does not work of Database server output log is open

### ISSUE THREAD

**Issue by mutigozel** [dbeaver/dbeaver#8489]
System information: 
- Operating system : Win 10 x64 latest version
- DBeaver version : 6.3 

Connection specification:
- Database name and version : PostgreSQL latest
- Driver name : standard one
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

Describe the problem you're observing:

Find/Replace does not work if the Database server output log is open.

Steps to reproduce, if exist:

- execute a query 
- open the Database server output log window ( Ctrl + Shift + O )
- return to the query window 
- press Ctrl + F to open Find/Replace
- type anything to search
- it does not work

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by chelebarry** [comment]
The find in the output query grid should be review when using the grid view some string you are searching for is not found sometimes, I get a "String not found" now if I use the text view and do the search for exactly the same string I do find what I want.
