### ISSUE TITLE
CSV Import is not working 7.0.3. The file import was working in 7.0.0

### ISSUE THREAD

**Issue by yogendratamang48** [dbeaver/dbeaver#8490]
#### System information: 
- Win 10
- DBeaver version: 7.0.3

#### Connection specification:
- Database name and version
- Postgres 
- With SSH Tunnel

**Comment by uslss** [comment]
hi @yogendratamang48 ,
unfortunately, cannot reproduce an issue. Works ok for me.
Probably you could some special steps and log?

**Comment by uslss** [comment]
there is no update on issue. if it is still actual for you - feel free to reopen the ticket with additional info
