### ISSUE TITLE
Why does dbeaver 7 need admin rights on mac?

### ISSUE THREAD

**Issue by slawo-ch** [dbeaver/dbeaver#8491]
#### System information: 
- MacOS mojave
- 7.0.2 installer

#### Describe your question:
Dear dbeaver team,

I was using DBeaver for quite some time now, and I don't recall it ever 'installing' and running scripts during that process, especially not with admin credentials. It seems to be necessary now. It used to be just an app you dragged into your /Applications folder, if I recall correctly.

I was wondering why there is an installer now that asks admin permissions, and whether there is still a way to run dbeaver without effectively giving it root permissions. 

I'm sure there's a good reason for the changes, I'd just like to know more about it, and where I can inspect what the installer does.

Thanks for creating DBeaver!

**Comment by serge-rider** [comment]
DBeaver doesn't need admin permissions to run. It always run under regular user permissions.
Installed itself needs admin permissions to copy dbeaver files into /Applications folder.
