### ISSUE TITLE
ERRORCODE=-4214, SQLSTATE=28000

### ISSUE THREAD

**Issue by karen-handcock** [dbeaver/dbeaver#8492]
I keep getting,

[jcc][t4][2013][11249][4.26.14] Connection authorization failure occurred.  Reason: User ID or Password invalid. ERRORCODE=-4214, SQLSTATE=28000

I have reset my password via ITIM. 

Thank you for reporting an issue.

*IMPORTANT* -  *before* creating a new issue please look around:
 - DBeaver documentation: https://github.com/dbeaver/dbeaver/wiki
 and
 - open issues in Github tracker: https://github.com/dbeaver/dbeaver/issues
  
If you cannot find a similar problem, then create a new issue. Short tips about new issues can be found here: https://github.com/dbeaver/dbeaver/wiki/Posting-issues

Please, do not create issue duplicates. If you find the same or similar issue, just add a comment or vote for this feature. It helps us to track the most popular requests and fix them faster.

Please fill in as much of the template as possible.
-->

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
hi @karen-handcock ,
what is your db? could you check if issue reproducible with another credentials?

**Comment by karen-handcock** [comment]
this is what I see
Host: 9.208.9.56
Database: WEB
Port: 3705
Driver name: DB2 LUW

**Comment by Sargul** [comment]
the message says that your userid or password is wrong. This could also mean that you’re not authorized to access this database. Talk to your DBA department

**Comment by karen-handcock** [comment]
Hi. I have tried to talk with DB2 support. they told me to reach out to DBeaver team.
I also spoke with ITIM team, they say password & Id is correct.
I'm going around in circles.

**Comment by uslss** [comment]
hi @karen-handcock , is it still actual?

**Comment by uslss** [comment]
there is no update on issue for a long time. If it is still actual for you - feel free to reopen the ticket with additional info.
BR

**Comment by NicklasAtFluor** [comment]
What was the issue?  I am experiencing the same with the Eclipse plugin of DBeaver for a DB2 LUW JDBC connection.   Same credentials and JDBC settings used with other apps and connects fine, but fails for the DB2 LUW connection under the DBeaver plugin with the following:

[jcc][t4][2013][11249][3.68.61] Connection authorization failure occurred.  Reason: User ID or Password invalid. ERRORCODE=-4214, SQLSTATE=28000
[jcc][t4][2013][11249][3.68.61] Connection authorization failure occurred.  Reason: User ID or Password invalid. ERRORCODE=-4214, SQLSTATE=28000

 **Eclipse** 
Version: 2021-06 (4.20.0)
Build id: 20210612-2011

**DBeaver Plugin**
Version: 21.3.3

I can create a SQL Server connection fine in the plugin but not DB2

I attached the trace output.

[trace_sds_3.log](https://github.com/dbeaver/dbeaver/files/7987029/trace_sds_3.log)
