### ISSUE TITLE
Navigation links not working in Data Editor

### ISSUE THREAD

**Issue by ricardomvreis** [dbeaver/dbeaver#8494]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro v18363.778
- DBeaver version: 7.0.3
- Java version: 8.2.0
- Additional extensions:

#### Connection specification:
- Database name and version
- Driver name: MS SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Since DBeaver 7.0.2, the navigation links to linked tables through foreign keys stopped working in the Data Editor.
Up until DBeaver 7.0.1, it worked fine.

#### Steps to reproduce, if exist:
Execute an SQL SELECT statement on a table with foreign keys and see the links not working.

**Comment by uslss** [comment]
Hi @ricardomvreis ,
unfortunately cannot reproduce an issue. Do you have any message in error log?
Also, please, clarify what happens when you click at the link?

**Comment by ricardomvreis** [comment]
Hi @uslss ,

Sorry I wasn't more specific. 
What I mean is that I have a connection to a Development database where the navigation links work as expected, but I have another connection to a Production database where the links are not available at all, that is, I only see the foreign key value as if it was a regular value (number or text), therefore there is no link for me to click.

Up until DBeaver 7.0.1, the navigation links worked on every connection.

**Comment by uslss** [comment]
@ricardomvreis , still not reproducible for me. Does issue solve if you change Prod type to Dev?

**Comment by ricardomvreis** [comment]
@uslss , I've already tried that but it didn't solve the issue either. 
I think it may have something to do with the connections' drivers that may have become incompatible with the later versions of DBeaver.

I've just checked and, in version 7.0.1, both Dev and Prod database drivers' libraries were OK, but in version 7.0.3, the Dev drivers are OK and the Prod ones are blue, as you can see below.

![image](https://user-images.githubusercontent.com/28712530/79849911-0ab55380-83bb-11ea-9209-e6109ae64cfb.png)

Why has this happened from one DBeaver version to another?

**Comment by uslss** [comment]
Drivers' libraries become blue if you click Reset to Default button.
Did you try to re-create the connection?
Also, maybe File - Reset UI Settings could help

**Comment by serge-rider** [comment]
It has nothing to do with drivers.

@ricardomvreis Does downgrade to older DBeaver version help? 
Links can be disabled for a particular connection:

![image](https://user-images.githubusercontent.com/6398845/79852532-743f5d00-83cf-11ea-8886-7eea442379f3.png)

**Comment by ricardomvreis** [comment]
@uslss and @serge-rider , thanks for all the help, but I managed to solve the issue and it had to do with some other detail.

The problem was that, in the Production connection, the database schema was somehow not selected, whereas, in the Development connection, it was. As soon as I noticed that, I selected the schema in the Prod connection and the foreign key links began to work.

@serge-rider while I had this issue, I decided to downgrade to version 7.0.1 so the links could work, but today I decided to re-upgrade and try to sort it out for good and voilà, everything is fine now (apart from a bug with translations which I also reported yesterday). :)


Thanks a lot to both of you!

**Comment by ricardomvreis** [comment]
@uslss , I don't know if I should open another issue, but after I select the database schema, it gets automatically delesected after a while, thus making the navigation links not to work. It seems like a bug of version 7.0.3

**Comment by uslss** [comment]
@ricardomvreis where did you select schema? could you post a screenshot?

**Comment by ricardomvreis** [comment]
@uslss I selected the schema through the "Choose catalog/schema" window, pressing Ctrl+0

**Comment by uslss** [comment]
hi @ricardomvreis ,
still cannot reproduce an issue. Could you try it against recent version?

**Comment by ricardomvreis** [comment]
Hi @uslss ,

In the new 7.0.4 version, the issue still persists, that is, right after I had selected the DB schema through the "Choose catalog/schema" window (Ctrl+0), I queried a table that I know has a foreign key, and the navigation link was not available in the result set grid afterwards (the foreign key Id was displayed just like any other number).

This time, even though I had selected a schema and it is visible in the database dropdown as "<schema>@<database>", it didn't take any actual effect because as soon as I reopened the dialog, it was not selected.

I don't know if it's relevant, but this issue happens on a Production mode connection, whereas in a Development mode connection, everything is OK. Apart from each one's specific connection settings, evey other setting is the same for both connections.

Hope you can now understand how to reproduce the issue.


Thanks!

**Comment by uslss** [comment]
cannot reproduce it for now.
If issue is still reproducible for you - please reopen the ticker

**Comment by ricardomvreis** [comment]
Hi @uslss ,

I am still being able to reproduce it, but I've managed to work around it by adding the schema in front of the table name in the queries (e.g SELECT * FROM my_schema.MY_TABLE). This way, DBeaver has the context needed to identify the foreign keys and their corresponding referenced tables.

 Thanks!
