### ISSUE TITLE
Interface copy in more than 1 language

### ISSUE THREAD

**Issue by ricardomvreis** [dbeaver/dbeaver#8495]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro v18363.778
- DBeaver version: 7.0.3
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I see many interface options and infos written in English and other ones in Portuguese, despite I have set the language to English.
I have my Windows language set to Portuguese, so it can have something to do with the issue.

#### Steps to reproduce, if exist:
Set the Windows language to other than English and check the language that several options in the interface are written in.

**Comment by kseniiaguzeeva** [comment]
Could you please check what is written in the application shortcut properties for object
![tPVBjRoDOI](https://user-images.githubusercontent.com/51405061/79770350-f67b4300-8335-11ea-9ed8-f5402bda86b3.png)

**Comment by ricardomvreis** [comment]
Hi,

On my side, the destination string ends precisely with "\dbeaver.exe", so it has nothing after that.

**Comment by kseniiaguzeeva** [comment]
Please tell also which locale is set in DBeaver?
You can see it in ResultSet> Data Formatting
![5ERcrRd3m0](https://user-images.githubusercontent.com/51405061/79780482-ac4d8e00-8344-11ea-9d8a-f5abfe5c1c4d.png)

**Comment by ricardomvreis** [comment]
It is set to English, but as you can see in the screenshot, there are 2 options in Portuguese.

![image](https://user-images.githubusercontent.com/28712530/79781159-f7f83b80-8334-11ea-80be-267e4c606740.png)

There are situations like that in the other menus.

**Comment by serge-rider** [comment]
We will add full Portuguese localization in version 7.0.4 (see  #8451). Currently only several platform-defined menus and pref pages are localized.

**Comment by uslss** [comment]
verified

**Comment by uslss** [comment]
verified
