### ISSUE TITLE
Cant write in any textbox. (editor, configuration fields, etc.)

### ISSUE THREAD

**Issue by GAZ082** [dbeaver/dbeaver#8499]
#### System information: 
- Operating system (distribution) and version Archx64, Gnome 3.36.1, Wayland
- DBeaver version Version 7.0.2.202004052249
- Additional extensions

#### Describe the problem you're observing:
Try to type or paste in any field.
![taptap](https://user-images.githubusercontent.com/100194/79811808-68ab5200-834d-11ea-8181-5d8f4b34e6a7.gif)

**Comment by uslss** [comment]
is it still actual?
unfortunately, we've got no similar os installed to test it (works ok on Ubuntu 19.04)

**Comment by GAZ082** [comment]
> is it still actual?
> unfortunately, we've got no similar os installed to test it (works ok on Ubuntu 19.04)

Hey ya! Since 7.1 it does not happen again. So we are good. I close the issue. Thanks!
