### ISSUE TITLE
Permissions are not sorted

### ISSUE THREAD

**Issue by michalk-k** [dbeaver/dbeaver#8502]
Roles in Permissions window are not softer alphabetically. My guess is records are sorted by oid
Checked for schema and table, likely valid for other objects.
Database: Postgresql 10
It makes this view hardly usable in case of a lot of roles

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
