### ISSUE TITLE
Query progress bar overlay missing on Alt-X

### ISSUE THREAD

**Issue by joel458** [dbeaver/dbeaver#8507]
#### System information: 
- win64
- DBeaver 7.0.2 and 7.0.3

#### Connection specification:
- Database : caché, postgres 

#### Describe the problem you're observing:
When I execute a query using Alt-X ("Execute SQL Script" command) I do not see the query progress bar (the overlay stating the elapsed time and the number of rows fetched, and the cancel button (see capture)). It shows when I launch with Ctrl-Alt-Shift-X ("Execute Statement in Separate Tabs" command). Is this behavior change as designed, or is there a setting I am missing?

This is the overlay i'm referring to:
![Capture](https://user-images.githubusercontent.com/64088448/79879636-f2463880-83bc-11ea-8d93-df5978764a85.PNG)

Other observations:
- in 7.0.1, "Execute Statement in Separate Tabs" creates a separate tab for each result set. 7.0.3 does not. This looks to me like a bug.
- that having "Maximize editor on script execute" under "SQL Processing" turned on by default was confusing to me because of the change in behavior, but this is very minor point.

I'll also take this opportunity to thank you for this awesome piece of software, keep up the good work!

#### Steps to reproduce, if exist:
- open script editor containing a single query
- execute with Alt-X (or right-click menus)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
We don't show progress visualization on results tab for scripts. Because there are many results.
We show popup dialog with progress instead. Probably you hide this dialog by pressing "Run in background". 

You can bring it back in Preferences->General->Always run in background.

**Comment by uslss** [comment]
now, four tabs appear when three queries are executed
![2020-05-06_17h20_06](https://user-images.githubusercontent.com/31996417/81188443-fa59c700-8fbd-11ea-8956-3a0671dab172.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
