### ISSUE TITLE
do not work csv import

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#8513]
OS WINDOWS 10 64bit
DBeaver community version 7.0.3

inactive START Button in csv import

Case:
Right button click on table in object tree->import->choose csv file->next

![изображение](https://user-images.githubusercontent.com/61137576/79954217-76b8ba00-8496-11ea-8aa2-f7fb93dd1919.png)

**Comment by uslss** [comment]
Hi @detkliff , what db do you use?
Do you have empty fields in Mapping Type column?

**Comment by detkliff** [comment]
> 
> 
> Hi @detkliff , what db do you use?
> Do you have empty fields in Mapping Type column?

Postgresql

8 fields in my csv and 8 empty fields in my table.

This csv import working in pgAdmin4 without problem with this file and this DB and table

**Comment by uslss** [comment]
could you post table create ddl and CSV sample?
it would be very helpful for investigating the issue.

**Comment by detkliff** [comment]
> 
> 
> could you post table create ddl and CSV sample?
> it would be very helpful for investigating the issue.

I discovered problem.  My csv file contained symbol ' in one string data
Examle kal'iningrad;;;kal'iningrad;kl$k;100;591;138

When i corrected csv to kaliningrad;;;kaliningrad;kl$k;100;591;138  button START is enabled.

**Comment by uslss** [comment]
thanks for response.
seems that issue is solved.
ticket closed
