### ISSUE TITLE
Proxy settings are cleared when update by dragged dmg into Application

### ISSUE THREAD

**Issue by ykqmain** [dbeaver/dbeaver#8519]
#### System information: 
- Operating system (distribution) and version: macOS 10.14.6
- DBeaver version: Community Edition 7.0.3.202004191823
- Additional extensions: None

#### Describe the problem you're observing:

My proxy preferences be lost when I drag new version .dmg into the Application folder. 

It only cleared the proxy settings, I have not modified the default configuration folder.

I discovered this phenomenon when I updated from 7.0.1 to 7.0.2, and today I updated 7.0.3 to reproduce.

`"General -> Network Connections -> Proxy entries".`

<img width="612" alt="屏幕快照 2020-04-22 20 23 36" src="https://user-images.githubusercontent.com/15179473/79981524-670d9580-84d7-11ea-945a-d3a8379eb7de.png">

**Comment by serge-rider** [comment]
I can't reproduce this..

Does it affects all preferences or only proxy settings?

**Comment by ykqmain** [comment]
@serge-rider 


only proxy settings

**Comment by serge-rider** [comment]
Reproduced.
Indeed, proxy settings are stored not in workspace but in local app settings. It is a part of Eclipse configuration. We can't fix this.

You could try to configure proxy for particular connections. IF you have many identical proxy settings for different connection you can use configuration profile for that.
These settings won't be lost after new version install.
