### ISSUE TITLE
NPE appears when trying to import some tables from CSV

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8520]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.3
- Additional extensions

#### Connection specification:
- Database name and version MySQL, PostgreSQL

#### Describe the problem you're observing:
When trying to import some table from CSV - NPE appears. Possibly it appears in some cases, when number of columns in CSV is less than number of column in target table
![image](https://user-images.githubusercontent.com/31996417/79983499-8ba24700-84b0-11ea-91f2-9bc3a1b41565.png)
str:
1. Export db3.sakila.actor to csv
2. Try to import it to d3.sakila.address

**Comment by serge-rider** [comment]
Probably fixed in #8536
