### ISSUE TITLE
Two Data Type fields are shown for columns in Oracle

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8522]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.0.3

#### Connection specification:
- Database name and version Oracle
#### Describe the problem you're observing:
Two Data Type fields are shown for columns in Oracle
![image](https://user-images.githubusercontent.com/31996417/79998475-6834c780-84c3-11ea-8701-a293805c25b8.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
