### ISSUE TITLE
How to build dbeaver on ARM pltaform machine?

### ISSUE THREAD

**Issue by TuQinggang** [dbeaver/dbeaver#8525]
#### System information: 
- Operating system (distribution) and version:deepin v20
- DBeaver version:7.0.3

#### Connection specification:
- Database name and version

#### Describe your question:
hello,now I should use dbeaver on a arm64 platform machine,How can I build it?

**Comment by serge-rider** [comment]
We don't support ARM platform officially. However there are some Eclipse builds for ARM. So potentially it is possible (open dbeaver in Eclipse and try to build it).
