### ISSUE TITLE
Query with malformed subquery returns results

### ISSUE THREAD

**Issue by diaabo** [dbeaver/dbeaver#8526]
- Operating system (distribution) and version:
Windows 10

- DBeaver version
7.0.3.202004191823

- Additional extensions
None

#### Connection specification:
- Database name and version
Oracle AWS RDS: Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

- Driver name
oracle.jdbc.OracleDriver

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
Results are returned even if subquery is malformed 

#### Steps to reproduce, if exist:
1. This query is malformed, that is, it gives an error: 

SELECT column_name FROM dual

**SQL Error [904] [42000]: ORA-00904: "COLUMN_NAME": invalid identifier (CORRECT!!)**

However, if you put it as a subquery, the main query retrieves results:

**SELECT * FROM all_tab_columns 
 WHERE column_name IN (SELECT column_name FROM dual);**

And you can see if you put a NOT IN it does not give an error but returns 0 rows:

**SELECT * FROM all_tab_columns 
 WHERE column_name NOT IN (SELECT column_name FROM dual);**

#### Include any warning/errors/backtraces from the logs
None

**Comment by uslss** [comment]
thanks for the bug report
and sorry for late response

**Comment by uslss** [comment]
seems it is expected behavior
https://docs.oracle.com/cd/B19306_01/server.102/b14200/queries009.htm
