### ISSUE TITLE
When saving file it disconnects

### ISSUE THREAD

**Issue by Moridin11** [dbeaver/dbeaver#8529]
In version 7.0.3 

First the RDP issue is resolved.  YAY.  
Secondly whenever I SAVE a file, it immediately disconnects me from my connection.  I didn't see this in previous versions so I assume it is a new bug, unless it is a feature that was added.

** Update ** When I said "feature" I meant it as a setting somewhere in the properties.  I just read this and realized I sounded like a ....

**Comment by Moridin11** [comment]
I'm sure this is a pretty low priority, but is there a projected milestone for this?

Just gets annoying to have to constantly reconnect.

**Comment by whabada** [comment]
I am also having trouble with this Issue: It is really annyoing to reconnect everytime after saving. I am using Version 7.0.5.

**Comment by whabada** [comment]
I just realized, it just happens if I save an script file in one project and the database connection is established in another project. When coyping the database into the same project where the script lies, the script stays connected.

**Comment by Moridin11** [comment]
I only have 1 project.  I do notice that sometimes it doesn't disconnect, but I haven't been able to pin point WHY.  It might have something to do with what connection I'm using though

**Comment by uslss** [comment]
cannot reproduce it against 21.1.1.
If it is still actual for you - feel free to reopen it.

**Comment by Moridin11** [comment]
I still see this as of 21.1.2

**Comment by xazos79** [comment]
I also still see this as of 22.2.0

Strange thing is that i've never seen it until this very version. And i've been using DBeaver for years.

**Comment by KevinJohnMulligan** [comment]
> I just realized, it just happens if I save an script file in one project and the database connection is established in another project. When coyping the database into the same project where the script lies, the script stays connected.

Thank you, this worked in my case!

**Comment by KevinJohnMulligan** [comment]
> > I just realized, it just happens if I save an script file in one project and the database connection is established in another project. When coyping the database into the same project where the script lies, the script stays connected.
> 
> Thank you, this worked in my case!

As for the initial problem... It's a very unintuitive and disruptive behaviour for the software to do without any kind of notification or hint on how to avoid it.

I'm using v22.0.0 but since I see it's still a problem in [22.2.0](https://github.com/dbeaver/dbeaver/issues/8529#issuecomment-1243226537) I'm not going to update the software.

**Comment by ScaryDBA** [comment]
Just discovered this problem myself. It's still going on in 22.3.0.202212041619. I get the workaround, but it's still really crappy behavior.

**Comment by xazos79** [comment]
Had been fixed for a while. It's happening again to me now. Must be a
regression.

**Comment by david67nyc** [comment]
still happening 7/2023. pos software.

**Comment by PLP-GTR** [comment]
This is still happening and it is still annoying. I don't know what the last working version was but since it's now September 2023 already, it was a long time ago :-(

I am using: 
* DBeaver Community Version
* Version 23.2.0.202309040911
* on MacBook Pro 14" 2021 (Apple M1 Pro) with macOS Ventura 13.4.1 (22F82)

Since this ticket is closed and therefore not showing up by default in Github Issues plus it's not assigned to anyone, I guess this will not come to attention?

**Comment by technicalbundle** [comment]
The same issue was observed.

Version 24.2.3.202410201725

**Comment by hannahshachar** [comment]
This drives me completely insane.  Please fix it!

**Comment by majraj** [comment]
still happens, makes it impossible to use dbeaver

**Comment by PLP-GTR** [comment]
I fixed this quite long time ago ... I can't remember what it was but it was fairly easy.
Damn guys ... I'm so sorry 🥲

**Comment by Moridin11** [comment]
All you have to do is copy you connections into your project.

Respectfully Submitted,


Chip Joseph Adams
703.200.4449
<https://aka.ms/AAb9ysg>
________________________________

**Comment by PLP-GTR** [comment]
> All you have to do is copy you connections into your project.
> 
> Respectfully Submitted,
> 
> 
> Chip Joseph Adams
> 703.200.4449

Yeah something like this. The scripts and the connections need to be in the same project.
I remember it was nothing complicated, just a small adjustment.

If the script is saved in another project, I'm getting very weird behaviour and it disables the current connection every so often.
If I move the script into the same project with the connection, the weird things stop.

![Image](https://github.com/user-attachments/assets/7219ded3-dcba-44fd-8243-8d787c888bae)

**Comment by majraj** [comment]
Hello

1. I want to use my scripts in many projects, just by selecting them 
2. what do u mean by "copy you connections into your project"

Regards



> All you have to do is copy you connections into your project.
> 
> Respectfully Submitted,
> 
> 
> Chip Joseph Adams
> 703.200.4449
> <https://aka.ms/AAb9ysg>
> […](#)

**Comment by PLP-GTR** [comment]
> Hello
> 
> 1. I want to use my scripts in many projects, just by selecting them
> 2. what do u mean by "copy you connections into your project"
> 
> Regards
> 
> > All you have to do is copy you connections into your project.
> > Respectfully Submitted,
> > Chip Joseph Adams
> > 703.200.4449
> > https://aka.ms/AAb9ysg
> > […](#)

Then you have to wait for a fix (if it will ever be fixed). This is a proposed workaround that does not fit your use case.

Another proposal: You could also use a shared folder (or called linked folder idk) which you can include in every project.

![Image](https://github.com/user-attachments/assets/86b3fe51-8bad-4a71-9a7f-c3107db64ea0)

I don't know how many projects you have with the same database but if they all are very similar you could structure them using folders inside one project.

Usually only simple projects have a similar database and you really don't need scripts for such use cases (in my very humble opinion).

**Comment by Moridin11** [comment]
Under each project there is a folder for connections.  You can just copy paste then into there

Respectfully Submitted,


Chip Joseph Adams
703.200.4449
<https://aka.ms/AAb9ysg>
________________________________
