### ISSUE TITLE
Convert Line Delimeter To menu is duplicated in Main menu

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8530]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.0.3

#### Describe the problem you're observing:
Convert Line Delimeter To menu is duplicated in Main menu. Also it doesn't make any changes in case of choosing these points
File menu:
![image](https://user-images.githubusercontent.com/31996417/80117020-54569780-858f-11ea-82d3-ec29f9d12d94.png)
Edit menu:
![image](https://user-images.githubusercontent.com/31996417/80117064-62a4b380-858f-11ea-8096-158f6fab770e.png)

**Comment by serge-rider** [comment]
Fixed (removed from Edit menu)

**Comment by uslss** [comment]
verified
