### ISSUE TITLE
After 1 connection, in the second, when clicking "Test Connection..." or "Finish" nothing happens

### ISSUE THREAD

**Issue by bbhgithub** [dbeaver/dbeaver#8531]
Same thing as #8503 and #5971

System information:
Windows 7 and Windows 10
DBeaver 7.0.3
Connection specification:
SQL Server and Oracle and DB2

Describe the problem you're observing:
In the second connection, when clicking "Test Connection..." or "Finish" nothing happens. No error, nothing.

Steps to reproduce, if exist:
The first connection is ok, Oracle, DB2 or SQL Server, and the second create a connection is not good.

When i copy/paste a connection and modified, works good...

**Comment by LiborVojtek** [comment]
I have the same issue.
Cannot test nor create new connection.
[.log](https://github.com/dbeaver/dbeaver/files/4527357/default.log)

**Comment by uslss** [comment]
close as diplicate of #8503 
anyway thanks for the bug report
