### ISSUE TITLE
Settings migration

### ISSUE THREAD

**Issue by michalk-k** [dbeaver/dbeaver#8534]
I know there is export/import option but it's extremely counter-intuitive. It even seems it provides no option to migrate connection settings.
A few months ago i somehow succeeded moving configuration/connections from linux to win10.
Recently I tried it again (by moving files as I found it's the only way to migrate connection settings) loosing all connection settings in w10 DBeaver  

The objective is: make app settings and connections export/import easier.
Please check if it still works  between operation systems

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
seems will be implemented in #13779
