### ISSUE TITLE
not find schema

### ISSUE THREAD

**Issue by myungsik89** [dbeaver/dbeaver#8538]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
7.0.3.202004191823

#### Connection specification:
- Database name and version
orcle / jdk1.8.0_231

#### Describe your question:
hello,
I don't know if the content will be delivered well due to my poor English skills, but please take good care of me.
If the name of the sql file is written in Korean, the following message will occur because the schema of db cannot be found.
The sql file in English finds the schema well and executes sql well.
It used to work well before, but not after this update.
I'm sorry I don't know how to attach a picture.
[error]
Can't open editor connection
이유:
 IO 오류: Undefined Error
![dbeaver](https://user-images.githubusercontent.com/49738329/80185955-2f722b00-8648-11ea-805f-0027d8a6090d.jpg)

**Comment by uslss** [comment]
hi @myungsik89 ,
did you try to invalidate connection? also is Connect on editor activation option is checked?
![image](https://user-images.githubusercontent.com/31996417/80223873-91835e00-8651-11ea-8f13-4aaf79fa443f.png)

**Comment by myungsik89** [comment]
It was checked.
Is there any other way?

![DBEAVER](https://user-images.githubusercontent.com/49738329/80446705-8763a700-8952-11ea-99c8-f052005bb91b.jpg)

**Comment by uslss** [comment]
still cannot reproduce an issue.
Is it still actual for you against the recent version?
Thanks in advance for the response

**Comment by uslss** [comment]
there are not any updates on issue. Ticket will be closed.
If issue is still actual for you - feel free to reopen the ticket
