### ISSUE TITLE
Copy as SQL (table name & separator)

### ISSUE THREAD

**Issue by bnORISHA** [dbeaver/dbeaver#8539]
#### System information: 
- Windows 10 1909 64bits
- DBeaver 7.0.3.202004191823

#### Connection specification:
- DB2 iSeries/AS400 driver (jt400 10.3)

#### Describe the problem you're observing:
Hello.
When I use "Copy as SQL" function the syntax is not correct.
Table names are surrounded by double quotes but DB2 for i database refuses it.
Also I use ~ (tilde) as SQL separator but when I paste it uses ; (semi colon).

Result :
`INSERT INTO "sysibm"."sysdummy1" (IBMREQD) VALUES (
'Y');`

This should be :
`INSERT INTO sysibm.sysdummy1 (IBMREQD) VALUES (
'Y')~`

#### Steps to reproduce, if exist:
- Execute SQL statement like "SELECT * FROM TABLExxx"
- Right clic on results >Special copy > Copy as SQL
- Paste

PS : Please excuse my English, I am a French speaker.

PS 2 : Another subject, how to use / (slash) instead of . (dot) as schema <=> table separator ? Because I use system naming with my DB2 for i database.

**Comment by JMarkMurphy** [comment]
DB2 refuses it because when using double quotes, the schema name and the table name must be upper case. It just can't find "sysibm"."sysdummy1", but it would be able to find "SYSIBM"."SYSDUMMY1".

The other issue, concerning naming. Did you set the JDBC driver to *SYSTEM naming? Select your connection -> F4 for connection properties, then select the "Driver properties" tab

![image](https://user-images.githubusercontent.com/2379218/89790719-56b61080-daf0-11ea-9265-d48cad89e1cb.png)

Scroll down until you find "naming". This defaults to sql for JDBC. If you want to use slashes, change it to system.

**Comment by bnserig** [comment]
I didn't know about upper case when using double quotes.

I have already set naming to system. I use it in my scripts. But when I use "Copy as SQL" it doesn't generate with slash and tilde.
I have the same problem with auto completion of table names, it doesn't want slash.

**Comment by molok** [comment]
same issue for Oracle DB, Copy as SQL adds double quotes which are invalid

**Comment by p91paul** [comment]
@molok which Oracle version are you on? double quotes around schema/table/column/... names are most certainly valid on oracle 11+!

**Comment by molok** [comment]
@p91paul let me exaplain better the issue: when you create an object in Oracle you can use both lowercase and uppercase: the statement `create table mytable [...]` creates a table named `MYTABLE` becase object names are turned to uppercase unless double quoted. If a name is double quoted the supplied casing is respected. `create table "mytable" [...]`  creates a different object named precisely `"mytable"`. If I issue the query `select * from mytable` Oracle selects from the table MYTABLE, but when I use Copy as SQL, DBeaver generates a DML like this: `insert into "mytable" [...]`, that refers to a different (usually not existing) object. It should be generated as either `insert into "MYTABLE"` or `insert into MYTABLE`, but never `insert into "mytable"`

**Comment by LonwoLonwo** [comment]
@molok This is unusual. We don't have a default setting - to put in quotes the table names in "Copy as SQL". 
No, only mostly for tables with different symbols or keywords. At first glance, MYTABLE should not appear in quotes.

![2021-01-30 23_31_27-DBeaver Enterprise 7 3 3 - _SNOWFLAKE_SAMPLE_DATA_ Script-78](https://user-images.githubusercontent.com/45152336/106367471-efb53e00-6353-11eb-9f3c-436bc5f0a2b9.png)

**Comment by LonwoLonwo** [comment]
I can't reproduce this issue against the latest DBeaver version.
Please check your case in the latest versions.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
