### ISSUE TITLE
"%productName" is displayed in Windows notification area and also in Oracle session

### ISSUE THREAD

**Issue by cesarmansur** [dbeaver/dbeaver#8551]
Hello!
I'm having this issue using Eclipse plugin.
"%productName" is displayed instead of "DBeaver"
 
Eclipse version: 2020-03
![image](https://user-images.githubusercontent.com/43681608/80285163-648a8600-86f9-11ea-9e77-18ce1987bc93.png)
 
 
 
Dbeaver plugin: 7.0.3
![image](https://user-images.githubusercontent.com/43681608/80285182-8be15300-86f9-11ea-9b1e-5fecc4a534e3.png)
 
 
 
Operating System: Windows 10 Pro 64-bit
![image](https://user-images.githubusercontent.com/43681608/80285299-3e191a80-86fa-11ea-8997-a030431fc288.png)
 
 
 
Windows notification area:
![image](https://user-images.githubusercontent.com/43681608/80285443-5a698700-86fb-11ea-8cc5-47b736807fc6.png)
 
 
 
Oracle session details:
![image](https://user-images.githubusercontent.com/43681608/80285320-61dc6080-86fa-11ea-8633-841532b5feb4.png)

**Comment by serge-rider** [comment]
Thanks for the bug report!

Fixed

**Comment by uslss** [comment]
verified

**Comment by cesarmansur** [comment]
Thank you!
Fixed in version 7.0.4
