### ISSUE TITLE
Preferences -> Editors -> SQL Editor -> SQL Formatting

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#8554]
while fixing the CASE ... END indentation with PR #8547 I also tried to improve translation in  _Preferences -> Editors -> SQL Editor -> SQL Formatting_ but noticed some issues there:

* Shouldn't `pref_page_sql_format_label_add_line_feed_before_close_bracket` = _Insert break before close bracket_  be described as _Indent substatements in parentheses_ as it does not only affact the last line before the closing _)_

* `pref_page_sql_format_label_insert_delimiters_in_empty_lines` = _Insert delimiters in empty lines_ inserts ; in the middle of statements, e.g. before LEFT OUTER JOIN in first statement

* would be nice if there is a live preview of the settings. currently one has to click `Apply` at the other end of the dialog

I would enable  `pref_page_sql_format_label_add_line_feed_before_close_bracket` by default, else complex statements are difficult to read

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
verified
