### ISSUE TITLE
PostgreSQL sequences have DDL generated without START value

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#8555]
#### System information: 
- Operating system (distribution) and version
Windows 10 64 bit
- DBeaver version
7.0.3.202004191823
- Additional extensions
N/A
#### Connection specification:
- Database name and version
Aurora RDS for PostgreSQL 11.4
- Driver name
PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No
#### Describe the problem you're observing:
DDL for a sequences includes START value from pg_catalog.pg_sequences.last_value, but not from  pg_catalog.pg_sequences.start_value.
In case last_value is empty, the DDL will be missing a START value and creation will start it from 1 by default instead of start_value.
#### Steps to reproduce, if exist:
1. Run:
CREATE SEQUENCE new_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
        START 100
	CACHE 1
	NO CYCLE;
2. Display DDL in its' properties section and you'll see the "START 100" clause is missing.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed.
In ancient times (pg < 10) we used different query to read sequence info. This bug is a side effect.
