### ISSUE TITLE
Driver editor: anonymous and empty password properties are not saved

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#8557]
Applicable for custom drivers

**Comment by serge-rider** [comment]
Fixed. + Legacy JDBC suport added

**Comment by uslss** [comment]
Reset to Default button has no effect on the mentioned options.
1. Check option
2. Save settings
3. Open Settings - click Reset to Default - options are still checked

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
