### ISSUE TITLE
editing / adding records to Mariadb InnoDB tables not being saved or added

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#8559]
#### System information: 
- Operating system (distribution) and version : MacOS 10.14.6
- DBeaver version 7.0.3.202004191823

#### Connection specification:
- Database name and version: MariaDB 10.3
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

When I attempt to add records or edit existing in a Mariadb InnoDB table, it asks me if I want to commit / save, and I answer yes, and then records DON'T get saved or updated, even though they APPEAR in subsequent "select" statements; 

This is a BIG issue..

#### Steps to reproduce, if exist:

add or edit records in a mariadb innodb table, then hit select and records will appear in resultset, but will not be in table. trying to save the editor fails, and when I try to close the editor, it warns that "transactions are uncommited. do you want to commit them?" If I answer yes, then the records actually get added.

**Comment by uslss** [comment]
hi @rotorboy ,
do you use auto-commit or manual commit?

**Comment by rotorboy** [comment]
I believe manual; but with way, a pop up Iasks me if I want to save / add, and I answer yes. Yet 1. Records are not in DB and 2. Subsequent selects show changes / added items to BE in DB. So something very odd is happening. 

-Avi

**Comment by rotorboy** [comment]
ok, I turned on "Autocommit" and that seemed to update records correctly; have not tried to add any records, but this may have been a case of pilot error. 

That said, it might be worth pointing out after "save" in manual mode to remind the user that records have not been "committed". 

As a side not, I do love dbeaver's power, but the user interface complexity coupled with the myriad of cryptically-worded preferences that are vaguely mentioned in the docs, combine to make it hard to truly divine and use the full power of this tool properly.
