### ISSUE TITLE
Bookmarks in SQL-Editor

### ISSUE THREAD

**Issue by MeboGit** [dbeaver/dbeaver#8560]
Hello,

I use to work with large working script with lots of sql-statements within the sql editor. The problem is, when working on different projects I have to search for those areas manually.

For this reason bookmarks would be very helpful:
e.g.;
ctrl+alt+1 - ctrl+alt+9 -> set bookmark
ctrl+1 - ctrl+9 -> jump to bookmark
The bookmarks should be stored corresponding to scriptxy.sql

Also, a shortcut for inserting timestamp into sql script (for documenting):
e.g.:
alt+d -> insert date(today) as in OneNote

That would be really great.

Thanks for you work...

Mebo

**Comment by uslss** [comment]
thanks for suggestion

**Comment by Boudyno** [comment]
I support such a featue.

**Comment by uslss** [comment]
duplicate of #3416
