### ISSUE TITLE
UI plugins refactoring. org.jkiss.dbeaver.ext.db2

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#8562]
Refactoring for this plugin:
org.jkiss.dbeaver.ext.db2
Separate ui-part to new *.ui plugin

**Comment by uslss** [comment]
verified
1. Tools (high-level checking):
    - runstats - ok;
    - reorg table - ok;
    - reorg index - ok;
    - reorg check - ok;
    - truncate - ok

**Comment by uslss** [comment]
verified
