### ISSUE TITLE
DBeaver generates Creation DDL for Oracle temporary table as a regular table

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#8565]
#### System information: 
- Operating system (distribution) and version
Windows 10 64 bit
- DBeaver version
7.0.3.202004191823
- Additional extensions
N/A

#### Connection specification:
- Database name and version
Oracle 11.2.0.4
- Driver name
JDBC Thin Client for Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No
#### Describe the problem you're observing:
When generating DDL for a temporary table the "GLOBAL TEMPORARY" syntax is missing after the "CREATE" command.
#### Steps to reproduce, if exist:
1. Run: "CREATE GLOBAL TEMPORARY TABLE tmp (id number);"
2. Generate DDL for tmp

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Can't reproduce. It gives me this:
```sql
  CREATE GLOBAL TEMPORARY TABLE "HR"."TMP" 
   (	"ID" NUMBER
   ) ON COMMIT DELETE ROWS ;
```

We use query
```sql
SELECT DBMS_METADATA.GET_DDL('TABLE','TMP','SCHEMA_NAME') TXT FROM DUAL
```
to get DDL text.

**Comment by yonisade** [comment]
I understand the issue now.
I was using a user without SELECT_CATALOG_ROLE to generate DDL for a temp
table in another schema.
When I ran the SELECT DBMS_METADATA.GET_DDL('TABLE',[table_name],
[schema_name] ) TXT FROM DUAL
I got this error:
So SQL Error [31603] [99999]: ORA-31603: object [table_name] of type TABLE
not found in schema [schema_name]
ORA-06512: at "SYS.DBMS_METADATA", line 5805
ORA-06512: at "SYS.DBMS_METADATA", line 8344
ORA-06512: at line 1

So DBeaver uses an alternative way to generate DDL in this kind of scenario
apparently.

Yoni


‫בתאריך יום ג׳, 5 במאי 2020 ב-19:46 מאת ‪Serge Rider‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by serge-rider** [comment]
Yes, exactly. When dbeaver can't read DDL from server it generates it locally. 
And it is not 100% correct as it uses basic SQL dialect.

**Comment by yonisade** [comment]
In this case, the "temporary" column in all_tables can help DBeaver
generate the definition locally properly.

‫בתאריך יום ג׳, 5 במאי 2020 ב-22:45 מאת ‪Serge Rider‬‏ <‪
notifications@github.com‬‏>:‬
