### ISSUE TITLE
Snap Dbeaver Xlsx Office Error

### ISSUE THREAD

**Issue by hugorn** [dbeaver/dbeaver#8566]
The following error message is being displayed when trying to export the result to excel.
I'm using the snap version.
Can't open xlsx file '/tmp/.dbeaver-temp11107781619775476/20200427-114601.xlsx'

![image](https://user-images.githubusercontent.com/9035153/80387122-a0028d00-887e-11ea-973c-3d4810d86934.png)

**Comment by hugorn** [comment]
SO: Manjaro
Dbeaver Version: 7.0.3
DBeaver Office Support	1.1.68.202004191823
Snap

**Comment by uslss** [comment]
hi @hugorn ,
sorry for the late response. Is the issue still actual for you against the recent version?

**Comment by serge-rider** [comment]
XLSX generation work ok. 
But the error happens because dbeaver can't launch xlsx viewer (Calc in case of OpenOffice). Probably because of Snap-specific environment.

**Comment by riednyko** [comment]
The dbeaver snap package cannot open the office, but an xlsx file is generated. Most likely, the problem is in the snap permissions, while it is being resolved, the generated xlsx can be opened manually.

**Comment by riednyko** [comment]
Waiting for response to solve the problem
https://forum.snapcraft.io/t/snap-package-cannot-open-another-snap-package/19403

**Comment by uslss** [comment]
fixed
