### ISSUE TITLE
Avoid a delete without wherer

### ISSUE THREAD

**Issue by jyanezp** [dbeaver/dbeaver#8567]
Hi team,

Nice to meet you. I was wondering if you could help to me with an issue. 

Sometimes, we execute a delete without a where clause and it could be a big problem.

I was wondering if is any way to avoid it Dbeaver, such os set thi SQL sentence as a forbidden clause.

Thanks!

Regards,
Jose

**Comment by uslss** [comment]
thanks for suggestion

**Comment by jyanezp** [comment]
Hi @uslss ,

Thanks for your feedback. Is there any workaroud to avoid a delete without where in DBeaver at this moment?

Regards,
Jose

**Comment by amzbiz** [comment]
I can't speak for other versions but all of the PC versions I've used (up to 7.03) have a warning (by default) when you try to run a delete statement without a clause:

![dbeaver delete warning](https://user-images.githubusercontent.com/11863552/80925121-73e88e00-8de1-11ea-8a62-c52b4be4cc70.png)

**Comment by serge-rider** [comment]
Yes, we already have warnings for all DELETE/UPDATE queries without WHERE.

If you don't see such warning - check preferences:
![image](https://user-images.githubusercontent.com/6398845/81306307-fd20ee80-9087-11ea-93e0-7ea801dfd71f.png)
