### ISSUE TITLE
Add support for Ubuntu 20.04 LTS in the PPA

### ISSUE THREAD

**Issue by MrMitch** [dbeaver/dbeaver#8568]
**Is your feature request related to a problem? Please describe.**
The Launchpad PPA is not available for the new LTS release of Ubuntu 20.04.

**Describe the solution you'd like**
Add support for Ubuntu 20.04 (named Focal Fossa) to https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce

**Describe alternatives you've considered**
X

**Additional context**
Thank you for all the work you do on this, much appreciated !

**Comment by uslss** [comment]
thanks for suggestion

**Comment by MrMitch** [comment]
I see that the PPA now supports Ubuntu 20.04, this issue can be closed.

![image](https://user-images.githubusercontent.com/576772/82300784-9967c100-99b7-11ea-8780-b932d9c99147.png)


Thank you !
