### ISSUE TITLE
Generating DDL SQL from procedures does not work in Informix

### ISSUE THREAD

**Issue by michbudz** [dbeaver/dbeaver#8572]
#### System information: 
- Windows 8.1 Pro
- DBeaver version 7.0.3.202004191823

#### Connection specification:
- Database IBM Informix 12.10.FC9W1
- Driver name idfjdbc.jar 3.70.JC2DE
- Driver properties: 
CLIENT_LOCALE pl_PL.912
DB_LOCALE pl_PL.912

#### Describe the problem you're observing:
Generate DDL SQL from procedures does not work in Informix database. The resulting SQL is ";".

#### Steps to reproduce, if exist:
Connect to database, set active database, expand list and select procedure then generate DDL. **I mention that it works perfectly in DBeaver 6.0**

#### Include any warning/errors/backtraces from the logs
No erros in "Error Log" view.
No erros in workspace\.metadata\.log and workspace\.metadata\dbeaver-debug.log

**Comment by uslss** [comment]
Hi @michbudz ,
sorry for the so long response. We've got no environment to test it.
Cannot reproduce the issue for now against 7.2.0. Is it still reproducible for you? Thanks in advance
![image](https://user-images.githubusercontent.com/31996417/92614898-38952900-f2c5-11ea-9da9-83c3b06e69f1.png)

**Comment by LonwoLonwo** [comment]
![2020-10-07 14_30_51-DBeaver Enterprise 7 3 0 - _stores_demo_ Script-45](https://user-images.githubusercontent.com/45152336/95325376-cc98e700-08a9-11eb-9531-d86b70aa54bf.png)
can not reproduce also.
wait for answer a couple more days, than close
