### ISSUE TITLE
[Oracle] UI issues for Column Property

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8578]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.0.3

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
Fields for Type and Comment are cut on Column Property view
![image](https://user-images.githubusercontent.com/31996417/80586303-6ddb6180-8a1d-11ea-8ff0-8597cde8dd38.png)

**Comment by serge-rider** [comment]
It is a bug in generic UI layout (not Oracle-specific).

**Comment by uslss** [comment]
verified
