### ISSUE TITLE
Import Data - Column Case Sensitivity Issue

### ISSUE THREAD

**Issue by WustlRob** [dbeaver/dbeaver#8585]
#### System information: 
- Operating system (distribution) and version: Windows 10.0.18363 Build 18363
- DBeaver version: 7.0.3.202004191823
- Additional extensions

#### Connection specification:
- Database name and version MSSQL 11.0.6518.0 (X64)/Postgres 9.6
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When importing into existing Postgres table from MSSQL or CSV where source columns contains mixed case column names and Postgres table has all lowercase column names:
    - New fields are created in target table for columns that are unmatched due to case
    - Import fails because Nulls are being assigned to the unmatched columns which violate not null constraint.
    - Modifying target table to allow nulls lets the import complete successfully, however the target table definition has been changed with extra fields and data aren't in the expected 
![ImportIssue](https://user-images.githubusercontent.com/13892353/80647425-109eda80-8a34-11ea-90da-51c06afab8e2.png)
column.

**Comment by kseniiaguzeeva** [comment]
To avoids this situation you can change column mapping. For this:
1. Go to step **Tables mapping** of Export wizard
2. Click **Columns** btn
3. Set target columns
4. Export

![KeZ2KmW8CR](https://user-images.githubusercontent.com/51405061/80799201-dd348b00-8bae-11ea-8ffa-ed91404cb4f5.png)

Please ask if you have any addditional questions.

**Comment by WustlRob** [comment]
Thank you for the instructions.  I completely missed that feature.  This resolves my issue.
