### ISSUE TITLE
[SQL Server] Schema changes from the second time in SQL Editor

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8591]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.4 EA

#### Connection specification:
- Database name and version SQL Server

#### Describe the problem you're observing:
Schema changes from the second time in SQL Editor

#### Steps to reproduce, if exist:
Precondition:
A database schema is selected for SQL Server in SQL Editor which exists in other database (e.a. guest).
1. Press Ctrl+0
2. Select another database name in the left list
3. Double click a schema name in the right list (except which was already set)
Actual result: the database is changed, but the schema is not.
4. Press Ctrl+0
5. Double click a schema name in the right list (except which was already set)
Actual result: correct schema name is set
![mfd1pOIRsA](https://user-images.githubusercontent.com/51405061/80709909-d0546080-8af6-11ea-8bc2-4efba4a2fa50.gif)

**Comment by serge-rider** [comment]
Generally we can't change active schema in SQL Server. So it is not a bug.
@kseniiaguzeeva How did you set to guest?

**Comment by kseniiaguzeeva** [comment]
I didn't set schema guest as default, I just selected it in upper toolbar of SQL Editor. Steps:
1. Select SQL Server in SQL Editor
2. Press Ctrl+0
3. Double click a schema guest in the right list of the opened window
