### ISSUE TITLE
[SQL Server] "Read data in SQL console" opens SQL Editor for dbo schema

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8592]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.4 EA

#### Connection specification:
- Database name and version SQL Server

#### Describe the problem you're observing:
"Read data in SQL console" always opens SQL Editor for dbo schema.

#### Steps to reproduce, if exist:
1. Expand a schema except dbo in DB Navigator
2. Select "Read data in SQL console" in table context menu in the schema

Actual result:
dbo schema is selected in SQL Editor top toolbar
![QHgVeEPbu4](https://user-images.githubusercontent.com/51405061/80710764-f62e3500-8af7-11ea-9a56-5ff84950284c.gif)

**Comment by serge-rider** [comment]
It is not a bug.
We can't change default schema in SQL server.
Query work without problems (as it contains FQ table name)
