### ISSUE TITLE
[SQL Server] It is necessary to write the schema name in select query, if the schema is not dbo

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8593]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.4 EA

#### Connection specification:
- Database name and version SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
It is necessary to write the schema name in select query, if the schema is not dbo.

Steps:
1. Select a schema in SQL Editor (except dbo) with a table (table_name)
2. Write a simple query select * from table_name

Actual result:
1. Error message appears: "SQL Error [208] [S0002]: Invalid object name."
2. The query is not executed
![QDyvWC1NTd](https://user-images.githubusercontent.com/51405061/80715638-52e11e00-8aff-11ea-8e8e-c44c5307ce82.gif)

**Comment by serge-rider** [comment]
It is not a bug. 
SQL Server sees table only in default user schema (and in system schemas).

Generally this is true for all databases. And this is why "default" schemas exist.
