### ISSUE TITLE
Bind parameters window opens twice during export from query

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8595]
#### System information: 
- Operating system (distribution) and version  Win10
- DBeaver version 7.0.4 EA

#### Describe the problem you're observing:
Bind parameters window opens twice during export from query
#### Steps to reproduce, if exist:
1. Write a query with a bind paramater in SQL Editor
2. Export from query.

Actual result:
Bind parameters window opens twice
![wHkDHDRm2O](https://user-images.githubusercontent.com/51405061/80719841-b6217f00-8b04-11ea-9982-e7b4a91b4ecf.gif)

**Comment by LonwoLonwo** [comment]
still reproducible in 7.2.2

**Comment by kseniiaguzeeva** [comment]
Was resolved in scope of another ticket.
