### ISSUE TITLE
"Error switching active page" in connection settings window (v7.0.3)

### ISSUE THREAD

**Issue by ssilva** [dbeaver/dbeaver#8599]
Note: this seems related to #8406 

#### System information: 
- Microsoft Windows 10 Pro (10.0.18363 N/A Build 18363)
- DBeaver 7.0.3
- No additional extensions

#### Connection specification:
- Sybase 15.7
- jConnect 16.0 SP03 PL02 (Build 27403)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/103355/80751197-612b3c00-8af7-11ea-9ec1-4e644a812e43.png)

#### Steps to reproduce, if exist:
1. On the Database Navigator: right-click the database connection > Edit Connection
1. On the left, select away from "Connection settings" to any other section.

#### Include any warning/errors/backtraces from the logs
No errors on the Error Log view nor in the log files

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

P.S. Steps
1. Open Sybase connection settings
2. Click any vertical tab
3. Click connection settings tab

**Comment by ssilva** [comment]
Closing as I have been unable to reproduce this bug after upgrading to 7.1.0.
