### ISSUE TITLE
Cannot change active catalog in SQL Editor

### ISSUE THREAD

**Issue by jkaetz** [dbeaver/dbeaver#8600]
#### System information: 
- Operating system (distribution) and version Windows 10 2004 x64
- DBeaver version DBeaver Enterprise 7.0.0.202003081756
- Additional extensions None

#### Connection specification:
- Database name and version  Denodo 7
- Driver name  com.denodo.vdp.jdbc.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
The active catalog in the SQL Editor cannot be changed away from the one specified in the connection string.  All attempts to change the catalog appear to work, but executing the query will execute against the catalog in the connection string and the title bar will revert to the catalog in the connection string after execution.  
Auto-sync editor connection with navigator selection is turned off.
Open separate connection for each editor is on.

#### Steps to reproduce, if exist:
Connect to a database with multiple catalogs
Open an SQL Editor with the default catalog
Change to another catalog
Execute SELECT 1 or another database query
Catalog reverts to the one in the connection string

**Comment by serge-rider** [comment]
I can't reproduce this.

You can disable schema refresh in preferences:
![image](https://user-images.githubusercontent.com/6398845/81062801-4da91800-8edf-11ea-8f02-c08703afa84f.png)

**Comment by jkaetz** [comment]
Clearing that checkbox prevents the active schema dropdown from switching back to the one in the connection string but it does not cause the query to execute against that schema.  While monitoring the server the queries are executed against the schema in the connection string and not the one represented by the dropdown.

**Comment by zejji** [comment]
This issue also occurs for me using DBeaver 7.1.4 community edition (and has done over many different versions of DBeaver for a long time).

The 'Set active connection' and 'Set active schema' options are entirely non-functional when connecting to a SQL server database server, which means I am unable to use DBeaver for executing SQL statements against the databases and can only use DBeaver for browsing and editing tables via the GUI. I have to fall back to SSMS to actually execute bespoke SQL statements.

**Comment by techlock77** [comment]
@zejji @jkaetz
I am experiencing the same issue now. Is it resolved?

@serge-rider I have tried disabling schema refresh in preferences, but, NO LUCK.

Still cannot switch to another schema and every time I run a query it is by default picking up default schema mentioned in the connection.

**Comment by jkaetz** [comment]
@techlock77 
This is still a problem in version 21.0.0  The Refresh schema after execution box has little to do with it as the execution is taking place on the default schema of the connection and not the one selected in the toolbar.  As before the code completion is checking the proper schema, it is only the execution happening on the wrong schema.

My workaround is to have multiple connections and force the editor to sync to the navigation window.

@serge-rider is there a way to help diagnose/reproduce this?  I'm happy to send logs if I know how to generate them and where to collect them from.

**Comment by uslss** [comment]
is it still actual?
unfortunately, we've got no environment to test

**Comment by uslss** [comment]
there is no update for a long time.
If it is still actual - feel free to reopen the issue.
