### ISSUE TITLE
Space in field name, table at end, should be allowed.. truncate spaces

### ISSUE THREAD

**Issue by SherlockSoftware** [dbeaver/dbeaver#8602]
Posgres......... added field say "bananas " and accepted with SPACE after banana.
At least should warn,, re space ACCEPT or TRUNCATE name,.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by SherlockSoftware** [comment]
Team

What a great product… damn awesome.

I cut n pasted a field name from email…to myself  and database access from my inhouse system bit crazy.
Could see UT8 errors in dBeaver.. but could not see issue.

WTF..

See field like ‘logo_url’  I must have grabbed ‘logo_url ’  <-- the space

Dbeaver created the field with the space .. no complaints.
I would expect it to trim at least from the right.
Not sure why anybody would want a space on the left.

Postgres when I loaded another editor showed this field as “logo_url “ rather than logo_url
So it allowed it but Postgres showing it appends the quotes.

Warning or auto truncate would be better.

Thanks for listening..

Phil McGuinness – Sherlock Software - Australia

logo_url                                               string holding the url to the agent branding logo (required)
primary_colour                                 string holding hexadecimal code for the primary branding colour (required)
secondary_colour                            string holding hexadecimal code for the secondary branding colour (possibly not required but helpful in the future)
tertiary_colour                                  string holding hexadecimal code for the tertiary branding colour (possibly not required but helpful in the future)

**Comment by LonwoLonwo** [comment]
New fixes do not allow adding spaces at the beginning or end of the names of columns, tables, databases, connection settings and others.

**Comment by kseniiaguzeeva** [comment]
I still can insert space at the end or beginning in PostgreSQL objects names (which were mentioned above):
- always when an object is created via UI
- never  when an object is changed via UI

Space can be add at the end or beginning in connection settings fields also (is it expected?):
1. host,database, driver properties, SSH, SSL - no changes after adding a space
2. login,password - error appears

Build  7.1.1.202006240709

**Comment by LonwoLonwo** [comment]
@kseniiaguzeeva 

> always when an object is created via UI
Yes, it's works just for editing, not for creating objects. I did not specify.

> Space can be add at the end or beginning in connection settings fields also
https://github.com/dbeaver/dbeaver/issues/9043 another ticket for this situation

**Comment by kseniiaguzeeva** [comment]
Please remove the ability to insert a space in names also when creating an object.

**Comment by LonwoLonwo** [comment]
ability to create names with spaces for columns/schemas/constraints/packages/roles etc. removed

**Comment by kseniiaguzeeva** [comment]
Could you add tables in your list too?

**Comment by LonwoLonwo** [comment]
Tables creating added

**Comment by uslss** [comment]
verified
