### ISSUE TITLE
SQL editor frame does not use "Connection type" color choice

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#8603]
#### System information: 
- MAcOS 10.14
- DBeaver version: 7.0.3
- Additional extensions: JDBC

#### Connection specification:
- Database name and version: MariaDB
- Driver name: JDBC

#### Describe the problem you're observing:

When a SQL editor is opened to a connection, the editor "window frame" still has the "grey" border, as opposed to adopting the "connection type" color 

#### Steps to reproduce, if exist:

open SQL editor attached to "production connection type", and frame will remain grey.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. It duplicates #8052
