### ISSUE TITLE
[SQL Server] Unable to export to new database table

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8604]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.4 EA

#### Connection specification:
- Database name and version SQL Server

#### Describe the problem you're observing:
Unable to export to new database table
#### Steps to reproduce, if exist:
1. Open export wizard for a table via DB Navigator tree
2. Set new target table in Tables mapping step
3. Start Export

Actual result:
1. Error appears "Error starting data transfer  New table testtest not found in container ksu_1.dbo"
2. The table is not exported
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4562736/dbeaver-debug.log)
![kTbQE9xZZa](https://user-images.githubusercontent.com/51405061/80787108-36d88d80-8b8e-11ea-9bdd-22ec6580fee5.gif)

**Comment by serge-rider** [comment]
Fixed.
@kseniiaguzeeva please test the same for other databases (mysql, postgresql, oracle).

**Comment by kseniiaguzeeva** [comment]
verified
