### ISSUE TITLE
NPE appears after a disconnected database refresh

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8605]
#### System information:  
- Operating system  Win10
- DBeaver version 7.0.4 EA

#### Describe the problem you're observing:
NPE appears after a disconnected database refresh

#### Steps to reproduce, if exist:
Refresh a disconnected database in DB Navigator tree
![SjXuY3R0G5](https://user-images.githubusercontent.com/51405061/80798270-b2e1ce00-8bac-11ea-8e27-33da3f67d229.gif)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4563407/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
