### ISSUE TITLE
DBeaver doesn't show trigger table/code in properties window opened from trigger function dependencies window

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#8609]
#### System information: 
- Operating system (distribution) and version
Windows 10 64 bit
- DBeaver version
 7.0.3.202004191823
- Additional extensions
N/A
#### Connection specification:
- Database name and version
Aurora for PostgreSQL 11
- Driver name
PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No
#### Describe the problem you're observing:
DBeaver doesn't show table name of trigger in properties window opened from the trigger function 
dependencies window.
Trigger code would also be nice.
#### Steps to reproduce, if exist:
1. create table t (id numeric);
2. create or replace function trg_fnc ()
 returns trigger
 language plpgsql
as $function$
begin
return null;
end $function$;
3. create trigger trg_t after update of id on t for each row execute procedure trg_fnc();
4. open function trg_fnc from Database Navigator and go to dependencies tab.
5. double click on trigger name and see the issue.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Dependencies viewer was enhanced. Now we show link to the target object (if we can determine it).
Also we read more info about triggers (schema and table).

**Comment by uslss** [comment]
verified
