### ISSUE TITLE
Execute Statements In Separate Tabs is broken

### ISSUE THREAD

**Issue by psygnoser** [dbeaver/dbeaver#8610]
#### System information: 
- Operating system Fedora 31
- DBeaver version 7.0.4

#### Describe the problem you're observing:
The "Execute Statements In Separate Tabs" functionality stopped working a while back - it now always runs the query/SQL in the current tab if there are up to two tabs open or if there are more,  you get a modal asking you if you wish to close the unpinned tabs which you would usually get if trying to run the query/SQL statements normally (w/o opening a new tab). Anyway this bug has been present possibly since 7.0.0 ... not sure which was the last working version but it's been a while.
Also to note is that running just one SQL in a new tab ie. "Execute SQL in new tab" still works fine.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
duplicates issue from #8507 
anyway, thanks for the bug report
