### ISSUE TITLE
SQL query log / history

### ISSUE THREAD

**Issue by BuZZ-dEE** [dbeaver/dbeaver#8613]
Is it possible to see all SQL queries, I have entered since a date? If yes, where?

**Comment by uslss** [comment]
Hi @BuZZ-dEE ,
you could see your queries using query manager
![image](https://user-images.githubusercontent.com/31996417/80968521-c6956a80-8e20-11ea-8aa3-0548e43ee396.png)

**Comment by BuZZ-dEE** [comment]
As far as I can see there are only queries from the current date (today). Do I need configure something to see older queries?

**Comment by JaggedJax** [comment]
It would be nice to have at least a little more history provided as just now DBeaver crashed on me and when I reopened it all my queries were gone. Sigh.

**Comment by p91paul** [comment]
@JaggedJax that's a feature available only in the enterprise edition

**Comment by BuZZ-dEE** [comment]
😭

**Comment by p91paul** [comment]
The queries can be logged in log files as well. There is an option in preferences for which type of queries should go in the logs. Not as searchable as the query manager, but better then nothing.

**Comment by gitgud5000** [comment]
> @JaggedJax that's a feature available only in the enterprise edition

![SmilingSmilingCatGIF](https://user-images.githubusercontent.com/17186026/147601184-13270333-43f4-4d8c-95e2-ef26a7040011.gif)
