### ISSUE TITLE
Connection settings default database doesn't work

### ISSUE THREAD

**Issue by kamil-p** [dbeaver/dbeaver#8614]
#### System information: 
- Operating system (distribution) and version MacOS, Catalina 10.15.4
- DBeaver version Version 7.0.4.202005031953
- Additional extensions: 0

#### Connection specification:
- Database name and version 5.6.33-0ubuntu0.14.04.1
- Driver name mysql:mysql-connector-java:RELEASE 5.1.44
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I specified the database in the connection configuration, but it didn't affect the database list. I can see all of them instead of one. 

#### Steps to reproduce, if exist:
Setup connection and specify one the database.
Connect.
You should see all databases instead of one.

**Comment by kseniiaguzeeva** [comment]
Please tell, whether **Show all databases** is disabled in Connection settings? What database do you use?

![dbeaver_NvjyX7DS2I](https://user-images.githubusercontent.com/51405061/81067996-489c9680-8ee8-11ea-9b7a-bee7e79e242e.png)

**Comment by kamil-p** [comment]
@kseniiaguzeeva it is for MySql (see the driver version above) I don't have such settings:

![image](https://user-images.githubusercontent.com/3785571/81097050-9d9bd500-8f07-11ea-8c3e-78e2c19b987c.png)

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce for MySQL 5.1.44 also.  
1. Do you have user privelegues to see all tables?
2. Can you see all databases if the database **app** is deleted from **Connection settings**?

**Comment by kamil-p** [comment]
Thank you. I have recorded my screen hope it will help to reproduce it [https://streamable.com/bz2rkn](https://streamable.com/bz2rkn) I can observe the same issue on my laptop as on my mac mini at work. Expected behaviour is to see only `app` DB.

**Comment by kseniiaguzeeva** [comment]
Now I see. It is expected behavior. Default database is set so that SQL Editor opens for it, when you click SQL Editor btn.

Please reopen the ticket or create a new one if you have any other questions.

**Comment by serge-rider** [comment]
@kamil-p If you don't need all databases in MySQL then you can use filters (right click on Databases->Filter)
