### ISSUE TITLE
Sybase ASA 9 - Multi column Primary Key problem

### ISSUE THREAD

**Issue by albertodegon** [dbeaver/dbeaver#8615]
#### System information: 
- Windows 10 Pro - Build 1909
- DBeaver 7.0.4 (same bug with the other 7.0.X versions, already tried to rollback)
- NO Additional extensions

#### Connection specification:
- Sybase Adaptive Server Anywhere 9.0.2.3951
- Sybase jConnect
- No tunnels

#### Describe the problem you're observing:

DBeaver incorrectly loads the primary key from all the tables dividing a single primary key formed by many columns in many primary keys formed by one column. 

Example of a table from ASA 9 DB (**wrong pks**)

![image](https://user-images.githubusercontent.com/27743252/80967635-f9d2fc00-8e16-11ea-9584-db58a185fa78.png)

Same table from ASA 11 DB (**right key**)

![image](https://user-images.githubusercontent.com/27743252/80967647-fdff1980-8e16-11ea-9b2d-e47d8db266d7.png)

#### Steps to reproduce, if exist:

Connect to a Sybase ASA 9 DB and open the TABLE PROPERTIES tab, all the tables with multi column PKs will be incorrectly displayed

This is a MASSIVE bug beacause inline edit will be using only the first column in the primary key and boom, the disaster is done.

#### Include any warning/errors/backtraces from the logs
When connecting to the DB, i get this error
[log_connect.log](https://github.com/dbeaver/dbeaver/files/4574795/log_connect.log)

Thanks.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
@albertodegon Do you use the same driver for both databases?
DBeaver uses JDBC database metadata to read primary key info. Maybe it is a driver-specific issue.

I agree that it is a major issue. But I don't know how to fix it yet.

**Comment by albertodegon** [comment]
> @albertodegon Do you use the same driver for both databases?
> DBeaver uses JDBC database metadata to read primary key info. Maybe it is a driver-specific issue.
> 
> I agree that it is a major issue. But I don't know how to fix it yet.

Yep, same driver.
I suppose that the driver dosent return the Primary Key name connected to the single column right ?
Otherwise you should merge these column in a single Key using this name (that should be unique)

**Comment by serge-rider** [comment]
Yeah, we already do this. And it works well for newer Sybase servers.
I assume that database doesn't return PK name at all or returns column name as a constraint name.

Unfortunately I can't test it as I don't have Sybase 9 server around.
We need to find a way to log driver API calls.

**Comment by serge-rider** [comment]
@albertodegon I've add extra logging.
Could you do this:
1. Download and install Early Access version from https://dbeaver.io/files/ea
1. Add line `-Ddbeaver.jdbc.trace=true` in the end of dbeaver.ini file
1. Run dbeaver, connect to your database and see table unique constraints

The go to `%APPDATA%\DBeaverData\workspace6\.metadata` and see contents of `jdbc-api-trace.log` file. There should be line 
```
-- Load primary keys
...
```
Please post everything under this line here. It will let me understand what is wrong with driver metadata read.

Thank you

**Comment by albertodegon** [comment]
Ok done, these are the table unique constraints

-- Load primary keys [cassa, DBA, PARAMETRI]
-------------------------------------------------------
TABLE_CAT [varchar] | TABLE_SCHEM [varchar] | TABLE_NAME [varchar] |
COLUMN_NAME [varchar] | KEY_SEQ [unsigned int] | PK_NAME [varchar] |
cassa | DBA | PARAMETRI | PARAMETRI_LOGIN | 1 | PARAMETRI_LOGIN |
cassa | DBA | PARAMETRI | PARAMETRI_MLUSER | 4 | PARAMETRI_MLUSER |
cassa | DBA | PARAMETRI | PARAMETRI_NOMEPAR | 2 | PARAMETRI_NOMEPAR |

I think you were right, it seems a real driver problem....



Il giorno mer 6 mag 2020 alle ore 15:08 Serge Rider <
notifications@github.com> ha scritto:

**Comment by serge-rider** [comment]
New driver version may be no fully backward compatible.

Maybe you need to use older driver for this Sybase version. 
Server should come with the JDBC driver, you could ask DBA about it.

**Comment by albertodegon** [comment]
> New driver version may be no fully backward compatible.
> 
> Maybe you need to use older driver for this Sybase version.
> Server should come with the JDBC driver, you could ask DBA about it.

Yep, that's what I'm trying to. But with the SQL Anywhere 11.0.1 jconn.jar, that should be the right driver, the result is the same.

Any method to disable inline edit at some conditions in dbeaver ?

**Comment by tati-kru** [comment]
@albertodegon unfortunately, there is no a known workaround for this issue. 

We cannot fix it on the DBeaver side.
