### ISSUE TITLE
Scrollbars appears in the editor while there's nowhere to scroll

### ISSUE THREAD

**Issue by braiam** [dbeaver/dbeaver#8616]
#### System information: 
- Operating system (distribution) and version: debian testing
- DBeaver version: 7.0.1
- Additional extensions: none

#### Describe the problem you're observing:

While producing a problem similar to issue https://github.com/dbeaver/dbeaver/issues/5398 , both scrollbar hides content in the editor, even when there's 0 pixels to scroll horizontally or vertically.

#### Steps to reproduce, if exist:

- Create a "New SQL editor"
- Put the pointer inside the editor box

![image](https://user-images.githubusercontent.com/1323412/80978884-a354c600-8df4-11ea-83ed-8c2bf0372fd3.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
will be fixed in the scope of #10950
