### ISSUE TITLE
Closing a script does not prompt to save it

### ISSUE THREAD

**Issue by nickberg-2020** [dbeaver/dbeaver#8617]
#### System information: 
- Mac OSX Catalina
- 7.0.4
- Git

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Closing a script does not prompt to save it

#### Steps to reproduce, if exist:

Create a new script or update an existing one. Script title bar changes to include a 
*, click close. Script closes with no prompt to save and does not save

**Comment by Zak8022** [comment]
Experiencing the same thing here. Only started with v7.0.4.

**Comment by 2019-05-10** [comment]
Same here.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by Neutrino-Sunset** [comment]
This isn't fixed at all.

I create a project linked to a directory on disk.

Right click Scripts -> Create -> Create New File

I get a script tab with the title '<none> Script'

If I close the editor window it gets deleted off disk.

I have to edit and save the file for it to not get deleted.

It's a ridiculous user experience.
