### ISSUE TITLE
DB Metadata Search Not Working

### ISSUE THREAD

**Issue by SamD** [dbeaver/dbeaver#8619]
#### System information: 
- Ubuntu 20.04
- 7.0.4.202005041853

#### Connection specification:
- PostgreSQL 10.10 on x86_64-unknown-linux-gnu, compiled by x86_64-unknown-linux-gnu-gcc (GCC) 7.3.0, 64-bit
- PostgreSQL JDBC Driver
- Using tunnel created outside of dbeaver

#### Describe the problem you're observing:
A simple table search produces no results

#### Steps to reproduce, if exist:
Connect to the database
CTRL+H
Select DB Metadata tab
On left panel select the target database connection
On right side select table and Name match: contains
In Object Name to search for enter a known table that exists and search
No results are returned
#### Include any warning/errors/backtraces from the logs
No errors produced in log

**Comment by SamD** [comment]
So my connection is set to `Show all databases`
Setting the active database returns the table in the metadata search, before the table did not belong to the default connected `postgres` db

So the search functionality only works against one database and not was is shown as available in the selected connection? If that is the case this is a bit confusing perhaps you need to indicate you have to specifically select the database in the left panel instead of having the connection alone being able to be selected

**Comment by kseniiaguzeeva** [comment]
Yes, you are right. The search goes within a default database. 
Thank you for the suggestion to refer it in Metadata search panel. I will change the ticket on feature request.
