### ISSUE TITLE
Sybase ASA 9 - problem selecting DB

### ISSUE THREAD

**Issue by oscvic** [dbeaver/dbeaver#8620]
**System information:**

    Windows 10 Pro - Build 1803
    DBeaver 7.0.4 (same error after version 6.3.0. Version 6.3.0 works fine.)
    NO Additional extensions

**Connection specification:**

    Sybase Adaptive Server Anywhere 9.0.2.3951
    Sybase jConnect
    No tunnels

**Describe the problem you're observing:**

the problem occurs when you tried to choose the database. I noticed this problem after version 6.3.0
![issue 1](https://user-images.githubusercontent.com/9664852/81017011-c4caa780-8e1e-11ea-843a-d77b8f0822d2.png)
![issue 2](https://user-images.githubusercontent.com/9664852/81017049-cdbb7900-8e1e-11ea-84a2-1b14c89d6bd8.png)

**Steps to reproduce, if exist:**

connect to a Sybase 9 database, you may notice the error and the default DB is not selected.
selecting it manually also generates the problem.

**Include any warning/errors/backtraces from the logs**

[errors.log](https://github.com/dbeaver/dbeaver/files/4577959/errors.log)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
cannot reproduce it for now.
If issue is still actual - feel fre to reopen it
