### ISSUE TITLE
Driver attempts to download from http://central.maven.org

### ISSUE THREAD

**Issue by elliottfrantz** [dbeaver/dbeaver#8622]
Steps to reproduce:

Database -> Driver Manager -> Mssql -> SQL Server -> Edit -> Download/Update

I am getting an error `Error resolving driver libraries` and `error resolving dependencies`

The request made seems to be going to `http://central.maven.org` when it seems like it should be made to `https://repo1.maven.org`

Editing to add: My local proxy configuration seems to be causing dbeavers certificate validation of `repo1.maven.org` to fail where it downgrades to `central.maven.org` this request throws a 404. Is there another `http://` repository available?

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce. Could you please tell DBeaver version and your OS?

**Comment by elliottfrantz** [comment]
> I cannot reproduce. Could you please tell DBeaver version and your OS?

Desktop is Windows 10. The workstation is configured with a web proxy; although the proxy certificate is trusted on the desktop, dbeaver seems to use it's own trust store to validate (this is fine). However it would be nice to inform the user that there is an error with the certificate validation of the maven repo.

It then tries to connect to the plain-text http://central.maven.org repo to fetch the drivers. The pom files no longer exist here. And causes the `Error resolving driver libraries` error. It would be nice here to show the user there was a 404 to help them debug. This took me a couple hours to figure out what was causing the misleading error message.

**Comment by serge-rider** [comment]
By default DBeaver uses https://repo1.maven.org.

http://central.maven.org is a legacy plain http repository. It is left for backward compatibility for those who, by any reason, can't use https protocol to download artifacts from Maven.

DBeaver uses legacy repo only if repo1 is not accessible and it warns user about unsecure driver download.

Recently non-https Maven Central repository was banned (that's great actually).
We need to remove non-secure Central repository config completely. Thanks for noticing this.

**Comment by kseniiaguzeeva** [comment]
verified
