### ISSUE TITLE
Random crashes after update

### ISSUE THREAD

**Issue by davideio87** [dbeaver/dbeaver#8623]
Hello everybody
I recently updated my Dbeaver from version 5.XXX to the latest 7.0.4

Sadly it crashes a lot of times, like every 10-20 minutes and I didn't found a common cause yet. The first times it was happening when opening a recent .SQL file because it was trying to reconnect to the latest db on which that sql was used, then I removed the reconnect option and things are better, still I get lots of crashes.

I'm running it on Windows 10 Enterprise and I use it to connect to Mysql 8.0.19

I can't find any log to attach, because the dbeaver-debug.log in the workspace is overwritten at any restart and I don't have any hs_err_*.log file in any folder in my pc.

How can I find more info about this problem to share?

thanks!

**Comment by uslss** [comment]
Hi @davideio87 ,
do you try to reset the workspace?
https://github.com/dbeaver/dbeaver/wiki/Reset-workspace

**Comment by davideio87** [comment]
Hello
sadly both solutions didn't work, it took longer to crash but still... 
This time it happened while trying to click on the suggestions appeared while I was writing a table name. Of course I can disable it, but it's just a workaround

The worst part is that I can't find anywhere the logs of the error, to understand what goes wrong.

Thanks

**Comment by uslss** [comment]
hi @davideio87 , is it still reproducible for you against the current version?
Probably, you could post a video. It can help to investigate an issue. Thanks in advance

**Comment by uslss** [comment]
there are not any updates on issue. Ticket will be closed.
If issue is still actual for you - feel free to reopen the ticket
