### ISSUE TITLE
Mariadb 10.3 not showing "user management"

### ISSUE THREAD

**Issue by polrus** [dbeaver/dbeaver#8624]
#### System information: 
- Operating system (distribution) and version
raspibian 10 (debian buster for arm) for raspberry 4
- DBeaver version 7.0.4
- Additional extensions

#### Connection specification:
- Database name and version
mariadb 10.3
- Driver name
MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
ssh tunnel
#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/9408405/81046299-5cc89f80-8eb8-11ea-8d1f-5b2e93cc7b72.png)

see the screenshot - both DBs are connected as root. 
The local one is an older version on my localhost and works as expected

The 46_tunnel one is a 10.3 mariadb on raspibian.
It has no Databases,Users,Administer,System info categories at all

**Comment by uslss** [comment]
hi @polrus ,
probably you have Simple view enabled (for this connection).
Please try to switch to Advanced View: Connection context menu - Connection view - Advanced
![image](https://user-images.githubusercontent.com/31996417/81053645-1716d180-8ece-11ea-944b-b86aefd6ce75.png)

**Comment by polrus** [comment]
Hi @uslss 
You are completely right - sorry for the lame bug report - I must have switched it to basic mode accdently.  I had not even been aware such mode existed.
