### ISSUE TITLE
Binding params doesnt work for selected code

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#8628]
Params binding doesnt work once Im selecting multiple queries

My test query:

![image](https://user-images.githubusercontent.com/5410448/81072856-12124c00-8ee7-11ea-8a4c-00547c424483.png)

As you can see param was bound only to 1 of 2 selected queries 

![image](https://user-images.githubusercontent.com/5410448/81072825-07f04d80-8ee7-11ea-8ac6-541586ccccfd.png)

**Comment by uslss** [comment]
hi @maciey ,
unfortunately, cannot reproduce an issue. params are asked one-by-one for me. 
How do you execute the script: select queries and execute it or just click Execute SQL script (alt+x)?

**Comment by maciey** [comment]
Im selecting code and pressing ctrl+enter 
As you can see on my example preview shows only 1st sql with replaced @table -> YYYYY

I think I've found how to repeat that:
1. select multi sqls script, ctrl+enter -> params replacement doesnt work (preview only!)
2. execute script (even if in preview sqls are shown as not replaced)
3. return to point (1) -> now preview works...

See my screen recording to demonstrate steps

![params_demo](https://user-images.githubusercontent.com/5410448/82410964-215dd180-9a71-11ea-8e06-8e375ae413a9.gif)

**Comment by uslss** [comment]
you could use alt+x or Execute SQL script instead. Does it suit you?
![2020-05-21_18h11_45](https://user-images.githubusercontent.com/31996417/82573581-9ecb3400-9b8e-11ea-80b8-7f590dd771f1.gif)

**Comment by maciey** [comment]
I'll give a try - but Id prefer (fixed version) of CTRL+Enter TBH :)

I have quite often 20+ queries in window - looking on your GIF - it seems I'll see 20x popup asking same param name ?

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
