### ISSUE TITLE
Change view of DB2TablespaceChooser dialogArea

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#8629]
Change view of DB2TablespaceChooser dialogArea
Delete NLS unused message in org.jkiss.dbeaver.ext.db2.ui.internal.DB2Resources

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/81412364-69652600-914c-11ea-9426-0b4bbd0168be.png)
