### ISSUE TITLE
After updating the Community edition of Dbeaver to 7.0.4 it stopped asking to save the SQL scripts before closing & hence many times I am closing the Dbeaver & accidentally loosing all of my changes that i have done on the SQL scripts.

### ISSUE THREAD

**Issue by dhirajkumarsinha27091982** [dbeaver/dbeaver#8630]
After updating the Community edition of Dbeaver to 7.0.4 it stopped asking to save the SQL scripts before closing & hence many times I am closing the Dbeaver & accidentally loosing all of my changes that i have done on the SQL scripts.

**Comment by uslss** [comment]
seems to be duplicate of  #8617 
anyway, thanks for the bug report
