### ISSUE TITLE
Pressing Ctrl+Backspace in data viewer filter clears active cell

### ISSUE THREAD

**Issue by fabianMendez** [dbeaver/dbeaver#8631]
#### System information: 
- Ubuntu 20.04
- DBeaver 7.0.4

#### Describe the problem you're observing:
If I press `Ctrl+Backspace` to delete a word in the filter of the data viewer it clears the active cell and does not delete the word

#### Steps to reproduce, if exist:
1. Right click on a table and select view data
2. Enter some text in the filter input
![imagen](https://user-images.githubusercontent.com/32204060/81086771-8dabd300-8ebe-11ea-8f28-24cf63cc4d58.png)
3. Press `Ctrl + Backspace`

The active cell gets cleared

![imagen](https://user-images.githubusercontent.com/32204060/81086954-c2b82580-8ebe-11ea-967d-e3b89bb09c19.png)

But I expected this:

![imagen](https://user-images.githubusercontent.com/32204060/81087027-d6fc2280-8ebe-11ea-9787-912d8cfbf52c.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
It is not a bug. <kbd>ctrl+backspace</kbd> for "Set default value" action. 
You can change it in Preferences->Keys.

**Comment by fabianMendez** [comment]
Oh I see, though I think is a little contra-intuitive that it clears the cell when the filter is focused.

**Comment by fabianMendez** [comment]
Fixed in version 7.1.2
