### ISSUE TITLE
Port field too narrow for longer ports

### ISSUE THREAD

**Issue by tobias47n9e** [dbeaver/dbeaver#8636]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04, Gnome Wayland session
- DBeaver version: Version 7.0.4.202005031953 (Flatpak)

#### Describe the problem you're observing:
Port field in edit-connection dialog is not wide enough for five digit ports. Should be a little wider so it can be viewed and edited comfortably.

On the screenshot you can see that only 4 digits of the 5 digit port are visible:

![dbeaver_port_field](https://user-images.githubusercontent.com/6953323/81167901-4ee94c00-8f96-11ea-87b7-d46f79bf1f46.png)

**Comment by uslss** [comment]
verified
