### ISSUE TITLE
UI plugins refactoring. org.jkiss.dbeaver.ext.exasol

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#8638]
Refactoring for this plugin:
org.jkiss.dbeaver.ext.exasol
Separate ui-part to new *.ui plugin

**Comment by kseniiaguzeeva** [comment]
1. Tools import table/export table- checked (only old bugs exist)
2. Session manager "force application"- checked
3. Lock Manager - skipped
4. New schema creation - verified
5. Constraint creation- checked
6. Foreign keys creation- checked (only old bugs exist)
7. Schema functions creation- checked (only old bugs exist)
7. Connection page- checked
