### ISSUE TITLE
Autosave SQL sheet

### ISSUE THREAD

**Issue by Ferrox12** [dbeaver/dbeaver#8640]
Hi,
with the last update, when I close a SQL sheet the alert that allows me to save the worksheet no longer appears.
Where can I reactivate it?
Is there a method to autosave the sheet?

**Comment by kseniiaguzeeva** [comment]
Looks like a bug. As a workaround you can use **Auto-save editor on close** (Database settings>SQL Editor).
![dbeaver_yr8I34KjyN](https://user-images.githubusercontent.com/51405061/81179981-19069080-8fb3-11ea-81ce-dc216500494b.png)

**Comment by uslss** [comment]
seems to be duplicate of #8617
