### ISSUE TITLE
SQL editor will not close after opening read only files

### ISSUE THREAD

**Issue by informje** [dbeaver/dbeaver#8643]
Windows 10  (1809) machine running DBeaver 7.0.4.202005031953.

In SQL Editor, after successful creation of a working query, I save it to a folder and mark it as read only. Thereafter if I open the same file it appears in the the sql editor as modified (* appears on the tab) and will never close on clicking the close (x) button on the tab. I will need to kill the program or choose to save as the file. 
        This issue can be reproduced by just opening a read only sql script in dbeaver. Then without changing anything try to close the file by clicking the (x) on the tab.

![DbeaverError](https://user-images.githubusercontent.com/5599400/81222697-b01f1880-8fb2-11ea-812d-d83b9f9d74b1.PNG)

Please see the attachment

**Comment by uslss** [comment]
hi @informje ,
unfortunately, cannot reproduce an issue.
could you provide you read-only file example? thanks in advance
![2020-05-07_12h25_36](https://user-images.githubusercontent.com/31996417/81278198-039a7080-905e-11ea-8d5c-fea9dd5287fa.gif)

**Comment by informje** [comment]
Me too could not reproduce this issue. Actually, the first line of the function somehow moved up in the read only file to cause this issue. This is evident in the screen shot provided. What caused it I am unable to tell.  But , I have experienced this 3 or 4 times at least. Will post back with more details when I come across this again. Any logs to look for that will provide hints?

**Comment by uslss** [comment]
thanks for response.
Logs could be very helpful.

**Comment by informje** [comment]
Attached is the whole DBeaverData folder in the Roaming profile. If it was something else you wanted, please let me know. The issue occurred  around the same date I made the original bug report. Tnx
[DBeaverData.zip](https://github.com/dbeaver/dbeaver/files/4611181/DBeaverData.zip)

**Comment by p91paul** [comment]
Guy, I hope you didn't save anything more than development databases... there be passwords stored in that folder of yours.

**Comment by informje** [comment]
it is only a dev env.

**Comment by informje** [comment]
Ok. I was able to reproduce this bug. Below are the steps. It does not happen normally but it does in my environment as we always do step one below.
1. Enable writing connection binding in script header.
![image](https://user-images.githubusercontent.com/5599400/87948591-e6791980-ca72-11ea-8e8c-7de9b7c15a57.png)
2. Create a .sql file. Add an extra blank line at the beginning of the file (above the connection info). Save and mark the file as read only.
![image](https://user-images.githubusercontent.com/5599400/87948931-58516300-ca73-11ea-96a1-a4c358fbdaf3.png)
3. Now open this read only file in Dbeaver, the application adds connection info at the beginning of the read only file. Thereafter it never saves or let us exit the application. Need to start Task manager to kill it.
![image](https://user-images.githubusercontent.com/5599400/87949163-ab2b1a80-ca73-11ea-8cdd-f86ae3c9c39d.png)

I am using the Dbeaver CE Version 7.1.0.202006031909 windows app on windows 10 1903. The same issue was happening on desktop versions also.

Thanks,

**Comment by uslss** [comment]
@informje , still cannot reproduce :( what am I doing wrong? :(
![2020-07-29_14h48_58](https://user-images.githubusercontent.com/31996417/88796766-dff14d00-d1aa-11ea-9102-5d35a5f11208.gif)

**Comment by informje** [comment]
Hi, You are doing it correctly. But why I am I not getting the dialogue box asking if I want to make the file writable? Instead, I am getting an infinite loop with that error dialogue in my environment. 

Which version of Dbeaver / OS are you using?  Let me try that. Tnx



Get Outlook for Android







On Wed, Jul 29, 2020 at 7:51 AM -0400, "uslss" <notifications@github.com> wrote:















@informje , still cannot reproduce :( what am I doing wrong? :(

**Comment by uslss** [comment]
Try it against 7.1.0 CE, pop-up is still triggered. Error pop-up mentioned by you appears only in case I choose not to make file writable.
Could you try to reset UI settings (Main Menu: File - Reset UI Settings) and write back if it helps?
thank you in advance

**Comment by uslss** [comment]
there is no update on the issue for a long time.  
If the issue is still actual for you - feel free to reopen the ticket with additional info that could help to investigate and reproduce an issue.
