### ISSUE TITLE
Number of concurrent connection when use with AWS redshift

### ISSUE THREAD

**Issue by darouwan** [dbeaver/dbeaver#8644]
- Windows 10 64 bit 1809
- DBeaver version 7.0.4

- Database name and version
Redshift

Describe your question:
The redshift I am using limits concurrent connection number to 3 at most. But when I use dbeaver to connect with redshift, our dba finds that there are 3 connections existed for the dbeaver so I cannot establish any other connections. All 3 connections start almost at the same time. So the 3 connections are all necessary ? Can I config the concurrent connection  for dbeaver when it connect to redshift?

Thanks!

**Comment by serge-rider** [comment]
By default dbeaver opens separate connection for each SQL editor. You csn disable this behavior in references:
![image](https://user-images.githubusercontent.com/6398845/81278018-cf26b480-905d-11ea-9db7-52b6bbffe038.png)

Also you can disable separate metadata connection if you have this option enabled:
![image](https://user-images.githubusercontent.com/6398845/81279496-e666a180-905f-11ea-9b1f-6aa5b781d728.png)

**Comment by darouwan** [comment]
The issue has been solved. Thanks!
