### ISSUE TITLE
Postgres Schema Change. DBeaver 7.0.4, Windows 10. When creating new tables, or compiling procedures, DBeaver is now ignoring default schema setting. Even if default setting shows schema_1, after compile it switches to Public. Appears to have something to do with Alt X.

### ISSUE THREAD

**Issue by ianamac** [dbeaver/dbeaver#8645]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Hi @ianamac ,
cannot reproduce an issue. works work for me. probably some special steps are needed?
![2020-05-07_12h19_35](https://user-images.githubusercontent.com/31996417/81277492-2b3d0900-905d-11ea-8b6a-e0ec690d6d4e.gif)

**Comment by ianamac** [comment]
See attached screenshots. See default schema in navigator, and in top bar on both. It compiled into public.
![pic_1](https://user-images.githubusercontent.com/56263529/81283929-ba4a2100-905d-11ea-8c79-b832ae249a83.PNG)
![pic_2](https://user-images.githubusercontent.com/56263529/81283966-c7671000-905d-11ea-932d-d4061e5ec1a1.PNG)
