### ISSUE TITLE
DBeaver v7.0.4, Windows 10.  Exporting a grid to CSV, am now forced to enter schema before all file names, otherwise it cannot find any relation. I think this is a bug, not a feature, as you may have multiple schema's with the same data structures, and now you cannot have a generic script.

### ISSUE THREAD

**Issue by ianamac** [dbeaver/dbeaver#8646]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Hi @ianamac ,
cannot reproduce an issue. could you post more clear steps that can help to investigate an issue?

**Comment by ianamac** [comment]
![pic_3](https://user-images.githubusercontent.com/56263529/81283605-3859f800-905d-11ea-8636-06e8e8a53404.PNG)
![pic_4](https://user-images.githubusercontent.com/56263529/81283626-3d1eac00-905d-11ea-9e8b-1b5a760fd7f1.PNG)
![pic_5](https://user-images.githubusercontent.com/56263529/81283636-41e36000-905d-11ea-8806-7556b85fbe67.PNG)
![pic_6](https://user-images.githubusercontent.com/56263529/81283653-46a81400-905d-11ea-9111-aa4427dd9a05.PNG)

**Comment by ianamac** [comment]
See above screenshots. Notice the default schema in navigator, and schema in top bar
