### ISSUE TITLE
Autocomplete does not work if the schema name in script has different case than in navigator

### ISSUE THREAD

**Issue by zolovey** [dbeaver/dbeaver#8647]
#### System information: 
- Operating system (distribution) and version: Win 10
- DBeaver version: 7.0.4

#### Connection specification:
- Database name and version: Sybase IQ SAP IQ/16.1.030.1437
- Driver: jConnect (TM) for JDBC(TM)/16.0 SP03 PL02 (Build 27403)/P/EBF27518/JDK 1.6.0/jdbcmain/OPT/Mon Aug 28 18:41:14 PDT 2017

#### Describe the problem you're observing:
Autocomplete does not give suggestions of the tables if the schema name in script has different case than in navigator.

I.e. if in Navigator schema name is DB, then when typing in script db. then autocomplete does not give suggestions of the tables under the schema

**Comment by uslss** [comment]
Hi, @zolovey .
If mixed case is used, you should write object names using double-quotes.

**Comment by zolovey** [comment]
Unfortunately it does not help.

But I've noticed that with Oracle DB there are no such issues (schema can be written in lowercase/uppercase, and autocomplete works)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by zolovey** [comment]
any news about the issue?

**Comment by LonwoLonwo** [comment]
Hello @zolovey 
Can you please test the new DBeaver version?
https://dbeaver.io/

Also, examples of incorrect behaviour will be very helpful.

**Comment by zolovey** [comment]
hi @LonwoLonwo 
checked 21.1.1 version

problem still exists

![image](https://user-images.githubusercontent.com/56155099/121681460-855f9780-cac3-11eb-97a4-dbdd1f6f99e6.png)

![image](https://user-images.githubusercontent.com/56155099/121681479-898bb500-cac3-11eb-9b10-48fd0174032f.png)

**Comment by LonwoLonwo** [comment]
and originally "SYS" in upper case is schema name?

**Comment by zolovey** [comment]
> and originally "SYS" in upper case is schema name?

Yep

**Comment by LonwoLonwo** [comment]
Ok, thanks for the help.

**Comment by zolovey** [comment]
@LonwoLonwo any progress on this bug?

**Comment by LonwoLonwo** [comment]
As I can see, Sybase supports mixed case in the names of tables, schemas etc.
For this reason DBeaver can't find schema "sys" in the list of schemas.
So I'm not sure what can I do in this situation.

**Comment by zolovey** [comment]
@LonwoLonwo can't you just convert everything to same case? i mean typed value and metadata when trying to find suggestions for autocomplete?

**Comment by zolovey** [comment]
@LonwoLonwo any thoughts/updates on the issue?

**Comment by LonwoLonwo** [comment]
Ok, ok. We can find some time for this ticket. I will add it to our development queue.
