### ISSUE TITLE
sec_to_time shows wrong value

### ISSUE THREAD

**Issue by mhenselin** [dbeaver/dbeaver#8648]
#### System information: 
- Operating system: Linux Mint 19
- DBeaver version: 7.0.4 / 7.0.3
- Additional extensions

#### Connection specification:
- Database: MariaDB 10.2
- Driver name: mariadb
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

running the query ```SELECT sec_to_time(127122) as time; ``` shows wrong value (18:xxxx should be 35:xxx) 

phpMyAdmin shows correct value

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by kseniiaguzeeva** [comment]
1. Please recheck the wrong value in Resultset. Is it 18:xxxx or 11:18:42?

2. If you enable Use native date/time format (Preferences>DBeaver>Editors>Data Editor>Data Formats), the result will be correct: 35:18:42
![dbeaver_HSTC6MHgXf](https://user-images.githubusercontent.com/51405061/82906539-170a6e80-9f6e-11ea-81db-169fb50bf113.png)

**Comment by mhenselin** [comment]
Just as an idea: 
should this probably be the default setting? It's hard to discover this "buggy" behaviour in daily usage.

**Comment by kseniiaguzeeva** [comment]
Thank you for your suggestion
