### ISSUE TITLE
Oracle number is reported as number(22,127)

### ISSUE THREAD

**Issue by asgh-mh** [dbeaver/dbeaver#8653]
#### System information: 
- MacOS 10.15.3
- DBeaver 7.0.4

#### Connection specification:
- Oracle

#### Describe the problem you're observing:

A number datatype is reported as number(22,127) in the Properties view but not when generating DDL.

#### Steps to reproduce, if exist:

CREATE TABLE foo (
	bar NUMBER
);

Then view the resulting table (and check the columns). However if you Generate DDL for it, it shows correctly.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
Fixed in 7.1.1
