### ISSUE TITLE
Closing File No Longer Prompts To Save Changes

### ISSUE THREAD

**Issue by Xylandor** [dbeaver/dbeaver#8655]
#### System information: 
- Windows 10 v1903 (OS Build 18362.788)
- DBeaver v7.0.4
- No extensions

#### Connection specification:
- N/A. Issue not related to any database connection.

#### Describe the problem you're observing:
Ever since upgrading from v7.0.3 to 7.0.4, DBeaver no longer prompts to save changes to any script file. So if you close the file or exit DBeaver without saving changes first, you will lose all your work.

#### Steps to reproduce, if exist:
1. Create a new script or open an existing one.
2. Make changes.
3. Without saving the file, close the script. You'll notice that it did not prompt you to save your changes.

![DBeaver-704-UnsavedChangesIssue](https://user-images.githubusercontent.com/24617679/81420183-318ebc00-9115-11ea-9e7d-912cb79d9e70.gif)

#### Include any warning/errors/backtraces from the logs
Issue did not trigger any errors.

**Comment by uslss** [comment]
fixed in scope of #8617 .
Anyway, thanks for the bug report
