### ISSUE TITLE
Update dbeaver lost all plugins

### ISSUE THREAD

**Issue by ceinmart** [dbeaver/dbeaver#8656]
Hi, 
I usually install/upgrade my dbeaver using the .zip package. 
I do not use the executable package because of the security company policies. 
Every time I update my dbeaver with last version I lost my plugins. 
Already notice if I didn't overwrite the "Configuration" folder they are kept but appears that some updates won't occur. 
Today I always install the Eclipse Market place and then I install vrapper (vim editor) . 
How I can avoid is annoying issue?

**Comment by uslss** [comment]
dupicate of #5317
