### ISSUE TITLE
Add ltree to "data type" options

### ISSUE THREAD

**Issue by mikicho** [dbeaver/dbeaver#8660]
**Is your feature request related to a problem? Please describe.**
ltree (postgres) option is missing:
![image](https://user-images.githubusercontent.com/11459632/81471054-18f6d280-91f7-11ea-8415-24ab6c0fb7b6.png)

**Describe the solution you'd like**
Add this data type to the list 

**Describe alternatives you've considered**
Create it via script

**Additional context**
N/A

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
verified
