### ISSUE TITLE
connection timeout on remote postgresql 10.4

### ISSUE THREAD

**Issue by lucamaf** [dbeaver/dbeaver#8661]
#### System information: 
- Operating system (distribution) and version: RHEL8.1 on docker image
- DBeaver version: 7.0.4
- Additional extensions

#### Connection specification:
- Database name and version: Postgrsql 10.4
- Driver name: PostgreSQL standard driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
yes, tried using both ssh port forward and ngrok but none works

#### Describe the problem you're observing:
I have a database deployed as container on OpenShift and while I'm perfectly able to connect when using the available command `oc port-forward` whenever I tried to forward the port using other methods (ssh tunnel or ngrok) I always received a connection time out. I tried also increasing the timeout in the connection settings with no success. I would also like to mention that there is no apparent firewall or network issue, since when the ssh tunnel or ngrok is running I can easily telnet on the assigned address and forwarded port.
I also checked the pg_hba.conf and have a row that reads like this:
`host all all all md5`
So I assume I should be allowed to connect remotely.

#### Steps to reproduce, if exist:
try to connect to a remote db instance using port and host forwarding

#### Include any warning/errors/backtraces from the logs
I was able to trace the connection with wireshark and noticed that in the case of failure dbvear is sending a PSH flag after the tcp connection is established

**Comment by uslss** [comment]
hi @lucamaf ,
please check if it works ok using telnet 
e.g. 
```
ssh user@domains.corp.com
telnet db.corp.com 3306
```

**Comment by uslss** [comment]
There isn't update on the issue for a long time.
If it is still actual for you - feel free to reopen the ticket
