### ISSUE TITLE
Dirty flag (asterisk) on editor tab name does not reset on succesful save

### ISSUE THREAD

**Issue by mark2016** [dbeaver/dbeaver#8663]
#### System information: 
- Windows 7 Pro
- DBeaver 7.04
- Additional extensions: none

#### Connection specification:
- Database name and version: Oracle 11
- Driver name: Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : Not via the Dbeaver driver but we connect via VPN to our LAN.

#### Describe the problem you're observing:
The Edit file tab filename does not change from <*filename.sql> to <filename.sql> when saving.

#### Steps to reproduce, if exist:
1. Open DBeaver
2. Open <filename.sql> file
3. Edit the file and observe the tab name changes from <filename.sql> to <*filename.sql>
4. Hit save (observe the tab name changes from <*filename.sql> to <filename.sql>
5. Close DBeaver (Settings are such that <filename.sql> opens automatically with DBeaver next time.)
6. Open DBeaver and observe the tab name is <filename.sql>
7. Execute a query (without editing the file) and observe the tab name changes from <filename.sql> to <*filename.sql>
8. Attempt to save, filename remains as <*filename.sql>
9. Edit the file, filename remains as <*filename.sql>
10. Save the file, filename remains as <*filename.sql>
11. Check the file with a different editor (eg Notepad), confirm that it has been saved

#### Include any warning/errors/backtraces from the logs

No logs

**Comment by uslss** [comment]
hi @mark2016 ,
cannot reproduce an issue. Is query still executed after step 7?

**Comment by mark2016** [comment]
Yes query executes. I've done a UI reset, I shall try a reset to defaults
and reinstall. It's been happening since my update to 7.03. Yesterday I
found that the first tab has stopped saving too (other tabs save).

**Comment by mark2016** [comment]
This is fixed: Uninstall, delete workspace folders, re-install and choose to Reset Settings as well as declining to migrate old settings on re-install.
Looks to be caused when migrating from DBeaver v6 to v7.03.
Thank you!
