### ISSUE TITLE
MS SQL Server ClientConnectionId

### ISSUE THREAD

**Issue by gduin** [dbeaver/dbeaver#8664]
I got "Login failed for user myUser ClientConnectionId" using dbeaver on linux but when I tried using dbeaver on Windows connection was successful. The database server is at AWS. I have installed the same version 7.0.4.202005031953 in both OS,

**Comment by uslss** [comment]
Hi @gduin ,
is it still reproducible for you against the recent version?
What authentication type do you use?

Sorry for the late response
