### ISSUE TITLE
Stored Procedure Properties DDL not showing - UI Bug(?)

### ISSUE THREAD

**Issue by Christian1912** [dbeaver/dbeaver#8665]
**System information:**
DBeaver  7.0.4.202005031953
Windows Server 2008 R2
(Problem did not appear in the previous version)

**Connection specification:**
DB2 LUW, com.ibm.db2:jcc:RELEASE 11.5.0.0

**Describe the problem you're observing:**
DDL is not shown anymore for stored procedures in properties overview.

**Steps to reproduce, if exist:**
Choose a procedure, F4, click on DDL.

DDL not showing, UI not changing at all. If you switch to Date & Time the DDL is shown there below.

![image](https://user-images.githubusercontent.com/65155608/81535565-5334b100-936a-11ea-9bc4-55192d82f94f.png)

![image](https://user-images.githubusercontent.com/65155608/81536253-888dce80-936b-11ea-90d8-8e5c6f08f978.png)

DDL is still created when procedure is chosen -> generate SQL -> DDL but there is no way now to disabled the automated formatting.

If you need more information let me know - I couldn't find any existing issue regarding this.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by Christian1912** [comment]
Thank you, fixed in 7.0.5!
