### ISSUE TITLE
 no mssql-jdbc_auth-8.2.0.x64 in java.library.path facing this issue

### ISSUE THREAD

**Issue by Harshitha1991** [dbeaver/dbeaver#8666]
![image](https://user-images.githubusercontent.com/65168686/81559655-6e74e000-93ad-11ea-8ceb-44475ef237c5.png)

- Tried Reset to default and download/Update. 
   Try to reset driver settings.
   From connection settings dialog click Edit Driver Settings -> Reset to Defaults (at the bottom).
   Then dbeaver is not asking dlls re-download, only jar downloads is prompted
- Manually placed the  no mssql-jdbc_auth-8.2.0.x64.dll file 
- Ensured both  no mssql-jdbc_auth-8.2.0.x64 and sqlserver version is the same.

Please help as this is blocking me.
Windows authentication only failed. Server Authentication works fine for me.

System information:
Operating system (distribution) and version: MacOS Catinila
DBeaver version 7.0.4 community

Connection specification:
Microsoft SQL Server

**Comment by Harshitha1991** [comment]
@uslss : I followed all your steps related to previous similar tickets. Did not help me solve the issue. Please guide me on this

**Comment by uslss** [comment]
hi @Harshitha1991 , 
unfortunately, cannot reproduce an issue. Is it actual for newly created connection too?
Could you show what is proposed when you click Download/Update button?

**Comment by Harshitha1991** [comment]
![image](https://user-images.githubusercontent.com/65168686/81634975-aae82080-942d-11ea-83d4-789488ff47c7.png)
I see only the jar in recommended downloads. But not mssql-jdbc_auth-8.2.0.x64.dll.
Please refer to the attached screen shot for more infow

**Comment by serge-rider** [comment]
Native Windows authentication available only on Windows machines. 
You can't load this DLL on MacOS.

**Comment by SantoshKesava** [comment]
I have the same issue. 
System : Mac OS Catalina
Dbeaver Version : 7.1
Tried the below steps but no luck
1. Download/upadate the drivers
2.Reset the drivers to default

please help

Thank you
Santosh

**Comment by uslss** [comment]
is it still actual?

**Comment by nmduarte** [comment]
I am facing the same issue still - are there any updates?

System : Mac OS Catalina
Dbeaver Version : 7.1.4

I have tried resetting to defaults and download them manually - no luck with any of the approaches.

Thank you,
Nuno

**Comment by EasonFanCHN** [comment]
How to download the drvier mannually?
System: Mac OS Catalina
Dbeaver Version: 7.1.5

**Comment by emiliogarza** [comment]
> Native Windows authentication available only on Windows machines.
> You can't load this DLL on MacOS.

Is there anyway around this? I have a MS Sql Server database I need to authenticate to with Windows Authentication on Mac OS

**Comment by p91paul** [comment]
@emiliogarza you can try jtds driver (should be a different connection type when creating connection). Look for documentation online, through some driver properties you can specify you windows domain, username and password. It lacks some other functionality with respect to official Microsoft driver however.
