### ISSUE TITLE
Error while connecting to Databricks Spark via VPN

### ISSUE THREAD

**Issue by 450031** [dbeaver/dbeaver#8667]
#### System information: 
- Window 10 Enterprise
- DBeaver version 6.3.4.202002011957

#### Connection specification:
- Azure Databricks - Spark

#### Describe your question:
When trying to connect to Spark while on VPN, I encounter the following error: 

[Simba][SparkJDBCDriver](500151) Error setting/closing session: HTTP Response code: 403.
  HTTP Response code: 403
  HTTP Response code: 403

JDBC URL: jdbc:spark://eastus.azuredatabricks.net:443/default;transportMode=http;ssl=1;httpPath=sql/protocolv1/o/7339348852698591/0406-221629-exile318;AuthMech=3;UID=token;PWD=<insert token here>;UseNativeQuery=1

**Comment by uslss** [comment]
is it still actual against the current (7.2.x) version?

**Comment by 450031** [comment]
I no longer use DBeaver.

Jennifer Romero-Higgins
American Airlines
Business Analytics (Orion/Mosaic) – Data Architect (PHX)
(480) 872-3110 Office
