### ISSUE TITLE
Date format not respected when importing CSV (at least with SQLite)

### ISSUE THREAD

**Issue by guardiande** [dbeaver/dbeaver#8669]
#### System information: 
- MacOS 10.15.4
- DBeaver 7.0.4

#### Connection specification:
- Database SQLite
- Driver SQLite
#### Describe the problem you're observing:

Importing CSV does not respect the date format specified in the import dialog.

**dates.csv**

```
format,value
yyyy-MM-dd,2025-12-31
dd.MM.yyyy,31.12.2025
```

**Import settings (note the German date format)**

<img width="391" alt="image" src="https://user-images.githubusercontent.com/4947715/81578570-471d1380-93ab-11ea-9666-0030aa9ee815.png">

**Check whether a valid date was imported**

```
SELECT format, value, JULIANDAY(value)
FROM dates;
```

**Output**

<img width="392" alt="image" src="https://user-images.githubusercontent.com/4947715/81579037-ec37ec00-93ab-11ea-8169-4c3cbc1c921d.png">

#### Steps to reproduce, if exist:

1. Create CSV file as shown above.
1. Create a new SQLite database.
1. Create a table
   ```
   CREATE TABLE dates (
	format TEXT,
	value DATE
    );
1. Refresh the database in the connection view so that the table appears.
1. Right click the table and select "Import data"
1. Select CSV, select the created csv table, set the date format to `dd.MM.yyyy'
1. Start the import.
1. Check the results (see above).

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by guardiande** [comment]
Just tried against 7.2.3, same steps as described above - still does not work as expected.
