### ISSUE TITLE
Data Editor Number Format Regression, Take 2 (not using scientific notation)

### ISSUE THREAD

**Issue by austin-beer** [dbeaver/dbeaver#8670]
Issue #8099 was not fixed in DBeaver 7.0.1 and so I'm re-opening that issue as a new issue.

#### System information: 
- Operating system (distribution) and version: Ubuntu 19.10
- DBeaver version: 7.0.4
- Additional extensions: N/A

#### Connection specification:
- Database name and version: PostgreSQL 10.6
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes, an SSH tunnel

#### Describe the problem you're observing:
Very small numbers are not being displayed with scientific notation in the data editor which makes it very difficult to see the actual value of the numbers with any degree of precision.

Using default number format settings:
![Rounding1](https://user-images.githubusercontent.com/22201316/81580034-22ed1280-936a-11ea-903f-bc66a9c3364f.png)

Increasing maximum fraction digits from 10 to 30:
![Rounding2](https://user-images.githubusercontent.com/22201316/81580080-326c5b80-936a-11ea-86a3-c89d519fb548.png)

Using native numeric format:
![Rounding3](https://user-images.githubusercontent.com/22201316/81580123-3ef0b400-936a-11ea-8002-85b79a9939db.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
Well, we removed scientific notation because of multiple user requests.
It is hard to decide how to show floating point numbers better. In many cases scientific notation makes column values hardly readable.

Maybe we should add extra data format option "Use scientific notation"?

@austin-beer WDYT?

**Comment by serge-rider** [comment]
Anyway, let's try it:

![image](https://user-images.githubusercontent.com/6398845/82760794-b577c200-9dfe-11ea-9038-a8fd26330bc2.png)

**Comment by uslss** [comment]
scientific notation isn't shown in Data Grid View. Text view and Value panel - ok
![image](https://user-images.githubusercontent.com/31996417/82879835-3392b080-9f46-11ea-9454-b16672038613.png)

**Comment by austin-beer** [comment]
> Well, we removed scientific notation because of multiple user requests.
> It is hard to decide how to show floating point numbers better. In many cases scientific notation makes column values hardly readable.
> 
> Maybe we should add extra data format option "Use scientific notation"?
> 
> @austin-beer WDYT?

Hmm, yes it is difficult to show floating point numbers well. I think adding a scientific notation option is "good enough" for now. Ideally I'd like an option that's similar to C's `printf("%17g")` where 17 provides maximum precision for doubles, but it sounds like that's not easy to exactly replicate in Java. Perhaps `String.format("%.17g", x)` would still be good enough, though.

https://stackoverflow.com/questions/873298/what-is-the-java-equivalent-of-cs-printf-g-format-specifier

**Comment by serge-rider** [comment]
It has to work now. 
Scientific format pref change now affects data immediately.
"Restore to defaults" was also fixed.

**Comment by uslss** [comment]
Scientific format pref change now affects data immediately - ok
"Restore to defaults" - repened in scope of #5368
