### ISSUE TITLE
Unable to build DBeaver in Eclipse (unknown extension point)

### ISSUE THREAD

**Issue by deceits** [dbeaver/dbeaver#8671]
Hi, 
I am trying to build Dbeaver in Eclipse. Most plugins build are working fine except it failed on:

org.kiss.dbeaver.ext.ui.colortheme 
(Unknown extension point: 'org.github.eclipsecolortheme.mapper')  

org.jkiss.dbeaver.ui 
(Unknown extension point: 'com.github.eclipsecolortheme.mapper') 

any idea?

**Comment by serge-rider** [comment]
It is just a warning, you can ignore it (and configure Eclipse to ignore such type of errors)
