### ISSUE TITLE
preferred way to define driver properties in dbeaver extension?

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#8674]
e.g. name of dummy table can be defined with

* `<parameter name="dual-table" value="...">` in plugin.xml
* `getDualTableName()` in SQLDialect class

what is preferred?

**Comment by serge-rider** [comment]
`<parameter name="dual-table" value="...">` makes sense only for Generic driver. 
In case of Generic driver there is no big difference. If there is SQL dialect implementation then probably it is better to define it there.

**Comment by kai-morich** [comment]
dummy table is returned by `HANASQLDialect.getDualTableName()` but 
`Database -> Driver Manager -> SAP/HANA -> Edit -> Advanced Parameters` does not show value for `dual table name`. looks like this view only considers values from plugin.xml
