### ISSUE TITLE
DBeaver reconnects all tabs/connections

### ISSUE THREAD

**Issue by peter-petrov** [dbeaver/dbeaver#8675]
#### System information: 
- Windows 10
- DBeaver version 7.0.2

#### Connection specification:
- Postgres 11

#### Describe the problem you're observing:
Say you have 20 open tabs/connections which you access via VPN.
You disconnect the VPN.

You reconnect to the VPN later (say in 10-12 hours).
You go to one of your open tabs in DBeaver and run a past/old query.
DBeaver then tries to reconnect all 20 tabs instead of just the current one.

**Comment by uslss** [comment]
seems it is not reproducible for now
