### ISSUE TITLE
[DB2] Index couldn't be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8676]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.0.4

#### Connection specification:
- Database name and version db2 luw
#### Describe the problem you're observing:
Index couldn't be created both in 
schema:
![image](https://user-images.githubusercontent.com/31996417/81674216-7f792c00-9455-11ea-988f-637272135e88.png)
table:
![image](https://user-images.githubusercontent.com/31996417/81674239-89029400-9455-11ea-8fad-5bc5115e3d02.png)

**Comment by LonwoLonwo** [comment]
no function "create index" in schemas == no problem :)

**Comment by uslss** [comment]
verified
