### ISSUE TITLE
MySQLCreateDatabaseDialog dialog fix

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#8681]
Create database dialog in MySQLCreateDatabaseDialog is not stretched correctly
![2020-05-12 22_09_11-DBeaver 7 0 1 - ACT](https://user-images.githubusercontent.com/45152336/81746124-9ef07300-94ae-11ea-9cf4-058ec9ab3100.png)

**Comment by uslss** [comment]
verified
