### ISSUE TITLE
Unable to enter min/max value range for row gradiant for read-only result column

### ISSUE THREAD

**Issue by overlind** [dbeaver/dbeaver#8683]
#### System information: 
- Windows 10 Pro 1909   (also tested on Windows 10 Enterprise 1903)
- DBeaver CE 7.0.4.202005031953
- Additional extensions

#### Connection specification:
N/A --- tested on local SQLite, MySQL 5.6 via SSH tunnel, and MySQL 8.0

#### Describe the problem you're observing:
I'm unable to enter a min/max value range to apply a color gradient to cells in the results grid if the column is marked as read-only.

#### Steps to reproduce, if exist:
I'm trying to apply range/gradient colors to cells in the results grid with integer values.  If the column is directly from a table, I can specify the min/max values for the range.  But if the column is the result of a calculation, it is read-only with a padlock icon on the column header, and the min/max values boxes in the customize colors box do not let me type in them.  The background/foreground color for the min value (that remains blank) then only applies to zero values.

#### Include any warning/errors/backtraces from the logs
none

Thanks,

David

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
