### ISSUE TITLE
NuoDB generate DDL not working properly

### ISSUE THREAD

**Issue by EstefaniaGilVaquero** [dbeaver/dbeaver#8685]
#### System information: 
- Operating system (distribution) and version: Win 10
- DBeaver version: 7.0.4

Hi guys, thanks in advance for your help, here is my problem.

I'm working with a NuoDb database, and when i try to generate the DDL from a table i don't get the columns of the table, please see picture below.

![image](https://user-images.githubusercontent.com/18489811/81785831-18b04d00-94ff-11ea-9206-269e5f8e89a6.png)

This feature is working fine with other database types like oracle and postgre, so i guess there is something wrong with NuoDb drivers or something. The NuoDb driver i've installed is:

![image](https://user-images.githubusercontent.com/18489811/81786317-c3287000-94ff-11ea-9189-ed46ad7eb03f.png)

Best regards

**Comment by EstefaniaGilVaquero** [comment]
i've realized that the problem is that the columns info does not appear in some tables, but it is ok in others.

For example i crete theese two tables:

CREATE TABLE "[SCHEMA]"."activation_method"
(
   activation_method_id varchar(2) NOT NULL,
   issuer_id varchar(4) NOT NULL,
   token_type_id varchar(1) NOT NULL,
   desc_act_met varchar(100),
   has_customer_data boolean NOT NULL,
   is_suspicious boolean NOT NULL,
   delivery_method_id varchar(2) NOT NULL,
   CONSTRAINT activation_method_pkey PRIMARY KEY (activation_method_id,issuer_id,token_type_id)
);

CREATE TABLE "[SCHEMA]"."bin"
(
   bin_id varchar(10) PRIMARY KEY NOT NULL,
   date_end timestamp,
   date_start timestamp,
   max_pan NUMERIC (22),
   min_pan NUMERIC (22),
   issuer_id varchar(4) NOT NULL,
   token_type_id varchar(1) NOT NULL,
   brand_id varchar(3) NOT NULL,
   type_bin_id varchar(3),
   score varchar(3)
);

One display column data:
![image](https://user-images.githubusercontent.com/18489811/81830826-dc034680-953c-11ea-809d-7c6668e2d2e6.png)

But not the other one:
![image](https://user-images.githubusercontent.com/18489811/81830908-f6d5bb00-953c-11ea-8b99-c706fb34d7f0.png)

Any idea???

**Comment by uslss** [comment]
hi @EstefaniaGilVaquero ,
unfortunately, we've got no such database (but we think about getting it in future) at the moment so we cannot investigate an issue for now. 
BR

**Comment by uslss** [comment]
there is no update for an issue for a long time.
if it is still actual against the recent version (21.1.3) feel free to reopen it with an additional info
