### ISSUE TITLE
Do not show object comment script in DDL Tab

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#8686]
DBaever version 7.0.4

very uncomfortable deсision. in past versions IDE do not show table comment script in DDL Tab
such as 'COMMENT ON TABLE mytable IS 'mytable ''
, show only comment for table column.

it was nice to view all DDL object script.

**Comment by serge-rider** [comment]
It is actually a bug.
Thanks for the report.

**Comment by uslss** [comment]
verified
