### ISSUE TITLE
Http driver repository has to be deleted

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8689]
Http driver repository has to be deleted, namely:
http://maven.nuiton.org/nexus/content/groups/releases/

![dbeaver_y4fMSaXKZ9](https://user-images.githubusercontent.com/51405061/81812438-cb4bd400-952e-11ea-8c93-cf95efaff788.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
virified
