### ISSUE TITLE
Insert Table Alias (in Join Clause)

### ISSUE THREAD

**Issue by cristianoisaac** [dbeaver/dbeaver#8690]
I'm using version 7.0.4 and there is an option on SQL Completion of 'Insert table aliases(in FROM clause). I like this very much but i didn't understand why there isn't an option of "Insert Table Alias (in Join Clause)" too. Some SGBD accepts multiple table in FROM clause that would put all alias but others don't and need to use the JOIN clause. Is it possible to add in Preferences -> DBeaver -> Editors -> SQL Completion an option to "Insert Table Alias (in Join Clause)"?

Thanks.

**Comment by E1izabeth** [comment]
As far as I see alias is inserted in joins on the latest DBeaver version.
