### ISSUE TITLE
Pgpass disappeared from CE version

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8691]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version  DBeaver	7.0.5.202005131147

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
Pgpass disappeared from CE version

#### Steps to reproduce, if exist:
Open Main tab of PostgreSQL connection settings

![dbeaver_q7mI5o6gib](https://user-images.githubusercontent.com/51405061/81826684-b710d280-9540-11ea-8579-58e039373f97.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Auth dropdown menu is visible now, but error appears "FATAL: password authentication failed for user "..." when I try to connect with pgpass.
Steps:
1. Create file pgpass.conf with content hostname:port:database:username:password
2. Put it in folder %APPDATA%\postgresql\
3. Create PostgreSQL connection via VPN
4. Select PgPass in Authentication dropdown menu
5. Press Test Connection btn

Actual result: the test is failed.
![dbeaver_Ck8WwjRlDJ](https://user-images.githubusercontent.com/51405061/81832899-b62f6f00-9547-11ea-8852-93eaaee766ab.png)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4622958/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
