### ISSUE TITLE
Parenthesis highlighting

### ISSUE THREAD

**Issue by mlazatinph** [dbeaver/dbeaver#8693]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.0.4
- Java version: 14.0.1

#### Describe the problem you're observing:
Starting in dBeaver 7.0.4, the closing parenthesis disappears after pressing enter right after the closing parenthesis. It also leaves an artifact on the opening parenthesis.

Here's the screenshot before pressing enter. It looks okay.
![before enter](https://user-images.githubusercontent.com/16606959/81834627-c8270700-9573-11ea-86c0-d4c243f2b46d.png)

After hitting enter, the closing parenthesis disappears from view. The background highlight did not disappear. There is a line of yellow after the opening parenthesis.
![after enter](https://user-images.githubusercontent.com/16606959/81834637-cc532480-9573-11ea-91f3-4199eda2446f.png)

Putting the cursor after the closing parenthesis brings back the closing parenthesis into view.
![putting cursor back to closing parenthesis](https://user-images.githubusercontent.com/16606959/81834645-cfe6ab80-9573-11ea-9238-556d339bd948.png)

#### Steps to reproduce, if exist:
Type "select count(*)" then press enter.

####Note:
This issue does not appear on dBeaver 7.0.4 on Mac with Java version 13. It also does not appear in dBeaver 7.0.3 on both Windows 10 with Java 14.

**Comment by uslss** [comment]
hi @mlazatinph ,
cannot reproduce an issue. Did you try to reset UI settings? (File - Reset UI Settings)
![2020-05-14_11h13_09](https://user-images.githubusercontent.com/31996417/81909925-f89e8d80-95d3-11ea-8075-5c616fb7dcba.gif)

**Comment by mlazatinph** [comment]
hi @uslss ,
I just tried "File - Reset UI Settings" and the issue is still there.

**Comment by mlazatinph** [comment]
hi @uslss ,
I tried erasing c:\Users\myuser\AppData\Roaming\DbeaverData and the issue no longer appears
