### ISSUE TITLE
Tabs blinking 

### ISSUE THREAD

**Issue by facundonrs** [dbeaver/dbeaver#8694]
Tabs started to blink since I installed AnyDesk on Debian 9 (stretch) 64-bit
Gnome version 3.2.2
When I installed Anydesk I had Dbeaver 6.3.0, so I updated to 7.0.4 but the problem still remains.

I shared a video to ilustrate the problem.
[https://www.youtube.com/watch?v=6MUmDqYOHQE](url)

**Comment by uslss** [comment]
It could be a known issue with GTK3 on Ubuntu (https://bugs.eclipse.org/bugs/show_bug.cgi?id=517671)

Could you try proposed workaround (export GTK_IM_MODULE=ibus)?

**Comment by extremejbr** [comment]
I'm like the same problem here.

Linux Mint 19.3
Cinnamon version 4.4.8
DBeaver Community 7.0.5

**Comment by facundonrs** [comment]
Sorry about the late response!

I tried adding **export GTK_IM_MODULE=ibus** to the **/etc/profile** file and it worked for me. (After reboot the system)

So, thanks **uslss** very much.

Ps: I'm not a good english speaker. Sorry if I had misspellings.

**Comment by extremejbr** [comment]
@facundonrs @uslss 
This worked for me.
On the Linux Mint I used the file /~/.profile.

Thanks very much.
