### ISSUE TITLE
Hide toolbars in views

### ISSUE THREAD

**Issue by WalterOesch** [dbeaver/dbeaver#8696]
#### System information:
- Operating system (distribution) and version: Microsoft Windows 10 Enterprise Version	10.0.17134 Build 17134
- DBeaver version:  7.0.4.202005031953	

#### Connection information:
- not relevant in my opinion

#### Question: 
Great tool with a lot of features, nonetheless very stable! 

Is there a way to customize or hide the toolbars of the views? The toolbar of the main window can be custimized, as I noticed.

Mainly I would like to customize the toolbars for the result / table view. I would like to remove some toolbars or buttons of toolbars.

Thank you,
Walter

**Comment by uslss** [comment]
unfortunately, it is not implemented yet. 
thanks for suggestion

**Comment by WalterOesch** [comment]
Hello usless
Thank you for the fast response. Would love that feature.
Thank you, Walter

**Comment by uslss** [comment]
closed as a duplicate of #4628
