### ISSUE TITLE
When closing a changed editor, there is no "do you want to save" warning

### ISSUE THREAD

**Issue by pokeydale** [dbeaver/dbeaver#8702]
#### System information: 
- Windows 10
- DBeaver version 7.0.4.202005031953
- Additional extensions

#### Connection specification:
- postgresql 9.6
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
SSH using bastion

#### Describe the problem you're observing:
When working on a sql script in the sql editor.  When I close the editor, i don't get any warning the changes have been made to the script and do I want to save the changes.  It used to work.

#### Steps to reproduce, if exist:
Open a script from disk or create a new one.  Make any change and close the editor.  It just closes no messages.

**Comment by rsella** [comment]
I have the same problem, after updating to 7.0.4 (7.0.3 was fine).
I'm using Oracle, but I'm pretty sure that is not a driver related issue.

The same behaviour happens when closing dbeaver with multiple unsaved tabs open: no dialog asking for save

**Comment by uslss** [comment]
issue is fixed in scope of #8617 .
anyway, thanks for the bug report
