### ISSUE TITLE
Database navigator view enhancements

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#8705]
- We need to show connection type in more fancy way. E.g. with filled rectangles/circles (fill color is connection color).
- We need to have ability to show some object statistics (e.g. table size) on the right side of navigator tree (configurable).
- We need to have ability to show extra info (e.g. target host) next to the connection name, e.g. in shadow color (configurable).

**Comment by kseniiaguzeeva** [comment]
Please add ability to show extra info (e.g. target host) next to the connection name, e.g. in shadow color (configurable).

**Comment by serge-rider** [comment]
Done

![image](https://user-images.githubusercontent.com/6398845/82884571-91c29200-9f4c-11ea-8f57-4451b6780068.png)

![image](https://user-images.githubusercontent.com/6398845/82884443-650e7a80-9f4c-11ea-934b-428ff7182211.png)
![image](https://user-images.githubusercontent.com/6398845/82884523-81aab280-9f4c-11ea-8da6-defa2fecfd02.png)

**Comment by kseniiaguzeeva** [comment]
Table statistics is not displayed for (the ticket is still checking):
SQLite
DB2
Athena
CockrouchDB
Derby
Exasol
Firebird
Snowflake
SQL Server

**Comment by serge-rider** [comment]
@kseniiaguzeeva It is ok.
For now we support it only for PostgreSQL (and forks), MySQL, MariaDB, Oracle, Clickhouse.

**Comment by kseniiaguzeeva** [comment]
Great.

**Comment by mboeringa** [comment]
@serge-rider : Just a very minor display issue, but the table size statistics use wrong file size unit notation, it is visible in your own screenshot as you posted here: https://github.com/dbeaver/dbeaver/issues/8705#issuecomment-633916230

- **Gb** should be **GB**
- **Mb** should be **MB**
- **Kb** should be **kB**

**Comment by miky-schreiber** [comment]
@serge-rider , Any chance to show also number of rows, not only table size?

**Comment by kseniiaguzeeva** [comment]
Could you please create a new feature request?
