### ISSUE TITLE
Oracle Java: No source code found for Java class

### ISSUE THREAD

**Issue by simasch** [dbeaver/dbeaver#8706]
#### System information: 
- Windows 10
- DBeaver 7.0.4

#### Connection specification:
- Oracle 12.2.0.1.0
- Oracle
- No tunnels or proxies

#### Describe the problem you're observing:
I can see all Java classes in the tree. But when I open some of them I only see: "No source code found for Java class"

#### Steps to reproduce, if exist:
Open tha Java node and click on a Java class

#### Include any warning/errors/backtraces from the logs
No warnings or errors in the logs

**Comment by simasch** [comment]
The problem seem to be the name of the Java code.

For example "ch/demo/Rtf2Image"

**Comment by simasch** [comment]
The problem is that you are using SOURCE column of *_JAVA_CLASSES but you must use NAME instead. That's the name you use when selecting the data from *_SOURCE

**Comment by serge-rider** [comment]
Thanks for the bug report and the details

**Comment by serge-rider** [comment]
Fixed by #8725

**Comment by uslss** [comment]
verified
