### ISSUE TITLE
Code Completion in Oracle 

### ISSUE THREAD

**Issue by AndreaOmodeo** [dbeaver/dbeaver#8710]
#### System information: 
- Windows 10
- DBeaver version 7.0.3

#### Connection specification:
- Oracle

#### Describe the problem you're observing:
Code completion in Oracle suggests SYSDATE() followed by a couple of parenthesis, which result in a syntax error, since SYSDATE in Oracle is a reserved word, not a function

#### Steps to reproduce, if exist:
Start code completion in an Oracle SQL window

**Comment by uslss** [comment]
thanks for the bug report

**Comment by pyrocks** [comment]
the same applies to postgres with `current_time` and `current_timestamp` (possibly more).

**Comment by uslss** [comment]
still reproducible for postgresql
![image](https://user-images.githubusercontent.com/31996417/84141722-4df77e80-aa5c-11ea-8ccb-292cf147907b.png)

**Comment by LonwoLonwo** [comment]
Yes, I didn’t specify.

I removed from functions these keywords in Oracle: CURRENT_DATE, CURRENT_TIMESTAMP, DBTIMEZONE, SESSIONTIMEZONE, SYSDATE, SYSTIMESTAMP

From PostgreSQL i removed only CURRENT_DATE. Another functions may have precision
![2020-06-09 14_23_12-PostgreSQL_ Documentation_ 9 4_ Date_Time Functions and Operators](https://user-images.githubusercontent.com/45152336/84142142-f0affd00-aa5c-11ea-8982-bf2ea400c9fe.png)
https://www.postgresql.org/docs/current/functions-datetime.html

**Comment by uslss** [comment]
verified
