### ISSUE TITLE
Is it possible to connect to a DB with its rotating password in AWS Secrets Manager?

### ISSUE THREAD

**Issue by Archehandoro** [dbeaver/dbeaver#8712]
#### System information: 
- Operating system (distribution) and version: macOS Catalina
- DBeaver version: 7.0.4

#### Connection specification:
- Database name and version: MySQL 5.6

#### Describe your question:

Hello,

We have recently enabled password rotation for our DBs and stored their values in AWS Secrets Manager. This causes connections to disconnect every X days after a password rotation. As well as a bit of hell to update passwords for those users that don't have programmatic/console access to Secrets Manager to check the password themselves.

I have been trying to run shell commands before connection retrieving said passwords using env variables, to not avail (probably for lack of knowledge on how to do it). I have also searched in github/stackexchange/reddit/internet with no luck finding anyone with a similar issue.

So, is it possible to do this? If it isn't, I think it's a feature I'd like to see in DBeaver, should I create a separate ticket for it?

Thanks!

**Comment by uslss** [comment]
thanks for suggestion

**Comment by GuillaumeDesforges** [comment]
Would love that feature

**Comment by Matvey16** [comment]
String with secret name is still used even after checkbox is unchecked

![dbeaver_m8FO7g6Ylv](https://user-images.githubusercontent.com/82543000/155539160-87e9c2e1-a353-4d54-9ce8-373da504546b.gif)

**Comment by Matvey16** [comment]
Option to use secret will automatically disable if connection is edited

**Comment by Matvey16** [comment]
Verified
