### ISSUE TITLE
no more unsaved file confirmation dialog on application quit or editor tab close

### ISSUE THREAD

**Issue by miellaby** [dbeaver/dbeaver#8715]
#### System information: 
- Windows
- DBeaver 7.0.4

#### Connection specification:
- Regular connexion Postgres,  Mysql

#### Describe the problem you're observing:
No more confirmation on application close or tab close because of unsaved files

#### Steps to reproduce, if exist:
open script file, modify, close dbeaver, no confirmation

**Comment by uslss** [comment]
issue is already fixed in scope of #8617 . It will be fixed in 7.0.5 version.
anyway, thanks for the bug report
