### ISSUE TITLE
See only single schema in DB Navigator

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#8719]
I have DB with dozen of various schemas.
Would i t be possible to define at DB connection params to see only selected schema in navigator ?
Now I have to scroll few pages to see the one Im mostly working on

**Comment by uslss** [comment]
Hi @maciey ,
you could use filters 
![image](https://user-images.githubusercontent.com/31996417/82218500-a7b8cd00-9924-11ea-9a0d-515c55e3a0e8.png)

**Comment by maciey** [comment]
Agh I missed that feature !
Brilliant will use that. 
So Im closing issue
