### ISSUE TITLE
[Postgresql] Rules are not shown in table DDL

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#8723]
When showing a table DDL, rules are missing.
They are correctly show in "Rules" tab though.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
Reopened
![2020-05-19_14h09_36](https://user-images.githubusercontent.com/31996417/82319994-2f611300-99db-11ea-9911-22b2da865612.gif)

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
fixed in 7.1.0
