### ISSUE TITLE
Installation/Upgrading documentation with ZIP file is incorrect

### ISSUE THREAD

**Issue by serpro69** [dbeaver/dbeaver#8726]
#### System information: 
- Operating system (distribution) and version - Ubuntu 20.04
- DBeaver version - 7.0.3 -> 7.0.5
- Additional extensions - 

#### Describe the problem you're observing:
Documentation for installing using ZIP Archive states:

> Extract the contents of the archive.
> NOTE: Do not unzip the archive over a previous DBeaver version. If you already have any version of DBeaver extracted in the same location - remove it before unzipping the new version.
> NOTE: **All configurations, scripts and other necessary data are stored in a separate location** (usually in the user`s home directory) so the program deinstallation does not affect them.

However after upgrading from 7.0.3 to 7.0.5 (removing previously unzipped directory) I don't see the previously installed plugins anymore.

DBeaver also prompts for drivers downloads which were already present in the home config directory (Not sure if it did actually re-download them again.)

It would be nice if the docs mentioned this since now I have to reinstall and reconfigure all the plugins.
Would be even better if actually "all configuration" (including extra plugins, settings, etc) was stored in user's home location.

#### Steps to reproduce, if exist:
1. Install older version with ZIP archive
2. Install some extra eclipse plugins
3. Upgrade to a newer version
4. Launch dbeaver and observe that there are no plugins anymore.

**Comment by serge-rider** [comment]
Unfortunately it is not possible to keep old plugins (they may be incompatible with the new app version).
However DBeaver asks about plugins re-installation after version upgrade.

**Comment by p91paul** [comment]
@serge-rider if you are not installing system-wide, in my experience it does not ask anything, you have to manually remember every time

**Comment by serpro69** [comment]
That was my experience as well.

**Comment by serpro69** [comment]
So I started using dbeaver with flatpack and that actually prompts for the re-installation of plugins after update.
From my POV this can be closed. Though the documentation could probably be updated to mention that zip-based upgrades will erase all information related to installed plugins.
