### ISSUE TITLE
[VERTICA] "Smart autocomplete" doesnt work on Vertica when using ${variables}

### ISSUE THREAD

**Issue by ashdam** [dbeaver/dbeaver#8728]
#### System information: 
- Windows 10 64bit
- 7.0.4

#### Connection specification:
- Vertica 9.1
- JDBC 9.1

#### Describe the problem you're observing:

"Smart autocomplete" doesnt work on vertica when using ${variables} with values. I've tested this feature on Oracle and it perfectly works.

It might be related: same happens when you want to inspect a table on ${schema}.table using CTRL+click on "table"

#### Steps to reproduce, if exist:

1) Execute:
select *
from ${schema}.table
2) Try to use CTRL+SPACE to autocomple when writing your "table"

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
Fixed for Vertica and for Oracle.

![2021-09-30 11_11_58-DBeaver Ultimate 21 2 2 - _Partner11DB_Script-66](https://user-images.githubusercontent.com/45152336/135725297-e3cd3551-3643-4e79-8091-ad2849d61031.png)

![2021-09-30 11_12_44-](https://user-images.githubusercontent.com/45152336/135725299-5cc09b25-6438-4cff-8e0d-66d79b479eee.png)
e.

**Comment by Matvey16** [comment]
Verified
