### ISSUE TITLE
Error executing row count in custom jdbc driver

### ISSUE THREAD

**Issue by kustoffigor** [dbeaver/dbeaver#8730]
Hi! I'm using DBeaver with a custom written JDBC driver to connect to my database. 

When I hit the "Calculate total row count" I do get "Error executing row count". This is probably due to the fact that I didn't implement something in my JDBC driver. 

However, I couldn't find anything in logs located on my Windows machine at %AppData%\Roaming\DBeaverData\workspace6\.metadata

So how could I get the error message? 

Thanks.

**Comment by uslss** [comment]
Hi @kustoffigor ,
sorry for the delayed response.
Could you check Error log (Main Menu: Window - Show View - Error log) and Query manager (to check query that is executed to calculate row count)?
