### ISSUE TITLE
7.05 ODBC drivers cannot install

### ISSUE THREAD

**Issue by sebringmi** [dbeaver/dbeaver#8732]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by sebringmi** [comment]
Clean install on dBeaver 7.0.5 driver issue for ODBC connections. States missing jar package and cannot connect to link for file download (get forbidden message like page not valid)  https://dbeaver.io/files/odbc

**Comment by nicorac** [comment]
Same here, after upgrading from 7.0.4 to 7.0.5.

![immagine](https://user-images.githubusercontent.com/2361673/82303816-be5e3300-99bb-11ea-84e8-a0edd680416d.png)

![immagine](https://user-images.githubusercontent.com/2361673/82303876-d46bf380-99bb-11ea-82cc-004b0bb21c91.png)

Reverting to 7.0.4 fixes the issue.

**Comment by serge-rider** [comment]
It is odbc driver configuration bug in 7.0.5.
Thanks for the bug report

**Comment by nicorac** [comment]
Just applied the patch on my installed 7.0.5 and it works, thanks 👍

**Comment by manoelsouzas** [comment]
it's still not working for me, if anyone can help me.

**Comment by sebringmi** [comment]
I reverted to version 7.0.3 and odbc works fine.

**Comment by nicorac** [comment]
> it's still not working for me, if anyone can help me.

Follow these steps:
- open DBeaver **plugins** folder (on Windows it should be **C:\Program Files\DBeaver\plugins**)
- copy file **org.jkiss.dbeaver.ext.generic_2.3........jar** to Desktop
- open it with 7-Zip (it's a ZIP file)
- extract **plugin.xml** file
- edit **plugin.xml** file like this:
line 300:
```<file type="jar" path="repo:/drivers/odbc/jdbc-odbc-bridge-jre7.jar" bundle="!drivers.odbc"/>```
line 303:
```<file type="jar" path="drivers/odbc/jdbc-odbc-bridge-jre7.jar" bundle="drivers.odbc"/>```
- put the edited plugins.xml file back to .jar (ZIP) file
- copy .jar file back to plugins folder
- open DBeaver

**Comment by uslss** [comment]
verified.
will be implemented in 7.1
