### ISSUE TITLE
Error connecting ODBC

### ISSUE THREAD

**Issue by manoelsouzas** [dbeaver/dbeaver#8733]
System information: 
- Windows 10 Pro
- DBeaver 5.0.5

When trying to connect with ODBC database the dbeaver results a error:
"Can't create driver instance
   Error creating driver 'ODBC' instance
Most likely require a jar files are missing.
You should configure a jars in diver settings.
Reason: can't load de driver class 'sun.jdbc.odbc.JdbcOdbcDriver'
   Error creating driver 'ODBC' instance.Most likely required jar file are missing. You should configure 
     jars in the drive settings.Reason: can't load driver class 'sun.jdbc.odbc.JdbcOdbcDriver' 
     sun.jsbc.odbc.JdbcOdbcDriver

Was working correctly in previous version 5.0.4

**Comment by uslss** [comment]
hi @manoelsouzas ,
do you mean versions 7.0.4 and 7.0.5?

**Comment by uslss** [comment]
probably duplicates #8732

**Comment by uslss** [comment]
thanks for the bug report.
issue will be fixed in scope of #8732
