### ISSUE TITLE
macOS version on launch shows "To use Java command-line tools you need to install a JDK"

### ISSUE THREAD

**Issue by fseesink** [dbeaver/dbeaver#8734]
#### System information: 
- Operating system (distribution) and version:  **macOS 10.15.4 with all updates**
- DBeaver version:  **7.0.5**
- Additional extensions

#### Connection specification:
- Database name and version:  **n/a**
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Whenever I try to run **DBeaver**, I get the following dialog box:
![Screen Shot 2020-05-18 at 2 02 14 PM](https://user-images.githubusercontent.com/48991/82245538-1be97580-9911-11ea-864b-99e7dcd64431.png)
To be clear, app never runs.

#### Steps to reproduce, if exist:

Download the .DMG and mount.
Window show usual application and alias to /Applications.
Drag/drop application icon to /Applications alias.
Double-click DBeaver.app in /Applications folder.

I figured you included the necessary JRE in the macOS bundle as some other apps do, since the main GitHub page states

____
...
### Running

DBeaver requires Java (JRE) 1.8+ to run.

* **Windows** and **MacOS X** installers include JRE so just use them and don't think about internals.
* On **Linux** you may need to install Java manually (usually by `running sudo apt-get install openjdk-11-jdk` or something similar).
* If you don't use installer (on Windows or Mac OS X) you may need to download Java (JDK) from [Adopt OpenJDK web site](https://adoptopenjdk.net/).
...
____

Odder still is that I DO have Java installed, specifically Oracle JRE version 8 update 251.  So not sure what's going on here.  But dialog box does indicate the app is trying to do something which requires the JDK vs. the JRE.

#### Include any warning/errors/backtraces from the logs

Not possible as can't get to Window menu since app won't start, and there's no `~/Library/DBeaverData/` let alone subdirectories therein.

**Comment by p91paul** [comment]
from the download page "If you are on Mac OS X and you do NOT use PKG installer then you will need to setup Java."
Just choose the "installer" option instead of dmg.

**Comment by fseesink** [comment]
"from the download page"... which page would that be exactly?
And again, I DO have Java setup.  It's just Oracle's Java 8 update 251 **JRE**.

Looking around, there's what is listed here that I referenced earlier:
https://github.com/dbeaver/dbeaver

Then there's the official site's download page:
https://dbeaver.io/download/

But I think the confusion may well be that the former page indicates that

>DBeaver requires Java (**JRE**) 1.8+ to run.

and also says

>Windows and MacOS X installers include **JRE** so just use them and don't think about internals.

The implication is that you only need the JRE.

But I suspect this is not the case.  The fact that on the latter page the following appears under the "**Install:**" section tips the hand:

>Java notes: if you use Windows or MacOS installer then you don’t need to install Java. Otherwise you will need to setup Java separately. Java 1.8+ must be the default Java version. **To validate this run “java -version” in terminal window.**

THAT, if true, requires the JDK.

[I didn't put much stock in references to Adopt OpenJDK where mentioned, as anyone who wishes to run the JRE on macOS but doesn't have/want to use the Oracle JRE has no choice with Adopt OpenJDK as they don't offer an installer with just the JRE.  All they have is the full JDK which then includes the JRE, which is all most folks likely need anyway.  But it's looking like here that DBeaver _requires_ the JDK.  And if true, this should be documented as such.

I had just figured since a .DMG file was offered with the usual drag/drop, combined with the bit about "Windows and MacOS X installers include JRE so just use them and don't think about internals", that maybe the DBeaver devs had done similar to what HelpSystems/Dartware did with their InterMapper software, where they bundled in the necessary Java runtime within the macOS application bundle itself, making it fully self-contained.  Guessing that's simply not the case here.

As a side note, you may also wish to clean up the docs to not only reflect that DBeaver requires the JDK, but also stop mixing the version numbering between saying it requires 1.8+ and then in other places referencing Java 8 (see first link above as you'll see both on the same page between the Running and Building sections).  Just call it Java 8.  It will create less confusion.

**Comment by p91paul** [comment]
your second link is the download page, and the first link of the mac os section is the one dubbed as "installer" which should be a PKG file.
That said, I don't use MacOS nor I'm a dbeaver developer, just a user trying to help based on what I've seen in many similar issues in the past.

Also I don't see how your quote shows dbeaver needs a jdk to run instead of just a jre. The *java* program is part of the jre, not the jdk.

**Comment by fseesink** [comment]
Ah, @p91paul , that explains it.  Since you're not a macOS user, allow me to clarify.  On macOS, the Oracle JRE does NOT provide the `java` utility.  Seems odd I know, but that's the reality.  Hence my opening an issue for the developers, as the documentation indicates all that is needed is the JRE (and specifically in reference to macOS).  And that, as I've noted, I have installed.

Also, again since you're not a macOS user, you may not know this either.  The AdoptOpenJDK project does a fantastic job taking Open JDK, the open-source implementation of the Java platform, and bundling it up into an easy to consume macOS installer.  That installer, however, is for the full JDK.  They don't even offer a JRE-only installer.  And whereas the Oracle JRE provides a System Preference (think Windows Control Panel or the various control panels in Gnome/KDE/etc.) which then gets you to the Java control panel (what you see if, for example, you go into the Windows Control Panel and double-click the Java icon), AdoptOpenJDK installs "under the hood" and you need to use a shell to do things with it.

My suspicion is the developers have been building the project using AdoptOpenJDK, so they may not realize that the project does, in fact, require the JDK and not just the JRE on macOS.  It's no big deal, but the docs as written may confuse new users.  It's one of the unfortunate side effects of using a language that doesn't compile straight to the binary of the OS, that you need to be clear what the requirements are just in order for your application to run.  (This would apply to any dynamic scripting language as well such as Perl, Python, Ruby, etc., so not restricted to Java, mind you).

**Comment by p91paul** [comment]
> Oracle JRE does NOT provide the `java` utility. Seems odd I know, but that's the reality

WHAT?? so what does it offer, an empty zip file? the JRE is basically the java program and its dependencies, I wouldn't know what to do with a JRE without java.

**Comment by serge-rider** [comment]
Well, we need JDK on MacOS to run. JRE is not enough. 
I'll fix instructions on download page (by replacing JRE on JDK everywhere).

In fact JRE is a historical term, there is no such thing in the OpenJDK.

**Comment by philwatt** [comment]
Still not working for me - I have installed OpenJDK and dbeaver from homebrew. Java version:
```
java --version
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+14)
OpenJDK 64-Bit Server VM (build 14.0.1+14, mixed mode, sharing)
```
<img width="532" alt="Screenshot 2020-08-20 at 10 00 21 pm" src="https://user-images.githubusercontent.com/38426850/90767470-9f5f9c00-e330-11ea-8ae3-12ea4e5b0b1b.png">

Is there a workaround for this? What should I be doing differently?

Thanks in advance
