### ISSUE TITLE
Never ending mapping - large MongoDB collections

### ISSUE THREAD

**Issue by christopher-bonitz** [dbeaver/dbeaver#8738]
#### System information: 
- OS: Windows 10 64bit Pro.
- DBeaver version: 7.0.0 Enterprise

#### Connection specification:
- Database: MongoDB 3.2.11
- Driver: MongoDB
- Standard login using SCRAM-SHA-1

#### Describe the problem you're observing:
Opening any "big" collection causes the background task to begin a map job of sorts, see screenshot for details.
The job never completes (Waited 10 minutes).
![image](https://user-images.githubusercontent.com/20163098/82302912-8a364280-99ba-11ea-9ef7-f3a699d222c9.png)

It is unknown to me if cancelling a jobs works, the text states that it is, but again never completes. 
![image](https://user-images.githubusercontent.com/20163098/82304248-5e1bc100-99bc-11ea-95d1-2ed49fbe84aa.png)

#### Steps to reproduce, if exist:
Connect to db using described settings in top of this ticket.
Double click a collection on over 1 Gig

#### Include any warning/errors/backtraces from the logs
[20200519.log](https://github.com/dbeaver/dbeaver/files/4649171/20200519.log)

**Comment by christopher-bonitz** [comment]
Adding some severity to this issue.
Our Server had a hard time processing whatever it was processing during this mapping.
I think its fair to say we "need" to be able to turn off this logic/process step.

![image](https://user-images.githubusercontent.com/20163098/82315672-eeadcd80-99cb-11ea-8998-17d5b236c159.png)

**Comment by serge-rider** [comment]
Agreed. We will disable attributes read in MongoDB. It is too "aggressive" in huge collections.

**Comment by christopher-bonitz** [comment]
I'm willing to help test the fix if you like, I use MongoDB on a daily basis towards several different machines of different sizes and OS type.
I will need to renew my Trial through, we're going to buy two copies of enterprise once we can rely on Dbeaver

**Comment by kseniiaguzeeva** [comment]
@christopher-bonitz EE release is available https://dbeaver.com/download/. Could you please check the fix?
Thank you in advance!

**Comment by christopher-bonitz** [comment]
Sorry, no can do.
![image](https://user-images.githubusercontent.com/20163098/84381658-a740e880-abe9-11ea-94db-1dd556f9b792.png)

If you can get me a new trial period I am happy to help

**Comment by christopher-bonitz** [comment]
In case you are able, you may renew me for a few weeks, here are my License ID: 
DB-3V1MPZB1-Z251

**Comment by serge-rider** [comment]
@christopher-bonitz please try again. If it won't work please write me on serge@jkiss.org

**Comment by christopher-bonitz** [comment]
After getting my application up and running again, I can confirm the fixes seem to be working as intended.
I've tried this on a 71 GB collection, CPU usage on server confirms there is no longer a problem.

Thanks a lot!
