### ISSUE TITLE
missing "set null" on right click context

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#8739]
#### System information: 
- Operating system (distribution) and version: mac latest
- DBeaver version 7.0.5
- Additional extensions

#### Connection specification:
- Database name and version pg: 11.6

#### Describe the problem you're observing:
Missing "set null" on right click context. The option which existed in 7.0.4 was replaced with "Set to default value (empty string/zero)" depending on column type which I personally find a lot less useful - but better keep both options.

#### Steps to reproduce, if exist:
right click a cell - no "set to null" option like before
the only option I found, which is very inconvenient is Edit->Edit cell value->Set Null.

**Comment by pyrocks** [comment]
my bad, the column was not nullable :|

**Comment by nievadev** [comment]
@pyrocks it was thanks to your comment that I too realized that my column wasn't nullable too! Thank you haha

**Comment by njminchin** [comment]
Whether it's nullable or not, the option should be there. My table has a BEFORE INSERT trigger that sets my field value if it's NULL, so not being able to set this to NULL when entering data manually means I can't fire this trigger :/
