### ISSUE TITLE
postgres 'xx:xx:xx' interval in generated script not wrapped in quotes

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#8740]
#### System information: 
- Operating system (distribution) and version macos latest
- DBeaver version 7.0.5

#### Connection specification:
- Database name and version pg 11.6

#### Describe the problem you're observing:
generated SQL for a row with "00:05:00" interval syntax is written without quotes - so it cannot run.
generated sql: insert into ... (...) values (...,05:00:00,...) --> not valid
should have been: insert into ... (...) values (...,'05:00:00',...)

#### Steps to reproduce, if exist:
in data grid of a table with an interval column, the interval column is displayed as 05:00:00
duplicate the row, generate script. sql generated without quotes.
If handling this, I think an interval column should also support supported interval strings like "5 minutes" - when generating SQL it should wrap such expressions with quotes too.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
fixed in 7.1.0
