### ISSUE TITLE
[EXASOL] Schema function cannot be deleted via UI

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8742]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.0.5

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
Schema function cannot be deleted via UI
#### Steps to reproduce, if exist:
1. Open schema in Object Editor
2. Open functions tab
3. Press **Create new function** btn
4. Press **Save** btn in the opened window
5. Press **Persist** btn in the opened window
6. Press **F5**
7. Click on the created function
8. Press **Delete database object** btn
9. Press **Yes** btn.

Actual result:
1. the function is not deleted
2. Error message appears:
SQL Error [42000]: script NEW_SCRIPT does not exist [line 1, column 13] (Session: 1667121796122279232)
  script NEW_SCRIPT does not exist [line 1, column 13] (Session: 1667121796122279232)

Workaround:
Execute in SQL Editor: DROP FUNCTION NEW_SCRIPT;

**Comment by Sargul** [comment]
With #9131 this should be fixed:
![image](https://user-images.githubusercontent.com/5595511/86205152-765d2f00-bb69-11ea-8045-ccdf650b8a85.png)
