### ISSUE TITLE
Auto Close doesn't work for Single / Double quote

### ISSUE THREAD

**Issue by Moridin11** [dbeaver/dbeaver#8744]
When AUTO-CLOSE of Single, Double and brackets is turned on, if I highlight a word and then press a one of those, it will surround it as I expect.  

However if what I am attempting to surround has an UNDERSCORE, then it only works for the brackets, not the single or double quote.

I'm currently on 7.0.3, windows 10 postgres db

**Comment by uslss** [comment]
hi @Moridin11 ,
unfortunately cannot reproduce it. could you try it against 7.0.5?

**Comment by Moridin11** [comment]
@uslss  - It appears to be resolved in 7.0.5.  Thanks!!
