### ISSUE TITLE
Fetch Table Data Very Slow

### ISSUE THREAD

**Issue by Phil807** [dbeaver/dbeaver#8745]
#### System information: 
- Operating system (distribution) and version
MacOS
- DBeaver version
Enterprise
- Additional extensions

#### Connection specification:
- Database name and version
Redshift database
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No
#### Describe the problem you're observing:
Fetch data is taking a very long time, see image below.
Is this a known issue?

<img width="299" alt="Screenshot 2020-05-19 at 16 48 35" src="https://user-images.githubusercontent.com/15194945/82348426-c8e6ef80-99f0-11ea-9916-89437e583d02.png">

**Comment by Phil807** [comment]
To note, it does not take this long to fetch dating using a different GUI.

**Comment by serge-rider** [comment]
I can't reproduce this so far.
You can check what exactly takes so long time in Query Manager view (you may need to enable metadata queries logging in the context menu).

Do you read data from some very big table?
If yes then did you try to enable "Use SQL to limit fetch size" parameter?

Note: as Redshift is AWS service it is sensitive to the location of client machine, target region, VPN and network settings.

![image](https://user-images.githubusercontent.com/6398845/82983831-88433380-9ff9-11ea-99df-f8f1b3413904.png)

**Comment by vlad88sv** [comment]
I have the same with Aurora MySQL
![image](https://user-images.githubusercontent.com/91489/108385388-3bc80580-71d1-11eb-8caa-6a30dfe24037.png)

Tried with and without tunnel, the only solution is to close and re-open DBeaver EE 7.3

It can hang in there indefinitely doing some light-medium CPU usage
![image](https://user-images.githubusercontent.com/91489/108385544-6619c300-71d1-11eb-965f-569852b6fe3c.png)

When it hangs I change to DataGrip or Workbench and it always works instantaneously, so I discard my network connection.

---

When it completed it shows this in the status bar:
![image](https://user-images.githubusercontent.com/91489/108387890-abd78b00-71d3-11eb-846e-baef59fe2231.png)

**Comment by vlad88sv** [comment]
Looks like there's something wrong with the driver and Aurora RDS in general:

![DBeaver EE AWS Aurora MySQL](https://user-images.githubusercontent.com/91489/108574607-80d95e00-72dd-11eb-88d6-3b7d3fff33ef.gif)

**Comment by pitjRizal** [comment]
I have found a similar problem, when started it only takes 15 seconds. But after idle and I want to refresh data, this happens.

![Screenshot from 2024-01-23 02-08-33](https://github.com/dbeaver/dbeaver/assets/157099211/be1794ab-d2ed-48f9-8506-8feaad3f52c4)

**Comment by ajitirto** [comment]
i am too, so long time to wait fetch data

**Comment by jliu0812** [comment]
> I can't reproduce this so far. You can check what exactly takes so long time in Query Manager view (you may need to enable metadata queries logging in the context menu).
> 
> Do you read data from some very big table? If yes then did you try to enable "Use SQL to limit fetch size" parameter?
> 
> Note: as Redshift is AWS service it is sensitive to the location of client machine, target region, VPN and network settings.
> 
> ![image](https://user-images.githubusercontent.com/6398845/82983831-88433380-9ff9-11ea-99df-f8f1b3413904.png)

I was facing this issue on my Apple Silicon-based Mac, but after this applying this suggestion then it worked for me.

**Comment by IgalSc** [comment]
I have the same issue wiht DBeaver Community edition 25.0.0
```
Updated Rows	1
Execute time	9.390s
Query	insert into content_providers 
	values
	('Atmosphere TV','Chive TV')
```
