### ISSUE TITLE
Fails to start with error "Java was started but returned exit code=13" on Windows (Zip install)

### ISSUE THREAD

**Issue by Chealer** [dbeaver/dbeaver#8746]
#### System information: 
- Windows 10
- DBeaver 7.0.4
- No additional extensions

I have Java 8 and JDK 13 installed.

#### Describe the problem you're observing:
DBeaver fails to initially start on this machine, showing instead the following dialog:
![image](https://user-images.githubusercontent.com/486141/82365953-69341880-99df-11ea-887f-a962fe29a5d5.png)

#### Steps to reproduce, if exist:
I do not know what steps are needed. What I did:
1. Download the zip file from https://github.com/dbeaver/dbeaver/releases/download/7.0.4/dbeaver-ce-7.0.4-win32.win32.x86_64.zip
1. Extract it (to C:\Program Files (x86)\dbeaver\)
1. Run dbeaver.exe

#### Include any warning/errors/backtraces from the logs
As this is an initial install, the log directory was not yet created.

---
Issue #5678 suggests this problem is not new.

**Comment by vl2376** [comment]
Same issue here only its exit code = 1 for me

**Comment by rafliher** [comment]
so no solution yet?

**Comment by meriturva** [comment]
same here with version 7.1.1. Version 7.0.4 is ok!

**Comment by vl2376** [comment]
So if you download the installation folder as a zip you'll see a dbeaver.ini file in which changing the path to Java and JDK installations may help you. That was the fix for me.

**Comment by rafliher** [comment]
all i do is delete the java path which leads to oracle folder and it works. for now.

**Comment by meriturva** [comment]
Fixed installing Java 64bit

**Comment by aniston** [comment]
> Fixed installing Java 64bit

Hi, I would like to confirm that having only Java JRE x86 or i586 was not sufficient on my W7x64 OS so I had to install a JRE x64 as well and that solved the startup problem with the .zip package.

**Comment by Chealer** [comment]
Why is this ticket closed and labelled as a question?

**Comment by Chealer** [comment]
@serge-rider , you marked this report as a question and removed its _bug_ label on 2020-07-24. Can you explain?

**Comment by serge-rider** [comment]
@Chealer Because @meriturva's reply answers the question about DBeaver start problems. DBeaver doesn't support 32-bit Java anymore.
To solve this problem just install 64-bit Java.

**Comment by Chealer** [comment]
What question are you talking about @serge-rider ? Do you know what an ITS is? This ticket is a report of a bug in DBeaver, it is not a support request.

**Comment by Chealer** [comment]
Please reopen this ticket

**Comment by Chealer** [comment]
@serge-rider thanks for reopening this ticket

**Comment by ceinmart** [comment]
Hi, I'm getting this issue when I'm installing the Eclipse Marketplace on version 25.0.5.

After the plugin install and the first restart, give the error and didn't open. 
The open without error and the plugin didn't work, but is listed as installed.
When uninstall it, the same error occur at the first restart.

(the window didn't fit on screen, needed to do a trick to capture it complete, change my 2nd monitor layout)

![Image](https://github.com/user-attachments/assets/b4fdea2b-2180-445a-9340-74f88544706b)

![Image](https://github.com/user-attachments/assets/06b39933-71b1-47c9-aab7-b9d4657c8d48)
