### ISSUE TITLE
PostreSQL WHERE Statement using UNICODE character

### ISSUE THREAD

**Issue by GITMichaelK** [dbeaver/dbeaver#8749]
#### System information: 
- kUBUNTU 18.04
- DBeaver version: 7.03

#### Connection specification:
- PostgreSQL 10.190

#### Describe your question:
An old table contains text-fields where unicode characters have been used:
’ UNICODE 8217
‚ UNICODE 8218
I want to replace these by the [normal Apostrophe](https://en.wikipedia.org/wiki/Apostrophe) (ASCII 27). Therefore the following SQL-statement:
select * from "SchemaName"."TableName" where "FieldName" like '%’%'; 
Although I know for sure, that there lines, having UNICODE 8217, this statement delivers nothing. Any mistake from my side or a bug?

**In Addition to that**, now I found that also the Search&Replace (CTRL-F) only works partially, e.g. it finds and replaces some fields, but not all. I could not figure any logical condition (in a word, at the beginning or end) where it finds or not.

Regards, Michael

**Comment by GITMichaelK** [comment]
May I remind this question? Is there anything, that I can do to find such characters?
Thank You. 
Michael

**Comment by kseniiaguzeeva** [comment]
@GITMichaelK as I see it is PostgreSQL question, not DBeaver issue. Please open new ticket if you have any other questions.
