### ISSUE TITLE
DBeaver 7.0.2 Driver properties

### ISSUE THREAD

**Issue by MTSerge** [dbeaver/dbeaver#8754]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.0.2

#### Connection specification:
- Database name and version: Cloudera Impala

#### Describe your question:
hi,

I am not able to update Driver properties (configure authentication and add new properties) when using DBeaver version 7.0.2. Is this a bug?

Thanks in advance for your guidance.

**Comment by MTSerge** [comment]
Operating system (distribution) and version: Windows 7

**Comment by uslss** [comment]
hi @MTSerge , could you try it against 7.0.5 version?

**Comment by MTSerge** [comment]
hi @uslss , not yet but will update to 7.0.5 if needed

**Comment by MTSerge** [comment]
hi @uslss , issue has been resolved; it was not a bug with version 7.0.2
