### ISSUE TITLE
Windows Store App / UWP: "Failed to load JNI shared library" on startup

### ISSUE THREAD

**Issue by vdurante** [dbeaver/dbeaver#8755]
#### System information: 
- Operating system (distribution) and version ~ fresh install of Windows 10 x64 1909
- DBeaver version ~ 7.0.0.0 x64
- Additional extensions ~ none

#### Describe the problem you're observing:
I attempted to install DBeaver CE on a fresh install of Windows 10 through the App Store, but I am unable to run it. The error I get:

`Failed to load the JNI shared library "C:\Program Files\WindowsApps\DBeaverCorp.DBeaverCE_7.0.0.0_x64__1b7tdvn0p0f9y\jre\bin\server\jvm.dll".`

![image](https://user-images.githubusercontent.com/5401232/82467564-2d10be80-9a98-11ea-88f8-c47929e97d75.png)

I have checked that folder and the file exists. I copied the whole `jre` folder to a portable `.zip` extraction of DBeaver and it worked properly.

I felt this was a permission issue caused by `C:\Program Files\WindowsApps` folder, since it is owned by `TrustedInstaller`. I took ownership of the folder, but failed to execute it.

#### Steps to reproduce, if exist:

1. Install Windows 10
2. Install DBeaver from Windows Store
3. Attempt to run it

#### Include any warning/errors/backtraces from the logs

- `%APPDATA%\DBeaverData\workspace6\.metadata` - this folder doesn't exist
- The only Event Log message I was able to find: `Failed with 0x490 modifying AppModel Runtime status for package DBeaverCorp.DBeaverCE_7.0.0.0_x64__1b7tdvn0p0f9y for user DESKTOP-J7V9MSL\vitor (current status = 0x0, desired status = 0x20).`

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce the issue. Do you have necessary user permissions?

**Comment by vdurante** [comment]
@kseniiaguzeeva I decided to reinstall windows once again and it worked. Makes no sense...

**Comment by vaempunk** [comment]
Had same issue, solved by installing MSVC 2015-2022 Redistributable

**Comment by ihola777** [comment]
exactly same problem here. can't fix it with installing msvc, any advise?
