### ISSUE TITLE
Interval style of CSS in exported html format file

### ISSUE THREAD

**Issue by machinewu** [dbeaver/dbeaver#8757]
#### System information: 
- Operating system (distribution) and version
Win10 x64
- DBeaver version
v7.0

#### Describe the problem you're observing:
After I export the result data as HTML format, I found the CSS in the exported HTML have some problem.
![CSS code in exported HTML](https://user-images.githubusercontent.com/4166753/82525472-09b34580-9b64-11ea-9387-78e69b3456ae.png)

#### Steps to reproduce, if exist:
1. Create a temporary data table according to the following code:
```
create temporary table test_table (
c1 varchar(10),
c2 varchar(10),
c3 varchar(10),
c4 varchar(10),
c5 varchar(10)
);

insert into test_table values
(1,1,111,1111,11111),
(2,22,222,2222,22222),
(3,33,333,3333,33333),
(4,44,444,4444,44444),
(5,55,555,5555,55555);

select * from test_table;
```

2. Export the result set as HTML format.
![result set](https://user-images.githubusercontent.com/4166753/82525551-3b2c1100-9b64-11ea-9c90-8ecc92193457.png)

3. In fact, we really needed result is:
![result set2](https://user-images.githubusercontent.com/4166753/82525678-89d9ab00-9b64-11ea-86ba-590b1c97bac9.png)
This can be achieved by deleting the css code:
![delete css code](https://user-images.githubusercontent.com/4166753/82525815-f81e6d80-9b64-11ea-9777-e21a49761208.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by LonwoLonwo** [comment]
@machinewu it looks better, thanks for the corrections
![2020-05-25 23_58_56-Mozilla Firefox](https://user-images.githubusercontent.com/45152336/82878756-9daa5600-9f44-11ea-9f70-f27d46a79d83.png)

**Comment by uslss** [comment]
verified
