### ISSUE TITLE
DDL table structure query syntax is wrong...

### ISSUE THREAD

**Issue by ramrasi** [dbeaver/dbeaver#8758]
#### System information: 
- Windows 10
- DBeaver version 7.0.5
- no Additional extensions

#### Connection specification:
- Postgresql 9.4
- Postgresql-42.2.5.jar

I am using Parent child concept in my project(Inheritance)... i checked the child table DDL statement it is showing parent table name two time. 

for reference please check the image .

![image](https://user-images.githubusercontent.com/6615196/82528853-547a9080-9b57-11ea-980b-9b5efc1643d6.png)

**Comment by uslss** [comment]
hi @ramrasi ,
unfortunately, cannot reproduce it. Is it happens for all of the tables?
![image](https://user-images.githubusercontent.com/31996417/82534995-d6b28700-9b4e-11ea-9bad-cdc63b3a6ab8.png)

**Comment by ramrasi** [comment]
@uslss 

Thanks for your reply...

i saw in all master-slave tables. Please refer following images.

![image](https://user-images.githubusercontent.com/6615196/82565165-96c3c200-9b97-11ea-90e0-6e53ed7d81b0.png)


![image](https://user-images.githubusercontent.com/6615196/82565244-b4912700-9b97-11ea-92b9-c0c2f9959635.png)


![image](https://user-images.githubusercontent.com/6615196/82565353-e5715c00-9b97-11ea-9db2-55ded10d3baa.png)


![image](https://user-images.githubusercontent.com/6615196/82565396-fde17680-9b97-11ea-957c-4733478e2e09.png)
