### ISSUE TITLE
Copy selection as IN clause

### ISSUE THREAD

**Issue by bnjow** [dbeaver/dbeaver#8760]
One feature that I find very useful in DBViz is the ability to highlight several values in a column and quickly create an IN string to be used in a filter/script.

It would be great to have an entry in the Advanced Copy or Generate SQL context menus that will produce a string that I can then paste elsewhere.

Right now the only way I've found to achieve this is to select the values, paste them into the script editor, highlight them again, use the morph to delimited list, then add the brackets and operator. Obviously this is not very efficient.

For example, given this column:

LOCATION_ID
121
122
**123
124
125**
126
127

By highlighting the entries in bold and using the feature we would end up with the following in the clipboard:

LOCATION_ID IN (123,124,125)

If multiple columns are involved in the selection then ideally the feature would produce two individual IN strings and place an AND in between:

COLUMN_1 IN (A,B,C) AND COLUMN_2 IN (X,Y,Z)

**Comment by uslss** [comment]
hi @bnjow ,
if I understand you correctly, you could generate statement of this kind using filters (please, see gif attached). Is it suitable for you?
![2020-05-21_12h38_32](https://user-images.githubusercontent.com/31996417/82546055-34030400-9b60-11ea-9228-ac395aa08735.gif)

**Comment by bnjow** [comment]
Thanks for the reply. Thats almost ideal and works fine for small tables, but I've found that when I click the filter button on a table with a large number of rows (e.g. 17 million) it can take considerable time for DBeaver to load the unique values and populate the filter window. Then applying the filter can also take considerable time to run before I can select the string to use elsewhere.

**Comment by lemon-juice** [comment]
I'd find it handy, too. The closest feature I could find is Advanced Copy > Advanced Copy and choosing comma as row delimiter in order to get a comma-delimited string. However, this would not work for multiple columns. Being able to create filter SQL for the selected cell values, even in multiple columns would be fantastic. Ideally, this would be available both as one of the Advanced Copy features (if I want to have it in the clipboard) and as a Filter > Cell Value option for activating immediate search.

**Comment by uslss** [comment]
thanks for clarification and suggestion

**Comment by ShadelessFox** [comment]
Fixed generator which allows you to create `SELECT .. FROM .. IN` statement from selected rows:

![image](https://user-images.githubusercontent.com/35821147/127184493-2969243a-377d-4a18-9c04-06b763c9696f.png)

It uses PKs in the `IN` clause. You can create a separate FR to support using arbitrary columns in the `IN` clause.

**Comment by Matvey16** [comment]
Verified with a possible enhancement #13344

**Comment by emergeit** [comment]
I think you should give a try on it:

1. CTRL+SHIFT+C on COLUMN;

Now:

column_strings -> aaa, bbb, ccc
![string](https://github.com/dbeaver/dbeaver/assets/87096896/8d8227bf-3148-4d70-9cef-b4ae4dcbe071)

column_integers(numerics)-> 1,2,3,4
![numbers](https://github.com/dbeaver/dbeaver/assets/87096896/69f12f44-b3e9-4990-bbe2-ebcd2e0a48c5)


The results will be displayed as desired selection.
All you have to do is give it a name like : where id in (CTRL+V) after decide which method above you will chose.

Credits to @ezequiel_carvalho
