### ISSUE TITLE
[Exasol] Tools>import table(s) doesn't work

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8761]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.0.5

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
[Exasol] Tools>import table(s) doesn't work.

#### Steps to reproduce, if exist:
1 Select in a table context menu in DB Navigator: tools>import table(s)
2. Select output directory in the opened window and press Ok

Actual result: No data is imported.

**Comment by Sargul** [comment]
Fixed in #9131 
![export_import](https://user-images.githubusercontent.com/5595511/86206621-1ec0c280-bb6d-11ea-856c-abb5841efc3b.gif)
