### ISSUE TITLE
[Exasol] Unable to delete a foreign key

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8762]
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 7.0.5

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
Unable to delete a foreign key.
#### Steps to reproduce, if exist:
Precondition: Create 2 tables with a foreign key between them.
Step: Delete foreign key via UI (Object Editor) or SQL Editor.
Actual result:
1. Error appears: SQL Error [22000]: data exception - constraint not found (Session: 1667294203564178943)
2. The foreign is not deleted
![dbeaver_sOGswBp9c3](https://user-images.githubusercontent.com/51405061/82549845-3e280100-9b66-11ea-95e1-9b325d60d493.png)

**Comment by Sargul** [comment]
Should be fixed with #9131 

![drop_fk](https://user-images.githubusercontent.com/5595511/86205464-3ba7c680-bb6a-11ea-9980-77ba4095b51a.gif)
