### ISSUE TITLE
Grouping separator is not taken from regional settings 

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#8763]
I have set in system settings (Windows/Regional settings) space as thousands grouping separator, so expecting numbers to be formatted like that: 123 456.78 
But this settings is not taken when presenting data in result set

Also I tried to change data format/  locale  - but whatever I change here (any language / country) same grouping and decimal symbol is presented (comma -> grouping, dot -> decimal place)

![image](https://user-images.githubusercontent.com/5410448/82551900-66613100-9b61-11ea-8e3e-79bd202d6565.png)

**Comment by kseniiaguzeeva** [comment]
Please try to enable setting **Use native numeric format**.

**Comment by maciey** [comment]
> Please try to enable setting **Use native numeric format**.

I did try - but then it stops grouping at all

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by serge-rider** [comment]
@maciey Please check connection settings (they can overwrite global data formatting settings).
You can see them on connection settings dialog or by clicking on cog icon in the bottom toolbar.

**Comment by maciey** [comment]
> 
> 
> @maciey Please check connection settings (they can overwrite global data formatting settings).
> You can see them on connection settings dialog or by clicking on cog icon in the bottom toolbar.

@serge-rider 
I cant see there any locale info / grouping setting - what option I should check ?
Below is what I see

![image](https://user-images.githubusercontent.com/5410448/84986191-6ba0a400-b13e-11ea-9053-a85f92328891.png)

**Comment by kseniiaguzeeva** [comment]
The data format can be set for whole DBeaver or for one database only.

Steps:
1. Select Edit connection in context menu in DB Navigator for your database
2. Go to Data viewer> Data formatting
3. Check whether Datasource settings enabled (they can overwrite global data formatting settings).

![6h1o3JnvI7](https://user-images.githubusercontent.com/51405061/85267303-c3604780-b47d-11ea-8ddc-00f09e79f961.gif)

**Comment by maciey** [comment]
I was able finally to set what I needed (space as grouping separator) - but I had to user FR region.
There is no option to select PL (Poland), no option to set own separator character (most welcome option), system regional settings are not honored (I have spaces as separator in all Windows apps)

So as long as I know workaround I can consider this as resolved. But from app perspective this is not most elegant way ... :)   


![image](https://user-images.githubusercontent.com/5410448/85825266-112cc680-b782-11ea-8f7c-655909ad2ab0.png)
