### ISSUE TITLE
Escaping in Configure Filters

### ISSUE THREAD

**Issue by namtab00** [dbeaver/dbeaver#8767]
#### System information: 
- Win10
- DBeaver Version 7.0.5.202005171753

#### Connection specification:
- irrelevant

#### Describe your question:
How do I escape an underscore "_" in a filter inclusion / exclusion, as per [Configure Filters](https://github.com/dbeaver/dbeaver/wiki/Configure-Filters) ?

I'm trying to exclude from the tree all functions starting with _, so I tried:

- _*
- \\_*
- [_]*

but none seems to work...

**Comment by uslss** [comment]
To escape underscore you could use backslash, e.g. %\_%
