### ISSUE TITLE
Tables are not displayed in the schemas - PostgreSQL 9.6

### ISSUE THREAD

**Issue by vpatil-git** [dbeaver/dbeaver#8769]
#### System information: 
- Operating system (distribution) and version - Windows 10 x64 1909
- DBeaver version - 7.0.5
- Additional extensions - Dark theme

#### Connection specification:
- Database name and version -  PostgreSQL 9.6.16 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.9.3, 64-bit
- Driver name - 
postgrsql-42.2.5.jar
postgis-jdbc-2.2.1.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
When I connect to the instance, I see the databases but when I expand it, i dont see the tables or any other objects like functions, triggers, sequences etc..
I have the admin rights on my account and when I use other clients like PgAdmin 4.0 or Azure Data Studio I am able to see everything correctly. Please mind that its an RDS Postgres Aurora instance and a huge one with 900+ databases.

I checked the connection settings and they look correct. I even deleted and created a new connection, but the issue still persists.

I referred to other issue - https://github.com/dbeaver/dbeaver/issues/933 but it does not have any solution.

#### Steps to reproduce, if exist:
- Create a new postgres connection > Expand the database > Tables > It is blank

**Comment by vpatil-git** [comment]
I discovered something new with this issue. When I expand the database> Schemas > public > Tables > It shows blank.
But if I right click on Tables and click 'Browse from here', it shows those tables in a new tab that opens on the right-bottom of the screen. This tab correctly shows all the tables and the objects within those tables.

So, I firmly believe its not an issue with the driver or the permissions on my account. Please fix this. I am falling in love with DBeaver and only this issue is keeping me away and making me use PgAdmin/Azure Data studio.

Thanks,

**Comment by uslss** [comment]
hi @vpatil-git , thanks for the bug report. Unfortunately, cannot check if it reproducible, because we've got no such environment.
could you check if any filters are applied in db navigator?

**Comment by vpatil-git** [comment]
hi @uslss  - I do not have any filters in DB Navigator window. I double checked that.
This should be a normal environment. All you need is a Aurora postgres DB. 

Do we not have support for RDS / Aurora DBs ?

Thanks,

**Comment by vpatil-git** [comment]
Hi @uslss - Any updates ? I am sorry I asked it too early, but this is a big issue.. If I cant see the tables, then I cannot work with the database. This is the only thing preventing me from using Dbeaver.

The workaround is too cumbersome and open a new tab which reduces the overall workspace.
Your help would be truly appreciated :)

Thanks,
Vish

**Comment by vpatil-git** [comment]
You may close this ticket. I am not sure how and what happened.. but I see the tables now..
Sorry for the inconvenience and thanks for your help!

**Comment by serge-rider** [comment]
This is weird.

@vpatil-git Could you check Error Log for any related errors/warnings?
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Ticket closed. If issue is still actual for you - feel free to reopen the ticket with additional info.

**Comment by EmirLogas** [comment]
I encountered the same error today. When I expand "Tables", the tables do not appear, but when I right click and use the "Browse from here" option, the tables are listed in the window that opens. This only happens in tables of 1 schema. I've checked the filters and permissions and I'm sure they're okay.

**Comment by EmirLogas** [comment]
It was fixed when I disconnected the db, closed and opened the application, and said connect. Strange.

**Comment by kevin18ramos** [comment]
Similiar to EmirLogas I disconnected closed and opened DBeaver and schema tables were appearing again.

**Comment by liam-taly** [comment]
Happening to me too. But the workaround doesn't work. No tables displayed for a postgres DB running on AWS. psql lists all tables. Updated dbeaver to the latest version. Version 23.2.0.202309041200

For a second I was OH Feck...

Please fix it so I don't have a heart attack :-)

**Comment by liam-taly** [comment]
I have reopened the issue: https://github.com/dbeaver/dbeaver/issues/21196

**Comment by vinicius-oa** [comment]
The same thing happened to me. A database with dozens of schema, just a few of them display the tables.

**Comment by marden** [comment]
Yes, I confirm it too. 
Version 24.1.1 - the bug is reproducing.

**Comment by morTaZz** [comment]
yes i can confirm, same version as original user

**Comment by SafiUllahAshfaq** [comment]
I'm also facing similar kind of problem

**Comment by data11y** [comment]
Version 25.0.0.2. Changing the metadata setting "Open separate connection for metadata read:" from **Default** to **Never** has helped get the metadata for Oracle and MS SQL server for me. 

![Image](https://github.com/user-attachments/assets/f9d89457-e1f6-4ed0-8502-856837bf982b)

**Comment by czare** [comment]
I confirm the issue. Running dbeaver 25.1.1 and SQL Server Express. The tables are shown when selecting the option "Browse from here" and the Metadata setting as "Never" did not fix the problem.

**Comment by EmirLogas** [comment]
I reverted back to version 24.3.3 because of a few bugs I was experiencing, and I don't think I've had any problems since I reverted back to that version. I recommend you too.

**Comment by Raye3** [comment]
This issue still exist, running  postgres:15.2-alpine3.17 on docker, it connects successfully, tables exist if I check from psql CLI, but missing on DDeaver UI
DBeaver version -> 25.1.4

**Comment by Raye3** [comment]
> This issue still exist, running postgres:15.2-alpine3.17 on docker, it connects successfully, tables exist if I check from psql CLI, but missing on DDeaver UI DBeaver version -> 25.1.4

NVM, Right click on the connection click on "Edit connection"

Check show all databases, it should show you all databases

<img width="991" height="726" alt="Image" src="https://github.com/user-attachments/assets/e78ff2b7-1fd1-44dd-8cc5-f7c75f6cd3e7" />
