### ISSUE TITLE
dbeaver-ce snap is not using the snapcraft.yaml of this repo

### ISSUE THREAD

**Issue by galgalesh** [dbeaver/dbeaver#8774]
The current snap does not seem to be using the `snapcraft.yaml` file of this repo. Are there plans to migrate towards the `snapcraft.yaml` of this repo?

**Comment by riednyko** [comment]
The current snap uses snapcraft.yaml from this repository. But there is a build problem via Jenkins using snapcraft.yaml from this repository, specifically in the cleanup part.

The Jenkins build crashes with an error:
```
Priming cleanup 
+ cd /snap/core18/current
+ find . -type f,l -exec rm -f /home/jenkins/workspace/DBeaverDesktop/snapcraft-dbeaver-ce/prime/{} ;
find: ‘./var/cache/ldconfig’: Permission denied
find: ‘./var/lib/snapd/void’: Permission denied
find: ‘./var/lib/private’: Permission denied
find: ‘./root’: Permission denied
find: ‘./etc/ssl/private’: Permission denied
Downloading 'dbeaver-ce_latest_amd64.deb'   0%                                 
Downloading 'dbeaver-ce_latest_amd64.deb' 100%                                 
Failed to run 'override-prime': Exit code was 1.
```
But manually, everything is building successfully, with the current snapcraft.yaml .
Please tell us if you know how to fix this problem with snap permissions.
