### ISSUE TITLE
7.0.5 ODBC

### ISSUE THREAD

**Issue by OGR84** [dbeaver/dbeaver#8776]
Good afternoon, upgraded dbeaver community edition today which I use to query a PROGRESS server using ODBC, after the upgrade the ODBC libraries needed updating but I get the error shown below when it tries to connect and get the files. 

Can't open 'https://dbeaver.io/files/jdbc/drivers/odbc': Forbidden

**Comment by uslss** [comment]
hi @OGR84 , thanks for the bug report.
issue was already fixed in #8732 .
ticket will be closed as duplicate
