### ISSUE TITLE
Release 7.0.5 has problems downloading ODBC Bridge drivers

### ISSUE THREAD

**Issue by mosin44** [dbeaver/dbeaver#8780]
#### System information: 
- Operating system (distribution) and version
Windows 10 1709
- DBeaver version
7.0.5
- Additional extensions

#### Connection specification:
- Database name and version
Netezza 7.2.1.9-P2 
- Driver name
ODBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
When attempting to set up ODBC-JDBC bridge, DBeaver wants to download drivers. Cannot download driver because it is getting a 403 error on https://dbeaver.io/files. Once it hits the 403 it aborts, not attempting the Maven repo.  

<<The problem does not exist in 7.0.3>>

#### Steps to reproduce, if exist:
Database menu -> Driver Manager -> Double-click on ODBC -> Click Download/Update -> Click Download

Error message:
Driver file download failed.
Do you want to retry?

Reason:
Can't open 'https://dbeaver.io/files/drivers/odbc': Not Found

**#################################################**
By contrast - in 7.0.3, the same path of operations gets the driver properly downloaded
**#################################################**

**Comment by nsimon** [comment]
Seeing the same issue here. Any help appreciated!
- Windows 10 Pro v1903
- DBeaver v7.0.5.202005171753 (5/18/2020)

![dbeaver dialog](https://user-images.githubusercontent.com/27472/82707972-6719c600-9c3a-11ea-9fdf-541506745254.png)

Thanks, Neil

**Comment by Henry-Jones** [comment]
Hello,

here is a picture with the difference between 6.3.0 and 7.0.5 maybe it is of help.

The first entry is a folder on the webserver, so the "Forbidden" error is ok I guess, as you cannot usually target an entire folder for downloading.

I've tried to add the missing entry for the jar file but have no idea how to. Neither "Add file" nor "Add artifact" seem to work.

![image](https://user-images.githubusercontent.com/9108755/82726371-f62ee880-9ce3-11ea-963b-9c4db335f721.png)

**Comment by uslss** [comment]
hi, issue is already fixed in #8732 Fixed will be released in scope of 7.1.0
thanks for the bug report

**Comment by nsimon** [comment]
Thanks uslss!
