### ISSUE TITLE
Geometry column is not correctly shown

### ISSUE THREAD

**Issue by ZhdislavDazhbogin** [dbeaver/dbeaver#8781]
### System information:  
- Operating system (distribution) and version 
Windows 10 64-bit
java 11.0.7 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
- DBeaver version 
7.0.5
- Additional extensions

#### Connection specification:
- Database name and version
PostgreSQL 12.3, compiled by Visual C++ build 1914, 64-bit
POSTGIS="3.0.1 3.0.1" [EXTENSION] PGSQL="120" GEOS="3.8.0-CAPI-1.13.1 " PROJ="Rel. 5.2.0, September 15th, 2018" LIBXML="2.9.9" LIBJSON="0.12" LIBPROTOBUF="1.2.1" WAGYU="0.4.3 (Internal)"
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
DBeaver doesn't show any content of geometry-type column:
![image](https://user-images.githubusercontent.com/33663705/82700762-84b95080-9c77-11ea-9ee8-ff3260bf7027.png)

> java.lang.NoClassDefFoundError: org/postgis/Geometry
> 	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
> 	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
> 	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
> 	at java.base/java.lang.Class.newInstance(Class.java:556)
> 	at org.postgresql.jdbc.PgConnection.getObject(PgConnection.java:625)
> 	at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:2585)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:612)
> 	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.fetchColumnValue(PostgreGeometryValueHandler.java:53)
> 	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
> 	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:200)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3580)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> Caused by: java.lang.ClassNotFoundException: org.postgis.Geometry
> 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> 	... 17 more

But, any information about table content are correctly shown:
![image](https://user-images.githubusercontent.com/33663705/82701020-03ae8900-9c78-11ea-8631-fd646c02cc17.png)

#### Steps to reproduce, if exist:
1) Create table with DBeaver SQL Editor:
`CREATE TABLE public."_test" (
	gid serial NOT NULL,
	poi_name text NULL,
	geom geometry(POINT, 4326) NULL,
	CONSTRAINT "_test_pkey" PRIMARY KEY (gid)
);`

2) Insert data with same Editor or with psql cmd-utility
`INSERT INTO _test (poi_name, geom) VALUES ('5', 'SRID=4326; POINT(30.3250575 59.9174455)');`

#### Include any warning/errors/backtraces from the logs

All log-files are empty

**Comment by ZhdislavDazhbogin** [comment]
Someone here?

**Comment by uslss** [comment]
Hi @ZhdislavDazhbogin ,
sorry for the late response. Cannot reproduce an issue - works ok for me (7.1.1)
![image](https://user-images.githubusercontent.com/31996417/85266764-04a42780-b47d-11ea-8789-4ed894290be4.png)
Probably you've got some problems with Postgis libraries

**Comment by ZhdislavDazhbogin** [comment]
I downloaded latest version (windows zip portable), unpacked it to empty folder, While was launching it suggested me to download drivers. I performed sql select and got appropriate content in geometry column.
it seems the problem was in incorrect last update of the program.
Thanks.
