### ISSUE TITLE
Date Time

### ISSUE THREAD

**Issue by cherinae** [dbeaver/dbeaver#8783]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 7.0.5

#### Describe your question:
Hi, I can't work with the date and timestamps in dBeaver. I want to do something like this : SELECT date('now','start of month','+1 month','-1 day'); This works in SQLite but I can't run it in dBeaver. Also, I would like to add 1hour to a timestamp but not sure how to. How do I go about typing the queries for dates and timestamps and is there a documentation on the CURRENT_TIMESTAMPS() etc somewhere? I can't seem to find it. Sorry for the basic question and thanks in advance!

**Comment by uslss** [comment]
Cannot reproduce it
![image](https://user-images.githubusercontent.com/31996417/88383585-74c30780-cdb3-11ea-95ee-6d87319b3ae5.png)
Could you post more info?

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Ticket closed. If issue is still actual for you - feel free to reopen the ticket with additional info.
