### ISSUE TITLE
(Firebird) Navigator > Tables structure shows first table after modifying the structure 

### ISSUE THREAD

**Issue by janderk2** [dbeaver/dbeaver#8785]
#### System information: 
- Operating system (distribution) and version
Windows 10

- DBeaver version
7.0.5

- Additional extensions
None

#### Connection specification:
- Database name and version
Firebird 2.5
- Driver name
org.firebirdsql.jdbc.FBDriver

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No. localhost

#### Describe the problem you're observing:
When changing the structure of a table (eg adding an field) and persist/save the changes, the tables list in the DBeaver Navigator is wrong. The edited table is replace with the first table.

#### Steps to reproduce, if exist:
Create a Firebird database with 2 or more tables.
Add a field to second table.
Save/persist changes
DBeaver > Navigation automatically refreshes and the current selected table is replaced with the first table. It can be fixed by disconnecting and reconnecting to the database.

#### Include any warning/errors/backtraces from the logs
Error log is empty

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
not reproducible anymore (21.1.3)
