### ISSUE TITLE
Can't insert large INT UNSIGNED and BIGINT UNSIGNED numbers

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#8786]
I have a table in MySQL with an INT UNSIGNED field and I can't insert large numbers above the signed threshold, that is 2147483648 and above. In the editor I can insert 2147483647 without problems but when I insert 2147483648 and press Enter the number changes to -2147483648 and the effect is I can't save the record because the number is out of range. 

A similar problem occurs when I have a BIGINT UNSIGNED field and I try entering a number above the signed threshold: 9223372036854775808 and larger. The only difference is that the number appears correctly in the editor cell but still the generated insert/update query is erroneous.

The same problems happen when trying to import such numbers through the Data Import tool from CSV.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
Fixed in 7.1.1

**Comment by Scapaflousx** [comment]
Всем привет.
У меня проблема.
Когда ввожу команду UNSIGNED пишет ошибку и не дает запустить дальше код.
Может быть у кого-нибудь была такая проблема?
И как вы ее решили?
Hello everyone. I have a problem. When I enter the UNSIGNED command, it gives an error and does not allow me to run the code further. Maybe someone had such a problem? And how did you solve it?
[

![Image](https://github.com/user-attachments/assets/cdd36d44-8119-4c5f-a0c1-c73cd79abb3e)

](url)
