### ISSUE TITLE
Define Dictionary description with references from the referenced table

### ISSUE THREAD

**Issue by lilyannh** [dbeaver/dbeaver#8787]
I'm having a hard time naming this feature request properly, so perhaps an example.

Let's say I have 3 tables:

organization
author
article

The `article` table contains articles or blog posts or whatever, with a foreign key reference to its `author`. The `author` table has identifying information about each author, with a foreign key reference to `organization`. Each organization can have many authors, and each author can have many articles.

From `article`, it is quite easy (and useful!) to see relevant information about the author using the dictionary feature - I think it would also be quite nice to define the dictionary entries to show information from the pertinent organization too.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by AnrDaemon** [comment]
Me, too, I wish to be able to define dictionary descriptions as SQL statements.
The use case of `article/author/organization` (i.e.) is quite common in business logic.
In my case, it is `document/status/workflow`, where I want to clearly see that document has status from its own workflow, not some different one. (Happens at times, causes much headache in investigation.)

**Comment by uslss** [comment]
will be implemented in #10765
