### ISSUE TITLE
Allow to see PostgreSQL REFCURSOR results in editor

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#8789]
**Is your feature request related to a problem? Please describe.**
I always wanted to see the results of a cursor returned from a function in PostgreSQL instead of just "<unnamed portal 1>"

**Describe the solution you'd like**
I would like to be able to double click "<unnamed portal 1>" in the query results and that a popup window would open with the cursor data (all columns an values).

**Describe alternatives you've considered**
Fetching the cursor manually in an anonymous block and printing its' values requires writing custom code.

**Additional context**

**Comment by serge-rider** [comment]
Yeah, we had to fix it a long time ago.
In fact we already have ref cursors support for Oracle and PostgreSQL.
It works only in manual commit mode. Currently you can see cursor contents by <kbd>shift+enter</kbd> (it will be opened in popup dialog).

But we definitely need to show it in panel viewer + have ability to reuse cursor.
Like this:
![image](https://user-images.githubusercontent.com/6398845/82880911-b1a38700-9f47-11ea-8176-cdd23d01c8b1.png)

**Comment by uslss** [comment]
verified
