### ISSUE TITLE
Impala press the F4 table to view the error report

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#8792]
After the new table is established, press F4 to report the error, and the query can be normal
![image](https://user-images.githubusercontent.com/26621087/82881211-fc39f900-9f71-11ea-82a5-2af1e055a861.png)

#### System information: 
- Operating system (distribution) and version  WIN10
- DBeaver version  7.05
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Hi @Pengchenghua ,
is issue appears when you create a table using UI? Does Refresh in DB Navigator solve the problem?

**Comment by uslss** [comment]
there is no update on the issue for a long time. if the issue is still actual for you, feel free to reopen it with additional info.
BR
