### ISSUE TITLE
Option "Force object refresh on editor open" does not work on Oracle packages

### ISSUE THREAD

**Issue by simasch** [dbeaver/dbeaver#8795]
#### System information: 
- Window 10
- 7.0.5

#### Connection specification:
- Oracle 12.2.0.1.0
- Oracle JDBC

#### Describe the problem you're observing:
Oracle Packages are not refreshed when the option "force object refresh on editor open" is set.

This is a severe error because it may lead to lost updates on package declarations!

#### Steps to reproduce, if exist:
Edit a package in another editor like SQL Developer and open the package in DBeaver. You will see that the changes are not visible.

#### Include any warning/errors/backtraces from the logs
No entries found in the log files

**Comment by simasch** [comment]
The problem are these lines in NavigatorHandlerObjectOpen

```
if (DBWorkbench.getPlatform().getPreferenceStore().getBoolean(NavigatorPreferences.NAVIGATOR_REFRESH_EDITORS_ON_OPEN)) {
    if (databaseObject instanceof DBSObjectContainer) {
        // do not auto-refresh object containers (too expensive)
    } else {
        refreshDatabaseNode(dnNode);
    }
}

```

OraclePackage implements DBSObjectContainer and will not be refreshed.
This is a mistake for Packages.

**Comment by uslss** [comment]
verified
