### ISSUE TITLE
Using multiple dash (-) in SQL where statement gives me no data

### ISSUE THREAD

**Issue by mickeydebby** [dbeaver/dbeaver#8801]
#### System information: 
- Windows 10
- Version 7.0.5.202005171753

#### Connection specification:
- AWS / Redshift

#### Describe your question:

I assume this could be some setting issue. When I have something like below (example, not actual data), I got no result

`where name = 'ni-hao-ma'`

Whereas if I use something like below, I got result (because there indeed is data where name = 'ni-hao-ma')

`where name like 'ni-hao%'`

Can you point out what the setting needs to be changed?

Thanks!

**Comment by uslss** [comment]
Hi @mickeydebby ,
unfortunately, cannot reproduce an issue. Probably some special steps are needed?
![image](https://user-images.githubusercontent.com/31996417/83576353-3b4fe780-a53a-11ea-9419-d081617498cd.png)

**Comment by uslss** [comment]
there is no update on the issue for a long time. if the issue is still actual for you, feel free to reopen it.  
BR
