### ISSUE TITLE
Filter by column value popup window disappear on move/resize

### ISSUE THREAD

**Issue by notAmine** [dbeaver/dbeaver#8802]
#### System information: 
- Operating system (distribution) and version: **Ubuntu 18.04.4 LTS**
- DBeaver version **Version 7.0.5.202005171753 CE**
- Additional extensions **No**

#### Connection specification:
- Database name and version: Microsoft SQL Server 11.00.6260 Microsoft SQL Server 2012 (SP3-GDR)
- Driver name MS SQL Server / SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? VPN

#### Describe the problem you're observing:
Can't move/resize 'Filter by column value' popup window
#### Steps to reproduce, if exist:
Connect to DB, Load any table results, click on Filter by column value icon and try to move resize window will make the popup disappear. 
Also clicking anywhere other than inside the window itself will have same effect.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed (switch to default popup panel renderer)

**Comment by uslss** [comment]
verified
