### ISSUE TITLE
Grid and Text results displays [NULL] for all string values (except when CAST to text)

### ISSUE THREAD

**Issue by nsimon** [dbeaver/dbeaver#8803]
#### System information: 
- Windows 10 Pro
- DBeaver v6.0.0

#### Connection specification:
- Reproducible with no database needed, via simple `SELECT` statement.

#### Describe your question:
Is there a configuration setting that will cause these **[NULL]** values to display correctly?

Grid (and Text) results displays **[NULL]** for all string values (except when `CAST` to text):
`SELECT CAST ('Hello Joe 1' AS text);  -- works`
`SELECT  'Hello Joe 5';  -- displays [NULL]`

![image](https://user-images.githubusercontent.com/27472/82945979-ce958580-9f5a-11ea-92b7-97539064edbc.png)

Thanks, Neil

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce it. Different databases do show such result? Could you try last version 7.0.5 https://dbeaver.io/download/?

**Comment by nsimon** [comment]
Thanks Kseniia. I was unable to get it to work. Unable to upgrade, as I need to run the 32-bit version -- which works with my 32-bit ODBC drivers. I have a solution with another SQL client now, which has been working well.
