### ISSUE TITLE
.dbeaver folder created with new/opening project

### ISSUE THREAD

**Issue by lindholm** [dbeaver/dbeaver#8806]
#### System information: 
- Operating system (distribution) and version:: Windows 10 1809
- DBeaver version: 7.0.5
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When I import a maven project in Eclipse a .dbeaver folder is automatically created

#### Steps to reproduce, if exist:
import  an existing maven project

**Comment by uslss** [comment]
will be solved in scope of #10507
