### ISSUE TITLE
SQL tools -> database tasks

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#8810]
We have quite a few SQL tools (like analyse, truncate, etc). They are UI components (dialogs with some embedded SQL generation logic).
We need to turn them into database tasks. So they can be called from both context menu and taqsk management view, scheduled, combined, etc.

**Comment by serge-rider** [comment]
This is a general ticket about task management UI (SQL tool task wizard)

**Comment by uslss** [comment]
verified
