### ISSUE TITLE
Error when change language (install from snap)

### ISSUE THREAD

**Issue by ASYOU99** [dbeaver/dbeaver#8811]
#### System information: 
- Ubuntu 20.04
- 7.0.5

#### Describe the problem you're observing:
when i try change language i have error: 
Unexpected error while saving startup configuration
  /snap/dbeaver-ce/56/usr/share/dbeaver/dbeaver.ini: Read-only file system  /snap/dbeaver-ce/56/usr/share/dbeaver/dbeaver.ini: Read-only file system
#### Steps to reproduce, if exist:
install fron snap
try change language
https://i.imgur.com/WEOxjsu.png

Same error if i install version deb package ce from dbeaver.io

**Comment by uslss** [comment]
thanks for the bug report

**Comment by jordanidejesus** [comment]
I have the same problem.

**Comment by riednyko** [comment]
Unfortunately, snap files are mounted read-only and we can't change the permissions in this path.
You can try changing the language manually by adding `-nl en` to the dbeaver.desktop file.

**Comment by lucianotres** [comment]
Same issue with Windows. 
`Can't save startup configuration - access denied.
You could try to change national locale manually in 'C:\Program Files\DBeaver\dbeaver.ini'. Refer to readme.txt file for details.`

This configurations should be into user folder, not app folder, like projects, etc, into %APPDATA%\DBeaverData

**Comment by dseira** [comment]
A possible workaround is adding `-nl en` to the snap desktop entry in `/var/lib/snapd/desktop/applications/dbeaver-ce_dbeaver-ce.desktop` at the end of the `Exec` option.

**Comment by santiagofn** [comment]
Hi. I'm using Ubuntu 20.10 and DBeaver CE 21.0.2.
Tried the workaround, didn't work.

![imagen](https://user-images.githubusercontent.com/8375708/114565530-b9dfe000-9c47-11eb-9c49-2e2515980a32.png)

![imagen](https://user-images.githubusercontent.com/8375708/114566079-4db1ac00-9c48-11eb-953d-4b4aa27c640e.png)

**Comment by serge-rider** [comment]
@santiagofn It has to be `nl` not `n1` (L <> 1)

**Comment by serge-rider** [comment]
Now language selector is disabled + instructions are shown when DBeaver is installed in a write-protected folder.

**Comment by uslss** [comment]
verified

**Comment by uslss** [comment]
Error appears if no changes were made, but Preference window was closed using "Apply and Close" button

https://user-images.githubusercontent.com/31996417/116363131-7bcbea00-a80b-11eb-9cde-fb1b986d6937.mp4

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by uslss** [comment]
notification in preferences isn't shown in case of installing application for All users

**Comment by serge-rider** [comment]
Extra check for write-protected directory was added.

**Comment by uslss** [comment]
verified

**Comment by Duduxs** [comment]
The workaround works here.
