### ISSUE TITLE
Mysql exec 2 query sql will err

### ISSUE THREAD

**Issue by JqueryArray** [dbeaver/dbeaver#8814]
#8672 ## System information: 
- Win10
- DBeaver version 7.0.5

#### Connection specification:
- MySQL 5.6.48
- MySQL Connector Java mysql-connector-java-5.1.44 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When exec 2 query sql, at the same time, then error. It seems that the end of th second sql misses ';'

![image](https://user-images.githubusercontent.com/27047948/83096419-32918880-a0d8-11ea-8d5a-14cf1b1a1efe.png)

**Comment by uslss** [comment]
hi @JqueryArray ,
could you try to execute your queries using Execute SQL scripts (Alt+x) button?

**Comment by uslss** [comment]
there is no update on issue for a long time. if issue is still actual for you, feel free to reopen it.
BR
