### ISSUE TITLE
Before connecting, I want to run "AWS RDS generate-db-auth-token" in "shell command" to set the password.

### ISSUE THREAD

**Issue by YutaOkoshi** [dbeaver/dbeaver#8815]
#### System information: 
- macOS Catalina 10.15.4
- DBeaver version: CE 7.0.5

#### Connection specification:
- RDS for MySQL 5.6.34

#### Describe your question:

I'm sorry if this is a silly question.

This RDS has IAM authentication enabled.
https://aws.amazon.com/premiumsupport/knowledge-center/users-connect-rds-iam/?nc1=h_ls

Before connecting, I want to run "AWS RDS generate-db-auth-token" in "shell command" to set the "$password".

But isn't it possible to set environment variables before the connection?
I want to be able to get connection tokens automatically.

thanks.

**Comment by YutaOokoshi** [comment]
Will this be difficult?

**Comment by uslss** [comment]
Hi @YutaOkoshi , it is already implemented in Enterprise Edition. You could test it in Trial version

**Comment by YutaOkoshi** [comment]
Thanks for the reply.
what should I do if I use 'AssumeRole' or 'AWS SSO'?

I don't think there is an access and secret key for the AssumeRole destination, and it looks like I can't enter the aws_session_token.

**Comment by YutaOkoshi** [comment]
@uslss 
Should I ask the question on a separate issue?
