### ISSUE TITLE
Error appears when trying to open Permissions in Simple View

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8817]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.0

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
Error appears when trying to open Permissions Tab for Table in Simple View
#### Steps to reproduce, if exist:
1. Connect to database in Simple View
1. Open any table in Metadata editor
1. Try to open Permissions Tab
**Actual result:**
Error appears on Permissions Tab opening
![image](https://user-images.githubusercontent.com/31996417/83132796-991fa200-a0ea-11ea-8ef2-3d4b8e23b317.png)

**Comment by serge-rider** [comment]
Permission management (As well as metadata editor) is no available in Simple mode. This tab mustn't be visible.
