### ISSUE TITLE
Copy Table with Data and Indices

### ISSUE THREAD

**Issue by geo-tech** [dbeaver/dbeaver#8819]
#### System information: 
- Windows 10 1909
- DBeaver 7.0.5.202005171753

#### Connection specification:
MySQL

#### Describe your question:
Is it possible to copy a Table with Data and Indices? 
If i copy a Table with CTRL+C/CTRL+V the complete DDL is copied without Data.
If i copy a Table with the Import/Export Wizard the Table with Data is copied, but without Indices. The DDL for new Table is only with columns.

**Comment by kseniiaguzeeva** [comment]
You can use dump/restore function in PostgreSQL and MySQL. (in schema context menu or via Database Task panel)
![dbeaver_KmUqvn5DpD](https://user-images.githubusercontent.com/51405061/89286379-c47abc00-d65a-11ea-8a69-1f7c83ae7637.png)

**Comment by justinTM** [comment]
not accurate solution:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/9123665/182230460-bc66925f-a193-4a7f-99de-e6e78d692c80.png">
