### ISSUE TITLE
Missing icon on Tint2 bar when snap is running

### ISSUE THREAD

**Issue by lfromanini** [dbeaver/dbeaver#8821]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Include any warning/errors/backtraces from the logs

When running DBeaver-ce 7.0.5 from snap, it's not showing the application icon on tint2 bar. Please notice that the icon exists in start menu. It's missing only on the Tint2 bar (in my case, since I use Openbox + Tint2).

**Comment by uslss** [comment]
cannot reproduce it for now.
If issue is still actual for you - feel free to reopen it
