### ISSUE TITLE
Incorrectly quoting values of a UUID array

### ISSUE THREAD

**Issue by kierxn** [dbeaver/dbeaver#8823]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro - 10.0.18363 Build 18363
- DBeaver version: 7.0.5
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgresSQL 12.2
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Nope

#### Describe the problem you're observing:
When copying an array of uuids from a column, the uuids are quoted which then pasted into another column will fail.

#### Steps to reproduce, if exist:
Create a table with an array of uuids

```
CREATE TABLE test (
	id int NOT NULL,
	"uuidArray" _uuid NULL,
	CONSTRAINT test_pkey PRIMARY KEY (id)
);

INSERT INTO public.test (id, "uuidArray") VALUES (1, '{62bd91ce-10c8-4a21-b818-06f70cafd2c6, f2ce6ff8-4202-4eb1-9439-e887a39e87cc}')
```

Now when you view the table, you can see the values are quoted, when they shouldn't be.

![image](https://user-images.githubusercontent.com/1763705/83153998-8364a980-a0f7-11ea-84e9-2957c71e0ed3.png)

If you then copy the value of the column you get:
```
{'62bd91ce-10c8-4a21-b818-06f70cafd2c6','f2ce6ff8-4202-4eb1-9439-e887a39e87cc'}
```

Instead of:
```
{62bd91ce-10c8-4a21-b818-06f70cafd2c6,f2ce6ff8-4202-4eb1-9439-e887a39e87cc}
```

I also tried advanced copy and it did nothing.

**Comment by uslss** [comment]
thanks for the bug report and sorry for the late response

**Comment by kierxn** [comment]
No problem! Thank you for your response, look forward to seeing this fixed!

**Comment by uslss** [comment]
verified
