### ISSUE TITLE
[Sybase] Schema couldn't be created using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8824]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.1.0

#### Connection specification:
- Database name and version Sybase jConnect

#### Describe the problem you're observing:
When trying to create New schema for Sybase - error appears.
Also, it is quite strange that Schema is called Owner in context menu.
![image](https://user-images.githubusercontent.com/31996417/83160536-00038200-a110-11ea-9ab4-f5546f1e2179.png)

**Comment by serge-rider** [comment]
Fixed
