### ISSUE TITLE
Office addin has errors

### ISSUE THREAD

**Issue by wwinker** [dbeaver/dbeaver#8826]
Getting the following when trying to export to Excel

Please fill in as much of the template as possible.
-->

#### System information: Win 10, DBeaver version 6.0.4/6.2.0/7.0.3
- Operating system (distribution) and version 
- DBeaver version

#### Connection specification:
- Database name and version

#### Describe your question:Query works fine. Exporting to Excel, getting the following:

 
![image](https://user-images.githubusercontent.com/66085428/83176922-3f1fdc00-a0ec-11ea-9b41-70ee650ec4e7.png)

These are the only versions supported in our corporate environment.

**Comment by uslss** [comment]
Hi @wwinker ,
unfortunately cannot reproduce it. Could you tell what database do you use?

**Comment by wwinker** [comment]
dbslp0568 (Hive) and dbsep2427 (SS)

**Comment by uslss** [comment]
cannot reproduce against 7.3.4
