### ISSUE TITLE
Win10: DBeaver 7.0.5: Firebird-DB 3: CreateTable: CreateColumn raises an error

### ISSUE THREAD

**Issue by hansguentermann** [dbeaver/dbeaver#8828]
Hello, 

1. I installed dbeaver-ce-7.0.5-x86_64-setup.exe on Windows 10 with Firebird 3 and JayBird 4.0 for all users. 
2. I created a new Firebird-DB with ISQL
3. I opened the database in DBeaver
4. I created a new table "TEST"
5. I tried to create a new column (right-click: create column) and the following error appeared: 
![DBeaver_ErrorcreatingNewObject](https://user-images.githubusercontent.com/66087771/83183465-233a2b80-a128-11ea-9165-d9865ec74b3e.png)

What am I doing wrong?
Thanks,
HG

EDIT 01.06.2020:
Same error under DBearver 7.1.0.

**Comment by JamesYuCN** [comment]
I have same error . (on firebird 3.0 and firebird 2.5). 

Thanks,
James

**Comment by hansguentermann** [comment]
Same error under DBearver 7.1.0.

**Comment by uslss** [comment]
sorry for the late response.
Thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
