### ISSUE TITLE
Upgrade from DBeaver 6.3 to 7.0.5 stopped postgres SSH tunnel from working

### ISSUE THREAD

**Issue by benlachs** [dbeaver/dbeaver#8831]
#### System information: 
- Operating system (distribution) and version macOS High Sierra 10.13.6
- DBeaver version 7.0.5
- Java version java version "1.8.0_181"
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name Postgres 10
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:

Basically, I was using DBeaver 6.3, connecting to a postgres DB through an SSH tunnel. This configuration had been working fine for many months, so configuration was all correct.

I upgraded to DBeaver 7.0.5, and the SSH tunnel no longer works:
Can't initialize tunnel
  Cannot establish tunnel
  Cannot establish tunnel
    invalid privatekey: [B@6083da0a
    invalid privatekey: [B@6083da0a

#### Steps to reproduce, if exist:

Setup DBeaver 6.3 to connect to a DB thrrough an SSH tunnel. Then upgrade to DBeaver 7.0.5

**Comment by serge-rider** [comment]
Can't reproduce.
Please check error/debug logs. I need error stacktrace to investigate this issue.
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by uslss** [comment]
there is not any update on issue for a long time. Ticket is closed.
If issue is still actual for you - feel free to reopen the issue with additional info
