### ISSUE TITLE
Error appears when trying to open Empty schema in Simple view

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8833]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.0

#### Connection specification:
- Database name and version PostgreSQL
#### Steps to reproduce, if exist:
1. Switch database view to simple
1. Open any empty database in property viewer
Actual result:
error appears
![image](https://user-images.githubusercontent.com/31996417/83259538-ea01ca00-a1c0-11ea-8972-19fd799d0326.png)

**Comment by serge-rider** [comment]
Fixed (error was caused by permission editor, now we don't show it in simple view mode)

**Comment by uslss** [comment]
verified
