### ISSUE TITLE
Postgres 9.6 - Schema does not list all the tables

### ISSUE THREAD

**Issue by vpatil-git** [dbeaver/dbeaver#8836]
#### System information: 
- Operating system (distribution) and version -- Win 10, 1909 x64
- DBeaver version -- 7.1.0 EA
- Java version - JRE 8
- Additional extensions - None

#### Connection specification:
- Database name and version - PostgreSQL 9.6.16 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.9.3, 64-bit
- Driver name - postgresql 42.2.12
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
My schema has a large number of table around 13,329.
When I try to expand the schema and try to see the tables, it does not load them and instead show me this - see the screenshot.

![image](https://user-images.githubusercontent.com/63340345/83265400-1593ad00-a1df-11ea-82cf-d9817416b430.png)

Is there a setting which limits the display of these tables? Is this a bug?

#### Steps to reproduce, if exist:

Same as above

**Comment by serge-rider** [comment]
Can't reproduce.
DBeaver limits number of elements in database navigator to 5k by default (you can change this number in Preferences->Navigator).
However it must show table list and then show `More ...` as last element.

Do you have any table/schema filters?
Are there any related messages in error/debug logs? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by uslss** [comment]
There are not any updates on issue more than a month.
It is closed.
If it is still actual for you - feel free to reopen it
