### ISSUE TITLE
"Invalid Configuration Location" when starting DBeaver Version 7.0.5.

### ISSUE THREAD

**Issue by riroly** [dbeaver/dbeaver#8838]
I am on a Windows 10 laptop.
I just downloaded "dbeaver-ce-7.0.5-win32.win32.x86_64.zip".
As usual, I unzipped the file, then attempted to run DBeaver.exe.
This time however, I got the following error.
![image](https://user-images.githubusercontent.com/51757023/83276265-58816080-a19e-11ea-8120-afe764fae328.png)

I was previously running version 7.0.0 without issue.

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it in 7.0.5 and 7.1.0. Is DBeaver 7.0.0 was deleted when you run 7.0.5 verson?

**Comment by uslss** [comment]
there is not any update on issue for a long time. Ticket is closed.
If issue is still actual for you - feel free to reopen the issue with additional info
