### ISSUE TITLE
Disable auto-capitalization of keywords inside comments.

### ISSUE THREAD

**Issue by cdabel** [dbeaver/dbeaver#8839]
#### System information: 
Mac OS - latest version

#### Connection specification:
Not sure if relevant, but Redshift via Postgres driver

#### Describe your question:
I think this may be more of an enhancement, but I would like to disable auto-capitalization of SQL keywords automatically while typing within comments. Is there a way to do this? I know how to turn it off completely, but I would like the behavior to be contextual in this way.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
duplicate of #5994
