### ISSUE TITLE
[Oracle] Java tab shows no content

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8842]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.0 EA

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
Java tab of DBO Editor shows no content
#### Steps to reproduce, if exist:

1. Open a schema in DBO Editor
2. Select **Java** tab in properties

Actual result: Error appears:
![dbeaver_eYwWrL1rtO](https://user-images.githubusercontent.com/51405061/83323464-99917780-a267-11ea-8246-4b6555d4d59b.png)
[.log](https://github.com/dbeaver/dbeaver/files/4705328/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4705329/dbeaver-debug.log)

**Comment by serge-rider** [comment]
I think this issue has the same nature as #8837

**Comment by riednyko** [comment]
Fixed. The solution is the same as [#8837](https://github.com/dbeaver/dbeaver/issues/8837)

**Comment by kseniiaguzeeva** [comment]
verified
