### ISSUE TITLE
Debian repo expired certificate?

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#8846]
Hi!
Trying to upgrade, receive

```
Err:10 https://dbeaver.io/debs/dbeaver-ce  Release                       
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 104.236.93.175 443]
```

Already tryed
```
wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
```
Same result

Thanks!

**Comment by bbruno** [comment]
Hi !
Same issue here.
Certificate date expiry seems to be ok (renewed 04-28-2020)

Thanks

**Comment by Gehadzeidan** [comment]
Hi All! 
Same issue here but I couldn't find the solution 
also Tried 
wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
sudo apt update 

Still the same issue, any advice ?

**Comment by serge-rider** [comment]
Sectigo RSA root certificate has expired by some reason.

I've reissues dbeaver.io SSL certificate. Everything must be ok now.

**Comment by serge-rider** [comment]
https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117LT

**Comment by jcassee** [comment]
Thank you, @serge-rider. I can verify apt is not complaining anymore.

**Comment by Gehadzeidan** [comment]
Thank you all for your support, I have updated successfully without any error 
Thank you @serge-rider

**Comment by utqinadhif** [comment]
and now this is happening again

**Comment by ghost-from-the-past** [comment]
> and now this is happening again

This time doesn't look as an expired certificate
APT says "The certificate issuer is unknown"

W: Failed to fetch https://dbeaver.io/debs/dbeaver-ce/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 104.131.190.124 443]

the solution is here
https://github.com/dbeaver/dbeaver/issues/35777
