### ISSUE TITLE
First query after a few minutes takes a long time to reconnect

### ISSUE THREAD

**Issue by kpconnell** [dbeaver/dbeaver#8849]
#### System information: 
- Mac Catalina, Latest
- .0.4.202005031953

#### Connection specification:
- Mysql Azure

#### Describe the problem you're observing:
When a connection times out (after 5 minutes or so), the next query revalidates / reconnects and this takes around 30 seconds on broadband and several minutes on slower connections.  

Note, this isn't a bug report - it's a design problem with the assumptions DBeaver makes about the need to get metadata and other aspects about the database before issuing the query.  All that is necessary is the tcp/ip setup.  No metadata about the database or server is necessary to actually issue a query...

#### Steps to reproduce, if exist:
Open a new editor.
Wait for a while
Run and query.

**Comment by uslss** [comment]
cannot reproduce it for now.
If it is still actual for you - feel free to reopen an issue
