### ISSUE TITLE
DBeaver 7.1.0 - gui - db explorer - color of connections is ... "messy"

### ISSUE THREAD

**Issue by miroque** [dbeaver/dbeaver#8854]
#### System information: 
- Operating system (distribution) and version:  OS: Ubuntu 18.04 bionic, DE: Cinnamon 4.2.4
- DBeaver version: 7.1.0

![image](http://imgur.com/5EmipNll.png)

1. border not over whole text, missing last 1.5-2 characters
2. bunch of borders is...like moire
3. previous version of color background - for my taste was better,

**Comment by serge-rider** [comment]
Seems to be GTK-specific issue in the tree custom renderer.

**Comment by miroque** [comment]
Thanks for your fast review, and super-duper product!
Hope, some day I become user of payed version :)

**Comment by mioux** [comment]
I don't use gtk (running kde), I've got this 
![image](https://user-images.githubusercontent.com/6904170/83393204-ad1f1880-a3f6-11ea-869b-dea8faca3401.png)

**Comment by eldarnegrinperion** [comment]
ubuntu 16.04 here, same.
I liked it better with the old version, full bg color. 
this way the color is barely noticeable, and ofc the text sticking out etc..
thanks!

**Comment by Xylandor** [comment]
> I liked it better with the old version, full bg color.
> this way the color is barely noticeable, and ofc the text sticking out etc..

I agree. This new way of coloring nearly every tree mode creates more of a distraction and just looks trashy. I know there's people out there that like it, but there's other that don't. If anything, please add an option to where we can choose whether or not to have the coloring affect the tree. 

Thanks.

**Comment by miroque** [comment]
also i saw #8705 about

> (e.g. target host) next to the connection name

it's very pretty feature!

but at my environment looks like

![image](http://i.imgur.com/1qpbuNq.png)

this not aligned vertically and horizontally

**Comment by dNvl** [comment]
Hello people,
got the same problem on Ubuntu 18.04 LTS with DBeaber 7.1.0 and gnome gtk.

The problem for me is that i am also fairly color blind so this mode makes it nearly impossible for myself to distinguish between the connection types. 

Could you at least provide an option in the settings to select a complete background coloring or provide a circle indicator before the line? Also strange that every table inherits the warning or was this intended?

Best regards and thanks for your work and the otherwise great update.

![image](https://user-images.githubusercontent.com/1012231/84026623-f1c62900-a98d-11ea-8935-007f1385891f.png)

**Comment by lemon-juice** [comment]
> > I liked it better with the old version, full bg color.
> > this way the color is barely noticeable, and ofc the text sticking out etc..
> 
> I agree. This new way of coloring nearly every tree mode creates more of a distraction and just looks trashy. I know there's people out there that like it, but there's other that don't. If anything, please add an option to where we can choose whether or not to have the coloring affect the tree.
> 
> Thanks.

Me, too! The new way of colouring doesn't look good and is a distraction. I don't know why this change but I suppose the devs looked for a way to mark the whole tree with a colour - before 7.1.0 only the connection name was coloured but when you scrolled further down, the expanded nodes were not coloured so it was not obvious which colour/connection they belonged to.

But I agree with you that the new way is not good. Perhaps a better way would be to leave the old colouring scheme and add a coloured vertical line along the whole height of a connection tree.

**Comment by serge-rider** [comment]
We changed the way we highlight connection types in 7.1.1

**Comment by eldarnegrinperion** [comment]
Thank you! 🥇

**Comment by uslss** [comment]
verified

**Comment by lemon-juice** [comment]
The new colouring style is excellent in 7.1.1, much appreciated!
