### ISSUE TITLE
Oracle wrong default numeric data type.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#8859]
All Oracle numeric data types are converted equally in NUMBER(22,0)
It should be:
DECIMAL -> NUMBER(38,0)
INTEGER -> NUMBER(38)
SMALLINT -> NUMBER(38)
![2020-06-01_14h22_07](https://user-images.githubusercontent.com/45152336/83412883-94792780-a423-11ea-9367-b369822d1b16.gif)
https://docs.oracle.com/cd/B28359_01/server.111/b28286/sql_elements001.htm#SQLRF00213

**Comment by serge-rider** [comment]
Fixed.
We will use default precision (38) instead of max length (22 bytes).

**Comment by uslss** [comment]
verified
