### ISSUE TITLE
SQL tools to tasks configuration (MySQL)

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#8861]
Turn tools into database tasks
Table Repair
Table Analyze
Table Optimize
Table Truncate

**Comment by kseniiaguzeeva** [comment]
Please see small issues:
1 task is not displayed in Database task panel if **Group tasks by category** is enabled in Database task panel
![1](https://user-images.githubusercontent.com/51405061/84255767-bc4f4600-ab1b-11ea-9952-09d21b0ef7a9.gif)

2 two popup task notifications appear after successful task execution (the same in Navigator tree tools)
![2](https://user-images.githubusercontent.com/51405061/84255786-c2ddbd80-ab1b-11ea-91ca-21e0f6842a69.gif)

3 in case of unsuccessful run, Success status is displayed
![3](https://user-images.githubusercontent.com/51405061/84255803-c8d39e80-ab1b-11ea-93d8-bd873c7fe81c.gif)

4 a whole schema can be selected, but cannot be analized, repaired,truncated
![4](https://user-images.githubusercontent.com/51405061/84255840-d557f700-ab1b-11ea-8628-afad3439211d.png)

5 tables are not checked if the tables folder has been checked
![5](https://user-images.githubusercontent.com/51405061/84255866-ddb03200-ab1b-11ea-8eb6-c5ee7ec51f01.gif)

6 up-down arrows of first/last objects in the list do not change the status to active / inactive when the object are moved to the opposite position  (the same in Navigator tree tools)
![6](https://user-images.githubusercontent.com/51405061/84255881-e274e600-ab1b-11ea-9179-ed5a4186cdcd.gif)

7 Should a task show status after execution like tools in DB NAvigator tree?
![7](https://user-images.githubusercontent.com/51405061/84255903-e99bf400-ab1b-11ea-9597-b048c17d1bef.png)

**Comment by kseniiaguzeeva** [comment]
Checked. New ticket for cl. 2 will be created
