### ISSUE TITLE
Can't use private key authentication for SSH tunneling in DBeaver 7.1.0 (from Snap Store)

### ISSUE THREAD

**Issue by bloopeti** [dbeaver/dbeaver#8863]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04.4 LTS
- Window manager: gdm3
- DBeaver version: 7.1.0.202005311732
- Additional extensions: - (fresh install from Snap Store)

#### Connection specification:
- Database name and version: PostgreSQL 9.1.24 (shouldn't matter according to repro steps)
- Driver name: PostgreSQL JDBC Driver (shouldn't matter according to repro steps)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : Trying to use SSH

#### Describe the problem you're observing:
I am unable to configure a database connection with an SSH tunnel using a private key as an authentication method. Any attempt gives an error message, as the application is unable to access the private key, as if it were running on a different user than the current one.

#### Steps to reproduce:
- Install DBeaver from the "Ubuntu Software" manager
- Open DBeaver
- Open "Connect to database" window
- Select "PostgreSQL"
- Swap to "SSH" tab
- Tick "Use SSH Tunnel" checkbox

- Change "Authentication Method" to "Public Key"
  - Try navigating to the current user's ".ssh" directory (/home/<curr_user>/.ssh) via the GUI tool at the right of the "Private Key" textbox
  - **Notice that an error popup appears saying "_Could not read contents of .ssh_ - _Error opening directory '<current users .ssh dir>': Permission denied_"**

OR

- Fill in the "Host/IP" and the "User Name" fields with valid values to which there is a private/public key pair configured
- Change "Authentication Method" to "Public Key"
  - Paste the path to the current user's private key (/home/<curr_user>/.ssh/id_rsa) into the "Private Key" textbox
  - Click the "Test Connection ..." button
  - **Notice that an error popup appears saying "_/home/<curr_user>/.ssh/id_rsa (Permission denied)_"**

**Comment by uslss** [comment]
Hi @bloopeti ,
sorry for the late response. is it still actual?

**Comment by pwaring** [comment]
I don't know about @bloopeti but I have also noticed this problem. I think the underlying issue might be that the Snap is confined (as all are by default unless they are 'classic' snaps), so any attempt to open a file (e.g. a private key) fails. If that's the case the Snap configuration might need to be updated to allow access to `$HOME`, as per the interface management documentation:

https://snapcraft.io/docs/interface-management

I suspect this might be the same problem that is causing #8864

**Comment by riednyko** [comment]
Snap never get access to dotfiles/directories and hidden files for safety.
We sent a request for permission to read such files/directories in the dbeaver snap package. While waiting for a response, to solve this problem, you can move the ssh key out of the /.ssh folder somewhere in homedir, or install the dbeaver-ce snap package using --devmode.

**Comment by uslss** [comment]
Verified

**Comment by JRRS1982** [comment]
Same issue here - but was not a snap install - error opening directory, permission denied error.
