### ISSUE TITLE
Creating multiple Tables in one session

### ISSUE THREAD

**Issue by Speirs47** [dbeaver/dbeaver#8865]
#### System information: 
- Operating system (distribution) and version openSUSE Leap 15.1
- DBeaver version 7.0.0 EE
- Additional extensions

#### Connection specification:
- Database name and version: MariaDB 10.2
- Driver name: mariadb-java-client-2.4.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)?:  SSH

#### Describe the problem you're observing:
When creating second table in a session I'm getting error "Constraint 'PRIMARY' already exists" when I'm trying to save it. If I restart DBeaver or reconnect and try creating exactly the same table it doesn't throw any error.

#### Steps to reproduce, if exist:
1. Create first table with one autoincrement, integer column and a constraint called PRIMARY for that column.
2. Save that table.
3. Create another table, again with one autoincrement, integer column and a constraint call PRIMARY for that column.
4. Try to save it
5. Result: Constraint 'PRIMARY' already exists

### Workarounds:
- restart DBeaver
- restart database connection

**Comment by uslss** [comment]
hi @Speirs47 ,
unfortunately, cannot reproduce it against 7.1.0 EA.
could you test if it works for you against ea version? (https://dbeaver.com/files/ea/)
Thanks in advance

**Comment by Speirs47** [comment]
Seems like it's somehow fixed in 7.1
