### ISSUE TITLE
wrong statement executed when line contains multiple statements

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#8868]
#### System information: 
- Operating system (distribution) and version: mac os latest
- DBeaver version: 7.1.0

#### Connection specification:
- Database name and version: pg 11.2, 12.2
- Driver name: default

#### Describe the problem you're observing:
having 2+ statements on the same line, pointer is on the 3rd or 4th, execute current statment using cmd+enter - the 2nd statement is being run instead of the one the pointer is at (see result in screenshot)
![image](https://user-images.githubusercontent.com/18515297/83543122-9a930500-a504-11ea-9eb7-0c49156496e5.png)

#### Steps to reproduce, if exist:
same as in screenshot

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed
@uslss please verify it on different queries

**Comment by uslss** [comment]
verified

**Comment by pyrocks** [comment]
confirmed - thanks!
