### ISSUE TITLE
Reserved keywords not being escaped on postgers 

### ISSUE THREAD

**Issue by jpssinning** [dbeaver/dbeaver#8870]
## System information: 
- Linux Mint 19.3 
- DBeaver 7.0.0.202003081756
- Java 1.8 

#### Connection specification:
- Database name and version: 12
- Driver name: Postgres
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Steps to reproduce, if exist:
create a new table on postgres using the GUI, if you name a column current_time, it will fail, the reason is current_time is reserved.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by LonwoLonwo** [comment]
fixed for keywords: CURRENT_TIME, CURRENT_DATE and CURRENT_TIMESTAMP.

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
Fixed in 7.1.1 DBeaver version
