### ISSUE TITLE
Dump/restore have disappeared from tools

### ISSUE THREAD

**Issue by silvershadowcc** [dbeaver/dbeaver#8871]
Reopening #7956 

Dump and restore are still gone in 7.1 from both right-click menu and Database top menu.

![afbeelding](https://user-images.githubusercontent.com/36823114/83570809-fe2e2a00-a526-11ea-9bc1-6566febe3274.png)

**Comment by serge-rider** [comment]
Thanks for the bug report.

Workaround: use database navigator tree context menu.

**Comment by silvershadowcc** [comment]
> 
> 
> Thanks for the bug report.
> 
> Workaround: use database navigator tree context menu.

That was fast :D 

I had just edited my initial comment to include that. If you mean the top menu that is.

**Comment by serge-rider** [comment]
I mean context menu on the left navigation tree: 
![image](https://user-images.githubusercontent.com/6398845/83572112-a47f2d00-a531-11ea-97cc-3d7250fc14c3.png)

**Comment by silvershadowcc** [comment]
Ah yes, there it is. Forgot to check that one. Thanks for the quick replies and fixing it.

@dreamlu We can use 7.1.1 soon :)

**Comment by purushottamnawale** [comment]
OS: Linux Ubuntu 22.04.3 LTS
DBeaver 23.3.0
Issue: Can't find the Restore/Dump Option on table. 

![Tools Backup](https://github.com/dbeaver/dbeaver/assets/96472310/2de2fc52-5375-4c73-94cc-0fd6065c92ba)

**Comment by fogbar** [comment]
> OS: Linux Ubuntu 22.04.3 LTS DBeaver 23.3.0 Issue: Can't find the Restore/Dump Option on table.
> 
> ![Tools Backup](https://private-user-images.githubusercontent.com/96472310/289456152-2de2fc52-5375-4c73-94cc-0fd6065c92ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDA0ODIsIm5iZiI6MTcyODU0MDE4MiwicGF0aCI6Ii85NjQ3MjMxMC8yODk0NTYxNTItMmRlMmZjNTItNTM3NS00YzczLTk0Y2MtMGZkNjA2NWM5MmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA2MDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MDdlNjlhYWM0NGRiYWJmYTM4MWFlOWZiY2FjNzUwMTM4MmI2OGIxNzM4MjhlNmE2MWI5MGJmOTYyYjgyODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qPRv68bwDi5UELhmjn0MRmitcKbWOfCROtr1-4On9_4)

Did you find Restore/Dump option on table?

**Comment by purushottamnawale** [comment]
@fogbar 
Export Data and Import Data now work like Dump/Restore.
