### ISSUE TITLE
Cannot list all DBs from a virtual MYSQL Server (by CData SQL GateWay) But Workbench Can

### ISSUE THREAD

**Issue by BillVSGitHub** [dbeaver/dbeaver#8873]
#### System information: 
- Operating system (distribution) and version: Win10 Updated
- DBeaver version Version 7.1.0.202005311732
- Additional extensions 

#### Connection specification:
- Database name and version MYSQL ( Virtual MYSQL Server by CData SQL Gateway latest version )
- Driver name mysql:mysql-connector-java:RELEASE
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
There two Databases in CData Gateway, `CData Acumatica Sys` and `INFORMATION_SCHEMA`.
But Dbeaver cannot list any database. 
In Creating Connection screen, we can put one database name, but it couldn't use  IntelliSense function because of no `INFORMATION_SCHEMA` database. 
However, Workbankch (6.3 64bit) it works fine, it can list all database and IntelliSense well.

**Comment by uslss** [comment]
hi @BillVSGitHub ,
do you have Show system objects enabled in connection property (F4)?
![image](https://user-images.githubusercontent.com/31996417/83644975-945f6000-a5ba-11ea-9c5a-92702b35d5f1.png)

**Comment by BillVSGitHub** [comment]
Hi There,

I appreciate the fast response,
Yes, that box has been ticked as default.

It could not list any database, but it can query the default database which is setup in the connection.

Thanks,

[cid:image002.png@01D63A04.541D60E0]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by kseniiaguzeeva** [comment]
Am I correct that you do not see available databases in DB Navigator tree? 
![dbeaver_qqWgyN3ZtM](https://user-images.githubusercontent.com/51405061/88267940-432a3d80-ccda-11ea-933f-f59875ec095e.png)
Doesn't SQL Assist function work in SQL Editor?
Does this issue still exist in 7.1.3 release https://dbeaver.io/download/?

**Comment by BillVSGitHub** [comment]
Yes,

It still does not work in 7.1.3 but workbench can for same CData server


[cid:image001.png@01D661E0.BE206150]

[cid:image002.png@01D661E1.0A136F30]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by kseniiaguzeeva** [comment]
Please send screenshot how your database looks now in DB Navigator tree

**Comment by uslss** [comment]
there are not any update on issue for a long time.
If issue is still actual for you - feel free to reopen the ticket with additional info that could help to investigate and reproduce an issue.
