### ISSUE TITLE
dbeaver

### ISSUE THREAD

**Issue by 416381012** [dbeaver/dbeaver#8874]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
quite strange ticket :)
if you have some issues, please create ticket with more info :)
BR

**Comment by 416381012** [comment]
ok, I'll do it
