### ISSUE TITLE
dbeaver use impala to import data into table meet Garbled words

### ISSUE THREAD

**Issue by 416381012** [dbeaver/dbeaver#8875]
#### System information: 
- macos 10.15.4
- Dbeaver 7.1.0.202005311732
- Additional extensions

#### Connection specification:
- Impala 3.2.0+cdh6.3.1
- com.cloudera.impala.jdbc41.Driver
- use Tunnelblick vpn 

#### Describe the problem you're observing:
I use utf8 csv file for data import, impala table is also utf8 encoding format.But the imported data will be partially garbled.

#### Steps to reproduce, if exist:

1. Select an Impala table and select the data import

2.use csv file, and import into this table

3.after import, you can see the imported data will be partially garbled.

#### Include any warning/errors/backtraces from the logs

I found the insertion code of dbeaver in the monitoring program of impala and found the problem.

data preview is ok
![image](https://user-images.githubusercontent.com/46945979/83607180-5a3b9180-a5ad-11ea-9851-8a4abd55b621.png)

then, Impala monitoring page sees the executed SQL statement
![image](https://user-images.githubusercontent.com/46945979/83607337-9bcc3c80-a5ad-11ea-90d1-f0d6e8e9ef5f.png)

last , the talbe's data is:
![image](https://user-images.githubusercontent.com/46945979/83607415-c6b69080-a5ad-11ea-8108-f3d664c6260c.png)

I like dbeaver, I'am waiting for you.

**Comment by 416381012** [comment]
We look forward to an early resolution of this matter :)

**Comment by LonwoLonwo** [comment]
Hello @416381012 

Could you please check the latest DBeaver version? We added some changes for default character recognition.

**Comment by 416381012** [comment]
the latest version is OK。thanks&nbsp;







------------------ Original ------------------
From: Anastasiya ***@***.***&gt;
Date: Mon,Oct 30,2023 10:49 PM
To: dbeaver/dbeaver ***@***.***&gt;
Cc: 王友俊 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [dbeaver/dbeaver] dbeaver use impala to import data into tablemeet Garbled words (#8875)





 
Hello @416381012
 
Could you please check the latest DBeaver version? We added some changes for default character recognition.

**Comment by LonwoLonwo** [comment]
Thaks for the update @416381012 !
