### ISSUE TITLE
Data filter autocomplete bug

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#8876]
Version 7.1.0
This does not happen with all tables.
![filterACFull](https://user-images.githubusercontent.com/3856344/83608702-f0f45800-a585-11ea-8b24-57deda6d8406.gif)

**Comment by uslss** [comment]
Hi @greenpeas ,
what database do you use?

**Comment by greenpeas** [comment]
Hi @uslss . PG.

**Comment by uslss** [comment]
Thanks for the clarification and bug report

**Comment by uslss** [comment]
verified
