### ISSUE TITLE
Export: no visible changes after enabling/disabling "Open new connection" option

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8879]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.0 EA

#### Describe the problem you're observing:
no visible changes after enabling/disabling "Open new connection" option in export settings

#### Steps to reproduce, if exist:

1. Open session manager for a database
2. Open export wizard for a table from this database
3. Enable "Open new connection" option
4. Export

Actual result: no visible changes
Expected: new connection appears in Session manager.

![ARK7Blj7ja](https://user-images.githubusercontent.com/51405061/83627719-0f674d00-a5a0-11ea-88d8-0e2da9e37d36.gif)

**Comment by serge-rider** [comment]
MongoDB doesn't support multiple connections. Please test on another (relational) database

**Comment by uslss** [comment]
Verified.
Works with postgreSQL
