### ISSUE TITLE
Table statistics won't redraw when scrolling horizontally

### ISSUE THREAD

**Issue by Z1ni** [dbeaver/dbeaver#8881]
#### System information: 
- Operating system (distribution) and version: Windows 10 1909 build 18363.836
- DBeaver version: 7.1.0.202005311732

#### Connection specification:
- Database name and version: PostgreSQL 9.6

#### Describe the problem you're observing:
The UI doesn't redraw the table statistics if the user scrolls the Database Navigator horizontally. The items are redrawn when hovered over with the cursor. The table names are updated correctly.
See: 
![image](https://user-images.githubusercontent.com/669686/83635670-4a23b200-a5ad-11ea-9c62-68896047067a.png)

#### Steps to reproduce, if exist:
1. Use narrow Database Navigator tab that doesn't fit the table statistics
2. Scroll the view horizontally

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
