### ISSUE TITLE
Pressing Ctrl+Backspace while typing in filter box removes the highlighted cell

### ISSUE THREAD

**Issue by MedicOP** [dbeaver/dbeaver#8887]
#### System information: 
- Windows 10
- DBeaver 7.1.0

#### Connection specification:
- MySQL

#### Describe the problem you're observing:
When you type in the filter box and you press Ctrl+Backspace, instead of deleting the text, it removes the highlighted cell in the data viewer.
![image](https://user-images.githubusercontent.com/18251099/83663186-cf689000-a5c8-11ea-8b78-a2bfa9000a78.png)

**Comment by uslss** [comment]
hi @MedicOP ,
unfortunately cannot reproduce an issue. Probably some special steps are needed?
![2020-06-04_19h10_10](https://user-images.githubusercontent.com/31996417/83781410-2d63a900-a697-11ea-9db2-e75cd5cd45a1.gif)

**Comment by MedicOP** [comment]
> hi @MedicOP ,
> unfortunately cannot reproduce an issue. Probably some special steps are needed?
> ![2020-06-04_19h10_10](https://user-images.githubusercontent.com/31996417/83781410-2d63a900-a697-11ea-9db2-e75cd5cd45a1.gif)

Hmm.. This happens for both me and my colleague on different machines. We both use Windows 10, maybe that's the common factor?

**Comment by uslss** [comment]
thanks for the bug report

**Comment by kseniiaguzeeva** [comment]
I can reproduce using following steps:

1. Open a table in default schema (e.g. Kseniia, sakila, table language4, language)
2. Select a cell and go to upper filter line
3. Press Ctrl+Backspace

Actual result: the cell data is set to default.

If you do not reach the actual result, continue:

4. Close the table
5. Set other schema as a default
6. Reopen the table
7. Select a cell and go to upper filter line
8. Press Ctrl+Backspace

Actual result: the cell data is set to default.

![lcrSlY7PJ4](https://user-images.githubusercontent.com/51405061/84241626-645b1400-ab08-11ea-9388-dc1e0cfde0ba.gif)

**Comment by LorisZ** [comment]
I have this problem now on 7.1.1, but when writing sql in the editor. Any Ctrl+backspace while writing sql will delete the currently selected cell in the result editor.

Currently using Windows 10, can't say I remember this happening on Kubuntu (that I was using yesterday).

**Comment by serge-rider** [comment]
I've fixed focus tracker service usage. Hopefully it will resolve the problem.

**Comment by kseniiaguzeeva** [comment]
Still can be reproduced using steps above. Build 7.1.1.202006241010

**Comment by serge-rider** [comment]
Extra fix added (problem with context activation)

**Comment by uslss** [comment]
verified
