### ISSUE TITLE
PostgreSQL extension management

### ISSUE THREAD

**Issue by sgrinko** [dbeaver/dbeaver#889]
We need fully-functional PostgreSQL extension.
this command CREATE EXTENSION ...
1. added into treeview "System info"new item with name 'Extensions'
2. implement an option button to hide/show the objects associated with extensions. Default offer this activate button.
Sample:
extension - dblink, creates a lot of functions beginning with the name of dblink_*
if such extensions a lot (I have 13), then manually hide all the objects from the list of functions is very tedious.
to obtain a list of such functions and filter it is possible that a request:

```
WITH extension_deps AS (
    SELECT dep.objid 
    FROM pg_catalog.pg_depend dep 
    WHERE refclassid = 'pg_extension'::regclass 
        AND dep.deptype = 'e'
)
SELECT p.proname
FROM pg_catalog.pg_proc p
LEFT JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
WHERE p.oid NOT IN (SELECT objid FROM extension_deps)
  AND n.nspname = 'public'
```

**Comment by serge-rider** [comment]
For now you can use object filters with masks (dblink_*). 
Integrating filters model with PG extensions is not easy.

**Comment by sgrinko** [comment]
I understand that it's not easy.
But the need is integration.
Manually set very tiring.

**Comment by uslss** [comment]
Already implemented
![image](https://user-images.githubusercontent.com/31996417/140029267-123c0d6a-7c23-4159-b124-4fc1b03d9841.png)
