### ISSUE TITLE
TRUNCATE as function

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#8892]
In SQL-editor in Oracle/db2/firebird and may be other database management systems TRUNCATE is offered like function. 
TRUNCATE() function works in MySQL db, but not in Oracle/db2/firebird
![2020-06-04 14_40_03-DBeaver 7 1 0 - _Oracle - XE_ Script-15](https://user-images.githubusercontent.com/45152336/83753287-adc3e300-a672-11ea-8eaa-a5c4dd571694.png)

**Comment by LonwoLonwo** [comment]
Truncate as a function from FireBird, Oracle and DB2 removed

**Comment by uslss** [comment]
verified
