### ISSUE TITLE
How to disable table alias autocomplete

### ISSUE THREAD

**Issue by shootingfly** [dbeaver/dbeaver#8894]
#### System information: 
- Operating system (distribution) and version
MacOS
- DBeaver version
7.1.0

#### Connection specification:
- Database name and version
MySQL

#### Describe your question:
How to disable table alias autocomplete?

**Comment by shootingfly** [comment]
Can we disabled it by default? It annoying and stupid.

**Comment by zachtidwelldc** [comment]
In the new interface: Editors -> SQL Editor -> Code Completion -> Insert table aliases (in FROM clause): N/A
![Screenshot 2024-10-30 at 11 43 24 AM (2)](https://github.com/user-attachments/assets/0bcde8c8-663d-41fa-b26e-eae3f79816ff)

**Comment by kwaki01** [comment]
DBeaver 24.3.2 not work

**Comment by GrabsOrion** [comment]
@kwaki01 try Completion mode -> Default (the setting is on the same screen as shown above).
