### ISSUE TITLE
Import CSV file with true/false column

### ISSUE THREAD

**Issue by ryan-boder** [dbeaver/dbeaver#8897]
#### System information: 
- OSX 10.15.4
- DBeaver Version 7.0.5.202005171753

#### Connection specification:
- MariaDB 10.1.44-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04

#### Describe your question:
I'm importing a lot of CSV files. Often they have a boolean column with values such as true/false. MariaDB uses tinyint for booleans. Is there a way for DBeaver to recognize the true/false values during the import and convert then to 1/0 for the tinyint column?

**Comment by uslss** [comment]
Unfortunately, it is nor supported by CSV driver that is used. You could try some third-party drivers
