### ISSUE TITLE
Support For YugabyteDB Distributed SQL Database

### ISSUE THREAD

**Issue by nchandrappa** [dbeaver/dbeaver#8898]
**Is your feature request related to a problem? Please describe.**
Please support the YugabyteDB Distributed SQL database in DBeaver. 

**Describe the solution you'd like**
YugabyteDB supports ANSI SQL, fully-relational geo-distributed SQL with PostgreSQL compatibility. As we continue to bring the PostgreSQL features into geo-distributed SQL, we will need to only enable DBeaver PostgreSQL features that are currently supported by YugabyteDB. As part of the this solution, we will configure a Yugabyte Specific JDBC Datasource. 

**Describe alternatives you've considered**
We have tried creating a custom driver definition of type "PostgreSQL", by default PostgreSQL driver uses `postgres` user and `postgres` database, however, Default user and database for YugabyteDB is `yugabyte`. Additionally, we have to disable PostgreSQL features like `MaterializedViews` which are yet to be enabled in YugabyteDB.

**Comment by serge-rider** [comment]
Please see comments in #8899

**Comment by serge-rider** [comment]
Done in #8899

**Comment by uslss** [comment]
Incorrect logo size in connection create dialog
![image](https://user-images.githubusercontent.com/31996417/84877711-8406b500-b091-11ea-8551-09536cd29fd3.png)

**Comment by serge-rider** [comment]
@nchandrappa could you fix logo icon. Max dimensions are about 300x100.

**Comment by nchandrappa** [comment]
Sorry folks, I didn't see the comment. I'll update the logo with the correct dimensions and revert back. Thanks.

**Comment by nchandrappa** [comment]
I've submitted a PR to fix this - #9090 .

**Comment by serge-rider** [comment]
@nchandrappa Thanks!

Moving t oQA
