### ISSUE TITLE
Find by column name in Data viewer

### ISSUE THREAD

**Issue by LendLord** [dbeaver/dbeaver#8901]
**Is your feature request related to a problem? Please describe.**
Very hard to find column on big tables(many columns), so I need to scroll through columns until find needed. 

**Describe the solution you'd like**
Find/Replace also work for columns in table view mode like with text view mode and row view mode.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by LonwoLonwo** [comment]
Hey @LendLord 
You can try to use the "Search item(s)" field or Ctrl+F.

![2021-07-27 13_10_36-DBeaver Enterprise 21 1 4 - Track](https://user-images.githubusercontent.com/45152336/127137402-2dcac47e-1c9f-45ad-8a88-82c2349295b7.png)

**Comment by LendLord** [comment]
@LonwoLonwo I need such feature when viewing table data, not table columns.

**Comment by E1izabeth** [comment]
Duplicate of #3052
