### ISSUE TITLE
Wrap SQL with Custom Text?

### ISSUE THREAD

**Issue by pokdbz** [dbeaver/dbeaver#8902]
Can you wrap text around each line in a SQL statement like below using a feature in dbeaver?
Statement:
select 
    sales
from sales_table

Result I'm looking for:
SQL + SQL = "select"
SQL + SQL = "    sales"
SQL + SQL = "from sales_table"

**Comment by uslss** [comment]
Hi @pokdbz ,
if I catch you correctly, you could use Copy SQL as Source Code, If you need some special format, please create feature request
![image](https://user-images.githubusercontent.com/31996417/88385133-7641ff00-cdb6-11ea-8515-641d3aab100d.png)
