### ISSUE TITLE
dbeaver hangs while trying to open previous tab with .erd that is deleted

### ISSUE THREAD

**Issue by AMassani** [dbeaver/dbeaver#8908]
#### System information: 
- Operating system (distribution) and version - Windows 10 Enterprise
- DBeaver version - 7.0 Enterprise
- Additional extensions
None

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Dbeaver hangs on startup and never recovers...

#### Steps to reproduce, if exist:
 Create a new ERD diagram and save the file.
Left the tab with .erd file open and closed the dbeaver application
Delete the .erd file
Open dbeaver, notice you will see the erd tab and blocked UI.

**Comment by uslss** [comment]
Hi @AMassani ,
unfortunately cannot reproduce it. Could you try if it reproducible for you against 7.1?

**Comment by uslss** [comment]
there is not any update on issue for a long time. Ticket is closed.
If issue is still actual for you - feel free to reopen the issue with additional info

**Comment by pbysh** [comment]
For what its worth, this exact same thing just happened to me in 7.1.0. I had to go delete the workbench.xmi file to be able to get back into DBeaver. I had an ERD I created in DBeaver and had subsequently deleted. Got hung trying to open that tab.
