### ISSUE TITLE
Shouldn't "Use SQL to limit fetch size" be the default? 

### ISSUE THREAD

**Issue by mshindal** [dbeaver/dbeaver#8909]
**Is your feature request related to a problem? Please describe.**

Opening a huge data set (millions of rows) will always cause DBeaver to hang without this option enabled. 

**Describe the solution you'd like**

Enable the "Use SQL to limit fetch size" option by default. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by p91paul** [comment]
Usually fetch size is set at the driver level. Some drivers do not honor it, so this option adds an explicit LIMIT clause to the query.
But modifying user queries is bad and most databases work fine even on huge tables without this option, hence the fact it's not default behavior. 

Also, when it's supported, default behavior might have better performance.

**Comment by serge-rider** [comment]
Although @p91paul is absolutely right we still can enable this option by default for some databases.

@mshindal What database do you use?

**Comment by mshindal** [comment]
It’s a Redshift database.

**Comment by tnatssb** [comment]
How do we know which drivers support this? For example, in Presto/Trino, with this option on, it doesn't add the limit and issues a cancel to the cluster.

**Comment by uslss** [comment]
duplicates #1936
