### ISSUE TITLE
DBeaver not creating a table alias after adding a JOIN clause in SELECT query

### ISSUE THREAD

**Issue by MuqadderIqbal** [dbeaver/dbeaver#8912]
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version: Version 7.1.0.202005311732
- Additional extensions: None

#### Connection specification:
- Database name and version: MySQL 5.7.19
- Driver name: mysql:mysql-connector-java
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
DBeaver doesn't auto-create table alias for the second (or any subsequent) table in a JOIN clause. The auto-alias for first table in the select query shows up fine.

#### Steps to reproduce, if exist:
Write a script like below. Dbeaver will automatically create the alias "a" because of auto-complete. However, as soon as you add tableB after an inner join, it does not create alias "b" automatically. You have to type in all subsequent aliases manually.

Select * from tableA a
inner join tableB b
on a.column = b.column

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
Fixed in 7.1.1

**Comment by LonwoLonwo** [comment]
Hello, @MuqadderIqbal. Version 7.1.1 will be available on 22.06.2020

**Comment by MuqadderIqbal** [comment]
@LonwoLonwo thank you for the quick resolution! Much appreciated.

**Comment by MuqadderIqbal** [comment]
Verified as fixed in 7.1.1. There's another bug I found but I'll log a separate issue.

**Comment by LonwoLonwo** [comment]
@MuqadderIqbal ok
