### ISSUE TITLE
Add quotes on CSV import with single quotes (PostgreSQL)

### ISSUE THREAD

**Issue by mdbraber** [dbeaver/dbeaver#8913]
#### System information: 
- Operating system (distribution) and version
macOS Catalina 10.15.5

- DBeaver version
7.0.5.202005171753
#### Connection specification:
- Database name and version
PostgresQL v11

- Driver name
org.PostgreSQL:postgresql:RELEASE[42.2.5] driver

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
I've got a CSV file with the fields: `id;text`. The text field sometimes contains a single quote (`'`) e.g. `James' bike` which is not quoted or escaped. When trying to import this .csv the SQL INSERT chokes on the input because it uses single quotes in the insert query and therefore generates an unbalanced quote. 

If possible there should be an option to use dollar quotes or another option to circumvent insert issues. Or am I missing something here that could fix this?

**Comment by uslss** [comment]
Hi, @mdbraber ,
probably importer settings could solve your problem?
![image](https://user-images.githubusercontent.com/31996417/84017784-d35d2f00-a987-11ea-81c3-c83933c63ad8.png)

**Comment by mdbraber** [comment]
@uslss no I already tried those, but not with this input, I've tried removing quote and escape characters but no dice (also makes sense that this wouldn't change).I don't want to change the input, but rather how imports are handled, which also would make more sense right?

**Comment by uslss** [comment]
@mdbraber could you provide table ddl and csv sample?
Thanks in advance

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Ticket closed. If issue is still actual for you - feel free to reopen the ticket with additional info.

**Comment by dmotte** [comment]
Hey there, I also had this problem.

- OS: **Ubuntu 20.04 LTS**
- DBeaver version: **22.2.5**
- Database: **MySQL 5**
- Do you use tunnels or proxies: **no**

These are the steps to reproduce it:

1. Create an **empty table** using this statement:
   ```sql
   CREATE TABLE inventory (
       name varchar(100),
       descr varchar(200)
   );
   ```
2. Create a **CSV file** with this content:
   ```csv
   name;descr
   my-keyboard;This is my keyboard
   johns-keyboard;This is John's keyboard
   my-chair;This is my chair
   claras-chair;This is Clara's chair
   guest-chair;This chair is for guests
   ```
3. Right click on the table &rarr; **Import Data**
   ![0](https://user-images.githubusercontent.com/37443982/204331936-2a44c057-7c5e-4a59-bbb1-047ebecec184.png)
4. Import using these settings:
   ![0](https://user-images.githubusercontent.com/37443982/204332530-ebf7ebd9-5794-4b1d-a651-5806f14d4ea4.png)
5. The result for me is the following:
   ![0](https://user-images.githubusercontent.com/37443982/204332645-aa8d1e59-d81a-41ed-b273-7017b1ab3af2.png)

As you can see, the final result is not what you expect.

Hope this helps :wink:

**Comment by itsavy** [comment]
Works by putting  \'  in "Escape character" field which retains those single quotes after import
