### ISSUE TITLE
SQL tools to tasks configuration (Oracle)

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#8920]
Turn tools into database tasks

**Comment by uslss** [comment]
when tools are executed as tasks, final screen (pic attached) isn't shown, so this isn't clear if task executed without error
![image](https://user-images.githubusercontent.com/31996417/84790636-3e4add80-affa-11ea-98b4-b572fed989a9.png)

**Comment by uslss** [comment]
Materialized view couldn't be refreshed

```
Error opening task 'ttttt' configuration editor

Reason:
class org.jkiss.dbeaver.ext.oracle.model.OracleTable cannot be cast to class org.jkiss.dbeaver.ext.oracle.model.OracleMaterializedView (org.jkiss.dbeaver.ext.oracle.model.OracleTable and org.jkiss.dbeaver.ext.oracle.model.OracleMaterializedView are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5562e3ae)
```
![2020-06-17_12h49_09](https://user-images.githubusercontent.com/31996417/84885337-938afb80-b09b-11ea-94a6-1dc0eb7a698b.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
