### ISSUE TITLE
[Eclipse plugin] Connection couldn't be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8921]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1 EE eclipse plugin
Eclipse Version: 2020-03 

#### Describe the problem you're observing:
The connection couldn't be established using ee plugin for eclipse. 
![image](https://user-images.githubusercontent.com/31996417/84050944-1b477a80-a9b7-11ea-8ce1-94473b1f19bb.png)

**Comment by serge-rider** [comment]
Fixed
You need a fresh version of Eclipse to install this update again.

**Comment by uslss** [comment]
verified
