### ISSUE TITLE
Tables filter in Database Navigator messed up after table altering

### ISSUE THREAD

**Issue by MebsSystem** [dbeaver/dbeaver#8924]
#### System information: 
- OSX 10.15.4
- 7.1.0 CE

#### Connection specification:
- Firebird 2.5
- org.firebirdsql.jdbc.FBDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - No

#### Describe the problem you're observing:
After saving changes on table with applied filter in Database Navigator program switches to the table which is in the same position but without filters.

#### Steps to reproduce, if exist:
Apply filter on table tree by right click>Filter>Configure "Tables" filter.
IMPORTANT - Filter should remove few first tables from tree.
Double click on some table, go to properties, add some column and click save.
Program will switch to the different table which is in the same position but without filter.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

(Steps to reproduce:
1.Apply filter for C%, D%, E% Firefox tables
2. Double click NEWTABLE in DB Navigator
3. Add a column in the table
4. Save the table changes.)

Actual result: the table in opened Data Editor and in DB Navigator tree was change on COUNTRY (the first in DB Navigator before the filter was applied)

![s26Bvas7su](https://user-images.githubusercontent.com/51405061/84132760-edae1000-aa4e-11ea-97c1-27b65999d9b3.gif)

**Comment by MebsSystem** [comment]
So this bug will not be fixed?

**Comment by kseniiaguzeeva** [comment]
The bug will be fixed, but not in 7.1.2

**Comment by uslss** [comment]
not reproducible in 21.0.3
