### ISSUE TITLE
Allow for setting option for dumping large object for PostgreSQL

### ISSUE THREAD

**Issue by djeison-integritas** [dbeaver/dbeaver#8931]
**Is your feature request related to a problem? Please describe.**
When executing a dump from a PostgreSQL database, large objects (text column values) are not exported.

**Describe the solution you'd like**
UI allow for setting the '-b' flag for exporting blob values, as per PostgreSQL docs:
https://www.postgresql.org/docs/9.6/app-pgdump.html

**Comment by uslss** [comment]
Hi, @djeison-integritas ,
could you try if setting flag in the highlighted field resolves your problem?
![image](https://user-images.githubusercontent.com/31996417/84168052-a12ef880-aa7f-11ea-8c5b-e1687337eb4e.png)

**Comment by djeison-integritas** [comment]
Oh I didn't notice that field.
It works now! Thanks a lot!
