### ISSUE TITLE
Skip/Ignore duplicate primary key errors in CSV import

### ISSUE THREAD

**Issue by ryan-boder** [dbeaver/dbeaver#8932]
#### System information: 
- OSX 10.15.4
- DBeaver Version 7.1.0.202005311732

#### Connection specification:
- MariaDB 

#### Describe your question:

I have to do periodic imports from CSV files. There isn't a convenient way for me to get CSV files that only have new records since the last time I did an import. If I import CSV files with some existing records (overlap) and then choose to Ignore the duplicate primary key error when it pops up during the import, will that ignore **all** errors or only duplicate primary key errors?

I'd still like to see other errors if they occur, such as bad data. I just want to ignore duplicate primary key errors.

**Comment by LonwoLonwo** [comment]
Dbeever uses batches when importing to speed up the process. Therefore, one error is shown for the entire batch. You can choose line-by-line import in import settings by putting 1 in the item: "Do commit after row insert". Then errors will be shown for each line. Use the skip after the first error to see all possible errors.
![2020-09-02 16_19_59-Data Transfer](https://user-images.githubusercontent.com/45152336/91989204-e8541f00-ed38-11ea-96d1-4bc65f270529.png)

**Comment by LonwoLonwo** [comment]
Now, if you want to control the import and all possible import errors line by line, then you can use the function of disabling batches in the import settings
![2020-09-04 17_31_14-Data Transfer](https://user-images.githubusercontent.com/45152336/92250715-7a445f00-eed4-11ea-9221-774ff9651872.png)

**Comment by uslss** [comment]
verified
