### ISSUE TITLE
Julian time not converted and displayed correctly in SQLite database

### ISSUE THREAD

**Issue by dmbr0** [dbeaver/dbeaver#8933]
#### System information: 
- Windows 10
- DBeaver Version 7.1.0.202005311732

#### Connection specification:
- sqlite

#### Describe your question:

I have a DATETIME column in an SQLite database that has the date saved in Julian time. The date time formatting does not change the number to be displayed as a normal date and time.

How do I make the column display the Julian time in a "normal" date time format?

Julian time that is displayed in the column: 2458634.1802860997

Desired Display:
5-30-2019               month-day-year
30/5/2019/16/19/36.72      day/month/year/hour/minute/second

**Comment by uslss** [comment]
Seems that it isn't connected to DBeaver. Please check SQLite documentation.
Best regards

**Comment by dmbr0** [comment]
When I open the database with Lita the date and time are displayed correctly
