### ISSUE TITLE
Very long-running queries make the tool unresponsive

### ISSUE THREAD

**Issue by ldhasson** [dbeaver/dbeaver#8935]
#### System information: 
- Windows 10, patched and current as of 2020-06
- DBeaver 7.1
- Additional extensions: none

#### Connection specification:
- localhost Postgres V11
 - vanilla settings

#### Describe the problem you're observing:
When running a very long query (> 1h), the counter keeps running but nothing can be canceled. There seems to be a timeout and the only way out is to restart DBeaver. Same query from PGAdmin or the local command line pgsql completes. I have repeated this issue in a number of environments, on Linux, on PG12 etc...

#### Steps to reproduce, if exist:
Create a very long running query such as commonly used for complex data warehouse. I haven't really played around to find when the timing breaks but it's more than 20mn and less than 45mn.

#### Include any warning/errors/backtraces from the logs
None... the timer keeps going, cancel is unresponsive, only way out is to restart DBeaver.

**Comment by serge-rider** [comment]
Can't reproduce with something dummy like `select pg_sleep(10000)`.
There are no any explicit socket timeouts in DBeaver. There is socketTimeout property in the driver settings but it is set to zero (=disabled) by default.

Do you use standalone dbeaver or Eclipse plugin?

**Comment by ldhasson** [comment]
Standalone DBeaver.

So pg_sleep(10000) does sleep for almost 3h (166mn) right? Let me see if I can replicate on my end.

Thank you,
Laurent.

**Comment by ldhasson** [comment]
Hello,

Some additional info: I tried the pg_sleep(60*60) on my local machine (DBeaver standalone against a local instance of Postgres) and it worked. However, when connecting to a remote postgres instance (on another server), then the same query hangs: the counter keeps going forever, and when pressing the "cancel" button, it greys out and then nothing happens. Only terminating DBeaver will help. See the attached picture to see how it had been going for 80mn before i hit the cancel button.

![image](https://user-images.githubusercontent.com/410503/86318946-42354d00-bc01-11ea-851d-c9def40de011.png)

I understand that this scenario adds a network layer, and another database, which in all honesty, could be misconfigured somehow compared to my local database. But the same query from the command line psql utility on the machine completes after 60mn. So something is going on, i am pretty sure, on the DBeaver side.

I am willing to get a debug build of some kind on my machine to do some additional testing that may bring some light to that issue if you are willing to go that route.

Thank you,
Laurent.

**Comment by christopher-bonitz** [comment]
I were going to add a ticket for this as well, only I'm working on MSSQL.
In my case a delete query whom would take roughly 5 minutes (exected it in managment studio instead) will time out the client.

I can see the connection disappear on the server, so for the purpose of keeping my findings aligned to this ticket I ran the following query.
`   WAITFOR DELAY '00:01'`
Same effect, the connection disapears on the server after 10+ seconds.
Client think its still running, and will not stop without my manual intervention.
![image](https://user-images.githubusercontent.com/20163098/86793617-edb02880-c06b-11ea-886e-bbe3c4d098cf.png)

I guess its network related as well.

**Comment by lmacedo-pivotal** [comment]
I see the same behavior for DBeaver 7.1.2 on MacOS with Greenplum Database. The DB is on Google Cloud. For short queries there is no problem but for long-running it gets lost and keep counting time even if it finished on the DB end.

**Comment by serge-rider** [comment]
This may happen when connection with database is lost  and database driver cannot determine that socket is already dead.
It is often happens when you use some proxy socket (SSH or VPN).
Many SSH servers close client sockets after some idle timeout. This is very problematic for synchronous database connection sockets.

Anyhow.
1. If you use SSH tunnel - try to set SSH keep-alive timeout (60 seconds is good enough timeout)
1. I'll try to add some client-side solution for hanging queries canceling. It will resolve problem with client UI hanging but it won't resolve the original problem (dying database connection sockets).

**Comment by ldhasson** [comment]
Yep, I understand the issue. Fyi that in my case, it was a direct connection from one server to another: no ssh or anything like that.

That being said, DBeaver should guard against that because it does happen and when it does, DBeaver locks up completely :)


Sent from my BlackBerry - the most secure mobile device

**Comment by serge-rider** [comment]
Extra cancel handler added

**Comment by christopher-bonitz** [comment]
> 
> 
> This may happen when connection with database is lost and database driver cannot determine that socket is already dead.
> It is often happens when you use some proxy socket (SSH or VPN).
> Many SSH servers close client sockets after some idle timeout. This is very problematic for synchronous database connection sockets.
> 
> Anyhow.
> 
>     1. If you use SSH tunnel - try to set SSH keep-alive timeout (60 seconds is good enough timeout)
> 
>     2. I'll try to add some client-side solution for hanging queries canceling. It will resolve problem with client UI hanging but it won't resolve the original problem (dying database connection sockets).

I were indeed on VPN to the host, I recently had the opportunity to test the theory, by running a few similar queries through Sql Management Studio. Who had similar behavior. (Although reconnecting fine after roughly 15 seconds)

Thanks for the extra cancel handler, it sounds like the right solution.

**Comment by uslss** [comment]
verified
