### ISSUE TITLE
(View) Source editor has now autocomplete

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#8937]
Double click on a view in database navigator, go to source.Type something: auto-complete is on.
This is a new feature, which (*please* guys) is activated by default, changing a "default" behiavour, and that has causes already some troubles.
This might apply to other objects.

*Please* do not enable new features by dafault guys :-)

**Comment by serge-rider** [comment]
We usually don't. But this was done by another feature request.
