### ISSUE TITLE
View Source Editor now does not show table schema names anymore

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#8938]
Schema names of source tables are not shown anymore in Views DDL.
Previously

```
FROM schema.table
```

now

```
FROM table
```

**Comment by serge-rider** [comment]
What is your database?

**Comment by wiwwo** [comment]
Postgresql 11, latest.

**Comment by serge-rider** [comment]
We read view definition from server (using `pg_get_viewdef`).
As far as I see it uses FQ names only if schema is not the search_path. Anyway, we can't affect this behavior from dbeaver side.

**Comment by wiwwo** [comment]
Just to be on the same page: this behiavour changed in latest release(s)
