### ISSUE TITLE
Unable to connect to remote Oracle database after upgrade to 7.1.0

### ISSUE THREAD

**Issue by raqua** [dbeaver/dbeaver#8940]
#### System information: 
- Operating system (distribution) and version: Linux Mint 18.3
- DBeaver version: 7.1.0
- Additional extensions

#### Connection specification:
- Database name and version: Oracle 12c Standard Edition, 12.1.0.2.0, 64bit
- Driver name: Oracle JDBC driver 12.2.0.1.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I can not connect to remote databases after upgrade to 7.1.0 from 6.3.3. After downgrade, the same connections work again. Only remote connections (access over VPN) do not work, local connections work. After fiddling with connection settings, it is possible to connect again until next DBeaver restart. 

#### Steps to reproduce, if exist:
- Set up remote connection in old version and ensure it works
- Upgrade to 7.1.0
- Try to connect to remote DB and observe that connection will timeout (attached log fail_to_connect)

Second attempt after restart (see attached log success.txt) 
- start DBeaver again
- go to 'Edit connection' dialog
- click 'Test connection' - it will not coonect and I have cancelled it (IO Error: Operation interrupted in logs)
- Click 'Edit Driver Settings' 
- Strange error appears in logs (Error reading Oracle client version from /usr/lib/jvm/java-13-openjdk-amd64/bin/sqlplus -version
java.io.IOException: Cannot run program "/usr/lib/jvm/java-13-openjdk-amd64/bin/sqlplus": error=2, No such file or directory)
- click through the four tabs in the middle of the dialog
- close the dialog
- click 'Test Connection' again, this time it succeeds and it is possible to connect to remote database until next DBeaver restart. 

#### Include any warning/errors/backtraces from the logs

[fail_to_connect.txt](https://github.com/dbeaver/dbeaver/files/4759000/fail_to_connect.txt)
[success.txt](https://github.com/dbeaver/dbeaver/files/4759006/success.txt)

**Comment by uslss** [comment]
Unfortunately, cannot reproduce it for now. Is it still actual for you against recent version?
Thanks in advance for response

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Ticket closed. If issue is still actual for you - feel free to reopen the ticket with additional info.

**Comment by raqua** [comment]
Sorry for late reply, life and vacations got in the way. I still have the same issue with 7.1.5. I would love to provide additional info, but I do not know what info. If you have anything in your mind, please let me know.
