### ISSUE TITLE
Add missing keywords to autocomplete for Snowflake

### ISSUE THREAD

**Issue by hubertwimmer** [dbeaver/dbeaver#8941]
**The following keywords for snowflake are missing (autocompletion does not work)**
- ilike 
- qualify 
- organization
- gscluster

I never used organization or gscluster, but the first two are used very often.

Link to complete snowflake keyword list:
https://docs.snowflake.com/en/sql-reference/reserved-keywords.html

**Comment by LonwoLonwo** [comment]
@hubertwimmer hi, do you have more information about using keywords "gscluster" ore "organization"? Are these functions or keywords? I found disappointingly few information about them

**Comment by LonwoLonwo** [comment]
"qualify" added, "ilike" we have already

**Comment by hubertwimmer** [comment]
Can you please double check "ilike" because the syntax highlighting for it is not working in dBeaver 7.1.0 (and as far i can remember also not in all versions before).

And i also couldn't find out more about "gscluster" and "organization". Maybe you skip them for this issue. If i can find out more i can create another request. Ok?

**Comment by LonwoLonwo** [comment]
@hubertwimmer ok, "ILIKE" added. 

>  If i can find out more i can create another request. Ok?

sounds like a great plan

**Comment by kseniiaguzeeva** [comment]
Tested 'qualify' and 'ILIKE'. Please create new feature requests for 2 others.

**Comment by LonwoLonwo** [comment]
Fixed in version 7.1.3
