### ISSUE TITLE
Teradata JDBC Connection with "Data Source DNS Entries" parameter

### ISSUE THREAD

**Issue by robb-randall** [dbeaver/dbeaver#8943]
#### System information: 
Operating System: Windows 10
DBeaver Version: 7.1.0.202005311732
Teradata JDBC Driver Version: 16.10.00.07
Teradata Database Version: 16.20.32.21

#### Connection specification:
```jdbc:teradata://{host}/DATABASE={database},DBS_PORT={port},ENCRYPTDATA=ON,LOGMECH=LDAP,Data Source DNS Entries=18```

#### Describe your question:
When attempting to connect with Teradata's JDBC connection with the "Data Source DNS Entries" our connection fails with:
```[Teradata JDBC Driver] [TeraJDBC 16.10.00.07] [Error 1536] [SQLState HY000] Invalid connection parameter name Data Source DNS Entries```

According to Teradata's documentation ([here](https://docs.teradata.com/reader/pk_W2JQRhJlg28QI7p0n8Q/KS1ls~9~o0aOc5T3xQhhrw)) the parameter is correct.  And when we try the same settings in Teradata Assistance it connects.  Also, older versions of the TD JDBC driver it worked as well.

Has anyone encountered this issue before?  And if so what did you do to fix it?

**Comment by kseniiaguzeeva** [comment]
Why did you use such URL, could you please recheck it?

**Comment by uslss** [comment]
there are not any update on issue for a long time.
If issue is still actual for you - feel free to reopen the ticket with additional info that could help to investigate and reproduce an issue.
