### ISSUE TITLE
Displayed units for table sizes are incorrect and confusing

### ISSUE THREAD

**Issue by rwarren** [dbeaver/dbeaver#8944]
This is a simple UI issue
Seen on DBeaver 7.1.0.202005311732

----
When displaying table sizes in the "Tables" treeview, or in the table Statistics, the displayed units are incorrect and extremely confusing For example, here is a small screencap of the treeview display.

![image](https://user-images.githubusercontent.com/2751728/84308538-b150e180-ab2c-11ea-9b16-208dbe9a42a6.png)

This is wrong in a few ways. Of note:

* the correct symbol for bytes is `B` (not `b`, which is bits, or a factor of 8x different)
* the correct symbol for the 1000x multiplier is `k`, _not_ `K` (`K` is technically a Kelvin unit)
* the correct symbol for the 1024x binary multiplier is `Ki`
* All DBeaver values are reporting as binary values, and the correct prefixes should be used accordingly
    * if a table is taking 1024 bytes on disk, this would be `1 KiB` (_not_ `1 Kb` as it shows now)
    * I should also add that I wish DBeaver didn't report binary units, but the more straightforward powers of 10 (ie. 1024 bytes would reports as `1.024 kB`, if reporting 4 digits of precision)

For convenience, the correct way to report binary multipliers (if that is what you continue to do, vs reporting powers of 10) is as follows:

* `2^10 bytes = 1 KiB = 1024^1 bytes`
* `2^20 bytes = 1 MiB = 1024^2 bytes`
* `2^30 bytes = 1 GiB = 1024^3 bytes`
* `2^40 bytes = 1 TiB = 1024^4 bytes`
* `2^50 bytes = 1 PiB = 1024^5 bytes`
* `2^60 bytes = 1 EiB = 1024^6 bytes`

See https://en.wikipedia.org/wiki/Binary_prefix for further reference.

This issue might seem like a niggly detail. but details matter. The `b` vs `B` is particularly bad. Proper binary prefixes is less of an issue (SO many things get that misleadingly wrong), but precision would be appreciated in DBeaver.

**Comment by kseniiaguzeeva** [comment]
Changes will be made in 7.1.5 release

**Comment by serge-rider** [comment]
I'd wish to keep unit names as short as possible. As they consume very deficit space in the right side of database navigator.
We use 1024 multipliers always.

I think, we could just remove confusing `b` at all leaving just K,M,G,T,P,E modifiers. 
Moreover, since 7.1.4 we show exact size on bytes in the tooltip.
WDYT?

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
