### ISSUE TITLE
SecretKeyFactory not available when trying to use private_key_file

### ISSUE THREAD

**Issue by joshuataylor** [dbeaver/dbeaver#8946]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04
- DBeaver version 7.1.0
- Additional extensions

#### Connection specification:
- Database name and version: Snowflake
- Driver name 3
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

To use Snowflake with RSA, you need to add `private_key_path` and `private_key_file_pwd`. This however does not work with DBeaver.

#### Steps to reproduce, if exist:
1. Add snowflake
2. In driver properties, sue the following:
`private_key_file` -> `/home/you/key.p8`
`private_key_file_pwd` -> `mypwd`
3. Test connection, then see below:

#### Include any warning/errors/backtraces from the logs

```
Private key provided is invalid or not supported: /home/josh/mykey.p8: 1.2.840.113549.1.5.13 SecretKeyFactory not available
```

**Comment by uslss** [comment]
thanks for the bug report

**Comment by clayheaton** [comment]
This is a bug with the underlying Java library, I believe. This Snowflake help page describes a work around:

https://community.snowflake.com/s/article/Private-key-provided-is-invalid-or-not-supported-rsa-key-p8--data-isn-t-an-object-ID

**Comment by LonwoLonwo** [comment]
DBeaver PRO versions support private key authentication:

![2023-09-04 13_31_36-DBeaver Ultimate 23 2 0 - OUTPUT_MESSAGE2(ENV VARCHAR)](https://github.com/dbeaver/dbeaver/assets/45152336/58302c57-a6b2-46b3-8268-5c8ab8719188)

Or you can try to use a workaround with extra libraries from this message: https://github.com/dbeaver/dbeaver/issues/8946#issuecomment-837243524
