### ISSUE TITLE
When connecting to embedded H2 database file, database is deleted.

### ISSUE THREAD

**Issue by ronenmalka** [dbeaver/dbeaver#8948]
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version : 7.1.0.202005311732
- Additional extensions : none

#### Connection specification:
- Database name and version: h2  - 1.4.1999
- Driver name: org.h2.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  N/A

#### Describe the problem you're observing:
When connecting to embedded H2 database file, database is deleted.
I'm using the following JDBC URL: jdbc:h2:c:/temp/db/config;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE

#### Steps to reproduce, if exist:

1. Place an H2 file in the file system
2. Create a connection with the following setup:
![image](https://user-images.githubusercontent.com/47978855/84354408-8072ba00-abc9-11ea-93dd-86d51cc151e0.png)
3. Click on Test (or just try to connect)

All data from database is gone! The database is empty as it was just initiated. 

I think this behavior started 2-3 version ago.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Can't reproduce.
Note: when you connect to H2 db you need to specify database name, not directory name. 
In your case there should be a file `config.mv.db` in folder `c:/temp/db/`.

This is not obvious but this is how H2 driver works..

**Comment by heatzync** [comment]
We also experienced this issue with H2, but DBeaver wasn't part of the picture.

We managed to reproduce the issue using version `1.4.199` of H2 with a backup of the H2 database files.

When using version `1.4.200` of H2 to open the same backed up H2 database file, the issue wasn't reproduced, i.e., the database was **not** deleted.
