### ISSUE TITLE
[PostgreSQL] Data type comment is missing from DDL.

### ISSUE THREAD

**Issue by cpburnz** [dbeaver/dbeaver#8953]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04 64-bit
- DBeaver version: 7.1.0.202006031642
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgreSQL 9.1 and 9.4.7
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

The DDL for the data type comment is not displayed under the "Source" tab.

#### Steps to reproduce, if exist:

Create a data type with a comment.

```sql
CREATE TYPE test_type AS ENUM ('a');

COMMENT ON TYPE test_type is 'Some description.';
```

The DDL for the data type will be shown as:

```sql
-- DROP TYPE test_type;

CREATE TYPE test_type AS ENUM (
	'a');
```

The comment is missing. There should be a line for the comment as:

```sql
COMMENT ON TYPE public.test_type IS 'Some description.';
```

**Comment by uslss** [comment]
thanks for the bug report

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by greenpeas** [comment]
@kseniiaguzeeva, comments for columns in DDL verified too? 7.1.2 - there are no comments in DDL.

**Comment by kseniiaguzeeva** [comment]
@greenpeas No, only comment for type was verified. Could you please create a new ticket?

**Comment by greenpeas** [comment]
@kseniiaguzeeva ok
