### ISSUE TITLE
The option in settings to set and save default value for CRS (SRID)

### ISSUE THREAD

**Issue by sergtop** [dbeaver/dbeaver#8955]
**Is your feature request related to a problem? Please describe.**
I do a query to get the resultset, then click on the geo-field and have to set SRID to a value I want to have. As long as I keep the application open it is set as needed. On the application relaunch, I have to set SRID again.

**Describe the solution you'd like**
I`d like to have an option for Connection\Database\Table\Field to set SRID either globally for the application or per object (at any level: Connection \ Database \ Table \ Field).

**Describe alternatives you've considered**
A checkbox like "Set this SRID as default globally" in a popup window to set SRID

**Additional context**

**Comment by uslss** [comment]
thanks for suggestion

**Comment by djagar** [comment]
This simple feature (or a workaround to it) would really enhance the geo functionality and I am missing it for a very long time.

**Comment by djagar** [comment]
Alternatively, is there a way to add an arbitrary SRID (e.g. 900913 which is currently not recognized) to the CRS List?

**Comment by uslss** [comment]
implemented in 21.2.4
![image](https://user-images.githubusercontent.com/31996417/140048197-b336d0cb-e805-4c46-933a-5872d3fe2ff5.png)
