### ISSUE TITLE
duplicate Table !!   Vertica 7.3.1+DBeaver7.1 used cmd【COMMENT ON COLUMN】

### ISSUE THREAD

**Issue by Kerry0527** [dbeaver/dbeaver#8956]
#### Connection specification:
- Vertica 9.3.1 CE
- vertica-jdbc-9.3.1-0.jar

#### Describe the problem you're observing:
used cmd【COMMENT ON COLUMN】,  
maintain Column comment , it's OK, but duplicate Table in Table Lists

#### Steps to reproduce, if exist:
Step1：
Create Schema：TEST
Step2：
run code

> create table if not exists TEST.TEST ( 
> A varchar(10)  not null,
> B varchar(20)  ,
> primary key ( A ) ); 
> COMMENT ON TABLE TEST.TEST IS 'TEST'; 
> COMMENT ON COLUMN TEST.TEST.A IS 'A';  
> COMMENT ON COLUMN TEST.TEST.B IS 'B';  

Step3:
Refresh Schema\Tables
Table【Test】has 3 items，Bug reproduce

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it on Vertica 10. The table is created according the code. Could you please send a picture what is wrong with the created table?

**Comment by Kerry0527** [comment]
Hi kseniiaguzeeva,
 Thank you for your reply,  [https://imgtu.com/i/6PNrRg](url)

**Comment by Kerry0527** [comment]
> I cannot reproduce it on Vertica 10. The table is created according the code. Could you please send a picture what is wrong with the created table?

Hi kseniiaguzeeva,
Thank you for your reply,  pls follow this pic, https://imgtu.com/i/6PNrRg

**Comment by uslss** [comment]
Still cannot reproduce it. 
![image](https://user-images.githubusercontent.com/31996417/110757213-3142de00-825c-11eb-9f17-e7da749456cb.png)
@Kerry0527 what dbeaver version and OS do you use?

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you - feel free to reopen it
