### ISSUE TITLE
Where is the maven log output?

### ISSUE THREAD

**Issue by sworisbreathing** [dbeaver/dbeaver#8957]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro
- DBeaver version: 7.1.0.202005311732

#### Connection specification:
- Database name and version: N/A

#### Describe your question:
I'm trying to download/update a JDBC driver with Maven, from the driver manager in DBeaver, but it just says "Error resolving dependencies" with no stack trace or any further useful information. I'd like to open a new issue, but before I do I want to troubleshoot from the log output.

I've checked `.log` and `dbeaver-debug.log` but there's nothing in either of them in relation to maven, driver updates, et cetera.

So, if the maven output isn't in these logs, where is it?

**Comment by kseniiaguzeeva** [comment]
Possible the needed driver cannot be found. You will be able to find more information in debug and error log in 7.1.4 release (03.08.20). 
Please write whether the problem will be found or not.

**Comment by uslss** [comment]
there are not any update on issue for a long time.
If issue is still actual for you - feel free to reopen the ticket with additional info that could help to investigate and reproduce an issue.

**Comment by sworisbreathing** [comment]
@uslss I don't seem to have the ability to reopen this ticket. Can you please do it for me?

@kseniiaguzeeva apologies for not replying - this one seems to have slipped through the cracks. My specific issue in raising this ticket was that I can't _find_ the maven output, and that it wasn't in the debug/error log in 7.1.0. Are you saying that maven output _is_ in these logs in 7.1.4?

**Comment by uslss** [comment]
@sworisbreathing ,
unfortunately, logging was broken in 7.1.0 version. Could you check if it available in 7.2.0 and provide it?
Thanks in advance

**Comment by uslss** [comment]
there aren't any updates for a long time.
Issue closed. If it is still actual for you - feel fee to reopen it
