### ISSUE TITLE
PostgreSQL 11 Partition DDL is improper

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#8964]
#### System information: 
- Operating system (distribution) and version: Windows Server 2016 Datacenter 64-bit
- DBeaver version: 7.1.0.202005311732
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11 on Aurora RDS
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When generating a partition DDL it should be:

CREATE TABLE [partition_name] **PARTITION OF [main_table]** 
(with an optional subpartition clause PARTITION BY ... ([column_name]))

Instead we get:
CREATE TABLE [partition_name] (
**empty columns definition**
) PARTITION BY LIST ([column_name])

#### Steps to reproduce, if exist:
Run this SQL:
CREATE TABLE x (id1 numeric,id2 numeric) PARTITION BY RANGE (id1);
CREATE TABLE x_1_5 PARTITION OF x FOR VALUES FROM (1) TO (5) PARTITION BY list (id2);

In Database Navigator, right click on partition "x_1_5" under "x" table and "Generate SQL"->"DDL"

--------------------------------------------------------------------------------------------------------------
**Note:** It would be nice also to have a checkboxed option in the DDL window called "Generate as independent table" to have the original columns definition without the "PARTITION OF [table_name]" clause

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
verified
