### ISSUE TITLE
Tool tasks are not displayed in Database task panel if tasks are grouped by category and other Mysql tasks do not exist

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8965]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.1 EA

#### Describe the problem you're observing:
Tool tasks are not displayed in Database task panel if **Group tasks by category** is enabled in Database task panel and other Mysql tasks do not exist (Dump, Restore, Script)

Precondition: Mysql Dump, Restore, Script tasks do not exist.
Steps:
1. Create a tool Mysql task (truncate, analyze etc)
2. Group tasks by category in Task panel

Actual result: task(s) disappears
Expected: The task is placed in MySQL category.

Note:
When you create Mysql Dump, Restore, Script task, then group by category, tool MySQL tasks are visible and sorted too.
![1](https://user-images.githubusercontent.com/51405061/84589442-2a0ab300-ae37-11ea-89cb-ba198656aabf.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
