### ISSUE TITLE
Table structure in Database Navigator doesn't refresh from the specific table node

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#8967]
#### System information: 
- Operating system (distribution) and version: Windows Server 2016 Datacenter 64-bit
- DBeaver version: 7.1.0.202005311732
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11 on Aurora RDS
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Trying to refresh only a specific table from the table node in order to see new partition structure after DDL, but the structure only really refreshes from the "Tables" node menu

#### Steps to reproduce, if exist:
Right click [table name] node -> "Refresh" -> nothing happens behind the scenes.
Right click "Tables" node -> "Refresh" -> all tables are refreshed in tree (but takes too long since I have thousands of partitions across schema).

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
cannot reproduce against 7.3.4
