### ISSUE TITLE
Task wizard: tables/scripts are not checked if the tables folder/schema has been checked

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8969]
#### System information: 
- Operating system (distribution) and version Win 10
- DBeaver version 7.1.1 EA

#### Describe the problem you're observing:
Tables are not checked if the tables folder/schema has been checked

#### Steps to reproduce, if exist:
1. Open Task Wizard
2. Select task type SQL Script/MySQL tools
3. Select a schema/tables folder in step Table parameters (for MySQL tools) or Scripts folder (SQL Script)

Expected: Tables/Scripts are checked inside of schema/tables folder.
Actual result: Tables/Scripts are not checked inside of schema/tables folder.
![dbeaver_lc7MtY2ELG](https://user-images.githubusercontent.com/51405061/84592170-4cf39200-ae4c-11ea-9545-52b4c2e4439d.png)

**Comment by flambchap** [comment]
Duplicates #5564
