### ISSUE TITLE
Tools Wizard: Up-down arrows of first/last objects in the list do not change on active/inactive

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#8970]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.1 EA

#### Describe the problem you're observing:

Tools Wizard: Up-down arrows of first/last objects in the list do not change the status to active / inactive when the object moves to the opposite position

Steps:
1. Open tools wizard via DB Navigator or task panel
2. Add several objects in first step
3. Move first object down using arrow on the right

Expected: Down arrow becomes inactive and Up arrow becomes active when the object reaches the end of the list

Actual result: Down arrow is still active, and Up arrow is not active.

![YVA9w3uFbx](https://user-images.githubusercontent.com/51405061/84592358-df486580-ae4d-11ea-9e51-26ba922aec5c.gif)

**P.S. the smallest addition:**
Add Script/Remove script is written in popup of Tools wizard, but really Add Table/Remove Table should be written
![5JPovtCgi4](https://user-images.githubusercontent.com/51405061/84592476-9e9d1c00-ae4e-11ea-99fc-3b9eb03a90de.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
