### ISSUE TITLE
Unable to create Oracle TNS connection

### ISSUE THREAD

**Issue by NekoKoneko** [dbeaver/dbeaver#8971]
#### System information: 
- Windows 10 x64 2004
- DBeaver 7.1.0
- No additional extensions

#### Connection specification:
- Oracle 11.2.0.4
- Driver version: 19.6.0.0
- Direct connection

#### Describe the problem you're observing:

Unable to create Oracle connection with TNS type - both Test Connection and Finish buttons do nothing and `Unhandled event loop exception` entries appear in the error log.

#### Steps to reproduce, if exist:

1. Open New Database Connection dialog.
2. Select Oracle database and press the Next button.
3. Select TNS connection type.
4. Browse to the TNS names path folder.
5. Choose the desired network alias.
6. Keep the Database Native authentication and type user name and password.
7. Press Test Connection or Finish button.
8. The window stays open and `Unhandled event loop exception` entry appears in the error log.

[ErrorLog.txt](https://github.com/dbeaver/dbeaver/files/4778730/ErrorLog.txt)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
This should be fixed in 18ad74b081b1c93e329636b0aeed785d87236488
Tthe problem was in empty databame during TNS search.

**Comment by NekoKoneko** [comment]
Thanks, it's OK now!
