### ISSUE TITLE
Show Indexes in Oracle Connections

### ISSUE THREAD

**Issue by simasch** [dbeaver/dbeaver#8975]
Indexes are not shown when the connection is to an Oracle database.

As I can see from the code there is no implementation for collecting and displaying indexes.

Indexes are accessible from ALL_INDEXES and its columns from ALL_IND_COLUMNS

**Comment by uslss** [comment]
thanks for suggestion

**Comment by simasch** [comment]
If you don't mind I could try to implement this feature and provide a pull request. But it will take me some time.

**Comment by serge-rider** [comment]
We already show indexes for individual tables.
Is this FR about showing all schema indexes (or even all database indexes)?

**Comment by simasch** [comment]
I'm sorry for beeing inexact. 

The request is about showing all indexes for a schema like Tables, Views etc.
