### ISSUE TITLE
SQL tools to tasks configuration (SQL Server)

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#8976]
Turn tools into database tasks
Triggers enable/disable
Rebuild table index(s)

**Comment by kseniiaguzeeva** [comment]
1 Tree node does not have a database name
Steps:
1. Open a task wizard
2. Go to SQL Server tools

Actual result: word **tools** is tree node for SQL Server tools
Expected: word **SQL Server** is tree node for SQL Server tools. Tools menu is under it
![1](https://user-images.githubusercontent.com/51405061/84887852-0ba6f080-b09f-11ea-86df-023fc0b84ec5.png)

2 Please correct SQL Server name
3 It is impossible to select an object for enable/disable trigger tools. Separate ticket is created https://github.com/dbeaver/dbeaver/issues/8974

**Comment by kseniiaguzeeva** [comment]
1,2 - verified
