### ISSUE TITLE
zeros getting truncated while exporting into CSV

### ISSUE THREAD

**Issue by shkpendy** [dbeaver/dbeaver#8979]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version : 7.1.0

#### Connection specification:
- Database name and version: Vertica 9.2x

#### Describe your question:
I'm trying to export the result set from DBeaver into CSV, the column data type is varchar. 
My requirement is, it should not truncate the leading zeros.

Column data:
50044
06789
34-6778

CSV data:
50044
6789 (0 got eliminated)
34-6778

Settings used while exporting:
![image](https://user-images.githubusercontent.com/66988915/84736147-cd3c0380-afc2-11ea-8cf9-555ed7ba74fe.png)

![image](https://user-images.githubusercontent.com/66988915/84736197-ef358600-afc2-11ea-85e0-2a2e56c073b1.png)

**Comment by shkpendy** [comment]
HI,

Can someone comment on this issue?

**Comment by Matvey16** [comment]
@shkpendy Hello. Is that still reproducible for you. I was not able to reproduce this behavior

**Comment by uslss** [comment]
There have been no updates on the issue for a long time.
If it is still actual - feel free to reopen it with additional info
