### ISSUE TITLE
0000-00-00 date is displayed as NULL

### ISSUE THREAD

**Issue by thombou** [dbeaver/dbeaver#8980]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro
- DBeaver version: 7.1.0
- Additional extensions : None

#### Connection specification:
- Database name and version: Mysql
- Driver name: mysql5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Similar issue as #7974 but I was not able to reopen it. the date "0000-00-00"is shown as NULL in DBeaver and not in PhpMyAdmin.
However those entries appear in a query like `SELECT * FROM mytable WHERE date IS NOT NULL`.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by thombou** [comment]
Can you reproduce the bug? In #7974 , yo usaid that you could the with the version you had at that time.

**Comment by serge-rider** [comment]
@thombou Try to set "Use native date/time format" in the data formatting settings:
![image](https://user-images.githubusercontent.com/6398845/84859165-4300a780-b075-11ea-913c-c8c886abb374.png)

**Comment by thombou** [comment]
@serge-rider It is already the case in my settings. This is what I have.

![image](https://user-images.githubusercontent.com/22955852/84871363-b9ef6d80-b080-11ea-9bcf-bd196ef6dec3.png)

**Comment by thombou** [comment]
Any new on that @serge-rider ?

**Comment by chuck-wood** [comment]
Can confirm I'm having this issue on 7.2 as well. I also don't have the "Result Sets" section in my connection properties, I have "Data Editor" in that spot :|

**Comment by sirtet** [comment]
I am running into this too, Win10 64bit dBeaver 7.2.3.202010181902 on a Mysql DB.

PS: 
The issue-title "considered" is wrong in my opinion, because it is _displayed as_, but not _interpreted as_ in a command, aka
`WHERE my_row = 0 ` and `WHERE my_row IS NULL` give me different resultsets, the dilplay value is just always NULL.

**Comment by thombou** [comment]
> PS:
> The issue-title "considered" is wrong in my opinion, because it is _displayed as_, but not _interpreted as_ in a command, aka
> `WHERE my_row = 0 ` and `WHERE my_row IS NULL` give me different resultsets, the dilplay value is just always NULL.

I took that into account and updated the title

**Comment by sirtet** [comment]
This seems to be a common issue and not really solvable as it comes from the mysql driver, if i correctly understand #1127.
If so, that's a complete showstopper for me if i can't visually distinguish 0000-date values from NULL.

**Comment by brki** [comment]
For info, it seems to me that in DBeaver 24.x (current version as of today), setting the option "Disable date/time formatting" under either the global or connection-specific settings "Data Editor" -> "Date Formats" lets you distinguish the the 0000-00-00 and null datetimes.

For example, with that setting, here is what I see when selecting from a timestamp column with a valid timestamp, a null value, and '0000-00-00':

```
2024-09-02 09:09:43.0
[NULL]
0000-00-00 00:00:00
```
