### ISSUE TITLE
Result tab does not show data

### ISSUE THREAD

**Issue by Nashev** [dbeaver/dbeaver#8982]
#### System information: 
- Operating system (distribution) and version: Windows 10 Home
- DBeaver version 7.1
- Additional extensions
[DBeaver System Configuration.txt](https://github.com/dbeaver/dbeaver/files/4785667/DBeaver.System.Configuration.txt)

#### Connection specification:
- Postgre SQL 9.6
- Driver name org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I see that query is executed, having a number of returned rows, but can't see these rows!

![image](https://user-images.githubusercontent.com/190140/84755308-2c514680-afca-11ea-8a0e-87b38b9239f4.png)

This problem I have seen in a previous version, and see again after updating.
I'm not sure it is was in a previous version from the time when I have installed it.

#### Steps to reproduce, if exist:
Connect to PostgreSQL database, open script window, write select command, execute them

#### Include any warning/errors/backtraces from the logs
[log.txt](https://github.com/dbeaver/dbeaver/files/4785641/log.txt)

**Comment by uslss** [comment]
hi @Nashev ,
unfortunately cannot reproduce it. Is it appears for postgresql 9.6v. only?

**Comment by uslss** [comment]
there aren't any updates on the issue for a long time.
Ticket closed.
If it is still actual for you, feel free to reopen the ticket

**Comment by bergesl1221** [comment]
The problem is that you forgot to put an asterisk (*) after SELECT.  Say SELECT * FROM...
