### ISSUE TITLE
"Column not found: value" error when generating Snowflake SP DDL script

### ISSUE THREAD

**Issue by demetrioi** [dbeaver/dbeaver#8983]
#### System information: 
- Operating system (distribution) and version: Windows 10.0.18363 N/A Build 18363. X64
- DBeaver version: Version 7.1.0.202005311732
- Additional extensions

#### Connection specification:
- Database name and version: Snowflake 4.20.3
- Driver name: Snowflake
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No 

#### Describe the problem you're observing:

I got the error: "Column not found: value" when I'm trying to extract stored procedure scripts from the IDE if the Procedure name is quoted like "SP_Name".

#### Steps to reproduce, if exist:
1 - Create both SPs:

CREATE or replace PROCEDURE DEMO_DB.DBO.proc1(id float)
RETURNS VARCHAR
LANGUAGE javascript
AS
$$
var rs = snowflake.execute( { sqlText: 
  `select current_version() ;`
   } );
return 'Done.';
insrtExec.next();
return rs.getColumnValue(1);
$$;
/
CREATE or replace PROCEDURE DEMO_DB.DBO."proc_1"(id float)
RETURNS VARCHAR
LANGUAGE javascript
AS
$$
var rs = snowflake.execute( { sqlText: 
  `select current_version() ;`
   } );
return 'Done.';
insrtExec.next();
return rs.getColumnValue(1);
$$;

The go to the SPs, right click / Generate SQL / DDL
![Not Working](https://user-images.githubusercontent.com/10916434/84766024-6e7d8680-afd0-11ea-9ad6-ee64f0c88bb2.PNG)
![Working](https://user-images.githubusercontent.com/10916434/84766027-6f161d00-afd0-11ea-9e6e-f51ca5069a42.PNG)

**Comment by LonwoLonwo** [comment]
Can't reproduce in 7.2.2
![2020-10-14 10_25_06-Window](https://user-images.githubusercontent.com/45152336/95956888-9efef100-0e07-11eb-8fd1-c96ca5e9df66.png)
@demetrioi it is still actual for you?

**Comment by uslss** [comment]
there are not any updates for a long time
Issue is closed.
If it is still actual for you - feel free to reopen it

**Comment by flambchap** [comment]
We have a customer with a similar issue.

**Comment by LonwoLonwo** [comment]
Close the ticket again due to the lack of response from the user.
