### ISSUE TITLE
Informix 11.7 View Schema's use Connection Database instead of Selected Database

### ISSUE THREAD

**Issue by nomadno** [dbeaver/dbeaver#8986]
#### System information:
- Operating system (distribution) and version:  Windows 10 Pro (1909)
- DBeaver version:  7.0.0.202002292132
- Java version:  Java SE Version 7 Update 55 (build 1.7.0_55-b14)
- Additional extensions

#### Connection specification:
- Database name and version:  Informix Dynamic Server 11.70.FC7
- Driver name:  IBM Informix JDBC Driver for IBM Informix Dynamic Server 3.70.JC2DE
- Do you use tunnels or proxies (SSH, SOCKS, etc)?:  Not through DBeaver - IPSec and L2TP

#### Steps to reproduce, if exist:
1 - Create a connection to an Informix database which hosts more than one database and share the same view names but have different Definitions (Create SQL commands).
2 - Open the database which is not in the database connection string and expand the Schema > Views and right-click on the view to test and select View View.
3 - Change the display to Definition to view the SQL Create definition.

The Definition displayed is that for the database/schema in the connection string.  Changing the connection string Database/Schema to another database results in that Definition being displayed.

This was seen on a production database which had nearly identical schemas across all of the databases.  When selecting a view which is not in the connection string's Database/Schema but is in another database viewable through DBeaver, then the Definition display is blank.

No errors were seen.

**Comment by michbudz** [comment]
I confirm this problem.
I have reported a similar problem [issue 8572](https://github.com/dbeaver/dbeaver/issues/8572)

**Comment by uslss** [comment]
thanks for the bug report
Sorry for the late response

**Comment by LonwoLonwo** [comment]
The solution to this problem can be considered a solution from this problem: https://github.com/dbeaver/dbeaver/issues/8987
so i close this ticket as duplicate.
