### ISSUE TITLE
Version control property visibility

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#9000]
One general class for checking version control
and particular version control for PostgreSQL Vacuum Tool

**Comment by LonwoLonwo** [comment]
it works for PostgreSQL Vacuum Tool options: SKIP_LOCKED, INDEX_CLEANUP, TRUNCATE since 12 PostreSQL version, and for DISABLE_PAGE_SKIPPING since 9.6 PostreSQL version

**Comment by uslss** [comment]
verified
