### ISSUE TITLE
ONS configuration failed

### ISSUE THREAD

**Issue by GTmAster** [dbeaver/dbeaver#9002]
#### System information: 
- Operating system (distribution) and version: Windows Server 2016 Datacenter
- DBeaver version: 7.1.0.202005311732
- Java version: Version 8 Update 251

#### Connection specification:
- Database name and version: Oracle
- Driver name: Oracle, 12.2.0.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

After latest update I can't connect to Oracle database anymore. After trying to connect for ~30sec connection failing with error: 
```
Unexpected driver error occurred while connecting  to the database
    ONS configuration failed
    ONS configuration failed
        Subscription time out
```

Oracle SQL Developer portable works completely fine on this machine without any problems.

#### Include any warning/errors/backtraces from the logs
Debug log:
```
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.600.v20200116-2127]
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.900.v20200213-1442]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.200.v20200127-0814]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF Common [org.eclipse.emf.common 2.18.0.v20191225-1014]
> Start EMF Ecore [org.eclipse.emf.ecore 2.21.0.v20200127-1342]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.800.v20200128-0855]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.800.v20191212-1231]
> Start Expression Language [org.eclipse.core.expressions 3.6.700.v20200212-1751]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.1100.v20200217-1217]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.12.800.v20191216-0805]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.15.500.v20200106-1259]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.900.v20200203-0840]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.12.600.v20200124-0005]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.49.202005311732]
> Start Help System Core [org.eclipse.help 3.8.700.v20191212-1123]
> Start Equinox Provisioning Core [org.eclipse.equinox.p2.core 2.6.300.v20200211-1504]
> Start Equinox Provisioning Operations API [org.eclipse.equinox.p2.operations 2.5.700.v20191211-1713]
> Start Equinox Provisioning Platform Automatic Update Support [org.eclipse.equinox.p2.ui.sdk.scheduler 1.4.600.v20200221-0754]
> Start Equinox Provisioning Update Checker [org.eclipse.equinox.p2.updatechecker 1.2.300.v20200222-1600]
> Start Equinox Provisioning Metadata [org.eclipse.equinox.p2.metadata 2.4.700.v20191213-1911]
> Start Equinox Provisioning Engine [org.eclipse.equinox.p2.engine 2.6.600.v20200110-2121]
> Start Equinox Provisioning Metadata Repository [org.eclipse.equinox.p2.metadata.repository 1.3.400.v20191211-1528]
> Start Equinox Provisioning Repository [org.eclipse.equinox.p2.repository 2.4.700.v20200110-2121]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.24.202005311732]
> Start Equinox Provisioning UI Support [org.eclipse.equinox.p2.ui 2.5.800.v20200213-1530]
> Start Default Text Editor [org.eclipse.ui.editors 3.13.100.v20200130-1507]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.14.100.v20200212-1049]
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.34.202005311732]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.34.202005311732]
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.34.202005311732]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.71.202005311732]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.40.202005311732]
> Start DBeaver ER Diagram [org.jkiss.dbeaver.ext.erd 2.0.136.202005311732]
> Start File Buffers [org.eclipse.core.filebuffers 3.6.900.v20200117-0616]
> Start DBeaver UI Editors - Connections [org.jkiss.dbeaver.ui.editors.connection 1.0.25.202005311732]
> Start DBeaver Oracle UI [org.jkiss.dbeaver.ext.oracle.ui 1.0.21.202005311732]
> Start DBeaver Oracle Support [org.jkiss.dbeaver.ext.oracle 2.1.119.202005311732]
> Start Java Native Access [com.sun.jna 4.5.1.v20190425-1842]
> Start DBeaver SSH tunnels [org.jkiss.dbeaver.net.ssh.ui 1.0.55.202005311732]
> Start DBeaver SSH tunnels [org.jkiss.dbeaver.net.ssh 1.0.55.202005311732]
> Start Team Support Core [org.eclipse.team.core 3.8.900.v20200211-0946]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.500.v20200114-1637]
Jun 17, 2020 5:09:08 PM oracle.simplefan.impl.FanManager configure
SEVERE: attempt to configure ONS in FanManager failed with oracle.ons.NoServersAvailable: Subscription time out
Jun 17, 2020 5:20:11 PM oracle.simplefan.impl.FanManager configure
SEVERE: attempt to configure ONS in FanManager failed with oracle.ons.NoServersAvailable: Subscription time out
```

**Comment by GTmAster** [comment]
Downgrade to jdbc7 helped.

**Comment by p91paul** [comment]
This happens to me every now and then with a specific server. I'm able to fix it with those steps:

1. Open connection properties
2. Click "Test connection"
3. Stop the test *before* it times out
4. Test again
5. It works!

It then continues to work for weeks. When the problem happens again, I just repeat the steps above.

**Comment by afimuc** [comment]
I'm having the same problem with DBeaver 7.1.1 and it happens all the time. Thank p91paul for the workaround, it was driving me mad.
This really seems to be a DBeaver bug.

**Comment by p91paul** [comment]
It happens to me only on a very specific db instance, I have dozen others where this never happens. So I think it might be server side, or both. Very strange though, especially the workaround is somewhat crazy.

**Comment by Simbamoureux** [comment]
I'm having the exact same issue except the workaround proposed by @p91paul doesn't work for me.

I'm also using a SSH tunnel

**Comment by luturol** [comment]
I'm currently using dbeaver 7.1.2 and had the same issue. The solution from @p91paul solved for me.

@Simbamoureux try to update to 7.1.2 or try to edit connections and then test the connection again.

**Comment by mikkk3l** [comment]
Still occurs in version 7.1.3. The workaround proposed by @p91paul works but I prefer reverting to version 7.0.0 which is more stable in my opinion.

**Comment by marin-h** [comment]
The workaround @p91paul proposed works! I tried downgrading until 7.0.2 with no success. Using MacOS catalina.

**Comment by serdarmutlu** [comment]
Thanks @p91paul, I spent 2 hours trying to solve issue until I met your workaround.

**Comment by claudiobalbin** [comment]
The workaround from @p91paul didn't work for me.
I'm also using a SSH tunnel like @Simbamoureux .
Any news on this?

**Comment by claudiobalbin** [comment]
I think I have worked it out.

1. Edit Connection
2. Edit Driver Settings
3. Select jdbc and click in "Download/Update"
4. Click on jdbc Version column, change to **19.7.0.0** and click Download, then OK

Hope it helps.

**Comment by Simbamoureux** [comment]
@claudiobalbin Updating to 7.1.3 allowed me to use the workaround. Will give a go to your fix.

**Comment by serdarmutlu** [comment]
@claudiobalbin 's solution to upgrade drivers was permanent fix for me.

**Comment by DetourToNirvana** [comment]
@claudiobalbin 's solution of Updating the jdbc version to v19.7.0.0 resolved this issue permanently for me. Attaching screenshot for clarity on where to change it.

<img width="1342" alt="Screenshot 2020-08-07 at 5 57 20 PM" src="https://user-images.githubusercontent.com/876603/89645645-d5843100-d8d7-11ea-8de3-b0724dc51780.png">

**Comment by lorenzomartinelli** [comment]
Set:
-Doracle.jdbc.fanEnabled=false

https://support.oracle.com/epmos/faces/DocumentDisplay?_afrLoop=99525057147918&parent=EXTERNAL_SEARCH&sourceId=PROBLEM&id=2308193.1&_afrWindowMode=0&_adf.ctrl-state=g3tq88y1z_53

In dbeaver Database / Driver Manager select Oracle and define the connection properties oracle.jdbc.fanEnabled and set to false

**Comment by serge-rider** [comment]
We will set `oracle.jdbc.fanEnabled` to false by default after 7.2.3.
DBeaver doesn't use this capability anyway.

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/95853239-bf727100-0d5d-11eb-9afc-23419dbf6a5b.png)

**Comment by marinhoysmael** [comment]
> This happens to me every now and then with a specific server. I'm able to fix it with those steps:
> 
> 1. Open connection properties
> 2. Click "Test connection"
> 3. Stop the test _before_ it times out
> 4. Test again
> 5. It works!
> 
> It then continues to work for weeks. When the problem happens again, I just repeat the steps above.

woooowww, congratulations... this magic saved my day
