### ISSUE TITLE
Success status is displayed for MySQL,DB2 tool task if a table, mentioned in the task, is deleted

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9010]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.1.1 EA
- MySQL

Success status is displayed for MySQL tool task if a table, mentioned in the task, is deleted

Steps:
1. Create a MySQL tool task for an eisted table (e.g. Kseniia.MyISAM_4)
2. Execute the task
3. Delete the table
4. Execute the task again using btn on Database Task Panel.

Expected: status **Error** appears is the task status (on the right of Database Task Panel)
Actual result: status **Success** is displayed in the task status (on the right of Database Task Panel)

**Comment by kseniiaguzeeva** [comment]
Actual for DB2 too.

**Comment by uslss** [comment]
verified
