### ISSUE TITLE
PostgreSQL INTERVAL type wrong schema migration script generated

### ISSUE THREAD

**Issue by AlexeyAG** [dbeaver/dbeaver#9013]
#### System information: 
- **Windows 10 x64**
- DBeaver **version 7.1.0 Enterprise**
- Additional extensions - **none**

#### Connection specification:
- Database **Postgres 10.10**
- Driver name **PostreSQL 10**
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  **NO**

#### Describe the problem you're observing:
When i compare tables with INTERVAL column, invalid script was generated by DBEaver
wrong result example:
CREATE TABLE "public"."GeoLocationObject" ("Id" SERIAL NOT NULL, "Employee_Id" INTEGER NOT NULL, "Latitude" FLOAT8 NOT NULL, "Longitude" FLOAT8 NOT NULL, "Accuracy" INTEGER NOT NULL, "CoordsProvider" TEXT NOT NULL, "SentFromMobileDevDB" INTEGER NOT NULL, "ReceiveTime" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "PositionTime" TIMESTAMP WITH TIME ZONE NOT NULL, "ProviderCoordsTime" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "TimeZoneOffset" INTERVAL(49, 6)(49, 6)(49, 6) NOT NULL, "TimeType" INTEGER NOT NULL, "GPSStatus" INTEGER NOT NULL, "SessionId" TEXT NOT NULL, CONSTRAINT "PK_GeoLocationObject" PRIMARY KEY ("Id"));

**Comment by uslss** [comment]
thanks for the bug report

**Comment by LonwoLonwo** [comment]
@AlexeyAG and what arguments did the "TimeZoneOffset" interval column have when creating? interval (6) or something else?

**Comment by LonwoLonwo** [comment]
So. Now Dbeaver correctly handles interval data type fields, not just precision. You can see fields information in Table Navigation Tree, in table DDL and in table properties, column tab. 
![2020-09-23 17_53_29-DBeaver Enterprise 7 3 0 - _master_ Script-24](https://user-images.githubusercontent.com/45152336/94030198-37d0bc80-fdc6-11ea-89af-3c6464029ce0.png)
![2020-09-23 17_55_26-DBeaver Enterprise 7 3 0 - inteval_atttyp_id_second](https://user-images.githubusercontent.com/45152336/94030206-3901e980-fdc6-11ea-90c0-f0dbf87a15ce.png)

**Comment by LonwoLonwo** [comment]
And about migration DDL.  Unfortunately Liquibase returns not correct DDL for interval data types. 
I could not do anything with the correct field conversion for the intervals, so I just removed the fields and the precision. Now at least DDL is liquid and can be used without errors.

**Comment by LonwoLonwo** [comment]
interval column creation script is now correct

**Comment by kseniiaguzeeva** [comment]
Verified per the comments above.

**Comment by ShadelessFox** [comment]
The generated DDL is still invalid for "non-range" interval types like `interval year`.

**Comment by ShadelessFox** [comment]
Fixed. Notice that only `.. to second` types have precision:

![image](https://user-images.githubusercontent.com/35821147/120785268-a9f0c800-c535-11eb-8d4e-6d9f7a3b57fa.png)

**Comment by kseniiaguzeeva** [comment]
verified
