### ISSUE TITLE
[MySQL] Copy as CSV copies only timestamp data if a part of a table is selected only

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9014]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.1 EA

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
Copy as CSV copies only timestamp data if a part of a table is selected only and Use native date/time format is enabled 

Precondition:
1. a table with several filled columns and rows exists
2. one of the columns has timestamp type
3. the table is opened in Data Editor
4. Use native date/time format is enabled in the connection settings

Steps:
1. Select a part of the table including data of the timestamp type column (e.g. in sakila.NewTable_2)
2. Select Copy AS CSV in Context menu for this part
3. Paste the copied data

Expected: 
the data is pasted completely

Actual result:
Only column names and data of timestamp column is pasted

![9w6uP9J3h6](https://user-images.githubusercontent.com/51405061/85013130-ba653280-b16c-11ea-8c22-b587bd121a88.gif)

**Comment by SA357** [comment]
The problem is with SQL Editor, setting "Extract SQL from source code". You can disable it or don't copy CSV to SQL Editor.

![image](https://user-images.githubusercontent.com/61096732/88164151-68587680-cc1c-11ea-930e-215e5057cda6.png)

**Comment by serge-rider** [comment]
I've added taskbar notification for SQL transformations. Otherwise it may look weird and unexpected.

![image](https://user-images.githubusercontent.com/6398845/88405797-6fc47f00-cdd8-11ea-8a4e-4e73b36334fe.png)

**Comment by p91paul** [comment]
Another suggestion: you could allow to get back to the unconverted string via ctrl+z. I don't know if putting something in the undo queue programmatically is easily doable.

This would be similar to the eclipse feature that allows you to revert "on save" actions by doing an undo.

**Comment by kseniiaguzeeva** [comment]
@SA357 Thank you for the help. It works.
