### ISSUE TITLE
[MySQL] Datasource MySQL settings cannot be disabled

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9016]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.1 EA

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
Datasource MySQL settings cannot be disabled.

#### Steps to reproduce, if exist:

1. Select MySQL in DB Navigator tree
2. Press F4
3. Go to Data viewer>Data formatting
4. Disable **Use native date/time format**
5. Press Ok
6. Open Data formatting for MySQL again
7. Disable **Datasource MySQL settings**
8. Press Ok
9. Open Data formatting for MySQL again

Expected: 
**Use native date/time format** and  **Datasource MySQL settings** are disabled
Actual result:
Checkboxes of **Use native date/time format** and  **Datasource MySQL settings** are checked
![gjRXfe7ASa](https://user-images.githubusercontent.com/51405061/85015867-6872db80-b171-11ea-8ed0-e84edcd84fd6.gif)

#### Include any warning/errors/backtraces from the logs

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4798236/dbeaver-debug.log)

**Comment by serge-rider** [comment]
It happens because MySQL has overwrited driver parameters for data formatting.

**Comment by uslss** [comment]
verified
