### ISSUE TITLE
Evironment colors in Navigator

### ISSUE THREAD

**Issue by michalk-k** [dbeaver/dbeaver#9017]
Since DBeaver v7.1.0 colors in Navigator are applied differently than before:
1. only colored frame is drawn
2. text doesn't fit the frame

OS: Linux/Kubuntu

Is it something expected:
![obrazek](https://user-images.githubusercontent.com/7868445/85016083-542ae080-b169-11ea-8819-a6ec6e8485d8.png)

**Comment by uslss** [comment]
hi, issue is already fixed in scope of #8854 
You could try it in EA version (https://dbeaver.io/files/ea).
Anyway, thanks for the bug report
