### ISSUE TITLE
Incorrect table statistics in DB Navigator

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9018]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.1

#### Connection specification:
- Database name and version SQL Server 2017

#### Describe the problem you're observing:
Table size becomes -1b when table is opened in Data viewer
![image](https://user-images.githubusercontent.com/31996417/85018633-2bf5ae80-b176-11ea-943b-3dea2227afb8.png)
![2020-06-18_15h11_55](https://user-images.githubusercontent.com/31996417/85018637-2f893580-b176-11ea-9d5e-4b254ac8d237.gif)

**Comment by serge-rider** [comment]
Fixed.
@uslss please check stats rendering in other databases  (PG, Oracle, Clickhouse, MongoDB, Redis).
Note: please check that dbeaver doesn't consume CPU in idle mode when there is statistics in the navigator.

**Comment by uslss** [comment]
verified

**Comment by serge-rider** [comment]
Fixed
