### ISSUE TITLE
Query isn't executed if cursor is placed after delimiter

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9019]
#### System information: 
- Operating system (distribution) and version win10x64
- DBeaver version 7.1.1

#### Describe the problem you're observing:
The query isn't executed if the cursor is placed after the delimiter
![2020-06-18_15h48_02](https://user-images.githubusercontent.com/31996417/85021889-2babe200-b17b-11ea-930f-b107ca2eae5e.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
