### ISSUE TITLE
SQL Editor Execution plan button is active but does nothing on click

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9020]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.1

#### Connection specification:
- Database name and version SQL Server

#### Describe the problem you're observing:
previously fixed in scope of #8243
In SQL Editor Execution plan button is active but does nothing on click. Also no error appears in Error log

**Comment by LonwoLonwo** [comment]
![2020-09-18 12_12_55-Window](https://user-images.githubusercontent.com/45152336/93580338-59860a00-f9a8-11ea-8b15-17e5209c4d02.png)
not reproducible in my case. more steps, may by?

**Comment by kseniiaguzeeva** [comment]
The button does nothing in SQL Editor for SQLServer. DBeaver 7.2.1 EA. But no errors in Error log now

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
The button is disabled
