### ISSUE TITLE
[MySQL] Data formatting is not applied in Export settings

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9021]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.1 EA

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
Data formatting is not applied in Export settings

Precondition:
1. a filled table with column of Timestamp type exists (e.g. Kseniia.Export)
2. the table is opened in Data Editor

Steps:
1. Open Export wizard for the table
2. Select any file type except Database
3. Go to Settings step
4. Press Edit btn
5. Select Timestamp format
6. Change the pattern to any other than the existing one in the table
7. Press Apply and Close
8. Make other settings if necessary
9. Start Export
10. Open the exported file

Expected: Changed timestamp format is applied in te file

Actual result: Timestamp format is the same like in the exported table

![cvDRMleLgQ](https://user-images.githubusercontent.com/51405061/85024238-84c94500-b17e-11ea-8fb2-4a687553e880.gif)

**Comment by serge-rider** [comment]
@kseniiaguzeeva Is it true for txt format only or for all formats?

**Comment by kseniiaguzeeva** [comment]
for all formats

**Comment by serge-rider** [comment]
Can't reproduce anymore. Probably fixed in #8669

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce anymore too. Closed.
