### ISSUE TITLE
Varbinary column's values isn't exported to HTML

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9022]
#### System information: 
- Operating system (distribution) and version wun10 x64
- DBeaver version 7.1.1

#### Connection specification:
- Database name and version SQL Server 2017

#### Describe the problem you're observing:
Varbinary column's value isn't exported to HTML even if Images option is checked in settings. It is DimEmployee table from sample [Adventure works](https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksDW-data-warehouse-install-script.zip) database

[DimEmployee_202006181625.html.txt](https://github.com/dbeaver/dbeaver/files/4798865/DimEmployee_202006181625.html.txt)

**Comment by uslss** [comment]
issue is also reproducible for db2 - blob type
db4.DB2INST1.EMP_PHOTO

**Comment by LonwoLonwo** [comment]
![2020-06-29 17_16_40-DBeaver 7 1 1 - EMP_PHOTO](https://user-images.githubusercontent.com/45152336/86025230-a5bf4f00-ba36-11ea-964e-35879371a8cc.png)
works fine with the right settings
