### ISSUE TITLE
Create New [object column] icon in context menu changes unexpectedly

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9023]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7,1,1

#### Describe the problem you're observing:
When open context menu e.g. for table in Columns tab, if no column is chosen - folder icon is shown near Create New Column. If some column is chosen - this column icon is shown. Issue is reproducible also for constraints, FKs, etc.
![2020-06-18_16h42_20](https://user-images.githubusercontent.com/31996417/85028027-41bda080-b183-11ea-9db9-e948545c599e.gif)
![image](https://user-images.githubusercontent.com/31996417/85028565-e8a23c80-b183-11ea-8065-47b6848f86ba.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
