### ISSUE TITLE
Database is shown incorrectly in DBO editor in Custom view.

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9025]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.1.1

#### Describe the problem you're observing:
Tables, Indexes and others are shown at the one tab, if options are enabled like they are shown at the picture.
![2020-06-18_17h21_08](https://user-images.githubusercontent.com/31996417/85032567-a7f8f200-b188-11ea-92b6-ba60840e275f.png)

**Comment by serge-rider** [comment]
Fixed. All items are still merged in db navigator when folder-less mode is enabled.
But in entity editor we put them in separate folders.

**Comment by uslss** [comment]
verified
