### ISSUE TITLE
Missing columns in DDL generation for PostgreSQL

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#9037]
I re-open the following issue: https://github.com/dbeaver/dbeaver/issues/7172
It still happens on the last DBeaver version with the same conditions to me, as described in the first issue.

Perhaps could I investigate a little bit further if I could get the query used to generate the DDL code, in order to try it on my PostgreSQL server and find where the problem could come from?

Regards,
Cedric

**Comment by uslss** [comment]
Hi @ced75 , thanks for the bug report.
You could see all the query executed using Query Manager (Main menu: Window - Show View - Query Manager).
Thanks in advance

**Comment by uslss** [comment]
there are not any updates on issue. Ticket will be closed.
If issue is still actual for you - feel free to reopen the ticket
