### ISSUE TITLE
Custom view: Hide folders function shows some table tabs incorrectly

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9038]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.1 EA

#### Connection specification:
- Database name and version MySQL, PostgreSQL

#### Describe the problem you're observing:
Custom view: Hide folders function shows some table tabs incorrectly

#### Steps to reproduce, if exist:
1. Open General tab of Connection configarution
2. Select **Custom** Navigator view
3. Press **Customize...** btn
4. Enable only **Hide folders**
5. Press Ok
6. Reconnect
7. Open a table.

Actual result:
Strange view of Columns, Constraints, Indexes Partitions tabs.
![Qu5v8HGPyJ](https://user-images.githubusercontent.com/51405061/85138103-e820a900-b24a-11ea-8578-5e59140dc4c1.gif)

Expected: correct view of visible tabs
![dbeaver_6HWpY5AjC4](https://user-images.githubusercontent.com/51405061/85138205-11d9d000-b24b-11ea-88f8-9f7ac195b10a.png)

**Comment by uslss** [comment]
duplicates #9025
