### ISSUE TITLE
Query manager shows wrong entries per page if entries <100 are set

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9039]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.1 EA

#### Describe the problem you're observing:
Query manager shows wrong entries per page if entries <100 are set

#### Steps to reproduce, if exist:
1. Open query manager
2. Create about 100 query entries
3. Press Filters.. btn
4. Set other Entries number (from 1 to 99)

Expected:
The quantity of entries is equel to the set number

Actual result:
The quantity of entries is less then the set number
![2ZbYNpyN3r](https://user-images.githubusercontent.com/51405061/85140672-3d11ee80-b24e-11ea-80d3-438c31cbe2a7.gif)

**Comment by serge-rider** [comment]
How do you calculate records number?
It seems quite close to the set number.

Note: it mustn't exactly match this number. Records filter works in lazy mode, there may be +/- 5 records .

**Comment by kseniiaguzeeva** [comment]
Yes, the difference is similar with 5 +/- records. The ticket is closed.
