### ISSUE TITLE
Default schema not working.

### ISSUE THREAD

**Issue by lroberts-lly** [dbeaver/dbeaver#9040]
#### System information: 
- OS:  Windows 7 
- DBeaver version: 7.1.0
- Java version : OpenJDK 11, (bundled with DBeaver)
- Additional extensions: None

#### Connection specification:
- Database name and version:  Postgres 10.6
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?   Yes, SSH tunnel.

#### Describe the problem you're observing:
The default schema not working as it should.  The connection is setup with a default database and schema.  When a new SQL Editor is opened, the active datasource and schema are correctly displayed in the toolbar.  However, a simple SELECT on a known table in the schema will generate a SQL error that table does not exists.  If you use the toolbar to temporarily change the active schema to "public" and then back to the desired shema, then the table is found and queries work correctly.    I noticed that the hints do work correctly.  e.g. if you are typing in a table name or view name, the list of options presented is correct.  It is only when performing the actual query execution where the error is encountered.

#### Steps to reproduce, if exist:
1.  Start DBeaver.
2.  Create connection to a Postgres DB with a default DB and Schema set in the connection.
3.  Click on "New SQL Editor" in tool bar.  The default DB and Schema from step 2 show be listed as the "Active DataSource and Schema" in the toolbar.
4.  Try to do a select on any table in the shema.  An error should be displayed that the table is not found.

#### Include any warning/errors/backtraces from the logs

[dbeaver.log.log](https://github.com/dbeaver/dbeaver/files/4805035/dbeaver.log.log)

**Comment by lroberts-lly** [comment]
Note: The last version where the default schema worked properly was 7.0.3.

**Comment by lroberts-lly** [comment]
This is possibly related to [#9185](https://github.com/dbeaver/dbeaver/issues/9185)

**Comment by kseniiaguzeeva** [comment]
Thank you for you suggection. With help of #9185 I could reproduce it.

Steps:
1. create postgresql connection
2. select default schema and database in connection settings>initialization (except public)
3. Press Ok
4. Select PostgreSQL in db navigator
5. Open new SQL Editor
6. Run a select statement (select * from tablename) for a table from the selected schema.7. 

Actual result: the table is not found in the schema and not displayed in ResultSet.
Expected: Mentioned table is displayed in ResultSet.

**Comment by mkgrgis** [comment]
This issue is about both Oracle and Postgres. [x:oracle] https://github.com/dbeaver/dbeaver/issues/8766

**Comment by serge-rider** [comment]
Fixed.
For PG I've changed connection state init procedure.
For Oracle I fixed a bug with active schema visualization.

**Comment by kseniiaguzeeva** [comment]
Verified both (PostgreSQL and Oracle)
