### ISSUE TITLE
Exasol Metadata Snapshot Execution

### ISSUE THREAD

**Issue by kamal-1** [dbeaver/dbeaver#9041]
**Is your feature request related to a problem? Please describe.**
Database Navigator in DBeaver gets stuck ETL loads are running. On analysis we found out that the metadata query fired by DBeaver was being blocked by ETL query. 

**Describe the solution you'd like**
Exasol introduced a feature called snapshot execution for metadata queries. This returns latest committed snapshot of the metadata. The metadata queries fired by DBeaver will benefit from this feature.

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshots attached.
Database Navigator
![DBeaver Database Navigator](https://user-images.githubusercontent.com/48100355/85143178-0d8fc180-b20f-11ea-9056-808f10dbfbf9.png)
ETL Session
![ETL Session](https://user-images.githubusercontent.com/48100355/85143175-0cf72b00-b20f-11ea-8c37-023480da83fd.png)
DBeaver Metadata Session
![DBeaver Blocked Session](https://user-images.githubusercontent.com/48100355/85143173-0c5e9480-b20f-11ea-8312-193611fdbf15.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by Sargul** [comment]
This should bei fixes by #9029.

For index retrievable I forgot to use lock free meta data hint.

**Comment by kamal-1** [comment]
Thanks for a quick turnaround on this

> This should bei fixes by #9029.
> 
> For index retrievable I forgot to use lock free meta data hint.

Thanks for a quick turnaround
