### ISSUE TITLE
Creating PROCEDURE throwing a SQL compilation error due to syntax error

### ISSUE THREAD

**Issue by bghou** [dbeaver/dbeaver#9042]
#### System information: 
- Mac OS Mojave 10.14.6 (18G4032)
- Version 7.1.0.202005311732
- Additional extensions: Snowflake Driver

#### Connection specification:
- Snowflake
- Driver name: snowflake-jdbc-3.12.4 
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:
_**Unable to create this simple PROCEDURE using dBeaver.**_ 

> CREATE OR REPLACE PROCEDURE simple_stored_procedure_example2()
> 	returns string not null
> 	language javascript
> 	as
> 	$$
> 		var cmd = `
> 		SELECT getdate();
> 		`
> 		var sql = snowflake.createStatement({sqlText: cmd});
> 		var result = sql.execute();
> 		return 'Hello World';
> 	$$
> ;

_**Error received:**_

> org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1003] [42000]: SQL compilation error:
> syntax error line 1 at position 0 unexpected '`'.
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:135)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:492)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:427)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:419)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:779)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2966)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3582)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
> syntax error line 1 at position 0 unexpected '`
> '.
> 	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:151)
> 	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:76)
> 	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:503)
> 	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:380)
> 	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:582)
> 	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:266)
> 	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:202)
> 	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:882)
> 	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:331)
> 	at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:395)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:342)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:132)
> 	... 12 more
> 

Although, can do so using Snowflake web Worksheet without any issue. I am assuming it has something to do with " ` " character.

#### Steps to reproduce, if exist:
1. Copy above PROCEDURE statement into dBeaver for a Snowflake connection
2. Execute the SQL

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
I think this happens because DBeaver doesn't support double-dollar quotes for Snowflake.
Fixed.

**Comment by uslss** [comment]
verified
