### ISSUE TITLE
Spaces at end of ssh hostname cause 'host not found' failures

### ISSUE THREAD

**Issue by PenelopeFudd** [dbeaver/dbeaver#9043]
#### System information: 
- Operating system (distribution) and version: MacOS Catalina 
- DBeaver version: 7.1.0 Community Edition
- Additional extensions: none

#### Connection specification:
- Database name and version: n/a
- Driver name: n/a
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:

Testing an SSH tunnel profile failed with a 'host not found' error, even though the hostname looked right.

#### Steps to reproduce, if exist:

When creating an SSH tunnel profile, I copied-and-pasted a hostname from a wiki page, and there were some spaces copied at the end.
When I clicked 'test connection', it barfed.  Removing the spaces fixed it.

**Comment by kseniiaguzeeva** [comment]
verified
