### ISSUE TITLE
Shape field has weird characters

### ISSUE THREAD

**Issue by ernestocd** [dbeaver/dbeaver#9046]
System information:
•	Windows 10 Pro
•	DBeaver version: Version 7.1.0.202005311732
Connection specification:
•	SQL Server Management Studio	18.5
Describe your question:
•	I am new to Dbeaver, I have imported the database successfully but when reviewing the shape field, it appears to have weird characters, therefore, I am unable to use the spatial components the platform offers.

**Comment by kseniiaguzeeva** [comment]
Could you please send a screenshot of the problem?
Which data type does it affect?

**Comment by ernestocd** [comment]
Here is the screenshot illustrating the shape field with the weird characters I mention above. Not sure if it is useful to know but this is an MS SQL spatial database created with ArcGIS, i.e., Esri software.

![image](https://user-images.githubusercontent.com/4702142/86789363-38fb1480-c035-11ea-933b-9b9b44e808c1.png)

**Comment by jlrodasr** [comment]
I have the same problem, any SELECT against MS SQL Server (2016 in my setup) with a geometry column does not get recognized by DBeaver as a query with a spatial column. For example, the following table:
```sql
CREATE TABLE [dbo].[ORDENES_DE_TRABAJO](
	[OBJECTID] [int] NOT NULL,
	[Shape] [geometry] NULL,
 CONSTRAINT [R1273_pk] PRIMARY KEY CLUSTERED 
(
	[OBJECTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];

ALTER TABLE [dbo].[ORDENES_DE_TRABAJO]  WITH NOCHECK ADD  CONSTRAINT [g1248_ck] CHECK  (([SHAPE].[STSrid]=(32717)));

ALTER TABLE [dbo].[ORDENES_DE_TRABAJO] NOCHECK CONSTRAINT [g1248_ck];
```
With the following data:
```sql
INSERT INTO [dbo].[ORDENES_DE_TRABAJO](OBJECTID, Shape) VALUES(1, geometry::STGeomFromText('POINT (730121.23979999963 9684060.2467)', 32717));
INSERT INTO [dbo].[ORDENES_DE_TRABAJO](OBJECTID, Shape) VALUES(2, geometry::STGeomFromText('POINT (718294.60570000019 9681684.4159)', 32717));
INSERT INTO [dbo].[ORDENES_DE_TRABAJO](OBJECTID, Shape) VALUES(3, geometry::STGeomFromText('POINT (717148.42839999963 9677159.2381)', 32717));
INSERT INTO [dbo].[ORDENES_DE_TRABAJO](OBJECTID, Shape) VALUES(4, geometry::STGeomFromText('POINT (724653.61419999972 9683178.6532)', 32717));
INSERT INTO [dbo].[ORDENES_DE_TRABAJO](OBJECTID, Shape) VALUES(5, geometry::STGeomFromText('POINT (718730.11070000008 9677819.0661)', 32717));
```
Results in the following after executing `SELECT * FROM [dbo].[ORDENES_DE_TRABAJO];`:
![imagen](https://user-images.githubusercontent.com/10855444/87992389-c9ae0780-caad-11ea-94e9-c6d3d49034eb.png)
Instead of seeing the points on the map I get this:
![imagen](https://user-images.githubusercontent.com/10855444/87993047-2fe75a00-caaf-11ea-8f00-a30d84a31b56.png)
The same query with the same data works when I query against Postgresql. I'm using DBeaver 7.1.2.

**Comment by kseniiaguzeeva** [comment]
Thank you for the example. I've reproduced it.

**Comment by hsseo0501** [comment]
I tried to solve this issue, but no longer want to follow it.
The issue is related to the commercial version.
[Working with Spatial GIS data](https://github.com/dbeaver/dbeaver/wiki/Working-with-Spatial-GIS-data).

**Comment by kseniiaguzeeva** [comment]
Please open new ticket if you have any issues

**Comment by serge-rider** [comment]
Geometry/spatial support for SQL Server presents in EE version only.

@jlrodasr Your test case:
![image](https://user-images.githubusercontent.com/6398845/89736775-99d29e00-da74-11ea-8c78-d9f80c7492e3.png)

There are no plans to add this feature in the Community Edition in near future.

@hsseo0501 Appreciate your efforts. EE version is more or less similar to it. However we are not ready to support two versions of the same functionality. Sorry.

**Comment by Stalfur** [comment]
Just want to thank you for this thread, it explains an issue we encountered. Saved me hours of headaches.
