### ISSUE TITLE
Decimals are being rounded

### ISSUE THREAD

**Issue by jdfieber** [dbeaver/dbeaver#9047]
Decimals are being rounded. My default settings in Preferences, Data Formats, Numbers is Maximum Fraction Digits = 10, but it is still being rounded. Thank you.

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
hi @jdfieber , what database do you use?

**Comment by jdfieber** [comment]
Hi there @uslss. Using redshift. There are up to 10 decimals for some stored values but four for one I calculated (even though there are more than four decimals)

**Comment by uslss** [comment]
cannot reproduce it for now. if it is still actual - feel free to reopen an issue
