### ISSUE TITLE
[MySQL] Case-sensetive function is not applied in Metadata search

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9049]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.1 EA

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
Case sensetive function is not applied in Metadata search
#### Steps to reproduce, if exist:

1. Connect to MySQL
2. Open Metadata Search
3. Select MySQL in the left part of the table
4. Enable Case-sensetive function on the right
5. Write a table name in Object name field using different case, then the table name has (e.g. ACTOR in schema sakila)
6. Press Search

Actual result: 
All tables with  word "actor" are found (regardless register type)

Expected: Only tables with word "actor" and correct case are found
![dbeaver_AX3lwV07Eh](https://user-images.githubusercontent.com/51405061/85220900-f7713500-b3b7-11ea-86e5-6c4b46010d6f.png)

**Comment by uslss** [comment]
still actual against 21.1.3

**Comment by E1izabeth** [comment]
Can't reproduce against DBeaver 23.0.5

**Comment by LonwoLonwo** [comment]
Reproducible in DBeaver 23.2.0
