### ISSUE TITLE
Application starts working very slow in special case

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9050]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.1.1
![2020-06-21_14h15_07](https://user-images.githubusercontent.com/31996417/85224342-60fe3d00-b3d2-11ea-884e-ae9a2a64cf61.gif)
[.log](https://github.com/dbeaver/dbeaver/files/4809423/default.log)

**Comment by serge-rider** [comment]
Fixed (stats was re-calculated in a loop because of stats checking bug)

**Comment by uslss** [comment]
verified
