### ISSUE TITLE
Table statistic disappears if Force object refresh is enabled

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9051]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.1.1

#### Connection specification:
- Database name and version MS SQL

#### Describe the problem you're observing:
Table statistic disappears if Force object refresh on editor open is enabled
![image](https://user-images.githubusercontent.com/31996417/85231987-77bd8780-b404-11ea-8e47-c1663ff3ec32.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
