### ISSUE TITLE
dbeaver hangs when executing a query with many parentheses in FROM clause

### ISSUE THREAD

**Issue by tomershay** [dbeaver/dbeaver#9054]
#### System information: 
- Operating system (distribution) and version: Macbook Pro 13'
- DBeaver version: 7.0.3.202004191823
- Additional extensions: none

#### Connection specification:
- Database name and version: MySQL 8.x
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Dbeaver hangs and becomes unresponsive when executing a query with many parentheses in the FROM clause

#### Steps to reproduce, if exist:
Run the following query with an existing table:
`SELECT * FROM ((((((((((((((((tblA))))))))))))))))`

**Comment by uslss** [comment]
hi @tomershay , thanks for the bug report.
btw, dbeaver shall not hang in this case if table name is quoted

**Comment by serge-rider** [comment]
Seems to be a bug in @JSQLParser library

**Comment by serge-rider** [comment]
Waiting for the fix in @JSQLParser

**Comment by wumpz** [comment]
Sorry about being late. Now JSqlParser 4.0-SNAPSHOT is able to parse this in <0.2 secs: 

    SELECT * FROM (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((tblA)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

**Comment by wumpz** [comment]
Jsqlparser 4 was released yesterday.

**Comment by serge-rider** [comment]
@wumpz thanks for the update. It resolves this ticket, the fix will be included in the next version (7.3.4)

**Comment by uslss** [comment]
verified

**Comment by wumpz** [comment]
@serge-rider You're welcome. DBeaver for now nearly replaced all of my used DB Tools and there are many since I have to deal with at least four different database types regularly.
