### ISSUE TITLE
MySQL (< 5.7.6) user management syntax without FLUSH PRIVILEGES

### ISSUE THREAD

**Issue by doublizer** [dbeaver/dbeaver#9055]
First of all, congratulations on this project and thanks for the quick fix on my previously submitted issue !

**Is your feature request related to a problem? Please describe.**
Related to #8857 
While setting user password via GUI, the syntax used requires FLUSH PRIVILEGES in order to take effect, which sometimes isn't possible due to not having RELOAD permission.
The problem was fixed on DBeaver 7.1.1 for version >= 5.7.6 with an alternative syntax, although for older versions it is still using the "UPDATE mysql.user" syntax

**Describe the solution you'd like**
Ideally I'd like to use the GUI to create users and set passwords without having to manually write SQL code.
A possible solution would be to use this syntax for versions below 5.7.6:
`SET PASSWORD FOR 'user-name-here'@'hostname' = PASSWORD('new-password')`

Sorry for not mentioning this earlier and thanks in advance.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
Good point, direct update  is an ugly way to change password anyway.

Fixed

**Comment by uslss** [comment]
verified
