### ISSUE TITLE
Session Manager window does not update data when connection changes

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#9056]
Session Manager window does not update data when connection changes.
To open the session manager for other connections, you have to close the tab of the current manager. The same problem and with the lock manager.
Windows 10, PG 11, dBeaver 7.1.1
![pg_sessions](https://user-images.githubusercontent.com/3856344/85285323-65415d80-b499-11ea-9d72-8db1e076af27.gif)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
