### ISSUE TITLE
Support for latest eclipse 2020-06 (4.16.0)

### ISSUE THREAD

**Issue by fireandfuel** [dbeaver/dbeaver#9058]
**Is your feature request related to a problem? Please describe.**
DBeaver doesn't support eclipse 2020-06 (4.16.0)

**Describe the solution you'd like**
Please update it to support 2020-06 (4.16.0)

**Comment by uslss** [comment]
Eclipse version was updated in the scope of 7.1.1 version

**Comment by fireandfuel** [comment]
At eclipse marketplace it is still the wrong version: https://marketplace.eclipse.org/content/dbeaver
