### ISSUE TITLE
Foreign key arrows missing

### ISSUE THREAD

**Issue by rpalloni** [dbeaver/dbeaver#9059]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.1.1
- Additional extensions.

#### Connection specification:
- Database name and version: Oracle
- Driver name: JDBC

#### Describe the problem you're observing: 
The fk arrow to switch table is missing in each record

#### Steps to reproduce, if exist: 
select a table with some fk and you won't see the arrow (see 7.1.0 pic below for comparison)
![foreign](https://user-images.githubusercontent.com/17080117/85338988-89299100-b4e3-11ea-98af-dc7dceecf356.png)

**Comment by uslss** [comment]
Thanks for the bug report.
seems that issue is fixed in scope of #9060 .
