### ISSUE TITLE
Manual commit option forgotten

### ISSUE THREAD

**Issue by rpalloni** [dbeaver/dbeaver#9061]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.1.1
- Additional extensions

#### Connection specification:
- Database name and version: Oracle
- Driver name: JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:
Select Manual commit for a db
Close dbeaver
Reopen dbeaver

**Comment by uslss** [comment]
hi @rpalloni ,
could you please check if the auto-commit option is unchecked in Connection properties?
![image](https://user-images.githubusercontent.com/31996417/85306209-d5121100-b4b6-11ea-86fc-0db22366f1e3.png)

**Comment by rpalloni** [comment]
Ok, right. The check is selected! Thanks indeed
