### ISSUE TITLE
Overlapping connection URL text

### ISSUE THREAD

**Issue by timneedham** [dbeaver/dbeaver#9062]
#### System information: 
- Operating system (distribution) and version: `Ubuntu 18.04.3 LTS`
- DBeaver version: `7.1.1.202006211844`
- Additional extensions: `None`

#### Connection specification:
- Database name and version: `PostgreSQL 11.6`
- Driver name: `PostgreSQL JDBC Driver`
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  `No`

#### Describe the problem you're observing:

Connection URL is now displayed in the Database Navigator tree, and the URL text is overlapping the connection name.

![image](https://user-images.githubusercontent.com/1216632/85299748-94f26480-b49d-11ea-9fe3-3b480c94c6dc.png)

* Should URL be visible, it's showing fine as a tooltip, and long URLs are proving to be quite distracting: :eyes: 

![image](https://user-images.githubusercontent.com/1216632/85299987-eb5fa300-b49d-11ea-80c1-4b9469b8a11f.png)

* Love the new left-hand bar though, much cleaner! :+1: 

#### Steps to reproduce, if exist:

Happens at startup. Only occurred since `7.1.1.`.
I've tried "Reset UI settings", but it had no effect.

#### Include any warning/errors/backtraces from the logs

Nothing obvious.

**Comment by uslss** [comment]
hi @timneedham , you could disable this feature in Preferences
![image](https://user-images.githubusercontent.com/31996417/85306474-32a65d80-b4b7-11ea-9cee-4fe3aaecab15.png)
and thanks for the bug report :)

**Comment by timneedham** [comment]
Ah, missed that one, perfect, thank you! :+1:

**Comment by eldarnegrinperion** [comment]
![image](https://user-images.githubusercontent.com/30038431/85371468-f4ea1900-b538-11ea-9edb-d66f200f0c7d.png)
i love the new interface, minor bug. ubuntu 16.04

**Comment by pyrocks** [comment]
> hi @timneedham , you could disable this feature in Preferences
> ![image](https://user-images.githubusercontent.com/31996417/85306474-32a65d80-b4b7-11ea-9cee-4fe3aaecab15.png)
> and thanks for the bug report :)

Actually I was looking for this setting using the preferences search, tried "host" and "connection", neither showed this option, so I figured it did not exist. Please make the search find this option.

**Comment by serge-rider** [comment]
Host name render was improved.
@uslss please test it on Ubuntu.

**Comment by uslss** [comment]
verified
