### ISSUE TITLE
Error resolving dependencies - Redshift driver

### ISSUE THREAD

**Issue by alejandrofm** [dbeaver/dbeaver#9065]
#### System information: 
- Ubuntu 20.04 and Windows 10
- DBeaver version 7.1.0 and 7.1.1
- Additional extensions: no

#### Connection specification:
- Database name and version: Redshift
- Driver name: RedshiftJDBC42-1.2.43.1067.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No 

#### Describe the problem you're observing:
When the download driver window open it shows this message:
Error resolving dependencies
  Maven artifact 'maven:/com.amazon.redshift:redshift-jdbc42:RELEASE' not found

Checked conectivity to both endopoints (maven and redshift in the configuration) I can reach them. Installing the driver manually works.

thanks!

**Comment by richardiversen** [comment]
I'm having exactly the same issue on Version 7.1.0.202005311732.

**Comment by richardiversen** [comment]
![Screen Shot 2020-06-22 at 6 07 31 PM](https://user-images.githubusercontent.com/16493119/85343892-c0804980-b4b3-11ea-9bae-1c0387deeb04.png)

**Comment by richardiversen** [comment]
When I go to https://dbeaver.io/files/jdbc/  I get forbidden.

**Comment by polocorona** [comment]
Same problem here.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
issue is also reproducible for enterpriseDB

**Comment by serge-rider** [comment]
AWS Redshift Maven repository is broken (something happened on this week).
I hope they will fix it. Meanwhile you can download Redshift driver from here: https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html#download-jdbc-driver

**Comment by alejandrofm** [comment]
> AWS Redshift Maven repository is broken (something happened on this week).
> I hope they will fix it. Meanwhile you can download Redshift driver from here: https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html#download-jdbc-driver

Yes it works fine manually, but for end users is not that simple to download a configure a driver. Thank you all

**Comment by serge-rider** [comment]
We'll use direct Redshift jar link instead of Maven artifact reference.
We can't rely on AWS Maven repo as it is not consistent (in compare with Maven Central). At least for now.

**Comment by uslss** [comment]
verified
