### ISSUE TITLE
Smart Commit Mode - bad behavior on error

### ISSUE THREAD

**Issue by Bschitter** [dbeaver/dbeaver#9066]
#### System information: 
- Linux Mint 19.3 / Windows 10
- DBeaver version: 7.0.4, 7.1.0, 7.1.1

#### Connection specification:
- PostgreSQL 11.6
- PostgreSQL JDBC Driver
- No tunnels or proxies used

#### Problem

If you are using Auto-Commit with the Smart commit mode following bad/strange behavior happens: If you execute an UPDATE SQL with an error, DBeaver will fall out of Auto-Commit mode and be in Manual-Commit mode as it should be. But then when you fix your UPDATE query an execute it, DBeaver will be back in Auto-Commit mode and already have committed the transaction.

#### Steps to reproduce:

* In auto commit
* Smart commit mode enable
* Execute UPDATE SQL with error: e.g. `UPDATE table set name = 'Hans' where id = 1);`
* Execute correct SQL: e.g. `UPDATE table set name = 'Hans' where id = 1;`

-> Transaction will be directly committed.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
It is a PostgreSQL-specific  issue.
PG has a special error recovery mode (you must rollback active transaction to continue to execute new queries). Auto-commit mode was toggled during this internal transaction recovery (rollback).
Fixed.

**Comment by uslss** [comment]
verified
