### ISSUE TITLE
Failure to attempt to change Data Formats 

### ISSUE THREAD

**Issue by CarlosDias01** [dbeaver/dbeaver#9068]
#### System information: 
- Operating system (distribution) and version: Win10 Pro v.2004
- DBeaver version: Version 7.1.1.202006211844
- Java version: build 1.8.0_241-b07
- Additional extensions: none

#### Connection specification:
- Database name and version: Oracle 10G
- Driver name: oracle.jdbc.OracleDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Trying to change data formats and locale but doesn't save the changes or just reload the global settings after "apply" and "apply and close".

![image](https://user-images.githubusercontent.com/18670288/85314058-e8a58380-b486-11ea-9b7e-418bdda91650.png)
![image](https://user-images.githubusercontent.com/18670288/85314099-f5c27280-b486-11ea-93ea-c670d4a9660e.png)

#### Steps to reproduce, if exist:
- Window/Preferences/DBeaver/Editor/Data Formats
1. Manage Profiles
1.1 New Profile
1.2 Language: pt-BR
1.3 Contry: Brazil
2. Format (date): dd-MM-yyyy
3. Format (timestamp): yyyy-MM-dd HH:mm:ss
4. Apply
5. Apply and Close
6. Repeat step 1 and you probably will see the glosal settings instead the new settings

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. It is actual for all connections.

**Comment by kseniiaguzeeva** [comment]
@CarlosDias01 A littler investigating was needed.
The described behaviour is expected. 
The profile is needed to select it during Export.
![kAqipNBQ5I](https://user-images.githubusercontent.com/51405061/86460757-a2c3a780-bd31-11ea-8057-ba7892b8781e.png)

You can set custom settings for your connection in Edit connection>Data viewer>Data Formatting
![dbeaver_pD52MbL8jw](https://user-images.githubusercontent.com/51405061/86460961-f6ce8c00-bd31-11ea-8496-8ea777332aaf.png)

Please open new ticket if you have any other questions.

**Comment by CarlosDias01** [comment]
Hi @kseniiaguzeeva 

I didn't know about the profile to export but all the preferences are the same, including the Global settings.

![image](https://user-images.githubusercontent.com/18670288/86463860-50b45f00-bcfc-11ea-9b45-3049679217a5.png)
![image](https://user-images.githubusercontent.com/18670288/86463867-5316b900-bcfc-11ea-8f71-f2f97ad2cb4e.png)
![image](https://user-images.githubusercontent.com/18670288/86463938-79d4ef80-bcfc-11ea-95ef-9173c9749254.png)
![image](https://user-images.githubusercontent.com/18670288/86463905-6a55a680-bcfc-11ea-855e-e33b1e8e5a70.png)

**Comment by kseniiaguzeeva** [comment]
To add profile to database settings will be implemented as feature request.

You can set your settings in global profile: window>preferences>dbeaver>editors>data editor>data formats. They are saved.
