### ISSUE TITLE
New object tree interface

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#9071]
It is nice idea to add IP information to object tree. But realization of this future is not comfortable.

New IP information scattered on a feild and difficult to read with eyes
![изображение](https://user-images.githubusercontent.com/61137576/85367239-4fd43e00-b542-11ea-863a-9c9c786a3d84.png)

By my practice most effective interface is for exaple
![изображение](https://user-images.githubusercontent.com/61137576/85367527-de48bf80-b542-11ea-8b6a-b2e81a304aba.png)
with IP ahead the db name. 

and it would be great to be able to sort the database names inside the group, for example by ip or by name. In practice, it is often necessary that databases from one server to be near
![изображение](https://user-images.githubusercontent.com/61137576/85367970-bd349e80-b543-11ea-9459-73906a000924.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by p91paul** [comment]
if you want it this way, why don't you add the ip to your connection names? I prefer to show my chosen name, and hostname/ip as additional info after that

**Comment by detkliff** [comment]
> 
> 
> if you want it this way, why don't you add the ip to your connection names? I prefer to show my chosen name, and hostname/ip as additional info after that

Now I do just that - point IP in name by mannualy. But I think it would be more comfortable to do this with the settings\options.

yes it would be great if there was such an option before or after.


but in its current version, ip readability is difficult, isn't it?
![изображение](https://user-images.githubusercontent.com/61137576/85677406-f3f3eb80-b6e0-11ea-84d2-c084c020cfc9.png)

**Comment by uslss** [comment]
will be tracked in #13127
