### ISSUE TITLE
DBeaver 7.1.1 : how to remove connection informations in database navigator

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#9074]
Hi,

#### System information: 
- Operating system (distribution) and version : Linux Mint 19.3
- DBeaver version : 7.1.1

#### Connection specification:
- Database name and version : PostgreSQL 11

#### Describe your question:
With DBeaver 7.1.1, a new feature appeared in database navigator: the connection informations appear next to the connexion name.
Under Linux Mint, the text is not positionned correctly. Here is a screenshot of the actual result:
![image](https://user-images.githubusercontent.com/12892581/85377080-dc79fe80-b538-11ea-92c7-016755a7dc48.png)

How can I hide connection informations ?

Thanks in advance for your help.
Kind regards,
Cedric

**Comment by uslss** [comment]
Hi @ced75 ,
you could disable this feature in properties
![image](https://user-images.githubusercontent.com/31996417/85410671-0e5a8780-b570-11ea-82de-386b1df0ed70.png)

**Comment by ced75** [comment]
Thanks for the answer, that did it.
Perhaps could you try to arrange the connection host name display? If possible, of course.
I suppose it depends on the OS.

**Comment by leocor** [comment]
Same problemi with Ubuntu 20.04 since 7.1.1 behaviour changed. "Show connection host name" in Navigator, Preferences fixed it. 
However if checked, host names are weirdly shown, with no padding and un-aligned.

**Comment by uslss** [comment]
bug is already created #9062
