### ISSUE TITLE
Cannot edit table data using the built in editor

### ISSUE THREAD

**Issue by sorcio46** [dbeaver/dbeaver#9076]
Hello everyone!

#### System information: 
- Windows 10.0.18363 build 18363
- DBeaver 7.1.1.202006211844

#### Connection specification:
- Legacy Microsoft JDBC Driver for SQL Server (MSSQL): mssql-jdbc-8.2.0.jre8.jar
- Microsoft SQL Server 2014 - 12.0.2000.8
&
- Oracle JDBC driver: Oracle 12.2.0.1.0
- Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

#### Describe the problem you're observing:
Cannot edit table data using the built in editor.

This issue is **not** present in release 7.1.0, I have noticed it after upgrading to 7.1.1.

I was **not** able to reproduce this issue while using DB2 LUW and PostgreSQL databases with the latest version.

#### Steps to reproduce, if exist:
Open a table via the built in editor and try to change a value inside a cell.

#### Include any warning/errors/backtraces from the logs
I can see the following message from the editor:
`Column XXX is read-only: No corresponding table column`

No error messages can be found inside _dbeaver-debug.log_.

**Comment by ramonamarth** [comment]
Same issue, there is a lock on the data-type icon next to column's name with a label stating "(Read-only: No corresponding table column)". 
It was working just fine on 7.1.0 and there has been no changes to settings, connections or schemmas.
System: Windows 10 Pro version 18363.900
DBeaver: 7.1.1.202006211844
Driver: Oracle JDBC 12.2.0.1.0
Server: Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

**Comment by uslss** [comment]
Hi @sorcio46,
thanks for the bug report. Issue is fixed in scope of #9060.
Close this as duplicate
