### ISSUE TITLE
Pressing ctrl + Enter at end of line with space executes query after instead

### ISSUE THREAD

**Issue by LorisZ** [dbeaver/dbeaver#9078]
#### System information: 
- Kubuntu 18.04
- Dbeaver 7.1.1

#### Connection specification:
- Postgres 12
- tunnels: no

#### Describe the problem you're observing:

When using dbeaver's autocomplete in the sql editor, it adds an alias and a space after that. If I press Ctrl + Enter and there is already another query after that, the next one will be executed.

#### Steps to reproduce, if exist:

1. Write a query like the following (attention to the space after `test t`, which is automatically inserted when using the editor's autocomplete):
```sql
select *
from test.test t 

insert into test.test (test_id) values (1)
```
2. and place cursor after the space following t
3. press Ctrl + Enter to execute current query
4. Insert query is executed instead of the select

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
