### ISSUE TITLE
ORA-00904 while dig into scheme from db view

### ISSUE THREAD

**Issue by rmrfchik** [dbeaver/dbeaver#9079]
#### System information: 
- Operating system (distribution) and version
 Debian 10.3
- DBeaver version
7.1.1.202006211844
- Additional extensions

#### Connection specification:
- Database name and version
PL/SQL Release 11.2.0.3.0 - Production
"CORE	11.2.0.3.0	Production"
TNS for Linux: Version 11.2.0.3.0 - Production
NLSRTL Version 11.2.0.3.0 - Production

- Driver name
Oracle thin, 12.2.0.1 (proposed and downloaded by dbeaver)

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
Get ORA-00904 when click on schema name in db window

#### Steps to reproduce, if exist:
1. Connect to oracle db and open database tree
2. Click on "schemas" in database tree view (on left)
2.1 Database window opens, tab "schemas" is selected, shows available schemas
3. Navigate to any schema with tables and double click on schema
4. An error window is appears (here is l18n in Russian)
Message: ORA-00904: "S"."OWNER": недопустимый идентификатор
Details:
Error reading table statistics
  Error : 904, Position : 96, Sql = SELECT SEGMENT_NAME,SUM(bytes) TABLE_SIZE
FROM USER_SEGMENTS s
WHERE S.SEGMENT_TYPE='TABLE' AND s.OWNER = :1 
GROUP BY SEGMENT_NAME, OriginalSql = SELECT SEGMENT_NAME,SUM(bytes) TABLE_SIZE
FROM USER_SEGMENTS s
WHERE S.SEGMENT_TYPE='TABLE' AND s.OWNER = ?
GROUP BY SEGMENT_NAME, Error Msg = ORA-00904: "S"."OWNER": недопустимый идентификатор

#### Include any warning/errors/backtraces from the logs
No meaningful logs are detected. 
dbeaver-debug.log contains only "> Start blah blah", 
.log is absent.

**Comment by uslss** [comment]
Hi @rmrfchik ,
unfortunately cannot reproduce it. Is it reproducible for all the schemas?

**Comment by uslss** [comment]
duplicates #9070
