### ISSUE TITLE
Ability to create CHECK constraints in "Add constraint for table" dialog for Oracle

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#9081]
As done in PostgreSQL
![2020-06-23 13_34_23-DBeaver 7 1 1 - parts](https://user-images.githubusercontent.com/45152336/85395179-65ecf900-b558-11ea-9284-177ffcb1760b.png)

**Comment by LonwoLonwo** [comment]
Works for all Oracle versions

**Comment by uslss** [comment]
verified
