### ISSUE TITLE
Read-Only forced in data view panel

### ISSUE THREAD

**Issue by brunopnogueira92** [dbeaver/dbeaver#9082]
#### System information: 
- Ubuntu 18.06LTS
- DBeaver Version 7.1.1.202006211844

#### Connection specification:
- Oralce Driver 

#### Describe your question:
Hello guys, in advance thanks for helping me.

I use the Dbeaver for a long time and for me is the best application ever :D

Well, the question: today my linux just updated for the last version and now when i try to open a table and edit any value directly in tab "Data", show me a notification in the right-bottom saying: "the column is read-only".

Where i can turn off this "read-only" mode?
![image](https://user-images.githubusercontent.com/65361033/85396674-0ab40a00-b54a-11ea-9585-ec0483ba7566.png)

**Comment by ramonamarth** [comment]
#9076

**Comment by uslss** [comment]
Hi @brunopnogueira92 ,
thanks for the bug report. Issue is fixed in scope of #9060.
Close this as duplicate
