### ISSUE TITLE
Cells are read only. Cant edit.

### ISSUE THREAD

**Issue by LwServices** [dbeaver/dbeaver#9092]
#### System information: 
- Windows 10
- 7.1.1
- None

#### Connection specification:
- Oracle 12c 12.2.0.1.0
- Oracle JDBC 12.2.0.1.0

#### Describe the problem you're observing:
Cant edit cells. Shows read only.
I have downgraded to 7.0 and error is gone.

**Comment by nur7186** [comment]
I have the same issue after update to version 7.1.1.

**Comment by sorcio46** [comment]
Duplicate of #9076

**Comment by kseniiaguzeeva** [comment]
The hotfix was published yesterday. Please download 7.1.1. again. Closed as a duplicate.
