### ISSUE TITLE
Advanced paste adds blank rows

### ISSUE THREAD

**Issue by Me963** [dbeaver/dbeaver#9095]
Hi,

I am using DBeaver Community edition 7.1.1. and I'm having problems with Advanced paste.
When I insert new rows and "Advanced paste" data, it adds the right amount of new rows 
![Picture_1](https://user-images.githubusercontent.com/67363842/85520395-27604880-b603-11ea-9ccd-d1b7e4ecdd90.JPG), 

then I select next column and advanced paste values 
![Picture_2](https://user-images.githubusercontent.com/67363842/85520399-28917580-b603-11ea-9dd9-bb9cfebc1dbd.JPG), 

and then I get all this empty rows 
![Picture_3](https://user-images.githubusercontent.com/67363842/85520400-292a0c00-b603-11ea-9149-c04471d695dc.JPG)

What am I doing wrong?

**Comment by kseniiaguzeeva** [comment]
Looks like a bug. Thank you for the report.
(To reproduce both MySQL and PostgreSQL can be used)

**Comment by uslss** [comment]
verified
