### ISSUE TITLE
如何输出存储过程返回的结果集，如何支持多标签同时查询返回结果集

### ISSUE THREAD

**Issue by mjj3610** [dbeaver/dbeaver#9096]
#### System information: 
- Operating system (distribution) and version
- DBeaver version

#### Connection specification:
- Database name and version

**Comment by kseniiaguzeeva** [comment]
Could you please write your ticket in English, tell your Database, DBeaver version

**Comment by mkgrgis** [comment]
This is very abstract question without RDBMS specification.
这个问题是非常抽象的。 答案是不可能的。

**Comment by uslss** [comment]
there are not any updates on issue. Ticket will be closed.
If issue is still actual for you - feel free to reopen the ticket
