### ISSUE TITLE
[Grid] Ordering or filtering by column with alias throws an error

### ISSUE THREAD

**Issue by coldenol** [dbeaver/dbeaver#9099]
#### System information: 
- Operating system (distribution) and version: Windows, Version 10.0.18362, Build 18362
- DBeaver version: 7.1.1.202006211844

#### Connection specification:
- Database name and version: MySQL 5.7, AWS Aurora

#### Describe the problem you're observing:
Trying to order of filter the result set (using header icons) by a column with alias leads to an error because the wrapping query uses the column's name instead of its alias.

![Screenshot_4](https://user-images.githubusercontent.com/49859188/85577349-d3288900-b641-11ea-8916-169f7f42d519.jpg)

**Comment by coldenol** [comment]
But it is not reproducible on every query. For example the same query but without the last JOIN orders and filters fine (I event do not see the wrapping query).

**Comment by kseniiaguzeeva** [comment]
Could you please give a query example to reproduce?

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Ticket closed. If issue is still actual for you - feel free to reopen the ticket with additional info.
