### ISSUE TITLE
Generic driver: metadata model configration

### ISSUE THREAD

**Issue by r-richmond** [dbeaver/dbeaver#910]
#904 & its fix got me wondering about a better way for tying drivers to .dbeaver plugins.

Perhaps it would be more future proof / user friendly to have a dropdown option called "Use Database Plugin" in the Driver Manager config page with the default option being generic.

This would allow users to indicate which plugin should be used for a given driver, should class names change again in the future/ if there other drivers are used.

What are your thoughts?

p.s. I'm not sure what "Driver Type" is supposed to be as its only option is Generic.

![image](https://cloud.githubusercontent.com/assets/9246654/19810455/603888a4-9ce2-11e6-8725-8d5a8b0719e3.png)

**Comment by serge-rider** [comment]
This makes sense although it is related to Generic plugin, not to any driver. 
This config may be added in the "advanced driver parameters".

**Comment by r-richmond** [comment]
Ahh didn't realize that Adv. Parameters were Dbeaver config options. Given that it seems like a good place. Although more hidden than Driver Type. 

What is the Driver Type Option? Its name indicated that it might be related to what I was suggesting but the dropdown only had generic. (And the postgres connection only had the postgres option)

![image](https://cloud.githubusercontent.com/assets/9246654/19811536/b12d031c-9ce6-11e6-8a5c-cd616c49df8a.png)

**Comment by serge-rider** [comment]
Driver type makes sense if you are create a new driver. Otherwise it has only one option.

Driver type == DBeaver driver extension. Currently they are: Generic, Oracle, DB2, MySQL, PostgreSQL, Exasol. All other drivers (including Teradata, SQL Server, etc) are based on Generic extension.
In 99% of cases you need Generic to create a new driver.

**Comment by serge-rider** [comment]
Now I can't realize what should be done here.
Is this still makes sense?

**Comment by r-richmond** [comment]
Yea it has been a while; I had to re-read this and 904 to remember.

Summary: Teradata changed the name of their class in their JDBC Driver. This broke Dbeaver's `light` integration with teradata because you use a [static list](https://github.com/serge-rider/dbeaver/commit/550a1eb80cc9b6f23f4f8eb5b892aa4d25c1b4b4) to determine which .dbeaver/plugin to use for a given connection.

Goal: Prevent the tool from "breaking" if a database provider changes the name of their JDBC class in the future.

Suggestion: Allow users to configure the .dbeaver/plugin to use in the driver manager page. (Originally I thought this belonged in the Driver Type drop down but you explained earlier in this thread that this wasn't the appropriate place). I would recommend a dropdown of some sort if placed in the advanced parameters page or main page.

does that make sense?

p.s. congrats on the release of the enterprise version

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on the ticket for a long time.
If it is still actual for you - feel free to reopen it with additional info
