### ISSUE TITLE
Improper autocomplete for column names in the Results panel

### ISSUE THREAD

**Issue by D3SL** [dbeaver/dbeaver#9101]
#### System information: 
- Win10 18363.836
- DBeaver 7.0.4
- no extensions

#### Connection specification:
NA, Dbeaver UI related issue

#### Describe the problem you're observing:
When using autocomplete to enter column names in the Results Panel the autocomplete insertion neither completes nor replaces the partially typed entry. EG If I were to begin to type the name of ```ColumnFoo``` and choose the autocomplete I would be left with ```ColColumnFoo```.  There's an option to fix this behavior in the SQL editor under SQL Completion but I haven't been able to find anything for this part of the UI.

#### Steps to reproduce, if exist:
Run a SQL query, open the Results panel, open Grouping, select ```Edit Grouping Columns```, begin typing a column name, choose one of the autocomplete options.

#### Include any warning/errors/backtraces from the logs
NA, user interface related issue

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
verified
