### ISSUE TITLE
Connection address isn't shown for local connection in DB Navigator

### ISSUE THREAD

**Issue by Ferrox12** [dbeaver/dbeaver#9102]
Hi,
with the last update of Dbeaver I have seen that near the connection's name it appears the address of the database.
I noticed that not in every connection this is activated/implemented. Why?
Is a bug or a wrong configuration?

**Comment by uslss** [comment]
Hi @Ferrox12 , can you tell for which connection address isn't shown? thanks in advance

**Comment by Ferrox12** [comment]
I use only OracleDB connection

**Comment by uslss** [comment]
Is it something special in database where host isn't visible? probably they are local?

**Comment by Ferrox12** [comment]
Yes they are local

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
