### ISSUE TITLE
Set default connection on editor not accept

### ISSUE THREAD

**Issue by nextstage-brasil** [dbeaver/dbeaver#9108]
To play:

Open an editor, and the transaction manager.

Select any database except postgres as active.

Run in the editor:
SET application.user_type TO '1.11.2'
and note the connection used in the transaction manager: Main <postgres>
![dbeaver-2](https://user-images.githubusercontent.com/12989226/85802744-f162b780-b71b-11ea-8ef1-97d3142f6f18.png)

Even with the change of the active base, the execution occurs in the transaction with the postgres connection.

I don't speak English, I used an online translator to write. 

![dbeaver-1](https://user-images.githubusercontent.com/12989226/85802771-03445a80-b71c-11ea-901b-eb375cf18456.png)
![dbeaver-2](https://user-images.githubusercontent.com/12989226/85802775-03dcf100-b71c-11ea-901b-b9960595f990.png)

**Comment by nextstage-brasil** [comment]
Na versão dbeaver-ce-6.3.0 isso não ocorria.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by nextstage-brasil** [comment]
Hello! I can't update to the newer versions since this error. Any adjustment forecast? I am still using version 6.3 for this reason.

I just tested v.7.1.4 and the problem continues

**Comment by nextstage-brasil** [comment]
anxious to be able to update a version. I'm still using 6.3

**Comment by kseniiaguzeeva** [comment]
Feel free to download https://dbeaver.io/download/. 7.1.5 is actual version now.

**Comment by kseniiaguzeeva** [comment]
Could you please tell is it actual for you in 7.1.5?

**Comment by LonwoLonwo** [comment]
No answer for a long time. If the error still occurs, then you are free to reopen the ticket

**Comment by nextstage-brasil** [comment]
Hello! I downloaded the new versions and the problem still remains. When using, for example:

set audit.application_name to 'DEV';

The connection used to update the table does not recognize this.

**Comment by nextstage-brasil** [comment]
Video with the error:

https://youtu.be/j95uwoD3KHo

**Comment by LonwoLonwo** [comment]
@nextstage-brasil thanks for video. how about [error logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by nextstage-brasil** [comment]
Same condition in version 7.2.2.

Steps to reproduce:

Table A has a trigger where when updating, it activates the audit.if_modified_func () function. This reads the current_setting ('audit.application_name') variable. This variable is defined in the editor:
set audit.application_name to 'DEV';

When I open the table and update a value, I get the message that the variable audit.application is not defined.

This is because the connection used in the query editor is not the same used in the visual editor of the table, as shown in the video.

**Comment by nextstage-brasil** [comment]
Hi! managed to reproduce?

**Comment by nextstage-brasil** [comment]
Same condition in version 7.2.5

**Comment by LonwoLonwo** [comment]
Please send DDL tables, triggers and "SET" commands for testing, so that we can reproduce the problem

**Comment by nextstage-brasil** [comment]
Here is the backup of the sample base:
https://1drv.ms/u/s!AmnkL7HXU9WavrBNtK3VvKH_J1bN3A?e=cQwGwO

Here is a video demonstrating the problem:
https://youtu.be/LG9ImZOMKLo

The "SET" Commands:
rollback;
set application."name" to 'DEV';
set application."user" to '4';
begin;
commit;


To reproduce:
Create a connection to more than one database, and set "postgres" as the
default database.
Within the operation, use the option to set active for the database
"dbeaver_issue".

**Comment by nextstage-brasil** [comment]
Hi.Anything I can help?

**Comment by LonwoLonwo** [comment]
Hello @nextstage-brasil 
Can you please try the new DBeaver version? Maybe something changed.
https://dbeaver.io/

**Comment by nextstage-brasil** [comment]
Hello!
problem still persists

Em sex., 11 de jun. de 2021 às 08:01, Anastasiya ***@***.***>
escreveu:

**Comment by nextstage-brasil** [comment]
YEEEESSSS!!! Solved!!!

Very very Thanks!!!
