### ISSUE TITLE
Bug: Ctrl+Enter executes query below in there is space at the line end

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#9109]
I think this was starting happening in 7.1.1

Case:
- I have 2 queries one below another
- if you add space at the end of 1st query and press ctrl+ enter query below is executed 

This is very misleading. Expected scenario is to execute query line is highlighted or above (in case of newline)
See screen below 

![image](https://user-images.githubusercontent.com/5410448/85827452-9fa34700-b786-11ea-9d49-fd26b2482d86.png)

**Comment by nmat** [comment]
I think this is a duplicate of: https://github.com/dbeaver/dbeaver/issues/9078

its said to be milestoned for 7.1.2

**Comment by uslss** [comment]
@maciey thanks for the bug report
Ticket is closed as a duplicate of #9078 .
