### ISSUE TITLE
Add autocomplete after Select statement of type: SELECT * FROM table_name

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9111]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.1

#### Describe the problem you're observing:
Autocomplete offers nothing after Select statement of type: SELECT * FROM table_name (e.g. where, order by).

#### Steps to reproduce, if exist:
1. Write a select statement (e.g. for MySQL SELECT * FROM sakila.actor)
2. Place cursor after the last word
3. Press Space
4. Press Ctrl+Space

Actual result: **no proposals** popup appears
Expected: the dropdown appears with a list of words which suite to continue the statement.

**Comment by kseniiaguzeeva** [comment]
Still can reproduce using steps above.
(build 7.1.1.202006290840, checked in MySQL, PostgreSQL)
- if press ctrl+Space  right after a table name, popup autocomplete appears with schema objects with the table name in objects name
- if press Space right after a table name, then press ctrl+Space, popup **no proposals** appears

**Comment by uslss** [comment]
Seems to be fixed for now.
Proposals appear on typing.
Where is automatically sugggested on <kbd>Ctrl+Space</kbd>
