### ISSUE TITLE
Oracle - add Trigger Status information to Object Properties

### ISSUE THREAD

**Issue by db2zosuser** [dbeaver/dbeaver#9112]
When displaying Table Triggers at object properties tab, the current trigger status (valid/invalid) is not displayed. One needs to query it manually. 

Would be nice to have information if trigger is valid or not directly in object properties. If possible for better visibility marked with green or red icon.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
verified
