### ISSUE TITLE
Netezza view definition not found;

### ISSUE THREAD

**Issue by dmcfarlane-uk** [dbeaver/dbeaver#9116]
hi,

 i am very new to dbeaver, so may well have missed a 'fix' for this - currently have installed version -7.1.1.202006231038

we have schemas within our Netezza environment disabled/not active.

i have created a view and with the view ddl in the sql editor, i am still not able to generate a view ddl via dbeaver. The 'work around' is fine for the moment but not ideal, especially when there is a function to do this which does ot work..

rgds Dave

**Comment by uslss** [comment]
Hi @dmcfarlane-uk ,
cannot reproduce it. Probably some special steps are needed?
![image](https://user-images.githubusercontent.com/31996417/87931362-5cd94400-ca92-11ea-8acd-fb6b546ae510.png)

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Ticket closed. If issue is still actual for you - feel free to reopen the ticket with additional info.
