### ISSUE TITLE
Cant generate a SQL script

### ISSUE THREAD

**Issue by YV38** [dbeaver/dbeaver#9117]
System information:
Ubuntu 20.04
7.1.1
None

Connection specification:
Oracle 12c 12.2.0.1.0
Oracle JDBC 12.2.0.1.0

Describe the problem you're observing:
Hello, I'm currently on 7.1.1 and before, I was able to generate the SQL insert script by using the rigth click on the result after a select request. This option was at the bottom of the menu (after the right click).

**Comment by p91paul** [comment]
based on my colleague experience, this was fixed by an hotfix version that is still marked as 7.1.1 but was released a few days later. Try redownloading and reinstalling.

**Comment by Robertiano** [comment]
I redownloaded and reinstalled, and the issue is there yet.
Downloaded from https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb

System information:
Ubuntu 20.04
Version 7.1.1.202006211844
None

**Comment by uslss** [comment]
@Robertiano 
please, check it against recent version (7.1.3)

**Comment by Robertiano** [comment]
I did it, it works!! Thanks!!
