### ISSUE TITLE
Data editor: extra double-click behavior

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#9118]
It would be handle to support new double-click behaviors:
1. Copy cell value
1. Copy cell value + insert it in the active SQL editor in SQL format.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/85888511-64d6f880-b7f2-11ea-9526-70ef757951be.png)

**Comment by uslss** [comment]
verified
