### ISSUE TITLE
Check expression field in Check constraints properties truncates long expressions

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9122]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.2 EA

#### Connection specification:
- Database name and version MySQL 8, Maria 10.3

#### Describe the problem you're observing:
Check expression field in Check constraints properties truncates the long Check constraint expression

Steps:
a. Open tab check contraints for a table (e.g create a table:
CREATE TABLE t2 (name VARCHAR(30) CHECK (CHAR_LENGTH(name)>2), start_date DATE, 
  end_date DATE CHECK (start_date IS NULL OR end_date IS NULL OR start_date<end_date));
b. Expand column **check expression** (e.g. for end_date)
![image](https://user-images.githubusercontent.com/51405061/86025102-7e688200-ba36-11ea-8ffd-1be87a0786f9.png)

**Comment by LonwoLonwo** [comment]
https://stackoverflow.com/questions/63741335/how-to-get-long-check-constraint-expression-clause-mariadb

**Comment by LonwoLonwo** [comment]
This is MariaDB bug, unfortunately. (Not MySQL. MySQL is fine).  Use DDL tab to see all check constraint expression.
