### ISSUE TITLE
Place Segment size under Extract type in Export settings

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9124]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.2 EA

#### Describe the problem you're observing:
Please place Segment size under Extract type in Export settings
![dbeaver_8Y7nsRgwM4](https://user-images.githubusercontent.com/51405061/86031389-6eed3700-ba3e-11ea-8b31-96bbffce1cb8.png)
#### Steps to reproduce, if exist:
Open **Settings** step of Export wizard

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/86339249-067ba100-bc5c-11ea-89a1-2fce458e2a0b.png)
