### ISSUE TITLE
Database Navigator for Exasol database runs for a long time to build all the objects

### ISSUE THREAD

**Issue by kamal-1** [dbeaver/dbeaver#9128]
**Is your feature request related to a problem? Please describe.**
Building Database Navigator tree for Exasol database in DBeaver takes a lot of time. Tested with version 7.0.3, 7.0.5 & 7.1.1. 

- In version 7.0.3, If user expanded the Tables tree under the schema, metadata retrieval stopped after building the list of all tables.
- In Version 7.0.5 & 7.1.1, if user expanded the Tables tree under the schema, the metadata retrieval loops through each of the tables and fires queries for Columns and Indicies. The database navigator tree keeps does not return anything back until all the metadata is retrieved for all tables.

**Describe the solution you'd like**
The behavior should be the same as version 7.0.3 where the only the top level tree should be retrieved and when user expands on the next level, then the metadata should be retrieved for that level. This will improve the load time and the user experience.

**Describe alternatives you've considered**
Downgraded DBeaver from version 7.1.1 to 7.0.3.

**Additional context**
If a particular schema has a lot of tables, approx. 350 in our case, the Database Navigator ended up firing over 700 queries to retrieve the metadata. The Database Navigator didn't show any objects till everything was loaded.

**Comment by Sargul** [comment]
If you mean the simple open of tables dropdown this should be fixed with 7.1.2
![image](https://user-images.githubusercontent.com/5595511/86559823-2f9e7900-bf5d-11ea-96c3-795b2ff29b2c.png)


However if you open schema properties by double clicking information like size, creation date etc have to be fetched one by one as there is an anomaly in the Exasol Optimizer regarding access and joins on meta data tables.

This was true until Exasol version 6.1.3 as it seems that this issue has been fixed by [EXASOL-2482](https://www.exasol.com/support/browse/EXASOL-2482).

I will have a look into speeding up schema/table details in version 7.1.3

**Comment by kamal-1** [comment]
> If you mean the simple open of tables dropdown this should be fixed with 7.1.2
> ![image](https://user-images.githubusercontent.com/5595511/86559823-2f9e7900-bf5d-11ea-96c3-795b2ff29b2c.png)
> 
> However if you open schema properties by double clicking information like size, creation date etc have to be fetched one by one as there is an anomaly in the Exasol Optimizer regarding access and joins on meta data tables.
> 
> This was true until Exasol version 6.1.3 as it seems that this issue has been fixed by [EXASOL-2482](https://www.exasol.com/support/browse/EXASOL-2482).
> 
> I will have a look into speeding up schema/table details in version 7.1.3

Thanks @Sargul. I tested with version 7.1.2 and it fixes the issue. However it introduced a new issue. The table list is now randomized instead of being ordered by table name.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by Sargul** [comment]
Hi @kamal-1,

this should be fixed with the next minor version.

Fix one bug introduce another - great ;-)

**Comment by uslss** [comment]
verified

**Comment by kamal-1** [comment]
Thanks @Sargul
