### ISSUE TITLE
SSH configuration with env variable is overwritten with variable value after connecting

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#9134]
#### System information: 
- Operating system (distribution) and version: mac os 10.15.4
- DBeaver version 7.1.1

#### Connection specification:
- Database name and version: postgres 12.2
- Driver name: default
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
In an SSH network configuration using an environment variable - the variable gets overwritten with its value after connecting.

#### Steps to reproduce, if exist:
I defined a a connection which uses an SSH network configuration.
Before connecting - the private key path is shown correctly
![image](https://user-images.githubusercontent.com/18515297/86246882-661e7180-bbb4-11ea-923a-d93c535fe931.png)
After connecting to the database, it gets resolved to the actual value:

![image](https://user-images.githubusercontent.com/18515297/86248106-16d94080-bbb6-11ea-8b2b-cf1792907d23.png)

Then if I edit the SSH network configuration - it will save it with the resolved value.

This will sometimes also reflect as a change in `data-sources.json`

One more thing that bothers me regarding `data-sources.json` - this file is committed to my repository and I monitor changes. Since json keys do not preserve order, sometimes the connection and their parents change by dbeaver, so from:
![image](https://user-images.githubusercontent.com/18515297/86246552-daa4e080-bbb3-11ea-820a-99aab7ca115c.png)
It's now
![image](https://user-images.githubusercontent.com/18515297/86246574-e1335800-bbb3-11ea-8d31-7fbad9f6b525.png)
And the next restart it might change again. Please prevent key reordering or use arrays which persist order.

**Comment by uslss** [comment]
thanks for the bug report.
_note: reproducible for profiles only_

**Comment by uslss** [comment]
verified
