### ISSUE TITLE
Bug on delete database (postgres)

### ISSUE THREAD

**Issue by zarpelon** [dbeaver/dbeaver#9139]
If u set the default database on edit connections (postgres) and mark "show all databases"

After u can try set other db with default and try delete the default database setting and get an error.

**Comment by Griha3212** [comment]
I also have this bug. What version do you use? For me, it's 7.1.1

**Comment by Griha3212** [comment]
Ok, it's not a bug. Just in tour connection type another database. Now you can delete previous default database.

**Comment by uslss** [comment]
hi @zarpelon ,
cannot reproduce it. Could you provide more clear steps that can help to reproduce an issue?
Thanks in advance

**Comment by zarpelon** [comment]
Sorry guys, I will post here some images to reproduce.

**Comment by zarpelon** [comment]
![1](https://user-images.githubusercontent.com/264762/86526079-ac4e2c00-be65-11ea-939d-3ad0bce7c195.png)
![2](https://user-images.githubusercontent.com/264762/86526080-ace6c280-be65-11ea-9d7c-d48c7fde4c83.png)
![3](https://user-images.githubusercontent.com/264762/86526081-ad7f5900-be65-11ea-8db7-87d2df546e3e.png)
![4](https://user-images.githubusercontent.com/264762/86526083-ad7f5900-be65-11ea-974b-65c1bfe9af8e.png)

**Comment by uslss** [comment]
thanks for clarification and bug report

**Comment by serge-rider** [comment]
You don't need to change default database - this won't help if you are already connected to a database you want to delete.
If you set `my_database` as main database in connection dialog then you won't be able to delete it, even if you will change default database.

Set "Database" to "postgresql" in the connection dialog. Reconnect - now you can delete "my_database".

**Comment by zarpelon** [comment]
What if I only have one database and want to leave it as a default? Will I have to create another database just to be able to delete the default?

**Comment by kseniiaguzeeva** [comment]
Yes, you are correct. Do you have any other questions regarding this situation?

**Comment by zarpelon** [comment]
Not right now.

**Comment by LonwoLonwo** [comment]
since there are no questions, the ticket is closed
