### ISSUE TITLE
The new query could be executed after reconnect only if the previous query was canceled

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9142]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.1.2 EA

#### Describe the problem you're observing:
The new query could be executed after reconnect only if the previous query was canceled
#### Steps to reproduce, if exist:
1. Open SQL editor and execute quite slow query
1. Cancel query - an error that connection is closed appears (expected, implemented in the scope of #9121)
1. Try to execute query once again - an error that connection is closed appears once again. The connection could be executed only after the connection will be invalidated.

**Comment by tati-kru** [comment]
It is database specific behavior. We close connection on query cancel for some databases. It works as expected.
