### ISSUE TITLE
Custom filter settings aren't applied in special case

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9145]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.2

#### Connection specification:
- Database name and version SQLite, PostgreSQL

#### Describe the problem you're observing:
Filter with the unchecked column isn't saved
#### Steps to reproduce, if exist:
1. Open table (e.g. albums)
1. Open Custom filters and uncheck any column - column isn't shown
1. Save filter
1. Reopen the table - All columns are shown, filter isn't applied

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
