### ISSUE TITLE
A small functional problem. Unable to display field comment description information

### ISSUE THREAD

**Issue by ProjectMoss** [dbeaver/dbeaver#9148]
This problem is very troublesome to me, when connecting to the clickhouse database, the field comment description information cannot be displayed

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
I've create a feature request in ClickHouse driver repo: https://github.com/ClickHouse/clickhouse-jdbc/issues/480

**Comment by serge-rider** [comment]
Will be fixed in clickhouse-jdbc 0.2.5

**Comment by serge-rider** [comment]
Fixed by #11195

**Comment by uslss** [comment]
verified
