### ISSUE TITLE
Incorrect column creation

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9150]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.2

#### Connection specification:
- Database name and version Firebird

#### Describe the problem you're observing:
Error appears when trying to create Table in firebird - any created table transforms to table Country (in my case :) )
![2020-07-03_13h12_19](https://user-images.githubusercontent.com/31996417/86460052-65aae580-bd30-11ea-8ab3-0ecb9db956d9.gif)

**Comment by serge-rider** [comment]
Fixed (there was a bug in FB table refresh)
