### ISSUE TITLE
[Oracle] Import: Auto-assign btn shows packages in schemas

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9152]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.2 EA

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
Import: Auto-assign btn shows packages in schemas
#### Steps to reproduce, if exist:

1. Select import
2. Select table
3. Press Next
4. Press Auto-assign
5. Expand schema in Oracle database

Actual result: packages are displayed.

![dbeaver_i8QP8Zjav4](https://user-images.githubusercontent.com/51405061/86463359-03ed7a00-bd36-11ea-8dad-1ef0b7cb5683.png)

Expected: the schema should be selected.

**Comment by uslss** [comment]
not actual anymore
