### ISSUE TITLE
Incorrect Column icon is shown in Context Menu

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9156]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.2

#### Describe the problem you're observing:
For now, Column icon is shown from the context
![image](https://user-images.githubusercontent.com/31996417/86477692-a5ce9000-bd51-11ea-9888-8bed9b6796c8.png)
It should be shown like it is shown in, e.g. Table Context Menu
![image](https://user-images.githubusercontent.com/31996417/86477764-c8f93f80-bd51-11ea-84a9-69942df0d997.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
