### ISSUE TITLE
Inline edit does not work anymore

### ISSUE THREAD

**Issue by kamaladafrica** [dbeaver/dbeaver#9158]
#### System information: 
- Ubuntu 18.04.4 LTS
- DBeaver 7.1.1.202006211844

#### Connection specification:
- Oracle 11g
- ojdbc7

#### Describe the problem you're observing:
Colums are readonly and inline edit is disabled. Before the last update, inline edit worked well.
Connecting to MySQL, inline edit works correctly.

#### Steps to reproduce, if exist:
Connect to an oracle database. 
Double click on a table and go to Data tab.
Try to edit a cell or delete a row

#### Include any warning/errors/backtraces from the logs
Message in statusbar says "Column is readonly..."

**Comment by kamaladafrica** [comment]
I also tried to File > Reset UI settings...

**Comment by p91paul** [comment]
Try redownloading and reinstalling. An hotfix version (still 7.1.1) was released to fix this bug.

**Comment by uslss** [comment]
@kamaladafrica thanks for the bug report. It is already resolved in the scope of #9060 .
please follow the instruction in @p91paul [comment](https://github.com/dbeaver/dbeaver/issues/9158#issuecomment-653798677)
