### ISSUE TITLE
Record details not displaying correctly via spatial view

### ISSUE THREAD

**Issue by timneedham** [dbeaver/dbeaver#9160]
#### System information: 
- Operating system (distribution) and version: `Ubuntu 18.04.3 LTS`
- DBeaver version: `7.1.1.202006211844`
- Additional extensions: `None`

#### Connection specification:
- Database name and version: `PostgreSQL 11.6`
- Driver name: `PostgreSQL JDBC Driver`
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  `No`

#### Describe the problem you're observing:

When clicking on a point in spatial view (which is awesome BTW! :heart: ) it now displays record details as an array of characters, it seems?

![image](https://user-images.githubusercontent.com/1216632/86494726-45018080-bd6e-11ea-9cc4-8ffd8a129fa8.png)

Here the record data is  `{id=e405b05boec ...}`... all the content is there, just listed out one character at a time!

So it is sort of usable, and it's such a great feature!

#### Steps to reproduce, if exist:

Doesn't seem to matter which map background or SSRID is used.

#### Include any warning/errors/backtraces from the logs

Nothing obvious.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed. This issue happened only in Spatial view.

In Value panel it worked ok.

**Comment by uslss** [comment]
verified
