### ISSUE TITLE
[Oracle] Table Index cannot be deleted

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9163]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.2EA
#### Connection specification:
- Database name and version Oracle

#### Steps to reproduce, if exist:
1. Open Indexes tab for a table (e.g. in schema HR)
2. Create an index
3. Drop Index via UI

Actual result:
1. Error appears ORA-01418: specified index does not exist
2. Wrong data in Declaration tab
3. Index is not deleted

![dbeaver_x1Zy9388db](https://user-images.githubusercontent.com/51405061/86510192-41b1d780-bdf6-11ea-8e84-3f695db1142d.png)

**Comment by serge-rider** [comment]
It works for current user schema only. Seems to be a specific of test environment.
