### ISSUE TITLE
Cannot set the default database for the "Read-only connection"

### ISSUE THREAD

**Issue by coldenol** [dbeaver/dbeaver#9167]
#### System information: 
- Operating system (distribution) and version: Windows, Version 10.0.18362, Build 18362
- DBeaver version: 7.1.1.202006211844

#### Connection specification:
- Database name and version: Database name and version: MySQL 5.7, AWS Aurora
- Driver name: JDBC

#### Describe the problem you're observing:
If a connection is marked as "Read-only connection" in Connection Settings > General it is impossible to set the default database neither from the Database Navigator nor in the panel "Active catalog/schema".

![Screenshot_5](https://user-images.githubusercontent.com/49859188/86511451-0d441880-be02-11ea-80d0-55c49957170b.jpg)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed.
Generally this looks like a driver/server bug as changing active schema doesn't change database state.

Anyhow, now we disable readonly mode just for active schema change operation (and then switch back to readonly)

**Comment by uslss** [comment]
verified
