### ISSUE TITLE
Not all options are shown if export is started from DB Navigator

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9168]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.2 EA

#### Describe the problem you're observing:
Selected columns/rows only options aren't shown if export is started from DB Navigator
![image](https://user-images.githubusercontent.com/31996417/86519163-d50ffa80-be40-11ea-8cf7-899c7ab452df.png)

**Comment by serge-rider** [comment]
It is not a bug. Selected columns/rows options don't make any sense when exporting from navigator. 
Columns/rows are in data viewer only.
