### ISSUE TITLE
Error when trying to search and replace \r in SQL Editor

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#9170]
#### System information: 
- Operating system (distribution) and version: Windows Server 2016 Datacenter 64-bit
- DBeaver version: 7.1.1.202006231904
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11 on Aurora RDS
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
In SQL Editor, when trying to search & replace \r with any string I get error:
"Incompatible line delimiter near line [xxx]"

**Comment by kseniiaguzeeva** [comment]
Could you please send a printscreen/video of your search settings?

**Comment by yonisade** [comment]
Issue was apparently resolved in v7.1.2

**Comment by yonisade** [comment]
I was able to recreate this issue.
Apparently this happens only in the Properties "Source" tab:
![image](https://user-images.githubusercontent.com/21174251/87289850-dc509b80-c505-11ea-8ba0-32c8350d9fee.png)

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it in Procedire DDL. Could you please try 7.1.3 version https://dbeaver.io/download/?

**Comment by uslss** [comment]
issue closed.
If it is still actual - feel free to reopen it
