### ISSUE TITLE
Output tab doesn't show RAISE messages from triggers when inserting data via data grid

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#9174]
#### System information: 
- Operating system (distribution) and version: mac 10.15.4 
- DBeaver version 7.1.1, 7.1.2

#### Connection specification:
- Database name and version postgres 12.2

#### Describe the problem you're observing:
Messages from RAISE statements in Triggers are not shown if modifying the table via the data grid and saving.
If I create a script from the modifications - the lines are shown properly.

#### Steps to reproduce, if exist:
```
SET client_min_messages=notice; -- it's the default

CREATE TABLE foo(
    id int,
    txt TEXT
);

CREATE OR REPLACE FUNCTION trgfn_foo()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE NOTICE 'we should see this in the Output tab';

    RETURN NULL;
END; $$;

CREATE TRIGGER foo_trg
AFTER INSERT ON foo
FOR EACH ROW 
EXECUTE FUNCTION trgfn_foo();


INSERT INTO foo(id, txt)
VALUES (1,'a'); -- "we should see this in the Output tab" will be shown in the output tab

SELECT * FROM foo;

--now duplicate the existing row in the data grid and save -->nothing is added to the Output tab
```

**Comment by serge-rider** [comment]
I can't reproduce this. I see all messages from trigger in the Output tab:
![image](https://user-images.githubusercontent.com/6398845/88339879-7d7bf500-cd43-11ea-933f-1f3d43e00405.png)

What PostgreSQL driver version do you use? (you can get driver version in the Test Connection dialog).

**Comment by pyrocks** [comment]
Did you do the insert from the data grid or just running the insert on the sql editor? Sql editor works fine, data grid doesnt. I use the default driver.

**Comment by kseniiaguzeeva** [comment]
@pyrocks Output is not supposed to show data if the action is performed in Data Grid. Would you like to see Output Viewer in Data Editor?

**Comment by pyrocks** [comment]
I don't understand why output is not supposed to show when doing operations from data grid. Why does it matter, for output purposes, if I inserted through the editor or through the grid? An insert is an insert is an insert - and if an insert fires a trigger which raises a notice it should be displayed in the output regardless of how the insert was performed.

**Comment by serge-rider** [comment]
This makes sense.

**Comment by serge-rider** [comment]
Data edit logging was added

**Comment by kseniiaguzeeva** [comment]
It doesn't work if changes are made in Data Editor (but everything is ok in ResultSet)

**Comment by serge-rider** [comment]
Do you mean table data editor? Is is not supposed to work there as there is no Output tab there at all.
This feature is about SQL editor and Results tabs only.

**Comment by kseniiaguzeeva** [comment]
Ok, implemented.
