### ISSUE TITLE
Deleting columns in sqlite... causes sql syntax error

### ISSUE THREAD

**Issue by katsar0v** [dbeaver/dbeaver#9176]
I just installed dbeaver and created an sqlite database to have a play with it. I created some columns and wanted to delete one, but it fails:

![image](https://user-images.githubusercontent.com/7236157/86589097-44930080-bf8d-11ea-92ad-aeddf7f50bc9.png)
![image](https://user-images.githubusercontent.com/7236157/86589106-4a88e180-bf8d-11ea-9d27-e056ef39ac94.png)

**Comment by uslss** [comment]
Hi @katsar0v ,
SQLite does not support ALTER TABLE DROP COLUMN statement. You could find how to do it [here](https://www.sqlitetutorial.net/sqlite-alter-table/)
BR

**Comment by katsar0v** [comment]
Then why did dbeaver allow me to delete columns, and if possible, why did the wrong syntax was written?

**Comment by uslss** [comment]
Feature request to solve this is already created #5447

**Comment by katsar0v** [comment]
Ok, closed an issue because of "solved" or "won't solve"? This is definitely a bug and unwanted behavior in dbeaver

**Comment by uslss** [comment]
@katsar0v issue is closed as a duplicate of already existing feature request. Drop Column behaviour will be implemented in scope of #5447

**Comment by favored-cruelty21** [comment]
> Then why did dbeaver allow me to delete columns, and if possible, why did the wrong syntax was written?





https://stackdev.space/questions/what-is-the-reason-behind-receiving-a-syntax-error-near-the-alter-keyword-when-executing-my
