### ISSUE TITLE
It is impossible to connect to Oracle database as admin user

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9177]
#### System information: 
- Operating system (distribution) and version
- DBeaver version Build #3538 

#### Connection specification:
- Database name and version Oracle
#### Describe the problem you're observing:
It is impossible to connect to Oracle database as admin user

#### Steps to reproduce, if exist:
Try to connect to sample database using creadentials from https://github.com/dbeaver-corp/dbeaver-devops/wiki/Sample-databases#oracle-122-ee

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
