### ISSUE TITLE
SQL Server: how to add a login via the GUI

### ISSUE THREAD

**Issue by wmeitzen** [dbeaver/dbeaver#9179]
Using the GUI, how do you add logins to a SQL Server instance, and how do you add users to a SQL Server database?

Edit: I'm using CE version 7.1.2.

Forgive me if this has already been asked.  I couldn't find an answer.

**Comment by kseniiaguzeeva** [comment]
Do you use local SQL Server? 
Set Windows auth if you login to SQL Server by this way.
![dbeaver_8R91R3rm6S](https://user-images.githubusercontent.com/51405061/86746062-75ce0800-c043-11ea-80d4-75997599fd9d.png)

**Comment by wmeitzen** [comment]
Thanks, perhaps my question wasn't specific enough.  I know how to log in to a SQL Server database.  I want to know how to create a login to the instance.

For example, for PostgreSQL, you can add a login: PG server name / PG database / Right-click Roles / Click "Create New Role."

How do you add a SQL Server login the same way you add a PG role?

**Comment by kseniiaguzeeva** [comment]
Now I see, thank you. This function is not implemented in DBeaver yet. I will change the label on feature request.

**Comment by LonwoLonwo** [comment]
We added support of sql server logins in DBeaver 21.1.4
And in 21.1.5 we added support of logins creating, renaming and deleting.

**Comment by Matvey16** [comment]
Verified
