### ISSUE TITLE
Message Task error after restore a postgres database

### ISSUE THREAD

**Issue by zarpelon** [dbeaver/dbeaver#9182]
#### System information: 
- Ubuntu 20.20
- DBeaver 7.1.1

#### Connection specification:
- Postgres

#### Describe the problem you're observing:
When the restore process is over I get this error on the screen, even though he did the process successfully.

* Other: When the backup process is over, the window with success message does not appear as the main window.

![1](https://user-images.githubusercontent.com/264762/86726518-033c3880-c001-11ea-85ad-c07d2ce69064.png)

![2](https://user-images.githubusercontent.com/264762/86726514-020b0b80-c001-11ea-9e98-a18c539d974d.png)

**Comment by zarpelon** [comment]
Other issue, when the task error window is active, if you try click on "Windows/Show Views/Errors " to see the logs, doesnt' works fine.

**Comment by zarpelon** [comment]
Oh, I believe that is can be an update feature.

When the restore is completed, do not refresh the "tables" tab, I need press F5 to reload with new restored tables.

![3](https://user-images.githubusercontent.com/264762/86727349-be64d180-c001-11ea-9c34-5486762340fa.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
verified

**Comment by zarpelon** [comment]
Sirs, Can I comment here or I need to open a new issue? Is related on the same task.

Now we have a window with message success for backup and restore tools, but when these process are doned, the popups still behind the screen, like these examples:

![image](https://user-images.githubusercontent.com/264762/92958608-e416b880-f440-11ea-88ac-4127bc9f8484.png)

![image](https://user-images.githubusercontent.com/264762/92958672-03154a80-f441-11ea-9189-542d72633117.png)

**Comment by LonwoLonwo** [comment]
and do not close the window? is it unavailable? I don't quite understand yet what the problem is

**Comment by zarpelon** [comment]
The problem is that the success window is behind the process window. I only found this out when I dragged the process window aside.

If the user is waiting for the success window it does not appear. It always seems to be processing something.|

Make sense?
