### ISSUE TITLE
Eclipse Marketplace: DBeaver Community not compatible with eclipse 2020-06

### ISSUE THREAD

**Issue by fireandfuel** [dbeaver/dbeaver#9187]
As mentioned at Issue #9058 DBeaver is not compatible with eclipse 2020-06, see https://marketplace.eclipse.org/content/dbeaver. 

It can not be installed from the eclipse Marketplace. DBeaver EE 7.1.1 is compatible with eclipse 2020-06. 
Please update the Community version.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
as a workaround, you could install recent version using Update site URL https://dbeaver.io/update/latest/

**Comment by serge-rider** [comment]
Marketplace info was updated,

**Comment by uslss** [comment]
verified
