### ISSUE TITLE
Can't resize grid columns

### ISSUE THREAD

**Issue by facuhump2409** [dbeaver/dbeaver#9188]
![image](https://user-images.githubusercontent.com/32522610/86787074-1966ea80-c03b-11ea-9101-dbd1ac36147d.png)
Since i updated dbeaver to version 7.1.2 i'm not being able to resize columns to analyze data in a clearer way. This is a big issue to me, because i need to analyze big strings
Any help will be welcome :)

**Comment by uslss** [comment]
hi @facuhump2409 ,
unfortunately cannot reproduce it on win10. What OS do you use?
is it reproducible for all the columns type and databases?

**Comment by facuhump2409** [comment]
Im currently using ubuntu 18. But this problem appeared with the latest 7.1.2 release. Before i could resize the columns in any query from any database

**Comment by shalikashvili** [comment]
Confirming behavior reported by facuhump2409

On Linux Mint 19 Tara (Ubuntu 18.04), using Cinnamon desktop, Upgraded from 7.0.4 to 7.1.2 and could no longer resize panes or adjust column sizes. Made the UI unusable. Uninstalled dBeaver and re-installed 7.0.4, and all's well again.

**Comment by shalikashvili** [comment]
Further confirmation on Ubuntu 18.04 host using XFCE desktop, same anomalous behavior on 7.1.2, resolved by reverting to 7.0.4.

**Comment by GiancarloPanarese** [comment]
Hi there,

Same issue as per @facuhump2409 description after upgrading from 7.1.1 to 7.1.2, on Ubuntu 16.04 using Unity desktop.

**Comment by facuhump2409** [comment]
Problem solved in version 7.1.3 thanks

**Comment by borkie** [comment]
Same problem here on Debian 11 with Wayland
