### ISSUE TITLE
"Find Next" command stopped working in object source view

### ISSUE THREAD

**Issue by cesarmansur** [dbeaver/dbeaver#9191]
Hello.
I've just noticed that "Find Next" command (Ctrl + K shortcut) stopped working in object source view.
It's working fine in SQL Editor.
Could you please check this issue?

![image](https://user-images.githubusercontent.com/43681608/86798785-8ed8b800-c047-11ea-872e-256ae2baa77a.png)

I'm using DBeaver Eclipse Plugin (version 7.1.2), Windows 10 x64

![image](https://user-images.githubusercontent.com/43681608/86799804-b714e680-c048-11ea-96be-6c9d3f35fd40.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
