### ISSUE TITLE
HSQLDB UUID Data Type Error

### ISSUE THREAD

**Issue by vanDarg** [dbeaver/dbeaver#9193]
#### System information: 
- Operating system (distribution) and version
Windows 10 Home
- DBeaver version
Version 7.1.2.202007051953
- Additional extensions
none

#### Connection specification:
- Database name and version
HSQLB 2.5.1
- Driver name
JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
On any table I create having UUID as data type for a column, I can't enter values there without getting errors.
If I use the UUID generator from within DBeaver and try to save a new row, it throws "Unsupported value type".
If I copy a UUID from another program (or just the same, basically) and paste from clipboard, it throws ""SQL Error [3401] [22001]: data exception: string data, right truncation".
Previously entered data (in another dm manager) is shown without errors, as soon as I try to edit, I get the same problems.

#### Steps to reproduce, if exist:
Just create a table in a database with a UUID column and try to enter (correct) values and save them.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
