### ISSUE TITLE
How to ignore quoting for CSV tables?

### ISSUE THREAD

**Issue by johntreankler** [dbeaver/dbeaver#9194]
#### System information: 
- macOS Catalina Version 10.15.5
- DBeaver Version 7.1.2.202007051953

#### Connection specification:
- Flat files / CSV
- net.sourceforge.csvjdbc:csvjdbc:RELEASE

#### Describe your question:

I have a CSV table that is pipe-delimited, and there **is no** quote character.
The default quote character is the double-quote (") character, so rows in my table
with one double-quote character make the CSV driver error out.

**How do I tell DBeaver to ignore the quote character?**

In Connection Settings > Driver Properties have 
**separator |**
**quotechar "**

and this one:
quotestyle (with no value)

Can I set quotestyle to "none" or "false"?

**Comment by kseniiaguzeeva** [comment]
Do you want to import this table? Which database do you use?
You can configure import settings in Import wizard.
![dbeaver_i8aN5b8xBX](https://user-images.githubusercontent.com/51405061/87030321-1eb66780-c1ea-11ea-826f-64e77b75f95f.png)

**Comment by uslss** [comment]
there aren't any updates on issue for a long time. If it is still actual for you - feel free to reopen the ticket
