### ISSUE TITLE
Infinite Zero

### ISSUE THREAD

**Issue by VrigaChabibi** [dbeaver/dbeaver#9195]
#### System information: 
- Windows 10 Pro 1909 18363.900
- DBeaver version 7.1.1

#### Connection specification:
- PostgreSQL (Old)

#### Describe your question:
- It is often happen when I export number data-type. Decimal places are added infinitely even the data has no decimal places.
For example: 29385763 would be exported to 29385763.00000000000000000000000000000000000000000000000000000
The zeros given are more than tens of thousands, so the exported csv file size is insanely huge.
- Please help, maybe there are some settings messed up. Thank you.

**Comment by uslss** [comment]
hi @VrigaChabibi ,
could you post screenshot of your Data Formats settings? Thanks in advance
![image](https://user-images.githubusercontent.com/31996417/86952050-119e6780-c15b-11ea-99d0-7238cd123302.png)

**Comment by VrigaChabibi** [comment]
here it is.. I'm using global settings
![Annotation 2020-07-10 125837](https://user-images.githubusercontent.com/55678945/87118247-68df2d80-c26a-11ea-803d-a7a6100eeff8.png)

**Comment by uslss** [comment]
@VrigaChabibi , could you tell what db version do you use, what is your column type and to which format do you export the table?

**Comment by VrigaChabibi** [comment]
I'm not sure.. but on test connection it showed up PostgreSQL 8.2..
![Annotation 2020-07-24 152949](https://user-images.githubusercontent.com/55678945/88369441-94403d00-cd7f-11ea-8fb6-3e5b803877da.png)
Column type is NUMBER with specified length of 38,0
Exported using CSV format

**Comment by uslss** [comment]
cannot reproduce an issue.
If it is still actual for you - feel free to reopen it with additional info.
