### ISSUE TITLE
Exasol: implement discovery for error types

### ISSUE THREAD

**Issue by Sargul** [dbeaver/dbeaver#9200]
**Is your feature request related to a problem? Please describe.**
currently no ErrorType discovery is implemented in exasol and exasol does not have sqlstates

**Describe the solution you'd like**
implement Exasol specific error discovery so that connection retry logic is working for exasol

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Sargul** [comment]
Can be tested by 

```sql 
select current_session;
kill <session_id from sql>;
select current_session;
``` 
the second sql should not throw an error as a new session should be established (because a ErrorType.CONNECTION_LOST is issued)

**Comment by kseniiaguzeeva** [comment]
Tested. Thank you for help with the example.
