### ISSUE TITLE
ValueValidator is not working

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#9205]
For example in ORACLE Gather table statistics tool. Numbers can be entered, but they do not appear in query
![2020-07-08 12_30_00-DBeaver 7 1 2 - _orcl_ Script-4](https://user-images.githubusercontent.com/45152336/86919458-f0288600-c130-11ea-9b8f-f3acd0a3ae53.png)

**Comment by kseniiaguzeeva** [comment]
verified
