### ISSUE TITLE
Database Navigator does not show connection information.

### ISSUE THREAD

**Issue by mjjong** [dbeaver/dbeaver#9210]
#### System information: 
- Operating system (distribution) and version : Window 10 / 64 Bit
- DBeaver version : DBeaver 7.1.0 -> 7.1.2 Upgrade
- Java version : 1.8.0_251
- Additional extensions

#### Connection specification:
- Database name and version : MariaDB 10.2.29
- Driver name : MariaDB(Confirm Attachment)
![MariaDB Driver](https://user-images.githubusercontent.com/61495657/86997383-dcd8f180-c1e8-11ea-85e8-be95693d3315.png)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Database Navigator list does not appear after DBeaver upgrade.
Reinstallation will not solve the problem.
Creating a new connection does not show up in the list.
Please Help me.
![MariaDB Database Navigator Error](https://user-images.githubusercontent.com/61495657/86997356-cb8fe500-c1e8-11ea-8246-91d1cae8b2d9.png)

#### Steps to reproduce, if exist:
DBeaver 7.1.0 to 7.1.2 Upgrade(Install Type)

**Comment by uslss** [comment]
Hi @mjjong , probably you've got more than one project? If project is active, it is shown in DB navigator. 
Could you check if the project, where you're creating a new connection, is also an active project?
![image](https://user-images.githubusercontent.com/31996417/87048584-8d082380-c204-11ea-8d58-b6d6004febb0.png)

Thanks in advance for the response

**Comment by uslss** [comment]
there aren't any updates on issue for a long time.
If it is still actual for you - feel free to reopen the issue.
