### ISSUE TITLE
Bad UI rendering of creating connection dialog

### ISSUE THREAD

**Issue by ghostoy** [dbeaver/dbeaver#9211]
#### System information: 
- Operating system (distribution) and version: Windows 10 2004 (Chinese)
- DBeaver version: 7.1.2
- Additional extensions: No

#### Connection specification:
- Database name and version: Not related
- Driver name: Not related
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Not related

#### Describe the problem you're observing:
The dialog of creating connections renders badly on Windows 10. Some of the following issues could be observed randomly:

* Missing some input field, e.g. Server Host as below
![image](https://user-images.githubusercontent.com/471928/87008501-6ba03b00-c1f6-11ea-9eab-e1af5d6aefce.png)
* Extremely large dialog with extremely long input field
* Extremely small input field. Probably only 1 pixel in width.
![image](https://user-images.githubusercontent.com/471928/87008750-cb96e180-c1f6-11ea-969b-44ac01fed0fe.png)

I tried to switch between different JDKs as below, but no luck.

* adoptopenjdk-openj9
* oraclejdk14
* openjdk14

#### Steps to reproduce, if exist:
1. Click creating new connection
2. Choose a DB type

**Comment by ghostoy** [comment]
The issue happens under all default settings.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Please to reset UI settings (File>Reset UI settings)

**Comment by ghostoy** [comment]
@kseniiaguzeeva Not working. The issue happens on my fresh installation. And the font rendering is kind of buggy.

**Comment by humphreygao** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=565025

不关DBeaver的事，是Windows内测版的问题，SWT没和系统配合好，等下一个内测版。

**Comment by kseniiaguzeeva** [comment]
Thank you. Some users (#9180) have similar problem in 7.1.2. The problem should be in it.

**Comment by serge-rider** [comment]
Perhaps we need to revert to Eclipse 2020-03. New version has too many glitches, dark theme looks weird, etc.

**Comment by humphreygao** [comment]
本周不会有Windows内测版发布，也不确定下一版本可以解决该问题，所以请回退至Windows上一个版本。查看https://support.microsoft.com/zh-cn/help/12415/windows-10-recovery-options， 点击 **回退到以前版本的 Windows** 下的 **打开“恢复设置”** 按钮进入设置界面以回退至上一个版本。

This issue is not related to the version of Eclipse Platform(since Eclipse 2020-03 also has this issue), but related to the version of Windows 10.

You can solve this issue by going back to your previous version of
Windows. See
https://support.microsoft.com/en-gb/help/12415/windows-10-recovery-options to know how to recover your Windows to previous version.

**Comment by ghostoy** [comment]
Looks like it's related to my Windows Insider version. Thanks @humphreygao

**Comment by ghostoy** [comment]
MS released an [insider release (20175)](https://blogs.windows.com/windowsexperience/2020/07/22/announcing-windows-10-insider-preview-build-20175/) including fixes on font rendering. I'm testing if it fixes this issue.

**Comment by kseniiaguzeeva** [comment]
I'm happy to hear it!

**Comment by ghostoy** [comment]
Confirmed that 20175 fixed this issue.
