### ISSUE TITLE
DataView - add basic math operations of selected cells (displayed in status bar )

### ISSUE THREAD

**Issue by knagyorg** [dbeaver/dbeaver#9212]
Enhance status bar of DataView to provide basic math operations calculated from selected cells.
For example like LibreOffice Calc does.

![libreoffice-calc-feature](https://user-images.githubusercontent.com/10117488/87011122-ca01f500-c1c7-11ea-9828-dab099c3f6d4.jpg)

**Comment by kseniiaguzeeva** [comment]
Thank you for your suggestion. We already have a similar option.
To use it press Calc btn on the panel on the right of Data View and select a function.
![dbeaver_r453yY2ITf](https://user-images.githubusercontent.com/51405061/87027778-558a7e80-c1e6-11ea-9d40-ed2f5f214bb4.png)

More info you can read here https://github.com/dbeaver/dbeaver/wiki/Panels
