### ISSUE TITLE
"Read more" cookie footer buggy and not compliant with law

### ISSUE THREAD

**Issue by mhombach** [dbeaver/dbeaver#9216]
If you open the page "https://dbeaver.io" and, inside the cookie notification, click on the "Read more", this just openes the same page again in a new tab.
Also there is no option to change the settings ("opt-out"), even if it's mentioned in the label.
This is not compliant to the law to my knowledge and is a bug which should be fixed asap.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by uslss** [comment]
Fixed
