### ISSUE TITLE
[SQLITE] Binary data corruption in BLOB fields

### ISSUE THREAD

**Issue by vegaminer** [dbeaver/dbeaver#9218]
#### System information: 
- Windows 10, v 1709, build 16299.64
- 7.1.2.202007051953

#### Connection specification:
- SQLite
- org.xerial:sqlite-jdbc:RELEASE 3.32.3
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
Error displaying binary fields. Looks like binary values decoded/encoded with some json converter before displaing.

#### Steps to reproduce, if exist:
```
CREATE TABLE NewTestTable (
	image BLOB
);
```
Insert a dummy record: `insert into NewTestTable (image) values ( 0 ) ;`

Right click on the new record -> Load From File -> Select any valid jpg img.
Just save the value back to file via Save to file menu
Contest of the field is garbled. Compare it with original image file in hex.

#### Include any warning/errors/backtraces from the logs
No errors in logs

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
It happens because you insert numeric value before loading binary data. 
DBeaver thinks that it is text content and tries to convert binary data to text format.
Workaround: use NULL instead of 0.

Fixed (now numeric values are treated as binaries)

**Comment by uslss** [comment]
verified
