### ISSUE TITLE
Data Import Help

### ISSUE THREAD

**Issue by jltz83** [dbeaver/dbeaver#9219]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.0.3

#### Connection specification:
- Database name and version: DB2 iSeries / AS 400

#### Describe your question:
Can someone please help troubleshoot slow data transfer rate from csv into DB2 table? I have attempted everything suggested in posts I could find (use Single Query, increase Fetch Size, use auto-commit instead of transactions) and nothing seems to help. I also used the Export Data tool to transfer data from one table to another in the same database, and it also takes over 15 minutes to transfer a table. The table does have 62 columns, but only 17,000 rows, and as csv file it is only 8.5MB.

**Comment by uslss** [comment]
hi @jltz83 ,
do you have the possibility to check if the issue is reproducible against 7.1.2v?

**Comment by jltz83** [comment]
Not very easily. I work in state government, and it can be difficult to get software installed/upgraded.

**Comment by jltz83** [comment]
So, I "cleaned" the csv file. It was a data download from an online survey tool, and it had text fields with line returns and commas. I thought that might be causing some problems. I was able to convert that into a series of insert statements that I put into a script, and the data loaded relatively quickly. The data transfer tool is still very slow, both from the csv and between tables in the same database.

**Comment by sandorvasas** [comment]
I'm experiencing the same issue. Importing 10,000 rows from a CSV files takes more than 45 minutes. And today  I have to import a 230MB CSV with ~200,000 lines. Can't wait 10 hours for that to finish!

**Comment by jltz83** [comment]
We installed 7.1.3 today, and it loaded the table in 12 minutes.

**Comment by serge-rider** [comment]
It has to be something with target database performance or network thoughput.
Just imported about 1 million of rows into DB2 LUW from CSV in about 40 seconds.

Do you use any tunnels, proxies or VPN? 
How fast is target data when you read data? 
What if you EXPORT 10-20k rows?

**Comment by uslss** [comment]
there are no updates more than a month.
Issue is closed.
If it is still actual for you - feel free to reopen it
