### ISSUE TITLE
Slow Athena Queries

### ISSUE THREAD

**Issue by vivshri** [dbeaver/dbeaver#9220]
I am using DBeaver Version 7.1.1.202006211844 for Athena using Simba JDBC driver. 
Overall the experience is pleasant but I have noticed that queries from DBeaver required more execution time (about 50%) than the corresponding execution time from Athena Web Interface. I assumed that there could be some difference in both the drivers or network lag but I found that Athena queries from Pandas are faster and nearly matched to the execution time from the Athena console. That means network is not making huge difference, wondering if there any driver settings that can improve the performance?

**Comment by vivshri** [comment]
I have noticed that the following settings in the Driver properties minimized the execution time difference

MaxQueryExecutionPollingInterval. 4000
MinQueryExecutionPollingInterval. 10
QueryExecutionPollingIntervalMultiplier 5

**Comment by kseniiaguzeeva** [comment]
Thank you for your report.

**Comment by serge-rider** [comment]
I don't think that we can improve this from DBeaver side. It is controlled by Simba driver.

@vivshri Thanks for the info about driver properties!
