### ISSUE TITLE
Closing connection when cancel execution or in standby for some time.

### ISSUE THREAD

**Issue by lestevam** [dbeaver/dbeaver#9222]
- Windows 10

- DBeaver 7.1.2

- Microsoft SQL Server 2017 (RTM-CU8) (KB4338363) - 14.0.3029.16 (X64) - Developer Edition (64-bit) on Linux (Ubuntu 16.04.4 LTS)

- Problem
When I cancel execution and I try to execute again it shows a message which it is don't connected and I need to click in reconnect again. I think would be more productive if in the attempt to execute it again it tried to reconnect automatically. The same problem occurs when I stay in standby for some time.

- Steps to reproduce
Executing a select with some thousand lines.
Click in cancel execution
Select the line and execute it again.

**Comment by irizzant** [comment]
Same issue here

**Comment by 632575987** [comment]
me too

**Comment by kseniiaguzeeva** [comment]
@irizzant, @632575987do you use SQL Server too?

**Comment by irizzant** [comment]
No I use Postgres

**Comment by 632575987** [comment]
I use oracle and Sybase

**Comment by uslss** [comment]
Hi,
we've already got an enhancement ticket created #9142  to resolve this issue.
Thanks for reporting. Close issue as duplicate
