### ISSUE TITLE
Export Wizard

### ISSUE THREAD

**Issue by VrigaChabibi** [dbeaver/dbeaver#9223]
#### System information: 
- Windows 10 Pro 1909 18363.900
- DBeaver version 7.1.2
- Darkest Dark Theme
- Resolution 1600 x 900px

#### Connection specification:
- PostgreSQL (Old)

#### Describe the problem you're observing:
- Export wizard seems blank, please help. Thank you.
![Annotation 2020-07-10 131741](https://user-images.githubusercontent.com/55678945/87119289-16534080-c26d-11ea-9df8-fbc2dc66824b.png)

#### Steps to reproduce, if exist:
- I can't remember it clearly, but back then when I'm going to export while using my PC remotely via TeamViewer, my position at the very first wizard step. And it seems my remoted PC monitor having power loss, CPU is fine. And following it, my remote resolution changed from 1600 x 900px to 800 x 600px. Wizard dialog still fine until I finished my export. Then the blank happened at the next export.
- It can only be fixed temporarily (the blank) by resizing the blank wizard area slightly. But it blank again at the next export progress.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report. It can be reproduced:
1. set The Darkest Dark Theme
2. select export in a PostgreSQL table context menu in DB Navigator

Actual result: the first step of the wizard is empty as on the photo above,

**Comment by serge-rider** [comment]
@kseniiaguzeeva is it still reproducible?
Perhaps it was fixed after revert to Eclipse 2020-03.

**Comment by kseniiaguzeeva** [comment]
Yes, version 7.1.3.202007230724
![dbeaver_UPR2ujaXuA](https://user-images.githubusercontent.com/51405061/88384208-a5f00780-cdb4-11ea-8b2d-2127243f2c50.png)

**Comment by serge-rider** [comment]
Weird bug. 
I can't realize what causes this glitch.

**Comment by VrigaChabibi** [comment]
@kseniiaguzeeva @serge-rider do you guys tried to resize the blank wizard already?

**Comment by kseniiaguzeeva** [comment]
We are going to do it.

**Comment by serge-rider** [comment]
I still don't understand what exactly caused this (looks like a sort of bug in Darkest Dark theme).
However small page re-layout fixed this.

**Comment by kseniiaguzeeva** [comment]
Verified
