### ISSUE TITLE
can't connect to SQL 2014

### ISSUE THREAD

**Issue by shakai2** [dbeaver/dbeaver#9235]
#### System information: 
- Centos 8
- Community 7.1.2

#### Connection specification:
- MS SQL Server 2014

#### Describe your question:

When I try to connect to the server I get an error:

The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]

The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]".

Any help ?
Thanks

**Comment by kseniiaguzeeva** [comment]
Sorry for the long responce. As I see it is not DBeaver issue.
Which driver have you used? Have you tried to connect in Windows?

**Comment by uslss** [comment]
there is not any update on the issue for a long time.
If the issue is still actual for you - feel free to reopen the ticket with additional info that could help to investigate and reproduce an issue.

**Comment by pgvee** [comment]
Solution (Though it weakens security)
Modify the <dbeaver_install>\jre\conf\security\java.security file. 
Remove the "TLSv1" value from the jdk.tls.disabledAlgorithms key.
Restart dBeaver.

**Comment by lucas-santana** [comment]
@pgvee 
I dont have TLSv1 in  jdk.tls.disabledAlgorithms key.
My conf location: /var/lib/flatpak/app/io.dbeaver.DBeaverCommunity/x86_64/stable/active/files/jre/conf/security
![image](https://user-images.githubusercontent.com/23356474/120531424-ffea3200-c3b4-11eb-8287-5fde067014de.png)

**Comment by lucas-santana** [comment]
@pgvee Ty, i was changed the wrong file.
The right file is in this location: /var/lib/flatpak/app/io.dbeaver.DBeaverCommunity/x86_64/stable/active/files/dbeaver/jre/conf/security/java.security
