### ISSUE TITLE
DBeaver 7.1.2 BROKEN

### ISSUE THREAD

**Issue by luizh7856** [dbeaver/dbeaver#9236]
Front end is destroyed.

1 - On sql editor you can't click and drag to select the text you want. When you click and drag it will select the entire upper part of the page until the point you clicked. 

![Selection_247](https://user-images.githubusercontent.com/68128626/87200960-091d6c80-c2d4-11ea-96e8-8d99a9580d89.png)

2 -  When visualizing the data of a table you no longer can click on the arrows to use the ordering.

3 - When visualizing the data of a table you no longer can change the columns sizes by clicking on the edge and dragging. 

4 - When visualizing the data of a table  you no longer can select more than one cell using the mouse.

Please send me instructions on how can I go back to a previous version without losing my DB connections. 

Thank You.

**Comment by serge-rider** [comment]
Can't reproduce.
What is your OS/window manager?

Perhaps it was caused by Eclipse platform update. We will revert to previous Eclipse version (2020-03) in the next version (7.1.3).

**Comment by mkwinco** [comment]
I can confirm the issues described above. (I am running ubuntu 16.04LTS with Unity.)
The application is virtually unusable in this state. :(

**Comment by serge-rider** [comment]
Could you check the fix in the Early Access version? (https://dbeaver.io/files/ea)

**Comment by mkwinco** [comment]
Installed dbeaver-ce_7.1.3_amd64.deb and I can confirm, that the issue is fixed. Thanks :)

**Comment by serge-rider** [comment]
@mkwinco thanks for testing this 👍

**Comment by mkwinco** [comment]
My pleasure :)
