### ISSUE TITLE
Autocomplete: Replace asterisk with all column names for INSERT statements

### ISSUE THREAD

**Issue by maffe** [dbeaver/dbeaver#9237]
**Is your feature request related to a problem? Please describe.**
The asterisk in `SELECT` queries can be replaced with all column names by placing the cursor after it and pressing Ctrl+Space. It would be helpful to be able to use this feature for `INSERT` queries.

**Describe the solution you'd like**
Pressing Ctrl+Space in `SELECT *| FROM customer` (with `|` being the cursor) replaces the asterisk with all columns from that table. Doing that in `INSERT INTO customer (*|)` should also work (instead it just displays a popup with column names).

**Describe alternatives you've considered**
An `INSERT` statement can be generated using a table’s context menu, but that requires much more effort.

**Additional context**
Tested with DBeaver Community Edition 7.1.2

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
this feature will be available in version 7.2.0 and will work for (*) {*} [*] after INSERT INTO tablename
