### ISSUE TITLE
Export result set, window cancel query, no cancel button

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#9238]
![image](https://user-images.githubusercontent.com/26621087/87222670-36d3e580-c3a8-11ea-96ce-81878879d60b.png)

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Hi @Pengchenghua ,
unfortunately, cannot understand what issue you're talking about.
Could you tell a bit more about issue and provide steps to reproduce it?
Thanks in advance

**Comment by Pengchenghua** [comment]
If you cancel the query, you cannot cancel, or where do you cancel the export

**Comment by uslss** [comment]
you could cancel export using mentioned button
![image](https://user-images.githubusercontent.com/31996417/88660393-49a42500-d0df-11ea-9b47-25fe78aecb49.png)
