### ISSUE TITLE
Cockroachdb Column is read-only: No corresponding table column

### ISSUE THREAD

**Issue by ws-fegon** [dbeaver/dbeaver#9239]
#### System information: 
- Operating system (distribution) and version
Linux Mint 19.3 Cinnamon
- DBeaver version
7.1.2
- Additional extensions
no

#### Connection specification:
- CockroachDB docker image: [latest](https://hub.docker.com/r/cockroachdb/cockroach/)
- Driver name 
I just installed a driver suggested by DBeaver
![image](https://user-images.githubusercontent.com/6111214/87245482-4dcd1300-c44e-11ea-94e7-ce38ef8228b7.png)
- Do you use tunnels or proxies (SSH, SOCKS, etc)?
No

#### Describe the problem you're observing:
I can't edit any data in tables. 
Column Column_name is read-only: No corresponding table column
Affected version: 7.1.2
**Downgrading to 7.1.0 resolved this issue for me**

#### Steps to reproduce, if exist:
Try to edit any data cell

**Comment by ws-fegon** [comment]
The same problem on OSX 10.15.5
DBeaver Version 7.1.2.202007051953

I found nothing useful in logs

**Comment by uslss** [comment]
thanks for the bug report

**Comment by intech** [comment]
7.1.2, 7.1.3 affected :(

**Comment by serge-rider** [comment]
Fixed for direct table data edit.

However data edit won't work  in custom SQL queries (because CDB doesn't provide information about source table in JDBC API)

**Comment by uslss** [comment]
verified
