### ISSUE TITLE
Data export - insert "ignore" to transfer data to another table

### ISSUE THREAD

**Issue by hdsheena** [dbeaver/dbeaver#9241]
#### System information: 
- MacOS Catalina
- DBeaver  Version 7.1.0.202006211226

#### Connection specification:
- MariaDB local and on AWS RDS

#### Describe your question:
In my efforts to migrate data from an AWS RDS instance to my local instance, it took me a bit to sort out how to do it. I had some disconnections, so I have a couple of tables that are missing "Randon" bits of data.
I think the SQL "INSERT IGNORE" function is what I need to clean this stuff up, but I can't find a way to do that in dbeaver. If it exists, I'd be very grateful for some help finding it!
I'm using the tasks to do a Data Export task into an existing table, and aside from the issue of data that's already in the new table, it's worked fantastically.

**Comment by kseniiaguzeeva** [comment]
@hdsheena try to 
1. dump your instance objects with --insert-ignore arg. (or change Insert on Insert ignore in dump file)
2. then create MySQL restore task in DBeaver and execute it (you can also execute dump/restore using Tools menu in context menu of DB Navigator).

![dbeaver_HN1dqMwY7s](https://user-images.githubusercontent.com/51405061/87406139-fef7b880-c5c8-11ea-854f-aa5649f8c071.png)


Let me know if this solution is convenient for you.

**Comment by hdsheena** [comment]
When I try to use "Dump database" tool, it says "Native client is not specified for connection" and I don't know what it's asking for?

**Comment by kseniiaguzeeva** [comment]
It is a task bug. Please use following way:
1 Select tools in a schema context menu in DB Navigator tree
![dbeaver_xCGWn8pG9X](https://user-images.githubusercontent.com/51405061/87519556-74778d80-c68a-11ea-9b1b-8b564d38e7e6.png)
2 Select dump/restore
3 Press Client in the opened window
![dbeaver_b6D7ucpGTF](https://user-images.githubusercontent.com/51405061/87519663-983ad380-c68a-11ea-8e3e-1b6eba6be53b.png)
4 Select MySQL Binaries
5 Dump/restore
(when Client is selected here, dump/restore via tasks will work)

**Comment by hdsheena** [comment]
I don't see MySQL Binaries as an option. I have "Browse..." but it takes me to a window asking for ID, Path, Name, Product Name and Product Version

**Comment by hdsheena** [comment]
--
I got it sorted by selecting the folder where mySql lives on my mac!

**Comment by kseniiaguzeeva** [comment]
Glad to hear!
