### ISSUE TITLE
Cannot list columns under a Spectrum schema in Redshift.

### ISSUE THREAD

**Issue by ecospinaa** [dbeaver/dbeaver#9244]
#### System information: 
- Operating system: Under linux and windows( W10 and Ubuntu)
- DBeaver version (7.1.2)

#### Connection specification:
- Spectrum schema under Redshift 
- Automatically downloaded:  Dbeaver

#### Steps to reproduce, if exist:

After updating to version 7.1.2, some friends and I started to see that under a spectrum schema in Redshift, we could not list columns from the tables  in the schema navigator in the left panel. It was working ok until we updated from version 7.1.0, to 7.1.2 :(. It is happening for both Ubuntu and W10.

![image](https://user-images.githubusercontent.com/7035912/87320645-c84e6f00-c4f0-11ea-9353-e1dad0d3b80f.png)

Also, after updating to 7.1.2, I noticed a new download of the Redshift driver , may be related to that?

**Comment by kseniiaguzeeva** [comment]
Sorry for the late response. Could you send logs?

**Comment by uslss** [comment]
there is not any update on the issue for a long time.
If the issue is still actual for you - feel free to reopen the ticket with additional info that could help to investigate and reproduce an issue.
