### ISSUE TITLE
NO OUTPUT [SELECT] STORE PROCEDURE ORACLE

### ISSUE THREAD

**Issue by apeiranoIS** [dbeaver/dbeaver#9245]
HI, have a problem with de out data in my store procedure.

i need out a lot data in a SELECT * FROM [TABLE] but de program or somtheng else not work.

example:

CREATE OR REPLACE PROCEDURE GESTION_DESA.GETAPPS(RT OUT SYS_REFCURSOR)
IS
BEGIN
	OPEN RT FOR
	  SELECT * FROM sistema_aplicacion;
END GETAPPS;

execute:

 DECLARE ouput_ refcursor;
 exec getapps(ouput_);

ERROR:
SQL Error [6550] [65000]: ORA-06550: línea 5, columna 0:
PLS-00103: Se ha encontrado el símbolo "end-of-file" cuando se esperaba uno de los siguientes:

   begin function pragma procedure subtype type <an identifier>
   <a double-quoted delimited-identifier> current cursor delete
   exists prior

#### System information: 
- Operating system (distribution) and version w10
- DBeaver version 7.1.1
- Additional extensions

**Comment by p91paul** [comment]
declare doesn't work that way, in Dbeaver at least, it would be the opening of a pl/sql block. Also dbeaver uses CALL instead of EXEC for calling a stored procedure.

Not entirely sure, but you could try 

    call getapps(?);

The ? should work as an output parameter, but never tried it myself.

**Comment by kseniiaguzeeva** [comment]
@apeiranoIS Do you have a possibility to check the advice?

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Ticket closed. If issue is still actual for you - feel free to reopen the ticket with additional info.
