### ISSUE TITLE
Eclipse DBeaver Autocomplete Suggestion not Highlighting

### ISSUE THREAD

**Issue by XxMcNastyxX** [dbeaver/dbeaver#9246]
Hello,

When the autocompletion window pops up and suggestions get generated, it does not highlight when either clicking on the suggestion or when using the up/down arrow keys. I was previously using the standalone DBeaver application which did not have this issue but have recently switched to using the Eclipse IDE and DBeaver plugin to keep all of my coding that I do in one place. Below is a screenshot of the issue where I actually clicked on the selection but did not highlight. I tried looking through the preferences but couldn't find anything.

![image](https://user-images.githubusercontent.com/68244209/87334347-1f117400-c504-11ea-9b4a-24fb8e31d020.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by jcachat** [comment]
This started happening for me after upgrading from 7.1.1 to 7.1.2.  The focus is not staying on the list of tables so it's not possible to use the up/down arrow keys to pick a table from the list.  I had to revert back to 7.1.1.

**Comment by serge-rider** [comment]
Can't reproduce this problem.
Perhaps it was caused by Eclipse platform change (in 7.1.2 we upgraded upto 2020-06 version). But we reverted this change in 7.1.3 version.

@jcachat could you test this in the latest version? (7.1.5)

**Comment by jcachat** [comment]
Yes, it was resolved when you reverted in 7.1.3.  And I am not having the issue now with 7.1.5 either.
