### ISSUE TITLE
Incorrect Default Database for YugabyteDB Connection

### ISSUE THREAD

**Issue by nchandrappa** [dbeaver/dbeaver#9248]
#### System information: 
- Mac OS
- DBeaver v7.1.2

#### Connection specification:
- YugabyteDB
- Postgres JDBC Driver

#### Describe the problem you're observing:

When creating a new YugabyteDB connection, the default database is being populated as `postgres` instead of `yugabyte`.

In the file `org.jkiss.dbeaver.ext.postgresql/plugin.xml`, entry is made to use `yugabyte` as the default database however when creating a new YugabyteDB connection `postgres` is being populated by default which is incorrect.

```
<extension point="org.jkiss.dbeaver.postgresql.serverType">
        .....
        <serverType id="yugabytedb" name="YugabyteDB" class="org.jkiss.dbeaver.ext.postgresql.model.impls.PostgreServerYugabyteDB" logo="icons/yugabyte_logo.png" defaultDatbase="yugabyte" defaultUser="yugabyte" customURL="true"/>
    </extension>
```

#### Steps to reproduce, if exist:

1. Create a new Database connection 
2. Select YugabyteDB
3. Database field will be populated with `postgres`

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by kseniiaguzeeva** [comment]
verified
