### ISSUE TITLE
Is posible to use custom variables in path of export data task ?

### ISSUE THREAD

**Issue by jeisondionatan** [dbeaver/dbeaver#9250]
#### System information: 
- Windows 10
- DBeaver version 7.1.2

#### Connection specification:
- Postgresql 9.5

#### Describe your question:

I'm trying to use my own custom variable created in the task in the folder path of the file to be exported. Is this possible in any way? Below are some prints illustrating what I'm talking about.

![image](https://user-images.githubusercontent.com/4604309/87366521-43467280-c54f-11ea-8262-5aa76881b5c4.png)

![image](https://user-images.githubusercontent.com/4604309/87366594-75f06b00-c54f-11ea-9303-8366c6d678b3.png)

![image](https://user-images.githubusercontent.com/4604309/87366648-95879380-c54f-11ea-8527-142bff693bf4.png)

**Comment by kseniiaguzeeva** [comment]
Btn **Variables..** is used to insert a variable value in task SQL Statement (e.g. when you do export from query, SQL statement execution).
Possibility to use custom variables in a folder path is not implemented, You can create a separate feature request for this.

**Comment by jeisondionatan** [comment]
Thank you

**Comment by jb-modist** [comment]
This is possible, as long as the custom variable is also used in the SQL statement. Unfortunately for string variables, this inserts quote characters into your path.
