### ISSUE TITLE
MariaDB: cast column is null in result

### ISSUE THREAD

**Issue by MeboGit** [dbeaver/dbeaver#9251]
- Operating system (distribution) and version
MacOS 10.15.5
- DBeaver version
Version 7.1.2.202007051953
- Database name and version
10.4.12-MariaDB-1:10.4.12+maria~buster-log

![Bildschirmfoto 2020-07-14 um 12 03 56](https://user-images.githubusercontent.com/15740317/87413064-1a16f800-c5ca-11ea-84d2-8ff024077287.png)

cast(datum_stunde as time) as stunde shows null?!

When scrolling down to next page (200 rows) and up again then it is shown as expected. Maybe problem with "cast"?!

#### System information: 
- Operating system (distribution) and version
MacOS 10.15.5
- DBeaver version
Version 7.1.2.202007051953
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
10.4.12-MariaDB-1:10.4.12+maria~buster-log
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Hi @MeboGit ,
unfortunately, cannot reproduce it. For what data type issue is happened?

**Comment by MeboGit** [comment]
concerned field type is datetime:

CREATE TABLE `station_datum_stunde` (
  `calledstationid` varchar(25) DEFAULT NULL,
  `mikrotik_router_id` int(1) NOT NULL,
  `hotspot_id` int(11) DEFAULT NULL,
  `datum` date DEFAULT NULL,
  `datum_stunde` datetime DEFAULT NULL,
  `stunde` int(7) DEFAULT NULL,
  `stunde_string` varchar(27) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `anzahl` bigint(21) NOT NULL,
  `acctsessiontime_mb` decimal(10,2) DEFAULT NULL,
  `acctinputoctets_mb` decimal(10,2) DEFAULT NULL,
  `acctoutputoctets_mb` decimal(10,2) DEFAULT NULL,
  KEY `idx_station_datum_stunde` (`hotspot_id`,`datum`,`stunde`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

**Comment by MeboGit** [comment]
Strange: When changing 
  cast(datum_stunde as time) as stunde,
to
  cast(datum_stunde as time) as x,
then it works as expected.

What could be wrong with "stunde"?

**Comment by uslss** [comment]
seems that issue is related to the already existing column with the name similar to the alias that was used but with another type

thanks for the help with investigation

**Comment by serge-rider** [comment]
Fixed (we had the same issue in PostgreSQL)

**Comment by uslss** [comment]
verified
