### ISSUE TITLE
Advanced Copy after column shuffle

### ISSUE THREAD

**Issue by wxtsxt** [dbeaver/dbeaver#9252]
#### System information: 
- Win10
- DBeaver version 7.1.1.202006231904
- Additional extensions NO

#### Connection specification:
- MS SQL

#### Describe the problem you're observing:
Pasting copied data from Grid returns correct header and wrong rows

#### Steps to reproduce, if exist:
- SELECT some data to Grid (at least 5 columns)
- take column 5 and move it as column 3
- select column 1, 2 and 3 (you want to copy some rows from only 3 columns)
- copy + paste to Notepad - works fine
- advanced copy... , choose Markdown, paste to notepad
- you will see data from columns 1,2 and 3, but column names will be from columns 1,2 and 5.
Pasted column name does not match column rows.
Pasted column data is from wrong column.

**Comment by uslss** [comment]
hi @wxtsxt ,
could you post a video?
and could you clarify: at the second step you move column 5 as column 3, and then you copy that column and column name is from 5 column. It seems for me, that it is the expected result...

**Comment by 2019-05-10** [comment]
Just experienced something slightly similar:

1) right click on table -> View Data
2) manually order data by column 'foo'
3) select a row, Advanced Copy -> SQL
4) paste in editor

Pasted row is not the one selected. I could repat steps 3 and 4 several times with different rows, always resulting in the wrong result pasted.
Only after limiting data to exactly the row I want (foo='123') I was able to successfully copy the row.

Closing Data editor and repeating from step 1, things suddenly worked.

Looks to me like the model and the view are out of sync here.

**Comment by serge-rider** [comment]
Yep. Copy As (it actually shortcut for "Export data" action) doesn't respect column order. 
Export is always in original column order.
It is a bit complicated to fix (because export just dumps original resultset to external format).
We need to reorder columns on the client side. It can be done by making some sort of "proxy" resultset which will transform original one into results with properly ordered columns.

**Comment by 2019-05-10** [comment]
I assume, the same approach has to be taken for **_rows_**, right?

**Comment by Matvey16** [comment]
Issue still persists

**Comment by Kerksys** [comment]
Use sort on server for rows!
![image](https://user-images.githubusercontent.com/89728905/156577757-94407ffd-dd5d-4db0-9624-eb7aa5048c02.png)

**Comment by Matvey16** [comment]
![dbeaver_RAIZzVMBAO](https://user-images.githubusercontent.com/82543000/162768621-1896cd61-ffd8-4a99-8ff0-ec1bb4719745.png)

|Column1|Column3|Column2|
|-------|-------|-------|
|1a|5e|4d|

**Comment by Matvey16** [comment]
Now all of the columns are copied regardless of selection

**Comment by Matvey16** [comment]
Verified
