### ISSUE TITLE
No results in search metadata db. Win 10 64 Pro, DBeaver 7.1.2.202007051953, connected to local Postgresql 10.5-2-windows-x64

### ISSUE THREAD

**Issue by drakut** [dbeaver/dbeaver#9254]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by drakut** [comment]
![image](https://user-images.githubusercontent.com/25223974/87435518-84dd2900-c5f4-11ea-9cb8-d0f53c58cdea.png)

**Comment by drakut** [comment]
No any tunnels

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
I can't reproduce it. How do you search metadata? Some screenshot would be very useful.
