### ISSUE TITLE
Query's timer don't stop correctly

### ISSUE THREAD

**Issue by zarpelon** [dbeaver/dbeaver#9257]
#### System information: 
- Ubuntu 20.20
- DBeaver 7.1.2

#### Connection specification:
- Postgresql
- Connection type is production 

#### Describe the problem you're observing:
When I run some sql instruction in this environment, I get this image, the timer keeps increasing, but if i click the commit button, it applies the changes. 

Maybe It's happens cause the auto-commit is off.

#### Include any warning/errors/backtraces from the logs
![image](https://user-images.githubusercontent.com/264762/87444097-bd690c80-c5cc-11ea-8349-8a55faf9f82d.png)

**Comment by uslss** [comment]
hi @zarpelon , could you provide a video?

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Ticket closed. If issue is still actual for you - feel free to reopen the ticket with additional info.
