### ISSUE TITLE
Error connecting to datasource

### ISSUE THREAD

**Issue by Jthovn** [dbeaver/dbeaver#9258]
Reason:
Unexpected driver error occurred while connecting to the database
  ONS configuration failed
  ONS configuration failed
    Subscription time out
    Subscription time out

First noticed after upgrading to Version: 7.1.2
Reverted back to Version 7.0.5.202005171753

Same issue

**Comment by uslss** [comment]
Hi @Jthovn ,
what database do you use?

**Comment by Jthovn** [comment]
Oracle 12c

**Comment by p91paul** [comment]
https://github.com/dbeaver/dbeaver/issues/9002 see there for a couple workarounds

**Comment by Jthovn** [comment]
That worked. Thanks

Open connection properties
Click "Test connection"
Stop the test before it times out
Test again
It works!
