### ISSUE TITLE
Search and Workspace tabs have white background on the dark theme

### ISSUE THREAD

**Issue by mfgabriel92** [dbeaver/dbeaver#9259]
#### System information: 
- Ubuntu 20.04 LTS
- 7.1.2

#### Connection specification:
- MySQL 8
- JDBC

#### Describe the problem you're observing:
The tabs from Search (Ctrl + H) and Eclipse Marketplace have a white background when using the DBeaver plugin. Once the plugin is uninstalled, they come back to how they should be.

![Screenshot from 2020-07-13 20-20-12](https://user-images.githubusercontent.com/26734503/87465044-7722a600-c5ea-11ea-8246-07a88305e272.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed (it is not just for search dialog tabs)

**Comment by uslss** [comment]
verified
