### ISSUE TITLE
Request: Refresh schema ability when selecting source container

### ISSUE THREAD

**Issue by r-richmond** [dbeaver/dbeaver#926]
When importing data using Dbeaver's import data feature I often find myself using source data that is from a newly created container.

This is a little frustrating as I'm unable to right-click and select refresh while in the import data wizard. This requires me to exit the wizard, scroll to the database in the database navigator, right-click & refresh, then scroll back to the table I want to import data to and re-enter the wizard.

Is it possible to add the ability to right-click & refresh for source containers during the import data wizard?

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by uslss** [comment]
seems feature request is outdated for now
