### ISSUE TITLE
Isolation Level not saved

### ISSUE THREAD

**Issue by tekook** [dbeaver/dbeaver#9262]
#### System information: 
- Operating system (distribution) and version: Win10 (19041.330)
- DBeaver version: 7.1.2
- Additional extensions: none

#### Connection specification:
- Database name and version: MSSQL docker / MySQL / MariaDB / Oracle
- Driver name: e.G MySQL -> com.mysql.jdbc.Driver 5.1.44 / MSSQL -> com.microsoft.sqlserver.jdbc.SQLServerDriver 8.2.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I'm trying to get DBeaver not to lock my database while reading data.
I found https://github.com/dbeaver/dbeaver/issues/4203 but I cannot set the isolation level for any conection.
It always reverts to Read Commited.
#### Steps to reproduce, if exist:
(1) Have a Production Connection
(2) Go to Edit Connection -> Connection -> Initialize
(3) Set Isolation levle to Read Uncommited
(4) DBeaver asks to reconnect the connection -> OK
(5) Edit connection again -> See setting is back to Read Commited.

#### Include any warning/errors/backtraces from the logs
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4924170/dbeaver-debug.log)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
There was a bug - saved isolation level was applied only if auto-commit is off.
Fixed.

**Comment by tekook** [comment]
Awesome thanks!

**Comment by kseniiaguzeeva** [comment]
I still can reproduce. Isolation level switches to read commited when Auto-commit is off and on. 
DBeaver	7.1.3.202007261800
![sqeXRrg5TJ](https://user-images.githubusercontent.com/51405061/88523862-4aff2000-d001-11ea-9efa-5fd41790cbf4.gif)

**Comment by serge-rider** [comment]
Another bug in the isolation level config page.
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
