### ISSUE TITLE
Save As greyed out

### ISSUE THREAD

**Issue by tatod** [dbeaver/dbeaver#9263]
#### System information: 
- Ubuntu 20.04 LTS
- 7.1.2.202007051953
- ms excel

#### Connection specification:
- oracle
- Oracle JDBC driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
when writing sql there is no Save As option, just Save.

#### Steps to reproduce, if exist:
write sql, run it and then try to Save As in File menu

#### Include any warning/errors/backtraces from the logs

there is no error, just Save As is greyed out, sometimes it is available if I restart the app but I do not like to do it

**Comment by HeleriMelsas** [comment]
Experience the same issue, "Save as" is disabled unless I "Save" first.

**Comment by dpeytorr** [comment]
The issue also happens when you open your own Script.

You are working on it, but you are not sure about the changes, you want to Save As as a version, but it's disabled. Only allows to Save overwriting your original file.

**Comment by uslss** [comment]
@dpeytorr , @HeleriMelsas what OS do you use?

**Comment by dpeytorr** [comment]
@uslss I use Windows 10 Enrerprise. And i work with Postgresql DDBB.

**Comment by JSellers0** [comment]
@uslss 
I am also experiencing this problem.

Using Windows10 Enterprise, DBeaver Community Edition Version 7.1.2.202007051953; connection doesn't seem to matter (I tried AWS Redshift and MSSQL Server connections).

I did notice if I open a new script window, Save As is available.  As soon as I type a character in the window, Save As becomes unavailable for selection:
![image](https://user-images.githubusercontent.com/7433295/87673566-c1b73600-c742-11ea-9a2f-e15771e48a88.png)
![image](https://user-images.githubusercontent.com/7433295/87673633-d7c4f680-c742-11ea-9ed6-e216441979e6.png)
![image](https://user-images.githubusercontent.com/7433295/87673679-e7dcd600-c742-11ea-9db2-2dc8e720f549.png)
![image](https://user-images.githubusercontent.com/7433295/87673727-f925e280-c742-11ea-8847-379006a2d640.png)

**Comment by uslss** [comment]
seems that issue will be fixed in scope of 7.1.3
7.1.3 version will be released this monday

**Comment by GiancarloPanarese** [comment]
Hi there,

Same issue here experienced as per @tatod and @JSellers0  descriptions on Community Version 7.1.2.
Working on Ubuntu 16.04 desktop Unity, Database MariaDB

**Comment by uslss** [comment]
@GiancarloPanarese please, check if it is reproducible against 7.1.3

**Comment by JSellers0** [comment]
@uslss Just installed newest update (7.1.3.202007192031) and this appears resolved for me.

**Comment by GiancarloPanarese** [comment]
@uslss Upgrading to 7.1.3 is solving this issue in my scenario as well.

**Comment by tatod** [comment]
solved in 7.1.3 for me too
