### ISSUE TITLE
Tables converting names to numbers

### ISSUE THREAD

**Issue by Jhonata-Bossa** [dbeaver/dbeaver#9267]
I am working with Caché, local and web. However, when I consult a table eg: (customer) at the local bank, this table only contains numbers and when I consult via the web it brings the names of the customers or the category. This by analyzing the same tables.

**Comment by uslss** [comment]
Hi @Jhonata-Bossa ,
if I understand you right, probably Value panel could solve your issue?
It shows data from related tables. You could choose what description to show by clicking at Define Description link
![image](https://user-images.githubusercontent.com/31996417/87666449-5173d900-c771-11ea-81fe-10aad683b141.png)

**Comment by Jhonata-Bossa** [comment]
I am totally new to DBeraver, I know little. Thanks for the tip.
I found some columns in other tables and found them, while others I can't see anything in value. I will send some examples. Same table, same columns.
![Table_with_value](https://user-images.githubusercontent.com/68339351/87707637-d06c1000-c777-11ea-88d8-1c049a3dcf0d.PNG)

![Table_DBeaver](https://user-images.githubusercontent.com/68339351/87708021-7455bb80-c778-11ea-8dad-19832f21f17e.jpeg)

![Table_Web](https://user-images.githubusercontent.com/68339351/87708025-76b81580-c778-11ea-9a15-7c610d68d163.jpeg)

Maybe it’s easier to understand.  :D

**Comment by Jhonata-Bossa** [comment]
the first two are from DBeaver and the last image is from the Web

**Comment by uslss** [comment]
Thanks for clarification :)
Unfortunately, it is not implemented in DBeaver yet, Labeled issue as feature request

**Comment by uslss** [comment]
will be implemented in the scope of #10765
