### ISSUE TITLE
Typo in 'Sorting Results' message

### ISSUE THREAD

**Issue by emont01** [dbeaver/dbeaver#9268]
#### System information: 
- Operating system: Windows 10 (64 bits)
- DBeaver version: 7.1.2.202007051953
- Java version: 1.8.0_252
- UI language: Spanish

#### Connection specification:
- Database name and version: Microsoft SQL Server 2012 - 11.0.2100.60 (X64) 	
- Driver name: MSSQL JDBC release 8.2.0.jre8
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: YES a VPN but I don't think it is relevant in this case

#### Describe the problem you're observing:
When I sort by a not indexed column on a potentially big table a message is displayed showing me the following warning [1], this warning contains a typo, "tablas grand**a**s" should be "tablas grand**e**s"

[1]
![imagen](https://user-images.githubusercontent.com/588937/87565377-2c0aa080-c687-11ea-840f-0f8fcd64f035.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
verified
