### ISSUE TITLE
Support geometries containing M and Z

### ISSUE THREAD

**Issue by geokarta** [dbeaver/dbeaver#9270]
The value viewer is a great tool to see and understand data.
But the Map tab of this feature seems to only support GEOMETRIES that does not contains M nor Z values.

To see a POINT, per example, I have to remove the M or Z 
Under POSTGRES/POSTGIS connection: SELECT select ST_Force2D(geom) as geom from mytable;

It is not a big deal for me to call ST_Force2D but it could be great to not to do so.

DBeaver could easely display a GEOMETRY containing M or Z just ignoring them or implicitly call Force2D.

Later it could be great to display M and Z values somewhere in the Map View.

Thanks

**Comment by uslss** [comment]
thanks for suggestion

**Comment by kseniiaguzeeva** [comment]
By some reason the same geometry data in varchar column (formatted to geometry) and geometry column (cut from 3D or 4D to 2D) is displayed differently in some cases:

**Comment by ShadelessFox** [comment]
Problems related to rendering is related to #11116
