### ISSUE TITLE
change time zone to utc on mac

### ISSUE THREAD

**Issue by OferOh-Fundbox** [dbeaver/dbeaver#9274]
I tried to change the time zone (mac) by following the instructor, and it does help.

Go to Finder > Applications.
Right-click on DBeaver and select Show Package Contents.
Open Contents\Eclipse\dbeaver.ini.
After the -vmargs line, add this: -Duser.timezone=UTC.
Save file and restart DBeaver.

I noticed if I click on the text I got this message 
as you can see it is a different location and could not change the file 
please advise what can i do
![image](https://user-images.githubusercontent.com/59009406/87635397-a3a00480-c747-11ea-886a-74b269326083.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by OferOh-Fundbox** [comment]
You can close the bug, it related to the way I installed dbeaver
