### ISSUE TITLE
Navigator "tables" node throws I/O error when trying to load >150,000 PostgreSQL tables/partitions from pg_class

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#9275]
#### System information: 
- Operating system (distribution) and version: Windows Server 2016 Datacenter 64-bit
- DBeaver version: 7.1.2.202007051953
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11 on Aurora RDS
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I have a PostgreSQL 11 schema with more than 150,000 partitions and when trying to open the table node, DBeaver throws and error after a timeout:
"Connection with [PostgreSQL - DB] lost
Reason:
SQL Error [08006]: An I/O error occurred while sending to the backend."

I tried using a filter but alas.

DBeaver runs this query in the background before failing:
SELECT c.oid,c.*,d.description,pg_catalog.pg_get_expr(c.relpartbound, c.oid) as partition_expr,  pg_catalog.pg_get_partkeydef(c.oid) as partition_key 
FROM pg_catalog.pg_class c
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=c.oid AND d.objsubid=0 AND d.classoid='pg_class'::regclass
WHERE c.relnamespace=$1 AND c.relkind not in ('i','c')

**Comment by uslss** [comment]
Hi @yonisade ,
did you try to change keep-alive value in connection settings?
![image](https://user-images.githubusercontent.com/31996417/87665036-ee814280-c76e-11ea-9411-192db1bdce4e.png)

**Comment by yonisade** [comment]
My Keep-Alive is on 120 but still getting this error.

**Comment by mank08mank** [comment]
What was the solution here ?
