### ISSUE TITLE
how to set"Show all databases"?

### ISSUE THREAD

**Issue by YoYogurt** [dbeaver/dbeaver#9276]
#### System information: 
- win10
- DBeaver7.1.1

#### Connection specification:
- Database name and version

#### Describe your question:
I created a database, but i cann't see it. And it tell me "it is already existed". How can I see the database I built？？？
and how to set"Show all databases"?

**Comment by uslss** [comment]
To see newly created db - Refresh connection in Connection's Context Menu
To set Show all database, e.g., for PostgreSQL check Show all database option in Connection Settings 
![image](https://user-images.githubusercontent.com/31996417/87664711-6864fc00-c76e-11ea-922e-36b732f52f83.png)
