### ISSUE TITLE
New Template window: "Name" field is too small

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9281]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.3 EA

#### Describe the problem you're observing:
**New Template** window: "Name" field is too small

#### Steps to reproduce, if exist:
1. Open Dbeaver>Editors>SQL Editor>Templates
2. Press **New..** btn

![dbeaver_fnSga4RnbQ](https://user-images.githubusercontent.com/51405061/87695709-80ea0c00-c798-11ea-8f5e-d30f40d1c9c5.png)

**Comment by SA357** [comment]
This window is from Eclipse and unfortunately it will be too difficult to change

**Comment by serge-rider** [comment]
Workaround: resize template edit dialog.

**Comment by AxiomaticAxolotl** [comment]
For me not just small, it's completely hidden. Resizing brings it back into view, but I didn't realize it would do that until I came here.
![2020-09-21-135326_791x527_scrot](https://user-images.githubusercontent.com/68200048/93804603-8e969480-fc14-11ea-8fe2-d3e78e1a75d9.png)
