### ISSUE TITLE
auto-refresh configuration?

### ISSUE THREAD

**Issue by obaillard** [dbeaver/dbeaver#9283]
#### System information: 
- Operating system (distribution) and version: windows 10 pro for workstations, 64bits
- DBeaver version: 7.1.2.202007051953

#### Connection specification:
- Database name and version: MariaDB version 10.5.4 64bits

#### Describe your question:
Hi,
sorry if my question is too trivial but I a new working with DBeaver and I really couldn't find any real answer in the DBeaver forum or in the internet.

Here a small example about what is happening:
So I have a working connection to a local MariaDB data base in DBeaver and I use a small SQL script in the SQL editor to create for example a database:
create database movie;
use movie;

then I click on "Execute SQL script" and see the script was executed without failure. But in the project view, the data base "movie" is not present. 

![mariadb_projectview_notupdated](https://user-images.githubusercontent.com/30605466/87754913-3c955500-c806-11ea-931c-13d2ac46ec5c.png)

I have to select the folder "Databases" and press "F5" to finally see my changes. 
Personally I was expecting to see directly the new data base "movie" in the project view after the execution of the SQL statements.
And actually, this append for ANY statements I am using to change the schema in my database (add/drop/alter table).

Now I am using transaction mode with following settings: auto-commit + smart commit mode, repeatable read.
But no matter which settings I am using, the project view is not automatically updated.

So I am wondering: 
- is this the default way of working with DBeaver?
- is there a way to configure DBeaver so that the change done on schemas in the SQL editor are automatically updated in the Projects view?

**Comment by uslss** [comment]
Hi @obaillard ,
yes, it is the default way of working with DBeaver.
Marked your issue as a feature request :)

**Comment by uslss** [comment]
probably, will be fixed in the scope of #6398
