### ISSUE TITLE
Statistics (table size) missing for child and partition tables in dbeaver 7.1.2

### ISSUE THREAD

**Issue by michaelsovik** [dbeaver/dbeaver#9284]
In dbeaver community edition 7.1.0 we had table sizes for both child and paritioned tables. When upgrading to dbeaver 7.1.2 this is now missing. Is this something that was removed on purpose? It was a really nice feature.

**Comment by naihil** [comment]
Confirm! DBeaver 7.1.2 CE dont show sizes for tables with native partitioning (parent table and partitions). Tested in PostgreSQL 12.3

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
verified
