### ISSUE TITLE
[Exasol] Export to new table from Data Editor partially skips syntax

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9285]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.3 EA

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
Export to new table from Data Editor partially skips syntax

#### Steps to reproduce, if exist:
**Precondition:** create a table with a not null column, a column of varchar type. E.g. 
CREATE TABLE "Export" (
		"Int" DECIMAL(18,0) NOT NULL ,
		"VAR" VARCHAR(50) UTF8 ,
		"Timestamp" TIMESTAMP 
);
;
A)
1. Select export in the table context menu in DB Navigator tree
2. Select Database and press Next
3. Select export to a new table and press DDL
Actual result:
CREATE TABLE "schema_name"."Export"(
	"Int" DECIMAL(18,0) NOT NULL,
	VAR VARCHAR(50),
	"Timestamp" TIMESTAMP)

B)
1. Open the table in Data Editor
2. Select Export in the Data Editor
3. Select Database and press Next
4. Select export to a new table and press DDL

Actual result: 
1. CREATE TABLE "schema_name"."Export"(
	"Int" BIGINT,
	VAR VARCHAR,
	"Timestamp" TIMESTAMP)
2. The new table cannot be created after finishing Export wizard

Expected: DDL has the same syntaxis like in Export via FB Navigator tree

**Comment by Sargul** [comment]
Hi,

this will be rather hard for me to fix, as this is an error based on the precision of the meta data returned by the exasol jdbc driver.

Wenn you have a look at the meta data in the resultset you will see that no nullability information is returned and the JDBC Type is BIGINT:

![image](https://user-images.githubusercontent.com/5595511/88019682-9cec0580-cb2a-11ea-89bb-492ae6e20aa9.png)

I had to work around this on other occasions as well.

Perhaps there is a way to fix this but implementing something in the Exasol Plugin that is called for this particular case but I don't know how to. Perhaps @serge-rider can help here?

**Comment by serge-rider** [comment]
This issue will be resolved in #7745
Currently we use dummy and very simple DDL syntax in data transfer wizard.
But we need to use native DDL syntax (from XTableManager).
This requires quite a bit of refactoring.
