### ISSUE TITLE
can not download  mssql-driver？ why  

### ISSUE THREAD

**Issue by xingx001** [dbeaver/dbeaver#9287]
Error resolving dependencies
  Maven artifact 'maven:/com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE' not found
  Maven artifact 'maven:/com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE' not found

**Comment by uslss** [comment]
hi @xingx001 , what dbeaver version do you use?
could you provide steps to reproduce?

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Ticket closed. If issue is still actual for you - feel free to reopen the ticket with additional info.

**Comment by reedjosh** [comment]
Seems these are all related:

https://github.com/dbeaver/dbeaver/issues/9812
https://github.com/dbeaver/dbeaver/issues/9503

Issue should probably still be open.

**Comment by keytrap-x86** [comment]
Try adding `http://insecure.repo1.maven.org/maven2/` and putting it a the top (and eventually disabling other Maven) :

![image](https://user-images.githubusercontent.com/17864005/105840606-9061d180-5fd3-11eb-841d-115dd21f4a21.png)

Worked for me after hours of triage
