### ISSUE TITLE
Disable possibility to create VFK for databases that don't support it

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9292]
**Is your feature request related to a problem? Please describe.**
For now in Database like Clickhouse we can create Connection (VFK) on ERD. But this feature isn't shown in Table Property Viewer. So after creation VFK on ERD, we've got an error in Table Reference Panel
![image](https://user-images.githubusercontent.com/31996417/87776883-28b31880-c831-11ea-9488-ced49c7ed912.png)

**Describe the solution you'd like**
Probably, we need to disable the possibility to create VFK in DB that doesn't support it/

**Comment by SamuelLanders** [comment]
Good morning, Yes, I have to also ask for this. I love DBeaver, however when working with MSSQL I was having issues where DBeaver would create vFK link, however my other admins on MSSQL Server Management Studio 18 could not see the FK, thus ended up re-making the FK, and I would have tables with multiple vFK and FK links to every table.

**Comment by SamuelLanders** [comment]
Update: where the vFK and FK are the exact same link.

**Comment by kseniiaguzeeva** [comment]
Can be solved in scope of https://github.com/dbeaver/dbeaver/issues/10657

**Comment by uslss** [comment]
already fixed

**Comment by Cheney-77** [comment]
> already fixed

@uslss  hello,i know dbeaver provides  "Virtual Unique Keys" to delete/update a row-data without unique-key defined in the table,but  i‘m wondering if there any quick solution to  fix this problem? as far as I am concerned,ORACLE/SQLite has implemented ROWID,but how it works when the DB is postgresql/mysql?looking forward to your reply,tkx!!
