### ISSUE TITLE
Data Formatting is not used for generated DML commands

### ISSUE THREAD

**Issue by Sargul** [dbeaver/dbeaver#9293]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
7.1.2
- Additional extensions
-

#### Connection specification:
- Database name and version
Exasol, Generic JDBC
- Driver name
exasol
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no
#### Describe the problem you're observing:
When configuring timestamp format for a data source this affects only the display format not the format for generated sql.

#### Steps to reproduce, if exist:
For example:
![image](https://user-images.githubusercontent.com/5595511/87780463-13d58580-c82f-11ea-8e04-fe9903a8c95c.png)

Display for the select:
![image](https://user-images.githubusercontent.com/5595511/87780500-2485fb80-c82f-11ea-8890-5b327d76fe55.png)

Generated Insert:
![image](https://user-images.githubusercontent.com/5595511/87780526-2fd92700-c82f-11ea-9635-3019f915f3ad.png)
![image](https://user-images.githubusercontent.com/5595511/87780552-3e274300-c82f-11ea-8525-69eefb59e1dc.png)

#### Excepted outcome
Use the display format for DML generation or an option to be able to use the display format for DML generation.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by Sargul** [comment]
acutally this is duplicate to #9331

**Comment by serge-rider** [comment]
DBeaver uses `native` date/time format for SQL scripts. Because generally UI format has nothing to do with it.

For Generic driver native format can be set in the driver settings:
![image](https://user-images.githubusercontent.com/6398845/89925881-b9043380-dc0c-11ea-8667-0ca7858b0cdc.png)

For non-generic drivers native format must be provided by value handler. See examples:
- https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/data/OracleTimestampValueHandler.java
- https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.db2/src/org/jkiss/dbeaver/ext/db2/data/DB2ValueHandlerProvider.java

Probably we need something similar for Exasol

**Comment by Sargul** [comment]
Tried to implement this for Exasol but the definied format has to be read from the database configuration as it depends on the settings and no connection context ist available in the value handler.

So basically if someone changed the default Oracle timestamp format using NLS_TIMESTAMP_FORMAT  dbeaver would stop working with that instance on genrated SQLs

**Comment by Sargul** [comment]
Also tried now for a generic connection:
![image](https://user-images.githubusercontent.com/5595511/90752895-3b10ee00-e2d8-11ea-8e36-779773bb2be6.png)
![image](https://user-images.githubusercontent.com/5595511/90752900-3ea47500-e2d8-11ea-9ee0-6ce5d9d0cb2d.png)
Then the sql is generated without single quotes around the timestamp values:
![image](https://user-images.githubusercontent.com/5595511/90752973-51b74500-e2d8-11ea-8664-bf59796071ec.png)

**Comment by sovittyagi** [comment]
Hi Team,

I have installed 7.1.5 and still having same issue with date Format. When we are running query then result displayed in correct format as requested DD-MMM-YYYY but when we try to use Generate SQL feature for Insert/Update then still timestamp coming DD-MM-YYYY format but we need into DD-MMM-YYYY as this ticket was raised for same. Can you take a look and help me out.

Results of Insert Command
VALUES('22', 1, '092121', 'UV0', 'H0609', 804, 0, '2019-01-01 00:00:00.000', '2019-12-31 00:00:00.000', 6000, '2019-09-25 01:47:35.050'

Expected Results :--
VALUES('22', 1, '092121', 'UV0', 'H0609', 804, 0, '01-JAN-2019 00:00:00.000', '12-DEC-2019 00:00:00.000', 6000, '25-SEP-2019 01:47:35.050'

**Comment by sovittyagi** [comment]
@tati-kru  @Sargul  Kindly take a look into for my comment.

**Comment by sovittyagi** [comment]
Hi @tati-kru @serge-rider  @Sargul @LonwoLonwo  @kseniiaguzeeva  - Can we include this feature in upcoming release as its really important for us to use this and our whole team is looking forward for this change. So please try to have as earliest to ready for users.  If you have any question about my ask please refer my question above for timestamp format issue in Generate SQL Feature. Thanks in Advance!

**Comment by tati-kru** [comment]
Ok, we will see what we can do...

**Comment by LonwoLonwo** [comment]
@sovittyagi that database you use?

**Comment by sovittyagi** [comment]
> @sovittyagi that database you use?

Hi @LonwoLonwo  we are using Oracle RDB DataBase through JDBC Connection and we have mass Insert/Update requirement in Database so we found an option Generate SQL statement for Insert/Update but when we are using it its giving timestamp in '2019-12-31 00:00:00.000' this format but we are looking into '12-DEC-2019 00:00:00.000' format. Without this dd-MMM-yyyy format we can perform Update/Insert query in our databse.

**Comment by serge-rider** [comment]
May be fixed in #9696

**Comment by serge-rider** [comment]
Fixed.
Now SQL exporter uses native date/time format when possible. It means: it fetches timestamp values in server-provided format so there is no need to mess with NLS_* variables.

Generally it should work for all databases unless they have some tricky timestamp represetnation (like Oracle with its `TIMESTAMP` prefix). In that case databases-specific timestamp value handler has to be patched.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/94335766-747afe80-ffe6-11ea-8725-6bbed72adea2.png)

**Comment by sovittyagi** [comment]
Hi - In which Dbeaver Version this fixed we can see and do we invoke any
additional settings to see required timestamp in SQL Generator feature like
24-SEP-2020.

Kindly advise the steps as appropriate. Thanks in advance for your help.

Thanks
Sovit

**Comment by serge-rider** [comment]
In the next one (7.2.2), see milestone information.

You could check the Early Access version at https://dbeaver.io/files/ea

**Comment by sovittyagi** [comment]
@serge-rider  On given link for early access version i can see only 7.2.1 folder there. When i can check the 7.2.2 version to verify the changes for Time Format issue. Please Advise!

**Comment by uslss** [comment]
doesn't work for generated statements

**Comment by serge-rider** [comment]
"Generate SQL" command doesn't perform any server-side queries, it uses data already read in the data viewer.

In order to have native date/time formatting in the "Generate SQL" dialog you need to enable option Data Formatting->Use native date/time format.

**Comment by uslss** [comment]
verified

**Comment by sovittyagi** [comment]
@serge-rider @uslss @tati-kru  Hi All , I have installed version 7.2.2 but not able to find option to have time format in INSERT query generated by Generate SQL feature in desired format 05-OCT-2020. Can you please help me out with steps how i can get this timestamp in INSERT query.

**Comment by sovittyagi** [comment]
Hi All,

Can you please provide steps to have timestamp in 01-Jan-2020 format in
Insert/update query using SQL Generator feature.

I am not able to find in version 7.2.2.

Thanks
Sovit

**Comment by uslss** [comment]
Reopened.
Generate SQL use native format in any case
![image](https://user-images.githubusercontent.com/31996417/95240304-dde3e400-0814-11eb-992c-5045a0ead636.png)

**Comment by sovittyagi** [comment]
Yes i need the format like 15-Feb-2006 in SQL query but i can see in your
screenshot also its 2006-02-15 which is not required.

**Comment by sovittyagi** [comment]
@serge-rider @uslss  Can you please make sure in version 7.2.3 this issue will resolve as we are waiting since long time for this feature. Many Thanks!

**Comment by serge-rider** [comment]
Fixed.
When native format disabled we will use UI format

**Comment by sovittyagi** [comment]
@serge-rider  Can we test this latest update before wait till next release. If so please let us know so we can test and confirm results are as expected. Thanks in Advance!

**Comment by serge-rider** [comment]
We will publish Early Access version later this week (probably at Friday).

**Comment by uslss** [comment]
@sovittyagi actual EA is available for now https://dbeaver.io/files/ea/

**Comment by sovittyagi** [comment]
@uslss  Can you please try in your machine this feature. I am getting error while trying to install this EA version. Not sure what is the issue but not able to install this version.

**Comment by uslss** [comment]
Using native/non-native date/time formatting for SQL exporter was implemented in the scope of this ticket. So if you need to Generate Insert Into statement e.g. with a custom timestamp, you could use Export - SQL 
![image](https://user-images.githubusercontent.com/31996417/95475274-b749b880-098e-11eb-8125-c53dbb48df6c.png)

The same feature for Generated SQL will be implemented in the scope of #10020 .
