### ISSUE TITLE
How does the column filter work?

### ISSUE THREAD

**Issue by greenpeas** [dbeaver/dbeaver#9294]
7.1.2
Postgresql
Problem columns have foreign keys.
![dbSearchFilter2](https://user-images.githubusercontent.com/3856344/87793118-7c335f80-c84d-11ea-89cf-98ae10dafee4.gif)

**Comment by kseniiaguzeeva** [comment]
Please tell column types from the video.

**Comment by greenpeas** [comment]
> Please tell column types from the video.

uuid

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. It is bug for this column type.

To reproduce tables postgres.Xeniia.9294 and postgres.Xeniia.fk9294 can be used.
Steps:
1. open postgres.Xeniia.fk9294
2. Copy an uuid cell value
3. Press filter btn in the column header
4. Insert the value in search field.

Actual result: the value is not filtered

**Comment by serge-rider** [comment]
We can't use value search with LIKE operator for non-string data types (like uuid). But we can search by exact match.

Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
