### ISSUE TITLE
[Exasol] Simple view: Columns are not displayed in table properties tab

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9295]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.3

#### Connection specification:
- Database name and version Exasol

#### Describe the problem you're observing:
Columns are not displayed in table properties tab in Simple view

#### Steps to reproduce, if exist:
1. Press Edit connection>General
2. Select Simple Navigator view
3. Press Ok
4. Open Properties for a table 

Actual result: Statistics and DDL tabs are displayed
![dbeaver_yOW6LHPAB8](https://user-images.githubusercontent.com/51405061/87802584-1ac5bd80-c85a-11ea-9b19-6f197dd454f0.png)

Expected: Columns, Statistics and DDL tabs are displayed

**Comment by Sargul** [comment]
Hi @kseniiaguzeeva,

I can't really reproduce in 7.1.2:

![image](https://user-images.githubusercontent.com/5595511/88016847-a6726f00-cb24-11ea-89f2-0241d303a676.png)

![image](https://user-images.githubusercontent.com/5595511/88016906-c86bf180-cb24-11ea-8bd4-bbcdd826472e.png)

Have you tried to refresh Meta Data by pressing F5?

There is a known bug for Meta Data retrieval in Exasol < 6.2 with the isolation used by DBeaver to retrieve meta data fast which causes the connection to abort sometimes on retrieval of meta data.

**Comment by EliGe** [comment]
Hi, I am facing the same problem. I have productName in the table but this column is not displayed in properties

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it anymore in the latest release. @EliGe could you try to download it too https://dbeaver.io/download/ ?

**Comment by whyriod** [comment]
This is also Present in Ubuntu 20.04 with Dbeaver 7.1.3. Only Statistics and DDL are present
