### ISSUE TITLE
Getting "No unique key defined" after version 7.0.2

### ISSUE THREAD

**Issue by KellyKimbleNotions** [dbeaver/dbeaver#9296]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 7.0.5, 7.1.2
- Additional extensions

#### Connection specification:
- Database name and version Basis 
- Driver name: Generic - com.basis.jdbc.BasisDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
I can't upgrade from my version 7.0.2 without losing the ability to save records.  It reports that there is no unique key defined.  If I reinstall 7.0.2 it works again and defines all the keys automatically.

#### Steps to reproduce, if exist:
Here is the connection information:
{
	"folders": {},
	"connections": {
		"FEA60486-9C6C-09D8-545F-E076FAF782F4-170d3c9d1e6-2ee7534d1c8d1f35": {
			"provider": "generic",
			"driver": "FEA60486-9C6C-09D8-545F-E076FAF782F4",
			"name": "dev1",
			"save-password": true,
			"read-only": false,
			"configuration": {
				"port": "2001",
				"server": "dev1.server.com",
				"database": "Dev1DB",
				"url": "jdbc:basis:dev1.server.com:2001?database=Dev1DB&user=<user_name>&password=<password>",
				"type": "dev",
				"properties": {
					"server": "dev1.server.com",
					"port": "2001"
				},
				"handlers": {}
			},
			"custom-properties": {
				"database.meta.separate.connection": "false"
			}
		}
	},
	"connection-types": {
		"dev": {
			"name": "Development",
			"color": "255,255,255",
			"description": "Regular development database",
			"auto-commit": true,
			"confirm-execute": false,
			"confirm-data-change": false
		}
	},
	"drivers": {
		"generic": {
			"FEA60486-9C6C-09D8-545F-E076FAF782F4": {
				"provider": "generic",
				"id": "FEA60486-9C6C-09D8-545F-E076FAF782F4",
				"name": "BBj",
				"class": "com.basis.jdbc.BasisDriver",
				"url": "jdbc:basis:{server}:{port}?database={database}&user=<user_name>&password=<password>",
				"port": "2001",
				"custom": true,
				"embedded": false,
				"anonymous": false,
				"allowsEmptyPassword": false,
				"libraries": {},
				"driver-parameters": {
					"supports-indexes": "true",
					"all-objects-pattern": "%",
					"quote-reserved-words": "true",
					"omit-schema": "false",
					"schema-filters-enabled": "false",
					"script-delimiter-redefiner": ";",
					"supports-struct-cache": "true",
					"supports-truncate": "true",
					"omit-type-cache": "false",
					"split-procedures-and-functions": "false",
					"supports-stored-code": "true",
					"supports-references": "true",
					"omit-single-catalog": "false",
					"ddl-drop-column-brackets": "false",
					"omit-single-schema": "false",
					"supports-scroll": "false",
					"omit-catalog": "false",
					"script-delimiter": ";",
					"legacy-sql-dialect": "false",
					"script-delimiter-after-query": "false",
					"use-search-string-escape": "false",
					"supports-multiple-results": "false",
					"script-delimiter-after-block": "false",
					"ddl-drop-column-short": "false",
					"supports-limits": "true",
					"supports-select-count": "true"
				}
			}
		}
	}
}
#### Include any warning/errors/backtraces from the logs

I did not see any errors in dbeaver-debug.log.

**Comment by uslss** [comment]
also reproducible for snowflake. Physical Key exists, but VUK creation is proposed
![image](https://user-images.githubusercontent.com/31996417/88178972-da888580-cc33-11ea-8739-f05acbb71664.png)

**Comment by serge-rider** [comment]
Fixed in c591ce3d12edec68bb623dc0dfa47f202193ae65

**Comment by uslss** [comment]
verified

**Comment by KellyKimbleNotions** [comment]
I updated to the 2020-08-03 version 7.1.4 but it gives me the same issue.  I can't update records because it says there is no unique key.  If you go to the Table Properties, you can definitely see there is a unique key (type is PRIMARY KEY).  I had to drop back to version 7.0.2 again.  It is possible that the fix did not make it into the release?

**Comment by AllexFelicio** [comment]
Tente colocar a chave primaria no select ou de um select*from e altere a coluna que gostaria exemplo:
SELECT * FROM (tabela_nome) 
ou
SELECT (primary_key), (coluna_que_deseja_alterar) FROM (tabela_nome) WHERE (condição)

**Comment by KellyKimbleNotions** [comment]
I have tried that.  It does not work.  I gave up on getting DBeaver to work long ago.  I actually thought they fixed it once, but I think it was because I added a virtual key to the table.

**Comment by sivaraman-27** [comment]
Hi,
I have upgraded to 23.0.4 today and facing this issue. It wasn't present in previous version.
Using MySQL. Please fix it soon
