### ISSUE TITLE
[Greenplum] Custom view: database cannot be opened if Hide folders is enabled

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9298]
Operating system (distribution) and version Win10
DBeaver version 7.1.3 EA
Database name and version Greenplum

Database cannot be opened if **Hide folders** is enabled in Custom view

Steps to reproduce:
1. Press Edit connection>General
2. Select Custom Navigator view
3. Press Customize
4. Enable Hide folders only
5. Press Ok
6. Open a database

Actual result:
1. the database cannot be opened
2. Error appears:

![dbeaver_C4crjNjbi5](https://user-images.githubusercontent.com/51405061/87804757-fe775000-c85c-11ea-9019-037d2cd1344c.png)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4938686/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed (we had a redundant joins in extension read query)

**Comment by kseniiaguzeeva** [comment]
Verified
