### ISSUE TITLE
New Redshift JDBC Driver Requires Additional Jars

### ISSUE THREAD

**Issue by MichaelRBlack** [dbeaver/dbeaver#9300]
The latest version of the AWS Redshift JDBC v.1.2.45.1069 requires additional JARs if you connect to your redshift cluster using ADFS. DBeaver will download just the single JAR download but when you go to AWS to download the jar, it's a zip file of several jars together. 

The workaround is to download the AWS zip file manually, then configure DBeaver to use the manual downloaded folder. It would be nice if DBeaver would do this automatically.

https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.45.1069/RedshiftJDBC42-1.2.45.1069.zip

**Comment by uslss** [comment]
thanks for suggestion

**Comment by uslss** [comment]
seems to be implemented in #13820
