### ISSUE TITLE
Saved data filter is not loaded on startup

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#9302]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.1.2.202007051953
- Additional extensions: office

#### Connection specification:
- Database name and version: Oracle 12
- Driver name: ojdbc19
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
When I save filter settings for a table in the table editor (with the top-right "Save filter settings" icon), those are not reloaded on startup. Only the ordering is restored, but not the where condition
I looked into the file saved-data-filter.xml, and the where condition is saved there, it's just not reloaded on startup.

#### Steps to reproduce, if exist:

1. Open a table with the table editor
2. Set a where condition
3. Order some columns
4. Save filter settings
5. Close DBeaver
6. Reopen DBeaver on the same table
7. Ordering is correctly restored. The where condition, however, is not.

**Comment by uslss** [comment]
thanks for the bug report

_issue is reproducible only in case if where condition is set in Custom Filters. In case filter was set using icon near column name it is not reproducible for me_

**Comment by serge-rider** [comment]
I believe it was fixed in #9145

**Comment by uslss** [comment]
verified
