### ISSUE TITLE
SQL Server - don't recognize "go" 

### ISSUE THREAD

**Issue by ceinmart** [dbeaver/dbeaver#9303]
DBEaver 7.1.1 .
Tried with multiple drivers : 
* mssql-jdbc 8.2.2
* jtds 1.3.1
* mssql-jdbc 6.1.0

With all them the GO delimiter aren't recognized. No matter if I ran with ctrl+enter or alt+x .
I saw this question #2220, but this not working for me. 
Perhaps at first, I believe this was because there is no advanced parameter for newer mssql-jdbc, but appears to not have a relation with my issue. 

Am I missing some configuration?

![image](https://user-images.githubusercontent.com/7062410/87821504-58205000-c846-11ea-90e6-c4dba4347861.png)

![image](https://user-images.githubusercontent.com/7062410/87820949-5d30cf80-c845-11ea-8d7e-c06748091732.png)
![image](https://user-images.githubusercontent.com/7062410/87820989-6f127280-c845-11ea-918a-08f3ce168440.png)

With old jTDS
![image](https://user-images.githubusercontent.com/7062410/87821657-9584dd80-c846-11ea-8fb4-a4ea7015464a.png)

**Comment by uslss** [comment]
Hi @ceinmart ,
could you check if the 'Ignore native delimiter' option is unchecked in preferences?
![image](https://user-images.githubusercontent.com/31996417/87919791-fef03080-ca80-11ea-85d9-118e07b5472c.png)

**Comment by ceinmart** [comment]
Bingo! 
Yes, it was checked. 
I uncheck it and now is working fine. 
Thanks!
