### ISSUE TITLE
DBeaver shows wrong array values from postgres - array values are correct in database

### ISSUE THREAD

**Issue by TryAndErr0r** [dbeaver/dbeaver#9306]
#### System information: 
- W10
- Version 7.1.2.202007051953
- Additional extensions - none

#### Connection specification:
- Postgresql
- org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? -no 

#### Describe the problem you're observing:
When using an array collumn of decimal values DBeaver failes to format the values right.

When using psql in bash:
30637 | 2020-07-18 11:06:18.71624 | 2020-07-18 09:15:07.515012+00 |   2068 | {{1.0001000000000000,15351.0700000000000000},{1.0002000000000000,12050.0000000000000000},{1.0003000000000000,9650.0000000000000000},{1.0004000000000000,2479.6200000000000000},{1.0005000000000000,1966.5000000000000000}} | {{1.0000000000000000,13929.9100000000000000},{0.9999000000000000,19707.1400000000000000},{0.9998000000000000,12668.5400000000000000},{0.9997000000000000,37557.6100000000000000},{0.9996000000000000,4150.3500000000000000}}

When using DBeaver text output 
30637|2020-07-18 11:06:18|2020-07-18 11:15:07|  2068|{{1.0001000000000000,153510700000000000000,{1.0002000000000000,120500000000000000000,{1.0003000000000000,96500000000000000000,{1.0004000000000000,24796200000000000000,{1.0005000000000000,19665000000000000000}|{{1.0000000000000000,139299100000000000000,{0.9999000000000000,197071400000000000000,{0.9998000000000000,126685400000000000000,{0.9997000000000000,375576100000000000000,{0.9996000000000000,41503500000000000000}|

#### Steps to reproduce, if exist:
1. Step create table:
CREATE TABLE public.orderbookrecords (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	msgtimestamp timestamp NULL,
	databasetimestamp timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	asks _numeric NULL,
	bids _numeric NULL,
	CONSTRAINT orderbookrecords_pk PRIMARY KEY (id)
);

2. Step create record:
Insert record:
INSERT INTO public.orderbookrecords (msgtimestamp, databasetimestamp, pairid, asks, bids) VALUES('2020-07-18T11:06:18.716240'::timestamp, CURRENT_TIMESTAMP,  ARRAY[ARRAY[1.0001,15351.07],ARRAY[1.0002,12050.0],ARRAY[1.0003,9650.0],ARRAY[1.0004,2479.62],ARRAY[1.0005,1966.5]], ARRAY[ARRAY[1.0,13929.91],ARRAY[0.9999,19707.14],ARRAY[0.9998,12668.54],ARRAY[0.9997,37557.61],ARRAY[0.9996,4150.35]]);

3. Step select value via DBeaver and compair to psql output
SELECT id, msgtimestamp, databasetimestamp, asks, bids FROM public.orderbookrecords;

**Comment by uslss** [comment]
Hi @TryAndErr0r ,
unfortunately, cannot reproduce it. Probably some special steps are needed?
![image](https://user-images.githubusercontent.com/31996417/87875917-2392cc80-c9dd-11ea-9091-7fff4ca1c203.png)

**Comment by hsseo0501** [comment]
This issue is related to PostgreUtils class's parseObjectString method.
It works well for one-dimensional arrays, but parsing does not work properly if it is more than two-dimensional.

**Comment by TryAndErr0r** [comment]
> Hi @TryAndErr0r ,
> unfortunately, cannot reproduce it. Probably some special steps are needed?
> ![image](https://user-images.githubusercontent.com/31996417/87875917-2392cc80-c9dd-11ea-9091-7fff4ca1c203.png)

Funny, but still the {} are not 100% correkt. 

Maybe it has something todo with german being my main system language and the '.' and ',' in numbers being replaced for one another.

**Comment by hsseo0501** [comment]
Hi, @uslss @TryAndErr0r  I also produce it. 

That is related to object parser logic about the Postgres util. 

![image](https://user-images.githubusercontent.com/6668548/88001236-92d20300-cb3a-11ea-8429-31d2f6f96ce5.png)

I fixed the logic and produced well as follows feature.

![image](https://user-images.githubusercontent.com/6668548/88002013-70d98000-cb3c-11ea-8de7-e9e75663ff74.png)

**Comment by kseniiaguzeeva** [comment]
Verified
