### ISSUE TITLE
Select query is incorrectly executed in special case

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9309]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.3

#### Connection specification:
- Database name and version Clickhouse

#### Describe the problem you're observing:
Select query is incorrectly executed after SQL formatting (Default formatter)
#### Steps to reproduce, if exist:
1. Choose any table and Read it in SQL console
1. Apply Format SQL to query
1. Try to execute it.
![image](https://user-images.githubusercontent.com/31996417/87873102-1f5bb480-c9c7-11ea-908e-76e2e60a3469.png)

**Comment by serge-rider** [comment]
Seems to be a bug in Clickhouse driver or server-side query parser.
If query doesn't contain whitespaces (NOT including \r, \n or \t) then driver doesn't return any resultset.

**Comment by serge-rider** [comment]
Will be fixed in clickhouse-jdbc 0.2.5

**Comment by serge-rider** [comment]
Moved to 0.2.6

**Comment by zhicwu** [comment]
Thank you @uslss and @serge-rider for reporting the issue. `0.2.6` is released and it works on DBeaver(community edition 7.3.5.202102141704) according to my test just now.

**Comment by serge-rider** [comment]
@zhicwu thank you for the update

**Comment by uslss** [comment]
verified
