### ISSUE TITLE
Column couldn't be created for existing table using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9310]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.3

#### Connection specification:
- Database name and version Sybase

#### Describe the problem you're observing:
When  trying to create and save column for existing table, error appears
![image](https://user-images.githubusercontent.com/31996417/87874534-402a0700-c9d3-11ea-8d36-af68a437a3b2.png)

Generated query that ends with error
`ALTER TABLE master.dbo.NewTable ADD Column3 tinyint GO`
Query that is successfully executed
`ALTER TABLE master.dbo.NewTable ADD Column3 tinyint NULL GO`

**Comment by serge-rider** [comment]
Fixed (we need explicit NULL modifier for all new Sybase columns)

**Comment by uslss** [comment]
verified
