### ISSUE TITLE
View couldn't be changed

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9311]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.3

#### Connection specification:
- Database name and version sybase
#### Describe the problem you're observing:
When trying to change view's definition and save it - it ends with an error. Create statement is used
![image](https://user-images.githubusercontent.com/31996417/87874667-440a5900-c9d4-11ea-8b7b-feae13645bef.png)

**Comment by serge-rider** [comment]
Fixed by patching view DDL (use CREATE OR REPLACE command)

**Comment by uslss** [comment]
verified
