### ISSUE TITLE
Error appears while opening Indexes for Schema

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9312]
#### System information: 
- Operating system (distribution) and version win10 
- DBeaver version 7.1.3

#### Connection specification:
- Database name and version Sybase

#### Describe the problem you're observing:
Error appears while opening Indexes tab for Schema
![image](https://user-images.githubusercontent.com/31996417/87874781-53d66d00-c9d5-11ea-9927-2390cedd95dc.png)

**Comment by serge-rider** [comment]
Fixed.

Schema-level index read not supported by Sybase driver (driver throws error). So we get indexes from schema tables.

**Comment by uslss** [comment]
verified
