### ISSUE TITLE
[Greenplum] Table cannot be created via UI

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9313]
#### System information:  
- Operating system (distribution) and version Win10
- DBeaver version 7.1.3 EA

#### Connection specification:
- Database name and version Greenplum

#### Describe the problem you're observing:
Table cannot be created via UI
#### Steps to reproduce, if exist:
1. Select Create new table in a schema context menu
2. Create a column in an opened window
3. Press Save

Actual result:
1. The table is not created
2. Error appears
 "SQL Error [25P02]: ERROR: current transaction is aborted, commands ignored until end of transaction block
  ERROR: current transaction is aborted, commands ignored until end of transaction block
    ERROR: relation "public.newtable_3gg" does not exist
  Position: 29"

Workaround: create a table via SQL Editor

**Comment by serge-rider** [comment]
Can't reproduce (table are created without problem).
The error (current transaction is aborted ...) is a result of some previously failed operation.

@kseniiaguzeeva Please provide more precise steps to reproduce.

**Comment by lmacedo-pivotal** [comment]
Can't reproduce the error. Either...

DBeaver 7.1.3 on Mac. GPDB 6.8.

@kseniiaguzeeva what is your GPDB version?

**Comment by kseniiaguzeeva** [comment]
Steps:
1. Connect to Greenplum
2. Expand it in DB Navigator
3. Select Create table in tables folder context menu
4. Create a column in the opened window
5. Press Save

Actual result: Error appears, the table is not created.
version 7.1.3.202007230724 
Driver
![dbeaver_FIep7Ec0rC](https://user-images.githubusercontent.com/51405061/88384711-9fae5b00-cdb5-11ea-932f-c84e4e08942c.png)
![dbeaver_MnOLeUXr8c](https://user-images.githubusercontent.com/51405061/88384973-22cfb100-cdb6-11ea-9b56-9590adfee430.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
