### ISSUE TITLE
[Greenplum] Metadata Search doesn't work when procedure search is enabled

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9314]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.3 EA

#### Connection specification:
- Database name and version Greenplum

#### Describe the problem you're observing:
Metadata Search doesn't work when function search is enabled
#### Steps to reproduce, if exist:

1. Select active schema for Greenplum in Metadata Search
2. Enter a valid data in Object name field
3. Enable Object type Procedure
4. Press Search

Actual result:
1. Window is closed
2. Object is not found
3. Error appears: "SQL Error [42883]: ERROR: could not identify an ordering operator for type aclitem[]
  Hint: Use an explicit ordering operator or modify the query.
  Position: 23"
![ZLE8Sl21Oy](https://user-images.githubusercontent.com/51405061/87875938-3dccaa80-c9dd-11ea-9d9e-7d1db6b228e4.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
