### ISSUE TITLE
Creating a project from git is imposible after its deleting

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9315]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.3 EA
- Additional extensions

#### Describe the problem you're observing:
Creating a project from git is imposible after its deleting
#### Steps to reproduce, if exist:
Precondition: Created project from Git exists (https://github.com/dbeaver-corp/dbeaver-qa/wiki/Test-connections-on-Git)
Steps:
1. Delete project folder from local storage (...\git\dbeaver-qa)
2. Press File>Git
3. Follow steps from the instruction https://github.com/dbeaver-corp/dbeaver-qa/wiki/Test-connections-on-Git

Actual result:
Impossible to finish the wizard. See picture
![dbeaver_g0jfoT8RBy](https://user-images.githubusercontent.com/51405061/87877365-98b6cf80-c9e6-11ea-8af7-1fdaa56d6b7f.png)

**Comment by akilovich** [comment]
More than that, it's impossible to complete the wizard with the instructions above even for the first time. Manual deletion of .project file fixes the problem, though.

**Comment by kseniiaguzeeva** [comment]
Workaround: go one step back in the wizard, delete .project from the folder and finish the wizard.
