### ISSUE TITLE
SQL generated from filtering operation does not contain double quote on  varchar type field 

### ISSUE THREAD

**Issue by wzj103306** [dbeaver/dbeaver#9317]
#### System information: 
- Operating system (distribution) and version：windows 10
- DBeaver version：7.1.2
- Additional extensions：none

#### Connection specification:
- Database name and version：presto
- Driver name：
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing
I want to filter some data in a table，so I click on the filtering button. Then I click some data which I’m interested in，and apply.
What is confused me is that the sql generated by such operations does not contain quote or double quote. So I have to queto these data on my own.
I use this filter operation frequently in a day, and sometimes I filter several data. It takes me a lot of time to quote.

Is is a Bug? Or I just use it in a wrong way? Help me

The steps to reprpduce such problem follows as these pictures.

Thanks

#### Steps to reproduce, if exist
![image](https://user-images.githubusercontent.com/6669181/87896982-82f3e980-ca7c-11ea-9d70-fa9c3f824a6f.png)
![image](https://user-images.githubusercontent.com/6669181/87896986-87b89d80-ca7c-11ea-9b06-de6befc51c59.png)
![image](https://user-images.githubusercontent.com/6669181/87896996-8c7d5180-ca7c-11ea-8cba-b00daa733d21.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
DBeaver can't recognize column type. As see that it has "Object" type icon - that's why the value is not enquoted.

@wzj103306 What type name column has? What target database is behind Presto?

**Comment by wzj103306** [comment]
> DBeaver can't recognize column type. As see that it has "Object" type icon - that's why the value is not enquoted.
> 
> @wzj103306 What type name column has? What target database is behind Presto?

Hi，serge-rider
The type of column I mentioned above is string or varchar
And the target database behind Presto is mysql

**Comment by akilovich** [comment]
Hi, @wzj103306. I can't reproduce the bug against the 7.2.2 version. Are you sure that the database behind Presto is MySQL? In the screenshot you posted above, it appears that you are targeting Hive. Would you please send us an example of table DDL, name, and version of the database behind Presto. Thanks.

**Comment by uslss** [comment]
there are not any updates more than a month.
Issue is closed.
If it is still actual for you - feel free to reopen it
