### ISSUE TITLE
DBeaver Community Edition v7.1.3 start-up loop

### ISSUE THREAD

**Issue by bramhoven** [dbeaver/dbeaver#9319]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro - v1903
- DBeaver version: 7.1.3
- Additional extensions: None

#### Describe the problem you're observing:

This morning when starting up DBeaver I got a notification that there was a new version available. After I had downloaded and installed this new version, DBeaver has been acting up. It starts to show the splash screen then it disappears and shows again. I guess it is fails and tries to restart, but I have no clue. I also can't end the process in task manager, since it just creates new processes each time.

#### Steps to reproduce, if exist:

Install the new version 7.1.3

#### Include any warning/errors/backtraces from the logs

I can't find any log files in these locations:
* <install-path>/configuration
* ${HOME}/.eclipse/org.jkiss.dbeaver.product_<dbeaver-version>

#### EDIT

Downgrading back to 7.1.2 is a quick work-around

**Comment by uslss** [comment]
Hi @bramhoven ,
probably, something going wrong during the installation. Could you try to reset the workspace? https://github.com/dbeaver/dbeaver/wiki/Reset-workspace
Wait for your response if it helps or not

**Comment by bramhoven** [comment]
@uslss That did indeed fix it!
Thanks for the quick response :D

**Comment by mk1tools** [comment]
Same problem. After each DBeaver upgrade (version 7 and now version 21.x.x), I install Office plugin. Then DBeaver start to loop on splash screen.
I install DBeaver for "anyone" on Windows 10.
I found this workaround:
1. upgrade Dbeaver
2. Start Dbeaver and install Office plugin, without automatic restart. Close Dbeaver.
3. Start DBeaver "as administrator" and install Office plugin, without automatic restart. Close Dbeaver.
4. Start DBeaver "as administrator". Close Dbeaver.
5. Start DBeaver normally

**Comment by mioux** [comment]
The solution proposed by @mk1tools worked until 21.1.2

I have to start it as administrator each time for this version

**Comment by Erdnah** [comment]
@mioux My startup loop was fixed by running dbeaver with "-clean" command line parameter.

**Comment by adrianag-redabogacia** [comment]
As @Erdnah pointed out, the simplest solution is changing dbeaver.ini (typically on C:\Program Files\DBeaver), add: 
`-clean`. 
It's annoying that you have to do it every time DBeaver is updated; so I usually don't update unless it brings some improvement I will really make the most of.
