### ISSUE TITLE
language option not respected

### ISSUE THREAD

**Issue by jrosetim** [dbeaver/dbeaver#9323]
#### System information: 
- Operating system (distribution) and version > Windows 10 1909
- Version 7.1.3.202007192031
- No Additional extensions

#### Describe the problem you're observing:
In the settings, when I select the language option to be in English, it is not being respected, it is always in Brazilian Portuguese, I am changing the settings in window> Preference> DBeaver> Language

**Comment by kseniiaguzeeva** [comment]
Please check what is written in Object line of DBeaver label properties. Do you have -nl -something there?
![explorer_rtCLpESaaH](https://user-images.githubusercontent.com/51405061/87938827-cf9cec00-ca9f-11ea-8a8c-1f26f097979d.png)

**Comment by jrosetim** [comment]
It has the default settings, nothing has been changed!

![image](https://user-images.githubusercontent.com/33268673/87962394-7e83fc80-ca8d-11ea-9541-42e0afd4e0b1.png)

**Comment by kseniiaguzeeva** [comment]
I caught a little other issue. When I change language from English to another and restart DBeaver, the change is applied, but when I go to  window> Preference> DBeaver> Language, there are written English again in the settings.

When you change the language to English, DBeaver isn't translated after restart, correct?

**Comment by jrosetim** [comment]
Correct, no matter what I do, I can't get it in English.

**Comment by lmacedo-pivotal** [comment]
Same issue I am having... The languages looks mixed up too, part in English, part in Portuguese. 

I am on macOS Catalina. 10.15.5

**Comment by kseniiaguzeeva** [comment]
Please send 2 screenshots:
1. when English is selected.
2. when Portuguese is selected

**Comment by kseniiaguzeeva** [comment]
Finally I caught the bug. 
Steps:
1. go to Preferences>DBeaver
2. Set Portuguese language
3. Restart DBeaver
4. Open Preferences>DBeaver again.

Actual result:
- the menu is only partially translated
- English language is displayed in locale settings.
![dbeaver_ENcciWu9vm](https://user-images.githubusercontent.com/51405061/88534026-e9927d80-d00f-11ea-8644-b8359b01dc11.png)

**Comment by serge-rider** [comment]
You need to reset UI settings (main menu File) to clean up UI elements cache.
Also note: some UI elements are not translated at all.

We will update translation of standard elements and preferences in version 7.1.5
