### ISSUE TITLE
Is it normal to have to add the database name in my Athena queries?

### ISSUE THREAD

**Issue by ryancabanas** [dbeaver/dbeaver#9325]
#### System information: 
_Operating System:_  Windows 10 Pro, Version 1809, Build 17763.1282
_DBeaver Version:_  7.1.3

#### Connection specification:
_Database:_  AWS Athena

#### Describe your question:
Hi,

I just created my first successful connection to AWS Athena!  In running some test queries, I found that I must specify the name of the database in my queries to get them to succeed, like this:

`select firstname from "mydatabase".mytable;`

The **"Active catalog/schema"** dropdown has the desired database selected.

Is this normal to have to fully qualify all queries with the database name like this?

Thanks!
Ryan

**Comment by kseniiaguzeeva** [comment]
It is a kind of bug. Thank you for the report.

**Comment by serge-rider** [comment]
Generally it depends on Athena driver..

**Comment by serge-rider** [comment]
It also depends on driver (Simba) behavior.

**Comment by serge-rider** [comment]
We can't fix it from the dbeaver side.
