### ISSUE TITLE
Tab switches on connect to database

### ISSUE THREAD

**Issue by dbajaj1** [dbeaver/dbeaver#9326]
#### System information: 
- Operating system (distribution) and version: MacOS 10.15.5
- DBeaver version Version 7.1.3.202007192031
- Additional extensions: None

#### Connection specification:
- Database name and version AWS/MySQL
- Driver name: Latest version
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH 

#### Describe the problem you're observing:
When dbeaver opens, it connects to a database. If more than 1 tab open, the tab will switch from tab a to tab b once the database is connected in tab a.
#### Steps to reproduce, if exist:
Open two tabs  with different databases connected to both tabs. Save, Quit. Open Dbeaver, once a connection is made, the tab will switch.

**Comment by kseniiaguzeeva** [comment]
Unfortunately I have not opportunity to reproduce it. Could you please send a video with the bug?

**Comment by dbajaj1** [comment]
Hello @kseniiaguzeeva, please see the video recording. I have only recorded the top (including the tabs) because below that are connection settings in text.
[bug_recorded.zip](https://github.com/dbeaver/dbeaver/files/5042287/bug_recorded.zip)

**Comment by dbajaj1** [comment]
@kseniiaguzeeva Hello, checking back in on this. Thank you.

**Comment by Matvey16** [comment]
@dbajaj1 Can you test this on the latest 21.2.5. I can't reproduce this anymore.

**Comment by dbajaj1** [comment]
@Matvey16 I can confirm that I am still able to reproduce this behavior. Would you like me to provide another video? Or is there any other info I can provide that will help reproduce this bug?

**Comment by Matvey16** [comment]
@dbajaj1 Yes, I would like to know some more details. Can this be reproduced if you have only 2 scripts open and they are associated with the same data source? If it happens only with different data sources, what are the databases that it is reproduced on?
Will this bug reproduce if you start DBeaver and focus is on the leftmost tab? If you disconnect from the connection in already running Dbeaver and click on a tab with a script that is associated with that connection, will the focus change?
Also I would like to know how are your preferences configured, particularly those:

![dbeaver_Fc3M9U14O6](https://user-images.githubusercontent.com/82543000/142146177-f9dbeff2-6910-4c2f-95ef-5dcaac77d4ce.png)

![dbeaver_e7FU6JtZLd](https://user-images.githubusercontent.com/82543000/142146188-888c8bc7-dbd1-4bce-b776-a36a1f680da7.png)

![dbeaver_F9gbbrJRHw](https://user-images.githubusercontent.com/82543000/142146197-b85cdccd-acd1-4eec-9263-e9bffbba2141.png)

**Comment by dbajaj1** [comment]
@Matvey16
Okay, so in order of the requests:
Can this be reproduced if you have only 2 scripts open and they are associated with the same data source? Yes, this still happens.
If it happens only with different data sources, what are the databases that it is reproduced on? The two databases I use are PostGres and Redshift
Will this bug reproduce if you start DBeaver and focus is on the leftmost tab? Yes, in that case, rather than shifting to a left tab, the focus shifts to the tab on the right of the first tab.
If you disconnect from the connection in already running Dbeaver and click on a tab with a script that is associated with that connection, will the focus change? Yes, this still is the case.

Regarding the screenshots:
![image](https://user-images.githubusercontent.com/50336413/142147474-35882ad0-a7a4-4462-aad5-946935799b99.png)
![image](https://user-images.githubusercontent.com/50336413/142147504-9eb96709-a4fb-471d-b459-b1eebf00b0f5.png)
![image](https://user-images.githubusercontent.com/50336413/142147621-5d318be2-50ce-4b1a-b90e-451dcfdd8d99.png)

**Comment by Matvey16** [comment]
@dbajaj1 I see that the firs time you reported this issue, you were using MacOS Catalina. Did it also occur on later versions or are you still using Catalina?

**Comment by dbajaj1** [comment]
I am on the latest version

**Comment by dbajaj1** [comment]
Ie, Monterey

**Comment by dbajaj1** [comment]
@Matvey16

**Comment by Matvey16** [comment]
@dbajaj1 Could you please record another video, but with more visible details. Particularily I need to see what happens in background tasks and database navigator. If you have sencible information you can use blank scripts and hide hosts names in navigator.
![NntrvTF3Ph](https://user-images.githubusercontent.com/82543000/142398968-39b5b72d-11cb-4705-a815-fab8cb12d405.png)

How to open background tasks

![87dcoTUGyI](https://user-images.githubusercontent.com/82543000/142399012-1a26b736-cd78-4508-bf2c-c17baefe566f.png)
![dbeaver_jRltlpiJJZ](https://user-images.githubusercontent.com/82543000/142399021-90dd82b4-f79e-45ae-87fe-70f9a97de8aa.png)

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info

**Comment by dbajaj1** [comment]
Hi @uslss Its not that I don't want to update, I just can't find the menu item connection view that @Matvey16 showed in the first screenshot every time I sit down to do this. I'm on Version 21.3.1.202112111946. (Mac)

**Comment by Matvey16** [comment]
@dbajaj1 It should be in the context menu when you right-click the connection in navigator

**Comment by dbajaj1** [comment]
@Matvey16
[trim2.mov.zip](https://github.com/dbeaver/dbeaver/files/8207885/trim2.mov.zip)

**Comment by dbajaj1** [comment]
@uslss I do not see a way to re-open the issue

**Comment by LonwoLonwo** [comment]
Hello @dbajaj1 
Can you please test the latest DBeaver version please? https://dbeaver.io/download/

**Comment by dbajaj1** [comment]
Hi @LonwoLonwo, I can confirm that I am on the latest version and still have the issue.
I've been installing the latest versions religiously every update in the hopes that it somehow fixes the issue.
<img width="431" alt="image" src="https://user-images.githubusercontent.com/50336413/163017040-4c8cdaa8-75a5-4a4d-a371-fee129d195cc.png">

**Comment by LonwoLonwo** [comment]
Could you please try resetting the workspace? You can find the instructions here: 
https://dbeaver.com/docs/wiki/Reset-workspace/

**Comment by dbajaj1** [comment]
Has not seemed to help.

**Comment by ShadelessFox** [comment]
We need to investigate the issue from the developer's perspective. It doesn't seem to be a platform-specific issue.

**Comment by emironovDB** [comment]
Hi @dbajaj1,

Have you tried installing the latest version of DBeaver?

Is the problem still present?

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
