### ISSUE TITLE
Different color marking for Boolean column value(s)

### ISSUE THREAD

**Issue by ghYura** [dbeaver/dbeaver#9327]
Color distinction visual among lots of Boolean column values in rows. #Usability #Color #Boolean
Current same blue color unreadable among others visually for Boolean type column values.

Please, mark depicted value (or background color) with color 
- Deep Green for 'true' [v]        or Light-light Green for cell background
- Deep Red for 'false' [ ]         or Light-light Red for cell background
- (any other but in contrast with whole cell background color) for 'null' [?]

Thank you.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by ghYura** [comment]
In addition, please consider **[x]** symbol for 'false' values

**Comment by bbulanda** [comment]
Hello! 

I've got a question regarding display of boolean in query result (7.1.3). 
I've been going through all settings and wiki as well, but can't seem to find a resolution to my issue.

The case is: is there a way to set globally for all the queries, to display boolean in data types in query results as "true/false" instead of graphical display (squares)? 

I'd much appreciate your help with this.

**Comment by ghYura** [comment]
View mode should be managable is settings. Some one like strict, other - decorated.

**Comment by BlaisePolonais** [comment]
> View mode should be managable is settings. Some one like strict, other - decorated.

Well, of course. I was kind of looking where I can adjust it. 
Missed it the first time, now found it. 
Window > Preferences > DBeaver > Editors > Data editor > Presentation > Grid > Last checkbox on the right side list. 

Thanks for your time, though.

**Comment by mkgrgis** [comment]
This feature request is about boolean display infrastructure, there is other feature request about this https://github.com/dbeaver/dbeaver/issues/7787.

**Comment by serge-rider** [comment]
Let's try to visualize checkboxes as unicode symbols instead of icons.

**Comment by mkgrgis** [comment]
Different regular text forms from #7787

- NLS forms for the values true/false (I think NULL is universal and needn't translation) for school students. Code with constants through properties files like other translations
- The form "+/-/?" (with whitespace switching) for industrial documents ("german" or "old office" notation )
- The original form by official console client (for PostgreSQL it is t/f) if there is.
- In #9327 @ghYura proposes [v] [x] [ ] console notation. There is any Unicode equivalent forms: ☐☑☒ or ✔✘ .

**Comment by uslss** [comment]
ubuntu - ok

**Comment by uslss** [comment]
at properties tab and in column creation pop-up checkboxes still remain pictures - not Unicode symbols

**Comment by kseniiaguzeeva** [comment]
Mac:
- settings window blinks after switching column to boolean view
- cell with NULL value in boolean format shows in Value panel data as was in previously pressed boolean cell

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by ghYura** [comment]
Implemented Not as desired in this issue. Verified.
Implementation is absolutely worse! Have you read customer feedback in comments/ descriptions? Where is the COLOR DIFFERENCING? Icons even became smaller!
Looks like you are trying to make it worse and revert to old feature design (also not usable)? 
Sorry, prove me I am wrong and I would accept that.

**Comment by kseniiaguzeeva** [comment]
@ghYura thanks for your feedback. Let's see what we can do.

**Comment by ghYura** [comment]
> @ghYura thanks for your feedback. Let's see what we can do.

Expected view and behavior to the right:
![9327expected](https://user-images.githubusercontent.com/42974628/99234979-eeb54b80-27fd-11eb-8ea5-d3908f675b6f.jpg)

**Comment by pyrocks** [comment]
@ghYura I personally don't find your suggested picture very much appealing, but it's a matter of perspective.
Whatever exists now works OK for me.

**Comment by p91paul** [comment]
also, colored items wouldn't go well with row colors feature

**Comment by p91paul** [comment]
@ghYura maybe you could use that instead. You can color cells or entire rows based on their value. You can find the feature right clicking on a cell, there's a submenu for that

**Comment by ghYura** [comment]
> @ghYura I personally don't find your suggested picture very much appealing, but it's a matter of perspective.
> Whatever exists now works OK for me.

See, as I mentioned before above: all view-mode customisations shold be configurable via wide "Settings..." menu
Someone like strict, other - decorated (even on ther own(!)).

**Comment by ghYura** [comment]
This issue is not considered as closed since COLOR differencing was not implemented at all yet.
