### ISSUE TITLE
Can not filter table after create table in filter mode

### ISSUE THREAD

**Issue by smcdl** [dbeaver/dbeaver#9330]
#### System information: 
- Operating system (distribution) and version: MacOS
- DBeaver version: 7.1.2
- Additional extensions: Nothing

#### Connection specification:
- Database name and version: MySQL 5.7
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
1. input a table name in filter textbox which does not exists in db 
2. input a table creation sql in script editor and execute it
3. click refresh on navigation bar of table or F5
4. the table does not show, delete a letter end of table name in the filter textbox 
5. the table is show.

#### Steps to reproduce, if exist:
Please refer to description.

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce it. Do you click on tables folder and then press F5?

**Comment by smcdl** [comment]
I found even delete the table, it will not disappear when click on tables folder and then press F5 or click refresh menu item.

**Comment by smcdl** [comment]
Because I always use Chinese language so when I switch English language the problem is disappear. even I switch back to Chinese language the problem is never appear again.

**Comment by kseniiaguzeeva** [comment]
Please send table DDL from step 2

**Comment by smcdl** [comment]
@kseniiaguzeeva I can not do that cause of the security rules of my company.  But it is ok when I switch to English language.
