### ISSUE TITLE
Can I use .pgpass authentication from command-line?

### ISSUE THREAD

**Issue by dtseiler** [dbeaver/dbeaver#9335]
#### System information: 
- Operating system (distribution) and version: MacOS 10.15.6
- DBeaver version: 7.1.3.202007192031

#### Connection specification:
- Database name and version: PostgresSQL 12.3

#### Describe your question:

I want to use DBeaver from the command-line, passing in all connection info as well as the username. However I don't want to have the password on the CLI arguments list. I see DBeaver supports `pgpass`, but it doesn't seem to be looking there for my CLI connection. I don't see any mention of pgpass.

If I don't specify the password, I get:

> The server requested password-based authentication, but no password was provided.

I see the data-sources.json describes it as `"auth-model": "postgres_pgpass"`, I tried passing in various versions of these strings but no dice. Is pgpass supported for CLI usage or am I missing something obvious?

**Comment by kseniiaguzeeva** [comment]
Could you please send an example of a command you use in command line to connect to PostgreSQL via pgpass?

**Comment by dtseiler** [comment]
Here is an example of how I use it now and this works:
```
/Applications/DBeaver.app/Contents/MacOS/dbeaver -con "driver=postgresql|create=false|connect=true|name=postgres1_staging|host=postgres1.staging.foo.com|port=5432|database=foo|user=USERNAME|password=PASSWORD"
```

Ideally I'd like to just leave the password off and have it refer to my `~/.pgpass` file.

**Comment by kseniiaguzeeva** [comment]
It should be implemented

**Comment by dtseiler** [comment]
@kseniiaguzeeva is there a PR I can reference?

**Comment by kseniiaguzeeva** [comment]
While not. We are going to do it in 7.2.0 release

**Comment by dtseiler** [comment]
OK I understand. So it is on your roadmap for 7.2.0.

**Comment by serge-rider** [comment]
PgPAss (and other non-default auth models) support was added. 
See 
https://github.com/dbeaver/dbeaver/wiki/Command-Line#connection-parameters and 
https://github.com/dbeaver/dbeaver/wiki/Database-authentication-models

**Comment by dtseiler** [comment]
Fantastic! So it will be out with 7.2.0? Do you have a rough ETA?

**Comment by uslss** [comment]
@dtseiler Yes, you're right. 7.2.0 CE release date is July 31. In nearest future EA version would be available here https://dbeaver.io/files/ea/

**Comment by uslss** [comment]
verified

**Comment by dtseiler** [comment]
> @dtseiler Yes, you're right. 7.2.0 CE release date is July 31. In nearest future EA version would be available here https://dbeaver.io/files/ea/

July 31 ... 2021?

**Comment by uslss** [comment]
omg, shame on me. August, of course

**Comment by dtseiler** [comment]
oh whew. That's great!
