### ISSUE TITLE
in-cell edit doesn't work for redshift

### ISSUE THREAD

**Issue by jj-klarna** [dbeaver/dbeaver#9336]
[with the latest update, I can not seem to edit in-cell any redshift database, I have checked 2 other redshift and 1 mssql, and it's only redshift, rolling back to different dbeaver version seems to cause problems with the driver download. I can update cells the normal way with the 'UPDATE' query, also I can create and delete tables with the quick links as well, it's just the in-cell edit that seems to be broken]
![2020-07-21_16-18-05](https://user-images.githubusercontent.com/68601149/88066286-e01b9800-cb6d-11ea-926c-85750ed3b556.png)
![2020-07-21_16-18-35](https://user-images.githubusercontent.com/68601149/88066289-e1e55b80-cb6d-11ea-8d90-d435f36f5fe4.png)

**Comment by uslss** [comment]
Hi @jj-klarna , what dbeaver version do you use?

**Comment by jj-klarna** [comment]
version 7.1.3.202007191748
On windows 10

**Comment by jj-klarna** [comment]
This has been fixed with the new update today, thanks for the great work!
