### ISSUE TITLE
CSV Export of Chinese Characters

### ISSUE THREAD

**Issue by quinton3200** [dbeaver/dbeaver#9337]
#### System information: 
- Operating system (distribution) and version  Windows 10, 64 bit  pro
- DBeaver version  7.1.1
- Additional extensions

#### Connection specification:
- Database name and version  Greenplum
- Driver name    PROGRESS_DATADIRECT_JDBC_DRIVER_PIVOTAL_GREENPLUM_5.1.4
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
When I export results that have text in Chinese it looks fine in the results window of DBeaver but  the exported csv file contains giberish.  I am using UTF-8.  I have tried several others and get the same results.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Could you please send a table example with table data?

**Comment by quinton3200** [comment]
I am not sure how to do that.  Here is a screen shot of what is in the results data.

查看CUE显示屏外观完好，屏幕平滑完整，无外力与人为拆装的痕迹，在车内未发现香水等化学物品，尝试断电，断电后故障依旧，尝试替换调幅/调频立体声收音机，故障排除，故判断为调幅/调频立体声收音机故障导致。      更换调幅/调频立体声收音机控制        显示屏有一条黑线
经技师检查，因座椅箍架问题，无法后移，无人为损坏痕迹 更换主驾座椅箍架        主驾座椅靠背无法后移




Here is what is looks like when the CSV files is opened in excel

ç»è½¦é—´æŠ€å¸ˆæ£€æµ‹æ•…éšœå­˜åœ¨ï¼Œè¡¨é¢å…‰æ»‘æ— å—åŠ›ç—•è¿¹ï¼Œäº’æ¢åŽè§†é•œæ€»æˆæ•…éšœæ¶ˆå¤±ï¼Œå»ºè®®æ›´æ¢å·¦å‰åŽè§†é•œæ€»æˆ

æŠ€å¸ˆæ£€æŸ¥æ•…éšœå­˜åœ¨ï¼Œæ‹†æ£€æ£€æŸ¥æœªå‘çŽ°æœ‰åŠ è£…ï¼Œæ£€æŸ¥æœªå‘çŽ°çº¿è·¯å¼‚å¸¸ï¼Œé‡æ–°æ‹†è£…ä»æ˜¯å‡ºçŽ°æ— æ³•æŠ˜å çš„æ•…éšœï¼ŒæŽ’é™¤äº†æŠ˜å å¼€å…³çš„é—®é¢˜ï¼Œå»ºè®®æ›´æ¢å·¦åŽè§†é•œæ€»æˆ

å®¢æˆ·ååº”å·¦åŽè§†é•œæ— æ³•æŠ˜å












ç”µè„‘æ£€æŸ¥æ•…éšœç ä¸ºçº¦æŸç³»ç»ŸæŽ§åˆ¶æ¨¡å— U3000 49 æŽ§åˆ¶æ¨¡å— å†…éƒ¨æ•…éšœ åŽ†å²è®°å½• ç­‰æ•…éšœç ï¼Œæ£€æŸ¥çº¿è·¯æ— å¼‚å¸¸ï¼Œç”µè„‘æµ‹è¯•æ— å¼‚å¸¸

æ›´æ¢å®‰å…¨æ°”å›Šä¼ æ„Ÿå’Œè¯Šæ–­æ¨¡å—ï¼›

æ˜¨å¤©å®¢æˆ·æ‰“ç”µè¯æŠ¥ä¿®ä»ªè¡¨æé†’ç»´ä¿®å®‰å…¨æ°”å›Šç­‰æ•…éšœç ï¼Œä»Šå¤©è¿‡æ¥æ£€æŸ¥åˆæ²¡æœ‰äº†

**Comment by quinton3200** [comment]
No luck on this one since we can’t duplicate it?

From: Jeffrey C Quinton
Sent: Wednesday, July 22, 2020 11:22 AM
To: 'dbeaver/dbeaver' <reply@reply.github.com>
Subject: RE: [EXTERNAL] Re: [dbeaver/dbeaver] CSV Export of Chinese Characters (#9337)

I am not sure how to do that.  Here is a screen shot of what is in the results data.

查看CUE显示屏外观完好，屏幕平滑完整，无外力与人为拆装的痕迹，在车内未发现香水等化学物品，尝试断电，断电后故障依旧，尝试替换调幅/调频立体声收音机，故障排除，故判断为调幅/调频立体声收音机故障导致。      更换调幅/调频立体声收音机控制        显示屏有一条黑线
经技师检查，因座椅箍架问题，无法后移，无人为损坏痕迹 更换主驾座椅箍架        主驾座椅靠背无法后移




Here is what is looks like when the CSV files is opened in excel

ç»è½¦é—´æŠ€å¸ˆæ£€æµ‹æ•…éšœå­˜åœ¨ï¼Œè¡¨é¢å…‰æ»‘æ— å—åŠ›ç—•è¿¹ï¼Œäº’æ¢åŽè§†é•œæ€»æˆæ•…éšœæ¶ˆå¤±ï¼Œå»ºè®®æ›´æ¢å·¦å‰åŽè§†é•œæ€»æˆ

æŠ€å¸ˆæ£€æŸ¥æ•…éšœå­˜åœ¨ï¼Œæ‹†æ£€æ£€æŸ¥æœªå‘çŽ°æœ‰åŠ è£…ï¼Œæ£€æŸ¥æœªå‘çŽ°çº¿è·¯å¼‚å¸¸ï¼Œé‡æ–°æ‹†è£…ä»æ˜¯å‡ºçŽ°æ— æ³•æŠ˜å çš„æ•…éšœï¼ŒæŽ’é™¤äº†æŠ˜å å¼€å…³çš„é—®é¢˜ï¼Œå»ºè®®æ›´æ¢å·¦åŽè§†é•œæ€»æˆ

å®¢æˆ·ååº”å·¦åŽè§†é•œæ— æ³•æŠ˜å












ç”µè„‘æ£€æŸ¥æ•…éšœç ä¸ºçº¦æŸç³»ç»ŸæŽ§åˆ¶æ¨¡å— U3000 49 æŽ§åˆ¶æ¨¡å— å†…éƒ¨æ•…éšœ åŽ†å²è®°å½• ç­‰æ•…éšœç ï¼Œæ£€æŸ¥çº¿è·¯æ— å¼‚å¸¸ï¼Œç”µè„‘æµ‹è¯•æ— å¼‚å¸¸

æ›´æ¢å®‰å…¨æ°”å›Šä¼ æ„Ÿå’Œè¯Šæ–­æ¨¡å—ï¼›

æ˜¨å¤©å®¢æˆ·æ‰“ç”µè¯æŠ¥ä¿®ä»ªè¡¨æé†’ç»´ä¿®å®‰å…¨æ°”å›Šç­‰æ•…éšœç ï¼Œä»Šå¤©è¿‡æ¥æ£€æŸ¥åˆæ²¡æœ‰äº†

**Comment by kseniiaguzeeva** [comment]
Still cannot reproduce. Please tell your column type.

**Comment by mkgrgis** [comment]
It can be a problem with Excel. Excel as program for Windows doesn't attribute any unmarked data as Unicode eg. UTF-8.

**Comment by kseniiaguzeeva** [comment]
@quinton3200 Can you open CSV file by another program?

**Comment by quinton3200** [comment]
It comes over as Chinese in NotePad++

**Comment by quinton3200** [comment]
It comes over as Chinese in NotePad++ so you must be right

**Comment by kseniiaguzeeva** [comment]
In this case the ticket is closed. Please reopen if you still have any questions.

**Comment by quinton3200** [comment]
Thank you for looking at this.  We used to use Terradata SQL assistant and it worked fine but in that case you could copy and paste the results area into an excel spread sheet.
