### ISSUE TITLE
Font change after in-cell editing

### ISSUE THREAD

**Issue by L3v3L** [dbeaver/dbeaver#9338]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro N Version 2004 Build 20170.1000
- DBeaver version: 7.1.3.202007192031
- Additional extensions: None

#### Describe the problem you're observing:
After triggering the in-cell editing, a lot of the labels in the app change font, and some change after hovering over.

#### Steps to reproduce, if exist:
Double press a cell to trigger in-cell editing.

#### Include any warning/errors/backtraces from the logs

Here is a screenshot of just before I double click in a cell:
![image](https://user-images.githubusercontent.com/30056/88097968-ea9b5900-cb90-11ea-8556-fda651a0af89.png)

Here is a screenshot of just after I double click in a cell (note that most of dbeaver has this font now, I can send more screenshots of other places if needed):
![image](https://user-images.githubusercontent.com/30056/88097986-f2f39400-cb90-11ea-8afa-85bee1dabbd2.png)

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Please tell your database and locale

**Comment by L3v3L** [comment]
after looking around ([this might be related](https://github.com/dbeaver/dbeaver/issues/9211)), and the issue might be due to my windows insider version.

**Comment by L3v3L** [comment]
I can confirmed, just updated windows to build 20175.1000 and problem has gone.
