### ISSUE TITLE
Can not copy and paste a table from remote to local db

### ISSUE THREAD

**Issue by smcdl** [dbeaver/dbeaver#9341]
#### System information: 
- Operating system (distribution) and version: MacOS
- DBeaver version: 7.1.3
- Additional extensions: Nothing

#### Connection specification:
- Database name and version: MySQL 5.7
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
Can not copy and paste a table from remote to local db

#### Steps to reproduce, if exist:
1. select a table in tables folder on remote db and press Command + C or click Copy menu item.
2. select a tables folder on local db and press Command + V or click Paste menu item.
3. click Save button on the tab of table creation and then show error window.

![image](https://user-images.githubusercontent.com/4975064/88126318-d5134700-cc03-11ea-828c-66608ce0f15f.png)

**Comment by smcdl** [comment]
Even it does not work copy from db A to db B  in local server no matter the table cotains records or not.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report. The local database from https://github.com/dbeaver/dbeaver/issues/9371 can be used to test.
![G2d2pFpda9](https://user-images.githubusercontent.com/51405061/88795618-ff877600-d1a8-11ea-8744-ac97b9e423b1.png)
Error: "Couldn't generate alter script
Reason:
class org.jkiss.dbeaver.ext.mysql.model.MySQLTableUniqueKey cannot be cast to class org.jkiss.dbeaver.ext.mysql.model.MySQLTableCheckConstraint (org.jkiss.dbeaver.ext.mysql.model.MySQLTableUniqueKey and org.jkiss.dbeaver.ext.mysql.model.MySQLTableCheckConstraint are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @71fe3e0)"
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4994602/dbeaver-debug.log)

**Comment by kseniiaguzeeva** [comment]
A little investigation was needed. If you copy/paste a table without a constraint, it will be successfull

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
Fixed in 7.1.4
