### ISSUE TITLE
Apache Drill Connection: 'Channel closed'

### ISSUE THREAD

**Issue by celarno** [dbeaver/dbeaver#9345]
#### System information: 
- MacOS Catalina
- DBeaver 7.1.3

#### Connection specification:
- Apache Drillbit is running on another machine
- Apache Drill driver: org.apache.drill.exec:drill-jdbc-all (v1.17.0)

#### Describe your question:

I can't connect to an Apache Drillbit since a while via SSH tunneling.
The port bindings are set as follows:

```
local host: localhost
local port: 31010

remote host: localhost
remote port: 31010
```

But DBeaver always uses another port on my local machine and show this error:
```
Failure in connecting to Drill: oadd.org.apache.drill.exec.rpc.ChannelClosedException: 
  Channel closed /127.0.0.1: 55188 <--> localhost/127.0.0.1:31010.
```

I've tried to use older drivers, but still nothing. It works though if I set up a SSH tunnel in the terminal and then connect in DBeaver without the tunnel option enabled.

What can I do?

**Comment by kseniiaguzeeva** [comment]
Please tell is it still actual for you?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
