### ISSUE TITLE
[postgresql] serial meta datatype not shown in table columns tab

### ISSUE THREAD

**Issue by michalk-k** [dbeaver/dbeaver#9352]
![obrazek](https://user-images.githubusercontent.com/7868445/88267863-c5faca80-ccd1-11ea-9acf-288de3c33983.png)

The first column is bigserial not bigint (int8).

Some might argue that it's correct but THERE IS a SIGNIFICANT difference between BIGINT with DEFAULT set to nextval() and SERIAL.
The difference is in relationship between sequence object and particular column. This relationship is set by ALTER SEQUENCE OWNED BY command (see https://www.postgresql.org/docs/10/sql-altersequence.html). Thanx to this relationship the sequence is dropped together with the table if DROP TABLE CASCADE is issued (also table which column is owned by sequence cannot be dropped without CASCADE).

Long story short this is remarkable information and should be presented.

Here is a query how to retrieve information about existing relationship. Watch out the condition  **d.classid = 1259**. It's mandatory!
Without that it might works sometimes, usually in new  databases. It's by coincidence. It breaks apart when database is restored from backups.

```
SELECT attrs.attname AS column_owned_by_sequence
FROM pg_depend d 
JOIN pg_class AS seqs ON seqs.relkind = 'S' AND seqs.oid = d.objid
JOIN pg_class AS tbls ON tbls.relkind = 'r' AND tbls.oid = d.refobjid
JOIN pg_attribute AS attrs ON attrs.attrelid = d.refobjid AND attrs.attnum = d.refobjsubid
WHERE d.deptype = 'a'
  AND d.classid = 1259
  AND seqs.oid::regclass::VARCHAR = 'clients.tab_client_history_id_client_history_seq'
  AND tbls.oid::regclass::VARCHAR = 'clients.tab_client_history'
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by LonwoLonwo** [comment]
Display of the serial data type in the table properties has been changed. Fixed in 7.2.3

**Comment by kseniiaguzeeva** [comment]
Serial and bigserial types are displayed correctly now. But smallserial is shown as int2 in Metadatavpanel and as smallint in Backup file.

**Comment by LonwoLonwo** [comment]
> 
> 
> Serial and bigserial types are displayed correctly now. But smallserial is shown:
> 
>     * as int2 in Metadata panel
> 
>     * as smallint in Backup file.
>       ![notepad_TPFdl8QmZn](https://user-images.githubusercontent.com/51405061/95218039-88034200-07fc-11eb-8968-aa0d1297a124.png)
>       ![dbeaver_uWUUaiuZnx](https://user-images.githubusercontent.com/51405061/95218037-86d21500-07fc-11eb-9113-302e918a365a.png)
>       (e.g. you can see tables in postgres.Xeniia)

unfortunately, we cannot influence the display of data types in these places. they are taken directly from the database
