### ISSUE TITLE
Integrate project Explorer and Project navigator views with Team work

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#9353]
At least for Git.
We need to show changed files (with icons or colors) and add some context menu actions for easy shared resource management.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/88292715-aaf47e80-cd02-11ea-895f-aa23f7dad96b.png)

**Comment by uslss** [comment]
Icons and colors for changed items aren't shown in Projects Navigator view
![image](https://user-images.githubusercontent.com/31996417/88637010-4a7a8e00-d0c2-11ea-8ab1-7d0b5160f96d.png)

**Comment by serge-rider** [comment]
Decoration were added for Project Navigator view too

**Comment by uslss** [comment]
verified
