### ISSUE TITLE
Support for Redis

### ISSUE THREAD

**Issue by mcandre** [dbeaver/dbeaver#9356]
Please add support for managing Redis databases.

**Comment by serge-rider** [comment]
We already support Redis in Enterprise Edition.

We don't plan to move it to CE version in near future (as well as other NoSQL or non-JDBC based drivers).

**Comment by shayneoneill** [comment]
Well thats a show stopper. Is there any recomendations for tools that do support it in open source software?

**Comment by linxu** [comment]
@serge-rider CE version support Redis is urgently needed.
