### ISSUE TITLE
Postgres: Single row cursor does not display with shift-enter

### ISSUE THREAD

**Issue by tacloban** [dbeaver/dbeaver#9357]
#### System information: 
- Operating system (distribution) and version: windows 10
- DBeaver version: > 7.0.5
- Additional extensions: N/A

#### Connection specification:
- Database name and version: Postgres 11.6
- Driver name: Postgres 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
It seems in versions of DBeaver greater than 7.0.5 do not display refcursors if they only have a single row.
#### Steps to reproduce, if exist:
Demo function to show this:

CREATE OR REPLACE FUNCTION test_cur() RETURNS refcursor
AS $body$
DECLARE

  ret refcursor;

BEGIN

  open ret for (select 1 as c);

  return ret;
END;
$body$
LANGUAGE PLPGSQL;

select test_cur();

Do shift+enter in the UI, the result has no rows.

I tried this in an Oracle db , and it seems to work as expected:
SELECT cursor(SELECT 'abc' AS c FROM dual)
FROM dual;

Cursors with 2 or more rows are fine.

#### Include any warning/errors/backtraces from the logs
I do not see any errors in either the UI or in %APPDATA%\DBeaverData\workspace6\.metadata\.log or dbeaver-debug

**Comment by tacloban** [comment]
I also just checked on Arch Linux dbeaver version 7.1.2.202007122053, the same problem is there as well.

**Comment by uslss** [comment]
Hi @tacloban ,
unfortunately, cannot reproduce it against 7.1.3 with postgres 11.6. Probably some special steps are needed.Could you post what result do you get? 
![image](https://user-images.githubusercontent.com/31996417/88536703-f2398280-d014-11ea-9fe5-e708a101527f.png)

**Comment by tacloban** [comment]
The issue only presents itself one you attempt to look at the data contained in the cursor iteself. I usually do that with the shift+enter key combination. Here is the screen shot of what i see when displaying the cursor:

![image](https://user-images.githubusercontent.com/68619466/88568219-76780f80-cfed-11ea-8c2f-19a781d75012.png)

Look at the 'C' column.

It should look like this, as it did in DBeaver 7.0.5:

![image](https://user-images.githubusercontent.com/68619466/88568762-5137d100-cfee-11ea-9441-3d9f2476a4ee.png)

where the 'C' column has the value of 1.

**Comment by uslss** [comment]
Thanks for the clarification and bug report :)

**Comment by serge-rider** [comment]
Fixed.
We had a wrong cursor scroll operator (it was MOE FIRST instead of MOVE ABSOLUTE 0)

**Comment by uslss** [comment]
verified

**Comment by tacloban** [comment]
Thank you so much for fixing this, I look forward to upgrading when its out.
