### ISSUE TITLE
SQL Error [137] [S0001]: Must declare the scalar variable ""

### ISSUE THREAD

**Issue by erlep** [dbeaver/dbeaver#9360]
Two variable are not working in T-SQL.  
Example:
DECLARE @FullName VarChar(25)
DECLARE @od int = 2;  -- od znaku
DECLARE @po int = 1;  -- pocet
SET @FullName = 'George Washington'
SELECT SUBSTRING(@FullName, @od, 6)
GO

**Comment by uslss** [comment]
Hi @erlep ,
cannot reproduce it. What database do you use?
![image](https://user-images.githubusercontent.com/31996417/88537070-89063f00-d015-11ea-9efb-c8f459070b3c.png)

**Comment by erlep** [comment]
I use MS SQL 2017

**Comment by uslss** [comment]
thanks for the bug report.
as a workaround you could select needed script (part of script) and execute it using Ctrl+Enter

**Comment by serge-rider** [comment]
Remove of ; delimiters after DECLARE also works.

@erlep You need to use either ; or GO as a delimiter.
If you use both then DBeaver will execute TSQL statements one by one and you can't use variables declared in previous statements.

Unfortunately we can't fix change this behavior as SQL Server JDBC driver doesn't support script mode.
