### ISSUE TITLE
Disable an ability to create view for CSV connection

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9361]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.3

#### Connection specification:
- Database name and version CSV

#### Describe the problem you're observing:
We need to disable views and its creation for CSV connection

**Comment by serge-rider** [comment]
Fixed.
Also indexes, unique keys and foreign keys were disabled for CSV and DBF drivers.

**Comment by uslss** [comment]
verified
