### ISSUE TITLE
There is no Delete database option on Sql Server

### ISSUE THREAD

**Issue by majkinetor** [dbeaver/dbeaver#9362]
I have this button for postgres but not for Sql Server:

## Sql Server

![image](https://user-images.githubusercontent.com/85767/88387817-97edb700-cdb3-11ea-956a-1d6b83d52481.png)

## Postgresql

![image](https://user-images.githubusercontent.com/85767/88387867-b358c200-cdb3-11ea-9e73-83c84771b0f2.png)

**Comment by uslss** [comment]
Seems this is not implemented yet. Marked as a feature request.
Thanks for suggestion

**Comment by kseniiaguzeeva** [comment]
implemented

**Comment by majkinetor** [comment]
Sql Server has this 'drop all active connections' to check before deleting. I always thought its not needed, does dBeaver implementation impose it internally ? If not, it should IMO.
