### ISSUE TITLE
1-click Update

### ISSUE THREAD

**Issue by allan-shoup** [dbeaver/dbeaver#9363]
Whenever there is a new version of DBeaver the user needs to go through a bunch of clicks to install the new version. The most prevalent use case is to do an in-place upgrade to the latest version. If that can be done in a single click, that would streamline the upgrade process.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion

**Comment by kseniiaguzeeva** [comment]
We already have such ticket. Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/1590
