### ISSUE TITLE
Oracle View UNDEFINED type

### ISSUE THREAD

**Issue by SA357** [dbeaver/dbeaver#9364]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
7.13
- Additional extensions 
none

#### Connection specification:
- Database name and version 
Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
SSH

#### Describe the problem you're observing:
Type of column is UNDEFINED. Also this view is editable.

![image](https://user-images.githubusercontent.com/61096732/88405599-2c6a1080-cdd8-11ea-87ef-971bde359e6f.png)

#### Steps to reproduce, if exist:
Open SQL Editor and create view to table from another schema.

**Comment by LonwoLonwo** [comment]
Hello, @SA357 
Please tell me the script for creating the view that was used. 
I can't reproduce it yet.

**Comment by SA357** [comment]
Sorry, but I don't have an exact script. But if I remember correctly, it was pretty simple, I just created a table view from a different schema. Maybe this has already been fixed?

**Comment by LonwoLonwo** [comment]
Perhaps it was the type of the column. But I couldn't find that special column type.
If the problem occurs again, we will reopen the ticket.
Thanks for the help!
