### ISSUE TITLE
Add connection host name and statistics toggle in navigator context menu

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#9367]
To simplify connection host name and table statistics enable/disable we could add these toggles in Connection View context menu.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/88456444-77426180-ce86-11ea-9ee3-edbdfaf00ebe.png)

**Comment by kseniiaguzeeva** [comment]
Closed
