### ISSUE TITLE
App exits on PostgreSQL Geometry field select

### ISSUE THREAD

**Issue by thewwwizard** [dbeaver/dbeaver#9368]
#### System information: 
- Ubuntu 20.04 LTS
- DBeaver Version 7.1.3.202007192031

#### Connection specification:
- PostgreSQL 12.2 (Ubuntu 12.2-4) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-8ubuntu1) 9.3.0, 64-bit
- PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - No 

#### Describe the problem you're observing:
Application exists in 1 sec after I click on a geometry type field value cell. 

#### Steps to reproduce, if exist:
1. Open DB Table through Navigator -> Right Click -> View Data. Table needs to have a geometry field AND in my case PostGIS extension is enabled. 
2. Click on that geometry field value if you already have a record OR click Add New Row button and then click on that field.  

#### Include any warning/errors/backtraces from the logs
eclipse.buildId=unknown
java.version=1.8.0_252
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.eclipse.core.resources
Warning
Sun Jul 26 17:09:00 EEST 2020
The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

**Comment by hsseo0501** [comment]
Can you give me the DDL & some sample data?

I try to this in my environment, DBeaver was not exited and processed well.

**Comment by thewwwizard** [comment]
> Can you give me the DDL & some sample data?
> 
> I tried to this in my environment, DBeaver was not exited and processed well.

Sorry, it looks like I've made a mistake - the field is "geography" type but not "geomerty"

CREATE TABLE public.tasks (
	id bigserial NOT NULL,
	user_id int8 NOT NULL,
	name varchar(150) NOT NULL,
	description text NULL,
	geo_point geography NULL,
	is_active bool NOT NULL DEFAULT true,
	status_id int8 NOT NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	CONSTRAINT routes_pkey PRIMARY KEY (id)
);

**Comment by hsseo0501** [comment]
@thewwwizard Can you give me a query example for some records.

**Comment by thewwwizard** [comment]
@hsseo0501 I'm able to reproduce it even with no data, when I click on add new row and then select geography field to add value.

Here is an example record:
INSERT INTO public.tasks (user_id,"name",description,geo_point,is_active,status_id,created_at,updated_at) VALUES 
(1,'Task 1','Description 1','POINT (-71.060316 48.432044)',true,1,NOW(),NOW());

**Comment by kseniiaguzeeva** [comment]
Most probably the issue happens due to a browser integration. Could you please find and send log file: hs_err_pidXXXX.log  ?

**Comment by thewwwizard** [comment]
> Most probably the issue happens due to a browser integration. Could you please find and send log file: hs_err_pidXXXX.log ?

Hi @kseniiaguzeeva . Wondering how quickly you reply guys! Bravo!
Simulated that error again and attaching last log file here. 
[hs_err_pid624074.log](https://github.com/dbeaver/dbeaver/files/5008163/hs_err_pid624074.log)
..

**Comment by uslss** [comment]
not reproducible in 21.3.1
