### ISSUE TITLE
Enhance progress monitoring accuracy

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#9369]
Some complex tasks (e.g. data transfer) produce hierarchy of progress tasks (series of nested beginTask/subTask/done).
We need to track this progress hierarchically (restore previous states after `done`).
Otherwise we loose progress info in many cases. Moreover it may disable possibility to cancel active job.

**Comment by serge-rider** [comment]
Can be tested in data transfer tasks

**Comment by kseniiaguzeeva** [comment]
Data trasfer progress bar displays information correctly, but Background Tasks bar - no (no operations to display at this time.)

**Comment by serge-rider** [comment]
It is ok.
I think this ticket is more for devs.
