### ISSUE TITLE
Initaliazation: default schema list isn't refreshed when default database has been changed

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9370]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.3

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
Initaliazation: default schema list isn't refreshed when default database has been changed.
#### Steps to reproduce, if exist:
1. Open Connection settings>Initialization for PostgreSQL
2. Change Default database
3. Click arrow to select Default Schema.

Expected: schemas for the changed database are displayed

Actual result:
Schema list is not refreshed and displays schemas for previous database.
![DUiu8Tdp6h](https://user-images.githubusercontent.com/51405061/88508163-c2738600-cfe6-11ea-8551-578c3efe1b9d.png)

**Comment by akilovich** [comment]
Default schema updates when 'Test Connection' button is clicked. There is an info message below the 'Connection' group where you can find out about this behavior.
