### ISSUE TITLE
ddl for the database roles

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#9372]
DBeaver 7.1.3

it would be very convenient to be able to see the role creation script

![изображение](https://user-images.githubusercontent.com/61137576/88515017-733c4e00-d004-11ea-8210-be27181158e9.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by detkliff** [comment]
DBeaver 7.2.3  problem not resolved

**Comment by kseniiaguzeeva** [comment]
Will try to implement the feature after 7.3 release.

**Comment by detkliff** [comment]
really hope. Nothing in 7.3.0 version

**Comment by LonwoLonwo** [comment]
![2020-12-27 01_27_03-DBeaver 7 3 1 - postgres](https://user-images.githubusercontent.com/45152336/103160197-ee3ba780-47e2-11eb-9c4b-5ec13ebc0958.png)

implemented in 7.3.2

**Comment by uslss** [comment]
verified
