### ISSUE TITLE
Unable to run Firebird SQL with DBeaver

### ISSUE THREAD

**Issue by cnc13** [dbeaver/dbeaver#9373]
#### System information: 
- Operating system (distribution) and version 
Windows 10 Pro Build1909
- DBeaver version 
7.1.3

#### Connection specification:
- Database name and version 
Firebird SQL v 3.0.5

#### Describe your question:
I want to connect my database with DBeaver, but every time i get the following Error message. I has looked up the DBeaver Documentation, but that didn't help me out. Maybe some  of you guys could help me out with this problem?

![firebirdsqlError](https://user-images.githubusercontent.com/68848485/88528233-a1b72a80-cffe-11ea-9f82-adf35a83ffe3.PNG)

**Comment by kseniiaguzeeva** [comment]
Please tell the type of connection to the database you use.

**Comment by cnc13** [comment]
I use the following settings, just the standard settings of DBeaver. No special parameters and other connection settings. I have installed Firebird SQL as a service and it seems to be running.

![firebirdsqlSETTINGS](https://user-images.githubusercontent.com/68848485/88530017-0ffcec80-d001-11ea-860d-9aaf4226946e.PNG)

**Comment by kseniiaguzeeva** [comment]
Please send me screenshot of Main tab of connection settings (and also SSH/Proxy tabs if smth is filled there).

**Comment by cnc13** [comment]
![firebirdsqlMainSETTINGS](https://user-images.githubusercontent.com/68848485/88536472-2b212980-d00c-11ea-9cef-1c434f642235.PNG)


The ssh/proxy tabs are not filled or used.

**Comment by cnc13** [comment]
Some interesting fact! I tried to create and connect to a database with Firebird 2.5 and it worked. I don't know why version 3.0 does not working for me.

**Comment by AndreiTS** [comment]
> Some interesting fact! I tried to create and connect to a database with Firebird 2.5 and it worked. I don't know why version 3.0 does not working for me.

Check if firebird 3.0 is running and if you are using the right port

**Comment by AndreiTS** [comment]
I'm not having any issues with firebird 3.0

**Comment by kseniiaguzeeva** [comment]
@cnc13 Have you tried the advice above?

**Comment by uslss** [comment]
there is no update on issue for a long time. 
if issue is still actual for you - feel free to reopen it
