### ISSUE TITLE
when  select  from  a  as400 table  when the  data  is  "0001-01-01" throw  an  exception
sql  error 181 01534: sql0181 value in  date time  or  timestamp  string  not  valid

### ISSUE THREAD

**Issue by baizhi1989** [dbeaver/dbeaver#9381]

**Comment by kseniiaguzeeva** [comment]
The reason can be similar with https://github.com/dbeaver/dbeaver/issues/9378

**Comment by serge-rider** [comment]
I'm afraid we can't fix this from dbeaver side. It is a jt400 driver exception.

Please see https://stackoverflow.com/questions/13447252/as400-database-access-via-jdbc
Perhaps adding connection properties `;date format=iso;time format=iso;` will solve the problem.

**Comment by stephecannon** [comment]
> I'm afraid we can't fix this from dbeaver side. It is a jt400 driver exception.
> 
> Please see https://stackoverflow.com/questions/13447252/as400-database-access-via-jdbc Perhaps adding connection properties `;date format=iso;time format=iso;` will solve the problem.

This resolved my issues. Thanks @serge-rider.
