### ISSUE TITLE
CUBRID connection URL sample is not created properly

### ISSUE THREAD

**Issue by hiclass** [dbeaver/dbeaver#9382]
#### System information: 
- Windows 10
- DBeaver Community Edition 7.1.3.202007192031

#### Connection specification:
- CUBRID 10.2

#### Describe your question:
URL Template: jdbc:CUBRID:{host}:{port}:{server}:{database}::
is not properly written, it should change to
URL Template: **jdbc:CUBRID:{host}:{port}:{database}:::**

on following connection URL manual of cubrid([https://www.cubrid.org/manual/en/10.2/api/jdbc.html#configuration-connection](https://www.cubrid.org/manual/en/10.2/api/jdbc.html#configuration-connection))
it dosen't have &gt;server&lt; property.

source position: plugins/org.jkiss.dbeaver.ext.generic/plugin.xml

**Comment by kseniiaguzeeva** [comment]
Thank you for the report

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
