### ISSUE TITLE
Driver download fails if DBeaver is executed behind proxy

### ISSUE THREAD

**Issue by akasolace** [dbeaver/dbeaver#9383]
#### System information: 
- Windows Professional 64bits
- DBeaver version:  DBeaver community 7.1.3.202007192031
- Additional extensions: None

#### Describe the problem you're observing:

I am using DBeaver behind proxy. I configuresd my proxy information but still I can't download drivers via the app, I am forced to donwload the driver manually. It has been the case for all recent version of Dbeaver I have used, I have finally decided to report it.

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/1136496/88625579-56a62180-d0a9-11ea-92b4-f6595af56f76.png)

![image](https://user-images.githubusercontent.com/1136496/88625676-82c1a280-d0a9-11ea-9d78-a281144359c6.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. To reproduce:
1. set Proxy in Window>Preferences>Drivers
2. download a driver

**Comment by sworisbreathing** [comment]
@kseniiaguzeeva it's confusing to have 2 separate places to configure your proxies ("Preferences -> General -> Network Connections" being the other one). Can't we just have one place to configure the proxy?

**Comment by kseniiaguzeeva** [comment]
Proxy in Window>Preferences>Drivers is used for driver download only. This is a difference
