### ISSUE TITLE
Database Navigator - add inline action buttons

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#9384]
Needed for easier access to connection configuration and for better connection status visualization.

Actions/icons we need:
- Connection configuration cog
- Tunnel/proxy enablement
- Read-only flag
- Smth else ?

**Comment by serge-rider** [comment]
First version is ready.
No we show datasource status on the right side of database navigator + show tooltips for the status (readonly connection, ssh tunnel, proxy).
Also we show tooltips for object statistics.

In the next version we will add active buttons to configure/control connection behavior.

**Comment by kseniiaguzeeva** [comment]
Is it ok, when:
1. Object statistics tooltips and host tooltips (for PROXY, local) are not displayed if they are disabled in Connection view
![2](https://user-images.githubusercontent.com/51405061/88904644-00c6aa80-d25e-11ea-9f26-2b3cb7e358b4.png)
2. PROXY is not displayed in tooltip if it goes together with SSL or SSH?
![4](https://user-images.githubusercontent.com/51405061/88905081-9104ef80-d25e-11ea-8969-4a9841af3c7f.png)
3. Object statistics in tooltip can differ from the statistics displayed in Properties (see printscreen)
![5](https://user-images.githubusercontent.com/51405061/88905116-9c581b00-d25e-11ea-84c6-b40bd2663eff.png)
4. Pgpass is not displayed as tooltip?

**Comment by serge-rider** [comment]
Yes, it is correct. We didn't change behavior for connection status, we changed UI only.

We will add status for authentication models in future versions.

**Comment by kseniiaguzeeva** [comment]
Ok, implemented
