### ISSUE TITLE
Cannot install Darkest Dark

### ISSUE THREAD

**Issue by jat255** [dbeaver/dbeaver#9386]
#### System information: 
- Operating system: Arch Linux
- DBeaver version: Version 7.1.3.202007261633
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1)
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Cannot install Darkest Dark theme through "Install New Software" menu

#### Steps to reproduce, if exist:
- Enter `http://www.genuitec.com/updates/devstyle/ci/` into "Work with" field in install new software menu
- Select just "DevStyle (includes Darkest Dark Theme)" (or all of them, doesn't matter)
- Click Next

#### Include any warning/errors/backtraces from the logs
Installation fails with the following error:
```
Cannot complete the install because one or more required items could not be found.
  Software currently installed: DBeaver 7.1.2 (org.jkiss.dbeaver.core.product 7.1.2)
  Missing requirement: DBeaver 7.1.2 (org.jkiss.dbeaver.core.product 7.1.2) requires 'org.eclipse.equinox.p2.iu; toolingorg.jkiss.dbeaver.core.product.configuration [7.1.2,7.1.2]' but it could not be found
```

**Comment by kseniiaguzeeva** [comment]
You use DBeaver 7.1.3, but it is written DBeaver 7.1.2 in error message.
Please try to delete DBeaver and then install again.

**Comment by chauhan-pawan** [comment]
I tried by uninstalling and reinstalling but still issue persisit. I am on 7.1.4. no eclipse, standalone dbeaver
![Capture1](https://user-images.githubusercontent.com/69239365/90116494-32b63180-dd73-11ea-812e-e661d82a4b0e.JPG)

**Comment by kseniiaguzeeva** [comment]
It seems that the reason is the same with #9458. Could you please try Darkest Dark in 7.1.5 too?

**Comment by chauhan-pawan** [comment]
I tried with latest version but no success.

**Comment by uslss** [comment]
@chauhan-pawan how do you install dbeaver?

**Comment by chauhan-pawan** [comment]
Using latest windows installer. Installed in user profile since i don't have elevated access on my system.

**Comment by chauhan-pawan** [comment]
I am not sure but when we try to install this add on it try to connect some xml file from "https://dbeaver.io/update/" but all xml file at the location ending with xz, which system doesn't expecting.

**Comment by wade-cole** [comment]
Hello, I am using DBeaver Version 7.2.1.202009201907 on Windows 10 Enterprise version 1909. I also encounter a similar issue when trying to install any theme, including Darkest Dark. When I drag and drop the URL, I get the error in the attached screenshot. Please let me know if I should submit additional information:
![image](https://user-images.githubusercontent.com/63322088/93824367-306bb080-fc18-11ea-8654-59065ab08541.png)

**Comment by serge-rider** [comment]
It looks like a local problems with Eclipse.org connectivity.
Still can't reproduce..

**Comment by kseniiaguzeeva** [comment]
Could you please try the latest version https://dbeaver.io/download/? Is the issue still actual for you?

**Comment by uslss** [comment]
There is no update on an issue for a long time.
If it is still actual for you - feel free to reopen an issue.
