### ISSUE TITLE
Incorrect presentation of Oracle date 2020-12-27 when using DBeaver format d/MM/YYYY

### ISSUE THREAD

**Issue by mark2016** [dbeaver/dbeaver#9390]
#### System information: 
- Operating system (distribution) and version: Windows 7 Pro 64 bit
- DBeaver version 7.1.3
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle 11g
- Driver name: Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing: 
select to_date('2020-12-27','YYYY-MM-DD') from dual; when executed with native timestamp formatting turned off is displayed as 27/12/2021, ie has the wrong year.

#### Steps to reproduce, if exist:
1) Execute query select to_date('2020-12-27','YYYY-MM-DD') from dual; with native date/time format ticked, observe result date is correct (in my case this is displayed as 2020-12-27 00:00:00 but it depends on your local NLS setup)
![image](https://user-images.githubusercontent.com/16224288/88758511-f51aab80-d1ab-11ea-8f6c-59b23bacd3c2.png)
Observe is correct date:
![image](https://user-images.githubusercontent.com/16224288/88763562-b0484200-d1b6-11ea-8450-216656a2aa14.png)

2) Change DBeaver timestamp format to d/MM/YYYY: (note that although we are formatting a DATE, it has to be entered in the TIMESTAMP format section due to bug #8673 )
![image](https://user-images.githubusercontent.com/16224288/88763038-c275b080-d1b5-11ea-9209-fc9d119e3f16.png)
Execute same query, observe date is incorrect (has wrong year):
![image](https://user-images.githubusercontent.com/16224288/88763518-9c9cdb80-d1b6-11ea-97c5-9e9169187643.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. I've added 1 more step to reproduce:
1. "Execute query select to_date('2020-12-27','YYYY-MM-DD') from dual; with native date/time format ticked, observe result date is correct (in my case this is displayed as 2020-12-27 00:00:00 but it depends on your local NLS setup)"
2. "Change DBeaver timestamp format to d/MM/YYYY: (note that although we are formatting a DATE, it has to be entered in the TIMESTAMP format section due to bug #8673 )"
3. Disable **use native date/time format** function
4. Execute same query and see the date in ResultSet

Actual result: the date is incorrect (has wrong year):

**Comment by LonwoLonwo** [comment]
@mark2016   So. In DBeaver in Data Formats settings we use Java date patterns, where the pattern case of letters is also important.
https://stackoverflow.com/a/32847390/14220989

Use "yyyy" in pattern instead "YYYY'.

**Comment by mark2016** [comment]
Ah fantastic didn't realise DBeaver used the Java date format patterns to format dates.  Is this in the DBeaver documentation, I can't find this fact that it uses Java date format patterns mentioned anywhere. eg https://github.com/dbeaver/dbeaver/wiki/Managing-Data-Formats makes no mention of what date format pattern to use.  I assume you mean Java Simple Date format patterns?  In which case, what is a good reference for these please (Sorry but I am totally unfamiliar with Java!)

**Comment by LonwoLonwo** [comment]
@mark2016 Well noted, we will add this to DBeaver documentation.
