### ISSUE TITLE
Force Truncate Table

### ISSUE THREAD

**Issue by brentlobbezoo** [dbeaver/dbeaver#9396]
**Problem**
I'm always frustrated when "Truncate table" doesn't truncate my table when there are constraints.

**Preferred solution**
I'd like to have a "Force truncate table" option, which automatically disables `foreign_key_checks` before executing.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by kseniiaguzeeva** [comment]
The function succesfully works in MySQL, MariaDB. But is it possible to fix Truncate tool Window blinking, when open it? See gif
![ckUvkNYmoU](https://user-images.githubusercontent.com/51405061/89184039-d4ce6080-d5a0-11ea-8ea8-bf62624fc85e.gif)

**Comment by serge-rider** [comment]
Blinking has nothing to do with Truncate (it is "Settings loading" popup which appears for very short period of time, I believe we have a ticket about it).

But I don't like wizard final page. It is empty (no any task status). This is frustrating and looks like a broken UI.

**Comment by LonwoLonwo** [comment]
broken UI fixed

**Comment by kseniiaguzeeva** [comment]
verified
