### ISSUE TITLE
New Postgres connection host section hidden

### ISSUE THREAD

**Issue by suBOTai3** [dbeaver/dbeaver#9397]
Hi.  

 To repro:

* Click new connection button
* Type Postgres as the type
* Double click
* Cannot fill in the hostname - its missing the textbox (see screenshot)
![hostmissing](https://user-images.githubusercontent.com/5020751/88810711-01a40180-d1b6-11ea-9422-dcfce9f1a32d.png)

Resizing the window does not show the missing textbox

**Comment by uslss** [comment]
Hi @suBOTai3 , could you reset UI settings (Main menu: File - Reset UI settings)?

**Comment by suBOTai3** [comment]
Hi @uslss 

Thanks for the feedback

I've reset the settings but still the same result. What is interesting now is that the window now covers the whole of the 2 monitors that I have, and I have to resize it down to a normal size

If I look at the right hand border of the controls it seems as if there is some misalignment because the borders are cut off

![stillmissing](https://user-images.githubusercontent.com/5020751/89003768-e85b9c00-d300-11ea-9f1c-c12e0285f9fb.png)

**Comment by uslss** [comment]
@suBOTai3 thanks for the response. 
What OS do you use?

**Comment by suBOTai3** [comment]
I'm on Win 10 Pro 64 bit 
Version 2004, Build 20161.1000

**Comment by uslss** [comment]
looks really weird. Does it appear at both monitors? Probably some special scale/screen definition is used?

**Comment by suBOTai3** [comment]
It does. This is my screen setup (1920x1080):

I have 3 monitors (1 laptop screen + 2 monitors)

![Disp](https://user-images.githubusercontent.com/5020751/89981005-585c1180-dc73-11ea-9bf1-dc0ee5dd0d85.png)

Initially when the new postgres connection screen loads, it is stretched (not maximized) over the 2 connected monitors, after which I normally have to resize it to the main monitor or click the 'maximize' button to see it on 1 screen.

At this point the hostname is not visible for editing.

I suspect the controls are not resizing properly (as you can see the postgres logo is also partially hidden) and are pinned to the right and left borders of the window.
 
Upon initial load of the form, the control sizes are initialized outside the border of the window, and then resize consistently when the window resizes by following the width of the window. 

Of course the problem is that (because the initial size is incorrect) they resize consistently incorrrectly.

**Comment by uslss** [comment]
cannot reproduce it against 7.3.1.
If the issue is still actual for you- feel free to reopen it.

**Comment by suBOTai3** [comment]
This was also fixed for me in the last update where Java came bundled. Perhaps there was a filie path mapping problem with java internally. But since the last update it works
