### ISSUE TITLE
Where to look for the detailed info of the numbers in a column in DBeaver

### ISSUE THREAD

**Issue by GoldenSun666** [dbeaver/dbeaver#9399]
#### System information: 
- Operating system (distribution) and version
- DBeaver version

#### Connection specification:
- Database name and version

**Comment by GoldenSun666** [comment]
Anyone can help, please?

**Comment by GoldenSun666** [comment]
What is completion_obs_no column? Where can i find the detailed info for it? It just has different numbers.

**Comment by uslss** [comment]
Hi @GoldenSun666 ,
what database do you use? Could you clarify what numbers are you talking about?

**Comment by GoldenSun666** [comment]
@uslss Hi usless, thanks for your reply. I can't upload the screenshot since it keeps telling me something went really wrong. Any solution?

**Comment by GoldenSun666** [comment]
It is weird that it doesnt allow me to upload the image...tried many times...

**Comment by GoldenSun666** [comment]
![picture 1](https://user-images.githubusercontent.com/68965707/89237793-5928df80-d5b1-11ea-8804-f1c43fcd2c5d.jpg)

finally...

**Comment by GoldenSun666** [comment]
Resolved the issue
