### ISSUE TITLE
Oracle: table info read performance improvements

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#9400]
In some Oracle databases table read takes too much time.
One of the reasons - reading from ALL_MVIEWS system view.

We don't need to query it + we can improve base table read query by replacing it with select from ALL_OBJECTS + filter by type.

**Comment by serge-rider** [comment]
Please check that metadata read isn't broken (tables, views, mviews, ERD, etc).

**Comment by kseniiaguzeeva** [comment]
12.2 Oracle was tested. Is it ok that java object does not have data in Declaration tab?
![dbeaver_SV7fDTZjvD](https://user-images.githubusercontent.com/51405061/88911363-69198a00-d266-11ea-91b3-f7f28ec9d629.png)

**Comment by serge-rider** [comment]
It is ok, our test db doesn't have many Java sources

**Comment by kseniiaguzeeva** [comment]
Other items are correct.
