### ISSUE TITLE
Proxy settings not taking effect on application start-up

### ISSUE THREAD

**Issue by sworisbreathing** [dbeaver/dbeaver#9402]
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise, Build 1809
- DBeaver version 7.1.0
- Additional extensions

#### Connection specification:
- Database name and version Redshift
- Driver name Redshift
- Do you use tunnels or proxies (SSH, SOCKS, etc)? yes, HTTP/HTTPS

#### Describe the problem you're observing:
We use the Redshift JDBC driver to do passwordless logon to Redshift (via the `jdbc:redshift:iam://{host}:{port}/{database}` URL pattern), and are behind a corporate web proxy. With this setup, when you open a JDBC connection the driver makes a call to [GetClusterCredentials API](https://docs.aws.amazon.com/redshift/latest/APIReference/API_GetClusterCredentials.html) under the hood.

Since upgrading to 7.1.0 I've noticed that the `GetClusterCredentials` call fails due to not going through the proxy. The error reported is:
```
[Amazon](500356) Error retrieving IAM credentials. "Unable to execute HTTP request: Software caused connection abort: recv failed".
```

 In order to get it working I have to open up the proxy settings (Preferences -> General -> Network Connections). I don't have to actually _change_ anything, I just have to open the settings window, and then the API calls start working.

#### Steps to reproduce, if exist:

1. Set up DBeaver to work behind an HTTP proxy using manual proxy configuration
1. Set up the redshift jdbc driver to point to redshift using the `jdbc:redshift:iam://{host}:{port}/{database}` URL pattern
1. Create a redshift connection
1. Close dbeaver and relaunch
1. Try to connect to the database. You should get an error:
```
[Amazon](500356) Error retrieving IAM credentials. "Unable to execute HTTP request: Software caused connection abort: recv failed".
```
1. Open the network connections preferences: Preferences -> General -> Network Connections
1. Observe the logs to see a bunch of messages about `System property http.proxyHost is not set but should be...` that print out when you open the dialog
1. Click Cancel
1. Try to connect to the database again. It should work this time.

#### Include any warning/errors/backtraces from the logs
From the logs I'm seeing a bunch of messages like:
```
System property http.proxyHost is not set but should be...
System property http.proxyPort is not set but should be...
```

These messages don't appear until I open the network connection preferences. This suggests the proxy settings aren't being loaded until I open that settings window.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Do you use DBeaver CE? Could you please try to connect via DBeaver EE (trial is available https://dbeaver.com/trial/). It can help us to find a reason.

**Comment by richardrawstronMOH** [comment]
I can reproduce this issue using DBeaver CE 7.1.4
I can not reproduce this issue using DBeaver EE 7.1.0

Let me know what I can do to assist while I still have a 2 week EE trial license.

System information:
    Operating system (distribution) and version: Windows Server 2016
    DBeaver version: as above
    Additional extensions: None

Connection specification:
    Database name and version: Snowflake
    Driver name: Snowflake JDBC 3.12.9
    Do you use tunnels or proxies (SSH, SOCKS, etc)? yes, HTTP/HTTPS

**Comment by serge-rider** [comment]
It is not database-specific. Global proxy settings aren't by some reason.

**Comment by serge-rider** [comment]
@sworisbreathing @richardrawstronMOH How do you configure proxy? Globally (in preferences->network) or in the particular database connection? 
Do you enable Proxy in connection settings?

**Comment by sworisbreathing** [comment]
@serge-rider I have mine in global settings (preferences->network)

**Comment by richardrawstronMOH** [comment]
CE does not provide any HTTP/HTTPS or Automatic proxy option (only SOCKS) in the Connection settings
Proxy is configured in Preferences > General > Network Connections:
- Active Provider = Manual
- HTTP = host + port
- HTTPS = host + port

EE provides Automatic proxy configuration and SOCKS options in the Connection settings.
As a different issue the connection times out testing Automatic proxy with:
- Proxy entered in browser settings Internet Options > Connections > LAN settings
- Use proxy = ticked
- Use automatic proxy detection = ticked
- Use browser proxy settings = ticked
- Preferences > General > Network Connections = Direct or Manual or Native
This appears to be different bug but I'm not sure I'm configuring this correctly.

**Comment by serge-rider** [comment]
Event if you use global proxy settings try to enable Proxy chechbox in particular connection settings:
![image](https://user-images.githubusercontent.com/6398845/97544972-63555100-19db-11eb-9b1d-59a328885098.png)

This will force proxy configuration activation.

**Comment by kseniiaguzeeva** [comment]
verified on EE version (proxy settings are saved in Network settings). Will be tested on CE also.

**Comment by sworisbreathing** [comment]
@kseniiaguzeeva - sorry for the late reply (I've been on leave from work so haven't had a chance to test).
Confirmed that ticking the box for "Use Proxy" on the DB connection itself (as shown in your screenshot) fixes the issue for me on DBeaver CE.

Thank you!

**Comment by kseniiaguzeeva** [comment]
Thank you very much for testing and response!
