### ISSUE TITLE
Commit is not allowed after modifying data in Grid.

### ISSUE THREAD

**Issue by tomkidd517** [dbeaver/dbeaver#9403]
#### Sysem information:  windows 10

- DBeaver version  : 7.1.3

#### Connection specification:
- Database name and version : 
        Microsoft SQL Server 2019 (RTM-GDR) (KB4517790) - 15.0.2070.41 (X64) 
	Oct 28 2019 19:56:59 
	Copyright (C) 2019 Microsoft Corporation
	Express Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 17134: )

#### Describe your question:
Commit is not allowed after modifying data in Grid.
If you modify the DATA in Grid, click Save, and click Commit, it should be saved. If you re-examine it, it will be saved.
It hasn't been modified.
![image](https://user-images.githubusercontent.com/51102284/88873710-3cf70c80-d258-11ea-81ef-8e0ba3267edb.png)

However, after using the update script, click Commit and re-review to modify the data.

![image](https://user-images.githubusercontent.com/51102284/88873086-d4f3f680-d256-11ea-9280-ce0ee15ef631.png)

**Comment by uslss** [comment]
Hi @tomkidd517 ,
do you use smart commit mode?

**Comment by tomkidd517** [comment]
I only use Manual commit mode.

**Comment by tomkidd517** [comment]
However, I still can't save the DATA entered in the grid even if I use the Manual commit mode and Smart commit mode at the same time.

**Comment by tomkidd517** [comment]
[2020-08-04_11-32-32.zip](https://github.com/dbeaver/dbeaver/files/5019763/2020-08-04_11-32-32.zip)
I am attaching a video recording of a situation that cannot be committed by executing the operation.

**Comment by uslss** [comment]
@tomkidd517 thanks for the video. Still cannot reproduce it.
New rows aren't visible even without where statement? Do you have Unique Key defined? 
Probably you could provide your table DDL?
thanks in advance!

**Comment by uslss** [comment]
btw, commit button becomes active in Manual and Smart Commit mode only after clicking at Save button at the bottom toolbar - it is expected behaviour

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Issue is closed. If it is still actual for you - feel free to reopen the ticket
