### ISSUE TITLE
Error when editing regconfig columns in PostgreSQL

### ISSUE THREAD

**Issue by alexhutsau** [dbeaver/dbeaver#9406]
#### System information: 
- Solus 4.1
- DBeaver 7.1.0

#### Connection specification:
- PostgreSQL 10.12
- PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Cannot create or add regconfig columns in table data view.

#### Steps to reproduce, if exist:
1. Create test table:
```sql
CREATE TABLE "test_table" ("id" integer NOT NULL, "config" regconfig NOT NULL, PRIMARY KEY ("id"));
```
2. Open data grid view for `test_table`
3. Create a new row
4. Enter some values and click save
5. An error dialog pops up with this error:
> Error synchronizing data with database
> 
> Reason:
> SQL Error [42804]: ERROR: column "config" is of type regconfig but expression is of type character varying
>   Hint: You will need to rewrite or cast the expression.
>   Position: 55

#### Some notes:
An auto-generated script looks good and can be successfully performed in SQL Editor:
```sql
-- Auto-generated SQL script #202007301156
INSERT INTO public.test_table (id,config)
	VALUES (1,'english'::regconfig);
```

**Comment by AlexHutsau** [comment]
It looks like a similar issue was in #8104 with enum columns.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by LonwoLonwo** [comment]
Error appears also with another [OID data types](https://postgrespro.com/docs/postgrespro/13/datatype-oid).

**Comment by LonwoLonwo** [comment]
Update/Insert values fixed for [OID data types](https://postgrespro.com/docs/postgrespro/13/datatype-oid) in DBeaver 21.1.1

**Comment by Matvey16** [comment]
Verified
