### ISSUE TITLE
[PostgreSQL] Syntax error with OFFSET FETCH NEXT statement

### ISSUE THREAD

**Issue by andywicht** [dbeaver/dbeaver#9410]
#### System information: 
- Win10 64bit
- DBeaver Version 7.1.3.202007192031

#### Connection specification:
- PostgreSQL 12.3 (Ubuntu 12.3-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
- PostgreSQL 42.2.14.jre7

#### Describe the problem you're observing:
The below mentioned statement throws a syntax error while working as expected using the psql cli.
```
SQL Error [42601]: ERROR: syntax error at or near "LIMIT"
  Position: 99
```

#### Steps to reproduce, if exist:

```sql
CREATE TABLE test (id serial PRIMARY KEY);

INSERT INTO test (SELECT * FROM generate_series(1,1000));

SELECT id
FROM test
ORDER BY id ASC
OFFSET 10
FETCH NEXT 10 ROWS ONLY;
```

This might be a bug in the underlying jdbc driver maybe? I am not able to pinpoint this issue. But somewhere it gets translated into a query which utilises `LIMIT`.

**Hint:** Prefixing the statement with `EXPLAIN` and/or `EXPLAIN ANALYZE` does not yield this error message.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it in DBeaver 7.1.4. Could you please try the latest release https://dbeaver.io/download/?

**Comment by uslss** [comment]
hi @andywicht ,
please, try to uncheck highlighted option in preferences
![image](https://user-images.githubusercontent.com/31996417/89900260-2b185080-dbec-11ea-8e0b-b76d06579b49.png)

**Comment by andywicht** [comment]
@uslss that works, thank you.
Do I have to deal with drawbacks once this option is disabled?

**Comment by serge-rider** [comment]
There are no drawbacks for PostgreSQL but it may be critical other databases (which do not support resultset size limit thru JDBC API).

**Comment by serge-rider** [comment]
Fixed (LIMIT/OFFSET clause won't be added to a query which already has it)

**Comment by uslss** [comment]
verified
