### ISSUE TITLE
Time data is placed on top of other cells data if the column is not wide enough

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9411]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.4 EA

#### Describe the problem you're observing:
Time data is placed on top of the data of other cells if the column is not wide enough
#### Steps to reproduce, if exist:
Open a table with numeric column type
Select a column choose a narrower column then Epoch time representation needs
Press View/Format>Epoch time

Actual result:
![dbeaver_2D0xhbb58O](https://user-images.githubusercontent.com/51405061/88932456-c6253800-d286-11ea-8297-17cd8911948b.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
