### ISSUE TITLE
How to connect to the database using mycat

### ISSUE THREAD

**Issue by TyouSF** [dbeaver/dbeaver#9415]
#### System information: 
- Operating system (distribution) and version: Mac
- DBeaver version: 7.1.3 by Community

#### Connection specification:
- Database name and version: MySQL by using myact

#### Describe your question:
Someone mentioned similar functional requirements before. The link:[Feature request:please support mycat #4198](https://github.com/dbeaver/dbeaver/issues/4198)

So, I think it is possible to connect to mycat. However, I don’t know how to connect to mycat using dbeaver.
In a word, I want to know the specific steps to connect to mycat.

**Comment by kseniiaguzeeva** [comment]
Please try to use MySQL driver.

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Issue is closed. If it is still actual for you - feel free to reopen the ticket
