### ISSUE TITLE
Data transfer: incorrect mapping tables status with quotes in name 

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#9418]
For tables with quotes mapping type is "create" instead "exist" in tables mapping dialog, which results in error copying tables
![2020-07-31 11_10_06-DBeaver Enterprise 7 2 0 - language](https://user-images.githubusercontent.com/45152336/89045648-87f64a00-d354-11ea-961a-b3b5bd6bad0d.png)

**Comment by kseniiaguzeeva** [comment]
verified
