### ISSUE TITLE
[Derby] Created view via UI becomes visiable only after reconnect 

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9424]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.4 EA

#### Connection specification:
- Database name and version Derby

#### Describe the problem you're observing:
Created view via UI becomes visiable after reconnect only

#### Steps to reproduce, if exist:
Create a view via UI

Expected: Source, Columns and Data Editor for the view are filled correctly

Actual result: 
1. Source and Columns tabs are empty
2. The view doesn't exist is written in Data Editor tab

Workaround:
Reconnect to the database or create a view in SQL Editor.

**Comment by serge-rider** [comment]
We don't support Derby view create via UI. How can I reproduce it?

**Comment by kseniiaguzeeva** [comment]
I select Create new view in a view context menu:
![dbeaver_JneIB6BrkG](https://user-images.githubusercontent.com/51405061/90864090-bf2aaa80-e398-11ea-9d6d-3ceda4ce6b5e.png)

In any case I cannot reproduce the issue anymore.
