### ISSUE TITLE
[Oracle] Columns tab is not displayed for materialized view

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9425]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.4 EA

#### Connection specification:
- Database name and version Oracle 12.2

#### Describe the problem you're observing:
Columns tab is not displayed for materialized view in Object Editor
#### Steps to reproduce, if exist:
Open Properties tab for a materialized view (e.g. SYS.NEWVIEW714)

Actual result: Columns tab does not exist
![dbeaver_DaTtybayWa](https://user-images.githubusercontent.com/51405061/89095002-5cb24000-d3d2-11ea-8af6-c243fab770bf.png)

**Comment by serge-rider** [comment]
Also folder "Constraints" was missing.
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
