### ISSUE TITLE
SSH tunnel cannot be used after VPN connection

### ISSUE THREAD

**Issue by duSupport** [dbeaver/dbeaver#9428]
#### System information: 
- Windows 10、Mac OS
- 7.1.3

#### Describe the problem you're observing:
Some of my databases need to be accessed through the office host. When I connect to the office network through VPN, I can't use SSH tunnel to connect to the office host, but I can connect directly through the SSH client

ERROR:
     Cannot establish tunnel
  timeout: socket is not established

**Comment by kseniiaguzeeva** [comment]
Please write SSH host in Main tab of connection settings and do not fill SSH tab. Does it help?
![dbeaver_77TqvUNLaB](https://user-images.githubusercontent.com/51405061/89170408-40580400-d588-11ea-8e2c-ec6e66d103e1.png)

**Comment by hexwanwan** [comment]
Hello, I had this problem and found a solution, use variables instead in SSH tab, `${host}`, `${user}`, `${password}`, not sure if this is a bug but it works for me.
