### ISSUE TITLE
Database Navigator descriptions 

### ISSUE THREAD

**Issue by hismayilov** [dbeaver/dbeaver#9430]
#### System information: 
- Operating system (distribution) and version : WIN 10
- DBeaver version : 7.1.3
- Additional extensions
![image](https://user-images.githubusercontent.com/676555/89161373-367bd400-d57b-11ea-802a-ed83ceef355c.png)

#### Connection specification:
- Database name and version : doesn't matter
- Driver name: any
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : nope

#### Describe the problem you're observing:
in Database Navigator view, description of nodes are  not readable because of color.
I use The Darkest Theme
![image](https://user-images.githubusercontent.com/676555/89160995-a50c6200-d57a-11ea-9435-060720aaf812.png)
when I do mouse over. 
![image](https://user-images.githubusercontent.com/676555/89161011-aa69ac80-d57a-11ea-9112-e3e06a4accea.png)

**Comment by kseniiaguzeeva** [comment]
My view is slightly different. Which theme do you use?

**Comment by hismayilov** [comment]
I use The [Darkest Dark Theme](https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle)
![image](https://user-images.githubusercontent.com/676555/89173635-400e3780-d58d-11ea-8381-9604780dba20.png)

**Comment by hismayilov** [comment]
after 7.1.4 solved. 

![image](https://user-images.githubusercontent.com/676555/89269585-be78e100-d642-11ea-8723-ffe47954e09d.png)

![image](https://user-images.githubusercontent.com/676555/89269486-9b4e3180-d642-11ea-88e8-977ead9284e1.png)

**Comment by kseniiaguzeeva** [comment]
Great
