### ISSUE TITLE
Tools: some tasks require refreshing after completion

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#9431]
Need to automatically update data after tool execution.

For tools:
- DB2:
- - truncate table
- SQLServer: 
- - disable/enable trigger
- MySQL: 
- - truncate table
- Oracle: 
-  - refresh Materializad view
- -  truncate table
- PostgeSQL: 
- - disable/enable trigger
- - truncate table

**Comment by kseniiaguzeeva** [comment]
A. Oracle: refresh materialized tool doesn't work, so refresh cannot be tested. 
Steps:
1. Select refresh materialized view tool for SYS.NEWVIEW
2. Press Start.

Expected: 
1. the tool is executed. 
2. the opened view is refreshed

Actual result:
1. Error appears "Task execution failed
Reason:
class org.jkiss.dbeaver.ext.oracle.model.OracleTable cannot be cast to class org.jkiss.dbeaver.ext.oracle.model.OracleMaterializedView (org.jkiss.dbeaver.ext.oracle.model.OracleTable and org.jkiss.dbeaver.ext.oracle.model.OracleMaterializedView are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @34339027)"
2. The execution fails

**Comment by kseniiaguzeeva** [comment]
verified
