### ISSUE TITLE
MySQL Time field data type displaying null

### ISSUE THREAD

**Issue by rodrigoguariento** [dbeaver/dbeaver#9435]
#### System information: 
- Operating system (distribution) and version **Ubuntu 18.04LTS**
- DBeaver version **7.1.3**
- Additional extensions **None**

#### Connection specification:
- Database name and version **MySQL 5.7 and MySQL 8.0**
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
According https://dev.mysql.com/doc/refman/8.0/en/time.html and https://dev.mysql.com/doc/refman/5.7/en/time.html the TIME values may range from '-838:59:59' to '838:59:59', and after insert or update some Time field with more than 23:59 DBeaver is displaying NULL on screen.

#### Steps to reproduce, if exist:
create table employee_rule (id integer primary key auto_increment, extra time null default null);
insert into employee_rule (extra) values ('10:00');
insert into employee_rule (extra) values ('20:00');
insert into employee_rule (extra) values ('30:00');
insert into employee_rule (extra) values ('40:00');
insert into employee_rule (extra) values ('50:00');
select * from employee_rule;

#### Include any warning/errors/backtraces from the logs
No warnings, no errors.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Can't reproduce, I see valid values.

![image](https://user-images.githubusercontent.com/6398845/90643239-08191c80-e23c-11ea-8fb1-1dc99424aaed.png)

BTW you could try to enable "Use native date/tiem format" for database-sepcific data types.
However it should even with this option disabled (and it works in my test env).
![image](https://user-images.githubusercontent.com/6398845/90643474-53332f80-e23c-11ea-814d-c386e2b6f8b3.png)

**Comment by kseniiaguzeeva** [comment]
I use 7.1.5.202008202100 and can reproduce it. I have enabled/disabled native date/time format.
![HUxyMitXfa](https://user-images.githubusercontent.com/51405061/90869257-a45c3400-e3a0-11ea-90ab-3e1974168932.gif)

**Comment by serge-rider** [comment]
It is a bug in old MySQL driver.
You should use driver for MySQL 8+. It also supports older version of MySQL servers.

We will rename drivers in the next version (so MySQL 8 will become the default).

**Comment by kseniiaguzeeva** [comment]
verified
