### ISSUE TITLE
Error connecting Oracle ADW - unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by luizmz94** [dbeaver/dbeaver#9437]
#### System information: 
- Operating system (distribution) and version: Windows Server 2019 Standard, 64 bits
- DBeaver version: 7.1.3

#### Connection specification:
- Database name and version: Oracle Autonomous Data Warehouse 19c

#### Describe your question:

I'm trying to connect the ADW to Dbeaver, but this error is occurring:
"unable to find valid certification path to requested target"

I'm trying to connect through the wallet with the TNS connection.
I have tried several ways, but without success.

complete error: 
IO Error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, connect lapse 5 ms., Authentication lapse 0 ms.
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, connect lapse 5 ms., Authentication lapse 0 ms.
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, connect lapse 5 ms., Authentication lapse 0 ms.
    PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, connect lapse 5 ms.
    PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, connect lapse 5 ms.
      PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        unable to find valid certification path to requested target
        unable to find valid certification path to requested target

**Comment by kseniiaguzeeva** [comment]
Wallet connection is available in DBeaver EE only. You can test the trial version for 2 weeks https://dbeaver.com/trial/

**Comment by luizmz94** [comment]
Is there an alternative to connecting with the community version?

**Comment by kseniiaguzeeva** [comment]
Through wallet - unfortunately no.

**Comment by luizmz94** [comment]
I managed to connect.

I configured ODBC with the Oracle Client, and then connected DBeaver using the ODBC driver.

**Comment by kseniiaguzeeva** [comment]
Great!
