### ISSUE TITLE
Can not copy table from one to other db. Unique key copied incorrectly

### ISSUE THREAD

**Issue by smcdl** [dbeaver/dbeaver#9439]
Fixed in 7.1.4

_Originally posted by @LonwoLonwo in https://github.com/dbeaver/dbeaver/issues/9341#issuecomment-667010986_

**Comment by smcdl** [comment]
1. copy a table in db A
2. paste the table in db B
3. the new table creation tab shows
4. click 'Save' button
5. the 'Persist Changes' dialogs shows
6. review the generated DDL you could find that unique index not only in DDL but also in create index statement.

**Comment by LonwoLonwo** [comment]
@smcdl What database name and version (both, A and B) you have?

**Comment by smcdl** [comment]
MySQL 5.7

**Comment by LonwoLonwo** [comment]
Still can't reproduce. 
@smcdl Have you any [error logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by smcdl** [comment]
![image](https://user-images.githubusercontent.com/4975064/89483496-d2e9e480-d7ce-11ea-85ba-1e0838b2032e.png)
I give you a screen record.

**Comment by smcdl** [comment]
![Kapture 2020-08-06 at 10 25 39](https://user-images.githubusercontent.com/4975064/89483795-8521ac00-d7cf-11ea-830a-ddb25ef8e0fc.gif)
I give you a clip of screen record

**Comment by smcdl** [comment]
![Kapture 2020-08-06 at 10 31 09](https://user-images.githubusercontent.com/4975064/89484043-24df3a00-d7d0-11ea-83af-abae656bfa53.gif)
I give you a clip of screen record

**Comment by LonwoLonwo** [comment]
So ok, i understood finally. The Unique key copied incorrectly in MySQL.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
