### ISSUE TITLE
Ideal connections after not using for too long

### ISSUE THREAD

**Issue by mittalyashu** [dbeaver/dbeaver#9440]
#### System information: 
- Operating system (distribution) and version: MacOS 10.15.5
- DBeaver version: 7.1.4

#### Describe your question:

Does dbeaver put a connection into ideal state after not using it for too long?

On the initial connection to database and query some data, it works perfectly. After not using for sometime _(10 minutes or more)_. Trying to query some data again, it doesn't load the data and continue to show the progress bar.

<img width="272" alt="Screenshot 2020-08-04 at 12 53 58 PM" src="https://user-images.githubusercontent.com/29014463/89265078-9775db80-d651-11ea-9df3-2af5419b2911.png">

**Comment by kseniiaguzeeva** [comment]
Which database and type of connection do you use?

**Comment by mittalyashu** [comment]
Database: Postgresql 12

What do you mean type of connection?

**Comment by kseniiaguzeeva** [comment]
Local, SSH, PROXY, another?

**Comment by mittalyashu** [comment]
I use the main connection type, using `HOST`, `DATABASE`, `USERNAME` and `PASSWORD`.

**Comment by uslss** [comment]
@mittalyashu 
could you try to change Keep-Alive option in Connection preferences and check if it solves the problem?
![image](https://user-images.githubusercontent.com/31996417/89900500-7f233500-dbec-11ea-8dc5-5508f4e306ee.png)
