### ISSUE TITLE
DB Navigator - add inline action buttons - the label is almost invisiable in the Darkest Dark Theme

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9446]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.4
- Additional extensions the Darkest Dark Theme

#### Describe the problem you're observing:
DB Navigator - add inline action buttons - the label is almost invisiable in the Darkest Dark Theme
#### Steps to reproduce, if exist:
Set a connection as read-only

Actual result:
1. Blue point is visiable only for SSH and other connections
2. Half of a lock and an arrow is visiable if SSH connection is read-only  

![dbeaver_l3VDectEGa](https://user-images.githubusercontent.com/51405061/89279856-8b3d4e80-d650-11ea-8e96-276a5f17b8a2.png)

**Comment by serge-rider** [comment]
Action icons were updated.
