### ISSUE TITLE
Export Geoms does not respect SRID

### ISSUE THREAD

**Issue by carlosbispo** [dbeaver/dbeaver#9447]
#### System information: 
- Operating system (distribution) and version: Windows
- DBeaver version: 7.1.4

#### Describe the problem you're observing:
When exporting a table with geoms using the export feature to SQL, SRID are not exported.
When trying to reimport an error occurs (SRID = 0)

#### Steps to reproduce, if exist:
- Create a table with a geom with SRID (geometry(Point,4326), for example)
- Create some dummy data
- Export to SQL using the export feature
- Truncate the table
- Reimport file created with export tool, error given (SRID = 0)

**Comment by kseniiaguzeeva** [comment]
Please tell me your database and is it possible to send an example of table DDL?

**Comment by carlosbispo** [comment]
Sure!

Here is an example: (This is for Postgres Database)

create table geom_testing (
	id int,
	"name" varchar(255),
	geom geometry(Point, 4326)
);

insert into geom_testing values(1, 'Testing', ST_SetSRID(ST_Point(-8.6964351, 40.3307427), 4326))

I´m afraid that maybe this is a problem in Postgres, when looking at exported SQL, the definition for geom column is POINT(-8.6964351, 40.3307427). This does not account for SRID in column...

Thanks for your reply!

**Comment by akilovich** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
