### ISSUE TITLE
SQL Error [1109] [42S02]: (conn=1154) Unknown table 'CHECK_CONSTRAINTS' in information_schema

### ISSUE THREAD

**Issue by cp-py** [dbeaver/dbeaver#9450]
#### System information: 
- Windows 10 Home 1909
- DBeaver version   DBeaver	7.1.4.202008021649	
- Java version : 11.0.5
- Additional extensions: NO

#### Connection specification:
- Mariadb 10.3.7
- org.mariadb.jdbc:mariadb-java-client: 2.4.3
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
Exactly same error as described in https://github.com/dbeaver/dbeaver/issues/9371#issue-666047048

**Comment by LonwoLonwo** [comment]
Fixed in 7.1.5

**Comment by uslss** [comment]
verified
