### ISSUE TITLE
"Remove all filters" button is inactive (greyed out) when sorting column

### ISSUE THREAD

**Issue by aironsholt** [dbeaver/dbeaver#9451]
Thanks for a great program. 

In version Version 7.1.4.202008021649 released 3rd Aug 2020, I'm struggling with the "remove all filters button/ordering". When manually sorting columns it stays greyed out (inactive). In previous versions it became active so the sorting could be removed.

Thanks in advance

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
Fixed in 7.2.0
