### ISSUE TITLE
Copying cell not working properly 

### ISSUE THREAD

**Issue by zumova** [dbeaver/dbeaver#9452]
#### System information: 
- Operating system (distribution) and version -- Windows 10
- DBeaver version 7.1.4.202008021649

#### Connection specification:
- Database Type: DB2 LUW
- Driver name: DB2 for Windows
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
Selecting all rows , select copy or Advance Copy function from Panel Result, the whole copied selection does not paste correctly, it pastes only the header and the value from column 1 row 1.

#### Steps to reproduce, if exist:
Run query
Get results
Go to results
Select all
Select Copy or Select Advance Copy
Paste the copied selection into a different editor application (word, Notepad, Excel, etc.)
[Copying cells - dbeaver.docx](https://github.com/dbeaver/dbeaver/files/5025038/Copying.cells.-.dbeaver.docx)

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce the issue. Is it possible to send me a table DDL example?

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Issue is closed. If it is still actual for you - feel free to reopen the ticket
