### ISSUE TITLE
PostgreSQL pgpass auth mishandles colon in password

### ISSUE THREAD

**Issue by baileych** [dbeaver/dbeaver#9454]
#### System information: 
- Operating system (distribution) and version: MacOS 10.14.6
- DBeaver version: 7.1.4.202008021649
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgreSQL 10.2, 12
- Driver name: org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
The PGPASS file uses a colon (':') as a field separator.  According to PostgreSQL documentation, if a password contains a colon, it must be escaped by use of a preceding backslash ('\\') character.  If I understand the DBeaver code path correctly, when a data source is defined with "pgpass" authentication type, DBeaver itself reads the PGPASS file and parses it, rather than deferring to the Postgres library or driver.  It uses a straightforward `.split(':')` to separate fields, but unfortunately this pattern does not account for potential backslash escape.

One might consider calling `.split('(?!\\):')` instead, to skip occurrences of '\\:'.

#### Steps to reproduce, if exist:
1. Define a PostgreSQL data source using pgpass authentication.
2. Set the password for a user to a string containing a colon (':').
3. Attempt to authenticate as that user.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
