### ISSUE TITLE
"All databases" option with no default database produces "FATAL: database 'something' does not exist.

### ISSUE THREAD

**Issue by KajKandler** [dbeaver/dbeaver#9456]
Did not find anything like this on issue or on Wiki 

### System information: 

- Operating system (distribution) and version
MacOS
- DBeaver version
Version 7.1.3.202007192031
- Additional extensions
non

#### Connection specification:

- Database name and version
PostgreSQL 10.11
PostgreSQL 10.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.9.3, 64-bit

- Driver name
PostgreSQL JDBC Driver 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
SSH tunnel

#### Describe the problem you're observing:

When I create a connection with "PostgreSQL-->"Show all Database = true" and I set no default database in "Main-->Database = empty" it tries to connect to a database 'something' (not the real database name), but does not exist. I'd expect it to try to connect to `postgres`

#### Steps to reproduce, if exist:

1. Configure a connection as in the problem description
2. Click "Test Connection" in the "Edit Connection" dialog.

#### Include any warning/errors/backtraces from the logs

nothing that seems to illuminate this issue

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it in the latest release 7.1.4.
1. Please check what is written in Connection settings>Initialization (default database and schema)
![dbeaver_oS1jRJuDFP](https://user-images.githubusercontent.com/51405061/89397905-1bdf6180-d719-11ea-9ddd-37bb175c4d8a.png)

2. If there are not wrong databases/schemas in Initialization could you please try 7.1.4 DBeaver version https://dbeaver.io/download/?

**Comment by cplasse** [comment]
There is another problem in "All database" option : when specified user does not have rights to all existing database, error message "permission denied for database xxx" is displayed instead of displaying only granted databases (seen after migrate from 7.1.3 to 7.1.5, PostgreSQL 9.6)

**Comment by uslss** [comment]
@cplasse this feature will be implemented in scope of #9721
