### ISSUE TITLE
Read only result in output grid

### ISSUE THREAD

**Issue by chauhan-pawan** [dbeaver/dbeaver#9457]
#### System information: 
- Operating system (distribution) and version - Windows 10
- DBeaver version - 7.1.4
- Additional extensions

#### Connection specification:
- Database name and version - Redshift
- Driver name - latest jdbc driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - on VPN

#### Describe the problem you're observing: Unable to edit records in query result grid, resultant columns are read only. as we can see "R" mentioned on columns name in attached snapshot. Issue exists since 7.1.1, prior version working fine.
![Capture](https://user-images.githubusercontent.com/69239365/89391859-60bdc500-d726-11ea-8737-7d32d3db80ed.JPG)

**Comment by serge-rider** [comment]
This issue is similar to #9239 . The bug is a result of change column search algorithm for PostgreSQL (which supports ambiguous column names in resultsets).
Fixed

**Comment by mhs1** [comment]
Same problem here

Operating system: Debian 9 (Stretch)
DBeaver version: 7.1.4
Additional extensions: - 

Database name and version: MariaDB 10.2
Proxies, tunnels: no.

Thanks.

**Comment by kseniiaguzeeva** [comment]
@mhs1 Please send me a query example to reproduce the issue.

**Comment by uslss** [comment]
verified
