### ISSUE TITLE
Unable to install Office plugin

### ISSUE THREAD

**Issue by chauhan-pawan** [dbeaver/dbeaver#9458]
#### System information: 
- Operating system (distribution) and version - windows 10
- DBeaver version - 7.1.4
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing: unable to install office plugin
![image](https://user-images.githubusercontent.com/69239365/89399576-4daff280-d730-11ea-848c-ad3acbcc3826.png)

**Comment by kseniiaguzeeva** [comment]
Do you use eclipse or standalone DBeaver?

**Comment by chauhan-pawan** [comment]
No eclipse, standalone DBeaver

**Comment by kseniiaguzeeva** [comment]
Could you please try to remove DBeaver completely and install it again?

**Comment by chauhan-pawan** [comment]
I tried by removing and reinstalling but issue persist. error - system unable to find xml file as i mentioned above currently concerned file is with xz extention.

**Comment by kseniiaguzeeva** [comment]
Could you please try latest 7.1.5 https://dbeaver.io/download/ ?

**Comment by chauhan-pawan** [comment]
Tried with latest version but no success, but when i copied files from server and placed them on local system and remove xz extention from xml file, it worked.

**Comment by chauhan-pawan** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5141853/dbeaver-debug.log)
[log.log](https://github.com/dbeaver/dbeaver/files/5141854/log.log)

**Comment by uslss** [comment]
cannot reproduce an issue against 7.3.0.
If it is still actual for you - feel free to reopen it with additional info.
