### ISSUE TITLE
Unable to install Darkest theme with dev style

### ISSUE THREAD

**Issue by chauhan-pawan** [dbeaver/dbeaver#9459]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 7.1.4
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing: Unable to install Darkest theme with dev style. I am receiving below mentioned error. I think it has the same case as i reported for Office plugin but not sure.
url - https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle
![image](https://user-images.githubusercontent.com/69239365/89400364-6d93e600-d731-11ea-935b-3939f88d0fa9.png)

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Which Java version do you use?

**Comment by chauhan-pawan** [comment]
i think dbeaver uses java version shipped with installation file. However java 8 update 231 is installed on my system.

**Comment by kseniiaguzeeva** [comment]
The ticket #9386 already exists.
