### ISSUE TITLE
DBeaver 7.1.4 going Hung

### ISSUE THREAD

**Issue by suby-ge** [dbeaver/dbeaver#9461]
#### System information: 
- Operating system (distribution) and version : Windows 10 Pro
- DBeaver version - 7.1.4 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by kseniiaguzeeva** [comment]
I can't reproduce it. Could you provide a description? 
Does it happen during DBeaver launch or during work? Any other specific details? 
Which OS and database do you use?

**Comment by suby-ge** [comment]
Yes. During launch.
Windows 10 pro – 64 bit

Thanks,

Subhadra Parthasarathy (Suby)

**Comment by kseniiaguzeeva** [comment]
And how long does it continue? Can you work in Dbeaver after it?

**Comment by suby-ge** [comment]
Its closing in few seconds, I even tried to restart my machine and try this, but no error found as such.

I am currently connected to 7.1.3 and your website is not having the old set up.

No of users affected as of now - 40

Thanks,

Subhadra Parthasarathy (Suby)

**Comment by kseniiaguzeeva** [comment]
Could you please try to delete DBeaver completely and then download and install the latest release again https://dbeaver.io/download/? 

Here you can find earlier versions https://dbeaver.io/files/

**Comment by suby-ge** [comment]
Will try and get back to you.

Thanks,

Subhadra Parthasarathy (Suby)

**Comment by suby-ge** [comment]
Hi,

Its working fine now.
Was any changes made?

Thanks,

Subhadra Parthasarathy (Suby)

From: Parthasarathy, Subhadra (GE Healthcare, consultant)
Sent: Wednesday, August 5, 2020 4:50 PM
To: dbeaver/dbeaver <reply@reply.github.com>; dbeaver/dbeaver <dbeaver@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: EXT: Re: [dbeaver/dbeaver] DBeaver 7.1.4 going Hung (#9461)

Will try and get back to you.

Thanks,

Subhadra Parthasarathy (Suby)

**Comment by kseniiaguzeeva** [comment]
No,most probably a fail was during installation process. In this case I close the ticket.
