### ISSUE TITLE
Cannot Update to the latest version of DBeaver CE

### ISSUE THREAD

**Issue by AgarkovAntonn** [dbeaver/dbeaver#9462]
#### System information: 
- Linux Mint 20
- DBeaver version 7.1.3
  DBeaver	7.1.3.202007192031	org.jkiss.dbeaver.core.product	null

#### Connection specification:
- Database name and version

#### Describe your question:
When i trying to update DBeaver via:
Help->Install New Software->"DBeaver CE update site - https://dbeaver.io/update/ce/latest/"->"DBeaver IDE	7.1.4.202008021649"->Next
i get next errors:
![изображение](https://user-images.githubusercontent.com/69244092/89404674-0b33e900-d723-11ea-904b-d126e65d22e4.png

How can i fix this problem?
Thanks

**Comment by uslss** [comment]
Hi @AgarkovAntonn ,
do you use eclipse plugin or standalone version?

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Issue is closed. If it is still actual for you - feel free to reopen the ticket
