### ISSUE TITLE
Can't connect to Sybase ASA 11

### ISSUE THREAD

**Issue by canozip** [dbeaver/dbeaver#9467]
#### System information: 
- Windows 10
- DBeaver version 7.14

#### Connection specification:
- Sybase ASA 11

#### Describe your question:

I can't connect to Sybase ASA 11 with current Dbeaver 7.14. It comes 
JZ00L: Login failed.  Examine the SQLWarnings chained to this exception for the reason(s).
JZ00L: Login failed.  Examine the SQLWarnings chained to this exception for the reason(s).
  SQL Anywhere Error -1212: Connection disallowed by login policy for this user
  010HA: The server denied your request to use the high-availability feature.  Please reconfigure your database, or do not request a high-availability session.
  SQL Anywhere Error -1212: Connection disallowed by login policy for this user
  010HA: The server denied your request to use the high-availability feature.  Please reconfigure your database, or do not request a high-availability session.

i dont know what i must do

**Comment by kseniiaguzeeva** [comment]
Which type of connection do you use? Please recheck user name and password. What is written in host in Main tab of Connection Settings?

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Issue is closed. If it is still actual for you - feel free to reopen the ticket

**Comment by kaidlokhandwala** [comment]
The below error Resolved after I stored the password in connection settings.

010HA: The server denied your request to use the high-availability feature. Please reconfigure your database, or do not request a high-availability session.

**Comment by Barhobbit18** [comment]
same issue

> The below error Resolved after I stored the password in connection settings.
> 
> 010HA: The server denied your request to use the high-availability feature. Please reconfigure your database, or do not request a high-availability session.

have the same issue. readonly user works, but mon_role giving this issue.
