### ISSUE TITLE
php export qoutes sometimes is bad

### ISSUE THREAD

**Issue by stivehu** [dbeaver/dbeaver#9468]
#### System information: 
- Operating system (distribution) and version: all
- DBeaver version: 7.1.4
- Additional extensions

#### Describe the problem you're observing:
I try to export this data
"password_hash" => "$2y$12$y4fh4zApgf6gVd4KmvnWUO0ct61aaiF7zTw\/KVpHpx.\/E5VlcXC.W"
This not use in php in dollar sign. My suggession  use an apostrophe instead of a quotation mark.
for example:
'password_hash' => '$2y$12$y4fh4zApgf6gVd4KmvnWUO0ct61aaiF7zTw\/KVpHpx.\/E5VlcXC.W'

**Comment by LonwoLonwo** [comment]
@stivehu I can add a new parameter to the php export settings to select the type of quotes. But this will change ALL quotes in the output file. Is this solution convenient for you? or do you only want to change quotes for a specific data type?

**Comment by stivehu** [comment]
That's perfect solution!

**Comment by kseniiaguzeeva** [comment]
In this case t he ticket is closed

**Comment by uslss** [comment]
verified
