### ISSUE TITLE
Cassandra uppercase keyspaces are forced to lowercase

### ISSUE THREAD

**Issue by davidellis** [dbeaver/dbeaver#9473]
I'm running Dbeaver Enterprise Version 7.1.202006211226 Released: June 1,2020 on Ubuntu 18.04.

I'm connecting to a Cassandra 2.1.16 cluster withe uppercase characters in the keyspace. My issue is that if I try and use the CQL Editor to run a select statement the keyspace is being converted to lowercase - resulting in "keyspace not found error".

Consider:

SELECT * FROM "MySpace"."MyItem" - it is running as SELECT * FROM myspace.MyItem - and failing for obvious reasons.

Asides from this once hitch I really love the product - It would be great to have this working.

**Comment by serge-rider** [comment]
This has to be fixed in the latest version

**Comment by kseniiaguzeeva** [comment]
verified
