### ISSUE TITLE
auto unselect datasource when editor save action in latest version

### ISSUE THREAD

**Issue by shiyingyan** [dbeaver/dbeaver#9474]
#### System information: 
- Windows10 1709
- DBeaver version  7.1.3.202007192031

#### Describe your question:
sql编辑器中，编辑后保存时，选择的数据源自动会变成非选择性，又让重新选择。 体验非常不好， 希望尽快改进。谢谢

**Comment by kseniiaguzeeva** [comment]
Could please send a description in English and attach a screenshot?

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Issue is closed. If it is still actual for you - feel free to reopen the ticket
