### ISSUE TITLE
Read data in SQL Console works incorrectly in special case

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9475]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.1.4

#### Describe the problem you're observing:
If Write connection binding in Script header option is enabled and then Read data in SQL Editor performed, query doesn't start from new line.

![image](https://user-images.githubusercontent.com/31996417/89659016-f2206900-d8d7-11ea-85cf-d295eefef83d.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
