### ISSUE TITLE
Refresh In Custom ERD Resets Notes To Front

### ISSUE THREAD

**Issue by Eddie-Hartman** [dbeaver/dbeaver#9480]
#### System information: 
- Operating system (distribution) and version
Windows 10 latest
- DBeaver version
7.1.4
- Additional extensions
Darkest Dark Theme

#### Connection specification:
- Database name and version
SQL Server
- Driver name
JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
Refreshing a custom ERD will reset the position of notes to the front.

#### Steps to reproduce, if exist:
1. Create a custom ERD with a single table.
2. Create a Note with text and cover the table like so:
![image](https://user-images.githubusercontent.com/14089997/89720440-442cc180-d9a0-11ea-8d8f-389d17985df0.png)

3. Send the note to the back.
4. Refresh the diagram.

Actual: The note is now in front of the table.
![image](https://user-images.githubusercontent.com/14089997/89720458-79391400-d9a0-11ea-8519-73198d643d18.png)

Expected: The diagram remembers relatively where the note is in front or behind the table. In this case, the note would be behind the table.

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report. It is actual for different databases.

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified

**Comment by flambchap** [comment]
@serge-rider has found a problem leading to NPE.

STR:
1. Open an embedded ER diagram, e.g. Chinook -> Artist -> ER Diagram.
2. Toggle 'persist diagram' twice.
3. A dialog window pops up. Choose 'Yes'.
4. Boom!

The fix is on its way.
