### ISSUE TITLE
SQLite Drop column / Modify constrains

### ISSUE THREAD

**Issue by mbnoimi** [dbeaver/dbeaver#9482]
Hi,

SQLite doesn't support modifying constraints/columns to an existing table so DBeaver allows to set them only during table creation so I suggest to support modifying constraints/columns by using [this trick](https://www.sqlite.org/faq.html#q11) (I hate to write scripts whenever I want to make this modification)

**Comment by mbnoimi** [comment]
[SQLite Maestro](https://www.sqlmaestro.com/products/sqlite/maestro/) already do this trick automatically in the background without forcing the user the manipulate it manually as shown below but unfortunately it's a commercial product.

![image](https://user-images.githubusercontent.com/284547/89729358-9bcd3a80-da3d-11ea-8ddc-d45eda90e298.png)

```SQL
CREATE TABLE Album01 (
  Album_id,
  title,
  Artist_id
);

INSERT INTO Album01
SELECT
  Album_id,
  title,
  Artist_id
FROM Album;

DROP TABLE Album;

CREATE TABLE Album (
  Album_id   integer NOT NULL DEFAULT -1 PRIMARY KEY,
  title      text NOT NULL DEFAULT Title,
  Artist_id  integer NOT NULL DEFAULT -1,
  /* Foreign keys */
  CONSTRAINT Album_FK
    FOREIGN KEY (Artist_id)
    REFERENCES Artist(Artist_id)
    ON UPDATE CASCADE
);

INSERT INTO Album
  (Album_id,
  title,
  Artist_id)
SELECT
  Album_id,
  title,
  Artist_id
FROM Album01;

DROP TABLE Album01;
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea!

**Comment by kseniiaguzeeva** [comment]
Drop column syntax will be added in 7.2.3 release according https://github.com/dbeaver/dbeaver/issues/5447

**Comment by mbnoimi** [comment]
Fantastic

**Comment by kseniiaguzeeva** [comment]
closed
