### ISSUE TITLE
Query Editor - Copying / Pasting text with mixed quotes (non verbatim paste)

### ISSUE THREAD

**Issue by rdenxx** [dbeaver/dbeaver#9483]
#### System information: 
- Windows 7
- DBeaver version 7
- No additional extensions

#### Connection specification:
- Firebird 1.5
- Driver name: (standard installed)

Copying / pasting - both ^C ,,, ^V or from right-click drop-down

highlighting and copying the following (including the quotes ):    '"' || stockcode || '"'
<single-quote><double-quote><single-quote> <bar><bar> {text} <bar><bar> <single-quote><double-quote><single-quote>

pasting it back into the sql editor yields  (including quotes):   ' || stockcode || '
<single-quote> <bar><bar> {text} <bar><bar> <single-quote>

pasting it elsewhere (i.e. notepad++, visual studio, even this report page etc yeilds the original result

... only pasting it back into the DBeaver sql editor yields an altered result

seems the paste function is interpreting the output rather than verbatim pasting it.

no warnings/errors/backtraces from the logs1

AS-IS: It's obscure, not something that matters a lot in daily use
except in a larger sense Paste should always be verbatim-out (i.e. not try to interpret/simplify - never modify)

**Comment by kseniiaguzeeva** [comment]
Am I correct that the steps are following?:
1. Open SQL Editor for Firebird 1.5
2. Enter in SQL Editor **'"' || stockcode || '"'
{text}**
3. Copy the text
4. Paste the text in SQL Editor

Actual result: the pasted text is altered: **' || stockcode || '
{text}**

I cannot reproduce it by this way. Could you please try the latest 7.1.4 https://dbeaver.io/download/? 
![quWQIBqSan](https://user-images.githubusercontent.com/51405061/89782554-284f2a00-db1e-11ea-8530-bfa2fa98425b.gif)

**Comment by uslss** [comment]
there is no update on the issue for a long time.  
If the issue is still actual for you - feel free to reopen the ticket with additional info that could help to investigate and reproduce an issue.
