### ISSUE TITLE
Improved "Show Comment" in "ER Diagrm"

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#9485]
Comments are not displayed even if the "Show Comment" option is checked in "ER Diagram"
If you update after searching "Table Properties", the comment is displayed correctly.
If "Dbeaver" is closed and run again, the comment is not displayed.
Like Column List or Primary Key, we want to be searched when opening Er Diagram.

![image](https://user-images.githubusercontent.com/59002295/89744238-fe7a1100-dae5-11ea-90c5-2dd8cb0cee17.png)
![image](https://user-images.githubusercontent.com/59002295/89744293-75170e80-dae6-11ea-82bf-bcd81ff53699.png)
![image](https://user-images.githubusercontent.com/59002295/89744247-08037900-dae6-11ea-96a6-8eb09dd63931.png)
 - after search "Table Properties".

Thank for read. :)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. Looks like a kind of bug. I cannot reproduce it. 
Which database and DBeaver version do you use?

**Comment by podoni** [comment]
#### System information: 
- Operating system (distribution) and version
  - Window10
- DBeaver version 
  - Dbeaver 7.1.4

#### Connection specification:
- Database name and version
  - Oracle 18c

1. When the table is first added to ERDiagram, the comment is not displayed, but when you refresh after searching the table properties, it is displayed on the screen.
![erd_1](https://user-images.githubusercontent.com/59002295/89845563-d0660100-dbb9-11ea-8707-34e2810198be.gif)

2. After saving and running Dbeaver again, open the ER Diagram and the comment is not displayed. After that, you should do it like No. 1 to look normal.
![erd_2](https://user-images.githubusercontent.com/59002295/89845586-dd82f000-dbb9-11ea-908b-387227226d99.gif)


Thank for reply and reading

**Comment by kseniiaguzeeva** [comment]
Thank you. It is Oracle issue.

**Comment by akilovich** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by Micron818** [comment]
but the issue was raised again at the latest version Version 23.0.5.202305211610

**Comment by flambchap** [comment]
@Micron818, I couldn't see the comments after turning this setting on, but when I closed and reopened the diagram again, it appeared. Can you please try reopening the diagram?

<img width="410" alt="image" src="https://github.com/dbeaver/dbeaver/assets/26031301/ac41e91c-888c-4193-b60a-930457a62440">

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
