### ISSUE TITLE
Add "show comments" for DDL and source of SQL functions

### ISSUE THREAD

**Issue by vandroiycl** [dbeaver/dbeaver#9487]
**Is your feature request related to a problem? Please describe.**
In version 6.0.+ I was able to see the comments in a Postgres function by default, but since 7.+ no comments are displayed.

**Describe the solution you'd like**
Add "Show Comments" button at the bottom of the source view, as in table DDL view.

**Describe alternatives you've considered**
As a workaround, I can only see the comments on a tooltip, while hovering the name of the function.

**Additional context**
![03_dbeaver_comms](https://user-images.githubusercontent.com/10758278/89748724-a1a13b00-da92-11ea-8ebf-95a372ffec18.png)

**Comment by SA357** [comment]
Was added in #9387

**Comment by uslss** [comment]
verified
