### ISSUE TITLE
Getting numeric values as strings when pasting into Excel

### ISSUE THREAD

**Issue by codie-fz** [dbeaver/dbeaver#9488]
I’m running DBeaver Version 7.1.3.202007192031 on Windows 10.

When I copy numeric values from a query output and paste it into Excel these values are imported as strings. If I have a negative number it is shown as a #FIELD error in Excel. I think this might be linked to data formats since I’m from a country where decimals are shown with a comma rather than a dot. Manually replacing dots with commas in Excel fixes this, however I’d like to save this step.

I already tried changing Data Formats settings to “Use native numeric format” plus using advanced copy with the Value Format “Display (default) which worked well for the numeric values. However it also imported NULL values as a “NULL” string. Again replacing the NULL strings in Excel would fix this but it is an additional step.

Is there any way to just copy and paste my query output to Excel and getting the numeric values as numeric values (with a comma for decimals) as well as NULL values as empty cells? Changing regional settings in Excel is not an option.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. As a workaround you can export selected rows/columns in xlsx format.

**Comment by kseniiaguzeeva** [comment]
Which database and locale do you use? And column type? I can reproduce the issue with decimal string only.
HAve you tried to use Advanced copy (Ctrl+Shift+C)?

**Comment by uslss** [comment]
Issue closed - no updates for a long time.
If it is still actual - feel free to reopen the ticket
