### ISSUE TITLE
PostgreSQL: Check constraint expression is not displayed in Table Properties

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9492]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version DBeaver 7.1.4

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
Check constraint expression is not displayed in Table Properties
#### Steps to reproduce, if exist:
1. Create a check constraint
2. Check **expression** field of the constraint (e.g. can be seen in Postgres 12 testas.foo)

![dbeaver_rRseJAnRco](https://user-images.githubusercontent.com/51405061/89799847-a9b2b680-db36-11ea-9d95-5499b767c5dd.png)

**Comment by LonwoLonwo** [comment]
Postgres 12 has removed the pg_constraint.consrc column. could try to link to information_schema.check_constraints by constraint name
https://www.postgresql.org/docs/12/catalog-pg-constraint.html

**Comment by kseniiaguzeeva** [comment]
verified
