### ISSUE TITLE
warning: unknown table 'check_constraints' in information_schema

### ISSUE THREAD

**Issue by rotorboy** [dbeaver/dbeaver#9493]
#### System information: 
- MacOS 10.14
- DBeaver 7.1.4.202008021649
- Additional extensions: none

#### Connection specification:
- Database name and version - MariaDB (Ver 15.1 Distrib 10.3.9-MariaDB)
- Driver name JKISS 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

After upgrading to 7.I.4 now get a warning of "unknown table 'check_constraints' in information_schema", and I'm no longer able to delete records using the editor "delete row" button, even when unique index column included in recordset; I must actually run a delete command on the actual record to do the delete. This was not a problem in DBeaver 7.1.3. 

I saw a similar issue here but doesn't seem to address my issue: https://github.com/dbeaver/dbeaver/issues/6069

Is there some way to disable the constraint check, or otherwise tell DBeaver to ignore that error?

thanks

**Comment by LonwoLonwo** [comment]
@rotorboy yes, now we know where the problem was. Fixed in 7.1.5 
Duplicate https://github.com/dbeaver/dbeaver/issues/9450

**Comment by rotorboy** [comment]
thanks. When will 7.1.5 be released?

**Comment by LonwoLonwo** [comment]
@rotorboy official release - August 17. But you can try to download from here https://dbeaver.io/files/ea/ in a couple of days
