### ISSUE TITLE
Make the show palette button greater

### ISSUE THREAD

**Issue by adriancuadrado** [dbeaver/dbeaver#9496]
**Is your feature request related to a problem? Please describe.**
The "Show palette" button is so small that it took me a while to discover it was there. I felt desperate at some point because in the documentation I saw how the palette was supposed to be there but it just didn't appear and I didn't know I had to press that super small button until I realized there was one right there. If you are not willing to make this button bigger by default at least mention in the documentation of ER diagrams how to make that palette appear.

![image](https://user-images.githubusercontent.com/29214635/89900370-f7d1c380-dbe3-11ea-8ded-040a52b48c81.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
We can't fix it in GEF 3 (it is not supported by GEF implementation).
Will be auto fixed after GEF 5 migration.
