### ISSUE TITLE
Add connection information when using multiple databases from the same server

### ISSUE THREAD

**Issue by ahbrajev** [dbeaver/dbeaver#9498]
Hey guys,

On the first screenshot, I created a remote connection to a server that has multiple databases on the same port - so far so good.
![image](https://user-images.githubusercontent.com/56494745/89910665-cdd2ce00-dbf0-11ea-9bb2-7e890b607d63.png)

Now my issue is that when opening the query tool to write some queries, I cannot really know which databases I'm connected to since it's just giving me the server name. Since I'm always switching between productive and test systems, it is really frustrating not to be sure which databse I am connected to. 

The second problem is that DBeaver believes that I'm using the same database and automatically opens a window to let me choose wether I want to use a new script or the existing one (that is used on another database). See second screenshot:
![image](https://user-images.githubusercontent.com/56494745/89910843-02468a00-dbf1-11ea-8ea8-63daedf4a509.png)

I hope you could understand me.

**Solution**
The solution for me would be to simple add the database you're connected to in the tab. See screenshot:
![image](https://user-images.githubusercontent.com/56494745/89911815-2787c800-dbf2-11ea-8349-46377b882052.png)

**Describe alternatives you've considered**
Till now, I used to create separate connection for each databases on that port - that does the trick, but really takes a lot of time.

Thank you

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. It can be implemented

**Comment by ahbrajev** [comment]
@kseniiaguzeeva in which update could we expect this?`

br

**Comment by kseniiaguzeeva** [comment]
It is planned in release 7.2.1

**Comment by ahbrajev** [comment]
Thank you

**Comment by serge-rider** [comment]
DBeaver shows active database in the main toolbar:
![image](https://user-images.githubusercontent.com/6398845/93172782-2cc9bc80-f734-11ea-89b9-23f8c15bf212.png)

I'm afraid adding the same information to the tab would be a bit excessive.
Anyhow, you can configure how script title looks in the preferences:
![image](https://user-images.githubusercontent.com/6398845/93174411-9945bb00-f736-11ea-86eb-fe66743dfd3f.png)

I've added new variables ${database} and ${schema}. You can use them to customize script name.

also I've added acxtive database and schema info in the editor tab tooltip.

**Comment by kseniiaguzeeva** [comment]
Is it expected when script pattern is used <${connectionName}>${schema}@${database}: ${fileName}:
- MySQL/Maria **${schema}** is written (database name is ok)
- DB2/Oracle **Schema** _schema_name_@**${database}** is written
- Firebird **${schema}@${database}** is written

Please see
![dbeaver_hZClAESqiR](https://user-images.githubusercontent.com/51405061/93206539-3538ec00-f762-11ea-96b5-d455e8dd04e8.png)

**Comment by ahbrajev** [comment]
That is exactly what I wanted to have. Thanks a lot!

**Comment by serge-rider** [comment]
@kseniiaguzeeva yes, it works as expected

**Comment by kseniiaguzeeva** [comment]
ok
