### ISSUE TITLE
Close SSH Tunnel when Connection is Closed

### ISSUE THREAD

**Issue by numeralnathan** [dbeaver/dbeaver#9500]
#### System information: 
- Operating system: Windows 10 version 1909 build 18363.959
- DBeaver: 7.1.4.202008021649
- Additional extensions: None

#### Connection specification:
- Database: Oracle 19c
- Driver name: DBeaver's built in Oracle driver (i.e. oracle.jdbc.driver.OracleDriver)
- Do you use tunnels?  Yes, SSH

#### Describe the problem you're observing:
I am unable to reconnect to a database via a SSH tunnel after canceling a query.  The SSH tunnel is already established and cannot be reestablished.

Please close the SSH tunnel when the connection is closed.

#### Steps to reproduce, if exist:
1. Execute a long running query
2. Click on the cancel query button
3. Wait for the connection to close
4. Select the connection
5. Click on the connect button
6. Wait for the error dialog to show up

#### Include any warning/errors/backtraces from the logs
Address already in use: NET_Bind
Can't initialize tunnel
  Cannot establish tunnel
  Cannot establish tunnel
    PortForwardingL: local port 127.0.0.1:61526 cannot be bound.
    PortForwardingL: local port 127.0.0.1:61526 cannot be bound.
      Address already in use: NET_Bind
      Address already in use: NET_Bind

**Comment by serge-rider** [comment]
I can't reproduce it on our environment.

**Comment by uslss** [comment]
@numeralnathan can you check if the issue is still reproducible for you against 7.3.1?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual - feel free to reopen it
