### ISSUE TITLE
can't import CSV into a hive table. 

### ISSUE THREAD

**Issue by bayeslearner** [dbeaver/dbeaver#9502]
I try to import a movie lens table u.data into a hive table. 

All the steps seem to go through till you click on execute button: 

It basically is stuck at the first batch, with no error messages.

**Comment by kseniiaguzeeva** [comment]
Could you please send Error log? Also there are a lot of changes in Data transfer in release 7.1.5 (17.08.20). The issue can be resolved there. EA version is already available. You can try it https://dbeaver.io/files/ea/

**Comment by uslss** [comment]
Issue closed - no updates for a long time.
If it is still actual - feel free to reopen the ticket
