### ISSUE TITLE
Postgresql driver download failed

### ISSUE THREAD

**Issue by harry100** [dbeaver/dbeaver#9503]
![Screenshot from 2020-08-12 12-58-44](https://user-images.githubusercontent.com/16368638/89986188-e815b600-dc9b-11ea-936d-463890798dee.png)
Im using the DBeaver community edition 7.1.4
 At first open I was prompted to download psql driver which failed.

Any thing else I need to setup?

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Which OS do you use?

**Comment by harry100** [comment]
ubuntu 18.04.1 LTS
Btw, I resolved it by manually downloading the jar file and added it from Driver manager.

I was just curious about the Maven error

**Comment by sloubi** [comment]
Hi,
Same error here on windows 10 with a fresh install.
![Capture](https://user-images.githubusercontent.com/2783444/90110612-c8d76100-dd4d-11ea-9fdc-178199f415ca.PNG)
