### ISSUE TITLE
Import task fails

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9504]
Import task fails (7.1.4.202008120713):
1. It is not offered to select database or CSV file format to import
2. NPE appears in **input files** step
![dbeaver_AkInYUgscs](https://user-images.githubusercontent.com/51405061/89992068-6b7bdb00-dc8d-11ea-95f1-4afd1c191a69.png)
3. CSV format is not offered when select a file from an external  folder

**Comment by serge-rider** [comment]
Please attach error log with stacktrace

**Comment by kseniiaguzeeva** [comment]
Please see logs
[.log](https://github.com/dbeaver/dbeaver/files/5061445/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5061447/dbeaver-debug.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
