### ISSUE TITLE
support postgresql 11+

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#9506]
dbeaver 7.1.4
postgresql 12

1. no section of table in table DDL 
![изображение](https://user-images.githubusercontent.com/61137576/90009893-57010800-dcb8-11ea-8b62-a06eab07ee0e.png)

2. no possibility for create index or keys on partition of table by the interface

![изображение](https://user-images.githubusercontent.com/61137576/90010361-279ecb00-dcb9-11ea-851c-27faedd61cc4.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
Create menu isn't available in case of focus absence
![2020-11-09_14h08_23](https://user-images.githubusercontent.com/31996417/98534247-3cc5ce80-2295-11eb-8f49-85e66b984407.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
