### ISSUE TITLE
[SQL Server] Int column type imports as Varchar from db to db

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9508]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.4 7.1.4.202008121055

#### Connection specification:
- Database name and version SQL Server

#### Describe the problem you're observing:
Int column type imports as Varchar from db to db
#### Steps to reproduce, if exist:
1. Create a table with Int column
2. Select Export data in context menu of DB Navigator for the table
3. Select Create new table as target
4. Press Schema btn
5. Run export

Actual result:
1. Varchar column type is displayed in table DDL when press Schema
2. New table is created with Varchar column instead of Int

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
