### ISSUE TITLE
Bad display in the grid

### ISSUE THREAD

**Issue by perverez** [dbeaver/dbeaver#9516]
#### System information: 
- Windows 10 Pro, version 2004, build 19041.388
- 7.1.4.202008021649
- None

#### Describe the problem you're observing:
- The data in the column that is right-aligned overlaps the data in the left column

#### Steps to reproduce, if exist:
- Change column width
![DbGrid](https://user-images.githubusercontent.com/27768361/90110201-23bc8880-dd4d-11ea-9933-b7f0d854fdbf.png)

**Comment by kseniiaguzeeva** [comment]
The ticket duplicates https://github.com/dbeaver/dbeaver/issues/9411. It will be fixed in 7.1.5 release
