### ISSUE TITLE
Set role to connect as, in postgresql connection

### ISSUE THREAD

**Issue by jeanpommier** [dbeaver/dbeaver#9518]
#### System information: 
- Linux, Debian Buster
- DBeaver 7.1.4

#### Connection specification:
- Postgresql (server is version 10.12)

#### Describe your question:

Hi,
PostgreSQL allows to grant roles to a user. If you set it to NOINHERIT, , they have to ask specificly to connect as this role to be able to impersonate it. For instance, I've created a role_db_admin role, with superuser privileges. But I want a user to be superuser only when he has to.
This means I have to be able to SET the role I want to impersonate when I define my connection. In pgAdmin4 for instance, there is a role field in the connection parameters. I haven't found one in DBeaver connection properties, driver properties, nor in the documentation, nor by googling it. It this a missing feature ? Or is there another way to do it, that I would have missed ?
Thanks !

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea!

**Comment by jeanpommier** [comment]
Well, you're welcome, this would be a very nice feature indeed ! ;o)

**Comment by akilovich** [comment]
Feature added.

**Comment by uslss** [comment]
verified
