### ISSUE TITLE
PostgreSQL at version 12 not support column hasoids in pg_catalog.pg_class

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#9522]
Dbeaver 7.1.4
PostgreSQL 12

https://postgresql.verite.pro/blog/2019/04/24/oid-column.html

Can't get column 'relhasoids': The column name relhasoids was not found in this ResultSet.

![2020-08-13 16_32_39-DBeaver Enterprise 7 2 0 - foo](https://user-images.githubusercontent.com/45152336/90141251-8f214d00-dd83-11ea-9bb3-ffac4555c676.png)

Using checkbox "hasoids" in Table Properties results in an error. 

Need to remove the reading of this column for version 12

**Comment by LonwoLonwo** [comment]
checkbox "hasoids" in table editor removed for Postgres version >= 12

**Comment by uslss** [comment]
verified
