### ISSUE TITLE
PostgreSQL table does not show column options for foreign table

### ISSUE THREAD

**Issue by GammaGames** [dbeaver/dbeaver#9525]
#### System information: 
- Operating system (distribution) and version: elementary OS 5.1.7
- DBeaver version: 7.1.4.202008021649

#### Connection specification:
- Database name and version: PostgreSQL 9.5.21
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I have a foreign table using the file_fdw wrapper to load a csv file. The table definition is:
```sql
CREATE FOREIGN TABLE public.my_table (
    column_one text,
	date timestamptz OPTIONS(force_null 'true') NULL,
)
SERVER file_fdw
OPTIONS (filename '/path/to/file.csv', format 'csv', null '');
```

When viewing the table's DDL in the browser it shows the following:
```sql
CREATE FOREIGN TABLE public.my_table (
    column_one text,
	date timestamptz NULL,
)
SERVER file_fdw
OPTIONS (filename '/path/to/file.csv', format 'csv', null '');
```

Excluding the column options works when creating the table, but it throws an error when trying to select data.

#### Steps to reproduce, if exist:
1. Create foreign table with column `OPTIONS`
2. Get query to recreate it from dbeaver
3. Recreate it
4. Errors when column is empty:

```
ERROR: invalid input syntax for type timestamp with time zone: ""
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. Is it possible to give a file example?

**Comment by GammaGames** [comment]
Sure, here's a demo with `docker-compose`. Just start it and look at the DDL for `public.my_table`:
![image](https://user-images.githubusercontent.com/7832163/90264164-e966f000-de0d-11ea-808c-3cac2d7b47c2.png)

[my_table.zip](https://github.com/dbeaver/dbeaver/files/5075310/my_table.zip)

**Comment by LonwoLonwo** [comment]
Foreign table column option can be found in pg_class.pg_attribute in column attfdwoptions

**Comment by kseniiaguzeeva** [comment]
verified
