### ISSUE TITLE
Geopackage (sqlite+spatial) as true DBeaver citizen

### ISSUE THREAD

**Issue by rduivenvoorde** [dbeaver/dbeaver#9526]
**Is your feature request related to a problem? Please describe.**

Geopackage, is a sqlite-based OpenData (http://www.geopackage.org/) format used as a filebased spatial personal database.
But there is no native 'geopackage' connection possible, and we cannot view the geometries in it (like we do in Postgis) :-)
You CAN open a Geopackage file (*.gpkg) using the sqlite driver, but there is no 'spatial' knowledge in it.

**Describe the solution you'd like**
It would be supercool to be able to handle a Geopackage file just like a Postgis database, so: create a connection to it, fire some queries (maybe some triggers to automagically do some metadata registration).
And a spatial data viewer tab in the data tab would be supercool too

**Describe alternatives you've considered**
You can open geopackages using gdal-based tools (like QGIS (qgis.org)). But given I manage most of my databases (Postgis, Oracle etc) with DBeaver it would be nice if there is some 'native' driver

**Additional context**
Attached a Geopackage file (crs: EPSG:28992, Dutch National coordinate system) with 3 layer (point, line, polygon) create with QGIS (by 'exporting' some old data to the aa.gpkg)

If you need more information, feel free to contact me.

[nl.zip](https://github.com/dbeaver/dbeaver/files/5070852/nl.zip)

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion

**Comment by ShadelessFox** [comment]
Basic support for GeoPackage was added:
![java_N2VBDvnbuo](https://user-images.githubusercontent.com/35821147/105096620-67fc4380-5ab8-11eb-9ea4-fed1bd0ddae2.png)

**Comment by uslss** [comment]
verified

**Comment by uslss** [comment]
verified
