### ISSUE TITLE
self referencing tables

### ISSUE THREAD

**Issue by EHornburg** [dbeaver/dbeaver#9530]
#### System information: 
- windows Enterprise 10
- DBeaver Enterprise 7.1

#### Connection specification:
- SQL Server 2016
#### Describe your question:
Hello

I’m testing your DBeaver enterprise Edition.

I have a question.
The table SBL has self referencing
-	SBL.GRUND_ID = SBL.SBL_ID
-	And SBL.UESBL_ID = SBL.SBL_ID
What is here wrong?
 
![image](https://user-images.githubusercontent.com/61511135/90225968-8c216d80-de12-11ea-8353-05bd9af62671.png)

i get this error:
![image](https://user-images.githubusercontent.com/61511135/90226087-c12dc000-de12-11ea-8360-c3c43b22d6a9.png)

**Comment by kseniiaguzeeva** [comment]
Error shows that there is an SQL Error in the statement. Could you please write this query as a text?

**Comment by EHornburg** [comment]
oohh sorry,
i lost the "S" in the select!
i have looked 1000 times over the sql, but i don't have seen it.

In my first try - with the "S" so it looks in the screenshot - i get the error.
then i copy paste the command in an other sql tool and then i see the missing "S".
After i corrcet it in DBeaver, the sql run ok!
sorry!!!!

**Comment by kseniiaguzeeva** [comment]
I'm glad you've found the reason!
