### ISSUE TITLE
Exporting data as SQL creates incorrect single quote escapes

### ISSUE THREAD

**Issue by cpuritscher** [dbeaver/dbeaver#9532]
#### System information: 
- Windows 10
- DBeaver 7.1.4

#### Connection specification:
- DB2 10.2
- Driver: DB2 LUW

#### Describe the problem you're observing:
Exporting data as SQL produces incorrect quotes if content of field starts/ends with a single quote '

#### Steps to reproduce, if exist:
CREATE TABLE qtest (field1 varchar(50));
INSERT INTO qtest (field1) VALUES ('''this is quoted''');
SELECT * FROM qtest;
![grafik](https://user-images.githubusercontent.com/67310095/90237704-00650c80-de25-11ea-97b9-d7292a118a8f.png)

Then rightclick table qtest, export data, export as sql, will produce the incorrect sql statment:
INSERT INTO QTEST (FIELD1) VALUES (''this is quoted'');
;

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
