### ISSUE TITLE
Hide invisible properties form lists and form editors

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#9535]
W need to hide properties (@Propertry(visibleIf = ...)) from entity form editor and from object lists.

**Comment by LonwoLonwo** [comment]
this should work for: 

Check constraint expression column - visible if MySQL version at least 8.0/ MariaDB version at least 10.2 + information schema has check_constraint table

Checkbox "Has oids" column - Table editor tab, Postgres - visible if Postgres version < 12

**Comment by uslss** [comment]
verified
