### ISSUE TITLE
Import from CSV: NPE appears when a column is skipped in tables mapping

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9537]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.5 EA

#### Describe the problem you're observing:
Import from CSV: NPE appears when a column is skipped in tables mapping
#### Steps to reproduce, if exist:
1. Export CSV file (e.g. MySQL.Kseniia.Export)
2. Open import wizard for a table via DB Navigator context menu (e.g. MySQL.Kseniia.Export)
3. Select CSV
4. Select the exported CSV file
5. Press Columns and skip a column in Table mapping step
6. Press Preview

Actual result: NPE appears
![dbeaver_AX8PRhGckd](https://user-images.githubusercontent.com/51405061/90245380-3b723a80-de3b-11ea-8a50-baa4bdc3d2df.png)
[.log](https://github.com/dbeaver/dbeaver/files/5074340/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5074341/dbeaver-debug.log)

[Export_202008141426.txt](https://github.com/dbeaver/dbeaver/files/5074359/Export_202008141426.txt)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
