### ISSUE TITLE
PostgreSQL: update table size on table refresh (and F5)

### ISSUE THREAD

**Issue by KuznetsovaNV** [dbeaver/dbeaver#9538]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro
- DBeaver version: 7.1.4
- Additional extensions: no

#### Connection specification:
- Database name and version: PostgreSQL 11.5
- Driver name: PostgreSQL JDBC Driver
- Do not use tunnels or proxies (SSH, SOCKS, etc).

#### Describe the problem you're observing:
Target table size (Object size on disk) could be updated only by refreshing all "Tables" or "Schema". Refresh on target table doesn't update target table size.
#### Steps to reproduce, if exist:
Right-click on target table => Refresh. Object size on disk for target table is the same.
F5 with selected target table or label "Tables", also label Schema name doesn't update target table size.
Right-click on label "Tables" => Refresh. Object size on disk for all tables (also target) updated.
Right-click on label with Schema name => Refresh. Object size on disk for all tables (also target) updated.
#### Include any warning/errors/backtraces from the logs
Error log is empty.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
Table Size disappears after table refresh.

**Comment by serge-rider** [comment]
Schema stats refresh added

**Comment by uslss** [comment]
verified
