### ISSUE TITLE
Import task (to not-existing table) is saved as Export task

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9539]
#### System information: 
- Operating system (distribution) and version win 10x64
- DBeaver version 7.1.5 EA

#### Describe the problem you're observing:
Import task (to not-existing table) is saved as Export task
#### Steps to reproduce, if exist:
1. Start import to non-existing table from csv
2. Provide all needed settings. 
3. At last step choose 'Save Task' - Task is saved as Export task
Note: works ok for import to existing table

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
