### ISSUE TITLE
No notification appears in case not all source files were chosen

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9540]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.5 EA

#### Describe the problem you're observing:
No notification appears in case not all source files were chosen - it is possible to switch to the next settings page, but export isn't possible
#### Steps to reproduce, if exist:
1. Choose more than 1 table and start import from CSV
1. Choose source for the first table (Browse dialog appears once only - no matter how many table is chosen)
1. Switch to the Next page, mape all the columns - Next button is greyed out, import isn't possible
![2020-08-14_15h35_07](https://user-images.githubusercontent.com/31996417/90250128-467d9880-de44-11ea-8293-656c5b23197a.gif)

**Comment by akilovich** [comment]
Fixed.

**Comment by uslss** [comment]
verified
