### ISSUE TITLE
Mapping is always unspecified when trying to import Data

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9541]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.5 EA

#### Steps to reproduce, if exist:
1. Choose some table and export it to CSV
1. Choose the same table and begin import
1. As source file choose CSV that was created at step 1. (columns are similar, no changes were made in target table structure)
1. Go to mapping page - all columns are unspecified. Seems they should had Existing state

![2020-08-14_15h41_37](https://user-images.githubusercontent.com/31996417/90250694-21d5f080-de45-11ea-9fbe-f1dd2d0513ae.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
