### ISSUE TITLE
Import task: impossible to import to 2 tables from 1 source

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9542]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.5 EA

#### Describe the problem you're observing:
Import task: impossible to import to 2 tables from 1 source
#### Steps to reproduce, if exist:
1. Create an import task
2. Select 2 tables for import
3. Select a type
4. Select one source and Press Next

Actual result:
One table name is select twice for import.
![OFLRRhy9ZX](https://user-images.githubusercontent.com/51405061/90251903-3b783780-de47-11ea-872a-b33f66b0270c.gif)

**Comment by serge-rider** [comment]
It is not clear how did you come to the first screen (when the same table mentioned twice in the source column).

**Comment by kseniiaguzeeva** [comment]
Cannot be reproduced anymore
