### ISSUE TITLE
Import: some CSV settings are not respected

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9544]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.5 EA

#### Describe the problem you're observing:
some CSV settings are not respected during import
#### Steps to reproduce, if exist:
Precondition:
Export table as CSV with following conditions:
-an empty cell exists
-a column of date format exists
import setting: Header position= both

Steps:
1. Open import wizard for a table via context menu of DB Navigator
2. Select CSV 
3. Select the exported file
4. Select Header position **both** in Importer settings
5. Enter a NULL value mark
6. Change date/time format
7. Select target table in the next step
8. Press Preview

Actual result:
1. The column names are displayed in the top and bottom of the columns
2. NULL value is not replaced
3. Date/Time format is not applied according import settings

**Comment by noom073** [comment]
Dbeaver 7.1.5 problem 
Fix it please my problem failure to import.
- my csv not specify field name but I order data by column

Result
- Dbeaver has create new column by number of column data and have no data in table

**Comment by LonwoLonwo** [comment]
@noom073 hello. please tell me - the header position in the import settings has been changed for your file?
![2020-08-18 10_36_55-Data Transfer](https://user-images.githubusercontent.com/45152336/90484642-22210500-e13f-11ea-8596-f98059227b4e.png)

**Comment by noom073** [comment]
@LonwoLonwo 
Yep
![1](https://user-images.githubusercontent.com/54969096/90506112-f2452200-e17d-11ea-9a5d-67491467688d.png)
then
![2](https://user-images.githubusercontent.com/54969096/90506119-f4a77c00-e17d-11ea-93ba-62284ca6fecd.png)

**Comment by noom073** [comment]
Yep
![1](https://user-images.githubusercontent.com/54969096/90506223-186ac200-e17e-11ea-9b2c-61b37bbfd6d1.png)
Then
![2](https://user-images.githubusercontent.com/54969096/90506243-1d2f7600-e17e-11ea-9921-12847281a58a.png)

**Comment by noom073** [comment]
> 
> 
> @noom073 hello. please tell me - the header position in the import settings has been changed for your file?
> ![2020-08-18 10_36_55-Data Transfer](https://user-images.githubusercontent.com/45152336/90484642-22210500-e13f-11ea-8596-f98059227b4e.png)

@LonwoLonwo 
Yep
![1](https://user-images.githubusercontent.com/54969096/90506320-3d5f3500-e17e-11ea-9862-90868a268cd6.png)
And then I next
![2](https://user-images.githubusercontent.com/54969096/90506359-54058c00-e17e-11ea-8976-4596ea2fa57e.png)

**Comment by noom073** [comment]
> 
> 
> @noom073 hello. please tell me - the header position in the import settings has been changed for your file?
> ![2020-08-18 10_36_55-Data Transfer](https://user-images.githubusercontent.com/45152336/90484642-22210500-e13f-11ea-8596-f98059227b4e.png)

Yep
![1](https://user-images.githubusercontent.com/54969096/90506538-a3e45300-e17e-11ea-933e-ed3248f9dd81.png)
And then I next
![2](https://user-images.githubusercontent.com/54969096/90506549-aba3f780-e17e-11ea-853e-89aa8edef89c.png)

**Comment by LonwoLonwo** [comment]
@noom073 have you specified the name of the table or imported into a new one? do you want to create new columns or import into existing ones? And maybe you can send an example of your csv file?

**Comment by noom073** [comment]
Table is existing, name is pre, MySql
example data:
![1597750019128](https://user-images.githubusercontent.com/54969096/90507675-7a2c2b80-e180-11ea-95e1-6613f020fde6.jpg)

**Comment by noom073** [comment]
Structure:
![1597750167855](https://user-images.githubusercontent.com/54969096/90507860-cd05e300-e180-11ea-926b-09fc80bd1c32.jpg)

**Comment by LonwoLonwo** [comment]
@noom073 and what about columns? you specified column names? Ore do you want to create new columns?

**Comment by noom073** [comment]
Thanks for responding @LonwoLonwo 
I want to insert record from csv file, not insert with create new column.
Thank you again.

**Comment by noom073** [comment]
@LonwoLonwo 
I apologize, I found solution to manage it
: It need to specify target column for data from csv 
![1597828040778](https://user-images.githubusercontent.com/54969096/90615793-c76ad480-e236-11ea-9960-20c561580a9a.jpg)

Some question, How to set auto specify target column in table, arrange from csv file?

**Comment by noom073** [comment]
@LonwoLonwo 
I don't worry if it can't cause I had practice to fix it.
Thank you again.

**Comment by LonwoLonwo** [comment]
@noom073 

> Some question, How to set auto specify target column in table, arrange from csv file?

When .csv import file have header, Then column names mapping automatic. 
there are no other automatic methods yet, unfortunately

**Comment by noom073** [comment]
@LonwoLonwo 
Thank you.

**Comment by serge-rider** [comment]
Option "both" will be removed from CSV import settings (as CSV parser doesn't support rows prefetch). 
And it is a really rare case and can be easily fixed before import.

Can't reproduce problem with NULL mark.

**Comment by serge-rider** [comment]
Problem with date formatting was fixed in #8669

**Comment by kseniiaguzeeva** [comment]
**A** both - ok, will wait for removing
**B** Null - 
1. please try to import enc file in table MySQL.Kseniia.Export_to3
2. set any value in Null value mark
![dbeaver_SypI9quHc7](https://user-images.githubusercontent.com/51405061/91071080-6715d180-e640-11ea-94ad-8d5a9b89d955.png)
3. import
Actual result: Null value is not replaced by value from Import settings
Expected: Null value is replaced  by value from Import 

**C** date formatting - still can reproduce. Steps
1. Truncate table MySQL.Kseniia.Export_to3
2. open import wizard for the table
3. select CSV and select the enc file
4. set data formatting different from the selected file (e.g. dd-MM-yyyy[ HH:mm:ss[.SSS]])
5. Import

Actual result: set timestamp from import settings is not applied
Expected: the timestamp changes are applied
![tucfJtRueF](https://user-images.githubusercontent.com/51405061/91072744-9e857d80-e642-11ea-8cc0-140c039d3046.gif)

[Export_to3_202008241918.txt](https://github.com/dbeaver/dbeaver/files/5119166/Export_to3_202008241918.txt)

**Comment by kseniiaguzeeva** [comment]
It would be very helpful to add a detailed description to Date/time format popup. Thank you in advance.

**Comment by kseniiaguzeeva** [comment]
Verified
