### ISSUE TITLE
How to move results panel toolbars?

### ISSUE THREAD

**Issue by Simbi0z** [dbeaver/dbeaver#9546]
#### System information: 
- Operating system (distribution) and version: Archlinux
- DBeaver version: 7.1.4

#### Connection specification:
- Database name and version: Microsoft SQL Server 2019 (RTM-CU5) (KB4552255) - 15.0.4043.16 (X64) 

#### Describe your question:
Can't move the toolbars in the results panel.
![20200816-005539](https://user-images.githubusercontent.com/15280980/90326902-2a6d1a80-df5c-11ea-901c-93eef96a2358.jpg)

**Comment by Simbi0z** [comment]
any update status on this?

**Comment by E1izabeth** [comment]
We implemented toolbar customization, so now you can set up which buttons should be visible.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/80a9cb6c-ad2c-4cc5-8f32-051e37758143)

Please, let me know if it solve your issue.

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still actual for you - feel free to reopen it.
