### ISSUE TITLE
Schema properties editor: Delete btn for view becomes inactive in special cases

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9547]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.5 EA

#### Describe the problem you're observing:
Schema properties editor: Delete btn for view becomes inactive after a view is opened
#### Steps to reproduce, if exist:
1. Open View tab of Schema Properties Editor
2. Open a view
3. Go back to View tab of Schema Properties Editor

Actual result: Delete btn becomes inactive in the bottom toolbar
![dbeaver_CRZSYt8SKC](https://user-images.githubusercontent.com/51405061/90329436-8ad87800-dfad-11ea-9e0d-c5c0f0a63468.png)

**Comment by serge-rider** [comment]
Need more details

**Comment by kseniiaguzeeva** [comment]
Cannot be reproduced anymore
