### ISSUE TITLE
NPE appears after editing materialized view comment

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9548]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.5 EA

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
NPE appears after editing materialized view comment
#### Steps to reproduce, if exist:
1. Open a materialized view
2. Edit a comment

Actual result: NPE appears after saving the edited comment
![dbeaver_tkj0mIPjCp](https://user-images.githubusercontent.com/51405061/90329635-3e8e3780-dfaf-11ea-9b76-ff85c9d64d2b.png)

**Comment by uslss** [comment]
verified
