### ISSUE TITLE
Sequence cannot be created if a table with the same name exists

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9549]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.5 EA
- Additional extensions

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
Sequence cannot be created if a table with the same name exists
#### Steps to reproduce, if exist:
Crerate a sequence using a name of a table from the same schema

Actual result: Error appears 
![dbeaver_AfmwoVBGJJ](https://user-images.githubusercontent.com/51405061/90329848-b14be280-dfb0-11ea-92e8-4cdd1f47ab92.png)

**Comment by p91paul** [comment]
well that's correct, you can't have 2 objects with the same name in the same schema on Oracle

**Comment by kseniiaguzeeva** [comment]
You are right, thank you! It is one of Oracle rules: https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements008.html
