### ISSUE TITLE
Firebird export data as update or insert sql statements

### ISSUE THREAD

**Issue by tJeyhun** [dbeaver/dbeaver#9551]
Since Firebird 2.1 there is support for `update or insert` statements

https://firebirdsql.org/refdocs/langrefupd21-update-or-insert.html

**Comment by kseniiaguzeeva** [comment]
Thank you for the information!

**Comment by LonwoLonwo** [comment]
Added in 7.2.3 
Specifically for this ticket: set in Data transfer settings field "Insert keyword" in "UPDATE OR", to get the output value like:
"UPDATE OR INSERT INTO test.some_table_name (some columns) VALUES (some values);"
![2020-10-05 12_44_04-Window](https://user-images.githubusercontent.com/45152336/95065389-a76d7280-0709-11eb-9bc6-a54b4cd0069f.png)

**Comment by LonwoLonwo** [comment]
In other cases. 
Keyword "INSERT INTO" can be changed on "UPSERT INTO", then choosing "UPSERT INTO" in field "Insert keyword".
Ore you can choose in field "Insert keyword" "ON CONFLICT" or "ON DUPLICATE" and set something in field "On conflict expression", to get an expression like;
"INSERT INTO test.some_table_name (some columns) VALUES (some values) ON DUPLICATE KEY UPDATE "the expression you entered";"

**Comment by kseniiaguzeeva** [comment]
implemented
