### ISSUE TITLE
Preferences rework

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#9552]
We have a lot of preferences.
And Eclipse platform has a lot of preferences. Now they are separated and it is confusing (unless you are an Eclipse user).

We need to merge them.

Also we need to move data editor and SQL execution prefs to a more easy accessible places.

**Comment by LonwoLonwo** [comment]
Now preferences menu looks differently. And it is slightly different from Eclipse market version. 
"Object Editor" tab moved into "Database Editors".
More keywords to search inside preferences also added (Russian keywords too).

**Comment by kseniiaguzeeva** [comment]
1. Is it ok that menu tab names of Data Editor is slightly different in DB Navigator preferences and Object Editor preferences
![data_editor](https://user-images.githubusercontent.com/51405061/93357646-398c0480-f849-11ea-8c1f-d570faa1be05.png)
2. Is it ok that SQL Editor tab has different content in DB Navigator preferences and Object Editor preferences?
![sql_editor](https://user-images.githubusercontent.com/51405061/93358395-157cf300-f84a-11ea-8c37-582408432b91.png)

**Comment by kseniiaguzeeva** [comment]
verified
