### ISSUE TITLE
How to customize comand in Database navigator 

### ISSUE THREAD

**Issue by Mjp9119** [dbeaver/dbeaver#9554]
Hi !! I'm using Dbeaver 6.1.5 (great tool!) on Win10

My database is MySql 4.1 (legacy reasons)
I'm having a problem when click on "tables" at the Database navigator pane.

It arouses a mysql error saying "you have a mysql erro near...etc etc)
I found that the error could be caused by the command  SHOW FULL TABLES FROM...etc..etc
I thin mysql version 4.1 does not support the FULL clause in SHOW TABLES FROM so,

I wonder if I can customize this comand to remove the word FULL when clicking on "tables" in the navigator.
This way I would continue to use DBeaver as the rest of my needs are perfectly covered by this great tool even in excess

I hope I've made myself clear. 

Thank you 
Mauricio

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. I change the label on feature request.

**Comment by akilovich** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
The correct DDL is used now. But when I try to open in Data Editor a table, a column etc, Generate SQL, the error appears:
SQL Error [1146] [42S02]: Table 'information_schema.statistics' doesn't exist
  Table 'information_schema.statistics' doesn't exist
  Table 'information_schema.statistics' doesn't exist

Also a table cannot be created via UI (Error that SQL syntax is wrong appears, but the same statement can be executed via UI)

[.log](https://github.com/dbeaver/dbeaver/files/5292503/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5292506/dbeaver-debug.log)

**Comment by akilovich** [comment]
Hi, @Mjp9119. As far as I understand, you're using MySQL 5 driver. After some consideration, we've concluded that the best solution for you would be to use our MySQL (Old) driver:

![mysql-old](https://user-images.githubusercontent.com/26031301/94449745-1d775400-01b5-11eb-90c9-cde9a35665e8.png)

**Comment by akilovich** [comment]
Changed the description of our MySQL 5 driver.

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by Mjp9119** [comment]
Hey, Thanks Nikita!!
You people are awsome!!

Just one question
Where can I get that mysql (old) driver ?
I´ve tried to find (on the internet) some mysql connector for mysql 4.1 but had no success

My options when acreating a new connection looks like this (DBeaver version 7.2.1)
(sorry if this question is to silly)
[cid:41fdb732-2c77-4844-a47d-3c3bd2c1b2c0]
________________________________
De: Nikita Akilov <notifications@github.com>
Enviado: lunes, 28 de septiembre de 2020 12:06
Para: dbeaver/dbeaver <dbeaver@noreply.github.com>
Cc: Mjp9119 <mjp9119@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [dbeaver/dbeaver] How to customize comand in Database navigator (#9554)


Hi, @Mjp9119<https://github.com/Mjp9119>. As far as I understand, you're using MySQL 5 driver. After some consideration, we've concluded that the best solution for you would be to use our MySQL (Old) driver:

[mysql-old]<https://user-images.githubusercontent.com/26031301/94449745-1d775400-01b5-11eb-90c9-cde9a35665e8.png>

**Comment by akilovich** [comment]
Hey, @Mjp9119. Thank you for your kind words. In order to use the old driver, create a brand new connection to your database. When you do that, a window like in my comment above will pop up where you can choose MySQL (old) driver.

**Comment by Mjp9119** [comment]
Thanks Nikita , but when iI do that, the "old" mysql driver doesn't show (I've sent a screen capture on my previous mail)
It only shows Mysql 5

thanks!
________________________________
De: Nikita Akilov <notifications@github.com>
Enviado: martes, 29 de septiembre de 2020 09:51
Para: dbeaver/dbeaver <dbeaver@noreply.github.com>
Cc: Mjp9119 <mjp9119@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [dbeaver/dbeaver] How to customize comand in Database navigator (#9554)


Hey, @Mjp9119<https://github.com/Mjp9119>. Thank you for your kind words. In order to use the old driver, create a brand new connection to your database. When you do that, a window like in my comment above will pop up where you can choose MySQL (old) driver.

**Comment by akilovich** [comment]
@Mjp9119 Try to update to the latest version of DBeaver.

**Comment by Mjp9119** [comment]
Thanks!!
This  is what DBeaver shows under Help->Credits:
Version7.2.1.202009201907
Release date: September 21st. 2020
C. 2020 JKISS project

I found the MySql (old) Driver!!
I've created a new connection with it and then it seems to download some new conector, I guess,
But after that, this message shows :
 CLIENT_PLUGIN_AUTH is required
I´ll google it



________________________________
De: Nikita Akilov <notifications@github.com>
Enviado: martes, 29 de septiembre de 2020 10:57
Para: dbeaver/dbeaver <dbeaver@noreply.github.com>
Cc: Mjp9119 <mjp9119@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [dbeaver/dbeaver] How to customize comand in Database navigator (#9554)


@Mjp9119<https://github.com/Mjp9119> Try to update to the latest version of DBeaver.

**Comment by kseniiaguzeeva** [comment]
It seems you should change a driver version. For this:
1. Click the database in DB Navigator and press F4
2. Press Edit Driber Settings in Main tab of Connection Settings
3. Press Download/Update
4. Select older version e.g. 3.1.14
5. Press Download
6. Press Ok
7. Reconnect

**Comment by Mjp9119** [comment]
Hi and thanks Kseniia!!
Did all that, but after downloading (even using the force option), when I try to connect
a little window pops up sayin exactly this message " CLIENT_PLUGIN_AUTH is required"

I'm using DBevaer 7.2.1 on Win 10 connecting to a mysql server ver .4.1.18(for legacy reasons)

In the Edit window for the driver the title is "Edit driver MySQL(Old)"
same window in the description section,  ID is "mysql3"
same window same section, Description is "Driver for MySQL (4.x and earlier)"

After clicking on Download /Update window shows :
"Files required by Driver"
     FILE: mysql:mysql-connector-java:RELEASE    VERSION:8.0.21    DESCRIPTION: JDBC Type 4 driver for MySQL

beneath that line indented it shows:
              com.google.protobuf:protobuf-java:3.11.4  VERSION:3.11.4 DECRIPTION: Core Protocol Buffers Library.....

I´ve force download this, close  the connection deletd it added a new one specifying this driver again , close DBevaer reopening repeating all this
But the same message keeps poping

Would it have some relation with the authentication protocol of mysql ? I read some time ago that it changed on this version ?
Anyway, my root user for mysql has NO password .

Any help greatly appreciated
Cheers!!


________________________________
De: Kseniia <notifications@github.com>
Enviado: jueves, 1 de octubre de 2020 07:08
Para: dbeaver/dbeaver <dbeaver@noreply.github.com>
Cc: Mjp9119 <mjp9119@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [dbeaver/dbeaver] How to customize comand in Database navigator (#9554)


It seems you should change a driver version. For this:

  1.  Click the database in DB Navigator and press F4
  2.  Press Edit Driber Settings in Main tab of Connection Settings
  3.  Press Download/Update
  4.  Select older version e.g. 3.1.14
  5.  Press Download
  6.  Press Ok
  7.  Reconnect

**Comment by kseniiaguzeeva** [comment]
Please change VERSION:8.0.21 on 3.11.4 
![xDIlW3dOB0](https://user-images.githubusercontent.com/51405061/95078920-8f541e00-071e-11eb-8592-9dc6bf5c93d2.gif)

**Comment by Mjp9119** [comment]
Great!!
Thank you sooo much!!
And again congratulations for this great software

Best regards
Mauricio
________________________________
De: Kseniia <notifications@github.com>
Enviado: lunes, 5 de octubre de 2020 09:22
Para: dbeaver/dbeaver <dbeaver@noreply.github.com>
Cc: Mjp9119 <mjp9119@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [dbeaver/dbeaver] How to customize comand in Database navigator (#9554)


Please change VERSION:8.0.21 on 3.11.4
[xDIlW3dOB0]<https://user-images.githubusercontent.com/51405061/95078920-8f541e00-071e-11eb-8592-9dc6bf5c93d2.gif>
