### ISSUE TITLE
Snowflake - invalid current schema

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#9559]
When you set a schema in the connection page it is ignored after connection instantiation.
Moreover SELECT CURRENT_SCHEMA() returns PUBLIC instead of real schema name.

**Comment by jsteinfort** [comment]
I have 7.1.5 installed.  `select current_schema()` works fine for me.

**Comment by akilovich** [comment]
Fixed the issue, although the selected schema still is not highlighted in the database navigator. We've decided to leave it this way until the better times come.

**Comment by uslss** [comment]
verified
