### ISSUE TITLE
no sub-nodes displayed; how to filter databases now?

### ISSUE THREAD

**Issue by nitwhiz** [dbeaver/dbeaver#9562]
#### System information: 

- Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- 7.1.4.202008021649

#### Connection specification:

- MySQL 8 and MySQL (old)
- SSH Tunnel via keyfile

#### Describe the problem you're observing:

The Sub-Nodes (Databases, Users, ...) are not displayed when connecting to a remote server, therefore it's impossible to filter by database name. They are displayed if the connection is localhost, untunneled.

#### Steps to reproduce, if exist:

- Have a mysql database connection setup

**Comment by kseniiaguzeeva** [comment]
Please check whether any data is entered in 
-DB Navigator filter line;
-Database filter.
![dbeaver_sQvNpES4g1](https://user-images.githubusercontent.com/51405061/90605879-a3dc6580-e207-11ea-8fdd-640b4ad673d2.png)

**Comment by nitwhiz** [comment]
@kseniiaguzeeva both are empty.

The problem is, that this "Databases" sub-folder is not displayed at all. In "[live]" I've got one open connection, you see it directly lists it's databases. But in "[local]" it's how I want it, "Databases", "Users", ... is displayed, too. Do they depend on any server-side rights for my user logged in?

![dbeaver](https://user-images.githubusercontent.com/6342866/90616244-7d212d80-e20d-11ea-98ab-090a5a01f0be.png)

The "environments" (dev/live/local) have the same view settings.

**Comment by kseniiaguzeeva** [comment]
I think you have **Simple** Navigator view setting. Please change it to **Advanced**:
Connection Settings>General (or via Database context menu)
![dbeaver_d9HbF2RH7Y](https://user-images.githubusercontent.com/51405061/90618448-b1e6b200-e218-11ea-8e1b-a48650b9ac32.png)
The ticket to have possibily to configure filters in Simple view is already exists: https://github.com/dbeaver/dbeaver/issues/9048.

**Comment by nitwhiz** [comment]
Sadly not, all my connections are set to Advanced. I guessed this was the problem, too and tried all the views. I did not customize anything in there, too.

**Comment by kseniiaguzeeva** [comment]
Please send me a screenshot of Advanced Navigator view settings.
![mstsc_VnAPsLs1Nx](https://user-images.githubusercontent.com/51405061/90623540-46eca980-e21f-11ea-9e53-b1ea6d63c363.png)

**Comment by nitwhiz** [comment]
same as yours

![image](https://user-images.githubusercontent.com/6342866/90630237-f2e2c480-e220-11ea-9c48-0e977102debd.png)

**Comment by nitwhiz** [comment]
I re-created the connection, did not help :/

**Comment by kseniiaguzeeva** [comment]
which driver did you select?

**Comment by nitwhiz** [comment]
MySQL (Old). Switched to MySQL and back to MySQL (Old) again, no change

**Comment by kseniiaguzeeva** [comment]
Please try to create new connection for MySQL 8+

**Comment by uslss** [comment]
@nitwhiz probably you could try to filter database in connection properties. Please, write back if it helps or not
![image](https://user-images.githubusercontent.com/31996417/92723677-14dbec80-f372-11ea-99bd-ea5012312d64.png)

**Comment by nitwhiz** [comment]
I'm sorry for not reporting back! Holidays and stuff, and I totally forgot about this.

I just deleted all connections, updated DBeaver to the latest version and it seems to work now. @uslss I made sure, it's not those filters.

No clue what went wrong, but it works again and I can continue working with beaver :)

Thanks!
