### ISSUE TITLE
Oracle: Error getting view definition from system package

### ISSUE THREAD

**Issue by SP3NGL3R** [dbeaver/dbeaver#9564]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: Community 7.1.5
- Additional extensions: Java JRE 1.8.0_261

#### Connection specification:
- Database name and version: Oracle 12c
- Driver name: Instant Client 12.1 with TNSnames
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Cannot view DDL of another user's views, worked in v7.1.3 and stopped working in v7.1.4

#### Steps to reproduce, if exist:
Login to Oracle as User1 and try to view the DDL of a view in User2

#### Include any warning/errors/backtraces from the logs
Event Details:
Severity:

> Warning

Message:
Error getting 

> view definition from system package

Exception Stack Track:

> An exception stack trace is not available.

Session Data:
eclipse.bui

> ldId=unknown
> java.version=1.8.0_261
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
> Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by SP3NGL3R** [comment]
This does work though (if it helps):
SELECT TEXT
FROM all_views
WHERE VIEW_NAME  = 'MY_VIEW_NAME';

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
