### ISSUE TITLE
DBeaver: When editing an INTEGER value in a grid, the cell is not opened if start typing a minus or plus sign

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#9567]
DBeaver - **Version 7.1.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

When editing an INTEGER value in a grid, the cell is not opened if start typing a minus "-" or a plus "+", this workes if I enter a number "0".."9" instead.

The grid ought to set the INTEGER cell in edit mode not only when I press "0".."9" on the keyboard, pressing "+" or "-" ought to open the cell in edit mode too.

1) Create a test table and fill it with test data:

```
CREATE TABLE TestInteger (Id INTEGER, Value INTEGER);
GO

INSERT INTO TestInteger
VALUES (1, 10), (2, 20);
```

2) View the table data **TestInteger** in a grid.

3) Click on the 1st row **Value** column (with the value of 10).

4) Press number "5" on the keyboard.

5) The cell is changed to edit mode. This is **OK**.

6) Click on the 2nd row **Value** column (with the value of 20).

7) Press **minus** sign (the "-" character) or the **plus** sign (the "+" character) on the keyboard. 

8) Nothing happens. This is an **ERROR**.

My guess is that the "-" and the "+" character should be added to characters that change the grid cell into edit mode.

**Comment by uslss** [comment]
`thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
**+** still doesn't change int cell in edit mode

**Comment by serge-rider** [comment]
Keypad buttons handle was added

**Comment by kseniiaguzeeva** [comment]
verified
