### ISSUE TITLE
DBeaver FR: Show HTML table column names even if unchecking the OUTPUT TABLE HEADER setting

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#9568]
DBeaver - **Version 7.1.4 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

When I tested to uncheck the **Export to HTML** setting **Output table header** I loose the header with column header (the column name) too.

I wanted only that the table name header shoudl be removed (and the column name header kept intact).

See issue #8058

**Comment by uslss** [comment]
verified
