### ISSUE TITLE
Make new Snowflake dialect formatting for $$ sections configurable/optional

### ISSUE THREAD

**Issue by jsteinfort** [dbeaver/dbeaver#9569]
**Is your feature request related to a problem? Please describe.**
Reference:  7.1.5 Release - Snowflake: SQL dialect support was fixed ($$ comments)

The new SQL formatting for the Snowflake dialect makes everything within a pair of "$$" delimiters into a comment.  As such it is all one color and has no highlighting.

This code within the "$$" delimiters is actually Javascript in the case of a Stored Procedure.

At the very least, the code within these delimiters should be treated as Javascript and be formatted accordingly.

**Describe the solution you'd like**
Make the formatting within the "$$" delimiters configurable in some way.  At a minimum, a checkbox to revert to the old behavior.  Ideally, I should be able to get the previous formatting back.

**Describe alternatives you've considered**
I looked through the preferences, but it isn't apparent to me if I can revert this formatting.
Should I use a different tool when editing Stored Procedures?  That seems unfortunate.

**Additional context**
I commonly use multi-line Strings in my Stored Procedures for the SQL.  This makes it very readable and in many cases _executable_ with a highlight + a `"control-enter"` command.  These strings used to be nicely formatted.  Now they are all the same color.  This makes them harder to read.

If I'm missing something, I'd be happy to withdraw this request.

**Comment by jsteinfort** [comment]
This issue appears to be fixed now.

**Comment by ShadelessFox** [comment]
Implemented. Now you can configure it under connection settings:

![java_j67AgaMUyf](https://user-images.githubusercontent.com/35821147/123245210-4848cb80-d4ed-11eb-8fd4-2183cc227f67.png)

**Comment by Matvey16** [comment]
Verified

**Comment by jsteinfort** [comment]
Excellent! Confirmed functionality (sorry been on vacation).  Thank you so much for implementing.  :-)
