### ISSUE TITLE
Schema/objects compare should produce DDL

### ISSUE THREAD

**Issue by allanlaal** [dbeaver/dbeaver#957]
right now it creates a pretty HTML report, but it would be much more useful if I could specify which table/database is the source and which is the target and then be presented with a series of CREATE/DROP/UPDATE/ADD INDEX etc.. SQL commands to bring target into the same state as source

**Comment by serge-rider** [comment]
Agreed.
I'm working on this task but as it requires pretty much changes in model/extensions it doesn't go fast..

**Comment by allanlaal** [comment]
it would be very cool if one could review all the commands to be executed and tick checkboxes on individual logical blocks of code to be executed or not. All checkboxes unchecked by default with a Select All button :)

**Comment by serge-rider** [comment]
We going to implement this in #3384 by using Liquibase.
Making such feature differently for different databases is too heavy, as I think.
Thanks for link anyway, will check how they do this.

**Comment by tati-kru** [comment]
@ottopic, unfortunately, we have moved it again. We remember about this feature but do not have enough resources now. 

Maybe, someone would like to help? We are ready to assist. Otherwise, it will not be closed at least until 6.1.

**Comment by serge-rider** [comment]
This feature will be added in 6.1. 
It will support compare of different databases - whole schemas or individual tables.

Initially it will be available in EE version only.

**Comment by scruel** [comment]
> 
> 
> This feature will be added in 6.1. It will support compare of different databases - whole schemas or individual tables.
> 
> Initially it will be available in EE version only.

Would you release this function in CE version? We truly need it!
