### ISSUE TITLE
New table size column

### ISSUE THREAD

**Issue by GeriZ** [dbeaver/dbeaver#9570]
#### System information: 
- Windows 2016
- 7.1.5

#### Connection specification:
- DB2 11.1 and DB2 11.5

#### Describe your question:

What means SHOW STATISTICS INFO exactly in PREFERENCES-NAVIGATOR? I've upgraded to 7.1.5 and suddenly the size of all  tables of a database will now be displayed in the navigator. This is a great feature but it takes up to 6 minutes for a multi TB database until the tablesize will be displayed. The problem is that during this time Dbeaver is not usable because it does not display the table names until the size of all tables has been calculated. DBeaver shows only "Loading.." during this time...

![grafik](https://user-images.githubusercontent.com/31589944/90490228-ab840780-e13e-11ea-80d1-0dbe92851862.png)

This option was already activated in 7.1.3 but the table size was not displayed. Which **other statistics** will I miss when I deactive this option in the preferences?

**Comment by uslss** [comment]
Hi @GeriZ ,
could you try to uncheck Show Statistics Info option in connection Context Menu?
![image](https://user-images.githubusercontent.com/31996417/90521160-edc73c00-e172-11ea-8a7b-b28a4c32eac2.png)

**Comment by GeriZ** [comment]
Hi uslss,

that works too. That is the same on connection level as this setting at global level:

![grafik](https://user-images.githubusercontent.com/31589944/90522849-7f7f7b00-e16c-11ea-8d9e-eb0f41c08739.png)

Do I miss other statistics except the table size when I turn them off?

To display the tablesize is a good feature but it would be better be to calculate it asynchronously in the background if this is possible. 6 minutes wait time before the tables will be shown is exhausting in a big database ;-)))

**Comment by uslss** [comment]
seems that issue would be solved in #9572 
close this issue as duplicate.
best regards :)
