### ISSUE TITLE
How can I pass a variable (a-la psql -v) in the DB connect setup ?

### ISSUE THREAD

**Issue by dfgpg** [dbeaver/dbeaver#9571]
- Red Hat Enterprise Linux Server release 7.7 (Maipo)
- DBeaver ver 7.1.5
- postgresql-9.6.7

When connecting to my postgres DB via the linux command line, I can use -v to pass a parameter to the server.  I do not see how to do this in DBeaver.  Is there a way ?

**Comment by kseniiaguzeeva** [comment]
Have you tried to use Shell Commands option (Connection Settings>Shell Commands)?

**Comment by dfgpg** [comment]
I saw that but what shell command could I add which would pass a parameter from client to server ?
In good-ole psql, they have the -v variable which seems to work for this...
psql -h <host name> -U <user name> -v sysinfo.osuser=$USER <dbname>
So $USER is pulled from the linux env when the command is run, it gets passed along via that vehicle, and I get it on the server end.  But is there accommodation for that sort of thing in DBeaver ?
