### ISSUE TITLE
Instructions requested for TLS enabling an MS SQL Server connection

### ISSUE THREAD

**Issue by jsimone-infoarmor** [dbeaver/dbeaver#9573]
#### System information: 
- macOS 10.15.6
- DBeaver version 7.1.5

#### Connection specification:
- MS SQL Server 
Microsoft SQL Server 14.00.3223
Microsoft SQL Server 2017 (RTM-CU16) (KB4508218) - 14.0.3223.3 (X64) 
	Jul 12 2019 17:43:08 
	Copyright (C) 2017 Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

#### Describe your question:
Given the database connection for MS SQL Server has been encrypted with TLS 1.2 how can we configure DBeaver to connect?  Instructions would be greatly appreciated.

[MS SQL Server documentation](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver15)

**Comment by uslss** [comment]
@jsimone-infoarmor 
we've got no instruction especially for that type of server. Did you try to connect as to the usual server? 

btw, some special settings could be founded there https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-with-ssl-encryption?view=sql-server-ver15
you could try to change some settings in driver properties (e.g. encrypt, trustServerCertificate to true)
![image](https://user-images.githubusercontent.com/31996417/91547164-32e62d80-e92c-11ea-9e52-66b7199e32d1.png)

**Comment by jsimone-infoarmor** [comment]
ok, I can add those 2 driver properties there.  Where can I drop the cert used to authenticate the connection?

**Comment by jsimone-infoarmor** [comment]
setting encrypt=true and trustServerCertificate=false I get the following error when I test the connection:

```
tThe driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:0e812163-c864-4aaf-a274-d283e02c0d20
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    unable to find valid certification path to requested target
    unable to find valid certification path to requested target
```

where do I add the .pem file which represents the cert.  I tried to add to driver libraries as a file which did nothing.

**Comment by uslss** [comment]
verified

**Comment by ShadelessFox** [comment]
For now the only solution is to provide path to keystore (PFX/JKS) and its password along. Feel free to ask questions.
![image](https://user-images.githubusercontent.com/35821147/94797457-cd80d300-03e8-11eb-8c5a-d409bdff2dff.png)

**Comment by jsimone-infoarmor** [comment]
I am using 7.2.0 and there is no SSL tab.  Main/Driver Properties/SSH/Proxy ... that's all.
So how would one enter in the above information?

**Comment by ShadelessFox** [comment]
You need to upgrade DBeaver to the latest version.

> I am using 7.2.0 and there is no SSL tab. Main/Driver Properties/SSH/Proxy ... that's all.
> So how would one enter in the above information?

**Comment by jsimone-infoarmor** [comment]
i upgraded to 7.2.1 community edition and there is no SSL tab.

**Comment by ShadelessFox** [comment]
Sorry, this fix is included in the next release of product. 
If current solution with keystore is suitable for you, then you can setup it manually via **Driver properties**:
|Key|Value|
|-|-|
|encrypt|true|
|trustServerCertificate|false|
|trustStore|Keystore file (.pfx/.jks)|
|trustStorePassword|Keystore password|
|hostNameInCertificate|Certificate hostname|

**Comment by jsimone-infoarmor** [comment]
ok, let me give that a try.  thx.
