### ISSUE TITLE
Internal driver error   No enum constant org.jkiss.dbeaver.ext.greenplum.model.GreenplumExternalTable.FormatType.p   No enum constant org.jkiss.dbeaver.ext.greenplum.model.GreenplumExternalTable.FormatType.p

### ISSUE THREAD

**Issue by kruzewski** [dbeaver/dbeaver#9575]
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise Version:1809
- DBeaver version: Version 7.1.5.202008180601
- Java version: 1.8.0_131-b11
- Additional extensions

#### Connection specification:
- Database name and version: Greenplum Database 5.26.0
- Driver name: Greenplum
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: None

#### Describe the problem you're observing:

When attempting to browse specific schemas in the database navigator, dbeaver throws the error below:

Internal driver error
  No enum constant org.jkiss.dbeaver.ext.greenplum.model.GreenplumExternalTable.FormatType.p

![image](https://user-images.githubusercontent.com/1432488/90552009-2c073000-e160-11ea-8ad7-6731911376f6.png)

#### Steps to reproduce, if exist:

Open the specific schema again.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
