### ISSUE TITLE
DB connection error.

### ISSUE THREAD

**Issue by kimtaedoo** [dbeaver/dbeaver#9577]
#### System information: 
- Operating system (distribution) and version : Mac OS Catalina 10.15.5
- DBeaver version : 7.1.5
- Additional extensions : No

#### Connection specification:
- Database name and version : Amazon Aurora with PostgreSQL(DB engine 10.11)
- Driver name : PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  : I use SSH tunnel.

#### Describe the problem you're observing:
I update my DBeaver version to 7.1.5.
And I try connect to my project database.
But it connection error. 
Display message was 
> can't connect ot remote PostgreSQL server ERROR: permission denied for database rdsadmin ERROR: permission denied for database rdsadmin

I retry down grade DBeaver to ver.7.1.4.
I success to connection.

So I think it is bug. Isn't it?

Information : I can connect to AWS RDS PostgreSQL DB(No SSH tunnel) with ver.7.1.5

#### Steps to reproduce, if exist:
1. running DBeaver.
2. default connection open, but it's error.

#### Include any warning/errors/backtraces from the logs

Sorry. I had already downgrade to ver 7.1.4.
So I haven't 7.1.5 log.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. It duplicates #9566. Please download 7.1.5 again https://dbeaver.io/download/. The hotfix was made.
