### ISSUE TITLE
unsupported work with MATERIALIZED VIEW comment

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#9579]
Dbwaver 7.1.5 
Postgresql 12

#1.problem

1. in sql editor
CREATE MATERIALIZED VIEW db1.mv_data as select
id,
org_id,
date
from db1.t_org_data
WITH DATA;

2. Open mv_data in object tree
I changed comment for mv_data in comment window. Click to save button.
Dbeaver show window for me with:

Drop db1.mv_data;
CREATE MATERIALIZED VIEW db1.mv_data as select..
COMMENT ON MATERIALIZED VIEW db1.mv_data IS 'Comment';

It is wrong! Because I do not want DROP and CREATE MATERIALIZED VIEW. 
I need to execute command
"COMMENT` ON MATERIALIZED VIEW db1.mv_data IS 'Comment';"
only.

#2.problem
1. in sql editor
CREATE MATERIALIZED VIEW db1.mv_data as select
id,
org_id,
date
from db1.t_org_data
WITH DATA;

2. Open mv_data in object tree
I'm trying to change comment for mv_data column. But duble click on mv_data column comment do not give result.

I need to execute command
"COMMENT ON COLUMN db1.mv_data.id IS 'ID comment';"
only in this case.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report

**Comment by LonwoLonwo** [comment]
So. Now there is a separate script for adding a comment (in case only the comment field has been changed) for views and materialized views. And the error reading view DDL has been fixed.
For the second problem, I created a separate ticket https://github.com/dbeaver/dbeaver/issues/9921

**Comment by kseniiaguzeeva** [comment]
Case 1 is verified
