### ISSUE TITLE
Debug problem with postgresql 

### ISSUE THREAD

**Issue by killerwzb** [dbeaver/dbeaver#9583]
Hi :
 I get a error from  DBeaver 7.1.5 CE when I debug the function with postgresql 12.2. 
 Operation System :windows 10
 database : postgesql 12.2
 
When i  debug the function at last step , I get a error from DBeaver.

for example:

this is my function:

CREATE OR REPLACE FUNCTION public.test(_a integer, _b integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$  
declare  
    total integer;  
BEGIN  
   total :=_a+_b;
   raise notice '%+%=%',_a,_b,total;
   RETURN total;  
END;  
$function$
;

When i step over at  this line "RETURN total;  ", i get follow message:

Failed to execute select pldbg_step_over(1)
error: debugger connection terminated
erro: debugger connection terminated

**Comment by uslss** [comment]
there aren't any updates for a long time.
Issue closed. If it is still actual for you - feel fee to reopen it

**Comment by killerwzb** [comment]
Maybe like Pgadmin , At same it was successed.

**Comment by jasonchenTJ** [comment]
@killerwzb  

Hello Bro, I got the same error on dbeaver. 

Does it got fixed? 


Thanks
Jason
