### ISSUE TITLE
Redshift Spectrum Query

### ISSUE THREAD

**Issue by Geogiev** [dbeaver/dbeaver#9592]
Hi
I am using DBeaver CE verison 7.10 running on Windows

This version DBeaver seems to freeze up while running queries against table in the Redshift Spectrum Schema and llooks like nothing is happening T

I have an older version (6.3.4) of Dbeaver where it works just fine and the results are back in seconds

Not sure what the issue is

Thansk
--Geogie Varughese

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by uslss** [comment]
Issue closed - no updates for a long time.
If it is still actual - feel free to reopen the ticket
