### ISSUE TITLE
Quest for documentation

### ISSUE THREAD

**Issue by Softsuit** [dbeaver/dbeaver#9598]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Include any warning/errors/backtraces from the logs

I'm searching for a documentation on dbeaver 7.1.5 since the import module has changed drastically and it seems to add generic columns and load the data into those columns rather than the right columns.  In previous models he aligned the csv columns with the available coloumns in the table.  And I found where I can select the columns to load it in, but if i have to do this manually for 60 or more columns then this tool renders useless for I loose more time with it than a bulkload on the server itself.

**Comment by uslss** [comment]
seems that issue is fixed for now. Could you check if it is still actual for you against 7.2.3?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
