### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by wayneforrest** [dbeaver/dbeaver#9599]
`ERROR: Can't read dir of './the_db_name/' (errno: 24 "Too many open files")`

I am constantly getting this error on my local machine, using DBeaver with MariaDB on MacOS.

stoping the MariaDB service helps, but the problem seems related to DBeaver.
```
brew services stop mariadb
brew services start mariadb
```

Perhaps the database is the problem. When the error occurs with DBeaver I am able to connect to the database using Sequel Pro.

Any ideas.. perhaps I can find a log...

Currently all that is visible is:
```
SQL Error [1018] [HY000]: (conn=14) Can't read dir of './the_db_name/' (errno: 24 "Too many open files")
  (conn=14) Can't read dir of './the_db_name/' (errno: 24 "Too many open files")
  (conn=14) Can't read dir of './the_db_name/' (errno: 24 "Too many open files")
    Can't read dir of './the_db_name/' (errno: 24 "Too many open files")
    Can't read dir of './the_db_name/' (errno: 24 "Too many open files")
```

Using` mariadb 10.4.13`

Using JDBC` mariadb-java-client-2.6.2.jar`

**Comment by wayneforrest** [comment]
I have resolved the issue by increasing the MariaDB open file limit.

Here is a snippet of `my.cnf`

```
[mysqld]
open_files_limit=32000

[mysqld_safe]
open_files_limit=32000
```

**Comment by kseniiaguzeeva** [comment]
Great!
