### ISSUE TITLE
Since release 7.1.4, Connecting to Oracle stuck as "Load TableCache"

### ISSUE THREAD

**Issue by doudz** [dbeaver/dbeaver#9602]
#### System information: 
- Operating system (distribution) and version : Ubuntu 20.04
- DBeaver version 7.1.4 (works good in 7.1.3)
- Additional extensions

#### Connection specification:
- Database name and version : Oracle 10g
- Driver name : Oracle 11.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:

Since release 7.1.4, Connecting to Oracle stuck as "Load TableCache"
it works good in previous release so I downgrade to 7.1.3

**Comment by doudz** [comment]
1.
There's no error in Error Log view
![image](https://user-images.githubusercontent.com/1262548/91029274-d79bfe80-e5fe-11ea-9704-e7fa1fa52e3d.png)
 
dbeaver-debug.log
```
> Start DBeaver ER Diagram [org.jkiss.dbeaver.ext.erd 2.0.141.202008180601]
> Start Application principale (core) du support d'équipe [org.eclipse.team.core 3.8.900.v20200211-0946]
> Start DBeaver Oracle Support [org.jkiss.dbeaver.ext.oracle 2.1.124.202008180601]
> Start DBeaver MySQL Support [org.jkiss.dbeaver.ext.mysql 2.1.124.202008180601]
> Start Tampons de fichiers [org.eclipse.core.filebuffers 3.6.900.v20200117-0616]
Warning: NLS unused message: Voir in: org.eclipse.ui.internal.editors.text.TextEditorMessages
> Start GEF (MVC) [org.eclipse.gef 3.11.0.201606061308]
2020-08-24 11:37:58.939 - Connect with 'Oracle - TBAAN' (oracle_thin-16df8167412-57d93a87573c1973)
2020-08-24 11:37:58.966 - Execution context opened (Oracle - TBAAN; Main; 0)
2020-08-24 11:37:59.444 - Connected (oracle_thin-16df8167412-57d93a87573c1973, Oracle JDBC driver [12.2.0.1.0])
```


The query : 
```
SELECT  O.*,
t.TABLE_TYPE_OWNER,t.TABLE_TYPE,t.TABLESPACE_NAME,t.PARTITIONED,t.IOT_TYPE,t.IOT_NAME,t.TEMPORARY,t.SECONDARY,t.NESTED,t.NUM_ROWS
FROM ALL_OBJECTS O
LEFT OUTER JOIN ALL_ALL_TABLES t ON (t.OWNER = O.OWNER AND t.TABLE_NAME = o.OBJECT_NAME AND o.OBJECT_TYPE = 'TABLE')
WHERE O.OWNER='BAANDB' AND O.OBJECT_TYPE IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW')
```
![image](https://user-images.githubusercontent.com/1262548/91029187-bcc98a00-e5fe-11ea-85d2-090d59e537d8.png)
![image](https://user-images.githubusercontent.com/1262548/91029243-cb17a600-e5fe-11ea-9656-bb8e828ffb92.png)

**Comment by doudz** [comment]
On 7.1.2 it works and queries are different :
![image](https://user-images.githubusercontent.com/1262548/91030846-0ebedf80-e600-11ea-8c8a-c1c54d000763.png)

**Comment by doudz** [comment]
Same problem with 7.2.0

**Comment by serge-rider** [comment]
@doudz please try to execute table read query manually (in SQL editor).
I mean this one:
```sql

SELECT  O.*,
t.TABLE_TYPE_OWNER,t.TABLE_TYPE,t.TABLESPACE_NAME,t.PARTITIONED,t.IOT_TYPE,t.IOT_NAME,t.TEMPORARY,t.SECONDARY,t.NESTED,t.NUM_ROWS
FROM ALL_OBJECTS O
LEFT OUTER JOIN ALL_ALL_TABLES t ON (t.OWNER = O.OWNER AND t.TABLE_NAME = o.OBJECT_NAME AND o.OBJECT_TYPE = 'TABLE')
WHERE O.OWNER='BAANDB' AND O.OBJECT_TYPE IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW')
```

**Comment by doudz** [comment]
Tested on known working version 7.1.2
it's terribly slow
![image](https://user-images.githubusercontent.com/1262548/93082812-dad05a80-f691-11ea-9217-fd9934d3ac65.png)
![image](https://user-images.githubusercontent.com/1262548/93082832-e4f25900-f691-11ea-9c8e-3d65fc6fb9f0.png)

really slow...
![image](https://user-images.githubusercontent.com/1262548/93083070-4adee080-f692-11ea-8f96-278439773e1c.png)

**Comment by doudz** [comment]
and looks stuck at 1000 rows
![image](https://user-images.githubusercontent.com/1262548/93083257-a0b38880-f692-11ea-884c-62519e61b454.png)

**Comment by doudz** [comment]
On my database, there's 7515 tables

**Comment by doudz** [comment]
Looks like the slow part is the "LEFT OUTER JOIN" because query on ALL_OBJECTS is fast and query on ALL_ALL_TABLES is fast too

**Comment by doudz** [comment]
I manage to run the query fast by removing  `AND o.OBJECT_TYPE = 'TABLE'` in JOIN
```sql
SELECT  O.*,
t.TABLE_TYPE_OWNER,t.TABLE_TYPE,t.TABLESPACE_NAME,t.PARTITIONED,t.IOT_TYPE,t.IOT_NAME,t.TEMPORARY,t.SECONDARY,t.NESTED,t.NUM_ROWS
FROM ALL_OBJECTS O
LEFT OUTER JOIN ALL_ALL_TABLES t ON (t.OWNER = O.OWNER AND t.TABLE_NAME = o.OBJECT_NAME)
WHERE O.OWNER='BAANDB' AND O.OBJECT_TYPE IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW')
```

**Comment by serge-rider** [comment]
@doudz Thanks for the details and for the workaround! Indeed this condition is not required (as all_tables contains table only). It doesn't affect performance on most Oracle server.
But I can image that such condition may break execution plan in some cases.

See fix in the next version.

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by doudz** [comment]
I confirm it's working, thanks !
