### ISSUE TITLE
1.7.5 discrepancy

### ISSUE THREAD

**Issue by michalk-k** [dbeaver/dbeaver#9603]
After updating DBeaver to v1.7.5 a system updater still offers update, likely to the same version:
This is what what "Check for updates" feature shows:

![obrazek](https://user-images.githubusercontent.com/7868445/90875094-ebe2c000-e3a0-11ea-853d-2e4c79c0f6fb.png)

OS. Kubuntu 18.4

**Comment by uslss** [comment]
if issue is still actual for you - feel free to reopen the issue
