### ISSUE TITLE
Store sqls continuesly

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#9608]
When electricity unexpectedly off I loss all sql written in tabs. After reboot I just get empty tabs.

Would be nice if content of tabs will be stored not just when DBeaver is closed

**Comment by KES777** [comment]
> Content is not stored when you close dbeaver, but when you save the file, just like most editors.
@p91paul, I use sublime text. It restores tabs even if I do not save them. This saves me a lot of time when I copy/paste some text/code into new unsaved tab. And this is very handy. Try it ;-)

**Comment by uslss** [comment]
as a workaround you could change workspace saving interval to 1 minute
![image](https://user-images.githubusercontent.com/31996417/91549483-afc6d680-e92f-11ea-9373-5d384349127e.png)

**Comment by p91paul** [comment]
This preference is more likely to be useful - if enabled it will save your current editor after 20 seconds of inactivity:
![image](https://user-images.githubusercontent.com/2157006/92411557-a2d48f00-f148-11ea-98de-baa10d0d72d1.png)

It's probably a bit different from what you are used to in sublime (which is probabily the same thing notepad++ does), but the end result should be very similar.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/95458626-10a7ec80-097b-11eb-8750-b7b8a2df4402.png)

**Comment by kseniiaguzeeva** [comment]
Implemented
