### ISSUE TITLE
Add new row & Duplicate Current row becomes disabled in data grid when connected to an ephemeral database

### ISSUE THREAD

**Issue by mintuamb** [dbeaver/dbeaver#9609]
I am using PostgreSQL to connect to an  ephemeral database and in the data grid Add new row & Duplicate Current row becomes disabled

but when I connected to the non ephemeral database  then these options are not disabled.

I am on windows 10 and I am using the latest 7.1.5 release

see attached for more details.

Any suggestions will be greatly appreciated 
![not disabled](https://user-images.githubusercontent.com/40477577/90914859-6efd1980-e393-11ea-97b6-8a7121dae9e5.jpg)
![dis-ephemeral database](https://user-images.githubusercontent.com/40477577/90914950-92c05f80-e393-11ea-9e02-5ba8a6f7f56a.jpg)

**Comment by uslss** [comment]
seems that dbeaver read this db as read-only. Could you check if it is also non-readable in usual data grid (not as query result)?
