### ISSUE TITLE
standard capitalization option

### ISSUE THREAD

**Issue by WellspringCS** [dbeaver/dbeaver#9612]
Per [this conversation with experts](https://stackoverflow.com/questions/63383503/is-there-a-best-practice-on-upper-lower-case-for-data-types-in-postgresql), it appears to me that the most widely accepted standard for PostgreSQL with respect to capitalization is that:
- all keywords (SELECT, DELETE, UPDATE, ON, AND, etc.) are upper case, but
- all datatypes (uuid, text, int, etc.) are lower case.

Unfortunately, I do not see a DBeaver setting that supports this dichotomy.

It would be nice to have a separate protocol for data-type capitalization which is distinct from keyword capitalization.

**Comment by uslss** [comment]
seems that it is already implemented. You just need to change highlighted options as it shown at the attached picture
![image](https://user-images.githubusercontent.com/31996417/91547797-1b5b7480-e92d-11ea-922d-df35154547dd.png)

**Comment by WellspringCS** [comment]
I was going to disagree, but when I went to check, I found that that things like uuid and int are left alone, an it's just the TEXT data type that gets converted to upper case, though I'd rather it remain lower case like uuid and int.

Is there some reason why TEXT is treated this way?

**Comment by uslss** [comment]
issue with text data types will be resolved in the scope of #10180
