### ISSUE TITLE
Latest PostGIS JDBC driver needs "postgis-geometry" JAR too

### ISSUE THREAD

**Issue by placaze** [dbeaver/dbeaver#9616]
I was having this issue https://github.com/dbeaver/dbeaver/issues/8781 (`java.lang.NoClassDefFoundError: org/postgis/Geometry`) with `postgis-jdbc-2.5.0.jar`.

I read there was a split in its last version: https://github.com/postgis/postgis-java/releases/tag/postgis-java-aggregator-2.5.0

> * Decoupled geometry and encoder/decoder from postgres-jdbc
>   * Introduced postgis-geometry module which now contain geometry classes, parser, and encoder/decoder

To fix this, `postgis-geometry-2.5.0.jar` must be added too with the PostgreSQL drivers in DBeaver.

____

**Links:**
* https://github.com/postgis/postgis-java/releases
* https://mvnrepository.com/artifact/net.postgis/postgis-jdbc
* https://mvnrepository.com/artifact/net.postgis/postgis-geometry

**Comment by uslss** [comment]
thanks for suggestion

**Comment by kseniiaguzeeva** [comment]
postgis-geometry-2.5.0.jar is added
