### ISSUE TITLE
DBeaver doesn't start on mac osx 11.0 Beta (20A5354i)

### ISSUE THREAD

**Issue by Mausora** [dbeaver/dbeaver#9617]
DBeaver doen´t start after intalled on mac osx 11.0 Beta (20A5354i). No error show. Just freeze and after a while "application DBeaver Communyty not responding".

[DBeaver Crush Report.rtf.zip](https://github.com/dbeaver/dbeaver/files/5114677/DBeaver.Crush.Report.rtf.zip)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. Most probably it duplicates #9566. Please download 7.1.5 again https://dbeaver.io/download/. The hotfix was made.

**Comment by Mausora** [comment]
I did the download and re-install, but the problem persist.

**Comment by kseniiaguzeeva** [comment]
While it is not resolved, please try workaround https://github.com/dbeaver/dbeaver/issues/9533

**Comment by MarcusCalidus** [comment]
I guess this is a BigSur beta issue. It happens across all Eclipse based applications. With me it is DBeaver, ApacheDirectoryStudio and Eclipse itself. The mentioned workaround works on all those. 

https://stackoverflow.com/questions/62647625/not-able-to-run-eclipse-on-macos-big-sur

**Comment by kseniiaguzeeva** [comment]
Thank you for the information.

**Comment by Mausora** [comment]
workaround #9533 and https://stackoverflow.com/questions/62647625/not-able-to-run-eclipse-on-macos-big-sur does`n work.

**Comment by MarcusCalidus** [comment]
Could you send your edited Info.plist? What Version of Java do you have installed?
