### ISSUE TITLE
Roles script of view with dll script in postgresql database

### ISSUE THREAD

**Issue by emretuna01** [dbeaver/dbeaver#9618]
it would be great to be able to take roles script of view with view ddl script in postgresql database

Here is the some ss for pgadmin behavior and dbeaver behavior when we take create script of view  

![image](https://user-images.githubusercontent.com/42046428/91048116-d4673980-e623-11ea-95ec-524899f2303a.png)

![image](https://user-images.githubusercontent.com/42046428/91048175-ea74fa00-e623-11ea-990b-4830ebbf98ac.png)

**Comment by uslss** [comment]
Hi @emretuna01 ,
seems that it is implemented in 7.1.5v.
You could check Show permissions checkbox in Generated SQL dialog
![image](https://user-images.githubusercontent.com/31996417/91063246-6bd58800-e636-11ea-8c6c-2037cb860c5e.png)

**Comment by emretuna01** [comment]
that's excellent work thanks for that
