### ISSUE TITLE
Migrate Data Structure generated CREATE SQL does not wrap INET data type default in single quotes 

### ISSUE THREAD

**Issue by FuzzyCoder** [dbeaver/dbeaver#9619]
#### System information: 
- Operating system (distribution) and version
Pop!_OS 20.04
- DBeaver version
EE 7.1
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:
Follow the wizard with a source table that contains an INET column with a default IP

#### Include any warning/errors/backtraces from the logs

Simply states illegal syntax .0

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. It is actual for setting default value to INET type via Object Editor too.

**Comment by LonwoLonwo** [comment]
Fixed in 7.3

> Thank you for the report. It is actual for setting default value to INET type via Object Editor too.

Unfortunately can't fix this. All values for all column types in default field are recorded without single quotes

**Comment by LonwoLonwo** [comment]
ALTER case fixed

**Comment by uslss** [comment]
verified
