### ISSUE TITLE
The Darkest Dark: DBeaver blinks when a new column has been creating

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9624]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.0 EA
- Additional extensions The Darkest Dark

#### Steps to reproduce, if exist:
1. Open a table (e.g. any in Postgres.postgres.public)
2. Create a new column
![dKCVrQ3FrB](https://user-images.githubusercontent.com/51405061/91286436-1fee2480-e797-11ea-942b-2d77aff87b2e.gif)

**Comment by uslss** [comment]
cannot reproduce against 21.0.3
