### ISSUE TITLE
How to compare two query result sets?

### ISSUE THREAD

**Issue by zwastik** [dbeaver/dbeaver#9626]
#### System information: 
- Operating system (distribution) and version: Archlinux 
- DBeaver version: 7.1.5

#### Connection specification:
- Database name and version: Microsoft SQL Server 2019 (RTM-CU5) (KB4552255) - 15.0.4043.16 (X64)

#### Describe your question:
How do I compare the result sets of two queries?

**Comment by uslss** [comment]
Hi @zwastik ,
could you clarify what exactly do you mean or provide an example?
thanks in advance

**Comment by zwastik** [comment]
Something like this:
https://github.com/msorens/SqlDiffFramework/wiki/VisualComparison

Basically, a tool to compare  and find differences between tables.

**Comment by uslss** [comment]
thanks for clarification. Marked as feature request

**Comment by uslss** [comment]
already implemented in EE version

**Comment by sjivan** [comment]
@uslss Can you point to the build that has this feature and where is it accessible in the UI or pointer to the documentation?

**Comment by ShadelessFox** [comment]
@sjivan please see https://github.com/dbeaver/dbeaver/wiki/Data-compare

**Comment by sjivan** [comment]
@ShadelessFox The link you pointed me to is different from this feature request which is the ability to compare two resultsets. I was expecting the right click context menu of the Resultset table to have a "Compare To" with the name of the other resultset tab names allowing the user to compare two resultsets. This is how AquaDataStudio allows the comparison of two resultsets.

**Comment by damgot** [comment]
I'm also looking for this feature.
Data-compare compares two tables but not two results.

**Comment by RoiSoleil** [comment]
Me too, i would like a feature to compare two resultsets.

**Comment by danfoxley** [comment]
> Me too, i would like a feature to compare two resultsets.

@ShadelessFox Yes, Please share how I can compare not the complete table, but a subset of the data in a table?  Compare data from the results of a where clause.

**Comment by ShadelessFox** [comment]
@danfoxley As of now, it's not possible. We have such a feature request in our internal issue tracker. If you are a paid customer, please get in touch with us via support@dbeaver.com so we can lift the priority of that ticket.
