### ISSUE TITLE
mysql8 dump Error

### ISSUE THREAD

**Issue by jamespatriot** [dbeaver/dbeaver#9627]
#### System information: 
- Operating system (distribution) and version: win10
- DBeaver version:  7.1.5.202008170457

#### Connection specification:
- Database name and version: mysql 8.0.16
- Driver name

#### Describe the problem you're observing:

C:\Users\pc-01\AppData\Roaming\DBeaverData\drivers\clients\mysql\win\mysqldump.exe --routines --add-drop-table --disable-keys --extended-insert --host=qq --port=3306 -u root sample
Task 'MySQL dump' started at Wed Aug 26 18:26:51 CST 2020
mysqldump: Got error: 2059: Authentication plugin 'caching_sha2_password' cannot be loaded:

**Comment by uslss** [comment]
Hi @jamespatriot ,
unfortunately, cannot reproduce it. Could you provide steps to reproduce?
thanks in advance

**Comment by jamespatriot** [comment]
![dbeaver](https://user-images.githubusercontent.com/8032851/91375611-bda42b00-e84d-11ea-8865-420c48b278e0.jpg)

**Comment by serge-rider** [comment]
https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded

**Comment by Fydon** [comment]
[Download](https://dev.mysql.com/downloads/mysql/) mysql.exe and mysqldump.exe for MySQL 8 and add it as another [local client](https://dbeaver.com/docs/wiki/Backup-Restore/).
