### ISSUE TITLE
Template with 2 variables: values of first object from the list are auto-assigned

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9629]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.0 EA

#### Describe the problem you're observing:
Template with 2 variables: values of first object from the list are auto-assigned
#### Steps to reproduce, if exist:
1. Create a Template with 2 variables (e.g. Select * from ${table} where ${column})
2. Execute it in SQL Editor for a schema with 2 or more tables

Actual result:
1. Values of first table from the list are inserted automatically
2. Dropdown list for the second variable dissapears as soon as value for the first variable is selected
3. A value of first table from the list are inserted on the place of second variable
![HyX1vSUC56](https://user-images.githubusercontent.com/51405061/91296410-3b602c00-e7a5-11ea-9888-0ad6ebafc740.gif)

**Comment by uslss** [comment]
not reproducible in 23.0.3
