### ISSUE TITLE
Export data opens wrong option

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#9630]
Selecting data on a datagrid, and than "Export Data" shows the options to export.
By default, the last used one is hilighted.
![Screenshot at 2020-08-26 13-05-51](https://user-images.githubusercontent.com/3930671/91296617-2f706c00-e79d-11ea-9637-23e4d5752d5d.png)

But selecting next without changing the oprion, still brings to the "Database Tables" selection, and not to the selected one
![Screenshot at 2020-08-26 13-05-57](https://user-images.githubusercontent.com/3930671/91296684-4911b380-e79d-11ea-9efa-efdfb9030b9a.png)

DBe 7.1.15

**Comment by uslss** [comment]
thanks for the bug report

**Comment by akilovich** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
Verified
