### ISSUE TITLE
Unable to connect to postgresSQL on azure with version update on 7.1.5 ubuntu 18

### ISSUE THREAD

**Issue by sujeet1** [dbeaver/dbeaver#9631]
#### System information: 
- Operating system (distribution) and version : Ubuntu 18.04
- DBeaver version: 7.1.5
- Additional extensions: none

#### Connection specification:
- Database name and version : postgres 10
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? yes, VPN 

#### Describe the problem you're observing:
connection issue over vpn however its working fine with 7.1.4
#### Steps to reproduce, if exist:
connection issue over vpn however its working fine with 7.1.4

**Comment by uslss** [comment]
Hi @sujeet1 
could you provide logs and error message?

**Comment by uslss** [comment]
Issue closed - no updates for a long time.
If it is still actual - feel free to reopen the ticket
