### ISSUE TITLE
Ordering doesn't work in ResultSet if raws have to be fetched

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9632]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.0 EA

#### Describe the problem you're observing:
Ordering doesn't work in ResultSet if raws have to be fetched
#### Steps to reproduce, if exist:
1. Open a table where raws have to be fetched in ResultSet if SQL Editor
2. Order values of any column

Actual result: the column order is not changed
![0TtjMlJTGk](https://user-images.githubusercontent.com/51405061/91297442-02c15200-e7a7-11ea-886c-b7d57c743b6b.gif)

Workaround: Press fetch all raws btn before  sorting a column

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
