### ISSUE TITLE
Grid lines of the next columns are visible in pinned columns

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9634]
#### System information: 
- Operating system (distribution) and version win10 
- DBeaver version 7.2.0

#### Describe the problem you're observing:
Grid lines of the next columns are visible in pinned columns
![image](https://user-images.githubusercontent.com/31996417/91298578-f211db80-e7a8-11ea-8557-7cec98ecfa8a.png)

**Comment by serge-rider** [comment]
Fixed
