### ISSUE TITLE
Auto increment option checking has no effect when trying to create column

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9637]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 7.2.0

#### Connection specification:
- Database name and version SQLite

#### Describe the problem you're observing:
Auto increment option checking has no effect when trying to create column in SQLite
#### Steps to reproduce, if exist:
1. Start table creation
1. Create int column and check Auto increment option
1. Try to save changes - There is no Autoincrement attribute in DDL.

![image](https://user-images.githubusercontent.com/31996417/91311615-f4316580-e7bb-11ea-986c-81e368f48bc2.png)

**Comment by akilovich** [comment]
Fixed. 
a) SQLite requires a column to be used as primary key in order to use autoincrement on it. Now we add primary key clause as well.
b) Since it's impossible to change primary keys on a persisted base, auto inc checkbox is disabled in this context.

**Comment by uslss** [comment]
verified
