### ISSUE TITLE
Db2 Runstats on Table "Index Statistics" = All wrong syntax

### ISSUE THREAD

**Issue by gerhard81** [dbeaver/dbeaver#9638]
**System information:**

- Operating system (distribution) and version All

**DBeaver version**

- 7.1.5

**Connection specification:**

- Database name and version Db2 LUW

**Describe the problem you're observing:**

- DBeaver 7.1.5 generates wrong syntax for Db2 LUW runstats When "Column Statisics" =  "All" and "Index Statistics" = "All"

**Steps to reproduce, if exist:**

- rclick on table(s) -> Tools -> runstats->"Column Statistics"=All & "Index Statistics" = All -> "Start" => Error

Wrong syntax 
`CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE SYSTOOLS.EXPLAIN_ARGUMENT
ON ALL COLUMNS ON ALL COLUMNS');`

Correct syntax 
`CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE SYSTOOLS.EXPLAIN_ARGUMENT
ON ALL COLUMNS AND DETAILED INDEXES ALL');`

![Screenshot from 2020-08-26 15-55-37](https://user-images.githubusercontent.com/69924414/91312694-cd236580-e7b4-11ea-95d4-4ae0cd969056.png)
![Screenshot from 2020-08-26 15-56-14](https://user-images.githubusercontent.com/69924414/91312707-d0b6ec80-e7b4-11ea-8786-a076a6ce788c.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by LonwoLonwo** [comment]
[DETAILED are equivalent SAMPLED DETAILED](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.admin.cmd.doc/doc/r0001980.html) so I corrected the erroneous syntax to "ON ALL COLUMNS AND INDEXES ALL"

**Comment by uslss** [comment]
verified
