### ISSUE TITLE
Netezza Table Distribution Key is not displayed when DDL is generated

### ISSUE THREAD

**Issue by shekar-k** [dbeaver/dbeaver#9639]
#### System information: 
- Operating system (distribution) and version : Windows 10 Pro (1903)
- DBeaver version : 7.1.4 CE
- Additional extensions : None

#### Connection specification:
- Database name and version : Netezza Release 7.2.1.7 [Build 34]
- Driver name : Netezza (org.netezza.Driver)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When Generating the DDL for a table, the distribution key assigned to the table(s) are not displayed in the DDL generated window.

#### Steps to reproduce, if exist:
Right click on the table, select Generate SQL -> DDL, the "Generate SQL" window is displayed.

**Comment by uslss** [comment]
please, check if it reproducible for you in 7.2.0 EA https://dbeaver.com/files/ea/

**Comment by shekar-k** [comment]
Sure, will try and let you know.

**Comment by shekar-k** [comment]
As suggested, I installed 7.2 EA and yes the Connection Settings window is a bit difference from 7.1.4 CE, there is an option to change the database name. I tried it and the change works well.

![dbeaverEE-Connection Settings](https://user-images.githubusercontent.com/70272638/91559272-65f0e700-e955-11ea-902c-e691653b8a94.PNG)

Would this option be reflected in CE any soon.

**Comment by tati-kru** [comment]
DBeaver EE has a special Netezza extension. This improvement cannot be easily reflected to CE.

**Comment by shekar-k** [comment]
Hi there, 

Apologies to have mixed up my response between #9639 and #9641. I have removed my earlier response in this ticket as it was incorrect. 

The updated information for this ticket #9639 is here.

In 7.2 EA, the DISTRIBUTION KEY is displayed in the "Generate DDL", refer the screenshot.

![dbeaver-9639-DistributionKey](https://user-images.githubusercontent.com/70272638/91681316-b5106500-eb6b-11ea-9f86-e3627f94fd8e.png)

Would this option be available in the next version of dbeaver CE.

**Comment by serge-rider** [comment]
Netezza extension is included in DBeaver EE only. And it will be included in DBeaver EE 7.2.

CE version contains only very basic functionality (as it uses Generic driver).

**Comment by shekar-k** [comment]
Thank you for the clarification...
