### ISSUE TITLE
Netezza Database name remains the same when the Connections Settings are modified

### ISSUE THREAD

**Issue by shekar-k** [dbeaver/dbeaver#9641]
#### System information: 
- Operating system (distribution) and version : Windows 10 Pro (1903)
- DBeaver version : 7.1.4 CE
- Additional extensions : None

#### Connection specification:
- Database name and version : Netezza Release 7.2.1.7 [Build 34]
- Driver name : Netezza (org.netezza.Driver)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
On an existing connection, when the database name is changed in the edit driver settings, the database name is reflected for a brief time in the JDBC URL of Connection Settings window. When OK is selected to save the details, the database name reverts to the previous one before editing.

#### Steps to reproduce, if exist:
Right click on a connection (Netezza Database connection), In "Connection settings" page, the "JDBC URL" shows the current database name, Now click "Edit Driver settings" and make the changes to the "URL Template" with a different database name. Click OK to return back to "Connection Settings", here the "JDBC URL" show the new database name,, Click OK to save the updated Connection details, When The first prompt "Connection XYZ has been changed..." appears, notice the contents of the "JDBC URL", the database name has changed to the previous database name. When saved, there is no effect to the database connection.

**Comment by uslss** [comment]
@shekar-k 
could you provide video of the issue?
btw, why do you need to change Driver settings? You could change the database name in connection settings window

**Comment by shekar-k** [comment]
I have attached a screenshot of the Connection Settings, the database name could not be changed from the area (see text in red), hence the need to get into the driver settings to change the database name.

![dbeaver-Connection Settings](https://user-images.githubusercontent.com/70272638/91554019-ef9bb700-e94b-11ea-8d33-a90c4354f4e7.PNG)

**Comment by shekar-k** [comment]
In the course of analyzing #9639, we were asked to install 7.2 EA, we installed and found the Connection Settings window is different.

We were able to change the database name in the Connection Settings window itself.

![dbeaverEE-Connection Settings](https://user-images.githubusercontent.com/70272638/91681530-53042f80-eb6c-11ea-8c44-e518c7e9969d.PNG)

Would this option be available in the updated version of dbeaver CE.

**Comment by shekar-k** [comment]
Ok.. As part of my checks, I did the following...

1) Uninstalled 7.1.4 CE
2) Removed the workspace (DbeaverData)
3) Re-installed 7.1.4 CE

Now the option to enter the Database/Schema is displayed. Refer the screenshot.

![dbeaver-9641-ConnectionSettings](https://user-images.githubusercontent.com/70272638/91828964-6db6d100-ec5e-11ea-9f80-6e9496a5b66c.png)

The first screenshot in this ticket and the current screenshots are from 7.1.4 CE. Not sure why this weird behavior is exhibited.
