### ISSUE TITLE
No Export xlsx in the Data Transfer Box.

### ISSUE THREAD

**Issue by acharest2020** [dbeaver/dbeaver#9642]
#### System information: 
- Operating system (distribution) and version:  Windows 10
- DBeaver version: Version 7.1.5.202008180601

#### Connection specification:
- Database name and version: Teradata Version 16.20.32.22

#### Describe your question:  I do not see the option to export to a xlsx file in the list.  See the picture below.  How do I get that option listed?
![export](https://user-images.githubusercontent.com/70276582/91316760-368c7f80-e787-11ea-93df-977c80f7764b.PNG)

**Comment by uslss** [comment]
Hi @acharest2020 ,
By default this option is available in EE version only.
You could install Office extension to get it in CE version (https://github.com/dbeaver/dbeaver/wiki/Optional-extensions)
