### ISSUE TITLE
Export and Import tables

### ISSUE THREAD

**Issue by g3blv** [dbeaver/dbeaver#9645]
#### System information: 
- DBeaver Community Edition 7.1.5 Flatpak

#### Connection specification:
- Maria DB 10

#### Describe your question:
Previously I used MySQL Workbench but I had some issue with memory. I have been very happy with DBeaver but there are some features when exporting and importing multiple tables that I used in MySQL Workbench that I haven't been able to find in DBeaver.

For instance in MySQL Workbench it is possible to chose if he export should be one `.sql` file or or one file per table saved in a folder. 

Another feature I haven't found in DBeaver is the possibility the to select which tables that should be imported and to which schema the tables should be imported to. 

In general it feels like there are a few more choices when exporting and importing tables in MySQL Workbench. Maybe it is just that I haven't found these features in DBeaver. 

I do exports in DBeaver by right clicking the schema and then select Tools - Dump databse

For imports I right click the schema and then select Tool - Execute script and then select the `.sql` file.

Any suggestions would be much appreciated.

**Comment by uslss** [comment]
This is not implemented yet. Marked as feature request.

**Comment by uslss** [comment]
obsolete
