### ISSUE TITLE
Error appears after adding/deleting a dashboard to Dashboard panel

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9646]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.0 EA

#### Steps to reproduce, if exist:
Open Dashboard panel with preconfigured dashboards
Add a dashboard to the panel

Actual result:
1. Error appears: Error saving dashboard view configuration
2. The dashboard is added (or deleted) as expected

[.log](https://github.com/dbeaver/dbeaver/files/5134790/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5134792/dbeaver-debug.log)

**Comment by serge-rider** [comment]
This is worse than it looks. Dashboard configuration save/load was broken.
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
