### ISSUE TITLE
Oracle - DBeaver uses ALL_OBJECTS instead of DBA_OBJECTS

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#9649]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.1.5
- Additional extensions: Office

#### Connection specification:
- Database name and version: Oracle 11
- Driver name: ojdbc v19
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

When loading tables with "Always use DBA Tables" enabled, the following query is issued:
```
SELECT  O.*,
t.TABLE_TYPE_OWNER,t.TABLE_TYPE,t.TABLESPACE_NAME,t.PARTITIONED,t.IOT_TYPE,t.IOT_NAME,t.TEMPORARY,t.SECONDARY,t.NESTED,t.NUM_ROWS
FROM ALL_OBJECTS O
LEFT OUTER JOIN DBA_ALL_TABLES t ON (t.OWNER = O.OWNER AND t.TABLE_NAME = o.OBJECT_NAME AND o.OBJECT_TYPE = 'TABLE')
WHERE O.OWNER='BIP_OWN' AND O.OBJECT_TYPE IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW')
```

![immagine](https://user-images.githubusercontent.com/2157006/91426180-6f4a5880-e85c-11ea-9490-9f7d5eb0b657.png)

DBA_OBJECTS should be used instead of ALL_OBJECTS while this setting is on. This query AFAIU populates database navigator, and I noticed missing tables because of that. I am accessing the database with an administration user, which should see all tables, partitions, tablespaces, etc but be able to query none of them. Also, ALL_OBJECTS is terribly slow compared with DBA_OBJECTS.

**Comment by kseniiaguzeeva** [comment]
Do you enable option here (Connection configuration>Connection settings>Oracle properties)?
![dbeaver_K1wT4ZTcvU](https://user-images.githubusercontent.com/51405061/91520813-e20c1000-e8fe-11ea-8228-1eeb378919f4.png)

**Comment by serge-rider** [comment]
@kseniiaguzeeva Yep, there is a screenshot in the first comment.

In fact we don't use DBA_ views to read tables and columns. It is a bug.
Fixed (you can see actual table read query in the Query Manager view in dbeaver)

**Comment by kseniiaguzeeva** [comment]
Verified
