### ISSUE TITLE
Error Save in 'Grid Mode'

### ISSUE THREAD

**Issue by inve00** [dbeaver/dbeaver#9651]
I have this error when i try to save a change directly on grid

![erroreDbeaver](https://user-images.githubusercontent.com/70329657/91453213-c01f7880-e87f-11ea-90d1-5708cedb75c7.PNG)

![erroreDbeaver1](https://user-images.githubusercontent.com/70329657/91453545-299f8700-e880-11ea-82b1-2900c6f9b84b.PNG)

I have no problem if i use a query SQL to make same change.

System information:
Operating system (distribution) and version Windows 7 Professional
Dbeaver version: 7.1.5
DB: DB2 (IBM)

**Comment by kseniiaguzeeva** [comment]
Please send me table DDL to reproduce it.

**Comment by uslss** [comment]
Issue closed - no updates for a long time.
If it is still actual - feel free to reopen the ticket
