### ISSUE TITLE
Can't connect to DB even after Test connection indicates success 

### ISSUE THREAD

**Issue by fuv0000** [dbeaver/dbeaver#9652]
I am having a terrible problem with DBEAVER. Recently, I was booted out of my database connection. When I tried to reconnect, it appears successful but does not actually connect to the DB. 

See this image:

![image](https://user-images.githubusercontent.com/70335134/91463416-5c825480-e859-11ea-9bd3-5ecb5597b2ca.png)

You can see in the image that the connection test is saying this is successful. However when I click "Finish" it does not actually connect to the DB. Nothing happens. And when i try and run a query i tells me i have no active connection.

I tried reinstalling. No luck. Please help!

**Comment by kseniiaguzeeva** [comment]
Database appears in DB Navigator and Projects view after pressing **Finish** btn. Please click the database in DB Navigator and then press **Connect** (in the upper toolbar or the database context menu)

**Comment by suryapsb** [comment]
is this issue resolved ? if resolved, can someone provide steps to fix this issue?
