### ISSUE TITLE
Autocomplete for view fields on Snowflake is not working correctly

### ISSUE THREAD

**Issue by AndrewHannigan** [dbeaver/dbeaver#9655]
Autocomplete for View fields on Snowflake is not working correctly.  Introspection for column names of view works fine in the explorer pane.  But in the sql editing window autocomplete does not work for these fields that have been detected in explorer.

DB: Snowflake
OS: iOS 10.15.5
Dbeaver: 7.1.5.202008180601

**Comment by kseniiaguzeeva** [comment]
Please clarify where it happens with columns autocomplete. It works ok for columns in SQL Editor and Data Editor (Source tab of view Properties), but the tables and views really cannot be found.

![IDgoANHWqm](https://user-images.githubusercontent.com/51405061/91539556-2f4da900-e922-11ea-88c2-ab7b254d2e60.gif)

**Comment by uslss** [comment]
there aren't any updates - the issue closed.
If it is still actual - feel free to reopen it.
