### ISSUE TITLE
Start menu entries not accessible to all users

### ISSUE THREAD

**Issue by richardrawstronMOH** [dbeaver/dbeaver#9656]
#### System information: 
- Operating system (distribution) and version:   Windows Server 2016 (Build 14393)
- DBeaver version:   CE 7.1.4, EE 7.1.0
- Additional extensions:   None

#### Connection specification:
- Database name and version: N/A
- Driver name: N/A
- Do you use tunnels or proxies (SSH, SOCKS, etc)? N/A

#### Describe the problem you're observing:
DBeaver menu items are not present for all users when "For anyone who uses this computer (all users)" is selected during install.
Start Menu items are created in the profile of the user installing DBeaver.

#### Steps to reproduce, if exist:
Install DBeaver
During install Select For anyone who uses this computer (all users)
Complete install 
Start Menu items are created in C:\Users\<user>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\
To be accessible to all users Start Menu items should be in C:\ProgramData\Microsoft\Windows\Start Menu\Programs

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
