### ISSUE TITLE
Start menu entries are not removed on uninstall

### ISSUE THREAD

**Issue by richardrawstronMOH** [dbeaver/dbeaver#9657]
#### System information: 
- Operating system (distribution) and version   Windows Server 2016 (Build 14393)
- DBeaver version   CE 7.1.4
- Additional extensions   None

#### Connection specification:
- Database name and version N/A
- Driver name N/A
- Do you use tunnels or proxies (SSH, SOCKS, etc)? N/A

#### Steps to reproduce, if exist:
Install DBeaver
During install Select For anyone who uses this computer (all users)
Complete install
Uninstall DBeaver (via Control Panel or Start Menu entry)
Start Menu entries remain in C:\Users\<user>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by kseniiaguzeeva** [comment]
Thank you for the report

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
