### ISSUE TITLE
Oracle NLS_LENGTH_SEMANTICS

### ISSUE THREAD

**Issue by bierbo** [dbeaver/dbeaver#9659]
**Is your feature request related to a problem? Please describe.**
For Oracle connections, NLS_LENGTH_SEMANTICS can't be set via GUI or via bootstrap command.
the bootstrap command "alter session set nls_length_semantics = CHAR;" is simply ignored.

**Describe the solution you'd like**
I want to set NLS settings either globally or per connection.

**Describe alternatives you've considered**
Currently I am settings NLS_LENGTH_SEMANTICS as first command of the day - but this is really prone to errors.

**Additional context**
This is the dialog how it looks like in oracle sql developer. Maybe it would be good if I could set all settings and not varchar format via settings.
![image](https://user-images.githubusercontent.com/800307/91540295-e1817280-e91a-11ea-8b5c-1f6ae7be290a.png)

**Comment by serge-rider** [comment]
Extra NLS parameters were added to the Oracle connection page:
![image](https://user-images.githubusercontent.com/6398845/94336366-64b1e900-ffeb-11ea-9d0d-67e210fa2c01.png)

**Comment by uslss** [comment]
verified
