### ISSUE TITLE
UTF-8 support for commenting tables in SQL server

### ISSUE THREAD

**Issue by kano77** [dbeaver/dbeaver#9664]
Hi,  
after resolving this issue "SQL Server Table, Adding Comments to the Table Failing #4754"  #dba0522 it performs perfectly but there is one more thing, I can't add a comment to the table in another language like Chines or Georgian.  

The SSMS performs a script like this: 

`USE [NAPR]; 
GO EXEC sys.sp_updateextendedproperty       
@name = N'MS_Description',      
@value = N'საკადასტრო კოდის უნიკალური ID',       
@level0type = N'SCHEMA',       
@level0name = N'DWH',      
@level1type = N'TABLE',       
@level1name = N'DIM_RealEstate',       
@level2type = N'COLUMN',       
@level2name = N'CadcodeID'; 
GO`

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. I do not have an error message, but chinese/georgian letters convert to question marks after table reopening

**Comment by ShadelessFox** [comment]
Hello, @kano77, what exactly is the problem? Is the text being replaced with quote marks or you're getting an error?
Please refer to the [SQL Server documentation page](https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver15) about collations to see if it helps.

**Comment by kano77** [comment]
Dear  *Mention,*

*Thank you for your response. The problem is that when I'm trying to add
some comment to the SQL server database table column from dbeaver, it
generates a script for a stored procedure like this:*

*EXEC LOMBARDI.sys.sp_addextendedproperty 'MS_Description',  'გიორგი',
'user', 'dbo', 'table', 'Bank_Payment', 'column', 'Payment_ID'*

It does perfectly but there is one problem. If I'm using Georgian or any
other Unicode character in the SQL server will get question marks in the
Extended Property.

If it is possible when the comments are made with Unicode character to have
'N' sign in front of comment like this:
*EXEC LOMBARDI.sys.sp_addextendedproperty 'MS_Description', N**'გიორგი'**,
'user', 'dbo', 'table', 'Bank_Payment', 'column', 'Payment_ID'* .

**Comment by kano77** [comment]
> Hello, @kano77, what exactly is the problem? Is the text being replaced with quote marks or you're getting an error?
> Please refer to the [SQL Server documentation page](https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver15) about collations to see if it helps.

Dear  ShadelessFox

Thank you for your response. The problem is that when I'm trying to add
some comment to the SQL server database table column from dbeaver, it
generates a script for a stored procedure like this:

```
EXEC LOMBARDI.sys.sp_addextendedproperty 'MS_Description',  'გიორგი',
'user', 'dbo', 'table', 'Bank_Payment', 'column', 'Payment_ID'
```

It does perfectly but there is one problem. If I'm using Georgian or any
other Unicode characters in the SQL server it converts to question marks in the
Extended Property.

If it is possible when the comments are made with Unicode character to have
'N' sign in front of comment like this:

```
EXEC LOMBARDI.sys.sp_addextendedproperty 'MS_Description', N**'გიორგი'**,
'user', 'dbo', 'table', 'Bank_Payment', 'column', 'Payment_ID'.
```

**Comment by ShadelessFox** [comment]
@kano77, thank you for your detailed response, now I understand what you mean. We will implement that in the near milestone.

**Comment by kseniiaguzeeva** [comment]
verified
