### ISSUE TITLE
Export from Oracle to SQL Server: wrong syntax for numeric column

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9665]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.0 EA

#### Connection specification:
- Database name and version Oracle

#### Steps to reproduce, if exist:
1. Export a table with INT column from Oracle to SQL Server (e.g. HR.EXPORT_F)
2. Press Schema btn in Tables mapping step.

Actual result: wrong DDL is displayed:
CREATE TABLE ksu_1.dbo.dd (
	VAR_T varchar(100) NULL,
	INT_T **0** NULL
) GO

P.S. Is it ok that INT type is displayed as number in columns mapping?
![dbeaver_IMvCUkHLAX](https://user-images.githubusercontent.com/51405061/91653838-b890e700-eaac-11ea-9556-a97bb0fb444e.png)

**Comment by p91paul** [comment]
on Oracle, INT is just an alias for NUMBER https://docs.oracle.com/database/121/SQLRF/sql_elements001.htm#SQLRF55581

**Comment by serge-rider** [comment]
`INT(0)` is definitely an incorrect data type definition.

**Comment by kseniiaguzeeva** [comment]
Cannot be reproduced anymore.
