### ISSUE TITLE
Export from Oracle in DBUnit format skips a table name

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9666]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.0 EA

#### Connection specification:
- Database name and version Oracle

#### Steps to reproduce, if exist:
Export a table in DbUnit format (e.g. HR.EXPORT_F)

Actual result:  there is not the table name in the exported file.
![notepad_gvhnXIfdju](https://user-images.githubusercontent.com/51405061/91654221-ba0fde80-eaaf-11ea-95ea-772e44dc5a8e.png)

**Comment by serge-rider** [comment]
And XML file is no in valid XML format

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified
