### ISSUE TITLE
sqlserverCe support

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#9669]
I know that the DB is near its end life, but it might be good to have support for sqlserverCe sdf file types too.

**Comment by kseniiaguzeeva** [comment]
Unfortunatelly we have not plans to do this  because jdbc driver doesn't exist for the database https://stackoverflow.com/questions/141454/jdbc-driver-for-microsoft-sql-server-cecompact-edition-3-5

**Comment by surpavan** [comment]
Point noted.  Thank you.
