### ISSUE TITLE
Outdated libraries still in plugins, slowing down startup  time

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#9672]
Hi!
There are dozen of old/outdated libraries loaded at DBeaver startup, that are not needed and that slow down startup time.
After disabling them, DBeaver starts waays quicker that before.

List so far:
![image](https://user-images.githubusercontent.com/3930671/91689510-9195ec00-eb64-11ea-8882-035da51d6c78.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
It seems to be Linux-specific behavior.
Workaround: delete `~/.eclipse` folder. It will be recreated on DBeaver startup.

**Comment by uslss** [comment]
Is this still actually against the recent version?

**Comment by uslss** [comment]
There have been no updates for a long time. if issue is still actual - feel free to reopen it
