### ISSUE TITLE
# @kseniiaguzeeva  Can you please take a look as i think we need to re-open this ticket as its still not fixed in new version 7.1.5.

### ISSUE THREAD

**Issue by sovittyagi** [dbeaver/dbeaver#9674]
# @kseniiaguzeeva  Can you please take a look as i think we need to re-open this ticket as its still not fixed in new version 7.1.5.

_Originally posted by @sovittyagi in https://github.com/dbeaver/dbeaver/issues/9331#issuecomment-683741258_

**Comment by kseniiaguzeeva** [comment]
Answer is here https://github.com/dbeaver/dbeaver/issues/9331#issuecomment-683741258. Closed as duplicate
