### ISSUE TITLE
Can't download old jaybird drivers

### ISSUE THREAD

**Issue by ANTONIOPSD** [dbeaver/dbeaver#9675]
Hi, I'm trying to download an old jaybird driver and it fails with this error:

Can't open 'https://repo1.maven.org/maven2/org/firebirdsql/jdbc/jaybird/3.0.6/jaybird-3.0.6.jar': Not Found

Any ideas? I clean installed it and still fails

![imagen](https://user-images.githubusercontent.com/1978099/91780497-06fecc80-ebf8-11ea-9a6a-0fb5d5949b9c.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
I'm afraid we can't fix it from dbeaver side. 3.x drivers were deleted from Maven central (I don't know why).
Default driver version is 4.0. You could also download 2.x drivers.

Is there any reason to download 3.x drivers?
