### ISSUE TITLE
configuration files in Mac Os High Sierra

### ISSUE THREAD

**Issue by verajosemanuel** [dbeaver/dbeaver#9678]
I use an old OsX system and I want to migrate all my connections to a new machine.
I tried to find the .local/share/DBeaverData folder to no avail

Noticed ~/Library/DBeaverData/workspace6/General/ folder but is empty. Nothing inside

where are config files located in High Sierra?

Regards

**Comment by kseniiaguzeeva** [comment]
You can find the information here: https://github.com/dbeaver/dbeaver/wiki/Workspace-location
Please open new ticket if you have any other questions.

**Comment by verajosemanuel** [comment]
~/Library/DBeaverData/  Is empty

**Comment by kseniiaguzeeva** [comment]
Which DBeaver version do you use?  Did not you set a custom location?

**Comment by verajosemanuel** [comment]
Hi @kseniiaguzeeva 
I use latest Dbeaver version (I always update when a new version is released)
I did not set a custom location

**Comment by uslss** [comment]
@verajosemanuel 
you could check workspace location in Preferences (Project Tab - Preferences - Resource)
![image](https://user-images.githubusercontent.com/31996417/92919154-c34a6500-f438-11ea-9ed5-f3e8d7c4e0fd.png)

**Comment by verajosemanuel** [comment]
That folder is Empty

**Comment by kseniiaguzeeva** [comment]
Perhaps you do not have saved scripts, bookmarks, schemes. If I'm right, this results in the folder not being visible to you. To see the folder, save the script and the folder will become visible

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
