### ISSUE TITLE
NPE falls in "Database -> Transaction mode" in special cases

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#9681]
When draws a checkbox for smart commit mode
For objects like User, Procedure, Session manager etc.
[npesmartcommit.txt](https://github.com/dbeaver/dbeaver/files/5162326/npesmartcommit.txt)
![2020-09-02 15_43_23-DBeaver Enterprise 7 2 0 - asya@%](https://user-images.githubusercontent.com/45152336/91982551-19315580-ed33-11ea-8a0d-3ba21533f808.png)

**Comment by uslss** [comment]
verified
