### ISSUE TITLE
Data editor shows empty string instead of [NULL] for NULL values in TEXT columns [MySQL]

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#9682]
Suppose I have a table like this:
```sql
CREATE TABLE `test` (
  `name` varchar(50) NOT NULL,
  `val` text,
  `val2` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO test (name, val, val2) VALUES('a', 'abc', NULL);
INSERT INTO test (name, val, val2) VALUES('b', NULL, NULL);
```
Then this is what I see:
![dbeaver-null-text](https://user-images.githubusercontent.com/11840364/91982816-1599d080-ed2b-11ea-9bcb-70e971048dbc.png)

In row `b` column `val` should show `[NULL]` but it looks like en empty string.

Also, Generate SQL -> INSERT doesn't export the NULL values but changes them to an empty string:
```sql
INSERT INTO test (name, val, val2) VALUES('a', 'abc', NULL);
INSERT INTO test (name, val, val2) VALUES('b', '', NULL);
```
However, Export Data as SQL produces correct result:
```sql
INSERT INTO test (name,val,val2) VALUES 
('a','abc',NULL)
,('b',NULL,NULL)
;
```
This is on MySQL 5.7. NULLs are displayed correctly in VARCHAR columns but not in TEXT columns.

**Comment by uslss** [comment]
Issue is reproducible with MySQL 8+ driver only. Works ok with MySQL driver

**Comment by serge-rider** [comment]
The error was in text (LOB) -> varchar conversion routine. Fixed.

**Comment by uslss** [comment]
verified
