### ISSUE TITLE
checksum for Windows 64 bit (installer) version dbeaver-ce-7.2.0-x86_64-setup.exe incorrect

### ISSUE THREAD

**Issue by wallybowles** [dbeaver/dbeaver#9689]
#### System information: 
- Winidows 10 64bit
- DBeaver version 7.2.0

#### Describe your question:
My checksums are not matching.  Anyone else having this problem?
I downloaded the Windows 64 bit (installer)
#1 md5 Test on file.
C:\Downloads\DBeaver>md5 dbeaver-ce-7.2.0-x86_64-setup.exe
35E25E342C539A2DE55C4D17EE067BC0  dbeaver-ce-7.2.0-x86_64-setup.exe

From website, The --> dbeaver-ce-7.2.0-installer.pkg.md5   is
673ef19cceb583e7a000858804605e88  <--- Does NOT match!!!!

#2 sha256 Test on file.
Algorithm : SHA256
Hash      : 3CDB537814510B5E4F50B8D2585FD0C29AECA058B7606F2738E0C40DEF53ACA4
Path      : C:\Downloads\DBeaver\dbeaver-ce-7.2.0-x86_64-setup.exe

From website, The --> dbeaver-ce-7.2.0-installer.pkg.sha256    is
3c930bf9ce16d7c08abd5149367ad7b436618ed922e4a4e7fa86e568d98bcce4 <--- Does NOT match!!!!

**Comment by kseniiaguzeeva** [comment]
Your OS is Windows. You should use dbeaver-ce-7.2.0-x86_64-setup.exe.md5   https://dbeaver.io/files/7.2.0/checksum/
