### ISSUE TITLE
[MySQL] Foreign key with SET DEFAULT option cannot be created

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9693]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.0
#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
1. Create a valid table foreign key via UI (SQL Editor gives the same error)
2. Select SET DEFAULT on **on delete** or **on update** field
3. Save the FK. 

Actual result: error appears: 
"eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Framework arguments:  -runTask @test:composite_import_import
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -runTask @test:composite_import_import
"

**Comment by LonwoLonwo** [comment]
https://stackoverflow.com/questions/20943459/innodb-mysql-unable-to-set-on-delete-set-default-how-to-set

> You can't use ON DELETE SET DEFAULT or ON UPDATE SET DEFAULT with InnoDB

**Comment by kseniiaguzeeva** [comment]
Thank you
