### ISSUE TITLE
SQL Group By and Calculation question

### ISSUE THREAD

**Issue by GoldenSun666** [dbeaver/dbeaver#9704]
Hi Guys,

I am new to SQL and I am trying to create some queries in DBeaver.  I have some questions regarding aggregation by using group by. I will use an example output table to explain (THIS IS THE OUTPUT by running my query):

ID                SubType     Data 1     Data 2   Data 3   Data 4
Sample 1       A               Null         Null       21          22
Sample 1       B               20            15         Null        Null

So in here, I have used where statement to select sample 1, then based on group by subtype, I can retrieve different information from Sample 1 (based on subtype, some data will be Null as shown from the table due to the reason that some data is only available for either A or B).  

Now the first difficulty for me: I want to create a new column "Data 5" for part B and the formula will be using 20 from Data 1 column, 15 Data 2 column and 21 from Data 3 column - i.e. 20/(21-15).  Is this possible to make new output based on output results? Hope I don't confuse you here.

Second difficulty for me: Initially, I want to make a one row table for Sample 1. So basically, I don't want to group by subtype and just show Data 1 - Data 4 columns. However, my query has case and end as statements that search for keywords in Subtype column to retrieve info. Therefore, it forces me to use group by subtype (I guess??). I don't know what to do. Is there a way to make this simple? I  want to make something like this:

ID                    Data 1     Data 2   Data 3   Data 4
Sample 1              20       15            21          22

If my questions are confusing, I can paste my actual query in here and output results so you guys can better understand.

Thank you for your help!!!!

**Comment by p91paul** [comment]
Looks like your issue is more with sql than dbeaver itself: I suggest you post your question on stackoverflow or a similar programming forum. Surely the actual sql used and more information about the source tables is going to be useful!

**Comment by kseniiaguzeeva** [comment]
@GoldenSun666 Please tell 
- your database, 
- DDL for tables you use 
- query examples from your question. 

I hope I will be able to help with the additional information

**Comment by GoldenSun666** [comment]
I think i can close this issue now. I have opened another ticket on stackedflow. Do i need to close this?

**Comment by GoldenSun666** [comment]
Thank you everyone for help. I have resolved the issue.

**Comment by kseniiaguzeeva** [comment]
Yes, thank you
