### ISSUE TITLE
[MySQL] Impossible to save changes after refresh in Data Editor

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9705]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.0

#### Connection specification:
- Database name and version MySQL

#### Steps to reproduce, if exist:
1. Open a table in Data Editor
2. Set Auto-commit, Read uncommited
3. Make a valid data change (without saving)
4. Refresh the table
5. Apply change saving in popup.

Expected: the change is applied and saved
Actual result:
1. Error appears
SQL Error: Streaming result set com.mysql.jdbc.RowDataDynamic@4c20df7f is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.

2. The changes are applied after table reopening.
![8Ol8ihOPDJ](https://user-images.githubusercontent.com/51405061/92320813-108b9880-f02d-11ea-8025-5c354e4123a9.gif)
[.log](https://github.com/dbeaver/dbeaver/files/5179225/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5179226/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment]
https://stackoverflow.com/questions/3550263/streaming-resultset-error

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Still can be reproduced in some tables (please try sakila.language or sakila.Test_refresh)

**Comment by serge-rider** [comment]
One more fix added (the error happens because tow select statements happen in the same moment: updated rows refresh + entire results refresh).

**Comment by kseniiaguzeeva** [comment]
verified
