### ISSUE TITLE
@fancywriter Could you try SSHJ instead of JSch (Help->Install New Software->https://dbeaver.io/update/sshj/latest/)?

### ISSUE THREAD

**Issue by goodgoodwish** [dbeaver/dbeaver#9707]
Install SSHJ works for me.   2020-09-06.

@fancywriter Could you try SSHJ instead of JSch (Help->Install New Software->https://dbeaver.io/update/sshj/latest/)?

_Originally posted by @nimda7 in https://github.com/dbeaver/dbeaver/issues/5845#issuecomment-541593022_

**Comment by uslss** [comment]
seems issue was created by mistake.
close it.
