### ISSUE TITLE
SQL Editor Tabs: Make Label the File Name

### ISSUE THREAD

**Issue by XiozTzu** [dbeaver/dbeaver#9708]
Rather than have the SQL Editor tabs display the connection name can it display the script file name without the .sql at end?  Or a create toggle to set it this way?  Also remove < and > which take up valuable character space.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion

**Comment by uslss** [comment]
@XiozTzu ,
you could change SQL editor tab name in preferences
![image](https://user-images.githubusercontent.com/31996417/92919393-10c6d200-f439-11ea-8e1d-d0767182aaaa.png)

**Comment by XiozTzu** [comment]
Ok great!  

I would only suggest changing the text to say “script TAB title pattern” so it can be found with the keyword “tab”. 

Thank you
