### ISSUE TITLE
MySQL does not show the name of database

### ISSUE THREAD

**Issue by smcdl** [dbeaver/dbeaver#9709]
#### System information: 
- Operating system (distribution) and version: MacOS
- DBeaver version: 7.2.0
- Additional extensions: Nothing

#### Connection specification:
- Database name and version: MySQL5.7
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
MySQL does not show the name of database.

#### Steps to reproduce, if exist:

![image](https://user-images.githubusercontent.com/4975064/92342586-d89b5880-f0f3-11ea-9d56-9845f8d1097b.png)
This is PostgreSQL.

![image](https://user-images.githubusercontent.com/4975064/92342615-ebae2880-f0f3-11ea-9d0a-10a6d7c76f6f.png)
This is MySQL

**Comment by kseniiaguzeeva** [comment]
Most probably a default database is not selected.
You can do it via context menu in DB Navigator tree or in connection settings
![dbeaver_7Nnsrgb5rf](https://user-images.githubusercontent.com/51405061/92363556-52cedb80-f0fa-11ea-88b1-ca9767a5af42.png)

**Comment by uslss** [comment]
there aren't any updates - the issue closed.
If it is still actual - feel free to reopen it.
