### ISSUE TITLE
Hana: Code complete does not show public synonyms

### ISSUE THREAD

**Issue by wernerdaehn** [dbeaver/dbeaver#9710]
#### System information: 
- Win 10
- 7.2.0

#### Connection specification:
- Hana 2 SP4

#### Describe the problem you're observing:

When typing in the SQL Editor:

    select * from tab...

the proposed objects do not include public synonyms. This is most important as all dictionary views have public synonyms, e.g. what you want to select in 90% of the cases will be

    SELECT * FROM tables;

I expected this PR to include the code but it is merged in 7.2.0
https://github.com/dbeaver/dbeaver/pull/8606/files

@kai-morich

**Comment by kai-morich** [comment]
My change shows PUBLIC as additional schema in the schema list. I did not add to auto complete as it was not obvious where to implement. 
As system views with public synonyms are in SYS schema, I usually type `sys.tables` if I want auto completion

**Comment by wernerdaehn** [comment]
Thanks Kai. I still find that important, though. Agree?
On a side note, I also typed

    select * from public.tab...

and it said "no proposals".

**Comment by LonwoLonwo** [comment]
The greatest problem for us is now in the implementation of this improvement, it is the lack of a test base. Without it, we cannot properly check the PR and make the necessary edits. We will try to come up with something to the test base (if you have ideas, then share!), But not in this release.

**Comment by wernerdaehn** [comment]
If you need help, I can create a new branch and implement it for you. Otherwise I can share a Hana database in AWS with you.
My problem is that I am pretty busy until end of June.

**Comment by serge-rider** [comment]
@wernerdaehn If you could share access to AWS Hana that would be super-awesome ❤️ 
Please write me on serge@jkiss.org

**Comment by wernerdaehn** [comment]
Copied your email, you can delete above post.

**Comment by LonwoLonwo** [comment]
Search with "Ctrl+Schift+D" on connection fixed.

**Comment by uslss** [comment]
verified

**Comment by wernerdaehn** [comment]
Is this really fixed? I don't think so.

`select * from public.tables;` works.
`select * from tables;` does not offer the `tables` for autocompletion. 

Yes, I have just upgraded to 21.0.2.

![image](https://user-images.githubusercontent.com/13607767/115214884-3e78a580-a103-11eb-9303-257a4a3b0695.png)

**Comment by LonwoLonwo** [comment]
Hello @wernerdaehn 
You can test [new version 21.0.3](https://dbeaver.io/)
![2021-04-19 14_28_32-](https://user-images.githubusercontent.com/45152336/115229414-b226ac80-a11b-11eb-96f3-cd28a5d25bcc.png)

**Comment by wernerdaehn** [comment]
That I don't question. But neither TRACKS nor SKITRACKS are synonyms and no public ones. `TABLE` is, see node PUBLIC -> Synonyms.

**Comment by LonwoLonwo** [comment]
I apologize for the misunderstanding.

Autocomplete works with schema_name + synonym name in case of synonyms from non default for SQL Editor schema,
![2021-04-19 14_59_01-DBeaver Enterprise 21 0 3 - _none_ Script-19](https://user-images.githubusercontent.com/45152336/115233344-74785280-a120-11eb-8fd2-84e45849346d.png)

or for schema synonyms in case "select * from synonym_name"
![2021-04-19 15_00_25-](https://user-images.githubusercontent.com/45152336/115233441-940f7b00-a120-11eb-93e9-6628d912e01d.png)

**Comment by wernerdaehn** [comment]
Exactly. But if a `select * from tables` is valid, and it is, it should be included in the autocomplete list. Don't you agree? 
Anyway, that was the original request. At least it should be reopened, I would say.

**Comment by LonwoLonwo** [comment]
You can create another new ticket.
About autocomplete for public synonyms without "public" schema name.

And It's kind of tricky, make public synonyms available always in autocomplete. 
As I see, the base does not prevent me from creating an not public synonym with an identical public synonym name.
![2021-04-19 16_14_07-DBeaver Enterprise 21 0 3 - _spserver rtdi io_ Script-19](https://user-images.githubusercontent.com/45152336/115242817-ee153e00-a12a-11eb-8a31-69ede25b1340.png)
