### ISSUE TITLE
Oracle RDB ODBC Driver connect with Dbeaver

### ISSUE THREAD

**Issue by sovittyagi** [dbeaver/dbeaver#9711]

**Comment by sovittyagi** [comment]
@kseniiaguzeeva  Could you please help me out with this issue.

**Comment by kseniiaguzeeva** [comment]
Unfortunately I do not have good news for you. DBeaver doesn't support 32 Bit systems anymore.
The latest version with 32 Bit support is 7.1 ЕЕ https://dbeaver.com/files/7.1.0/.

**Comment by sovittyagi** [comment]
@kseniiaguzeeva Is it support 64 Bit Systems? Please Advise!

**Comment by sovittyagi** [comment]
Is it available for 64 Bit System? Please Advise!

**Comment by kseniiaguzeeva** [comment]
DBeaver supports 64 bit drivers. Oracle 64 bit driver also exists.

**Comment by sovittyagi** [comment]
Can you please help me out to connect Oracle RDB ODBC driver 64 bit
Local/System DSN with Dbeaver. If you can provide me the steps that would
be great help for me.

Thanks in Advance

**Comment by uslss** [comment]
@sovittyagi ,
seems that driver could be found [here.](https://www.oracle.com/database/technologies/rdb-related-products-downloads.html)
Unfortunately, we've got no special documentation on how to install it.

**Comment by sovittyagi** [comment]
@uslss  - I already have this driver in my machine and i have setup DSN with Oracle RDB ODBC Driver with my DB connection but i need know how i can connect Oracle RDB ODBC with Dbeaver. Please Advise!

**Comment by kseniiaguzeeva** [comment]
Please try to
1. open New Database Connection wizard (The button in upper toolbar or Database>New Database Connection in Main menu),
2. select ODBC driver there
3. fill necessary fields.

![dbeaver_1uFEwAmW2I](https://user-images.githubusercontent.com/51405061/93074325-d9e8fa00-f68c-11ea-9aae-7808e1f6a55a.png)

**Comment by sovittyagi** [comment]
@kseniiaguzeeva  Not that option not useful to connect Oracle RDB ODBC Driver connections. Please refer original question and share the connection steps to connect for same. Thanks in Advance for help!

**Comment by sovittyagi** [comment]
@kseniiaguzeeva  For our Data Base work we are using excel macro and which used ODBC Data Source 64 Bit Driver (Oracle RDB ODBC Driver) to connect our DB. But i got to know about this tool and think if we can connect through this utility. So can you please help me to connect through with it. Thanks
![ODBC RDB Driver](https://user-images.githubusercontent.com/68591302/93096416-fbb0a400-f6c1-11ea-84e2-540ae1f8c0d2.PNG)

**Comment by sovittyagi** [comment]
Do you know any other method to connect DSN connection with Dbeaver. Any ODBC JDBC bridge kind of which is available as open source. Please help me out for this.

**Comment by sovittyagi** [comment]
@kseniiaguzeeva @serge-rider @tati-kru  Can someone take a look and suggest me best possible way to connect ODBC Data Source Administration 32 Bit (DSN). If Dbeaver is not the option then can you please suggest some alternative tool/method to connect through it.
