### ISSUE TITLE
UI Issue: Filter History view is unusably tiny

### ISSUE THREAD

**Issue by machty** [dbeaver/dbeaver#9712]
#### System information: 
- Operating system (distribution) and version: macOS 10.14.6
- DBeaver version:  7.2.0.202008302047
- Additional extensions

#### Connection specification:
- Database name and version: Postgres 12
- Driver name: n/a
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : n/a

#### Describe the problem you're observing:

When inspecting the Data tab of a table, when I click the Filter History button, it appears to open a list of previous filters but the size of the text is about a pixel tall rendering the UI unusable. Also, and maybe this is minor / unrelated, but it seems weird that the system context menus (i.e. File, Edit, Navigate, etc) disappear when the UI is open.

Here's video demonstration: https://machty.s3.amazonaws.com/ia/to_s3_uploads/DBeaverFilterBug.mp4

#### Steps to reproduce, if exist:

Open a table, go to Data tab, enter a filter expression e.g. `id = 1`, press enter, then tap the downward-facing error by the filter text field with alt text "Filter History"

#### Include any warning/errors/backtraces from the logs
I don't see any errors in the logs.

**Comment by uslss** [comment]
@machty , in CE version, filters history saved until restart. Could you check if the filter's history is shown if you enter some expression and then change it?

**Comment by machty** [comment]
I went to a table, typed `id = 1`, pressed enter, then changed to `id = 2` , enter, all the way up to 10. No change in the appearance. Yet, if I open it and press enter, it does appear to select and load the previous filter, but the UI itself is unusable and doesn't display clickable/selectable filters.

**Comment by uslss** [comment]
@machty is it still actual for you against 7.3.1?

**Comment by machty** [comment]
@uslss Yes, indeed, it appears to be fixed in 7.3.1! Screenshot:

![image](https://user-images.githubusercontent.com/81818/102782445-5ca5e300-4367-11eb-9b41-ab9075a05744.png)
