### ISSUE TITLE
Unable to download any drivers from repos.

### ISSUE THREAD

**Issue by Panguaneta** [dbeaver/dbeaver#9715]
#### System information: 
- Operating system:
Windows 10 x64 2004 (build 19041.450)
- DBeaver version
7.2.0.202008302047
- Additional extensions
none

#### Connection specification:
- Database name and version
Informix on Microsoft ODBC

- Driver name
DBeaver ODBC 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
Error trying to download any driver from the DBeaver repo.
Error is: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
unable to find valid certification path to requested target

#### Steps to reproduce, if exist:
Try to make a new ODBC connection

**Comment by uslss** [comment]
hi @Panguaneta ,
cannot reproduce the issue. Could you provide steps to reproduce?
thanks in advance

**Comment by Panguaneta** [comment]
Installed the program. Make a new connection. Select ODBC. type the odbc name, user and password. try to connect. Driver settings form appears. click on Download button. Error displayed in screenshot.
![Immagine 2020-09-14 090204](https://user-images.githubusercontent.com/56425452/93054032-0428c080-f669-11ea-96fc-42662cf4438e.png)

**Comment by Panguaneta** [comment]
Nevermind,
Solution founded.
The repo is not on the classical 80 or 443 port.

**Comment by kseniiaguzeeva** [comment]
Good!
