### ISSUE TITLE
closed connection

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#9716]
dbeaver 7.2.0
postgresql 12

1. Open table->data tab
2. after 10 minutes trying to enter data to this table. 

I press SAVE button and see this message

![изображение](https://user-images.githubusercontent.com/61137576/92456138-fb08a100-f1db-11ea-86be-91365089dfad.png)
![изображение](https://user-images.githubusercontent.com/61137576/92466291-52613e00-f1e9-11ea-8f68-716a088786cd.png)

as a solution when trying to enter data, display a message - You need to update the table data! Want to do it?

**Comment by hiperjp** [comment]
same here and is an annoying behaviour, it feels like dbeaver 7.2.0 is slower than 7.1.x branch.

**Comment by detkliff** [comment]
> 
> 
> same here and is an annoying behaviour, it feels like dbeaver 7.2.0 is slower than 7.1.x branch.

for this reason there is no desire to by enterprise version. I hope a more stable version will be developed. Because current version does not fit to  enterprise developement.

**Comment by uslss** [comment]
Hi @detkliff ,
could you try to change Keep-Alive value in connection properties to non-null and write back if it helps or not? Thanks in advance
![image](https://user-images.githubusercontent.com/31996417/92582354-885dfb00-f299-11ea-9e31-ea565bd7b177.png)

**Comment by detkliff** [comment]
> 
> 
> Hi @detkliff ,
> could you try to change Keep-Alive value in connection properties to non-null and write back if it helps or not? Thanks in advance
> ![image](https://user-images.githubusercontent.com/31996417/92582354-885dfb00-f299-11ea-9e31-ea565bd7b177.png)

Yes, this option help me, but for one connection only. In my Dbeaver more than 50 connections. It would be nice  if it was a global option.

**Comment by uslss** [comment]
Close this issue as solved.
Improvement is created

**Comment by D3SL** [comment]
> same here and is an annoying behaviour, it feels like dbeaver 7.2.0 is slower than 7.1.x branch.

Agreed. When I first started using DBeaver a few months ago it was fast, responsive, and reliable. Since at least 7.1.5 if not somewhat earlier however it's become far more sluggish and constantly throws errors where before it would work seamlessly, to say nothing of interface changes that have made even something as basic as cancelling a query a multi-popup exercise in frustration.

I'm considering digging out an old installer for ~7.1.0 and checking back in when 7.3.0.is out.
