### ISSUE TITLE
Navegation window

### ISSUE THREAD

**Issue by jldmatwork** [dbeaver/dbeaver#9718]
This request will solve the problem of finding connected DB.

The solution is simple: Adding a filter (dropdown list) in Navigation window that allows you to choose between "Connected DB" and "all DB".

This two option must be there by default.
Phase 2 of this feature:
Add another option at the end of the drop down list to "create new filters" if you click there another window opens and let you add a filter (maybe a regular expression) and also let you select if you want to filter by connected status or not.
Then this "custom filter" must be test/validated and than ask for a name to show and also store in file for persistence.

**Comment by serge-rider** [comment]
Done.
Beside "show connected only" option "filter objects of specific type" was added.

![image](https://user-images.githubusercontent.com/6398845/93690235-cf8c8d00-fade-11ea-8d54-859e55013e53.png)

**Comment by kseniiaguzeeva** [comment]
Implemented
