### ISSUE TITLE
Feature request: Wizard to re-order columns in a table and preserve data

### ISSUE THREAD

**Issue by ScotterMonk** [dbeaver/dbeaver#9720]
I can see the "engine" of my proposed wizard merely being some queries that:
(1) Duplicate the table structure and data to temp table.
(2) Delete original table.
(3) Recreate original table but with new column order.
(4) Copy all the data from temp table into new version of original table.
Notes:
(a) Auto-incrementing columns will require special treatment. Loop through data doing multiple inserts? I'm not expert enough to know.
(b) Of course an interface so the user can pick modified column order for the resulting table.
Seems do-able and something many want.
Ideas? Possible?

**Comment by kseniiaguzeeva** [comment]
Which database do you use? 
1. It is already implemented in MySQL:
1.1 go to Columns tab of table Properties, 
1.2 select a column
1.3 press arrows on the bottom toolbar
![dbeaver_SUpEUrgJv3](https://user-images.githubusercontent.com/51405061/92701314-7ee79800-f358-11ea-90c3-b58f9eeeb218.png)
2. You can temporarily change the order of the columns (If you want to save changes in table view after its reopening, press **Save filter settings** button on the right from upper filter field)
a) DND them in ResultSet of SQL Editor or in Data Editor
![1](https://user-images.githubusercontent.com/51405061/92702078-7348a100-f359-11ea-92d4-c0ac7a6117ec.gif)
b) Change order in **Customize filters...** menu (press the button on the right from upper filter field)
![FsZXwYeKNB](https://user-images.githubusercontent.com/51405061/92702237-a1c67c00-f359-11ea-9765-f08058915001.gif)
c) you can also pin necessary columns. Select Pin column in the column header context menu
![mspaint_Rxa21Bfi7W](https://user-images.githubusercontent.com/51405061/92703257-b8210780-f35a-11ea-9512-9b42409693bd.png)

**Comment by ScotterMonk** [comment]
Postgres.

Scott Swain
512-817-6806
https://ClearSay.net
https://OceanMedia.net
Media & Mediation since 1995

**Comment by kseniiaguzeeva** [comment]
Thank you. Will the way described in cl. 2 suit you?

**Comment by ScotterMonk** [comment]
YES! Thank you! You made my life sooo much easier!

Scott Swain
512-817-6806
ClearSay.net <http://clearsay.net/>
OceanMedia.net <http://oceanmedia.net/>
Mediation & Media Creation
since 1995

**Comment by kseniiaguzeeva** [comment]
Great!
