### ISSUE TITLE
Display DB

### ISSUE THREAD

**Issue by adminsyszg** [dbeaver/dbeaver#9721]
#### System information: 
Windows 7
DBeaver 7.1.5

#### Connection specification:
Postgresql version 9.6 -12.3

#### Describe your question:
Good day.
DBraver does not display postgreSQL databases for which it is forbidden to connect: ALTER DATABASE database_name ALLOW_CONNECTIONS false, but pgadmin displays them, and  query select * from pg_database also displays all databases on the server. How to enable display of hidden databases?

**Comment by uslss** [comment]
Hi @adminsyszg ,
please try to check the highlighted option in connection properties.
![image](https://user-images.githubusercontent.com/31996417/92581579-89425d00-f298-11ea-9fec-91a57003ce2c.png)

**Comment by adminsyszg** [comment]
> 
> 
> Hi @adminsyszg ,
> please try to check the highlighted option in connection properties.

Hey @uslss  Thanks for the answer, but this checkbox includes displaying all available databases, but not those described in the post. Without this checkbox, the base that matches the username is shown (default postgres behavior)

**Comment by uslss** [comment]
@adminsyszg thanks for clarification :)
seems it is not implemented, mark issue as a feature request.
thanks for suggestion

**Comment by akilovich** [comment]
Added checkbox in connection configuration and in global Postgre driver preferences.

**Comment by uslss** [comment]
verified
