### ISSUE TITLE
DBeaver asks twice for SSH password

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#9723]
[Sorry if I put this issue to a wrong category but I don't know if it should be a bug report, feature request or a question]

When I have a MySQL connection set via SSH without a saved password (but with a saved password for the database) then DBeaver asks me twice for the same SSH password. The first dialog window is titled "Specify password for SSH Tunnel" with message "User Credentials" and the second is "Password Required" with message "Keyboard interactive authentication required for user@address.x".

The funny thing is that the first password is not used at all, I can enter any invalid password or just empty string and the connection is established if I provide the second password correctly.

I'd like to get rid of the first unnecessary password prompt and just have one appear - is there a way to do it?

**Comment by uslss** [comment]
Thanks for the bug report

**Comment by kseniiaguzeeva** [comment]
verified
