### ISSUE TITLE
Trying to save MySQL password without including username@LinuxBoxName.

### ISSUE THREAD

**Issue by bsthinker** [dbeaver/dbeaver#9724]
When I create a MySQL connection and click save password locally, then test connection, the program sends my username in the form of username@localboxname.  If I don't click on save locally, the credentials are sent without append @localboxname.  But I keep having to enter my password.

How do I save the password and strip off the @localboxname?

Thanks,
Brent

**Comment by uslss** [comment]
seems it is mysql behaviour, not DBeaver. DBeaver sends username only in any case.

**Comment by uslss** [comment]
there aren't any updates for a long time.
Issue closed. If it is still actual for you - feel free to reopen it
