### ISSUE TITLE
[Hive] Use SQL to limit fetch size is not working

### ISSUE THREAD

**Issue by akizminet** [dbeaver/dbeaver#9725]
I am running Hive on Spark.
I need to use hive with option `hive.fetch.task.conversion=none` . So all SQL commands will run within an Apache Spark application.  Howerver, the Data Editor will run `SELECT * FROM [table]` without `LIMIT` clause and this take a long time to run this job. 
Therefore, I have enabled `Use SQL to limit fetch size` in Data Editor setting but the `SELECT *` query still didn't append `LIMIT` clause. I think this is a bug of Dbeaver.

**Comment by uslss** [comment]
Hi @akizminet ,
unfortunately, we've got no environment to test for now. Cannot reproduce it against postgresql.
Could you check that there is no limit clause in Query Manager? Thanks in advance
![image](https://user-images.githubusercontent.com/31996417/92580962-c0643e80-f297-11ea-8f3d-778ce3866021.png)

**Comment by akizminet** [comment]
@uslss Yeah. I have also tested with PostgreSQL and it worked well. PostgreSQL SELECT query had LIMIT clause. Hive still didn't have.

**Comment by uslss** [comment]
thanks for the bug report and clarification

**Comment by akilovich** [comment]
Fixed.

**Comment by uslss** [comment]
verified
