### ISSUE TITLE
How do I use External formatter and Sql workbench/j formatter

### ISSUE THREAD

**Issue by MoliYe** [dbeaver/dbeaver#9733]
#### System information: 
- Operating system (distribution) and version : Windows 7
- DBeaver version : 7.0.5

#### Connection specification:
- Database name and version : Greenplum  6.2

#### Describe your question:
When write sql,I want it will be formated with my own define, and I find the SQL formatter function,and it includes External formatter and Sql workbench/j formatter,how can I use these two function,Is there any examples or docunments?  Waiting for you~

**Comment by kseniiaguzeeva** [comment]
For Sql workbench/j formatter:
1. Install the formatter
2. Open DBeaver>Editors>SQL Editor>SQL Formatting
3. Select Sql workbench/j formatter
4. Enter path to Sql workbench/j formatter
5. Apply the changes
6. Open SQL Editor
7. Enter SQL Expression
8. Press Ctrl+Shift+F (or select Format>Format SQL in DQL Editor context menu)
![dbeaver_XGfiKCLJmn](https://user-images.githubusercontent.com/51405061/92700238-43000300-f357-11ea-836e-24ad5f28d956.png)

The query will be formated according default Sql workbench/j formatter settings.

Please note, DBeaver doesn't apply custom settings of Sql workbench/j formatter

**Comment by MoliYe** [comment]
How about External formatter？How to use it step by step，Thanks a lot.

**Comment by MoliYe** [comment]
where can I use the custom settings formatter?

**Comment by kseniiaguzeeva** [comment]
You can use only default Sql workbench/j/external formatter settings in DBeaver.

For external formatter:
1. Install a formatter
2. Open DBeaver>Editors>SQL Editor>SQL Formatting
3. Select **external formatter**
4. Enter path to the formatter in **Command line** field (variable can be used there)
5. Sometimes you should enable **Use temp file** option and write ${file} in **Command line**
6. Apply the changes
7. Open SQL Editor
8. Enter SQL Expression
9. Press Ctrl+Shift+F (or select Format>Format SQL in DQL Editor context menu)

**Comment by MoliYe** [comment]
I have tried the Sql workbench/j formatter, but still don't know how to use external formatter, when use external formatter, how can I write the Command line? Is there any examples?

**Comment by MoliYe** [comment]
> You can use only default Sql workbench/j/external formatter settings in DBeaver.
> 
> For external formatter:
> 
> 1. Install a formatter
> 2. Open DBeaver>Editors>SQL Editor>SQL Formatting
> 3. Select **external formatter**
> 4. Enter path to the formatter in **Command line** field (variable can be used there)
> 5. Sometimes you should enable **Use temp file** option and write ${file} in **Command line**
> 6. Apply the changes
> 7. Open SQL Editor
> 8. Enter SQL Expression
> 9. Press Ctrl+Shift+F (or select Format>Format SQL in DQL Editor context menu)

Would you please give me a example how to write the Command line? Many thanks

**Comment by kseniiaguzeeva** [comment]
Sorry for the late response. Just write a path to a formatter on your computer.

**Comment by bbkane** [comment]
It's worth noting that the external tool should be prepared to read the SQL to format from `stdin`.

As a complete (but useless) example, here's a "formatter" I wrote that just appends the string  "// hi" to the query:

```python3
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys

sql = sys.stdin.read().rstrip()
print(sql, "// hi", end="")
```
I created this file at `/Users/bbkane/test_sql_format.py` and I have made it executable with `chmod +x /Users/bbkane/test_sql_format.py`

I then went to DBeaver>Editors>SQL Editor>SQL Formatting and change the settings:

![image](https://user-images.githubusercontent.com/6081085/105619618-3382d300-5da9-11eb-943d-ff886bfa037c.png)

Now, when I format, I see the following:

![image](https://user-images.githubusercontent.com/6081085/105619626-4c8b8400-5da9-11eb-8742-3abac9569060.png)

Hope that helps anybody else work with this seemingly undocumented issue. Happy to submit a PR if the maintainers want this example in their docs.

**Comment by CarbonChauvinist** [comment]
Just chiming in to say that, for my case at least on windows using the latest 21.1.4 version, I needed to do some escaping of the path in order to get this to work. Leaving this here in case it helps others.
![sqlparse_dbeaver_path_escaping](https://user-images.githubusercontent.com/21365869/128246550-6c0d1338-404b-4da0-92b6-4d0025eb2738.PNG)

Edit: Actually it turns out using slash character `/` in the path for Windows works, but if you try and use backslash `\` (which most will probably try to do since that's Windows path separator) won't work:
i.e
`C:/Users/myusername/Miniconda3/envs/dbeaver_formatter/python.exe ...` works as path
but
`C:\Users\myusername\Miniconda3\envs\dbeaver_formatter\python.exe ...` doesn't work as path

**Comment by SSSDNSY** [comment]
> 4\. workbench/j

you are awesome!

**Comment by Reyesnes** [comment]
Someone please do a step by step on how to install this on Windows.
