### ISSUE TITLE
Navigator icons missing

### ISSUE THREAD

**Issue by monsieurrouge2** [dbeaver/dbeaver#9735]
In the navigator I don't see separate icons for databases, tables, views, indexes, etc. They all have the same anonymous folder icon. Columns do have icons, see screenshot. This is also happening in other database connections.

Using DBeaver 7.2.0 (portable) on Windows 2019 Server.
I tried 7.1.3, this has the same issue. Even on Windows 2008 Server.

I have worked with the portable versions for years, but have never seen this.

Does anyone of you have a clue about what is going on?

![dbeaver navigator icons](https://user-images.githubusercontent.com/19549593/92702896-05e54200-f352-11ea-8ed5-408a420d954c.png)

**Comment by uslss** [comment]
Looks weird. How do you install new version? 
You should remove previous version before install, not just replace it

**Comment by monsieurrouge2** [comment]
It is a portable install, so not much installing.
Furthermore, I don't have other versions running/installed.

**Comment by monsieurrouge2** [comment]
does anyone have a clue?

**Comment by monsieurrouge2** [comment]
OK, found out that my portable directory is an UNC folder.
I have to run DBeaver with a -vm argument. Windows screws up the present working directory because it cannot deal with UNC paths, and changes the present working directory to C:\Windows.

**Comment by tati-kru** [comment]
Thank you for the explanation.
