### ISSUE TITLE
Result of auto-commit on Network Failure

### ISSUE THREAD

**Issue by WustlRob** [dbeaver/dbeaver#9738]
#### System information: 
- Operating system (distribution) and version Server CentOS, Client: Windows 10.0.18363
- DBeaver version 7.2.0.202008302047

#### Connection specification:
- PostgreSql 9.6

#### Describe your question:
- A delete query against large database takes about 24 hours to process.  Had a network failure (VPN timed out) and I can see after reconnecting that the query is still "active".  Auto-commit is on.  So the question is: is this query continuing or rolling back?  If continuing, will it auto-commit?  I know time will tell, but it would be nice to have it addressed online for reference to others.

DBeaver error message on connection failure: SQL Error [08001]: The connection attempt failed.

**Comment by uslss** [comment]
Hi @WustlRob ,
Mostly it depends on the database and its settings. Most likely it will not auto-commit.

**Comment by WustlRob** [comment]
The disconnected query was still showing active after three days.  Sysadmin killed it, so we never really got a real life answer.  We've changed our SOP to PuTTY into server and use "screen" to prevent this situation in the future.  Not all knowledge is obtainable. :)  If no one has any additional info, This can be closed.
