### ISSUE TITLE
java.lang.NullPointerException 

### ISSUE THREAD

**Issue by dddddddddddddds** [dbeaver/dbeaver#9741]
When I want import .erd file, so displayed this error: java.lang.NullPointerException

**Comment by kseniiaguzeeva** [comment]
Please write steps to reproduce it

**Comment by dddddddddddddds** [comment]
Error 1)
1) Create ER diagram.
2) Export ER diagram.
3) Open ER diagram on other PC with program DBeaver.
Result: java.lang.NullPointerException

Error 2)
1) Create ER diagram.
2) Export ER diagram.
3) Import ER diagram on other PC (in DBeaver).
Result: 
eclipse.buildId=unknown
java.version=1.8.0_232
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_GB
Command-line arguments:  -os linux -ws gtk -arch x86_64
org.jkiss.dbeaver.model
Warning
Fri Sep 11 09:49:03 CEST 2020
Datasource 'oracle_thin-1744dd18c12-204929726a111362' not found

**Comment by LonwoLonwo** [comment]
@dddddddddddddds what Dbeaver version are you using?

**Comment by dddddddddddddds** [comment]
![image](https://user-images.githubusercontent.com/71123128/93076888-52998780-f688-11ea-8d15-89e9f515aa97.png)
I use, latest Version 7.2.0.202008302047.

**Comment by LonwoLonwo** [comment]
@dddddddddddddds Problem still not clear. Any [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by uslss** [comment]
There are not any updates on issue for a long time. 
It is closed.
If it is still actual for you - feel free to reopen it

**Comment by paidgeek** [comment]
Hello,

I stumbled upon this issue looking for details on how to share ERDs build in DBeaver. Now I believe this issue applies to me and my team..

This java.lang.NullPointerException issue appears when my teammate tries to open a DBeaver ERD created by me on my local machine. Below is the error window I was about to screenshot.
![DBeaver_Error_Window_20201217](https://user-images.githubusercontent.com/76182173/102537141-2ff48180-4070-11eb-9d8b-144443695f9b.JPG)

Other than the data-source id value in the XML, I am not sure what is different between our two instanced of DBeaver CE (see below).
![DBeaver_Error_Window_20201217](https://user-images.githubusercontent.com/76182173/102537330-6d590f00-4070-11eb-9f26-c039487bff50.JPG)

ERD File: [EDW DIM set 2b.zip](https://github.com/dbeaver/dbeaver/files/5711849/EDW.DIM.set.2b.zip)

Regards.

-PG

**Comment by serge-rider** [comment]
@paidgeek You can't jsut copy ERD file. It refers to the particular project connection/entities. So you need to export/import entire project.
