### ISSUE TITLE
DB Navigator -> db context menu -> New SQL Editor

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#9747]
Given the potentially rather deep tree to be opened before reaching a table, it would be nice to have a
New SQL Editor
in the context menu of a database already.
To me. it's more natural to right click and use the context menu that to select the DB and then click the button in the toolbar far away.

**Comment by uslss** [comment]
Hi @2019-05-10 ,
New SQL Editor is available in Connection context menu. Also it could be opened from the toolbar/main menu/using f3 button. Doesn't it solve your problem?
![image](https://user-images.githubusercontent.com/31996417/92931557-4c1ecc00-f44c-11ea-9ab9-b4a5180dec68.png)

**Comment by 2019-05-10** [comment]
No, not exactly -- it's basically the same issue: I have to go elsewhere to complete the operation.
Here, in both cases, a new dialog appears requiring me to move the mouse over to at least hit the "New Script" button.
Additionally, it does use the default DB, which is not necessarily the one I want to run a query against. So, yet another trip across the screen ;)

**Comment by uslss** [comment]
thanks for clarification and suggestion :)

**Comment by serge-rider** [comment]
To avoid main context menu over-complication I've added a sub-menu for SQL editor commands:
![image](https://user-images.githubusercontent.com/6398845/97306869-130db000-1870-11eb-96e0-335d599cd741.png)

**Comment by kseniiaguzeeva** [comment]
Implemented

**Comment by Zahoor-Ahmed** [comment]
@serge-rider This is exactly what I was looking for, how you added "New SQL Editor" Ctrl+] to the context manu. How can i do this on my laptop. And is it possible to keep it as 1st option instead of 3rd..?
![image](https://user-images.githubusercontent.com/72337020/98654342-427fea80-234f-11eb-93fc-22369289c58a.png)

**Comment by 2019-05-10** [comment]
"Additionally, it does use the default DB, which is not necessarily the one I want to run a query against. So, yet another trip across the screen ;)"

This still true, and why I requested it on the DB node, not just the connection, which will most likely expand to more than one DB.

**Comment by kseniiaguzeeva** [comment]
Could you please create a new enhancement/feature request for your 2 last comments?

**Comment by 2019-05-10** [comment]
Uhm, my last comment only repast why I opened the ticket in the first place.
So, the ticket should be reopened rather that me just copying it again.

**Comment by serge-rider** [comment]
I think we can just add context menu  SQL Editor to databases/schemas as well.

**Comment by serge-rider** [comment]
Done. Now SQL editor sub-menu is shown on databases/schemas so default database/schema will be set according to navigator selection.

**Comment by kseniiaguzeeva** [comment]
Verified.
Note: the feature works correctly with enabled option **Open separate connection for each editor** (Settings>SQL Editor)
![Screenshot 2021-01-19 at 12 28 18](https://user-images.githubusercontent.com/51405061/105014804-ea9de800-5a51-11eb-9dc9-eedb10d7cb1f.png)
