### ISSUE TITLE
Still getting "No unique key defined" after version 7.0.2 even after fix in c591ce3

### ISSUE THREAD

**Issue by KellyKimbleNotions** [dbeaver/dbeaver#9748]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version Any version after 7.0.2
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version Basis
- Driver name Generic - com.basis.jdbc.BasisDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No 

#### Describe the problem you're observing:
I can't upgrade from my version 7.0.2 without losing the ability to save records. Although it was reported to have been fixed in "c591ce3", the problem still exists for my database. If I upgrade to a newer version (7.2.0 is the latest I tried), it reports that there is no unique key defined when I try to update any record but if you look at the table information, the unique keys are clearly defined.  I have to reinstall version 7.0.2 to get it working again.

#### Steps to reproduce, if exist:
Open any table with a Unique Key.  Modify a record then try to save it.

#### Include any warning/errors/backtraces from the logs
 There are none.
![Reports No Unique Key](https://user-images.githubusercontent.com/49687785/92937509-68eddc00-f419-11ea-8ca9-31749e0d594d.png)
![Shows Unique Key](https://user-images.githubusercontent.com/49687785/92937511-69867280-f419-11ea-9cb2-4748f72505cb.png)

**Comment by KellyKimbleNotions** [comment]
Still broken in 7.2.1

**Comment by uslss** [comment]
Hi @KellyKimbleNotions ,
sorry for the late response.
Unfortunately, we've got no env to test it, could you check if it is still reproducible against 7.2.3?
Thanks in advance

**Comment by KellyKimbleNotions** [comment]
I just downloaded 7.2.3 and tried it.  It is still broken.  Is there anything I can do that would help?  Additional logging or anything?

**Comment by KellyKimbleNotions** [comment]
I tried every version up until 7.3.3 and 7.3.3 finally fixed the issue.
