### ISSUE TITLE
CockroachDB: Role-based access control code generation

### ISSUE THREAD

**Issue by kai-niemi** [dbeaver/dbeaver#9749]
#### System information: 
- Operating system (distribution) and version: os/x 10.15.6 (client)
- DBeaver version: 7.2.0
- Additional extensions: n/a

#### Connection specification:
- Database name and version: CockroachDB v20.1.5 on Ubuntu 18.04.5 LTS
- Driver name: CockroachDB 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

Creating or modifying users, roles and grants on privileges fail when using the CockroachDB adapater. For example, when creating a role, DBeaver passes the role attributes NOINHERIT and NOSUPERUSER that are not valid options in CockroachDB.

Example of generated SQL:

`CREATE ROLE db_admin NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN PASSWORD 'password';`

![92764694-ede2e200-f394-11ea-96c0-f204615dd4ab](https://user-images.githubusercontent.com/53807125/92940670-a8cfb600-f44f-11ea-8829-f18a7d2fca47.png)

In addition, attempting to delete an existing role (occationally) fail with:

![92765102-54680000-f395-11ea-95fc-8203d38e548d](https://user-images.githubusercontent.com/53807125/92940818-dcaadb80-f44f-11ea-83ec-31f6f2f5da9c.png)

CockroachDB does not support `pg_total_relation_size()`. 

#### Steps to reproduce, if exist:

1. Connect to a CockroachDB database using the adapter
2. Enable the advanced view
3. Create a new role, press save.

and

1. Connect to the CLI console of CockroachDB
2. Execute: CREATE ROLE test;
3. Attempt to delete role 'test in DBeaver

#### Include any warning/errors/backtraces from the logs
n/a

**Comment by akilovich** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
NOINHERIT and NOSUPERUSER is removed from the generated SQL
