### ISSUE TITLE
How to use Windows Authentication to connect to MS SQL server?

### ISSUE THREAD

**Issue by blangsmgi** [dbeaver/dbeaver#9751]
#### System information: 
- macOS Mojave 10.14.6
- DBeaver Version 7.2.0.202008302047

#### Connection specification:
- MS SQL using the automatically downloaded drivers for the same. Current version appears to be 8.2.0.jre8 and 8.2.0 x64

#### Describe your question:
I'm trying to use Windows Authentication to connect to a MS SQL server. When I select that option, the username and password fields become unavailable. I receive the following Connection error when I try to connect.

![image](https://user-images.githubusercontent.com/48220374/92957331-3514b580-f41d-11ea-8c6c-6de005f6c89c.png)

How do I set the username & password to use for the connection?

**Comment by kseniiaguzeeva** [comment]
Windows Authentication uses OS user credentials to login. That's why the fields are not active. 
Please check host and port fields. What is written there?

**Comment by blangsmgi** [comment]
The host field has the name of the server I'm connecting to, and the port is 1433.
As I am on a Mac, and not part of the Windows domain, my macOS credentials don't work for Windows Authentication

**Comment by kseniiaguzeeva** [comment]
I did not see you use Mac. Windows auth is not available there. Please use NTLM authentication. You will need to enter user name and password.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
