### ISSUE TITLE
Cursor left on commented line after active line = script is ignored (postgres)

### ISSUE THREAD

**Issue by mbelvadi2** [dbeaver/dbeaver#9753]
#### System information: 
- Operating system (distribution) and version, DBeaver version
Dbeaver 7.2.0 on Windows 10 Pro.
- Additional extensions - none

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
My database is a postgres via ssh tunnelling but I don't think that's relevant to this problem.

#### Describe the problem you're observing:

I have a script file that is a series of paired lines, to DELETE duplicate lines, followed by and ALTER TABLE to add a unique constraint so I don't ever get duplicates again (cleaning up past errors).
I've put the whole thing into an SQL Editor window with every line commented out except the one I want to run at the moment, eg.
--DELETE FROM  oclc_ocn_isbn where ctid not in (SELECT min(ctid) FROM  oclc_ocn_isbn GROUP BY  isbn, ocn );
--ALTER TABLE ONLY  public.oclc_ocn_isbn ADD CONSTRAINT oclc_ocn_isbn_key UNIQUE ( isbn, ocn );
--DELETE FROM  oclc_lcc where ctid not in (SELECT min(ctid) FROM  oclc_lcc GROUP BY  isbn, lcc, ocn );
--ALTER TABLE ONLY  public.oclc_lcc ADD CONSTRAINT oclc_lcc_key UNIQUE ( isbn, lcc, ocn );
DELETE FROM  oclc_edition_ocns where ctid not in (SELECT min(ctid) FROM  oclc_edition_ocns GROUP BY  isbn, edition_ocn, ocn );
--ALTER TABLE ONLY  public.oclc_edition_ocns ADD CONSTRAINT oclc_edition_ocns_key UNIQUE ( isbn, edition_ocn, ocn );

With this code, only the last DELETE line is uncommented, so it should run.
However, I find  that if I happen to have left my input cursor sitting at the end of the commented line after the active line, dbeaver doesn't notice the uncommented line and absolutely nothing happens when I click on the little orange Execute triangle.
The moment I realize it's not running, I click to put my cursor anywhere on the uncommented line, then hit the triangle again, and it starts running just fine.

Note that I don't actually have any of the code "selected". The cursor is just sitting at the end of a commented line as if I were going to type more there.

#### Steps to reproduce, if exist:
I'm not sure I can produce 100% repeatable steps regardless of database. When I test this against one of my sqlite databases,  I actually get an error that says: "SQL Error: The prepared statement has been finalized" instead of doing nothing at all.  Also (again in my postgres database) if the cursor is on a commented line above, rather than below, the active line, the active line runs as desired.

#### Include any warning/errors/backtraces from the logs
Nothing recorded about this in the logs

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.
![LEP2QjpR9t](https://user-images.githubusercontent.com/51405061/93081270-af506e80-f697-11ea-8894-61b8b91d6847.gif)

**Comment by ShadelessFox** [comment]
Hello, @mbelvadi2, sorry for late response.
Actually this is correct behavior - queries are separated using `;` symbol. In your example, uncommented statement has `;` at the end, so no comments after that statement will be appended to query (and executed). This is why you can execute query successfully if your cursor is placed at uncommented statement or above it.
You can remove semicolon to proceed without problem.

**Comment by kseniiaguzeeva** [comment]
Please ask to reopen the ticket if you think the bug still exists.

**Comment by mbelvadi2** [comment]
I would like to re-open this. I don't think ShadelessFox understood the problem correctly. I understand very well that the uncommented line has a semicolon and execution should stop there. What he/she did not address is why the location of my input cursor should matter to what gets executed. To repeat, if my cursor is at the very bottom line (which is commented out), the uncommented line that has the semi-colon does NOT execute at all.  If the execution rule truly is as he/she describes, that dbeaver starts with the very first line of the query in the editor box, and looks for whatever query is uncommented AND concludes with a semicolon and stops there, then the fact that my cursor is sitting on the last, commented, line should not in any way affect the execution.  Yet it does, quite repeatably.

**Comment by p91paul** [comment]
Where your cursor is does matter. Dbeaver will execute the statement *under your cursor*, so if you put yourself on a commented line there is nothing to execute.

To do what you are trying to do, you could actually just avoid commenting the lines you don't want, because you just have to put your cursor on the one line you want to run. No other lines will be launched (unless you use the "run script" button, which actually runs all the scripts in the editor)

**Comment by kseniiaguzeeva** [comment]
@p91paul Thank you again for help with the answer.

@mbelvadi2 Please ask if you still need more details

**Comment by mbelvadi2** [comment]
> Where your cursor is does matter. Dbeaver will execute the statement _under your cursor_, so if you put yourself on a commented line there is nothing to execute.
> 
> To do what you are trying to do, you could actually just avoid commenting the lines you don't want, because you just have to put your cursor on the one line you want to run. No other lines will be launched (unless you use the "run script" button, which actually runs all the statements in the editor)

Ah, thank you! The difference between Execute Script and Execute Statement was too subtle for me to notice before.
However, it's not quite true that: " if you put yourself on a commented line there is nothing to execute".
If I put my cursor on a commented line that is ABOVE an uncommented line, and Execute Statement, the uncommented line does execute. It's only if the cursor is on a commented line BELOW the uncommented line that it does not.  
Now that I understand what's happening, perhaps I need to amend this bug report to be that statements are executing that should NOT execute when the cursor is left on a commented line above the uncommented line. According to your answer, and for user interface consistency, when using Execute Statement, nothing should execute when the cursor is on a commented line regardless of where that commented line is relative to uncommented lines in the same script file.

**Comment by p91paul** [comment]
I oversimplified when I said "so if you put yourself on a commented line there is nothing to execute."; I'm not a DBeaver developer, but I believe the script is split into statement using blank lines and/or separators, and comments are part of the nearest statement (unless a separator/blank line divides them, that is).
What you are asking does make sense for your specific use case, but if your script is

    SELECT * FROM TABLE
    WHERE X = Y AND
          --X = Z AND
          Z=K;

Running the statement while the cursor is on the comment is the most obvious thing. Of course there are going to be hedge cases, but current DBeaver behavior is quite nice in my opinion.

**Comment by kseniiaguzeeva** [comment]
@p91paul gave a good example. Yes, what you are describing is working as expected. In your case, the semicolon is part of the comment and does not stop the query execution below.

You can add blank lines between queries, because the blank line also works as a statement delimiter by default.
![Screenshot 2020-12-08 at 13 57 21](https://user-images.githubusercontent.com/51405061/101475698-c41e6480-395d-11eb-9d66-f29cf01236ee.png)

**Comment by artgoldberg** [comment]
This was helpful to me as someone encountering a "The prepared statement has been finalized" error from SQLite.
