### ISSUE TITLE
GraphMl Option to export notes when exporting ERD

### ISSUE THREAD

**Issue by Eddie-Hartman** [dbeaver/dbeaver#9754]
**Is your feature request related to a problem? Please describe.**
/issues/7067
Essentially, when exporting to graphml, it would be nice to have the option to also export notes with appropriate colors.

**Describe the solution you'd like**
Essentially, when exporting to graphml, it would be nice to have the option to also export notes with appropriate colors.

**Describe alternatives you've considered**
Exporting to a PNG, but since I am exporting from DBeaver to import into draw.io for people on my team without DBeaver to use, this isn't the best option if we want to change the diagram.

*Somewhat Irrelevant*

Draw.io currently has a sql script option for generating diagrams, but it does not link tables that have FKs right now. DBeaver is what I use to manage my databases and is just what I would prefer over creating a diagram from my db creation scripts in draw.io, but it is an alternative that I had tried.
I also called this out on the draw.io repo and plan on making a feature request there as well: https://github.com/jgraph/drawio/pull/233#issuecomment-677494010

**Additional context**
Example before export:
![image](https://user-images.githubusercontent.com/14089997/91755708-9032e680-eb99-11ea-9af8-0329c3c7bc4f.png)

After Export:
![image](https://user-images.githubusercontent.com/14089997/91755788-ae98e200-eb99-11ea-8d29-d2ea48c6af45.png)

You can see how preserving this data is important to how I'm organizing my work.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by ShadelessFox** [comment]
Implemented (also z-order is now respected):

![chrome_CVlcew3BcJ](https://user-images.githubusercontent.com/35821147/128159569-b5e9df57-44cb-44ac-8238-ecaa0d92d78a.png)

**Comment by uslss** [comment]
verified
