### ISSUE TITLE
Virtual Schemas order in Exasol

### ISSUE THREAD

**Issue by GriGrim** [dbeaver/dbeaver#9759]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 7.2.0

#### Connection specification:
- Database name and version: Exasol

#### Describe the problem you're observing:
The list of virtual schemas is not sorted.
Regular schemas are sorted properly, but virtual schemas are not sorted at all, and displayed randomly.
It is pretty hard to find any virtual schema, especially if the list is big.

#### Steps to reproduce, if exist:
Just create a few virtual schemas and take a look on their order.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.
