### ISSUE TITLE
Vertica Add comments to column

### ISSUE THREAD

**Issue by eugeneantipanov** [dbeaver/dbeaver#9760]
Hello guys!
Please, add column comments for Vertica like it done for Oracle:

- show in table view
- show in screen tips in sql redactor

I found issue 3335, but now Vertica add comment to table column
https://www.vertica.com/docs/9.3.x/HTML/Content/Authoring/SQLReferenceManual/Statements/COMMENT/COMMENTONTABLECOLUMN.htm

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion!

**Comment by ShadelessFox** [comment]
Hello, @eugeneantipanov
Adding comments to the table columns should be working. Do you have an error when you're trying to save changes? If so, can you provide log files?

**Comment by eugeneantipanov** [comment]
Hello @ShadelessFox 
> Hello, @eugeneantipanov
> Adding comments to the table columns should be working. Do you have an error when you're trying to save the changes? If so, can you provide log file?
I meant than screentip (popup) don't show correct value.
Issue 3335 was close by vertica restriction, but it is not actual now.
<img width="741" alt="screen1" src="https://user-images.githubusercontent.com/51695010/98997499-a66c0400-2545-11eb-9479-9ac15f821918.png">
<img width="612" alt="screen2" src="https://user-images.githubusercontent.com/51695010/98997529-ad931200-2545-11eb-8bea-95672e0a42fe.png">
<img width="651" alt="screen3" src="https://user-images.githubusercontent.com/51695010/98997542-b08e0280-2545-11eb-9b2b-70135ee6aa07.png">

**Comment by kseniiaguzeeva** [comment]
The similar ticket https://github.com/dbeaver/dbeaver/issues/11523

**Comment by LonwoLonwo** [comment]
Vertica columns remarks implemented in 21.0.2
Will be available [here](https://dbeaver.io/) at 2020-04-05

**Comment by uslss** [comment]
verified
