### ISSUE TITLE
Option to create new table/view in DBeaver  PostgreSQL does not show up for me

### ISSUE THREAD

**Issue by scottxu502** [dbeaver/dbeaver#9761]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 7.2.0

#### Connection specification:
- Database name and version PostgreSQL

#### Describe your question:

Sorry for such a basic issue - new to SQL/DBeaver this kind of stuff in general. Basically I looked up how to create a new table or a view on different videos/guides (right clicking on the database properties viewer usually gives a selectable option in the dropdown) but this does not show up for me. Please let me know what I'm doing wrong/how I should do it.

**Comment by kseniiaguzeeva** [comment]
I hope DBeaver is useful for you. Most probably Simple view is enabled. You should switch Navigator view to Advanced. For this:
1. Right-click a connection in DB Navigator tree
2. Select **Connection view> Advanced** in the opened context menu.
![dbeaver_AwXPtCnCdZ](https://user-images.githubusercontent.com/51405061/93197934-f6e90000-f754-11ea-94d2-e036fb2a8baf.png)
Then you can create objects via schema/object context menu
![dbeaver_Rl8hHp0OQI](https://user-images.githubusercontent.com/51405061/93198345-927a7080-f755-11ea-84fa-60c5244d3a6d.png)
Or you can double-click a schema in DB Navigator tree and then create objects in the opened Object Editor
