### ISSUE TITLE
Two 'Download driver files' windows open simultaneously when connecting to PostgreSQL or CockroachDB for the first time 

### ISSUE THREAD

**Issue by akilovich** [dbeaver/dbeaver#9762]
#### System information:
- Operating system (distribution) and version: macOS 10.15.5
- DBeaver version: 7.2.0, 7.2.1
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 12, CockroachDB 2.0.5
- Driver name: n/a
- Do you use tunnels or proxies (SSH, SOCKS, etc)?:  SSH tunnel while connecting to CockroachDB

#### Describe the problem you're observing:

Two 'Download driver files' windows open simultaneously when connecting to PostgreSQL or CockroachDB for the first time.

#### Steps to reproduce, if exist:
1. Use fresh installation of the Beaver, or delete the folder with drivers, or never download Postgres driver in the first place
2. Open New Database Connection wizard
3. Select Postgres or Cockroach, hit 'Next'
4. Two 'Download driver files' windows will pop up, one window behind the other.

**Comment by akilovich** [comment]
I just found out that the same problem occures with Greeenplum.

**Comment by Matvey16** [comment]
Fixed and verified.
