### ISSUE TITLE
Show all the tables that will be deleted

### ISSUE THREAD

**Issue by zarpelon** [dbeaver/dbeaver#9765]
![image](https://user-images.githubusercontent.com/264762/93128873-8388b500-f6a6-11ea-9a90-6faa640d8e95.png)

**Comment by zarpelon** [comment]
Hey, If possible, translate too the messages to pt_BR.

"Tem certeza que deseja deletar as tabelas nametable1, nametable2, nametable3"

**Comment by akilovich** [comment]
We've decided to choose a somewhat different and more general approach. In case of deleting more than one object, there will be a table in the dialog describing all the objects you're trying to delete. It won't be possible to delete objects from different databases in one batch, though.

**Comment by kseniiaguzeeva** [comment]
Implemented in 7.2.2. The message differs a little now, that's why it is not translated.
