### ISSUE TITLE
CTE intellisense\Auto Complete

### ISSUE THREAD

**Issue by detwizard** [dbeaver/dbeaver#9766]
Could you include auto-complete when using CTE in a query, SSMS has this feature and it seems to be the missing piece in the Query builder. Thank you!

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion.

**Comment by dfx413** [comment]
It's a pity that this one keeps getting postponed.

**Comment by iannicktl** [comment]
I would love to see this feature. Its the only downside i've found to dbeaver

**Comment by E1izabeth** [comment]
Let's keep one issue for this #8949
