### ISSUE TITLE
ubuntu software center show dbeaver-ce license as "proprietary"

### ISSUE THREAD

**Issue by mhow2** [dbeaver/dbeaver#9770]
#### System information: 
- Ubuntu 18.04.5 LTS
- dbeaver v7.2.0
- Java version : 1.8.0_201

#### Describe the problem you're observing:
I've installed the deb package from the official website https://dbeaver.io/download/ (the community edition)
I wonder why Ubuntu Software center the display that the software license "proprietary"

![image](https://user-images.githubusercontent.com/9987241/93184406-80d89f00-f73c-11ea-85c9-75d3dfbef49c.png)

#### Steps to reproduce, if exist:
Download and Install dbeaver deb package from https://dbeaver.io/download/ using Ubuntu's software center

**Comment by uslss** [comment]
Seems it is an issue. Thanks for the report

**Comment by uslss** [comment]
verirfied
![image](https://user-images.githubusercontent.com/31996417/133051850-119e7f58-93d8-44ca-bb84-c04e5764123b.png)
