### ISSUE TITLE
How to assign mysql table permissions to users

### ISSUE THREAD

**Issue by ZhouJiaZhi** [dbeaver/dbeaver#9771]
**MySQL: 5.7
beaver: 7.2.0.202008302047**

How to assign table permissions to users in Dbeaver? I don't want to write SQL by myself, is there a way to assign permissions through the interface?

**Comment by LonwoLonwo** [comment]
![2020-09-15 14_07_55-DBeaver Enterprise 7 3 0 - mysql infoschema@localhost](https://user-images.githubusercontent.com/45152336/93203358-f9e7ee80-f75c-11ea-9f47-f0c697c0e3ca.png)
@ZhouJiaZhi hello. In Database Navigtor tree in tab "Users" you can find many permissions settings. Is it what you looking for?

**Comment by ZhouJiaZhi** [comment]
@LonwoLonwo 
**I have A user joe, A database vtdc, A table employee, employee is in vtdc**
Please see the following SQL statement, he can achieve my needs, can I automatically generate this statement through the interface
**grant select,insert,update,delete,create,drop on vtdc.employee to joe@10.163.225.87 identified by ‘123′;**

**Comment by LonwoLonwo** [comment]
![2020-09-16 10_58_47-Window](https://user-images.githubusercontent.com/45152336/93309104-cadc8600-f80b-11ea-966a-72718492da9a.png)

@ZhouJiaZhi schema privileges tab can help

**Comment by ZhouJiaZhi** [comment]
Thank you, This is exactly what I want.
But I find a typo, when I switch language to Chinese, This **catalogs** is displayed as '表', Please see the red box part of the picture below  
<img width="1610" alt="截屏2020-09-16 下午4 09 17" src="https://user-images.githubusercontent.com/20750357/93310320-3851dc00-f837-11ea-88a3-5278d784f7aa.png">
