### ISSUE TITLE
Export query result requires active tab/script to have open connection

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#9773]
#### System information: 
- Operating system (distribution) and version - Windows 10 1909
- DBeaver version - 7.1.3
- Additional extensions - None

#### Connection specification:
- Database name and version - Redshift
- Driver name  - com.amazon.redshift.jdbc42.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  Nope

#### Describe the problem you're observing:
When we need to export from existing sql code - we right click the selected code, then Execute>Export from Query option is used.  In my case, lets say I am limited to only 1 active connections to redshift, so when I open the script, the connection is  established (default), so I manually disconnect database, then right click and use the export menu.  

The error is : when I click on export menu, the active script is opening connection to DB and using up one connection.  The export from query should only connect at end execute, and active script should not try to connect when I open the export from query dialog box.

#### Steps to reproduce, if exist:
On a script with closed connection - right click and select Execute>Export from Query option , it is reconnecting the existing connection of the script window, which is not required.

**Comment by serge-rider** [comment]
You can just disable "Open new connection" option in data export wizard:
![image](https://user-images.githubusercontent.com/6398845/98448887-7fc25d80-2140-11eb-8f34-ba1a1cdf6fde.png)

In this case DBeaver will reuse connection of active SQL editor.

**Comment by surpavan** [comment]
@serge-rider -I am fine with the option given in the above dialog box.  But the issue is that for that dialog box to be open the connection should be established.  I am in the impression that connection is required only when I start the data fetching.

**Comment by serge-rider** [comment]
@surpavan Currently it can't work this way. It needs the connection because it needs information about underlying database SQL dialect to parse the query.
However it shouldn't be a problem in general. It will use single connection for all operations and you can close it after the export operation.

**Comment by surpavan** [comment]
@serge-rider - Thank you for the reply. Closing the issue as it is not much of an actual issue.
