### ISSUE TITLE
SQL Editor disconnects after SQL code is changed

### ISSUE THREAD

**Issue by pgodfrin** [dbeaver/dbeaver#9776]
#### System information: 
- Operating system MS Windows 10
- DBeaver version 7.2.0.202008302047
- Additional extensions -none-

#### Connection specification:
- Database name and version PostgreSQL 12.3
- Driver name PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
SQL Editor disconnects after SQL code is changed
#### Steps to reproduce, if exist:
DBeaver no longer reconnects upon startup
Open SQL Editor, connect to DB
Execute SQL
Change SQL
SQL Editor loses connection

#### Include any warning/errors/backtraces from the logs
[db09152020.log](https://github.com/dbeaver/dbeaver/files/5225126/db09152020.log)

**Comment by pgodfrin** [comment]
More info: This does not happen with new sql files. Only with older files.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce. Should I wait for some time after executing SQL?

**Comment by pgodfrin** [comment]
You can close this. I think it's for files saved from an older version. Once I started doing 'save as' the problem went away. Weird eh?

**Comment by pgodfrin** [comment]
see above
