### ISSUE TITLE
Is there a way to stop DBeaver from pre-fixing default 'View Table' query with schema name?

### ISSUE THREAD

**Issue by qacollective** [dbeaver/dbeaver#9779]
#### System information: 
- Windows 10.0.17763 Build 17763
- DBeaver version 7.0.1

#### Connection specification:
- Apache Drill (not sure on version)

#### Describe your question:
When I connect to the Drill server, it has a default catalog of 'DRILL' under which all other databases and tables reside.  So it somewhat makes sense that when browsing a table's data, it's default query is:

`SELECT * FROM DRILL.'hive.database_name'.table_name`

(the ' characters above are actually backticks but I have no idea how to escape them properly in this markdown!)

However, this renders the following error:

![image](https://user-images.githubusercontent.com/25289661/93285871-3bd66a80-f819-11ea-843e-3337d77ba34c.png)

Copying and pasting the same query into a query window and removing the 'DRILL.' text executes fine.

Is there a way to stop Database Beaver from pre-fixing 'DRILL.' to the default query used for exploration of tables?

**Comment by kseniiaguzeeva** [comment]
Looks like a bug. Thank you for the report.

**Comment by qacollective** [comment]
Oh okay, until now I'd assumed it could have been something I was doing wrong, missed or maybe something to do with bad database configuration on the end of my organisation.  Happy to help further if needed.

**Comment by serge-rider** [comment]
@qacollective Please try to enable option "Omit catalog" in the driver properties:
![image](https://user-images.githubusercontent.com/6398845/102981833-9c60fc00-451a-11eb-9819-e8419255dbb6.png)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual - feel free to reopen it

**Comment by qacollective** [comment]
Sorry for the delay, I don't seem to get any notifications from GitHub about new messages.

I have tested this, and it works - when reconnecting to the database, there is no 'DRILL' node in the table tree and subsequently when I click 'View' on a table, I don't get the query error!

:+1:

**Comment by kseniiaguzeeva** [comment]
Great!
