### ISSUE TITLE
Import Data -> CSV -> File Chooser opens twice

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#9780]
#### System information: 
- Operating system (distribution) and version Debain/SID
- DBeaver version Version 7.2.0.202008302047
- Additional extensions -

#### Connection specification:
- Postgres 12
- Driver name Postgres JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Importing a CSV causes the file chooser for the CSV file to open twice -- after selecting the CVS , the chooser appears again

#### Steps to reproduce, if exist:

1) Database Navigator -> expand DB tree to table
2) rmc on the table node -> Import Data -> CSV -> [Next]
3) file chooser opens -> select CSV file -> [Open]
4) for a moment the wizard is visible again with all buttons inactive ...
5) ... and then  the file chooser opens again
6) whether you cancel the chooser now or select the CSV file again and hit [Open] -- you are now at the "Input file(s)" pane of the wizard and may proceed as expected

**Comment by uslss** [comment]
thanks for the report

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
