### ISSUE TITLE
Exporting a table that has a TEXT[] column to SQL creates an invalid SQL insert query

### ISSUE THREAD

**Issue by Zambito1** [dbeaver/dbeaver#9793]
#### System information: 
- Operating system (distribution) and version
    - Windows 10
- DBeaver version
    - 7.2.0
- Additional extensions
    - None

#### Connection specification:
- Database name and version
    - PostgreSQL 12.4
- Driver name
    - PostgreSQL standard driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
    - No

#### Describe the problem you're observing:

I tried exporting a table to SQL, and executing the query to insert into another database. The query failed because the array values were malformed.

#### Steps to reproduce, if exist:

1. Create a SQL table that has at least 1 column of type TEXT[].
2. Populate the table with data.
3. Right click on the table in the Database Navigator, and click Export Data.
4. Select SQL.
5. Hit Next until getting to the Output page
6. Select "Copy to clipboard"
7. Paste the copied query into a `psql` prompt

#### Include any warning/errors/backtraces from the logs

ERROR:  malformed array literal: \<the array value here\>

**Comment by Zambito1** [comment]
I believe the issue is that values are not being placed between double quotes. The documentation shows TEXT[]s being inserted with double quotes around each value: https://www.postgresql.org/docs/current/arrays.html#ARRAYS-INPUT

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. DBeaver recognizes the generated SQL as correct:
INSERT INTO public.testttable (column1,column2,column3,"text") VALUES 
('a',3,'q','{1,2}')
,('a',4,'q','{1,2}')
;

**Comment by serge-rider** [comment]
We must put string literals in double quotes in INSERT queries.
Fixed

**Comment by serge-rider** [comment]
Multi-dimensional arrays support added.

**Comment by kseniiaguzeeva** [comment]
verified
