### ISSUE TITLE
I want to connect DBeaver PostgreSQL to excel, as an ODBC driver, to upload a table onto excel

### ISSUE THREAD

**Issue by scottxu502** [dbeaver/dbeaver#9801]
#### System information: 
- Windows 10
- 7.20

#### Connection specification:
- Database name and version

#### Describe your question:

https://www.devart.com/odbc/postgresql/docs/excel.htm

From the looks of this tutorial, I would need the driver, the server, and the database. The database is pretty self-explanatory - could you please clarify where I would find the information for the other 2 items on DBeaver?

**Comment by kseniiaguzeeva** [comment]
You can export a table in Excel format using DBeaver. For this:
1. Open Help>Install new software...
2. Enter in **work with** field _DBeaver Office integration - https://dbeaver.io/update/office/latest/_
3. Go through the wizard to install the extension
4. Export a table in Excel format.

Will it cover your needs?
