### ISSUE TITLE
High Idle CPU Usage

### ISSUE THREAD

**Issue by zelewitzSB** [dbeaver/dbeaver#9803]
Note: I have seen comparable issues but none of them were on macs nor did they work for me.

I am running DBeaver (Version 7.1.5.202008180601) on a MacBook Pro on Catalina 10.15.6. When DBeaver is completely idle it can have triple digit idle wake ups and consume 18-30% of the CPU which seems terrible excessive. Screenshot of my activity monitor here:

![image](https://user-images.githubusercontent.com/68710550/93479967-29603d80-f8ba-11ea-8e3f-dda93d225521.png)

I have also attached the thread dump in case that is helpful.

[thead-dump.txt](https://github.com/dbeaver/dbeaver/files/5239596/thead-dump.txt)

**Comment by serge-rider** [comment]
Thanks for the bug report.
Thread dump doesn't contain anything suspicious.

- Do you have any open editors? 
- Does dbeaver consume CPU even if the main app windows is minimized?
- Does it keep using cpu after app restart?

**Comment by zelewitzSB** [comment]
I have had them open and shut, connections open and shut. It still consumes
CPU when minimized. It does after the restart.

I appreciate you reaching out btw.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it on Macos Catalina in DBeaver 7.2.2. CPU increases significantly during activities (connecting to database, opening SQL editor). After that, CPU drops to about 2%. Is this still actual for you?

**Comment by zelewitzSB** [comment]
The problem has been so bad I have been avoiding Dbeaver in general. I just
upgraded to the version you mention and the problem seems like it may be a
bit better but I still would not call it resolved. DBeaver when completely
idle (not querying) still sits at around 6% CPU.

**Comment by kseniiaguzeeva** [comment]
Сlosed because not reproduced.

**Comment by benyaminl** [comment]
@kseniiaguzeeva This is also happen on Linux Fedora with Java sitting around on 5-7%. Any idea to reduce it at least to 2%? I already minimize the view, java still sitting around on 7% on average. 

This is killing battery on the go when not used tbf

**Comment by dodbrian** [comment]
I have the same issue on macOS Monterey 12.6, M1 chip.
DBeaver 22.2.5

<img width="963" alt="image" src="https://user-images.githubusercontent.com/2762450/204596823-305d8148-9561-46a2-b5a2-b6560744f171.png">

**Comment by baikov** [comment]
same issue on macOS Ventura 13.2.1, Intel
![Screenshot 2023-04-03 at 15 01 33](https://user-images.githubusercontent.com/34839184/229503248-6add81a6-465d-4c6d-b182-9553fddd1ffa.jpg)
