### ISSUE TITLE
7.1.4 Upgrade to 7.2.0 Issues with Workspace

### ISSUE THREAD

**Issue by comptech87** [dbeaver/dbeaver#9806]
#### System information: 
- Operating system (distribution) and version    Windows Server 2019
- DBeaver version    Version 7.2.0
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
So right now we have a custom path for user workspace to live.  So in version 7.1.4 we updated the Target of the shortcut to set a new workspace location (D:\Software\DBeaver\dbeaver-ce-7.2.0-win32.win32.x86_64\dbeaver\dbeaver.exe -data "D:\Home\%username%\DBeaver\Workspace").  Now that i have upgraded to 7.2.0 its not reading the old workspace.  How do I fix this issue?

**Comment by uslss** [comment]
@comptech87 are there something in the log? What happens when you try to start DBeaver?
Thanks in advance for the response.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
