### ISSUE TITLE
comment block creates one more close comment

### ISSUE THREAD

**Issue by ngkaho** [dbeaver/dbeaver#9808]
Hi,

I opened a comment block /**/ and press enter in between two stars ( expected result - open a new line inside the comment block ). however it creates one more close comment block.

expected:
/*
 *
 */

now:
/*
 *
 */*/

Dbeaver version: 7.2.0.202008302047

Many thanks!

Kelvin

**Comment by kseniiaguzeeva** [comment]
Thank you for the report

**Comment by LonwoLonwo** [comment]
Fixed for this case:
![2020-10-27 10_44_56-DBeaver Enterprise 7 3 0 - _none_ Script-51](https://user-images.githubusercontent.com/45152336/97271550-c01d0400-1841-11eb-8b20-9c09cfc53d6a.png)
And for this:
![2020-10-27 10_45_57-DBeaver Enterprise 7 3 0 - _none_ Script-51](https://user-images.githubusercontent.com/45152336/97271686-e93d9480-1841-11eb-8e78-69ae2c1d0a25.png)
