### ISSUE TITLE
Misleading error message when network settings block driver download

### ISSUE THREAD

**Issue by RandomAsianBDA** [dbeaver/dbeaver#9812]
I have installed DBeaver. I want to use my local mysql server. There is an Issue regarding the driver download. When I try to connect to the server, following Error occurs: Error resolving driver libraries 
Cause:Error resolving driver libraries 
Error resolving dependencies
Maven artifact 'maven:/mysql:mysql-connector-java:5.1.44' not found
When I try to download the required drivers, following Error pos up: 
Can't create driver instance
  Error creating driver 'MySQL' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.mysql.jdbc.Driver'
  Error creating driver 'MySQL' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.mysql.jdbc.Driver'
    com.mysql.jdbc.Driver
    com.mysql.jdbc.Driver
Please Help

**Comment by RandomAsianBDA** [comment]
Using the DBeaver Version 7.1.4

**Comment by reedjosh** [comment]
Same issues here.

**Comment by uslss** [comment]
Could you check if it reproducible against 7.2.3?

**Comment by reedjosh** [comment]
It's not specific to the Driver, and it's easier for me to take down my Oracle service and restore it later, so I did so w/Oracle.

![image](https://user-images.githubusercontent.com/9508385/96921773-d56de900-1463-11eb-9dbf-69dc15d55794.png)
![image](https://user-images.githubusercontent.com/9508385/96921918-04845a80-1464-11eb-9fc2-60e9758c5d95.png)

Still have the same issue. Double checked--no VPN enabled. : (

**Comment by uslss** [comment]
still cannot reproduce it.
Did you try Reset to default?
Thanks in advance

**Comment by reedjosh** [comment]
I'm unclear on exactly what you mean by Reset to default, but I believe I reset the maven config to default via a default button.

What's the procedure? I'll give it a try.

**Comment by LonwoLonwo** [comment]
@reedjosh have you try "Reset to default" button in Edit Driver Settings dialog in Connection Settings?
Sometimes old dependencies remain in the list and the list needs to be updated.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual - feel free to reopen it

**Comment by widada** [comment]
I got same issues

**Comment by ayzesantos** [comment]
I also have the same issues. Restore to default don't fix anything.

1st error when I try to connect:
<img width="1440" alt="Screen Shot 2021-06-30 at 1 43 52 AM" src="https://user-images.githubusercontent.com/67475294/123930552-73865b80-d9c2-11eb-92f9-330179bb85a9.png">

Then I clicked the download button here:
<img width="1440" alt="Screen Shot 2021-06-30 at 1 44 20 AM" src="https://user-images.githubusercontent.com/67475294/123930637-8567fe80-d9c2-11eb-9071-5c3e9a6b3293.png">

Then get this error:
<img width="997" alt="Screen Shot 2021-06-30 at 1 42 45 AM" src="https://user-images.githubusercontent.com/67475294/123930689-90bb2a00-d9c2-11eb-892b-21eefcff58f9.png">

**Comment by Matvey16** [comment]
@widada @ayzesantos It looks like a problem with internet connection. Maybe you have VPN or proxy or even firewall blocking the connection. Can you verify that those are not the problem?

Also you can download the driver manually if it is not possible to adjust network settings

![dbeaver_Ewm4a0LaJ2](https://user-images.githubusercontent.com/82543000/125281500-f68ea680-e31e-11eb-96dd-e692e760e3b3.png)

**Comment by serge-rider** [comment]
Fixed.

Now we will show network error if network access is unavailable

**Comment by Matvey16** [comment]
Verified

**Comment by j-melara-oh** [comment]
having issue myself to where it will not even let me hit the vendor website or download files

**Comment by hhhaiai** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/5738285/43e9b514-1b7e-4fc2-9c7b-5f91a4ddf9a3)
