### ISSUE TITLE
Float Unsigned not listed on mysql

### ISSUE THREAD

**Issue by mcunha98** [dbeaver/dbeaver#9821]
#### System information: 
- Windows 10 
- Version 7.2.0.202008302047
- N/A

#### Connection specification:
- mySQL
- MariaDB JDBC driver
- no

When I'll append a new field on table structure on mysql cannot select float unsigned type 
To reproduce open any table in a Mysql database and add Create New Column and will notice the Data Type list 

![image](https://user-images.githubusercontent.com/6831010/93712643-8879b880-fb2d-11ea-8aca-f594522b500c.png)

**Comment by kseniiaguzeeva** [comment]
Float unsigned is going to be removed from MySQL acccording the article https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html.

**Comment by mcunha98** [comment]
Hmmm...I confess I don't know this update for future versions.
But how DBeaver will be deal with old versions of mysql/maria ?
Probably if is possible, they need to check version in use, to show/remove the option.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. The ticket is added in future releases.

**Comment by serge-rider** [comment]
Data type list is provided by MySQL JDBC driver. Thus it depends on driver version.
Anyhow, you can specify FLOAT UNSIGNED as column type manually.

Potentially we could add extra data types to MySQL connections. But I don't think we should as actual list of supported type depends on too many factors (server version, fork type, driver configuration, etc).
