### ISSUE TITLE
I hope dbeaver will provide the ability to create databases in the future

### ISSUE THREAD

**Issue by ldzqdrm** [dbeaver/dbeaver#9824]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I hope dbeaver will provide the ability to create databases in the future

**Comment by uslss** [comment]
Hi @ldzqdrm ,
what database type do you use?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
Please add the connection type you use and reopen the ticket. Thanks in advance
