### ISSUE TITLE
Database navigator view

### ISSUE THREAD

**Issue by jgranduel** [dbeaver/dbeaver#9827]
#### System information: 
- Windows 10
- DBeaver-7.2.0

#### Connection specification:
- PostgreSQL

#### Describe your question:
How to toggles view in navigator pane? I might have changed without noticing, but cannot restore it!

![image](https://user-images.githubusercontent.com/586675/93755707-09a37f00-fc04-11ea-8bbb-580e4490ceb8.png)

Thanks in advance.

**Comment by kseniiaguzeeva** [comment]
You should:
1. right-click on a connection in DB Navigator tree to see the context menu.
2. select Connection view>Advanced
![dbeaver_1ABjLERU3J](https://user-images.githubusercontent.com/51405061/93756646-1331e480-fc0e-11ea-99c7-63243d13ea99.png)
Please ask if the issue will not be resolved
