### ISSUE TITLE
Word Occurrences highlighting

### ISSUE THREAD

**Issue by mstup** [dbeaver/dbeaver#9830]
#### System information: 
- Operating system (distribution) and version: Fedora 26
- DBeaver version: 7.2.1.202009201907
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 9.4
- Driver name: postgresql-42.2.5.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
Word Occurrences highlighting works incorrect for the reason highlight sub-word as well.

![word_occur_bag](https://user-images.githubusercontent.com/16793676/93787243-3ce30f80-fbfe-11ea-859c-ef65f0f67234.png)

#### Steps to reproduce, if exist:
Script example:
`CREATE OR REPLACE VIEW public.reference_ratio_view
AS SELECT rfr.sample_id,
    rd.activity_ratio,
    rd.activity_ratio_uncertainty,
    ncl1.name AS nuclide_name1,
    ncl2.name AS nuclide_name2,
    rfr.exercise_id,
    ( SELECT sum(rav.activity) AS sum
           FROM reference_activity_view rav
          WHERE rav.exercise_id = rfr.exercise_id AND rav.sample_id::text = rfr.sample_id::text AND rav.nuclide_name::text = ncl1.name::text) AS activity1,
    ( SELECT sum(rav.activity) AS sum
           FROM reference_activity_view rav
          WHERE rav.exercise_id = rfr.exercise_id AND rav.sample_id::text = rfr.sample_id::text AND rav.nuclide_name::text = ncl2.name::text) AS activity2,
    rd.reference_date,
    rd.activity_ratio_robust_average,
    rd.activity_ratio_robust_average_uncertainty,
    exncl1.id AS exercise_nuclide1_id,
    exncl2.id AS exercise_nuclide2_id
   FROM reference_ratio rfr
     JOIN ratio_data rd ON rd.id = rfr.ratio_data_id
     JOIN exercise_nuclide exncl1 ON exncl1.id = rd.exercise_nuclide_parent_id
     JOIN exercise_nuclide exncl2 ON exncl2.id = rd.exercise_nuclide_child_id
     JOIN nuclide ncl1 ON ncl1.id = exncl1.nuclide_id
     JOIN nuclide ncl2 ON ncl2.id = exncl2.nuclide_id
  WHERE exncl1.deleted IS FALSE AND exncl1.deleted IS FALSE AND rd.deleted IS FALSE AND rfr.deleted IS FALSE AND ncl1.deleted IS FALSE AND ncl2.deleted IS FALSE;`

#### Include any warning/errors/backtraces from the logs
There are no errors in the log.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
For me it works as expected. 
Having sub-words selected is very useful in some cases.

You could try option "Mark occurences of word under cursor" in 7.2.5.

**Comment by kseniiaguzeeva** [comment]
- Is it expected that the option works only via the Global settings?
- Should an ability be made to activate only one of the options (**word under cursor** or **selected word)** in the settings?

**Comment by serge-rider** [comment]
1. Yes. I've reworked SQL editor pref page and now all code editing settings are global.
2. Yes, these options can be set independently

![image](https://user-images.githubusercontent.com/6398845/98664325-49acf580-235b-11eb-8672-51acf234aa68.png)

**Comment by kseniiaguzeeva** [comment]
closed
