### ISSUE TITLE
no editor cursor in dark theme

### ISSUE THREAD

**Issue by oldguy76** [dbeaver/dbeaver#9833]
#### System information: 
- Operating system (distribution) and version
Ubuntu 20.04
- DBeaver version
7.20.0
- Java version 
1,8.0_265
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:

In Dark Theme, Database Navigator, Tables, View Data, when a cell is double-clicked for editing, no cursor is visible, although editing works normally.

**Comment by uslss** [comment]
Sorry for the late response and thanks for the report
The cursor is shown, but due to its' color it is not visible
[2020-12-10 13:37:53.zip](https://github.com/dbeaver/dbeaver/files/5672057/2020-12-10.13.37.53.zip)

**Comment by flambchap** [comment]
Unfortunately, there is nothing we can do here. DBeaver is based on the Eclipse platform, and Eclipse has the same problem now.
