### ISSUE TITLE
Task Scheduler Question

### ISSUE THREAD

**Issue by AndrewBaxter01** [dbeaver/dbeaver#9834]
![DB_output_LI](https://user-images.githubusercontent.com/36285657/93805111-4035c580-fc15-11ea-897e-c5c808261977.jpg)

#### System information: 
- Windows 10 1909
- DBeaver version 7.2.0

#### Connection specification:
- ODBC

#### Describe your question:
We just purchased the EE of DBeaver after using the standard edition for a bit. My plan was to schedule scripts to run and the output saved, so that I could set up macros in Excel with this output. From what I am seeing, I can schedule a task to run a script, but am I unsure what happens when it does run. The log shows that it ran successfully in DBeaver and in Task Scheduler. In the picture I see that there is an option to have the query results dumped into the log file, but that it greyed out. I've tried to look through documentation on the website and on Github, but haven't had much luck. Could someone point me in the right direction? I think I am just missing a simple step.

**Comment by hegyre** [comment]
Hello @HopDevvil814 , how did you managed to fix that please ?
We are having the same issue (Community Edition)
