### ISSUE TITLE
Data Export of Postgres tables can result in duplicate keys and inconsistent data

### ISSUE THREAD

**Issue by keneasson** [dbeaver/dbeaver#9836]
This looks like an old bug resurfacing. [https://github.com/dbeaver/dbeaver/issues/735]

DBeaver Version  on OSX 10.15

#### System information: 
- OSX 10.15
- DBeaver version: 7.2.1.202009201907
- eclipse.buildId=unknown
- java.version=1.8.0_171
- java.vendor=Oracle Corporation
- BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_CA
- Framework arguments:  -keyring /Users/kene/.eclipse_keyring
- Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/kene/.eclipse_keyring

#### Connection specification:
- Database name: Postgres 9.5
- Driver name 
- OpenVPN

#### Describe the problem you're observing:
When using Data Export to copy data from one Postgres Database into another Postgres Database on a different server, some rows are read more than once, resulting in duplicate key errors. This appears to be due to an old bug where the "order" is not specified. 

#### Steps to reproduce, if exist:
Select a large table in a Postgres Database where the data has large holes or is busy.
Select Data Export
Select another DB to insert the data into, complete the wizard using default settings.
#### Include any warning/errors/backtraces from the logs
SQL Error [23505]: Batch entry 0 INSERT INTO public.alerts (id,email,****,****,***)
	VALUES (508015,'*******',101,'string','DATE_TIME') was aborted: ERROR: duplicate key value violates unique constraint "table_pkey"
  Detail: Key (id)=(508015) already exists.  Call getNextException to see other errors in the batch.

#### Possible Solution
There should be an explicit order by column and the last value extracted should be used in a where order_key > last_order_key
this is the only way to guarantee that duplicate data isn't retrieved on subsequent queries.

**Comment by kseniiaguzeeva** [comment]
Is it possible to send a table DDL example? And a file with data to export (CSV or SQL format)?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.

**Comment by richard-popham** [comment]
This is an issue with Postgres not guaranteeing the order without an order by when limit is used.[ Documentation](https://www.postgresql.org/docs/9.5/queries-limit.html) states:

> The query optimizer takes LIMIT into account when generating query plans, so you are very likely to get different plans (yielding different row orders) depending on what you give for LIMIT and OFFSET. Thus, using different LIMIT/OFFSET values to select different subsets of a query result will give inconsistent results unless you enforce a predictable result ordering with ORDER BY. This is not a bug; it is an inherent consequence of the fact that SQL does not promise to deliver the results of a query in any particular order unless ORDER BY is used to constrain the order.

I am currently seeing this issue with tables over 800,000 records.

**Comment by RobSimpsonHove** [comment]
I am experiencing this with 400k records.  What is the work-around - set batch size to > number of records?

**Comment by atharva-novi** [comment]
Changing the `extract type` to "Single query" solved this for me. I think the issue is that Postgres exports `segment_size` number of entries in a batch and does not guarantee non-overlap in each subsequent segment.

You can check this by checking the following:

- Export data to csv
- Check number of unique values in `0 : segment_size` (answer will be `segment_size`)
- Check number of unique values in `segment_size : 2 * segment_size` (answer will be `segment_size`)
- Check number of unique values in `0 : 2 * segment_size` (answer will be < `2 *segment_size`)

My suggestion would be to either make this explicit in the DBeaver export data functionality or registered as a bug.
