### ISSUE TITLE
[UI] the check box at Properties tab is not visible (selected color blue) icon color also blue

### ISSUE THREAD

**Issue by erlangp** [dbeaver/dbeaver#9837]
**A clear and concise description of what the problem is**
I'm always frustrated when cannot see the icon state, it is checked or not. Because the colors are same.
The check box not visible (selected color is blue) icon color also blue.

**Solution**
Change icon color to black.

**Additional context**
Screenshots about the problem: https://imgur.com/a/oYatjfP

Env: Linux, Ubuntu 18, MariaDB

**Comment by erlangp** [comment]
Alternative solution: change color of selection to more transparent, not solid blue color. Thank you

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Similar to #9327

**Comment by serge-rider** [comment]
Fixed in #9327

**Comment by uslss** [comment]
ubuntu - ok

**Comment by serge-rider** [comment]
Fixed.
Now we use textual representation of checkboxes (unicode chars) everywhere in UI. Thus they can be styled/colored according to the current OS/theme.

**Comment by kseniiaguzeeva** [comment]
Could you please disable popup for checkboxes in Properties?
![dbeaver_B2HPgt7FFH](https://user-images.githubusercontent.com/51405061/98460678-87711900-21b7-11eb-8124-529b47d50634.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Fixed in Column properties

**Comment by erlangp** [comment]
Thank you very much :D :+1:
