### ISSUE TITLE
able to switch time zone for view/format - epoch time 

### ISSUE THREAD

**Issue by kush87** [dbeaver/dbeaver#9840]
**Is your feature request related to a problem? Please describe.**
I have lot of timestamps which i want to see in America/New_York time zone but whenever i select the view/format - epoch time , it always converts it to my local time.
It becomes very frustrating when analysing certain anomaly which happen in your product and you want to compare when what happened by whom.

**Describe the solution you'd like**
I would like to be able to either type in the time zone i want the time stamps to be rendered in whenever  i use the view/format option or a setting somewhere.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by flambchap** [comment]
Implemented. There is now a timezone option right in the transformer dialog.

**Comment by uslss** [comment]
verified
