### ISSUE TITLE
Data transfer: export to HTML but don't export the query

### ISSUE THREAD

**Issue by troegel01** [dbeaver/dbeaver#9842]
Can you please add an option (checkbox) where the user can choose, if the query itself should be in the html result or not?

Maybe you can integrate it inside the export settings, as shown in my screenshot.

Thanks. Enrico

![dbeaver_2020-09-22_12-59-24](https://user-images.githubusercontent.com/5850983/93874602-e21be780-fcd3-11ea-99e3-d1e271f1d5d5.png)

**Comment by kseniiaguzeeva** [comment]
Do you mean both: query and query result will be displayed in html after export?

**Comment by troegel01** [comment]
> Do you mean both: query and query result will be displayed in html after export?

That's right. The html export looks like this:

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/><style>
table {border: medium solid #6495ed;border-collapse: collapse;width: 100%;} th{font-family: monospace;border: thin solid #6495ed;padding: 5px;background-color: #D0E3FA;}td{font-family: sans-serif;border: thin solid #6495ed;padding: 5px;text-align: center;}.odd{background:#e8edff;}img{padding:5px; border:solid; border-color: #dddddd #aaaaaa #aaaaaa #dddddd; border-width: 1px 2px 2px 1px; background-color:white;}</style>
</head>
<body>
<table><tr><th colspan="4">SELECT TRIM(AUKOD.AU_NR), AUKOD.LI_DAT, AUKOD.REF_POS_NR_GES, AUKOD.STATUS_KZ FROM DBAUFT.AUKO_D AUKOD
WHERE AUF_NR LIKE '15A11%'
AND AUF_DAT &amp;gt; 20200901
AND AU_NR IN (
'0004318345'
)</th></tr><tr><th>TRIM(AUKOD.AU_NR)</th><th>LI_DAT</th><th>REF_POS_NR_GES</th><th>STATUS_KZ</th></tr><tr class="odd"><td>0004318345</td><td>0</td><td>&nbsp;</td><td>30</td></tr>
</table></body></html>#

**Comment by troegel01** [comment]
@kseniiaguzeeva Can you reproduce the issue?

**Comment by uslss** [comment]
@troegel01 , if I understand you right, it is implemented in scope of 7.2.3.
You could check if it solves your problem in EA version https://dbeaver.io/files/ea
![image](https://user-images.githubusercontent.com/31996417/95573188-c0409580-0a33-11eb-81ba-f02bc70f4219.png)

**Comment by troegel01** [comment]
@uslss Thanks for your answer. This helps for now.
Is it possible to remember the settings from menu 'export results' and use this setup inside 'extended copy / copy as HTML'?

**Comment by uslss** [comment]
@troegel01 ,
Unfortunately, it is not possible for now. Extended copy use default settings that couldn't be changed. But if it is needed for you - feel free to create an enhancement or FR about it.
Best regards :)
