### ISSUE TITLE
Sequence doesn't increase on data insert

### ISSUE THREAD

**Issue by sefacan** [dbeaver/dbeaver#9843]
#### System information: 
- Windows 10
- DBeaver 7.2.1.202009201907

#### Connection specification:
- Postgrel SQL 12
- PostgreSQL JDBC Driver

#### Describe the problem you're observing:
I insert data as manual to postgresql database. Sequence not increase automatically. I'm using a ORM(EntityFramework Core) for my project. When I insert data with orm, sequence is increasing automatically but it's not increase on dbeaver.

#### Steps to reproduce, if exist:
Insert data as manual.
Insert data with an orm. You will get an error about the duplicate identity key error.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce the issue. Could you please write steps/DDL example. Here what I do in DBeaver:
![SuPBcWryYT](https://user-images.githubusercontent.com/51405061/94675946-39990380-0323-11eb-9ce1-7e2849c8e150.gif)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it
