### ISSUE TITLE
Oracle: Trying to update a row with CLOB column fails with ORA-00932 error

### ISSUE THREAD

**Issue by creage** [dbeaver/dbeaver#9845]
#### System information: 
- Operating system (distribution) and version: Windows Server 2012 R2
- DBeaver version: 7.2.1
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle [Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0 - Production]
- Driver name: Oracle JDBC driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:
Trying to update a row with existing CLOB value, fails with error.

#### Steps to reproduce, if exist:
Have a table with CLOB and VARCHAR columns. Create new row in table by filling all values. Now try to update VARCHAR column, and save.
#### Include any warning/errors/backtraces from the logs

Error log entry
```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Sep 22 22:08:57 CEST 2020
Error : 932, Position : 72, Sql = UPDATE SJSYSADM.SD_DATADICT x
	SET x.DATADICT=:1 
	WHERE x.NAME=:2  AND x.DATADICT=:3  AND x.LOAD=:4  AND x.TYPE_RANK=:5  AND x.MODULE_RANK=:6  AND x."RANK"=:7  AND x.PRIORITY IS NULL AND x.MODIFIED=:8  AND x.CULTURE_NAME IS NULL AND x.PRIORI IS NULL AND x.ROWID=:9 , OriginalSql = UPDATE SJSYSADM.SD_DATADICT x
	SET x.DATADICT=?
	WHERE x.NAME=? AND x.DATADICT=? AND x.LOAD=? AND x.TYPE_RANK=? AND x.MODULE_RANK=? AND x."RANK"=? AND x.PRIORITY IS NULL AND x.MODIFIED=? AND x.CULTURE_NAME IS NULL AND x.PRIORI IS NULL AND x.ROWID=?, Error Msg = ORA-00932: inkonsistente datatyper: forventede -, fik CLOB
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
@creage do you have Primary key in your table "SJSYSADM.SD_DATADICT"?
Or did you choose to use all columns as keys?
![2020-10-26 16_23_51-Window](https://user-images.githubusercontent.com/45152336/97178070-0cb40100-17a8-11eb-9b58-ee6a428f7c1e.png)

If this is the second case, then you cannot do this with the СLOB data type, because it should not be mentioned in the [WHERE clause](https://stackoverflow.com/a/12980560/14220989). And then you just need to add a constraint to the table.

**Comment by creage** [comment]
@LonwoLonwo no, this table does not have any keys defined. But I've tried to configure the custom unique key excluding CLOB column, and it works fine now!

Thank you!
