### ISSUE TITLE
Check constraints are cut off after 64 characters

### ISSUE THREAD

**Issue by queueseven** [dbeaver/dbeaver#9848]
#### System information: 
- Windows 10
- 7.2.1

#### Connection specification:
- MariaDB 10.3

#### Describe the problem you're observing:
If you view a check constraint, only the first 64 characters are displayed.

#### Steps to reproduce, if exist:

Create an example database + table + contraint:

```
create database test;

use test;

create table foo (some_int_column1 int null, some_int_column2 int null);

alter table foo add constraint CONSTRAINT_1 check (if(`some_int_column1` is not null,1,0) + if(`some_int_column2` is not null,1,0) = 1);

insert into foo values (1,null); -- OK

insert into foo values (null,1); -- OK

insert into foo values (null,null); -- fails, OK

insert into foo values (1,1); -- fails, OK
```

Now, if you view the constraint in the editor, you only see the first 64 characters:
![grafik](https://user-images.githubusercontent.com/3126597/93990717-be1bdd00-fd8b-11ea-9c8b-f38c0bd73695.png)

It's even worse when you generate the DDL of that constraint:

![grafik](https://user-images.githubusercontent.com/3126597/93990774-d2f87080-fd8b-11ea-8652-270600b927c8.png)

But generating the DDL for the entire table works fine and the complete constraint is shown:

![grafik](https://user-images.githubusercontent.com/3126597/93990841-e6a3d700-fd8b-11ea-9b05-793f62cf7ac0.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/issues/9122

**Comment by LonwoLonwo** [comment]
It's MariaDB issue, unfortunately.
waiting answer https://jira.mariadb.org/browse/MDEV-24139

**Comment by LonwoLonwo** [comment]
Hello @queueseven 

The problem was solved here https://jira.mariadb.org/browse/MDEV-24139 in new MariaDB versions. 

![2020-12-09 10_51_31- MDEV-24139  CHECK_CLAUSE field in INFORMATION_SCHEMA CHECK_CONSTRAINTS truncate](https://user-images.githubusercontent.com/45152336/101600688-b96ed880-3a0c-11eb-87e6-60844be73ee9.png)

We have not tested in new versions of MariaDB yet, but we hope that everything is ok.
