### ISSUE TITLE
Data Transfer Error - Timeout while loading data transfer settings

### ISSUE THREAD

**Issue by SirGJC** [dbeaver/dbeaver#9851]
#### System information: 
- Operating system (distribution) and version - Windows 10 64bit 1809
- DBeaver version - 7.2.1
- Additional extensions - None

#### Connection specification:
- Database name and version
- Driver name - Amazon Redshift
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Right click SQL query -> Execute -> Export from Query

Results in an error message "Can not open data transfer wizard. Reason: Timeout while loading data transfer settings."

After deleting %HOMEPATH%/.dbeaver/.metadata/ I was able to open it once (however the select target destination page of the wizard took 5mins to load) however the error has returned when trying a subsequent time.

#### Steps to reproduce, if exist:

As above.

#### Include any warning/errors/backtraces from the logs
!ENTRY org.jkiss.dbeaver.model 4 0 2020-09-23 13:22:10.530
!MESSAGE Timeout while loading data transfer settings
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-09-23 13:22:10.530
!MESSAGE Timeout while loading data transfer settings
!STACK 0
org.jkiss.dbeaver.DBException: Timeout while loading data transfer settings

**Comment by apocalypse2012** [comment]
I am having the same problem trying to open a migration task. The driver for my source data is Postgres. The Target is MS SQL. 

"Can not open data transfer wizard

Reason:
Timeout while loading data transfer settings"

**Comment by serge-rider** [comment]
Fixed. Now we load target database settings on demand (for database->database transfer, page mappings or final).
It reduces data transfer wizard delays.

@Matvey16 please test in different cases including task editor.

**Comment by Matvey16** [comment]
Verified
