### ISSUE TITLE
Script execution truncated

### ISSUE THREAD

**Issue by EmilianoElMariachi** [dbeaver/dbeaver#9852]
#### System information: 
- Windows 10 Pro
- DBeaver  7.2.1.202009201907
- Additional extensions

#### Connection specification:
- Driver: Oracle OJDBC10.jar

#### Describe the problem you're observing:

I'm trying to execute an SQL script (Alt+X) file which is supposed to create an Oracle SQL package (with Oracle driver). The script execution is resulting in an SQL execution error and when I look at the execution log, I can see that the real text taken into account is missing chars at the end.

#### Steps to reproduce, if exist:

Here is an example of Oracle SQL script file (grammatically correct in PL-SQL)

``` lang-sql
CREATE OR REPLACE PACKAGE BODY my_package AS

procedure my_proc as
begin
null;
end my_proc;

END my_package;
```

And here is what's really executed (Alt+X)

``` lang-sql
CREATE OR REPLACE PACKAGE BODY my_package AS

procedure my_proc as
begin
null;
end my_proc;
```

Here the last line «END my_package;» is missing...

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by bjervrob** [comment]
I have a similar issue using DBeaver IDE 7.2.2.202010041557 in Eclipse 2020-09 (4.17.0) with HSQLDB as database.

CREATE TRIGGER TRI_CODE_SYSTEM 
BEFORE INSERT ON CODE_SYSTEM 
REFERENCING NEW AS NEWROW FOR EACH ROW 
BEGIN ATOMIC
	IF TRUE THEN
		SIGNAL SQLSTATE '45000'; 
	END IF;
END;

The "execute SQL script" command skips the last END; when sending the code to the database.  The "execute SQL statement" command works, but I have to run each statement in the script one by one.

Cheers
/Robert

**Comment by LonwoLonwo** [comment]
As a workaround you can use Ctrl+Enter on the selected area instead of Alt+X

**Comment by LonwoLonwo** [comment]
Close as duplicate: https://github.com/dbeaver/dbeaver/issues/8095
