### ISSUE TITLE
cell does not enter edit mode on non-ASCII character

### ISSUE THREAD

**Issue by oldguy76** [dbeaver/dbeaver#9856]
#### System information: 
- Operating system (distribution) and version
Ubuntu 20.04
- DBeaver version
7.2.0
- Additional extensions

#### Connection specification:
- Database name and version
postgresql 12.4
- Driver name
postgreSQL JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
I have a table with a sv_SE.utf8 collation. When the data is displayed as a spreadsheet and a cell is highlighted, if the first character pressed is an ASCII character, the cell automatically goes into edit mode, but if the first character pressed is a non-ASCII character (å, ä, ö), the cell does not respond, in which case a double-click is required to enter edit mode.

**Comment by kseniiaguzeeva** [comment]
Could you please send a table DDL example?

**Comment by oldguy76** [comment]
CREATE TABLE public.verb (
	pres text NOT NULL COLLATE "sv_collate",
	decl text NULL,
	p bpchar(1) NULL,
	w bpchar(1) NULL,
	s bpchar(1) NULL,
	def text NULL,
	CONSTRAINT verb_pkey PRIMARY KEY (pres)
);

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. It is actual for different databases.

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
