### ISSUE TITLE
import custom connections into a certain folder

### ISSUE THREAD

**Issue by herbinator** [dbeaver/dbeaver#9857]
I would like to be able to import a custom connections file into a created folder in the database navigator.
I'm using the File/import/custom  function

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/104812910-a83c9700-5816-11eb-8734-c2f0ce1dcbaf.png)

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by herbinator** [comment]
It works great
