### ISSUE TITLE
Export wizard error

### ISSUE THREAD

**Issue by feritailor** [dbeaver/dbeaver#9862]
When you try to export to the CSV, a table is created in the database

#### System information: 
- Operating system (distribution) and version  Ubuntu 20.04.1 LTS
- DBeaver version Version 7.2.1.202009201907
- Java version java-11-openjdk-amd64
- Additional extensions

#### Connection specification:
- Database name and version Postgresql
- Driver name 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? yes

**Comment by uslss** [comment]
duplicates #9630 
anyway, thanks for the bug report
