### ISSUE TITLE
MariaDb tables are not refreshed

### ISSUE THREAD

**Issue by sbentin** [dbeaver/dbeaver#9863]
#### System information: 
- Linux Mint 20 Cinnamon
- DBeaver	7.2.1.202009201907	org.jkiss.dbeaver.core.product	null
- Java version  11

#### Connection specification:
- Database name and version MariaDb ver 10.1
- Driver name maraiadb-java-client-2.4.3.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Tables are not being refreshed. 
When I open a table in the Data tab and scroll down to the end I get the last record. When there more records added to the table by a different process (some other system using this table) and I refresh I don't get the new rows. I have to disconnect and reconnect in order to get them

#### Steps to reproduce, if exist:
Open a mariadb table. look at the data. do to another client ad rows. press refresh I won't see the rows.

**Comment by uslss** [comment]
hi @sbentin ,
cannot reproduce it. 
probably some special connection settings are needed?

**Comment by LonwoLonwo** [comment]
No updates for a long time. You can reopen the ticket if the problem reoccurs.
