### ISSUE TITLE
Update eclipse supported versions on download page

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#9864]
On https://dbeaver.io/download/ you state:

> Note: plugin is compatible with Eclipse platform (from 4.2 to 2019-09). Required plugins: gef and draw2d.

I believe support goes up to 2020-09 now, so this phrase should be updated.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report

**Comment by serge-rider** [comment]
Fixed
