### ISSUE TITLE
Executed query duration units. 

### ISSUE THREAD

**Issue by connorwilloughby** [dbeaver/dbeaver#9866]
Hi All, 

When executing queries in dbeaver the unit of duration is measured in seconds. As someone who regularly runs multi hour queries it would be nice to see this in a more appropriate format like HH:MM:SS:MS.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by Xylandor** [comment]
Nearly two years since requested. Could we possibly implement this? This is an easy win and shouldn't take long to implement.

**Comment by Xylandor** [comment]
Didn't see this earlier, but this request was reported over four years again in issue https://github.com/dbeaver/dbeaver/issues/3087

**Comment by Manja-S** [comment]
I would really like it to be implemented.

**Comment by E1izabeth** [comment]
Done 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/300a91af-c033-4d5a-9f80-a2c8be930173)

**Comment by connorwilloughby** [comment]
Looks amazing thank you so much! 👌

**Comment by osenijoshua** [comment]
> Done ![image](https://private-user-images.githubusercontent.com/28875055/308857059-300a91af-c033-4d5a-9f80-a2c8be930173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODg2NDcsIm5iZiI6MTcxNjI4ODM0NywicGF0aCI6Ii8yODg3NTA1NS8zMDg4NTcwNTktMzAwYTkxYWYtYzAzMy00ZDVhLTlmODAtYTJjOGJlOTMwMTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEwNDU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YTgyNGFjYTE4NmJjMThlODYwNTY5ZjQ0OWMxMjEzZmQzZWJiZGRiOGU5YTRmMjc2OWMzZDJkNjZjYjIzZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VvJYwc9WQ6iuDLJyTk_eYGyoqTynAMEOWTIxlrdrEQo)

Mine still shows in seconds. Any idea on how to change it?

**Comment by E1izabeth** [comment]
@osenijoshua have you updated DBeaver?

**Comment by osenijoshua** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/119590200/ac9c419a-4df2-42db-8ba2-e529bff87c76)

just did. No updates.

**Comment by Manja-S** [comment]
@osenijoshua Which version do you currently use? Please see: Main menu => Help => About

**Comment by osenijoshua** [comment]
**Version 23.0.1.202303250535**

**Comment by E1izabeth** [comment]
The latest version is 24.0.5. Version 23.0.1 doesn't have these changes.

**Comment by osenijoshua** [comment]
For some reason, I'm unable to find any further update.

Edit 1: I just retried and now I got the update. Thanks. Will let you know how it goes.

**Comment by osenijoshua** [comment]
Works fine. Thank you all.

**Comment by JRDK92** [comment]
Hi @E1izabeth. How do you enable that feature? When executing a query, all I see is 'execute script (0%) in the lower right hand corner of the screen. There's no popup window or anything that indicates progress of a query in Dbeaver under my current version, 24.1.0. Does this only work for single executions, or entire scripts ?

**Comment by E1izabeth** [comment]
Hi, @jsauerland 
It works for a single query execution
![image](https://github.com/dbeaver/dbeaver/assets/28875055/fd759118-54cf-478b-b70d-1ab4f36ae9ab)

If you run a script and want to see the execution time of each query, you can check it in Query Manager
![image](https://github.com/dbeaver/dbeaver/assets/28875055/4f23cb49-9670-4d0b-8ab4-283b5054b271)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/5c3e5c35-faf6-43e7-b7ee-d1bc007d6000)

or in Execution Log
![image](https://github.com/dbeaver/dbeaver/assets/28875055/893e1627-d6d2-495f-972f-3d972141d617)
