### ISSUE TITLE
Option to disable the tooltip for linked .sql script files

### ISSUE THREAD

**Issue by jcachat** [dbeaver/dbeaver#9867]
I have lots of .sql script files included in my project.  If I hover the mouse over one of them, I get a giant tooltip showing me the contents of the file.  That seems helpful except that it makes it very difficult and distracting when I'm just trying to move my mouse to double-click a file to open it.  The tooltips are so big, they always cover up the list of files that I'm trying to look at.

Could an option be added to disable that tooltip for script files?  Or to tweak the time before it's shown to delay it so we have time to drag our mouse to the file we are looking for before the list gets covered up?

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
Tooltips configuration was added.
SQL script contents in tooltips was disabled (by default).

![image](https://user-images.githubusercontent.com/6398845/94563262-20367f80-026f-11eb-9971-2627db2ad465.png)

**Comment by kseniiaguzeeva** [comment]
Implemented

**Comment by jcachat** [comment]
Works great, thank you very much!
