### ISSUE TITLE
Oracle Reset Password

### ISSUE THREAD

**Issue by mahadea** [dbeaver/dbeaver#9869]
#### System information: 
- Windows 10 Build 1607
- 7.2.0
- Additional extensions

#### Connection specification:
- Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
- Driver name ojdbc6.jar
- Yes VPN

#### Describe the problem you're observing:
I am trying to connect to an oracle database for which I had set up the connection some time back. It pops up a window saying password is expired and has three fields to enter current(expired) pwd, and new password and new password confirmation.
But when I enter the relevant information it doesn't complete the connection, just pops up another window that says connection refused, password expired.
![Image_20200923002](https://user-images.githubusercontent.com/9688051/94182953-b46ba580-fe6f-11ea-92b6-d5a293daeb81.png)
![Image_20200923003](https://user-images.githubusercontent.com/9688051/94183051-d5cc9180-fe6f-11ea-8c70-ee3529a719f5.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed.
This functionality was broken after we added extra authentication method.

**Comment by uslss** [comment]
verified

**Comment by armyofda12mnkeys** [comment]
Is this closed because its fixed in a recent release? Just curious as having devs in my company download this month, Thanks!
