### ISSUE TITLE
database dropdown changes unexpectedly when opening second SQL Script

### ISSUE THREAD

**Issue by verajosemanuel** [dbeaver/dbeaver#987]
Using Mysql database with several databases in the same server, the database dropdown changes active database unexpectedly by itself when executing more than one script.

Steps to reproduce issue (Community Edition 3.7.8/3.8.0 Windows 7, java version "1.8.0_101", 32bits)

- open a script tab > select database from drop down > execute a simple select query
- open a second script tab > select a **different** database from drop down > Execute select

The dropdown database selector **changed to the first selected database in BOTH script tabs,** making subsequent sql sentences using the second script tab to fail.

"autosync connection with navigator" has no effect in order to correct this issue checked or not.

Worst of all is when databases has the same tables/fields. You can never be sure if recordset is from the desired database.

**Comment by serge-rider** [comment]
Currently active database change affects whole connection (you can see it in database navigator tree). So it will be changed for all connection editors.
So basically it is a feature, not a bug. But this may lead to problems, I agree.

Maybe it makes sense to have different active database for each editor. Although it is not obvious how this should be visualized in database navigator tree.

For now as a workaround you can create multiple connections (using copy-paste) and set different active databases in editors.

**Comment by tati-kru** [comment]
Hello @verajosemanuel,
Does this problem continue to be actual or workaround works fine?

**Comment by verajosemanuel** [comment]
Away from my desktop right now. I'll try to check ASAP

**Comment by uslss** [comment]
already implemented
