### ISSUE TITLE
support of dynamic path for folder on database configuration

### ISSUE THREAD

**Issue by heimankl** [dbeaver/dbeaver#9870]
https://dbeaver.com/ticket/48238/
Allow the creation of a variable on the Driver definition for the folder path.  Or allow an override in the database definition .
or allow registration of the same JDB driver as different driver managers.

The JDBC we are using has other connection specific data in the folder with the driver.  so we need different folders for each connection.
DBeaver does not allow this, see ticket.
thanks

**Comment by serge-rider** [comment]
@heimankl Is this driver publicly available?
We will need to test connection configuration with it.

**Comment by heimankl** [comment]
The driver is publicly available, however the data it has access to is per customer.
We have since found a way to pass in the credentials as a URL parameter.
I would be OK to review with you if needed.

**Comment by serge-rider** [comment]
After it looks like a problem in the driver. It re-loads class files o every connection. This leads to class loader errors.
The owrkaround is to create separate drivers for each connection.
