### ISSUE TITLE
Arrow key navigation in Tree widgets

### ISSUE THREAD

**Issue by tsjam** [dbeaver/dbeaver#9872]
Navigating a level up in tree widgets like "Projects" or "Database Navigator" with the left arrow key does not work.
Left and right arrow keys do work if a node is selected that supports collapsing and expanding.
What doesn't work is when pressing the left arrow key while a child node is selected. Expected behaviour would be that the selection changes to the parent node of the selected node. Instead, just nothing happens.

Could not find any error messages on console or the "Error log" view.

Other software on this system behaves like expected.

DBeaver Version: 7.2.1 CE
Operating System: Linux Mint 20
Window Manager: MATE
DB: Oracle 12c
DB Driver: JDBC Thin Driver

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by akilovich** [comment]
Fixed.

**Comment by uslss** [comment]
verified
