### ISSUE TITLE
DBeaver Performance Issue Due to Meta Data calls

### ISSUE THREAD

**Issue by vivek-billore** [dbeaver/dbeaver#9875]
Hi Team

We are trying to setup DBeaver client SQL tool, we have setup the connection, but while testing we’ve run into performance issues around the client trying to read the system metadata where each table being read submits a show all columns statement for a given database and it takes quite some time to load those. Can you help us in setting this up, is there any property/setting within the tool which can help us avoid this.

Regards

Vivek

**Comment by uslss** [comment]
hi @vivek-billore ,
what database do you use?

**Comment by vivek-billore** [comment]
Hi @uslss - we are using Snowflake

**Comment by vivek-billore** [comment]
we have done some analysis and observed that when calling databasemetadata.getcolumns() api, it is defaulting to a search on database because it failed to find the table name. The reason it is not able to find the table name is because it is not escaping '_' (Underscore)

This means that DBeaver needs to add some logic to escape underscores or the underscores will be treated as wildcards when they send the query. When treated as a wildcard, the api will default to searching for all the columns in the database, which is causing a huge performance degradation.

**Comment by nlindner** [comment]
I'm having the same issue (connecting with the Snowflake JDBC 3.13.4 driver, via DBeaver 21.1.0). It's making using DBeaver incredibly painful. For context, the database I'm connecting to has underscores in the catalog name, the schema name, the table names, and the column names. Even for a small, constrained query, it's taking >30 seconds just to get the table and column metadata.

Could I provide any details that would help you debug this, or do you need a user to provide feedback? If so, I will gladly help if I am able. 

If it helps, I'm seeing a similar issue reported to Snowflake as [Improve performance of JDBC getMetaData() driver APIs](https://community.snowflake.com/s/question/0D53r00009sz79fCAA/improve-performance-of-jdbc-getmetadata-driver-apis), and the accepted answer is to escape any underscores.

**Comment by NilsDiet** [comment]
I am using Snowflake with dbeaver as well and I am quite happy.
But I am facing exactly the same issues nlindner mentioned.
All our schema/table names have underscores so for auto completion and any meta operation dbeaver will try to fetch the columns for everything in the database instead of the actual object resulting into 30 seconds response time.
Not using the meta data at all is an workaround but in this case lacking the feature of using auto completion.
So any ideas how to actually fix this or is this topic not relevant enough to get fixed?
