### ISSUE TITLE
DBeaver doesnt start on RHEL 7.5

### ISSUE THREAD

**Issue by sachin234s** [dbeaver/dbeaver#9876]
Hi team,

i have installed the latest version of Dbeaver on my RHEL 7.5 VM. However , i am unable to start it and facing the error. Please refer the attachment log for details

# ./dbeaver
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 7.2.1.202009201907]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.700.v20200106-1020]
Dbeaver:
An error has occurred. See the log file
/usr/share/dbeaver/configuration/1601062494453.log.

[1601062494453.log](https://github.com/dbeaver/dbeaver/files/5283257/1601062494453.log)

java version
# java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

Please let me know how to proceed

Regards,
Sachin S
Hewlett Packard Enterprise RnD

**Comment by serge-rider** [comment]
You need GTK3 in order to run DBeaver on RHEL.

What GTK version do you have?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
