### ISSUE TITLE
DBeaver 7.2 always open new result tab

### ISSUE THREAD

**Issue by Eddie9710** [dbeaver/dbeaver#9881]
DBeaver will always open a new result tab no matter whether you use the "Execute SQL statement" or "Execute SQL statement in new tab" command. It is annoying because you have to constantly close the old tabs.
This only happens if you already have at least 2 result tabs open. Both DBeaver EE 7.2 and DBeaver CE 7.2.1 have the same issue. I am running the Windows version in Windows 10 1909 and the database I am working on is Oracle 12c.
I did some research before I post the issue here and did not find any reports of this issue (or similar issues). Thanks in advance for any help.

**Comment by uslss** [comment]
Hi @Eddie9710 ,
could you try to change setting in the confirmation window?
![image](https://user-images.githubusercontent.com/31996417/94407245-e46ebd80-017b-11eb-865c-cef1441b0517.png)
then choose Yes button (and, probably, check Don't ask me again checkbox).
![image](https://user-images.githubusercontent.com/31996417/94407440-1bdd6a00-017c-11eb-9857-654695607c29.png)
seems it should solve your problem

**Comment by jeffreydmohler** [comment]
I have the same issue. Can this issue be reopened?  It is really frustrating to not have the Control+Enter option (to execute a query) working properly anymore.

**Comment by ShadelessFox** [comment]
Hello @jeffreydmohler, this issue was fixed in 7.3.1. Can you download newer version to see if your problem still occurs?

**Comment by WVUTampaAlum** [comment]
This issue still persist. There must be multiple queries in the window and clicking 'execute SQL Script' more than 1 time keeps opening up multiple result tabs. v7.3.5

**Comment by ShadelessFox** [comment]
Hello @WVUTampaAlum,

This is happening because the previous query is not finished at the moment you start a new one.

**Comment by WVUTampaAlum** [comment]
I'm 100% sure the queries are finished.

**Comment by ShadelessFox** [comment]
Please, create a new issue and provide detailed steps how to reproduce it, along with database info.

**Comment by WVUTampaAlum** [comment]
mysql (execute sql script - alt x)
--  create table a(col1 varchar(32) null);

select * from a;
select * from a;
select * from a;
select * from a;

**Comment by PaulBeauregard-CoT** [comment]
I am seeing the same problem, can this be re-opened?

**Comment by ShadelessFox** [comment]
Hello @PaulBeauregard-CoT,

We are aware of this issue. Please refer to https://github.com/dbeaver/dbeaver/issues/16402
