### ISSUE TITLE
Unable To Open DBeaver

### ISSUE THREAD

**Issue by Eddie-Hartman** [dbeaver/dbeaver#9882]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
7.2.0
- Additional extensions
N/A

#### Connection specification:
- Database name and version
N/A
- Driver name
N/A
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
N/A

#### Describe the problem you're observing:
When I open dbeaver, it immediately crashes. This happens whenever I have a large ERD open then close the software.
When I try to re-open the software, it becomes unresponsive.

This is pretty impactful for me, but I've at least found a workaround where I go to my workspace and remove the diagram from the workbench.xmi file in the sharedElements section so that it doesn't persist the next time I open the software. (I'm sure that this probably causes other issues, but I was hoping it was going to be a one-off weird issue that once I got working again it wouldn't be reproducible)

#### Steps to reproduce, if exist:
See above, unfortunately, I cannot share the diagram file. I attached the log though. Hope it helps.

#### Include any warning/errors/backtraces from the logs

[log.txt](https://github.com/dbeaver/dbeaver/files/5285610/log.txt)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
hi @Eddie-Hartman ,
cannot reproduce an issue. What database do you use? How many objects does diagram have?
probably some special steps are needed?

**Comment by Eddie-Hartman** [comment]
Did you take a look at the log? Just wanted to make sure before providing a
lot more detail. That would have to be much later today at the earliest.

**Comment by uslss** [comment]
@Eddie-Hartman ,
yes, but still cannot reproduce an issue.
Probably it depends on database.

**Comment by Eddie-Hartman** [comment]
I was using a SQL server database with easily over 500 objects in the
diagram.

**Comment by Eddie-Hartman** [comment]
I ran into this issue again. Additional detail being that the diagram must be the first tab that dbeaver tries to load.

I had a script and the diagram open and it tried to load the script first and opened fine. When I closed the script then re-opened dbeaver it would have the same crash behavior and I would have to edit workbench file again.

**Comment by uslss** [comment]
is it also reproducible against the recent version?

**Comment by Eddie-Hartman** [comment]
I'm using the enterprise 7.2.0 version. I could attempt to use the community version at some point and see, but no promises that will happen soon. I can definitely try once enterprise 7.3.0 comes out.

**Comment by Eddie-Hartman** [comment]
@uslss I upgraded to 7.3 today and still experience this issue.

**Comment by uslss** [comment]
cannot reproduce an issue against 21.1.0.
If it is still actual for you - feel free to reopen it with additional info

**Comment by Eddie-Hartman** [comment]
@uslss Sorry for the delayed response. I got a new machine and was setting it up.

On my new machine with version 21.1.0. SQL Server 2019 dev. I transferred the file over from my old machine and works perfectly fine as long as it is not when dbeaver is first launching.

The database has over 350 tables and the diagram has 35 notes in it to give a scope of size. The file itself is 109 kb.

I can't provide the file itself, but if you need anything else feel free to ask.
