### ISSUE TITLE
Display in the standard cinnamon theme

### ISSUE THREAD

**Issue by oblitsov** [dbeaver/dbeaver#9883]
Hello! I use centos 7 and cinnamon with the standard "minty-dark" theme. However, some of the labels are not visible or poorly visible, because they do not use the theme colors.

**Comment by uslss** [comment]
Hi @oblitsov ,
could you provide some screenshots that show the problem?
thanks in advance

**Comment by oblitsov** [comment]
Screenshots
![1](https://user-images.githubusercontent.com/4876653/94415234-8788fc80-01a7-11eb-89d1-9d39c6b18554.png)
![2](https://user-images.githubusercontent.com/4876653/94415243-8a83ed00-01a7-11eb-9594-2d621c647e12.png)

**Comment by beefes** [comment]
Hello.
Same happening in Version 7.3.2.202101032114 on Ubuntu:
![image](https://user-images.githubusercontent.com/3812226/103875936-f0e3aa00-50ca-11eb-9707-f5226412366d.png)
![image](https://user-images.githubusercontent.com/3812226/103876100-238da280-50cb-11eb-8271-95f67c4836de.png)

**Comment by beefes** [comment]
Changing to dark theme solves the issue.
THanks
https://github.com/dbeaver/dbeaver/issues/5869
