### ISSUE TITLE
When trying to connect to PostgreSQL 11 through an SSH tunnel: "The connection attempt failed"

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#9886]
#### System information: 
- Operating system (distribution) and version
Windows 10 64 bit 2004
- DBeaver version
7.2.1.202009201907
- Java version 
1.8.0_261
- Additional extensions

#### Connection specification:
- Database name and version
Azure PostgreSQL 11
- Driver name
JDBC PG Driver 42.2.16
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
External local SSH tunnel (using PUTTY with a jump server)

#### Describe the problem you're observing:
I'm able to connect with other clients (Azure Data Studio / PGAdmin 4) to Azure Postgres DB through a local external tunnel (localhost:5432) but not with DBeaver.
Getting error: "The connection attempt failed." without any other output.

(Originally, I tried to define an SSH Tunnel inside the connection in DBeaver but got the same error)

#### Steps to reproduce, if exist:
1. Create Azure PostgreSQL DB
2. Create internal/external SSH tunnel to it
3. Try to connect

**Comment by uslss** [comment]
Hi @yonisade ,
did dbeaver through any error message (after click at Test tunnel configuration) in case of defining ssh tunnel inside the connection?
thanks in advance for the response

**Comment by yonisade** [comment]
I got the same error if I define it internally.

**Comment by yonisade** [comment]
Exception Stack Trace:
An exception stack trace is not available.

Session Data:
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

I also want to mention that I have a proxy script setup active in Windows 10, but it works with other clients as I mentioned above.
I also tried using the proxy in DBeaver connection but got "timeout: socket is not established"

**Comment by yonisade** [comment]
Solved it by using older driver: postgresql-42.2.14.jar
