### ISSUE TITLE
Cant connect to Oracle from DBeaver in Windows 10 pro

### ISSUE THREAD

**Issue by tvrhossain** [dbeaver/dbeaver#9887]
While trying to connect to Oracle 18C(express edition) from Dbeaver 7.2.0 in Windows 10 Pro (I m using the password that I set during Oracle installation), I am getting the error: **connection refused, IO ERROR:Network Adapter could not establish the connection**

![image](https://user-images.githubusercontent.com/6359871/94365841-ee4ddd80-00f5-11eb-8582-ef3857fbf7af.png)
JDBC DRIVER DOWNLOADED
![image](https://user-images.githubusercontent.com/6359871/94365850-fb6acc80-00f5-11eb-8709-4a81682d887b.png)

**Comment by uslss** [comment]
Hi, @tvrhossain 
Do you use tunnels or proxies (SSH, SOCKS, etc), or database is local?
Do you try to connect using some other client?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
