### ISSUE TITLE
Search according to a partial database name 

### ISSUE THREAD

**Issue by nlpsuge** [dbeaver/dbeaver#9889]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I cannot search the database by typing partial database name.

**Describe the solution you'd like**
1.Split the 'Enter a part of table name here' entry to two entries: one for entering a part of table name, the other for entering a part of database name.

**Describe alternatives you've considered**
a)Show 'Enter a part of table name here' entry when clicking a specified database. 
b)Show 'Enter a part of database name here' entry when clicking the Databases. 

**Additional context**

**Comment by uslss** [comment]
Hi @nlpsuge ,
the feature is already implemented in the scope of #9718 and will be available in 7.2.2.
anyway, thanks for suggestion
