### ISSUE TITLE
Cant store connection permanently

### ISSUE THREAD

**Issue by petersternwald** [dbeaver/dbeaver#9891]
Hi
I must create hundred of connection in dbeaver (7.2). How can i do this automatically?
I use follow line, but this does not store the connection permanently:
.\dbeaver.exe -con "name=hugo_code|driver=oracle|url=jdbc:oracle:thin:@10.6.16.20:1526/dg_hugobvp|user=xxx|password=xxx|folder=BAU|savePassword=true|create=true"

Thans for your help.
Greetings Peter

**Comment by uslss** [comment]
You could find information here https://github.com/dbeaver/dbeaver/wiki/Admin-Manage-Connections
