### ISSUE TITLE
Error with SSL PostgreSQL

### ISSUE THREAD

**Issue by stegausaq** [dbeaver/dbeaver#9898]
I obtain this error.

The hostname sl...326 could not be verified by hostnameverifier PgjdbcHostnameVerifier.

- Operating system (distribution) and version
      Windows 10 Enterprise version 2004
- DBeaver version
     7.2.1
- Driver
     postgresql-42.2.14.jar

PostgreSQL is on version 12 and ssl is configured.  The server sl...326 is configure on pg_hba.conf...

**Comment by uslss** [comment]
Could you provide screenshot with your SSL configuration and error log?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
