### ISSUE TITLE
Import Data UI not as Intuitive as Before

### ISSUE THREAD

**Issue by darren-teo** [dbeaver/dbeaver#9900]
#### System information: 
- Windows 10 Pro 2004
- 7.2.1

#### Connection specification:
- PostgreSQL 12.2

#### Describe your question:
I have been using the "Import Data" feature periodically to import CSV into a table in my database. I have just upgraded to version 7.2.1 and I noticed the "Import Data" wizard has changed dramatically. The key feature where I specify a "custom value" is no longer available. The columns mappings are also not as automated as before, requiring manual inputs to change from "create" to "existing". I have to fall back to version 7.1.4 to maintain these features.

Are there plans to bring back or is there a way to enable the functionalities of the previous wizard?
##### Data Import on 7.2.1
![7 2 1](https://user-images.githubusercontent.com/32067070/94525520-c5008f00-0266-11eb-8744-743dd6142e12.jpg)
##### Data Import on 7.1.4
![7 1 4](https://user-images.githubusercontent.com/32067070/94526258-d8602a00-0267-11eb-8499-64766d7faba1.jpg)

**Comment by uslss** [comment]
obsolete
