### ISSUE TITLE
Is there any way to turn off these $(*^%&^@$ tooltips

### ISSUE THREAD

**Issue by hrbruen** [dbeaver/dbeaver#9901]
#### Describe the problem you're observing:
I am trying to read, for example, the list of scripts. But every time I pause a HUGE BLACK BLOB OF USELESS information obscures the list. This occurs everywhere.
Surely in this day and age there should be a setting that gets rid of this undesirable and unpleasant effect.

tia

**Comment by uslss** [comment]
thanks for the suggestion. close this issue as a duplicate of #9867 .
hope, it will be implemented ASAP.
