### ISSUE TITLE
Is it possible to open synonym table, not just info view?

### ISSUE THREAD

**Issue by andrzejdziekonski** [dbeaver/dbeaver#9902]
**Is your feature request related to a problem? Please describe.**
It is a bit frustrating that when i have synonym tables (MsSQL) and i can easily find them via ctrl+shift+d i cannot visit those tables unless i focus select correct database in the navigator window on the left. Instead i see only some info view which is not much usfeul to me.

**Describe the solution you'd like**
I would like it to behave this way that when i find synonym table and i click open i am moved to this table with all the features that table view has.

Thanks, i enjoy dbeaver much besides this :)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
@andrzejdziekonski You can see synonym target in the synonym editor:
![image](https://user-images.githubusercontent.com/6398845/111993299-81a52000-8b27-11eb-99db-b75847926f89.png)

Just click the link to jump to actual table.

PS I've added several improvements, including synonym delete support.

**Comment by uslss** [comment]
Link isn't available in case Synonym is created using a fully qualified table name
works ok, link is shown:
```sql
CREATE SYNONYM test23  
FOR dimdate;
```
Doesn't work, link is N/A:
```sql
CREATE SYNONYM test23  
FOR master.dbo.dimdate;
```
![image](https://user-images.githubusercontent.com/31996417/112119042-0ba7c400-8bce-11eb-9421-ae6692251776.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
