### ISSUE TITLE
Server-side results ordering doesn't work

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#9905]
There is an option in Data Editor > Server-side results ordering, which is enabled in my case but when I view data and choose ordering by clicking on the column header arrows then the results are reordered by DBeaver and not by the server. The problem is that accented characters are sorted incorrectly because only the database knows how to use the desired collation and sort properly. To force server-side ordering I have to refresh the view after choosing ordering.

The option "Server-side results ordering" doesn't seem to do anything for me, whether it's on or off the behaviour is the same: application ordering after choosing column to order and server-side ordering after refreshing. I don't know what this option is supposed to do but I would expect it to force server-side ordering in all cases.

This is tested with MySQL 5.7 on Dbeaver 7.2.1.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by ShadelessFox** [comment]
An option in Data Editor preferences was added to force server-side ordering:
![image](https://user-images.githubusercontent.com/35821147/100514366-1ead0900-3185-11eb-8f3a-5e27069e7bdc.png)

**Comment by uslss** [comment]
verified
