### ISSUE TITLE
FATAL: connection requires a valid client certificate

### ISSUE THREAD

**Issue by Yuvirenu** [dbeaver/dbeaver#9914]
#### System information: 
- Operating system (distribution) and version
Windows 2016 STandardard
- DBeaver version
7.1.3.202007192031
#### Connection specification:
- Database name and version
pg_us_at38638_te2_806 , PostgresQL 11.5
#### Describe your question:
I am trying to connect to my PostgreSQL server but psql is complaining that I don't have a valid client certificate. The same credentials works fine using PGadmin.

Status : Failure -Test failed: FATAL: connection requires a valid client certificate

**Comment by Yuvirenu** [comment]
![image](https://user-images.githubusercontent.com/72101895/94603748-4d2d6700-025c-11eb-84bd-5cbff5688b15.png)

**Comment by Yuvirenu** [comment]
![image](https://user-images.githubusercontent.com/72101895/94603806-61716400-025c-11eb-991c-3487881ba096.png)

**Comment by Yuvirenu** [comment]
![image](https://user-images.githubusercontent.com/72101895/94603838-6e8e5300-025c-11eb-94de-a685faebc126.png)

**Comment by uslss** [comment]
Hi @Yuvirenu ,
do you use SSL?

**Comment by Yuvirenu** [comment]
I am not using SSL for db connection.

**Comment by uslss** [comment]
@Yuvirenu 
Can you check if issue is reproducible against 7.2.2 version?
Thanks in advance

**Comment by uslss** [comment]
there are not any updates for a long time
The issue is closed.
If it is still actual for you - feel free to reopen it
