### ISSUE TITLE
Generated SQL INSERT from Data Export ignores "Data rows per statement"

### ISSUE THREAD

**Issue by andilem** [dbeaver/dbeaver#9915]
When exporting a table as SQL INSERT statements, the setting "Data rows per statement" is ignored. The result consists of one INSERT statement per row.

Note: I'm using Oracle. The problem seems to be the same as #4751.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by LonwoLonwo** [comment]
Oracle does not support multi-insertion as standard, I had to use the option from here: https://stackoverflow.com/a/93724/14220989

**Comment by uslss** [comment]
verified
