### ISSUE TITLE
GREENPLUM OR POSTGRE SQL‘s  sql edit & debug

### ISSUE THREAD

**Issue by lctlover** [dbeaver/dbeaver#9916]
use gp or pg sql edit ,while exists some errores only Position ,like this  SQL 错误 [42601]: ERROR: syntax error at or near "SELECT"
  Position: 51

**Comment by uslss** [comment]
hi @lctlover ,
cannot catch your issue. Could you clarify it a bit more?
Thanks in advance

**Comment by uslss** [comment]
there are not any updates for a long time
The issue is closed.
If it is still actual for you - feel free to reopen it
