### ISSUE TITLE
import data for MySQL.  to support import sql file.

### ISSUE THREAD

**Issue by realtanwei** [dbeaver/dbeaver#9918]
the dbeaver is only support CSV & DB's table . but i have a sql (INSERT/UPDATE..) file. i wish import it by dbeaver's import data function...

thanks // ^_^//

**Comment by MrMuminov** [comment]
i want to do the same :)

**Comment by uslss** [comment]
Seems it is not possible.
You could use Restore option for MySQL and PostgreSQL databases to import data from sql file.
Also you could Open SQL file in SQL editor and execute it

**Comment by allanlaal** [comment]
please reopen

opening a few GB in the SQL Editor is not possible

**Comment by allanlaal** [comment]
additional options for .sql dump data import:

- Ignore Missing cols
- Ignore Missing tables

**Comment by allanlaal** [comment]
* Continue on any Error
