### ISSUE TITLE
Relation 

### ISSUE THREAD

**Issue by MrMuminov** [dbeaver/dbeaver#9919]
The program is very well designed. Thank you

The error is small. in the first figure, the tables are linked together and the value of the linked table is shown correctly.
#1 https://i.imgur.com/k0CvZih.png

but in Fig. 2 it gives an error in realtion
#2 https://i.imgur.com/Xw2nxGx.png

My device: Acer Aspire 3
OS: Ubuntu Desktop 20.04

**Comment by MrMuminov** [comment]
foreign key 
https://i.imgur.com/Zz2isK2.png

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. Which database and DBeaver version do you use? Is it possible to send a DDL example to reproduce the bug?

**Comment by uslss** [comment]
there are not any updates for a long time
The issue is closed.
If it is still actual for you - feel free to reopen it
