### ISSUE TITLE
[PostgreSQL] Ability to add column comment to view/materialized view

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#9921]
Ability to add column comment to view/materialized view through UI

Now there is no way to edit the columns of views/materialized views at all, so it's not a trivial task to make it possible to edit only comments.

**Comment by detkliff** [comment]
version 7.3.3  not changed

**Comment by detkliff** [comment]
21.0.3 added this future. Ok

**Comment by LonwoLonwo** [comment]
The feature is not implemented yet.

**Comment by LonwoLonwo** [comment]
Closed as duplicate of https://github.com/dbeaver/dbeaver/issues/16337
