### ISSUE TITLE
Start browsing table data

### ISSUE THREAD

**Issue by limenleap** [dbeaver/dbeaver#9930]
**Is your feature request related to a problem? Please describe.**
No problem. 

**Describe the solution you'd like**
This would be a nice functionality to connect between apps. An external app can send a command-line and dbeaver can open database as well as show the data  in a table

**Describe alternatives you've considered**
Only alternative is to load the database into Dbeaver, and manually browse data in table

**Additional context**
The command line has all the options EXCEPT one for browsing a specific table. Maybe an extra parameter in the _-con_ argument of the command-line argumetns?

**Comment by uslss** [comment]
It is already implemented.
More information could be found here https://github.com/dbeaver/dbeaver/wiki/Admin-Manage-Connections
