### ISSUE TITLE
DBeaver Community > SQLite > CHECK Constraints Support?

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#9931]
#### System information: 
- Operating system (distribution) and version macOS 10.15.7
- DBeaver version 7.2.1

#### Connection specification:
- Database name and version SQLite 3.32.3

#### Describe your question:
Does DBeaver Community support CHECK Constraints for SQLite databases? Where in the UI would it be found?

**Comment by uslss** [comment]
it is not implemented yet.
Thanks for suggestion

**Comment by uslss** [comment]
will be implemented in #14499
