### ISSUE TITLE
Incorrect statement is generated for column creation/deletion using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9935]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.2.2

#### Connection specification:
- Database name and version Hive

#### Describe the problem you're observing:
The column couldn't be created using UI - the incorrect statement is generated
A generated statement that ends up with an error:
`ALTER TABLE newtable ADD Column2 VARCHAR(100);`
Correct statement:
`ALTER TABLE newtable ADD COLUMNS (Column3 VARCHAR(100));`

The similar issue appears when trying to drop column.
Table:
`CREATE TABLE test_change (a int, b int, c int);`
A generated statement that ends up with an error:
`ALTER TABLE test_change DROP COLUMN c;`
Correct statement (delete column c):
`ALTER TABLE test_change REPLACE COLUMNS (a int, b int);`

**Comment by LonwoLonwo** [comment]
Adding and deleting columns fixed

**Comment by LonwoLonwo** [comment]
The ability to rename a table has also been added.

**Comment by uslss** [comment]
verified
