### ISSUE TITLE
"No Data" is shown in resultset in case of execution queries like CREATE

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9936]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.2.2

#### Connection specification:
- Database name and version Hive

#### Describe the problem you're observing:
No data is still shown as resultset after query execution (e.g. CREATE TABLE test_change123 (a int, b int, c int);
![2020-10-01_14h21_26](https://user-images.githubusercontent.com/31996417/94803208-a549a200-03f1-11eb-9484-253b9314d698.gif)

For other dbs Statistics tab is shown in this case
![image](https://user-images.githubusercontent.com/31996417/94803183-9cf16700-03f1-11eb-8c3c-bd54a43c99e2.png)

**Comment by tati-kru** [comment]
I think it was fixed in 7.2.4

**Comment by uslss** [comment]
verified (snowflake)
