### ISSUE TITLE
Script preview isn't shown in Create new script pop-up if Show file contents in tooltips unchecked

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9938]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.2.2

#### Describe the problem you're observing:
Script preview isn't shown in Create new script pop-up if Show file contents in tooltips unchecked
#### Steps to reproduce, if exist:
1. Disable Show file contents in tooltips
1. Start New script creation
![image](https://user-images.githubusercontent.com/31996417/94811039-83561c80-03fd-11eb-9607-dba8b528b543.png)

**Comment by serge-rider** [comment]
Fixed
