### ISSUE TITLE
Cannot update/delete table values using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9945]
#### System information: 
- Operating system (distribution) and version win 10
- DBeaver version 7.2.2

#### Connection specification:
- Database name and version Hive 2.3.2

#### Describe the problem you're observing:
Table values cannot be updated using UI - an error appears.
```
-- Auto-generated SQL script. Actual values for binary/complex data types may differ - what you see is the default string representation of values.
UPDATE `default`.product
	SET product_vendor_id=5
	WHERE product_id=1;
```
Error:
`SQL Error [10294] [42000]: Error while compiling statement: FAILED: SemanticException [Error 10294]: Attempt to do update or delete using transaction manager that does not support these operations.`

**DELETE:**
```
-- Auto-generated SQL script #202010021224
DELETE FROM `default`.product
	WHERE product_id=1;
```
Error:
```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Fri Oct 02 12:23:36 MSK 2020
org.apache.hadoop.hive.ql.parse.SemanticException:Attempt to do update or delete using transaction manager that does not support these operations.

```
Note: INSERT INTO works ok, values could be added.

**Comment by serge-rider** [comment]
ACID operations work in Hive only in certain tables.
See https://stackoverflow.com/questions/34198339/attempt-to-do-update-or-delete-using-transaction-manager-that-does-not-support-t

We probably need to add this config to our Hive test server.
