### ISSUE TITLE
VFKs aren't shown in Reference Panel

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9946]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 7.2.2

#### Connection specification:
- Database name and version Hive

#### Describe the problem you're observing:
Virtual Foreign Keys isn't visible in Reference Panel
![2020-10-02_13h09_56](https://user-images.githubusercontent.com/31996417/94912842-ee146000-04b0-11eb-8047-9107861e20f3.gif)

**Comment by serge-rider** [comment]
Fixed
The bug was caused by exception "Method not supported" in Hive driver.

**Comment by uslss** [comment]
verified
