### ISSUE TITLE
Copy/Paste of RAW data changes content

### ISSUE THREAD

**Issue by andilem** [dbeaver/dbeaver#9947]
#### System information: 
- Operating system (distribution) and version: Win 10
- DBeaver version : 7.2.0

#### Connection specification:
- Database name and version: Oracle 19

#### Describe the problem you're observing:
Pasting copied RAW data changes its content.

#### Steps to reproduce, if exist:
A column with data type RAW and some data in row 1. Copy data from row 1 (Ctrl+C), paste it into row 2 (Ctrl+V). You will see that the pasted data in row 2 is different than the copied data from row 1.
I did it with type RAW(40) and INSERT INTO Table (Column) VALUES ('356A192B7913B04C54574D18C28D46E6395428AB')

**Comment by uslss** [comment]
Thanks for the bug report

**Comment by LonwoLonwo** [comment]
Interesting. Error appears in case String view format, copy/paste work fine, when data in Hex or Base64 format. 

![2020-10-27 12_32_52-DBeaver Enterprise 7 3 0 - 9947](https://user-images.githubusercontent.com/45152336/97283482-f4e48780-1850-11eb-8301-3e3f895d668e.png)

**Comment by serge-rider** [comment]
Binary value copy-paste implemented.

Note: we probably need to support images copy-paste as well. In some other ticket.

**Comment by uslss** [comment]
verified
