### ISSUE TITLE
Error appears when Reference tab is opened

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9948]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 7.2.2

#### Connection specification:
- Database name and version hive
#### Describe the problem you're observing:
Error appears when Reference tab is opened
![image](https://user-images.githubusercontent.com/31996417/94915154-0a1a0080-04b5-11eb-8cdf-40c74a7890ca.png)

**Comment by serge-rider** [comment]
This is not a dbeaver bug. Hive driver just doesn't support references read, we can't fix this.
Hopefully future Hive driver versions will add this feature.
