### ISSUE TITLE
[PostgreSQL] Custom connection view-Hide folders: error appears when Permissions table tab opens

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9950]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version DBeaver 7.2.2 EA

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
1. Set Custom connection view-Hide folders
2. Open Permissions tab in table Properties

Actual result: error appears: Can't detect root node for objects tree
![dbeaver_JS17yBqvJU](https://user-images.githubusercontent.com/51405061/94920947-fa53e980-04bf-11eb-8ad4-a4bcb58dd257.png)

**Comment by akilovich** [comment]
Disabled that tab altogether when the Hide folders option selected.

**Comment by kseniiaguzeeva** [comment]
By some reason Custom view>Hide folders differs for PostgreSQL 10 and 12
![P12](https://user-images.githubusercontent.com/51405061/98829639-7e4baa80-244a-11eb-811a-a56017ef15af.png)
![P10](https://user-images.githubusercontent.com/51405061/98829644-7f7cd780-244a-11eb-83bb-5bb2268a0bb6.png)

**Comment by akilovich** [comment]
The reasons for that lay somewhere else.

**Comment by kseniiaguzeeva** [comment]
closed
