### ISSUE TITLE
[PostgreSQL] Comment in DDL will appear twice if View is created with a comment

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9951]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.2 EA

#### Connection specification:
- Database name and version PostreSQL

#### Steps to reproduce, if exist:
1. Create a view via UI
2. Fill a comment via view UI
3. Press Save

Actual result: DDL Window appears with 2 comment statements
![dbeaver_TXAsbbqYf5](https://user-images.githubusercontent.com/51405061/94932402-b10c9580-04d1-11eb-94d3-001ab8ae589d.png)

**Comment by LonwoLonwo** [comment]
Fixed in 7.2.3

**Comment by kseniiaguzeeva** [comment]
verified
