### ISSUE TITLE
How to view functions?

### ISSUE THREAD

**Issue by caverman11** [dbeaver/dbeaver#9952]
I'm new with dbeaver and I'm using it to connect to an Oracle 12 database. I'm trying to look at a function and I can not find where I can view/edit functions in the UI.

**Comment by uslss** [comment]
Hi @caverman11 ,
you could find both functions and procedures in Procedure folder
![image](https://user-images.githubusercontent.com/31996417/94953701-a8778780-04f0-11eb-8adc-a2674067d02f.png)
