### ISSUE TITLE
Cannot establish tunnel - invalid privatekey

### ISSUE THREAD

**Issue by jrmarco** [dbeaver/dbeaver#9955]
#### System information: 
- Ubuntu 20.04
- DBeaver	7.2.1.202009201907	org.jkiss.dbeaver.core.product
- Java openjdk version "14.0.1" 2020-04-14
- Java OpenJDK Runtime Environment (build 14.0.1+7-Ubuntu-1ubuntu1)
- Java OpenJDK 64-Bit Server VM (build 14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing)

#### Connection specification:
- MySql
- Driver MySql5
- Connection is done via SSH tunnel

#### Describe the problem you're observing:
Cannot connect on remote DB via SSH tunnel
I've just updated my DBeaver CE version today along with Ubuntu. At first i tought was something related to the Ubuntu update, but than I tried the same connection with a different Sql Client using same configuration and the same key, the connection works. Before the update the same key was used to open the connection as usual. 
Private key have format : -----BEGIN OPENSSH PRIVATE KEY----- .... -----END OPENSSH PRIVATE KEY-----
#### Steps to reproduce, if exist:
Open the connection
#### Include any warning/errors/backtraces from the logs
Error alert : 
- Can't initialize tunnel  
  - Cannot establish tunnel   
  - Cannot establish tunnel
    - invalid privatekey: [Bxxxxxxxxxxx   
    - invalid privatekey: [Bxxxxxxxxxxx   

Log:
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: 2020-10-02 17:55:11.014 - Connect with 'Remote-US-SFW1' (mysql5-174e9dd1842-6f2bab05b6f8ba8c)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: 2020-10-02 17:55:11.018 - Connection failed (mysql5-174e9dd1842-6f2bab05b6f8ba8c)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: 2020-10-02 17:55:11.019 - org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:830)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:64)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:157)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:199)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: Caused by: org.jkiss.dbeaver.DBException: Cannot establish tunnel
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:107)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:141)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:825)
...
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: Caused by: com.jcraft.jsch.JSchException: invalid privatekey: [B@388b616c
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at com.jcraft.jsch.KeyPair.load(KeyPair.java:664)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at com.jcraft.jsch.KeyPair.load(KeyPair.java:561)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at com.jcraft.jsch.JSch.addIdentity(JSch.java:406)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at com.jcraft.jsch.JSch.addIdentity(JSch.java:366)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:61)
...
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: 2020-10-02 17:55:11.068 - Cannot establish tunnel
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: org.jkiss.dbeaver.DBException: Cannot establish tunnel
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:107)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:141)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:825)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:64)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:157)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:199)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: Caused by: com.jcraft.jsch.JSchException: invalid privatekey: [B@388b616c
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at com.jcraft.jsch.KeyPair.load(KeyPair.java:664)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at com.jcraft.jsch.KeyPair.load(KeyPair.java:561)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at com.jcraft.jsch.JSch.addIdentity(JSch.java:406)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at com.jcraft.jsch.JSch.addIdentity(JSch.java:366)
Oct  2 17:55:11 ub101 dbeaver.desktop[15273]: #011at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:61)
...

**Comment by uslss** [comment]
Hi @jrmarco ,
you could check if the issue is solved in EA https://dbeaver.io/files/ea/
probably it was solved in scope of #5845

**Comment by jrmarco** [comment]
Can confirm, issue gone on 7.2.2. Sorry for double posting, I didn't search well
