### ISSUE TITLE
Useless tooltip is shown in Scale column for interval type 

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9958]
#### System information: 
- Operating system (distribution) and version win 10 
- DBeaver version 7.2.2

#### Connection specification:
- Database name and version postgres
#### Describe the problem you're observing:
Useless tooltip is shown in Scale column for interval type 
![image](https://user-images.githubusercontent.com/31996417/94947464-5af61d00-04e6-11eb-95a8-f1ec88a23fb1.png)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
