### ISSUE TITLE
Connecting to the heroku postgres takes too long

### ISSUE THREAD

**Issue by foremtehan** [dbeaver/dbeaver#9962]
DB: PostgreSQL 12.4

When i try to connect to heroku's postgress it take about 20second to fetch information about the current table, This is happening when i dont use the connection for about 10 minutes, it sound like it going to sleep and takes too much time to wake up.

**Comment by kseniiaguzeeva** [comment]
Please tell:
your OS, 
DBeaver version,
do you use SSH, SSL etc?

**Comment by foremtehan** [comment]
Ubuntu 18.04.5 LTS
DBeaver: 7.2.1

I dont use any ssl ssh,

step to reproduce:

1. create a free heroku account And create a new app
2. click on your app and go to the Resource tab and click on Find more add-on
3. choose and install Heroku Postgres
4. copy your postgres credentials via Setting tab and click Reveal Config Vars
5. push your app from git and import 20000 dummy records to a table
6. go to the dbeaver and create postgres driver
7. open that table contains 20k records and minimize the app about 30minutes
8. after 30 minutes go to the app again refresh database by Pressing F5

it takes 20second for me hear.
