### ISSUE TITLE
Missing tabbed editors?

### ISSUE THREAD

**Issue by Duplicated** [dbeaver/dbeaver#9963]
#### System information: 
- Operating system (distribution) and version: **Ubuntu 18.04.5**
- DBeaver version: **7.2.2**

#### Connection specification:
- Database name and version: Postgres via postgres-jdbc

#### Describe your question:
I recall tabbed editors used to be available by default, but as of 7.2.2 they are gone, nor can I find related settings to re-enable them either. 

This is how it used to be prior to 7.2.2 (same screenshot from the wiki):
![dbeaver_before](https://user-images.githubusercontent.com/3392880/95046175-d259c580-070d-11eb-87ed-86b92d6f35ba.png)

And this is how it looks now:
![dbeaver_after](https://user-images.githubusercontent.com/3392880/95046192-e30a3b80-070d-11eb-941d-41c01caf19bb.png)

While I could read directly from the DDL, having those foreign keys/constraints tabs are much faster to verify my tables. Can anyone please help?

**Comment by uslss** [comment]
Hi @Duplicated ,
seems you've got Simple view enabled. You could change view to Advanced, e.g. in Connection properties.
![image](https://user-images.githubusercontent.com/31996417/95053514-358d2d00-06f9-11eb-9414-0fe47c933f00.png)

**Comment by Duplicated** [comment]
@uslss That was it. Thank you very much.

Follow-up: could it be that upgrading my dbeaver reset the global default configuration?

**Comment by uslss** [comment]
@Duplicated , no it shouldn't reset global configuration. What options do you mean?

**Comment by Duplicated** [comment]
This one:
![dbeaver_no_colorized](https://user-images.githubusercontent.com/3392880/95413387-78e3d780-0955-11eb-92f4-ed3a0512a15d.png)
Notice how the `Colorized Data Types` option is still selected, yet the result of the query is still unformatted (staff_id and logo_id should be purple for int data type, and timestamp should be green). Unset and set that option again does fixed the problem, although I have to do it every time I open up Dbeaver.

**Comment by uslss** [comment]
seems the issue with colorized data types is fixed for now. (7.3.0)
If it is still actual - please create a new issue.
BR
