### ISSUE TITLE
no database selected when running tasks. 

### ISSUE THREAD

**Issue by mrhargro** [dbeaver/dbeaver#9970]
i think have recently updating dbeaver i've had issues running some simple tasks. they are queries i run on a weekly basis and have not changed. I get an error "no database selected." 

anyone run into this and resolve it? 

Version 7.2.0.202008302047

**Comment by p91paul** [comment]
you should be able to select a database from the top bar, there's a connection selector

**Comment by mrhargro** [comment]
back to this...thanks for the reply. Still having this issue when creating tasks. Selecting the DB when in the normal editor interface is no issue, but when adding a query in the task creation workflow, i no longer am asked to select the database, I can just select my data source. 

there is no option after this step to select the database. I can then add the query and save the task successfully, but when running it i get the error that no database is selected. this happened when i upgraded to  7.2.0.202008302047 a while back. 

![image](https://user-images.githubusercontent.com/2421704/97239015-1138e380-17c1-11eb-80e8-20831f1a4f30.png)

![image](https://user-images.githubusercontent.com/2421704/97239092-3d546480-17c1-11eb-8769-4ca9e3ad823b.png)

![image](https://user-images.githubusercontent.com/2421704/97239171-6248d780-17c1-11eb-8791-b1b38d1db9a7.png)

**Comment by uslss** [comment]
Hi @mrhargro ,
sorry for the late response.
Can you check if issue is still reproducible for you against 7.3.0?
Cannot reproduce it for now.
Thanks in advance
