### ISSUE TITLE
Add option to "or ignore" unique constraints when importing csv/database into sqlite

### ISSUE THREAD

**Issue by mbelvadi2** [dbeaver/dbeaver#9973]
**Is your feature request related to a problem? Please describe.**
Problem: Importing a csv/tsv file into an existing table that has a unique index, and some of the incoming data may duplicate what's already there (or possibly even duplicates in the incoming file itself) - this gives two consecutive errors (see attached) and stops the entire import.  Ditto if the data is coming via import "database" target type to pull directly from another table.

**Describe the solution you'd like**
A checkbox option in the dialogue that sets up the import criteria that will essentially add "OR IGNORE" to the INSERT command or its equivalent on a row by row basis so offending rows are just skipped and the rest of the file processing continues.

**Describe alternatives you've considered**
Alternative solution is very tedious - what I've been doing for now is to download the existing/target table (plus the source one if using import 'database' rather than csv), and then use Unix sort, uniq and "grep -v -F -x -f file1 file2" on the old data and new data to produce a subset import file that I can be really sure won't violate the unique constraint.
But since sqlite very helpfully has already implemented that "or ignore" option, it would be nice to be able to take advantage of it when importing from tsv/database  just like I can do when executing an insert using select logic.

![Screenshot 2020-10-05 162547](https://user-images.githubusercontent.com/28821980/95123722-c3344100-0728-11eb-9f96-80e482242f55.jpg)
![Screenshot 2020-10-05 162527](https://user-images.githubusercontent.com/28821980/95123723-c3ccd780-0728-11eb-8303-20cca712b2d4.jpg)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by LonwoLonwo** [comment]
@mbelvadi2 Hello.
We have added this functionality in this ticket https://github.com/dbeaver/dbeaver/issues/10533

Available from [DBeaver 7.3.1 ](https://dbeaver.io/) in Data Transfer load settings/

![2020-12-21 10_52_26-Data Transfer](https://user-images.githubusercontent.com/45152336/102752910-5de10b00-437b-11eb-8949-7752bf8cc65c.png)
