### ISSUE TITLE
Error extracting table from Intersystems Cache dB.

### ISSUE THREAD

**Issue by JohnSerpico1967** [dbeaver/dbeaver#9975]
#### System information: 
- Operating system : WIN 2016 (64 Bit)
- DBeaver version: 7.2.0

#### Describe your question:

I did a SQL line count on a table that gave me 151,356 lines

SELECT COUNT (*) FROM tableA

When I exported the table, the process died out after a little over 60,000 lines with no error message.

I've notices that the last line, last column shows: DBCException: SQL Error: No data found 

Not sure how to bypass this line if its a bad piece of data. 
Editing the SQL command to state:

WHERE UDIX IS NOT NULL

doesn't work.
I'm looking to find out why the other lines are stuck in that table.

**Comment by uslss** [comment]
Could you provide error log?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
