### ISSUE TITLE
Apple cannot check for malicious software

### ISSUE THREAD

**Issue by mittalyashu** [dbeaver/dbeaver#9976]
I didn't face this issue in any of the previous versions.

<img width="532" alt="Screenshot 2020-10-06 at 10 36 25 AM" src="https://user-images.githubusercontent.com/29014463/95161073-ccbcb800-07bf-11eb-8822-000a3e2d6cea.png">

#### System information: 
- Operating system (distribution) and version: MacOS 10.15.7
- DBeaver version: 7.2.2

**Comment by mittalyashu** [comment]
Steps to reproduce the error _(not sure if that might work)_
* Install the pervious version
* Use homebrew to upgrade to newer version

@kseniiaguzeeva

**Comment by daniellockard** [comment]
I can't reproduce this either and I just updated my version from homebrew.

**Comment by daniellockard** [comment]
I did just have a coworker experience this. To work around it I had him option-right click-open on the app and hit "open". I'm unsure if it will continue to prompt after that, but we did see it.

**Comment by loban** [comment]
I can confirm that this is happening to me too. Reinstalling did not help. It was installed (and reinstalled using `brew`).

**Comment by michaelvaes** [comment]
Similar issue over here after installing w/ homebrew.
Re-installing did **not** help: `brew cask install --force dbeaver-community`

@daniellockard's solution with right-click and open worked; after that it keeps working for me.

**MacOS:** `10.15.7 (19H2) `
**DBeaver:** `Version 7.2.2.202010041557`

**Comment by akshah123** [comment]
I ran into the same problem but @daniellockard 's work around isn't working for me either.  I have tried reinstalling directly as well but still no luck.

**Comment by uslss** [comment]
could you try if the issue is reproducible against 7.2.3?
probably in 7.2.2 it was related to the hotfix of this version

**Comment by mittalyashu** [comment]
Seems like the issue got fixed @uslss

**Comment by abemedia** [comment]
Latest version doing the same... Right-click & open worked though...

**Comment by rahulkhanna2** [comment]
> Latest version doing the same... Right-click & open worked though...

This is strange but it seems to be working for now

**Comment by matias-laino-rev** [comment]
Just happened to me on latest version.
