### ISSUE TITLE
Issue on Theme Change

### ISSUE THREAD

**Issue by bhagatkhyati5** [dbeaver/dbeaver#9977]
![image](https://user-images.githubusercontent.com/72433097/95166997-799d3200-07cc-11eb-8a0f-564c33960c09.png)

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Please:
- tell your OS and DBeaver version
- send logs

**Comment by uslss** [comment]
Reproducible (Windows 10)
![image](https://user-images.githubusercontent.com/31996417/95176741-f5e04700-07c5-11eb-82e9-66b69907e600.png)

**Comment by bhagatkhyati5** [comment]
> I cannot reproduce it. Please:
> 
> * tell your OS and DBeaver version
> * send logs

DBeaver 7.2.2
and OS - Windows 10 Pro

**Comment by serge-rider** [comment]
This issue was resolved in the recent Eclipse platform

**Comment by kseniiaguzeeva** [comment]
verified
