### ISSUE TITLE
DynamoDB Filters with map objects

### ISSUE THREAD

**Issue by aakArnaud** [dbeaver/dbeaver#9979]
Hi, 
I connected an AWS dynamoDB and I try to filter map objects but I get an error message  "ExpressionAttributeNames contains invalid key: Syntax error; key: "#environment.item" (Service: DynamoDb, Status Code: 400, Request ID: TVDIN0SGF7JSFBR1HAA3006BI3VV4KQNSO5AEMVJF66Q9ASUAAJG)".

You can see on screenshot DBeaver 1 the filter and on screensho DBeaver 2 the error. 

May you help me solve this error ? 

Thanks
![DBeaver 1](https://user-images.githubusercontent.com/72438531/95178871-35a43000-07c0-11eb-9c11-336dcbf15864.JPG)
![DBeaver 2](https://user-images.githubusercontent.com/72438531/95178876-36d55d00-07c0-11eb-8684-1ad722aeeeb7.JPG)

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Fixed. 
Now you can use maps (aka nested attributes) in both table filters and SQL queries.
E.g.
```sql
SELECT *
FROM Movies WHERE info.rating>8;
```

**Comment by uslss** [comment]
verified
