### ISSUE TITLE
Data types colors are applied only after resultset reopening

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9981]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.2.2

#### Describe the problem you're observing:
Data types colors are applied only after resultset reopening
#### Steps to reproduce, if exist:
Precondition: Colorize Data Types option is enabled.
1. Change colors in `Window > Preferences > General > Appearance > Colors and Fonts > Database Query Results > Resultset Data Types `, set the colors and save changes
2. Open SQL Editor and execute a SQL Script, the resultset still come out in grayscale
3. Close Resultset and run query once again - data types color are shown accordingly to preferences
![2020-10-06_12h53_18](https://user-images.githubusercontent.com/31996417/95186738-faf7c300-07d2-11eb-8fca-ecaaa693fbaf.gif)

**Comment by akilovich** [comment]
Not reproducible anymore.
