### ISSUE TITLE
help me(I'm using the oracle 8i )

### ISSUE THREAD

**Issue by youngkwanghwang** [dbeaver/dbeaver#9982]
#### System information: 
- Operating system (distribution) and version : windows 10
- DBeaver version : 7.2.2.202010041557
- Additional extensions

#### Connection specification:
- Database name and version  : oracle 8i
- Driver name :  Oracle JDBC driver 10.1.0.2.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
Hello.
I am using oracle 8i.

It’s not that I’m choosing a table list
"ORA-00933: SQL command not properly ended"
Returns the error value.

SELECT /*+RULE*/ O.*,
t.TABLE_TYPE_OWNER,t.TABLE_TYPE,t.TABLESPACE_NAME,t.PARTITIONED,t.IOT_TYPE,t.IOT_NAME,t.TEMPORARY,t.SECONDARY,t.NESTED,t.NUM_ROWS
FROM ALL_OBJECTS O
LEFT OUTER JOIN ALL_ALL_TABLES t ON (t.OWNER = O.OWNER AND t.TABLE_NAME = o.OBJECT_NAME)
WHERE O.OWNER='EMR' AND O.OBJECT_TYPE IN ('TABLE','VIEW','MATERIALIZED VIEW')a
                                                                                                                                   
Seeing that this query statement doesn't work, I wonder if 8i doesn't support left join.

Please help!

#### Steps to reproduce, if exist:

![20201006_201743](https://user-images.githubusercontent.com/46339747/95195166-200b2680-0811-11eb-9972-b6980b9465f5.png)

**Comment by uslss** [comment]
thanks for the bug report
closed as duplicate #9904
