### ISSUE TITLE
UUID Insert Error

### ISSUE THREAD

**Issue by onurtekir** [dbeaver/dbeaver#9984]
Hi, 

Today, I upgraded 7.2.1 version to 7.2.2. After upgrade, I started not to insert UUID fields by copy/paste online generated UUID values. After downgrade to 7.2.1, problem solved. I didn't make any changes on table or database structure. I think you should check UUID insertion. You can see the error that I faced when inserting UUID included record.

![Error](https://user-images.githubusercontent.com/10272800/95196967-84ae8d00-07e1-11eb-9e3e-a9695d9caa3a.jpg)

**Comment by piaste** [comment]
The bug also appears if you edit any field in a table where the primary key is a UUID.

**Comment by onurtekir** [comment]
> The bug also appears if you edit any field in a table where the primary key is a UUID. You get that same error message when you hit 'Save' or 'Script'.
> 
> EDIT: I've found that what I wrote has its own issue in #9964. Most likely the same bug in the ValueHandler resolution chain.

**Comment by onurtekir** [comment]
> The bug also appears if you edit any field in a table where the primary key is a UUID. You get that same error message when you hit 'Save' or 'Script'.
> 
> EDIT: I've found that what I wrote has its own issue in #9964. Most likely the same bug in the ValueHandler resolution chain.

UUID is not primary key in my table. I can insert to same table with same records without changing UUID with version 7.2.1.
