### ISSUE TITLE
JSON view: dividing lines between JSON items change length

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9986]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.2.2

#### Steps to reproduce, if exist:
1. Open a table in JSON view (e.g. Dynamo Movies)
2. Scroll to the right.

Expected: dividing lines are of fixed length
Actual result: dividing lines change length
![0qP3w0Q0Si](https://user-images.githubusercontent.com/51405061/95207438-8c296280-07f0-11eb-9882-3e826bb0a8ec.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
It is impossible to scroll through JSON view after expanding the window from compact, where the view was scrolled to the right by horizontal scroll 
Steps:
1. open JSON view (e.g. mongo test.restaurants)
2. reduce the application window so that a horizontal scroll appears and scroll to the right
3. maximize the view back to full screen mode.

Expected: all data is visible
Actual result: only part of the data is visible, as it was when scrolling to the right in a reduced window view

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Closed. New ticket is created https://github.com/dbeaver/pro/issues/535
