### ISSUE TITLE
Can't initialize tunnel - process hasn't exited

### ISSUE THREAD

**Issue by mrhargro** [dbeaver/dbeaver#9989]
Doing and SSH connection and had to generate a new public key. Updated everything, but i'm getting the following error when testing connection. Has anyone run into this?

**Comment by cytsunny** [comment]
Just ran into the same problem today, and I guess it is because dBeaver ssh client can only use a certain kind of key.
If your key is generated by `ssh-keygen`, adding `-m PEM` should solves the problem.

For example,
`ssh-keygen -t rsa -b 2048 -m PEM -f my-ssh-key`
should generate a set of key that solves the problem.

**Comment by mrhargro** [comment]
thanks! i recall doing that now on an older project. i was able to resolve my issue by going to Help > Install new software > SSHJ. Updated the implementation on the SSH tab of your connection setup. 

![image](https://user-images.githubusercontent.com/2421704/95586704-0a635000-0a0f-11eb-8d6f-a48842df3524.png)

![image](https://user-images.githubusercontent.com/2421704/95586760-1fd87a00-0a0f-11eb-94d5-6b496d800a0b.png)

**Comment by uslss** [comment]
Could you check if the issue is solved against 7.2.3 version?

**Comment by comprexz** [comment]
The issue still persists in 7.2.3.

**Comment by mrhargro** [comment]
Yes it it does. I had to reinstall the SSHJ extension after upgrading.

**Comment by comprexz** [comment]
OK with SSHJ it works.

**Comment by ronjouch** [comment]
I have the same issue with JSch, and I'd like to follow the advice to switch to SSHJ, but I'm unable to install it. When I try to install it (from `Install New Software` → `DBeaver SSHJ extension - https://dbeaver.io/update/sshj/latest/` → `Next`), the installation fails with:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver SSHJ 1.0.76.202104181339 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.76.202104181339)
  Missing requirement: SSHv2 library for Java 0.27.3 (org.jkiss.bundle.sshj 0.27.3) requires 'osgi.bundle; org.bouncycastle.bcpkix 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver SSH implementation (SSHJ) 1.0.76.202104181339 (org.jkiss.dbeaver.net.ssh.sshj 1.0.76.202104181339)
    To: osgi.bundle; org.jkiss.bundle.sshj 0.0.0
  Cannot satisfy dependency:
    From: DBeaver SSHJ 1.0.76.202104181339 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.76.202104181339)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.net.ssh.sshj [1.0.76.202104181339,1.0.76.202104181339]
```

Am I missing something?

I'm running the latest DBeaver 21.0.3.202104181339, installed from the official deb package and running on Ubuntu 20.10.

**Comment by p91paul** [comment]
I suggest you open a new bug, commenting on closed issues might get overlooked.

**Comment by ronjouch** [comment]
> I suggest you open a new bug, commenting on closed issues might get overlooked.

True, here we go: https://github.com/dbeaver/dbeaver/issues/12218
