### ISSUE TITLE
7.3 Upgrade

### ISSUE THREAD

**Issue by black0828** [dbeaver/dbeaver#9990]
#### System information: 
- Operating system (distribution) and version - Mac OS 10.15.7 (Catalina)
- DBeaver version - Version 7.2.0.202009071746
- Java version - Version 8 Update 261
- Additional extensions

#### Connection specification:
- Database name and version - n/a
- Driver name - n/a
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - n/a

#### Describe the problem you're observing:

When I launch DBeaverEE, I am presented with the option of upgrading to version 7.3. I click on the button and it takes me to a site that automatically starts downloading the program. Unfortunately, the version that gets downloaded is 7.2. I've tried finding 7.3 manually, but with no luck.

**Comment by uslss** [comment]
Hi @black0828 ,
issue is fixed for now. 7.3.0 will be available on December 7 only.
Sorry for the inconvenience caused.
