### ISSUE TITLE
Cannot delete element from _varchar with value editor

### ISSUE THREAD

**Issue by diegmonti** [dbeaver/dbeaver#9991]
#### System information: 
- Operating system (distribution) and version: Ubuntu 20.04
- DBeaver version: 7.2.2
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgreSQL 12
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
I cannot delete an element from a _varchar array using the value editor.

#### Steps to reproduce, if exist:
1. Create a test table: ```CREATE TABLE domains (id_domain serial NOT NULL, urls _varchar NULL);```
2. Insert a row: ```INSERT INTO domains VALUES (1, '{"http://www.google.com","https://www.google.com"}');```
3. Using the value editor, try to remove an element from the array.
![edit_urls](https://user-images.githubusercontent.com/6765143/95237666-cb63ad80-0808-11eb-868f-5c4fe344c031.png)
4. When you save it, you will get the following error.
![edit_error](https://user-images.githubusercontent.com/6765143/95237670-cdc60780-0808-11eb-9121-cec88d96147c.png)

#### Include any warning/errors/backtraces from the logs
```
Error creating struct
  Unable to find server array type for provided name _varchar.
```

**Comment by uslss** [comment]
thanks for the bug report

**Comment by SephShom** [comment]
I have a similar problem but not exacly the same. I would like to know if i must to open new issue for that. I Cannot edit any record from editor, the answer is:
Error synchronizing data with database

Reason:
Object parameter [79c0b4c2-5ca0-4e2c-b6cb-db87a9467d8e] binding not supported

**Comment by nacknime-official** [comment]
I have the same bug. After creating a row, I can't add, edit values or delete them. It says:
_Error creating struct
  Unable to find server array type for provided name _varchar._

**Comment by uslss** [comment]
not reproducible in 7.2.3

**Comment by SephShom** [comment]
i am sorry but, why this is closed?
Postgresql
dbeaver Version 7.2.3.202010181902

Button Save reproduces this error:

![errorDB](https://user-images.githubusercontent.com/22324660/97095980-f5540700-1633-11eb-8287-2e525409a937.png)

Thank you

**Comment by p91paul** [comment]
@SephShom your error message looks very different from the one of this issue. #10048 should be your bug.

**Comment by SephShom** [comment]
ok thank you. That s why in my first message i asked if i'd need to open a
new issue. I will, thank you.
