### ISSUE TITLE
Time Format for Insert Query Using SQL Generator

### ISSUE THREAD

**Issue by sovittyagi** [dbeaver/dbeaver#9992]
Win -10 
Dbeaver 7.2.2

Hi All , I have installed version 7.2.2 but not able to find option to have time format in INSERT query generated by Generate SQL feature in desired format 05-OCT-2020. Can you please help me out with steps how i can get this timestamp in INSERT query.

Thanks
Sovit

**Comment by sovittyagi** [comment]
@uslss  @serge-rider @kseniiaguzeeva @tati-kru  - Please help me out here with steps.

**Comment by uslss** [comment]
@sovittyagi something going wrong during the implementation, so #9293 is reopened, to resolve the mentioned issue.
