### ISSUE TITLE
DBeaver FR: Add set focus to the SHOW/HIDE RESULTS PANEL function

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#9994]
DBeaver - **Version 7.2.2 CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver** _(the new Microsoft Driver)_
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

It would be benificial if the command **Show/hide results panel (Metadata)** also set focus to the **Panel Metadata**. This in the same manner as function **Toggle result panels** does.

Today if I call up the metadata panel using a keyboard shortcut, I have to click on the metadata panel first using the mouse before I can search/select a column to show. This seems ineffective.

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
Done

**Comment by uslss** [comment]
verified
