### ISSUE TITLE
Problems that occur when saving sql statements as Korean file names

### ISSUE THREAD

**Issue by pro9dan** [dbeaver/dbeaver#9995]
I renamed my sql file name from script-5.sql to 사용자쿼리.sql in dbeaver.
And I opened 사용자쿼리.sql file in dbeaver
Then, the following error message appeared.

"can't open editor connection"

I think the Korean file name seems to be the problem.
Is there any good solution?

Dbeaver version : 7.2.2
DB : Oracle
![이미지 3](https://user-images.githubusercontent.com/5861473/95296606-053dbe00-08b4-11eb-8826-c0d586332e43.png)

**Comment by pro9dan** [comment]
When I changed the file name from 사용자쿼리.sql to aaa.sql, it works fine.

**Comment by uslss** [comment]
Hi @pro9dan ,
unfortunately, cannot reproduce an issue. Do you rename sql file using dbeaver?

**Comment by pro9dan** [comment]
Yes, I renamed sql file using dbeaver.

![이미지 4](https://user-images.githubusercontent.com/5861473/95302342-cbbd8080-08bc-11eb-820a-95424c6edab6.png)

**Comment by uslss** [comment]
still cannot reproduce it.
Can you try if the issue is still reproducible for you against the recent version (7.2.5.)?
Thanks in advance

**Comment by uslss** [comment]
there is no update on the issue for a long time.
if it is still actual for you - feel free to reopen it
