### ISSUE TITLE
Incorrect list of columns for table containing underscore

### ISSUE THREAD

**Issue by alumni** [dbeaver/dbeaver#9998]
#### System information: 
- Operating system (distribution) and version: _both Windows and Linux_
- DBeaver version: _7.2.2 (issue present in previous versions too)_ 
- Additional extensions: _none_

#### Connection specification:
- Database name and version: _SAP HANA (both 2.0 and HANA Cloud)_
- Driver name: _maven:/com.sap.cloud.db.jdbc:ngdbc, versions 2.4, 2.5, 2.6_
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  _no_

#### Describe the problem you're observing:
A table with the name containing an underscore will display an incorrect list of columns, if there is another table with a letter instead of the underscore in the name.

#### Steps to reproduce, if exist:
1. Create two tables, `ABC` and `A_C`.
2. Double click on `A_C`, go to Properties, then Columns. You will see the columns from both tables, first the ones from `ABC` and then the ones from `A_C`.

The reason most likely is that underscore matches any letter in the SQL `LIKE` predicate: 
https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.05/en-US/20fa17f375191014a4d8d8cbfddfe340.html

If this is the case, other databases might also be affected, as this is not HANA-specific - it is also specified in the ANSI SQL standard. In general, a check for equality should be done using the `=` operator instead, while `LIKE` should be used for pattern matching only.

**Comment by geomorillo** [comment]
i think this applies to other databases at least i can confirm this on sqlite, it makes the table unable to drop it

**Comment by kai-morich** [comment]
could reproduce issue with Sqlite, so does not look HANA specific.

**Comment by ShadelessFox** [comment]
This is caused because the driver does not return any information about escapes for pattern strings.

We should fix this manually for generic dialects.

**Comment by wernerdaehn** [comment]
The driver does not return anything because it is user-defined.

https://help.sap.com/viewer/7c78579ce9b14a669c1f3295b0d8ca16/Cloud/en-US/20fa17f375191014a4d8d8cbfddfe340.html

```
SELECT * FROM schemas WHERE schema_name in ('_SYS_BI', '_SYS_RT', '_SYS_XS');

SELECT * FROM schemas WHERE schema_name like '_SYS___';

SELECT * FROM schemas WHERE schema_name like '\_SYS\___' ESCAPE '\';
```

**Comment by ShadelessFox** [comment]
We're retrieving information about columns using JDBC API [DatabaseMetaData#getColumns](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getColumns-java.lang.String-java.lang.String-java.lang.String-java.lang.String-) that accepts table name pattern. The escape sequence for this pattern should be retrieved using [DatabaseMetaData#getSearchStringEscape](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getSearchStringEscape--) but the driver decided to not return it, so we can't escape it manually because we can break something for other databases.

**Comment by wernerdaehn** [comment]
I see. Thanks for the correction.

**Comment by wernerdaehn** [comment]
@kai-morich Do you mind to create a SAP internal support incident for that?

**Comment by kai-morich** [comment]
looks like this missing property could be _fixed_ in HANASqlDialect class

**Comment by ShadelessFox** [comment]
> looks like this missing property could be _fixed_ in HANASqlDialect class

We still don't know what escape sequence the driver uses.

**Comment by kai-morich** [comment]
the internal statement for `DatabaseMetaData#getColumns` contains

      WHERE 
         ( ($2) IS NULL  OR ($2) = '' OR C.SCHEMA_NAME LIKE ($2) ESCAPE '\')
         AND C.TABLE_NAME LIKE ($3) ESCAPE '\'
         AND C.COLUMN_NAME LIKE ($4) ESCAPE '\'
        
so \ is the escape character

**Comment by alumni** [comment]
That means the `DatabaseMetaData#getSearchStringEscape` should be updated to return `'\'`, right?

@kai-morich DBeaver could treat HANA as a special case, but others that use the HANA JDBC driver will have the same problem.

I tried it in DataGrip before opening this ticket, but it seems they don't use the methods from the driver, they build their own statements (and they have other issues because of that 😆). However, if you check SQL Workbench/J, you'll find this issue there as well.

IMO, we should create an internal incident for the driver, it should be fixed there if possible.

**Comment by kai-morich** [comment]
Of course would be better if the JDBC driver would provide this option but this will take some time.
Many JDBC drivers are incomplete so dbeaver has various places to compensate for missing properties like [SQLDialect](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.hana/src/org/jkiss/dbeaver/ext/hana/model/HANASQLDialect.java#L76) classes and driver [plugin.xml](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.hana/plugin.xml#L121)

**Comment by ShadelessFox** [comment]
Fixed for HANA. Unfortunately, in case of SQLite we can't do anything about it.

**Comment by uslss** [comment]
verified
