### ISSUE TITLE
Unable to load authentication plugin 'caching_sha2_password'

### ISSUE THREAD

**Issue by rezetta** [dbeaver/dbeaver#9999]
#### System information: 
- MS Windows 10, 10.0.19041 Build 19041
- DBeaver 7.2.2.202010041557

#### Connection specification:
- YeahRight Mysql 8.0.21-0ubuntu0.20.04.4

#### Describe your question:
Unable to load authentication plugin 'caching_sha2_password'

**Comment by uslss** [comment]
Hi @rezetta ,
could you provide steps to reproduce?

**Comment by da-anda** [comment]
I have the same issue. How did you resolve it @rezetta ?
